### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by rereborn** [2dust/v2rayNG#1]
昨天装上APP，用的还不错，晚上时发现浏览器无论打开国内还是国外，都特别慢或者打不开，用百度IP搜了下，分流功能正常。但不知道为什么会这么慢，重启应用无效，后来重启手机后正常。
今天好像又有新的更新，目前为止没有发现昨天类似的情况，但好几次看到有提示：v2ray restart.

**Comment by gloomy-ghost** [comment]
上游库问题，在应用层只能临时做好错误处理等上游修复。

**Comment by 2dust** [comment]
v2ray restart 这个提示是0.2.4加入的，根据android网络广播来调用lib的中断重连。
也许会解决部分问题，在反馈和测试后的后续版本会移除此提示消息
