### ISSUE TITLE
绕过中国大陆地址失败，只能全局

### ISSUE THREAD

**Issue by nobodysclown** [2dust/v2rayNG#1]
建议添加GFWlist。

**Comment by FirstJavaMaster** [comment]
我这里测试, 路由模式选择"绕过局域网及大陆地址"时,网络出口ip确实是国内,不过相比较于直连(关掉该软件)速度确实慢了一些

**Comment by nobodysclown** [comment]
> 我这里测试, 路由模式选择"绕过局域网及大陆地址"时,网络出口ip确实是国内,不过相比较于直连(关掉该软件)速度确实慢了一些

我之前是和你的情况一样，隔了一天就成了全局了。现在用的BifrostV，他的规则设置里可以添加GFWlist，我觉的这一点比较好。除了客户端卡顿，网络是挺正常。

**Comment by caoli5288** [comment]
+1，很多应用速度都变慢了，希望能解决这个问题

**Comment by Ryan-fai** [comment]
同样遇到该问题，希望尽快修复

**Comment by HochGit** [comment]
ls各位，我试了下设置“分应用代理”，基本上可以解决绕行问题。

**Comment by nobodysclown** [comment]
> ls各位，我试了下设置“分应用代理”，基本上可以解决绕行问题。

嗯嗯，是可以了，但是浏览器用分应用代理就不太合适。。

**Comment by FirstJavaMaster** [comment]
> > ls各位，我试了下设置“分应用代理”，基本上可以解决绕行问题。
> 
> 嗯嗯，是可以了，但是浏览器用分应用代理就不太合适。。

所以我的做法是用的时候开代理,不用的时候关掉

**Comment by free4537** [comment]
设置一个本地 DNS 就好了。

**Comment by colorfulshark** [comment]
> 设置一个本地 DNS 就好了。

果然解决了,看来默认所有DNS都会走代理

**Comment by oO0oO0oO0o0o00** [comment]
当然，dns后才能判断是否大陆ip……

不然就只能域名列表了，那会全吗

**Comment by 2dust** [comment]
1.分应用代理
2.try 本地 DNS

**Comment by yelosheng** [comment]
> 设置一个本地 DNS 就好了。

请问怎样设置本地DNS呢？
