### ISSUE TITLE
安卓机报错

### ISSUE THREAD

**Issue by brossli** [2dust/v2rayNG#10]
unexpected end of stream on com.android ok http .adress @7b4c55ec

**Comment by brossli** [comment]
安卓手机版本9，并且在过一段时间后会自动恢复

**Comment by SoulMateK** [comment]
我也遇到了类似的问题，无法连接，但是显示流量在飞跑，不知道哪里的问题

**Comment by SoulMateK** [comment]
安卓9

**Comment by 2dust** [comment]
sorry
No real machine can test

**Comment by JC-S** [comment]
我也碰到了同样的问题。开启飞行模式，稍等几秒，再解除飞行模式可以暂时解决问题。经常在使用LTE网络并且切换基站的时候碰到。
