### ISSUE TITLE
无限报错：Fail to connect to jdwp control socket

### ISSUE THREAD

**Issue by haomuch** [2dust/v2rayNG#1002]
小米9se，MIUI 12.5，无论连通还是断开状态，日志都会无限报告以下信息：
![IMG_20210411_135404_231](https://user-images.githubusercontent.com/3903046/114294025-bfb1b600-9acd-11eb-90fa-0c9a9f5e08f9.jpg)

这个问题可能会导致手机耗电增加，敬请关注

**Comment by haomuch** [comment]
网上搜索了一下，说是打开开发者选项的USB调试，就能解决这个报错，请开发者看看能否修改一下，不再让ng试图连接这个socket

**Comment by rurirei** [comment]
need more.

**Comment by ChinaParrot** [comment]
不太好用了
