### ISSUE TITLE
couldn't connect vpn mod in my own build

### ISSUE THREAD

**Issue by eroxs** [2dust/v2rayNG#1003]
I created an aar file using AndroidLibV2rayLite and used it to update the v2ray kernel
I build a apk; with Android Studio
The core is 4.37.2
But the problem I have is when I add the configuration and I want to connect. VPN mode is not enabled
The VPN key is not shown above and only the v2ray application connection is displayed in the notification.
---
我使用AndroidLibV2rayLite创建了一个AAR文件，并用它来更新v2ray内核
我建立了一个APK； 使用Android Studio
核心是4.37.2
但是我遇到的问题是当我添加配置并想要连接时。 未启用VPN模式
上面没有显示VPN密钥，通知中仅显示v2ray应用程序连接。

log : 
--------- beginning of main
04-11 22:14:02.947 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:02.948 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:02.949 I/GoLog   ( 4281): 127.0.0.1:49582 accepted //www.google.com:443 [proxy]
04-11 22:14:03.151 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:03.554 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:04.162 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:04.964 I/GoLog   ( 4281): [Warning] [3253825035] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [fail to protect] > common/retry: all retry attempts failed
04-11 22:14:04.970 D/com.v2ray.ang( 5975): testConnection IOException: javax.net.ssl.SSLHandshakeException: Connection closed by peer
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.v2ray.ang.util.Utils.testConnection(Utils.kt:342)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at com.v2ray.ang.viewmodel.MainViewModel$testCurrentServerRealPing$1.invokeSuspend(MainViewModel.kt:102)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-11 22:14:04.970 D/com.v2ray.ang( 5975):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
--------- beginning of system
04-11 22:14:22.460 I/GoLog   ( 4281): 127.0.0.1:49608 accepted //www.google.com:443 [proxy]
04-11 22:14:22.460 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:22.462 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:22.666 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:23.070 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70
04-11 22:14:23.674 I/GoLog   ( 4281): fdConn fail to protect, Close Fd: 70

**Comment by eroxs** [comment]
@yuhan6665 i need your help :(
i can pay for your help 
need source code with xray core 1.4.2 and i can pay fee 
i use AndroidLibxrayLite but have problem in connection .

**Comment by yuhan6665** [comment]
`04-11 22:14:02.947 I/GoLog ( 4281): fdConn fail to protect, Close Fd: 70`
you need to check why VPN service is not started successfully. Is old version 4.31.2 working?

Need some code change in https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite to support Xray. I can do that next week.

**Comment by eroxs** [comment]
@yuhan6665  Yes sir I build 4.31.2 and it worked fine ( open source ) 
But when I built AndroidLibV2rayLite aar and replaced it with v2rayng, then I had a connection problem (4.37.2)
I also build AndroidLibXrayLite and the problem was not resolved (1.4.2)
but release in google play , worked well

what should i do ?

**Comment by yuhan6665** [comment]
Let me update  https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite and then see if that works for you

**Comment by eroxs** [comment]
Is it possible to add x ray 1.4.2? I need uTLS capability.

**Comment by lavelleo** [comment]
why don't you migrate the entire V2rayNG project from android support library to androidx?

**Comment by yuhan6665** [comment]
@eroxs 
https://github.com/2dust/v2rayNG/pull/1015
