### ISSUE TITLE
请问新版安卓v2rayng里的仅代理和vpn模式的区别

### ISSUE THREAD

**Issue by wsickid** [2dust/v2rayNG#1006]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/wiki/Mode

**Comment by whqijy** [comment]
白话文解释一下（可能不对请指正）：
仅代理模式：指的是仅在你的手机搭建一个本地端代理服务，其他应用可以通过内置的代理设置来调用代理服务。
某些应用自带代理设置，这时候就可以打开代理设置把代理指向本地服务，从而调用V2NG的代理科学上网，例如TG。
但大部分的软件是没有代理设置的，所以此模式并不适用正常国内富强。

VPN模式：创建一个虚拟网络接管你手机的流量，从而实现系统级的全局代理。
正常使用的话，应该是使用此模式。可以让你所有的应用流量通过V2NG代理。

**Comment by guanjian1212** [comment]
那如果是vpn模式的同时，预定义规则选择了绕过局域网及大陆地址而后代理，这时是全局模式吗？

**Comment by SyberRabbit** [comment]
> 那如果是vpn模式的同时，预定义规则选择了绕过局域网及大陆地址而后代理，这时是全局模式吗？

你百度搜ip，看一下ip就知道了，
