### ISSUE TITLE
v2rayNG在ws+tls下的性能存在疑问

### ISSUE THREAD

**Issue by kingsznhone** [2dust/v2rayNG#1007]
### 预期行为
谷歌商店的应用下载速度应该达到1M/s

### 实际行为

V2rayNG在WS+TLS下的性能好像有点问题，使用同一个配置，BifrostV的速度能到1M/S左右，但是NG最高只能到70k/s左右
使用PC测试网络，从电脑端开启MUX满载的速度在300k/s附近，关闭MUX的速度最高是2M/s
谷歌市场下载app的时候是多线程下载，但是不管是在小米11pro上还是备用的galaxy S8上，NG的速度表现很像开启了MUX

### 环境信息
自建小鸡，i7+1070笔记本，小米11pro，三星galaxy S8，电信百兆光纤，华硕AX86U路由器

**Comment by Herts** [comment]
设置-参数设置：Mux默认开启。
