### ISSUE TITLE
cannot load jdwp agent

### ISSUE THREAD

**Issue by shallowdream233** [2dust/v2rayNG#1010]
预期行为
日志捕获开启info，启动连接可以看到日志

实际行为
logcat显示无法加载jdwp进程

### 复现方法
设置日志等级改成info，启动连接，打开logcat

### 日志信息
--------- beginning of main
E/com.v2ray.ang(15953): Not starting debugger since process cannot load the jdwp agent.

### 额外信息（可选）
连接测试时显示io read/write on close pipe，但实际节点可用，不确定是否为该原因导致

**Comment by rurirei** [comment]
all of logs please?

**Comment by shallowdream233** [comment]
--------- beginning of main
04-13 21:58:35.241 E/com.v2ray.ang(28084): Not starting debugger since process cannot load the jdwp agent.
it's all

**Comment by xiangaoole** [comment]
我在新手机上第一次用的时候也遇到过这个问题，后来发现是手机的时间设置有问题。手机时间和服务器主机时间不能相差超过3分钟。你可以先排查下是不是这个原因。

**Comment by shallowdream233** [comment]
> 我在新手机上第一次用的时候也遇到过这个问题，后来发现是手机的时间设置有问题。手机时间和服务器主机时间不能相差超过3分钟。你可以先排查下是不是这个原因。

谢谢你的建议，但是我的手机时间与time.is没有区别，至少在分钟上是这样，所以应该不是这个问题。

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/issues/1002#issuecomment-817256163
