### ISSUE TITLE
服务启动失败

### ISSUE THREAD

**Issue by Mohisters** [2dust/v2rayNG#1017]
服务器端无问题，在V2rayN及SSRP+上均能正常使用代理

### 预期行为
点击连接按钮后应正常连接至服务器

### 实际行为
弹出“服务启动失败”气泡，连接失败

### 日志信息
--------- beginning of system
--------- beginning of crash
04-17 10:09:30.248 E/AndroidRuntime( 9011): FATAL EXCEPTION: main
04-17 10:09:30.248 E/AndroidRuntime( 9011): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 9011
04-17 10:09:30.248 E/AndroidRuntime( 9011): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5092665 u0 com.v2ray.ang/.service.V2RayVpnService}
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at android.os.Looper.loop(Looper.java:233)
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at java.lang.reflect.Method.invoke(Native Method)
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
04-17 10:09:30.248 E/AndroidRuntime( 9011): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
04-17 12:50:27.929 E/AndroidRuntime(32630): FATAL EXCEPTION: main
04-17 12:50:27.929 E/AndroidRuntime(32630): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 32630
04-17 12:50:27.929 E/AndroidRuntime(32630): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ec55d2 u0 com.v2ray.ang/.service.V2RayVpnService}
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at android.os.Looper.loop(Looper.java:233)
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at java.lang.reflect.Method.invoke(Native Method)
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
04-17 12:50:27.929 E/AndroidRuntime(32630): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
04-17 12:51:09.213 E/AndroidRuntime(10752): FATAL EXCEPTION: main
04-17 12:51:09.213 E/AndroidRuntime(10752): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 10752
04-17 12:51:09.213 E/AndroidRuntime(10752): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{efe6b81 u0 com.v2ray.ang/.service.V2RayVpnService}
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at android.os.Looper.loop(Looper.java:233)
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at java.lang.reflect.Method.invoke(Native Method)
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
04-17 12:51:09.213 E/AndroidRuntime(10752): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
--------- beginning of main
04-17 19:25:49.822 E/com.v2ray.ang(31162): Not starting debugger since process cannot load the jdwp agent.
04-17 19:25:57.898 I/com.v2ray.ang(31162): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
04-17 19:29:13.881 I/com.v2ray.ang(31162): The ClassLoaderContext is a special shared library.
04-17 19:29:13.890 I/com.v2ray.ang(31162): The ClassLoaderContext is a special shared library.
04-17 19:29:18.278 I/GoLog   (31043): loading core config
04-17 19:29:18.278 I/GoLog   (31043): Preparing Domain: {domain}:{port}
04-17 19:29:18.424 I/GoLog   (31043): infra/conf/serial: failed to parse json config > encoding/hex: invalid byte: U+0000
04-17 19:29:18.425 D/com.v2ray.ang(31043): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > encoding/hex: invalid byte: U+0000
04-17 19:29:18.839 I/GoLog   (31043): Prepare Result:
04-17 19:29:18.839 I/GoLog   (31043): Domain: {domain}
04-17 19:29:18.839 I/GoLog   (31043): Port: {port}
04-17 19:29:18.839 I/GoLog   (31043): IPs: [{IPV4} {IPV6}]

### 环境信息
小米11Ultra Android 11 MIUI12.5 全部开发版均存在该问题

**Comment by wuyoupeng611** [comment]
怎么弄好呢，，

**Comment by Mohisters** [comment]
> 怎么弄好呢，，
我也想知道怎么弄好

**Comment by Mohisters** [comment]
> 怎么弄好呢，，

我也想知道怎么弄

**Comment by yuhan6665** [comment]
failed to parse json config > encoding/hex: invalid byte: U+0000

**Comment by a501839212** [comment]
> 无法解析json配置>编码/十六进制：无效字节：U + 0000

怎么解决呢？

**Comment by Mohisters** [comment]
> failed to parse json config > encoding/hex: invalid byte: U+0000

我通过在v2rayN上填写节点信息，并使用二维码分享扫描解决了，但是这并不能说明v2rayNG本身没有问题，同样的节点信息在v2rayNG里新建节点直接填写及无法启动服务，但是在v2rayN里新建节点直接填写并通过二维码分享至v2rayNG就可以正常使用。
