### ISSUE TITLE
服务端已指定好部分网站走ipv6，shadowrocket和v2rayN完美，但是安卓端任然走ipv4

### ISSUE THREAD

**Issue by Choutouketsu** [2dust/v2rayNG#1018]
当初年少无知，年付了一台cc机房服务器扶墙学习，碰到谷歌搜索验证机器人问题，最起码还要用大半年，所以已经按照教程从HE申请绑定了ipv6通道，服务器config.json指定了谷歌和学术走ipv6访问，目前电脑端v2rayN和iPhone端shadowrocket可以正常默认走ipv6，但安卓端无论是免费的v2rayng还是已付费的v2fly客户端依旧是走ipv4，依旧碰到验证码问题并且无法访问学术，这是bug吗？如果需要日志，请告之。。。感谢大佬

### 预期行为
描述你认为应该发生什么

服务端config设置好路由，安卓端应该也同样按照路由正常走ipv6访问谷歌和学术

### 实际行为
描述实际发生了什么

安卓端无论是免费的v2rayng还是已付费的v2fly客户端依旧是走ipv4，依旧碰到验证码问题并且无法访问学术

**Comment by Choutouketsu** [comment]
只有我这个情况吗？😅

**Comment by azureaz** [comment]
![Screenshot_20210421-002108__01](https://user-images.githubusercontent.com/36233817/115431179-99131e00-a237-11eb-96b5-1d8e6ce3068f.jpg)
我的也是，通过ip addr命令发现没有对外的ipv6地址

**Comment by azureaz** [comment]
ipv4不影响，我也没太在意，直到今天有人也有这个问题我也吐槽下

**Comment by yuhan6665** [comment]
有可能是 sniffing 问题，你关了重新开一下再试

**Comment by Choutouketsu** [comment]
> 有可能是 sniffing 问题，你关了重新开一下再试

感谢，但刚刚试了v2rayng关闭流量嗅探，还是一样，难道服务端也要设置？

**Comment by yuhan6665** [comment]
> > 有可能是 sniffing 问题，你关了重新开一下再试
> 
> 感谢，但刚刚试了v2rayng关闭流量嗅探，还是一样，难道服务端也要设置？

没说清楚，试一下
关流量嗅探 -> 开流量嗅探 -> 连接节点
服务端不用

**Comment by azureaz** [comment]
![Screenshot_20210424-161233](https://user-images.githubusercontent.com/36233817/115952351-fa790c80-a517-11eb-87c0-d30943c5e43e.jpg)
![Uploading Screenshot_20210424-161413.jpg…]()

我的不是嗅探的问题，把ipv6优先打开，就能用ipv6地址了

**Comment by Choutouketsu** [comment]
> 我的不是嗅探的问题，把ipv6优先打开，就能用ipv6地址了

该方法可以解决搜索验证的问题，但是谷歌学术可以访问，不可以搜索，你可以试试，v2rayN和小火箭没问题

**Comment by haohaoget** [comment]
> > 我的不是嗅探的问题，把ipv6优先打开，就能用ipv6地址了
> 
> 该方法可以解决搜索验证的问题，但是谷歌学术可以访问，不可以搜索，你可以试试，v2rayN和小火箭没问题

确实我也一直是这个问题，后面发现Android端需要开启ipv6优先，解决google学术的方法是给服务端添加host
2404:6800:4008:c06::be scholar.google.com
2404:6800:4008:c06::be scholar.google.com.hk
2404:6800:4008:c06::be scholar.google.com.tw
2401:3800:4001:10::101f scholar.google.cn #www.google.cn
2404:6800:4008:c06::be scholar.google.com.sg
2404:6800:4008:c06::be scholar.l.google.com
2404:6800:4008:803::2001 scholar.googleusercontent.com
原因应该是服务端dns服务器的问题通过ping google youtube等能解析出ipv6地址但是ping scholar.google.com会发现解析到了一个ipv4地址上。
故修改host即可解决

**Comment by Choutouketsu** [comment]
> > > 我的不是嗅探的问题，把ipv6优先打开，就能用ipv6地址了
> > 
> > 
> > 该方法可以解决搜索验证的问题，但是谷歌学术可以访问，不可以搜索，你可以试试，v2rayN和小火箭没问题
> 
> 确实我也一直是这个问题，后面发现Android端需要开启ipv6优先，解决google学术的方法是给服务端添加host
> 2404:6800:4008:c06::be scholar.google.com
> 2404:6800:4008:c06::be scholar.google.com.hk
> 2404:6800:4008:c06::be scholar.google.com.tw
> 2401:3800:4001:10::101f scholar.google.cn #www.google.cn
> 2404:6800:4008:c06::be scholar.google.com.sg
> 2404:6800:4008:c06::be scholar.l.google.com
> 2404:6800:4008:803::2001 scholar.googleusercontent.com
> 原因应该是服务端dns服务器的问题通过ping google youtube等能解析出ipv6地址但是ping scholar.google.com会发现解析到了一个ipv4地址上。
> 故修改host即可解决

感谢，不过试过了貌似还是一样，/etc/hosts指定了ipv6的scholar，直接无法访问，原先是可以访问但是不可以搜索，很邪门

**Comment by xqdoo00o** [comment]
我也是一样，一定要开ipv6优先，否则根本不走ipv6的流量
