### ISSUE TITLE
1.6.0版本之后，VLESS+XTLS，伪装域名(host)无法配置

### ISSUE THREAD

**Issue by Grandom-P** [2dust/v2rayNG#1019]
### 预期行为
同1.6.0之前的版本一样，正常填写并保存伪装域名(host)

### 实际行为
保存后伪装域名(host)变为空值，连接时提示“io:read/write on closed pipe”

**Comment by yuhan6665** [comment]
host 是 ws h2 等传输的配置，vless+tcp+xtls 只有 sni

**Comment by wfniub** [comment]
新版本确实伪装域名之后就会无法连接，同一个节点旧版本没问题！

**Comment by wfniub** [comment]
不知道是哪里的问题

**Comment by yuhan6665** [comment]
导出配置看一下与旧版本有啥差别

**Comment by wfniub** [comment]
> 导出配置看一下与旧版本有啥差别

{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "test.niux.ga",
            "port": 80,
            "users": [
              {
                "alterId": 0,
                "id": "35f2f0be-2e62-402a-94de-47f8bcca955a",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tcpSettings": {
          "header": {
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache",
                "Host": [
                  "gd.189.cn/TS/recharge/tzUrl.html"
                ]
              }
            },
            "type": "http"
          }
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

上面是旧的正常的




下面是新的无法连接的
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": false
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "test.niux.ga",
            "port": 80,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "35f2f0be-2e62-402a-94de-47f8bcca955a",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tcpSettings": {
          "header": {
            "request": {
              "headers": {
                "Host": [
                  "gd.189.cn/TS/recharge/tzUrl.html"
                ]
              },
              "path": [
                ""
              ]
            },
            "type": "http"
          }
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

**Comment by 2dust** [comment]
看旧版本的配置你使用的是tcp的http伪装,和你的标题对不上.
tcp的http伪装1.6.0+版本应该有问题,我们会处理

**Comment by 2dust** [comment]
> > 导出配置看一下与旧版本有啥差别
> 
> {
> "dns": {
> "hosts": {
> "domain:googleapis.cn": "googleapis.com"
> },
> "servers": [
> "8.8.8.8"
> ]
> },
> "inbounds": [
> {
> "listen": "127.0.0.1",
> "port": 10808,
> "protocol": "socks",
> "settings": {
> "auth": "noauth",
> "udp": true,
> "userLevel": 8
> },
> "sniffing": {
> "destOverride": [
> "http",
> "tls"
> ],
> "enabled": true
> },
> "tag": "socks"
> },
> {
> "listen": "127.0.0.1",
> "port": 10809,
> "protocol": "http",
> "settings": {
> "userLevel": 8
> },
> "tag": "http"
> },
> {
> "listen": "127.0.0.1",
> "port": 10853,
> "protocol": "dokodemo-door",
> "settings": {
> "address": "8.8.8.8",
> "network": "tcp,udp",
> "port": 53
> },
> "tag": "dns-in"
> }
> ],
> "log": {
> "loglevel": "warning"
> },
> "outbounds": [
> {
> "mux": {
> "concurrency": -1,
> "enabled": false
> },
> "protocol": "vmess",
> "settings": {
> "vnext": [
> {
> "address": "test.niux.ga",
> "port": 80,
> "users": [
> {
> "alterId": 0,
> "id": "35f2f0be-2e62-402a-94de-47f8bcca955a",
> "level": 8,
> "security": "auto"
> }
> ]
> }
> ]
> },
> "streamSettings": {
> "network": "tcp",
> "security": "",
> "tcpSettings": {
> "header": {
> "request": {
> "version": "1.1",
> "method": "GET",
> "path": [
> "/"
> ],
> "headers": {
> "User-Agent": [
> "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
> "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
> ],
> "Accept-Encoding": [
> "gzip, deflate"
> ],
> "Connection": [
> "keep-alive"
> ],
> "Pragma": "no-cache",
> "Host": [
> "gd.189.cn/TS/recharge/tzUrl.html"
> ]
> }
> },
> "type": "http"
> }
> }
> },
> "tag": "proxy"
> },
> {
> "protocol": "freedom",
> "settings": {},
> "tag": "direct"
> },
> {
> "protocol": "blackhole",
> "settings": {
> "response": {
> "type": "http"
> }
> },
> "tag": "block"
> },
> {
> "protocol": "dns",
> "tag": "dns-out"
> }
> ],
> "policy": {
> "levels": {
> "8": {
> "connIdle": 300,
> "downlinkOnly": 1,
> "handshake": 4,
> "uplinkOnly": 1
> }
> },
> "system": {
> "statsOutboundUplink": true,
> "statsOutboundDownlink": true
> }
> },
> "routing": {
> "domainStrategy": "IPIfNonMatch",
> "rules": [
> {
> "inboundTag": [
> "dns-in"
> ],
> "outboundTag": "dns-out",
> "type": "field"
> },
> {
> "ip": [
> "8.8.8.8"
> ],
> "outboundTag": "proxy",
> "port": "53",
> "type": "field"
> },
> {
> "ip": [
> "223.5.5.5"
> ],
> "outboundTag": "direct",
> "port": "53",
> "type": "field"
> }
> ]
> },
> "stats": {}
> }
> 
> 上面是旧的正常的
> 
> 下面是新的无法连接的
> {
> "dns": {
> "hosts": {
> "domain:googleapis.cn": "googleapis.com"
> },
> "servers": [
> "8.8.8.8"
> ]
> },
> "inbounds": [
> {
> "listen": "127.0.0.1",
> "port": 10808,
> "protocol": "socks",
> "settings": {
> "auth": "noauth",
> "udp": true,
> "userLevel": 8
> },
> "sniffing": {
> "destOverride": [
> "http",
> "tls"
> ],
> "enabled": false
> },
> "tag": "socks"
> },
> {
> "listen": "127.0.0.1",
> "port": 10809,
> "protocol": "http",
> "settings": {
> "userLevel": 8
> },
> "tag": "http"
> },
> {
> "listen": "127.0.0.1",
> "port": 10853,
> "protocol": "dokodemo-door",
> "settings": {
> "address": "8.8.8.8",
> "network": "tcp,udp",
> "port": 53
> },
> "tag": "dns-in"
> }
> ],
> "log": {
> "loglevel": "warning"
> },
> "outbounds": [
> {
> "mux": {
> "concurrency": 8,
> "enabled": false
> },
> "protocol": "vmess",
> "settings": {
> "vnext": [
> {
> "address": "test.niux.ga",
> "port": 80,
> "users": [
> {
> "alterId": 0,
> "encryption": "",
> "flow": "",
> "id": "35f2f0be-2e62-402a-94de-47f8bcca955a",
> "level": 8,
> "security": "auto"
> }
> ]
> }
> ]
> },
> "streamSettings": {
> "network": "tcp",
> "security": "",
> "tcpSettings": {
> "header": {
> "request": {
> "headers": {
> "Host": [
> "gd.189.cn/TS/recharge/tzUrl.html"
> ]
> },
> "path": [
> ""
> ]
> },
> "type": "http"
> }
> }
> },
> "tag": "proxy"
> },
> {
> "protocol": "freedom",
> "settings": {},
> "tag": "direct"
> },
> {
> "protocol": "blackhole",
> "settings": {
> "response": {
> "type": "http"
> }
> },
> "tag": "block"
> },
> {
> "protocol": "dns",
> "tag": "dns-out"
> }
> ],
> "policy": {
> "levels": {
> "8": {
> "connIdle": 300,
> "downlinkOnly": 1,
> "handshake": 4,
> "uplinkOnly": 1
> }
> },
> "system": {
> "statsOutboundUplink": true,
> "statsOutboundDownlink": true
> }
> },
> "routing": {
> "domainStrategy": "IPIfNonMatch",
> "rules": [
> {
> "inboundTag": [
> "dns-in"
> ],
> "outboundTag": "dns-out",
> "type": "field"
> },
> {
> "ip": [
> "8.8.8.8"
> ],
> "outboundTag": "proxy",
> "port": "53",
> "type": "field"
> },
> {
> "ip": [
> "223.5.5.5"
> ],
> "outboundTag": "direct",
> "port": "53",
> "type": "field"
> }
> ]
> },
> "stats": {}
> }

看旧版本的配置你使用的是tcp的http伪装,和此issue标题对不上.
tcp的http伪装1.6.0+版本应该有问题,我们会处理

**Comment by yuhan6665** [comment]
@Andywei110 感谢反馈，1.6.5 版本应该已经修复了这个问题，请尝试重新导入

**Comment by 6907699** [comment]
单独使用TCP+伪装域名没问题，加了tLS后，老版本可以，3.8号稳定版本也不行，最新1.66也不行，望大佬修复下
