### ISSUE TITLE
ws+tls+domain+cfcdn网页能正常翻出去，play下载不了

### ISSUE THREAD

**Issue by hps0123** [2dust/v2rayNG#102]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
play正常下载

### 实际行为
fb,twitter,google能正常访问，play软件下载不了

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
日志未见明显异常
```
</details>

### 环境信息
andriod7.1.2

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/200
