### ISSUE TITLE
Pixel 3(Android 10) 开启后无反应

### ISSUE THREAD

**Issue by Alienover** [2dust/v2rayNG#102]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
开启V2rayNG，并且连接到自己服务器

### 实际行为
点击APP右下角按钮以及通知栏上的Switch按钮无反应，最后在长按图标出来的菜单栏上点击Switch成功启动连接，但仍然无法成功连接到自己服务器

### 复现方法
一直出现

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
09-16 18:50:42.646 24228 24228 I GoLog   : start v2ray core
09-16 18:50:42.647 24228 24258 I GoLog   : [Warning] v2ray.com/core: V2Ray 4.20.0 started
```
adb获取日志后，发现只有到V2Ray启动的日志，同时服务器那边，没有连接日志
</details>

### 环境信息

设备：Pixel 3
Android版本：Android 10

**Comment by Alienover** [comment]
感觉像是没有获得开启VPN的权限，但。。。不知道怎么搞那个权限

**Comment by Alienover** [comment]
额，发现删掉SSR在VPN上的设置之后就好了😂，应该是第一个启动VPN的，系统会默认设置权限，之后的就不行了，在VPN设置那边删掉之前那个

**Comment by Wowgreat** [comment]
把时间调正确就可以了

**Comment by JackCoder2025** [comment]
> 把时间调正确就可以了

确实要把时间调整正确，tls 对客户端时间误差有一定的要求的。

**Comment by Alienover** [comment]
> > 把时间调正确就可以了
> 
> 
> 
> 确实要把时间调整正确，tls 对客户端时间误差有一定的要求的。

嗯嗯，其实后面发现是Pixel的VPN设置问题，删掉其他软件创建的VPN只保留一个，这样就没问题了👌
