### ISSUE TITLE
建议本地响应 ICMP 报文

### ISSUE THREAD

**Issue by RPRX** [2dust/v2rayNG#1027]
今天测试了一下某线路的稳定性，发现使用 Netch 时本机 ping 任何合法 IP 都是：

```
PS C:\Users\Hidden> ping a.b.c.d

正在 Ping a.b.c.d 具有 32 字节的数据:
来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64

a.b.c.d 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms
```

而在手机上使用 v2rayNG 时，在 Termux 中 ping 任何 IP 都是无响应。

联想到之前有人在 Project X 群说自己玩的一个手游是用 ping 测试连通性，但 NG 不代理 ICMP，就玩不了那个游戏。建议本地响应 ICMP 报文（可能需要简单改改 tun2socks 的代码），实现和 Netch 的效果一致，麻烦 @2dust @yuhan6665

**Comment by yuhan6665** [comment]
好的 我这两天看下

**Comment by rprx** [comment]
https://github.com/XTLS/badvpn

**Comment by RPRX** [comment]
可以直接使用：

https://github.com/XTLS/badvpn
https://github.com/XTLS/libancillary

**Comment by rurirei** [comment]
i'm agreed with madeye to drop all icmp ping request.

**Comment by RPRX** [comment]
@rurirei 首先你要能分清 madeye 和 mygod，其次，这里的问题已经解决，close

**Comment by kekomenos** [comment]
> 今天测试了一下某线路的稳定性，发现使用 Netch 时本机 ping 任何合法 IP 都是：
> 
> ```
> PS C:\Users\Hidden> ping a.b.c.d
> 
> 正在 Ping a.b.c.d 具有 32 字节的数据:
> 来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
> 来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
> 来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
> 来自 a.b.c.d 的回复: 字节=32 时间<1ms TTL=64
> 
> a.b.c.d 的 Ping 统计信息:
>     数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
> 往返行程的估计时间(以毫秒为单位):
>     最短 = 0ms，最长 = 0ms，平均 = 0ms
> ```
> 
> 而在手机上使用 v2rayNG 时，在 Termux 中 ping 任何 IP 都是无响应。
> 
> 联想到之前有人在 Project X 群说自己玩的一个手游是用 ping 测试连通性，但 NG 不代理 ICMP，就玩不了那个游戏。建议本地响应 ICMP 报文（可能需要简单改改 tun2socks 的代码），实现和 Netch 的效果一致，麻烦 @2dust @yuhan6665
