### ISSUE TITLE
新版客户端提示音异常

### ISSUE THREAD

**Issue by charlienew** [2dust/v2rayNG#103]
之前版本的客户端在连接成功之后手机会震动一下。今天更新了Google Play上的最新版，连接成功后会不断发出震动提示直到断开连接，严重影响其他音频播放。
手机Android版本：8.0

**Comment by kirbyzhu** [comment]
同样问题

**Comment by xiaobai1226** [comment]
我的也是，提示音加震动，一直不停

**Comment by kai2ou** [comment]
我的也是

**Comment by cbwang2016** [comment]
我的也是

**Comment by bingvip** [comment]
同样

**Comment by herpherd** [comment]
希望尽快更新解决呢

**Comment by xiaobai1226** [comment]
更新出了，更新后问题解决了

**Comment by charlienew** [comment]
问题似乎没有完全解决，一旦设置显示速度还是会有之前的问题

**Comment by 2dust** [comment]
更新到0.5.6版本,如还有问题在设置中关闭速度显示.
由于手上只有一个手机做测试,这种兼容性的问题只能慢慢调整

**Comment by liu42** [comment]
关闭v2rayNG通知后问题得到解决
