### ISSUE TITLE
v2rayNG内置的ss无法使用

### ISSUE THREAD

**Issue by HubGitty** [2dust/v2rayNG#103]
### 预期行为
正常连接和使用内置的ss

### 实际行为
vmess协议可以使用，ss所有配置输入都确认无误，但浏览器访问网站显示DNS_PROBE_FINISHED_NO_INTERNET
同时使用最新版的ss客户端同样配置可以连接使用，没有问题

### 复现方法
1.打开v2rayNG
2.连接ss的配置文件
3.浏览器访问网站显示DNS_PROBE_FINISHED_NO_INTERNET

### 日志信息
<details>

打开服务器查看无法连接时的日志
得到如下信息：

2019/09/17 16:45:‪28 106.45.0.255‬:39422 accepted tcp:49.4.38.10:443
2019/09/17 16:45:‪29 106.45.0.255‬:40678 rejected  v2ray.com/core/proxy/shadowsocks: failed to read address > chacha20poly1305: message authentication failed

2019/09/17 16:47:‪59 123.144.25.218‬:47376 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack
2019/09/17 16:48:‪01 123.144.25.218‬:48430 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack

2019/09/17 16:49:‪14 106.45.0.255‬:56470 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack
2019/09/17 16:49:‪14 106.45.0.255‬:56756 rejected  v2ray.com/core/proxy/vmess/encoding: duplicated session id, possibly under replay attack

2019/09/17 16:49:‪18 106.45.0.255‬:59334 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user

</details>

### 环境信息
荣耀magic2,最新系统安卓9

### 额外信息
查了下日志里相关ip，以及报告中相关的重放攻击，是否与墙有关？内置的ss模块是否有缺陷？

**Comment by 2dust** [comment]
https://www.v2ray.com/chapter_02/protocols/shadowsocks.html
