### ISSUE TITLE
为了启动时 隐藏VPN 创建的提示，看到可以使用Proxy 模式，请问大家如何有什么方式可以把指定 app 的流量重定向到socks5 端口？

### ISSUE THREAD

**Issue by fuqiangleon** [2dust/v2rayNG#1030]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
启动V2rayNG 的时候，总是会出现 网络请求的提示，请问是否有方法关闭这个提示？

### 实际行为
在启动VPN 的时候 会出现一个VPN 请求的弹窗提示，似乎无法去除，如果使用Porxy 模式，如何重定向 APP 的流量 到1080？

**Comment by fuqiangleon** [comment]
![image](https://user-images.githubusercontent.com/1288399/116201972-a87cf480-a76c-11eb-9e13-84f0c2201faa.png)
![image](https://user-images.githubusercontent.com/1288399/116504412-ccfedb00-a8ea-11eb-8070-25b97d7bc77e.png)

**Comment by yin1999** [comment]
1. 上面这个提示是系统的授权提示，不是这个应用的提示
2. **指定应用代理**可以在`设置`里面设置`分应用代理`（该有VPN提示还是有的，系统原因）

**Comment by fuqiangleon** [comment]
@yin1999 如果要隐藏这个提示，有什么可能的方案或者建议吗？谢谢。

**Comment by yin1999** [comment]
没法隐藏，这个是授权提示，不授权没法开启VPN。
不过系统设置里面应该会有个VPN的设置，你可以去瞅一眼。如果没法保存已授权VPN设置的话，那就只能每次点确认。

**Comment by xiaorong61** [comment]
我是 adguard 作为 vpn，v2rayNG socks5 作为 adguard 的出口。
