### ISSUE TITLE
dns无法解析问题

### ISSUE THREAD

**Issue by wfniub** [2dust/v2rayNG#1032]
最近时长遇到手机端ng无法解析出连接节点的域名dns问题，同环境wifi下，电脑没问题，不知道是哪里的问题，也尝试取消勾选了启用本地dns，也尝试修改了境内dns和远程dns都无法解决！

**Comment by Fo0o0oX** [comment]
我也遇到了 应该是梯子商的问题，梯子运营商block了某些域名，v2rayNG无论怎么配都会走梯子运营商解析IP，导致部分网站开不了 觉得v2rayNG某些域名解析的处理逻辑有问题，国内域名明明可以不用代理解析的

**Comment by wfniub** [comment]
> 我也遇到了 应该是梯子商的问题，梯子运营商block了某些域名，v2rayNG无论怎么配都会走梯子运营商解析IP，导致部分网站开不了 觉得v2rayNG某些域名解析的处理逻辑有问题，国内域名明明可以不用代理解析的

应该不是节点的问题，节点是自己的，没有限制，而且用电脑端v2rayn连接同样的节点是没有问题的，不是解析不到要访问的域名，而是解析不到要连接的节点的域名！

**Comment by DarinzyGH** [comment]
也遇到过，直接用ip才行

**Comment by shijia7** [comment]
关了分应用代理，只用本地dns，重启服务试试

**Comment by cryptomoai** [comment]
我也遇到了同样的问题，手机端无法使用域名连接服务器，但电脑可以。另外，如果新建一个基于ip地址的配置，连接成功后断开，然后再次连接基于域名的配置，就可以成功连接，不知道为什么。

**Comment by shijia7** [comment]
还有一个远古诡异的问题，有时twitter的图片加载不出来，重启服务不行，加了白名单也不行，杀掉软件重启才能解决

**Comment by libea18** [comment]
@shijia7 turn on ipv6 route and Share the result .
