### ISSUE TITLE
Couldn't start download in Google Play 安卓无法在Google商店下载

### ISSUE THREAD

**Issue by q350976501** [2dust/v2rayNG#1040]
Figured problem on
domain:google.cn,
domain:googleapis.cn,
Should these two site through proxy or direct？
site strategy should be ip on demand or ip if notmatch？

Plus，I was wonder if there is a better settup for an enhance geoip and geosite.

看了很多问题，感觉主要问题是在
domain:google.cn,
domain:googleapis.cn,
这两个域名的解释上，
问题是，这个两个域名应该选择直连还是代理？
域名策略应该选 ip on demand 还是 ip if notmatch？

**Comment by q350976501** [comment]
同时求个好用的域名规则，已更新了增强版geostie和ip文件，目前只代理geosite:geolocation-!cn

**Comment by cmj799** [comment]
我也遇到了同样的问题，也不知道怎么解决。。。

**Comment by q350976501** [comment]
已解决，全局代理
IP if not match
以下加入代理
domain:google.cn,
domain:googleapis.cn,

**Comment by cmj799** [comment]
问题仍然没有解决

**Comment by 93syblack** [comment]
用别的vpn能登陆google play，然后用v2rayng能上，但是过1天左右再用v2rayng单独登录就不行了，即使用上面那位朋友的设置也不行

**Comment by lbbboy** [comment]
> 用别的vpn能登陆google play，然后用v2rayng能上，但是过1天左右再用v2rayng单独登录就不行了，即使用上面那位朋友的设置也不行

用clash for android 啊。这个app不好用了。

**Comment by luckiestone** [comment]
同样的问题，上面提到的添加规则，以及取消嗅探选项的都不起作用。使用的分应用代理，全局，Google Play上无法更新和下载，使用Clash正常。

**Comment by q350976501** [comment]
我最近也不行了，之前测试的话，切换全局代理和绕过局域网都不影响。但是在没有更改设置的情况下，最近又无法下载了，所以还是APP问题吧我感觉。

**Comment by lbbboy** [comment]
> 用别的vpn能登陆google play，然后用v2rayng能上，但是过1天左右再用v2rayng单独登录就不行了，即使用上面那位朋友的设置也不行

你这个吧 dns  1.1.1.1 改下，可能别墙了.

**Comment by sacc-leo** [comment]
> > 用别的vpn能登陆google play，然后用v2rayng能上，但是过1天左右再用v2rayng单独登录就不行了，即使用上面那位朋友的设置也不行
> 
> 用clash for android 啊。这个app不好用了。

一样的问题，按照之前提到的修改方法都不行

**Comment by cmj799** [comment]
问题解决了，我就是把google市场升级到最新版本就好了，不知道为什么，google市场不会自动升级？！！！！！

**Comment by niclau** [comment]
同样问题，查看v2rayng的log，发现可能是这个原因，这个域名被解析到google cn的ip了
2:00:00.428 I/GoLog   ( 6516): Not Using Prepared: tcp,r17---sn-ni57dn76.xn--ngstr-lra8j.com:443
2:00:00.430 I/GoLog   ( 6516): tcp:127.0.0.1:37230 accepted tcp:203.208.32.35:443 [socks -> direct]

**Comment by q350976501** [comment]
问题还是反复出现，可能是更新了之后
