### ISSUE TITLE
自5月1日起，手机端V2rayNG无法访问自建VPS，电脑端正常。

### ISSUE THREAD

**Issue by xeencheng** [2dust/v2rayNG#1045]
服务端进行过排查，可以Ping通，且通过IPIP.net的ping工具进行检查，证明IP没有被墙。伪装网站可以正常访问,cloudflare代理DNS服务正常，域名与IP地址可以正常对应，通过Ping命令检查过，acme证书已更新，xray服务端内核已升级至1.4.2，电脑端V2rayN内核已升级至1.4.2。手机端使用v2rayNG-1.5.16版本

### 预期行为
自建VPS，正常使用两月有余，期间使用电脑端V2rayN和手机端V2rayNG访问均正常

### 实际行为
于5月1日起手机端V2rayNG无法访问，TCP测试提示fail to detect internet connection: context deadline exceeded。前一日（即4月30日）使用正常，电脑端5月1日前后使用一切正常，该Issue发起亦为电脑端使用V2rayN加载该VPS发起。手机端并未更改设置，亦未更换软件版本。

一度怀疑是服务器时间不同步导致，故检查后将服务器时间与本地时间同步，后尝试连接，故障依旧。后排除服务器时间，因为使用的是Vless+Xray+XTLS-rprx-direct, 应该与服务器与本地时间不同步无关。

同期使用自建heroku小鸡测试，手机端和电脑端，无论哪个版本均可正常访问。heroku服务器采用Vless+v2ray内核+WS+Couldflare反代

### 复现方法
1. 更新手机端至1.6.5版本，故障依旧
2. 降级手机端至1.5.14版本，故障依旧
3. 降级手机端至1.5.10版本，故障依旧
4. 重启服务器N次，且将Ngix服务，证书及Xray内核升级至最新，故障依旧
5. 手机端尝试使用本地DNS，修改远程DNS地址，故障依旧
6. Allowinsecure选项，无论开启与否，故障依旧

### 日志信息
<details>
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog: {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "dns": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "hosts": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "domain:googleapis.cn": "googleapis.com"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "servers": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "1.1.1.1"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     ]
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "inbounds": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "listen": "127.0.0.1",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "port": 10808,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "socks",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "settings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "auth": "noauth",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "udp": true,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "userLevel": 8
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "sniffing": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "destOverride": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "http",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "tls"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         ],
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "enabled": true
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "socks"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "listen": "127.0.0.1",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "port": 10809,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "http",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "settings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "userLevel": 8
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "http"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "listen": "127.0.0.1",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "port": 10853,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "dokodemo-door",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "settings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "address": "1.1.1.1",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "network": "tcp,udp",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "port": 53
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "dns-in"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   ],
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "log": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "loglevel": "warning"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "outbounds": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "mux": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "concurrency": -1,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "enabled": false
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "vless",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "settings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "vnext": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:             "address": "rXXXXXXXX（代理服务器地址）",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:             "port": 443,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:             "users": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:               {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:                 "alterId": 0,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:                 "encryption": "none",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:                 "flow": "xtls-rprx-direct",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:                 "id": "2XXXXXXXXXXXXXXXX",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:                 "level": 8,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:                 "security": "auto"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:               }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:             ]
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         ]
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "streamSettings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "network": "tcp",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "security": "xtls",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "xtlsSettings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "allowInsecure": false,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "serverName": ""
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "proxy"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "freedom",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "settings": {},
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "direct"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "blackhole",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "settings": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "response": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "type": "http"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "block"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "protocol": "dns",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "tag": "dns-out"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   ],
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "policy": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "levels": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "8": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "connIdle": 300,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "downlinkOnly": 1,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "handshake": 4,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "uplinkOnly": 1
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "system": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "statsOutboundUplink": true,
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       "statsOutboundDownlink": true
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "routing": {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "domainStrategy": "IPIfNonMatch",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     "rules": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "inboundTag": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "dns-in"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         ],
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "outboundTag": "dns-out",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "type": "field"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "ip": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "1.1.1.1"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         ],
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "outboundTag": "proxy",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "port": "53",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "type": "field"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       {
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "ip": [
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:           "223.5.5.5"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         ],
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "outboundTag": "direct",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "port": "53",
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:         "type": "field"
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:       }
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:     ]
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   },
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog:   "stats": {}
05-03 23:19:35.900  9205  9205 D V2rayConfigUtilGoLog: }
05-03 23:19:36.101  2559  2559 I GoLog   : loading core config
05-03 23:19:36.101  2559  2620 I GoLog   : Preparing Domain: rXXXXXXXXX
05-03 23:19:36.117  2559  2559 I GoLog   : new core
05-03 23:19:36.123  2559  2559 I GoLog   : start core
05-03 23:19:36.125  2559  2619 I GoLog   : [Warning] core: Xray 1.2.1 started
05-03 23:19:36.162  2559  2559 D com.v2ray.ang: [/data/app/~~OYQhhbKHnuBaqnhqCfIA0w==/com.v2ray.ang-F0DXns3Yx1iuA8v5cHTJ2Q==/lib/arm/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
05-03 23:19:36.173  2559  2559 D com.v2ray.ang: Process[pid=2649, hasExited=false]
05-03 23:19:36.173  2559  2559 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
05-03 23:19:36.252  2559  2653 D com.v2ray.ang: sendFd tries: 0
05-03 23:19:36.289  2559  2616 I GoLog   : tcp:127.0.0.1:45426 accepted tcp:172.217.160.106:443 [proxy]
05-03 23:19:36.290  2559  2615 I GoLog   : Dial pending prepare  ... rXXXXXXXXX:443
05-03 23:19:36.296  2559  2615 I GoLog   : Dial pending prepare  ... rXXXXXXXXX:443
05-03 23:19:36.297  2559  2615 I GoLog   : tcp:127.0.0.1:45430 accepted tcp:172.217.27.138:443 [proxy]
05-03 23:19:36.325  2559  2619 I GoLog   : 127.0.0.1:47281 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:19:36.325  2559  2615 I GoLog   : Dial pending prepare  ... rXXXXXXXXX:443
05-03 23:19:36.501  2559  2619 I GoLog   : Dial pending prepare  ... rXXXXXXXXX:443
05-03 23:19:36.501  2559  2615 I GoLog   : tcp:127.0.0.1:45434 accepted tcp:172.217.160.110:443 [proxy]
05-03 23:19:36.509  2559  2616 I GoLog   : Dial pending prepare  ... rXXXXXXXXX:443
05-03 23:19:36.509  2559  2624 I GoLog   : tcp:127.0.0.1:45438 accepted tcp:172.217.160.86:443 [proxy]
05-03 23:19:36.523  2559  2624 I GoLog   : Dial pending prepare  ... rXXXXXXXXX:443
05-03 23:19:36.524  2559  2616 I GoLog   : tcp:127.0.0.1:45442 accepted tcp:172.217.160.86:443 [proxy]
05-03 23:19:36.677  2559  2616 I GoLog   : 127.0.0.1:46311 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:19:36.696  2559  2615 I GoLog   : 127.0.0.1:45269 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:19:36.714  2559  2615 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:36.714  2559  2615 I GoLog   : tcp:127.0.0.1:45450 accepted tcp:172.217.160.110:443 [proxy]
05-03 23:19:36.930  2559  2615 I GoLog   : 127.0.0.1:43200 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:19:36.963  2559  2624 I GoLog   : 127.0.0.1:39184 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:19:37.103  2559  2616 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:37.103  2559  2615 I GoLog   : tcp:127.0.0.1:45454 accepted tcp:172.217.160.109:443 [proxy]
05-03 23:19:37.201  2559  2616 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:37.201  2559  2615 I GoLog   : tcp:127.0.0.1:45456 accepted tcp:172.217.160.110:443 [proxy]
05-03 23:19:37.204  2559  2624 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:37.204  2559  2615 I GoLog   : tcp:127.0.0.1:45458 accepted tcp:172.217.160.110:443 [proxy]
05-03 23:19:37.734  2559  2624 I GoLog   : 127.0.0.1:40798 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:19:37.890  2559  2629 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:37.890  2559  2619 I GoLog   : tcp:127.0.0.1:45462 accepted tcp:203.119.175.223:443 [proxy]
05-03 23:19:38.185  2559  2625 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:38.186  2559  2629 I GoLog   : tcp:127.0.0.1:45472 accepted tcp:121.46.30.53:7002 [proxy]
05-03 23:19:38.217  2559  2625 I GoLog   : Dial pending prepare  ... rXXXXXXXXXX:443
05-03 23:19:38.218  2559  2629 I GoLog   : tcp:127.0.0.1:45476 accepted tcp:157.240.12.5:443 [proxy]
05-03 23:19:38.218  2559  2624 I GoLog   : Dial pending prepare  ... rXXXXXXXXXXXX:443
05-03 23:19:38.218  2559  2629 I GoLog   : udp:127.0.0.1:44537 accepted udp:216.58.200.246:443 [proxy]
05-03 23:19:38.602  2559  2619 I GoLog   : Dial pending prepare  ... rXXXXXXXXXXXX:443
05-03 23:19:38.602  2559  2629 I GoLog   : tcp:127.0.0.1:45480 accepted tcp:157.240.12.5:443 [proxy]
以下省略....

05-03 23:20:00.783  2559  2620 I GoLog   : tcp:127.0.0.1:45534 accepted tcp:121.46.30.53:7002 [proxy]
05-03 23:20:00.954  2559  2629 I GoLog   : 127.0.0.1:40953 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:02.927  2559  2616 I GoLog   : 127.0.0.1:43420 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:02.927  2559  2624 I GoLog   : 127.0.0.1:37922 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:04.065  2559  2653 D com.v2ray.ang: measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded
05-03 23:20:06.426  2559  2616 I GoLog   : 127.0.0.1:41323 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:06.916  2559  2615 I GoLog   : 127.0.0.1:40494 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:07.305  2559  2620 I GoLog   : 127.0.0.1:44892 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:07.578  2559  2625 I GoLog   : 127.0.0.1:43355 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:08.040  2559  2620 I GoLog   : 127.0.0.1:49125 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
05-03 23:20:08.198  2559  2559 D com.v2ray.ang: tun2socks destroy
05-03 23:20:10.122  2559  2619 I GoLog   : PrepareDomain err: i/o timeout
05-03 23:20:10.123  2559  2619 I GoLog   : PrepareDomain exit due to core closed

</details>

### 环境信息
pixel 4A 5G, 已Root，安全补丁更新至210405

**Comment by cyao2q** [comment]
使用1.5.16旧版或者不要用cloudflare代理地址

**Comment by xeencheng** [comment]
> 使用1.5.16旧版或者不要用cloudflare代理地址

不好意思，恕我语文不好，没有看懂您的回复。1.5.16旧版是什么意思？第二dns解析没有问题，去掉伪装网址不是此地无银三百两么？顺便一提：相同配置，在ios上使用小火箭一切正常，挂着不论是访问网址还是看油管都可以。

**Comment by e3lz** [comment]
您是正确的，问题是软件，我也使用此软件，某些国家/地区也这样使用，我认为此应用程序中有一项服务需要电话自由但无法访问，通常华为电话有此问题，您的手机是什么 模型

**Comment by xeencheng** [comment]
> 您是正确的，问题是软件，我也使用此软件，某些国家/地区也这样使用，我认为此应用程序中有一项服务需要电话自由但无法访问，通常华为电话有此问题，您的手机是什么 模型

Hi there. As I mentioned above, I'm using pixel 4A 5G, BTW, I did a test on Honor Mate 10, with the same VPS, and the version of v2rayNG is 1.5.10. Again, I've got the very same error- context deadline exceeded, by which I was not surprised. So if anyone got something new, please let me know. Ps: this freaking error is driving me nuts! I really appreciate if anyone could help me resolve it!

**Comment by yuhan6665** [comment]
05-03 23:19:38.602 2559 2619 I GoLog : Dial pending prepare ... rXXXXXXXXXXXX
Not able to resolve VPS ip, as a workaround, you can type ip in address, instead of domain.
Maybe domain expired?

**Comment by xeencheng** [comment]
> 05-03 23:19:38.602 2559 2619 I GoLog : Dial pending prepare ... rXXXXXXXXXXXX
> Not able to resolve VPS ip, as a workaround, you can type ip in address, instead of domain.
> Maybe domain expired?

Hi guys, good news and bad news! The bad one is when I followed your advice and switch the address to the genuine ip address of the server, the error became--- I/o read and write on closed pipe 😭, and yes it remained unconnected (when I was using 1.5.10). On the other hand, when I updated the software to 1.6.5 and tried again by switching it to the genuine ip address, it worked finally!! And you know what, when I set the address back to my disguise address, it still works!! Don't know what happened, but it definitely was not the problem of the certificate nor the domine, as I can use shadow rocket to connect the server. I suspect it was a bug happened when the software tired to translate the web address to ip.

So I urge anyone who had the same problem to update the software to latest version and set your address to genuine ip of your server, then swith it back after the connection was successfully made. 💥 You may see the miracle, at least it worked for me!

**Comment by DefiedParty** [comment]
> > 05-03 23:19:38.602 2559 2619 I GoLog : Dial pending prepare ... rXXXXXXXXXXXX
> > Not able to resolve VPS ip, as a workaround, you can type ip in address, instead of domain.
> > Maybe domain expired?
> 
> Hi guys, good news and bad news! The bad one is when I followed your advice and switch the address to the genuine ip address of the server, the error became--- I/o read and write on closed pipe 😭, and yes it remained unconnected (when I was using 1.5.10). On the other hand, when I updated the software to 1.6.5 and tried again by switching it to the genuine ip address, it worked finally!! And you know what, when I set the address back to my disguise address, it still works!! Don't know what happened, but it definitely was not the problem of the certificate nor the domine, as I can use shadow rocket to connect the server. I suspect it was a bug happened when the software tired to translate the web address to ip.
> 
> So I urge anyone who had the same problem to update the software to latest version and set your address to genuine ip of your server, then swith it back after the connection was successfully made. 💥 You may see the miracle, at least it worked for me!

nice solution!!!!

**Comment by DefiedParty** [comment]
这个问题是新版核心策略调整导致的，按上面 @xeencheng 提供的方法首次连接使用IP，然后再改回CF代理的域名即可，实测后续流量还是会经过CF的代理！

**Comment by leo985** [comment]
补充一下吧，新开一个端口，电脑客户端 v2rayU，用了很久没问题，如果同样的端口给手机用，能用2分钟，很快就不行了，此时电脑再用，电脑端也不行！服务端 V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.)
