### ISSUE TITLE
订阅消失

### ISSUE THREAD

**Issue by BruceDeng619** [2dust/v2rayNG#1046]
订阅消失，需要重新订阅。

**Comment by yuhan6665** [comment]
version?

**Comment by BruceDeng619** [comment]
> version?

1.6.6

**Comment by yuhan6665** [comment]
What did you do or observe when it happens? Are you able to reproduce this issue?

**Comment by TujinLee** [comment]
> version?
1.5.16版本，即当前googleplay最新版本订阅也消失了，而且更新订阅提示失败

**Comment by BallM8964** [comment]
小米手机否？我朋友是小米手机出现了此问题。

**Comment by TujinLee** [comment]
> 小米手机否？我朋友是小米手机出现了此问题。

小米10pro

**Comment by BruceDeng619** [comment]
小米10

TujinLee ***@***.***> 于2021年5月10日周一 下午3:43写道：

**Comment by BruceDeng619** [comment]
> What did you do or observe when it happens? Are you able to reproduce this issue?

I will let you know when it happens again.

**Comment by yuhan6665** [comment]
If you encounter this when update subscription. That means the subscription link has some issue.

**Comment by BruceDeng619** [comment]
I believe that is not the case.
