### ISSUE TITLE
apk可执行文件和tag、和源代码有很大差异，且不少代码从未被提交

### ISSUE THREAD

**Issue by jameszjca** [2dust/v2rayNG#1047]
1.5.2-v2fly-core 及其它版本

apk可执行文件和tag、和源代码对不上，代码实际落后不少，且从未被提交。
release并不是用被提交的代码build得来。

既然选择开源，最起码的专业底线还是要保持。

**Comment by ghost** [comment]
它是老版本开源，新的版本闭了。原因是许多人拿源码修改了搞成自己的牟利

**Comment by ghost** [comment]
> 它是老版本开源，新的版本闭了。原因是许多人拿源码修改了搞成自己的牟利

Selling foss software is completely legal and encouraged by the gnu project, as long as they provide the corresponding complete source code.

>Many people believe that the spirit of the GNU Project is that you should not charge money for distributing copies of software, or that you should charge as little as possible—just enough to cover the cost. This is a misunderstanding.

>Actually, we encourage people who redistribute free software to charge as much as they wish or can. If a license does not permit users to make copies and sell them, it is a nonfree license. If this seems surprising to you, please read on.

>The word “free” has two legitimate general meanings; it can refer either to freedom or to price. When we speak of “free software”, we're talking about freedom, not price. (Think of “free speech”, not “free beer”.) Specifically, it means that a user is free to run the program, study and change the program, and redistribute the program with or without changes.

>Free programs are sometimes distributed gratis, and sometimes for a substantial price. Often the same program is available in both ways from different places. The program is free regardless of the price, because users have freedom in using it.

source: https://www.gnu.org/philosophy/selling.en.html

There are more real world example of selling foss software:
1. https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux
2. https://www.suse.com/products/server
3. https://play.google.com/store/apps/details?id=app.fedilab.android

This is a totally invalid excuse.

**Comment by ghost** [comment]
btw, @2dust is also selling this app for money on google play: https://play.google.com/store/apps/details?id=com.v2ray.v2fly

Should he also be banned from accessing source code of this app?

**Comment by wc7086** [comment]
> 
> 
> > 它是老版本开源，新的版本闭了。原因是许多人拿源码修改了搞成自己的牟利
> 
> Selling foss software is completely legal and encouraged by the gnu project, as long as they provide the corresponding complete source code.
> 
> > Many people believe that the spirit of the GNU Project is that you should not charge money for distributing copies of software, or that you should charge as little as possible—just enough to cover the cost. This is a misunderstanding.
> 
> > Actually, we encourage people who redistribute free software to charge as much as they wish or can. If a license does not permit users to make copies and sell them, it is a nonfree license. If this seems surprising to you, please read on.
> 
> > The word “free” has two legitimate general meanings; it can refer either to freedom or to price. When we speak of “free software”, we're talking about freedom, not price. (Think of “free speech”, not “free beer”.) Specifically, it means that a user is free to run the program, study and change the program, and redistribute the program with or without changes.
> 
> > Free programs are sometimes distributed gratis, and sometimes for a substantial price. Often the same program is available in both ways from different places. The program is free regardless of the price, because users have freedom in using it.
> 
> source: https://www.gnu.org/philosophy/selling.en.html
> 
> There are more real world example of selling foss software:
> 
>     1. https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux
> 
>     2. https://www.suse.com/products/server
> 
>     3. https://play.google.com/store/apps/details?id=app.fedilab.android
> 
> 
> This is a totally invalid excuse.

但是作者并不喜欢这样，很多作者只想开放源代码，但并不希望别人拿去牟利。虽然作者完全可以使用私有开源软件协议而不使用自由开源软件协议，但本软件在中华人民共和国不会得到法律保护。且开源协议在中华人民共和国是否有效是存疑的。

**Comment by wc7086** [comment]
#172
