### ISSUE TITLE
Re-report issue#1045

### ISSUE THREAD

**Issue by xeencheng** [2dust/v2rayNG#1048]
Retested and it turned out that my solution to error context deadline exceeded is just a temporary one, yet did not really fixed the problem!

### 
As I rebooted my phone, and turned v2rayNG, the very same error, again, haunted me. So I used my "magic" solution and it worked. But on the second thought, I pulled out the logcat and want to figure out why it worked.
### 实际行为
The address in the software actually didn't change to my disguise address, but the genuine ip address. That's the reason why it worked. But if I did so, what's the point of my disguise address?

### 复现方法
1. Interesting thing is, when I used my other server, the heroku's, and turn back to the original one, the error changed to net/http 1.x transportation connection. Then I realized maybe the different error occured because the software treat the address as the address of heroku's server.
2.  When I opened the log to check out, yep, it's exactly what I assumed. See for yourselves.
3. 104.17.8.171, is the address of a cloudflare server that I used for my heroku's server.
4. It seems the used info of ip address will store in the cache for a while, when I forced to clear the cache of V2RAYNG, same error info was back. So I assume it might be a problem of the software when translating the address.
5. Again, it worked fine on ios with shadow rocket, ver 2.1.82.

### 日志信息
<details>
--------- beginning of main
05-06 17:10:57.814 I/GoLog   (23126): udp:127.0.0.1:48853 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:10:57.834 I/GoLog   (23126): tcp:127.0.0.1:43292 accepted tcp:34.102.215.99:443 [socks >> proxy]
05-06 17:10:58.102 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:10:58.103 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:10:58.104 I/GoLog   (23126): udp:127.0.0.1:47747 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:10:58.410 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:10:58.592 I/GoLog   (23126): udp:127.0.0.1:49630 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:10:58.695 I/GoLog   (23126): udp:127.0.0.1:48590 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:10:58.818 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:10:58.942 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:10:59.442 D/com.v2ray.ang(23126): tun2socks destroy
05-06 17:10:59.443 I/tun2socks(25355): NOTICE(tun2socks): termination requested
05-06 17:10:59.443 I/tun2socks(25355): NOTICE(tun2socks): tearing down
05-06 17:10:59.443 I/tun2socks(25355): NOTICE(tun2socks): Free TCP connections
05-06 17:10:59.462 I/tun2socks(25355): NOTICE(tun2socks): exiting
05-06 17:11:00.642 I/GoLog   (23126): Preparing Domain r xxxxxxxxxx:443
05-06 17:11:00.643 I/GoLog   (23126): loading core config
05-06 17:11:00.659 I/GoLog   (23126): new core
05-06 17:11:00.662 I/GoLog   (23126): start core
05-06 17:11:00.665 I/GoLog   (23126): [Warning] core: Xray 1.4.2 started
05-06 17:11:00.732 D/com.v2ray.ang(23126): [/data/app/~~x7XlLGtvCe2zDMA5tCc78Q==/com.v2ray.ang-QY_-Jy1yWqjDYiShnB3RvQ==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
05-06 17:11:00.734 D/com.v2ray.ang(23126): Process[pid=26963, hasExited=false]
05-06 17:11:00.735 D/com.v2ray.ang(23126): /data/user/0/com.v2ray.ang/files/sock_path
05-06 17:11:00.751 I/tun2socks(26963): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
05-06 17:11:00.785 D/com.v2ray.ang(23126): sendFd tries: 0
05-06 17:11:00.786 I/tun2socks(26963): NOTICE(tun2socks): entering event loop
05-06 17:11:00.858 I/GoLog   (23126): tcp:127.0.0.1:43354 accepted tcp:31.13.75.5:443 [socks >> proxy]
05-06 17:11:00.957 I/GoLog   (23126): udp:127.0.0.1:40007 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:11:00.959 I/GoLog   (23126): udp:127.0.0.1:41203 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:11:01.065 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:01.126 I/GoLog   (23126): udp:127.0.0.1:40561 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:11:01.161 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:01.183 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:01.263 I/GoLog   (23126): tcp:127.0.0.1:43370 accepted tcp:34.102.215.99:443 [socks >> proxy]
05-06 17:11:01.330 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:01.348 I/GoLog   (23126): udp:127.0.0.1:43794 accepted udp:35.201.85.233:443 [socks >> proxy]
05-06 17:11:01.521 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:01.569 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:02.019 I/GoLog   (23126): udp:127.0.0.1:39141 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:11:02.282 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:02.283 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:02.525 I/GoLog   (23126): tcp:127.0.0.1:43382 accepted tcp:34.102.215.99:443 [socks >> proxy]
05-06 17:11:02.801 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:02.802 D/com.v2ray.ang(23126): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\u007f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
05-06 17:11:03.292 I/GoLog   (23126): udp:127.0.0.1:42828 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:11:03.498 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:03.551 I/GoLog   (23126): udp:127.0.0.1:43794 accepted udp:35.201.85.233:443 [socks >> proxy]
05-06 17:11:03.833 I/GoLog   (23126): Using Prepared: 104.17.8.171
05-06 17:11:05.960 I/GoLog   (23126): udp:127.0.0.1:40007 accepted udp:1.1.1.1:53 [socks >> proxy]
05-06 17:11:05.960 I/GoLog   (23126): udp:127.0.0.1:41203 accepted udp:1.1.1.1:53 [socks >> proxy]

</details>

### 额外信息（可选）
I will do more test and report later 😊.

**Comment by xeencheng** [comment]
Problem solved by updating the version 1.6.7, been testing for a week or two, it seems fine now!

**Comment by leo985** [comment]
1.7.17都还有这个问题。。。。。。没有解决方案么？
自从搞了xray，这个fly就不行了。之前一直很稳定

**Comment by TheHolyLoli** [comment]
1.7.20 still has this problem
