### ISSUE TITLE
1.6.6 版本 quic协议不可用

### ISSUE THREAD

**Issue by Dts725** [2dust/v2rayNG#1049]
pc 版本的  v2rayN  可以正常使用quic  dtls 
安卓的  quic  连接失败 context deadline exceeded
日志看起来很奇怪
--------- beginning of system
--------- beginning of main
05-07 17:47:45.159 I/GoLog   (23672): udp:127.0.0.1:49337 accepted udp:10xx.xxx.157.xx:29xx [socks >> proxy]
05-07 17:47:47.195 I/GoLog   (23672): udp:127.0.0.1:46344 accepted udp:1.1.1.1:53 [socks >> proxy]
05-07 17:47:47.375 I/GoLog   (23672): tcp:127.0.0.1:43700 accepted tcp:123.125.102.202:443 [socks >> proxy]
05-07 17:47:47.655 D/com.v2ray.ang(23672): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded
05-07 17:47:50.162 I/GoLog   (23672): udp:127.0.0.1:38017 accepted udp:10xx.xxx.157.xx:29xx [socks >> proxy]
05-07 17:47:52.198 I/GoLog   (23672): udp:127.0.0.1:43012 accepted udp:114.114.114.114:53 [socks >> proxy]
05-07 17:47:52.346 I/GoLog   (23672): tcp:127.0.0.1:43704 accepted tcp:203.107.1.1:80 [socks >> proxy]
05-07 17:47:55.016 I/GoLog   (23672): udp:127.0.0.1:41585 accepted udp:1.1.1.1:53 [socks >> proxy]
05-07 17:47:55.168 I/GoLog   (23672): udp:127.0.0.1:

远程地址稍微处理了下 10xx.xxx.157.xx:29xx
各位大佬帮忙看下

**Comment by yuhan6665** [comment]
在分应用里面把 v2rayNG 排除了试一下

**Comment by Dts725** [comment]
> 在分应用里面把v2rayNG排除了试一下

试了下概率能测试通过 但是打不开 页面

**Comment by xeencheng** [comment]
不用折腾了，5月开始很多都是人context deadline exceeded，原因尚不明确。顺带一提，我的也是PC端可以用，而安卓端就是CDE

**Comment by Dts725** [comment]
> 不用折腾了，5月开始很多都是人context deadline exceeded，原因尚不明确。顺带一提，我的也是PC端可以用，而安卓端就是CDE
已经放弃了  使用默认tcp

**Comment by reatang** [comment]
PC一直用的quic协议没问题，但是Android不能用。
然后改为kcp协议，直接把服务器封了。。。。

**Comment by yuhan6665** [comment]
Fixed in 1.6.29

**Comment by kkTTAO** [comment]
大佬们问题解决了吗？我的1月份才出现CDE  手机版更新到最新版也无济于事
