### ISSUE TITLE
移除 ipv6优先 选项后，不给TUN接口分配ipv6地址，导致无法连接ipv6 only网站

### ISSUE THREAD

**Issue by lns103** [2dust/v2rayNG#1052]
### 预期行为
正常连接ipv6 only的网站

### 实际行为
更新至1.6.7后，无法访问远程和国内的纯ipv6网站
（因为家中没有公网ipv4，只能通过ddns ipv6地址访问回家）

### 复现方法
1. 使用1.6.6打开ipv6优先，使用chrome正常访问 [ipv6.google.com](https://ipv6.google.com/) 和家中设备的ddns地址 xxx.dynv6.net (只有AAAA记录) ，[test-ipv6.com](http://test-ipv6.com/) 测试通过。
2. 更新到1.6.7，没有ipv6相关选项，使用chrome访问 [ipv6.google.com](https://ipv6.google.com/) 以及 xxx.dynv6.net 提示 "无法访问此网站 检查 xxx.dynv6.net 中是否有拼写错误 DNS_PROBE_FINISHED_NXDOMAIN"。[test-ipv6.com](http://test-ipv6.com/) 测试不通过。
3. 退回1.6.6打开ipv6优先，网站正常访问。

### 日志信息

1.6.6启动日志(开启ipv6优先)

```
05-09 15:50:58.139 D/com.v2ray.ang(28115): [/data/app/~~rjTDnEspHg4_IKhg7JzBNQ==/com.v2ray.ang-hdGAdkQFLcXSLQYpnEc8yw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
```

1.6.7启动日志   

```
05-09 15:47:59.874 D/com.v2ray.ang(17589): [/data/app/~~x5UuN2JcQvTqzEH4mwv0WA==/com.v2ray.ang-WEji_2MtQpGQyEhqx6E_aA==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
```

1.6.7的日志最后少了一句```--netif-ip6addr, da26:2626::2```

### 环境信息
服务器和手机网络都是ipv4/ipv6双栈
MIUI 12.5 Andriod 11

**Comment by pty819** [comment]
我的miui12.5更新后也是这样，无法访问ipv6。移除该选项之前打开ipv6优先时，会因为返回ipv6地址但是没考虑到wifi没有分配ipv6而无法访问国内网站。。。

**Comment by lns103** [comment]
> 我的miui12.5更新后也是这样，无法访问ipv6。移除该选项之前打开ipv6优先时，会因为返回ipv6地址但是没考虑到wifi没有分配ipv6而无法访问国内网站。。。

在1.6.6中，打开本地DNS，导出已经添加的完整配置，导入自定义配置（就是刚才导出的），在"DNS": "servers":[ ......在最后加上,"localhost"]，然后关闭本地DNS，连接自定义配置即可
