### ISSUE TITLE
是否可以在设置里添加开启tls时vmess默认使用zero加密的选项

### ISSUE THREAD

**Issue by pty819** [2dust/v2rayNG#1053]
![Screenshot_2021-05-12-02-29-32-154_com.v2ray.ang.jpg](https://user-images.githubusercontent.com/14341805/117867795-6e166a00-b2cb-11eb-9519-aac1f8846d8c.jpg)
vmess的加密默认为auto，在aes和chacha中二选一，但是在使用tls之后再对vmess加密就有些浪费性能了。考虑到一些用户在使用cdn，不能贸然把tls时auto加密设为zero。

请问是否可以在设置里添加一个选项，打开该选项时vmess在使用tls时默认使用zero加密，这样的话可以照顾手机用户对于省电的需求。毕竟新版soga已经支持了zero加密，其他后端也会跟上。目前vless仍在高速迭代的状态，机场不会贸然支持vless订阅，因此提出该issue。

**Comment by yuhan6665** [comment]
Security should be "auto" by default. If you want otherwise, 机场 can send a link with new format to specify what security they like. See "scy" details in
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)
