### ISSUE TITLE
v2rayng无法使用he.net的ipv6通道

### ISSUE THREAD

**Issue by clk01** [2dust/v2rayNG#1055]
先谢过大佬的魔法app。

### 预期行为
访问google时使用he.net的IPV6通道

### 实际行为
不能使用vps上he.net的IPV6通道。
在vps上设置了he.net的IPV6通道，并且加入了google使用hosts中ipv6地址，使用windows端的v2rayn已经可以规避vps垃圾ip导致谷歌搜索出现验证的问题，使用google搜索my ip也是ipv6地址。
使用v2rayng时一开始以为可能是使用了app中的远程ipv4的dns而导致谷歌搜索是出现验证，但即使将app中的远程dns改成谷歌ipv6的dns也不行，依然会出现搜索验证。

### 复现方法
1.使用google搜索不能使用he.net的ipv6通道而出现搜索验证。
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android 10 任何网络都由此问题。

**Comment by yidit** [comment]
使用什么浏览器的，chrome的话关闭quic

**Comment by clk01** [comment]
> 使用什么浏览器的，chrome的话关闭quic

android上任何一个浏览器都有这个问题，chrome关闭quic也不行

**Comment by huangguiniab** [comment]
是否在app的设置里勾选了`ipv6优先`？我也在服务器上部署了he隧道，但是必须在app里勾选这个选项，否则无法访问ipv6的网站。
