### ISSUE TITLE
ipv6流量问题

### ISSUE THREAD

**Issue by xqdoo00o** [2dust/v2rayNG#1066]
### 预期行为
v2rayng走ipv6流量

### 实际行为
仍然走了ipv4

### 复现方法
1. 服务端 inbound 关闭sniffing，outbound为
```
"outbounds": [
    {
        "sendThrough": "::",
        "protocol": "freedom",
        "settings": {
            "domainStrategy": "UseIPv6"
        }
    }
]，
```
并关闭v2rayng的流量探测和ipv6优先选项。

2. whatismyipaddress.com 只检测到ipv4地址。

3. 打开任意一端的流量探测就显示出来双栈地址了。

### 环境信息
v2rayng 为1.6.2版本

### 额外信息
v2rayn(4.14版本)可以正常显示vps 双栈地址，也关闭了流量探测。

个人理解 流量探测跟outbound流量出口应该没啥关系吧，很难理解为啥会影响到ipv6，但是v2rayn又很正常

**Comment by yuhan6665** [comment]
n 和 ng 原理不一样，ng 在代理之前有一个 vpn 发出的 dns，关闭流量探测时代理地址将由这个 dns 决定，总之建议还是打开流量探测

**Comment by xqdoo00o** [comment]
主要是我这打开流量探测的话，偶尔看奈飞和直播的时候会卡顿 或者 奇怪的画面问题

**Comment by xqdoo00o** [comment]
> n 和 ng 原理不一样，ng 在代理之前有一个 vpn 发出的 dns，关闭流量探测时代理地址将由这个 dns 决定，总之建议还是打开流量探测

嗯，n是dns都交给vps解析了吧，我看用n的话 服务端日志是请求的域名。

用ng是先请求1.1.1.1:53 再请求到ip(v4)的连接，唯一例外是点测试连接会直接请求google.com域名。

开了流量探测的话，是先请求1.1.1.1:53 再请求到域名的连接，所以是从1.1.1.1解析的地址里反得到域名 然后发给服务端再解析吧

请问有木有可能直接 把域名发给服务端解析(不开启流量探测，并不请求1.1.1.1:53)，类似n那样。要不这样dns解析了两次感觉有些奇怪。

有木有可能 udp 53抓包 从报文中得到域名，一定要请求1.1.1.1的话。

**Comment by yuhan6665** [comment]
> > n 和 ng 原理不一样，ng 在代理之前有一个 vpn 发出的 dns，关闭流量探测时代理地址将由这个 dns 决定，总之建议还是打开流量探测
> 
> 嗯，n是dns都交给vps解析了吧，我看用n的话 服务端日志是请求的域名。
> 
> 用ng是先请求1.1.1.1:53 再请求到ip(v4)的连接，唯一例外是点测试连接会直接请求google.com域名。
> 
> 开了流量探测的话，是先请求1.1.1.1:53 再请求到域名的连接，所以是从1.1.1.1解析的地址里反得到域名 然后发给服务端再解析吧
> 
> 请问有木有可能直接 把域名发给服务端解析(不开启流量探测，并不请求1.1.1.1:53)，类似n那样。要不这样dns解析了两次感觉有些奇怪。
> 
> 有木有可能 udp 53抓包 从报文中得到域名，一定要请求1.1.1.1的话。

第一个 DNS 原理上不可省 你只能使用本地 DNS 导入 core 的方法处理它
你可以尝试在 DNS 模块直接解析出 IP v6 或者尝试 fakedns

**Comment by xqdoo00o** [comment]
嗯，好吧
