### ISSUE TITLE
开启v2rayN之后下载steam游戏时速度最高只能到20m/s

### ISSUE THREAD

**Issue by realkim1** [2dust/v2rayNG#1077]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
开启v2rayN之后不影响直连的速度,下载速度达到60m/s

### 实际行为
开启v2rayN之后下载steam游戏时速度最高只能到20m/s,
关闭之后下载速度能到最高60m/s.

### 复现方法
1.开启v2rayN启用高级路由,设置黑名单模式
2.下载steam游戏
3.下载速度只能达到20m/s

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by huangguiniab** [comment]
这里是V2rayNG，继续讨论请移步至 [V2rayN](https://github.com/2dust/v2rayN/issues)  讨论。
同时，为了防止指纹特征检测，v2ray会自动填充大量空数据至数据包，会占用1/2的流量，如果是用kcp，占用的流量会更多。比如说你裸连的时候能跑到60M，但是过了v2ray以后，空数据会占用40M，你的软件就只能跑到20M了，所以你这个现象应该是正常的

**Comment by realkim1** [comment]
好的，谢谢你的解答。(´｡✪ω✪｡｀)------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月1日(星期二) 晚上10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [2dust/v2rayNG] 开启v2rayN之后下载steam游戏时速度最高只能到20m/s (#1077)
