### ISSUE TITLE
After upgrade of 1.6.11 from google play I get Failed to detect internet connection

### ISSUE THREAD

**Issue by mactrash** [2dust/v2rayNG#1079]
io: read/write on close pipe

1.5.16 work well with same config? Why?

**Comment by CharlesLocke** [comment]
流控那里设置为空试试

**Comment by yuhan6665** [comment]
@mactrash 请附上配置和日志

**Comment by mactrash** [comment]
> 流控那里设置为空试试

flow tcp

沒有 空白 哦

@yuhan6665

alterid 64
security auto
Network tcp
header type none / http

--------- beginning of main
06-02 22:07:09.906 I/GoLog   (29263): tcp:127.0.0.1:48650 accepted tcp:149.154.175.55:443 [socks >> proxy]
06-02 22:07:09.945 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.128 I/GoLog   (29263): 127.0.0.1:44550 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:10.129 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.fdf8a3f9-1ab5-46c8-85ad-f2409e8372aa -> proxy]
06-02 22:07:10.153 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.372 I/GoLog   (29263): tcp:127.0.0.1:48660 accepted tcp:91.108.56.185:443 [socks >> proxy]
06-02 22:07:10.374 I/GoLog   (29263): tcp:127.0.0.1:48662 accepted tcp:91.108.56.197:443 [socks >> proxy]
06-02 22:07:10.390 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.391 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.623 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.fdf8a3f9-1ab5-46c8-85ad-f2409e8372aa -> proxy]
06-02 22:07:10.645 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:11.055 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.fdf8a3f9-1ab5-46c8-85ad-f2409e8372aa -> proxy]
06-02 22:07:11.086 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:12.039 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.fdf8a3f9-1ab5-46c8-85ad-f2409e8372aa -> proxy]
06-02 22:07:12.077 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:13.160 D/com.v2ray.ang(29263): tun2socks destroy
06-02 22:07:13.160 I/tun2socks(31209): NOTICE(tun2socks): termination requested
06-02 22:07:13.160 I/tun2socks(31209): NOTICE(tun2socks): tearing down
06-02 22:07:13.160 I/tun2socks(31209): NOTICE(tun2socks): Free TCP connections
06-02 22:07:13.169 I/tun2socks(31209): NOTICE(tun2socks): exiting
06-02 22:07:14.508 I/GoLog   (29263): loading core config
06-02 22:07:14.508 I/GoLog   (29263): Preparing Domain: freenet.ddnsfree.com:48011
06-02 22:07:14.509 I/GoLog   (29263): new core
06-02 22:07:14.509 I/GoLog   (29263): start core
06-02 22:07:14.510 I/GoLog   (29263): [Warning] core: Xray 1.4.2 started
06-02 22:07:14.510 I/GoLog   (29263): Prepare Result:
06-02 22:07:14.510 I/GoLog   (29263):  Domain: freenet.ddnsfree.com
06-02 22:07:14.510 I/GoLog   (29263):  Port: 48011
06-02 22:07:14.510 I/GoLog   (29263):  IPs: [17.255.255.255]
06-02 22:07:14.532 D/com.v2ray.ang(29263): [/data/app/com.v2ray.ang-k_046lihqjzbyGJW47CHAw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
06-02 22:07:14.534 D/com.v2ray.ang(29263): Process[pid=31923, hasExited=false]
06-02 22:07:14.534 D/com.v2ray.ang(29263): /data/user/0/com.v2ray.ang/files/sock_path
06-02 22:07:14.541 I/tun2socks(31923): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
06-02 22:07:14.585 D/com.v2ray.ang(29263): sendFd tries: 0
06-02 22:07:14.587 I/tun2socks(31923): NOTICE(tun2socks): entering event loop
06-02 22:07:14.657 I/GoLog   (29263): 127.0.0.1:42755 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:14.657 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:14.662 I/GoLog   (29263): tcp:127.0.0.1:48696 accepted tcp:117.48.116.227:443 [socks >> proxy]
06-02 22:07:14.676 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:14.680 I/GoLog   (29263): 127.0.0.1:39271 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:14.680 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:15.511 I/GoLog   (29263): tcp:127.0.0.1:48702 accepted tcp:117.48.116.227:443 [socks >> proxy]
06-02 22:07:15.541 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:15.574 I/GoLog   (29263): tcp:127.0.0.1:48706 accepted tcp:114.114.114.114:853 [socks >> proxy]
06-02 22:07:15.575 I/GoLog   (29263): tcp:127.0.0.1:48708 accepted tcp:26.26.26.2:853 [socks >> proxy]
06-02 22:07:15.591 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:15.592 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:16.082 I/GoLog   (29263): 127.0.0.1:38158 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:16.082 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:16.083 I/GoLog   (29263): 127.0.0.1:39065 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:16.117 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:17.106 I/GoLog   (29263): 127.0.0.1:39545 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:17.106 I/GoLog   (29263): 127.0.0.1:48349 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:17.107 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:17.141 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:18.064 I/GoLog   (29263): tcp:127.0.0.1:48720 accepted tcp:149.154.175.55:5222 [socks >> proxy]
06-02 22:07:18.102 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:18.592 I/GoLog   (29263): tcp:127.0.0.1:48730 accepted tcp:91.108.56.197:443 [socks >> proxy]
06-02 22:07:18.592 I/GoLog   (29263): tcp:127.0.0.1:48728 accepted tcp:91.108.56.185:5222 [socks >> proxy]
06-02 22:07:18.621 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:18.622 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.175 I/GoLog   (29263): 127.0.0.1:37461 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:19.176 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:19.214 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.665 I/GoLog   (29263): 127.0.0.1:42202 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:19.666 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:19.689 I/GoLog   (29263): 127.0.0.1:41631 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:19.707 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.820 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.842 D/com.v2ray.ang(29263): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe
06-02 22:07:20.693 I/GoLog   (29263): 127.0.0.1:42845 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
06-02 22:07:20.694 I/GoLog   (29263): DNS accepted udp:94.140.14.14:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:20.729 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:22.144 I/GoLog   (29263): tcp:127.0.0.1:48746 accepted tcp:149.154.175.55:5222 [socks >> proxy]
06-02 22:07:22.182 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:22.695 I/GoLog   (29263): tcp:127.0.0.1:48752 accepted tcp:91.108.56.185:443 [socks >> proxy]
06-02 22:07:22.696 I/GoLog   (29263): tcp:127.0.0.1:48756 accepted tcp:91.108.56.197:443 [socks >> proxy]
06-02 22:07:22.722 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:22.723 I/GoLog   (29263): Using Prepared: 17.255.255.255

**Comment by mactrash** [comment]
流控那里设置为空试试

flow tcp

沒有 空白 哦

@yuhan6665

alterid 64
security auto
Network tcp
header type none / http

--------- beginning of main
06-02 22:07:09.906 I/GoLog   (29263): tcp:127.0.0.1:48650 accepted tcp:149.154.175.55:443 [socks >> proxy]
06-02 22:07:09.945 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.128 I/GoLog   (29263): 127.0.0.1:44550 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:10.129 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:10.153 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.372 I/GoLog   (29263): tcp:127.0.0.1:48660 accepted tcp:91.108.56.185:443 [socks >> proxy]
06-02 22:07:10.374 I/GoLog   (29263): tcp:127.0.0.1:48662 accepted tcp:91.108.56.197:443 [socks >> proxy]
06-02 22:07:10.390 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.391 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:10.623 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:10.645 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:11.055 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:11.086 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:12.039 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:12.077 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:13.160 D/com.v2ray.ang(29263): tun2socks destroy
06-02 22:07:13.160 I/tun2socks(31209): NOTICE(tun2socks): termination requested
06-02 22:07:13.160 I/tun2socks(31209): NOTICE(tun2socks): tearing down
06-02 22:07:13.160 I/tun2socks(31209): NOTICE(tun2socks): Free TCP connections
06-02 22:07:13.169 I/tun2socks(31209): NOTICE(tun2socks): exiting
06-02 22:07:14.508 I/GoLog   (29263): loading core config
06-02 22:07:14.508 I/GoLog   (29263): Preparing Domain: freenet.ddnsfree.com:48011
06-02 22:07:14.509 I/GoLog   (29263): new core
06-02 22:07:14.509 I/GoLog   (29263): start core
06-02 22:07:14.510 I/GoLog   (29263): [Warning] core: Xray 1.4.2 started
06-02 22:07:14.510 I/GoLog   (29263): Prepare Result:
06-02 22:07:14.510 I/GoLog   (29263):  Domain: freenet.ddnsfree.com
06-02 22:07:14.510 I/GoLog   (29263):  Port: 48011
06-02 22:07:14.510 I/GoLog   (29263):  IPs: [17.255.255.255]
06-02 22:07:14.532 D/com.v2ray.ang(29263): [/data/app/com.v2ray.ang-k_046lihqjzbyGJW47CHAw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
06-02 22:07:14.534 D/com.v2ray.ang(29263): Process[pid=31923, hasExited=false]
06-02 22:07:14.534 D/com.v2ray.ang(29263): /data/user/0/com.v2ray.ang/files/sock_path
06-02 22:07:14.541 I/tun2socks(31923): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
06-02 22:07:14.585 D/com.v2ray.ang(29263): sendFd tries: 0
06-02 22:07:14.587 I/tun2socks(31923): NOTICE(tun2socks): entering event loop
06-02 22:07:14.657 I/GoLog   (29263): 127.0.0.1:42755 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:14.657 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:14.662 I/GoLog   (29263): tcp:127.0.0.1:48696 accepted tcp:117.48.116.227:443 [socks >> proxy]
06-02 22:07:14.676 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:14.680 I/GoLog   (29263): 127.0.0.1:39271 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:14.680 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:15.511 I/GoLog   (29263): tcp:127.0.0.1:48702 accepted tcp:117.48.116.227:443 [socks >> proxy]
06-02 22:07:15.541 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:15.574 I/GoLog   (29263): tcp:127.0.0.1:48706 accepted tcp:114.114.114.114:853 [socks >> proxy]
06-02 22:07:15.575 I/GoLog   (29263): tcp:127.0.0.1:48708 accepted tcp:26.26.26.2:853 [socks >> proxy]
06-02 22:07:15.591 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:15.592 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:16.082 I/GoLog   (29263): 127.0.0.1:38158 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:16.082 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:16.083 I/GoLog   (29263): 127.0.0.1:39065 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:16.117 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:17.106 I/GoLog   (29263): 127.0.0.1:39545 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:17.106 I/GoLog   (29263): 127.0.0.1:48349 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:17.107 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:17.141 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:18.064 I/GoLog   (29263): tcp:127.0.0.1:48720 accepted tcp:149.154.175.55:5222 [socks >> proxy]
06-02 22:07:18.102 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:18.592 I/GoLog   (29263): tcp:127.0.0.1:48730 accepted tcp:91.108.56.197:443 [socks >> proxy]
06-02 22:07:18.592 I/GoLog   (29263): tcp:127.0.0.1:48728 accepted tcp:91.108.56.185:5222 [socks >> proxy]
06-02 22:07:18.621 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:18.622 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.175 I/GoLog   (29263): 127.0.0.1:37461 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:19.176 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:19.214 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.665 I/GoLog   (29263): 127.0.0.1:42202 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:19.666 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:19.689 I/GoLog   (29263): 127.0.0.1:41631 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:19.707 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.820 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:19.842 D/com.v2ray.ang(29263): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe
06-02 22:07:20.693 I/GoLog   (29263): 127.0.0.1:42845 accepted udp:17.253.144.10:53 [dns-in -> dns-out]
06-02 22:07:20.694 I/GoLog   (29263): DNS accepted udp:17.253.144.10:53 [xray.system.00000000-0000-0000-0000-000000000 -> proxy]
06-02 22:07:20.729 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:22.144 I/GoLog   (29263): tcp:127.0.0.1:48746 accepted tcp:149.154.175.55:5222 [socks >> proxy]
06-02 22:07:22.182 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:22.695 I/GoLog   (29263): tcp:127.0.0.1:48752 accepted tcp:91.108.56.185:443 [socks >> proxy]
06-02 22:07:22.696 I/GoLog   (29263): tcp:127.0.0.1:48756 accepted tcp:91.108.56.197:443 [socks >> proxy]
06-02 22:07:22.722 I/GoLog   (29263): Using Prepared: 17.255.255.255
06-02 22:07:22.723 I/GoLog   (29263): Using Prepared: 17.255.255.255

**Comment by yuhan6665** [comment]
看不出问题，能否看一下导出的完整配置（服务器和敏感信息打码）
如果可能，使用1.5.x 再导一份配置

**Comment by libea18** [comment]
i have same issue
I think this goes back to sni and request host in tcp/http
