### ISSUE TITLE
After updating to the latest version, v2rayng cannot be connected and v2rayn is normal

### ISSUE THREAD

**Issue by Hojokerzhang** [2dust/v2rayNG#1081]
After updating to the latest version, v2rayng cannot be connected and v2rayn is normal

**Comment by cairenbin** [comment]
我也有一样的问题，不管是http伪装的还是ws的都不行了。。。

**Comment by yuhan6665** [comment]
能否看一下导出的完整配置（服务器和敏感信息打码）
如果可能，使用1.5.x 再导一份配置

**Comment by mactrash** [comment]
@yuhan6665 

{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "94.140.14.14"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "94.140.14.14",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "none"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "111.111.111.111",
            "port": 111,
            "users": [
              {
                "alterId": 64,
                "id": "0000000-00000-000000-000000",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "",
        "tcpSettings": {
          "header": {
            "request": {
              "version": "1.1",
              "method": "GET",
              "path": [
                "/"
              ],
              "headers": {
                "User-Agent": [
                  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36",
                  "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                ],
                "Accept-Encoding": [
                  "gzip, deflate"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache",
                "Host": [
                  "apple.com"
                ]
              }
            },
            "type": "http"
          }
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "94.140.14.14"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "94.140.14.14"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      }
    ]
  }
}

**Comment by cairenbin** [comment]
> 能否看一下导出的完整配置（服务器和敏感信息打码）
> 如果可能，使用1.5.x 再导一份配置

我试了一下，重建了服务器Profile之后高版本的WS节点可以用了，去年构筑的HTTP的还是不行，应该是不能直接使用原来的节点profile导致的，大家如果碰到这样的问题可以考虑用高版本重构服务器后重新在NG里添加节点来解决

**Comment by 2dust** [comment]
试一试新版
https://github.com/2dust/v2rayNG/releases/tag/1.6.12

**Comment by mactrash** [comment]
@2dust it work normally

**Comment by xzchsia** [comment]
我的更新到了最新的版本，也是类似的问题，trojan协议即vmess和vless的ws tls模式不能访问，但是vmess的tcp模式，直接用ip访问是正常的。。之前一直以为是我的vps配置问题，还重建过。pc版本的V2rayN是正常的。
域名是freenom申请，cloudflare解析。

**Comment by xzchsia** [comment]
好像要把最底下的跳过证书 allowInsecure手动设置为true可以解决问题
