### ISSUE TITLE
SSPANEL-UIM面板 v2ray 更新订阅失败

### ISSUE THREAD

**Issue by jelly0925** [2dust/v2rayNG#1083]
### 预期行为
节点类型v2ray手机在更新订阅的时候手机更新订阅应该成功
### 实际行为
安卓11版本，目前手机使用的v2rayng 版本是1.6.11，节点类型v2ray目前更新订阅提示失败
### 复现方法
1.试着降级v2rayng版本也是一样的情况。希望帮忙分析一下原因，谢谢
### 日志信息
--------- beginning of main
06-03 22:28:50.880 E/com.v2ray.ang(12614): Invalid ID 0x00000000.
06-03 22:28:50.880 E/com.v2ray.ang(12614): Invalid ID 0x00000000.
06-03 22:28:52.323 E/com.v2ray.ang(12614): Invalid ID 0x00000000.
--------- beginning of system
06-03 22:28:52.333 E/com.v2ray.ang(12614): Invalid ID 0x00000000.
06-03 22:28:58.115 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.115 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.115 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.115 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.115 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.115 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.115 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.115 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.115 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.115 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.115 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.115 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.115 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.115 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.115 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-03 22:28:58.116 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.116 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.116 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.116 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.116 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.116 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.116 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.116 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.116 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.116 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.117 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.117 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.117 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.117 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.117 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-03 22:28:58.118 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.118 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.118 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.118 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.118 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.118 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.118 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.118 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.118 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.118 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.118 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.118 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.118 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.118 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.118 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-03 22:28:58.119 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.119 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.119 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.119 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.119 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.119 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.119 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.119 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.119 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.119 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.119 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.119 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.119 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.119 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.119 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-03 22:28:58.120 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.120 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.120 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.120 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.120 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.120 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.120 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.120 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.120 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.120 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.120 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.120 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.120 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.120 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.120 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-03 22:28:58.121 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.121 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.121 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.121 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.121 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.122 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.122 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.122 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.122 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.122 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.122 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.122 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.122 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.122 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.122 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-03 22:28:58.123 W/System.err(12614): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$isBlank
06-03 22:28:58.123 W/System.err(12614): 	at kotlin.text.StringsKt__StringsJVMKt.isBlank(Unknown Source:2)
06-03 22:28:58.123 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:215)
06-03 22:28:58.123 W/System.err(12614): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:682)
06-03 22:28:58.123 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:378)
06-03 22:28:58.123 W/System.err(12614): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$$inlined$forEach$lambda$1$1.invokeSuspend(MainActivity.kt:489)
06-03 22:28:58.123 W/System.err(12614): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 22:28:58.123 W/System.err(12614): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 22:28:58.123 W/System.err(12614): 	at android.os.Handler.handleCallback(Handler.java:938)
06-03 22:28:58.123 W/System.err(12614): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 22:28:58.123 W/System.err(12614): 	at android.os.Looper.loop(Looper.java:233)
06-03 22:28:58.123 W/System.err(12614): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
06-03 22:28:58.123 W/System.err(12614): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 22:28:58.123 W/System.err(12614): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-03 22:28:58.123 W/System.err(12614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

### 环境信息
一加7 pro安卓11版本系统

**Comment by RManLuo** [comment]
同样出现该问题，怀疑是出现了某些新增的配置字段，导致V2rayNG无法解析配置文件。

**Comment by yuhan6665** [comment]
感谢反馈 应该是分享没有 sni 的原因 修复了 https://github.com/2dust/v2rayNG/pull/1088
