### ISSUE TITLE
打开v2rayNG时自动更新订阅

### ISSUE THREAD

**Issue by kia678** [2dust/v2rayNG#1084]
Is your feature request related to a problem? Please describe.
由于本人使用的订阅经常有变动导致经常需要手动更新订阅，不太方便，希望可以增加：默认自动更新订阅功能（每次打开v2rayNG时）

Describe the solution you'd like
打开v2rayNG时自动更新订阅

Describe alternatives you've considered
暂无

Additional context
暂无

**Comment by viagram** [comment]
我也有同需求，如果可以，建议增加一下定时自动更新订阅。谢谢！
