### ISSUE TITLE
v2rayng 1.6.12版本配置文件 path 例如/api/aall 实际抓包就只有/

### ISSUE THREAD

**Issue by yixuan-Q** [2dust/v2rayNG#1085]
v2rayng 1.6.12版本 配置文件 path 例如/api/aall 实际抓包就只有/
![IMG_20210605_031940](https://user-images.githubusercontent.com/61373853/120852575-f4615b80-c5ac-11eb-911d-4f5cd6e8ef65.jpg)

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/issues/1086#issuecomment-855412533
