### ISSUE TITLE
v2flyNG failed to connect after updating to 1.6.12 v2flyNG 在升级 1.6.12 后已有配置无法连接

### ISSUE THREAD

**Issue by lalcd** [2dust/v2rayNG#1086]
After updating to the latest（>1.6）, the previously used config failed to connect.

**Below is the Config that works in < 1.6.**

<details>

{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8",
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ],
        "port": 53
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "REPLACEMENT",
            "port": REPLACEMENT,
            "users": [
              {
                "alterId": REPLACEMENT,
                "id": "REPLACEMENT",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "httpSettings": {
          "host": [],
          "path": "REPLACEMENT"
        },
        "network": "h2",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "serverName": ""
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

</details>

**Comment by lucifersun** [comment]
遇到同样问题，更新后原有配置文件无法连接。

**Comment by lalcd** [comment]
> 遇到同样问题，更新后原有配置文件无法连接。

你使用的 H2 吗？

**Comment by yixuan-Q** [comment]
> > 遇到同样问题，更新后原有配置文件无法连接。
> 
> 你用的H2吗？

tcp http
v2rayng 导出的完整配置 path路径 和 写的路径不一样
![IMG_20210606_090201](https://user-images.githubusercontent.com/61373853/120909259-dfb4be80-c6a5-11eb-9c7a-2a9be00e70f9.jpg)
![IMG_20210605_031940](https://user-images.githubusercontent.com/61373853/120909849-04ac3000-c6ac-11eb-967b-b17652e80879.jpg)

**Comment by lalcd** [comment]
> > > 遇到同样问题，更新后原有配置文件无法连接。
> > 
> > 
> > 你用的H2吗？
> 
> tcp http
> v2rayng 导出的完整配置 path路径 和 写的路径不一样
> ![IMG_20210606_090201](https://user-images.githubusercontent.com/61373853/120909259-dfb4be80-c6a5-11eb-9c7a-2a9be00e70f9.jpg)
> ![IMG_20210605_031940](https://user-images.githubusercontent.com/61373853/120909849-04ac3000-c6ac-11eb-967b-b17652e80879.jpg)

我使用的 H2，导出的配置的 path 路径和写得一样。目前使用自定义的 Config 能正常用，应该是 1.6.x 后 Config 部分的变更导致的。

**Comment by yixuan-Q** [comment]
> > > > 遇到同样问题，更新后原有配置文件无法连接。
> > > 
> > > 
> > > 你用的H2吗？
> > 
> > 
> > tcp http 
> > v2rayng 导出的完整配置路径路径和写的路径不一样
> > ![IMG_20210606_090201](https://user-images.githubusercontent.com/61373853/120909259-dfb4be80-c6a5-11eb-9c7a-2a9be00e70f9.jpg)
> > ![IMG_20210605_031940](https://user-images.githubusercontent.com/61373853/120909849-04ac3000-c6ac-11eb-967b-b17652e80879.jpg)
> 
> 我使用的H2，导出的配置的路径路径和写得一样。目前使用自定义的配置可以正常使用，应该是1.6.x后配置部分的更改导致的。

我在paht配置/api/all 抓包显示 /
![IMG_20210606_161954](https://user-images.githubusercontent.com/61373853/120917707-3b516d00-c6e3-11eb-95bf-f8bbece08526.jpg)

![IMG_20210606_161935](https://user-images.githubusercontent.com/61373853/120917692-2aa0f700-c6e3-11eb-8533-c95ff3f40049.jpg)

**Comment by lucifersun** [comment]
> 
> 
> > 遇到同样问题，更新后原有配置文件无法连接。
> 
> 你使用的 H2 吗？

是的，用的是H2。尝试在两侧的配置文件里，把path改成"/"，也不起作用。

**Comment by yuhan6665** [comment]
目前 http 伪装改成了 path 固定为 / 需要其他 path 可以暂时使用自定义配置

**Comment by lalcd** [comment]
> 目前 http 伪装改成了 path 固定为 / 需要其他 path 可以暂时使用自定义配置

可以确认，自定义配制目前可以正常使用。谢谢。

**Comment by lucifersun** [comment]
> 
> 
> 目前 http 伪装改成了 path 固定为 / 需要其他 path 可以暂时使用自定义配置

自定义配置实测正常，谢谢。

**Comment by lalcd** [comment]
Issue still exists in V1.6.13 of v2flyNG.

**Comment by lalcd** [comment]
@2dust @yuhan6665 这个问题目前还是存在于最新的更新。

**Comment by lalcd** [comment]
问题依旧。Vmess 导入后不能使用，再使用已经导入的 Vmess 导出全量配置，会出现https://github.com/2dust/v2rayNG/issues/1121#issuecomment-870388449 的问题。辛苦查看 @yuhan6665
