### ISSUE TITLE
可否增加一个自动更新Geo资源文件的选项

### ISSUE THREAD

**Issue by Kukuair** [2dust/v2rayNG#1087]
电脑版的V2rayN已经支持在客户端内更新Geo文件了，手机版的仍然不支持，而且从谷歌商店下载下来的V2rayNG中的初始版本的Geo资源文件太旧了，其中一个只有几百k,大多数用户可能都会忽略更新，导致启动代理时出现某些错误代理的问题，如果从手机浏览器下载的话，还得进V2rayNG手动更换，尤其是手机的文件管理目录太不方便寻找了，希望可以增加自动更新选项

**Comment by iseeyo** [comment]
同问，app更新了数个版本，geo资源文件还是去年的，能否同步更新geo文件或者让用户手动更新呢？最新版app找不到geo文件路径，没法直接替换。

**Comment by sunlewuyou** [comment]
手机没root可以替换？
