### ISSUE TITLE
[Enhancement] Publish the app on F-Droid

### ISSUE THREAD

**Issue by oksjd** [2dust/v2rayNG#109]
The app itself is excellent, however it would be even nicer to have this app on F-Droid, a FOSS app store. By this way, more Android users can download the app easily.

**Comment by 2dust** [comment]
sorry
No time to do this thing

**Comment by dimqua** [comment]
@2dust what if someone else will add it? Are you OK with it?

**Comment by xmha97** [comment]
> sorry
> No time to do this thing

Why? Google Play Store is blocked in my country.
I want to install this app from F-Droid.

**Comment by Korb** [comment]
The app is still missing from F-Droid:

![Screenshot_2024_1102_184732_org fdroid fdroid](https://github.com/user-attachments/assets/b9ba3578-20d1-4dd1-a7ba-58332981ab62)

> (No matching applications available.)

> Why? Google Play Store is blocked in my country. I want to install this app from F-Droid.

You always have [a workaround](https://github.com/2dust/v2rayNG/releases) 😉

**Comment by muelli** [comment]
> You always have [a workaround](https://github.com/2dust/v2rayNG/releases) 😉

but f-droid takes care of updates. And it makes it more difficult to sneak proprietary components into the app.

**Comment by Korb** [comment]
> it makes it more difficult to sneak proprietary components into the app.

Publishing on F-Droid does not make it difficult to embed unwanted (for FOSS cult users) entities, but it does make the presence of these entities in the installed applications obvious. This is a tool of openness and transparency that is missing from the method of distributing APK packages by third-party sites, even if it is Github.

**Comment by ghost** [comment]
hello from 2026. https://github.com/2dust/v2rayNG/issues/5334
