### ISSUE TITLE
v2rayng可以做一个测速排行吗，

### ISSUE THREAD

**Issue by chenlie449** [2dust/v2rayNG#1094]
节点测速完了
每次找最快的节点都要好久

### 预期行为
做好这个测速就很完美了，用户会非常喜欢

### 实际行为
很难找到最快的节点

### 复现方法
我不懂写代码，是小白希望版主改进做出速度排行榜来谢谢

**Comment by Sumire-Heanna** [comment]
好家伙，国际出口带宽全给你们拿去测速了

**Comment by pansila** [comment]
其实测下延迟也行
