### ISSUE TITLE
安卓模拟器问题

### ISSUE THREAD

**Issue by zqs125** [2dust/v2rayNG#1096]
请问下是不支持安卓模拟器吗？在电脑上试了好多个安卓模拟器，只要启用v2rayNG就没有网，可在软件下面的测试延时又是正常的，是我的问题还是不支持模拟器？

**Comment by yuhan6665** [comment]
发一下日志吧 （敏感信息打码）

**Comment by zqs125** [comment]
日志里报异常错误：
06-15 22:55:18.649 I/GoLog   ( 3907): new core
06-15 22:55:18.661 I/GoLog   ( 3907): start core
06-15 22:55:18.669 I/GoLog   ( 3907): [Warning] core: Xray 1.4.2 started
06-15 22:55:18.683 D/com.v2ray.ang( 3907): [/data/app/com.v2ray.ang-1/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
06-15 22:55:18.687 D/com.v2ray.ang( 3907): java.io.IOException: Cannot run program "/data/app/com.v2ray.ang-1/lib/arm64/libtun2socks.so" (in directory "/data/user/0/com.v2ray.ang/files"): error=13, Permission denied
app的存储权限是开通的

**Comment by yuhan6665** [comment]
/data/app/com.v2ray.ang-1/lib/**arm64**
你这个 arm64 有点奇怪 一般模拟器不是 arm 架构吧。你用的啥模拟器，能用 google 的试一下吗

**Comment by zqs125** [comment]
我试了逍遥模拟器和夜神模拟器都是一样的错误，安卓版本是7.1 64位

**Comment by Nanosk07** [comment]
> 我试了逍遥模拟器和夜神模拟器都是一样的错误，安卓版本是7.1 64位

我把手机上用的apk直接给模拟器也是这个问题，但是模拟器上从google商店直接下就没这个问题，估计是不同架构版本问题，换个版本试试。

https://github.com/2dust/v2rayNG/releases/

**Comment by chrsas** [comment]
搞定了，原来是要用 x86 版本的。
