### ISSUE TITLE
失败：io:read/write on closed pipe 

### ISSUE THREAD

**Issue by fangyong125** [2dust/v2rayNG#1099]
服务器没问题，Linux、Windows客户端均运行正常

### 预期行为
Android不跳过证书验证的情况下，可以正常使用

### 实际行为
Android跳过证书验证时可以正常使用，不跳过证书验证时，出现异常失败：io:read/write on closed pipe 

### 复现方法
1.设备：荣耀V20
2.打开跳过证书验证，一切OK
3.关闭证书验证，出现异常

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
D:\tmp\v2>adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main
* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
--------- beginning of system
--------- beginning of main
06-17 09:37:35.146 25567 26406 I GoLog   : Using Prepared: 18.166.xxx.xxx
06-17 09:37:35.178 25567 26418 D com.v2ray.ang: measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe
06-17 09:37:37.811 25567 25567 D com.v2ray.ang: SCREEN_OFF, stop querying stats
06-17 09:39:27.054 25567 25567 D com.v2ray.ang: SCREEN_ON, start querying stats
06-17 09:39:37.616 26299 26299 I com.v2ray.ang: Settings ViewModel is cleared
06-17 09:39:49.777 25567 26406 I GoLog   : Using Prepared: 18.166.xxx.xxx
06-17 09:39:49.813 25567 26418 D com.v2ray.ang: measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe
06-17 09:39:58.798 25567 25567 D com.v2ray.ang: SCREEN_OFF, stop querying stats
```
</details>

### 环境信息
荣耀V20
### 额外信息（可选）
域名是阿里云的免费域名，HTTPS站点可以正常访问，无证书异常的

**Comment by fangyong125** [comment]
已确认两边时间一致，时区也是一致的
Android 版本：10
Magic UI 版本：4.0.0
ss服务器：trojan

**Comment by fangyong125** [comment]
Android 版本：10
Magic UI 版本：4.0.0

**Comment by fangyong125** [comment]
服务器是trojan

**Comment by ghost** [comment]
我也是同样情况 用了VLESS协议 同样 io:read/write on closed pipe 
Android 下面

**Comment by lbbboy** [comment]
推荐你用 clash。没这烦恼。

**Comment by ghost** [comment]
> 推荐你用 clash。没这烦恼。

找不到clash这款应用，一搜clash就弹出很多游戏，在米国区哦

**Comment by lbbboy** [comment]
> > 推荐你用 clash。没这烦恼。
> 
> 找不到clash这款应用，一搜clash就弹出很多游戏，在米国区哦

clash for android 第二个就是啊  google play

**Comment by ghost** [comment]
> > > 推荐你用 clash。没这烦恼。
> > 
> > 
> > 找不到clash这款应用，一搜clash就弹出很多游戏，在米国区哦
> 
> clash for android 第二个就是啊 google play

IOS用什么？谢谢

**Comment by ghost** [comment]
> > > 推荐你用 clash。没这烦恼。
> > 
> > 
> > 找不到clash这款应用，一搜clash就弹出很多游戏，在米国区哦
> 
> clash for android 第二个就是啊 google play

https://github.com/Dreamacro/clash/issues/1455
不支持vless的

**Comment by baicaisir** [comment]
请问这个问题有解决的吗，突然就不好使了，之前还是好好的
