### ISSUE TITLE
Shadowsocks DNS 异常

### ISSUE THREAD

**Issue by dstsmallbird** [2dust/v2rayNG#110]
Shadowsocks DNS 异常

### 预期行为

在 1.1.1 版本中，建立 SS 连接正常，但是 SS 的 DNS 工作异常

### 实际行为

SS 模式无法正常完成 DNS 解析，其它 SS APP 均无异常

### 复现方法
1. 添加 SS
2. 建立连接
3. 访问任意无 DNS 缓存网站

**Comment by dstsmallbird** [comment]
存在于全局模式，猜测可能是没有走 v2ray 的路由导致迷路了。

**Comment by 2dust** [comment]
合并了,应该是一个问题
