### ISSUE TITLE
连接4秒后就连接不上

### ISSUE THREAD

**Issue by atm16888** [2dust/v2rayNG#1100]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
应该能正常连接，而不是连接4秒后就断开了。
### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yat-hhh** [comment]
华为手机如果不允许程序“后台运行”的话，切换到其他app时，就会立即断开连接。。

**Comment by atm16888** [comment]
你认为我这点常识都不懂么？
没切换没切换没切换重要的事情说三遍。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月26日(周六) 晚上11:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [2dust/v2rayNG] 连接4秒后就连接不上 (#1100)




 
华为手机如果不允许程序“后台运行”的话，切换到其他app时，就会立即断开连接。。

**Comment by yat-hhh** [comment]
没有，没有。
是我没有常识
不是这个问题，你就忽略我的发言吧。。
