### ISSUE TITLE
Vless 协议不行 read/write on closed pipe

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1105]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

用了Google play最新版本也不行
Vless 
xtls-rprx-direct
tcp传输

### 实际行为
read/write on closed pipe

### 复现方法
1.重启
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by netcccyun** [comment]
我也是出现这种情况，一开始可以，后来就连不上了，相同客户端网络下无法再连当前服务器IP，重新拨号又恢复。但是电脑版一直都正常

**Comment by ghost** [comment]
> 我也是出现这种情况，一开始可以，后来就连不上了，相同客户端网络下无法再连当前服务器IP，重新拨号又恢复。但是电脑版一直都正常

我开始也不可以，我没有成功连上过

**Comment by yanwh0311** [comment]
是不是xray开始不兼容v2ray了。
我也出现这种情况
linux v2ray正常，clash也正常，这两个都是用v2ray-core的。但v2rayng应该是用xray的。

**Comment by ghost** [comment]
> 是不是xray开始不兼容v2ray了。
> 我也出现这种情况
> linux v2ray正常，clash也正常，这两个都是用v2ray-core的。但v2rayng应该是用xray的。


原来这样啊，我试试换一个服务试试，谢谢

**Comment by ghost** [comment]
> 是不是xray开始不兼容v2ray了。
> 我也出现这种情况
> linux v2ray正常，clash也正常，这两个都是用v2ray-core的。但v2rayng应该是用xray的。

找不到这款应用，一搜clash就弹出很多游戏，我在米国区搜哦

**Comment by ghost** [comment]
> 是不是xray开始不兼容v2ray了。
> 我也出现这种情况
> linux v2ray正常，clash也正常，这两个都是用v2ray-core的。但v2rayng应该是用xray的。

我试过 teddysun , gist v2ray ,也是v2ray-core 都不行

**Comment by ghost** [comment]
我说的是服务端哈

**Comment by yanwh0311** [comment]
> 我说的是服务端哈

clash for android 
在github上有

**Comment by micro-stone** [comment]
> > 我说的是服务端哈
> 
> clash for android
> 在github上有

clash 支持vless了吗？

**Comment by agooday** [comment]
我的设置跳过证书验证就正常

**Comment by SyzenEinca** [comment]
> 是不是xray开始不兼容v2ray了。
> 我也出现这种情况
> linux v2ray正常，clash也正常，这两个都是用v2ray-core的。但v2rayng应该是用xray的。

的确如此，我只有V2fly-core的v2rayN能够连接到V2ray-core的服务端
切换v2rayN到Xray-core就也不行了，明天我服务端换成Xray看看吧

**Comment by JxiaoC** [comment]
我也遇到了...以前一直正常使用, 昨天恢复了出厂设置,忘了备份之前的apk, 重新在谷歌应用市场下载的, 就这样了...服务器一直没动过
