### ISSUE TITLE
为什么用一段时间，手机上的钥匙图标会不见了，然后就上不了网。访问不了谷歌

### ISSUE THREAD

**Issue by chenlie449** [2dust/v2rayNG#1106]
vpn钥匙图标会不见了，访问不了谷歌

**Comment by xiaofage001** [comment]
The process was  killed.

**Comment by zazitufu** [comment]
1、手机应用被杀后台了
2、你开启了其他使用VPN的app，手机好像现在都只支持单个vpn链接。开了一个使用VPN的，前一个VPN就会被顶掉。为什么我会知道呢，因为我前段时间买了个联想个人云，它的APP是使用VPN的。我每次开个人云就会把v2rayNG顶掉。或者你可以使用“仅代理”的模式，在需要翻墙的APP里面设置代理。
