### ISSUE TITLE
同一个节点，电脑端可用，V2RayNG手机端不可使用？连接瞬间断开，小钥匙还在！

### ISSUE THREAD

**Issue by ShereFrank** [2dust/v2rayNG#1107]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常使用节点

### 实际行为
连接瞬间断开，小钥匙还在！电报、Google等无法手机访问

**Comment by lbbboy** [comment]
用clash吧，这个app我不能用好几个月了。

**Comment by szwuzy** [comment]
用了同一个WIFI。手机v2rayng连接同一站点可用，二堆码分享，配置一样在手机上连接测试正常，但无法打开youtube和google等。

**Comment by sdshdv** [comment]
你看下电脑端是不是用了v2ray内核，v2rayng现在强制改成xray内核了，内核不同所以电脑能用手机不能用

**Comment by genghis-yang** [comment]
I've got the same issue. Could access from PC but not from android.
But a few days later, the PC cannot access either. I found that the HTTPS requests didn't get any responses. So I guess the provider block my IP address.
After I changed my IP address, all works well.

So, I suggest first check if you can connect to your IP from your phone: E.g. `curl -vi https://<your-domain>/`
Termux is a wonderful tool to do the test on android phone.

**Comment by Nicecsh** [comment]
> 用clash吧，这个app我不能用好几个月了。

clash确实好用，只需要配置好线路后，youtube、google map等几个软件直接傻瓜式翻墙成功！

**Comment by bulidoge** [comment]
看这个.....我解决了 如果是华为的话很可能是这样 被后台自动清理了https://blog.csdn.net/sxf1061700625/article/details/127476100

**Comment by hkiceflow** [comment]
> 看这个.....我解决了 如果是华为的话很可能是这样 被后台自动清理了https://blog.csdn.net/sxf1061700625/article/details/127476100

it's amazing bro.
打开自启动真的就好了，之前只有一个节点能用，别的在手机端都用不了。打开自启动就好了。what's is it smoking?
ty bro
