### ISSUE TITLE
华为鸿蒙系统路由设置在哪？想用 绕过局域网和大陆 模式

### ISSUE THREAD

**Issue by Tobylive** [2dust/v2rayNG#1108]
华为鸿蒙系统安装v2rayng，在设置里找不到 路由设置 这一选项了，怎样可以使用 绕过局域网和大陆？谢谢！

**Comment by Gayhub-okr** [comment]
HMOS 116，设置-路由设置-预定义规则

**Comment by jackhuo2** [comment]
用鸿蒙扶墙，简直就是自投罗网，分分钟请你喝茶。
