### ISSUE TITLE
设置中的Mux开关不显示

### ISSUE THREAD

**Issue by Sherman-Liu** [2dust/v2rayNG#111]
### 预期行为
设置中显示MUX开关

### 实际行为
设置中并未显示MUX开关

### 复现方法
打开设置菜单

请问开发者，是Mux开关挪位置了吗，还是这个功能被取消了呢？

这个功能在部分场景下其实还蛮实用的，现在不得不用手动文件配置来开启Mux，很麻烦。

![Screenshot_20190924-043831_v2rayNG](https://user-images.githubusercontent.com/11748513/65460861-6c452c00-de85-11e9-8c66-b0430ecd7515.png)

**Comment by 2dust** [comment]
移动端最好关闭mux,所以没有开放

**Comment by Tynba** [comment]
> 移动端最好关闭mux,所以没有开放

😭为什么啊？

**Comment by xkgg** [comment]
？？我也是醉了

TciBan <notifications@github.com> 于 2020年9月14日周一 17:28写道：
