### ISSUE TITLE
我怀疑程序偷上传节点信息

### ISSUE THREAD

**Issue by ljodan** [2dust/v2rayNG#1112]
如题，我所有上传更新过的节点用不了几天，甚至隔天立马就不能用了

**Comment by zazitufu** [comment]
额，我怀疑：
1、你用的是免费的别人共享节点，被人取笑共享了
2、你用的是裸奔的协议，用一下就被gfw识别了

**Comment by slipdaly** [comment]
开源的，去代码里找证据说事，我们要用事实说话

**Comment by Alphabet1226** [comment]
> 开源的，去代码里找证据说事，我们要用事实说话

虽然但是，该项目其实早就闭源了……只有1.0.2版本是开源的
https://github.com/2dust/v2rayNG/blob/50d9057f1ad304ef9ef333fe80c44723e2619328/V2rayNG/app/build.gradle#L20
