### ISSUE TITLE
错误日志反馈

### ISSUE THREAD

**Issue by bike3097a** [2dust/v2rayNG#1114]
--------- beginning of main
06-25 22:48:02.061 E/tun2socks(18250): ERROR(BDatagram): recv failed
06-25 22:48:02.064 E/tun2socks(18250): ERROR(BDatagram): recv failed
06-25 22:48:49.063 E/tun2socks(19640): ERROR(BDatagram): recv failed
06-25 22:48:49.063 E/tun2socks(19640): ERROR(BDatagram): recv failed
06-25 22:57:48.457 E/com.v2ray.ang(22056): LoadAppImageStartupCache enabled : 1
06-25 22:57:48.458 E/com.v2ray.ang(22056): Not starting debugger since process cannot load the jdwp agent.
06-25 22:58:29.021 E/tun2socks(22156): ERROR(BDatagram): recv failed
06-25 22:58:29.021 E/tun2socks(22156): ERROR(BDatagram): recv failed
06-25 22:59:09.678 E/tun2socks(22804): ERROR(BDatagram): recv failed
06-25 22:59:09.679 E/tun2socks(22804): ERROR(BDatagram): recv failed
06-25 22:59:35.749 E/tun2socks(23102): ERROR(BDatagram): recv failed
06-25 22:59:35.750 E/tun2socks(23102): ERROR(BDatagram): recv failed

**Comment by habbyCP** [comment]
解决了吗

**Comment by jiehuo666** [comment]
解决了吗

**Comment by wxh06** [comment]
检查操作系统设置项“应用启动管理”中是否将 v2rayNG 设置为“自动管理”。“手动管理”时确实会 `ERROR(BDatagram): recv failed`
