### ISSUE TITLE
请问如何自定义规则？Trojan-gRPC自定义配置模板

### ISSUE THREAD

**Issue by onlyJinx** [2dust/v2rayNG#1118]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

我想使用Trojan-gRPC

### 实际行为
描述实际发生了什么

目前core已经支持trojan-gcp，但是v2rayNG UI里好像没有相关的添加方式，所以只能通过自定义配置的方式来使用，但是没找到模板，自己改写VLESS+gRPC的client.json可以在电脑使用cmd命令xray.exe -c client.json正常使用，但是手机上我就不会了，想像大火讨要个模板，哈哈。。。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
手动输入vless -> 导出完整配置 -> 导入自定义配置

**Comment by onlyJinx** [comment]
> 手动输入vless -> 导出完整配置 -> 导入自定义配置

卧槽，我忘记还能这么玩，已经解决了，谢谢。顺便把配置文件贴在下面给可能需要的人


{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "protocol": "trojan",
      "settings": {
          "servers": [
              {
                  "address": "",  //服务器地址
                  "port": 443,
                  "password": ""  //密码
              }
          ]
      },
      "streamSettings": {
          "network": "grpc",
          "security": "tls",
          "grpcSettings": {
              "serviceName": ""	 //你的serviceName
          }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
