### ISSUE TITLE
connection DrainSize

### ISSUE THREAD

**Issue by libea18** [2dust/v2rayNG#1119]
i have some client in v2rayNG 
i see logs in my server and see this :

2021/06/26 10:52:32 5.125.86.xx:0 accepted tcp:31.13.66.34:443
2021/06/26 10:52:41 5.125.86.xx:0 rejected  proxy/vmess/encoding: failed to drain connection DrainSize = 2654 63 9 > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/06/26 10:52:22 5.125.86.xx:0 accepted tcp:149.154.167.92:5222
2021/06/26 10:53:03 5.125.86.xx:0 rejected  proxy/vmess/encoding: failed to drain connection DrainSize = 2654 63 27 > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2021/06/26 10:52:32 5.125.86.xx:0 accepted udp:1.1.1.1:53

what is connection DrainSize ? how can i fixed this ?

**Comment by yuhan6665** [comment]
https://www.v2fly.org/guide/faq.html#vmess-invalid-user
