### ISSUE TITLE
希望支持“始终开启的vpn”功能

### ISSUE THREAD

**Issue by rhjdvsgsgks** [2dust/v2rayNG#112]
![如图](https://ww1.sinaimg.cn/large/005zWjpngy1futa1zuar4j30u00gfmy1.jpg)
如图中所示，开启后可避免后台被杀掉

**Comment by trivita** [comment]
支持，pie 一直被杀

**Comment by smdx** [comment]
支持，非常需要这个功能。

**Comment by fcying** [comment]
直接后台锁住也能不被杀吧...在一加和小米上都是锁住就好了

**Comment by rhjdvsgsgks** [comment]
> 直接后台锁住也能不被杀吧...在一加和小米上都是锁住就好了

原生😢
