### ISSUE TITLE
vmess + h2 无法连接

### ISSUE THREAD

**Issue by gitiray** [2dust/v2rayNG#1121]
vmess + h2 + tls 协议，使用新版本无法连接，但**使用旧版本（1.5.10 xray）则连接正常**，且同**网络环境下的其它设备、同一部手机上的其它客户端，亦没有连接问题**

**Comment by yuhan6665** [comment]
能看一下导出的完整配置，新旧版本有什么区别吗

**Comment by lalcd** [comment]
> 能看一下导出的完整配置，新旧版本有什么区别吗

估计还是 path 的问题。

**Comment by gitiray** [comment]
以下3处不同，左侧是新版，无法连接的 @yuhan6665 
**将第3处差异的host修改为旧版后，连接恢复正常**
![图片](https://user-images.githubusercontent.com/84114630/123762912-d5c55a80-d8f5-11eb-9062-ed914c3ebc6a.png)

**Comment by yuhan6665** [comment]
@gitiray 会写脚本就是不一样 大佬 给你点个赞 我这周末就修

**Comment by coffilk** [comment]
> 以下3处不同，左侧是新版，无法连接的 @yuhan6665
> **将第3处差异的host修改为旧版后，连接恢复正常**
> ![图片](https://user-images.githubusercontent.com/84114630/123762912-d5c55a80-d8f5-11eb-9062-ed914c3ebc6a.png)

vless也有这个问题，把host括号里的引号去掉就正常了

**Comment by yuhan6665** [comment]
fix in https://github.com/2dust/v2rayNG/pull/1129

**Comment by gitiray** [comment]
@yuhan6665 抱歉，通过对 https://github.com/2dust/v2rayNG/releases/tag/1.6.15 的进一步测试，发现此问题依然存在，配置文件里host还是带有引号的空值

**Comment by yuhan6665** [comment]
@gitiray 嗯 我这儿测 h2 host 里面是 [] 
你说的问题是 httpSettings 的 host 吗？有问题的节点能删了重新导入试一下？

没事 不用客气

**Comment by gitiray** [comment]
> 
> 
> @gitiray 嗯 我这儿测 h2 host 里面是 []
> 你说的问题是 httpSettings 的 host 吗？有问题的节点能删了重新导入试一下？
> 
> 没事 不用客气

似乎需要多次重新导入之后才会正常？
一直使用同一个 `vmess://` （保证完全一致无修改），之前发现问题还在，重新导入多次，均存在问题，因此跟帖。
今天再次尝试导入，又正常了…… O__O"

**Comment by 8lexliu** [comment]
我也遇到了这个类似的奇怪问题
同一个配置，我在v2flyNG 中尝试重新导入 N 次都无法正常使用，中间还清除了 App 数据也不行。但是相同配置导入到 v2rayNG （同版本）就能正常使用。尝试把在 v2rayNG 正常使用的 Vmess 导入到 v2flyNG，还是无法在 v2flyNG 使用。 @yuhan6665  我能提供什么信息来协助找到问题根源吗？
