### ISSUE TITLE
自定义规则下手动在“直连的网址或IP”栏目下添加域名规则走的是代理而非直连流量？

### ISSUE THREAD

**Issue by yooofei** [2dust/v2rayNG#1125]
“路由设置”下的“域名解析策略”设置为“IPIfNonMatch”；“预定义规则”设置为“绕过局域网和大陆”；并清空了“自定义规则”下的“代理的网址或IP”和“阻止的网址或IP”两个栏目下的“默认路由规则”，只在“直连的网址或IP”栏目下保留手动添加的几条规则。手动添加的直连规则如“domain:baiyunju.cc”这条，在访问其对应网站时手机“通知栏”下v2rayNG的通知还显示走的代理流量，并非直连访问。基于v2rayNG(版本1.6. 14)下。

### 预期行为
“直连的网址或IP”栏目手动添加规则，直连访问而非通过代理

### 实际行为
“直连的网址或IP”栏目手动添加规则，却通过代理访问而非直连

### 复现方法
1.手动将“domain:baiyunju.cc”这条规则添加到“阻止的网址或IP”栏目下后，在访问其相关网址时是无法访问的。(说明“阻止的网址或IP”栏下这条规则是生效的)

### 日志信息
--------- beginning of system
--------- beginning of main
06-30 12:18:06.655 I/GoLog   (17308): Not Using Prepared: tcp,114.55.166.154:443
06-30 12:18:06.656 I/GoLog   (17308): tcp:127.0.0.1:56732 accepted tcp:114.55.166.154:443 [socks -> direct]
06-30 12:18:06.773 I/GoLog   (17308): Not Using Prepared: tcp,114.55.166.154:443
06-30 12:18:06.774 I/GoLog   (17308): tcp:127.0.0.1:56738 accepted tcp:114.55.166.154:443 [socks -> direct]
06-30 12:18:06.777 I/GoLog   (17308): Not Using Prepared: tcp,114.55.166.154:443
06-30 12:18:06.778 I/GoLog   (17308): tcp:127.0.0.1:56744 accepted tcp:114.55.166.154:443 [socks -> direct]
06-30 12:18:06.780 I/GoLog   (17308): Not Using Prepared: tcp,114.55.166.154:443
06-30 12:18:06.780 I/GoLog   (17308): tcp:127.0.0.1:56750 accepted tcp:114.55.166.154:443 [socks -> direct]
06-30 12:18:06.784 I/GoLog   (17308): Not Using Prepared: tcp,114.55.166.154:443
06-30 12:18:06.784 I/GoLog   (17308): tcp:127.0.0.1:56756 accepted tcp:114.55.166.154:443 [socks -> direct]
06-30 12:18:06.915 I/GoLog   (17308): Not Using Prepared: tcp,114.55.166.154:443
06-30 12:18:06.915 I/GoLog   (17308): tcp:127.0.0.1:56762 accepted tcp:114.55.166.154:443 [socks -> direct]
06-30 12:18:09.161 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 82 Err: connection timed out
06-30 12:18:09.161 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 78 Err: connection timed out
06-30 12:18:09.161 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 74 Err: connection timed out
06-30 12:18:09.562 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: failed to find an available destination > common/retry: [connection timed out] > common/retry: all retry attempts failed
06-30 12:18:09.562 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: failed to find an available destination > common/retry: [connection timed out] > common/retry: all retry attempts failed
06-30 12:18:09.962 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [connection timed out] > common/retry: all retry attempts failed
06-30 12:18:11.213 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 60 Err: connection timed out
06-30 12:18:11.614 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: failed to find an available destination > common/retry: [connection timed out] > common/retry: all retry attempts failed
06-30 12:18:13.209 I/GoLog   (17308): tcp:127.0.0.1:56768 accepted tcp:198.177.121.244:443 [socks >> proxy]
06-30 12:18:13.257 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 179 Err: connection timed out
06-30 12:18:14.058 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://46.182.107.147/footers):  > connection timed out] > common/retry: all retry attempts failed
06-30 12:18:15.538 I/GoLog   (17308): Using Prepared: 143.244.60.164
06-30 12:18:17.353 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 80 Err: connection timed out
06-30 12:18:17.754 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/shadowsocks: failed to find an available destination > common/retry: [connection timed out] > common/retry: all retry attempts failed
06-30 12:18:19.405 I/GoLog   (17308): fdConn unix.Connect err, Close Fd: 86 Err: connection timed out
06-30 12:18:20.206 I/GoLog   (17308): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [connection timed out] > common/retry: all retry attempts failed
06-30 12:18:21.620 I/GoLog   (17308): Not Using Prepared: tcp,14.215.177.39:443
06-30 12:18:21.620 I/GoLog   (17308): tcp:127.0.0.1:56774 accepted tcp:14.215.177.39:443 [socks -> direct]
06-30 12:18:35.081 I/GoLog   (17308): tcp:127.0.0.1:56784 accepted tcp:142.250.123.188:5228 [socks >> proxy]
06-30 12:18:35.391 I/GoLog   (17308): Using Prepared: 143.244.60.164
06-30 12:18:36.294 I/GoLog   (17308): Not Using Prepared: udp,1.1.1.1:53
06-30 12:18:36.295 I/GoLog   (17308): 127.0.0.1:33506 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
06-30 12:18:36.497 I/GoLog   (17308): 127.0.0.1:42422 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
06-30 12:18:36.880 I/GoLog   (17308): Not Using Prepared: tcp,49.4.43.101:443
06-30 12:18:36.881 I/GoLog   (17308): tcp:127.0.0.1:56788 accepted tcp:49.4.43.101:443 [socks -> direct]
06-30 12:18:37.441 I/GoLog   (17308): Not Using Prepared: tcp,114.115.188.59:10000
06-30 12:18:37.442 I/GoLog   (17308): tcp:127.0.0.1:56792 accepted tcp:114.115.188.59:10000 [socks -> direct]

**Comment by TedYarm** [comment]
遇到相同的问题。直连配置无法生效，无论是否使用local DNS，配置各种代理模式，自定义规则不生效！ 使用的节点是Trojan！！

**Comment by lqxhub** [comment]
我今天也遇到了, 想使用自定义规则去广告, 然后发现不能访问外网了
预设规则选择直连,自定义规则从v2rayN复制过来的,也是报这个错误 `Not Using Prepared: tcp`

**Comment by Keillion** [comment]
After test, the problem did resolved in https://github.com/2dust/v2rayNG/releases/tag/1.8.5.  🎉🎉

**Comment by Keillion** [comment]
由于业务模拟测试需要，本次主要利用v2rayNG 1.8.5达到免root/adb达到修改hosts、绊除一些域名的效果，没有真的代理需求。

留下我成功的设置：

启用流量探测：启用不启用都可以
勾选“启用本地DNS”
域名策略：IPOnDemand
预定义规则：全局直连
自定义规则：阻止了一些域名

修改好设置后，需要关闭并重新开启代理才能生效

效果：
成功阻止相关域名的访问，<del>出现了一次403，未仔细探究具体是哪种阻断</del>
