### ISSUE TITLE
切换节点导致系统界面崩溃

### ISSUE THREAD

**Issue by SHY1226** [2dust/v2rayNG#113]
### 预期行为
正常切换节点

### 实际行为
切换节点时导致系统界面停止运行（复现几率100%）
### 复现方法
已连接到一个节点时在不手动断开连接的情况下直接切换节点

### 日志信息
<details>

[log.txt](https://github.com/2dust/v2rayNG/files/2340965/log.txt)

</details>

### 环境信息
ROM：魔趣最新版
Android版本：8.1.0
机型：小米NOTE顶配
有XP框架和Magisk框架，但并未对系统界面做任何改动
V2rayNG版本：0.5.6
前几个版本都没有出现这个问题，应该是从更新0.5.5或0.5.6之后就出现了问题

### 额外信息（可选） 
不清楚是V2rayNG的BUG还是ROM的BUG
因为没有调试经验所以不能确保日志完整，我大概是截取的刚刚按下另一节点时开始的日志，如果日志不够完整请告诉我，我重新抓取一下

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.5.7
