### ISSUE TITLE
在miui10的手机分身模式下，两边同时连接，后连的会报端口占用

### ISSUE THREAD

**Issue by aLLeENSmith** [2dust/v2rayNG#113]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
0）miui有个手机分身功能，可以用不同指纹进不同桌面，可以当作两部手机，但很多东西还是可以互通的；
1）主空间开启v2rayng的连接；
2）切换到分身空间，再次开启v2rayng连接；
3）预计需要能够正常使用

### 实际行为
3）实际会报端口占用错误；
ps）在之前的版本，两边同时连接是没有问题的，版本是0.4.2还是多少，已经覆盖了不记得；

### 复现方法
1. 一台miui手机
2. 开启手机分身，将v2rayng应用安装到主空间并迁移安装到分身空间，两边都有
3. 主空间连接，切换分身空间，再次连接，报错

### 日志信息
adb什么的不是太懂，我把应用内logcat的内容发上来：

--------- beginning of system
--------- beginning of main
09-26 16:10:43.912 I/com.v2ray.ang(20793): Background concurrent copying GC freed 5069(353KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/4MB, paused 98us total 552.135ms
09-26 16:10:47.658 I/GoLog   ( 4749): loading v2ray config
09-26 16:10:47.661 I/GoLog   ( 4749): Preparing Domain: xxxxxx.nl:443
09-26 16:10:48.630 I/GoLog   ( 4749): new v2ray core
09-26 16:10:48.640 I/GoLog   ( 4749): start v2ray core
09-26 16:10:48.640 I/GoLog   ( 4749): v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10808 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:10808 > listen tcp 0.0.0.0:10808: bind: address already in use
09-26 16:10:48.641 D/com.v2ray.ang( 4749): go.Universe$proxyerror: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10808 > v2ray.com/core/transport/internet: failed to listen on address: 0.0.0.0:10808 > listen tcp 0.0.0.0:10808: bind: address already in use
09-26 16:10:50.174 I/GoLog   ( 4749): Prepare Result:
09-26 16:10:50.174 I/GoLog   ( 4749):  Domain: xxxxxx.nl
09-26 16:10:50.174 I/GoLog   ( 4749):  Port: 443
09-26 16:10:50.174 I/GoLog   ( 4749):  IPs: [xxx.xxx.xxx.xxx]

**Comment by 2dust** [comment]
我不了解分身的原理
core开启一次会占用端口

**Comment by linsui** [comment]
在自定义配置中不使用10808和10809就可以正常启动，所以请问可以支持自定义代理端口吗？谢谢

Shadowsocks Android 的处理方式是如果端口占用，则只有 tun2socks 的部分工作，流量会进入另一个先启动实例。因此，若首先启动 v2rayng, 然后将 ss 的端口设置为10808后启动，则可以达到两边同时使用v2rayng代理的效果。
