### ISSUE TITLE
更新节点失败

### ISSUE THREAD

**Issue by Michaee295** [2dust/v2rayNG#1131]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
安卓端更新节点失败，然而电脑端可以正常使用使用

### 实际行为
安卓端在更新订阅时候显示失败

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by EricPHPH** [comment]
同样的问题。google play下载的，自己clone代码下来编译的，都不行。

**Comment by 8v6** [comment]
同样的问题，测试了好久，发现是因为用了订阅链接用了短链接造成失败，用原始链接就可以。但其他软件使用短链接是可以正常使用的，不知能否修复呢。
