### ISSUE TITLE
可否增加Geo资源文件的自动更新选项？

### ISSUE THREAD

**Issue by kobehuanghai** [2dust/v2rayNG#1138]
RT，谢谢

**Comment by pansila** [comment]
不仅是自动，而且希望可以更新第三方的数据，比如官方推荐的增强版data包，在#662里面曾经试图实现过这个功能，不知为何停止了？

**Comment by kobehuanghai** [comment]
是的，我也是这个意思，AnXray现在就可以选择更新源> 不仅是自动，而且希望可以更新第三方的数据，比如官方推荐的增强版data包，在#662里面曾经试图实现过这个功能，不知为何停止了？

**Comment by sunlewuyou** [comment]
不说自动更新，安卓手机上连手动更新也不可以，同求增加该功能，谢谢！

**Comment by pansila** [comment]
> 不说自动更新，安卓手机上连手动更新也不可以，同求增加该功能，谢谢！

手动更新可以啊，你没找到地方吧 @sunlewuyou
