### ISSUE TITLE
只保留shadowsocks协议需要怎么做，还有lib.so很大导致包体很大怎么能优化包体大小

### ISSUE THREAD

**Issue by songzhili** [2dust/v2rayNG#1143]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
认为可以改变包体大小
### 实际行为
现在app包体太大，想减少包体大小，去掉别的协议会减小包体大小吗？因为发现实际lib.so占用的资源太大导致的，有优化办法吗

### 环境信息
1.6.2

**Comment by Jin123HAO** [comment]
你使用的是1.6.2的版本嘛？
