### ISSUE TITLE
代码版本是 1.0.2，但是项目发布的安装包版本不匹配，有最新源码吗

### ISSUE THREAD

**Issue by Jin123HAO** [2dust/v2rayNG#1145]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Jack-bin183** [comment]
同问

**Comment by yanghang203** [comment]
同问， 用源码编译的apk是版本1.0.2，用的v2ray-core， 按照首页提示将go项目编译后的aar替换，依然没有改变

**Comment by yanghang203** [comment]
实测页面虽然不能添加VLESS协议配置，但是导入url后可以正常上网，然后编辑就会闪退

**Comment by ysy950803** [comment]
好家伙这个项目后面直接闭源了，README也没见声明，表面还是开源项目。https://github.com/2dust/v2rayNG/issues/651
