### ISSUE TITLE
Android11的DNS解析設定

### ISSUE THREAD

**Issue by mitis1233** [2dust/v2rayNG#1149]
### 問題
VPN DNS預設值 1.1.1.1 在Android 11 無法使用

### 解決
須改為DNS-over-TLS
例如:
1.1.1.1:853
8.8.8.8:853
dns.google

**Comment by rurirei** [comment]
please say the situation you met in details.

**Comment by mitis1233** [comment]
![Screenshot_2021-07-21-02-52-14-84_4212e40b9225be51d3d564b7661326c8](https://user-images.githubusercontent.com/27880243/126379565-12d5de94-cb8e-492d-b487-94a8cb04059a.jpg)
就這個預設值
android 11的vpn dns是使用DoT
使用dns會出現dns無法解析ip
需要改用DoT才能正常使用

**Comment by rurirei** [comment]
try 8.8.8.8 or 1.0.0.1, etc. ip only.
