### ISSUE TITLE
测试延迟可能不准确

### ISSUE THREAD

**Issue by aawwsslll** [2dust/v2rayNG#115]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
延迟测试应该和电脑版相差不大
### 实际行为
延迟测试和电脑版相差几倍

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
手机版的延迟测试在同一个网络同一个结点的情况下数据和电脑版v2rayN相差很多。实际上我也认为电脑应该要更准确点。手机版1000ms的延迟，电脑200多ms。测试情况多次复现。所以要么是电脑不准要么是手机版不准。但是我用ss又测试了下300ms。所以大概率还是手机版不准。

**Comment by 2dust** [comment]
N只有一个ping
NG是本地经过远程服务器到google的时间
