### ISSUE TITLE
能够连接，可以ping通，不能打开任何网页

### ISSUE THREAD

**Issue by ClemenceCc** [2dust/v2rayNG#1150]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
连接后，可以ping通，网页能够正常打开。

### 实际行为
任何网页不能打开

### 复现方法
1.重装v2rayNG
2.输入订阅，更新订阅
3.选定正常节点连接
4.打开浏览器，任何网页不能打开，包括墙内墙外，但微信，qq可以使用

### 日志信息
未获取

### 环境信息
Android 11
### 额外信息（可选）
通过三星S换机助手迁移软件，原手机可以使用

**Comment by ClemenceCc** [comment]
已解决。打开手机 VPN 设置  私人DNS

**Comment by jhooo** [comment]
> 已解决。打开手机 VPN 设置 私人DNS
我擦，牛逼，解决了，从off状态改为on就好了。。
设置，搜索vpn ,里面有个私人VPN ，点击后，从off改为on就好了
