### ISSUE TITLE
VLESS配置flow字段无法正确保存

### ISSUE THREAD

**Issue by kevin-zhu-ca** [2dust/v2rayNG#1154]
### 预期行为
VLESS配置能够正常工作

### 实际行为
VLESS配置中flow字段无法被保存，也无法正确建立连接

### 复现方法
1. 点击+新建配置，选择手动输入VLESS
2. 输入VLESS配置，flow一栏任意选择一个
3. 保存，再次点击编辑这个配置，发现flow的选项被清空
4. 接步骤2，若直接启动连接，发现不能建立连接

### 环境信息
Android 11
v2rayNG v1.16.15 (Lib v23, Xray-core v1.4.2)  (从Google Play安装）

**Comment by yuhan6665** [comment]
只要用了 xtls 才能填 flow

**Comment by kevin-zhu-ca** [comment]
Solved. Closing issue. Thanks.
