### ISSUE TITLE
V2rayNG的Shadowsocks节点的dns解析似乎有问题

### ISSUE THREAD

**Issue by xiaopang0v0** [2dust/v2rayNG#1155]
### 预期行为
我认为使用SS协议连接以后测试连接成功以后就可以正常访问谷歌

### 实际行为
但是连接以后，点击下方连接测试显示连接成功：延迟xxms，但实际无法打开谷歌

### 复现方法
1.使用Shadowsocks-Rust搭建服务器，配置文件中mode设置成**tcp_only**，然后使用V2rayNG 1.6.15连接，连接以后，下方连接测试显示连接成功：延迟xxms，但是谷歌网站**无法打开**
2.使用Shadowsocks-Rust搭建服务器，配置文件中mode设置成**tcp_and_udp**，然后使用V2rayNG 1.6.15连接，连接以后，下方连接测试显示连接成功：延迟xxms，但是谷歌网站**打开成功**
3.使用Shadowsocks-Rust搭建服务器，配置文件中mode设置成**tcp_only**，然后使用Shadowsocks安卓5.2.3连接，连接以后，下方连接测试显示连接成功：延迟xxms，但是谷歌网站**打开成功**

### 问题分析
本人技术水平有限，是一个新手，但是据我观察发现，V2rayNG无法使用SS访问网站的原因应该**与UDP连接有关**，我怀疑网页无法打开的原因可能是**DNS的解析问题**，但由于SS的UDP存在**安全问题**（https://gfw.report/blog/ss_tutorial/zh/#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BD%BF%E7%94%A8tcp_only%E6%A8%A1%E5%BC%8F ），实践时发现在2021年7月1日附近，我的Shadowsocks服务器的端口确实被墙了，所以远程服务端无法打开UDP供V2rayNG解析，所以希望可以**添加 在不使用UDP的情况下解决DNS的查询问题**

**Comment by yuhan6665** [comment]
Use fakeDNS or UOT protocol like Vmess

**Comment by yuhan6665** [comment]
Use fakeDNS or UOT protocol like Vmess

**Comment by xiaopang0v0** [comment]
> Use fakeDNS or UOT protocol like Vmess

好的，按照您的方案已经解决了我的问题，十分感谢，可以关闭这个issue了
