### ISSUE TITLE
连接一段时候没有流量

### ISSUE THREAD

**Issue by Arctictlz** [2dust/v2rayNG#1156]
一开始连接正常测速，正常使用，一分钟左右之后没有流量再跑，然后再去测一下速就可以正常使用。

**Comment by Deice6666** [comment]
更新了安卓11是吗？我更新之后也有这毛病

**Comment by Arctictlz** [comment]
> 更新了安卓11是吗？我更新之后也有这毛病

不是，我是安卓9.荣耀play

**Comment by yuhan6665** [comment]
感觉是需要关掉电池优化

**Comment by Arctictlz** [comment]
> 感觉是需要关掉电池优化

我关掉了自动启动，设置手动启动，允许在后台保留，现在情况好一些，但是偶尔还会出现断的情况
