### ISSUE TITLE
同样的分享链接path手机端会有问题。是bug吗还是

### ISSUE THREAD

**Issue by zhaozhejun** [2dust/v2rayNG#1157]
vless://51bc130d-208c-4c16-c0db-3ca8c9cb4a21@tw.my03.com:11295?type=ws&security=none&path=%252Fhinet#tw-11295

这个配置，在电脑端v2rayn导入正常，v2rayng手机端 path 就出问题，，
![微信图片_20210727145450](https://user-images.githubusercontent.com/22097252/127109454-0f78acbb-df44-4f15-b65b-f1b199f5b2ed.jpg)

**Comment by 2dust** [comment]
URLEncoder.encode("", "UTF-8");

**Comment by zhaozhejun** [comment]
这是  需要咱们这边解决吗？？因为同样的链接，，v2rayn电脑上可以 正常导入，，手机端V2RAYNG不行

**Comment by zhaozhejun** [comment]
> URLEncoder.encode("", "UTF-8");
这是 需要咱们这边解决吗？？因为同样的链接，，v2rayn电脑上可以 正常导入，，手机端V2RAYNG不行

**Comment by Deice6666** [comment]
你的导入配置就是错的，导入链接里path就是%252Fhinet，导入进v2rayng肯定不对，还是直接扫码吧

**Comment by PanHsin** [comment]
这大概是链接 编码转义 和解码 的问题，应该把%2F 换为/  。
 当参数无法还原时， 应参照实际可用的参数 配置节点的参数项，并适当修正，而不是过于依赖 链接导入。

链接存在需要转义的部分，并且由于链接分享标准不一，不同平台，不同软件的客户端的链接识别得到的参数也有问题，客户端之间的链接 ，有时不能100%还原 ，有兼容性的问题。兼容性不同的情况 类似于 IOS  某一客户端导出的链接 导入 安卓 某一客户端 或 反过来 。 

**原始链接 或 未按 N  或 NG 的标准来设计？**
----------------------------------------------------------
对于N：
导入N后，此链接的识别已经发生了变化，不再是原始100%的链接。
原始链接 和 N识别的链接 如下 ：
 vless://51bc130d-208c-4c16-c0db-3ca8c9cb4a21@tw.my03.com:11295?type=ws&security=none&path=%252Fhinet#tw-11295
 vless://51bc130d-208c-4c16-c0db-3ca8c9cb4a21@tw.my03.com:11295?encryption=none&security=none&type=ws&path=%2fhinet#tw-11295


最大的不同： 
（原）   %252Fhinet  
  N识别  %2fhinet 

丢弃了部分字符 ， N才识别.
%2F 或 %2f 识别为  / ，故N中识别为 /hinet

-----------------------------------------------------------------
对于NG :
如果要Ng兼容，应用N分享出来的链接，而不是原始链接。
