### ISSUE TITLE
[更新请求]  v2flyNG 1.6.15 更新

### ISSUE THREAD

**Issue by lalcd** [2dust/v2rayNG#1158]
目前 Play 商店版本为 1.6.14
希望能更新 1.16.15，以便修复 [https://github.com/2dust/v2rayNG/commit/3795348b0417412ae97f667452e529556c235910](url)。

**Comment by maidmeow4** [comment]
加入beta测试

**Comment by lalcd** [comment]
> 加入beta测试

v2flyNG 不像 v2rayNG 有 Beta 测试版。
