### ISSUE TITLE
REQUEST FOR INBUILT CONFIG FILES.

### ISSUE THREAD

**Issue by lavelleo** [2dust/v2rayNG#1166]
@yuhan6665 
Add at least five or more built-in config files.
Hide the address of config files from the users.
The built-in config files should not be editable and sharable.

**Comment by ghost** [comment]
> @yuhan6665
> 添加至少五个或更多内置配置文件。
> 对用户隐藏配置文件的地址。
> 内置配置文件不应是可编辑和可共享的。

NG只是一个用于调试、配置网络的工具。你的这种请求和GooglePlay中NG下方的90%的请求/评论一样毫无逻辑，完全不经大脑思考。

“添加至少五个或更多内置配置文件。” 五个怎么能满足你这种人？起码得20个以上，再附赠10个高质量/优质的配置才行。对了，再给你添加一些推广和投放这样你才对得起自己良心。

“对用户隐藏配置文件的地址。” 直接隐藏所有功能，给你个一键起飞的按钮吧。你知道这类软件的开放性、自定义性、可见性、配置性和注解性有多重要吗？

“内置配置文件不应是可编辑和可共享的。” 想得还挺周到。另外，给你内置服务器就已经是共享了。

你的这种请求如果实现，那即代表NG已脱离本质。
你不适合用这类软件，更不适合用NG。

上述言论仅代表个人。
