### ISSUE TITLE
谷歌市场不能下载应用app

### ISSUE THREAD

**Issue by maryjeck** [2dust/v2rayNG#1171]
好像是老生常谈，大家有没有碰到这个问题啊

**Comment by Deice6666** [comment]
给谷歌储存权限和安装了吗？如果还是不行的话建议换个节点试试，或者看看谷歌三件套正不正常

**Comment by YuboZhang** [comment]
我也碰到这个问题了。
- 手机环境：
小米10S手机，MIUI12.5.7稳定版。
v2rayNG 版本1.6.15。
Google Play商店版本26.3.16-19
Google Play服务版本21.09.15
Google 服务框架版本11-6684105

- 代理权限：
谷歌三件套；
下载管理（迅雷下载引擎已关闭，数据网络下载限制已修改为没有限制）
下载管理程序

现象描述：
使用Google Play商店下载APP，一直显示等待中，通知栏显示正在下载com.google.android.trichromelib，下载完了貌似啥都没做，然后下次启动的时候又重新下载这个trichromelib。其他APP下载永远等待中。

**Comment by maryjeck** [comment]
升级了三件套，又神奇的好了，话说，他自己不是会自动升级么？

**Comment by luckiestone** [comment]
> 升级了三件套，又神奇的好了，话说，他自己不是会自动升级么？

我的一直是这个问题，下不了，一直等待。我也升级了，从apkpure下载的service和store，你怎么升级三件套的？

**Comment by dbguo** [comment]
> > 升级了三件套，又神奇的好了，再说，他自己不是会自动升级么？
> 
> 我一直是这个问题，下不了，一直在等待。我也升级了，从apkpure下载的服务和商店，你怎么升级三件套的？

你用的是WebSocket + TLS吗？

**Comment by YuboZhang** [comment]
> > 升级了三件套，又神奇的好了，话说，他自己不是会自动升级么？
> 
> 我的一直是这个问题，下不了，一直等待。我也升级了，从apkpure下载的service和store，你怎么升级三件套的？

我的是MIUI12.5，从apkpure上下载的三件套，也出现了这个问题。后来把这些都卸载了，直接从小米应用商店下载谷歌商店，就好了。

**Comment by JarmoHu** [comment]
荣耀V20 发现也是这个原因，但是过了一会儿自己好了。
vless-分应用代理（自动选择app）-绕过大陆和局域网-

-----------2021/08/29更新-----------
妈的又不行了

**Comment by gcphym** [comment]
https://github.com/2dust/v2rayNG/issues/1234#issuecomment-926995485 可以看一下
