### ISSUE TITLE
xray这个配置的链接在PC端V2rayN可使用，在安卓端V2rayNG上不能使用

### ISSUE THREAD

**Issue by wpyok500** [2dust/v2rayNG#1174]
用xray这个配置https://github.com/XTLS/Xray-examples/tree/main/VLESS-TCP-XTLS-WHATEVER部署的链接在PC端V2rayN可使用，在安卓端V2rayNG上不能使用

--------- beginning of main
08-06 14:14:33.527 E/tun2socks( 7542): ERROR(BConnection): recv failed

**Comment by fisher-he** [comment]
我也是遇到一样的问题，PC可用，安卓不可用。

**Comment by volatileAntiEntropy** [comment]
+1, cannot use after recent update. Ping is normal but still no connection.

**Comment by ibafly** [comment]
My Problem is: On my Android phone A all is good, but not working on the other Android Tablet B from A's brand. Both using v2rayNG in same version (latest) and same config settings.

Tcpings are all good. Being `io: read/write on closed pipe` when trying to connect though.

I've tried:
1. Config: allowInsecure to true ❌ 
2. Tablet system: Reset network settings ❌ 
3. Config: fake host to my domain address 🆗 

Success connecting! And weird that my failing config now is able to connect, too. So maybe there is a bug?

Also see:
- https://github.com/2dust/v2rayNG/issues/369#issuecomment-825005868
- https://www.reddit.com/r/dumbclub/comments/icf5oo/help_v2ui_v2ray_io_readwrite_on_closed_pipe_error/g2a00au

**Comment by forgotmymilk** [comment]
我的情况也一样，只能再电脑端使用xray和trojan，ng上不能用xray和trojan，我是怎么知道是客户端的问题，因为电脑v2ray能用，ios的小火煎亦可以用。ng不行。

**Comment by tcg123** [comment]
最近两天也遇到了同样的问题，本来用的好好的，开始先打不开youtube，能打开电报 今天都打不开了，pc端正常使用

**Comment by tcg123** [comment]
回退到1.6.14使用

**Comment by forgotmymilk** [comment]
> 回退到1.6.14使用

还是不行

**Comment by superabbite1** [comment]
同样的问题，1.6.15也这样，更新到1.6.23已一样，电脑可以，安卓不行

**Comment by cxqn** [comment]
需要把手机设置里的私人dns设置打开并且设置为自动，dns的原因

**Comment by LZZ383** [comment]
同样的问题，电脑端和苹果手机端都能用，android手机端无法使用，测试提示：context deadline exceeded

**Comment by nicklhy** [comment]
got same problem in android, any updates ?

**Comment by realIronWang** [comment]
系统时间设置为网络时间就好了

**Comment by leo985** [comment]
> 系统时间设置为网络时间就好了

没用的，试过了。
