### ISSUE TITLE
sock5代理UDP转发至172.16.0.12，导致无网

### ISSUE THREAD

**Issue by Jin123HAO** [2dust/v2rayNG#1178]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
使用腾讯云IP进行代理链接，进行数据转发

### 实际行为
TCP转发正常，但UDP协议全部转发至172.16.0.12，

### 复现方法
1.使用腾讯云或者其他云服务器IP进行sock5代理

### 日志信息

Not Using Prepared: udp,172.16.0.12:58496

**Comment by BozhanL** [comment]
你把socks5部署到云服务器上了？入站的socks5配置是什么？

**Comment by Jin123HAO** [comment]
> 你把socks5部署到云服务器上了？入站的socks5配置是什么？

基于CC proxy架设的架设的sock5服务

**Comment by BozhanL** [comment]
> > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> 
> 基于CC proxy架设的架设的sock5服务

是v2rayNG连接到 CC proxy ?

**Comment by Jin123HAO** [comment]
> 你把socks5部署到云服务器上了？入站的socks5配置是什么？
配置没问题，在普通拨号上用同样的方式架设的，正常转发

**Comment by Jin123HAO** [comment]
> > > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> > 
> > 
> > 基于CC proxy架设的架设的sock5服务
> 
> 是v2rayNG连接到 CC proxy ?

对的

**Comment by Jin123HAO** [comment]
> > > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> > 
> > 
> > 基于CC proxy架设的架设的sock5服务
> 
> 是v2rayNG连接到 CC proxy ?

可加我Q 853476895

**Comment by BozhanL** [comment]
> > > > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> > > 
> > > 
> > > 基于CC proxy架设的架设的sock5服务
> > 
> > 
> > 是v2rayNG连接到 CC proxy ?
> 
> 对的

别的客户端没有这个问题，只有v2rayNG有？

**Comment by Jin123HAO** [comment]
> > > > > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> > > > 
> > > > 
> > > > 基于CC proxy架设的架设的sock5服务
> > > 
> > > 
> > > 是v2rayNG连接到 CC proxy ?
> > 
> > 
> > 对的
> 
> 别的客户端没有这个问题，只有v2rayNG有？

Windows端软件转发正常

**Comment by BozhanL** [comment]
> > > > > > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> > > > > 
> > > > > 
> > > > > 基于CC proxy架设的架设的sock5服务
> > > > 
> > > > 
> > > > 是v2rayNG连接到 CC proxy ?
> > > 
> > > 
> > > 对的
> > 
> > 
> > 别的客户端没有这个问题，只有v2rayNG有？
> 
> Windows端软件转发正常

v2rayNG 的 socks Outbound 默认有 ```"network": "tcp"``` 。 创个自定义配置，删了这条试试

**Comment by Jin123HAO** [comment]
> > > > > > > 你把socks5部署到云服务器上了？入站的socks5配置是什么？
> > > > > > 
> > > > > > 
> > > > > > 基于CC proxy架设的架设的sock5服务
> > > > > 
> > > > > 
> > > > > 是v2rayNG连接到 CC proxy ?
> > > > 
> > > > 
> > > > 对的
> > > 
> > > 
> > > 别的客户端没有这个问题，只有v2rayNG有？
> > 
> > 
> > Windows端软件转发正常
> 
> v2rayNG 的 socks Outbound 默认有 `"network": "tcp"` 。 创个自定义配置，删了这条试试

方便加下我QQ吗。有偿解决
