### ISSUE TITLE
使用泛域名证书时，必须打开“跳过证书验证”，否则连不上

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1187]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
v2rayNG 服务端使用泛域名证书，v2rayNG关闭“跳过证书验证”；连上

### 实际行为
v2rayNG 服务端使用泛域名证书，v2rayNG关闭“跳过证书验证”；连不上

### 复现方法
1. 服务端使用泛域名证书
2. v2rayNG关闭“跳过证书验证”
3. 连不上

### 日志信息
<details>
 > x509: certificate signed by unknown authority] > common/retry: all retry attempts failed
</details>

**Comment by michealhansun** [comment]
泛域名证书时，连接失败，请问，跳过证书验证，我打勾和取消打勾 都是连不上，只能使用不需要证书的模式。
哥们，请问你解决了吗

**Comment by ghost** [comment]
我也忘了咋回事，应该是配置问题；后来用泛域名证书没有任何问题；

我想起来了，好像是需要使用fullchain的那个证书，普通的不行

**Comment by michealhansun** [comment]
> fullchain

换了“fullchain”证书，现在可以使用泛域名证书成功连接了，谢谢哈。
