### ISSUE TITLE
建议：能否恢复v2ray-core的v2rayNG版本

### ISSUE THREAD

**Issue by bhoppi** [2dust/v2rayNG#1192]
如题，Xray内核的v2rayNG可以另外创建名为XrayNG（举例）的项目。
建议的原因如下：
首先，Xray-core已经好几个月没有维护了，导致一系列v2ray的新功能例如：Loopback outbound、链式代理、observatory、mph域名匹配算法（功能已merge但迟迟不发版本）、“fakedns+others”等等以及诸多bug修复都无法实装到v2rayNG中。
其次，即使Xray-core今后恢复维护，rprx也已说过今后不再刻意维持与v2ray-core的兼容性，这样以后二者的分化会越来越大，因此使用Xray-core却顶着"v2ray"NG的名字会显得不伦不类。
最后，我知道Play商店里有基于v2ray-core的v2flyNG版本，但我由于手机品牌原因，并不能使用Google Play，更无法进行付款（Google要求有绑定Google帐户的设备），所以v2flyNG我愿意付费使用都求之无门。
因此，希望能够考虑如题的建议。

**Comment by cache444** [comment]
> 如题，X射线内核的v2rayNG可以另外创建名为XrayNG（举例）的项目。
> 建议的原因如下：
> 首先，X射线核已经好几个月没有维护了，导致一系列v2ray的新功能例如：环回呼出，链式代理、天文台、mph域名算法匹配（功能已合并但迟迟不发版本）、“fakedns+others”等以及网络bug修复都无法实装到v2rayNG中。
> 其次，即使Xray-core将恢复维护，rx也已经说过即将不再刻意维持v2ray-core的，这样以后开口的着会越来越大，使用ray-core却顶“v2ray”NG的名字会不伦不类。
> 最后，我知道Play商店里有基于v2ray-core的v2flyNG版本，但我因为手机原因，并不能使用Google Play，更进行付款（Google要求绑定Google帐户的设备），所以v2flyNG我愿意付费使用都求之无门。
> 因此，希望能够考虑如题的建议。

表示认同。目前xray说的完全兼容v2ray的功能和配置，但其实连v2ray-core本身支持的DNS-over-QUIC在xray-core上就不可用。

另外v2flyNG的图标不太好看…（希望开发者可以考虑发起一个项目LOGO/图标征集，我第一个无条件参与并提交设计）

**Comment by bhoppi** [comment]
> 
> 
> > 如题，X射线内核的v2rayNG可以另外创建名为XrayNG（举例）的项目。
> > 建议的原因如下：
> > 首先，X射线核已经好几个月没有维护了，导致一系列v2ray的新功能例如：环回呼出，链式代理、天文台、mph域名算法匹配（功能已合并但迟迟不发版本）、“fakedns+others”等以及网络bug修复都无法实装到v2rayNG中。
> > 其次，即使Xray-core将恢复维护，rx也已经说过即将不再刻意维持v2ray-core的，这样以后开口的着会越来越大，使用ray-core却顶“v2ray”NG的名字会不伦不类。
> > 最后，我知道Play商店里有基于v2ray-core的v2flyNG版本，但我因为手机原因，并不能使用Google Play，更进行付款（Google要求绑定Google帐户的设备），所以v2flyNG我愿意付费使用都求之无门。
> > 因此，希望能够考虑如题的建议。
> 
> 比较认同。目前xray说的完全兼容v2ray的功能和配置，但其实并不是，例如v2ray-core本身支持的DNS-over-QUIC在xray-core上就不可用。
> 不过话说回来，xray本身也有很多优势，相比v2ray实际体验上也确实要快，NG用xray个人认为是完全可以的，只想安心稳定上网的话几乎没有毛病 没啥问题。总之感觉鱼和熊掌不可兼得。
> 
> 另外v2flyNG的图标不太好看…（希望开发者可以考虑发起一个项目LOGO/图标征集，我第一个无条件参与并提交设计）

我说了Xray可以再开一个坑，并不是说要放弃Xray啊。
另外，你这个引用的是什么鬼，感觉是来回翻译过的？

**Comment by cache444** [comment]
我当然能看明白你说的意思，只是觉得这样对开发者来说相当于又多了一个需要维护的项目，显然会更加“心累”一些。

然后引用那个是因为回复时会自动引用原文在前，我也懒得删所以回复出来就那个样子了。。  你看我现在回复的这个就没有引用了对吧，因为我删了它的自动引用

**Comment by bhoppi** [comment]
> 
> 
> 我当然能看明白你说的意思，只是觉得这样对开发者来说相当于又多了一个需要维护的项目，显然会更加“心累”一些。
> 
> 然后引用那个是因为回复时会自动引用原文在前，我也懒得删所以回复出来就那个样子了。。 你看我现在回复的这个就没有引用了对吧，因为我删了它的自动引用

因为有v2flyNG的存在，开发者本来也是要维护v2ray-core的版本的，所以我觉得应该不会增加多少工作量（我没用过v2flyNG，凭想象说的，说错勿怪）。
引用那里我是说你的引用把我的很多话都改掉了，像是翻译成英文再翻回中文的结果。

**Comment by cache444** [comment]
> > 我当然能看明白你说的意思，只是觉得这样对开发者来说相当于又多了一个需要维护的项目，显然会更加“心累”一些。
> > 然后引用那个是因为回复时会自动引用原文在前，我也懒得删所以回复出来就那个样子了。。 你看我现在回复的这个就没有引用了对吧，因为我删了它的自动引用
> 
> 因为有v2flyNG的存在，开发者本来也是要维护v2ray-core的版本的，所以我觉得应该不会增加多少工作量（我没用过v2flyNG，凭想象说的，说错勿怪）。
> 引用那里我是说你的引用把我的很多话都改掉了，像是翻译成英文再翻回中文的结果。

哈哈好像是的，Chrome的自动翻译，没注意，无伤大雅。

话说回来，工作量和一个独立的新项目几乎是一样的。其实你看看例如隔壁的Sagernet(v2ray-core)和Anxray(xray-core)就知道了，除了内核外几乎没有区别，但它们却是两个分开/独立的APP，不明白的人都会认为难以理解。

**Comment by 2dust** [comment]
https://github.com/2dust/v2flyNG
