### ISSUE TITLE
建议:可否增加几个实用功能

### ISSUE THREAD

**Issue by qianyiqq** [2dust/v2rayNG#1193]
1:增加一个对下载测速的功能
2:增加一个对ping值排序或者下载速度排序的功能
3:去除重复节点

现在其实已经很好用了，如果增加了这几个功能，基本碾压安卓端其他软件了。

**Comment by cache444** [comment]
> 1：一个对下载测速的功能
> 2：增加一个对循环值增加或下载速度排序的功能
> 3：重复节点
> 
> 现在实际上已经很好用了，如果增加了这几个功能，基本压压安卓端其他软件了。

1. 目前几乎所有主流平台(操作系统)上的代理工具(客户端)都没有所谓的“下载测速”这个功能。首先下载测速对代理工具来说是完全无必要的功能；其次这也不是代理工具该做的事。你要下载测速或检测网络质量，又或者机场测速，完全可以去用Speedtest或SSRSpeed。

2. 推荐你用Sagernet。你提出的这些功能需求Sagernet都能满足，包括你说的测速、速度排序、去重。但是请注意，Sagernet也没有下载测速（原因请看1）。

3. 去重这个我倒是认同，同样建议NG添加去重(即订阅链接/更新订阅时可检测并提供去除重复配置节点的选项)。

4. NG目前可以说已经很稳定和完善了，完全适合非高玩用户和不喜欢折腾的用户。
