### ISSUE TITLE
关于订阅设置的功能建议，请求添加

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1194]
![S10819-21022019](https://user-images.githubusercontent.com/89191925/130107206-c0385401-e480-4115-b389-17a9d089396b.jpg)
如图，Sagernet订阅设置里的这两个功能很棒，特别是对于像我这样懒得折腾的重度机场用户来说，做得很细节。用户代理(User agent)用来向代理服务器隐藏自己的真实UA，机场后台是可以看到这个UA的，只要你订阅就会有记录，此UA包括了用户的设备名称/型号、操作系统、系统版本等信息。
为了更直观的说明此功能，请看如下截图对比：
①某机场后台（未使用用户代理）
![11111333111](https://user-images.githubusercontent.com/89191925/130109089-fa805656-fe14-4ffb-a671-89dbf7726558.png)

②还是同样的某机场后台（使用了用户代理）
![1629378515439](https://user-images.githubusercontent.com/89191925/130107666-0218ef9f-05e4-4caa-b107-d0ce14f63c5d.png)

希望开发者能采纳如上功能建议，辛苦了，感谢你们所做的一切！

**Comment by yuhan6665** [comment]
How about change 用户代理(User agent) to "v2rayNG v1.x.x"
CC @2dust

**Comment by cache444** [comment]
> ![S10819-21022019](https://user-images.githubusercontent.com/89191925/130107206-c0385401-e480-4115-b389-17a9d089396b.jpg)
> 如图，Sagernet订阅设置里的这两个功能真的太细节了！！特别是对于像我这样懒得折腾的重度机场用户来说，真的很细节，特别是用户代理及仅在连接时更新这两个功能。用户代理(User agent)可以在订阅时向代理服务器隐藏自己的真实UA，机场后台是可以看到这个UA的，只要你订阅就会有记录。此UA包括了订阅用户的设备名称/型号、操作系统、系统版本等信息。

> 为了更直观的说明此功能，请看如下截图对比：
> ①某机场后台（未使用用户代理）
![1629378515145](https://user-images.githubusercontent.com/89191925/130108131-5d7c2d58-8dc5-4c50-9b07-d9dcda902cac.png)

> ②还是同样的某机场后台（使用了用户代理）
> ![1629378515439](https://user-images.githubusercontent.com/89191925/130107666-0218ef9f-05e4-4caa-b107-d0ce14f63c5d.png)
> 
> 希望开发者能采纳如上功能建议，辛苦了，谢谢你们所做的一切！

**Comment by cache444** [comment]
> 将用户代理（用户代理）更改为“v2rayNG v1.xx”
> CC @2dust怎么样

非常感谢！！！
建议可以由用户自定义，在用户不做任何更改(即默认设置)下，用户代理为应用名“v2rayNG”+当前版本号“v1.x.x”，如“v2rayNG v1.6.16”。但更建议默认为“v2rayNG”即可，无需添加版本后缀，这样更简洁美观，也有利于后续客户端升级更新时开发者无需再进行后缀的更新(如果是不能自动获取当前NG版本的话)。

然后用户也可以手动进行编辑更改，显示用户自定义的UA，就如同用户可以自定义自己想用的DNS一样。（自定义对用户来说会觉得很cool？）

**Comment by cache444** [comment]
> > 将用户代理（用户代理）更改为“v2rayNG v1.xx” 
> > CC @2dust怎么样
> 
> 非常感谢！！！
> 建议可以由用户自定义，在用户不做任何更改（即默认设置）下，用户代理为应用名“v2rayNG”+当前版本号“v1.xx”，如“v2rayNG v1.6.16” 。。但更但更NG的默认开发为“v2ray NG默认开发”，无需添加版本后缀，这样建议更简洁美观，也有插件客户端升级更新时者无需再进行后缀的更新（如果是不能自动获取当前NG版本的话） 。
> 
> 然后用户也可以手动进行修改更改用户自定义的 UA，就可以显示用户可以自定义自己想用的 DNS 一样。（自定义用户会觉得很酷？）

@yuhan6665  @2dust

**Comment by yuhan6665** [comment]
Convention over configuration. Let me know if you have a strong reason to configure it.
Added in https://github.com/2dust/v2rayNG/pull/1198
