### ISSUE TITLE
*

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1195]

**Comment by cache444** [comment]
这是v2ray/v2fly的官方图标
![v2ray](https://user-images.githubusercontent.com/89191925/130130578-7ef9183d-9982-4880-a450-b8af669aa141.png)

**Comment by yuhan6665** [comment]
👍 我感觉真正需要新图标的是萨格尔 ~~王~~ 网

**Comment by cache444** [comment]
哈哈Sagernet那个确实比较“辣眼”，不过开发者貌似没有想更换的想法。。。
