### ISSUE TITLE
v2rayng无法连接甲骨文的节点

### ISSUE THREAD

**Issue by tjyuli** [2dust/v2rayNG#1196]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
甲骨文上已经关闭了防火墙和安全规则，用的xray建立的vless+ws，用其他的客户端都能连接，anxray，电脑上的v2rayn都是能连接的，只有v2rayng用不了，无法连接不知道怎么回事

### 实际行为
用其他的客户端都能连接，anxray，电脑上的v2rayn都是能连接的，只有v2rayng用不了，无法连接不知道怎么回事

### 复现方法
1. 节点的二维码我已经发送到邮箱了，还请查收

### 日志信息
<details>

--------- beginning of crash
--------- beginning of main
08-20 12:46:23.626 13153 16515 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:23.627 13153 22852 I GoLog   : tcp:127.0.0.1:40464 accepted tcp:151.101.130.219:443 [socks >> proxy-global-3]
08-20 12:46:24.031 13153 22894 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:24.032 13153 22844 I GoLog   : udp:127.0.0.1:37562 accepted udp:216.58.194.206:443 [socks >> proxy-global-3]
08-20 12:46:24.697 13153 22850 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:24.698 13153 22852 I GoLog   : tcp:127.0.0.1:40474 accepted tcp:151.101.130.219:443 [socks >> proxy-global-3]
08-20 12:46:36.832 13153 22852 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:36.833 13153 22895 I GoLog   : tcp:127.0.0.1:40488 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:46:37.632 13153 22850 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:37.633 13153 22844 I GoLog   : tcp:127.0.0.1:40494 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:46:40.378 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:40.379 13153 22850 I GoLog   : tcp:127.0.0.1:40500 accepted tcp:149.154.166.120:443 [socks >> proxy-global-3]
08-20 12:46:40.383 13153 22850 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:40.383 13153 22852 I GoLog   : tcp:127.0.0.1:40504 accepted tcp:149.154.166.120:443 [socks >> proxy-global-3]
08-20 12:46:41.850 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:41.850 13153 22894 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:46:41.850 13153 22850 I GoLog   : tcp:127.0.0.1:40516 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:46:41.850 13153 22850 I GoLog   : tcp:127.0.0.1:40520 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:47:32.978 13153 22852 I GoLog   : 127.0.0.1:54191 accepted udp:1.0.0.1:53 [dns-in -> dns-out]
08-20 12:47:32.981 13153 22852 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:47:32.983 13153 22851 I GoLog   : DoH accepted https://1.0.0.1/dns-query [xray.system.24ff6a71-7ee3-4258-9394-963b4c3d2c84 >> proxy-global-3]
08-20 12:47:33.929 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:47:33.931 13153 22850 I GoLog   : udp:127.0.0.1:56631 accepted udp:142.251.2.102:443 [socks >> proxy-global-3]
08-20 12:47:39.853 13153 16515 I GoLog   : udp:127.0.0.1:55545 accepted udp:216.58.194.206:443 [socks >> proxy-global-3]
08-20 12:47:39.854 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:47:41.555 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:47:41.557 13153 22852 I GoLog   : tcp:127.0.0.1:40562 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:48:13.638 13153 22852 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:48:13.639 13153 16515 I GoLog   : tcp:127.0.0.1:40568 accepted tcp:142.250.101.188:5228 [socks >> proxy-global-3]
08-20 12:48:46.346 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:48:46.353 13153 22852 I GoLog   : tcp:127.0.0.1:40594 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:48:55.774 13153 16515 I GoLog   : udp:127.0.0.1:58951 accepted udp:216.58.194.206:443 [socks >> proxy-global-3]
08-20 12:48:55.774 13153 22850 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
--------- beginning of system
08-20 12:49:51.149 13153 16515 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:49:51.149 13153 22844 I GoLog   : tcp:127.0.0.1:40614 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:50:11.571 13153 22850 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:50:11.571 13153 22844 I GoLog   : udp:127.0.0.1:41691 accepted udp:216.58.194.206:443 [socks >> proxy-global-3]
08-20 12:50:19.423 13153 22894 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:50:19.424 13153 16515 I GoLog   : DoH accepted https://1.0.0.1/dns-query [xray.system.24ff6a71-7ee3-4258-9394-963b4c3d2c84 >> proxy-global-3]
08-20 12:50:19.424 13153 16515 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:50:19.424 13153 22852 I GoLog   : DoH accepted https://1.0.0.1/dns-query [xray.system.24ff6a71-7ee3-4258-9394-963b4c3d2c84 >> proxy-global-3]
08-20 12:50:20.296 13153 22852 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:50:20.296 13153 16515 I GoLog   : tcp:127.0.0.1:40624 accepted tcp:142.250.101.188:5228 [socks >> proxy-global-3]
08-20 12:50:55.983 13153 22850 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:50:55.984 13153 16515 I GoLog   : tcp:127.0.0.1:40636 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:51:25.997 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:51:26.000 13153 22851 I GoLog   : tcp:127.0.0.1:40646 accepted tcp:142.250.101.188:5228 [socks >> proxy-global-3]
08-20 12:51:27.850 13153 22851 I GoLog   : udp:127.0.0.1:39139 accepted udp:216.58.194.206:443 [socks >> proxy-global-3]
08-20 12:51:27.854 13153 22844 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:52:00.802 13153 22844 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:52:00.807 13153 22851 I GoLog   : tcp:127.0.0.1:40658 accepted tcp:149.154.175.55:443 [socks >> proxy-global-3]
08-20 12:52:07.849 13153 22850 I GoLog   : 127.0.0.1:51109 accepted udp:1.0.0.1:53 [dns-in -> dns-out]
08-20 12:52:07.850 13153 22844 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:52:07.850 13153 22850 I GoLog   : DoH accepted https://1.0.0.1/dns-query [xray.system.24ff6a71-7ee3-4258-9394-963b4c3d2c84 >> proxy-global-3]
08-20 12:52:08.212 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:52:08.212 13153 22850 I GoLog   : udp:127.0.0.1:34713 accepted udp:142.251.2.102:443 [socks >> proxy-global-3]
08-20 12:52:08.786 13153 22895 I GoLog   : Not Using Prepared: tcp,oramd1.甲骨文节点.ga:443
08-20 12:52:08.786 13153 16515 I GoLog   : udp:127.0.0.1:35284 accepted udp:172.217.6.42:443 [socks >> proxy-global-3]
08-20 12:53:04.737 29634  6106 W com.v2ray.ang: Reducing the number of considered missed Gc histogram windows from 250 to 100
08-20 12:53:08.413 27004 27004 D com.v2ray.ang: {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "dns": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "hosts": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "domain:googleapis.cn": "googleapis.com"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "servers": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "1.1.1.1",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "address": "223.5.5.5",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "domains": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "geosite:cn"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "expectIPs": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "geoip:cn"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "port": 53
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     ]
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "inbounds": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "port": 10808,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "protocol": "socks",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "settings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "auth": "noauth",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "udp": true,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "userLevel": 8
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "sniffing": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "destOverride": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "http",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "tls"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "enabled": true
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "tag": "socks"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "port": 10809,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "protocol": "http",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "settings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "userLevel": 8
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "tag": "http"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "log": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "loglevel": "warning"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "outbounds": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "mux": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "concurrency": 8,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "enabled": false
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "protocol": "vless",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "settings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "vnext": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:             "address": "oramd1.甲骨文节点.ga",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:             "port": 443,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:             "users": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:               {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:                 "encryption": "none",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:                 "flow": "",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:                 "id": "3174ea26-a798-4acf-b452-8f44ed88a072",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:                 "level": 8,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:                 "security": "auto"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:               }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:             ]
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ]
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "streamSettings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "network": "ws",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "security": "tls",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "tlsSettings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "allowInsecure": true,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "serverName": "oramd1.甲骨文节点.ga"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "wsSettings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "headers": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:             "Host": "oramd1.甲骨文节点.ga"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "path": "/oramd1"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "tag": "proxy"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "protocol": "freedom",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "settings": {},
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "tag": "direct"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "protocol": "blackhole",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "settings": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "response": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "type": "http"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "tag": "block"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "policy": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "levels": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "8": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "connIdle": 300,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "downlinkOnly": 1,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "handshake": 4,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "uplinkOnly": 1
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "system": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "statsOutboundUplink": true,
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       "statsOutboundDownlink": true
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "routing": {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "domainStrategy": "IPIfNonMatch",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     "rules": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "ip": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "1.1.1.1"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "outboundTag": "proxy",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "port": "53",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "type": "field"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "ip": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "223.5.5.5"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "outboundTag": "direct",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "port": "53",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "type": "field"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "domain": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "domain:googleapis.cn"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "outboundTag": "proxy",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "type": "field"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "ip": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "geoip:private"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "outboundTag": "direct",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "type": "field"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "ip": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "geoip:cn"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "outboundTag": "direct",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "type": "field"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       {
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "domain": [
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:           "geosite:cn"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         ],
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "outboundTag": "direct",
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:         "type": "field"
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:       }
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:     ]
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   },
08-20 12:53:08.413 27004 27004 D com.v2ray.ang:   "stats": {}
08-20 12:53:08.413 27004 27004 D com.v2ray.ang: }
08-20 12:53:08.417 27004 27004 I GoLog   : loading core config
08-20 12:53:08.417 27004 27672 I GoLog   : Preparing Domain: oramd1.甲骨文节点.ga:443
08-20 12:53:08.421 27004 27672 I GoLog   : Prepare Result:
08-20 12:53:08.421 27004 27672 I GoLog   :  Domain: oramd1.甲骨文节点.ga
08-20 12:53:08.421 27004 27672 I GoLog   :  Port: 443
08-20 12:53:08.421 27004 27672 I GoLog   :  IPs: [156.56.103.200]
08-20 12:53:08.493 27004 27004 I GoLog   : new core
08-20 12:53:08.513 27004 27004 I GoLog   : start core
08-20 12:53:08.515 27004 27672 I GoLog   : [Warning] core: Xray 1.4.2 started
08-20 12:53:08.573 27004 27004 D com.v2ray.ang: [/data/app/com.v2ray.ang-ECpn6eyZm5Kd7PLwnQhzTw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
08-20 12:53:08.610 27004 27004 D com.v2ray.ang: Process[pid=27683, hasExited=false]
08-20 12:53:08.611 27004 27004 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
08-20 12:53:08.665 27004 27685 D com.v2ray.ang: sendFd tries: 0
08-20 12:53:09.168 27004 27672 I GoLog   : DNS accepted udp:1.1.1.1:53 [xray.system.cb2d1991-790e-4635-9a5d-ef1397a95e40 -> proxy]
08-20 12:53:09.320 27004 27666 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:11.342 27004 27675 I GoLog   : tcp:127.0.0.1:56070 accepted tcp:149.154.175.55:443 [socks >> proxy]
08-20 12:53:11.432 27004 27670 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:13.169 27004 27680 I GoLog   : Not Using Prepared: udp,223.5.5.5:53
08-20 12:53:13.169 27004 27670 I GoLog   : DNS accepted udp:223.5.5.5:53 [xray.system.cb2d1991-790e-4635-9a5d-ef1397a95e40 -> direct]
08-20 12:53:17.297 27004 27679 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:17.701 27004 27680 I GoLog   : tcp:127.0.0.1:56066 accepted tcp:74.125.203.188:5228 [socks >> proxy]
08-20 12:53:17.772 27004 27670 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:18.224 27004 27679 I GoLog   : udp:127.0.0.1:52314 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:18.307 27004 27670 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:18.735 27004 27679 I GoLog   : udp:127.0.0.1:47283 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:18.810 27004 27680 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:23.230 27004 27666 I GoLog   : udp:127.0.0.1:52442 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:23.307 27004 27680 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:23.744 27004 27675 I GoLog   : udp:127.0.0.1:45894 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:23.824 27004 27680 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:24.322 27004 27680 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:28.774 27004 27679 I GoLog   : udp:127.0.0.1:60832 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:28.869 27004 27675 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:33.778 27004 27675 I GoLog   : udp:127.0.0.1:40573 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:33.856 27004 27679 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:53:58.371 27004 27004 D com.v2ray.ang: SCREEN_OFF, stop querying stats
08-20 12:53:58.381 27004 27679 I GoLog   : udp:127.0.0.1:57280 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:53:58.452 27004 27675 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:54:03.401 27004 27670 I GoLog   : udp:127.0.0.1:58098 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:54:03.483 27004 27675 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:54:16.191 27004 27675 I GoLog   : tcp:127.0.0.1:56106 accepted tcp:149.154.175.55:443 [socks >> proxy]
08-20 12:54:16.307 27004 27680 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:54:48.507 27004 27679 I GoLog   : udp:127.0.0.1:52518 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:54:48.616 27004 27670 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:54:53.524 27004 27679 I GoLog   : udp:127.0.0.1:59214 accepted udp:1.1.1.1:53 [socks -> proxy]
08-20 12:54:53.672 27004 27680 I GoLog   : Using Prepared: 156.56.103.200
08-20 12:55:21.669 27004 27675 I GoLog   : tcp:127.0.0.1:56118 accepted tcp:149.154.175.55:443 [socks >> proxy]
08-20 12:55:21.788 27004 27679 I GoLog   : Using Prepared: 156.56.103.200
</details>

### 环境信息
android 10 
v2rayng v1.6.16[xray-core v1.4.2]

**Comment by yuhan6665** [comment]
大概是 dns 不通 可能要用 DOH

**Comment by xiaopang0v0** [comment]
请检查设置中 启用本地DNS 、启用虚拟DNS 两个选项是否打开

**Comment by TjongLIU** [comment]
我也是甲骨文的节点，最近2周手机版V2rayNg一直连不上，启用本地DNS 、启用虚拟DNS 两个选项打开也没有什么卵用，但是Openwrt上的同样节点，客户端passwall就没有问题。

**Comment by tjyuli** [comment]
> 我也是甲骨文的节点，最近2周手机版V2rayNg一直连不上，可以本地DNS、可以虚拟DNS两个选项打开也没有什么卵用，但是Openwrt上的同样节点，客户端passwall就没有问题。

我找出原因了，把dns改成1.0.0.1   不要用1.1.1.1

**Comment by TjongLIU** [comment]
非常感谢，实测有效！

**Comment by shijia7** [comment]
> > 我也是甲骨文的节点，最近2周手机版V2rayNg一直连不上，可以本地DNS、可以虚拟DNS两个选项打开也没有什么卵用，但是Openwrt上的同样节点，客户端passwall就没有问题。
> 
> 我找出原因了，把dns改成1.0.0.1 不要用1.1.1.1

牛逼，我今天还纳闷呢，明明在电脑上飞快的v2rayN在手机上卡成狗，改了1.0.0.1真的有用
