### ISSUE TITLE
连接成功，点击测度提示Connection closed by peer

### ISSUE THREAD

**Issue by dongbingliu** [2dust/v2rayNG#12]
HuaWei Mate 9 ，Android 9 系统，连接成功后，点击测试连接：

时间设置为与网络同步

提示：
失败：Connection closed by peer;

**Comment by dongbingliu** [comment]
多次点击测试连接：偶尔出现连接成功：延时100+毫秒

但绝大部分次数提示失败：Connection closed by peer;

**Comment by dongbingliu** [comment]
退而求其次，改用 BifrosttV 软件

**Comment by excitedbrent** [comment]
我手机上 BifrosttV  也不行，kitsunebi 也不行，不知道咋回事，你弄好了吗？怎么解决的

**Comment by gustav183** [comment]
用华为这种垃圾手机翻墙，就要忍受各种后门和翻墙干扰

**Comment by KGB333** [comment]
@keepmycode 跟你一样，最奇怪的是我其他手机都能用，就一台是这样，电脑也没问题，重装软件啥的都一样，不懂

**Comment by dongbingliu** [comment]
找商家协商给我换了一组新的节点连接正常。
