### ISSUE TITLE
功能改进

### ISSUE THREAD

**Issue by VORYTAB** [2dust/v2rayNG#120]
滑动删除节点不需要确认

**Comment by pope-L** [comment]
同恳请 增加滑动删除 确认提示

VORYTAB <notifications@github.com> 于 2018年9月16日周日 14:24写道：

**Comment by billowcbt** [comment]
同意，有时大量删除节点时每个都提示会很麻烦。
建议：做成像SSRR那样，每删除一个节点，底部提示“撤销”，发现误删可以立刻点“撤销”。
感谢作者。
