### ISSUE TITLE
v2rayNG as chromebook VPN

### ISSUE THREAD

**Issue by aou** [2dust/v2rayNG#1201]
First of all, fantastic work on this project.

I have a working config for my phone, that can also work as an android vpn on my chromebook, in that android browsers like Firefox, etc, route traffic through v2ray.

However, DNS is not working when I direct the chromebook to use v2rayNG as its VPN. IP addresses are reachable, but DNS lookups all fail. I have tried a combination of settings in v2rayNG (local DNS, etc), as well as chromebook network settings, but with no success.

Any help would be appreciated!

**Comment by yuhan6665** [comment]
logs please

**Comment by aou** [comment]
will do! for some reason did not think to look if logging was possible on a chromebook, but evidently it is. I will post tonight.

**Comment by aou** [comment]
v2rayNG log:

[v2rayng.log](https://github.com/2dust/v2rayNG/files/7035857/v2rayng.log)

**Comment by aou** [comment]
chromebook net.log:

[chromebook_net.log](https://github.com/2dust/v2rayNG/files/7035858/chromebook_net.log)

**Comment by aou** [comment]
I can confirm that using a third-party android VPN app (expressVPN, in this case) works as intended, so I know it's possible. Perhaps something in my config or combination of DNS settings on either side.

**Comment by ghost** [comment]
这种情况属于透明代理吧。
引用：
“问：在透明代理的作用中，DNS 是怎样工作的
答：取决于透明代理的形式。有些是把 DNS 作为普通流量直接转发到代理，这不受 V2ray 的 DNS 机制影响；有些通过中间组件如 redsocks，把子网内的 DNS 请求转换成 socks5 请求，这也类似流量直走，不受 V2ray 的 DNS 机制影响；有些是使用 V2ray 作为 DNS 服务端，受内置服务器的缓存和匹配影响。”
详细参阅https://guide.v2fly.org/basics/dns.html#%E9%97%AE-v2ray-%E4%BD%9C%E4%B8%BA-dns-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%97%B6%E5%80%99%E7%AE%97%E4%BB%80%E4%B9%88%E6%A8%A1%E5%BC%8F

**Comment by aou** [comment]
Thank you @cache444 ! I missed that part of the documentation; the headings don't quite match between English and Chinese. I will try it today and see.

**Comment by sgon00** [comment]
@aou Hi, I am trying to make v2rayNG work in my chromebook, but it never works. So far, I see DNS errors, chrome can not resolve any host/domain names. After reading all posts in this thread, I have no ideas what to do. Did you make it work in chromebook and how? Thanks a lot.

**Edited:**

I tried all Routing > Predefined Rules and tried to enable and disable local DNS. I just nearly tried everything. v2rayNG just never works in chromebook. 

Btw, v2rayNG works fine in my physical android phones though, just not in chromebook.

**Comment by sgon00** [comment]
@aou Please ignore my last question post. After three hours debug, I fixed my problem. I feel I am really stupid or maybe chromebook is very stupid. The problem is caused by incorrect Android date/time. Somehow, there is no `ntp_server` setup in android enviornment and the android default setup is using network provided time and has 6 minutes difference from my chromebook time. If adb debug is enabled, the ntp server can be verified by running `settings get global ntp_server` in adb shell, it returns `null`. After adding ntp server by `settings put global ntp_server pool.ntp.org` in adb shell and sync the time. My v2rayNG works fine in my chromebook.

**Comment by aou** [comment]
@sgon00 wow that's awesome! I'd stopped trying a while ago as getting this to work was an edge case anyway, but with what you discovered I'm going to try again. Thanks!

**Comment by Quartex246** [comment]
> @sgon00 I activated adb debug but I don't know how to activate the adb shell interface. I searched and it says the adb shell in a chromebook is crosh. Is that right? I also typed the commands you wrote below in the crosh, but it says settings : command not found.
