### ISSUE TITLE
一个新的错误现象

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1202]
错误现象(录屏GIF)：
![video2gif_20210822_195221](https://user-images.githubusercontent.com/89191925/130354736-f0f88345-8952-4baf-9d77-78b342c28681.gif)
如图所示，每次点进[自定义规则]进行切换规则的操作时顶部会出现如图的现象；此现象只在1.6.15之后的版本出现，也就是说目前只在1.6.16和1.6.17存在。（从我将客户端更新到1.6.16后就出现了这个现象，当时我发现后就直接卸载换回到了1.6.15。当我看到1.6.17发布后我以为应该修复了，但没想到还是存在。我现在又再次换回到了1.6.15）

补充截图：
![S10822-195344(1)](https://user-images.githubusercontent.com/89191925/130355677-f931576d-ca42-4da9-bded-b597e41a56d0.jpg)
![S10822-195400(1)](https://user-images.githubusercontent.com/89191925/130355692-d6344069-984f-4560-b32e-54d01f69487f.jpg)

这应该算是一个小错误，但对我这样的强迫症来说也太难受了，哭了。

**Comment by ghost** [comment]
复现方法：使用1.6.15以上的版本。（即1.6.16和目前最新的1.6.17）

**Comment by yuhan6665** [comment]
似乎是新的 viewpager2 造成的 我研究一下看能不能修

**Comment by ghost** [comment]
> 似乎是新的 viewpager2 造成的 我研究一下看能不能修

感谢，辛苦了

**Comment by wangyifan349** [comment]
我还没遇到这种,兄弟你用的哪个版本?

**Comment by yuhan6665** [comment]
fix in https://github.com/2dust/v2rayNG/pull/1208
