### ISSUE TITLE
最近的几个版本有明显的断流问题，

### ISSUE THREAD

**Issue by Kukuair** [2dust/v2rayNG#1205]
最近的几个版本有明显的断流问题，比如，开着略过大陆和局域网，手机访问网页时，出现图片损坏（就是图片裂开的那个小图标）的情况，需要多刷新几次才能正常显示图片，还有就是，开着略过大陆和局域网，打微信视频电话的时候也能明显感觉到卡顿，此时下拉通知栏停止v2rayng后，视频质量明显好转

**Comment by ghost** [comment]
1. 确保v2rayNG可以后台运行（例如在某些国产ROM/OS上，你需要在系统设置或自带的手机管家里允许软件后台运行+允许软件后台联网）。
2. 分流的正确操作：勾选客户端内的[启用流量探测]+[启用本地DNS]，再将[域名策略]设置为IPIfNonMatch(推荐)或IPOnDemand。此外如果你发现某些网站不能正确分流，那你可能需要手动添加自定义规则或更新geo资源文件。
3. 对于你说的微信问题，你完全可以在[分应用代理]里设置你想代理的APP或你想略过的APP。

**Comment by guoxiaochen** [comment]
开启局域网 玩游戏延迟无变化，测试不支持udp转发，应该如何修改配置信息，我是用的ss节点

**Comment by yuhan6665** [comment]
might be fixed in https://github.com/2dust/v2rayNG/pull/1218
