### ISSUE TITLE
开启了局域网代理，测试udp数据转发失败，外网网页打开正常

### ISSUE THREAD

**Issue by guoxiaochen** [2dust/v2rayNG#1206]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
希望可以支持udp转发，降低游戏延迟
### 实际行为
开启了局域网代理，玩游戏延迟无变化，测试udp数据转发失败，查了网上的资料，有的说开启dns，都尝试了还是不行
### 复现方法
1.通过网上的节点进行配置，启动本地dns和局域网代理
2.开启加速，测试延迟正常，打开网页正常，可以打开外网
3.switch配置代理模式，进入游戏，游戏延迟无变化，用pc工具测试，显示udp转发失败

### 日志信息

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android 10加速 ，pc和switch进行测试

**Comment by guoxiaochen** [comment]
![图片](https://user-images.githubusercontent.com/16371189/130889729-d34a5965-bd61-4ca9-afd8-dcf1232c7d76.png)
![图片](https://user-images.githubusercontent.com/16371189/130889769-7b50463f-0ba5-440f-b299-2cb8f3786e09.png)
![图片](https://user-images.githubusercontent.com/16371189/130891237-2eb80ceb-8fd4-4709-95be-e31007732cf0.png)

这个是手机端配置信息 日志和测试结果

**Comment by ghost** [comment]
1. 需要你的服务器本身支持；如果你在用机场，那你应该询问机场是否支持（有些机场会提供专用于游戏的节点/专线）。
2. 你应该是用NG来共享代理给局域网内的设备使用(这就好比你用一台未插卡/不能上网的手机去连接一个能上网的wifi，连接后手机的所有网络流量都会被该wifi的网关接管)，这种方式已经实现了“真全局”，所以针对你要代理的设备来说，不需要任何配置就已经是全局模式了。
3. NG是基于SOCKS5的代理软件，SOCKS5只能代理会话层上的应用；有些游戏是跑在传输层，所以无论你开不开全局都无法代理传输层的流量(例如LOL)。
4. 如果你是手机游戏，用VPN或支持游戏代理的服务器(机场)可解；如果你是电脑游戏，用VPN或v2rayN+SSTap或Netch可解。

**Comment by guoxiaochen** [comment]
> 
> 
>     1. 确认你的服务器支持代理游戏流量；如果你在用机场，那你应该询问机场是否支持（例如有些机场会提供专用于游戏的节点/专线）。
> 
>     2. 你应该是用NG来共享代理给局域网内的设备使用(这就好比你用一台未插卡/不能上网的手机去连接一个能上网的wifi，连接后手机的所有网络流量都会被该wifi的网关接管)，这种方式已经实现了“真全局”，所以针对你要代理的设备来说，不需要任何配置就已经是全局模式了。
> 
>     3. NG是基于SOCKS5的代理软件，SOCKS5只能代理会话层上的应用；有些游戏是跑在传输层，所以无论你开不开全局都无法代理传输层的流量(例如LOL)。
> 
>     4. 如果你是手机游戏，用VPN或支持游戏代理的服务器(机场)可解；如果你是电脑游戏，用VPN或v2rayN+SSTap或Netch可解。

情况一：我在switch上玩游戏，Android手机开的NG,然后共享给swich，如果inbounds使用http 游戏能进去，如果使用socks，设备提示检测网络异常
情况二 ：Android手机开的NG,开启局域网，其他Android手机配置这个网络，使用inbounds使用访问网页正常，inbounds使用socks 提示没有网络，不能访问网页

**Comment by ghost** [comment]
@guoxiaochen NG开启允许局域网连接，然后打开手机热点给switch连上，switch的wifi设置里把主机/网关IP改为手机的IP，端口改为socks(10808)，试试看。

**Comment by ghost** [comment]
@guoxiaochen 你再试试NG设置里把socks5代理端口改下(10808~65535之间，例如改成19919)，然后switch里端口同样改和NG的socks5端口一致。如果还是不行，那应该就是服务器的问题了

**Comment by guoxiaochen** [comment]
> 
> 
> @guoxiaochen 你再试试NG设置里把socks5代理端口改下(10808~65535之间，例如改成19919)，然后switch里端口同样改和NG的socks5端口一致。如果还是不行，那应该就是服务器的问题了

第二个手机端口改成socks(18888)网络都不通，第二个手机使用http（18889）网页正常 ，线路 ： vmess://eyJob3N0IjoiamlrZTEtcnUwOC5kZG5zLW9ubHkueHl6IiwicGF0aCI6Ii9qaWtlIiwidGxzIjoiIiwidmVyaWZ5X2NlcnQiOnRydWUsImFkZCI6Imppa2UxLXJ1MDguZGRucy1vbmx5Lnh5eiIsInBvcnQiOjMxMDA0LCJhaWQiOjIsIm5ldCI6IndzIiwiaGVhZGVyVHlwZSI6Im5vbmUiLCJ2IjoiMiIsInR5cGUiOiJ2bWVzcyIsInBzIjoiSksxLeaWsOWKoOWdoeWFjei0uXYycmF5IiwicmVtYXJrIjoiSksxLeaWsOWKoOWdoeWFjei0uXYycmF5IiwiaWQiOiIyYzNhNDc2Ni1mYjJjLTNlNGMtOTMzMy1iZDZiYTcyMzVlMDciLCJjbGFzcyI6MH0=     以下是配置文件
  {
  "stats":{},
  "log": {
    "loglevel": "warning"
  },
  "policy":{
      "levels": {
        "8": {
          "handshake": 4,
          "connIdle": 300,
          "uplinkOnly": 1,
          "downlinkOnly": 1
        }
      },
      "system": {
        "statsOutboundUplink": true,
        "statsOutboundDownlink": true
      }
  },
  "inbounds": [{
    "tag": "socks",
    "port": 18888,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "userLevel": 8
    },
    "sniffing": {
      "enabled": true,
      "destOverride": [
        "http",
        "tls"
      ]
    }
  },
  {
    "tag": "http",
    "port": 18889,
    "protocol": "http",
    "settings": {
      "userLevel": 8
    }
  }
],
  "outbounds": [{
    "tag": "proxy",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "v2ray.cool",
          "port": 10086,
          "users": [
            {
              "id": "a3482e88-686a-4a58-8126-99c9df64b7bf",
              "alterId": 64,
              "security": "auto",
              "level": 8
            }
          ]
        }
      ],
      "servers": [
        {
        "address": "v2ray.cool",
        "method": "chacha20",
        "ota": false,
        "password": "123456",
        "port": 10086,
        "level": 8
      }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "wsSettings": {
        "path": "/e75500"
      }
    },
    "mux": {
      "enabled": true,
      "concurrency": 8
    }
  },
  {
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  },
  {
    "protocol": "blackhole",
    "tag": "block",
    "settings": {
      "response": {
        "type": "http"
      }
    }
  }
  ],
  "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": []
  },
  "dns": {
      "hosts": {},
      "servers": []
  }
}

**Comment by ghost** [comment]
@guoxiaochen 我刚才用firefox测试了在本机(127.0.0.1)上，NG的http和socks5都没有问题，无论是VPN模式还是仅代理模式。可以确定不是NG的问题。

然后对于你的问题我也忽略了一点，那就是应用本身不能手动配置socks代理，你连接NG后系统的wifi设置也只能是http端口，比如在仅代理模式下，telegram可以手动配置走socks5，但其它应用就不行，在同一模式下，其它要走udp的应用自然就会挂，而telegram不会挂。所以这样一来你还是直接通过路由器翻墙来操作吧。如果你手机已root，可以用“vpn热点”来重新分享手机网络，在google play可以找到相关应用。

**Comment by guoxiaochen** [comment]
> 
> 
> @guoxiaochen 我刚才用firefox测试了在本机(127.0.0.1)上，NG的http和socks5都没有问题，无论是VPN模式还是仅代理模式。可以确定不是NG的问题。
> 
> 然后对于你的问题我也忽略了一点，那就是应用本身不能手动配置socks代理，你连接NG后系统的wifi设置也只能是http端口，比如在仅代理模式下，telegram可以手动配置走socks5，但其它应用就不行，在同一模式下，其它要走udp的应用自然就会挂，而telegram不会挂。所以这样一来你还是直接通过路由器翻墙来操作吧。如果你手机已root，可以用“vpn热点”来重新分享手机网络，在google play可以找到相关应用。

哦，明白了，你的意思就是switch上配置只有http的配置，没有配置socks地方，所以不行，那如果用ng的http    udp数据可以正常代理吗 我ng配置这样     {
      "tag": "http",
      "port": 18889,
      "protocol": "http",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },

**Comment by ghost** [comment]
@guoxiaochen 抱歉我无法在这方面给你更多帮助，因为我本身没有过这方面的需求。唯一能确定的是这个问题和v2rayNG无关，Android上其它支持局域网共享的代理软件(ss/clash等)你会发现也一样无法解决你这个问题。你还是试试去搜索如何代理switch相关的内容看能不能找到答案吧~

**Comment by guoxiaochen** [comment]
> 
> 
> @guoxiaochen 抱歉我无法在这方面给你更多帮助，因为我本身没有过这方面的需求。唯一能确定的是这个问题和v2rayNG无关，Android上其它支持局域网共享的代理软件(ss/clash等)你会发现也一样无法解决你这个问题。你还是试试去搜索如何代理switch相关的内容看能不能找到答案吧~

好的，我也是看了一个youtube视频 说的可以才尝试的

**Comment by rojunghwa** [comment]
你关掉局域代理，试试谷歌商店里有个叫Every proxy的软件，如果还是不行就和v2rayng无关

**Comment by farzad17** [comment]
> 在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
> 
> ### 预期行为
> 希望可以支持udp转发，降低游戏延迟
> 
> ### 实际行为
> 开启了局域网代理，玩游戏延迟无变化，测试udp数据转发失败，查了网上的资料，有的说开启dns，都尝试了还是不行
> 
> ### 复现方法
> 1.通过网上的节点进行配置，启动本地dns和局域网代理
> 2.开启加速，测试延迟正常，打开网页正常，可以打开外网
> 3.switch配置代理模式，进入游戏，游戏延迟无变化，用pc工具测试，显示udp转发失败
> 
> ### 日志信息
> 通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。
> 
> 如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
> 
> ```
> 在这里粘贴日志
> ```
> 
> ### 环境信息
> Android 10加速 ，pc和switch进行测试
> 
> ### 额外信息（可选）
