### ISSUE TITLE
反馈问题，这个app经常要自动断开连接,手动重连，多次重连还连不上。

### ISSUE THREAD

**Issue by honghongtu** [2dust/v2rayNG#121]
反馈问题，这个app经常要自动断开连接,手动重连，多次重连还连不上。

**Comment by 2dust** [comment]
先看是否锁定app和电池优化
其他的就没有了

**Comment by honghongtu** [comment]
> 先看是否锁定app和电池优化
> 其他的就没有了

我发现只要在通知栏系统提示的vpn通知关掉vpn就没这毛病。
