### ISSUE TITLE
关于v2rayNG的连接后的限速

### ISSUE THREAD

**Issue by c954825** [2dust/v2rayNG#1215]
经过测试，同一个设备，同一个网络，同一个节点的测速情况下来看。v2rayNG一直是无法突破300Mbps，而clash则是可以完全跑满500Mbps。v2rayNG一直最多就是295Mbps左右。这是什么问题?

**Comment by cache444** [comment]
Android：在同一设备/同一网络/同一节点(配置)的情况下，最快的是Surfboard⁽¹⁾，其次是Clash⁽²⁾；v2rayNG⁽³⁾比Kitsunebi⁽⁴⁾快一点。

不知道具体原因。
