### ISSUE TITLE
Feature Request: 允许自定义bypass_private_ip_address

### ISSUE THREAD

**Issue by ccaapton** [2dust/v2rayNG#1216]
在开启fakedns后，我们可以把需要代理的domain全部fake至ipPool中，把ipPool 加入到bypass_private_ip_address，这样就可以大量减少bypass_private_ip_address的覆盖范围，使得不需要代理的连接直连上游，而不需要走tun2socks，从而使网速更快耗电更少。

**Comment by yuhan6665** [comment]
嗯 这种方法理论上可行 不知道实际使用会不会有问题

**Comment by ccaapton** [comment]
我用root强行修改tun0的路由表，把自带的bypass_private_ip_address里面的条目都删掉，只保留fakedns ipPool, 运行了两天没啥异常.

**Comment by ccaapton** [comment]
这个需求可以考虑下吗? 拜托了 @yuhan6665

**Comment by yuhan6665** [comment]
这样做实际上是把分流功能移到 DNS 模块处理 但是我怀疑这个分流的精确度可能不如 routing 必须要做成可选项 而且要让用户知道会影响某些自定义路由的功能
Ng 的一个目标是保持简单 所以我倾向不加
