### ISSUE TITLE
可否增加按ping结果进行排序的功能呢？ 前边有人提，但没看见有反馈。

### ISSUE THREAD

**Issue by yeslsl** [2dust/v2rayNG#1217]

**Comment by ghost** [comment]
NG里的[测试全部Tcping]实际上没什么用，[测试全部配置真连接]才是真正有用的东西。其实无论是Tcping还是真连接的测试结果都只能用于参考，并不代表节点实际使用上的延时和上下行速率，不能以测试结果来判断节点。（举个例子：比如某个节点的延时很低，但有可能下行速率很慢，而某个节点的延时很高，但下行速率反而很快；又比如Tcping能通的节点有可能连接后完全不能用。）只要不是真小白应该都知道这些。

对于你说的按速度排序的话，取决于开发者吧。我个人觉得这个功能是可有可无的，因为NG主界面直接就一目了然的展示了各个配置/节点，在手动测试Tcping或真连接后是完全能自己按速度选择使用的。不过在节点很多的情况下是会让人觉得有点难以甄选。

**Comment by yeslsl** [comment]
> NG里的[测试全部Tcping]实际上没什么用，[测试全部配置真连接]才是真正有用的东西。其实无论是Tcping还是真连接的测试结果都只能用于参考，并不代表节点实际使用上的延时和上下行速率，不能以测试结果来判断节点。（举个例子：比如某个节点的延时很低，但有可能下行速率很慢，而某个节点的延时很高，但下行速率反而很快；又比如Tcping能通的节点有可能连接后完全不能用。）只要不是真小白应该都知道这些。
> 
> 对于你说的按速度排序的话，取决于开发者吧。我个人觉得这个功能是可有可无的，因为NG主界面直接就一目了然的展示了各个配置/节点，在手动测试Tcping或真连接后是完全能自己按速度选择使用的。不过在节点很多的情况下是会让人觉得有点难以甄选。
