### ISSUE TITLE
在MIUI12.5中无法使用通知栏中的开关打开代理

### ISSUE THREAD

**Issue by qmgta** [2dust/v2rayNG#1219]
### 预期行为
点击通知栏中的 v2ray 开关应该可以打开代理

### 实际行为
实际上只会弹出正在启动服务的提示，但是无法启动

### 复现方法
直接点击通知栏中的开关，就会弹出启动服务中的提示，但是代理是无法开启的。如果已经打开了软件，然后再去点击开关就是有效的；如果将软件关闭，等待一段时间，再去点击开关就又失效了。

### 环境信息
手机：Redmi K20 Pro Premium Edition
系统：MIUI 12.5.5

**Comment by yuhan6665** [comment]
大概是需要关闭电池优化

**Comment by qmgta** [comment]
> 大概是需要关闭电池优化

因该和电池优化没有关系，因为在MIUI 11中就没有这样的问题

**Comment by dzhchina** [comment]
同样的问题

**Comment by BelieveDa** [comment]
12.0.8没有什么问题 自从到了12.5.6之后问题就来了 12.5.6 之前版本不知道  一般通知栏启用长按才可以   电池优化 锁屏白名单  自启动 全部权限打开都没用 这是个遗留性问题

**Comment by yuhan6665** [comment]
看来是个 MIUI 新问题，也许能跟小米反馈一下。。

**Comment by qmgta** [comment]
或许是安卓11的问题？MIUI 12.5 升级了安卓11。

**Comment by yuhan6665** [comment]
我试了一下在三星安卓11无法复现

**Comment by BelieveDa** [comment]
具体跟什么有关系说不上来  我刷完机后就不行了 刷机前是没问题的  一定程度上可能跟miui有关

**Comment by qmgta** [comment]
怎么样才能知道到底是哪里出现了问题呢？点击开关之后到底发生了什么？

**Comment by yuhan6665** [comment]
> 怎么样才能知道到底是哪里出现了问题呢？点击开关之后到底发生了什么？

https://github.com/2dust/v2rayNG/blob/2d5351ec9ee35f8b186dadf1b8701b236528837f/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt#L81
也许是禁用了背景启动 service

**Comment by qmgta** [comment]
有可能，我试了其他的软件也不能正常使用

**Comment by alexmaze** [comment]
权限管理里开启 “后台弹出界面” 权限就好了

**Comment by qmgta** [comment]
> 权限管理里开启 “后台弹出界面” 权限就好了

没用啊，跟没开一样

**Comment by laggage** [comment]
~~同样的问题+1~~

~~重新安装了最新版本后可以了~~

省电策略调整为无限制可以正常使用

**Comment by BelieveDa** [comment]
开发版9.1  省电策略选择无限制，没什么问题  当然我的后台弹出界面是允许的。

**Comment by qmgta** [comment]
突然发现省电策略改成无限制后功能正常了，我没有打开后台弹出界面的权限

**Comment by ShadowTeamCN** [comment]
> ~同样的问题+1~
> 
> ~重新安装了最新版本后可以了~
> 
> 省电策略调整为无限制可以正常使用

感谢，设置之后正常
