### ISSUE TITLE
客户端配置消失

### ISSUE THREAD

**Issue by betaback** [2dust/v2rayNG#122]
### 实际行为
客户端服务器配置全部消失，需要重新填写，分应用代理配置也全部还原了

### 复现方法
完全随机，已出现多次

### 日志信息

日志也自己清空了，没有贴在这里的任何价值
### 环境信息
一加5t 氢os5.1.3

**Comment by tigren** [comment]
同样的情况，手机自动重启，之后发现所有配置都消失了

系统 原生6.1
