### ISSUE TITLE
可否跳过局域网时，允许部分局域网走代理

### ISSUE THREAD

**Issue by muziling** [2dust/v2rayNG#1220]
比如设置了绕过大陆和局域网，是否可以设置192.168.66.0/24 走代理，感觉就是自定义的优先级比绕过局域网高就行。

**Comment by ghost** [comment]
我个人对v2rayNG[自定义规则]和[预定义规则]的优先级也不是很清楚，不过可以肯定的是[预定义规则]对小白和新手来说很友好，对不想折腾规则只喜欢简单直接的用户来说也很友好。

或许可以在预定义规则里添加如下(PS图示)选项？：
![1630893037518](https://user-images.githubusercontent.com/89191925/132150354-8049ab6a-2c0b-4d9c-ae06-b4d081bcc6d5.png)

不知道是否可行或者是否会带来其他问题，所以仅仅是设想。
@yuhan6665

**Comment by muziling** [comment]
> 我个人对v2rayNG[自定义规则]和[预定义规则]的优先级也不是很清楚，不过可以肯定的是[预定义规则]对小白和新手来说很友好，对不想折腾规则只喜欢简单直接的用户来说也很友好。
> 
> 或许可以在预定义规则里添加如下(PS图示)选项？：
> ![1630893037518](https://user-images.githubusercontent.com/89191925/132150354-8049ab6a-2c0b-4d9c-ae06-b4d081bcc6d5.png)
> 
> 不知道是否可行或者是否会带来其他问题，所以仅仅是设想。
> @yuhan6665

有另一个选项配置自定义的白名单和黑名单的呀， 只要这里自定义的优先级高就行，类似iptables -I最前插入, 不要 iptables -A最后追加

**Comment by yuhan6665** [comment]
自定义的规则是高于预定义的，你们可以导出完整配置看一下就能明白了。
但是有一个是例外，预定义绕过局域网是在 vpn service 绕过的，会导致优先级最高，所以，要代理 192.168.x.x 必须选择全局或者绕过大陆，然后在自定义里面加规则

**Comment by ghost** [comment]
> 自定义的规则是遥远的预定义，你们可以导出完整的配置一下明白了。
> 但是是特殊的，预定义的服务是在vpn导致的绕过的，会优先级最高，所以，要代理92.16xx xx 必须选择绕过8.大陆，然后在自定义里面加规则

明白啦，感谢
