### ISSUE TITLE
三星W21（Galaxy Z Fold2 5G）三星Galaxy Z Flip3 5G（SM-F7110）用v2rayNG在APP内无法登陆Google账号

### ISSUE THREAD

**Issue by lijinyu619** [2dust/v2rayNG#1223]
国行三星W21（Galaxy Z Fold2 5G）三星Galaxy Z Flip3 5G（SM-F7110）用v2rayNG在APP内无法登陆Google账号
网页版登陆没问题
无论在设置里面的Google服务、Google play、YouTube都无法登陆Google账号。
使用其他翻墙软件可以登陆
在小米手机用同样的设置可以登陆
使用过编辑规则等方法都失败

**Comment by BozhanL** [comment]
https://github.com/2dust/v2rayNG/issues/503#issuecomment-662232378
试一下

**Comment by lijinyu619** [comment]
> [#503 (comment)](https://github.com/2dust/v2rayNG/issues/503#issuecomment-662232378)
> 试一下

感谢回复  目前无论用分应用代理还是全局代理都无法访问

**Comment by lijinyu619** [comment]
> [#503 (comment)](https://github.com/2dust/v2rayNG/issues/503#issuecomment-662232378)
> 试一下

已经试过  没有效果

**Comment by gcphym** [comment]
#1234

**Comment by sueeeeeeeeee** [comment]
一样的问题  我是国行三星s21

**Comment by yan2035** [comment]
我也是国行三星，用vpn就可以，用节点就不行，

**Comment by ouguajian** [comment]
国行S20一样问题
