### ISSUE TITLE
编译AndroidLibV2rayLite生成libv2ray.aar替换后编译v2rayNG失败

### ISSUE THREAD

**Issue by sunlewuyou** [2dust/v2rayNG#1225]
### 编译了 AndroidLibV2rayLite，并将最新的 libv2ray.aar 替换到 v2rayNG 项目中，构建时报错如下： 
![image](https://user-images.githubusercontent.com/19728435/133017798-1343897c-ea89-42e0-8477-b7966733419f.png)

这个问题与我情况相同：https://github.com/2dust/v2rayNG/issues/864#issue-796131104

请问大家伙知道是什么原因导致的吗？网上各种搜索研究了2天也是不行，还请有经验的各位大神指点一下问题出在哪里，不胜感激~~~

**Comment by sunlewuyou** [comment]
### v2rayNG编译后默认内核版本为v1.0.2
![image](https://user-images.githubusercontent.com/19728435/133024338-b693ee03-bf81-4502-a85d-5fa547257868.png)

### 如果编译出最新的 libv2ray.aar 替换到 v2rayNG 项目中成功编译出来的apk版本是否为最新版的`v1.6.18`呢？

**Comment by sunlewuyou** [comment]
### 突然发现原来是闭源了，原本因为手机未root，无法更新geo才选择自行编译的，两天熬夜折腾终究无果~~~
https://github.com/2dust/v2rayNG/issues/982
**在此提醒一下后来者吧**

**Comment by chickmy** [comment]
我把aar编译了最新，也发现连接不上服务器，在谷歌下载的版本能连接

**Comment by frugerard** [comment]
你可不可以给我外链吗？
