### ISSUE TITLE
Not working after upgrade to 1.6.20 in google play

### ISSUE THREAD

**Issue by mactrash** [2dust/v2rayNG#1227]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Not working after upgrade to 1.6.20 

### 实际行为
1.6.15 working well by Not working after upgrade to 1.6.20 

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by crackevil** [comment]
having the same issue right now
older versions tested, 19 also failed, 18 works fine

**Comment by lfxx** [comment]
> having the same issue right now
> older versions tested, 19 also failed, 18 works fine

Same problem here
