### ISSUE TITLE
Cannot connect with Always-on VPN on boot if using a domain name instead of IP.

### ISSUE THREAD

**Issue by lss4** [2dust/v2rayNG#1229]
If using a domain name instead of IP address (e.g. behind Cloudflare), v2rayNG (also applies to v2flyNG) cannot connect to the server on boot, and will stop itself after several attempts. On the surface it looks like DNS related issues.

The issue doesn't occur if using IP address directly. However, the traffic will not go through Cloudflare this way.

### 预期行为
The system should correctly connect to the v2ray server on boot.

### 实际行为
The network is not usable on boot as v2rayNG kept failing to resolve the domain name. A few seconds later v2rayNG will stop itself. As I also turned on "Always-on VPN" and "Block connections without VPN", a notification saying that I'm "disconnected from Always-on VPN" will appear and the device cannot connect to the Internet (since non-VPN connections are blocked by the other option).

### 复现方法
1. Configure a v2rayNG entry using a domain (for Cloudflare).
2. Connect to the service and enable "Always-on VPN" and "Block connections without VPN".
3. Reboot and see if you can connect using v2rayNG right after boot.

### 日志信息
<details>

The logcat shows it keeps trying to resolve the domain name, with this log entry (domain name replaced) as well as several connection attempts to the DNS servers you configured.
```
Dial pending prepare ... www.example.com:443
```

After several seconds (it can be as long as several minutes), it'll complain about DNS resolution timing out.
```
PrepareDomain err: i/o timeout
```

And eventually it exceeded the retry count and stopped itself, followed by the same usual shutdown/teardown logs seen when you disconnect v2rayNG.
```
PrepareDomain maxRetry reached. exiting.
```

</details>

### 环境信息
Android 11

### 额外信息（可选）
The reproducibility of the issue probably depends on the network environment and the DNS server used. In my place this issue is nearly 100% reproducible on several different devices of mine (all running Android 11).

In most cases I could properly connect to the v2ray server after restarting the service, so it's not really a major issue, but it looks like there are some kind of race condition going on during boot.

Don't know if anyone has reported similar issues before, as I'm not sure if the issue is caused by v2rayNG, or is due to a bug in Android's Always-on VPN logic.

**Comment by yuhan6665** [comment]
Sounds like a bug in NG's logic to resolve vps ip. If NG got an error at beginning, it might not work until you stop and restart.
At the moment you can try use Cloudflare's ip with your sni.

**Comment by lss4** [comment]
> Sounds like a bug in NG's logic to resolve vps ip. If NG got an error at beginning, it might not work until you stop and restart.
> At the moment you can try use Cloudflare's ip with your sni.

Cloudflare IP is dynamic. Every time I access my VPS via Cloudflare I get a different IP.

Personally, I think it's best to retry on domain resolve infinitely (and clean DNS cache if necessary). For now it looks like v2rayNG is only trying to resolve the domain for a finite amount of time before giving up.

Another trivially reproducible case would be: I have SIM lock enabled and didn't unlock SIM and phone as early as possible on boot (so no network until I unlock SIM). In this case, by the time I unlocked the phone v2rayNG has already tried enough times and gave up so I would immediately see "Disconnected from Always-on VPN" and have to start the app manually.

**Comment by iopq** [comment]
Same here, I either have to turn it and off, or switch to another server
