### ISSUE TITLE
安卓首次安装，无法点击右下角的启动开关

### ISSUE THREAD

**Issue by tandalin** [2dust/v2rayNG#123]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
V2NG右下角开关无法打开，点了没反应

### 复现方法
1.红米5A，MIUI10.3
2.没开护眼模式
3.没额外安装杀毒

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by tandalin** [comment]
> 在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
> 
> ### 预期行为
> 描述你认为应该发生什么
> 
> ### 实际行为
> V2NG右下角开关无法打开，点了没反应
> 
> ### 复现方法
> 1.红米5A，MIUI10.3（骁龙425）
> 2.没开护眼模式
> 3.没额外安装杀毒
> 安装【app-armeabi-v7a-release.apk】用不了，然后换了【app-universal-release.apk】也用不了
> ### 日志信息
> ### 环境信息
> ### 额外信息（可选）

**Comment by NKUCodingCat** [comment]
360n6 也遇到同样的问题【谷歌play安装或release均不能成功】，安卓7.1.1，骁龙636，shadowsocks一直用没有问题

**Comment by tandalin** [comment]
> 360n6 也遇到同样的问题【谷歌play安装】

你手机是什么型号？

**Comment by NKUCodingCat** [comment]
回复楼上，360N6 6+64G版本，我手机不知道怎么引用

**Comment by huoshan017** [comment]
最新的1.1.2是有问题，换成1.1.1没问题

**Comment by 2dust** [comment]
1.1.2和1.1.1基本无区别,只是改进了一个分应用的小问题
所以这种还是rom的问题

**Comment by JaeZheng** [comment]
小米9 MIUI10 安装1.1.1版本连接后上不了，报错unexpected end of stream on com.android.okhttp.Address@xxxxxx。有遇到同样问题的老铁吗？

**Comment by lweo** [comment]
同360手机，好像现在国产手机对翻墙软件有限制…翻墙还得另外买个国外手机，真是蛋疼…

**Comment by lweo** [comment]
@2dust 这是不是跟创建vpn权限有关？试了bifrostv ，也是同样的现象，点右下角，抛出“Permission denied to create a VPN service

**Comment by lweo** [comment]
折腾一晚上终于找到问题所在！跟翻墙软件和ROM无关，其实是一个很简单的系统设置问题！“开启始终此VPN ”后，意味着VPN 被此app锁定，其他app将无法开启vpn，有的翻墙软件会报vpn权限被拒绝。
解决办法就是 关闭始终此vpn！！
@2dust

**Comment by wujinkui** [comment]
我也遇到了这个问题，同红米手机，我描述一下哈，不知道是不是你的意思，下载ss或者ssr以后连接VPN，会弹出一个让你确定的弹窗，点击右下角的确定没有反应，所以无法创建VPN。

这个问题其实跟vpn完全无关，长按ss或者ssr，然后选择应用信息，点击权限管理，然后允许后台弹出界面，确定就可以点击了

**Comment by Kongsea** [comment]
> 我也遇到了这个问题，同红米手机，我描述一下哈，不知道是不是你的意思，下载ss或者ssr以后连接VPN，会弹出一个让你确定的弹窗，点击右下角的确定没有反应，所以无法创建VPN。
> 
> 这个问题其实跟vpn完全无关，长按ss或者ssr，然后选择应用信息，点击权限管理，然后允许后台弹出界面，确定就可以点击了

我试了你这个方法，还是不可以。

**Comment by gjzzh1640** [comment]
在权限管理里开启悬浮窗和后台弹出
