### ISSUE TITLE
Android 12 系统使用 V2ray 导入“Geo 资源文件”时闪退

### ISSUE THREAD

**Issue by DustinWin** [2dust/v2rayNG#1232]
手机系统版本：Android 12（MIUI 12.5 21.9.18）
V2ray 版本：1.6.22（Lib v23，Xray-core v1.4.5）

### 复现方法
1. 进入应用首页-->左上角“☰”图标-->Geo 资源文件；
2. 点击右上角“+”图标。

### 预期行为
能够正常进入手机文件管理，并选择 Geo 资源文件。

### 实际行为
没有进入手机文件管理，无法选择 Geo 资源文件，应用回到首页。

**Comment by Gokou-Ruri** [comment]
我是用su定期自动下载更新geoip/geosite的，然后用tasker force-stop v2的进程再重新连接v2，如果你是开发版（自带root）可以试试这个办法，比手动导入更好一些。

**Comment by DustinWin** [comment]
> 我是用su定期自动下载更新geoip/geosite的，然后用tasker force-stop v2的进程再重新连接v2，如果你是开发版（自带root）可以试试这个办法，比手动导入更好一些。

谢谢，我去学习学习，还没搞过。可否提供一下关键词？

**Comment by sunlewuyou** [comment]
最新稳定版miui，点击Geo“+”图标就闪一下，无法正常打开文件管理器。不知有多少小伙伴是这样。miui的体验感越来越差了，升级12.5之后连谷歌商店都用不了了。

**Comment by yuhan6665** [comment]
在设置中给与文件权限试试

**Comment by DustinWin** [comment]
> 最新稳定版miui，点击Geo“+”图标就闪一下，无法正常打开文件管理器。不知有多少小伙伴是这样。miui的体验感越来越差了，升级12.5之后连谷歌商店都用不了了。

我的就是这样，同 MIUI。不过谷歌商店没有遇到跟你一样的问题。

**Comment by DustinWin** [comment]
> 在设置中给与文件权限试试

我就放在很普通的“Download”文件夹下。

**Comment by geol** [comment]
直接复制到/storage/emulated/0/Android/data/com.v2ray.ang/files/assets即可。

**Comment by DustinWin** [comment]
> 直接复制到/storage/emulated/0/Android/data/com.v2ray.ang/files/assets即可。

“data”文件夹内的所有子文件夹都不能粘贴文件，不过问题已经解决了。

**Comment by cqwuzonglin** [comment]
手机 Android 12 MIUI 12.5 
APP 1.6.26
GEO资源文件下只有安装自带的geoip.dat,geosite.dat
点加号 能选择到下载的文件 但是选择后 GEO资源文件下无变化,没有刚选的文件

**Comment by cqwuzonglin** [comment]
> /storage/emulated/0/Android/data/com.v2ray.ang/files/assets 这个目录需要二次授权 而这个app没做
Es文件浏览器上能二次授权  已成功更新geo

**Comment by denglianwei** [comment]
> 最新稳定版miui，点击Geo“+”图标就闪一下，无法正常打开文件管理器。不知有多少小伙伴是这样。miui的体验感越来越差了，升级12.5之后连谷歌商店都用不了了。

同样的问题 我用其他软件替代了，还能用
