### ISSUE TITLE
通过adguard连接代理，游戏频繁断线

### ISSUE THREAD

**Issue by Gokou-Ruri** [2dust/v2rayNG#1233]
### 实际行为
我是采用Adguard + v2rayNG的模式科学上网的，Adguard通过root+连接代理模式，v2rayNG选择仅代理，玩宝可梦大集结（jp.pokemon.pokemonunite）时，游戏几秒或十几秒就会重连一次（下方截图）。Adguard没有过滤宝可梦大集结的广告，只对它开启了路由（连接到v2rayNG的代理）。
补充：因为直接用v2rayNG开启VPN模式，宝可梦大集结会识别出VPN，提示“很抱歉,您所在的地区无法登录该游戏。”，所以只能用adguard的代理模式把宝可梦大集结挂到v2rayNG上去。
补充2：Adguard代理里连接的是socks5（v2rayNG），并勾选了udp流量走代理，不勾选的话宝可梦大集结也会提示“所在地区无法登录”。
补充3：并不只是宝可梦大集结会这样，还有其它游戏也这样，所以我猜应该和游戏本身没什么关系。

### 预期行为
我不确定这个情况是不是v2rayNG的问题（也有可能是Adguard的问题），所以发个issue问一下各位有没有和我一样的情况，寻求一下解决办法。再加上我不清楚除了Adguard以外还有什么其它的可以把APP流量转发到v2rayNG的流量过滤程序，如果有其它的软件就可以测试一下是不是Adguard的bug了。

### 问题截图
![Screenshot_20210924-151617_Pokémon_UNITE~01](https://user-images.githubusercontent.com/26711804/134638692-8b90f1a1-66b0-4926-9954-8c47aa618f2f.png)

### 日志信息
清空日志以后，用su执行`logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main > /sdcard/udp.txt`，然后开着游戏放置几分钟，日志如下：
[udp.txt](https://github.com/2dust/v2rayNG/files/7224028/udp.txt)

### 环境信息
Android 11 类原生自定义ROM
v2rayNG 版本 1.6.22
Adguard 版本 3.6.32(stable) & 4.0.65(nightly) 问题相同

**Comment by cache444** [comment]
“ 因为直接用v2rayNG开启VPN模式，宝可梦大集结会识别出VPN，提示“很抱歉,您所在的地区无法登录该游戏。” ”

我有点懵，因为adguard本身也是通VPN来作用的，你打开adguard和打开v2rayng都一样需要启用vpn，如果游戏是因为检测到你的设备启用了vpn而阻止你继续，那就不太合理了。有没有可能是节点的问题？(你参考下Netflix，如果你的节点本身就不行，Netflix也会提示“检测到你在用VPN/代理”，从而无法正常使用，但换用“没问题”的节点则不会有任何提示便可正常使用)

另外，基于socks5的代理软件(NG就是之一)无法代理或无法正常代理游戏流量也是正常的，我之前玩其他国家的手游也差不多像你这样，断流啥的。你换成VPN软件，选一个日本的服务器连接后你会发现一切都正常了

**Comment by Gokou-Ruri** [comment]
> “ 因为直接用v2rayNG开启VPN模式，宝可梦大集结会识别出VPN，提示“很抱歉,您所在的地区无法登录该游戏。” ”
> 
> 我有点懵，因为adguard本身也是通VPN来作用的，你打开adguard和打开v2rayng都一样需要启用vpn，如果游戏是因为检测到你的设备启用了vpn而阻止你继续，那就不太合理了。有没有可能是节点的问题？(你参考下Netflix，如果你的节点本身就不行，Netflix也会提示“检测到你在用VPN/代理”，从而无法正常使用，但换用“没问题”的节点则不会有任何提示便可正常使用)
> 
> 另外，基于socks5的代理软件(NG就是之一)无法代理或无法正常代理游戏流量也是正常的，我之前玩其他国家的手游也差不多像你这样，断流啥的。你换成VPN软件，选一个日本的服务器连接后你会发现一切都正常了

谢谢您的解答！上文说过“Adguard通过root+连接代理模式”，我的Adguard并不是用VPN模式。
Adguard的VPN确实不会被宝可梦大集结判定为“代理程序”，但我用当前节点能登录宝可梦大集结，所以节点本身肯定没有问题，并且之前我曾尝试更换其它地区节点但在v2rayNG的VPN模式下依旧无法登录，而adguard+v2rayNG代理则可以登录，我下载的是国际服，并不是日服，所以并不需要日本IP。

无论Adguard使用root路由还是VPN模式均可玩，但由于我需要用国内加速器加速一些国内游戏，所以Adguard和v2rayNG都不能选VPN模式，否则加速器就开不了了。另外还有极个别软件检测到任何VPN都不允许使用，所以我才尽量避免使用VPN模式。

**Comment by xiaorong61** [comment]
会不会是你的线路不支持 udp？
比如我用的 jms 只有 shadowsocks 线路才支持 udp： 
![image](https://user-images.githubusercontent.com/5251387/217129847-feb2e855-dfe2-477a-b558-e6476e265a92.png)
