### ISSUE TITLE
自动生成的 "domain:googleapis.cn": "googleapis.com" 导致无法下载play商店软件

### ISSUE THREAD

**Issue by GeorgeRudd** [2dust/v2rayNG#1234]

**Comment by cache444** [comment]
![IMG_20210924_183614](https://user-images.githubusercontent.com/89191925/134661620-61e46880-653a-4d73-b6cb-ad733d763763.jpg)

清空所有自定义规则（其实自定义规则只需要配置直连的网址/IP就行了），然后预定义直接全局。如图，我用v2rayNG一般就这样勾选和设置的，google play随时秒更新秒下载，你这个问题其实有不少人都说过，其实就是你们自己的配置问题，比如你现在试试分应用代理，再选择绕行模式，勾选需要绕掉的APP(微信QQ啥的)，我猜就能正常了，因为下载是要依赖系统的下载管理和下载管理服务组件的(在不同的设备，名称可能会有差异)，如果下载管理和下载管理服务没有被代理，那无法下载就很正常了。

**Comment by GeorgeRudd** [comment]
参考了一下这里的讨论之后解决了 https://v2ex.com/t/696735?p=1
首先我先去apkmirror更新了一下框架和商店
后来发现根本原因还是服务端ip被谷歌标记为cn 最简单的解决方法就是换ip 如果没办法换 可以用warp添加一个ipv6
需要设置三个域名
services.googleapis.cn,
services.googleapis.com,
xn--ngstr-lra8j.com
在客户端让这三个走代理
在服务端设置这三个走ipv6

客户端配置文件的hosts设置可以改成这样
		"hosts": {
			"services.googleapis.cn": "services.googleapis.com"
		}

另外三星手机国行固件要把 设置 加到走代理的应用里

**Comment by luckiestone** [comment]
> 参考了一下这里的讨论之后解决了 https://v2ex.com/t/696735?p=1
> 首先我先去apkmirror更新了一下框架和商店
> 后来发现根本原因还是节点的问题 ip被谷歌标记为cn 最简单的解决方法就是换ip，之后在客户端让这三个走代理
> 我自己的机器只有ipv4 我的方法是用warp添加一个ipv6 然后服务端xray设置让下面三个走ipv6
> googleapis.cn,
> googleapis.com,
> xn--ngstr-lra8j.com
> 
> 另外三星手机国行固件要把 设置 加到走代理的应用里
```
    "outbounds": [
        {
          "tag":"IP4_out",
          "protocol": "freedom",
          "settings": {}
        },
       {
          "tag":"IP6_out",
          "protocol": "freedom",
         "settings": {
              "domainStrategy": "UseIPv6" 
              }
        }
    ],
    "routing": {
        "rules": [
            {
                "type": "field",
                "outboundTag": "IP6_out",
                "domain": [
                    "domain:google.cn",
                    "domain:googleapis.cn",
                    "domain:googleapis.com",
                    "domain:xn--ngstr-lra8j.com"
                ] 
            },
            {
                "type": "field",
                "outboundTag": "IP4_out",
                "network": "udp,tcp" 
            }
        ]
    }
```
机器获取ipv6后，config这么设置了，似乎也并没有起作用哎。这种情况下ping google.com和YouTube竟然也是ipv6的地址，ping baidu就是ipv4

**Comment by gcphym** [comment]
> > 参考了一下这里的讨论之后解决了 https://v2ex.com/t/696735?p=1
> > 首先我先去apkmirror更新了一下框架和商店
> > 后来发现根本原因还是节点的问题 ip被谷歌标记为cn 最简单的解决方法就是换ip，之后在客户端让这三个走代理
> > 我自己的机器只有ipv4 我的方法是用warp添加一个ipv6 然后服务端xray设置让下面三个走ipv6
> > googleapis.cn,
> > googleapis.com,
> > xn--ngstr-lra8j.com
> > 另外三星手机国行固件要把 设置 加到走代理的应用里
> 
> ```
>     "outbounds": [
>         {
>           "tag":"IP4_out",
>           "protocol": "freedom",
>           "settings": {}
>         },
>        {
>           "tag":"IP6_out",
>           "protocol": "freedom",
>          "settings": {
>               "domainStrategy": "UseIPv6" 
>               }
>         }
>     ],
>     "routing": {
>         "rules": [
>             {
>                 "type": "field",
>                 "outboundTag": "IP6_out",
>                 "domain": [
>                     "domain:google.cn",
>                     "domain:googleapis.cn",
>                     "domain:googleapis.com",
>                     "domain:xn--ngstr-lra8j.com"
>                 ] 
>             },
>             {
>                 "type": "field",
>                 "outboundTag": "IP4_out",
>                 "network": "udp,tcp" 
>             }
>         ]
>     }
> ```
> 
> 机器获取ipv6后，config这么设置了，似乎也并没有起作用哎。这种情况下ping google.com和YouTube竟然也是ipv6的地址，ping baidu就是ipv4

你是warp解锁的ipv6吗

**Comment by gcphym** [comment]
> > 参考了一下这里的讨论之后解决了 https://v2ex.com/t/696735?p=1
> > 首先我先去apkmirror更新了一下框架和商店
> > 后来发现根本原因还是节点的问题 ip被谷歌标记为cn 最简单的解决方法就是换ip，之后在客户端让这三个走代理
> > 我自己的机器只有ipv4 我的方法是用warp添加一个ipv6 然后服务端xray设置让下面三个走ipv6
> > googleapis.cn,
> > googleapis.com,
> > xn--ngstr-lra8j.com
> > 另外三星手机国行固件要把 设置 加到走代理的应用里
> 
> ```
>     "outbounds": [
>         {
>           "tag":"IP4_out",
>           "protocol": "freedom",
>           "settings": {}
>         },
>        {
>           "tag":"IP6_out",
>           "protocol": "freedom",
>          "settings": {
>               "domainStrategy": "UseIPv6" 
>               }
>         }
>     ],
>     "routing": {
>         "rules": [
>             {
>                 "type": "field",
>                 "outboundTag": "IP6_out",
>                 "domain": [
>                     "domain:google.cn",
>                     "domain:googleapis.cn",
>                     "domain:googleapis.com",
>                     "domain:xn--ngstr-lra8j.com"
>                 ] 
>             },
>             {
>                 "type": "field",
>                 "outboundTag": "IP4_out",
>                 "network": "udp,tcp" 
>             }
>         ]
>     }
> ```
> 
> 机器获取ipv6后，config这么设置了，似乎也并没有起作用哎。这种情况下ping google.com和YouTube竟然也是ipv6的地址，ping baidu就是ipv4

这是我的配置
```
	"routing": {
		"rules": [
			{
				"outboundTag": "IPv6_out",
				"type": "field",
				"domain": [
                                        "google.cn",					
                                        "googleapis.cn",
					"googleapis.com",
					"xn--ngstr-lra8j.com"
				]
			}
		]
	}
```

**Comment by luckiestone** [comment]
> > > 参考了一下这里的讨论之后解决了 https://v2ex.com/t/696735?p=1
> > > 首先我先去apkmirror更新了一下框架和商店
> > > 后来发现根本原因还是节点的问题 ip被谷歌标记为cn 最简单的解决方法就是换ip，之后在客户端让这三个走代理
> > > 我自己的机器只有ipv4 我的方法是用warp添加一个ipv6 然后服务端xray设置让下面三个走ipv6
> > > googleapis.cn,
> > > googleapis.com,
> > > xn--ngstr-lra8j.com
> > > 另外三星手机国行固件要把 设置 加到走代理的应用里
> > 
> > 
> > ```
> >     "outbounds": [
> >         {
> >           "tag":"IP4_out",
> >           "protocol": "freedom",
> >           "settings": {}
> >         },
> >        {
> >           "tag":"IP6_out",
> >           "protocol": "freedom",
> >          "settings": {
> >               "domainStrategy": "UseIPv6" 
> >               }
> >         }
> >     ],
> >     "routing": {
> >         "rules": [
> >             {
> >                 "type": "field",
> >                 "outboundTag": "IP6_out",
> >                 "domain": [
> >                     "domain:google.cn",
> >                     "domain:googleapis.cn",
> >                     "domain:googleapis.com",
> >                     "domain:xn--ngstr-lra8j.com"
> >                 ] 
> >             },
> >             {
> >                 "type": "field",
> >                 "outboundTag": "IP4_out",
> >                 "network": "udp,tcp" 
> >             }
> >         ]
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 机器获取ipv6后，config这么设置了，似乎也并没有起作用哎。这种情况下ping google.com和YouTube竟然也是ipv6的地址，ping baidu就是ipv4
> 
> 这是我的配置
> 
> ```
> 	"routing": {
> 		"rules": [
> 			{
> 				"outboundTag": "IPv6_out",
> 				"type": "field",
> 				"domain": [
>                                         "google.cn",					
>                                         "googleapis.cn",
> 					"googleapis.com",
> 					"xn--ngstr-lra8j.com"
> 				]
> 			}
> 		]
> 	}
> ```

看来我规则写法不对，改了，还是不行。我ipv6是VPS原生的。看来这个问题还是比较棘手
