### ISSUE TITLE
DOH问题

### ISSUE THREAD

**Issue by mariokart1992** [2dust/v2rayNG#1235]
近期突然出现设置内置DNS服务器时

只要设置了DOH V2rayNg卡死
不管是host加 https://cloudflare-dns.com/dns-query还是https://1.1.1.1/dns-query都是卡死。

设置为1.1.1.1就可正常使用

查看日志没有出现异常

也是近期突然出现，之前使用一直没有问题

**Comment by cache444** [comment]
你说的卡死应该是指连接后无法正常使用吧（无法访问网络），DoH可以是https://xxx.xxx.xxx.xxx/dns-query或https+local://xxx.xxx.xxx.xxx/dns-query(直接对外请求)，如果你要用CF的DNS，请将1.1.1.1换为1.0.0.1再尝试，或者将IP换为域名。（可参看https://github.com/SagerNet/SagerNet/issues/180）

DoH需要勾选启用本地DNS后在远程DNS输入。

另外，某些节点可能无法使用DoH，例如台湾地区的节点。

**Comment by mariokart1992** [comment]
因为证书的原因导致的，重新配置了服务器的证书好了
