### ISSUE TITLE
老设备上的v2rayng和v2flyng都无法使用vpn模式

### ISSUE THREAD

**Issue by ansemz** [2dust/v2rayNG#1237]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
确认服务端没有问题，同类程序可以正常使用。没有其他人提出同样的问题，可能因为大家不用老设备

### 预期行为
启动v2rayng(v2flyng)，连接服务器后应该可以正常使用，访问各种网络服务

### 实际行为
启动app并连接服务器后，测试服务器是没有问题的，但是所有联网的程序都断网了。

### 复现方法
1.android 4.2.2 + v2rayng 1.6.22(v2flyng 1.6.21) + 确认正常的服务器
2.打开app并连接服务器
3.打开浏览器，访问google等网站

### 日志信息
--------- beginning of /dev/log/main
......
09-27 11:34:25.160 I/GoLog   (22543): loading core config
09-27 11:34:25.183 I/GoLog   (22543): new core
09-27 11:34:25.184 I/GoLog   (22543): [Debug] app/log: Logger started
09-27 11:34:25.186 I/GoLog   (22543): [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
09-27 11:34:25.187 I/GoLog   (22543): [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:10808
09-27 11:34:25.187 I/GoLog   (22543): [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:10809
09-27 11:34:25.188 I/GoLog   (22543): start core
09-27 11:34:25.189 I/GoLog   (22543): [Info] transport/internet/tcp: listening TCP on 127.0.0.1:10808
09-27 11:34:25.192 I/GoLog   (22543): [Info] transport/internet/udp: listening UDP on 127.0.0.1:10808
09-27 11:34:25.193 I/GoLog   (22543): [Info] transport/internet/tcp: listening TCP on 127.0.0.1:10809
09-27 11:34:25.193 I/GoLog   (22543): [Warning] core: Xray 1.4.5 started
09-27 11:34:25.304 D/com.v2ray.ang(22543): [/data/app-lib/com.v2ray.ang-1/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
09-27 11:34:25.325 D/com.v2ray.ang(22543): Process[pid=22624]
09-27 11:34:25.325 D/com.v2ray.ang(22543): /data/data/com.v2ray.ang/files/sock_path
09-27 11:34:25.425 D/com.v2ray.ang(22543): sendFd tries: 0
09-27 11:34:25.433 D/com.v2ray.ang(22543): java.io.IOException: No such file or directory
09-27 11:34:25.533 D/com.v2ray.ang(22543): sendFd tries: 1
09-27 11:34:25.534 D/com.v2ray.ang(22543): java.io.IOException: No such file or directory
09-27 11:34:25.734 D/com.v2ray.ang(22543): sendFd tries: 2
09-27 11:34:25.734 D/com.v2ray.ang(22543): java.io.IOException: No such file or directory
09-27 11:34:26.134 D/com.v2ray.ang(22543): sendFd tries: 3
09-27 11:34:26.135 D/com.v2ray.ang(22543): java.io.IOException: No such file or directory
09-27 11:34:26.935 D/com.v2ray.ang(22543): sendFd tries: 4
09-27 11:34:26.935 D/com.v2ray.ang(22543): java.io.IOException: No such file or directory

[log.txt](https://github.com/2dust/v2rayNG/files/7233233/log.txt)

### 环境信息
android 4.2.2 + v2rayng 1.6.22(v2flyng 1.6.21) + 确认正常的服务器
### 额外信息（可选）
app启动的代理本身127.0.0.1:10808/192.168.1.123:10808，经过测试是可以访问的。

**Comment by ghost** [comment]
Android TV版本都没比你这个更低的了吧？不兼容或者无法在老设备上运行的APP太多了。与时俱进不好吗

**Comment by ansemz** [comment]
主要是想让几个老平板发挥一下余热，需求确实很小众。找了一下，Kitsunebi可以用。

**Comment by PingerAI** [comment]
除了换用Kitsunebi之外还有什么其他解决办法吗？我这边是打包apk可以使用，打包aab之后就不行了，之前有人也提过类似的issue，但是采用了他的解决方案同样不行
