### ISSUE TITLE
GooglePlay谷歌应用商店无法下载/更新app奇怪问题的一些反馈

### ISSUE THREAD

**Issue by zsbstephen** [2dust/v2rayNG#1238]
手机：Samsung Galaxy S10e G9700
系统OS：Android 11
v2rayng版本：1.6.22（发帖时最新）

已测试过下列所有的场景，GooglePlay谷歌应用商店均不能下载：
1、v2rayng所有代理模式（全局、绕过局域网或中国大陆）。
2、自定义规则中添加下列所有GooglePlay商店涉及的域名，强制这些域名走代理。
connectivitycheck.gstatic.com
services.googleapis.cn
xn--ngstr-lra8j.com
android.clients.google.com
digitalassetlinks.googleapis.com
play.google.com
play-fe.googleapis.com
3、局域网里面使用台式机上的v2rayN，开启局域网代理，让手机连接台式机的局域网代理，可以发现日志里面接收到手机请求上面第2点列出的域名，已经强制了这些域名走代理，但下载进度一直是卡在0%。
4、VPS端的xray写一段inboundDetour开一个shadowsocks协议端口，手机端改用shadowsocks Android版本开启代理，GooglePlay谷歌应用商店倒是能正常更新了（但众所周知GFW已经会主动探测识别Shadowsocks服务器，因此只能下载更新app时临时开一下，不能长期开）。

以上是一些反馈。

**Comment by ghost** [comment]
v2rayNG app客户端本身不存在你描述的问题。你自己翻翻Issues(包括已关闭的Issues)看看是你哪里配置出错了吧。

**Comment by gcphym** [comment]
#1234

**Comment by Z-LL** [comment]
感谢！
connectivitycheck.gstatic.com
services.googleapis.cn
xn--ngstr-lra8j.com
android.clients.google.com
digitalassetlinks.googleapis.com
play.google.com
play-fe.googleapis.com
添加了这些域名，强制走代理后，可以了！
