### ISSUE TITLE
是否考虑添加链式代理的功能

### ISSUE THREAD

**Issue by jialinjun** [2dust/v2rayNG#1240]
### 预期行为
能够有UI选择2个或者多个现有的配置文件，形成一个链式代理

### 实际行为
实际使用中确实存在这样的场景。比如：在连接美国节点的时候网络较差，我会使用日本或者香港作为跳板。或者在敏感时期，先使用JC，再连接到自己的节点，保证安全和隐私。

### 复现方法
无

### 日志信息
无

### 环境信息
安卓11

### 额外信息（可选）
目前确实有部分用户有这样的使用场景，希望能够实现 :)

**Comment by ghost** [comment]
+1
同样有这个需求，虽然可能很少用到
