### ISSUE TITLE
使用v2rayNg切换服务器后，旧的服务器没有断开连接

### ISSUE THREAD

**Issue by derek1dong** [2dust/v2rayNG#1242]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
配置了两个服务器，当从服务器A切换到服务器B时，应该断开和A的连接

### 实际行为
实际上，每次切换，都不会断开旧的连接。如果多切换几次，那么连接数会累积

### 复现方法
1. 配置多个服务器
2. 切换服务器
3.查看服务器A和B，从特定客户端ip发起的连接个数在增加； 而且这些连接都是活动的，每个固定时间会有数据收发。
4.当关闭v2rayng程序后，所有连接才会中断。

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
v1.6.20 xray-core v1.4.3
服务器配置成vless+grpc，这样客户端跟服务器应该只有一个连接

### 额外信息（可选）
这个是服务器上的iftop -f "host clientip" 过滤图，每次切换这个连接数都会增加
![image](https://user-images.githubusercontent.com/85718501/135371244-2d7b03e8-0dd6-46aa-9ae1-c1cce320b9a9.png)

**Comment by yuhan6665** [comment]
I noticed this behavior earlier when debugging traffic issue.
Looks like this is caused by the "soft" close behavior in core:
https://github.com/v2fly/v2ray-core/blob/b3e0d54630c1a7d33b59fce1d812732d89317c33/v2ray.go#L246
Though it seems not a big problem right now, unless we are to add automatic server switching function.

**Comment by zjudongze** [comment]
目前主要的影响是后台耗电。使用一段时间，累积的连接数量多了后，耗电增加。目前都是通过主动杀死v2rayng，再重新打开，规避这个问题

**Comment by yuhan6665** [comment]
按理说这些连接过一段时间会断掉吧 那么应该对耗电没有什么影响

**Comment by derek1dong** [comment]
目前看到的行为，断开连接之后，会重连；

也就是之前有几个连接，之后还是几个连接；不会因为时间久了，连接数减少

**Comment by yuhan6665** [comment]
是只有 grpc 传输方式还是其它方式都这样

**Comment by derek1dong** [comment]
测试了一下：xtls，ss都没问题，过一段时间后连接会中断； 只有grpc会保持连接

**Comment by yuhan6665** [comment]
感谢测试 @derek1dong 麻烦给 xray-core 发一个 issue 吧 需要在 core 里面修复
我有机会会研究一下这个问题

**Comment by derek1dong** [comment]
使用windows的v2rayN，同样的grpc配置，没有这个问题：windows上好像是重新启动xray进程。
感觉还是android v2rayNG和xray在grpc下的特殊问题

**Comment by derek1dong** [comment]
今天发现一个grpc的另外一个bug：
更新v2rayNg到1.6.22 (xray 1.4.5)之后，无论服务端是1.4.5还是1.4.3， 当android手机网络切换后，v2rayng会建立N个服务端的连接，而且这些连接都会定期保活，即使再次网络切换，还会重建至少十几个连接；但是实际工作的只有一个grpc连接

网络切换时，会刷一排这样的日志
GoLog   : Using Prepared

在服务器端看到的客户端连接个数：
<img width="1392" alt="Screen Shot 2021-10-09 at 1 58 15 PM" src="https://user-images.githubusercontent.com/85718501/136646863-5b50752b-2930-4c8f-9a82-049ed0e0eb5f.png">

我感觉解决了旧的grpc连接不能中断的问题后，1.6.22这个问题应该也能解决

**Comment by yuhan6665** [comment]
确实 grpc 有一点问题 看起来是保活了应该丢弃的连接
问一下 @derek1dong 你用自定义 grpc 配置吗？如果是的话写一下 outbound

**Comment by zjudongze** [comment]
grpc + tls，multi模式，其他都是默认配置

服务端 xray前置，回落到nginx，然后再回落到xray的 grpc，为了保持连接，nginx加了这些设置：

         proxy_read_timeout 600m;
         client_body_timeout 600m;
         grpc_connect_timeout 600s;
         grpc_read_timeout 720m;
         grpc_send_timeout 720m;
client_body_buffer_size 1m;
client_max_body_size 0;

所以除非客户端主动挂断，这个链接基本不会断开

**Comment by derek1dong** [comment]
测试了一下：1.6.25版本解决了1.6.22一次网络切换时刷出几十个连接的问题；
但是没有解决1.6.20就有的问题：手动切换节点之后，原来的grpc连接不会中断。

**Comment by yuhan6665** [comment]
明白 这个问题修复仍在计划中
