### ISSUE TITLE
Vless: Fail to detect internet connection IO read/write on closed pipe

### ISSUE THREAD

**Issue by alcatraz-zz** [2dust/v2rayNG#1243]
My samsung tab s running marshmallow has been working for years with v2rayng connected to the same vless server. The other day suddenly it stopped. I have other android devices on the same network that are still connected and work fine. I even restored the device to factory defaults and still nothing. This is so weird. Has v2rayng stopped supporting adding new vless servers? I was running 1.6.22 when it happened. How can only one device stop working? I tried many old versions of v2rayng but nothing. I always get "failed to detect internet connection. io: read/write on closed pipe". I'm connected to wifi and I can reach the server using other protocols. What???? Are my other devices going to die soon too? Thanks for reading 
and helping. I really appreciate it.

**Comment by alcatraz-zz** [comment]
Ok, I can confirm that all Android 6 (marshmallow) devices I have now show the same error. What is going on? Two tablets and and one Xiaomi TV. 

My Android8 nougat phone is still fine. ???? Does someone have any idea?

**Comment by zxjrainbow** [comment]
me too

**Comment by alcatraz-zz** [comment]
> me too

Have you found any version of v2rayNG that works? I have tried several but nothing. I think it's so weird that all devices stop at the same time, and then reverting back to an older version doesn't work. Yet the server works fine with some devices still. It's a real mindf**k. 🤣

**Comment by zxjrainbow** [comment]
> > me too
> 
> Have you found any version of v2rayNG that works? I have tried several but nothing. I think it's so weird that all devices stop at the same time, and then reverting back to an older version doesn't work. Yet the server works fine with some devices still. It's a real mindf**k. 🤣

allowInsecure set to true . all done.  If don't ,try set phone's datetime same as the server.

**Comment by tiennan** [comment]
I think this is the root cause:
“On 30th September 2021, the root certificate that Let's Encrypt are currently using, the IdentTrust DST Root CA X3 certificate, will expire.”
https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

My testing result as below:
Android >=8: works fine without any changes
Android 7: works fine if setting allowInsecure to true
Android < 7: failed

**Comment by alcatraz-zz** [comment]
Thank you so much. I've gotten it to work on the two devices I have nearby. On one I installed the https://letsencrypt.org/certs/isrgrootx1.der certificate and then got it to work by setting allowInsecure to true. The other device I just had to set allowInsecure to true. Thanks.

Is G-F-W going to detect the traffic as insecure now and block the server?

**Comment by wuwentao** [comment]
I have the same error in my **Android 9** OS with **v2rayNG_1.6.22_armeabi-v7a.apk**

all my windows 10 PC/ios device works well, only this Android 9.0 device can't works（it's a TV box : gt-king pro wifi6 hardware version, and software version is Android 9）.

in addition, my server config is **VMESS+ TLS+  WebSocket**  after **Nginx**  (Let's Encrypt cert service)

steps: 

1. checked my device time, confirmed it works well with NTP
2. also enabled not verify server TLS option in app setting(forgot the name, in chinese version), also can't works
3.  downgrade to a very old software **Kitsunebi-v0.9.2.apk** (released in 2019), seems it works.
4. what's the error and how to fix it ?
5. also tried with SagerNet for android **SN-0.5-rc23-armeabi-v7a.apk** have the same IO error as v2rayNG
6. is there some option not work in new software ?

below is my client config file 

```json
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx.xxx.yyy",
            "port": 443,
            "users": [
              {
                "email": "user@email.com",
                "id": "xxxxxxx",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/myfiles"
        }
      }
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:cn"]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ]
      }
    ]
  },
  "dns": {
    "hosts": {
      "geosite:category-ads": "127.0.0.1"
    },
    "servers": [
      "1.1.1.1",
      {
        "address": "114.114.114.114",
        "port": 53,
        "domains": ["geosite:cn"],
        "expectIPs": ["geoip:cn"]
      }
  ]
  }
}

```

**Comment by pedram6195** [comment]
I had the same issue with my huawei phone which is android 9. I changed time settings in my phone to automatic and it solved the problem.

**Comment by mostafa1647** [comment]
I had the same issue with Xiaomi phone and I set time settings of devices to automatic and problem solved, too.

**Comment by glyimo** [comment]
hellow, 
can you help me how to solve this issue "failed to detect internent connection: connection closed".

**Comment by KayDWastedTime** [comment]
Hey , 
I have Android 10 , I tried to set my time to auto and my  allowInsecure to true and reinstalling v2rayng , none of them worked . (Also the confing works on another device with same Internet)
I appreciate it if you help me ,

**Comment by Ehsanrezazadeh1** [comment]
in the Iran you must set the time zone to Automatic

**Comment by jerryjedi** [comment]
where is the time zone configuration? I use v1.8.15 on Huawei phone.

**Comment by kedeng** [comment]
I updated v2ray to latest version in server reslove this issue.

**Comment by chatgptak22** [comment]
Есть решение проблемы?

**Comment by alcatraz-zz** [comment]
When it only works on some devices/computers but not others, I believe the problem is the server isn't using the "fullchain" certificate/key in its configuration. Just edit that one parameter to the fullchain file and you're done!

**Comment by mohoshin7401-png** [comment]
Same Issu , anyone got any solution ??

**Comment by alcatraz-zz** [comment]
> Same Issu , anyone got any solution ??

Is your server configured with cert parameter pointing to a "fullcert" file? If not it probably is the reason.

When obtaining cert/key people mistakingly choose the wrong certificate file in the config.

**Comment by mohoshin7401-png** [comment]
> > Same Issu , anyone got any solution ??
> 
> Is your server configured with cert parameter pointing to a "fullcert" file? If not it probably is the reason.
> 
> When obtaining cert/key people mistakingly choose the wrong certificate file in the config.

first time i am uiseing ([AndroidLibV2rayLite](https://github.com/2dust/AndroidLibV2rayLite)) but that is not working then i am useing  [AndroidLibXrayLite](https://github.com/2dust/AndroidLibXrayLite) and now working  .. now working ip change and Connect success but also my phone gose offline .

**Comment by soltanmk22** [comment]
ples confing
