### ISSUE TITLE
希望添加类似系统代理的功能

### ISSUE THREAD

**Issue by w6lc** [2dust/v2rayNG#1250]
### 现状
目前软件有vpn模式和仅代理模式
vpn模式的缺点是会全局流量代理，部分有非代理需求的软件会出现错误（如果是wifi设置系统代理，则不会报错）
仅代理模式缺点是，需要手动对wifi设置代理，在不开启代理时需要手动修改
### 需求
希望添加一个类似windows端v2rayN的系统代理模式，应用会根据是否使用系统代理自行判断，达到和wifi里设置代理一样的效果
这样可以避免开启关闭v2rayNG时，需要反复设置wifi代理，并且在切换wifi时也需要设置，较为麻烦

**Comment by ghost** [comment]
vpn模式+仅代理模式已经完美(特别是对于手机端来说)。

抱歉看半天没看明白你说的意思，你说的vpn模式缺点，你就不会分应用？。还有仅代理缺点，这算缺点吗。。？这就好比你的服务端已经部署好了，接着就是要配置客户端来使用一样的，这不是必需的正常操作吗，哪个代理和支持被代理的软件不是这样？  如果理解有误请见谅。

**Comment by w6lc** [comment]
> vpn模式+仅代理模式已经完美(特别是对于手机端来说)。
> 
> 抱歉看半天没看明白你说的意思，你说的vpn模式缺点，你就不会分应用？。还有仅代理缺点，这算缺点吗。。？这就好比你的服务端已经部署好了，接着就是要配置客户端来使用一样的，这不是必需的正常操作吗，哪个代理和支持被代理的软件不是这样？ 如果理解有误请见谅。

windows上的代理软件，不论是v2rayN还是clash，都支持系统代理，可以理解为帮用户自动修改所有wifi或者以太网的代理设置，这样会方便不少，软件开启和关闭时自动就会修改系统里的代理设置，而不是自己之后还需要修改
![image](https://user-images.githubusercontent.com/49556918/136333884-c18d7b99-cc96-448b-b042-fcecbdaeed68.png)

至于你说的分应用代理，有的应用就是很奇葩，继需要用到代理，也需要用到非代理，简单来说就是vpn的全部流量代理模式就是会出问题，这就导致有些时候我不能使用vpn模式（举个例子，手机版duellinks，用vpn会导致界面无法登入，用wifi系统代理则不会），这不是分应用代理能解决的

**Comment by ghost** [comment]
@wielice 那我觉得这个功能在手机上就比较难搞了，首先软件可能需要用户授予root权限来修改系统设置(这会直接劝退85以上%的新老用户)，其次手机端不同品牌、不同型号、不同的ROM/OS所对应的设置项均各有不同，可能会引发诸多BUG。  再说仅代理开启并连接后就是透明代理模式了，你不如直接拿一台闲置的Android设备专用来热点或局域网。

**Comment by w6lc** [comment]
好的确实，归根到底还是安卓不像windows那样方便开发😂
________________________________
发件人: cache444 ***@***.***>
发送时间: 2021年10月7日 15:25
收件人: 2dust/v2rayNG ***@***.***>
抄送: wielice ***@***.***>; Mention ***@***.***>
主题: Re: [2dust/v2rayNG] 希望添加类似系统代理的功能 (#1250)


@wielice<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwielice&data=04%7C01%7C%7C5c43ecde5adb4ed4572508d989639fe7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637691883238191138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tAFu%2Bv7QnW89c1xitWYz3xMGBMLBSqzA3WCy3ySAF5Q%3D&reserved=0> 那我觉得这个功能在手机上就比较难搞了，首先软件可能需要用户授予root权限来修改系统设置(这会直接劝退85以上%的新老用户)，其次手机端不同品牌、不同型号、不同的ROM/OS所对应的设置项均各有不同，可能会引发诸多BUG。 再说仅代理开启并连接后就是透明代理模式了，你不如直接拿一台闲置的Android设备专用来热点或局域网。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F2dust%2Fv2rayNG%2Fissues%2F1250%23issuecomment-937526144&data=04%7C01%7C%7C5c43ecde5adb4ed4572508d989639fe7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637691883238201149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FMpBaMPob%2BzDKLPrqjWD1hzN03x52%2B9Agwc%2FMPe6kCU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL2C3NTVRZOOMRLA3TAWRWDUFVDODANCNFSM5FQJDCJA&data=04%7C01%7C%7C5c43ecde5adb4ed4572508d989639fe7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637691883238201149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EpnctVQ6mlUAi%2BDR65d%2Fd%2Bpwup8n2197kYZbvW04mco%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5c43ecde5adb4ed4572508d989639fe7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637691883238211140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=twF%2FNEhK98RL2sXBV3u9aYDh7JVN85RqfSw9eIKZHBg%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5c43ecde5adb4ed4572508d989639fe7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637691883238211140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mxnrJUcbn1869Jzv6NMH8i1LjBZfT3gtaEC68qL94JQ%3D&reserved=0>.

**Comment by qnxsgwy** [comment]
> > vpn模式+仅代理模式已经完美(特别是对于手机端来说)。
> > 抱歉看半天没看明白你说的意思，你说的vpn模式缺点，你就不会分应用？。还有仅代理缺点，这算缺点吗。。？这就好比你的服务端已经部署好了，接着就是要配置客户端来使用一样的，这不是必需的正常操作吗，哪个代理和支持被代理的软件不是这样？ 如果理解有误请见谅。
> 
> windows上的代理软件，不论是v2rayN还是clash，都支持系统代理，可以理解为帮用户自动修改所有wifi或者以太网的代理设置，这样会方便不少，软件开启和关闭时自动就会修改系统里的代理设置，而不是自己之后还需要修改 ![image](https://user-images.githubusercontent.com/49556918/136333884-c18d7b99-cc96-448b-b042-fcecbdaeed68.png)
> 
> 至于你说的分应用代理，有的应用就是很奇葩，继需要用到代理，也需要用到非代理，简单来说就是vpn的全部流量代理模式就是会出问题，这就导致有些时候我不能使用vpn模式（举个例子，手机版duellinks，用vpn会导致界面无法登入，用wifi系统代理则不会），这不是分应用代理能解决的

安卓没有root权限没法修改这个设置，并不是Windows方便开发，你用非管理员账号在windows上也没权限设置。既需要用到代理也需要用到非代理的情况下你可以设置路由规则啊，并非不能解决。

**Comment by jzjohn789** [comment]
> > > vpn模式+仅代理模式已经完美(特别是对于手机端来说)。
> > > 抱歉看半天没看明白你说的意思，你说的vpn模式缺点，你就不会分应用？。还有仅代理缺点，这算缺点吗。。？这就好比你的服务端已经部署好了，接着就是要配置客户端来使用一样的，这不是必需的正常操作吗，哪个代理和支持被代理的软件不是这样？ 如果理解有误请见谅。
> > 
> > 
> > windows上的代理软件，不论是v2rayN还是clash，都支持系统代理，可以理解为帮用户自动修改所有wifi或者以太网的代理设置，这样会方便不少，软件开启和关闭时自动就会修改系统里的代理设置，而不是自己之后还需要修改 ![image](https://user-images.githubusercontent.com/49556918/136333884-c18d7b99-cc96-448b-b042-fcecbdaeed68.png)
> > 至于你说的分应用代理，有的应用就是很奇葩，继需要用到代理，也需要用到非代理，简单来说就是vpn的全部流量代理模式就是会出问题，这就导致有些时候我不能使用vpn模式（举个例子，手机版duellinks，用vpn会导致界面无法登入，用wifi系统代理则不会），这不是分应用代理能解决的
> 
> 安卓没有root权限没法修改这个设置，并不是Windows方便开发，你用非管理员账号在windows上也没权限设置。既需要用到代理也需要用到非代理的情况下你可以设置路由规则啊，并非不能解决。

路由规则对于DUEL LINKS登录的进不去没效果的，这个应用就是登录时候麻烦，既要代理也要非代理，但是如果已经登录进去，那选什么模式都可以正常用（只要应用不退出来），VPN模式和仅代理对于它这个应用（登录时候）都没用的，只能在WIFI或者数据流量自己手动设置代理信息之后才可以登录进去
