### ISSUE TITLE
请问下，代理模式，相对于vpn模式+分应用代理 会更省电么？

### ISSUE THREAD

**Issue by ffplayer** [2dust/v2rayNG#1253]
如题，突然想到这个点。不知是否会有明显差别？

**Comment by ghost** [comment]
https://github.com/2dust/v2rayNG/wiki/Mode

**Comment by ffplayer** [comment]
> https://github.com/2dust/v2rayNG/wiki/Mode

这里面好像也没有说明耗电情况呀

**Comment by ghost** [comment]
![Screenshot_2021-10-11-15-57-59-81](https://user-images.githubusercontent.com/89191925/136753719-d41ce4cf-7ec4-48bf-a5ff-4e60b176af47.jpg)
很难理解吗？

另外，如果你想明确的知道具体耗电情况，可以自己在设备查看：设置 > 电池 > 应用耗电详情/耗电管理

分别使用两种模式各一段时间，然后再观察对比耗电情况就知道了。

**Comment by ffplayer** [comment]
emm 不好意思英语不好没留意到第2项。谢了谢了！@cache444

麻烦管理员关闭下
