### ISSUE TITLE
v2rayNG在鸿蒙系统中没有【允许后台活动】选项

### ISSUE THREAD

**Issue by aglent** [2dust/v2rayNG#1258]
最近华为平板安装了v2rayNG 是最新版本 平板是鸿蒙最新
连接后总是打不开页面 查看了一些issue 应该是系统设置里没有开启允许后台活动
但是我在平板系统的应用设置里找不到允许后台活动的选项 我看其他工具比如ss clash等都是有这个选项的
所以想问问这是工具的原因还是鸿蒙的原因？

**Comment by geeksnow** [comment]
毫无疑问是鸿蒙的问题，鸿蒙删除了部分安卓应有的设置并替换了自己的设置，您应该在鸿蒙的设置中寻找类似选项

**Comment by steelheadz** [comment]
我和楼主一样的情况，我开了允许后台活动也是一样
