### ISSUE TITLE
开启sniffing后hulu安卓app无法读取视频

### ISSUE THREAD

**Issue by iceye2072** [2dust/v2rayNG#126]
开启sniffing的情况下，hulu安卓app无法读取视频，关闭sniffing则恢复正常。 因为想中转流量，需要用到域名规则，所以需要开启sniffing。 请问这个情况是不是v2rayng的bug问题。。

youtube. Netflix没有这个问题，网页版的hulu也无问题。 这个问题目前只出现在hulu安卓上（日区）。。。

**Comment by iceye2072** [comment]
https://github.com/v2ray/v2ray-core/issues/1932#issue-504061141
这是我开的另一个issue，讨论关于这个问题。上面有完整log（因为没有错误提示，恐怕意义不大）

**Comment by 2dust** [comment]
估计ng无法帮你
