### ISSUE TITLE
tiktok与流量探测

### ISSUE THREAD

**Issue by jimmy-Smile-ltl** [2dust/v2rayNG#1260]
流量探测开启  tiktok无法运行，youtube等正常
流量探测关闭，tiktok运行 youtube等无法运行
运行指网络连接
已测试多个节点

**Comment by jimmy-Smile-ltl** [comment]
说明：使用全局模式可以联网，但是无法加载出视频，
绕过大陆模式下，无法联网。

使用tiktok破解版，全局模式下可以使用，能够使用了，放弃探索

**Comment by HsimWong** [comment]
tiktok破解版请问是如何搞定的？ @jimmy-Smile-ltl
