### ISSUE TITLE
DNS over QUIC无法生效

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1261]
https://github.com/XTLS/Xray-core/releases/tag/v1.5.0

配置远程DNS为“quic+local://dns.adguard.com”，但无法生效，判断依据是根据adguardDNS的广告屏蔽功能是否生效以及访问https://adguard.com/en/test.html页面检测未运行。

而使用DoH则是正常的。

**Comment by ghost** [comment]
配置为IP时“quic+local://94.140.14.14/dns-query”同样无法生效

**Comment by ghost** [comment]
v2rayNG版本：1.6.24

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/blob/2d5351ec9ee35f8b186dadf1b8701b236528837f/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/Utils.kt#L142
plan to fix it this weekend

**Comment by ghost** [comment]
> https://github.com/2dust/v2rayNG/blob/2d5351ec9ee35f8b186dadf1b8701b236528837f/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/Utils.kt#L142
> 
> 
> plan to fix it this weekend

谢谢你们，辛苦了❤️

**Comment by yuhan6665** [comment]
fixed in https://github.com/2dust/v2rayNG/pull/1263
