### ISSUE TITLE
代理的网址 直连的网址 阻止的网址 格式问题

### ISSUE THREAD

**Issue by GeorgeRudd** [2dust/v2rayNG#1262]
直连里面填geosite:cn 代理和阻止留空
这时候如果在代理里面填baidu.com 百度就可以走代理
但是如果要屏蔽就必须在阻止里面填domain:baidu.com 只写baidu.com就无法屏蔽 
为什么

代理和直连都是可以只写域名 比如ip.sb
但是阻止就必须写成domain:ip.sb

**Comment by ghost** [comment]
geosite/geoip里面可能包含了你不想走代理的域名/ip，也可能没有包含你想走代理的域名/ip。想要个人自定义的话就别引用geo，或者自己定制geo文件。
格式的话参见https://www.v2ray.com/chapter_02/03_routing.html    一般来说除了ip，代理/直连/阻止的标准格式都需要加domain:
此外还需要勾选启用本地dns来作用
