### ISSUE TITLE
从本地导入自定义配置对 $.dns.hosts 的处理异常

### ISSUE THREAD

**Issue by 10330384** [2dust/v2rayNG#1265]
从本地导入自定义配置的**dns.hosts**的内容为Array时会提示配置格式错误。如：
`{
"dns": {
    "hosts": {
      "dns.google": [
        "8.8.8.8",
        "8.8.4.4"
      ]
    }
}
}`
软件提示配置格式错误
实际上该项在v2ray-core中是支持传入Array或String类型的数据

**Comment by yuhan6665** [comment]
Thanks for reporting. Plan to fix soon..

**Comment by devpius** [comment]
Phlona














My

**Comment by yuhan6665** [comment]
fix in https://github.com/2dust/v2rayNG/pull/1268

**Comment by hkbase** [comment]
xray 1.5 已经支持这个单域名映射多个ip地址的格式了。之前的旧版本都是不支持的。
{ "dns": { "hosts": { "dns.google": [ "8.8.8.8", "8.8.4.4" ] } } }
