### ISSUE TITLE
华为手机提示危险应用 打开就提示要卸载

### ISSUE THREAD

**Issue by APPX-Studio** [2dust/v2rayNG#1266]
![编组](https://user-images.githubusercontent.com/49307767/139169964-e4115010-c4f8-459b-9277-cf6040c69294.jpg)

**Comment by APPX-Studio** [comment]
<img width="828" alt="QQ20211028-162708@2x" src="https://user-images.githubusercontent.com/49307767/139217449-7ff88df7-8882-4244-8fb5-e6b72cb3b46b.png">
自己打包提示这个什么原因啊？过不了华为杀毒

**Comment by asting** [comment]
用华为翻墙？
