### ISSUE TITLE
dns安全问题疑问

### ISSUE THREAD

**Issue by wangyifan349** [2dust/v2rayNG#1267]
想问一下,v2ray我dns设置成223.5.5.5运营商能否根据我的53端口查看到我的查询内容?
v2ray有没有那种通过https加密的dns呢?

**Comment by ghost** [comment]
https://guide.v2fly.org/basics/dns.html#dns-over-https

**Comment by wangyifan349** [comment]
安卓的是否也能使用？

**Comment by wangyifan349** [comment]
我看了你的链接，电脑端的设置成功了，不知道安卓的行不行？

**Comment by chika0801** [comment]
客户端v2rayN
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS/dns_routing_example_config_client.json
服务器端
https://github.com/chika0801/Xray-examples/blob/main/VLESS-TCP-XTLS/dns_routing_example_config_server.json

希望能帮到你。在手机上的v2rayNG，配置文件用的原理类似

**Comment by wangyifan349** [comment]
在安卓的浏览器中设置安全DNS，否则运营商可以看见。
