### ISSUE TITLE
耗电严重且手机发热

### ISSUE THREAD

**Issue by daniaoren** [2dust/v2rayNG#127]
在手机待机的情况下，使用了大量电量（43%），且手机发热严重。

使用版本0.5.8
手机为一加5，安卓系统版本8.1.0

不知道有没有遇到类似情况的，升级到新版本后这种情况比较多

**Comment by alex-cham** [comment]
同样的情况，Pixel2 8.1固件未root，装了绿色守护但没对v2ray使用，没有wifi的环境中，早上7点半拨充电器，到中午12点只剩37%电，电量消耗达43%，手机能感觉到温热。而相同情况下的ssr耗电4%。

**Comment by 2dust** [comment]
耗电问题不是我能解决的.
因为app并没有什么可以改进能耗的优化

**Comment by yjk199771** [comment]
是什么机制导致如此耗电？
昨晚飞行模式睡觉，今早起，电量从93跌到51
