### ISSUE TITLE
启动页面添加广告了吗？好像启动就有某音的广告了

### ISSUE THREAD

**Issue by mrdream-wong** [2dust/v2rayNG#1271]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Happyflying666** [comment]
的确，突然发现有广告了，每次软件启动都有

**Comment by GeorgeRudd** [comment]
#930 是这个原因吗

**Comment by Happyflying666** [comment]
> #930 是这个原因吗

请教小米11有解决方案吗

**Comment by xiaomi2077** [comment]
https://github.com/2dust/v2rayNG/issues/930#issuecomment-796299937
https://github.com/2dust/v2rayNG/issues/930#issuecomment-796422612
我是按第一个链接解决的。nmd小米

**Comment by mrdream-wong** [comment]
> [#930 (comment)](https://github.com/2dust/v2rayNG/issues/930#issuecomment-796299937) [#930 (comment)](https://github.com/2dust/v2rayNG/issues/930#issuecomment-796422612) 我是按第一个链接解决的。nmd小米

谢谢老哥，可以了，真服了这miu...

**Comment by mrdream-wong** [comment]
> #930 是这个原因吗

谢谢，按他的新建一个弄好了，真服了这miui

**Comment by Happyflying666** [comment]
小米流氓
