### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by tudosxxx** [2dust/v2rayNG#1272]
--------- beginning of main
11-03 15:54:18.498 E/com.v2ray.ang(21355): Not starting debugger since process cannot load the jdwp agent.
11-03 15:54:18.764 I/com.v2ray.ang(21355): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
11-03 15:54:18.773 I/com.v2ray.ang(21355): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
11-03 15:54:30.651 D/com.v2ray.ang(21355): xxxxxxxxxxxxxxxx
11-03 15:54:31.211 W/System.err(21355): javax.net.ssl.SSLHandshakeException: Connection closed by peer
11-03 15:54:31.212 W/System.err(21355): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:383)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1424)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1368)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:219)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:392)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:325)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:470)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
11-03 15:54:31.212 W/System.err(21355): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
11-03 15:54:31.212 W/System.err(21355): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:385)
11-03 15:54:31.212 W/System.err(21355): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:492)
11-03 15:54:31.213 W/System.err(21355): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-03 15:54:31.213 W/System.err(21355): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-03 15:54:31.213 W/System.err(21355): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11-03 15:54:31.213 W/System.err(21355): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
11-03 15:54:31.213 W/System.err(21355): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
11-03 15:54:31.213 W/System.err(21355): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by tudosxxx** [comment]
xxxxxxxxxx 地址注释掉的

**Comment by tudosxxx** [comment]
今天更新就失败了，以前一直能用，现在PC上也能用。就手机不行

**Comment by cache444** [comment]
如果你订阅的地址本来就是被墙了那肯定更新不了。一个很简单的方法测试，如果你手机有其他vpn软件的话，先开启其他VPN，然后再打开NG更新订阅，如果能更新就说明是你订阅地址的问题

**Comment by lzpnbl** [comment]
订阅地址没用了，怎么弄一个新的啊？
