### ISSUE TITLE
开启本地DNS后，会导致DNS解析失败无法上网

### ISSUE THREAD

**Issue by xspeed1989** [2dust/v2rayNG#1280]
开启本地DNS后，会导致DNS解析失败无法上网
![Screenshot_2021-11-11-02-36-37-985_com v2ray ang](https://user-images.githubusercontent.com/5162926/141173101-4210cbb2-bd5f-49fc-b3b7-9547aef84339.jpg)

**Comment by ghost** [comment]
那就别勾选好了。

最近的issues光是看标题就不想点进去了，这个就当我手贱吧。

**Comment by xspeed1989** [comment]
> 那就别勾选好了。
> 
> 最近的issues光是看标题就不想点进去了，这个就当我手贱吧。

咋了
