### ISSUE TITLE
已经成功启动服务，无法访问墙外内容。

### ISSUE THREAD

**Issue by mudcastles** [2dust/v2rayNG#1281]
已经成功启动服务，测试真链接延时几百毫秒，tcping也是很小，但是无法访问Google和youtube等墙外内容。

**Comment by ghost** [comment]
去问你的代理服务器提供者可解。

**Comment by mudcastles** [comment]
> 去问你的代理服务器提供者可解。

我的订阅没有问题。相同的订阅我在电脑端V2RayN就可以用，在Android11的手机上就不行。

**Comment by drc5521** [comment]
一样的情况，服务端还会报这个错误和警告 [#785](https://github.com/233boy/v2ray/issues/785)

**Comment by ChloeKurumi** [comment]
> 去问你的代理服务器提供者可解。

同一个网络，同一个节点，电脑正常，但手机端测试连接正常却不能访问网站......之前都还正常.....

**Comment by drc5521** [comment]
> 去问你的代理服务器提供者可解。

自己搭的服务也是这个情况，电脑端没有这个问题，只有手机端会有这个问题。

**Comment by mudcastles** [comment]
不知道到底哪的问题，没解决，被close了。。。
