### ISSUE TITLE
订阅设置排序问题

### ISSUE THREAD

**Issue by raddyyt** [2dust/v2rayNG#1283]
我的订阅比较多，有十几个，添加时按速度快慢排好了顺序，最近发现列表顺序总是变得错乱，已启用的链接和已禁用的混在一起很难分辨。
求问能否给订阅列表添加手动排序功能呢，就是那种可以按住然后上下拖动的。每次想排序都要全部删除再重新添加实在是太伤了。

**Comment by ghost** [comment]
“就是那种可以按住然后上下拖动的” 
一直都可以。你为什么不长按试试呢

**Comment by raddyyt** [comment]
> 一直都可以。你为什么不长按试试呢

我的意思是说“订阅设置”里的“订阅链接”列表，不是主页的节点列表。目前找不到除了重填以外的方法能给订阅排序。
