### ISSUE TITLE
十数秒后自动断开连接

### ISSUE THREAD

**Issue by JZSTAR01** [2dust/v2rayNG#1284]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
始终保持连接
### 实际行为
描述实际发生了什么
在软件内不就断开连接
### 复现方法
1.iqoo手机或matepad11导入节点后开启服务十数秒自动断开连接
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
11-13 21:59:26.199 30300 30723 I com.v2ray.ang: Waiting for a blocking GC ProfileSaver
11-13 21:59:26.222 30300 30723 I com.v2ray.ang: WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 22.580ms
11-13 21:59:34.781 30300 30300 D com.v2ray.ang: Observe settings changed: pref_core_loglevel
11-13 21:59:36.830 30300 30300 I com.v2ray.ang: Settings ViewModel is cleared
11-13 21:59:39.215  9581  9581 D com.v2ray.ang: {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   "dns": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     "hosts": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "domain:googleapis.cn": "googleapis.com"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     "servers": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "1.1.1.1"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     ]
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   "inbounds": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "listen": "127.0.0.1",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "port": 10808,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "protocol": "socks",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "settings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "auth": "noauth",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "udp": true,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "userLevel": 8
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "sniffing": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "destOverride": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "http",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "tls"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         ],
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "enabled": true
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "tag": "socks"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "listen": "127.0.0.1",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "port": 10809,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "protocol": "http",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "settings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "userLevel": 8
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "tag": "http"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   ],
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   "log": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     "loglevel": "warning"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   "outbounds": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "mux": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "concurrency": 8,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "enabled": false
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "protocol": "vless",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "settings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "vnext": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:             "address": "[2406:da14:1c8:f600:3e12:6a94:ae9a:****]",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:             "port": 443,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:             "users": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:               {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:                 "encryption": "none",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:                 "flow": "",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:                 "id": "583a5ea2-4a88-4197-8119-57c2b053****",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:                 "level": 8,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:                 "security": "auto"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:               }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:             ]
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         ]
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "streamSettings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "network": "ws",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "security": "tls",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "tlsSettings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "allowInsecure": false,
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "serverName": "aws.*******.top"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "wsSettings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "headers": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:             "Host": "aws.********.top"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "path": "/imcpws?ed=2048"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "tag": "proxy"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "protocol": "freedom",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "settings": {},
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "tag": "direct"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "protocol": "blackhole",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "settings": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "response": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "type": "http"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       },
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       "tag": "block"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   ],
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   "routing": {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     "domainMatcher": "mph",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     "domainStrategy": "IPIfNonMatch",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     "rules": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       {
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "ip": [
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:           "1.1.1.1"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         ],
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "outboundTag": "proxy",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "port": "53",
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:         "type": "field"
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:       }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:     ]
11-13 21:59:39.215  9581  9581 D com.v2ray.ang:   }
11-13 21:59:39.215  9581  9581 D com.v2ray.ang: }
11-13 21:59:39.216  9581  9581 I GoLog   : loading core config
11-13 21:59:39.216  9581 10362 I GoLog   : Preparing Domain: [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443
11-13 21:59:39.216  9581 10362 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:39.217  9581 10362 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:39.217  9581  9581 I GoLog   : new core
11-13 21:59:39.217  9581  9581 I GoLog   : start core
11-13 21:59:39.218  9581 10362 I GoLog   : [Warning] core: Xray 1.4.5 started
11-13 21:59:39.235  9581  9581 D com.v2ray.ang: [/data/app/com.v2ray.ang-3-sEWd1eDV05md5PlkC-qA==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
11-13 21:59:39.237  9581  9581 D com.v2ray.ang: Process[pid=13309, hasExited=false]
11-13 21:59:39.237  9581  9581 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
11-13 21:59:39.288  9581 10372 D com.v2ray.ang: sendFd tries: 0
11-13 21:59:39.378  9581 10367 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:39.379  9581 10359 I GoLog   : tcp:127.0.0.1:52490 accepted tcp:114.115.188.228:5223 [socks >> proxy]
11-13 21:59:39.379  9581 10367 I GoLog   : fdConn unix.Connect err, Close Fd: 100 Err: network is unreachable
11-13 21:59:39.380  9581 10362 I GoLog   : [Warning] [1277516405] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:39.642  9581 10359 I GoLog   : udp:127.0.0.1:60503 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:39.643  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:39.643  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:39.644  9581 10359 I GoLog   : [Warning] [16118270] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:40.263  9581 10359 I GoLog   : tcp:127.0.0.1:52492 accepted tcp:157.148.42.213:80 [socks >> proxy]
11-13 21:59:40.263  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:40.264  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 100 Err: network is unreachable
11-13 21:59:40.265  9581 10359 I GoLog   : [Warning] [1429501933] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:41.217  9581 10359 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:41.217  9581 10359 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:41.650  9581 10396 I GoLog   : udp:127.0.0.1:42814 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:41.651  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:41.654  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:41.657  9581 10396 I GoLog   : [Warning] [1031701686] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:43.218  9581 10396 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:43.218  9581 10396 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:43.418  9581 10362 I GoLog   : tcp:127.0.0.1:52496 accepted tcp:114.115.188.228:443 [socks >> proxy]
11-13 21:59:43.418  9581 10397 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:43.419  9581 10397 I GoLog   : fdConn unix.Connect err, Close Fd: 100 Err: network is unreachable
11-13 21:59:43.419  9581 10367 I GoLog   : [Warning] [2208155459] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:43.650  9581 10359 I GoLog   : udp:127.0.0.1:60503 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:43.650  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:43.651  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:43.652  9581 10359 I GoLog   : [Warning] [16118270] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:45.219  9581 10359 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:45.220  9581 10359 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:45.656  9581 10359 I GoLog   : udp:127.0.0.1:42814 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:45.656  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:45.661  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:45.662  9581 10397 I GoLog   : [Warning] [1031701686] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:45.895  9581 10359 I GoLog   : udp:127.0.0.1:54880 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:45.895  9581 10397 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:45.896  9581 10397 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:45.896  9581 10359 I GoLog   : [Warning] [2254043832] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:47.223  9581 10359 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:47.223  9581 10359 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:47.661  9581 10359 I GoLog   : udp:127.0.0.1:50195 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:47.661  9581 10367 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:47.663  9581 10367 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:47.664  9581 10362 I GoLog   : [Warning] [2247847883] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:47.903  9581 10396 I GoLog   : udp:127.0.0.1:56016 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:47.903  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:47.906  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:47.907  9581 10396 I GoLog   : [Warning] [2990506312] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:49.224  9581 10396 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:49.224  9581 10396 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:49.666  9581 10396 I GoLog   : udp:127.0.0.1:60643 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:49.666  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:49.668  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:49.669  9581 10397 I GoLog   : [Warning] [1421235041] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:49.905  9581 10362 I GoLog   : udp:127.0.0.1:54880 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:49.906  9581 10359 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:49.909  9581 10359 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:49.910  9581 10367 I GoLog   : [Warning] [2254043832] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:51.226  9581 10367 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:51.226  9581 10367 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:51.669  9581 10367 I GoLog   : udp:127.0.0.1:50195 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:51.669  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:51.673  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:51.675  9581 10397 I GoLog   : [Warning] [2247847883] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:51.909  9581 10397 I GoLog   : udp:127.0.0.1:56016 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:51.910  9581 10362 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:51.914  9581 10362 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:51.916  9581 10367 I GoLog   : [Warning] [2990506312] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:53.227  9581 10367 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:53.227  9581 10367 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:53.673  9581 10367 I GoLog   : udp:127.0.0.1:60643 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:53.674  9581 10359 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:53.677  9581 10359 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:53.678  9581 10396 I GoLog   : [Warning] [1421235041] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:53.917  9581 10396 I GoLog   : udp:127.0.0.1:59526 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:53.917  9581 10359 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:53.919  9581 10359 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:53.922  9581 10367 I GoLog   : [Warning] [2207607826] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:55.229  9581 10367 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:55.229  9581 10367 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:55.921  9581 10367 I GoLog   : udp:127.0.0.1:34968 accepted udp:180.76.76.76:53 [socks >> proxy]
11-13 21:59:55.922  9581 10359 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:55.924  9581 10359 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:55.926  9581 10396 I GoLog   : [Warning] [2380778673] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:57.231  9581 10397 I GoLog   : PrepareDomain SplitHostPort Err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:57.231  9581 10397 I GoLog   : PrepareDomain err: address [[2406:da14:1c8:f600:3e12:6a94:ae9a:****]]:443: missing port in address
11-13 21:59:57.926  9581 10397 I GoLog   : udp:127.0.0.1:59526 accepted udp:1.1.1.1:53 [socks -> proxy]
11-13 21:59:57.927  9581 10396 I GoLog   : Not Using Prepared: tcp,[2406:da14:1c8:f600:3e12:6a94:ae9a:****]:443
11-13 21:59:57.931  9581 10396 I GoLog   : fdConn unix.Connect err, Close Fd: 93 Err: network is unreachable
11-13 21:59:57.933  9581 10397 I GoLog   : [Warning] [2207607826] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://[2406:da14:1c8:f600:3e12:6a94:ae9a:****]/imcpws):  > network is unreachable
11-13 21:59:59.232  9581 10397 I GoLog   : PrepareDomain maxRetry reached. exiting.
11-13 21:59:59.233  9581 10397 I GoLog   : vServer cannot resolved, shutdown
11-13 21:59:59.237  9581 10397 D com.v2ray.ang: tun2socks destroy
</details>

### 环境信息
无
### 额外信息（可选）
最新版1.6.23

**Comment by yuhan6665** [comment]
[2406:da14:1c8:f600:3e12:6a94:ae9a:] 地址不要加方括号

**Comment by JZSTAR01** [comment]
> [2406:da14:1c8:f600:3e12:6a94:ae9a:] 地址不要加方括号

非常感谢你快速的回应，这是我使用直接使用v2rayN的URL链接导入到v2rayNG的，没有想到问题出在这里，我想有很多人都可能遇到这个问题，希望在以后的版本可能优化？或者我应该去v2rayN项目反映？

**Comment by yuhan6665** [comment]
这个是 core 的格式 去 v2rayN 那边开个 issue 吧

**Comment by 13356914971** [comment]
vless://fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf@[::ffff:156.238.18.244]:8880?encryption=none&security=none&sni=sg.laoyoutiao.link&type=ws&host=sg.laoyoutiao.link&path=Telegram%40WangCai2%2F%3Fed%3D2048#US%E7%BE%8E%E5%9B%BD%28mibei77.com%20%E7%B1%B3%E8%B4%9D%E8%8A%82%E7%82%B9%E5%88%86%E4%BA%AB%29   这个也会断开
