### ISSUE TITLE
打开时有广告，让下载软件

### ISSUE THREAD

**Issue by CryptoXDom** [2dust/v2rayNG#1285]

**Comment by CryptoXDom** [comment]
![Screenshot_2021-11-16-10-16-05-695_com v2ray ang](https://user-images.githubusercontent.com/84830636/141883575-fb36ff4d-216f-4eda-bba8-95b55afc97ad.jpg)

**Comment by Ainner** [comment]
+1

**Comment by RedLeavesSun** [comment]
做了一个测试
魅族17: 没有开屏广告
小米9: 有开屏广告

怀疑是小米加的

**Comment by Euthpic** [comment]
我测试了下,打开京东,切换到wifi,再打开v2rayng就有京东和抖音的开屏广告.  手机小米10s miui12.5.8

**Comment by RedLeavesSun** [comment]
不对比不知道 对了一些常见的app，相同的app，不同的手机，小米就是多了开屏广告

**Comment by crmmc** [comment]
红米k20pro，昨日更新最新版确实忽然多了广告很奇怪，发现好像最新版本包名好像也不同，逐个版本降级到1.6.15版本就没广告了。

**Comment by Aobanana-chan** [comment]
小米手机的原因。Mix2同样有这个问题。
删掉手机根目录下MIAD文件夹，第一次开就没广告了，但是会自动创建mida文件夹，之后就又有广告。

**Comment by crmmc** [comment]
如果是小米的问题，那这太恶心了。
但是我降级到1.6.15就内有任何问题，但是1.6.16及以上版本100%出现广告，辛亏1.6.15版本对我来说完全够用了，xray-core也只是在进行修复行更新而已，没有很有用的大版本更新。
我昨晚那么觉得MIAD这种过于明显的文件夹名字和可能存在的特定机型识别行为是碰瓷小米的呢（纯猜测），因为新版连应用包名都变了。

**Comment by badgv** [comment]
之前版本都没有广告，好像更个新有广告了

**Comment by Euthpic** [comment]
https://zhuanlan.zhihu.com/p/356367971  有问题的小米用户可以根据这个来屏蔽,但是不确定这个广告计划是不是开发者主动加入的

**Comment by badgv** [comment]
> https://zhuanlan.zhihu.com/p/356367971 有问题的小米用户可以根据这个来屏蔽,但是不确定这个广告计划是不是开发者主动加入的

能否告知下从哪个版本开始有广告的，我回退下？我今天直接在PLAY更新的，上次也是PLAY更新的，没有广告，今天更新的就有广告了

**Comment by RedLeavesSun** [comment]
> > https://zhuanlan.zhihu.com/p/356367971 有问题的小米用户可以根据这个来屏蔽,但是不确定这个广告计划是不是开发者主动加入的
> 
> 能否告知下从哪个版本开始有广告的，我回退下？我今天直接在PLAY更新的，上次也是PLAY更新的，没有广告，今天更新的就有广告了

看样子应该是APP被碰瓷了

**Comment by badgv** [comment]
> > > https://zhuanlan.zhihu.com/p/356367971 有问题的小米用户可以根据这个来屏蔽,但是不确定这个广告计划是不是开发者主动加入的
> > 
> > 
> > 能否告知下从哪个版本开始有广告的，我回退下？我今天直接在PLAY更新的，上次也是PLAY更新的，没有广告，今天更新的就有广告了
> 
> 看样子应该是APP被碰瓷了

我退回了之前的版本，一样有广告

**Comment by crmmc** [comment]
红米K20Pro,系统MIUI 12.5.4稳定版更新到最新版有广告，但是小米8是MIUI12.0.4系统更新到最新版没广告，也做了其他实验证明了不是v2rayng里加了广告，看了楼上的说法，应该就是小米系统加的广告，估计是v2rayng的包名给人恶意申请了小米的那个广告计划了，社会真是险恶啊，小米审核就这？？？确实该整治一下！
把小米的“智能服务”的“在其他应用上显示”关掉，在/sdcard/Android/data/com.miui.systemadsolution/files/里删掉miad文件夹，创建一个与之同名的文件就可以了。（试试zarchiver可以安卓11直接访问data文件夹，免费好用）

**Comment by badgv** [comment]
> 红米K20Pro,系统MIUI 12.5.4稳定版更新到最新版有广告，但是小米8是MIUI12.0.4系统更新到最新版没广告，也做了其他实验证明了不是v2rayng里加了广告，看了楼上的说法，应该就是小米系统加的广告，估计是v2rayng的包名给人恶意申请了小米的那个广告计划了，社会真是险恶啊，小米审核就这？？？确实该整治一下！ 把小米的“智能服务”的“在其他应用上显示”关掉，在/sdcard/Android/data/com.miui.systemadsolution/files/里删掉miad文件夹，创建一个与之同名的文件就可以了。（试试zarchiver可以安卓11直接访问data文件夹，免费好用）

真好使，我把miad文件夹删了，弄了个miad的文件放进去，启动就没有广告了

**Comment by ghost** [comment]
有广告的全都是自己设备OS的问题。

不要随意瞎发issues，楼上某些评论不能说是随意，只能说是无脑。

“在提出问题前请先自行排除自身问题，同时也请通过搜索确认是否有人提出过相同问题”

**Comment by crmmc** [comment]
> 有广告的全都是自己设备OS的问题。
> 
> 不要随意瞎发issues，楼上某些评论不能说是随意，只能说是无脑。
> 
> “在提出问题前请先自行排除自身问题，同时也请通过搜索确认是否有人提出过相同问题”

首先，这确实不是第一个提出类似问题的issus，看到它open而且遇到相同问题就进来讨论了。
其次，“不要随意瞎发issue，楼上某些评论不能说是随意，只能说是无脑”这样富含攻击性的引战话语实属不应该出来污染互联网环境，不是第一个发现这个问题，不应该接受你这种人的教育，更不应该接受你这种人的谩骂，不会自我控制，随意宣泄情绪是素质低下，教育程度不足的表现。
再说，问题确实解决了，你又不是开发者，而且也没有碍着你的事，“管理者”般的口吻对普通民众破口大骂实属不应该
最后，这个issue确实应该关闭了，毕竟在众多帮忙者的帮助下，完美解决。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/930

**Comment by ghost** [comment]
@crmmc 网络菩萨？你从哪里看出我的评论具有攻击性？ 还是说因为评论的内容里带有“无脑”两个字就是攻击就是谩骂了？如果这样就是攻击谩骂，那我很难想象你是怎么活在当下的。你第一天上网？我寻思诸如“sb”这样直白的字词，不管是在现实中还是网络上，几乎都是随处可见、再正常不过的词汇了吧？怎么一个“无脑”就攻击谩骂了？玻璃心满级？

其次，上来就是对方“宣泄情绪”，对方“素质低下、教育不足”。究竟是谁在宣泄？您的素质和教育又体现在何处？ 还有，引用issues的基本准则也成了“管理者口吻”，那还好我引用的不是相关文档，不然我就变成“作者口吻”了。。

最重要的一点，既然发出问题，那就要接受问题底下的所有评论。你既然想把照片发朋友圈，那就不要怕有人评论你丑。要么你就别发。

自己对号入座就不说了，网络菩萨和玻璃心也不说了。但上来就直接把素质和教育扯进来这种事，我只能说一个人越缺乏什么，他就越爱表现什么，意识里也越爱动不动就去提及自身所缺乏的东西。

**Comment by crmmc** [comment]
> @crmmc 网络菩萨？你从哪里看出我的评论具有攻击性？ 还是说因为评论的内容里带有“无脑”两个字就是攻击就是谩骂了？如果这样就是攻击谩骂，那我很难想象你是怎么活在当下的。你第一天上网？我寻思诸如“sb”这样直白的字词，不管是在现实中还是网络上，几乎都是随处可见、再正常不过的词汇了吧？怎么一个“无脑”就攻击谩骂了？玻璃心满级？
> 
> 其次，上来就是对方“宣泄情绪”，对方“素质低下、教育不足”。究竟是谁在宣泄？您的素质和教育又体现在何处？ 还有，引用issues的基本准则也成了“管理者口吻”，那还好我引用的不是相关文档，不然我就变成“作者口吻”了。。
> 
> 最重要的一点，既然发出问题，那就要接受问题底下的所有评论。你既然想把照片发朋友圈，那就不要怕有人评论你丑。要么你就别发。
> 
> 自己对号入座就不说了，网络菩萨和玻璃心也不说了。但上来就直接把素质和教育扯进来这种事，我只能说一个人越缺乏什么，他就越爱表现什么，意识里也越爱动不动就去提及自身所缺乏的东西。

首先，我发issue的目的不是为了让你明白错误，而是给后来人看个清楚明白，你看不懂没事，我是为了其他人不要误解这个issue里的提问者和热心的解答者，不要像热心的解答者寒心，让这个世界的好人寒心！
你发这些废话的时候，问题都得到解决了，只是没有close而已，你反而网络警察一般进来一番说教，真是可笑至极！

都是中国人，读读你自己发的第一个issue吧

[
“有广告的全都是自己设备OS的问题。

不要随意瞎发issues，楼上某些评论不能说是随意，只能说是无脑。

“在提出问题前请先自行排除自身问题，同时也请通过搜索确认是否有人提出过相同问题”
]
第一句没问题，第二句明显携带个人情感，感情宣泄，是废话，也是我所批评的。说大道理一定要骂两句别人如何不如你？了？？？，仅仅第三句引用了相关文档，引用了一句正确的话就一定全盘正确？？而且我批评的可不是第三句话，典型的转移话题，稻草人谬误！！

说别人发issue是“乱发”，上面的评论全都是“无脑”评论，回应质疑的开头就给我贴标签辱骂我“网络菩萨”，现在的互联网环境就是给这类人搞坏的，还说别人不能适应环境，我搞坏的环境，不尽力修好，还去吐槽那些想让环境恢复原状的人，就像人类无止境破坏环境，还说灭绝的动物不能适应环境的变化死亡，都是天意，不可避免！这不可笑吗？谁对谁错人尽皆知，只是当局者迷罢了。
最后一段也直接说“别怕人说你丑”，暴露了你发issue的真实目的和发的东西的本质。
仔细阅读你发的这篇话，多少内容不是在辛辣的讽刺他人，批评他人和为自己批评他人的行径寻找借口。我不会再回复你的任何辛辣的讽刺了批评了，我不想让github都变成喷子们的战地，网络面具人的战场！对你，不值得！
我不会再对你的话给与任何回复，你的出发点就不含多少正义！

**Comment by Euthpic** [comment]
> 有广告的全都是自己设备OS的问题。
> 
> 不要随意瞎发issues，楼上某些评论不能说是随意，只能说是无脑。
> 
> “在提出问题前请先自行排除自身问题，同时也请通过搜索确认是否有人提出过相同问题”

网络环境就靠你的键盘净化了 :)
