### ISSUE TITLE
华为手机限速

### ISSUE THREAD

**Issue by jhfcU7O** [2dust/v2rayNG#1286]
华为手机在链接前测试全部配置Tcping时所有服务器网速显示正常，但连接后再测试网速变慢很多，甚至无法正常连接
![Screenshot_20211117_165131_com v2ray ang](https://user-images.githubusercontent.com/94524127/142168558-a13c8867-4201-4cf1-b44c-86bcd4503ee5.jpg)
![Screenshot_20211117_165154_com v2ray ang](https://user-images.githubusercontent.com/94524127/142168589-265af753-c5bc-42fb-9583-c4a1ccf9b24f.jpg)
尝试卸载重装或切换服务器都没有效果

**Comment by silencelzx** [comment]
+1

**Comment by RallyQ** [comment]
三部华为手机使用都没问题，自建v2服务器
你这是公用v2吧，用的人多无法保证速度，不能看测速

**Comment by d2184** [comment]
TCPing是测端口延迟的吧，测网络连接应该测真连接/urltest
