### ISSUE TITLE
v2ray用CDN代理以后 手机上不能用

### ISSUE THREAD

**Issue by moumou-cpu** [2dust/v2rayNG#1287]
--------- beginning of system
--------- beginning of main
11-18 16:47:15.313 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:15.359 I/GoLog   (15861): [Warning] [2245549845] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:15.430 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:15.503 I/GoLog   (15861): [Warning] [2476787369] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:15.518 I/GoLog   (15861): [Warning] [1331694608] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:15.536 I/GoLog   (15861): udp:127.0.0.1:39999 accepted udp:172.217.163.45:443 [socks >> proxy]
11-18 16:47:15.631 I/GoLog   (15861): [Warning] [614716077] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:15.647 I/GoLog   (15861): [Warning] [83813731] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:15.677 I/GoLog   (15861): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:15.734 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:15.735 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:16.013 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:16.196 I/GoLog   (15861): [Warning] [4197404573] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:16.224 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:16.235 I/GoLog   (15861): udp:127.0.0.1:40396 accepted udp:1.1.1.1:53 [socks -> proxy]
11-18 16:47:16.383 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:16.406 I/GoLog   (15861): [Warning] [202993543] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://moumou.store/KTNUXHZi/): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
11-18 16:47:16.429 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:16.433 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:17.082 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:17.132 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:17.266 I/GoLog   (15861): Using Prepared: 172.67.182.72
11-18 16:47:17.274 I/GoLog   (15861): Using Prepared: 172.67.182.72
1

电脑v2rayN正常

**Comment by superabbite1** [comment]
同样的问题，用手机就这样，感觉无解啊
