### ISSUE TITLE
远程dns和境内dns都设置为加密dns时(域名）dns查询失败

### ISSUE THREAD

**Issue by Fhokud** [2dust/v2rayNG#1288]
![IMG_2021_2845.jpg](https://user-images.githubusercontent.com/62986412/142426793-db9af569-2186-48fb-8093-e3387b39f2d9.jpg)

如上配置
当为都为DoT/DoH/DoQ时dns查询失败，看了一下日志，是因为无法解析加密dns的ip地址所以查询失败，无法使用，(虽然延迟测试正常)
注:自建的dns，所以不能为ip申请tls证书

在[SagerNet](https://github.com/SagerNet/SagerNet)或[Anxray](https://github.com/XTLS/AnXray/releases)
可以通过一下方法解决
![IMG_2021_31984.jpg](https://user-images.githubusercontent.com/62986412/142427913-6f73f048-9da1-4c36-ad84-532404a2c305.jpg)
通过内置的dns将域名解析到对应IP

v2rayng里这个问题怎么解决？

**Comment by GeorgeRudd** [comment]
远程dns删掉+local

**Comment by Fhokud** [comment]
我不打算远程dns走出站
