### ISSUE TITLE
ss 协议里面的 chacha20 加密方式没有了

### ISSUE THREAD

**Issue by declandragon** [2dust/v2rayNG#1289]
版本升级之后（不知道哪个版本开始的），chacha20  没有了，导致服务不能启动

还有下面两种 chacha20 的 加密方式，测试不能正常使用。
chacha20-poly1305
chacha20-ietf-poly1305

1.6.17 是正常的

**Comment by Fhokud** [comment]
删了不支持AEAD的加密算法并默认禁用OTA

**Comment by 2dust** [comment]
https://www.v2fly.org/config/protocols/shadowsocks.html

**Comment by declandragon** [comment]
加密方式 `chacha20` 已经被移除  https://github.com/v2fly/v2fly-github-io/commit/fb859f42b62fd4ccf4b51e582085c2303fb95b2b
