### ISSUE TITLE
network connection check still error

### ISSUE THREAD

**Issue by KillingJacky** [2dust/v2rayNG#129]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
![image](https://user-images.githubusercontent.com/5130185/46573094-ccb43280-c9c2-11e8-9cdc-20565d8c046f.png)

### 复现方法
1. 点击底部”检查网络连接“
2.
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

### 环境信息
samsung s8 Android Version 8.0.0

**Comment by eet-eet** [comment]
Same problem to you， i use s8+，v2rayng 0.5.9（Googleplay），mkcp+wireguard(error）,mkcp+srtp(error),ws+tls(okay).
