### ISSUE TITLE
Issue with app bundle (aab) version

### ISSUE THREAD

**Issue by jianxiansining** [2dust/v2rayNG#1290]
When i install apk versions from android studio its ok.
But when i install aab version vpn connected and unfortunately it's not working

**Comment by yhpgi** [comment]
Same problem here.. sad.. :(

**Comment by mxbhaee** [comment]
You can fix this issue of aab by adding the following in

gradle.properties : add this line below 👇👇

```
android.bundle.enableUncompressedNaticeLibs = false 

```

build.gradle app : add it inside dependencies { 

}

```
implementation fileTree(dir: 'jniLibs', include: ['*.so'], exclude: [ ])

```

If you need explanation to why this two line could help or if it works out to why it did work out you can ask below 👇👇 .

If this fails send the issue your facing make sure you test all protocols , vmess , socks etc and comment clear which ones have failed to function .

**Comment by PingerAI** [comment]
同样的问题

**Comment by PingerAI** [comment]
pay attention！pay attention！pay attention！
gradle.properties : add this line below：
android.bundle.enableUncompressedNativeLibs = false
not
android.bundle.enableUncompressedNaticeLibs = false

**Comment by zhengtingguang** [comment]
I have configured android.bundle.enableUncompressedNativeLibs = false, but the aab package still does not work, can you solve it?

**Comment by la-niina** [comment]
Yes, Do you have your project on github and the aab for testing, but try adding bundle 
```
{
    enableUncompressedNativeLibs = false
}
``` 
in you build .gradle or else bundle the lib.aar in a module the issue is playstore is not stripping the .aar lib well , create a module for the libv2ray.aar , will solve that also can use ProGuard

**Comment by mik-sh** [comment]
`android.bundle.enableUncompressedNativeLibs = false` is depreceted now

This works for me:
```
android {
    packagingOptions {
        jniLibs.useLegacyPackaging = true
    }
}
```
