### ISSUE TITLE
总是不小心点到删除节点。

### ISSUE THREAD

**Issue by 110560** [2dust/v2rayNG#1296]
总是不小心点到删除, 不会弹出是确认删除 或撤销的提示  求改进。。。。。总是不小心点到，好烦。

**Comment by xkrusher** [comment]
我也是啊，同样的问题，有时候一不小心就有节点找不到了，随便碰到就把节点删除了。希望大佬改进一下

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.5
