### ISSUE TITLE
使用美西VPS搭建vless ws tls访问时，加载时间很长才能打开外网网站

### ISSUE THREAD

**Issue by ximiTech** [2dust/v2rayNG#1297]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
使用美西VPS搭建vless ws tls访问时，加载时间在延时范围内

### 实际行为
使用美西VPS搭建vless ws tls访问时，加载时间很长才能打开外网网站，如google.com等

### 复现方法
每次都可以复现

**Comment by ghost** [comment]
建议先去用用jc的美西，然后再好好反思下问题所在。
