### ISSUE TITLE
0.2.6通用版默认配置不可用

### ISSUE THREAD

**Issue by JuanMao1997** [2dust/v2rayNG#13]
直接在GitHub下载的0.2.6通用版，
安装后使用默认配置成功开启服务，
但无法使用（浏览器打不开任何网址）。

**Comment by 2dust** [comment]
请自己配置服务器

**Comment by AbcdefgXW** [comment]
昨晚1点左右突然全部不能用，不知道是不是更新的问题……到现在我还没办法翻出来，服务端没动它，我Play都上不去T_T但是应该不是客户端的问题……
