### ISSUE TITLE
telegram正常使用，但其他app和谷歌这些网页无响应。

### ISSUE THREAD

**Issue by github-24** [2dust/v2rayNG#1301]
今天开始的，只有tg正常使用，其他皆无响应

### 预期行为
正常使用

### 实际行为
无法打开网页或者无响应

**Comment by d2184** [comment]
这应该是DNS的问题，tg是直接跟IP建立连接的，不需要做DNS域名解析所以没问题。这个问题可以开启DOT解决，尝试打开手机系统设置里的DNS加密/私人DNS

**Comment by github-24** [comment]
> 这应该是DNS的问题，tg是直接跟IP建立连接的，不需要做DNS域名解析所以没问题。这个问题可以开启DOT解决，尝试打开手机系统设置里的DNS加密/私人DNS

具体要怎么操作
