### ISSUE TITLE
希望能增加个使用前置代理的功能,比如添加两个out服务器,其中一个指定另一个为前置代理

### ISSUE THREAD

**Issue by Tmalll** [2dust/v2rayNG#1305]
希望能增加个使用前置代理的功能,
比如添加两个out服务器,
其中一个指定另一个为前置代理
在文档里就是下面这两个, 应该不难实现吧
https://xtls.github.io/config/outbound.html#proxysettingsobject
https://www.v2fly.org/config/outbounds.html#proxysettingsobject

**Comment by ghost** [comment]
之前也有人提issue希望增加链式代理，不过似乎未被开发者们看好
