### ISSUE TITLE
geoip.dat 和 geosite.dat 选择更新

### ISSUE THREAD

**Issue by 22NinE99** [2dust/v2rayNG#1307]
希望可以加一个 https://github.com/Loyalsoldier/v2ray-rules-dat 的更新功能，不用手动替换 geoip.dat 和 geosite.dat ，增强配置路由功能

**Comment by ghost** [comment]
这个其实没啥必要。手动替换也只是几秒钟的事，不麻烦。

**Comment by ghost** [comment]
这个不需要频繁更新

**Comment by KOF136** [comment]
> 这个其实没啥必要。手动替换也只是几秒钟的事，不麻烦。

用户多一个选择嘛

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.0
