### ISSUE TITLE
三星note9安装软件后ping报错

### ISSUE THREAD

**Issue by jiyuedong** [2dust/v2rayNG#131]
三星note9，安装版本为0.5.9通用版，导入节点测试时会报错，具体错误如图，但是实际测试的时候代理成功。三星安卓版本8.1，
![123](https://user-images.githubusercontent.com/21293081/47204784-c3f63000-d3b6-11e8-969e-8690b5d949e8.jpg)

**Comment by trivita** [comment]
I have that too. oneplus6 Android pie

**Comment by leowood2000** [comment]
same boat, note 9

**Comment by BackTrackCRoot** [comment]
我也是这个问题

**Comment by twzchi** [comment]
一样的，测速不成功

**Comment by iikk** [comment]
s8一样的问题，不能测速。浏览器和app能正常番。

显示：
失败：Attempt to invoke virtual method 'java.lang.String java.net.InetAddress.toString()' on a null object reference

**Comment by SilasY** [comment]
S9+也是一样的问题

**Comment by woodytian** [comment]
S8+，一样。能番但是不能测速，刚开始还以为不能用。

**Comment by niuniuliu** [comment]
Some error on Samsung's Note 8, Note 9, S8+

**Comment by unfailingfireworks** [comment]
三星a9star 一样的问题。

**Comment by githoniel** [comment]
the same

**Comment by skyDebugger** [comment]
一样,NOTE9有这样的问题

**Comment by soyuzom** [comment]
同，三星S7  Android8.0   
测速就提示：
attempt to invoke virtual method java.lang.string java.net.inetaddress.tostring() on a null object reference

**Comment by Colmi** [comment]
S10 遇到了相同的情况

**Comment by fotock** [comment]
S10+。同遭遇。

**Comment by zhenpingfeng** [comment]
same here on Samsung S10+.

**Comment by XuHuapeng001** [comment]
S9+ Android P 同样问题。

**Comment by ericgu2017** [comment]
Note 8
