### ISSUE TITLE
socks协议不支持非v2ray-core的服务器

### ISSUE THREAD

**Issue by RelicOfTesla** [2dust/v2rayNG#1310]
socks格式，不支持非v2ray的服务端，
测试网页报 net::ERR_NAME_NOT_RESOLVED 错误

防火墙udp端口已全开

逍遥模拟器安卓镜像7.1

v2rayNG v1.6.23

[gost](https://github.com/ginuerzh/gost) 
```
gost -L :5779
```

[goproxy](https://github.com/snail007/goproxy)
```
proxy socks -t tcp -p "0.0.0.0:5778"
```

以上两工具，使用安卓WIFI里的代理设置(goproxy是http模式测试的，不算)，以及Postern这个app，**是正常的**。

使用v2rayNG连接就不正常，已重试过重装，手工删除所有VPN，无效!

**Comment by zblc4c4** [comment]
参考https://github.com/2dust/v2rayNG/issues/91
