### ISSUE TITLE
null

### ISSUE THREAD

**Issue by cuynu** [2dust/v2rayNG#1312]
null

**Comment by cuynu** [comment]
@2dust

**Comment by ghost** [comment]
Decompile yourself

**Comment by cuynu** [comment]
@forever8938 How to decompile?

**Comment by ShellWen** [comment]
It's a open source application, which means that you can compile it by yourself instead of modify it.
And it's ResGuard, which is enable in Android Gradle Plugin by default.

**Comment by cuynu** [comment]
@ShellWen Okay. I will decompile yourself.
