### ISSUE TITLE
客户端shadowsocks ivCheck选项

### ISSUE THREAD

**Issue by GeorgeRudd** [2dust/v2rayNG#1313]
根据https://github.com/v2fly/v2ray-core/pull/777#issuecomment-813963430 好像客户端服务端要同时开启ivCheck
服务端已经开了 但是在客户端没找到设置的地方 请问是自适应吗

另外1.5.1新增了 xchacha20-ietf-poly1305 加密 请问客户端会加上这个选项吗

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/blob/main/Shadowsocks-TCP/README.md#android%E7%B3%BB%E7%BB%9F%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97

暂时建议你使用自定义配置，参考上面的方法

**Comment by 2dust** [comment]
请使用自定义配置
