### ISSUE TITLE
订阅链接能一键导入么？

### ISSUE THREAD

**Issue by raddyyt** [2dust/v2rayNG#1314]
发现其他客户端有一键导入的功能，像CFA在链接前添加clash://install-config?url=，这样用网站转换订阅链接后就可以点击按钮一键导入，对于攒了很多条订阅链接时是很有用的，V2rayN和v2rayNG有这样的设置么，我没有搜索到有相关的介绍。

**Comment by LukkaVog** [comment]
v2rayng://install-config?url=
