### ISSUE TITLE
建议加入隐藏后台功能

### ISSUE THREAD

**Issue by iridescent233** [2dust/v2rayNG#1316]
希望可以加入隐藏后台功能
![Screenshot_20211223-190247](https://user-images.githubusercontent.com/23291458/147231478-3e5b2f4e-a076-4ebd-9aaa-4aad67c0eaea.jpg)

**Comment by GeorgeRudd** [comment]
不知道你用的什么牌子手机 把自启打开 电池优化啥的关了 这样划掉后台也不会断

**Comment by iridescent233** [comment]
> 不知道你用的什么牌子手机 把自启打开 电池优化啥的关了 这样划掉后台也不会断

谢谢，可以了 ，我是一加手机

**Comment by ghost** [comment]
tips: 从桌面/窗口小部件直接启动即可。
