### ISSUE TITLE
更新订阅混乱问题

### ISSUE THREAD

**Issue by llllllllqq** [2dust/v2rayNG#132]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
更新订阅后，顺序按订阅链接的排序，分组依次排列

### 实际行为
哪个订阅链接先下载完就排在上面

### 复现方法
1.更新订阅
2.再次更新订阅

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
无。不需要日志
```
</details>

### 环境信息
任意

**Comment by 2dust** [comment]
因为更新是并发不可控的,所以无法顺序得到结果

**Comment by llllllllqq** [comment]
那可否记住上次选择的【节点】，而不是上次选择的【位置】？
每次订阅更新顺序乱了之后，上次选中的节点就变了

**Comment by 2dust** [comment]
因为节点是没有id的,并且更新后有id也会被删除,所以从一开始设计就是记住的位置
如果要改变这点,是需要重构很多功能的
所以结论是暂时做不到

在服务器还算可用的情况下,尽量少更新订阅
