### ISSUE TITLE
Wifi = OK, Cellular = DEAD.

### ISSUE THREAD

**Issue by alcatraz-zz** [2dust/v2rayNG#1325]
Up until a few days ago my V2rayNG stopped working on cellular. It just gives the error as in "pipe closed yada yada". On wifi it works fine.

It's an Honor phone running android8 Nougat. Tried 1.6.27 and 1.6.28. Both are the same. I tried to uninstall and reinstall + setup but the problem remains.

Anyone got a clue? Thank you for reading and commenting. 👍

**Comment by ndhanh96** [comment]
it's your server not set up properly.
