### ISSUE TITLE
应该下载哪个版本？

### ISSUE THREAD

**Issue by daminoac** [2dust/v2rayNG#1326]
![Screenshot_20220101_150734_com android browser](https://user-images.githubusercontent.com/96685208/147845778-5f32cf67-3279-4a0a-90df-a98502801edc.jpg)

**Comment by mingyoucao** [comment]
![Uploading Screenshot_20220101_150734_com.android.browser.jpg…]()

**Comment by yuhan6665** [comment]
Can't go wrong with the biggest one

**Comment by yin1999** [comment]
ARM架构手机（高通、麒麟、联发科）：

| 架构 | 说明 |
| ---- | ---- |
| `arm64-v8a` | 支持绝大部分的现代手机（64位，高通骁龙810开始的SoC均支持） |
| `armeabi-v7a` | 旧手机（32位，到目前为止的高通和联发科芯片均支持，但在8Gen1等SoC下性能不会太好） |

一般按上面两个下就可以了（除非是很特殊的Android机型）。
