### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by esthernofoente** [2dust/v2rayNG#1327]
I'm using Vmess for the past few days and it had been working amazing, but since yesterday when I click to check connection this message appears : 
"Fail to detect internet connection: context deadline exceeded"

Anyone knows how can I solve this problem??

**Comment by yuhan6665** [comment]
Might be an issue with Vmess AEAD, try older version like https://github.com/2dust/v2rayNG/releases/tag/1.6.18

**Comment by esthernofoente** [comment]
It solved the problem, thanks

**Comment by esthernofoente** [comment]
It solved the problem, thanks

**Comment by esthernofoente** [comment]
It solved the problem, thanks

**Comment by o01eg** [comment]
Could it be solved in recent 1.6.30 version? In recent v2ray logs I get `VMessAEAD is enforced and a non VMessAEAD connection is received.`

**Comment by o01eg** [comment]
Oh, it looks like `alterId` should be 0 so AEAD is supported.
