### ISSUE TITLE
怎样绕开BT(P2P)流量？

### ISSUE THREAD

**Issue by Gokou-Ruri** [2dust/v2rayNG#1328]
### 预期行为
希望可以绕开BT流量，也就是让同一个APP中的P2P流量或非http(s)端口流量走直连，而http境外流量走代理。

### 实际行为
目前BT流量走的是代理。

### 复现方法
因为我用的是termux里的transmission 3.0（网站限制了BT客户端种类，只能使用transmission），而termux平时是需要走代理的（例如官方软件源和youtube-dl等软件需要走代理），但transmission很显然是不能走代理的，但现在我测试发现transmission的流量全都走了代理。
geo文件我目前用的是[v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)。
使用的规则如下：
```
代理：geoip:telegram,
      geosite:gfw,
      geosite:greatfire,
直连：默认路由规则
阻止：默认路由规则
```

PC端v2rayN我在直连规则里填入了0-65535（port），实测BT是不会走代理的。但我在手机端的v2rayNG的直连规则末尾添加了一行`port:0-65535,`却没有效果。
请大佬指教一下如何操作？或者有这方面需求的用户一起讨论应该怎么操作来绕开BT流量？

### 环境信息
v2rayNG v1.6.28 (Lib v23, Xray-core v1.5.2)
Android 11

**Comment by Animisml** [comment]
请问有没有节点

**Comment by Gokou-Ruri** [comment]
> 请问有没有节点

？

**Comment by MreDiaos** [comment]
就我使用到现在来说，v2ray ng目前的自定义规则只能设定routing里的domain和IP这两项，至于port这些都是无法修改的（也可能是我没有找到方法修改）

**Comment by Gokou-Ruri** [comment]
> 就我使用到现在来说，v2ray ng目前的自定义规则只能设定routing里的domain和IP这两项，至于port这些都是无法修改的（也可能是我没有找到方法修改）

有没有什么办法能让同一个APP的BT流量不走代理，http境外走代理呢？

**Comment by MreDiaos** [comment]
> > 就我使用到现在来说，v2ray ng目前的自定义规则只能设定routing里的domain和IP这两项，至于port这些都是无法修改的（也可能是我没有找到方法修改）
> 
> 有没有什么办法能让同一个APP的BT流量不走代理，http境外走代理呢？

这个我就不清楚了，我是个小白，只会科学上网，玩不来高难度的

**Comment by Moius** [comment]
你可以在PC上写一份路由配置文件，然后传输给安卓手机。如果是你自己的代理服务器则可以在服务端配置文件内禁用BT类型链接，然后在客户端检测BT链接走freedom直连

**Comment by Gokou-Ruri** [comment]
> 你可以在PC上写一份路由配置文件，然后传输给安卓手机。如果是你自己的代理服务器则可以在服务端配置文件内禁用BT类型链接，然后在客户端检测BT链接走freedom直连

v2rayNG不支持protocol路由，v2rayN才支持，所以配置文件复制过来也没效果。目前不清楚开发者会不会考虑支持protocol。
如果单单只是服务端禁用BT协议，而客户端不支持设定，会导致客户端的BT协议完全无法下载。

**Comment by Moius** [comment]
那我就不太清楚了，对不起

From
ORCHIDCYAN
________________________________

**Comment by Gokou-Ruri** [comment]
> 那我就不太清楚了，对不起 From ORCHIDCYAN
> […](#)

没关系没关系，我提这个issue就是为了集思广益，每个帮忙提供思路的人我都欢迎的，而且关注的人多了也许开发者会考虑把protocol路由纳入开发计划呢。

**Comment by tiandown** [comment]
> > 你可以在PC上写一份路由配置文件，然后传输给安卓手机。如果是你自己的代理服务器则可以在服务端配置文件内禁用BT类型链接，然后在客户端检测BT链接走freedom直连
> 
> v2rayNG不支持protocol路由，v2rayN才支持，所以配置文件复制过来也没效果。目前不清楚开发者会不会考虑支持protocol。 如果单单只是服务端禁用BT协议，而客户端不支持设定，会导致客户端的BT协议完全无法下载。

请问下v2rayNG和v2rayN这两个有啥区别？手机端在google play只有v2rayNG，而且有个问题是无法打开google play和youtube，其他的翻墙网站和app都可以使用，就是不能打开google系列的app，咋回事？

**Comment by ghost** [comment]
> 

我只能说我的 google play和youtube都能打开。 你贴一下v2rayNG的配置，我们看一下。如果有log的话更好

**Comment by Moius** [comment]
手机上的我用的sugarnet 因为这个可以自定义路由规则，v2rayNG现在可以吗？如果不可以我建议你换成sugarnet试试呢？关于Googleplay无法访问有可能是Googleapis.com导致的，但是至于youtube我并不清楚，最好贴一下你的配置给大家看一下。

________________________________
发件人: Andrew Wu ***@***.***>
发送时间: 2022年3月22日星期二 下午3:10
收件人: 2dust/v2rayNG
抄送: despairlight; Comment
主题: Re: [2dust/v2rayNG] 怎样绕开BT(P2P)流量？ (Issue #1328)


你可以在PC上写一份路由配置文件，然后传输给安卓手机。如果是你自己的代理服务器则可以在服务端配置文件内禁用BT类型链接，然后在客户端检测BT链接走freedom直连

v2rayNG不支持protocol路由，v2rayN才支持，所以配置文件复制过来也没效果。目前不清楚开发者会不会考虑支持protocol。 如果单单只是服务端禁用BT协议，而客户端不支持设定，会导致客户端的BT协议完全无法下载。

请问下v2rayNG和v2rayN这两个有啥区别？手机端在google play只有v2rayNG，而且有个问题是无法打开google play和youtube，其他的翻墙网站和app都可以使用，就是不能打开google系列的app，咋回事？

―

**Comment by Gokou-Ruri** [comment]
> 手机上的我用的sugarnet 因为这个可以自定义路由规则，v2rayNG现在可以吗？如果不可以我建议你换成sugarnet试试呢？关于Googleplay无法访问有可能是Googleapis.com导致的，但是至于youtube我并不清楚，最好贴一下你的配置给大家看一下。
SugarNet？SagerNet？

**Comment by Moius** [comment]
sagernet，不好意思，打错了。
________________________________

**Comment by alwaysbetter1314** [comment]
双开个termux不就好了
