### ISSUE TITLE
SOCKS5 proxy port 和 http proxy port 应该做到可以修改

### ISSUE THREAD

**Issue by ted-dev-42** [2dust/v2rayNG#133]
否则如果端口被占用，就无法正常启动： 

> 10-15 14:52:14.628  5607  5607 I GoLog   : new v2ray core
> 10-15 14:52:14.633  5607  5607 I GoLog   : start v2ray core
> 10-15 14:52:14.633  5607  5607 I GoLog   : v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10808 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10808 > listen tcp 127.0.0.1:10808: bind: address already in use
> 10-15 14:52:14.634  5607  5607 D com.v2ray.ang: go.Universe$proxyerror: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10808 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10808 > listen tcp 127.0.0.1:10808: bind: address already in use

此外这两个端口给谁用的？ 我的"allow connections from the LAN" 也没有勾选啊，这个socks代理和http代理是做什么用的？

**Comment by 2dust** [comment]
core需要
