### ISSUE TITLE
读取配置文件有错误

### ISSUE THREAD

**Issue by wxdczd** [2dust/v2rayNG#1332]
版本是v1.6.28
我的配置文件有3个,都是同一个服务器,第一个,第二个都是写得ip地址,第三个写的是域名.每个服务的端口不同.
运行第一个很正常.
运行第三个就出错误,我仔细看了一下日志发现,我运行第三个配置时,日志里面出现了第一个配置的端口号码.(我运行第三个前,清除了日志)
我把第一个配置删除了,第三个就正常了.

我写第三个配置的时候,用的第一配置导出到剪贴板,然后导入剪贴板,改名,改服务器地址.改端口号,这样操作有问题吗?

**Comment by shi4ts** [comment]
购买了一年的使用时间。然后用了不到三个月。客服微信自己注销了。我先问问这个怎么整。

**Comment by shi4ts** [comment]
购买了一年的使用时间。用了三个月就用不了了。客服的微信还注销了。怎么办？
