### ISSUE TITLE
可以支持“始终和VPN保持连接”吗？感谢

### ISSUE THREAD

**Issue by smdx** [2dust/v2rayNG#134]
OPPO的系统杀软件禁后台非常神经作者君可以支持一下可以支持“始终和VPN保持连接”功能吗？感谢

![screenshot_2018-11-03-19-04-57-95](https://user-images.githubusercontent.com/9279217/47951467-2dbc2f80-df9c-11e8-98d3-d0136e288fe9.png)

### 环境信息
OPPO 系统v5.2.1 Android 8.1.0

**Comment by tifish** [comment]
一加5T同求此功能。运行一会就失效了，只能打开app重新连接。

**Comment by pope-L** [comment]
加入白名单了没，允许自启了没

Tinyfish <notifications@github.com> 于 2018年11月8日周四 22:04写道：

**Comment by smdx** [comment]
加入白名单，允许自启了的。

**Comment by pope-L** [comment]
多任务界面有加锁 大概这个意思 的吗
会不会有多个这种后台清理的app，

smdx <notifications@github.com> 于 2018年11月9日周五 18:42写道：

**Comment by smdx** [comment]
没试过在任务界面加锁一会试试，没有安装第三方管理类型软件。

**Comment by tifish** [comment]
一加5的电池选项中有优化列表，已经选择了不优化。另外我安装了黑阈，也加入了白名单。现在的现象是，有时候1天都工作正常，有时候一会就退出了。任务界面加锁是个好主意，我也试试。

**Comment by tifish** [comment]
另外，v2rayNG没有注册启动事件吧？所以每次重启都要手动开启一次。刷机党经常忘记。。。

**Comment by smdx** [comment]
的确在多任务锁定后可以确保后台一直运行
