### ISSUE TITLE
vless+ws+tls+CDN 用安卓就会断开无法连接

### ISSUE THREAD

**Issue by superabbite1** [2dust/v2rayNG#1347]
vless+ws+tls 没用套cdn的情况下PC端和安卓端都是可以正常访问的，没有任何问题，

但是如果套了cdn，PC端可以正常访问没用任何问题，ws+tls+CDN 在安卓端就会断开无法连接（打开软件连接节点可以访问google，但是如果访问youtube就会马上断开连接，连不上提示 io:read/wirte on closed pipe），然后关闭v2rayNg后重新连接节点 又能正常。目前看只有是安卓端连接youtube肯定马上就断开连接，怎么连都连不上，必须关了软件重新打开。

这个问题又人知道说明原因吗

**Comment by Gokou-Ruri** [comment]
我两台手机一台正常，另一台不管哪个节点都是`io:read/wirte on closed pipe`，其中有个节点也是ws+cdn。

**Comment by wing731** [comment]
> 我两台手机一台正常，另一台不管哪个节点都是`io:read/wirte on closed pipe`，其中有个节点也是ws+cdn。

我也是一样
