### ISSUE TITLE
 安卓手机路由设定可以添加GFW列表吗？

### ISSUE THREAD

**Issue by zerozero123** [2dust/v2rayNG#135]
作为一个重度翻墙使用者，每天几乎都会连v2ray,但路由有一点做得不好。怎么说呢，绕过大陆地址，当我使用qq音乐时，流量还是会走v2ray(走境外vps访问),这岂不是增加我被墙的几率吗？所以我希望开发者能够改进这一点
也许你会问为什么不设置分应用代理，相信我，我尝试过，很不好用。

**Comment by pope-L** [comment]
选 geo全家桶呢？
zerozero123 <notifications@github.com> 于 2018年11月5日周一 21:33写道：

**Comment by 2dust** [comment]
相信我,用分应用代理
android就应该用分应用.只有ios不能分应用才会用那么复杂的路由.
另外尝试下0.6.1-beta2,更新了最新的geo
