### ISSUE TITLE
功能意见：允许来自局域网的链接 可不可以顺便显示一下手机的内网ip呢 

### ISSUE THREAD

**Issue by dylanbai8** [2dust/v2rayNG#135]
允许来自局域网的链接 可不可以顺便显示一下 手机的内网ip呢 

### 预期行为
在 允许来自局域网的链接 处显示出 手机连接wifi时的内网ip地址 

### 实际行为
无

### 复现方法
1.无
2.
3.

### 额外信息（可选）
手机内网Ip地址 每次连接wifi都有可能变化 ，本人是用小米手机 每次 手动查询手机的内网ip 并不是那么方便 ，希望能够顺便显示一下 ，个人认为挺实用的 。

**Comment by 2dust** [comment]
建议在自己设置下常用wifi的静态ip

**Comment by dylanbai8** [comment]
好吧，谢谢。
