### ISSUE TITLE
v2rayNG cannot import config problem

### ISSUE THREAD

**Issue by cuynu** [2dust/v2rayNG#1350]
I moved v2rayNG to SD Card with Use SD card as storage option.
When try to add config it's only show Success but config not show up
![Screenshot_20220124-155403](https://user-images.githubusercontent.com/90895715/150752354-0b4c1f82-6b23-4cdc-9c47-f8e530d80ed7.png)

Here is my logcat :
--------- beginning of main
01-24 16:07:01.303 W/com.v2ray.ang(10525): type=1400 audit(0.0:1499): avc: denied { search } for name="files" dev="dm-0" ino=2359365 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c105,c256,c512,c768 tclass=dir permissive=0
01-24 16:07:01.303 W/com.v2ray.ang(10525): type=1400 audit(0.0:1500): avc: denied { search } for name="files" dev="dm-0" ino=2359365 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c105,c256,c512,c768 tclass=dir permissive=0
01-24 16:07:01.303 W/com.v2ray.ang(10525): type=1400 audit(0.0:1501): avc: denied { search } for name="files" dev="dm-0" ino=2359365 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c105,c256,c512,c768 tclass=dir permissive=0

**Comment by cuynu** [comment]
Problem fixed

**Comment by mehdiggggggg** [comment]
Gh

**Comment by sirpasha** [comment]
How did you fix it?
