### ISSUE TITLE
电视上安装后点启动总是闪退

### ISSUE THREAD

**Issue by jefcn** [2dust/v2rayNG#1353]
微鲸电视，安装好后点启动服务，总是闪退，试了好几个版本都如此（pc上安卓模拟器里运行没问题）
请问是什么原因？

**Comment by jefcn** [comment]
这个是跟电视系统有关系么？
点服务重启，可以启动服务，但是点测试报错“io: read/write on closed pipe”

**Comment by inamoto316** [comment]
我的极米电视也是，闪退

**Comment by rulaimc** [comment]
电视的安卓系统是不完整的，要么路由器翻墙，要么你用一台旧手机或者老电脑翻墙，做局域网代理就好了
