### ISSUE TITLE
提一个小建议，Shadowsocks已经不再安全，期待能支持相对安全的ShadowsocksR的节点

### ISSUE THREAD

**Issue by uposink** [2dust/v2rayNG#136]
前面提了个建议，很感谢 现在v2rayNG 对 socks 支持已经算是完美了。
但是Shadowsocks已经不再安全，期待能支持相对安全的ShadowsocksR的节点
虽然我也在用 v2ray的节点 但是现在用ShadowsocksR节点的人还是很多的。

**Comment by 2dust** [comment]
不要讨论r
