### ISSUE TITLE
新版导出ss节点含ip地址，老毛子固件不认节点链接。

### ISSUE THREAD

**Issue by huweitianc** [2dust/v2rayNG#1363]
新版导出ss链接和以前不一样了。以前ip地址用base64编码，现在直接用ip地址加端口，老毛子固件不认节点链接。只好手动输入，好麻烦。举例说明如下:同一个节点。
上一版本:ss://YWVzLTI1Ni1nY206Rm9PaUdsa0FBOXlQRUdQQDE2Ny44OC42MS4xNzU6NzMwNw==#%F0%9F%87%BA%F0%9F%87%B8%E7%BE%8E%E5%9B%BD%28%E7%BB%BF%E5%A4%B4%E5%A4%96%E7%BD%91%E9%9B%86%E5%9B%A2%29%28Public%29。
现在版本:ss://YWVzLTI1Ni1nY206Rm9PaUdsa0FBOXlQRUdQ@167.88.61.175:7307#%F0%9F%87%BA%F0%9F%87%B8%E7%BE%8E%E5%9B%BD%28%E7%BB%BF%E5%A4%B4%E5%A4%96%E7%BD%91%E9%9B%86%E5%9B%A2%29%28Public%29。
打算退回1.52版本。

**Comment by 2dust** [comment]
https://shadowsocks.org/en/wiki/SIP002-URI-Scheme.html
