### ISSUE TITLE
绕过大陆+流量探测net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by llllllllqq** [2dust/v2rayNG#137]
[剪纸堆备份10月 19，周六 08-21-57.txt](https://github.com/2dust/v2rayNG/files/3746029/10.19.08-21-57.txt)
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常访问zhidao.baidu.com（http网站跳转https）

### 实际行为
net::ERR_EMPTY_RESPONSE
（并没有跳转https）

### 复现方法
1.清空dns缓存 清空数据重新配置v2ray
2.仅仅更改绕过大陆和局域网，其它默认，链接
3.via浏览器打开任意没访问过的zhidao页面（http）

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
日志参见附件
```
</details>

### 环境信息
安卓9 miui10
### 额外信息（可选）
https页面没问题，打开本地dns好像也没问题，关了流量探测也没问题，选择仅绕过局域网也没问题。仅在中国移动数据网络下能复现，电信wifi无问题。
补充：仅开绕过大陆+流量探测，不开本地dns，刷新国内网站（如百度）极慢（20k/s），而打开本地dns或关流量探测立即好了。不论wifi还是数据都慢。

**Comment by 948171624** [comment]
补充，发现原因了，是这样操作会阻止http跳转https

**Comment by 2dust** [comment]
暂时解决不了你的问题
