### ISSUE TITLE
在lineageos上不打开调试的气概况下，程序总请求jdwp失败并打印日志

### ISSUE THREAD

**Issue by Momo-ProMax** [2dust/v2rayNG#1375]
### 日志信息
<details>
--------- beginning of main
02-15 19:25:54.827 E/com.v2ray.ang(17273): failed to connect to jdwp control socket: Connection refused
02-15 19:25:56.830 E/com.v2ray.ang(17273): failed to connect to jdwp control socket: Connection refused
02-15 19:25:58.831 E/com.v2ray.ang(17273): failed to connect to jdwp control socket: Connection refused

</details>

### 环境信息
lineageos18.1

**Comment by cuynu** [comment]
Change your configuration. I'm using v2rayNG on LineageOS 18.1 normally

**Comment by Bumblehao** [comment]
> 

我在v2rayNG中打开了本地DNS与虚拟DNS并配置ipv6优先，需要更改什么？

**Comment by Momo-ProMax** [comment]
> Change your configuration. I'm using v2rayNG on LineageOS 18.1 normally

change what

**Comment by rust17** [comment]
关闭日志试试
