### ISSUE TITLE
trojan二维码剪贴板导出后导入失败

### ISSUE THREAD

**Issue by taylorwin** [2dust/v2rayNG#1378]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
通过导出到剪贴板，二维码
可以在正常导入

### 实际行为
导出后导入时提示失败

### 复现方法
1.导出到剪贴板或二维码
2.点添加通过剪贴板或二维码
3.失败

### 日志信息
--------- beginning of main
02-16 23:40:22.869 W/System.err( 9252): java.lang.NullPointerException
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.extension._ExtKt.getIdnHost(_Ext.kt:80)
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:306)
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:684)
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:384)
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:383)
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:375)
02-16 23:40:22.869 W/System.err( 9252): 	at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:216)
02-16 23:40:22.869 W/System.err( 9252): 	at android.app.Activity.onMenuItemSelected(Activity.java:4401)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
02-16 23:40:22.869 W/System.err( 9252): 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
02-16 23:40:22.869 W/System.err( 9252): 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
02-16 23:40:22.869 W/System.err( 9252): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
02-16 23:40:22.869 W/System.err( 9252): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3528)
02-16 23:40:22.869 W/System.err( 9252): 	at android.widget.AbsListView$3.run(AbsListView.java:4691)
02-16 23:40:22.869 W/System.err( 9252): 	at android.os.Handler.handleCallback(Handler.java:938)
02-16 23:40:22.869 W/System.err( 9252): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-16 23:40:22.869 W/System.err( 9252): 	at android.os.Looper.loopOnce(Looper.java:226)
02-16 23:40:22.869 W/System.err( 9252): 	at android.os.Looper.loop(Looper.java:313)
02-16 23:40:22.869 W/System.err( 9252): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
02-16 23:40:22.869 W/System.err( 9252): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 23:40:22.869 W/System.err( 9252): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
02-16 23:40:22.869 W/System.err( 9252): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
02-16 23:40:22.870 I/com.v2ray.ang( 9252): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
02-16 23:40:22.870 I/com.v2ray.ang( 9252): Parse base64 url safe failed java.lang.IllegalArgumen

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
安卓  
1.6.30
### 额外信息（可选）

**原因是密码里包含 “@” 特殊字符。**

**Comment by 2dust** [comment]
请列出导出后的链接

**Comment by taylorwin** [comment]
trojan://xxx@123321@127.0.0.1:8443?security=tls&headerType=none&type=tcp&sni=abc.abc.com#abc1

**Comment by 2dust** [comment]
xxx@123321不能带@
