### ISSUE TITLE
Problem With Mux.Cool (invalid data send by server to client)

### ISSUE THREAD

**Issue by mtnkm** [2dust/v2rayNG#138]
Mux : Enabled
after testing speed with SpeedTest program and closing that program in android ,,,SERVER Still shows sending data to that port for about 15-30 seconds .(16Mbps) . these are invalid data and not shows on program but it shows on server side and my phone data calculator .
WITH NO MUX there is no problem
WITH OFFICIAL Windows software for v2ray there is no problem

this problem cause more data usage .
and in that 15-30 seconds that data is sending ... THE SPEED WILL be very low (line will be full)

sorry for bad english .
thanks

**Comment by mtnkm** [comment]
this problem cause more data usage .
and in that 15-30 seconds that data is sending ... THE SPEED WILL be very low

**Comment by 2dust** [comment]
do not enable mux on mobile devices
