### ISSUE TITLE
控制中心快捷方式只能关闭,点击打开V2rayNG无反应,Clash可以

### ISSUE THREAD

**Issue by gloryandel** [2dust/v2rayNG#1380]
系统版本:MIUI13 安卓12
**以前的安卓11可以使用**
控制中心快捷方式只能关闭,点击打开V2rayNG无反应,Clash可以

### 预期行为
可以在控制中心随𫔭随关

### 实际行为
只能关闭,不能开启,得手动进入app开启
![Screenshot_20220217101620](https://user-images.githubusercontent.com/51497852/154392548-f3e6cdcc-6d8a-4cd3-b7dc-0f8d919e1f3a.jpg)
![Screenshot_20220217102409](https://user-images.githubusercontent.com/51497852/154392559-3ce50105-708f-4447-9fa6-38fb6941ebe8.jpg)

**Comment by yuhan6665** [comment]
应该是电池优化的问题

**Comment by gloryandel** [comment]
> 应该是电池优化的问题

感谢大佬,真的是电池优化问题

**Comment by itheabyss** [comment]
原来是这个原因，困扰了我两个月
