### ISSUE TITLE
10 天前，我的Google Pixel 6 手机的V2ray 突然就再也连接不上了 

### ISSUE THREAD

**Issue by brian12392** [2dust/v2rayNG#1387]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
10 天前，在国内，我的Google Pixel 6 手机的V2ray 突然就再也连接不上了 ，一个月前使用都是正常的，我还和另外一个VPN app 交替使用，现在这个V2RAY 就是连接不上， 连接提示成功，但是实际连接不上，提示连接成功后，手机所有网络都会自动断掉， 但是我在我的老的Pixel 3XL 手机就可以正常使用，还有另外一个Android 10 手机也可以正常使用， 为什么Pixel 6手机不能连接了？？？

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by realIronWang** [comment]
试试系统时间设置为网络时间？？
我的是这样好了

**Comment by brian12392** [comment]
你说的对，现在好了

谢谢！

**Comment by brian12392** [comment]
你好， 
我的Pixel 6手机最近又不能正常使用 V2ray 了，我已经把时间设置成了自动，但是还是不行，过一会就自动断开连接，请问怎么解决呢？

**Comment by brian12392** [comment]
已经确定不是机场服务的问题，因为相同的节点服务在我的另外一个安卓设备上和其他设备上都是正常使用的，

**Comment by shenzongli** [comment]
> 
如果早能看到你的回复就好了，我一开始还能连上，就是后来设置了一下系统时间，结果怎么弄也连不上了，还找不到问题所在，升级了系统都没用，现在一下就解决了，真的感谢你！

**Comment by shenzongli** [comment]
> 试试系统时间设置为网络时间？？ 我的是这样好了

没有你的话我怕是这辈子都解决不了了，，，

**Comment by brian12392** [comment]
但是最近发现不是很稳定，时不时自动断开连接，频繁需要手动进行重新连接
