### ISSUE TITLE
Auto Subscription update

### ISSUE THREAD

**Issue by rt58-a** [2dust/v2rayNG#1392]
Please add the server as a folder. And add automatic mode to update the subscription.
Thanks for your good app

**Comment by rt58-a** [comment]
![IMG_20220301_150224_088](https://user-images.githubusercontent.com/99919138/156161870-ab7a2c7f-d978-471a-95c7-dc1b0035c19f.jpg)

**Comment by rt58-a** [comment]
![20220301_150425](https://user-images.githubusercontent.com/99919138/156162128-903d9762-516e-4366-af93-33e0f23880c6.jpg)

**Comment by cuynu** [comment]
It doesn't look like v2rayNG. Can you give me the apk file?
