### ISSUE TITLE
系统状态栏显示的网速异常

### ISSUE THREAD

**Issue by lostever** [2dust/v2rayNG#1395]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
在系统设置中打开状态栏显示网速后，开启v2rayNG系统状态栏能够显示正常网速

### 实际行为
开启软件代理后系统状态栏显示的网速比v2rayng显示的网速高数倍，关闭代理后网速显示恢复正常。

### 复现方法
1.![Screenshot_20220301-003127576.jpg](https://user-images.githubusercontent.com/44220239/156021107-788e4faa-8970-4165-a0d3-a89b10d8451f.jpg)
2.![Screenshot_20220301-003133155.jpg](https://user-images.githubusercontent.com/44220239/156021115-c84709ba-915a-4f14-9d69-a32c2fad311d.jpg)
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
--------- beginning of main
--------- beginning of system
03-01 00:38:26.906 31974 32005 I GoLog   : tcp:127.0.0.1:41368 accepted tcp:91.108.56.185:443 [proxy]
03-01 00:38:26.959 31974 31995 I GoLog   : Using Prepared: 20.205.32.206
03-01 00:38:27.571 31974 32005 I GoLog   : tcp:127.0.0.1:41374 accepted tcp:91.108.56.185:443 [proxy]
03-01 00:38:27.630 31974 31995 I GoLog   : Using Prepared: 20.205.32.206
</details>

### 环境信息
![Screenshot_20220301-004431781.jpg](https://user-images.githubusercontent.com/44220239/156023000-d428206d-28f5-434b-a425-c88eeeb82d63.jpg)
![Screenshot_20220301-004433984.jpg](https://user-images.githubusercontent.com/44220239/156023003-e332b643-c6d1-4b84-9fbb-048248d54518.jpg)

**Comment by lostever** [comment]
实测差不多是实际网速的4倍

**Comment by PositionZer0** [comment]
同样的问题，系统为 Android 12

**Comment by super5xy** [comment]
same problem.

**Comment by selcarpa** [comment]
#624
