### ISSUE TITLE
grpc path 包含!时无法连接到服务器

### ISSUE THREAD

**Issue by onlyJinx** [2dust/v2rayNG#1397]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
grcp path包含`!`时v2rayNG发送给服务器的是`%21`导致nginx无法转发数据
### 复现方法
1.grcp path包含`!`时即可复现

### 日志信息
下方nginx日志上半部分为v2rayNG产生的(无法连接)，下方为SagerNet产生的(正常使用)。
以前同样的问题发聩给clash后修复了，可以参考https://github.com/Dreamacro/clash/commit/847f41952e97996bc5f4358a2df2ec8a1e4a8739 
```
xxx - - [04/Mar/2022:02:25:09 -0500] "POST /KdMAFS8mJvoS_ne%21N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:25:12 -0500] "POST /KdMAFS8mJvoS_ne%21N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:25:12 -0500] "POST /KdMAFS8mJvoS_ne%21N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:25:16 -0500] "POST /KdMAFS8mJvoS_ne%21N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:25:16 -0500] "POST /KdMAFS8mJvoS_ne%21N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:26:19 -0500] "POST /KdMAFS8mJvoS_ne!N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:27:40 -0500] "POST /KdMAFS8mJvoS_ne!N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 5373 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:27:44 -0500] "POST /KdMAFS8mJvoS_ne!N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 0 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:27:51 -0500] "POST /KdMAFS8mJvoS_ne!N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 4164 "-" "grpc-go/1.44.1-dev"
xxx - - [04/Mar/2022:02:27:53 -0500] "POST /KdMAFS8mJvoS_ne!N7P47aUXHnO4ZXdCxA/Tun HTTP/2.0" 200 4176 "-" "grpc-go/1.44.1-dev"
```

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
在配置页你看到的是 `！` 还是 `%21` ？
如果是`%21`需要一个分享链接的例子

**Comment by onlyJinx** [comment]
我服务器配置文件里的是`!`，V2rayNG里填的也是`!` ，`%21`是v2rayNG连接服务器时我在服务器的nginx log里看到的。

**Comment by yuhan6665** [comment]
那我知道了 是由于 core 的这个 https://github.com/XTLS/Xray-core/commit/3dc9fba20d9274d004652330e3dce72401aca087
加这个逻辑是因为有人用其他非法的字符做 servicename
在标准里面是说了建议不要用特殊字符的 https://github.com/XTLS/Xray-core/issues/91
如果你仍然要用叹号的话 可能只能在服务端兼容两种配置了。。

**Comment by onlyJinx** [comment]
好的，因为这个path是我用openssl随机生成的25个字符，如果不是bug的话那我就替换掉感叹号就可以了，多谢
