### ISSUE TITLE
在小米手机上启动服务失败，还会闪退

### ISSUE THREAD

**Issue by Michaelxia6** [2dust/v2rayNG#1398]
最新版64位
![691B0372CDEBF7C44C361A85BC21EA24](https://user-images.githubusercontent.com/86915639/156880963-738aa709-8cab-43d8-a7af-f52508135340.jpg)
![A4FA636B0F1C868CD29F604877131E50](https://user-images.githubusercontent.com/86915639/156880966-dc8536be-6667-44a5-ae29-9b83ef728df8.jpg)

**Comment by yuhan6665** [comment]
看一下是不是有电池优化导致后台服务起不来

**Comment by matelslug** [comment]
我的也是，系统没有升级啊，一直提示启动服务失败，请高人指点一下
