### ISSUE TITLE
安卓客户端经常出现SSL错误了

### ISSUE THREAD

**Issue by chengeast** [2dust/v2rayNG#140]
自从升级了新版，安卓手机app经常出现SSL错误，导致无法科学上网。不改任何设置，过几十分钟后又可以上了。感谢大神的辛苦付出！！希望v2ray越来越好！！
![Screenshot_20191013_014440_com v2ray ang](https://user-images.githubusercontent.com/48310197/67148452-55ea8e80-f2d2-11e9-99ff-79361dee4ff8.jpg)
![Screenshot_20191013_012224_com v2ray ang](https://user-images.githubusercontent.com/48310197/67148454-55ea8e80-f2d2-11e9-9247-574459189c0e.jpg)

**Comment by chengeast** [comment]
难道没有人和我一样吗？那我卸载重装试试。

**Comment by jsczzp** [comment]
我的经常自动退出，毫无规律。你这个问题我也经常出现，PC上v2rayN测试服务器延迟都正常，但是手机上同一个服务器就经常测不出延迟

**Comment by Undefined-User** [comment]
一样的问题，基本上每次开启都会出现，出现这个错误的同时各种软件也都连不上网，旧版本似乎只是掉后台，还没到手动开启都不能用的程度。用v2rayNG后根本不敢长时间挂在后台用（必断网），以前ss都是24小时挂后台的

**Comment by chengeast** [comment]
那我倒是不会自动退出，只是关闭的时候那个钥匙的图标老是消不掉，消不掉还是翻不了墙，要关闭WIFI，然后钥匙才会消掉。

**Comment by Pinocchio2018** [comment]
我也是这个问题

**Comment by sum198888** [comment]
我目前也有这个问题，同时还有okhttp发送接收错误

**Comment by 2dust** [comment]
请升级到1.1.7测试反馈下
这个版本修改了这个功能

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.1.9
这个版本不行的话暂时是没有办法解决了
