### ISSUE TITLE
为何绕过局域网和大陆模式代理网址非常慢？

### ISSUE THREAD

**Issue by humorwang** [2dust/v2rayNG#1404]
v2rayNG 在全局代理模式下，访问各个网址google，youtube等都速度正常。而一旦切为绕过局域网和大陆模式，google，youtube等需要代理的网址访问就奇慢无比。尝试启用本地dns，修改dns等都未见效果，都是非常慢。与全局模式差异非常大。

**Comment by chika0801** [comment]
建议不要用全局，分应用代理才是正确的使用方式。

**Comment by cache444** [comment]
预定义规则设置全局，自定义规则设置绕过geosite:cn,和geoip:cn,即可，再勾选启用本地dns，远程dns设为doh地址。

**Comment by 582583241** [comment]
就是因为这个所以我转用了小猫咪。
