### ISSUE TITLE
部分手机googlePlay商店无法下载应用一直转圈圈等待中的个人解决方案

### ISSUE THREAD

**Issue by rulaimc** [2dust/v2rayNG#1405]
检查日志发现两个疑似谷歌的域名没有走代理

![image](https://user-images.githubusercontent.com/40266264/157693064-42a1577a-5223-418a-b3fc-6af35a449538.png)

于是便尝试将这两个域名加入路由强制走代理，结果就可以正常下载了。
我猜测是国内部分手机google play商店做了些手脚，我的机型是 iQOO Neo5

**Comment by rulaimc** [comment]
connectivitycheck.gstatic.com
services.googleapis.cn

**Comment by rucswax** [comment]
> connectivitycheck.gstatic.com services.googleapis.cn

这个有效果，请问能否说一下，截图的日志是如何获取的吗？

**Comment by CussiusKon** [comment]
已经加入了，还是不行。ng的play下载问题时好时坏，搞不明白到底是哪里问题
