### ISSUE TITLE
vless服务器必须开启allowInsecure,否则连接失败

### ISSUE THREAD

**Issue by wjz2001** [2dust/v2rayNG#1406]
### 描述此错误

如标题所说，测试配置会显示io: read/write on closed pipe。
我的证书是用Let'sEncrypt生成的，没有任何问题。
电脑上用v2rayN关闭allowInsecure依然可以正常连接。
即便在xtlsSettings中的serverName里填写上我的域名也没有用，而且手动输入vless根本没有地方可以填这个配置。

### 如何复现该错误

步骤 1:选择手动输入vless
步骤 2: allowInsecure选择true

### 设备信息

- 机型:一加2
- 系统类型:氢os
- Android 版本:6.0

### 应用信息

- 版本:1.6.30
- 安装包文件名:v2rayNG_1.6.30.apk
- 应用来源:github

### 配置文件
这是用分享功能导出的配置。
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8",
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ],
        "port": 53
      }
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 50800,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 50801,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    },
    {
      "listen": "127.0.0.1",
      "port": 10853,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "8.8.8.8",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 443,
            "users": [
              {
                "encryption": "none",
                "flow": "xtls-rprx-splice",
                "id": "",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "xtlsSettings": {
          "allowInsecure": false,
          "serverName": ""
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "AsIs",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "8.8.8.8"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },   
   {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

### 日志

--------- beginning of main
03-12 10:15:36.265 I/GoLog   (12675): Using Prepared: 23.105.222.59
03-12 10:15:36.471 D/com.v2ray.ang(12675): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe

**Comment by b6g9** [comment]
Same problem.

Device name: Pixel 4a
Android version: 12
v2rayNG Version: [1.7.2]

**Comment by zhukm** [comment]
trojan节点也有这问题。clash正常连接，导入v2Ray不能连接，编辑，把跳过证书验证（allowance）选项false改成true，就正常了。
