### ISSUE TITLE
[Feature] Fix NAT type for online games

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#141]
## Motivation

Most games on some game consoles use P2P UDP protocol to enable online multiplayer, which require a good NAT type of your network. Is it possible to improve NAT type with V2rayNG (so I can share it to my game console without a router)?

Links:

- [Netch](https://github.com/NetchX/Netch): Game accelerator. Support V2Ray protocol. UDP NAT FullCone.
- A relevant issue in [VPNHotspot](https://github.com/Mygod/VPNHotspot/issues/130).

**Comment by 2dust** [comment]
No plan
