### ISSUE TITLE
电脑连接局域网共享无法连接外网,手机正常

### ISSUE THREAD

**Issue by Srtvk** [2dust/v2rayNG#1413]
### 预期行为
电脑可以连接外网
### 实际行为
无法连接外网,内网正常
![image](https://user-images.githubusercontent.com/44525831/158941545-b0badf78-6913-4767-9a6a-5f064a8afe02.png)

![IMG_20220318_115639](https://user-images.githubusercontent.com/44525831/158941511-7aa0e7e3-4aee-4c76-a75b-ed856f64554e.jpg)

### 复现方法
1.打开局域网共享(Nokia x6 已root)
![Screenshot_2022-03-18-11-49-08](https://user-images.githubusercontent.com/44525831/158935586-e273f5d7-ca72-4296-9543-8a6977a7d9f6.png)
连接节点
![Screenshot_2022-03-18-11-49-20](https://user-images.githubusercontent.com/44525831/158935611-989a29ee-c4be-46f1-84c7-e827d724b2e0.png)
2.打开电脑并配置代理设置(chrome os flex 端)
![IMG_20220318_115233](https://user-images.githubusercontent.com/44525831/158935819-babec22f-47ef-40d6-b42a-f4c94b0d2433.jpg)
Windows11 端
![image](https://user-images.githubusercontent.com/44525831/158935971-4cd22791-fffd-4074-be11-949076e88d43.png)
安卓端(Nubia z17s)
![Screenshot_2022-03-18-11-50-08-877](https://user-images.githubusercontent.com/44525831/158939958-7b39cd87-005f-41cd-a26a-61743269593f.png)

3.配置好打开网页进行测试网络
Windows11 端(连接不可用)
![image](https://user-images.githubusercontent.com/44525831/158939650-89783ee8-5895-4fe4-b621-1ddaa4a22b01.png)
Chrome OS flex
![IMG_20220318_115639](https://user-images.githubusercontent.com/44525831/158939796-1ac1155b-7680-4116-9a07-9f2f09155df1.jpg)
安卓(Nubia z17s)
![Screenshot_2022-03-18-11-50-14-460](https://user-images.githubusercontent.com/44525831/158939927-9d62058d-521c-4a62-85af-4d47c3297ab6.png)

### 环境信息
手机两部:Nokia x6(已root并开启局域网共享)
               Nubia z17s
操作系统:Windows 11 专业版 版本号:22000.556
              Chrome OS flex

配置:Lenovo yoga c740-15
CPU:Intel i5-8365
内存:8g 镁光
网卡:Intel(R) Wireless-AC 9462

**Comment by ech0ooo** [comment]
您好，请问这个问题您解决了吗

**Comment by Srtvk** [comment]
没有,已经不用那个系统了
________________________________
发件人: ech0ooo ***@***.***>
发送时间: 2022年4月7日 11:02
收件人: 2dust/v2rayNG ***@***.***>
抄送: Srtvk ***@***.***>; Author ***@***.***>
主题: Re: [2dust/v2rayNG] 电脑连接局域网共享无法连接外网,手机正常 (Issue #1413)


您好，请问这个问题您解决了吗

―

**Comment by EarunWu** [comment]
我switch也连不上

**Comment by xuezhanpingrang** [comment]
我也连接不了，手机可正常vpn，但是电脑无法连接到代理服务器，电脑版本是win11的23h2版本22631.3296，换另一个win11的笔记本电脑却可以。

**Comment by Srtvk** [comment]
> 我也连接不了，手机可正常vpn，但是电脑无法连接到代理服务器，电脑版本是win11的23h2版本22631.3296，换另一个win11的笔记本电脑却可以。

换clash用了,好用太多.虽然最近删库了,但还是比v2好用太多.手机用suf冲浪板
