### ISSUE TITLE
求支持gfwlist

### ISSUE THREAD

**Issue by diyici18sui** [2dust/v2rayNG#142]
跪求，如有不妥请关闭问题。

**Comment by 2dust** [comment]
core明确表示这个不好,所以请用分应用+自定义路由

关注下
https://github.com/v2ray/domain-list-community

**Comment by diyici18sui** [comment]
> core明确表示这个不好,所以请用分应用+自定义路由
> 
> 关注下
> https://github.com/v2ray/domain-list-community

非常感谢
