### ISSUE TITLE
能做一个自动更新订阅的功能吗

### ISSUE THREAD

**Issue by ARROWBOW** [2dust/v2rayNG#1424]
功能类似于 clash上面的自动更新 希望能加入这个功能  希望自动更新之后默认启动的还是之前选中的节点

**Comment by huochequan** [comment]
Windows端很需要呢

**Comment by 2dust** [comment]
v2rayN已有
v2rayNG不增加是因为这个功能浪费电池

**Comment by kia678** [comment]
> v2rayN已有 v2rayNG不增加是因为这个功能浪费电池

自动更新订阅可以考虑让用户自己设置更新间隔，默认为每24小时自动更新一次订阅，对电池的消耗应该很小

**Comment by leoxxx** [comment]
加个自定义时间就不会浪费电了。

**Comment by small-ora** [comment]
同求，更新频率不高的话就不会浪费电池了。

**Comment by huochequan** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    这个功能已经有了。
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月23日 17:27
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [2dust/v2rayNG] 能做一个自动更新订阅的功能吗 (Issue #1424)
        
      
    
  
  

同求，更新频率不高的话就不会浪费电池了。

**Comment by small-ora** [comment]
> 
> 
>     
> 
> 
> 
>     font{
>         line-height: 1.6;
>     }
>     ul,ol{
>         padding-left: 20px;
>         list-style-position: inside;
>     }
> 
> 
>     
>     这个功能已经有了。
>  
> 
>   
>     ---- 回复的原邮件 ----
>   
>   
>     
>       
>         
>          发件人 
>         
>         
>             ***@***.***>
>             
>         
>       
>       
>         
>          发送日期 
>         
>         
>         2022年11月23日 17:27
>         
>       
>       
>         
>          收件人 
>         
>         
>          
>           
>             ***@***.***>
>             
>           
>         
>       
>       
>         
>          抄送人 
>         
>         
>           
>             ***@***.***>
>             ,
>           
>           
>             ***@***.***>
>             
>           
>         
>       
>       
>         
>          主题 
>         
>         
>               Re: [2dust/v2rayNG] 能做一个自动更新订阅的功能吗 (Issue #1424)
>         
>       
>     
>   
>   
> 
> 同求，更新频率不高的话就不会浪费电池了。
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

安卓端好像还没有
