### ISSUE TITLE
三星s10 googleplay问题

### ISSUE THREAD

**Issue by meymself** [2dust/v2rayNG#143]
googleplay 下载 更新app 有时正常有时不正常

### 环境信息
s10e  oneui1.1 android9 patchlevel2019.9.1

同网络环境同配置1.1.5华为emui9 一加android9 小米ui10无问题
同网络环境ios windows无问题
同配置kitsunebi似乎没问题
似乎1.1.3以后出现

**Comment by meymself** [comment]
似乎不仅是谷歌play 谷歌全家桶都有刚开始链接的fail 刷新几次才正常 测速也是前几次connection closed by peer 后面正常

**Comment by meymself** [comment]
时间问题

**Comment by DayDayYiDay** [comment]
> 时间问题

请问是怎么解决的
