### ISSUE TITLE
升级到1.7.3之后，自建的节点连接不上了，升级之前能用

### ISSUE THREAD

**Issue by danger0001** [2dust/v2rayNG#1431]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ldgwfyf** [comment]
我的也是这样,PC没问题,手机1.6.23时也没问题,但升级到1.7.3就连接不上了

经过多次的安装卸载后发现,先清除旧数据再卸载 然后安装新版就正常了

**Comment by c55kai** [comment]
我也是
