### ISSUE TITLE
能否支持自定义host

### ISSUE THREAD

**Issue by ZhangCharlie** [2dust/v2rayNG#1432]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
支持自定义host设置
"domain:xxx.com": "xxx.xxx.xxx.xxx",
...,
...,

### 实际行为
"dns": {
     "hosts": {
       "domain:xxx.com": "xxx.xxx.xxx.xxx",
       ...,
       ...
     }

**Comment by JarmoHu** [comment]
同求，电脑端就有这个功能

**Comment by sbusersb** [comment]
经测试，host功能在pc客户端可以正常使用。在安卓客户端连相关debug都没有。导入客户端上的完整配置文件也不行。 "hosts": {"domain.com": "111.111.111.111",略。

请增加下hosts功能吧，本身安卓手机不root就没有hosts功能，只能通过挂代理的方法

**Comment by sbusersb** [comment]
而且如果服务器上面配置了自定义hosts，客户端不配置，电脑端也能相应自定义解析。但是安卓端不行
