### ISSUE TITLE
[feature request] 为订阅支持authentication 

### ISSUE THREAD

**Issue by Shikopat** [2dust/v2rayNG#1434]
希望支持订阅authentication，url 形态如下：

https://user:pass@raw.githubusercontent.com/<user>/<repo>/<branch>/xxx.txt
尝试通过 github private repo 托管订阅文件，测试发现不能通过如下两种类型的链接获取配置，crul 可以正常获取配置文件。

https://<access_token>@raw.githubusercontent.com/<user>/<repo>/<branch>/xxx.txt
https://<user>:<access_token>@raw.githubusercontent.com/<user>/<repo>/<branch>/xxx.txt

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/blob/e9b1052ef78a71506d6b98f9099980b45e0ac15c/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/Utils.kt#L472

代码中已有此功能
