### ISSUE TITLE
希望能增加订阅功能分组

### ISSUE THREAD

**Issue by lxtx528** [2dust/v2rayNG#1435]
希望大佬能新增订阅分组功能，订阅多了节点也多很难管理，如果有分组功能管理起来更方便，不用的订阅折叠起来。

**Comment by qv88** [comment]
没人啊？软件开发者对自己的软件也不上心吗？

**Comment by Code-Dramatist** [comment]
可能有更好的方案出来了，作者也就对这个放松了，忙自己的事情去了。

**Comment by liqwnt** [comment]
电脑上用的 v2rayN 已经可以分组了，这个手机上用的，也快了吧，感谢

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.7

**Comment by lxtx528** [comment]
收到，非常感谢，使用中的问题已反馈到了gethub

2dust ***@***.***> 于 2022年5月6日周五 15:02写道：
