### ISSUE TITLE
请求增加一个自动更新订阅功能

### ISSUE THREAD

**Issue by lst-git** [2dust/v2rayNG#144]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

预期行为

最近SS经常被封了，订阅经常更新 但每次都是手动更新订阅  测试ping 
想请求增加一个可以每次启App动自动更新订阅 自动检测Ping测试（显示） 开关功能 需要的打开 不需要此功能的可以关闭 谢谢

**Comment by 2dust** [comment]
不接受需求
另外自动是不合适的
