### ISSUE TITLE
安卓手机开v2rayNG,Chrome可以打开Youtube网站，YouTube客户端刷不出内容，换成SSR就可以

### ISSUE THREAD

**Issue by leonsodey** [2dust/v2rayNG#144]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

安卓手机开v2rayNG,Chrome可以打开Youtube网站，YouTube客户端刷不出内容。换成连接同一个VPS上的SSR，网页和客户端都能打开。

这是为什么？有解决办法吗？

**Comment by leonsodey** [comment]
> 路由问题，选全局试试，不要用分代理

谢谢，这个方法可以了，那希望作者，能对这一块加以优化。

**Comment by kfen** [comment]
我也是这样，我以为只有我一个人有这问题~  呼呼~
