### ISSUE TITLE
Android TV上安装了此app，点测试真链接延迟全是-1ms，而实际连接同一个路由的手机上却都可以使用。

### ISSUE THREAD

**Issue by Nicolas-One** [2dust/v2rayNG#1440]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
每个节点都是可以使用的。

### 实际行为
没有一个节点可以使用，之前还好好的，某次安装了新版本后就不能使用了，即使卸载退回老版本也不行。

### 复现方法
1.直接测试真链接就能复现，每次都会这样，之前重启偶尔还能可用下，现在是完全不能使用了。

### 日志信息
<details>
日志信息无法获取，因为没有线能连接安卓电视。

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android 9

### 额外信息（可选）
刚才去开机试了下又可以了。。。之前一周一直不行，不知道为啥，尝试了卸载，重装，路由器刷新的OpenWrt都不行，手机却没这个问题，所以肯定非自己的vps问题，也非路由器问题，而且连接wifi都是可以正常上网看电视的，希望大佬能检查下看看是什么情况导致的。

**Comment by xsm1834** [comment]
我是一直—1ms，重装什么都试过了，还是不行，会不会是地址出问题了？

**Comment by Nicolas-One** [comment]
> 我是一直—1ms，重装什么都试过了，还是不行，会不会是地址出问题了？

我最近也是一直-1ms。。。。怎么搞都不行，已经放弃了。

**Comment by Nicolas-One** [comment]
> 我是一直—1ms，重装什么都试过了，还是不行，会不会是地址出问题了？

跟地址没关系，我相同的节点在手机上一直都可以用，电脑上也是，电视上怎么都不行。

**Comment by xsm1834** [comment]
我是手机不行，昨天中午还可以的，晚上就开始出问题了。

**Comment by Nicolas-One** [comment]
> 我是手机不行，昨天中午还可以的，晚上就开始出问题了。

那有可能是你节点的问题咯，你先检查下不用wifi和用wifi是不是都不行，如果网络确保没问题情况下，大概率就是节点的问题了。

**Comment by xsm1834** [comment]
确实用wifi和不用wifi都不行，不过节点这个问题要怎么处理？因为我不是经常用的。

**Comment by Nicolas-One** [comment]
> 确实用wifi和不用wifi都不行，不过节点这个问题要怎么处理？因为我不是经常用的。

你问别人要个现在可用的试试，如果可以用就是你节点问题，你要是自建的就自己去服务器上修复，如果用的别人分享的。。。那估计就是失效了。。。重新找新的吧。

**Comment by xsm1834** [comment]
好的好的
