### ISSUE TITLE
MIUI13控制中心无法启动v2rayng

### ISSUE THREAD

**Issue by Sweetestcc** [2dust/v2rayNG#1441]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
miui13之前可以直接通过控制中心快捷键启动

### 实际行为
点击快捷键没有任何反应，但是可以通过快捷键停止连接

### 复现方法
1.miui13版本

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
怀疑是升级为安卓12版本的原因

**Comment by Sweetestcc** [comment]
> 在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
> 
> ### 预期行为
> miui13之前可以直接通过控制中心快捷键启动
> 
> ### 实际行为
> 点击快捷键没有任何反应，但是可以通过快捷键停止连接
> 
> ### 复现方法
> 1.miui13版本
> 
> ### 日志信息
> ### 环境信息
> ### 额外信息（可选）
> 怀疑是升级为安卓12版本的原因

**Comment by gxres042** [comment]
如果是 MIUI，看一下省电策略是否为“无限制”
