### ISSUE TITLE
一个小bug，若使用v2rayNG内置geo文件会导致代理无法启动

### ISSUE THREAD

**Issue by watermeloncq** [2dust/v2rayNG#1445]
如题，在刚安装v2rayNG后便设置自定义规则时，若规则中使用了软件内置的geo文件便会导致代理服务无法启动。

解决办法是安装完v2rayNG后先不要设定自定义规则，先在软件中更新下geoip和geosite文件，然后再设定规则。

很多人使用v2rayNG无法启动服务可能就是这个原因吧，可以在下个版本中改进下

**Comment by 2dust** [comment]
可能是您的规则里面有些内容是原生不支持的
下载了最新的geo文件后就支持了
