### ISSUE TITLE
华为手机系统任务栏vpn图标显示异常

### ISSUE THREAD

**Issue by tltv1212** [2dust/v2rayNG#1449]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
系统vpn（钥匙）图标应正常显示在任务栏，断开时不显示
### 实际行为
描述实际发生了什么
vpn图标一直显示在任务栏或一直不显示在任务栏
### 复现方法
1.添加vpn配置
2.应用分应用代理
3.连接vpn
4.断开vpn
5.查看任务栏图标是否正常
### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
手机型号：华为Nova5Pro
系统版本：HarmonyOS 2.0.0.230（C00E230R1P6）
应用版本：v1.73( Lib v23, Xray-core v1.5.4)
### 额外信息（可选）
故障概率：100%
![Screenshot_20220222_220333_com android settings](https://user-images.githubusercontent.com/103621036/163311963-76298d67-3fb1-41e4-a29a-ab3e3325af46.jpg)

**Comment by 2dust** [comment]
此问题无解
