### ISSUE TITLE
安卓10系统 DNS似乎修改了不起作用

### ISSUE THREAD

**Issue by mariokart1992** [2dust/v2rayNG#145]
本地及远程DNS均设置为1.1.1.1, 在1.1.1.1/help上显示没有使用这个DNS

使用手机为一加7pro 氧系统
是不是和安卓10的兼容还不是那么匹配？

**Comment by cutelua** [comment]
客户端使用的DNS地址主要是为了给路由分发功能使用，实际访问地址的DNS解析过程在服务器端。

**Comment by mariokart1992** [comment]
感谢解答
