### ISSUE TITLE
隔壁AnXray分应用代理可通过uidList在路由中配置应用流量是否走代理

### ISSUE THREAD

**Issue by yezige** [2dust/v2rayNG#1451]
本人使用的是自定义配置文件，所以也求一个v2rayNG在路由中定位某应用流量的方法

下图为AnXray路由中指定应用的配置结果，当选择微信走代理时，则出现下图路由部分配置
![image](https://user-images.githubusercontent.com/11436166/163528632-1c49bdd0-4868-4a3a-9905-13c91762af96.png)

**Comment by yuhan6665** [comment]
Only sagernet support this at the moment

**Comment by yezige** [comment]
后期会有支持的可能吗？比如在分应用代理那里显示一下每个应用的uid，这样就可以自定义配置时使用了

**Comment by yuhan6665** [comment]
这个功能比较复杂 目前无计划

**Comment by yezige** [comment]
收到感谢
