### ISSUE TITLE
v2rayNG 1.7.3 crash when add custom config from locally

### ISSUE THREAD

**Issue by cuynu** [2dust/v2rayNG#1452]
v2rayNG crash when add custom config from locally on Android 9, please fix it

Here is the log :
--------- beginning of system
--------- beginning of crash
04-16 05:50:32.023 E/AndroidRuntime( 6855): FATAL EXCEPTION: main
04-16 05:50:32.023 E/AndroidRuntime( 6855): Process: com.v2ray.ang, PID: 6855
04-16 05:50:32.023 E/AndroidRuntime( 6855): java.lang.IllegalStateException: FragmentManager is already executing transactions
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2000)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:818)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:51)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.tbruyelle.rxpermissions.RxPermissions.<init>(RxPermissions.java:38)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.v2ray.ang.ui.MainActivity.readContentFromUri(MainActivity.kt:538)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.v2ray.ang.ui.MainActivity.chooseFileForCustomConfig$lambda-13(MainActivity.kt:530)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$kC5rmdOtWJBi-hmucWYIWt8_hm4(Unknown Source:0)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda11.onActivityResult(Unknown Source:4)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.Fragment.performStart(Fragment.java:2548)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.FragmentController.dispatchStart(FragmentController.java:193)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.Activity.performStart(Activity.java:7175)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.os.Looper.loop(Looper.java:193)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
04-16 05:50:32.023 E/AndroidRuntime( 6855): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
--------- beginning of main
04-16 05:50:39.405 D/AndroidRuntime( 6898): Shutting down VM
04-16 05:50:39.406 E/AndroidRuntime( 6898): FATAL EXCEPTION: main
04-16 05:50:39.406 E/AndroidRuntime( 6898): Process: com.v2ray.ang, PID: 6898
04-16 05:50:39.406 E/AndroidRuntime( 6898): java.lang.IllegalStateException: FragmentManager is already executing transactions
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2000)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:818)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:51)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.tbruyelle.rxpermissions.RxPermissions.<init>(RxPermissions.java:38)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.v2ray.ang.ui.MainActivity.readContentFromUri(MainActivity.kt:538)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.v2ray.ang.ui.MainActivity.chooseFileForCustomConfig$lambda-13(MainActivity.kt:530)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$kC5rmdOtWJBi-hmucWYIWt8_hm4(Unknown Source:0)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda11.onActivityResult(Unknown Source:4)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.Fragment.performStart(Fragment.java:2548)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.FragmentController.dispatchStart(FragmentController.java:193)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.Activity.performStart(Activity.java:7175)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.os.Looper.loop(Looper.java:193)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
04-16 05:50:39.406 E/AndroidRuntime( 6898): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-16 05:51:24.274 W/com.v2ray.ang( 7404): Unexpected CPU variant for X86 using defaults: x86_64
04-16 05:51:24.315 I/com.v2ray.ang( 7404): Waiting for a blocking GC AddRemoveAppImageSpace
04-16 05:51:24.328 I/com.v2ray.ang( 7404): WaitForGcToComplete blocked AddRemoveAppImageSpace on HeapTrim for 13.016ms
04-16 05:51:24.457 I/com.v2ray.ang( 7404): type=1400 audit(0.0:1619): avc: denied { map } for path="/dev/event-log-tags" dev="tmpfs" ino=8919 scontext=u:r:untrusted_app:s0:c78,c256,c512,c768 tcontext=u:object_r:runtime_event_log_tags_file:s0 tclass=file permissive=1
04-16 05:51:24.514 E/GoLog   ( 7404): Failed to create /data/.cache for shader cache (Permission denied)---disabling.
04-16 05:51:42.439 D/AndroidRuntime( 7404): Shutting down VM
04-16 05:51:42.439 E/AndroidRuntime( 7404): FATAL EXCEPTION: main
04-16 05:51:42.439 E/AndroidRuntime( 7404): Process: com.v2ray.ang, PID: 7404
04-16 05:51:42.439 E/AndroidRuntime( 7404): java.lang.IllegalStateException: FragmentManager is already executing transactions
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2000)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:818)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:51)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.tbruyelle.rxpermissions.RxPermissions.<init>(RxPermissions.java:38)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.v2ray.ang.ui.MainActivity.readContentFromUri(MainActivity.kt:538)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.v2ray.ang.ui.MainActivity.chooseFileForCustomConfig$lambda-13(MainActivity.kt:530)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$kC5rmdOtWJBi-hmucWYIWt8_hm4(Unknown Source:0)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda11.onActivityResult(Unknown Source:4)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.Fragment.performStart(Fragment.java:2548)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.FragmentController.dispatchStart(FragmentController.java:193)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.Activity.performStart(Activity.java:7175)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.os.Looper.loop(Looper.java:193)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
04-16 05:51:42.439 E/AndroidRuntime( 7404): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-16 05:51:43.578 W/com.v2ray.ang( 7606): Unexpected CPU variant for X86 using defaults: x86_64
04-16 05:51:43.744 E/GoLog   ( 7606): Failed to create /data/.cache for shader cache (Permission denied)---disabling.
04-16 05:51:50.007 D/AndroidRuntime( 7606): Shutting down VM
04-16 05:51:50.007 E/AndroidRuntime( 7606): FATAL EXCEPTION: main
04-16 05:51:50.007 E/AndroidRuntime( 7606): Process: com.v2ray.ang, PID: 7606
04-16 05:51:50.007 E/AndroidRuntime( 7606): java.lang.IllegalStateException: FragmentManager is already executing transactions
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2000)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2056)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:818)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:51)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.tbruyelle.rxpermissions.RxPermissions.<init>(RxPermissions.java:38)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.v2ray.ang.ui.MainActivity.readContentFromUri(MainActivity.kt:538)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.v2ray.ang.ui.MainActivity.chooseFileForCustomConfig$lambda-13(MainActivity.kt:530)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$kC5rmdOtWJBi-hmucWYIWt8_hm4(Unknown Source:0)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda11.onActivityResult(Unknown Source:4)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.Fragment.performStart(Fragment.java:2548)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.FragmentController.dispatchStart(FragmentController.java:193)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.Activity.performStart(Activity.java:7175)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.os.Looper.loop(Looper.java:193)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at java.lang.reflect.Method.invoke(Native Method)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
04-16 05:51:50.007 E/AndroidRuntime( 7606): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-16 05:51:56.897 W/com.v2ray.ang( 7670): Unexpected CPU variant for X86 using defaults: x86_64
04-16 05:51:57.018 E/GoLog   ( 7670): Failed to create /data/.cache for shader cache (Permission denied)---disabling.

**Comment by yuhan6665** [comment]
Looks like a bug in RxPermissions:
```
04-16 05:50:32.023 E/AndroidRuntime( 6855): at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:51)
04-16 05:50:32.023 E/AndroidRuntime( 6855): at com.tbruyelle.rxpermissions.RxPermissions.(RxPermissions.java:38)
04-16 05:50:32.023 E/AndroidRuntime( 6855): at com.v2ray.ang.ui.MainActivity.readContentFromUri(MainActivity.kt:538)
```

**Comment by lerignoux** [comment]
Hello

Sorry it seems I still have a similar issue.
Got the same I think：
V2 RayNG version: 1.8.5
Android version: 8.0.0
Model: Galaxy S7
```
--------- beginning of main
12-12 15:26:19.615 D/AndroidRuntime(19515): Shutting down VM
--------- beginning of crash
12-12 15:26:19.616 E/AndroidRuntime(19515): FATAL EXCEPTION: main
12-12 15:26:19.616 E/AndroidRuntime(19515): Process: com.v2ray.ang, PID: 19515
12-12 15:26:19.616 E/AndroidRuntime(19515): java.lang.RuntimeException: Unable to resume activity {com.v2ray.ang/com.v2ray.ang.ui.MainActivity}: java.lang.IllegalStateException: FragmentManager is already executing transactions
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1746)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.os.Looper.loop(Looper.java:164)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at java.lang.reflect.Method.invoke(Native Method)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
12-12 15:26:19.616 E/AndroidRuntime(19515): Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1993)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:798)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment(RxPermissions.java:51)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.tbruyelle.rxpermissions.RxPermissions.<init>(RxPermissions.java:38)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.v2ray.ang.ui.MainActivity.readContentFromUri(MainActivity.kt:566)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.v2ray.ang.ui.MainActivity.chooseFileForCustomConfig$lambda$12(MainActivity.kt:553)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$XHQElb2b-MDTTZN6xaeWAsgU7zQ(Unknown Source:0)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda13.onActivityResult(Unknown Source:4)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.ReportFragment$Companion.dispatch$lifecycle_runtime_release(ReportFragment.kt:192)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.kt:87)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.kt:56)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.Fragment.performStart(Fragment.java:2637)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1312)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3045)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3002)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.FragmentController.dispatchStart(FragmentController.java:190)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.Activity.performStart(Activity.java:7206)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.Activity.performRestart(Activity.java:7340)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.Activity.performResume(Activity.java:7353)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
12-12 15:26:19.616 E/AndroidRuntime(19515): 	... 8 more
```

Should I open a new issue instead ?
Can I help with anything ?
