### ISSUE TITLE
VLESS协议从V2rayN分享至V2rayNG BUG

### ISSUE THREAD

**Issue by ywyt** [2dust/v2rayNG#1454]
V2rayN下的伪装域名字段，在V2rayNG中被解析成SNI。
1.5.17版本无问题，后续版本会。

**Comment by 2dust** [comment]
把你的分享发出来，去掉敏感信息

**Comment by ywyt** [comment]
vless://UUID@我的IP:8443?encryption=none&flow=xtls-rprx-direct&security=tls&type=tcp&headerType=none&host=我的域名#VLESSfallback
vless://UUID@我的IP:443?encryption=none&flow=xtls-rprx-direct&security=tls&type=ws&host=我的域名&path=%2Fless#VLESSws

**Comment by 2dust** [comment]
> 
vless://UUID@我的IP:8443?encryption=none&flow=xtls-rprx-direct&security=tls&type=tcp&headerType=none&host=我的域名#VLESSfallback
因为tcp是没有host的，所以ng会自动填入到SNI中，这个是正确的。

vless://UUID@我的IP:443?encryption=none&flow=xtls-rprx-direct&security=tls&type=ws&host=我的域名&path=%2Fless#VLESSws
这个填入到SNI中也可以的，因为缺少SNI的时候默认就用host

**Comment by ywyt** [comment]
然后我就出现了问题
vless+tls报 io:read/write on closed pipe错误

**Comment by 2dust** [comment]
如果您怀疑是NG的配置有问题，请导出完整配置，然后对照v2ray的文档反馈下哪个地方有问题

**Comment by ywyt** [comment]
跟#1463 一样，突然就好了。
不知道具体的原因是什么，总之1.5.17版本毫无问题。
后续版本不知道更改了什么，从win端分享VLESS配置到安卓端会出现 io:read/write on closed pipe错误。
反馈下这个问题，具体的原因可能我搞错了。
