### ISSUE TITLE
[Feature request] Add support for shadowsocks-2022 ciphers

### ISSUE THREAD

**Issue by Shikopat** [2dust/v2rayNG#1455]
Please Add support for shadowsocks-2022 ciphers:

2022-BLAKE3-AES-128-GCM
2022-BLAKE3-AES-256-GCM
2022-BLAKE3-CHACHA20-IETF-POLY1305

Regards

**Comment by GeorgeRudd** [comment]
内核现在已经支持了 请求在客户端添加相应加密方式的选项
