### ISSUE TITLE
Tiktok域名问题

### ISSUE THREAD

**Issue by foxdodo** [2dust/v2rayNG#1456]
### 预期行为
描述你认为应该发生什么
tiktok域名应该经过代理, 否则大陆ip无法正常使用tiktok

### 实际行为
默认设置下v2rayng绕过了tiktok域名

### 复现方法
大陆ip默认设置下使用v2rayng作为代理无法刷出tiktok视频(已经使用了mod改区). 使用全局模式或者clash则可正常刷出视频.

### 日志信息
<details>
04-17 19:02:51.562 I/GoLog   (24718): [Debug] app/dns: domain api22-normal-c-alisg.tiktokv.com matches following rules: [geosite:cn(DNS idx:0) geosite:cn(DNS idx:4)]
04-17 19:02:51.562 I/GoLog   (24718): [Debug] app/dns: domain api22-normal-c-alisg.tiktokv.com will use DNS in order: [FakeDNS UDP:223.5.5.5:53 UDP:1.1.1.1:53 UDP:1.1.1.1:53 UDP:223.5.5.5:53]
04-17 19:02:51.562 I/GoLog   (24718): [Info] app/dns: FakeDNS got answer: api22-normal-c-alisg.tiktokv.com -> [198.18.145.170]
04-17 19:02:51.562 I/GoLog   (24718): [Debug] app/dns: domain api22-core-c-alisg.tiktokv.com matches following rules: [geosite:cn(DNS idx:0) geosite:cn(DNS idx:4)]
04-17 19:02:51.562 I/GoLog   (24718): [Debug] app/dns: domain api22-core-c-alisg.tiktokv.com will use DNS in order: [FakeDNS UDP:223.5.5.5:53 UDP:1.1.1.1:53 UDP:1.1.1.1:53 UDP:223.5.5.5:53]
04-17 19:02:51.562 I/GoLog   (24718): [Info] app/dns: FakeDNS got answer: api22-core-c-alisg.tiktokv.com -> [198.18.145.171]
</details>

### 环境信息
安卓11

### 额外信息（可选）
开始以为是修改版tiktok的问题, 后来发现v2rayng开全局模式可以刷出视频, 接着换成clash也正常. 所以为什么没把geosite:tiktok添加到默认自定义规则里面? 现在大陆ip直连tiktok没有意义

**Comment by 2dust** [comment]
您自己添加下
请到 https://github.com/2dust/v2rayCustomRoutingList/blob/master/proxy
