### ISSUE TITLE
[Feature request] Add support for open app with link v2board

### ISSUE THREAD

**Issue by GenzPN** [2dust/v2rayNG#1457]
Please add support for open app with link v2board

v2rayng://install-config/url=https://domain/api/v1/client/subscribe?token=token&name=VPN

**Comment by 2dust** [comment]
Please provide the documentation about this feature in v2board

**Comment by GenzPN** [comment]
You can update app can v2rayng app with config ? For us can easy to update

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.5

 v2rayng://install-config?url=http%3A%2F%2Fexample.com&name=example

**Comment by PouryaDe** [comment]
> v2rayng://install-config?url=http%3A%2F%2Fexample.com&name=example

&name=example not work name parameter

and please add "Enable atomatic updates" params

**Comment by sbh96** [comment]
> > v2rayng://install-config?url=http%3A%2F%2Fexample.com&name=example
> 
> &name=example not work name parameter
> 
> and please add "Enable atomatic updates" params

please add Enable atomatic updates in query params
like `updates=1440`
@2dust

**Comment by ixomidi** [comment]
This feature is very important for me, and I kindly request the developer to add it as soon as possible.
[@2dust](https://github.com/2dust)

**Comment by GenzPN** [comment]
It support now but dont have path name

**Comment by ixomidi** [comment]
What I want is that when we put the command v2rayng://install-config?url from the subscription link, once the subscriptions are updated and the configuration is displayed.
