### ISSUE TITLE
加强版geoip等的应用规则如何导入？

### ISSUE THREAD

**Issue by q350976501** [2dust/v2rayNG#1458]
"routing": {
  "rules": [
    {
      "type": "field",
      "outboundTag": "Reject",
      "domain": ["geosite:category-ads-all"]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "domain": ["geosite:gfw", "geosite:greatfire"]
    },
    {
      "type": "field",
      "outboundTag": "Proxy",
      "ip": ["geoip:telegram"]
    },
    {
      "type": "field",
      "outboundTag": "Direct",
      "network": "tcp,udp"
    }
  ]
}

例如这种规则，请问是否有合适的方式在v2rayN以及NG中导入呢？我试过剪贴板和文件都不行

**Comment by 2dust** [comment]
v2rayN在高级路由里面可以自己写入，注意N的Tag和你这里不同
v2rayNG需要自己填，比如geosite:greatfire填在代理项里面

**Comment by q350976501** [comment]
> v2rayN在高级路由里面可以自己写入，注意N的Tag和你这里不同 v2rayNG需要自己填，比如geosite:greatfire填在代理项里面

明白，N的规则是全都在一起，最上面的优先，但是NG的，代理、直连、禁用三个标签并立，不知道逻辑上哪个最优先？优先触发代理？

**Comment by 2dust** [comment]
顺序是：代理、直连、禁用 ，预定义规则

**Comment by juneszh** [comment]
> 顺序是：代理、直连、禁用 ，预定义规则

@2dust 
期望后续可以增加自定义顺序, 因为白名单和黑名单的流程通常不一样. 特别是最近443端口广泛被封, 普遍被认为是用国外服务器访问国内ip时被识别.
习惯是 先禁用广告 -> 能直连的尽量直连 -> 再用!cn代理 -> 最后再用一个直连兜底

**Comment by 2dust** [comment]
白名单 ：设置绕过大陆即可
黑名单 ：自己设置自定义代理，最后设置全局直连
