### ISSUE TITLE
新增分应用代理需要切换节点才能生效

### ISSUE THREAD

**Issue by onemapl3** [2dust/v2rayNG#1459]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
即时热更新

### 实际行为
需要切换节点才能应用规则

### 复现方法
1. 勾选新的分应用代理应用
2. 切到新勾选的app 流量未走代理
3. 切换节点 切回前述app 流量走代理

### 日志信息
暂无

### 环境信息
安卓12

**Comment by 2dust** [comment]
分应用设置后需要重启服务

**Comment by onemapl3** [comment]
如果无法hot-update 建议在用户界面上给出提示
