### ISSUE TITLE
关于UI的一个建议

### ISSUE THREAD

**Issue by vki7** [2dust/v2rayNG#146]
目前的状态栏通知图标和下拉通知是同时存在的。
是否可以选择只显示下拉通知，隐藏状态栏图标呢？

**Comment by 2dust** [comment]
做不出来

**Comment by wydy** [comment]
原生安卓可以左右滑一下，点省略号再点最小化即可实现

**Comment by vki7** [comment]
> 原生安卓可以左右滑一下，点省略号再点最小化即可实现

你说的是Android 9吧，Android 10通知最小化被取消了
