### ISSUE TITLE
希望“自定义路由”可以更完善一些，例如可以使用“geoip:cn”、“geosite:cn”这些值

### ISSUE THREAD

**Issue by trysh** [2dust/v2rayNG#146]
希望“自定义路由”可以更完善一些，例如可以使用“geoip:cn”、“geosite:cn”这些值

**Comment by 2dust** [comment]
现在就是支持的

纯字符串: 当此字符串匹配目标域名中任意部分，该规则生效。比如"sina.com"可以匹配"sina.com"、"sina.com.cn"和"www.sina.com"，但不匹配"sina.cn"。
正则表达式: 由"regexp:"开始，余下部分是一个正则表达式。当此正则表达式匹配目标域名时，该规则生效。例如"regexp:\\.goo.*\\.com$"匹配"www.google.com"、"fonts.googleapis.com"，但不匹配"google.com"。
子域名 (推荐): 由"domain:"开始，余下部分是一个域名。当此域名是目标域名或其子域名时，该规则生效。例如"domain:v2ray.com"匹配"www.v2ray.com"、"v2ray.com"，但不匹配"xv2ray.com"。
完整匹配: 由"full:"开始，余下部分是一个域名。当此域名完整匹配目标域名时，该规则生效。例如"full:v2ray.com"匹配"v2ray.com"但不匹配"www.v2ray.com"。
特殊值"geosite:cn": 内置了一些常见的国内网站域名。
特殊值"geosite:speedtest" (V2Ray 3.32+): Speedtest.net 的所有公用服务器列表。
