### ISSUE TITLE
vless xtls报 io:read/write on closed pipe错误

### ISSUE THREAD

**Issue by handus** [2dust/v2rayNG#1463]
很奇怪同vps搭建的vless tls模式以及 vmess trojan都正常  xtls电脑端也正常
排除了时间以及流控的问题 也重装过面板 换了新的证书

**Comment by charlie0929max** [comment]
我也是 重新订阅了也不行

**Comment by DiNG-007** [comment]
手机连WiFi可以连上，使用移动数据报错io:read/write on closed pipe

**Comment by ywyt** [comment]
我之前也遇到同样错误。
参考https://github.com/2dust/v2rayNG/issues/1454
可能是同样的BUG
手机端手动修改配置，把SNI的配置上的域名剪切后粘贴到伪装域名字段，保存后应该可以（如果能保存成功的话）。

**Comment by handus** [comment]
突然又好了 昨天看了ywyt的回复 本来想试着弄下sni的配置的 结果发现突然就好了 不知道为啥 节点信息 设置都没变的

**Comment by qist** [comment]
vless quic 报一样的错误。

**Comment by ChuLiqiang** [comment]
换fullchain.cer证书
