### ISSUE TITLE
可以增加一个流量统计功能，就是本次使用，共用了多少流量，clash有这个功能，v2rayng的用户或许也是需要的

### ISSUE THREAD

**Issue by zouhhx** [2dust/v2rayNG#1465]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
流量统计浪费手机资源

**Comment by liwenjie119** [comment]
> 流量统计浪费手机资源

这个功能还是有用的，网速统计都有了，流量统计应该占用不了太多资源吧？
