### ISSUE TITLE
能否提供Relese中Assets的打包细节

### ISSUE THREAD

**Issue by cipchk** [2dust/v2rayNG#1466]
git clone 后未做任何修改直接进行 Build 打包出来的 apk，比 Release 大一半，其中最主要区别就是 Relese 下的 `libgojni.so` 才 `6.8MB`，而为什么我通过 Android Studio 打包出来后的有 `26MB`。

我的环境：

- Mac
- Java 11
- Go 1.18.1

**Comment by yuhan6665** [comment]
gomobile bind -v -ldflags='-s -w' github.com/2dust/AndroidLibV2rayLite

-ldflags='-s -w' is important

**Comment by cipchk** [comment]
@yuhan6665 的确降低大小了，但是依然还有 `19.3` MB，Release 里面只有 `6.7` MB。不过问题已经解决 了，是我调整了 `minSdkVersion`  导致 SO 文件无法压缩，设置 `android:extractNativeLibs="true"` 后，APK 大小已经下降到 Release 水平。
