### ISSUE TITLE
[Feature 请求] 支持非标准端口 DNS 服务

### ISSUE THREAD

**Issue by zw4832** [2dust/v2rayNG#147]
【背景】
V2RAY 的 DNS 功能可以帮助自己搭建一个 DNS 服务器。由于众所周知的原因，很多时候标准 53 端口的流量是被屏蔽的。

【需求】
将“境内DNS”指向一个非标准端口的 DNS 服务。

我不确定现在的 V2RAYNG 是否有这一功能。我尝试将 V2RAYNG DNS 服务器信息填为 ip:port 和 ip#port, 但服务端似乎都没有回应。

**Comment by zw4832** [comment]
从文件 `V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt`的代码来看，目前是没有支持这个功能。

不过我找到了一个替代的解决方案，将自行架设的 DNS 服务器地址填入“远程DNS”中，在“境内DNS”填一个无意义的地址，V2RAYNG 就会将 DNS 查询流量导到 V2RAY 服务器上。然后 V2RAY 的路由配置可以解决一切问题。

**Comment by 2dust** [comment]
core是支持非53 port的dns的
但是UI为了简化设置没有做支持,可能后面也不会支持.理由如下
1.远程dns没有必要支持,用户肯定要保证出口dns正常
2.本地dns一般是大陆内,理论上53 port也是正常的
