### ISSUE TITLE
V2rayNG上显示context deadline exceeded 手机是红米K40 重装无效 有解吗?

### ISSUE THREAD

**Issue by Osiris0421** [2dust/v2rayNG#1470]
另一个一加手机就没事

**Comment by ONCfan** [comment]
我也是K40，最近也是V2ray上不了网，同一个节点电脑就可以，手机什么网页都打不开，play store可以打开应用的详情页看评论，但下载时就下载不了。

**Comment by meitoufaduola** [comment]
同k40，前几天用的好好的，不知道为啥就用不成了，不知道是这个软件的问题，还是我节点的问题。希望能尽快改善，其他的VPN软件有广告，还贵。只有这个最快了，希望能尽快解决问题。

**Comment by ONCfan** [comment]
你们的K40是什么版本的miui，我前两天刚更新到13.0.5.0，我觉得可能和我前两天升级的系统有关，现在MIUI降级还要解BL锁线刷，贼麻烦，以前还能断网改包名卡刷，现在升级系统必须联网，小米吃相是真难看。

**Comment by meitoufaduola** [comment]
我是12.5.19，我觉得跟系统版本没关系吧，前几天一切正常，速度贼快，后来就不行了。现在还会有测试延时也不高，就是上不去网，啥都打不开

**Comment by Bom234** [comment]
how to fix error Context deadline exceeded by v2ray

**Comment by xiaoguaishou92** [comment]
客户端的alterId给改成0即可

**Comment by phillip2019** [comment]
我的alterid调成100就好了

**Comment by 1466343432** [comment]
> 我的alterid调成100就好了

安卓的alterid怎么调

**Comment by 1466343432** [comment]
> 客户端的alterId给改成0即可

安卓要怎么改

**Comment by dbthinking** [comment]
> 

使用v2ray协议的服务线路，在具体的线路配置里，就能看到修改alterId的选项。

**Comment by dbthinking** [comment]
> > 我的alterid调成100就好了
> 
> 安卓的alterid怎么调

@1466343432 

使用v2ray协议的服务线路，在具体的线路配置里，点击修改按钮，就能看到alterId选项。

**Comment by leo985** [comment]
这么多人遇到这个问题，居然没人解决，服了。alterid改了也是没有用的。不改alterid也能用2分钟怎么解释？？？？？？2分钟后就不行。

**Comment by zimiyu** [comment]
> 

你这个大概率是被服务器防火墙（非gfw）给挡了

**Comment by YapuWang** [comment]
是的。我经过测试同一个节点用电信5G就提示这个错误，换wifi就正常了，所以是服务器防火墙挡了，出现这个情况换个wifi或者运营商测试下吧，都不行就只能换节点了
