### ISSUE TITLE
Add a option to force V2rayNG use English instead of System language

### ISSUE THREAD

**Issue by realldz** [2dust/v2rayNG#1472]
Please add a option to force V2rayNG use English instead of System language

**Comment by cuynu** [comment]
Why you need this?

**Comment by realldz** [comment]
I'm used to using English than others

**Comment by 2dust** [comment]
v2rayng://install-config?url=http%3A%2F%2Fexample.com&name=example

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.5

**Comment by realldz** [comment]
@2dust some part of app still follow system language. Although app language is set to English
![image](https://user-images.githubusercontent.com/31581520/166144830-6bf0eebf-82e4-4c74-902f-afec1f8c4fe9.png)
![image](https://user-images.githubusercontent.com/31581520/166144890-2c1d3491-dd49-4157-9930-4c1cdffad375.png)
