### ISSUE TITLE
排序

### ISSUE THREAD

**Issue by KmooooU** [2dust/v2rayNG#1474]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
节点排序，是否可以灵活，比如，按节点名称排序，或者，按节点类型分类排序

### 实际行为
没有上述排序功能

### 复现方法
1.打开v2rayng
2. 点击右上角
3.  没有上述排序功能

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by orz12** [comment]
好奇一下 类型具体是指什么呀😀 可以举例子吗

**Comment by KmooooU** [comment]
按ss，trojan，vmess等类型，分类排序
