### ISSUE TITLE
勾选”启用虚拟dns“时，会自动添加geosite:cn规则，导致规则重复

### ISSUE THREAD

**Issue by GeorgeRudd** [2dust/v2rayNG#1475]
路由设置：
域名策略：ipifnonmatch
预定义规则：全局代理
自定义规则只填写 直连的网址或ip：
geosite:cn,
geoip:cn

这种配置下，勾选”启用虚拟dns“，选择节点导出完整配置，可以看到geosite:cn出现了两次
```
      {
        "address": "fakedns",
        "domains": [
          "geosite:cn",
            ..........
          "geosite:cn"
        ]
      }
```
虽然也不影响使用

**Comment by GeorgeRudd** [comment]
另外勾选”启用虚拟dns“后 发现freedom outbound 由默认的"domainStrategy":"AsIs"变成了"domainStrategy": "UseIP" 
```
{
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    }
```
顺便请问如果将freedom outbound配置成 "domainStrategy":"AsIs"  会影响”虚拟dns“功能吗？此时直连的域名由哪个dns解析？

**Comment by yuhan6665** [comment]
对的 因为 AsIs 会由系统解析 然后系统解析又回到 core 得到 Fake IP 这个请求将失败

**Comment by GeorgeRudd** [comment]
谢谢
