### ISSUE TITLE
v2rayng问题

### ISSUE THREAD

**Issue by KmooooU** [2dust/v2rayNG#1477]
v2rayng根本不支持多出站代理，比如，让Netflix 走美国节点， disney走日本节点，v2ray core 明明可以的，但v2rayng 不行，失望极了

**Comment by 2dust** [comment]
您可以使用自定义配置文件达到

**Comment by KmooooU** [comment]
哪里配置自定义文件？

**Comment by 2dust** [comment]
主界面点击+号，最下面的自定义配置

**Comment by KmooooU** [comment]
怎么看到我所有节点配置文件，一个个导出吗？自定义配置也需要这些
