### ISSUE TITLE
[BUG] Socks 协议没有使用代理的 DNS

### ISSUE THREAD

**Issue by dstsmallbird** [2dust/v2rayNG#148]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为

Socks 协议连接并访问网络

### 实际行为

使用 Socks 协议时，域名无法解析。
猜测是未使用 socks 代理进行解析的缘故。
建议修改 socks:// -> socks5h:// 

### 复现方法
1. 添加一个 socks 连接
2. 使用域名访问网站

**Comment by dstsmallbird** [comment]
在全局模式中出现，可能是因为没有走 v2ray 的路由配置导致的 dns 不知道交给谁？

**Comment by 2dust** [comment]
加入socks初衷是给一个内网或大陆内连接使用的
dns方面我本人也未测试过

**Comment by yW9ryqWqaUPW9gN3j** [comment]
我也遇到了相同的问题。从日志上看，本地一直在发 dns 请求即使服务端都能收到。
本地直接做 dns 请求会影响连接速度，可以搭配 clientip 试试。

**Comment by 2dust** [comment]
https://www.v2ray.com/chapter_02/protocols/socks.html
标准 Socks 协议实现，兼容 Socks 4、Socks 4a 和 Socks 5

**Comment by ghost** [comment]
这不是v2rayNG的bug。
v2ray socks服务端要开启udp。
{
  "auth": "noauth",
  "udp": true,
  "ip": "192.168.1.x",
  "userLevel": 0
}
其中“ip"要与Android手机的ip在同一网段。
当开启 UDP 时，V2Ray 需要知道本机的 IP 地址。默认值为"127.0.0.1"。
