### ISSUE TITLE
订阅功能失效

### ISSUE THREAD

**Issue by Seekerzero** [2dust/v2rayNG#148]
订阅功能不能正常使用

机器：荣耀8

具体情况：

在成功订阅之后，想再次订阅就持续显示订阅失败。

请问是否能够提供一个 base64 加密的参数样板，或者将您测试用的base64加密网址提供一下

**Comment by GreenHatHG** [comment]
同楼上，我的也是，ios，win都可以订阅，就android不行。能提供下最好
