### ISSUE TITLE
导入链接后点更新配置显示更新失败

### ISSUE THREAD

**Issue by leisure1x** [2dust/v2rayNG#1485]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by leisure1x** [comment]
以前用的一直好好的，昨天点更新后就一直显示失败了

**Comment by leisure1x** [comment]
用的是vc喵

**Comment by liuhanfei0615** [comment]
同一直更新订阅失败，且重装无效

**Comment by orz12** [comment]
> 用的是vc喵

我也是 昨天vc喵维护了 你加他们tg群就知道 预计今晚解决 不是v2ray的问题

**Comment by orz12** [comment]
不过我这里更新失败好像没有提示啊 就只是没反应而已 不知道能否在importConfigViaSub里面加一个失败的toast

**Comment by Tinmhero** [comment]
v2用户表示也出现了更新失败的问题，从昨天开始就一直报错
