### ISSUE TITLE
红米k30p无法正常使用v2rayNG联网

### ISSUE THREAD

**Issue by mochan934** [2dust/v2rayNG#1486]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
正常链接
### 实际行为
描述实际发生了什么
无法正常链接
### 复现方法

完全相同的服务器使用SSR可以正常链接 使用v2rayNG就无法链接 找了5个不同服务提供商的订阅列表全部无法链接
同时在本Issues页面发现也有人有相同问题 可能是MIUI系统的问题?
### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志

05-02 13
</details>

### 环境信息 MIUI 12.5.7

### 额外信息（可选）

**Comment by wangyifan349** [comment]
我们是一个系统,我也是MIUI但是我能用哎，你换个v2ray的节点试试吧？
