### ISSUE TITLE
EMUI 10上无法正确开启VPN连接

### ISSUE THREAD

**Issue by qakcn** [2dust/v2rayNG#149]
如题，更新到EMUI 10后无法正确开启VPN连接。
v2rayNG成功连接，但系统没有VPN连接（此时可以用浏览器通过10808端口的SOCKS5代理使用，但无法在其他应用使用）。
有时系统会有VPN连接，但无法正常使用。而且断开了v2rayNG连接之后系统VPN连接不断开。
![QQ图片20191030132608](https://user-images.githubusercontent.com/1809188/67831317-e322b400-fb18-11e9-9415-c149d0d34d1a.jpg)
![QQ图片20191030132553](https://user-images.githubusercontent.com/1809188/67831320-eae25880-fb18-11e9-9f1e-15411e2b06b4.jpg)

### 预期行为
v2rayNG连接时，系统出现VPN连接。断开时，系统VPN连接消失。

### 实际行为
连接时，系统VPN不出现。或者出现之后无法访问，并且断开时，系统VPN连接不消失。

### 复现方法
1.打开v2rayNG
2.连接

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of system
--------- beginning of main
10-30 13:23:28.266 I/GoLog   (19713): Using Prepared: 104.28.16.29
```
</details>

### 环境信息
荣耀20 MagicUI3.0.0，EMUI 10.0.0.165，Android 10

**Comment by ibitr** [comment]
同样存在相同的问题，不知道是v2rayNG的问题还是android系统版本的问题，求解。

**Comment by 2dust** [comment]
这个就难了,没有设备可以测试

**Comment by ileeoyo** [comment]
我也有同样的问题，VPN连接图标和软件代理是否开启好像没有关联，我是miui11。另bifrostv也有这个问题。

**Comment by chanfried** [comment]
emui 9 升级到emui 10。v2rayNG配置没有任何变化， 浏览器、twittter 等可以正常翻墙，但是 google play、youtube 无法翻墙。

**Comment by XdaTk** [comment]
找到问题了，默认后台活动被冻结了，国产优化，你懂的

解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”

**Comment by cnmdnews** [comment]
p20 pro链接一会就断流了，什么情况

**Comment by 2dust** [comment]
各种rom各种型号的设备,实话说开发者也很难解决这种类型的问题
也只能是大家都发出来交流下了

**Comment by dbguo** [comment]
同样的emui10一切正常

**Comment by SunWenN** [comment]
mate20 正常使用

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/203

**Comment by enlyhua** [comment]
> 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> 
> 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”

试了，还是不行

**Comment by blizzardster** [comment]
> 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> 
> 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”

真的可以了，感谢

**Comment by revolutionxuanbei** [comment]
> > 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> > 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”
> 
> 真的可以了，感谢

Miui11把所有能打开的权限都打开了，还是不好使。不知道为什么

**Comment by Binly42** [comment]
> > > 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> > > 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”
> > 
> > 
> > 真的可以了，感谢
> 
> Miui11把所有能打开的权限都打开了，还是不好使。不知道为什么

我刚也是这样类似情况, 无法连接, MIUI 11.0.3

FYI @revolutionxuanbei , 我把 MIUI 的那个 VPN 设置里已有的配置 (我之前一直用的是 Shadowsocks) 关掉, 然后再跑 v2rayNG, 按提示重新配一下 VPN 之后就能正常连接了

**Comment by 93Alliance** [comment]
问题核心是需要分应用里面把com.android.setting勾选代理

**Comment by revolutionxuanbei** [comment]
> 问题核心是需要分应用里面把com.android.setting勾选代理

试了，好像还是不得行

**Comment by revolutionxuanbei** [comment]
> > > > 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> > > > 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”
> > > 
> > > 
> > > 真的可以了，感谢
> > 
> > 
> > Miui11把所有能打开的权限都打开了，还是不好使。不知道为什么
> 
> 我刚也是这样类似情况, 无法连接, MIUI 11.0.3
> 
> FYI @revolutionxuanbei , 我把 MIUI 的那个 VPN 设置里已有的配置 (我之前一直用的是 Shadowsocks) 关掉, 然后再跑 v2rayNG, 按提示重新配一下 VPN 之后就能正常连接了

我也试了这样，确实可以，但是有效期只有五分钟，然后又不行了，得再执行一次

**Comment by 93Alliance** [comment]
> > 问题核心是需要分应用里面把com.android.setting勾选代理
> 
> 问题根本没有com.android.setting这个包啊，压根没找到

分应用代理里面，名字可能不叫这个，com.android.setting 是小标题，有可能显示是 ***设置之类的，你找关于设置相关的应用，然后标题下面会有一行小字 就是上面的那个包。找到之后重启v2rayNG

**Comment by revolutionxuanbei** [comment]
> > > 问题核心是需要分应用里面把com.android.setting勾选代理
> > 
> > 
> > 问题根本没有com.android.setting这个包啊，压根没找到
> 
> 分应用代理里面，名字可能不叫这个，com.android.setting 是小标题，有可能显示是 ***设置之类的，你找关于设置相关的应用，然后标题下面会有一行小字 就是上面的那个包。找到之后重启v2rayNG

大佬你看，我已经把android的seting加到代理了，还是这样。
![Screenshot_2020-02-24-22-38-13-670_com v2ray ang](https://user-images.githubusercontent.com/40100149/75161256-79c55180-5756-11ea-9b9a-4ad62e319eab.jpg)

**Comment by 93Alliance** [comment]
重启之后呢

**Comment by revolutionxuanbei** [comment]
> 重启之后呢

无论是手机还是应用都重启过，甚至重装过了。方便透露你是什么手机什么系统嘛。我是小米10pro

**Comment by 93Alliance** [comment]
我是mate 10 pro,小米10推荐直接使用开发版本，完全没有问题

**Comment by revolutionxuanbei** [comment]
> 我是mate 10 pro,小米10推荐直接使用开发版本，完全没有问题

你是mate10你咋知道小米10用开发版没问题...猜的还是手头有小米

**Comment by 93Alliance** [comment]
> > 我是mate 10 pro,小米10推荐直接使用开发版本，完全没有问题
> 
> 你是mate10你咋知道小米10用开发版没问题...猜的还是手头有小米

对的，有一台，华为的比较恶心，设置被代理之后会导致华为share功能在翻墙的时候不能使用

**Comment by revolutionxuanbei** [comment]
> > > 我是mate 10 pro,小米10推荐直接使用开发版本，完全没有问题
> > 
> > 
> > 你是mate10你咋知道小米10用开发版没问题...猜的还是手头有小米
> 
> 对的，有一台，华为的比较恶心，设置被代理之后会导致华为share功能在翻墙的时候不能使用

我其实不是那种用得特别激进的人，开发版对我来说不稳定。老哥你是小米10还是10pro

**Comment by 93Alliance** [comment]
10 pro

**Comment by 93Alliance** [comment]
> > > > 我是mate 10 pro,小米10推荐直接使用开发版本，完全没有问题
> > > 
> > > 
> > > 你是mate10你咋知道小米10用开发版没问题...猜的还是手头有小米
> > 
> > 
> > 对的，有一台，华为的比较恶心，设置被代理之后会导致华为share功能在翻墙的时候不能使用
> 
> 我其实不是那种用得特别激进的人，开发版对我来说不稳定。老哥你是小米10还是10pro

10 pro

**Comment by revolutionxuanbei** [comment]
> > > > > 我是mate 10 pro,小米10推荐直接使用开发版本，完全没有问题
> > > > 
> > > > 
> > > > 你是mate10你咋知道小米10用开发版没问题...猜的还是手头有小米
> > > 
> > > 
> > > 对的，有一台，华为的比较恶心，设置被代理之后会导致华为share功能在翻墙的时候不能使用
> > 
> > 
> > 我其实不是那种用得特别激进的人，开发版对我来说不稳定。老哥你是小米10还是10pro
> 
> 10 pro

老哥方便加个微信不，请教一下

**Comment by JeanYoung-Y** [comment]
尝试了上面的很多方法，无一惯用的，我的今天刚升级为EMUI10，故障表示：连接时，系统VPN出现之后无法访问，断开时，系统VPN连接不消失。
请问诸君有没有找到新的解决办法

**Comment by JeanYoung-Y** [comment]
> 尝试了上面的很多方法，无一惯用的，我的今天刚升级为EMUI10，故障表示：连接时，系统VPN出现之后无法访问，断开时，系统VPN连接不消失。
> 请问诸君有没有找到新的解决办法

啊，头秃，我通过更新V2ary客户端的方式解决了这个问题
https://www.lanzous.com/i9om17i

**Comment by revolutionxuanbei** [comment]
> > 尝试了上面的很多方法，无一惯用的，我的今天刚升级为EMUI10，故障表示：连接时，系统VPN出现之后无法访问，断开时，系统VPN连接不消失。
> > 请问诸君有没有找到新的解决办法
> 
> 啊，头秃，我通过更新V2ary客户端的方式解决了这个问题
> https://www.lanzous.com/i9om17i

我使用github发布页面和google play的最新版本均无效果，不建议在第三方下载客户端，大家注意甄别。

**Comment by qakcn** [comment]
> 问题核心是需要分应用里面把com.android.setting勾选代理

可以了……感谢！！

**Comment by Junpliu** [comment]
Apart from the advices above, you may need ensure the option "ipv6 first" disabled. 
And my version is 1.2.5.

**Comment by DreamSaddle** [comment]
> 问题核心是需要分应用里面把com.android.setting勾选代理

正确答案

**Comment by GarfieldR** [comment]
我的小米10 貌似低位的端口号都被禁了 443的所有链接都完犊子

**Comment by liangrongzhi136** [comment]
红米手机前段时间升级完系统就不能用了

**Comment by loser135** [comment]
> 问题核心是需要分应用里面把com.android.setting
你好 ， 怎么操作啊 ？非常着急， 分应用是什么意思？在哪里操作？可以具体说一下吗，跪谢

**Comment by loser135** [comment]
> > > 问题核心是需要分应用里面把com.android.setting勾选代理
> > 
> > 
> > 问题根本没有com.android.setting这个包啊，压根没找到
> 
> 分应用代理里面，名字可能不叫这个，com.android.setting 是小标题，有可能显示是 ***设置之类的，你找关于设置相关的应用，然后标题下面会有一行小字 就是上面的那个包。找到之后重启v2rayNG

分应用代理从哪里找 ？ 非常着急，可以帮忙一下吗

**Comment by donshx** [comment]
忘了在哪里看到，说是连接谷歌服务时，要连接一个google*.cn（具体哪个忘了），如果不用全局代理，这个.cn的连接就不通，整个连接就建立不起来。这是试图通过香港连接谷歌的情况

**Comment by zw963** [comment]
见此贴。 https://github.com/v2fly/domain-list-community/issues/398

**Comment by SanjunLiu** [comment]
> 我也有同样的问题，VPN连接图标和软件代理是否开启好像没有关联，我是miui11。另bifrostv也有这个问题。

请问这个问题解决了吗？

**Comment by blizzardster** [comment]
停用电池优化，开启后台运行，启动什么问题都好了，我的手机是华为

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dreamfly32** [comment]
allowInsecure 设置为true，问题解决

**Comment by StarkShang** [comment]
> emui 9 升级到emui 10。v2rayNG配置没有任何变化， 浏览器、twittter 等可以正常翻墙，但是 google play、youtube 无法翻墙。

有解决吗？

**Comment by donshx** [comment]
问题只是，不能成功登录google账号，所以google play上不去。
如果不登录账号，youtube还是可以跑的。
最后，改用clash，就OK了，但涉及局域网的通讯，譬如内网的打印机，就不太畅顺

**Comment by minggangLu** [comment]
> 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> 
> 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”

老哥牛逼，一时手贱把那个选项给取消选中了，结果今天就上不了了，找了半天的问题，居然是这个

**Comment by asd8855** [comment]
> 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> 
> 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”

鸿蒙2.0 也好了 感谢感谢

**Comment by duwanjiang** [comment]
> 找到问题了，默认后台活动被冻结了，国产优化，你懂的
> 
> 解决办法: 需要在 电池-耗电排行-v2rayng-应用启动管理中，开启“容许后台活动”

我的meta30 鸿蒙2.0为啥不行

**Comment by yannick1817** [comment]
> > > 问题核心是需要分应用里面把com.android.setting勾选代理
> > 
> > 
> > 问题根本没有com.android.setting这个包啊，压根没找到
> 
> 分应用代理里面，名字可能不叫这个，com.android.setting 是小标题，有可能显示是 ***设置之类的，你找关于设置相关的应用，然后标题下面会有一行小字 就是上面的那个包。找到之后重启v2rayNG

正解
