### ISSUE TITLE
希望手机端能够简易搜索配置文件

### ISSUE THREAD

**Issue by Sunev** [2dust/v2rayNG#1491]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
目前使用的机场通过订阅链接提供了包含美国，日本，韩国，香港等等200余个节点，按照美国1，美国2这样的方式命名。因为我实际使用的需要，经常会在日，美，港之间切换节点，但是列表太长，滑动寻找不是很方便，所以希望有一个简易的搜索或者说过滤功能，方便快速找到特定的配置文件。

### 实际行为
v1.7.4尚无此功能

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.8

**Comment by Sunev** [comment]
试用了一下，完全满足预期，十分感谢
