### ISSUE TITLE
Please Update V2flyNG core to v4.45.0

### ISSUE THREAD

**Issue by Gherkashen2** [2dust/v2rayNG#1493]
Please update V2ray Core to v4.45.0 for v2flyNG app.

Regards

**Comment by ValdikSS** [comment]
+1 on this.
v4.45.0 includes TCP Keep Alive settings modification, which could greatly improve idle battery life: golang send TCP pings every 15 seconds by default.
See https://github.com/golang/go/issues/48622

**Comment by aawwsslll** [comment]
现在有个分支v2flyng了，内核是v2ray-core，最新版是4.45.2内核的。如果你不用xray内核可以去这下载v2ray-core的版本。
https://github.com/2dust/v2flyNG/releases

**Comment by 2dust** [comment]
https://github.com/2dust/v2flyNG/releases/tag/1.7.17

**Comment by tasty0tomato** [comment]
Maybe time to update v2flyng again.
