### ISSUE TITLE
17.2没事，17.3我的vless+xtls，提示启动服务失败，回档没事，但是Google又给我自动更新了又不行了…………

### ISSUE THREAD

**Issue by q350976501** [2dust/v2rayNG#1496]
PC端用的好好的，以前版本的安卓也用的好好的，升级就不行了，我升到了17.7也还是不行，回退又得删除重装（丢失配置文件）
我甚至又更新了服务器端，现在用的vmess+tls，依然还是不行。

**Comment by yuhan6665** [comment]
导出完整配置看看两者有啥不一样

**Comment by q350976501** [comment]
> 导出完整配置看看两者有啥不一样

没找到这个选项。。只能导出我自己的机场
