### ISSUE TITLE
Russian lang

### ISSUE THREAD

**Issue by 94KONG1** [2dust/v2rayNG#1497]
[languages Ukrainian and Russian](https://homothallic-rehabil.000webhostapp.com/Ukrainian%20and%20Russian%20language.zip) Please add the Russian language, the files are attached.
Thank you in advance!
Bild 1.7.7
[languages Ukrainian and Russian](https://homothallic-rehabil.000webhostapp.com/Ukrainian_and_Russian_language.zip)

**Comment by 2dust** [comment]
please pr here
https://github.com/2dust/v2rayNG/tree/master/ExtRes/

**Comment by 94KONG1** [comment]
> please pr here https://github.com/2dust/v2rayNG/tree/master/ExtRes/
Sorry! I tried to upload files but unfortunately it didn't work out for me, I'm new to this site and still haven't figured out how to use...
Could you help me and upload the files instead of me, I would be grateful to you!
I corrected the translation a little, eliminated inaccuracies.
The archive has two languages; Ukrainian and Russian.

[languages Ukrainian and Russian](https://homothallic-rehabil.000webhostapp.com/Ukrainian_and_Russian_language.zip)

**Comment by 2dust** [comment]
Please provide the content file in the same format
Do not delete and add

https://github.com/2dust/v2rayNG/blob/master/ExtRes/values/strings.xml

**Comment by 94KONG1** [comment]
Guys, I don't understand English, and I don't know how to use your site, please download the archive and upload the files themselves to the repository

**Comment by 94KONG1** [comment]
Download archive from the link
