### ISSUE TITLE
电脑v2rayn可以，手机v2rayNG不行，ping为-1，测试报错IO read/write on closed pipe 

### ISSUE THREAD

**Issue by boredice** [2dust/v2rayNG#1499]
电脑v2rayn可以连接，手机v2rayNG不能连接，ping为-1，测试报错IO read/write on closed pipe 

刚又试了下，同样的节点，cf之后的不行，cf之前的可以

### 复现方法
1.重启手机，依然报错
2.更换版本，1.7.7，1.7.3，1.7.2，1.7.1，1.6.30，1.4.6，依然报错
3.取消手机自动设置时间区，依然报错

### 日志信息
<details>
```
not starting debugger since process acnnot load the jdwp agent
```
</details>

### 环境信息
华为荣耀v10，harmonyos2.0.0

**Comment by Tinmhero** [comment]
同表示连不上，PC可以，换个移动端的就怎么都不行，无论是安装哪个版本还是重启都是一样的情况。
2020年的时候也有人反映过一样的问题，不知道当时是怎么解决的

**Comment by Karry0209** [comment]
今天早上突然开始的，怎么都连不上😣

**Comment by wangyunlg** [comment]
一样的状况，有解决的吗？

**Comment by wangyunlg** [comment]
#369 解决了

**Comment by wangyunlg** [comment]
我这是间歇性的啊？晚上就是报错，早上7.30试了下，也是报错，13.30试了下，又好了。电脑上一直正常，真奇怪！应用数据都清除了一次，重新导入数据也没好。

**Comment by HLearning** [comment]
配置文件重新配， 不要从剪切板导入。。。

**Comment by ZongrongLi** [comment]
电脑和其中一个安卓客户端都正常 , 再加一个就不行了 , 提示一样的,当时第一个安卓刚加的时候也不行,后来不知怎么的就好了,每次新加客户端一开始都不行,但是行了以后还挺稳定的

**Comment by ChuLiqiang** [comment]
> 电脑和其中一个安卓客户端都正常 , 再加一个就不行了 , 提示一样的,当时第一个安卓刚加的时候也不行,后来不知怎么的就好了,每次新加客户端一开始都不行,但是行了以后还挺稳定的

证书换全链证书。fullchain.cer

**Comment by ChuLiqiang** [comment]
不想换证书,就把证书校验关了.

**Comment by ZongrongLi** [comment]
> 不想换证书,就把证书校验关了.

栓q关了就好了

**Comment by kubeadm** [comment]
一样，三星U21，手动配置的伪装host url地址会被移动到sni而非http地址

**Comment by leo985** [comment]
有解决的么，同样的v2ray server，电脑端可以连，手机端 v2rayng不能连。手机端操作系统是：华为鸿蒙
手机端操作系统和app最近都没有没做任何版本变更。突然就不行了。

**Comment by Zeus-chen** [comment]
醉了  有人解决了没

**Comment by Zeus-chen** [comment]
把证书校验关了也不行

**Comment by ghost** [comment]
> 把证书校验关了也不行

唉，可以的。你先中断链接之后记得保存。
不过为什么不能校验证书，这功能到底有什么意义？

**Comment by kakagogo** [comment]
> 



> 有解决的么，同样的v2ray server，电脑端可以连，手机端 v2rayng不能连。手机端操作系统是：华为鸿蒙 手机端操作系统和app最近都没有没做任何版本变更。突然就不行了。

去手机应用设置里面吧数据清除，然后从电能重新导入订阅和相关设置

**Comment by Daoker01** [comment]
关了证书效验可以用了

**Comment by zjsailor** [comment]
1.如果电脑上是OK的，则服务器端就不用管，至少说明VPS是OK的
2.将手机的时间全部设置为手动，不要自动选区时区与时间。
3.将allowInsecure 由默认的false修改为true，保存
再连接并测试。

**Comment by kdsunset** [comment]
从电脑导入配置，不要手打

**Comment by tttangz** [comment]
> > 电脑和其中一个安卓客户端都正常 , 再加一个就不行了 , 提示一样的,当时第一个安卓刚加的时候也不行,后来不知怎么的就好了,每次新加客户端一开始都不行,但是行了以后还挺稳定的
> 
> 证书换全链证书。fullchain.cer

fullchain.cer换了就好了，真正的好方法竟然没人点赞没想到，禁用证书改成true相当于裸奔那么多人真敢用。。

**Comment by ZongrongLi** [comment]
我今天发现一个大坑, 就是dns解析, 你的手机或者电脑, 很有可能没有刷新dns, 域名换了指向ip还刷到原来的,改了host以后就好了

**Comment by cxnext** [comment]
证书换全链证书。fullchain.cer  这个有效

**Comment by lavine66** [comment]
咋换这个呀 在手机端

**Comment by zhychen1173** [comment]
我也遇到同样的问题。同一个VPS，自建的v2ray服务，vmess+tls+ws，一直用的好好的，电脑手机均正常，今天突然安卓手机v2rayNG连不上了，iphone 的shadowrocket也连不上了，但电脑还正常链接。手机连我另外两个节点都正常的，就这个突然就不行了，网络不管是用家里的wifi，还是移动、联通的4G网络都不行，v2rayNG 点测试连接 报：失败：context deadline exceeded。
安卓手机是小米11 pro，MIUI 13 ，v2rayNG也更新到最新版了，iphone 12，ios 15.6.1，shadowrocket更新到最新版，都不行。而且就这个节点突然手机就连不上了，自建的其他节点手机还可以正常链接。这期间手机客户端、服务器端都什么也没做，没更新，没改设置，头天还可以，一觉醒来突然就不行了。
求大神指点该如何解决，谢谢！
前面有提到证书换 fullchain.cer ,不知道这个应该如何操作？我是用一键脚本安装的，证书是acme脚本自动续签。

**Comment by tttangz** [comment]
> 我也遇到同样的问题。同一个VPS，自建的v2ray服务，vmess+tls+ws，一直用的好好的，电脑手机均正常，今天突然安卓手机v2rayNG连不上了，iphone 的shadowrocket也连不上了，但电脑还正常链接。手机连我另外两个节点都正常的，就这个突然就不行了，网络不管是用家里的wifi，还是移动、联通的4G网络都不行，v2rayNG 点测试连接 报：失败：context deadline exceeded。 安卓手机是小米11 pro，MIUI 13 ，v2rayNG也更新到最新版了，iphone 12，ios 15.6.1，shadowrocket更新到最新版，都不行。而且就这个节点突然手机就连不上了，自建的其他节点手机还可以正常链接。这期间手机客户端、服务器端都什么也没做，没更新，没改设置，头天还可以，一觉醒来突然就不行了。 求大神指点该如何解决，谢谢！ 前面有提到证书换 fullchain.cer ,不知道这个应该如何操作？我是用一键脚本安装的，证书是acme脚本自动续签。

检查你服务器的的config.json的"certificates"配置是否用了fullchain.cer，config.json文档官网有的，如果没用全链证书就换，如果已经用了全链证书或者换了全链证书后还有问题，可能续签脚本出问题了，手动续签一下，如果这样可以，你再去改acme脚本

**Comment by zhychen1173** [comment]
> > 我也遇到同样的问题。同一个VPS，自建的v2ray服务，vmess+tls+ws，一直用的好好的，电脑手机均正常，今天突然安卓手机v2rayNG连不上了，iphone 的shadowrocket也连不上了，但电脑还正常链接。手机连我另外两个节点都正常的，就这个突然就不行了，网络不管是用家里的wifi，还是移动、联通的4G网络都不行，v2rayNG 点测试连接 报：失败：context deadline exceeded。 安卓手机是小米11 pro，MIUI 13 ，v2rayNG也更新到最新版了，iphone 12，ios 15.6.1，shadowrocket更新到最新版，都不行。而且就这个节点突然手机就连不上了，自建的其他节点手机还可以正常链接。这期间手机客户端、服务器端都什么也没做，没更新，没改设置，头天还可以，一觉醒来突然就不行了。 求大神指点该如何解决，谢谢！ 前面有提到证书换 fullchain.cer ,不知道这个应该如何操作？我是用一键脚本安装的，证书是acme脚本自动续签。
> 
> 检查你服务器的的config.json的"certificates"配置是否用了fullchain.cer，config.json文档官网有的，如果没用全链证书就换，如果已经用了全链证书或者换了全链证书后还有问题，可能续签脚本出问题了，手动续签一下，如果这样可以，你再去改acme脚本

谢谢，是在config.json的streamSettings中增加例如如下内容？
        "tlsSettings": {
              "allowInsecure": false,
              "certificates": [
                    {
                         "certificateFile": "/data/v2ray.crt", 
                         "keyFile": "/data/v2ray.key"
                    }
               ]
         },

**Comment by ansonfish** [comment]
如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！

我是这样设置之后，解决了问题： io read/write on closed pipe

**Comment by echo-cheng** [comment]
> 



> 不想换证书,就把证书校验关了.
手机上怎么换证书呀

**Comment by ChuLiqiang** [comment]
服务端换啊

echo-cheng ***@***.***> 于 2023年1月31日周二 20:35写道：

**Comment by googlelovegfw** [comment]
今天刚搭的xray，已经配置使用了fullchain证书，在windows上使用v2rayN上可以访问成功，但在华为harmonyOS上使用v2rayNG上却不能访问，测试报错IO read/write on closed pipe

**Comment by tianxvy** [comment]
为什么换成/root/cert/fullchain.cer就好了，求原理

**Comment by JeanTse** [comment]
> 1.如果电脑上是OK的，则服务器端就不用管，至少说明VPS是OK的 2.将手机的时间全部设置为手动，不要自动选区时区与时间。 3.将allowInsecure 由默认的false修改为true，保存 再连接并测试。

感谢！！是真的可以了！
因为是购买的节点所以没法使用后面有人介绍的直接从服务器端改为全链证书的方法，只能跳过证书裸奔了，而且不需要将手机时间设置为手动也OK~
真的就是十分感谢！

**Comment by xsjlmzs** [comment]
> > 电脑和其中一个安卓客户端都正常 , 再加一个就不行了 , 提示一样的,当时第一个安卓刚加的时候也不行,后来不知怎么的就好了,每次新加客户端一开始都不行,但是行了以后还挺稳定的
> 
> 证书换全链证书。fullchain.cer

亲测好用，已解决！不过不知道原理
