### ISSUE TITLE
TLS 1.3 please

### ISSUE THREAD

**Issue by moralrebuild** [2dust/v2rayNG#15]
The core has already supported from 4.18.1. My windows client v2rayN has been upgraded to enjoy the 100Mbit/sec speed but this latest Android client can only achieve <20Mbit/sec for the same server.

**Comment by akiirui** [comment]
这个应该是 AndroidLibV2rayLite, Go 版本的问题...
我看新发布了1.0.1 用 Go-1.12 编译的. Go 从1.12 开始支持 TLS 1.3.

**edit**
测试了, 可以正常使用 TLS 1.3 only 的服务了.
