### ISSUE TITLE
vmess://链接无法导入

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#150]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

配置被成功导入

### 实际行为
描述实际发生了什么

显示失败,无法导入配置

### 复现方法
1.点击加号
2.点击从剪贴板导入
3.显示失败

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

链接如下
vmess://bm9uZToxZjdjOWRiMS1mYmY1LTRjZTMtOGQxOC1iY2NhNWM1ZmFiYTNAMS4xLjEuMToxMDA4Ng==  

在Shadowrocket上可以导入

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

**Comment by ghost** [comment]
感谢
