### ISSUE TITLE
希望v2rayNG支持clash的节点订阅格式

### ISSUE THREAD

**Issue by ropotop** [2dust/v2rayNG#1500]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
对clash节点订阅格式支持后，只需一个订阅链接即可解决所有协议格式。

### 实际行为
shadowsocks iso已支持，非常方便。希望v2rayNG可以尽快支持。

**Comment by 2dust** [comment]
是想在本app内直接使用clash-core，还是把clash节点转换后使用xray-core？

**Comment by ropotop** [comment]
节点转换

**Comment by 2dust** [comment]
https://github.com/tindy2013/subconverter
看下这个项目
用法：在本app的订阅中使用下面的链接
https://sub.xeton.dev/sub?target=v2ray&url=您原来clash的订阅链接

**Comment by ropotop** [comment]
看过这个，不想用第三方，像shadowsocks的iso版一样原生支持岂不是更完美。

**Comment by 2dust** [comment]
> 

原生支持当然美好，但人力有限，一两人一直用爱发电无法长久。
所以能有个现成的轮子先用着吧，等哪天闲着的时候可能就有了
