### ISSUE TITLE
v2rayNG长期运行会出现网络连接不上的情况

### ISSUE THREAD

**Issue by alongL** [2dust/v2rayNG#1501]
服务端一直没问题。
在Android上长期运行v2rayNG，大概将近24小时的时候，容易出现网络连接不了的情况。
我用的是Trojan协议。即使断开连接重新连接也不行。
将v2rayNG结束掉，再重新连接就可以了。
在几个终端（包括真机、模拟器）上的现象是一样的。

具体的日志还没有拿到，只是反映一下这个现象。
v2rayNG版本是最新的版本。

**Comment by suki-on-git** [comment]
更新APP了？我之前更新了UDP连不上
它需要清除数据，卸载重新安装，我是这样解决的

（Xray）

**Comment by zjudongze** [comment]
举个手，但是不知道怎么定位问题
目前用的1.7.11版本

**Comment by ChinaParrot** [comment]
反正老是掉线，没有一个掉线重连机制

**Comment by orz12** [comment]
我也是 目前我就是需要更换节点来恢复 v2rayN也有这个问题
