### ISSUE TITLE
Vmess: Fail to detect internet connection io: read /write on closed pipe Android

### ISSUE THREAD

**Issue by honemz12** [2dust/v2rayNG#1507]
I've been using v2rayng for quite some time but today suddenly I can't connect help me!
#1507

**Comment by Daoker01** [comment]
我也是，在最新版1.7.18有这个问题

**Comment by ansonfish** [comment]
如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！

我是这样设置之后，解决了问题： io read/write on closed pipe
