### ISSUE TITLE
Android不能链接 pc可以链接

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1508]
已排除服务器问题

### 预期行为
手动添加Trojan应该可以正常链接上网

### 实际行为
不能上网，且流控选项设置之后 一直为空

### 复现方法
1. 添加 Trojan
2. 返回
3. 选择添加好的Trojan，进入之后查看流控为空

### 日志信息
<details>
暂无
</details>

### 环境信息
夜神模拟器 x64

**Comment by leo985** [comment]
同样的问题。。。。。是针对app有特殊行动了么，手机操作系统，软件版本均为变过。突然就不行了。但是v2ray电脑客户端仍然能连服务器。

**Comment by huanblog** [comment]
红米Note9，情况一样。
