### ISSUE TITLE
io read/write on closed pipe

### ISSUE THREAD

**Issue by meymself** [2dust/v2rayNG#151]
1.1.7
io read/write on closed pipe
多台设备复现

**Comment by meymself** [comment]
配置问题

**Comment by mia0x75** [comment]
@imrbg 请问什么样的配置问题？手机1上使用正常，手机2扫描分享的二维码，就会有错，两部手机都是，一部Pixel，一部Pixel XL。

**Comment by lvvvmd** [comment]
> @imrbg 请问什么样的配置问题？手机1上使用正常，手机2扫描分享的二维码，就会有错，两部手机都是，一部Pixel，一部Pixel XL。

系统时间问题
