### ISSUE TITLE
vmess传输协议问题

### ISSUE THREAD

**Issue by xuetogong007** [2dust/v2rayNG#1510]
vmess传输协议为tcp时填写伪装提示保存成功其实保存失败这是BUG吧

**Comment by xuetogong007** [comment]
发现居然没有websocket协议导致选择none

**Comment by chika0801** [comment]
vmess?实在要用，建议vmess ws tls吧 vmess tcp好久没用过了。

**Comment by yuhan6665** [comment]
保存时无效的配置会消失
