### ISSUE TITLE
v2rayNG扫描二维码打开摄像头后直接卡死不动

### ISSUE THREAD

**Issue by 326412908a** [2dust/v2rayNG#1512]
### 实际行为
v2rayNG扫描二维码打开摄像头直接卡死不动
### 复现方法
1.添加节点扫描二维码就卡死不动。

### 环境信息
安卓11
### 额外信息（可选）
联想z6 pro

**Comment by cylonchau** [comment]
我也这样，安卓13

**Comment by 326412908a** [comment]
我也是，安卓13。

**Comment by 2dust** [comment]
升级到 https://github.com/2dust/v2rayNG/releases/tag/1.8.3
