### ISSUE TITLE
启动服务失败 清除了数据还是没用 如何处理 设备是红米note7pro 昨天突然出现的问题

### ISSUE THREAD

**Issue by antushengbujaingtonghua10086** [2dust/v2rayNG#1516]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by antushengbujaingtonghua10086** [comment]
--------- beginning of system
--------- beginning of main
05-20 18:19:19.408 E/com.v2ray.ang( 7456): Not starting debugger since process cannot load the jdwp agent.
05-20 18:19:19.517 W/com.v2ray.ang( 7456): type=1400 audit(0.0:21005): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=4657 scontext=u:r:untrusted_app:s0:c236,c258,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
05-20 18:19:21.127 I/GoLog   ( 7502): loading core config
05-20 18:19:21.127 I/GoLog   ( 7502): Preparing Domain: els.kuli888.xyz:443
05-20 18:19:21.130 I/GoLog   ( 7502): new core
05-20 18:19:21.131 I/GoLog   ( 7502): start core
05-20 18:19:21.131 I/GoLog   ( 7502): listen udp 127.0.0.1:10808: bind: address already in use
05-20 18:19:21.131 D/com.v2ray.ang( 7502): go.Universe$proxyerror: listen udp 127.0.0.1:10808: bind: address already in use
05-20 18:19:21.481 I/GoLog   ( 7502): Prepare Result:
05-20 18:19:21.481 I/GoLog   ( 7502):  Domain: els.kuli888.xyz
05-20 18:19:21.481 I/GoLog   ( 7502):  Port: 443
05-20 18:19:21.481 I/GoLog   ( 7502):  IPs: [92.223.72.133]

**Comment by yuhan6665** [comment]
listen udp 127.0.0.1:10808: bind: address already in use
端口占用 这个比较奇怪我也没有遇到过 不行重启手机吧
