### ISSUE TITLE
分应用代理设置功能不理想

### ISSUE THREAD

**Issue by chiupak** [2dust/v2rayNG#1523]
开启该设置后，国内期货软件还是无法使用，即使是在菜单中选择自动选中也没用，能出个教程吗？

**Comment by dbthinking** [comment]
@chiupak  国内期货软件应该不需要走代理吧，你先关闭v2rayNG试试能否使用。分应用代理注意是黑名单还是白名单模式。

**Comment by chiupak** [comment]
> 

我就是想设置不走代理，因为全局就使用不了，但是试了白名单和黑名单都不行

**Comment by chiupak** [comment]
> @chiupak 国内期货软件应该不需要走代理吧，你先关闭v2rayNG试试能否使用。分应用代理注意是黑名单还是白名单模式。

是不需要啊，所以我想设置不走代理，但是设置不成功，黑名单和白名单模式都不行，这点的话clash就很简单，而且设置成功了

**Comment by orz12** [comment]
> 开启该设置后，国内期货软件还是无法使用，即使是在菜单中选择自动选中也没用，能出个教程吗？

那你开了自动选中以后，把你的这款期货软件去除勾选了吗？

**Comment by Tintinding** [comment]
> > @chiupak 国内期货软件应该不需要走代理吧，你先关闭v2rayNG试试能否使用。分应用代理注意是黑名单还是白名单模式。
> 
> 是不需要啊，所以我想设置不走代理，但是设置不成功，黑名单和白名单模式都不行，这点的话clash就很简单，而且设置成功了

好像是启用分应用，部分节点就失效了，要重新测试一下
