### ISSUE TITLE
Geo资源文件实现订阅

### ISSUE THREAD

**Issue by Eyion** [2dust/v2rayNG#1525]
如题，如何将geo资源文件（包括geoip.dat和geosite.dat）添加成订阅源一样？每次手动下载更新不太方便。

**Comment by chika0801** [comment]
没有办法，作者没做自动更新的功能。因为这个文件不用天天更。

**Comment by ghost** [comment]
这个完全没必要，考虑过低运存/低性能的设备用户吗？其实客户端自带的geosite和geoip已经够用了，使用更大的geo文件就会占用更大的运存，消耗更多的cpu，也会直接增加启动服务的时长，所以像现在这样默认使用自带的原生geo文件挺好的，新版加的下载功能也让用户可以选择下载更新成第三方geo文件(Loyalsoldier的geoip和geosite)，这还不够方便？还要有多懒？而且v2rayNG本身就支持手动替换geo文件(也可以在同一文件夹中使用第三方数据文件)，已经很强很完善了。另外，越新、越大的geo文件包含的域名和ip就越多，你确定不会被误杀？毕竟都是别人写的规则，说不定哪天你发现自己访问的一个本该被代理的网站却走了直连，本该直连的却走了代理，又或者本该能打开的却被莫名其妙block…  总之越新越大的geo文件出现这种情况的概率就越高。反正更新使用第三方的geo文件我个人是不放心。

**Comment by Eyion** [comment]
考虑到使用人的设备，是否可做成开关供用户自主选择？许多工具在折腾的同时，也是为了之后的懒，这不冲突。误杀和安全的问题，确实要注意。
另外，Geo资源文件+旁边的下载按键点了好像总失败，它是下载哪儿的文件，还是需要先另外添加下载地址？

**Comment by chika0801** [comment]
> 考虑到使用人的设备，是否可做成开关供用户自主选择？许多工具在折腾的同时，也是为了之后的懒，这不冲突。误杀和安全的问题，确实要注意。 另外，Geo资源文件+旁边的下载按键点了好像总失败，它是下载哪儿的文件，还是需要先另外添加下载地址？
下载网址是github的，你先连上你的节点，自然能正常下载。。。你不会每次都是不连上节点你国内运营商下吧。。。

**Comment by Eyion** [comment]
> > 考虑到使用人的设备，是否可做成开关供用户自主选择？许多工具在折腾的同时，也是为了之后的懒，这不冲突。误杀和安全的问题，确实要注意。 另外，Geo资源文件+旁边的下载按键点了好像总失败，它是下载哪儿的文件，还是需要先另外添加下载地址？
> > 下载网址是github的，你先连上你的节点，自然能正常下载。。。你不会每次都是不连上节点你国内运营商下吧。。。

科学上着网，下载失败...

**Comment by chika0801** [comment]
> > > 考虑到使用人的设备，是否可做成开关供用户自主选择？许多工具在折腾的同时，也是为了之后的懒，这不冲突。误杀和安全的问题，确实要注意。 另外，Geo资源文件+旁边的下载按键点了好像总失败，它是下载哪儿的文件，还是需要先另外添加下载地址？
> > > 下载网址是github的，你先连上你的节点，自然能正常下载。。。你不会每次都是不连上节点你国内运营商下吧。。。
> 
> 科学上着网，下载失败...

那就不知道原因了，帮不了你。你就在电脑上翻墙了下载好，传到文件里，从手机本地导入也一样
