### ISSUE TITLE
v2rayNG crash while import custom configuration from file

### ISSUE THREAD

**Issue by cuynu** [2dust/v2rayNG#1527]
Version : 1.7.8
Here is the crash log after import custom configuration file :
--------- beginning of main
05-28 21:40:39.090 D/AndroidRuntime( 2047): Shutting down VM
--------- beginning of crash
05-28 21:40:39.094 E/AndroidRuntime( 2047): FATAL EXCEPTION: main
05-28 21:40:39.094 E/AndroidRuntime( 2047): Process: com.v2ray.ang, PID: 2047
05-28 21:40:39.094 E/AndroidRuntime( 2047): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionMainViewHolder{c83e342 position=1 id=-1, oldPos=1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{1dc7ee5 VFED..... ......ID 0,0-1080,1731 #7f0901a7 app:id/recycler_view}, adapter:com.v2ray.ang.ui.MainRecyclerAdapter@3a9fdba, layout:androidx.recyclerview.widget.LinearLayoutManager@28be46b, context:com.v2ray.ang.ui.MainActivity@38ae1d8
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4255)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2028)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.view.Choreographer.doFrame(Choreographer.java:727)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.os.Handler.handleCallback(Handler.java:938)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.os.Looper.loop(Looper.java:223)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at java.lang.reflect.Method.invoke(Native Method)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-28 21:40:39.094 E/AndroidRuntime( 2047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.10
