### ISSUE TITLE
期望支持xray内核的新Shadowsocks加密方式配置选项，或者提供手动输入框

### ISSUE THREAD

**Issue by nexply** [2dust/v2rayNG#1528]
### 预期行为
期望支持xray内核的新Shadowsocks加密方式配置选项，或者提供手动输入框
[![XMYZFA.png](https://s1.ax1x.com/2022/05/29/XMYZFA.png)](https://imgtu.com/i/XMYZFA)
[Shadowsocks新协议](https://xtls.github.io/config/inbounds/shadowsocks.html)
### 实际行为
不支持新Shadowsocks加密方式配置选项，也无手动输入框

### 复现方法
1.
2.
3.

### 日志信息
<details>

```
在这里粘贴日志
```
</details>

### 环境信息
华为Mate20 鸿蒙系统
V2rayNG 1.7.3
xray v1.5.5

**Comment by chika0801** [comment]
等NG更新xray core 1.5.6使用自定义配置载入即可。你如果不会写自定义配置，可关注https://github.com/chika0801/Xray-examples/tree/main/Shadowsocks-2022-TCP

我会写设置指南

**Comment by nexply** [comment]
大佬牛逼，这效率也没谁了！！！

**Comment by nexply** [comment]
大佬牛逼，这效率也没谁了！！！
