### ISSUE TITLE
新版本shadowsockets模式解析http异常

### ISSUE THREAD

**Issue by xieccc** [2dust/v2rayNG#153]
使用shadowsockets模式，直连ip的连接正常，但是http请求dns解析异常。使用测试链接，提示connection closed by peer。

**Comment by xieccc** [comment]
#108

**Comment by 2dust** [comment]
是1.1.7吗？
logcat贴出来

**Comment by xieccc** [comment]
是的

**Comment by 2dust** [comment]
能否把你的节点信息发一份给我测试？
captainironng@gmail.com

**Comment by xieccc** [comment]
已经发到你的邮箱，请查收

**Comment by 2dust** [comment]
用你的配置我测试了，正常使用。
你删除ng。重新装后只配置这个点，什么都不要设置试一试。
如果不行把log cat内容贴上了

**Comment by xieccc** [comment]
好的，我删除数据以及重新安装使用一下测试

**Comment by xieccc** [comment]
连接还是很慢，日志我发送到您邮箱

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/110

**Comment by 2dust** [comment]
初步判断原因应该是 服务端会不处理dns请求
而ng的dns是发往远程处理的

**Comment by 2dust** [comment]
我查看了部分ss的服务端源码,有的版本里面确实有类似的配置

  Only Ban these target ports (for blacklist mode)
SS_BAN_PORTS = [22, 23, 25]

**Comment by xieccc** [comment]
用跳板后，应该是dns解析有问题

切换到vmess正常使用

**Comment by 2dust** [comment]
没有根本解决问题
建议大家使用vmess协议吧
