### ISSUE TITLE
v2ng 延迟

### ISSUE THREAD

**Issue by Kim-xx** [2dust/v2rayNG#153]
你好,我有个问题,想请教下.
同一个SS节点(使用V2自带的服务端), 使用安卓SSR连接测试, 延迟200以内,但用v2rayng 连接测试,延迟400多.换了好几个节点,结果都一样.
为什么会有这个现象呢?
网络,硬件环境都是一样的,只有客户端的变化,
而据我了解, ss的延迟是tls握手的延迟，ssr的延迟是ping的延迟。
v2ng 延迟是什么呢? 是不是协议有差异?

**Comment by 2dust** [comment]
NG和ss一样,使用socks代理测试连接

**Comment by git10135405** [comment]
> NG和SS一样，使用袜子代理测试连接

大佬 能不能加个延迟测试 很希望能有这个功能
