### ISSUE TITLE
最新版扫描二维码添加后所有配置文件都变成2个

### ISSUE THREAD

**Issue by lsh1215225** [2dust/v2rayNG#1530]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
之前版本都是只正常增加该二维码配置
### 实际行为
扫描二维码添加后，所有配置文件都变成2个，退出重开后恢复正常

### 复现方法
1.扫描二维码
2.
3.

### 日志信息
<details>--------- beginning of system
--------- beginning of main
05-30 15:01:43.902 E/com.v2ray.ang(18823): Not starting debugger since process cannot load the jdwp agent.
05-30 15:01:43.919 I/com.v2ray.ang(18823): hprofopt setDumpFlag: 0
--------- beginning of untrustedapp
05-30 15:01:44.258 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:44.267 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:44.269 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:44.476 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:44.680 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:44.883 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:45.086 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:45.299 E/com.v2ray.ang(18823): No package ID ff found for ID 0xffffffff.
05-30 15:01:45.748 E/com.v2ray.ang(18823): No packag

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```--------- beginning of main
05-30 15:09:24.713 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:24.768 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:25.232 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
--------- beginning of untrustedapp
--------- beginning of kernel
05-30 15:09:27.195 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:27.200 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:29.012 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:29.016 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:29.075 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:29.533 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
05-30 15:09:30.623 E/com.v2ray.ang(21347): No package ID ff found for ID 0xffffffff.
</details>

### 环境信息
andriod 11
### 额外信息（可选）

**Comment by GeorgeRudd** [comment]
我也有这个问题 另外 手动添加配置文件时 app会崩溃

**Comment by 2dust** [comment]
请给出详细的复现步骤

**Comment by 2dust** [comment]
> 我也有这个问题 另外 手动添加配置文件时 app会崩溃

请给出详细的复现步骤

**Comment by gcphym** [comment]
> > 我也有这个问题 另外 手动添加配置文件时 app会崩溃
> 
> 请给出详细的复现步骤

我用的是基于安卓12的 三星官方系统 oneui 4.1 v2rayNG版本1.7.9 右上角加号 扫描二维码 扫的是电脑上v2rayN生成的节点二维码
当app首页没有任何节点时，扫描添加一个名字为a的节点，结果如图1
<img src="https://raw.githubusercontent.com/gcphym/bug/main/1.jpg" width="200px">
可以看到 虽然只扫了一个码 却出现了两个一样的a
此时 如果**点击home键回到桌面**，或者**点击多任务键进入多任务列表** 之后再回到v2rayNG 就会恢复正常 不需要强制停止v2rayNG 如图2
<img src="https://raw.githubusercontent.com/gcphym/bug/main/2.jpg" width="200px">
在图2的情况下，点击右上角加号，扫描一个名字为b的节点，结果如图3
<img src="https://raw.githubusercontent.com/gcphym/bug/main/3.jpg" width="200px">
出现了两个a两个b
同样，此时**点击home键回到桌面**，或者**点击多任务键进入多任务列表** 之后再回到v2rayNG 就会恢复正常 不需要强制停止v2rayNG 如图4

<img src="https://raw.githubusercontent.com/gcphym/bug/main/4.jpg" width="200px">

**Comment by gcphym** [comment]
> > 我也有这个问题 另外 手动添加配置文件时 app会崩溃
> 
> 请给出详细的复现步骤

另外 手动添加配置文件时 app会崩溃
右上角加号→自定义配置→从本地导入自定义配置 此时会进入系统自带的文件浏览
<img src="https://raw.githubusercontent.com/gcphym/bug/main/10.jpg" width="200px">
点击json文件后会立刻闪退回手机桌面 同时弹出提示
<img src="https://raw.githubusercontent.com/gcphym/bug/main/5.jpg" width="200px">

此时重新进入v2rayNG 可以看到 实际上json已经添加成功 可以正常使用

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.10

**Comment by 2dust** [comment]
> 进入

查看是否已经给了app读取权限
把log发下

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.10
