### ISSUE TITLE
安卓版问题,出现各种错误,边看边学习,各种排除都做了.从14.1版本到17.9版本,全试了.安卓始终无法稳定运行

### ISSUE THREAD

**Issue by Alexclzyzwd** [2dust/v2rayNG#1533]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为

希望能够解决context deadline exceeded 这个错误问题.

### 实际行为
这两天被搞崩溃了,centOS 7.2 -8.2 各种版本都试了,卓版问题,出现各种错误,边看边学习,各种排除都做了.从14.1版本到17.9版本,全试了.安卓始终无法稳定运行.错误代码最多的就是:context deadline exceeded.前前后后解决各种疑难杂症,MD5证书问题,系统时间问题,systemd的版本问题,alterID的问题.BBR内核问题,这期间解决了,但是系统重启后又链接不了,测试版本为17.2.
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
2022/06/01 09:23:33 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:23:33 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:23:36 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": dial tcp 8.8.4.4:443: i/o timeout
2022/06/01 09:23:36 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:23:37 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:23:37 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:24:03 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:24:03 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded
2022/06/01 09:24:07 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": dial tcp 8.8.8.8:443: i/o timeout
2022/06/01 09:24:07 [Error] app/dns: failed to retrieve response > Post "https://dns.google/dns-query": context deadline exceeded

```
</details>

###

系统版本:centOS 8.2
systemd版本: 239
服务端版本:233大神脚本
客户端:14.1 至 17.9

###

### 
各种依赖环境都测试过
git
ntp
curl
yum源

**Comment by PanHsin** [comment]
这样纯属盲猜，看不出什么问题

**Comment by wangyifan349** [comment]
你怎么运行的？

这样吗
nohup xray run>/dev/null 2>&1&

**Comment by lsill** [comment]
有没有一种可能是你的安全组没配置对应的端口号

**Comment by Cirooo** [comment]
有没有那么一种可能，用的是国内的主机？

**Comment by leo985** [comment]
顶起来，维护的人有么，这问题这么多人提，视而不见？？
本人服务端：V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.)
客户端v1.7.17 v2fly-core 4.45.2
手机时间不同步问题不存在的，alterid问题不存在的。md5证书问题不存在的
现象是：一个新的端口，测试能成功，手机能连两分钟不到，然后马上就不行。然后再测试： context deadline exceeded. 期间什么配置都没动。哪位大神解释一下，2分钟后不行的问题？这个总该不是因为配置不对吧？？？
电脑macpro：使用的v2rayu,好得很，一直稳定连，同一个配置哦。
