### ISSUE TITLE
安卓tv10 运行后自动终止

### ISSUE THREAD

**Issue by fffzzl** [2dust/v2rayNG#1537]
### 预期行为
选择节点开始运行
### 实际行为
运行后10s-30s后自动关闭
### 复现方法
1.索尼电视9000h打开v2rayNG
2.选择节点运行
3.等待一会运行按钮就会从亮变暗

### 日志信息
<details>
(30024 ) : Not UsingPrepared :udp ,1.1.1.1 : 53
(30024):127.0.0.1:51949 accepted udp:1.1.1.1:53[dns-out
(30024): Not Using Prepared:tcp,120.195.6.192:11101
06-0417:11:07.666/ OlOg
(30024):tcp:127.0.0.1:49786 accepted tcp47.24638.208:80 proxy
06-0417:11:08.758/ GoLog
(30024 ) : PrepareDomainerr : lookup120.195.6.192 : No address associated with hostname
06-0417:11:10.7581/ GoLog
(30024 ) : PrepareDomain maxRetryreachedexiting.
06-0417:11:10.758/ GOLog
(30024 ) : sErver cannotresolved , shutdown
0417 :11 : 10.760D /com .vrayang (30024 ) : c
06-0417 :11 : 10.761l /tun2socks (2786 ) :NOTICE (tun2socks ) : termination requested
06-0417 :11 :10 . /tun2socks (2786 ) :NOTICE (tun2socks ) : tearing down
060417 :11 : 10.761I /tun2socks (2786 ) :NOTICE (tun2socks ) : Free TCP connections
060417 :11 : 10.762I /tun2socks (2786 ) :NOTICE (tun2socks ) : exiting
</details>
（百度翻译截图提取
### 环境信息
索尼9000h
安卓tv10
内核4.19.75
### 额外信息（可选）
端午快乐（球球了

图片版日志
![image](https://user-images.githubusercontent.com/67791411/171993279-d56b0895-3eac-4105-b422-2614cd093805.png)

**Comment by fffzzl** [comment]
在开启过程中是可以正常代理

**Comment by yuhan6665** [comment]
似乎是你的 IP 后面多写了一个空格

**Comment by fffzzl** [comment]
还真是
