### ISSUE TITLE
安全疑问:关于代理被系统监听的疑问

### ISSUE THREAD

**Issue by wangyifan349** [2dust/v2rayNG#1538]
我想问一下安卓手机尤其是中国的手机当中,如果浏览器和v2ray之间使用明文传输,是不是可以被监听？？？？？？？？(我个人认为可以,否则kill switch这种功能似乎不能实现就是因为能看到通信流量才能实现拦截),这么做不太好吧严重泄露隐私,先不说v2rayNG不支持https over dns这本身就很不安全,普通浏览内容我相信安卓手机肯定能通过中间人的方法看到URL。

希望改进如下
1、加入https over dns功能
2、加入ssl代理
3、对于windows设置代理时将socks,一起设置了http/https

我个人是v2ray/xray的铁粉,但是感觉安全问题待增强,实在不行就出两个版本一个安全版一个普通版.......

**Comment by wangyifan349** [comment]
仅仅是个人猜想,我没有证据,但是我很担心和怀疑.....

**Comment by ghost** [comment]
莫名其妙的issue，有被笑到。

ng是基于xray-core，而xray本身支持doh和doq，你连个doh的地址都不会填就来说不支持doh，不是真傻？而且doh我知道，hod是什么？

还有，v2ray/xray铁粉能问出这种问题有震惊到我，这些不应该是老王vpn用户才能问出来的吗

**Comment by wangyifan349** [comment]
> 莫名其妙的issue，有被笑到。
> 
> ng是基于xray-core，而xray本身支持doh和doq，你连个doh的地址都不会填就来说不支持doh，不是真傻？而且doh我知道，hod是什么？
> 
> 还有，v2ray/xray铁粉能问出这种问题有震惊到我，这些不应该是老王vpn用户才能问出来的吗

![v2rayNG配置的安全dns](https://user-images.githubusercontent.com/86041125/172083626-96386f9d-6a52-44c6-9174-9b0d66617616.jpg)
![抓取到dns查询域名](https://user-images.githubusercontent.com/86041125/172083633-d4e91e29-6df4-4a2e-b45f-52d21ed7c17a.PNG)

**Comment by wangyifan349** [comment]
![windows开启移动热点](https://user-images.githubusercontent.com/86041125/172083681-d0fe8164-3724-4214-b28a-52a51a3bc336.PNG)

**Comment by wangyifan349** [comment]
火狐android的about:config中的network.trr.mode改为0了，然后其他如上面配置所示，访问Youtube主页。

**Comment by wangyifan349** [comment]
这边看到了???这边wireshark抓包看到了，什么情况??????
能否解释下?

**Comment by wangyifan349** [comment]
这个服务器是支持udp的.............

**Comment by atlanticfirst** [comment]
系统监听你,你流量加密有个屁用,信息安全十大法则第一条就是如果电脑你给别人用上了,这电脑就不属于你了,系统层要是有后门,你干脆还是别用了.手机浏览器和vray之间流量加密,和中毒电脑走https自欺欺人有什么区别

**Comment by bhuangzhe** [comment]
> socks,一起设置了http/https



> 我想问一下安卓手机尤其是中国的手机当中,如果浏览器和v2ray之间使用明文传输,是不是可以被监听？？？？？？？？(我个人认为可以,否则kill switch这种功能似乎不能实现就是因为能看到通信流量才能实现拦截),这么做不太好吧严重泄露隐私,先不说v2rayNG不支持https over dns这本身就很不安全,普通浏览内容我相信安卓手机肯定能通过中间人的方法看到URL。
> 
> 希望改进如下 1、加入https over dns功能 2、加入ssl代理 3、对于windows设置代理时将socks,一起设置了http/https
> 
> 我个人是v2ray/xray的铁粉,但是感觉安全问题待增强,实在不行就出两个版本一个安全版一个普通版.......

看来兄弟有点底子哦，我建议浏览器再加个插件，防止WebRTC泄露本机IP
