### ISSUE TITLE
配置默认有没有加密？

### ISSUE THREAD

**Issue by epubreader** [2dust/v2rayNG#1540]
手机上其他程序APP是不是能读取V2ray配置，然后上传？
那安卓手机的配置有没有加密， 不加密不是一下就知道了？

**Comment by yuhan6665** [comment]
app 有沙盒

**Comment by epubreader** [comment]
> app 有沙盒

安卓没有sandbox, 什么程序都能读到

**Comment by CatGuai** [comment]
> > app 有沙盒
> 
> 安卓没有sandbox, 什么程序都能读到

安卓当然有沙盒，安卓APP最常用的几个位置：
/data/data/<包名>/
/data/user/<用户ID>/<包名>/
/storage/emulated/<用户ID>/Android/data/<包名>/
/storage/emulated/<用户ID>/
1、2都是APP专属沙盒空间；
在安卓11+上，1、2、3都是APP专属沙盒空间；
4是<内置存储空间>，属于授权存储权限后任何APP都可读取的位置，但也基本没有APP会傻到在公共存储空间存放配置文件。

**Comment by epubreader** [comment]
> 

如果是系统预装的具有root权限的，能不能读到配置文件？

**Comment by yuhan6665** [comment]
系统预装的 app 确实有一些更高权限 但仍然低于 root 不能读沙盒
root 可以读沙盒
