### ISSUE TITLE
ss-2022,  ng连不上，

### ISSUE THREAD

**Issue by PanHsin** [2dust/v2rayNG#1541]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

xray server配置
 config.json：
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "warning",
    "dnsLog": true
  },
  "inbounds": [
    {
      "port": 1235,
      "protocol": "shadowsocks",
      "settings": {
        "method": "2022-blake3-aes-128-gcm",
        "password": "O1hvO9ynXKNOmIH9Edu5v1O1fgRMBYhbVv+BbddrPsU=",
        "network": "tcp,udp"
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ]
}

客户端配置，ng和n完全一样。

客户端配置的链接： ss://MjAyMi1ibGFrZTMtYWVzLTEyOC1nY206TzFodk85eW5YS05PbUlIOUVkdTV2MU8xZmdSTUJZaGJWditCYmRkclBzVT0=@1.2.3.4:1235#ss-blake

类似的 问题 
https://github.com/2dust/v2rayNG/issues/1529 

测试连接提示 io: read/write on closed pipe

安卓端 1.7.9(或10或11)版  使用shadowsocks 2022 ，软件中的logcat提示：
app/proxyman/outbound: failed to process outbound traffic > read tcp *.*.*.*:48536->*.*.*.*:1235: read: connection reset by peer
measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe

虽然有说“”目前问题是在 ng 的真链接测试 有大约80%的几率测试失败 不过应该不影响使用“”
**实际安卓端没法正常连接**。

换了sagernet似乎也不行。

但在windows端,5.25版本，同一网络，无论是宽带或流量网，都可正常连接。

### 预期行为
描述你认为应该发生什么
安卓端应可正常连接。
### 实际行为
描述实际发生了什么

实际上 安卓端没法使用。连不上。打不开网页

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
日志文件

[logcat-ss-blake.txt](https://github.com/2dust/v2rayNG/files/8845558/logcat-ss-blake.txt)
</details>

### 环境信息
MIUI eu 版 12.0.6
安卓 10
mi 9


VPN模式 
![image](https://user-images.githubusercontent.com/26317972/172193826-10348f73-bef9-482c-ba23-cc8107649c07.png)
![image](https://user-images.githubusercontent.com/26317972/172193854-963dca19-67af-4496-a73b-acb2ece8b9a7.png)
![image](https://user-images.githubusercontent.com/26317972/172193878-ab0e4e35-f495-4be6-9378-f090f4f9d091.png)

### 额外信息（可选）

**Comment by yuhan6665** [comment]
你遇到的这个情况应该是服务器的问题 目前 ss 2022 处于试用阶段 有问题不奇怪 你的服务器版本~~和配置~~和日志贴一下
对一下时间看看？

**Comment by chika0801** [comment]
5.注意

因为有[重放保护](https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/ss-2022/2022-1-shadowsocks-2022-edition.md#314-replay-protection)机制，客户端与服务器端的时间差要在[30秒](https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/ss-2022/2022-1-shadowsocks-2022-edition.md#313-header)以内。
同步时间命令

apt install -y ntpdate && ntpdate pool.ntp.org

**Comment by PanHsin** [comment]
服务器核心版本，
xray 1.5.6 或1.5.7

时间同步过了，北京时间。
没用。

 vps上，安卓端的连接日志看不到。

访问或错误的实时日志没有。
pc端连接正常，日志正常显示。

**Comment by PanHsin** [comment]
开启debug级日志，发现时间误差为67s
同步两端时间后，正常了。

**Comment by chika0801** [comment]
> 开启debug级日志，发现时间误差为67s 同步两端时间后，正常了。

那关了这个iss吧
