### ISSUE TITLE
导入Hysteria配置文件直接崩溃

### ISSUE THREAD

**Issue by brooks-li** [2dust/v2rayNG#1543]
### 复现方法
1.复制Hysteria配置文件
2.添加自定义配置，从剪切板导入自定义配置
3.程序直接崩溃，崩溃后再也打不开

### 环境信息
小米10、MIUI13.0.4、安卓12
v2RayNG版本1.7.8、1.7.11

### 额外信息（可选）
崩溃后桌面图标菜单可用，能正常开启服务，而且能服务正常使用

**Comment by 2dust** [comment]
不支持
