### ISSUE TITLE
增加一个分应用计数功能吧，求求了！！

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1544]
#1319
#1517

手机都会经常安装或卸载各种app，所以[分应用代理]真的会用得比较频繁，加一个统计勾选了多少app的计数功能可以一目了然，而不用每次安装或卸载app的时候都要点进去一个个的数看对不对，这样其实也是为了后续使用的一劳永逸，真的很有必要呀，求求大佬加上吧，拜托了😭😭

**Comment by dbthinking** [comment]
增加了计数功能，用户也未必能记住这个数字来做判断。就算数字正确，可能还需要点进去确认下是否被勾选才靠谱。
如果能把新增app显示在分应用代理列表的前面，或者增加“按照安装时间排序”的功能，能更好解决这种新安装app开启代理的需求，在一堆app里寻找和搜索（主要是包名有些变化）确实都相对麻烦。

**Comment by dbthinking** [comment]
> #1319 #1517
> 
> 手机都会经常安装或卸载各种app，所以[分应用代理]真的会用得比较频繁，加一个统计勾选了多少app的计数功能可以一目了然，而不用每次安装或卸载app的时候都要点进去一个个的数看对不对，这样其实也是为了后续使用的一劳永逸，真的很有必要呀，求求大佬加上吧，拜托了😭😭

@real362865 

增加了计数功能，用户也未必能记住这个数字来做判断。就算数字正确，可能还需要点进去确认下是否被勾选才靠谱。
如果能把新增app显示在分应用代理列表的前面，或者增加“按照安装时间排序”的功能，能更好解决这种新安装app开启代理的需求，在一堆app里寻找和搜索（主要是包名有些变化）确实都相对麻烦。

**Comment by whp98** [comment]
感觉应该增加一个自动检测新装应用的功能

**Comment by yuhuazhu** [comment]
你应该要个排序功能，新安装的包在最上面，你一看就知道了
