### ISSUE TITLE
安卓12下拉菜单点击后无法快速连接

### ISSUE THREAD

**Issue by DeicideBuster** [2dust/v2rayNG#1546]
如题

**Comment by chika0801** [comment]
早就像这样了。

具体点，你手机第一次开机，点快捷按钮启动不起的。

你进v2rayng程序，再去开关按钮，就得行。

原因不详，也不影响用，自己知道就是了。

我是小米 安卓12 xiaomi.eu的ROM

**Comment by yuhan6665** [comment]
@chika0801 我的 pixel 好像没问题 你们看一下应用设置里面的电池优化 启动限制啥的

**Comment by chika0801** [comment]
> @chika0801 我的 pixel 好像没问题 你们看一下应用设置里面的电池优化 启动限制啥的

小米 手机 把v2rayng的后台限制  改成无限制 就解决了。3qu
