### ISSUE TITLE
用v2rayNG 扫 v2rayN 生成的二维码，生成的节点配置有问题

### ISSUE THREAD

**Issue by GeorgeRudd** [2dust/v2rayNG#1549]
https://github.com/XTLS/Xray-examples/tree/main/Shadowsocks-2022
v2rayN 里添加一个 Shadowsocks-2022（多用户）节点 ，密码是 server psk:user psk，但是用v2rayNG 扫二维码，手机上生成的配置，密码只有server psk:，没有user psk，需要手动加上

**Comment by yuhan6665** [comment]
Fixed in https://github.com/2dust/v2rayNG/pull/1555
