### ISSUE TITLE
4.7新增QUIC传输方式,请尽快支持吧!

### ISSUE THREAD

**Issue by wysnxzm** [2dust/v2rayNG#155]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by trivita** [comment]
支持

**Comment by jeremy125** [comment]
> 支持

是如何支持的呢？我扫描WINDOWS版v2rayN客户端分享的二维码，或者URL，在v2rayNG客户端中始终将quic协议识别为TCP。而手动输入VMESS服务器信息时，并没有quic协议可选。
quic在WINDOWS客户端v2rayN中是支持的，可以正常使用。

**Comment by trivita** [comment]
@2dust 不知道这个啥时候能支持？
