### ISSUE TITLE
kcp功能无法正常使用

### ISSUE THREAD

**Issue by ileeoyo** [2dust/v2rayNG#155]
### 预期行为
kcp,伪装bt，同时开启了动态端口，无法正常使用。连接不上

### 实际行为
描述实际发生了什么

### 复现方法
1.最开始使用kcp，可以正常连接使用
2.后来开启了伪装bt，和动态端口，目前无法正常使用
3.同配置电脑正常，手机端bifrostv正常

**Comment by 2dust** [comment]
我们已经放弃kcp了，你也放弃吧

**Comment by sunqb** [comment]
> 我们已经放弃kcp了，你也放弃吧

耿直boy
