### ISSUE TITLE
“删除无效配置（先测试）”的功能改进建议

### ISSUE THREAD

**Issue by z999000** [2dust/v2rayNG#1550]
现在每次删除无效配置，必须先点击**测试全部配置真连接**，再次点击**删除无效配置（先测试）**。事实上是点了2次（最少）。
能不能改成一次成功，即：“**测试链接并删除无效配置**”。

如果更进一步，改成：“**更新订阅后测试并删除无效配置**”

**Comment by dbthinking** [comment]
“删除无效配置”的功能设计并不妥善，因为会存在IP被封然后又解封、域名不能解析然后又能解析的情况，就这样删除配置然后再加回来其实挺麻烦的。
产品优化建议：“测试所有链接并**标记无效配置**”，接下来的选项就是“删除被标记的无效配置（加上**二次确认**更好）”，用户也可以在连接测速后自动或手动标记无效配置（删除需求不是很有必要）。

**Comment by dbthinking** [comment]
> 现在每次删除无效配置，必须先点击**测试全部配置真连接**，再次点击**删除无效配置（先测试）**。事实上是点了2次（最少）。 能不能改成一次成功，即：“**测试链接并删除无效配置**”。
> 
> 如果更进一步，改成：“**更新订阅后测试并删除无效配置**”

@cd6003  
“删除无效配置”的功能设计并不妥善，因为会存在IP被封然后又解封、域名不能解析然后又能解析的情况，就这样删除配置然后再加回来其实挺麻烦的。
产品优化建议：“测试所有链接并**标记无效配置**”；接下来的选项就是“删除被标记的无效配置（加上**二次确认**更好）”，用户也可以在连接测速后自动或手动标记无效配置（删除配置的需求不是很有必要）。

**Comment by z999000** [comment]
> > 现在每次删除无效配置，必须先点击**测试全部配置真连接**，再次点击**删除无效配置（先测试）**。事实上是点了2次（最少）。 能不能改成一次成功，即：“**测试链接并删除无效配置**”。
> > 如果更进一步，改成：“**更新订阅后测试并删除无效配置**”
> 
> @cd6003 “删除无效配置”的功能设计并不妥善，因为会存在IP被封然后又解封、域名不能解析然后又能解析的情况，就这样删除配置然后再加回来其实挺麻烦的。 产品优化建议：“测试所有链接并**标记无效配置**”；接下来的选项就是“删除被标记的无效配置（加上**二次确认**更好）”，用户也可以在连接测速后自动或手动标记无效配置（删除配置的需求不是很有必要）。

@dbthinking 
谢回复。
1、现在的情况是，既然有了 **删除无效配置(先测试)** 这个按钮，这个明显是要求：“先测试再删除”，但是要分2步。为什么不放在一起，做一个“测试并删除无效配置”的按钮，不是更好吗，也和原来的按钮一个意思，还减少一步操作。
2、不知道其他人怎么用V2rayNG的。对我而言，就是订阅了某个地址，然后每天更新一下。所以没有需求把删除的配置再加回来。正常情况下，每天都会更新一下服务器。（因为被封的情况太普遍了）。这时，就希望可以有 **更新订阅-测试-删除无效配置** 这样一个一条龙的按钮。^_^。

**Comment by xuefer** [comment]
建议增加”未测试“状态，对于未测试的也别删除，只有测试了超时了才算无效设置
