### ISSUE TITLE
shadowsocks新加密算法XChaCha系列支持

### ISSUE THREAD

**Issue by orz12** [2dust/v2rayNG#1552]
V2rayN已经支持了xchacha20-poly1035和xchacha20-ieft-poly1035，该算法可以降低随机数重用的安全隐患，希望v2rayNG可以抽空补充一下~辛苦啦☺

**Comment by BelieveDa** [comment]
测试ss节点中 Xchacha20-poly1305 算法的 不完全适配 比如手机打开twitter 部分信息不加载 比如图片 头像等

**Comment by 2dust** [comment]
> 

这是core的行为，可以提交log给core

**Comment by BelieveDa** [comment]
明白了
还有一句废话 我v2rayn 用的也是Xray  没问题 为什么NG会出问题
