### ISSUE TITLE
Releases 1.7.11 小米9安卓11 mui12.56

### ISSUE THREAD

**Issue by ChinaParrot** [2dust/v2rayNG#1554]
![RC$1$ }TXF9IV UI10`0YRJ](https://user-images.githubusercontent.com/14269139/174435463-2db78d19-ec0a-43f3-b1f5-603e8b6ce7b4.jpg)

**Comment by yuhan6665** [comment]
可能是架构错了 建议下载39mb的完整版

**Comment by Cirooo** [comment]
> 

pixel 2，lineageOS 19/android 12. 下载39M的那个也提示appear to be not invalid. 是不是sdk没加入android 12？

**Comment by yuhan6665** [comment]
检查安装包是否完整

**Comment by ChinaParrot** [comment]
下载完整版本没有问题了，谢谢
