### ISSUE TITLE
期望ss2022分享链接能与之前保持相同策略

### ISSUE THREAD

**Issue by FranzKafkaYu** [2dust/v2rayNG#1557]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
按照SS2022之前的url scheme生成的ss2022可以被v2rayNG识别

### 实际行为

无法被识别

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

我看了之前的issue好像是SS2022新的url scheme导致，但是能否兼容ss2022之前的url分享策略呢？本身都属于shadowsocks，两套分享策略确实有点麻烦

**Comment by 2dust** [comment]
https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme

你说的很有道理，应该使用一套方案比较好。 
但是2022的新的分享是上游定的，你去提下意见

**Comment by FranzKafkaYu** [comment]
> https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme
> 
> 你说的很有道理，应该使用一套方案比较好。 但是2022的新的分享是上游定的，你去提下意见

咨询了社区的成员，本身在之前的设计中base64加密是可选项，而完全以明文呈现的链接形式则是一直存在的。不知道v2rayNG/v2rayN会采取怎样的策略，会优先以明文的形式去解析吗？

**Comment by 2dust** [comment]
> > https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme
> > 你说的很有道理，应该使用一套方案比较好。 但是2022的新的分享是上游定的，你去提下意见
> 
> 咨询了社区的成员，本身在之前的设计中base64加密是可选项，而完全以明文呈现的链接形式则是一直存在的。不知道v2rayNG/v2rayN会采取怎样的策略，会优先以明文的形式去解析吗？

先判断是否明文（是否存在冒号:）,否再用base64解密再次处理

**Comment by FranzKafkaYu** [comment]
> > > https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme
> > > 你说的很有道理，应该使用一套方案比较好。 但是2022的新的分享是上游定的，你去提下意见
> > 
> > 
> > 咨询了社区的成员，本身在之前的设计中base64加密是可选项，而完全以明文呈现的链接形式则是一直存在的。不知道v2rayNG/v2rayN会采取怎样的策略，会优先以明文的形式去解析吗？
> 
> 先判断是否明文（是否存在冒号:）,否再用base64解密再次处理

我理解一下，相当于先判断是否为明文，如果非明文则按照base64解码，解码后得到method，判断method是否为2022新的cipher，如果为新的cipher则认为属于无效链接，如果为旧的cipher，其他配置欧克的话就能正常导入配置，是这样吗

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/blob/dd65c3fcaa75db9c51d2fd4e2f39b5bed13bedfb/v2rayN/v2rayN/Handler/ShareHandler.cs#L598

**Comment by FranzKafkaYu** [comment]
> https://github.com/2dust/v2rayN/blob/dd65c3fcaa75db9c51d2fd4e2f39b5bed13bedfb/v2rayN/v2rayN/Handler/ShareHandler.cs#L598

Get, thx ~

**Comment by FranzKafkaYu** [comment]
> https://github.com/2dust/v2rayN/blob/dd65c3fcaa75db9c51d2fd4e2f39b5bed13bedfb/v2rayN/v2rayN/Handler/ShareHandler.cs#L598

您好，经过测试，目前的1.7.13版本无法识别老的shadowsocks链接，但是确实可以识别全明文的ss2022的链接，还请看看呢
示例url：
SS2022:

ss://2022-blake3-aes-256-gcm:7E7MsZNzHQZmCBftqzGlAKzxD0DNFe08urJJeAQ5krrF@127.0.0.1:40083#shadowsocks2022

SS old（AES_256_GCM）：ss://YWVzLTI1Ni1nY206NXRDNVRRVllsbVVGTTNQVkpVSFdrUGx2VnNYVzFCWmM2SXZjQUtVMzAzWW9AMTI3LjAuMC4xOjQ4OTkw#shadowscos

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/pull/1563
感谢大佬提供用例

> > https://github.com/2dust/v2rayN/blob/dd65c3fcaa75db9c51d2fd4e2f39b5bed13bedfb/v2rayN/v2rayN/Handler/ShareHandler.cs#L598
> 
> 您好，经过测试，目前的1.7.13版本无法识别老的shadowsocks链接，但是确实可以识别全明文的ss2022的链接，还请看看呢 示例url： SS2022:
> 
> ss://2022-blake3-aes-256-gcm:7E7MsZNzHQZmCBftqzGlAKzxD0DNFe08urJJeAQ5krrF@127.0.0.1:40083#shadowsocks2022
> 
> SS old（AES_256_GCM）：ss://YWVzLTI1Ni1nY206NXRDNVRRVllsbVVGTTNQVkpVSFdrUGx2VnNYVzFCWmM2SXZjQUtVMzAzWW9AMTI3LjAuMC4xOjQ4OTkw#shadowscos

**Comment by FranzKafkaYu** [comment]
最新的pre release版本已支持
