### ISSUE TITLE
任何节点都无法连接至谷歌商店

### ISSUE THREAD

**Issue by Beanstalk0310** [2dust/v2rayNG#1558]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
连上谷歌商店，并且正常下载，更新软件

### 实际行为
描述实际发生了什么
无论哪个节点都连接不上谷歌商店，甚至还出现了裸连谷歌商店并且正常下载的情况
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by FranzKafkaYu** [comment]
plus +1,最新的 pre release版本存在不少问题，希望开发团队可以解决一下
