### ISSUE TITLE
希望加入ARP劫持功能和代理USB 热点分享网络

### ISSUE THREAD

**Issue by daiaji** [2dust/v2rayNG#156]
开了V2ray 热点共享网络无效 直接无连接 只能本机用
ARP劫持是fqrouter2提供的梯子分享方案
通过ARP劫持把局域网网络流量劫持到本机 来处理某些没法设置代理的情境（比如开机google激活 或者你急需让你局域网的某台机子上外网）
fqrouter2还弄了套方案是手机上实现WDS（这个姑且不提）

**Comment by 2dust** [comment]
自行解决,无能为力

**Comment by daiaji** [comment]
@2dust API不支持？

**Comment by 2dust** [comment]
是我没有这个技术能力解决

**Comment by daiaji** [comment]
@2dust fqrouter2那边也没开源他的方法 就是很蛋疼

**Comment by qiuqiuuuu** [comment]
Check out this.
https://play.google.com/store/apps/details?id=be.mygod.vpnhotspot
