### ISSUE TITLE
更新订阅无法识别trojan

### ISSUE THREAD

**Issue by SoulGuardianZ** [2dust/v2rayNG#1561]
通关剪切板可以导入trojan的节点，也能使用，但更新订阅的时候却识别不出来

怎么解决？感谢

**Comment by 2dust** [comment]
给出订阅链接中的trojan用例
或发订阅到邮箱captainIronng@protonmail.com

**Comment by SoulGuardianZ** [comment]
问题已解决，详情见下方
https://github.com/2dust/v2rayNG/issues/1567#issuecomment-1168156363
