### ISSUE TITLE
今天好像突然都无法穿墙了

### ISSUE THREAD

**Issue by oodzchen** [2dust/v2rayNG#1564]
可以正常更新订阅，也可以测试全部配置真连接，可以连接成功，但是浏览器无法翻墙，点击下边的测试ping值会卡住没有返回。

日志如下
> 06-25 12:55:30.421 I/GoLog   (26233):  Port: 8321
06-25 12:55:30.421 I/GoLog   (26233):  IPs: [120.241.236.201]
06-25 12:55:30.429 D/com.v2ray.ang(26233): [/data/app/~~Z_c9SBZNaQU7V-Du_ZX9qw==/com.v2ray.ang-cPomwWocf5PcQRxDBXY9Yg==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
06-25 12:55:30.432 D/com.v2ray.ang(26233): Process[pid=26618, hasExited=false]
06-25 12:55:30.432 D/com.v2ray.ang(26233): /data/user/0/com.v2ray.ang/files/sock_path
06-25 12:55:30.451 I/tun2socks(26618): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
06-25 12:55:30.482 D/com.v2ray.ang(26233): sendFd tries: 0
06-25 12:55:30.483 I/tun2socks(26618): NOTICE(tun2socks): entering event loop
06-25 12:55:30.506 I/GoLog   (26233): Not Using Prepared: tcp,52.81.169.54:5229
06-25 12:55:30.507 I/GoLog   (26233): tcp:127.0.0.1:36522 accepted tcp:52.81.169.54:5229 [direct]
06-25 12:55:31.473 I/GoLog   (26233): Not Using Prepared: tcp,26.26.26.2:853
06-25 12:55:31.474 I/GoLog   (26233): tcp:127.0.0.1:36526 accepted tcp:26.26.26.2:853 [direct]
06-25 12:55:48.068 I/GoLog   (26233): 127.0.0.1:43771 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:48.071 I/GoLog   (26233): DNS accepted udp:8.8.8.8:53 [proxy]
06-25 12:55:48.104 I/GoLog   (26233): Using Prepared: 120.241.236.201
06-25 12:55:48.243 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:55:48.244 I/GoLog   (26233): tcp:127.0.0.1:36544 accepted tcp:172.217.194.99:443 [direct]
06-25 12:55:50.647 I/GoLog   (26233): 127.0.0.1:39595 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:50.829 I/GoLog   (26233): 127.0.0.1:53647 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:50.843 I/GoLog   (26233): Not Using Prepared: tcp,13.225.103.91:443
06-25 12:55:50.844 I/GoLog   (26233): tcp:127.0.0.1:36552 accepted tcp:13.225.103.91:443 [direct]
06-25 12:55:50.844 I/GoLog   (26233): tcp:127.0.0.1:36554 accepted tcp:13.225.103.91:443 [direct]
06-25 12:55:50.845 I/GoLog   (26233): Not Using Prepared: tcp,13.225.103.91:443
06-25 12:55:50.969 I/GoLog   (26233): Not Using Prepared: tcp,20.205.243.166:443
06-25 12:55:50.972 I/GoLog   (26233): tcp:127.0.0.1:36562 accepted tcp:20.205.243.166:443 [direct]
06-25 12:55:51.246 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.147:443
06-25 12:55:51.246 I/GoLog   (26233): tcp:127.0.0.1:36568 accepted tcp:172.217.194.147:443 [direct]
06-25 12:55:51.730 I/GoLog   (26233): 127.0.0.1:50050 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:51.733 I/GoLog   (26233): 127.0.0.1:54802 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:51.984 I/GoLog   (26233): 127.0.0.1:45520 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:51.989 I/GoLog   (26233): Not Using Prepared: tcp,185.199.108.133:443
06-25 12:55:51.994 I/GoLog   (26233): tcp:127.0.0.1:36574 accepted tcp:185.199.108.133:443 [direct]
06-25 12:55:51.994 I/GoLog   (26233): 127.0.0.1:42482 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:52.005 I/GoLog   (26233): Not Using Prepared: tcp,185.199.109.154:443
06-25 12:55:52.006 I/GoLog   (26233): tcp:127.0.0.1:36578 accepted tcp:185.199.109.154:443 [direct]
06-25 12:55:54.253 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.105:443
06-25 12:55:54.253 I/GoLog   (26233): tcp:127.0.0.1:36586 accepted tcp:172.217.194.105:443 [direct]
06-25 12:55:54.385 I/GoLog   (26233): 127.0.0.1:47875 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:54.436 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 101 Err: connection timed out
06-25 12:55:54.437 I/GoLog   (26233): Not Using Prepared: tcp,26.26.26.2:853
06-25 12:55:54.828 I/GoLog   (26233): Not Using Prepared: tcp,34.120.208.123:443
06-25 12:55:54.828 I/GoLog   (26233): tcp:127.0.0.1:36594 accepted tcp:34.120.208.123:443 [direct]
06-25 12:55:55.186 I/GoLog   (26233): 127.0.0.1:45780 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:55:55.445 I/GoLog   (26233): Not Using Prepared: tcp,52.27.117.254:443
06-25 12:55:55.446 I/GoLog   (26233): tcp:127.0.0.1:36600 accepted tcp:52.27.117.254:443 [direct]
06-25 12:55:56.929 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:55:56.929 I/GoLog   (26233): tcp:127.0.0.1:36606 accepted tcp:172.217.194.99:443 [direct]
06-25 12:55:57.076 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:55:57.076 I/GoLog   (26233): tcp:127.0.0.1:36612 accepted tcp:172.217.194.99:443 [direct]
06-25 12:55:57.211 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:55:57.211 I/GoLog   (26233): tcp:127.0.0.1:36618 accepted tcp:172.217.194.99:443 [direct]
06-25 12:55:57.245 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:55:57.246 I/GoLog   (26233): tcp:127.0.0.1:36624 accepted tcp:172.217.194.99:443 [direct]
06-25 12:55:57.258 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.106:443
06-25 12:55:57.258 I/GoLog   (26233): tcp:127.0.0.1:36630 accepted tcp:172.217.194.106:443 [direct]
06-25 12:55:57.793 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:55:57.793 I/GoLog   (26233): tcp:127.0.0.1:36636 accepted tcp:172.217.194.99:443 [direct]
06-25 12:56:00.274 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.103:443
06-25 12:56:00.275 I/GoLog   (26233): tcp:127.0.0.1:36642 accepted tcp:172.217.194.103:443 [direct]
06-25 12:56:02.884 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 95 Err: connection timed out
06-25 12:56:02.885 I/GoLog   (26233): Not Using Prepared: tcp,26.26.26.2:853
06-25 12:56:03.287 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.104:443
06-25 12:56:03.287 I/GoLog   (26233): tcp:127.0.0.1:36650 accepted tcp:172.217.194.104:443 [direct]
06-25 12:56:04.899 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:04.901 I/GoLog   (26233): tcp:127.0.0.1:36656 accepted tcp:172.217.194.99:443 [direct]
06-25 12:56:05.051 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:05.051 I/GoLog   (26233): tcp:127.0.0.1:36662 accepted tcp:172.217.194.99:443 [direct]
06-25 12:56:05.901 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:05.902 I/GoLog   (26233): tcp:127.0.0.1:36668 accepted tcp:172.217.194.99:443 [direct]
06-25 12:56:06.297 I/GoLog   (26233): 127.0.0.1:47558 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:56:10.971 I/com.v2ray.ang(29277): Settings ViewModel is cleared
06-25 12:56:11.266 I/com.v2ray.ang(29277): Background concurrent copying GC freed 289175(11MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7527KB/14MB, paused 203us,81us total 117.596ms
06-25 12:56:19.782 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 98 Err: connection timed out
06-25 12:56:19.782 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:22.597 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 110 Err: connection timed out
06-25 12:56:22.597 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.147:443
06-25 12:56:25.669 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 113 Err: connection timed out
06-25 12:56:25.670 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.105:443
06-25 12:56:25.925 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 101 Err: connection timed out
06-25 12:56:26.026 I/GoLog   (26233): Not Using Prepared: tcp,26.26.26.2:853
06-25 12:56:28.484 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 122 Err: connection timed out
06-25 12:56:28.484 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 120 Err: connection timed out
06-25 12:56:28.484 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:28.485 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:28.600 I/com.v2ray.ang(29277): Background concurrent copying GC freed 372611(14MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 6883KB/13MB, paused 195us,68us total 115.945ms
06-25 12:56:28.741 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 124 Err: connection timed out
06-25 12:56:28.741 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 126 Err: connection timed out
06-25 12:56:28.742 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:28.742 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:28.744 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 128 Err: connection timed out
06-25 12:56:28.744 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.106:443
06-25 12:56:28.766 I/com.v2ray.ang(29277): Settings ViewModel is cleared
06-25 12:56:29.254 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 130 Err: connection timed out
06-25 12:56:29.255 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:30.630 I/GoLog   (26233): 127.0.0.1:59908 accepted udp:8.8.8.8:53 [dns-out]
06-25 12:56:30.791 I/GoLog   (26233): Not Using Prepared: tcp,129.226.106.18:80
06-25 12:56:30.792 I/GoLog   (26233): tcp:127.0.0.1:36706 accepted tcp:129.226.106.18:80 [direct]
06-25 12:56:31.812 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 131 Err: connection timed out
06-25 12:56:31.813 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.103:443
06-25 12:56:34.376 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 94 Err: connection timed out
06-25 12:56:34.478 I/GoLog   (26233): Not Using Prepared: tcp,26.26.26.2:853
06-25 12:56:34.629 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 127 Err: connection timed out
06-25 12:56:34.629 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.104:443
06-25 12:56:36.421 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 129 Err: connection timed out
06-25 12:56:36.421 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 133 Err: connection timed out
06-25 12:56:36.421 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:36.421 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:37.445 I/GoLog   (26233): fdConn unix.Connect err, Close Fd: 135 Err: connection timed out
06-25 12:56:37.445 I/GoLog   (26233): Not Using Prepared: tcp,172.217.194.99:443
06-25 12:56:43.601 I/com.v2ray.ang(29277): Background concurrent copying GC freed 322551(12MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 9045KB/17MB, paused 282us,70us total 111.791ms

**Comment by yuhan6665** [comment]
日志设置成 debug 看一下
服务器日志看一下

**Comment by oodzchen** [comment]
@yuhan6665 这是 debug 日志
<del>v2raynglog.txt<del>

服务器日志看不了，因为是用的别人搭的服务，同样的配置我在 PC 和 iOS 上都能正常使用。

**Comment by yuhan6665** [comment]
看出问题了 你选择了“全局直连”这个预定义规则 这个规则下你要写自定义代理的网站 否则跟没开代理是一样的

**Comment by oodzchen** [comment]
@yuhan6665 好吧确实是我的问题，我把“全局直连”当成是“全局代理”，改了一下就好了

**Comment by yuhan6665** [comment]
没事 记得上传日志的时候要隐去服务器关键信息
