### ISSUE TITLE
订阅中节点名带有“|”就无法识别

### ISSUE THREAD

**Issue by thisthebest** [2dust/v2rayNG#1567]
目前只测试了Trojan，节点名带有“|”的就不会显示出来

**Comment by 2dust** [comment]
无法复现
请给出测试用例

**Comment by SoulGuardianZ** [comment]
你这个情况跟我的一样，把链接的remark部分删掉才识别的出来

**Comment by thisthebest** [comment]
> 无法复现 请给出测试用例

复现例子：
trojan://xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx@8.8.8.8:8888?sni=8.88888.xyz#888
通过粘贴板导入，成功
trojan://xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx@8.8.8.8:8888?sni=8.88888.xyz#888|
通过粘贴板导入，失败。

**Comment by SoulGuardianZ** [comment]
> > 无法复现 请给出测试用例
> 
> 复现例子： trojan://xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx@8.8.8.8:8888?sni=8.88888.xyz#888 通过粘贴板导入，成功 trojan://1348xxxxx-6c39-xxxx-bc20-xxxxxxxx@8.8.8.8:8888?sni=8.88888.xyz#888| 通过粘贴板导入，失败。

我也这样子测试了一下，确实是这样，我之前的更新订阅失败应该就是这个原因了

**Comment by 2dust** [comment]
使用你们给的用例确实是会异常，导入失败。
原因是解析分享使用的是URI函数，如果直接带有“|”则无法被正确解析；
问题在生成分享时，“|”应该要被编码（encodeURIComponent）成%7C，
应该这样的 
`trojan://1348xxxxx-6c39-xxxx-bc20-xxxxxxxx@8.8.8.8:8888?security=tls&sni=8.88888.xyz&type=tcp&headerType=none#888%7C`

现在的解决方案是只能打个死的补丁，把“|”替换成%7C

**Comment by 2dust** [comment]
[v2rayNG_1.7.14test_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8997290/v2rayNG_1.7.14test_arm64-v8a.apk.zip)

使用此版测试

**Comment by thisthebest** [comment]
> [v2rayNG_1.7.14test_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/8997290/v2rayNG_1.7.14test_arm64-v8a.apk.zip)
> 
> 使用此版测试

使用此版本测试，就可以成功订阅出来了！看来确实是这个的问题。

**Comment by 2dust** [comment]
这就是使用这种分享格式的缺点了，当分享的链接不按标准处理数据就会导致兼容问题。
最简单的普遍兼容的方式是 v2rayN 的 [VMess分享 ](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))
不管是什么字符串，不管是否ipv6都能很好的分享；但是有人觉得这种方式丑陋

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.14
