### ISSUE TITLE
红米k40刷的PixelExperience系统，每当使用v2rayng一段时间后就会导致系统特别的卡顿，像慢动作一样，需要断开连接才能恢复

### ISSUE THREAD

**Issue by anxnxs** [2dust/v2rayNG#1570]
红米k40刷的PixelExperience系统，每当使用v2rayng一段时间后就会导致系统特别的卡顿，像慢动作一样，需要断开连接才能恢复

**Comment by SummerAfternoon** [comment]
咦 我也是耶 K40刷的欧版 用了一段时间就卡卡的 卸了换其他的就正常了 然后又下v2rayng又好了😳😅😅😅

**Comment by lawpdas** [comment]
same problem

**Comment by aa77ss55dd** [comment]
你好，你的信件我们已经收到，谢谢。I have received your letter and I will respond to it ASAP.Thank you very much.
