### ISSUE TITLE
1.7.15 doesn't start the service

### ISSUE THREAD

**Issue by Denio-7** [2dust/v2rayNG#1578]
Version 1.7.15 does not start the service. Any protocols (vmess, vless etc) - without results.
Rollback on 1.7.14 - works fine. 

Logcat:
--------- beginning of main
07-04 23:37:24.096 E/com.v2ray.ang(13725): Not starting debugger since process cannot load the jdwp agent.
07-04 23:37:24.192 I/com.v2ray.ang(13725): The ClassLoaderContext is a special shared library.
07-04 23:37:24.195 I/com.v2ray.ang(13725): The ClassLoaderContext is a special shared library.
--------- beginning of system

Redmi Note 7 Pro, Android 10, MIUI 12.0.2 stock.

**Comment by ifconfig2333** [comment]
一样。最新版本 小米 启动不了。。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.16

**Comment by Denio-7** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/1.7.16

Tested. Cool. Thanks for the quick fix!
