### ISSUE TITLE
Cannot start service for multiple user at the same time

### ISSUE THREAD

**Issue by 4piu** [2dust/v2rayNG#158]
### 预期行为
userA started the v2ray with configA, then login as UserB, and start the v2ray with configB. 
The local port should be set automatically if conflict detected, or allow user to set it manually. 

### 实际行为
userA started the v2ray with configA, then login as UserB, service start failed. 
If userB want to use the v2ray, the app must be stopped in userA's session first. 

### 复现方法
1. Start v2ray with userA
2. Login to UserB
3. Attempt to start the v2ray

### 日志信息
<details>

```
11-06 22:10:24.977 14417 14417 I GoLog   : new v2ray core
11-06 22:10:24.988 14417 14417 I GoLog   : start v2ray core
11-06 22:10:24.988 14417 14417 I GoLog   : v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10808 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10808 > listen tcp 127.0.0.1:10808: bind: address already in use
11-06 22:10:24.989 14417 14417 D com.v2ray.ang: go.Universe$proxyerror: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 10808 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:10808 > listen tcp 127.0.0.1:10808: bind: address already in use
```
</details>

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.1.10

**Comment by joshua311** [comment]
What causes services of V2rayNG to fail????

**Comment by joshua311** [comment]
What causes that in that screenshot????
