### ISSUE TITLE
Google Play上的v2rayNG不再推送更新了吗？

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1581]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
GitHub上的最新版本已经更新到了1.7.16

### 实际行为
Google Play上的最新版本还是1.7.4并且会提醒我有应用更新。虽然不影响使用但还是有点碍眼。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
![Screenshot_2022-07-06-23-54-45-476_com v2ray ang](https://user-images.githubusercontent.com/93695718/177593268-c97808bb-bd12-4781-a465-1be1e16e3e7a.jpg)
![Screenshot_2022-07-06-23-55-37-667_com android ve](https://user-images.githubusercontent.com/93695718/177593302-b2426826-2394-419e-ad1d-7d490b09bfef.jpg)

#

**Comment by dwanhy** [comment]
不要安装第一个apk，安装[arm64-v8a.apk]版本。您可以试试。gplay不会提示更新了。

**Comment by ghost** [comment]
> 不要安装第一个apk，安装[arm64-v8a.apk]版本。您可以试试。gplay不会提示更新了。

感谢，我去试试
