### ISSUE TITLE
trojan+grpc，v2ng无法导入ng分享的

### ISSUE THREAD

**Issue by sjnhnp** [2dust/v2rayNG#1583]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
用v2rayng 1.17.5 分享的trojan+grpc的二维码/导出到剪切板/完整配置，v2rayng自己无法导入

### 实际行为
trojan+grpc，ng无法导入自己分享的链接

**Comment by 2dust** [comment]
把分享出来的连接贴出来
