### ISSUE TITLE
每次关机打开时V2rayn无法正常使用

### ISSUE THREAD

**Issue by wei78963** [2dust/v2rayNG#1588]
打开时
![image](https://user-images.githubusercontent.com/109010318/178129938-b154d1f9-f9e8-4557-b75c-5319c8518bb6.png)
测速时
![image](https://user-images.githubusercontent.com/109010318/178129960-04ca8e68-50a6-4d19-b447-10bc425da794.png)

**Comment by chika0801** [comment]
这是NG，你发错地方了

**Comment by ghost** [comment]
为什么要把V2rayN放桌面？
