### ISSUE TITLE
关于路由功能的建议

### ISSUE THREAD

**Issue by stw8** [2dust/v2rayNG#159]
目前，v2rayNG的路由功能的使用逻辑混乱。
v2rayNG有三处路由设置。1.导入的配置文件自带的路由设置。2.设置界面可切换的路由设置：全局、绕过XXX等。3.设置界面的自定义路由。
用户完全不知道上述三处的优先级（或是怎样生效），而且也没有相关说明。

再说v2rayNG设置界面的自定义路由，同样逻辑混乱，并且实用性很低。
只有代理、直连、阻止三个大文本框，不知道优先级，不知道名单外的走直连还是代理，不支持正则表达式等高级格式。
自定义路由BiforstV做的就很好，可以参考。

其实大部分用户最常用的，就一个只代理GFWList、一个全局。就算是做技术的不看重用户体验，但是起码能够让用户就算麻烦一些也能够满足自己的需求，然而目前完全就是非常混乱。

最后再补充一点，导入的配置文件不能像手动添加那样编辑（也不知道配置文件里附加的那些配置比如路由配置有没有用）。其实就读取配置文件中的关键设置（手动添加时的那些）就够了，然后就可以像手动添加的那样编辑了。

**Comment by qgtxqj** [comment]
我个人体验是导入配置的路由优先级是最高的，然后是界面上的配置路由，最后才是自定义路由，这些是从上到下排列的，匹配到哪个就用哪个路由。

**Comment by elvisw** [comment]
实在不行，可以考虑提供外置geo文件的支持，比如这个：
https://github.com/ToutyRater/V2Ray-SiteDAT

**Comment by 2dust** [comment]
NG的目标是使用简单,本来是不想加路由的
如果你需要bv那么复杂的路由功能,那只能让你失望了

路由生效规则
1.自定义配置的话,除了分应用外其他设置都失效,路由也就是你自己随便写
2.app生成配置时,自定义的路由排前面,接下来是选择的全局还是绕过大陆
就这样,没有了

**Comment by 2dust** [comment]
不要提什么gfw,pac,acl等等是永远不会加入
我的想法是这些应该交给core处理
