### ISSUE TITLE
shadowsocks超时10秒中断

### ISSUE THREAD

**Issue by llllllllqq** [2dust/v2rayNG#159]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常下载大文件

### 实际行为
下载10秒后自动结束了

### 复现方法
1.链接ss协议节点
2.用chrome下载大文件（https，yandex网盘，地址https://yadi.sk/d/XNd3kso_uS8sEA）
3.10秒后自动结束下载（提示下载完成，实际不完整），换ss官方客户端正常

### 环境信息
miui11 安卓9

### 备注
这个yandex网盘网页版分享页面好像配置有问题，而v2rayng的timeout也有问题导致提前结束下载。kitsunebi和ss官方客户端就可以正常下载不中断。
而下载其它配置正常的网站如vultr测速文件（猜测是设好了timeout和keepalive）用v2rayng没问题。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.1.9
