### ISSUE TITLE
v2rayN 和 v2rayNG 的 wss协议有什么区别吗？

### ISSUE THREAD

**Issue by JarmoHu** [2dust/v2rayNG#1590]
### 预期行为
同样的一个wss协议，PC端v2rayN可以用，安卓端v2rayNG不可以。

**Comment by karafen** [comment]
Hello! The same configuration vless ws+tls+cloudflare cdn doesn't work on v2rayNG client  android, but works on v2rayN client windows, what could be the problem ?

**Comment by JarmoHu** [comment]
vmess + ws + tls, no cloudflare

**Comment by chika0801** [comment]
他们都是给你生成config.json配置文件，生成的内容你可以自己看。

这问题xray群也有老外来问，原来也有国内网友来问。我自己不用vmess ws tls好久了。不清楚原因。

建议不要研究了为什么了，除非你有能力水平时间，换种协议组合。

**Comment by GleenJi** [comment]
肯定哪里搞错了，怎么会一个能用一个不能用，建议把具体配置参数发全
