### ISSUE TITLE
当我在Windows双屏上使用v2rayNG

### ISSUE THREAD

**Issue by iconFehu** [2dust/v2rayNG#1592]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
可以在第一台显示器上发现我创建的服务器

### 实际行为
无法在第一台显示器显示出服务器列表

### 复现方法
1.打开您的电脑
2.连接上另外一台显示器并接通它的电源
3.右键[v2rayNG]选择[服务器]

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

![1658127862859](https://user-images.githubusercontent.com/46149128/179460204-2eb0c955-495a-428e-92a9-021c33a3d94f.png)

**Comment by NMSLOOO** [comment]
是不是问错地方了？

**Comment by chika0801** [comment]
你用的是v2rayN这里是NG，N在隔壁

**Comment by iconFehu** [comment]
谢谢好心人，我溜了
