### ISSUE TITLE
极米Z6投影仪安装v2rayNG成功了，配置也是成功的，测试连接也是通的，但是点击运行闪退

### ISSUE THREAD

**Issue by chenjun1206** [2dust/v2rayNG#1596]
极米Z6投影仪安装v2rayNG成功了，配置也是成功的，测试连接也是通的，但是点击运行闪退
我分别安装了
v2rayNG_v1.7.4_apkpure.com.apk
v2rayNG_1.6.30.apk
这两个版本，都不行，我还以为是版本的原因，结果还是没有翻墙成功

**Comment by yuhan6665** [comment]
大概是没有 vpn 组件

**Comment by chenjun1206** [comment]
> 大概是没有 vpn 组件

那是不是就不能通过安装软件的方式翻墙了

**Comment by yuhan6665** [comment]
用路由器吧

**Comment by chenjun1206** [comment]
> 用

**Comment by vespersm** [comment]
解决了吗？我也是z6x 各种翻墙软件节点弄好后一连接就闪退

**Comment by chenjun1206** [comment]
只能用软路由了，不能直接用客户端

**Comment by vespersm** [comment]
极米好垃圾

**Comment by SamYangzx** [comment]
遇到同样问题，大佬们解决没

**Comment by renjiwu963** [comment]
我用 安心加速器 可以正常使用  缺点是 要配鼠标 才能点开始
