### ISSUE TITLE
bug: 在更新订阅时滑动服务器列表将导致应用崩溃

### ISSUE THREAD

**Issue by verifyurhuman** [2dust/v2rayNG#1597]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
清空服务器列表并获取新的订阅，提示成功

### 实际行为
应用崩溃：很抱歉，v2rayNG已停止运行

### 复现方法
1. 在列表服务器较多的情况下点击右上角更新订阅
2. 如果在获取新订阅过程中滑动服务器列表，v2rayNG将停止运行

### 日志信息
<details>
无
</details>

### 环境信息
Android 8.1 arm64v8a
### 额外信息（可选）
其实是个不大的问题，主要是个人在更新订阅时习惯滑动服务器列表到顶部，导致老是触发这个bug，以后克制下自己的手。。当然开发者有空的话也可以修一下

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.18

**Comment by verifyurhuman** [comment]
问题解决，感谢 2dust 和 zhaoguomanong
