### ISSUE TITLE
sony手机无法使用

### ISSUE THREAD

**Issue by liCN** [2dust/v2rayNG#16]
xperia performance
硬件版本 F8131
安卓版本  7.1.1
软件版本  0.2.6 google play 版本
故障描述 导入配置后，无法启动，无故障提示，已排除配置问题，使用 def 配置也无法启动

**Comment by liCN** [comment]
这是0.3的Locat

--------- beginning of main
12-02 11:09:51.973 30519 30519 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
12-02 11:09:51.990 30519 30537 I DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
12-02 11:09:51.990 30519 30537 I DynamiteModule: Selected local version of com.google.android.gms.flags
12-02 11:09:51.991 30519 30519 I FirebaseInitProvider: FirebaseApp initialization successful
12-02 11:09:51.993 30519 30537 W System  : ClassLoader referenced unknown path: 
12-02 11:09:52.000 30519 30537 D ApplicationLoaders: ignored Vulkan layer search path /data/app/com.google.android.gms-2/lib/arm64:/system/fake-libs64:/data/app/com.google.android.gms-2/base.apk!/lib/arm64-v8a for namespace 0x7f8610b0f0
12-02 11:09:52.012 30519 30537 W DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
12-02 11:09:52.013 30519 30540 I FA      : App measurement is starting up, version: 11717
12-02 11:09:52.013 30519 30540 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-02 11:09:52.013 30519 30540 I FA      : To enable faster debug mode event logging run:
12-02 11:09:52.013 30519 30540 I FA      :   adb shell setprop debug.firebase.analytics.app com.v2ray.ang
12-02 11:09:52.038 30519 30537 I DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:10
12-02 11:09:52.038 30519 30537 I DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 10
12-02 11:09:52.058 30519 30519 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
12-02 11:09:52.065 30519 30537 W art     : Found duplicate classes, falling back to interpreter mode for /data/user_de/0/com.google.android.gms/app_chimera/m/0000002f/DynamiteModulesC_GmsCore_prodmnc_xxhdpi_release.apk
12-02 11:09:52.066 30519 30537 W art     : Found duplicated class when checking oat files: 'La;' in /data/user_de/0/com.google.android.gms/app_chimera/m/0000002f/DynamiteModulesC_GmsCore_prodmnc_xxhdpi_release.apk and /data/user_de/0/com.google.android.gms/app_chimera/m/0000002b/DynamiteLoader_GmsCore_prodmnc_xxhdpi_release.apk
12-02 11:09:52.076 30519 30519 V BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
12-02 11:09:52.076 30519 30519 V BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
12-02 11:09:52.076 30519 30519 V BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
12-02 11:09:52.079 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2bcbf65
12-02 11:09:52.079 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9cc743a
12-02 11:09:52.100 30519 30537 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000002f/n/arm64-v8a
12-02 11:09:52.104 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@2ffa63
12-02 11:09:52.104 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e49f660
12-02 11:09:52.105 30519 30519 I ViewConfigCompat: Could not find method getScaledScrollFactor() on ViewConfiguration
12-02 11:09:52.116 30519 30537 I FirebaseCrashApiImpl: FirebaseCrashApiImpl created by ClassLoader t[DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000002f/DynamiteModulesC_GmsCore_prodmnc_xxhdpi_release.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000002f/n/arm64-v8a, /system/lib64, /vendor/lib64]]]
12-02 11:09:52.116 30519 30537 I FirebaseCrash: FirebaseCrash reporting loaded - com.google.android.gms.internal.zzdxu@b3346fd
12-02 11:09:52.126 30519 30540 I FA      : Tag Manager is not found and thus will not be used
12-02 11:09:52.128 30519 30538 I DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
12-02 11:09:52.128 30519 30538 I DynamiteModule: Selected local version of com.google.android.gms.flags
12-02 11:09:52.135 30519 30538 W DynamiteModule: Local module descriptor class for com.google.android.gms.crash not found.
12-02 11:09:52.156 30519 30546 I Adreno  : QUALCOMM build                   : 49a2ab3, Ifedc5bd8d0
12-02 11:09:52.156 30519 30546 I Adreno  : Build Date                       : 12/15/16
12-02 11:09:52.156 30519 30546 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
12-02 11:09:52.156 30519 30546 I Adreno  : Local Branch                     : 
12-02 11:09:52.156 30519 30546 I Adreno  : Remote Branch                    : 
12-02 11:09:52.156 30519 30546 I Adreno  : Remote Branch                    : 
12-02 11:09:52.156 30519 30546 I Adreno  : Reconstruct Branch               : 
12-02 11:09:52.163 30519 30546 I OpenGLRenderer: Initialized EGL, version 1.4
12-02 11:09:52.163 30519 30546 D OpenGLRenderer: Swap behavior 1
12-02 11:09:52.167 30519 30538 I FirebaseCrashApiImpl: FirebaseCrash reporting API initialized
12-02 11:09:52.167 30519 30538 I FirebaseCrash: FirebaseCrash reporting initialized com.google.android.gms.internal.zzdxu@b3346fd
12-02 11:09:52.168 30519 30538 D FirebaseCrash: Firebase Analytics Listener for Firebase Crash is initialized
12-02 11:09:52.467 30519 30519 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@921bafb time:670309924
12-02 11:09:52.473 30519 30536 D FirebaseInstanceId: topic sync succeeded
12-02 11:09:53.751 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1736f8a
12-02 11:09:53.897 30519 30519 I Timeline: Timeline: Activity_launch_request id:com.android.vpndialogs time:670311354
12-02 11:09:54.058 30519 30519 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@921bafb time:670311515
12-02 11:09:56.531 30519 30519 W art     : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
12-02 11:09:56.535 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@da93d1d
12-02 11:09:56.535 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@31c0b92
12-02 11:09:59.261 30519 30519 I Timeline: Timeline: Activity_launch_request id:com.v2ray.ang time:670316718
12-02 11:09:59.314 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f68b64a
12-02 11:09:59.314 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e5c59bb
12-02 11:09:59.378 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@58a39a1
12-02 11:09:59.378 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@cefc7c6
12-02 11:09:59.489 30519 30546 D OpenGLRenderer: endAllActiveAnimators on 0x7f63fff800 (MenuPopupWindow$MenuDropDownListView) with handle 0x7f61a3f440
12-02 11:09:59.505 30519 30524 I art     : Do partial code cache collection, code=26KB, data=29KB
12-02 11:09:59.506 30519 30524 I art     : After code cache collection, code=26KB, data=29KB
12-02 11:09:59.506 30519 30524 I art     : Increasing code cache capacity to 128KB
12-02 11:09:59.559 30519 30519 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c2135a7 time:670317017
12-02 11:10:02.142 30519 30519 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@921bafb time:670319599
12-02 11:10:02.787 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5673caa
12-02 11:10:02.787 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@6ecd09b
12-02 11:10:03.480 30519 30519 I Timeline: Timeline: Activity_launch_request id:com.v2ray.ang time:670320938
12-02 11:10:03.543 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@dae592d
12-02 11:10:03.544 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@835de62
12-02 11:10:03.556 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f4fb7dc
12-02 11:10:03.556 30519 30519 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f1e80e5

**Comment by 2dust** [comment]
使用最新版再提供个log

**Comment by liCN** [comment]
目前手机已更新到了 8.0,NG更新到0.3.4
已可以正常使用

--------- beginning of main
12-17 15:11:36.424 I/GoLog   (31785): NoAutoConvert:true VpnConf:<Service:<Target:"/data/data/com.v2ray.ang/tun2socks" Args:"--netif-ipaddr" Args:"26.26.26.2" Args:"--netif-netmask" Args:"255.255.255.0" Args:"--socks-server-addr" Args:"127.0.0.1:10808" Args:"--tunfd" Args:"3" Args:"--tunmtu" Args:"1500" Args:"--sock-path" Args:"/dev/null" Args:"--loglevel" Args:"4" Args:"--enable-udprelay" VPNSetupArg:"m,1500 a,26.26.26.1,24 r,0.0.0.0,0" > PreparedDomainName:<TCPVersion:"tcp4" UDPVersion:"udp4" DomainNameList:"z3ss.eu.org:995" > > RootModeConf:<Scripts:<UpScript:"#none" DownScript:"#none" > > Env:<Vars:<key:"V2RaySocksPort" value:"10808" > > 
12-17 15:11:36.706 I/GoLog   (31785): <nil>
12-17 15:11:36.711 I/GoLog   (31785): 2017/12/17 07:11:36 [Debug]App|Proxyman|Inbound: creating tcp worker on 127.0.0.1:10808
12-17 15:11:36.719 I/GoLog   (31785): Preparing DNS, z3ss.eu.org:995
12-17 15:11:36.719 I/GoLog   (31785): 2017/12/17 07:11:36 [Warning]Core: V2Ray started
12-17 15:11:36.719 I/GoLog   (31785): unforgivenessCloser() <-v.unforgivnesschan
12-17 15:11:42.472 I/GoLog   (31785): (*net.UDPAddr)(0x44219b8120)(165.227.15.187:995)
12-17 15:11:42.585 I/GoLog   (31785): unforgivenessCloser() <-v.unforgivnesschan
12-17 15:11:42.622 I/GoLog   (31785): /data/data/com.v2ray.ang/tun2socks
12-17 15:11:42.624 I/GoLog   (31785): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
12-17 15:11:42.625 I/GoLog   (31785): Waiting....
