### ISSUE TITLE
可不可以只开启http代理，而不要接管系统VPN?

### ISSUE THREAD

**Issue by chinaszq** [2dust/v2rayNG#160]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
手机里同一时候只能有一个VPN服务开启，这便和其它VPN（如广告拦截APP）造成了冲突，可不可以在建立连接的时候，只做http代理，而不接管系统VPN？这样可以通过配置代理功能上网。
谢谢
### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by jsda** [comment]
目前只有ss和tor有这个功能，可以只作本地socks5或http代理，而不接管vpn。



作者辛苦了，希望以后能添加这个功能😉

**Comment by oO0oO0oO0o0o00** [comment]
好主意，也可以用来多层代理。
只不过安卓上这样可能更容易被系统关掉。

**Comment by IceCodeNew** [comment]
附议

**Comment by Landscapelr** [comment]
附议，这样就能和adguard一起使用了

**Comment by jarvanh** [comment]
同样希望可以只开启本地代理，而不接管系统VPN

**Comment by commis** [comment]
建议两种可考虑的方案：
1、支持仅代理模式，可以和adguard一起使用
2、不管是否绕过局域网和国内地址，都使用已配置的远程DNS解析，在DNS服务器上做广告过滤

另外：
    当前界面上的DNS配置感觉过于复杂，建议保留DNS设置开关，开关关闭默认走内部DNS，开关打开走用户自己设定的DNS解析。

**Comment by 1human** [comment]
我说呢。。。。。  现在V2ray+adguard只能是全局的规则，如果开启per-app proxy的话，代理不了所有浏览器的流量。。。。

**Comment by IceCodeNew** [comment]
![image](https://user-images.githubusercontent.com/32576256/85999133-41a08900-ba3e-11ea-89a5-315bf90ab882.png)
如果我没理解错你们的意思，这个功能已经支持了。
你们是不是没升级客户端，还是没注意到这就是你们需要的。

**Comment by 1human** [comment]
> ![image](https://user-images.githubusercontent.com/32576256/85999133-41a08900-ba3e-11ea-89a5-315bf90ab882.png)
> 如果我没理解错你们的意思，这个功能已经支持了。
> 你们是不是没升级客户端，还是没注意到这就是你们需要的。

Android版的好像没有

**Comment by oO0oO0oO0o0o00** [comment]
> 附议



> ![image](https://user-images.githubusercontent.com/32576256/85999133-41a08900-ba3e-11ea-89a5-315bf90ab882.png)
> 如果我没理解错你们的意思，这个功能已经支持了。
> 你们是不是没升级客户端，还是没注意到这就是你们需要的。

噗。。。不记得自己之前的回复了嘛QAQ 这个是安卓用的

**Comment by IceCodeNew** [comment]
哦我混了，尴尬

**Comment by oO0oO0oO0o0o00** [comment]
> 哦我混了，尴尬

摸摸头~~

**Comment by yousiki** [comment]
附议，希望可以同时使用V2rayNG和Adguard

**Comment by Lehmaning** [comment]
附议。

**Comment by yuhan6665** [comment]
Added in #587

**Comment by IceCodeNew** [comment]
> Added in #587

期待这一 PR 尽快被包含在新版本里发布，虽然内核从 `4.27.4` 到 `4.27.5` 的改动不多，但还是值得伴随这样一个重要的功能提升一起发布的。
