### ISSUE TITLE
导入配置文件中的socks端口未被覆写

### ISSUE THREAD

**Issue by arnesacnussem** [2dust/v2rayNG#160]
### 预期行为
导入配置文件中设置了socks端口为8080，导入后应被override为10808
(毕竟这个设置在0.6.2 play版中无法修改)

### 实际行为
本地socks端口仍为8080，所以出现无法连接到127.0.0.1:10808的问题

### 复现方法
1.导入一个socks端口不为10808的配置文件
2.启动服务
3.点击测试连接

**Comment by CoolCollin** [comment]
我也有同样问题： 点击测试，出现如下提示: Fail to detect internet connection: failed to connect to localhost 127.0.0.1 (port 10808) from  /127.0.0.1 (46346）after 30000ms:

**Comment by arnesacnussem** [comment]
> 我也有同样问题： 点击测试，出现如下提示: Fail to detect internet connection: failed to connect to localhost 127.0.0.1 (port 10808) from /127.0.0.1 (46346）after 30000ms:

暂时的解决方法是修改配置文件里的socks端口为10808

**Comment by CoolCollin** [comment]
> > 我也有同样问题： 点击测试，出现如下提示: Fail to detect internet connection: failed to connect to localhost 127.0.0.1 (port 10808) from /127.0.0.1 (46346）after 30000ms:
> 
> 暂时的解决方法是修改配置文件里的socks端口为10808

谢了。我试试看。貌似这个问题在最近几个beta都一直存在。

**Comment by 2dust** [comment]
因为app里面开启了tun2socks,需要指定一个端口
在core没有开启新配置之前，都是由app强制覆盖inbound得到这个10808端口的
现在有新配置了，这样自定义配置的格式可能千奇百怪，强制覆盖inboud会出问题，所以要求用户自己写
inbound 或inbounds中一定要有一个socks端口10808，其他随意

**Comment by arnesacnussem** [comment]
@2dust 也就是说，最好的办法其实是在导入配置文件的时候加个确认框。。。
