### ISSUE TITLE
指定几个应用走全局代理，几个应用走分流，其余的都直连

### ISSUE THREAD

**Issue by hahaleyile** [2dust/v2rayNG#1601]
有些游戏会锁区，像宝可梦大集结会判断你的IP是不是国内的，我希望能将这些应用全局代理，但是又希望很多应用走分流规则。请问现在能否出个方案，让一套应用对应一套规则，default再对应一套规则。

**Comment by Sul999999** [comment]
想做全局代理，哪位大神➕个v

**Comment by yuhan6665** [comment]
Sagernet

**Comment by Sul999999** [comment]
看附件图片，短视频发不了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yuhan6665 ***@***.***&gt;
发送时间: 2022年7月30日 23:04
收件人: 2dust/v2rayNG ***@***.***&gt;
抄送: Sul999999 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [2dust/v2rayNG] 指定几个应用走全局代理，几个应用走分流，其余的都直连 (Issue #1601)





 
Sagernet
