### ISSUE TITLE
v2rayNG can not be used in Anbox

### ISSUE THREAD

**Issue by lixiaodongsql** [2dust/v2rayNG#1602]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
Hello, I can install v2rayNG_1.6.30.apk by the command adb install v2rayNG_1.6.30.apk in Anbox.  
https://anbox.io/
I import a v2ray node which I can normally use in Qv2ray client on Ubuntu 18.04 to v2rayNG_1.6.30
After I connect to the V2ray node through v2rayNG_1.6.30.apk, I can not open any webpage in Anbox.
I run adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main in my Ubuntu 18.04 terminal, below is the partial log.

07-30 06:36:36.598  1697  1697 I GoLog   : loading core config
07-30 06:36:36.598  1697  1718 I GoLog   : Preparing Domain: my v2ray hostname:443
07-30 06:36:36.599  1697  1718 I GoLog   : PrepareDomain err: lookup my v2ray hostname: No address associated with hostname
07-30 06:36:36.606  1697  1697 I GoLog   : new core
07-30 06:36:36.606  1697  1697 I GoLog   : start core
07-30 06:36:36.607  1697  1719 I GoLog   : [Warning] core: Xray 1.5.3 started
07-30 06:36:36.619  1697  1697 D com.v2ray.ang: tun2socks destroy
07-30 06:36:36.619  1697  1697 D com.v2ray.ang: kotlin.UninitializedPropertyAccessException: lateinit property process has not been initialized
07-30 06:36:36.624  1697  1727 I GoLog   : PrepareDomain exit due to core closed

Judging from the log, It seems that v2rayNG_1.6.30.apk can not find my v2ray host name. How to solve this problem? Thank you very much for your help. I really appreciate it.
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
Use ip instead of host

**Comment by lixiaodongsql** [comment]
Should I ping my v2ray host name in https://ping.pe/ to obtain the IP address of my v2ray host name? Thank you so much for your help again.

**Comment by lixiaodongsql** [comment]
I input the iP address of my v2ray host name which I obtained from ping.pe in v2rayNG_1.6.30.apk
I connect to my v2ray node in Anbox through v2rayNG_1.6.30.apk
I still can not open any webpage in Anbox.
I execute the command  adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main in my Ubuntu 18.04 terminal

Below is my partial log

07-31 04:54:03.800  1243  1243 I GoLog   : loading core config
07-31 04:54:03.801  1243  1264 I GoLog   : Preparing Domain: IP address of my v2ray host name:443
07-31 04:54:03.801  1243  1264 I GoLog   : Prepare Result:
07-31 04:54:03.801  1243  1264 I GoLog   :  Domain: IP address of my v2ray host name
07-31 04:54:03.801  1243  1264 I GoLog   :  Port: 443
07-31 04:54:03.801  1243  1264 I GoLog   :  IPs: [IP address of my v2ray host name]
07-31 04:54:03.807  1243  1243 I GoLog   : new core
07-31 04:54:03.807  1243  1243 I GoLog   : start core
07-31 04:54:03.808  1243  1268 I GoLog   : [Warning] core: Xray 1.5.3 started
07-31 04:54:03.867  1243  1243 D com.v2ray.ang: tun2socks destroy
07-31 04:54:03.867  1243  1243 D com.v2ray.ang: kotlin.UninitializedPropertyAccessException: lateinit property process has not been initialized

How to solve this problem? Thank you so much for your help again.

**Comment by yuhan6665** [comment]
weird issue, need full logs

**Comment by lixiaodongsql** [comment]
Today I execute the command adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main in my Ubuntu 18.04 terminal


Below is today's log.

* daemon not running. starting it now on port 5037 *
* daemon started successfully *
--------- beginning of system
--------- beginning of main
--------- beginning of crash
08-01 04:32:02.622  1280  1280 I com.v2ray.ang: Main ViewModel is cleared
08-01 04:32:08.903  1379  1379 D com.v2ray.ang: {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   "dns": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     "hosts": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "domain:googleapis.cn": "googleapis.com"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     "servers": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "1.1.1.1"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     ]
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   "inbounds": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "listen": "127.0.0.1",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "port": 10808,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "protocol": "socks",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "settings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "auth": "noauth",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "udp": true,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "userLevel": 8
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "sniffing": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "destOverride": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "http",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "tls"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         ],
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "enabled": true
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "tag": "socks"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "listen": "127.0.0.1",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "port": 10809,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "protocol": "http",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "settings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "userLevel": 8
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "tag": "http"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   ],
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   "log": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     "loglevel": "warning"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   "outbounds": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "mux": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "concurrency": 8,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "enabled": false
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "protocol": "vmess",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "settings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "vnext": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:             "address": "IP address of my v2ray host name",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:             "port": 443,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:             "users": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:               {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:                 "alterId": 0,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:                 "encryption": "",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:                 "flow": "",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:                 "id": "my UIUD",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:                 "level": 8,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:                 "security": "auto"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:               }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:             ]
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         ]
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "streamSettings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "network": "ws",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "security": "tls",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "tlsSettings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "allowInsecure": false,
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "serverName": ""
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "wsSettings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "headers": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:             "Host": ""
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "path": "/"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "tag": "proxy"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "protocol": "freedom",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "settings": {},
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "tag": "direct"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "protocol": "blackhole",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "settings": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "response": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "type": "http"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       },
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       "tag": "block"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   ],
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   "routing": {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     "domainMatcher": "mph",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     "domainStrategy": "IPIfNonMatch",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     "rules": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       {
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "ip": [
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:           "1.1.1.1"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         ],
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "outboundTag": "proxy",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "port": "53",
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:         "type": "field"
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:       }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:     ]
08-01 04:32:08.903  1379  1379 D com.v2ray.ang:   }
08-01 04:32:08.903  1379  1379 D com.v2ray.ang: }
08-01 04:32:08.903  1379  1379 I GoLog   : loading core config
08-01 04:32:08.903  1379  1405 I GoLog   : Preparing Domain: IP address of my v2ray host name:443
08-01 04:32:08.903  1379  1405 I GoLog   : Prepare Result:
08-01 04:32:08.903  1379  1405 I GoLog   :  Domain: IP address of my v2ray host name
08-01 04:32:08.903  1379  1405 I GoLog   :  Port: 443
08-01 04:32:08.903  1379  1405 I GoLog   :  IPs: [IP address of my v2ray host name]
08-01 04:32:08.905  1379  1379 I GoLog   : new core
08-01 04:32:08.906  1379  1379 I GoLog   : start core
08-01 04:32:08.906  1379  1405 I GoLog   : [Warning] core: Xray 1.5.3 started
08-01 04:37:34.061  1761  1761 D com.v2ray.ang: {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   "dns": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     "hosts": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "domain:googleapis.cn": "googleapis.com"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     "servers": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "1.1.1.1"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     ]
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   "inbounds": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "listen": "127.0.0.1",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "port": 10808,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "protocol": "socks",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "settings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "auth": "noauth",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "udp": true,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "userLevel": 8
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "sniffing": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "destOverride": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "http",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "tls"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         ],
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "enabled": true
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "tag": "socks"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "listen": "127.0.0.1",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "port": 10809,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "protocol": "http",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "settings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "userLevel": 8
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "tag": "http"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   ],
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   "log": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     "loglevel": "warning"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   "outbounds": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "mux": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "concurrency": 8,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "enabled": false
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "protocol": "vmess",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "settings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "vnext": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:             "address": "IP address of my v2ray host name",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:             "port": 443,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:             "users": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:               {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:                 "alterId": 0,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:                 "encryption": "",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:                 "flow": "",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:                 "id": "my UIUD",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:                 "level": 8,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:                 "security": "auto"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:               }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:             ]
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         ]
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "streamSettings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "network": "ws",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "security": "tls",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "tlsSettings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "allowInsecure": false,
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "serverName": ""
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "wsSettings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "headers": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:             "Host": ""
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "path": "/"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "tag": "proxy"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "protocol": "freedom",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "settings": {},
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "tag": "direct"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "protocol": "blackhole",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "settings": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "response": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "type": "http"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       },
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       "tag": "block"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   ],
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   "routing": {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     "domainMatcher": "mph",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     "domainStrategy": "IPIfNonMatch",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     "rules": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       {
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "ip": [
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:           "1.1.1.1"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         ],
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "outboundTag": "proxy",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "port": "53",
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:         "type": "field"
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:       }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:     ]
08-01 04:37:34.061  1761  1761 D com.v2ray.ang:   }
08-01 04:37:34.061  1761  1761 D com.v2ray.ang: }
08-01 04:37:34.065  1761  1761 I GoLog   : loading core config
08-01 04:37:34.065  1761  1780 I GoLog   : Preparing Domain: IP address of my v2ray host name:443
08-01 04:37:34.065  1761  1780 I GoLog   : Prepare Result:
08-01 04:37:34.065  1761  1780 I GoLog   :  Domain: IP address of my v2ray host name
08-01 04:37:34.065  1761  1780 I GoLog   :  Port: 443
08-01 04:37:34.065  1761  1780 I GoLog   :  IPs: [IP address of my v2ray host name]
08-01 04:37:34.067  1761  1761 I GoLog   : new core
08-01 04:37:34.067  1761  1761 I GoLog   : start core
08-01 04:37:34.068  1761  1784 I GoLog   : [Warning] core: Xray 1.5.3 started
08-01 04:37:34.070  1761  1761 D com.v2ray.ang: tun2socks destroy
08-01 04:37:34.070  1761  1761 D com.v2ray.ang: kotlin.UninitializedPropertyAccessException: lateinit property process has not been initialized

net::ERR_INTERNET_DISCONNECTED shows in Anbox WebView Browser Tester

How to solve this problem? Thank you so much for your help again.

**Comment by yuhan6665** [comment]
Looks like a limitation with Anbox architecture
Why not use https://github.com/v2rayA/v2rayA btw

**Comment by lixiaodongsql** [comment]
I use Qv2ray client to connect to v2ray nodes on Ubuntu 18.04. I want to use Anbox to emulate Android system on Ubuntu 18.04 
v2rayA does not have Android version app
I want to use v2rayNG app to circumvent China's firewall on Anbox
How to use v2rayNG app to circumvent China's firewall on Anbox? Thank you very much for your help. I really appreciate it

**Comment by lixiaodongsql** [comment]
My Qv2ray HTTP and HTTPS proxy adress is 127.0.0.1:8888

After I execute adb shell settings put global http_proxy 127.0.0.1:8888 in my Ubuntu 18.04 terminal , I can not open any webpage in Anbox

I estimate that the default HTTP proxy local address which Anbox can use is not 127.0.0.1
What is the default HTTP proxy local address which Anbox can use ?
How to let Anbox use HTTPS proxy ?
Thank you so much for your help again. I really appreciate it.

**Comment by lixiaodongsql** [comment]
https://docs.anbox.io/userguide/advanced/network_configuration.html

What is the default HTTP proxy host address which Anbox can use ?
How to let Anbox use HTTPS proxy ?
Thank you so much for your help again. I really appreciate it.

**Comment by lixiaodongsql** [comment]
Is the default HTTP proxy host address which Anbox can use 192.168.250.1
