### ISSUE TITLE
检测/识别代理服务器是否支持 UDP，如果是则显示标签

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1604]
![1659277454858](https://user-images.githubusercontent.com/110406842/182173997-9e20d823-b76e-4404-8c0c-182068adb341.png)
如图所示(截图是其他代理软件)，希望能增加一个小标签来显示代理服务器是否支持 UDP，如果支持，则在节点处显示“UDP”标签。
比如这样：
![IMG_20220801_225302](https://user-images.githubusercontent.com/110406842/182177872-64449c26-48e7-4d80-a18d-f167023d7d4b.png)
或者直接将 UDP 标签显示在“协议”标签的左边：
![IMG_20220801_225327](https://user-images.githubusercontent.com/110406842/182178220-d772ea90-94d6-4127-891d-9674e381dfc3.png)

UDP 可以说至关重要，有时候根本无法得知代理服务器是否支持 UDP，只能自己手动一个个去测试，对JC用户来说非常不友好(某些代理服务器商家称支持 UDP，实际使用后才发现根本不支持)。很多人在无法接通TG语音、打不通GV、游戏加载不了的时候会怀疑是代理软件的锅，但其实与代理软件无关，毕竟现在主流的代理软件没有不支持 UDP 的。希望能采纳，辛苦了，谢谢！

**Comment by ghost** [comment]
@2dust     @yuhan6665

**Comment by lankylonky22** [comment]
in order to make clash for windows display udp, u have to edit ur config file, it has nothing to do with whether the proxy servers has full cone udp
