### ISSUE TITLE
三星手机代理无效（我找了三种型号的三星手机）

### ISSUE THREAD

**Issue by 337077418** [2dust/v2rayNG#1605]
不好意思打扰了，我在下载使用v2rayng的时候发现我的三星手机开启代理后无法访问网络，其他平台的手机都可以翻墙，三星的开启代理后就访问不了网络（s20 s10 s21），没有报错。可以的话给我一个邮箱我发我的节点给您

**Comment by hqiu999** [comment]
我是三星s21ultar可以正常使用
