### ISSUE TITLE
节点中断又恢复后必须重连

### ISSUE THREAD

**Issue by xjuiean** [2dust/v2rayNG#1607]
v2rayNG用得好好的，节点对应的服务器中途断联一会儿后自动恢复了，v2rayNG必须关闭重连此节点才能恢复网络。

**Comment by xiaopang0v0** [comment]
> v2rayNG用得好好的，节点对应的服务器中途断联一会儿后自动恢复了，v2rayNG必须关闭重连此节点才能恢复网络。

你可能遇到了运营商的 TCP 重置，或者是 v2rayNG 的后台被操作系统杀掉了，你可以先排查一下是不是后台被杀掉了
