### ISSUE TITLE
无法更新订阅，更新订阅频繁显示失败

### ISSUE THREAD

**Issue by FeliciaViviana** [2dust/v2rayNG#1610]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Wangyi20010320** [comment]
请问这个问题解决了吗？要怎么解决呢？

**Comment by suucss** [comment]
无法订阅原因可能有很多：
- 可能是付费订阅链接到期（远端）
- 可能是手机所处网络不好（本地）
- 可能是由于数据跨境安全网关阻断了更新的请求（途中）
- 可能得到的返回包中含有非法字符（远端/途中）
- 等等
