### ISSUE TITLE
延迟过高8至9千左右完全不能使用

### ISSUE THREAD

**Issue by yjiawqgj** [2dust/v2rayNG#1611]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
我有两个手机都装着这个软件以前的时候都能用，昨天天用了以后延迟特别高八九千左右，完全没办法用，但是以前的时候可以用，我以为这个软件可能没有更新吧，我又下载了一个最新版本，安装上还是不行，但是用别的软件 clash for andriod却没有问题 .
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
锤子手机和小米 11

**Comment by jjsawyer** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmZskkSvOgOk7A4mHhNx0cehakj-fhj9L3pndVhf_c&s

**Comment by xiaopang0v0** [comment]
如果你使用了 xtls 导致你观察到的延迟高，那就请不要使用它，xtls 已经不安全了

**Comment by yjiawqgj** [comment]
xtls是什么

**Comment by xiaopang0v0** [comment]
> xtls是什么

是你的节点的传输层安全协议的类型，点进节点编辑界面就可以看到，有 xtls、tls、无 三种选项

**Comment by xiaopang0v0** [comment]
> xtls是什么

请问解决了吗？

**Comment by yjiawqgj** [comment]
> > xtls是什么
> 
> 请问解决了吗？

没有，但是现在能用了，但是你说的这安全协议类型没有找到，程序本身设置里没有，节点里只有Aes 256 128这样的设置。
