### ISSUE TITLE
VPN一直无法连接，节点失败 怎么回事？

### ISSUE THREAD

**Issue by azhu734** [2dust/v2rayNG#1613]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
无法连接

### 实际行为
节点失败，vpn无法连接

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>--------- beginning of main
08-07 19:10:40.116 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 99 Err: connection timed out
08-07 19:10:41.141 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 155 Err: connection timed out
08-07 19:10:41.141 I/GoLog   ( 6713): Not Using Prepared: tcp,117.131.104.183:80
--------- beginning of system
08-07 19:10:43.956 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 73 Err: connection timed out
08-07 19:10:44.184 I/GoLog   ( 6713): Not Using Prepared: tcp,117.131.104.183:80
08-07 19:10:48.308 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 74 Err: connection timed out
08-07 19:10:48.342 D/com.v2ray.ang(25779): https://sub.lemonyun.top/link/ukprpDqr2rrnPeUa?sub=3
08-07 19:10:48.416 I/GoLog   ( 6713): Not Using Prepared: tcp,117.131.104.183:80
08-07 19:10:51.380 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 73 Err: connection timed out
08-07 19:10:51.718 I/GoLog   ( 6713): Not Using Prepared: tcp,117.131.104.183:80
08-07 19:10:52.386 W/System.err(25779): java.net.SocketException: Connection reset
08-07 19:10:52.386 W/System.err(25779): 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
08-07 19:10:52.386 W/System.err(25779): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
08-07 19:10:52.386 W/System.err(25779): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
08-07 19:10:52.387 W/System.err(25779): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
08-07 19:10:52.387 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
08-07 19:10:52.387 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
08-07 19:10:52.387 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
08-07 19:10:52.387 W/System.err(25779): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
08-07 19:10:52.387 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
08-07 19:10:52.387 W/System.err(25779): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:385)
08-07 19:10:52.387 W/System.err(25779): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:492)
08-07 19:10:52.387 W/System.err(25779): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-07 19:10:52.387 W/System.err(25779): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-07 19:10:52.387 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-07 19:10:52.387 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
08-07 19:10:52.387 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-07 19:10:52.387 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-07 19:10:55.476 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 74 Err: connection timed out
08-07 19:10:55.712 I/GoLog   ( 6713): Not Using Prepared: tcp,117.131.104.183:80
08-07 19:10:58.804 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 73 Err: connection timed out
08-07 19:11:02.900 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 74 Err: connection timed out
08-07 19:11:03.240 I/GoLog   ( 6713): Not Using Prepared: tcp,117.131.104.183:80
08-07 19:11:10.324 I/GoLog   ( 6713): fdConn unix.Connect err, Close Fd: 73 Err: connection timed out
08-07 19:11:35.459 D/com.v2ray.ang(25779): https://sub.lemonyun.top/link/ukprpDqr2rrnPeUa?sub=3
08-07 19:11:40.666 W/System.err(25779): java.net.SocketException: Connection reset
08-07 19:11:40.666 W/System.err(25779): 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
08-07 19:11:40.666 W/System.err(25779): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
08-07 19:11:40.666 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
08-07 19:11:40.667 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
08-07 19:11:40.667 W/System.err(25779): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
08-07 19:11:40.667 W/System.err(25779): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
08-07 19:11:40.667 W/System.err(25779): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:385)
08-07 19:11:40.667 W/System.err(25779): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:492)
08-07 19:11:40.667 W/System.err(25779): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-07 19:11:40.667 W/System.err(25779): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-07 19:11:40.667 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-07 19:11:40.667 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
08-07 19:11:40.667 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-07 19:11:40.667 W/System.err(25779): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by yuhan6665** [comment]
订阅失效了

**Comment by azhu734** [comment]
> 订阅失效了

是需要续费吗？之前是别人给我买的所以我不大清楚

**Comment by chika0801** [comment]
> > 订阅失效了
> 
> 是需要续费吗？之前是别人给我买的所以我不大清楚

谁帮你买的，你找他去。

或者你自己找机场，自己买去。

不是软件的问题。

**Comment by liber-vie** [comment]
机场没问题，电脑窗口10系统的可以正常使用，安卓的没法用，安卓7版本
