### ISSUE TITLE
安卓系统很久都存在这个问题，V2rayNG连接后的状态,无法检测列表中节点哪些是有效的

### ISSUE THREAD

**Issue by hbw9123** [2dust/v2rayNG#1614]
安卓系统很久都存在这个问题，希望工程师改善，v2rayng连接后的状态，无法检测列表中节点哪些是有效的，必须断开链接状态后，才能成功进行检测哪些节点是绿色有效的；希望改善这个问题，在连接状态中也要能成功检测列表中的哪些节点是有效能正常使用的，先表示感谢了哦，

**Comment by yuhan6665** [comment]
用真连接测试不用断开啊
