### ISSUE TITLE
允许自定义socks5代理端口

### ISSUE THREAD

**Issue by lejay70643** [2dust/v2rayNG#162]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
socks5代理端口可以自定义。

### 实际行为
现有版本socks5代理端口被写死，系统内若已经启动占用该端口的app则无法启动。对于多用户android，若一个用户开启代理，第二个将无法开启代理。其他代理app，如shadowoskcs和kitsunebi，无此问题，因为大多采用随机端口号。

### 复现方法
1.正常使用时发现

### 环境信息
Android 9.0系统。

**Comment by lejay70643** [comment]
related issues
#113 
#158 
#133

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.1.10
