### ISSUE TITLE
v1.7.11版本（Xray 1.5.7）耗电量比较严重

### ISSUE THREAD

**Issue by Kannnnng** [2dust/v2rayNG#1625]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
耗电量低一点

### 实际行为
耗电量基本都排在所有应用的第一个

### 复现方法
1.正常开启 v2rayNG 以后打开几个应用用一段时间（一个小时或者更长时间），查看手机各个应用的耗电量统计

### 日志信息
无

### 环境信息
机型：小米8，8+128

### 额外信息（可选）
![046a2b45edc6f8342104c4c9f5eeab5](https://user-images.githubusercontent.com/22359680/185042010-8fad19e3-a07c-4b69-a9ba-6f317c68614b.jpg)

**Comment by chika0801** [comment]
换最新版本，或不管它，作者也没空管这个事情。

**Comment by Kannnnng** [comment]
> 换最新版本，或不管它，作者也没空管这个事情。

好像这个版本就已经是最新版本了，上个月我刚刚更新的……也没什么好办法，不管就不管吧……

**Comment by chika0801** [comment]
> > 换最新版本，或不管它，作者也没空管这个事情。
> 
> 好像这个版本就已经是最新版本了，上个月我刚刚更新的……也没什么好办法，不管就不管吧……

https://github.com/2dust/v2rayNg/releases
现在是1.7.18

你如果是软件作者来一个人抱怨这种莫名耗电，作者自己手机上用一切正常，你也不会管的，作者都是用爱发电。你先安个最新版本试试

**Comment by Kannnnng** [comment]
> > > 换最新版本，或不管它，作者也没空管这个事情。
> > 
> > 
> > 好像这个版本就已经是最新版本了，上个月我刚刚更新的……也没什么好办法，不管就不管吧……
> 
> https://github.com/2dust/v2rayNg/releases 现在是1.7.18
> 
> 你如果是软件作者来一个人抱怨这种莫名耗电，作者自己手机上用一切正常，你也不会管的，作者都是用爱发电。你先安个最新版本试试


嗯呢，当然还是感谢作者的，不然的话用都没得用（ :-P）

**Comment by chika0801** [comment]
> > > > 换最新版本，或不管它，作者也没空管这个事情。
> > > 
> > > 
> > > 好像这个版本就已经是最新版本了，上个月我刚刚更新的……也没什么好办法，不管就不管吧……
> > 
> > 
> > https://github.com/2dust/v2rayNg/releases 现在是1.7.18
> > 你如果是软件作者来一个人抱怨这种莫名耗电，作者自己手机上用一切正常，你也不会管的，作者都是用爱发电。你先安个最新版本试试
> 
> 嗯呢，当然还是感谢作者的，不然的话用都没得用（ :-P）

那你自己关下这ISS，不麻烦作者来关了
