### ISSUE TITLE
0.6.2版本似乎无法刷lnstagram，能更新但是无法加载图片。

### ISSUE THREAD

**Issue by WeiFengJL** [2dust/v2rayNG#163]
我重新换回0.6.1后可正常使用，使用的是分应用代理模式。
不知是否是路由问题，未测试全局模式

**Comment by WeiFengJL** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/0.6.4

已测试0.6.4版本，开启后需翻应用完全无法加载，而0.6.3和0.6.2只是不能加载lnstagram而已。

**Comment by 2dust** [comment]
把远程dns设置成1.1.1.1

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.4-beta3

**Comment by CoolCollin** [comment]
# 远程dns设置也没了，怎么设？
