### ISSUE TITLE
建议允许对每个v2ray配置文件，分别设置分应用代理

### ISSUE THREAD

**Issue by lejay70643** [2dust/v2rayNG#163]
建议允许对每个v2ray配置文件，分别设置分应用代理。

因为不同代理服务商经常有不同的限制，设置全局的分应用代理难以满足要求。另外，有的app访问的地址很多，通过域名来区分app较为困难。

**Comment by 2dust** [comment]
NG定位在简单上,你这个功能可以用用bv
