### ISSUE TITLE
手机下拉列表的状态图标在红米Noto10pro上无法正确变换

### ISSUE THREAD

**Issue by yh23931050** [2dust/v2rayNG#1631]
![image](https://user-images.githubusercontent.com/63437052/187105107-d75004d1-004f-49c5-9d7b-5bc6dc8584f2.png)
有流量传输时这个圆形的标志会出现这个功能很好，但我在红米Noto10pro上测试时有流量传输时无法显示出来

**Comment by yuhan6665** [comment]
通知栏的流量统计正常吗？如果流量会变图标不变应该是系统的“特性”

**Comment by yh23931050** [comment]
> 通知栏的流量统计正常吗？

正常显示
