### ISSUE TITLE
双击服务器删除按钮后出现闪退

### ISSUE THREAD

**Issue by Kukuair** [2dust/v2rayNG#1633]
### 预期行为

双击服务器删除按钮加速删除，即不必等待该服务器之后的服务器上移填充移除的位置，加速删除列表中的服务器，我记得在以前的版本中都可行。

### 实际行为

双击删除后app闪退，录屏 https://streamja.com/0OWeA

### 复现方法
1.  添加若干服务器。
2. 快速、多次点击删除按钮

### 日志信息
    尝试了使用所给的adb命令进行调试，但是在快速点击删除按钮瞬间未发现cmd终端界面有日志的变动

**Comment by 2dust** [comment]
版本号？

**Comment by Kukuair** [comment]
> 版本号？

1.7.19

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.23
