### ISSUE TITLE
android SOCKS代理上网速度慢丢包

### ISSUE THREAD

**Issue by yangfan2008** [2dust/v2rayNG#1634]
### 预期行为
描述你认为应该发生什么
目前采用v2ray sock5 搭建与android v2ray sock5同时开启启用本地DNS, 上网基本正常，但是下载和浏览网页，打开手机侧监控与window 客户端上面对速度明显慢很多，比较奇怪模拟器里面速度也是正常，就是真机下面比较慢，请教一下作者如何排查问题和优化
以下是我的配置文件 
    "dns": {
      "hosts": {
        "domain:googleapis.cn": "googleapis.com"
      },
      "servers": [
        {
          "address": "fakedns",
          "domains": [
            "geosite:cn"
          ]
        },
        "1.1.1.1"
      ]
    },
    "fakedns": [
      {
        "ipPool": "198.18.0.0/15",
        "poolSize": 10000
      }
    ],
    "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "destOverride": [
            "http",
            "tls",
            "fakedns"
          ],
          "enabled": true
        },
        "tag": "socks"
      },
      {
        "listen": "127.0.0.1",
        "port": 10809,
        "protocol": "http",
        "settings": {
          "userLevel": 8
        },
        "tag": "http"
      },
      {
        "listen": "127.0.0.1",
        "port": 10853,
        "protocol": "dokodemo-door",
        "settings": {
          "address": "1.1.1.1",
          "network": "tcp,udp",
          "port": 53
        },
        "tag": "dns-in"
      }
    ],
    "log": {
      "loglevel": "warning"
    },
    "outbounds": [
      {
        "mux": {
          "concurrency": 8,
          "enabled": false
        },
        "protocol": "socks",
        "settings": {
          "servers": [
            {
              "address": "x.x.x.x",
              "level": 8,
              "method": "chacha20-poly1305",
              "ota": false,
              "password": "",
              "port": 10002,
              "users": [
                {
                  "level": 8,
                  "pass": "xxxxxxx",
                  "user": "xxxxxx"
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp",
          "security": ""
        },
        "tag": "proxy"
      },
      {
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "tag": "direct"
      },
      {
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "tag": "block"
      },
      {
        "protocol": "dns",
        "tag": "dns-out"
      }
    ],
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "inboundTag": [
            "dns-in"
          ],
          "outboundTag": "dns-out",
          "type": "field"
        },
        {
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53",
          "type": "field"
        },
        {
          "ip": [
            "x.x.x.x"
          ],
          "outboundTag": "direct",
          "type": "field"
        }
      ]
    }
  }

**Comment by xiaopang0v0** [comment]
请问 socket5 代理是局域网内部搭建的吗？
