### ISSUE TITLE
Ad blocker does not work

### ISSUE THREAD

**Issue by net-warriors** [2dust/v2rayNG#1635]
Hello, I want to block ads in my browser and I have also used geosite:category-ads-all, but on sites like this site.
 https://www.zoomg.ir/movie-tv-show-review/341103-hotel-transylvania-4-transformania-review/
  Ads are not blocked, but ublock origin can block them.
 Is it possible to block such dynamic ads with v2ray?
 Can v2ray only block specific domains or IPs????
Thank you very much

**Comment by yuhan6665** [comment]
v2ray support only static rules
