### ISSUE TITLE
更新一次订阅后配置文件清空，再次更新一直失败

### ISSUE THREAD

**Issue by igohome8** [2dust/v2rayNG#1636]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
更新订阅刷新当前可用配置节点链接。

### 实际行为
v1.4.13，前天的使用中原本的链接大多无法使用于是更新了一次订阅，但配置文件界面链接在更新后全部清空 后续再次更新提示失败。
搜索到曾经有空白配置文件无法更新订阅的bug于是随便手动添加一个无效链接再尝试更新订阅，依然失败

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
ask your subscription provider

**Comment by Shaw666** [comment]
我目前也是同样的问题，删除后无法获取到节点了
