### ISSUE TITLE
V2RayNG 安卓端 tcping 测速有延迟，真连接测试为-1。节点失败信息：io:read/write on lcosed pipe

### ISSUE THREAD

**Issue by GourdErwa** [2dust/v2rayNG#1638]
## 你正在使用的版本 ？
V2RayU 版本 v1.7.19
手机：谷歌 pixel3 
安卓系统：12

## 你遇到的问题是什么？
安卓端勾选跳过证书校验、手动设置时间为当前时间
 Mac 端正常使用

问题：
1. 安卓端 tcping 测速有延迟正常显示演示毫秒数值，真连接测试为 -1ms。
2. 点击可用节点测试错误为：`失败：io:read/write on lcosed pipe`
## 日志信息
```log
-- 点击真连接测试时候日志

08-25 11:25:03.849  5482  9805 I GoLog   : [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
08-25 11:25:03.850  5482 12327 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe

-- 点击节点测试时候日志

08-25 11:26:39.839  5482  5517 I GoLog   : [Warning] [2979404894] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF

```

**Comment by GourdErwa** [comment]
已解决。手机时分秒对上了。日期忘了核对，慢了 11 天。[校对日期](https://time.is/)

**Comment by 13852313341** [comment]
手机咋校验

**Comment by GourdErwa** [comment]
> 手机咋校验

校验时间吗？访问[这个网站](https://time.is/)可以看到，或者你打开手机系统直接看你手机当前的日期时间，我是光看时间了，没看日期。

**Comment by 13852313341** [comment]
好吧，谢谢


小王科技
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2dust/v2rayNG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 上午9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [2dust/v2rayNG] V2RayNG 安卓端 tcping 测速有延迟，真连接测试为-1。节点失败信息：io:read/write on lcosed pipe (Issue #1638)





  
手机咋校验
  
校验时间吗？访问这个网站可以看到，或者你打开手机系统直接看你手机当前的日期时间，我是光看时间了，没看日期。

**Comment by ansonfish** [comment]
如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！

我是这样设置之后，解决了问题： io read/write on closed pipe
