### ISSUE TITLE
更新0.6.2無法連线

### ISSUE THREAD

**Issue by la8896** [2dust/v2rayNG#164]
Failed to connect to local 127.0.0.1(port 10808) /127.0.0.1 (port 52150)
使用其它apps是可正常連接的
剛剛測試了0.6.1是可正常連接

--------- beginning of system
--------- beginning of main
12-03 10:24:19.697 I/GoLog   (  818): loading v2ray config
12-03 10:24:20.332 I/GoLog   (  818): file exists
12-03 10:24:20.332 I/GoLog   (  818): new v2ray core
12-03 10:24:20.355 I/GoLog   (  818): start v2ray core
12-03 10:24:20.356 I/GoLog   (  818): run vpn apps
12-03 10:24:20.359 I/GoLog   (  818): 2018/12/03 02:24:20 [Warning] v2ray.com/core: V2Ray 4.8 started
12-03 10:24:20.413 I/GoLog   (  818): unforgivenessCloser() <-v.unforgivnesschan
12-03 10:24:20.413 I/GoLog   (  818): /data/user/0/com.v2ray.ang/tun2socks
12-03 10:24:20.414 I/GoLog   (  818): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 54 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
12-03 10:24:20.477 I/GoLog   (  818): EscortRun Waiting....

Phone
Sansung Note 8 SM--N9500 Android 8.0.0
Huawei Mate 10 Android 8.0.0(c636)

**Comment by la8896** [comment]
我改了port為10800就可連接了
但還是出現錯誤
attempy to invoke virtuxx method 'java.lang.string java.net.lnetaddress.tosring()'

**Comment by 2dust** [comment]
偵測出網際網路連線失敗:attempy to invoke virtuxx method 'java.lang.string java.net.lnetaddress.tosring()'

这个只是测试时的异常,和是否正常使用无关
即使异常出来了,也是能用的
这个异常很多手机都有,但是我无法在自己的环境重现,一直解决不了
