### ISSUE TITLE
socks添加用户名认证

### ISSUE THREAD

**Issue by RiotGamesU** [2dust/v2rayNG#1640]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
socks使用用户名+密码认证

### 实际行为
描述实际发生了什么
只有密码认证

### 复现方法
1.添加socks代理

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```

```
</details>

### 环境信息
Android12
V2rayNG 1.7.3

### 额外信息（可选）
https://www.v2fly.org/config/protocols/socks.html#accountobject

**Comment by 2dust** [comment]
暂时不考虑
