### ISSUE TITLE
慎用虚拟dns功能

### ISSUE THREAD

**Issue by channingbox** [2dust/v2rayNG#1641]
v2ray ng设置为分应用代理，启用本地dns模式，绕过大陆地址和局域网。如果此时同时启用虚拟dns，会导致浏览器访问大陆网站缓慢或根本无法访问，副作用大于正向作用。

**Comment by xiaopang0v0** [comment]
请确定你的 路由设置 中的 域名策略是否为 IPOnDemand ，预定义规则是否为 绕过局域网及大陆地址后代理 。本人在这个配置下使用 虚拟dns 功能一切正常

**Comment by channingbox** [comment]
> 请确定你的 路由设置 中的 域名策略是否为 IPOnDemand ，预定义规则是否为 绕过局域网及大陆地址后代理 。本人在这个配置下使用 虚拟dns 功能一切正常

我看了一眼，我设置的域名策略为ip if non match，改成和你一样的 ip if on demand ，效果一样，还是国内网站缓慢或者不能访问，可能和地域有关。

**Comment by xiaopang0v0** [comment]
> 

预定义规则是 绕过局域网及大陆地址后代理 吗？

**Comment by channingbox** [comment]
> > 
> 
> 预定义规则是 绕过局域网及大陆地址后代理 吗？

是的，并且Geo资源文件已更新为最新。
