### ISSUE TITLE
v2rayNG服务启动失败

### ISSUE THREAD

**Issue by gyp741760245** [2dust/v2rayNG#1645]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
服务启动成功

### 实际行为
服务启动失败

### 复现方法
1.更换节点链接依然失败
2.
3.

### 日志信息
<details>
--------- beginning of main
09-21 12:08:29.610 I/GoLog   ( 9684): Preparing Domain: iplc-enter-hk-xe4.fib-sys.xyz:11451
09-21 12:08:29.611 I/GoLog   ( 9684): loading core config
09-21 12:08:29.611 I/GoLog   ( 9684): new core
09-21 12:08:29.612 I/GoLog   ( 9684): start core
09-21 12:08:29.612 I/GoLog   ( 9684): app/proxyman/inbound: failed to listen TCP on 10808 > transport/internet: failed to listen on address: 127.0.0.1:10808 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:10808 > listen tcp 127.0.0.1:10808: bind: address already in use
09-21 12:08:29.612 I/GoLog   ( 9684): Prepare Result:
09-21 12:08:29.612 I/GoLog   ( 9684):  Domain: iplc-enter-hk-xe4.fib-sys.xyz
09-21 12:08:29.612 I/GoLog   ( 9684):  Port: 11451
09-21 12:08:29.612 I/GoLog   ( 9684):  IPs: [42.240.133.213]
--------- beginning of system
09-21 12:08:50.178 I/GoLog   (10129): Preparing Domain: iplc-enter-hk-xe4.fib-sys.xyz:11451
09-21 12:08:50.178 I/GoLog   (10129): loading core config
09-21 12:08:50.180 I/GoLog   (10129): Prepare Result:
09-21 12:08:50.180 I/GoLog   (10129):  Domain: iplc-enter-hk-xe4.fib-sys.xyz
09-21 12:08:50.180 I/GoLog   (10129):  Port: 11451
09-21 12:08:50.180 I/GoLog   (10129):  IPs: [42.240.133.213]
09-21 12:08:50.182 I/GoLog   (10129): new core
09-21 12:08:50.183 I/GoLog   (10129): start core
09-21 12:08:50.183 I/GoLog   (10129): app/proxyman/inbound: failed to listen TCP on 10808 > transport/internet: failed to listen on address: 127.0.0.1:10808 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:10808 > listen tcp 127.0.0.1:10808: bind: address already in use

</details>

### 环境信息
华为p30 EMUI11

**Comment by gyp741760245** [comment]
![Uploading Screenshot_20220921_120832_com.v2ray.ang.jpg…]()

**Comment by yuhan6665** [comment]
listen tcp 127.0.0.1:10808: bind: address already in use
有程序占用了端口

**Comment by xiaopang0v0** [comment]
请重启手机，然后测试软件是否恢复正常

**Comment by HushWay** [comment]
遇到相似的问题，我将v2rayNG置于下拉快捷按钮中，点击出现两种情况：
1. 如果v2rayNG已经在后台，可以成功启动服务；
2. 如果v2ryaNG未启动，虽然显示"启动服务中"，但是**有时（并不总是）**不能正常启动服务。
版本：v2ray 1.7.19
环境：红米K40 MIUI 13.0.7

**Comment by HushWay** [comment]
这个问题我已经解决，只需要将v2rayNG的电量管理设为不限制后台运行即可.

**Comment by Alex314000** [comment]
我是安卓机，版本1.8.5。启动服务失败，然后我重启了手机，还是不行，之后把从手机设置里把VPN链接删了，重新链接就正常了。
