### ISSUE TITLE
tiktok不会默认走代理

### ISSUE THREAD

**Issue by Chenyu550** [2dust/v2rayNG#1650]
在应用绕过大陆地址之后，tiktok的官网会被错误的绕过，从而造成无法访问

**Comment by Chenyu550** [comment]
抱歉，是我看错了

**Comment by xiaopang0v0** [comment]
请确定你的 路由设置 中的 域名策略是否为 IPOnDemand ，预定义规则是否为 绕过局域网及大陆地址后代理 。如果不是，请修改以后再检查软件会不会错误的绕过这些地址

**Comment by Chenyu550** [comment]
> 请确定你的 路由设置 中的 域名策略是否为 IPOnDemand ，预定义规则是否为 绕过局域网及大陆地址后代理 。如果不是，请修改以后再检查软件会不会错误的绕过这些地址

订阅节点暂时挂了，过几天我试试

**Comment by Chenyu550** [comment]
我今天试了，策略和规则都没问题，还是会错误的绕过，只有在自定义规则中手动添加 tiktok.com 为要代理的网址才能访问

**Comment by PanHsin** [comment]
默认内置规则(绕过大陆)并没有很好的区分国内外的抖音流量。走默认的绕过大陆时，会按国内的来处理，故请在自定义规则的"代理的网址或ip"那里添加一行
![Screenshot_20221019_190005](https://user-images.githubusercontent.com/26317972/196673754-4133f419-a532-4822-9bbc-3d3a732ef988.jpg)

geosite:tiktok
并用逗号(英文状态下的",")隔开其他规则
这个规则会优先匹配到，则tiktok app正常使用。

只写domain:tiktok.com的做法是不全的.
不推荐

**Comment by Chenyu550** [comment]
> 默认内置规则(绕过大陆)并没有很好的区分国内外的抖音流量。走默认的绕过大陆时，会按国内的来处理，故请在自定义规则的"代理的网址或ip"那里添加一行 ![Screenshot_20221019_190005](https://user-images.githubusercontent.com/26317972/196673754-4133f419-a532-4822-9bbc-3d3a732ef988.jpg)
> 
> geosite:tiktok 并用逗号(英文状态下的",")隔开其他规则 这个规则会优先匹配到，则tiktok app正常使用。
> 
> 只写domain:tiktok.com的做法是不全的. 不推荐

好的，感谢

**Comment by shafreeck** [comment]
我遇到了同样的问题，问题的深层原因是 tiktok 被包含进了 geosite:cn， 我注意到 tiktok 域名规则中有 `@!cn` 的标志，我理解应该是将其从 cn 列表中排除，但据我测试，最新的 v2ray-core 也不能正确的将 tiktok 从 cn 列表中排除。我们前直接手动将 tiktok 从 bytedance 的规则中删掉了，问题解决。

如果我对 `@!cn` 没有理解错的话，那 v2ray-core 可能是有 bug 的。

**Comment by qian9008** [comment]
> 我遇到了同样的问题，问题的深层原因是 tiktok 被包含进了 geosite:cn， 我注意到 tiktok 域名规则中有 `@!cn` 的标志，我理解应该是将其从 cn 列表中排除，但据我测试，最新的 v2ray-core 也不能正确的将 tiktok 从 cn 列表中排除。我们前直接手动将 tiktok 从 bytedance 的规则中删掉了，问题解决。
> 
> 如果我对 `@!cn` 没有理解错的话，那 v2ray-core 可能是有 bug 的。

这是geo文件的问题

**Comment by Andywang089** [comment]
按上面的方法，在路由设置中，路由规则设置中 domain添加了一行“geosite:tiktok”，解决问题

**Comment by w263756314** [comment]
> 按上面的方法，在路由设置中，路由规则设置中 domain添加了一行“geosite:tiktok”，解决问题

我使用 v2rayNG_1.9.9_arm64-v8a.apk 访问别的没问题，只有tiktok访问不了，按您说的尝试设置没有成功，可以说下具体步骤吗 ？感谢

**Comment by Bruinchina** [comment]
> > 按上面的方法，在路由设置中，路由规则设置中 domain添加了一行“geosite:tiktok”，解决问题
> 
> 我使用 v2rayNG_1.9.9_arm64-v8a.apk 访问别的没问题，只有tiktok访问不了，按您说的尝试设置没有成功，可以说下具体步骤吗 ？感谢

1.9.19版本遇到了同样的问题，路由规则设置中 domain添加了一行“geosite:tiktok”，也无法解决问题，请问还有其他办法吗？

**Comment by sleeper1023** [comment]
拔了手机卡就好了，检测到手机卡了

**Comment by w263756314** [comment]
我用的模拟器，没有手机卡呀

> 拔了手机卡就好了，检测到手机卡了

**Comment by opser-gavin** [comment]
移动端手机 v1.9.31同样遇到了这问题，所有app都没问题，就是tiktok不行~
拔掉手机卡 切换VPN节点同样不行~

**Comment by win4556** [comment]
怎么设置了那个geosite:tiktok”，就启动服务失败了

**Comment by AbrahamCui** [comment]
取消绕过大陆就行了...............

**Comment by win4556** [comment]
怎么取消阿

AbrahamCui ***@***.***> 于 2025年3月10日周一 15:12写道：

**Comment by yicen123** [comment]
不用分流

**Comment by honghongtu** [comment]
添加一个规则代理geosite:tiktok

**Comment by lsm1103** [comment]
添加一个规则代理geosite:tiktok还是没有用
