### ISSUE TITLE
使用一段时间后个别app无法代理

### ISSUE THREAD

**Issue by sj-nick** [2dust/v2rayNG#1655]
### 预期行为
app设置好服务器后访问正常  各个app均能正常访问，经过一晚上后第二天再访问YouTube 和GooglePlay 则无法连接 显示无网络  此时打开Instagram是可以正常访问的  尝试关闭链接重连  或者关闭app重启app均无法恢复   已经连续遇到2次  第一次遇到我重新打开其他VPN可以正常访问后关闭vpn  再打开v2eayng连接 就恢复正常了。

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by xeefei** [comment]
看起来有点像DNS的问题，改一下试试。
