### ISSUE TITLE
每次更新订阅时，代理连接会重置为第一个代理服务器，每次更新订阅还要重新选择之前的代理，比较麻烦

### ISSUE THREAD

**Issue by HAHAHAMaster** [2dust/v2rayNG#1657]
一直在用V2RayN和NG，V2RayN之前也有这个问题，但最近的5.3x版本解决了，每次订阅更新不再重新选择代理服务器，保持原代理服务器的连接不断，但V2RayNG仍然如此，应该不是服务商的原因，希望能优化一下。

**Comment by yuhan6665** [comment]
应该已经没这个问题 除非更新订阅后的地址变了 你NG的版本是？

**Comment by HAHAHAMaster** [comment]
刚才又试了一下，版本是最新的1.7.20，问题依旧，更新订阅，默认选择第一个代理服务器，而不是之前在用的。
