### ISSUE TITLE
v2rang:// 订阅链接不支持读取 name

### ISSUE THREAD

**Issue by betaxab** [2dust/v2rayNG#1658]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
点击链接添加后 remark 应为 name= 的指定值

### 实际行为
remark 为 "import sub"

### 复现方法
1. 通过 v2rayng://install-config?url=http%3A%2F%2Fexample.com&name=example 导入后即可复现

### 日志信息
无需日志

### 额外信息（可选）

https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/MmkvManager.kt#L122

看着是不支持识别 &name= 后的 remark，希望可以添加支持，这样就免得一键导入后再进去订阅分组设置里改名字了，谢谢。

**Comment by xiaopang0v0** [comment]
v2rang 是什么啊？

**Comment by 2dust** [comment]
现在没有制定这样的规范
也就是name不是必须的，只需要有url
订阅的名称用户可手工更改

**Comment by jwstaceyOvO** [comment]
v2rayng版本：1.8.5
v2rayng://install-config?url=http%3A%2F%2Fexample.com&name=example，实际测试中能一键导入，但是name不起作用，为默认名称import sub，另外需要手动更新订阅才能显示订阅中的节点；
此外我在代码中看到了以下两段

                        "install-sub" -> {
                            val uri: Uri? = intent.data
                            val url = uri?.getQueryParameter("url")!!
                            val name = uri.getQueryParameter("name") ?: "Subscription"
                            importSubscription(url, name)
                        }
                        
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:scheme="v2rayng"/>
                <data android:host="install-config"/>
                <data android:host="install-sub"/>
            </intent-filter>
            
v2rayng://install-sub?url=http%3A%2F%2Fexample.com&name=example，这样的格式无法跳转，是还未实现吗？希望scheme能导入即显示节点，并支持订阅名
