### ISSUE TITLE
0.6.2 自定义路由里填写网站黑名单无效

### ISSUE THREAD

**Issue by appstestacc** [2dust/v2rayNG#166]
### 预期行为
在自定义路由里设置需要阻止的域名，或是用自定义配置文件进行blackhole相关配置，希望阻止对一些网站的访问。

### 实际行为
似乎完全不起作用，仍可用浏览器访问这些网站。记得0.6.1应该是正常的，升级到0.6.2就失效了。

**Comment by appstestacc** [comment]
谢谢 2dust 大佬，不过升级到0.6.3似乎并没有解决问题？

**Comment by appstestacc** [comment]
服务端升级到4.8.0之后问题解决了！
谢谢 2dust ！
不过... 原本可以用的自定义配置文件突然不能用了（已将端口改10808），不知道是不是新bug...

**Comment by 2dust** [comment]
有问题开issue提交log，你这样的文字没有任何作用
我不可能知道如何解决你的问题
