### ISSUE TITLE
分应用代理-希望能修改为自己的连接

### ISSUE THREAD

**Issue by tandalin** [2dust/v2rayNG#166]
【分应用代理-自动选中需代理应用】

这种方式有些被和谐的APP没选上，需要手动再勾选，
例如【behance】和【国产浏览器】

新装的APP用自动选中后，之前手动勾选的也会被取消，这样非常麻烦

所以，希望【自动选择需代理应用】可以改为我自己的连接。
每次启动V2能自动更新一次更好。

**Comment by 2dust** [comment]
https://github.com/2dust/androidpackagenamelist
提交
或导出你自己的设置出来保存
下次导入
