### ISSUE TITLE
关于kde connect无法连接问题

### ISSUE THREAD

**Issue by iwoomi** [2dust/v2rayNG#1663]
安卓手机安装KDE Connect，可以和电脑互通(Linux, Windows, macOS都可以)，类似iPhone和Mac的Airdrop，用过的应该都知道，但现在我的问题是，我已经在：设置——自定义规则——直连的网址或IP里面填了直连的ip了，我这边家里路由器下发的网址是：192.168.0.x的，所以我设置了`192.168.0.1/24`直连ip，也设置了`geoip:private`，它就是不行，
![IMG_20221004_115835](https://user-images.githubusercontent.com/112089622/193731655-95afd191-d276-46e5-9cbd-f536138d1bb5.jpg)

但是Sagernet，我都没有去设置这个，它就没问题，而且我确定我已经保存了，我也试过关掉v2rayNG再打开，再去看直连ip，我设置的记录还在，说明确实是保存了的，而且保存后，我也有断开连接再重新连接，反正它就是不行，由于我非常常用KDE Connect，所以这个问题对我造成很大困扰，总是要开开关关的(关了v2rayNG的连接，KDE Connect才能通)。

不知道有没有谁也用Kde Connect的？如果你没有遇到我这个问题，可以提供一个解决问题的思路吗？

**Comment by yuhan6665** [comment]
在菜单里面选择 预定义路由 绕过局域网

**Comment by iwoomi** [comment]
一直都是选绕过局域网及大陆地址而后代理，它就是不行
![IMG_20221004_232955](https://user-images.githubusercontent.com/112089622/193861935-19d09bad-2d83-433d-888a-ce5f7386e14d.jpg)

不知道有没有人真实使用过这个KDE Connect的？理论上肯定是绕过局域网就可以，但实际上它就是不行，而Sagernet就没这问题，要不是因为Sagernet默认用v2fly内核，我就直接用Sagernet了，因为我试了sagernet可能内核版本问题，能用，但是非常慢，同一个服务器配置，用v2rayNG就快很多

**Comment by iwoomi** [comment]
竟然石沉大海，敢情是没有一个人用kde connect？🤣

**Comment by heimoshuiyu** [comment]
我跟你的情况刚好相反。我是 kde connect 在 v2rayNG 下选 选绕过局域网及大陆地址而后代理完全正常。而SagerNet里无论是配置了绕过LAN（此时kde connect 设备在局域网内），还是使用 wireguard 代理 10.39.39.0/24 （我的VPN IP段，kde connect 设备在此段内），都无法找到任何设备

**Comment by yztz** [comment]
wireguard路过，不太类似的情况，但是可以分享下。我是在op上设置了wireguard，手机全网段路由，结果kdeconnect无法探测到内网电脑设备（即使指定了设备IP）。在指定设备IP的情况下，用wireshark抓包后发现kdeconnect连接过程大致为：手机向目标ip([1714-1764](https://userbase.kde.org/KDEConnect#Troubleshooting)端口)发送UDP包，目标设备接收到包后，会主动向包来源设备ip([1714-1764](https://userbase.kde.org/KDEConnect#Troubleshooting)端口)建立TCP连接。

我的问题是在OP作为旁路由，自定义防火墙规则中添加了`iptables -t nat -I POSTROUTING -j MASQUERADE`规则，导致无论是内网还是wireguard的出包都被伪装为了软路由的ip，此时kdeconnect主动对软路由发起连接自然无法建立。

![image](https://github.com/2dust/v2rayNG/assets/42884283/631137d6-1a26-49d8-aca6-ae36fca11839)
> 注：`.233`是软路由ip，`.56`是主机ip
