### ISSUE TITLE
disable tls1.0 and tls1.1

### ISSUE THREAD

**Issue by JohnGooler** [2dust/v2rayNG#1667]
Hi,
when v2RayNG try to connect to server, its start with tls1.0 client hello.  
how can i disable tls1.0 and tls1.1 in v2RayNG? or force it to use tls1.2 and tls1.3?

regards
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Meissamomidi** [comment]
کد فعال سازی لطفاً

**Comment by JohnSirous** [comment]
Hi
Have a same issue with some device.

**Comment by Mehranpc** [comment]
Same problem...

**Comment by OnceUponATimeInAmerica** [comment]
You have to tell them you want an explicit TLS v1.3 for everything (subscription update, server testing and connection) setting in the UI.

**Comment by Mehranpc** [comment]
> You have to tell them you want an explicit TLS v1.3 for everything (subscription update, server testing and connection) setting in the UI.

Exactly

**Comment by OnceUponATimeInAmerica** [comment]
This is most probably a TLS fingerprinting-based blocking. One workaround which I found, for vmess+ws+tls servers is to enable "browser forwarding" option in the v2ray-core client. I don't know if the option is exposed in v2rayNG but I have set and successfully used it in the Matsuri (SagerNet fork) client.
Cheers.

**Comment by JohnSirous** [comment]
> This is most probably a TLS fingerprinting-based blocking. One workaround which I found, for vmess+ws+tls servers is to enable "browser forwarding" option in the v2ray-core client. I don't know if the option is exposed in v2rayNG but I have set and successfully used it in the Matsuri (SagerNet fork) client. Cheers.

Thanks for your advice.
i added "useBrowserForwarding": true, but not solved the problem on android
