### ISSUE TITLE
切换网络或掉线后不能重连

### ISSUE THREAD

**Issue by qgdlantern** [2dust/v2rayNG#167]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
切换网络(例如从WLAN切换到LTE)时会自动重连节点，待机唤醒是会重边节点

### 实际行为
切换网络或唤醒后被代理网站无法访问

### 复现方法
1.连接v2ray节点
2.测试连接(youtubde.com)
3.切换网络或唤醒
4.再次测试连接,提示错误

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
 fdConn unix.Connect err, Close Fd: 582 Err: connection timed out
```
</details>

### 额外信息（可选）
版本为v1.1.9，更新到最新版出现此现象。

**Comment by Mit2g** [comment]
可能是你选择的协议的缘故 可以尝试[QUIC](https://www.v2ray.com/chapter_02/transport/quic.html) 看看问题是否复现
