### ISSUE TITLE
multiplex connection to servers

### ISSUE THREAD

**Issue by masihtehrani** [2dust/v2rayNG#1670]
Hi there
Thank you for the great application.
I saw a feature in another client for connecting to servers. It's a multiplex connection to servers. I don't have any stable connection and lost servers in moments. I need to switch between servers for a better relationship. for example, v2raya has this feature.
![Screenshot from 2022-10-08 12-09-38](https://user-images.githubusercontent.com/9476972/194698543-72845390-c531-478a-b0ac-ea53c3369c01.png)

**Comment by 2dust** [comment]
Mobile devices are not suitable for enabling mux
