### ISSUE TITLE
cannot connect to trojan server using v2rayNG but openv2ray works.

### ISSUE THREAD

**Issue by crashpb** [2dust/v2rayNG#1673]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
be able to connect to my trojan server.
### 实际行为
描述实际发生了什么
cannot connect using v2rayng-v2flyng-sagernet can only connect using openv2ray to my server.
### 复现方法
1.import profile
2.connect
3.

### 日志信息
V2rayng logcat:

`10-09 00:36:13.720 22489 22489 D com.v2ray.ang: tun2socks destroy
10-09 00:36:45.868 22489 22489 D com.v2ray.ang: {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "dns": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "hosts": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "domain:googleapis.cn": "googleapis.com"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "servers": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "1.1.1.1"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     ]
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "inbounds": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "listen": "127.0.0.1",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "port": 10808,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "protocol": "socks",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "settings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "auth": "noauth",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "udp": true,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "userLevel": 8
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "sniffing": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "destOverride": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "http",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "tls"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         ],
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "enabled": true
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "tag": "socks"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "listen": "127.0.0.1",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "port": 10809,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "protocol": "http",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "settings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "userLevel": 8
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "tag": "http"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   ],
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "log": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "loglevel": "warning"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "outbounds": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "mux": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "concurrency": 8,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "enabled": false
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "protocol": "trojan",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "settings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "servers": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "address": "my.domain.name",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "flow": "",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "level": 8,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "method": "chacha20-poly1305",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "ota": false,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "password": "xrRc7tKU4k",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "port": 443
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         ]
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "streamSettings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "network": "tcp",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "security": "tls",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "tcpSettings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "header": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:             "type": "none"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "tlsSettings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "allowInsecure": false,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "serverName": "my.domain.name"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "tag": "proxy"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "protocol": "freedom",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "settings": {},
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "tag": "direct"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "protocol": "blackhole",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "settings": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "response": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "type": "http"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "tag": "block"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   ],
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "policy": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "levels": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "8": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "connIdle": 300,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "downlinkOnly": 1,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "handshake": 4,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "uplinkOnly": 1
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "system": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "statsOutboundUplink": true,
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       "statsOutboundDownlink": true
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "routing": {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "domainMatcher": "mph",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "domainStrategy": "IPIfNonMatch",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     "rules": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       {
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "ip": [
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:           "1.1.1.1"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         ],
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "outboundTag": "proxy",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "port": "53",
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:         "type": "field"
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:       }
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:     ]
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   },
10-09 00:36:45.868 22489 22489 D com.v2ray.ang:   "stats": {}
10-09 00:36:45.868 22489 22489 D com.v2ray.ang: }
10-09 00:36:45.870 22489 22489 I GoLog   : loading core config
10-09 00:36:45.871 22489 25265 I GoLog   : Preparing Domain: my.domain.name:443
10-09 00:36:45.878 22489 25265 I GoLog   : Prepare Result:
10-09 00:36:45.878 22489 25265 I GoLog   :  Domain: my.domain.name
10-09 00:36:45.878 22489 25265 I GoLog   :  Port: 443
10-09 00:36:45.878 22489 25265 I GoLog   :  IPs: [server IPV4 (server ip v6 address but last part is wrong>ok::ok:ok:ok:not_part_of_server's_ipv6)]
10-09 00:36:45.880 22489 22489 I GoLog   : new core
10-09 00:36:45.880 22489 22489 I GoLog   : start core
10-09 00:36:45.881 22489 25343 I GoLog   : [Warning] core: Xray 1.6.0 started
10-09 00:36:45.896 22489 22489 D com.v2ray.ang: [/data/app/com.v2ray.ang-FOWoo-BriOHNfVj-feixvw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-09 00:36:45.906 22489 22489 D com.v2ray.ang: Process[pid=27282, hasExited=false]
10-09 00:36:45.906 22489 22489 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
10-09 00:36:45.957 22489 25276 D com.v2ray.ang: sendFd tries: 0
10-09 00:36:49.911 22489 25383 I GoLog   : tcp:127.0.0.1:42625 accepted tcp:149.154.167.92:443 [socks >> proxy]
10-09 00:36:50.000 22489 25343 I GoLog   : Using Prepared: server IP
10-09 00:36:56.256 22489 25343 I GoLog   : Using Prepared: server IP
10-09 00:37:04.122 22489 25343 I GoLog   : udp:127.0.0.1:48202 accepted udp:4.2.2.4:53 [socks >> proxy]
10-09 00:37:04.233 22489 25265 I GoLog   : Using Prepared: server IP
10-09 00:37:08.163 22489 25276 D com.v2ray.ang: measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": context deadline exceeded
10-09 00:37:14.140 22489 25264 I GoLog   : udp:127.0.0.1:45659 accepted udp:4.2.2.4:53 [socks >> proxy]
10-09 00:37:14.227 22489 25342 I GoLog   : Using Prepared: server IP
10-09 00:37:23.944 22489 25268 I GoLog   : tcp:127.0.0.1:42631 accepted tcp:149.154.167.92:443 [socks >> proxy]
10-09 00:37:24.037 22489 25265 I GoLog   : Using Prepared: server IP
10-09 00:37:24.173 22489 25265 I GoLog   : udp:127.0.0.1:47600 accepted udp:4.2.2.4:53 [socks >> proxy]
10-09 00:37:24.265 22489 25343 I GoLog   : Using Prepared: server IP
10-09 00:37:26.002 22489 25343 I GoLog   : udp:127.0.0.1:38542 accepted udp:4.2.2.4:53 [socks >> proxy]
10-09 00:37:26.096 22489 25342 I GoLog   : Using Prepared: server IP
10-09 00:37:27.003 22489 22489 D com.v2ray.ang: tun2socks destroy`

openv2ray logcat:

`--------- beginning of system
--------- beginning of main
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog: {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   "dns": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     "hosts": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "domain:googleapis.cn": "googleapis.com"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     "servers": [
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "1.1.1.1"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     ]
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   "inbounds": [
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "listen": "127.0.0.1",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "port": 10808,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "protocol": "socks",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "settings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "auth": "noauth",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "udp": true,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "userLevel": 8
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "sniffing": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "destOverride": [
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           "http",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           "tls"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         ],
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "enabled": false
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "tag": "socks"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "listen": "127.0.0.1",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "port": 10809,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "protocol": "http",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "settings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "userLevel": 8
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "tag": "http"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   ],
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   "log": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     "loglevel": "warning"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   "outbounds": [
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "mux": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "concurrency": 8,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "enabled": false
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "protocol": "trojan",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "settings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "servers": [
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "address": "my.domain.name",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "level": 8,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "method": "chacha20-poly1305",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "ota": false,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "password": "xrRc7tKU4k",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "port": 443
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         ]
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "streamSettings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "network": "tcp",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "security": "tls",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "tcpSettings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           "header": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:             "type": "none"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "tlsSettings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           "allowInsecure": true,
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           "serverName": "my.domain.name"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "tag": "proxy"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "protocol": "freedom",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "settings": {},
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "tag": "direct"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "protocol": "blackhole",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "settings": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         "response": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:           "type": "http"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:         }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       },
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:       "tag": "block"
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   ],
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   "routing": {
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     "domainStrategy": "IPIfNonMatch",
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:     "rules": []
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog:   }
10-09 00:46:41.677 16400 16400 D V2rayConfigUtilGoLog: }
10-09 00:46:41.681 16400 16400 I GoLog   : loading v2ray config
10-09 00:46:41.681 16400 22277 I GoLog   : Preparing Domain: my.domain.name:443
10-09 00:46:41.688 16400 16400 I GoLog   : new v2ray core
10-09 00:46:41.689 16400 16400 I GoLog   : start v2ray core
10-09 00:46:41.689 16400 22277 I GoLog   : Prepare Result:
10-09 00:46:41.689 16400 22277 I GoLog   :  Domain: my.domain.name
10-09 00:46:41.689 16400 22277 I GoLog   :  Port: 443
10-09 00:46:41.689 16400 22277 I GoLog   :  IPs: [server IPV4 (server ip v6 address but last part is wrong>ok::ok:ok:ok:not_part_of_server's_ipv6)]
10-09 00:46:41.689 16400 22281 I GoLog   : [Warning] v2ray.com/core: V2Ray 4.31.2 started
10-09 00:46:41.708 16400 16400 I GoLog   : EnableLocalDNS: false
10-09 00:46:41.708 16400 16400 I GoLog   : ForwardIpv6: false
10-09 00:46:41.708 16400 16400 I GoLog   : DomainName: my.domain.name:443
10-09 00:46:41.708 16400 21186 I GoLog   : /data/app/com.opentunnel.vpn-cwIzI18lt5ObwKaG9JEWPg==/lib/arm64/libtun2socks.so [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.opentunnel.vpn/sock_path]
10-09 00:46:41.715 16400 21186 I GoLog   : EscortRun Waiting....
10-09 00:46:42.708 16400 16429 D com.opentunnel.vpn: sendFd tries: 0
10-09 00:46:42.770 16400 22281 I GoLog   : tcp:127.0.0.1:42729 accepted tcp:216.58.212.138:443 [proxy]
10-09 00:46:42.851 16400 19431 I GoLog   : udp:127.0.0.1:44152 accepted udp:1.1.1.1:53 [proxy]
10-09 00:46:42.879 16400 22284 I GoLog   : Using Prepared: serverIP
10-09 00:46:42.974 16400 22281 I GoLog   : Using Prepared: serverIP
10-09 00:46:43.183 16400 22277 I GoLog   : tcp:127.0.0.1:42733 accepted tcp:172.217.18.10:443 [proxy]
10-09 00:46:43.285 16400 22284 I GoLog   : Using Prepared: serverIP
10-09 00:46:45.718 16400 22284 I GoLog   : tcp:127.0.0.1:42736 accepted tcp:149.154.167.92:5222 [proxy]
10-09 00:46:45.997 16400 22277 I GoLog   : Using Prepared: serverIP
10-09 00:46:46.794 16400 22281 I GoLog   : 127.0.0.1:45781 accepted //cp.cloudflare.com:443 [proxy]
10-09 00:46:46.804 16400 22284 I GoLog   : udp:127.0.0.1:45046 accepted udp:1.1.1.1:53 [proxy]
10-09 00:46:47.021 16400 22277 I GoLog   : Using Prepared: serverIP
10-09 00:46:47.021 16400 22284 I GoLog   : Using Prepared: serverIP
10-09 00:46:47.365 16400 22277 I GoLog   : tcp:127.0.0.1:42742 accepted tcp:173.194.76.188:5228 [proxy]
10-09 00:46:47.542 16400 22281 I GoLog   : Using Prepared: serverIP
10-09 00:46:47.666 16400 22277 I GoLog   : udp:127.0.0.1:42281 accepted udp:1.1.1.1:53 [proxy]
10-09 00:46:47.899 16400 22281 I GoLog   : Using Prepared: serverIP
10-09 00:46:48.339 16400 22281 I GoLog   : tcp:127.0.0.1:42746 accepted tcp:142.250.185.106:443 [proxy]
10-09 00:46:48.620 16400 22277 I GoLog   : Using Prepared: serverIP
10-09 00:46:57.214 16400 16400 I GoLog   : EscortingDown() Killing all escorted process
10-09 00:46:57.225 16400 21186 I GoLog   : EscortRun cmd.Wait err: signal: killed
10-09 00:46:57.225 16400 21186 I GoLog   : EscortRun Exit
10-09 00:46:57.226 16400 16400 I GoLog   : EscortingDown pr.Wait err: waitid: no child processes
10-09 00:46:57.289 16400 16400 D com.opentunnel.vpn: java.lang.IllegalArgumentException: Receiver not registered: com.opentunnel.vpn.service.V2RayServiceManager$ReceiveMessageHandler@d1422a0
10-09 00:46:57.295 16400 16400 D com.opentunnel.vpn: java.lang.IllegalArgumentException: Receiver not registered: com.opentunnel.vpn.service.V2RayServiceManager$ReceiveMessageHandler@d1422a0`

通过`adb logcat -s com.opentunnel.vpn GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
server : ubuntu server running x-ui
clients android devices ranging from 9.0 to 13.0

### 额外信息（可选）
v2rayn on windows works fine.

**Comment by Fightxing** [comment]
I have the same problem
