### ISSUE TITLE
紧急： V2ray 频繁自动断开连接 - 谷歌 Pixel 6 安卓 手机 ，

### ISSUE THREAD

**Issue by brian12392** [2dust/v2rayNG#1674]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

紧急： V2ray 频繁自动断开连接 - 谷歌 Pixel 6 安卓 手机 ，
已经排除了机场服务的问题，我另外一个安卓设备使用相同的机场节点服务，没有问题，但是在谷歌Pixel 6 手机上，最近频繁自动断开连接，以前记得通过把时间设置成“自动” 可以解决，但是现在系统时间设置成自动后 还是不行，请问如何解决呢？

**Comment by xiaopang0v0** [comment]
**你什么日志都不给，甚至说连你的连接配置都不提供一下**，你就发个 “紧急” ，开发者免费开发了软件，你就这么对开发者呼来喝去的哈。

**Comment by xiaopang0v0** [comment]
你这样提出问题，社区的志愿者很难对你的问题进行定位，请你规范提交 issues 。

**Comment by brian12392** [comment]
你好，
不好意思啊 ，我这边因为是公司业务邮箱是Gmail 所以需要用到你们开发的V2rayN'g app
因为业务联系比较紧急，所以才这么急
那么怎么解决这个问题呢，你说的日志是什么？如何提交呢，？
请告诉我一下 谢谢

**Comment by brian12392** [comment]
你好，
请看一下附件的截屏照片，我用红色圆圈圈起来的是我们公司业务连接需要使用的美国节点，
就是这两个节点连接非常不稳定，刚连接上过一会就自动连不上了，
还是烦请解决一下 好吗 谢谢

**Comment by brian12392** [comment]
你好，

请问如何解决呢？

**Comment by xiaopang0v0** [comment]
你好，前几天是 UTC +8 北京时间的周末，是法定休息日，所以没有看邮箱。

你使用邮件发送的附件我这里是看不到的，请你在 Issues 中提交节点配置截图，记得在提交的时候删除掉 IP 信息，截图完成以后不要保存删除了 IP 信息的节点就可以了（总之只需要在截图的时候不暴露 IP 信息即可）

**Comment by brian12392** [comment]
你好，好的 我会尽快提交issue 谢谢

**Comment by brian12392** [comment]
你好，
2个问题
1，你说的节点配置截图，具体是指哪里的截图？ 是我打开V2RayNG 连接一个节点后的 App 界面截图，？ 还是什么什么截图？
2，你说的IP，是哪里？ 怎么删除IP信息？

**Comment by brian12392** [comment]
你好，app 连接 还是非常不稳定，昨天我发给你的回复 问题你收到了吗？
