### ISSUE TITLE
shadowsocks协议无法使用

### ISSUE THREAD

**Issue by 2857584289** [2dust/v2rayNG#1675]
谷歌商店1.7.20，所有的ss协议的节点没法使用

**Comment by Andy963** [comment]
+1， release 里面下的1.7.20 在使用SS(2022-blake3-aes-128-gcm)也无法使用， 提示：context deadline exceeded（ 在ios 小火箭, windows上通过qv2ray都正常）

**Comment by xiaopang0v0** [comment]
> +1， release 里面下的1.7.20 在使用SS(2022-blake3-aes-128-gcm)也无法使用， 提示：context deadline exceeded（ 在ios 小火箭, windows上通过qv2ray都正常）

我无法在 1.7.20 版本下复现你的问题。
请提供日志（LogCat），如果你在中国大陆且你不介意的话，请提供你所在的省份，用于排除是否是 "白名单" 政策的实验省份造成的额外影响。

**Comment by 2857584289** [comment]
--------- beginning of main
10-17 15:33:19.240 D/com.v2ray.ang(15840): {
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "dns": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "hosts": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "domain:googleapis.cn": "googleapis.com"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "servers": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "1.1.1.1",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "address": "223.5.5.5",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "domains": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "geosite:cn"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "expectIPs": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "geoip:cn"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "port": 53
10-17 15:33:19.240 D/com.v2ray.ang(15840):       }
10-17 15:33:19.240 D/com.v2ray.ang(15840):     ]
10-17 15:33:19.240 D/com.v2ray.ang(15840):   },
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "inbounds": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "listen": "127.0.0.1",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "port": 10808,
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "socks",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "settings": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "auth": "noauth",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "udp": true,
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "userLevel": 8
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "sniffing": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "destOverride": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "http",
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "tls"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "enabled": true
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "socks"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "listen": "127.0.0.1",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "port": 10809,
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "http",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "settings": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "userLevel": 8
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "http"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "listen": "127.0.0.1",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "port": 10853,
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "dokodemo-door",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "settings": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "address": "1.1.1.1",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "network": "tcp,udp",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "port": 53
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "dns-in"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     }
10-17 15:33:19.240 D/com.v2ray.ang(15840):   ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "log": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "loglevel": "warning"
10-17 15:33:19.240 D/com.v2ray.ang(15840):   },
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "outbounds": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "mux": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "concurrency": 8,
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "enabled": false
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "shadowsocks",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "settings": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "servers": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           {
10-17 15:33:19.240 D/com.v2ray.ang(15840):             "address": "star-moble.gatknqh.cn",
10-17 15:33:19.240 D/com.v2ray.ang(15840):             "level": 8,
10-17 15:33:19.240 D/com.v2ray.ang(15840):             "method": "aes-128-gcm",
10-17 15:33:19.240 D/com.v2ray.ang(15840):             "ota": false,
10-17 15:33:19.240 D/com.v2ray.ang(15840):             "password": "335877e4-08d3-442b-a368-cd8ab5899faa",
10-17 15:33:19.240 D/com.v2ray.ang(15840):             "port": 23004
10-17 15:33:19.240 D/com.v2ray.ang(15840):           }
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ]
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "streamSettings": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "network": "tcp",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "security": ""
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "proxy"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "freedom",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "settings": {},
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "direct"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "blackhole",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "settings": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "response": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "type": "http"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         }
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "block"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "protocol": "dns",
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "tag": "dns-out"
10-17 15:33:19.240 D/com.v2ray.ang(15840):     }
10-17 15:33:19.240 D/com.v2ray.ang(15840):   ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "policy": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "levels": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "8": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "connIdle": 300,
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "downlinkOnly": 1,
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "handshake": 4,
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "uplinkOnly": 1
10-17 15:33:19.240 D/com.v2ray.ang(15840):       }
10-17 15:33:19.240 D/com.v2ray.ang(15840):     },
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "system": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "statsOutboundUplink": true,
10-17 15:33:19.240 D/com.v2ray.ang(15840):       "statsOutboundDownlink": true
10-17 15:33:19.240 D/com.v2ray.ang(15840):     }
10-17 15:33:19.240 D/com.v2ray.ang(15840):   },
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "routing": {
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "domainMatcher": "mph",
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "domainStrategy": "IPIfNonMatch",
10-17 15:33:19.240 D/com.v2ray.ang(15840):     "rules": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "inboundTag": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "dns-in"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "dns-out",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "ip": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "1.1.1.1"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "proxy",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "port": "53",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "ip": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "223.5.5.5"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "direct",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "port": "53",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "domain": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "domain:googleapis.cn"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "proxy",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "ip": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "geoip:private"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "direct",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "ip": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "geoip:cn"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "direct",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       },
10-17 15:33:19.240 D/com.v2ray.ang(15840):       {
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "domain": [
10-17 15:33:19.240 D/com.v2ray.ang(15840):           "geosite:cn"
10-17 15:33:19.240 D/com.v2ray.ang(15840):         ],
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "outboundTag": "direct",
10-17 15:33:19.240 D/com.v2ray.ang(15840):         "type": "field"
10-17 15:33:19.240 D/com.v2ray.ang(15840):       }
10-17 15:33:19.240 D/com.v2ray.ang(15840):     ]
10-17 15:33:19.240 D/com.v2ray.ang(15840):   },
10-17 15:33:19.240 D/com.v2ray.ang(15840):   "stats": {}
10-17 15:33:19.240 D/com.v2ray.ang(15840): }
10-17 15:33:19.242 I/GoLog   (15840): loading core config
10-17 15:33:19.242 I/GoLog   (15840): Preparing Domain: star-moble.gatknqh.cn:23004
10-17 15:33:19.314 I/GoLog   (15840): Prepare Result:
10-17 15:33:19.314 I/GoLog   (15840):  Domain: star-moble.gatknqh.cn
10-17 15:33:19.314 I/GoLog   (15840):  Port: 23004
10-17 15:33:19.314 I/GoLog   (15840):  IPs: [221.131.165.115]
10-17 15:33:19.367 I/GoLog   (15840): new core
10-17 15:33:19.401 I/GoLog   (15840): start core
10-17 15:33:19.403 I/GoLog   (15840): [Warning] core: Xray 1.6.0 started
10-17 15:33:19.429 D/com.v2ray.ang(15840): [/data/app/~~6fAFjoGOB1NMa5E2R2uyKg==/com.v2ray.ang-4grqBFxtJoGLMvEaIsK5FQ==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
10-17 15:33:19.431 D/com.v2ray.ang(15840): Process[pid=18558, hasExited=false]
10-17 15:33:19.431 D/com.v2ray.ang(15840): /data/user/0/com.v2ray.ang/files/sock_path
10-17 15:33:19.445 I/tun2socks(18558): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-17 15:33:19.482 D/com.v2ray.ang(15840): sendFd tries: 0
10-17 15:33:19.482 I/tun2socks(18558): NOTICE(tun2socks): entering event loop
10-17 15:33:19.747 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 5 Err: connection timed out
10-17 15:33:20.003 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 80 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 81 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 97 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 96 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 83 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 95 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 90 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 94 Err: connection timed out
10-17 15:33:20.259 I/GoLog   (15840): fdConn unix.Connect err, Close Fd: 82 Err: connection timed out
10-17 15:33:20.261 I/GoLog   (15840): DNS accepted udp:1.1.1.1:53 [xray.system.a0027a15-6b4a-4144-ba0c-8dcc5206ab34 -> proxy]
10-17 15:33:20.262 I/GoLog   (15840): Using Prepared: 221.131.165.115
10-17 15:33:24.262 I/GoLog   (15840): Not Using Prepared: udp,223.5.5.5:53
10-17 15:33:24.262 I/GoLog   (15840): DNS accepted udp:223.5.5.5:53 [xray.system.a0027a15-6b4a-4144-ba0c-8dcc5206ab34 -> direct]
10-17 15:33:28.463 I/GoLog   (15840): Using Prepared: 221.131.165.115
10-17 15:33:37.951 I/GoLog   (15840): Using Prepared: 221.131.165.115

**Comment by 2857584289** [comment]
![Screenshot_2022-10-17-15-37-02-548_com v2ray ang](https://user-images.githubusercontent.com/64118371/196116693-61f82814-67e1-496b-904e-63a6190c5da3.png)
测试是正常的，但是无法使用

**Comment by 2857584289** [comment]
测试是正常的，但是无法使用
![Uploading Screenshot_2022-10-17-15-38-51-033_com.v2ray.ang.png…]()

**Comment by 2857584289** [comment]
![Screenshot_2022-10-17-15-37-02-548_com v2ray ang~01](https://user-images.githubusercontent.com/64118371/196117330-fcbfe99d-505c-4658-b8a0-c03dcec5e99b.png)
![Screenshot_2022-10-17-15-38-51-033_com v2ray ang](https://user-images.githubusercontent.com/64118371/196117338-c3436cac-3c10-4b2f-b2e6-7a63f7d43990.png)
测试似乎是正常的，但是无法使用。

**Comment by xiaopang0v0** [comment]
> ![Screenshot_2022-10-17-15-37-02-548_com v2ray ang~01](https://user-images.githubusercontent.com/64118371/196117330-fcbfe99d-505c-4658-b8a0-c03dcec5e99b.png) ![Screenshot_2022-10-17-15-38-51-033_com v2ray ang](https://user-images.githubusercontent.com/64118371/196117338-c3436cac-3c10-4b2f-b2e6-7a63f7d43990.png) 测试似乎是正常的，但是无法使用。

你好，很抱歉这么久才回复你，我已经检查了你的日志，节点是没有问题的，由于日志信息暴露了部分隐私，请你删除日志的那段回复。

**Comment by xiaopang0v0** [comment]
现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23

如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)

如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)

先更新软件，以排除软件版本过老导致的无法使用的情况

**Comment by 2857584289** [comment]
> 更新之后，仍然无法使用。

**Comment by 2857584289** [comment]
> 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> 
> 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> 
> 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> 
> 先更新软件，以排除软件版本过老导致的无法使用的情况


更新之后，仍然没法使用。


https://v2cross.com/archives/1881
使用这个方法之后能用了，不知道为什么

**Comment by xiaopang0v0** [comment]
> > 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> > 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> > 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> > 先更新软件，以排除软件版本过老导致的无法使用的情况
> 
> 更新之后，仍然没法使用。
> 
> https://v2cross.com/archives/1881 使用这个方法之后能用了，不知道为什么

哦，那就是软件设置的问题，你进入 v2rayNG 的设置，然后按照下图设置即可（切记，要所有选项都跟图中一样才行）

![image](https://user-images.githubusercontent.com/67624661/197375543-b8536b5c-fa52-4327-9ddd-013e863cd1b0.png)

**Comment by xiaopang0v0** [comment]
> > 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> > 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> > 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> > 先更新软件，以排除软件版本过老导致的无法使用的情况
> 
> 更新之后，仍然没法使用。
> 
> https://v2cross.com/archives/1881 使用这个方法之后能用了，不知道为什么

顺便提一句，你的这个节点的来源是什么地方呢？是**自行购买**还是**公共的免费订阅**？值得注意的是，公共的免费订阅（或者说免费 VPN ）存在不稳定的现象十分正常，这并不意味着软件的出现了问题，而是因为来源节点不稳定导致的。

**Comment by 2857584289** [comment]
> > > 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> > > 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> > > 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> > > 先更新软件，以排除软件版本过老导致的无法使用的情况
> > 
> > 
> > 更新之后，仍然没法使用。
> > https://v2cross.com/archives/1881 使用这个方法之后能用了，不知道为什么
> 
> 顺便提一句，你的这个节点的来源是什么地方呢？是**自行购买**还是**公共的免费订阅**？值得注意的是，公共的免费订阅（或者说免费 VPN ）存在不稳定的现象十分正常，这并不意味着软件的出现了问题，而是因为来源节点不稳定导致的。

购买的订阅。
按照你的设置之后，测试延迟是不正常的，大约9000毫秒，打开网页也是反应很慢，10秒才会有反应。
当我把域名策略切换到asls之后，测速和网页打开速度都正常了。

**Comment by xiaopang0v0** [comment]
> > > > 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> > > > 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> > > > 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> > > > 先更新软件，以排除软件版本过老导致的无法使用的情况
> > > 
> > > 
> > > 更新之后，仍然没法使用。
> > > https://v2cross.com/archives/1881 使用这个方法之后能用了，不知道为什么
> > 
> > 
> > 顺便提一句，你的这个节点的来源是什么地方呢？是**自行购买**还是**公共的免费订阅**？值得注意的是，公共的免费订阅（或者说免费 VPN ）存在不稳定的现象十分正常，这并不意味着软件的出现了问题，而是因为来源节点不稳定导致的。
> 
> 购买的订阅。 按照你的设置之后，测试延迟是不正常的，大约9000毫秒，打开网页也是反应很慢，10秒才会有反应。 当我把域名策略切换到asls之后，测速和网页打开速度都正常了。

这不科学啊，IPOnDemand 会把所有的访问域名解析成 IP 地址进行匹配，然后绕过大陆地址。理论上来说，几乎能完全对大陆地址进行分流的，这样分流访问应该会更快啊，真奇怪。

**Comment by aswekan** [comment]
我也是同样的问题，当 域名策略 设置为 AsIs 时，shadowsocks协议能够正常使用，测试延迟正常。当 域名策略 设置为其他两个选项时，无法使用，测试延迟8000-9000毫秒。

**Comment by aswekan** [comment]
> > > > > 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> > > > > 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> > > > > 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> > > > > 先更新软件，以排除软件版本过老导致的无法使用的情况
> > > > 
> > > > 
> > > > 更新之后，仍然没法使用。
> > > > https://v2cross.com/archives/1881 使用这个方法之后能用了，不知道为什么
> > > 
> > > 
> > > 顺便提一句，你的这个节点的来源是什么地方呢？是**自行购买**还是**公共的免费订阅**？值得注意的是，公共的免费订阅（或者说免费 VPN ）存在不稳定的现象十分正常，这并不意味着软件的出现了问题，而是因为来源节点不稳定导致的。
> > 
> > 
> > 购买的订阅。 按照你的设置之后，测试延迟是不正常的，大约9000毫秒，打开网页也是反应很慢，10秒才会有反应。 当我把域名策略切换到asls之后，测速和网页打开速度都正常了。
> 
> 这不科学啊，IPOnDemand 会把所有的访问域名解析成 IP 地址进行匹配，然后绕过大陆地址。理论上来说，几乎能完全对大陆地址进行分流的，这样分流访问应该会更快啊，真奇怪。

我也是同样的问题，当 域名策略 设置为 AsIs 时，shadowsocks协议能够正常使用，测试延迟正常。当 域名策略 设置为其他两个选项时，无法使用，测试延迟8000-9000毫秒。是付费订阅。

**Comment by aswekan** [comment]
> > > > > 现在我初步怀疑是你的 v2rayNG 软件配置出现了问题，所以我需要您检查您的软件版本是否为最新版本的 v2rayNG，最新版本请从此处下载 https://github.com/2dust/v2rayNG/releases/tag/1.7.23
> > > > > 如果你的手机是比较新款的手机（2015 年以后生产的）请点击后面的这个链接一键下载 [v2rayNG_1.7.23_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_arm64-v8a.apk)
> > > > > 如果上面的版本不行，那就下载这个版本[v2rayNG_1.7.23_armeabi-v7a.apk](https://github.com/2dust/v2rayNG/releases/download/1.7.23/v2rayNG_1.7.23_armeabi-v7a.apk)
> > > > > 先更新软件，以排除软件版本过老导致的无法使用的情况
> > > > 
> > > > 
> > > > 更新之后，仍然没法使用。
> > > > https://v2cross.com/archives/1881 使用这个方法之后能用了，不知道为什么
> > > 
> > > 
> > > 顺便提一句，你的这个节点的来源是什么地方呢？是**自行购买**还是**公共的免费订阅**？值得注意的是，公共的免费订阅（或者说免费 VPN ）存在不稳定的现象十分正常，这并不意味着软件的出现了问题，而是因为来源节点不稳定导致的。
> > 
> > 
> > 购买的订阅。 按照你的设置之后，测试延迟是不正常的，大约9000毫秒，打开网页也是反应很慢，10秒才会有反应。 当我把域名策略切换到asls之后，测速和网页打开速度都正常了。
> 
> 这不科学啊，IPOnDemand 会把所有的访问域名解析成 IP 地址进行匹配，然后绕过大陆地址。理论上来说，几乎能完全对大陆地址进行分流的，这样分流访问应该会更快啊，真奇怪。

我也是同样的问题，当 域名策略 设置为 AsIs 时，shadowsocks协议能够正常使用，测试延迟在100毫秒左右。当 域名策略 设置为其他两个选项时，无法使用，测试延迟8000-9000毫秒。

**Comment by yes00766428** [comment]
有新的登录网址吗？我之前购买订阅的网址打不开了

**Comment by feileb** [comment]
1.7.38版本shadowsocks协议无法使用，只有域名策略配置为AsIs能正常使用，其它两个无效
查看服务器连接，确认并没有连接到服务器，日志里面所有的数据都走了proxy/freedom，估计是路由配置有问题

**Comment by viRikaRe** [comment]
可能是处理Shadowsocks的分流规则存在问题，所以仅当域名策略+预定义规则设置成需要分流时才会触发。具体表现：
* 当域名策略为`AsIs`时，预定义规则可任选都没问题
* 当预定义规则为`全局`时，域名策略可任选都没问题
* 当域名策略为`IPIfNonMatch`或`IPOnDemand`且预定义规则为`绕过局域网地址而后代理`或`绕过大陆地址而后代理`时，Shadowsocks代理延迟测试在4000ms以上
* 当域名策略为`IPIfNonMatch`或`IPOnDemand`且预定义规则为`绕过局域网及大陆地址而后代理`时，Shadowsocks代理延迟测试失败
* 仅Shadowsocks协议存在此问题，VMess和VLESS没问题
* 版本: v1.7.38 (Lib v24, Xray-core v1.7.5)，从Google Play安装

**Comment by 2dust** [comment]
远程dns设置 为 https://dns.google/dns-query
