### ISSUE TITLE
Crashes when minifyEnabled=true

### ISSUE THREAD

**Issue by NimaEagle** [2dust/v2rayNG#1686]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
我希望程序在启用此选项时工作

### 实际行为
程序停止

### 复现方法
in app module build.gradle add this
minifyEnabled true
zipAlignEnabled false
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

**Comment by m1faridi** [comment]
add in proguard-rules.pro 
-keep class com.v2ray.ang.dto.*
