### ISSUE TITLE
增加shadowsocks协议的ws等，tls支持。

### ISSUE THREAD

**Issue by KOF136** [2dust/v2rayNG#1688]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.我的节点是ss+ws+tls，windows端正常使用。
2.安卓端不支持
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Hamidrezafayezi** [comment]
Good

**Comment by xiaopang0v0** [comment]
“搜索确认是否有人提出过相同问题”，你有搜索过吗？这一页有其他人提出了这个问题的吧，你现在又重复提一个 issue

**Comment by GeorgeRudd** [comment]
https://github.com/2dust/v2rayNG/issues/1653#issuecomment-1259684595
