### ISSUE TITLE
自定义路由不支持ip段，只支持单个IP

### ISSUE THREAD

**Issue by qgtxqj** [2dust/v2rayNG#169]
自定义路由里写入了IP段后，导出配置看得出，IP段被当成字符串处理了。
"rules":[{"domain":["1.201.0.0/24","103.2.28.0/22","103.246.56.0/22","103.27.148.0/22",....

**Comment by LittleGrocery** [comment]
感谢分享，另，我也同意希望赶快支持IP段，还有，ip段是直接以逗号相隔，似乎不需要在前面加domain吧
