### ISSUE TITLE
第一次使用v2rayNG，更新订阅失败

### ISSUE THREAD

**Issue by Ahmyya** [2dust/v2rayNG#1690]
### 预期行为
已经完成图1操作，本应再点击更新订阅后在页面中显示出各个节点（图2）

### 实际行为
完成图1操作后，点击更新订阅，屏幕下方出现“失败”（图3）

### 额外信息（可选）
值得注意的是，图1的操作要求“3. ...进入 设置 页面，点击路由模式 将其更改为 绕过局域网及大陆地址。”而在实际操作中，设置页面中无“路由模式”，可以选择“绕过局域网及大陆地址”的按钮只有“预定义规则”，不知道 更新订阅的失败 是否与此有关
第一次使用飞机场，可以说是什么也不懂了😥
![Uploading Screenshot_20221014_175521.jpg…]()

**Comment by taki-na** [comment]
请检查一下你的图片链接

**Comment by mehdifirefox** [comment]
I have the same problem from Iran ...
I solved my problem with another filter
https://github.com/MatsuriDayo/Matsuri/issues/122

**Comment by mehdifirefox** [comment]
Don't look at this?

I have no problem with Windows.
But Android is a problem

**Comment by jsahdja** [comment]
> 不看这个？
> 
> 我对 Windows 没有问题。但是Android是一个问题

一样不知道怎么解决，大哥现在有方法解决吗
