### ISSUE TITLE
Set Custom DNS SERVER

### ISSUE THREAD

**Issue by Padandish** [2dust/v2rayNG#1692]
Hi dear,
How can l set my custom dns server (IP with port)?
My service provider filter many domains. i need set my dns server.

Thanks

**Comment by Miladnedaei** [comment]
Y

**Comment by Miladnedaei** [comment]
> Hi dear, How can l set my custom dns server (IP with port)? My service provider filter many domains. i need set my dns server.
> 
> Thanks
