### ISSUE TITLE
新版本建议

### ISSUE THREAD

**Issue by 845929528** [2dust/v2rayNG#1695]
希望后续版本支持在Chromeast

**Comment by cuynu** [comment]
Chromecast not working with any VPN services include v2rayNG.

**Comment by 845929528** [comment]
最新Chromecaste 4k 设备是Android TV10 系统 希望增加一个账户自动同步其他设备覆盖节点订阅更新

**Comment by yuhan6665** [comment]
你说的不就是机场 :)
