### ISSUE TITLE
【功能】建议增加高级功能自定义 DNS 和 路由，允许同时启用多个不同 tag 的服务器。

### ISSUE THREAD

**Issue by mokeyish** [2dust/v2rayNG#1696]
目前 DNS 配置和路由都是由 v2rayNG 生成的，缺乏灵活性。

我的需求是能够同时访问谷歌、家里路由器、公司开发机器，这需要自定义路由转发和 DNS 解析。

希望能够提供这两部分自定义编辑 JSON，然后可自定义服务的 tag前缀，允许同时启用多个代理服务。
我觉得 v2rayNG 主要功能就是支持读取订阅，并更新 v2ray 的 outbound.

**Comment by donnyxray** [comment]
Ideally v2rayNG supports full JSON subscriptions. It would allow for any arbitrary function, including DNS changes, load-balancing, protocol and server fall-backs, etc.
