### ISSUE TITLE
v2rayNG设置just my socks服务器无法连接

### ISSUE THREAD

**Issue by kmtan78** [2dust/v2rayNG#17]
你好，使用v2rayNG设置Just My Socks 的shadowsocks节点无法连接上Google play，twitter，youtube等服务
Just My Socks 的节点在window的v2rayN是可以使用的

可以建议一下怎么处理吗，很喜欢手机上使用v2rayNG

手机是Android 9系统，如需要配合请告知。

**Comment by HNACROBEN** [comment]
我的Just My Socks 的shadowsocks节点 也无法连接，连接测试是通的

**Comment by 2dust** [comment]
Email  the configuration information to me

**Comment by szeto226** [comment]
Same problem here. But using other ss client software is ok.
