### ISSUE TITLE
Crash on pixel 2xl with Android 8.1 beta

### ISSUE THREAD

**Issue by febtancot** [2dust/v2rayNG#17]
It will crash when I click start button on the main screen

**Comment by franklee628** [comment]
Are you running OPP6.171019.012? I have a Pixel and comes to the same problem after a recent system update to version above.

**Comment by febtancot** [comment]
Yes, I'm running the same version with you.

**Comment by franklee628** [comment]
OPM1.171019.011 is out today, you might wanna give a try and see if it solves the problem?

**Comment by RedDragonFalcon1** [comment]
Nexus 6P Android 8.1.0 OPM1.171019.011 has the same issue.

**Comment by 2dust** [comment]
no device available for testing.
logcat?

**Comment by RedDragonFalcon1** [comment]
--------- beginning of main
12-07 09:07:55.397 I/GoLog   (16737): NoAutoConvert:true VpnConf:<Service:<Target:"/data/data/com.v2ray.ang/tun2socks" Args:"--netif-ipaddr" Args:"26.26.26.2" Args:"--netif-netmask" Args:"255.255.255.0" Args:"--socks-server-addr" Args:"127.0.0.1:10808" Args:"--tunfd" Args:"3" Args:"--tunmtu" Args:"1500" Args:"--sock-path" Args:"/dev/null" Args:"--loglevel" Args:"4" Args:"--enable-udprelay" VPNSetupArg:"m,1500 a,26.26.26.1,24 r,0.0.0.0,0" > PreparedDomainName:<TCPVersion:"tcp4" UDPVersion:"udp4" > > RootModeConf:<Scripts:<UpScript:"#none" DownScript:"#none" > > Env:<Vars:<key:"V2RaySocksPort" value:"10808" > > 
12-07 09:07:55.402 I/GoLog   (16737): [pdnsd-te.conf]<nil>
12-07 09:07:55.480 I/GoLog   (16737): <nil>2017/12/07 01:07:55 [Debug]App|Proxyman|Inbound: creating tcp worker on 127.0.0.1:10808
12-07 09:07:55.481 I/GoLog   (16737): 2017/12/07 01:07:55 [Info]Transport|Internet|TCP: listening TCP on 127.0.0.1:10808
12-07 09:07:55.482 I/GoLog   (16737): 2017/12/07 01:07:55 [Info]Transport|Internet|UDP: listening UDP on 127.0.0.1:10808
12-07 09:07:55.482 I/GoLog   (16737): 2017/12/07 01:07:55 [Warning]Core: V2Ray started
12-07 09:07:55.483 I/GoLog   (16737): unforgivenessCloser() <-v.unforgivnesschan
12-07 09:07:55.532 I/GoLog   (16737): unforgivenessCloser() <-v.unforgivnesschan
12-07 09:07:55.558 I/GoLog   (16737): /data/data/com.v2ray.ang/tun2socks
12-07 09:07:55.558 I/GoLog   (16737): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
12-07 09:07:55.558 I/GoLog   (16737): Waiting....
--------- beginning of crash
12-07 09:07:58.808 I/GoLog   (16792): NoAutoConvert:true VpnConf:<Service:<Target:"/data/data/com.v2ray.ang/tun2socks" Args:"--netif-ipaddr" Args:"26.26.26.2" Args:"--netif-netmask" Args:"255.255.255.0" Args:"--socks-server-addr" Args:"127.0.0.1:10808" Args:"--tunfd" Args:"3" Args:"--tunmtu" Args:"1500" Args:"--sock-path" Args:"/dev/null" Args:"--loglevel" Args:"4" Args:"--enable-udprelay" VPNSetupArg:"m,1500 a,26.26.26.1,24 r,0.0.0.0,0" > PreparedDomainName:<TCPVersion:"tcp4" UDPVersion:"udp4" > > RootModeConf:<Scripts:<UpScript:"#none" DownScript:"#none" > > Env:<Vars:<key:"V2RaySocksPort" value:"10808" > > 
12-07 09:07:58.836 I/GoLog   (16792): unforgivenessCloser() <-v.unforgivnesschan
12-07 09:07:58.837 I/GoLog   (16792): <nil>
12-07 09:07:58.837 I/GoLog   (16792): 2017/12/07 01:07:58 [Debug]App|Proxyman|Inbound: creating tcp worker on 127.0.0.1:10808
12-07 09:07:58.837 I/GoLog   (16792): 2017/12/07 01:07:58 [Warning]Core: V2Ray started
12-07 09:07:58.873 I/GoLog   (16792): unforgivenessCloser() <-v.unforgivnesschan
12-07 09:07:58.880 I/GoLog   (16792): /data/data/com.v2ray.ang/tun2socks
12-07 09:07:58.880 I/GoLog   (16792): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
12-07 09:07:58.880 I/GoLog   (16792): Waiting....
12-07 09:07:59.985 I/GoLog   (16792): Protecting Sock: 38
12-07 09:08:00.238 I/GoLog   (16792): Protecting Sock: 41

**Comment by febtancot** [comment]
Same issue

发自我的 iPhone

**Comment by lbbboy** [comment]
等待修复。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.3.2
may be ok

**Comment by RedDragonFalcon1** [comment]
it works

**Comment by febtancot** [comment]
Upgrade from play store. It's works , thanks for hard work, but still need to make it stable ,as may crash some time l. And is there any plan to add ACL support ?

**Comment by 2dust** [comment]
ACL support ?NO
