### ISSUE TITLE
EMUI9.0版本无法使用

### ISSUE THREAD

**Issue by YUOL-CCY** [2dust/v2rayNG#170]
![78be61b30c202bd96a2f3a060c115966](https://user-images.githubusercontent.com/26436652/49630340-b3fae400-fa28-11e8-9ad6-51760e43cfa1.jpg)

**Comment by zrcaeiou** [comment]
我也遇到了，后来发现新版在inbound使用socks协议时，必须把端口写成固定值10808 。
