### ISSUE TITLE
Mobile Browser as well as Google play do not get routed net from V2rayng

### ISSUE THREAD

**Issue by khayyamin** [2dust/v2rayNG#1705]
Hello to all,
I have set up a config to be used by V2rayN and V2raynG (for my pc and mobile device), and it is much to my surprise that in PC everything works very well, BUT in mobile the situation is a bit complicated:

My filtered apps such as Facebook and twitter connect, but my browser (chrome) does not open any filtered website.

how could we rectify this?

Wishes

**Comment by amid11** [comment]
I had the same issue but fixed it by disabling `Local DNS` option and setting another Public DNS such as Google's `8.8.8.8` for `VPN DNS` option. Both options can be found in the application settings.
Also make sure to include your browser in the `Per-app proxy`.
