### ISSUE TITLE
v2ray的android耗电发热问题

### ISSUE THREAD

**Issue by zhlila** [2dust/v2rayNG#171]
![v2ray](https://user-images.githubusercontent.com/6738727/68929815-095a7c00-07c8-11ea-9293-82c463601070.png)

v2ray的cpu占用基本是长时间保持在第一位的，而且相比ss或者是google play上面的一些其他vpn，手机发热和掉电更加严重

**Comment by zmplpq** [comment]
参考ss耗电问题：
为什么使用了代理应用后在电量统计中显示耗电很多？
这是移动操作系统的一个特殊机制，Surge、Quantumult、Shadowrocket等等所有的 SS 客户端开启后会接管全局的（几乎）所有通信，所以所有的网络方面电量消耗都会被算在 SS 客户端头上，实际使用中不会感到 SS 客户端对电量有明显影响，「设置-电池」中看到它的电池用量，绝大部分都是网络所消耗的电量，并不是 SS 客户端消耗的电量，SS 客户端就是背锅侠。
网络流量也是如此的。
