### ISSUE TITLE
长时间后台运行后，无法正常代理

### ISSUE THREAD

**Issue by zjudongze** [2dust/v2rayNG#1711]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常

### 实际行为
长时间后台运行后，回到前台，无法连接telegram等任何需要代理的app
但是点击v2rayng的测试： 连接工作正常；手动关闭再开启代理，工作正常。

### 日志信息
10-24 12:23:21.149  1821  2187 I ActivityManager: Process PhantomProcessRecord {9176357 19954:31983:libtun2socks.so/u0a291} died

### 额外信息（可选）
v2rayNG 依赖 libtun2socks.so这个进程；
但是android的电源管理目前只能保证v2rayNG不被杀掉，而无法保证 通过v2rayNG启动的
libtun2socks.so这个进程不会因为cpu占用过高，或者 达到PhantomProcess 上限 （默认32个） 被杀掉， 或者因为程序bug而崩溃；

需要在V2rayNG处理libtun2socks.so因为种种原因挂掉的情况：
比如在创建tun2socks进程时 ProcessBuilder#start()， 保存返回值，定期检查Process.isAlive(); 如果进程挂了，那么重新启动进程

**Comment by lq746224** [comment]
同样遇到这个问题，长时间后台运行后就无法正常代理了。需要重新连接一下

**Comment by zjudongze** [comment]
> 同样遇到这个问题，长时间后台运行后就无法正常代理了。需要重新连接一下

花了半个小时，打了个补丁。
可以试试我的补丁，自从用了之后，妈妈再也不用担心我后台失联了；

**Comment by LYZ10** [comment]
谢谢您的贡献，不过小白想请问下怎么才能用上这个补丁呢？

**Comment by zjudongze** [comment]
目前只能下载源代码，自己用android studio编译
或者等合并入主干后新的版本

**Comment by LYZ10** [comment]
了解了，谢谢你呀！
（第一个办法对小白来说有点难度，害怕翻车，哈哈；还是耐心等待新版本）
不过好像最近没有出现这个问题

**Comment by orz12** [comment]
作者好像一直没有合并这个pr 我还是蛮期待的 遇到这个问题很久了

**Comment by zjudongze** [comment]
我自己一直在用，很稳定； 关键是很省心
有了这个补丁之后，除了有时手动切换服务器，经常一个礼拜不用管v2ray； 以前是休眠后回来，得手动关开一次v2rayng

至于为啥不合并，我就不知道了。也没人给反馈
