### ISSUE TITLE
App Icon not showing on Android TV 

### ISSUE THREAD

**Issue by farshad-sadri** [2dust/v2rayNG#1712]
The app properly works on Android TV and the layout adapts to landscape mode. However the app does not show up in apps list screen. 

I tested on Mi Box S
Android 8.1
Official Launcher

**Comment by cuynu** [comment]
Because v2rayNG are basically designed for Android phone, emulator, not designed for Android TV

**Comment by farshad-sadri** [comment]
What I am saying is v2rayNG works fine and looks fine on Android TV despite other phone intended apps. It might worth fixing this issue to be compatible with Android TV. Besides Google play has already checked the compatibility of your app and it is visible in native Google Play Store app on Android TV.

**Comment by MHSanaei** [comment]
I'm delighted to see this because I tested with my android tv today, and I had the same problem. It cloud be so cool if they add a version  for Android tv

**Comment by ebzeueg** [comment]
+1

**Comment by mdbaniani** [comment]
> The app properly works on Android TV and the layout adapts to landscape mode. However the app does not show up in apps list screen.
> 
> I tested on Mi Box S Android 8.1 Official Launcher

did you manage to connect your mi Box using v2Ray proxy? I didn't succeed using a vmess connection profile. the app connects but no data is transferred

**Comment by farshad-sadri** [comment]
Sure, I did do that and it works fine, however since no icon is showing when you close the app, you should reopen it from the Settings / Apps section.

**Comment by mdehghani65** [comment]
> 

thanks. I also managed to get the job done using Armod app. the connection string also matters. some work, some don't.

**Comment by mdehghani65** [comment]
> Sure, I did do that and it works fine, however since no icon is showing when you close the app, you should reopen it from the Settings / Apps section.
thanks. I also managed to get the job done using Armod app. the connection string also matters. some work, some don't.

**Comment by mdbaniani** [comment]
> Sure, I did do that and it works fine, however since no icon is showing when you close the app, you should reopen it from the Settings / Apps section.

thanks. I also managed to get the job done using Armod app. the connection string also matters. some work, some don't.

**Comment by thisisamir98** [comment]
@farshad-sadri @MHSanaei @mdehghani65 @ebzeueg 
Just found this on YT, works as a temporary solution for now: https://www.youtube.com/watch?v=7aThirrOtXU

**Comment by PAYAMiN** [comment]
First install original v2rayNG app and then install following APK file, then your V2RAY application will be shown in your app list same as ATV-Designed applications. 
Also native V2RAYNG app is working fine with remote control.
[Download ATV v2rayNG APK](https://www.mediafire.com/file/32aoxu7bq8dvhtq/V2rayng_ATV.apk/file)

**Comment by mmrabbani** [comment]
Here is why you cannot see the app icon.
The app is set incompatible on android TV in play store by the developer. So android TV cannot download it on google play store.
When an app is installed from outside of google play store, TV launcher doesn't show the app icon.
Please change the compatibility on google play store

**Comment by emadtoranji** [comment]
It's listed on 'System Apps'
