### ISSUE TITLE
[Bug]: 不支持IDN域名

### ISSUE THREAD

**Issue by GH6324** [2dust/v2rayNG#1713]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
订阅成功

### 实际行为
订阅内容中的使用域名是IDN域名编码，例如ミン.コム这种域名，会直接订阅不了，V2rayN就没这个问题，会自动转码

### 复现方法
1.ミン.コム
2.
3.

### 日志信息
无

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.7.31
