### ISSUE TITLE
can not set flow when tls set to "tls" in android

### ISSUE THREAD

**Issue by omidi60** [2dust/v2rayNG#1716]
in android version when create a VLESS config if set tls value to "tls" the flow value did not save in config when selected.
after save profile config and edit it again the flow value is empty. 

this problem exist in version 1.7.20 and 1.7.4 as I check.

this problem is not exist in version 1.5.16 as I check.

**Comment by yuhan6665** [comment]
It is a feature not a bug.
It helps you to know that flow does nothing when you use "tls". It currently only work with "xtls"

**Comment by omidi60** [comment]
if this is how it work so it seems in recent android version with no flow and tls value set to "tls" the connection not working. same configuration (no flow and tls set to "tls") work on windows with same server.

**Comment by adisubagja** [comment]
> It is a feature not a bug. It helps you to know that flow does nothing when you use "tls". It currently only work with "xtls"

Hello how to apply trojan without tls i need it !
