### ISSUE TITLE
[BUG]服务器导入失败

### ISSUE THREAD

**Issue by kczack** [2dust/v2rayNG#1719]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常导入服务器

### 实际行为
用户ID包含“@”字符的VLESS服务器，通过二维码或剪贴板导入，会显示”失败“。手动添加服务器无此问题。

### 复现方法
1.用户ID包含“@”字符
2.通过二维码或剪贴板导入
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
v2rayNG版本：v1.7.20 (Lib v24, Xray-core v1.6.0)

**Comment by yuhan6665** [comment]
I think you should not put @ in user id
