### ISSUE TITLE
1.7.24无法安装

### ISSUE THREAD

**Issue by SekiBetu** [2dust/v2rayNG#1720]
### 预期行为
顺利安装

### 实际行为
一直提示安装中，无法顺利安装

### 复现方法
1.卸载1.7.23版本
2.安装1.7.24版本
3.无法安装

### 日志信息
手边没有电脑，不方便获取日志

### 环境信息
Android 12

**Comment by SekiBetu** [comment]
似乎是配置文件问题
开启tls时候再开xtls的流控就不行，会闪退
但是新的流控必须是tls+xtls-rprx-vision，请作者把中间的判断逻辑改下，tls也可以开启流控

**Comment by TwilightHome20** [comment]
> 似乎是配置文件问题 开启tls时候再开xtls的流控就不行，会闪退 但是新的流控必须是tls+xtls-rprx-vision，请作者把中间的判断逻辑改下，tls也可以开启流控

同样的问题,使用tls和新的xtls-rprx-visionudp443时会闪退

**Comment by 2dust** [comment]
把有问题的配置分享出来

**Comment by SekiBetu** [comment]
我在检查自己的配置的时候发现，哦，是不是新流控和uTLS是不兼容的，我给忘了，一直开着呢，怪不得，那问题不大了，不过安装的时候总是安装不上很怪，可以从老版本升级上去，但是单独安装新版本总是会卡住，重启之后就是个损坏的APP，需要再次覆盖安装才能用，建议作者再编译一份上传，是不是编译过程有什么古怪

**Comment by 2dust** [comment]
> 我在检查自己的配置的时候发现，哦，是不是新流控和uTLS是不兼容的，我给忘了，一直开着呢，怪不得，那问题不大了，不过安装的时候总是安装不上很怪，可以从老版本升级上去，但是单独安装新版本总是会卡住，重启之后就是个损坏的APP，需要再次覆盖安装才能用，建议作者再编译一份上传，是不是编译过程有什么古怪

下载测试了下，在开发者手机Pixel上都正常安装
