### ISSUE TITLE
开启代理后，不能访问纯v6域名

### ISSUE THREAD

**Issue by sungamma** [2dust/v2rayNG#1723]
ng设置了分应用代理chrome，并采用vpn方式。此时如果打开ng并连接纯v4的代理，chrom不能访问v6的纯域名。即使自定义规则设置了直连改域名。
设置见图
![Screenshot_2022-10-30-09-49-07-179_com v2ray ang](https://user-images.githubusercontent.com/33790/198858948-c68302ba-91ae-4a47-9e8d-451d82d98ab0.jpg)

### 预期行为
对于规则直连内的域名应直接能访问

### 实际行为
chrome提示dns解析错误

关闭代理，即可访问。

请问是设置错误吗？该如何设置，目前已尝试很多设置组合，均未成功

**Comment by yuhan6665** [comment]
Your vps must support ipv6 AFAIK
