### ISSUE TITLE
1.1.11版本会导致无法以ipv6流量访问支持ipv6的网站,旧版本则无此问题

### ISSUE THREAD

**Issue by emiyalee1005** [2dust/v2rayNG#173]
1.1.11版本会导致无法以ipv6访问支持ipv6的网站,旧版本则无此问题

### 预期行为
原先使用1.1.11以前的版本时（服务器拥有ipv6地址并设置为UseIPV6策略），访问google等支持ipv6的网站，默认会以ipv6访问(google直接搜索ip就可以看到当前访问google用的ip)

### 实际行为
描述实际发生了什么

这两天更新1.1.11版后，在其他任何东西都没变更的情况下，访问google变ipv4了。然后我立刻卸载1.1.11，重装老版本1.1.10，再访问google就变成ipv6，为了确认不是偶然的情况，我又多次在1.1.11和1.1.10之间来回切换测试，然后结果都是一样，可以确定是最新版1.1.11版引起的问题（设置里无论开不开启优先使用ipv6都没有任何变化，服务端配置一直都是UseIPV6，并且服务器ipv6地址同一时间也是ok，无论ping还是tcp都没问题，也和我自己手机是用ipv4还是ipv6地址来连接服务器没关系，各种情况都试了，关键是服务端访问google这些支持ipv6的网站时并没有自动走ipv6）

ps：pc端的v2rayn则无论哪个版本都无此问题

### 复现方法
1.手机端使用1.1.10时，访问google等网站，服务器会自动走ipv6通道连接google
2.然后升级到1.1.11时，服务器访问google变成走ipv4通道了
3.降级到1.1.10则一切正常，再次走回ipv6通道

### 日志信息
<details>

</details>

### 环境信息
服务端v2ray 4.21.3 (有ipv6地址，使用UseIpv6策略，dns 8.8.8.8和1.1.1.1)
android客户端 1.1.11(开启优先走ipv6流量，客户端与服务端本身通过ipv6连接也没问题)

### 额外信息（可选）
目前解决方案，android客户端切换会1.1.11以前的版本，则一切正常

**Comment by 2dust** [comment]
把你的配置email给我或tg组里面找管理员
理论上这个版本没有修改ipv6的东西,只不过是做了个端口的设置而已

**Comment by 2dust** [comment]
感谢你的反馈,我测试了下,确实有这个问题,等修复

**Comment by 2dust** [comment]
[v2rayNG_test.apk.zip](https://github.com/2dust/v2rayNG/files/3856645/v2rayNG_test.apk.zip)
下载这个测试反馈

**Comment by emiyalee1005** [comment]
刚又测试了一次，发现问题了，通过google play store从1.1.10更新到1.1.11就会出现这问题，但是如果是直接从github下的1.1.11版本就不会又问题

现在有个疑问，google play store上的版本和github上的版本是一致的吗？因为google play store很多时候会提示我v2rayng有更新，所以就从上面更新了，但现在看两个渠道下的版本运作上有点不一样。还是说这个是其他人clone这个工程源码私自发布的源码？？？

**Comment by emiyalee1005** [comment]
[https://ibb.co/7CBpph1](url)

1.1.10是我从github这下的，google play也会提示我可以更新，这个是刚才又试了一次，从google play更新的就会又问题。

**Comment by 2dust** [comment]
你下载 https://github.com/2dust/v2rayNG/files/3856645/v2rayNG_test.apk.zip
gp上面的匹配版本可能和你自己下载的有不同吧
因为app打包的时候,因为要分版本,所以这个版本ID是很大的一个数值,如果你从github上下载的是统一版,可能gp还是会提示更新

**Comment by emiyalee1005** [comment]
ok 我试下

**Comment by emiyalee1005** [comment]
> 你下载 https://github.com/2dust/v2rayNG/files/3856645/v2rayNG_test.apk.zip
> gp上面的匹配版本可能和你自己下载的有不同吧
> 因为app打包的时候,因为要分版本,所以这个版本ID是很大的一个数值,如果你从github上下载的是统一版,可能gp还是会提示更新

这个版本没问题，ipv6正常了

**Comment by Kissycat** [comment]
最新版这个bug似乎又出现了...
