### ISSUE TITLE
安卓端v2rayNG无法打开whatsapp和telegram

### ISSUE THREAD

**Issue by cpyb** [2dust/v2rayNG#1752]
### 预期行为
打开whatsapp和telegram

### 实际行为
安卓端v2rayNG可以正常开网页、开youtube、play商店等，
geo已经更新至最新，全局模式，
无法打开whatsapp和telegram，显示 connecting 或者连接中。

### 日志信息
安卓端不知道该怎样获取日志

谢谢

**Comment by LYZ10** [comment]
同样的问题，请问您解决了吗？

**Comment by sahar741** [comment]
Okk

**Comment by sahar741** [comment]
Hi
