### ISSUE TITLE
希望v2rayNG可以支持ss的obfs功能，就像v2rayN一样，否则不能连接部分节点。

### ISSUE THREAD

**Issue by SakuraChanNya** [2dust/v2rayNG#1756]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
    可以正常连接ss-obfs节点
### 实际行为
描述实际发生了什么
    实际上只有Windows的v2rayN支持连接ss-obfs节点
### 复现方法
1.v2rayN截图：
[img]https://p.kamept.com/73ec652bba2a127ee5098a538614110d-Full.webp [/img]
2.v2rayNG截图：
[img]https://p.kamept.com/01baaa84179c8bed428fe5f89c15bf3e-Full.webp [/img]

### 日志信息
<details>

</details>

### 环境信息
Android12+Windows11 21H2

**Comment by fastdream2** [comment]
赞同，希望作者大人能给加上。

**Comment by LYAN0526** [comment]
赞同，今天新买了节点发现用不了，折腾半天才知道ng不支持obfs...希望尽快能有这个支持哇
