### ISSUE TITLE
［分流问题］系统开启“阻止不经过vpn的连接”后，v2rayng“分应用代理”-不代理的应用无连接。

### ISSUE THREAD

**Issue by luis1111111111** [2dust/v2rayNG#1761]
Android 12

系统vpn设置开启“阻止不经过vpn的连接”情况下， 由ng规则分流直连的地址可以直连，但通过“分应用代理”设置不代理的应用无连接。如果关闭“阻止不经过vpn的连接”，“分应用代理”中设置不代理的应用可以直连。

我希望通过开启“阻止不经过vpn的连接”来应对“手机刚启动未解锁状态下vpn不会自动连接，但wifi/数据会自动连接”造成的泄漏。因为即便系统vpn设置开启“常开vpn”，在解锁前vpn也不会自动连接，只有解锁后vpn才会自动连接。

V2rayng分流直连倒是可以在开启“阻止不经过vpn的连接”的状态下让规则设置为直连的连接直连，但规则难以收纳所有需要直连的地址，且如果国内应用测试/访问国外地址会被规则分流走代理，导致代理路径暴露给该应用，并且该应用功能也有可能出现异常。

另外vxin一类国产应用长期和ng一起使用会有问题吗？

**Comment by yuhan6665** [comment]
It is working as expected as far as I can tell

**Comment by luis1111111111** [comment]
> It is working as expected as far as I can tell


Maybe the behavior is by design, but it's undesirable in my case. 

Instead of getting blocked, I'm hoping that the "bypassed" apps in "per-app proxy" can access Internet directly, since the domains and IPs in "custom rules"'s related section can still access internet directly with the system VPN setting "block connections without VPN" turned on.

And after power on/restart the device, before unlock the device, while the VPN/NG won't connect automatically before the unlocking, the WiFi and mobile data seem to be able to connect automatically, which probably will cause massive connection leak without "block connections without VPN" turned on.

And I'm trying to minimize the human intervention, so toggling airplane mode manually is not an option.
