### ISSUE TITLE
How to bypass proxy for some specified domains?

### ISSUE THREAD

**Issue by agn-7** [2dust/v2rayNG#1764]
How can I not use the proxy for some kind of domains in v2rayNG app? Actually, I say there is a section in settings named router setting and I added the following pattern to bypass proxy for that into the direct section but it doesn't work:

```
*.ir
```

In fact, I want to bypass the proxy for all websites that have `.ir` postfix domain.

**Comment by yuhan6665** [comment]
Try `domain:ir`

**Comment by agn-7** [comment]
@yuhan6665 

It worked. But the problem is, in this case, I should add thousands of domains containing `.ir` suffix.
Is there a smart solution for example using `regex` pattern to catch them?

**Comment by yuhan6665** [comment]
I think it should work for all domain end with .ir so no regex is needed. We does support for regex though. Please refer to documentation for details
https://xtls.github.io/config/routing.html#routingobject

**Comment by agn-7** [comment]
@yuhan6665 thank you for your instant response. At the end of the documentation you sent, I found a way to bypass the proxy for all domains ending with `.ir`. To do that, you just need to add `.ir,` into the <kbd>Settings</kbd> --> Custom rules (Routing) --> <kbd>Direct URL it IP</kbd>

**Comment by goldensky67** [comment]
Thank you for this solution. it works for me. is there any solution for V2rayN for desktop?

**Comment by agn-7** [comment]
@goldensky67 I have no idea about V2rayN but I proposed a regex method for Nekoray [here](https://github.com/WeAreMahsaAmini/FreeInternet/blob/main/guides/vmess/how-to-connect.md#3--optional). Maybe the process would be the same in V2rayN as well. Give it a try.

**Comment by mahansalimi** [comment]
> Thank you for this solution. it works for me. is there any solution for V2rayN for desktop?

for windows v2rayng : got to setting-> Option setting-> system Proxy setting and write *.ir ,then all ir websites will not use proxy.

for android v2rayng :setting - >  custom ruls -> Direct url or IP - add "domain:ir" and save


برای پراکسی نشدن  سایت های ایران با دامنه IR در v2rayng به روش بالا عمل کنید.

**Comment by rezamilani** [comment]
can we add more websites to bypass after the *.ir? if so is there a specific way to do it?

**Comment by agn-7** [comment]
@rezamilani 

you can add a comma (`,`) after `.ir` and place the respective URL or URL pattern:

```
.ir, domain:ir, example.com,
```

**Comment by mahansalimi** [comment]
> can we add more websites to bypass after the *.ir? if so is there a specific way to do it?

Its better to use :
android v2rayng :setting - > custom ruls -> Direct url or IP - add "geoip:ir" and save
Also update geoip database from  v2rayng - Geo assets files and push update icon above page.

**Comment by QMahyar** [comment]
can we bypass a process`?
or a application in windows?

**Comment by SamPourrahim** [comment]
> can we bypass a process`? or a application in windows?

For Windows Follow this:
1. 
![1](https://github.com/2dust/v2rayNG/assets/126234854/8d06d662-3704-4cbd-abc6-892955e5696c)

2. in global section >> click add rules 

![2](https://github.com/2dust/v2rayNG/assets/126234854/23e89f65-3ee4-4ddc-bb7b-2a81c2ea5866)

3. set outbound tag on **Direct**  and put the domain name in the first column 

![3](https://github.com/2dust/v2rayNG/assets/126234854/439002dc-3473-4172-987c-6ab47df589d0)


4. **make sure this rule should be above the default rule as you see in the second img.**

**Comment by rezamt1991** [comment]
is it possible to proxy only 1 url address ?
all others urls on direct and specific urls just through proxy!

**Comment by a2z05** [comment]
> is it possible to proxy only 1 url address ? all others urls on direct and specific urls just through proxy!

I have this issues with discord.gg domain

**Comment by mezhgano** [comment]
I will leave it here for those who new to rules syntax like me.

All you need to understand how to wrote specific domain rules is this part of documentation:
[https://xtls.github.io/en/config/routing.html#ruleobject](https://xtls.github.io/en/config/routing.html#ruleobject)

Scroll to "domain" section.

So, to bypass (or proxy) all domains that contains a word, for example, **amazon**, you just type word **amazon** and that's it!
Not **domain:amazon**, because it will lead to different behavior (read the link above).

For example:

Adding bypass rule **domain:amazon**
Restarting service and visit [https://checkip.amazonaws.com](https://checkip.amazonaws.com)
Result: It shows VPN server IP (Not works as expected)

Modifying rule to just plain **amazon**
Result: It shows my direct IP (Gotcha!)

**Comment by hossein2408** [comment]
How about android apps?

**Comment by sinjimbe** [comment]
How about android apps?

**Comment by SamPourrahim** [comment]
> is it possible to proxy only 1 url address ? all others urls on direct and specific urls just through proxy!

**YES!** Just change the direct and proxy outboundtag in image below and instead of that website put your desire URL 
![n10](https://github.com/user-attachments/assets/26e9da8d-d0ec-4e86-a3f2-7cd68b67dec8)

**Comment by pooria-ebrahimi** [comment]
Hello, good morning. I want to direct the LinkedIn app from my phone so that LinkedIn Direct opens and no proxy is used.

**Comment by pezhmn46** [comment]
How can i use exception app (exe) on windows

**Comment by Gholamrezadar** [comment]
Just want to note one of my mistakes.
putting a / (slash) at the end of the url doesn't work!
good: `varzesh3.com`
bad: `varzesh3.com/`
