### ISSUE TITLE
关于分组的一些改进意见

### ISSUE THREAD

**Issue by xixiri** [2dust/v2rayNG#1771]
1，订阅分组设置界面，希望每个订阅条目可以加个更新按钮，可以单独更新此订阅，因为有时候不想全部更新所有订阅
2，现在关闭程序再打开后，分组过滤又默认是全部节点了，每次都要重新过滤，希望能够记住当前分组过滤，下次打开还是这个分组

**Comment by xiebruce** [comment]
其实像小火箭那样做一个分组列表，每个分组可以展开和关闭，分组上设置一个 更新按钮 多好啊
