### ISSUE TITLE
[功能建议]建议加上routeonly选项

### ISSUE THREAD

**Issue by Extreme-Icer** [2dust/v2rayNG#1779]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
对于使用adguard进行DNS解析的用户来讲，v2rayNG因为使用xray内核，开启流量探测可能会二次解析，而xtls文档提供了一种方法，通过inbound里sniffer子项的routeonly来解决这个问题。它可以在前置dns能够解析的情况下，流量嗅探得到的结果仅用于分流，发出去仍为IP。对于自建节点用户很友好，可以自定义配置，而机场用户则只能拿出单个节点来处理。

### 实际行为
开启流量探测可以分流但是会二次解析。

### 复现方法
无。

### 日志信息
<details>
None
</details>

### 环境信息
Android10，SM-N950N,V2rayNG1.7.26

**Comment by Extreme-Icer** [comment]
@2dust 这个添加是跟PC版本一致的，开启流量探测、设置入站规则asis、开启routeonly即可。可以考虑1.8版本添加或者未来版本添加。 配置参考v2rayN issue #2799

**Comment by xiaorong61** [comment]
adguard 代理改成 socks5 试试

**Comment by Extreme-Icer** [comment]
> adguard 代理改成 socks5 试试

Android可以，不过routeonly的作用是避免二次解析，直接用adguard的解析结果

**Comment by xiaorong61** [comment]
我是关掉了 v2rayNG 的流量探测，可能会对域名分流有影响。

**Comment by Extreme-Icer** [comment]
> 

嗯是的。IP有的时候不如域名来的得劲（
