### ISSUE TITLE
一加6 安卓9 使用per-app 模式 只有youtube客户端无法被代理

### ISSUE THREAD

**Issue by chilejiang1024** [2dust/v2rayNG#178]
一加6 安卓9 使用per-app 模式 只有youtube客户端无法被代理
不想使用全局代理, 因为好多app不适合使用全局代理

### 预期行为
youtube客户端可以通过代理上网

### 实际行为
youtube客户端无法上网

### 复现方法
1. 设置per-app模式
2. 设置per-app里的app全局代理
3. 打开youtube

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by wangshengxin1998** [comment]
你的youtube客户端是不是刚刚安装的?

**Comment by SR2k** [comment]
一加6T H<sub>2</sub>OS (Android 10) 可复现，情况一致

开启分应用代理 YouTube 无限菊花，关闭分应用代理后 YouTube 就正常了

**Comment by chilejiang1024** [comment]
> 你的youtube客户端是不是刚刚安装的?

不是 好久之前 买手机的时候装的

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/203
