### ISSUE TITLE
wiki ??

### ISSUE THREAD

**Issue by LeOS-GSI** [2dust/v2rayNG#1782]
Where can I find the wiki. The link in readme isn't working

**Comment by cuynu** [comment]
https://github.com/2dust/v2rayNG/wiki

**Comment by cuynu** [comment]
damn

**Comment by LeOS-GSI** [comment]
thx, but I still don't know how to start 'Proxy Mode only'. This is TrackerControl, which acts as VPN
![proxy](https://user-images.githubusercontent.com/2726574/202737729-b6c70e89-dc78-4b33-b496-693f058ec8a2.jpg)
