### ISSUE TITLE
xray 的quic 无法上网

### ISSUE THREAD

**Issue by majia1984** [2dust/v2rayNG#1783]
xray 用的1.6.1和1.6.4 

电脑版的quic可以正常使用

android 的quic 无法使用。版本1.7.26

**Comment by chika0801** [comment]
不是软件问题，你研究下在NG里怎么填

**Comment by majia1984** [comment]
一模一样的配置，电脑可以使用quic，苹果手机可以使用，android v2rayNG不能用。

**Comment by lolitakon** [comment]
是的，我也遇到同样问题，V2RayN和Shadowrocket都正常使用，但是V2RayNG却无法正常使用，TLS握手都无法正常进行，不知道什么原因，使用vless+quic与TLS，并且双方配置都是正确的。

**Comment by lolitakon** [comment]
是的，我也遇到同样的问题，V2RayN和Shadowrocket都正常使用，但是V2RayNG却无法正常使用，quic握手无法正常进行，不知道是什么原因，使用vless+quic与TLS，并且双向配置都是正确的，可能是V2RayNG对quic握手没处理好？
