### ISSUE TITLE
io 读或者写管道被关闭

### ISSUE THREAD

**Issue by cantonJoneslone** [2dust/v2rayNG#1785]
![Screenshot_2022-11-19-01-06-27-396_com v2ray ang](https://user-images.githubusercontent.com/97668367/202766045-82b51fc7-1a53-4144-82c6-e1ba56dba74f.jpg)
#

**Comment by Mahmuod51** [comment]
> ![Screenshot_2022-11-19-01-06-27-396_com v2ray ang](https://user-images.githubusercontent.com/97668367/202766045-82b51fc7-1a53-4144-82c6-e1ba56dba74f.jpg)
