### ISSUE TITLE
Play商店 DF-DFERH-01问题探究

### ISSUE THREAD

**Issue by falcolee** [2dust/v2rayNG#179]
油管、chrome正常上网看视频
经大量搜索得知该问题由services.googleapis.cn这个域名被解析到了谷歌中国导致

### 复现步骤
1.自定义规则:代理添加 domain:services.googleapis.cn, 或者添加domain:googleapis.cn
2.断开重新连接

### 预期行为
选择绕过局域网及大陆地址，play商店可以正常联网

### 实际行为
无论全局亦或是绕过大陆地址
启动play商店后DF-DFERH-01错误，无法正常下载应用
而SSRR直接用默认配置开启分应用绕过局域网和大陆地址，可完美使用play商店

### 环境信息
节点:v2ray 日本，加密auto，伪装none，tcp传输
版本:Android 10
机型:1+7T
分应用:chrome/play商店/play服务/油管等
域名策略:IPIfNonMatch
未启用本地DNS
### 额外信息（可选）

![2A9BAA50-B4BA-425C-99FA-0D6A1E7E5455](https://user-images.githubusercontent.com/4252835/69330175-6bfebc80-0c8d-11ea-994d-1a7bd48d5754.png)
![Jietu20191121-183232](https://user-images.githubusercontent.com/4252835/69330189-71f49d80-0c8d-11ea-8560-764391e7238f.jpg)
![Jietu20191121-183251](https://user-images.githubusercontent.com/4252835/69330200-7620bb00-0c8d-11ea-9795-74624618a8fc.jpg)

**Comment by 2dust** [comment]
开启本地dns 时 ,services.googleapis.cn 会被硬处理
清空play的缓存并重启设备试一试

**Comment by muyufan** [comment]
楼主我也是，以前好好的，最近忽然用了一下play发现怎么弄怎么设置折腾都无法避免这个错误，其他什么国外app，网站都无问题可以翻墙。哎 感谢楼上建议，重启手机就没问题了
