### ISSUE TITLE
[优化建议] 为uTLS功能设置默认选项

### ISSUE THREAD

**Issue by real-Shigure** [2dust/v2rayNG#1797]
### 预期行为
客户端在未主动设置uTLS选项时，应默认设置为下拉菜单中的某一项，以进一步提升伪装程度。

### 实际行为
客户端在未主动设置uTLS选项时，此项为空（未选中任何选项）。

### 复现方法
添加任何支持uTLS功能的节点后，编辑节点信息，即可看到uTLS项为空

### 日志信息
*此issues可能无需日志*

### 环境信息
使用运行安卓9.x的模拟器进行测试

### 额外信息（可选）
这一建议主要是考虑到部分不会主动设置uTLS的用户：当用户未设置uTLS时，他们的流量特征可能较为显著，借助uTLS可以提升伪装，降低被阻断的可能。

**Comment by siampour** [comment]
Can we add utls or fingerprint to vless links?

**Comment by redstoneleo** [comment]
https://github.com/v2fly/v2ray-core
9个小时前v2ray也开始支持utls了，希望跟进，谢谢！
