### ISSUE TITLE
自定义配置的 DNS 配置无效

### ISSUE THREAD

**Issue by rubnet** [2dust/v2rayNG#18]
如图 DNS 走 v2rayNG 默认的1.1.1.1 ![Screenshot_2019-06-19-20-04-48-941_com.evbadroid.wicap.png](https://i.loli.net/2019/06/19/5d0a257325ae535379.png)
自定义的 DNS 配置
![Screenshot_2019-06-19-20-11-04-763_com.v2ray.ang.png](https://i.loli.net/2019/06/19/5d0a2687728eb30709.png)
版本及设置如下图所示，未启用本地 DNS
![Screenshot_2019-06-19-20-14-46-411_com.v2ray.ang.png](https://i.loli.net/2019/06/19/5d0a276a5017463110.png)

**Comment by 2dust** [comment]
自定义的配置已经和NG无关了,都是core自己的行为,您只能再折腾了
