### ISSUE TITLE
请问能否加入绕过局域网的功能？

### ISSUE THREAD

**Issue by FengkuiChan** [2dust/v2rayNG#18]
开着V2RayNG，登不进路由器后台。
我真的太懒啦。

**Comment by FengkuiChan** [comment]
上次提了一下tasker，马上就更新了，给力啊。虽然app未推出自动随系统启动，但可以通过tasker实现。已捐赠8.99刀，期待持续添加新功能。

**Comment by 2dust** [comment]
多谢捐赠.局域网理论上默认是绕过的,等我测试下

**Comment by FengkuiChan** [comment]
@2dust 我的路由地址是192.168.199.1，用V2RayNG无法登录，用Shadowsocks可以，或者关闭V2RayNG也可以。

**Comment by FengkuiChan** [comment]
@2dust 换成192.168.1.1也不行。

This page isn’t working

192.168.1.1 didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by FengkuiChan** [comment]
顺便说一下，绕过大陆也是失效的，网页打开淘宝直接跳国际版。怀疑是不是这个绕过都是失效的。

**Comment by 2dust** [comment]
收到,感觉上是geo这个加入的有点问题,等我测试后调整

**Comment by 2dust** [comment]
测试下0.3.1

**Comment by FengkuiChan** [comment]
昨晚更新后试了一下，可以正常局域网了。也可以播放优酷视频，绕过大陆应该生效了。
