### ISSUE TITLE
v2ray配置动态端口后，PC端能连，而手机端连接速度下降明显

### ISSUE THREAD

**Issue by AndyChao-83** [2dust/v2rayNG#180]
### 预期行为
v2ray服务器端配置了动态端口，希望PC端和手机端有一定提速

### 实际行为
PC端貌似连接提速了（实际提速貌似也不太明显），但是手机端，明显连接速度下降

### 复现方法
在v2rayNG操作“点击测试”，一直提示“失败：io:read/write on closed pipe”

### 日志信息
以下是手机v2rayNG的部分日志信息，还请大神解析
<details>

- 11-23 13:40:44.219 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 67 Err: connection refused
11-23 13:40:44.221 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 69 Err: connection refused
11-23 13:40:44.223 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:44.368 I/GoLog   (32650): udp:127.0.0.1:43556 accepted udp:1.1.1.1:53 [proxy] 
11-23 13:40:44.368 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:15501
11-23 13:40:44.736 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:44.820 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:13524
11-23 13:40:44.822 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:13524
11-23 13:40:44.824 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:15501
11-23 13:40:44.986 I/GoLog   (32650): Using Prepared: x.x.xx.xx
11-23 13:40:45.067 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 68 Err: connection refused
11-23 13:40:45.077 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 69 Err: connection refused
11-23 13:40:45.078 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 63 Err: connection refused
11-23 13:40:45.867 I/GoLog   (32650): [Warning] [4212804032] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [connection refused] > v2ray.com/core/common/retry: all retry attempts failed
11-23 13:40:45.877 I/GoLog   (32650): [Warning] [3820189329] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [connection refused] > v2ray.com/core/common/retry: all retry attempts failed
11-23 13:40:45.879 I/GoLog   (32650): [Warning] [1684082729] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [connection refused] > v2ray.com/core/common/retry: all retry attempts failed
11-23 13:40:46.571 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:13524
11-23 13:40:46.572 I/GoLog   (32650): udp:127.0.0.1:43002 accepted udp:172.217.10.2:443 [proxy] 
11-23 13:40:46.889 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:46.889 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:13524
11-23 13:40:47.196 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:47.398 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:15501
11-23 13:40:47.708 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:48.109 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:15501
11-23 13:40:48.421 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:49.022 I/GoLog   (32650): Not Using Prepared: tcp,x.x.xx.xx:13524
11-23 13:40:49.288 I/GoLog   (32650): fdConn unix.Connect err, Close Fd: 62 Err: connection refused
11-23 13:40:50.089 I/GoLog   (32650): [Warning] [4212804032] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [connection refused] > v2ray.com/core/common/retry: all retry attempts failed
</details>

### 额外信息（可选）
另外附上服务器端的config.json配置文件，是仿照一些网上的文章设置的，不知道是否设置有问题。

`{
  "inbounds": [{
    "port": 35598,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
          "level": 1,
          "alterId": 64
        }
      ],
      "detour": {
          "to": "dynamicPort"   
        }
    }
  },

 {
      "protocol": "vmess",
      "port": "10000-20000", 
      "tag": "dynamicPort",  
      "settings": {
        "default": {
          "alterId": 64
        }
      },
      "allocate": {           
        "strategy": "random",  
        "concurrency": 2,     
        "refresh": 3          
      },
      "streamSettings": {
        "network": "kcp"
      }
    }
 ],

  "outbounds": [{
    "protocol": "freedom",
    "settings": {}
  },{
    "protocol": "blackhole",
    "settings": {},
    "tag": "blocked"
  }],
  "routing": {
    "rules": [
      {
        "type": "field",
        "ip": ["geoip:private"],
        "outboundTag": "blocked"
      }
    ]
  }
}
`

**Comment by 2dust** [comment]
此app不支持动态端口
