### ISSUE TITLE
how can use subscription feature  in v2rayNG?

### ISSUE THREAD

**Issue by BenyaminMoadab** [2dust/v2rayNG#1804]

**Comment by aminmazi** [comment]
create an http/https endpoint and in the response put the list of vmess/vless/etc connections. each line should contain one connection and the whole response should be base64 encoded.

https://liolok.com/v2ray-subscription-parse/

**Comment by lambdaxyzt** [comment]
vless not working ! you sure ?

**Comment by llaravell** [comment]
@lambdaxyzt i think only supported (vmess, ss, socks) only
and you must put in an array then encode to base64.
Not sure...

**Comment by aminmazi** [comment]
It supports every connection
Just look at the below example
The url response(first textbox) should be base64 encoded of the connection URIs (second text box)

![Screenshot_2023-02-14-18-53-02-232-edit_com android chrome](https://user-images.githubusercontent.com/10259426/218781677-c77f8a2f-d9b5-4e26-b49d-87936ec6445a.jpg)

**Comment by llaravell** [comment]
@aminmazi you mean no need to put them in array?
Cause 

> create an http/https endpoint and in the response put the list of vmess/vless/etc connections. each line should contain one connection and the whole response should be base64 encoded.
> 
> https://liolok.com/v2ray-subscription-parse/

This url example i think put them in an array

**Comment by aminmazi** [comment]
> @aminmazi you mean no need to put them in array?

Not an array
Just put each connection uri in a separate line, then encoded the entire string to base64

```
vless://domain.com/blabla
vmess://domain com/blabla
```

**Comment by arminhasanzade1** [comment]
vless://domain.com/blabla
vmess://domain com/blabla
