### ISSUE TITLE
hi battery consumption on 

### ISSUE THREAD

**Issue by alireza1385mamani** [2dust/v2rayNG#1806]
there is a hi batory consumption on samsung galecxy a72 on andriod12. please fix it as soone as possible. thanks.

**Comment by cuynu** [comment]
That's normal behavior, not an issue

**Comment by alireza1385mamani** [comment]
Really but actually I haven't seen a VPN used over 15% of my battery

**Comment by mahdi-mz** [comment]
I have the the same issue on Galaxy A73.
Please fix it. Thanks.

**Comment by danirzv** [comment]
I'm using a pixel 8 pro and it takes 42% of the battery in 5 Hours how it could it be a normal behavior
