### ISSUE TITLE
增加节点下载速度测试

### ISSUE THREAD

**Issue by yanwave** [2dust/v2rayNG#1809]

**Comment by PanHsin** [comment]
即 测试 服务器速度的功能，早就有了

**Comment by youkai666** [comment]
> 

老哥能看一下上面的，我的问题吗

**Comment by yanwave** [comment]
> 

电脑端我知道有，手机端的只看见测试ping的

**Comment by yanwave** [comment]
> > 
> 
> 老哥能看一下上面的，我的问题吗
你搜机场再加些关键词有很多的，PC版里面也有推荐

**Comment by yanwave** [comment]
> 即 测试 服务器速度的功能，早就有了

电脑端我知道有，手机端的只看见测试ping的
