### ISSUE TITLE
基于xray的x-ui搭建的节点，所有协议均失效

### ISSUE THREAD

**Issue by linxi1158** [2dust/v2rayNG#1816]
贵开发，基于xray的x-ui搭建的节点，trojan、vless、vmess测试均无效，但同样的节点，v2rayn、shadowrockers有效，望解决此bug.
vps: 搬瓦工vps
系统：debian-10-x64
搭建节点协议以及导出：x-ray协议的x-ui面板搭建节点，通过链接导出
测试的协议：(均未使用443端口)
      1. vless+ws+tls
      2. vmess+ws+tls
      3. trojan+xtls
      4. trojan+tls

**Comment by linxi1158** [comment]
v2rayNG测试版本：1.7.27

**Comment by chika0801** [comment]
如果你遇到问题，你应该尝试

XTLS VISION（TCP）
https://github.com/chika0801/Xray-examples/tree/main/VLESS-TCP-XTLS-Vision

Hysteria（UDP）
https://github.com/chika0801/hysteria-install

TUIC（UDP）
https://github.com/chika0801/tuic-install

**Comment by ChiefHYK** [comment]
我也遇到了这个问题，系统提示
Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > infra/conf: both file and bytes are empty.
但是我查看了x-ui下的config.json文件是有用户信息的，后面把暂时把tls选项关闭了，测试可用，大概率应该是证书的问题，时间关系没继续往下测试了

**Comment by aawwsslll** [comment]
一样的问题。v2rayn能用，但是v2rayng用不了，
提示：io：read/write on closed pipe.
具体配置是： xtls-rpxrx-vision - tcp + tls 
同样的配置在电脑端可用，不知道问题出在哪。xray版本1.6.4， v2rayng版：17.26

————————编辑------
看来是证书问题，设置把跳过证书验证改为true可以用了。

**Comment by linxi1158** [comment]
> 一样的问题。v2rayn能用，但是v2rayng用不了， 提示：io：read/write on closed pipe. 具体配置是： xtls-rpxrx-vision - tcp + tls 同样的配置在电脑端可用，不知道问题出在哪。xray版本1.6.4， v2rayng版：17.26
> 
> ————————编辑------ 看来是证书问题，设置把跳过证书验证改为true可以用了。

确实将证书验证设置改为true就可以，👍

**Comment by linxi1158** [comment]
> 看来是证书问题，设置把跳过证书验证改为true可以用了。



> 我也遇到了这个问题，系统提示 Failed to start: main: failed to load config files: [bin/config.json] > infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > infra/conf: both file and bytes are empty. 但是我查看了x-ui下的config.json文件是有用户信息的，后面把暂时把tls选项关闭了，测试可用，大概率应该是证书的问题，时间关系没继续往下测试了

看来是证书问题，设置把跳过证书验证改为true可以用了。

**Comment by Mydong** [comment]
除了上面的方法外。将x-ui的 xray 切换到低版本，也可以解决；

![image](https://user-images.githubusercontent.com/14023137/222065772-1568a208-307e-4115-a52b-2e1007242460.png)

**Comment by netfreshman** [comment]
有没有大神指导一下，我用X-UI建的节点，用的443的端口，可以在苹果的小火煎/安卓的v2rayNG上上网，但是win的v2rayN就不行，安卓的clash也不行，这个是什么原因啊
