### ISSUE TITLE
start service failure

### ISSUE THREAD

**Issue by MojtabaIsfahani** [2dust/v2rayNG#1818]
Hello
In Xiaomi Mi A3, Android 11 when try to connect (when pressed V button), show this Toast message:
start service failure.
Please help
Thanks

**Comment by wreck2build** [comment]
I'm having the same issue, did you find any solution?

**Comment by MojtabaIsfahani** [comment]
When I run NapsternetV and then run V2rayNG, this issue occured.
I was rest my phone, and try again.

**Comment by Mehdibaseri** [comment]
I think napsternetv have the issues with v2rayng
Because last night i install napsternet and since last night v2rayng not work

**Comment by soearkar1** [comment]
https://github.com/2dust/v2rayNG/issues/1818

**Comment by mahpooya** [comment]
My problem was an already used port. I force closed all my VPNs and "start service failure" never happened again.
