### ISSUE TITLE
Not conection

### ISSUE THREAD

**Issue by rezamihandoost** [2dust/v2rayNG#1839]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by rezamihandoost** [comment]
I am from Iran and I paid for using this software in Iran, but it was stopped after 20 days from today

**Comment by rezamihandoost** [comment]
What should I do? Please help. Thanks.

**Comment by NimaaZx** [comment]
> I am from Iran and I paid for using this software in Iran, but it was stopped after 20 days from today



> What should I do? Please help. Thanks.

defiantly you have to contact to the guy who sell the v2ray account to you. It is not related to developer issue . in country like Iran the most reliable v2ray, vmess, vless accounts are the ones you configure and run on your VPS server. it might be tough for Non-specialists . sometimes like these days in Iran there is DNS problem on network .

**Comment by DariushMazlumi** [comment]
Hi @rezamihandoost.
Imagine buying a glass bottle to hold liquids and some milk from a convenience store. you go home, pour the milk into the bottle and find it rotten. now whom would you blame? the store whom you bought the container from, or the store you bought the milk? v2rayNG is the container here. simply put, its application is to provide a proxy connection from your device to the provided server. THEY ARE NOT A PROXY PROVIDER. hence, please contact the same store/salesperson whom you paid for your configuration. by the way, this app is completely FREE on Google Play Store, so you didn't pay the developer anything.
