### ISSUE TITLE
ws bug

### ISSUE THREAD

**Issue by goodjimli** [2dust/v2rayNG#184]
![image](https://user-images.githubusercontent.com/19948103/69590705-4e35ac80-102b-11ea-8971-09413be82d0c.png)
![Screenshot_20191126_085446 36](https://user-images.githubusercontent.com/19948103/69590812-ac628f80-102b-11ea-80f4-935e5397c0a8.jpg)
 情况是这样，做了一个v2ray 服务端的代理拦截。前期，iOS，Windows，openwrt 开启 mux(路由复用)，websocket的连接数基本都是1~2个每个终端。
但是到了android， 我在google play 下载了3个不同的客户端，ws 传输协议的连接数都巨高。开始40多，后面维持到20多个连接数。这不是http 这种短连接啊，对服务器来说要命。
发现3个android客户端（v2rangNG Kitsunebi bifostv）情况一样，要不是同一个人，就是用的是同一个jdk的问题。

期望结果 在 ws 协议下，有限的ws连接。

**Comment by 2dust** [comment]
请去core那边提交
