### ISSUE TITLE
xray 已修复mux历史问题：取消下载文件后流量还会继续跑，是时候添加mux选项了。

### ISSUE THREAD

**Issue by devwak** [2dust/v2rayNG#1853]
xray 已修复mux使用历史遗留问题：取消下载文件后流量还会继续跑，见

https://github.com/XTLS/Xray-core/pull/1417
https://github.com/XTLS/Xray-core/commit/3e4e0503133edbd12f10ebd9ea5931c5df5cacfe

搜了下本issu, 移动端不适合mux ?   请加上mux选项，客户选择可好

**Comment by 2797613519** [comment]
支持˃ʍ˂，希望开发者添加

**Comment by codetang-2417** [comment]
希望开发大大加入mux功能，因为最近好像不太稳定，总是断流，想通过减少tcp连接的方式，尽量使线路稳定一些
