### ISSUE TITLE
v2rayng doesnt work in operagx

### ISSUE THREAD

**Issue by VirUssaldo** [2dust/v2rayNG#1863]
i connect to a v2ray server and it works well, but when i try to go to a site it says i dont have internet connection even tho other apps work well with this server but only operagx doesnt work and idk what to do

**Comment by Mahdikore** [comment]
Mahdiii

**Comment by jojo1364** [comment]
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpYczlPUlQ0ajY1YjhIcmVacmcwcEAxODUuMTYwLjI2LjkxOjE2NjQ=#1358(@Outline_Vpn)

**Comment by jojo1364** [comment]
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpYczlPUlQ0ajY1YjhIcmVacmcwcEAxODUuMTYwLjI2LjkxOjE2NjQ=#1358(@Outline_Vpn)

**Comment by jojo1364** [comment]
> من به یک سرور v2ray وصل می شوم و خوب کار می کند، اما وقتی می خواهم به یک سایت بروم می گوید من اتصال اینترنت ندارم حتی برنامه های دیگر به خوبی با این سرور کار می کنند اما فقط operagx کار نمی کند و نمی دانم چه کار کنم
