### ISSUE TITLE
0.6.4比0.6.3上下行速度慢了很多

### ISSUE THREAD

**Issue by la8896** [2dust/v2rayNG#187]
0.6.3下行95M上行85M速度,
更新到0.6.4后下行只有50M,上行只有70M
三星Note 8和華為Mate 10也出現同樣速度下降情況

**Comment by CoolCollin** [comment]
同样，比061慢更多。以前061下行可以300m，现在只有60m左右，以前远比bifrostv快，现在不行了，再加上配置文件导入总是莫名其妙无法使用，又用回了bifrostv。

**Comment by 2dust** [comment]
测试下0.6.5版本
另外配置文件启用了新版的配置,需要在inbouds里面的socks端口固定为10808

**Comment by la8896** [comment]
0.6.5版本回復正常速度了,謝謝您
