### ISSUE TITLE
测速

### ISSUE THREAD

**Issue by laoasl** [2dust/v2rayNG#187]
大佬 , 有没有可能将pc端的v2rayN的"批量节点测速"(不是测延迟)功能移植到v2rayNG , 手机端无论安卓还是iOS好像还没有app能做到这一点 , 你要是办成了就是唯一.

**Comment by 2dust** [comment]
那样得浪费多少流量
另外测速还是用专业软件好,只要能真联通即可

**Comment by laoasl** [comment]
> 那样得浪费多少流量
> 另外测速还是用专业软件好,只要能真联通即可

我没表达清楚 , 我想要测速功能的目的其实不是为了测速 , 而是为了**方便快速的找出机场里速度相对快些的节点** , 打个比喻的就是方便我在"矮子里面挑将军" . 当然 , it's up to you. 毕竟v2rayN/G这两个软件感觉已经近乎完美了 , 感谢大佬的辛勤付出!
