### ISSUE TITLE
Dns-over-Https for VPN DNS

### ISSUE THREAD

**Issue by msshn** [2dust/v2rayNG#1874]
Please add support for DNS-over-Https in "VPN DNS" setting
Currently only IPv4/6 DNS address can be set.

**Comment by Amirazimi864** [comment]
https://github.com/2dust/v2rayNG/issues/1874#issue-1511985835

**Comment by Amirazimi864** [comment]
> Please add support for DNS-over-Https in "VPN DNS" setting Currently only IPv4/6 DNS address can be set.
