### ISSUE TITLE
Dns not working with ad blocking dns

### ISSUE THREAD

**Issue by Zenith727** [2dust/v2rayNG#1877]
The dns work for sometime then die not send any request to the dns server like pihole or ad guard

**Comment by Amin2460** [comment]
I confirm this too.
It seems like dns stops working after sometimes.
May I ask how you're testing your ad blocking DNS?
In YouTube or another app?

**Comment by Zenith727** [comment]
Im trying load webpage and youtube with pihole and checking pihole logs but no request send to it

**Comment by Amin2460** [comment]
So at the first minutes some requests are made but after that it stops sending requests? Or it doesn't send request at all?

**Comment by Zenith727** [comment]
No it working fine for random number of day then after that it stopped sending dns request to the server tried to turn off and on clear cache but not working but changing the server worked

**Comment by Zenith727** [comment]
Werid
