### ISSUE TITLE
SS协议无法在不支持udp的服务器上使用

### ISSUE THREAD

**Issue by llllllllqq** [2dust/v2rayNG#188]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常链接不支持udp的服务器并解析dns（就像ss官方客户端不开udp转发一样）

### 实际行为
无法解析dns

### 复现方法
1.默认设置（本地dns和流量探测随意设置不影响结果）
2.链接ss协议节点，此ss服务器不支持udp
3.打开任意网站，比如youtube，dns解析失败

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
日志见附件，倒数第二次启动和之前的数次是udp不支持的服务器，最后一次是udp支持的服务器
[1.txt](https://github.com/2dust/v2rayNG/files/3906663/1.txt)

```
</details>

### 环境信息
安卓9  miui11

**Comment by 2dust** [comment]
这个问题好像遇到过,暂时无解
如果vps是你自己的,请改成vmess
如果不是,请用ss原版吧

**Comment by eastcukt** [comment]
这个问题还是存在，上面很多关于ss转发不通的issues都是因为这个原因造成的
