### ISSUE TITLE
同样的v2ray节点，小米中国大陆版系统能连，国际版系统连不上咋回事？

### ISSUE THREAD

**Issue by kingsi01** [2dust/v2rayNG#1887]
原先手机和电脑都能连，小米手机升级了国际版系统后就连不上了？电脑是可以正常连的，别的手机测试也可以正常联网。只是这部升级国际版系统后的手机不行，但是用别的节点试过，可以连上。自己搭建的连不上，显示：失败，context deadline exceeded。v2rayN 是在官网下的。

**Comment by lemocn** [comment]
+1,redmi note 7 miui10,欧版

**Comment by zylx0532** [comment]
荣耀V30 PRO /鸿蒙 2.0.0.278
荣耀Magic3PRO  /Magic UI 6.0.0.151
同样问题
经过测试
1.两部手机都是四川电信流量/四川电信宽带下的WIFI 无法使用
2.两部手机任意一部开热点，另一部手机连接热点后通过热点  可以使用

**Comment by h4rvey-g** [comment]
+1

**Comment by yogkin** [comment]
Check to see if the system time is correct

**Comment by smddgz** [comment]
> 原先手机和电脑都能连，小米手机升级了国际版系统后就连不上了？电脑是可以正常连的，别的手机测试也可以正常联网。只是这部升级国际版系统后的手机不行，但是用别的节点试过，可以连上。自己搭建的连不上，显示：失败，context deadline exceeded。v2rayN 是在官网下的。

我装的原生安卓，把手机时间改为24小时制就可以了，你可以试试看。
