### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by Jace-317** [2dust/v2rayNG#1891]
### 日志信息

--------- beginning of main
01-05 23:20:52.483 D/com.v2ray.ang(12744): https://rss.okggrss.buzz/link/mDrZPXGb6CLKmue2?mu=2
01-05 23:20:53.362 W/System.err(12744): java.net.SocketException: Connection reset
01-05 23:20:53.362 W/System.err(12744): 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
01-05 23:20:53.362 W/System.err(12744): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
01-05 23:20:53.362 W/System.err(12744): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
01-05 23:20:53.362 W/System.err(12744): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
01-05 23:20:53.362 W/System.err(12744): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
01-05 23:20:53.363 W/System.err(12744): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
01-05 23:20:53.363 W/System.err(12744): 	at com.v2ray.ang.util.Utils.getUrlContentWithCustomUserAgent(Utils.kt:387)
01-05 23:20:53.363 W/System.err(12744): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:498)
01-05 23:20:53.363 W/System.err(12744): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
01-05 23:20:53.363 W/System.err(12744): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by nonme13** [comment]
同样是更新订阅失败，不知道开发者什么时候可以修复问题
![屏幕截图 2023-01-08 222706](https://user-images.githubusercontent.com/122214300/211201872-d468ee96-67b4-448e-ac68-c933e14d9194.jpg)

**Comment by q874709551** [comment]
> 同样是更新订阅失败，不知道开发者什么时候可以修复问题 ![屏幕截图 2023-01-08 222706](https://user-images.githubusercontent.com/122214300/211201872-d468ee96-67b4-448e-ac68-c933e14d9194.jpg)

我刚遇到这种情况 你的解决了吗
