### ISSUE TITLE
1.7.32 升级安装问题，以及节点配置"uTLS"项迁移问题

### ISSUE THREAD

**Issue by ebzeueg** [2dust/v2rayNG#1897]
1. 已安装 1.7.31 版本，安装 v2rayNG_1.7.32.apk 时提示安装失败。
失败原因：无法降级安装。之前版本升级时没出现过此类问题。

2. 节点配置文件中的 “uTLS” 项设置无法随导出迁移，
每次更新节点后都需要手动重新设置。

**Comment by 2dust** [comment]
v2rayNG_1.7.32.apk此版本只能覆盖v2rayNG_1.7.31.apk这样的版本，不能覆盖带cpu架构的版本

**Comment by 2dust** [comment]
uTLS没有标准分享格式，无法导出

**Comment by ebzeueg** [comment]
> v2rayNG_1.7.32.apk此版本只能覆盖v2rayNG_1.7.31.apk这样的版本，不能覆盖带cpu架构的版本

我之前只下载安装不带cpu架构名称的版本，一直都如此。
看到回复后，**我尝试了安装带cpu构架名称的版本，结果安装成功了。**给遇到问题的朋友参考一下。

---------------
update: 找到原因了：手机中手动安装的版本被google play后台自动更新了，导致手动下载的版本不再适用。
