### ISSUE TITLE
模拟器上运行闪退

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#190]
作者你好 我将源码放到 Android Studio 运行 
实机运作正常 但模拟器上运行到连线那一步却会闪退

我又尝试将最新版的apk 装到模拟器上却成功运行
是否是最新版的apk 与 源码lib上的aar不一样呢？
如果可以 可否提供 最新版的aar？
非常谢谢你

**Comment by 2dust** [comment]
不支持模拟器

**Comment by ispboy** [comment]
kitsunebi-android成功在模拟器上运行
