### ISSUE TITLE
0.6.5版本打开fb，ins网页版都比0.6.4慢很多

### ISSUE THREAD

**Issue by ZPaulZzz** [2dust/v2rayNG#191]
我用同一节点来回安装卸载好几次   发现这个问题   之前包括0.6.3都相对慢   就0.6.4没问题   我看core好像不一样   4.9明显

**Comment by ZPaulZzz** [comment]
4.9明显快  0.6.5用的是4.1版本? 这个不是啥大问题   我就是提一下   看看最新版是否考虑core用4.9版本的

**Comment by 2dust** [comment]
这个应该是dns的问题
你试一试开启本地dns
不行的话用0.6.4先

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/192
