### ISSUE TITLE
建议可选将 v2rayNG 作为系统 HTTP 代理以避免 Chrome 导致 DNS 泄露。目前为仅作为系统 SOCKS5 代理

### ISSUE THREAD

**Issue by slusludy** [2dust/v2rayNG#1916]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
可选在开启 v2rayNG 的服务后，将 v2rayNG 在本机开设的 HTTP 代理服务器作为系统 HTTP 代理。

### 实际行为
开启 v2rayNG 服务后，只有 v2rayNG 在本机开设的 SOCKS5 代理服务器被作为系统代理。
即使仅将 v2rayNG 设为系统 SOCKS5 代理， `curl` 、 Telegram 、推特和 Via 浏览器等软件也不会导致 DNS 泄露。
仅将 v2rayNG 设为系统 SOCKS5 代理后用 Chrome 翻墙，Chrome 的 DNS prefetch 功能一定会直连 1.1.1.1 的 UDP 53 明文查询要翻墙访问的域名，导致 DNS 泄露。
如果将 v2rayNG 作为系统 HTTP 代理，那么 Chrome 不会导致 DNS 泄露，但这样会导致 Chrome 无法用 QUIC 从 Bilibili 的 CDN 下载音视频，这个特征可能意味着用户在用翻墙软件，但也比 DNS 泄露要好些。

### 复现方法
1.v2rayNG 的预定义规则设为“绕过局域网及大陆地址而后代理”，自定义规则全空，启动本地 DNS 和虚拟 DNS，SOCKS5 代理服务器和 HTTP 代理服务器监听的端口分别为 `10808` 和 `10809`，然后开启 v2rayNG 的 VPN 功能，手机连接 WiFi
2.在手机用 root 权限执行 `tcpdump -i any -v /sdcard/capture.txt` 来给手机的无线网卡抓包
3.在手机用 Chrome 访问 https://www.google.com
4.停止抓包，可以从抓包得到的文件中搜索到从手机无线网卡向 1.1.1.1 UDP 53 发出的解析 www.google.com 的数据包（ DNS 泄露），和从 127.0.0.1 向 TCP 127.0.0.1:10808 发出的 TLS 握手数据包（ SOCKS5 代理）
5.root 权限执行 `settings put global http_proxy 127.0.0.1:10809` ，来将 v2rayNG 作为手机的系统 HTTP 代理
6.再次开始抓包、 Chrome 访问 https://m.youtube.com 、停止抓包，抓包得到的文件里不再出现 DNS 数据包（无 DNS 泄露），有从 127.0.0.1 向 TCP 127.0.0.1:10809 发出的 TLS 握手数据包（ HTTP 代理）

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by slusludy** [comment]
复现方法第二条里的抓包命令写错了，应该改为 `tcpdump -i any -v -n > /sdcard/capture.txt`

**Comment by rurirei** [comment]
what is a system proxy (mode), you said?

the only way is that you should forward all dns requests with **tun(2socks)** and **dns** outbound of v2ray.

**Comment by slusludy** [comment]
> what is a system proxy (mode), you said?

I mean Android system-wide HTTP proxy, just like [Clash for Android](https://github.com/Kr328/ClashForAndroid) does.
![Clash System HTTP Proxy](https://user-images.githubusercontent.com/101031963/216998380-be4b05c7-98a3-42ea-ad61-111ae8c09c87.jpg)


> the only way is that you should forward all dns requests with **tun(2socks)** and **dns** outbound of v2ray.

Sorry, I made a mistake that in fact v2rayNG doesn't set itself as the system SOCKS5 proxy but set up tun2socks.
It's good if all TCP and UDP packages go to TUN, but in fact Chrome will cause plain UDP DNS lookup packages to 1.1.1.1 passing through the physical network interface if there's only tun2socks but no system-wide HTTP proxy, no matter whether the domain to visit has hit any route rules.

**Comment by rurirei** [comment]
i wonder what is the approach of system-wide HTTP proxy.

**Comment by slusludy** [comment]
> i wonder what is the approach of system-wide HTTP proxy.

I guess Clash for Android implemented system-wide HTTP proxy with [`android.net.VpnService.Builder.setHttpProxy`](https://developer.android.com/reference/android/net/VpnService.Builder#setHttpProxy(android.net.ProxyInfo)) in [this line of code](https://github.com/Kr328/ClashForAndroid/blob/04efed17afd8de5c35c700cd3aba03f055ffd025/service/src/main/java/com/github/kr328/clash/service/TunService.kt#L193). I'm not familiar with developing Android APPs.

**Comment by rurirei** [comment]
>> Sets an HTTP proxy for the VPN network. This proxy is only a recommendation and it is possible that some apps will ignore it. PAC proxies are not supported.

not available for dns forwarding.

> > i wonder what is the approach of system-wide HTTP proxy.
> 
> I guess Clash for Android implemented system-wide HTTP proxy with [`android.net.VpnService.Builder.setHttpProxy`](https://developer.android.com/reference/android/net/VpnService.Builder#setHttpProxy(android.net.ProxyInfo)) in [this line of code](https://github.com/Kr328/ClashForAndroid/blob/04efed17afd8de5c35c700cd3aba03f055ffd025/service/src/main/java/com/github/kr328/clash/service/TunService.kt#L193). I'm not familiar with developing Android APPs.

**Comment by slusludy** [comment]
> not available for dns forwarding.
When HTTP proxy is on, APPs using HTTP protocol such as Chrome and Google Play Store won't issue DNS requests but just tell HTTP proxy server what domain it wants to visit. tun2socks can be turned on at the same time, forwarding DNS requests issued by other APPs not using HTTP protocol such as online games. Just like Clash for Android does: TUN and system-wide HTTP proxy are turned on at the same time, leading all APPs bypassing GFW and not causing DNS leak, but only makes QUIC unavailable for browsers.

**Comment by slusludy** [comment]
> not available for dns forwarding.

When HTTP proxy is on, APPs using HTTP protocol such as Chrome and Google Play Store won't issue DNS requests but just tell HTTP proxy server what domain it wants to visit. tun2socks can be turned on at the same time, forwarding DNS requests issued by other APPs not using HTTP protocol such as online games. Just like Clash for Android does: TUN and system-wide HTTP proxy are turned on at the same time, leading all APPs bypassing GFW and not causing DNS leak, but only makes QUIC unavailable for browsers.

**Comment by rurirei** [comment]
you could simply forwards udp 53 all data to the outbound dns-out, and always disable the secure dns query of chrome.

**Comment by rurirei** [comment]
you could simply forwards udp 53 all data to the outbound dns-out, and leaves disabled the secure dns query of chrome always.

**Comment by slusludy** [comment]
> forwards udp 53 all data to the outbound dns-out

Just dropping all packages towards `1.1.1.1` UDP 53 is OK. My ISP blocked `1.1.1.1`, which doesn't matter that Chrome can bypass GFW when system-wide HTTP proxy server isn't set. But root privilege is required, meanwhile most users don't have root privilege.

I really don't know how to disable DNS prefetch of Chrome, Edge and Firefox on Android and Windows, googled a lot.

I recommend [Via Browser](https://play.google.com/store/apps/details?id=mark.via.gp) and [X Browser](https://play.google.com/store/apps/details?id=com.xbrowser.play) but not Chrome to my friends when using v2rayNG. None of my friends has get root privilege.

**Comment by rurirei** [comment]
>> But root privilege is required, meanwhile most users don't have root privilege.

android vpn services depends on its method AddDNSServer() as the dns query is upto some like "8.8.8.8:53" (as vpn dns address setting provided inside v2rayng) then you wouldn't use root privileged.

**Comment by rurirei** [comment]
>> I really don't know how to disable DNS prefetch of Chrome, Edge and Firefox on Android and Windows, googled a lot.

chrome://flags, edge://flags, etc.

**Comment by slusludy** [comment]
v2rayNG used `AddDNSServer()` [here](https://github.com/2dust/v2rayNG/blob/90636bb294bc9b46cc5582d93a66737773ee0fae/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L138) but Chrome DNS leak still exists.

Seems like newest Chrome canceled the function to disable DNS prefetch.
![search "dns" in chrome://flags in Android Chrome](https://user-images.githubusercontent.com/101031963/224553444-88fe8aea-4cea-4235-8740-e2620c9b2a3e.jpg)

Hope I can commit code to v2rayNG after some study.

**Comment by rurirei** [comment]
>> Seems like newest Chrome canceled the function to disable DNS prefetch.

no worry to just forwards the udp 53 all data to some like a custom dns server.

**Comment by rurirei** [comment]
>> v2rayNG used AddDNSServer() [here](https://github.com/2dust/v2rayNG/blob/90636bb294bc9b46cc5582d93a66737773ee0fae/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L138) but Chrome DNS leak still exists.

maybe there's the wrong testing or configuration you made.
