### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by OghabTeam** [2dust/v2rayNG#1918]
Why some configurations do not work in this program but are connected in other programs?!
like this:

vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJFTUUiLAogICJhZGQiOiAib2doYWItdnAuY2YiLAogICJwb3J0IjogNDQzLAogICJpZCI6ICJiYTg1MjM3Mi03YjZmLTRjMGYtZGQ0Zi01OGUyZTI5NjhiN2UiLAogICJhaWQiOiAwLAogICJuZXQiOiAidGNwIiwKICAidHlwZSI6ICJodHRwIiwKICAiaG9zdCI6ICIiLAogICJwYXRoIjogIi8iLAogICJ0bHMiOiAidGxzIgp9

**Comment by OghabTeam** [comment]
please fix this problem, thanks ❤️‍🩹

**Comment by sanvkarm** [comment]
> Why some configurations do not work in this program but are connected in other programs?! like this:
> 
> vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJFTUUiLAogICJhZGQiOiAib2doYWItdnAuY2YiLAogICJwb3J0IjogNDQzLAogICJpZCI6ICJiYTg1MjM3Mi03YjZmLTRjMGYtZGQ0Zi01OGUyZTI5NjhiN2UiLAogICJhaWQiOiAwLAogICJuZXQiOiAidGNwIiwKICAidHlwZSI6ICJodHRwIiwKICAiaG9zdCI6ICIiLAogICJwYXRoIjogIi8iLAogICJ0bHMiOiAidGxzIgp9

**Comment by OghabTeam** [comment]
> > Why some configurations do not work in this program but are connected in other programs?! like this:
> > vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJFTUUiLAogICJhZGQiOiAib2doYWItdnAuY2YiLAogICJwb3J0IjogNDQzLAogICJpZCI6ICJiYTg1MjM3Mi03YjZmLTRjMGYtZGQ0Zi01OGUyZTI5NjhiN2UiLAogICJhaWQiOiAwLAogICJuZXQiOiAidGNwIiwKICAidHlwZSI6ICJodHRwIiwKICAiaG9zdCI6ICIiLAogICJwYXRoIjogIi8iLAogICJ0bHMiOiAidGxzIgp9

what?!

**Comment by sanvkarm** [comment]
jfgjj bhhjggm

در تاریخ شنبه ۱۴ ژانویه ۲۰۲۳،‏ ۲۱:۳۵ MahdiTohidi ***@***.***>
نوشت:
