### ISSUE TITLE
v2rayng启用ipv6优先后会屏蔽双栈网站的v4解析结果

### ISSUE THREAD

**Issue by wxg1015** [2dust/v2rayNG#1919]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
我家里的宽带是双栈公网(国内) 我v4/v6都用相同域名做了ddns  我在上边启用了一些服务   比如emby 我是启用了ipv6的8096端口   transmission启用了ipv4的9091端口
然后我想实现的是在打开 优先ipv6 后  我不需要关闭v2rayng的情况下可以同时访问以上两个服务(关闭v2rayng情况下是可以的)
### 实际行为
实际情况是 我一旦启用v2rayng的优先ipv6   那我就只能访问emby服务 他只开启了ipv6端口的   transmission则不行 它只开启了v4端口
  换言之  v2rayng强制只解析了v6 ip 或者说强制只用ipv6访问  当域名解析结果有ipv6时

### 环境信息
安卓13

**Comment by laaArmy** [comment]
你是什么系统？
