### ISSUE TITLE
请问最新版不支持安卓7.1.2吗？

### ISSUE THREAD

**Issue by Suitear** [2dust/v2rayNG#1923]
有一个电视盒子，安卓版本是7.1.2，安装最新的几个版本，比如1.7.34，都是显示连接成功，但是测试出现如图错误。
![CDA21342-8873-4240-AFA5-1C0E10A61D44](https://user-images.githubusercontent.com/9960618/212607852-12fed228-f4f2-4f1d-981d-e9add7a04e5b.jpeg)

或者请问支持7.1.2安卓的最后一个版本是什么呢？

**Comment by 2dust** [comment]
支持
你这是节点挂了
