### ISSUE TITLE
自定义规则的匹配顺序

### ISSUE THREAD

**Issue by azuo** [2dust/v2rayNG#1925]
自定义规则包含代理、直连和阻止三个部分，目前它们的的优先级顺序是先匹配代理，然后匹配直连，最后匹配阻止。但这个顺序在某些情况可能会产生问题：

例如，使用黑名单模式，将预定义规则设为“全局直连”，同时将自定义规则的代理设为“geosite:google”。此时如果还想屏蔽google的广告，或是保持部分可以直连的google服务（比如mtalk*.google.com或fonts.googleapis.com等），在自定义规则中填写相应的阻止或直连规则都是无效的。这种情况下，自定义规则的匹配顺序应为“阻止、直连、代理”更为合理。

是否可以加入调整自定义规则的匹配顺序的功能？或者加入选项可以按需选择不同的匹配顺序？

**Comment by jiuqianyuan** [comment]
面临同样的问题，比如直连域名被包含进了代理规则中（如apple中国域名被包含进了代理规则geosite:geolocation-!cn），根本无法调整。建议采用v2rayN的高级路由模式，可增减预定义规则集，并灵活修改规则集内规则。

最好把日志也整一下，把域名显示出来，直接显示ip很难排查。

02-14 20:21:33.861 I/GoLog   (13096):tcp:127.0.0.1:44500 acceptedtcp:142.250.72.238:80 [socks -> proxy]
