### ISSUE TITLE
新功能建议：一键删除重复连接

### ISSUE THREAD

**Issue by Elecleus** [2dust/v2rayNG#1930]
部分节点名称虽然不同，但是IP或URL是一样的，这样会占用列表的空间，也（可能？）会在一键测试时占用更多资源，希望可以一键删除重复的连接

**Comment by EzSync** [comment]
Good suggestion!

**Comment by deeplee** [comment]
good idea I also need it

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.2

**Comment by Elecleus** [comment]
@2dust 现在的功能并不像我曾设想的那样。只有名称不同但其他属性都相同的两个连接应该被视为重复的，而不是像现在这样，只有完全相同才会被删除。

**Comment by deeplee** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/1.8.2

this version delete duplicate means all meta same!

not only host and port same ==>This is I  means same, and nedd this
