### ISSUE TITLE
show traffic usage in remarks

### ISSUE THREAD

**Issue by MG-Token** [2dust/v2rayNG#1931]
hi
its possible to show traffic usage or sniff in remarks (Alias)?
like:
(USAGE: $flow/20GB)
or
(USAGE: $pref_sniffing/20GB)

**Comment by Moladoogh** [comment]
> hi
> its possible to show traffic usage or sniff in remarks (Alias)?
> like:
> (USAGE: $flow/20GB)
> or
> (USAGE: $pref_sniffing/20GB)
