### ISSUE TITLE
使用WIFI时通知栏无标志

### ISSUE THREAD

**Issue by wangp-blog** [2dust/v2rayNG#1939]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
打开WIFI的情况下，连接v2ray，应该有一个VPN的标志

### 实际行为
描述实际发生了什么
实际上手机上方并没有该标志

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
vivo z1 Android12

### 额外信息（可选）
此外，安卓手机通知栏无法正常控制v2rayng，如关闭状态下，点击图标无法变亮，实际上已打开。开启情况下，图标点击（此时仍为灰色）会关闭节点连接。

**Comment by wangp-blog** [comment]
这个bug是我自己设置的问题吗

是否需要补充其他信息

**Comment by 2dust** [comment]
图标等是手机系统控制，app无关

**Comment by wangp-blog** [comment]
> 图标等是手机系统控制，app无关

谢谢答复
