### ISSUE TITLE
how to use geoip

### ISSUE THREAD

**Issue by hamidtb** [2dust/v2rayNG#1944]
hi
how i can use geoip in v2rayng app to avoid proxy specific country ip?

**Comment by amid11** [comment]
In the settings, under `Routing` section, select `Custom rules`, tap on `Direct URL or IP ` tab. There you can add your own rules, something in the form of `geoip:Country code TLD`. 

For instance, adding `geoip:cn, geoip:ru` would result a direct connection to The Chinese and Russian IPs based on your Geo Asset files.

**Comment by Bahman2580** [comment]
😂😐

در تاریخ چهارشنبه ۲۵ ژانویهٔ ۲۰۲۳،‏ ۱۸:۳۶ hamidtb ***@***.***>
نوشت:

**Comment by hamidtb** [comment]
hi
thank you for answering
I add the flowing code to custom rules->direct url or ip
geoip:ir,
domain:ir

and change domain strategy to ipifnonmatch
it seem it work for sites

but some application detect that I use vpn

any suggestions for this problem..

**Comment by WTFThatPerson** [comment]
Try to set Your local timezone equal to Your server timezone: it helps sometime...

**Comment by black-khan** [comment]
ایا من میتوانم خودم کانفیگ شخثی وارد برنامه  کنم و به کاربران خود بدم اکر میتوانم لطفا راهنمایی بفرمایید

**Comment by ssstroke** [comment]
> but some application detect that I use vpn

Apps are able to see that the VPN is working on the system, so they can easily see the fact that you use VPN, even if it is being bypassed.
