### ISSUE TITLE
VLESS+TLS+ws doesn't work with selfsigned CA

### ISSUE THREAD

**Issue by WTFThatPerson** [2dust/v2rayNG#1948]
### Version
1.7.34 (Libv24, Xray0core v1.7.2

### Server configuration
Apache2 -> V2Ray server
    |
obfuscating site

Client logs error
`failed to dial to (socket): >x509 > certificate signed by unknown authority`
while obfuscating site works OK without errors; V2Ray client on Ubuntu having exactly the same config file works OK, it's only v2rayNG problem in ws mode: when I try server configuration

V2Ray server -> Nginx -> obfuscating site

everything seems OK on v2rayNG

### Config in question
```
{
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
      {
            "port": <port>,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "sniffing": {
                "enabled": true,
                "destOverride": ["http", "tls"]
       },
            "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
            }
       }
  ],
    "outbounds": [

        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "<server>",
                        "port": 443,
                        "users": [
                            {
                                "id": "<UUID>",
                                "encryption": "none"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "none",
                "wsSettings": {
                     "path": "/<path>"
                }
            },
            "tag": "vless-tunnel"
        },
        {
            "protocol": "freedom",
            "settings": {},
            "tag": "direct"
        }
    ],
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "domain": [
                    "ext:h2y.dat:gfw"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "network": "tcp,udp",
                "outboundTag": "vless-tunnel"
            }
        ]
    }
}
```

**Comment by amid11** [comment]
Enable `Allow insecure` both in the application settings and by editing your configuration file. The long term solution would be to issue a valid SSL certification and introduce the crt and key to your server configuration.

**Comment by WTFThatPerson** [comment]
I don't think turn off TLS check is that what I need. I think, there is problem with app, which one lacks read user CAs:
We already have "valid" certificates; yes, they aren't public, but they are OK anyway. We issued our inner CA, propagated it to every device, then signed by it our servers certificates, so it's quite valid nonpublic corporate PKI. Everything works OK except given app, So, does anyone of developers add reading of user installed CAs?

**Comment by WTFThatPerson** [comment]
Definitely, app has problem with user CA access. I ended with CA content copied into "certificate": [] CertificateObject

**Comment by BabakArtist** [comment]
@amid11
