### ISSUE TITLE
如何设置开启v2rayng后安卓浏览器能够ipv6访问

### ISSUE THREAD

**Issue by sungamma** [2dust/v2rayNG#1958]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
在仅仅有v4的vps代理时，v2rayng作用于chrome的情况下，浏览器输入v6地址，能够直接访问v6地址，而不经过v2rayng。

### 实际行为
各种设置选项打开，例如设定直连的v6域名，开启v6 dns，还是不能访问v6的地址，关闭v2rayng后，可正常访问。

### 复现方法

![Screenshot_2023-01-28-23-57-15-069_com v2ray ang](https://user-images.githubusercontent.com/33790/215277721-7b96247f-9d4b-4f54-86b1-9dff5659affd.jpg)

### 环境信息
安卓13

**Comment by gdtv** [comment]
遇到同样的问题，当服务器只支持v4时，无法访问纯ipv6网站(包括国内和国外的网站)。
手机系统：安卓13原生系统，
v2rayNG版本：1.7.38
