### ISSUE TITLE
Cannot set "request host" when using GRPC

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#1963]
I noticed that when using GRPC as network, cannot set the `request host(host/ws /host/ h2/host)/QUIC security` field. The applicaton won't save it.

OS: Android
App version: 1.7.34

**Comment by Clash-zone** [comment]
> I noticed that when using GRPC as network, cannot set the `request host(host/ws /host/ h2/host)/QUIC security` field. The applicaton won't save it.
> 
> OS: Android
> App version: 1.7.34

I have the same issue
Actually the new v2rayng has some bugs
Most important bug is ssl handshake problem, it dosent allow to connect to any server
