### ISSUE TITLE
v2rayng fails to start when custom config uses geosite and geosite.dat is not updated 

### ISSUE THREAD

**Issue by emdaitaj** [2dust/v2rayNG#1966]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

when using custom configs which use geolcation ,with IRAN contry , v2rayng fails to start becuase default geolcation file does not have category-ir 
it's diffcult for non thenchical users to follow long instactions ,also you need to have an already working vpn to update geolocation (it's banned in IRAN) 
### 预期行为
描述你认为应该发生什么
1-v2rayng should have updated geolocation file, or atleast an empty geosite.dat which has only one site per country so it does not fail to start and updates geosite
2-release an version with updated geo files (i guess you don't incude in default version for makin gapk smaller ) 
3-when a custom config uses geosite and it's not updated , v2ray shoudl start instead of failing , but update the database automatically 
### 实际行为
描述实际发生了什么
v2ray fails to start when a custom config has geosite:category-ir  
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ho30hero** [comment]
I have this problem too.
