### ISSUE TITLE
google play abb bundle not work

### ISSUE THREAD

**Issue by nevisaCo** [2dust/v2rayNG#1971]
Hello, when releasing the source ، 
Debug APK works fine,
Release APK works fine 
Download APK via apk downloader  from Google play bundle works fine
but direct installation from google does not work
APKS from the bundle(edit Configuration), not works

```
            minifyEnabled false
            zipAlignEnabled false
            shrinkResources false
```

Can anyone help?

**Comment by devrx5** [comment]
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
