### ISSUE TITLE
请在订阅功能中添加一个可以认证用户名密码的功能

### ISSUE THREAD

**Issue by Tmalll** [2dust/v2rayNG#1978]
俺用nginx自建了个订阅连接并且增加了认证
用户名密码是: user:qwe123123
正常浏览器可以用: https://user:qwe123123@xxx.xxx.com:11443/v2rayN.txt 这个连接来访问, 并且不会提示让输入用户名密码.
但是v2rayNG不行.

所以希望NG可以在订阅里添加个可以输入认证用户名密码的功能, 或者支持上面这种带用户名密码的网址格式.

**Comment by Fangliding** [comment]
你这是自建方案，订阅这种统一标准的东西 修改需要合作讨论的
而且大多数解决方案一般都会在订阅链接里附带一个随机字符串作为token，这其实也就是当密码了

**Comment by Tmalll** [comment]
> 你这是自建方案，订阅这种统一标准的东西 修改需要合作讨论的 而且大多数解决方案一般都会在订阅链接里附带一个随机字符串作为token，这其实也就是当密码了

这种应该属于http自带的功能吧?   我记得很早前IE浏览器都能这么用, 我测试过隔壁clash和matsuri都是支持这种地址格式的订阅, 可以去抄下代码[狗头]

**Comment by AdrianDSW** [comment]
同希望加入这个功能，就普通的http认证就足够

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/pull/1204
有此功能

**Comment by hn-kitty** [comment]
> 俺用nginx自建了个订阅连接并且增加了认证
> 用户名密码是: user:qwe123123
> 正常浏览器可以用: https://user:qwe123123@xxx.xxx.com:11443/v2rayN.txt 这个连接来访问, 并且不会提示让输入用户名密码.
> 但是v2rayNG不行.
> 
> 所以希望NG可以在订阅里添加个可以输入认证用户名密码的功能, 或者支持上面这种带用户名密码的网址格式.

#1204 有提交此功能，但测试了下貌似这功能有问题
