### ISSUE TITLE
vmess://导入host和path栏位错误

### ISSUE THREAD

**Issue by didila** [2dust/v2rayNG#198]
### 预期行为
vmess：//链接
host导入后应该在伪装域名栏位上
path就在path

### 实际行为
{
"v": "191209",
"ps": "v",
"add": "myhostname.com",
"port": "443",
"id": "00000000-0000-0000-0000-000000000000",
"aid": "64",
"net": "ws",
"type": "none",
"host": "myhostname.com",
"path": "/data",
"tls": "tls"
}
vmess://ewoidiI6ICIxOTEyMDkiLAoicHMiOiAidiIsCiJhZGQiOiAibXlob3N0bmFtZS5jb20iLAoicG9ydCI6ICI0NDMiLAoiaWQiOiAiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwKImFpZCI6ICI2NCIsCiJuZXQiOiAid3MiLAoidHlwZSI6ICJub25lIiwKImhvc3QiOiAibXlob3N0bmFtZS5jb20iLAoicGF0aCI6ICIvZGF0YSIsCiJ0bHMiOiAidGxzIgp9

实际导入后
host保存在path栏位
导入的path内容不见了
![WechatIMG206](https://user-images.githubusercontent.com/4469206/70443675-829d7400-1ad3-11ea-96b1-f53f8fdb0658.jpeg)
### 复现方法
1.
2.
3.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

**Comment by didila** [comment]
这个说明我看过了，我就是比对了好几次，确认错误才会发issues

**Comment by 2dust** [comment]
"v": "2"

**Comment by didila** [comment]
谢谢，我发现我的问题了
