### ISSUE TITLE
[IMPORTANT] NG的xray core版本不对

### ISSUE THREAD

**Issue by Extreme-Icer** [2dust/v2rayNG#1983]
1.7.37NG客户端使用的是xray core1.7.2而非1.7.3
@2dust

**Comment by GreatMichaelLee** [comment]
同问。1.7.3的xray core我在openwrt上用的没问题啊,新的原生uTLS指纹都可以配置，不知道大佬为何回滚到1.7.2，是指纹相关的feature在app上不支持吗？
