### ISSUE TITLE
为什么只要手机上v2rayng一打开，百度贴吧app就不能看帖了？

### ISSUE THREAD

**Issue by ALG254** [2dust/v2rayNG#1984]
我也没设置为全局代理

**Comment by Leao9203** [comment]
😅老老实实的把本地 DNS 做好+分应用代理，哪来这么多jb事

**Comment by ALG254** [comment]
> 



> 😅老老实实的把本地 DNS 做好+分应用代理，哪来这么多jb事

分应用代理是个很不好的功能，就比如手机上的浏览器你是让他不翻墙呢还是翻墙呢，你让它翻了，所有的国内网站也会用的外国ip。本地dns是干啥的，不懂

**Comment by livingfree2023** [comment]
> 



> > 
> 
> > 😅老老实实的把本地 DNS 做好+分应用代理，哪来这么多jb事
> 
> 分应用代理是个很不好的功能，就比如手机上的浏览器你是让他不翻墙呢还是翻墙呢，你让它翻了，所有的国内网站也会用的外国ip。本地dns是干啥的，不懂

你打开本地DNS，然后在路由设置的”自定义规则“里面”设置默认路由规则“，最后在预定义规则里面选择绕过局域网及大陆地址
这样就解决了你的问题

**Comment by Leao9203** [comment]
> 分应用代理是个很不好的功能，就比如手机上的浏览器你是让他不翻墙呢还是翻墙呢，你让它翻了，所有的国内网站也会用的外国ip。本地dns是干啥的，不懂

![image](https://user-images.githubusercontent.com/45661339/218315398-4a13b8e5-336c-4d41-ae76-44e3e4f1ed44.png)

乐

**Comment by ALG254** [comment]
> > 分应用代理是个很不好的功能，就比如手机上的浏览器你是让他不翻墙呢还是翻墙呢，你让它翻了，所有的国内网站也会用的外国ip。本地dns是干啥的，不懂
> 
> ![image](https://user-images.githubusercontent.com/45661339/218315398-4a13b8e5-336c-4d41-ae76-44e3e4f1ed44.png)
> 
> 乐

那个分应用代理只要一开启，你就要为所有app都设置了，不可能只选择贴吧，别的都按照规则

**Comment by Shrink9** [comment]
> > 
> 
> > > 
> > 
> > 
> > > 😅老老实实的把本地 DNS 做好+分应用代理，哪来这么多jb事
> > 
> > 
> > 分应用代理是个很不好的功能，就比如手机上的浏览器你是让他不翻墙呢还是翻墙呢，你让它翻了，所有的国内网站也会用的外国ip。本地dns是干啥的，不懂
> 
> 你打开本地DNS，然后在路由设置的”自定义规则“里面”设置默认路由规则“，最后在预定义规则里面选择绕过局域网及大陆地址 这样就解决了你的问题

谢谢你的回复，真的有用！

**Comment by undefine-man** [comment]
我发现我电脑开v2rayN也无法访问百度贴吧网页版，这该如何处理
