### ISSUE TITLE
please add auto update for subscription link 

### ISSUE THREAD

**Issue by Redshado0w** [2dust/v2rayNG#1988]
please add auto update for subscription link look like surfboard and other software.

**Comment by YOUNGGUNNAA** [comment]
dadash chejuri mishe subscribtion  url add kard?

**Comment by 123asd321dsa** [comment]
> please add auto update for subscription link look like surfboard and other software.

I agree, this is really necessary.  
When adding, the user can choose to have his subscription automatically updated hourly, daily and ...
