### ISSUE TITLE
更新v2rayng 0.6.6版本后，ins和google引擎搜索显示离线

### ISSUE THREAD

**Issue by songtaoshikuang** [2dust/v2rayNG#199]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常浏览

### 实际行为
升级到v2rayng 0.6.6后，使用移动流量时ins和google引擎搜索显示离线，使用联通的wifi时ins显示离线，google引擎搜索功能恢复正常，换回0.6.4版本，功能一切正常。使用的是小米5s miui9 固件为7.0

### 复现方法
升级v2rayng0.6.6版本后，使用移动或联通wifi即可复现上述故障

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by 1arry1iu** [comment]
Same. Lineage OS 15.1 on China Mobile 4G. Works alright on China Unicorn 4G.

**Comment by chnfreeze** [comment]
同样的问题，切换到移动数据或是宽带，google.com就打不开，直接显示拒绝连接疑似被DNS污染，切换联通网络一切正常！同时处于移动网络下使用隔壁的bifrostv却能正常访问google.com，😴😎😄，只是隔壁的app耗电量大的惊人！

**Comment by songtaoshikuang** [comment]
可是换回0.6.4以及之前的版本一切正常

**Comment by pentie** [comment]
0.6.6 / 0.6.7 同样确认问题；ig内的图片只能刷出空白框。

**Comment by pentie** [comment]
第二天起来0.6.7好像又没问题了.... 是DNS缓存导致？

**Comment by songtaoshikuang** [comment]
我这边的情况是联通宽带ins显示离线，而移动数据网路则是ins和Google引擎全都离线

**Comment by pentie** [comment]
确定是DNS泄漏问题引起的，建议先使用biforstv挺着吧。让2dust专心研究一下问题和解决方案。

**Comment by 2dust** [comment]
0.6.8
