### ISSUE TITLE
1.7.38未支持对Vless协议分享链接中fq选项的识别

### ISSUE THREAD

**Issue by FranzKafkaYu** [2dust/v2rayNG#1994]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
可以正常识别

### 实际行为
未正常识别

### 复现方法
获取链接，如下所示:
vless://fdbde599-75ce-426c-cbb0-5bb32ae57a42@test.example.net:16520?type=tcp&security=tls&sni=test.example.net&flow=xtls-rprx-vision&fq=firefox#test

导入v2rayNG，通过读取剪切板进行添加，其余识别正常，但fingerprint处仍为空。

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
fingerprint 的缩写是fp

**Comment by FranzKafkaYu** [comment]
> fingerprint 的缩写是fp

sorry,my bad~
