### ISSUE TITLE
最近这软件实在是不敢恭维啊，没几个能用的不说，延迟还高

### ISSUE THREAD

**Issue by Jace-317** [2dust/v2rayNG#1997]
![Screenshot_20230209-102729.png](https://user-images.githubusercontent.com/111726159/217702015-11440084-8b65-4219-a815-91dff6978b64.png)

**Comment by Leao9203** [comment]
乐 承包了我今天的笑料

**Comment by leohougmail** [comment]
机场差怪客户端 == 拉不出屎怪茅坑臭
