### ISSUE TITLE
从默认全局代理改为绕过局域网和大陆地址后
延迟从800ms变为8000ms
从默认全局代理改为绕过大陆地址后
延迟从800ms改为4000ma

### ISSUE THREAD

**Issue by GTian5418** [2dust/v2rayNG#1999]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
默认延迟无变化

### 实际行为
延迟几倍增加

### 复现方法
1.设置→路由设置→预定义规则
2.全局代理→绕过局域网和大陆地址
2.全局代理→绕过大陆地址

### 环境信息
v2rayNG --version  1.7.34

**Comment by kvjxhjwentnwm** [comment]
我也一样,1.7.38版本,200延迟直飞4000

**Comment by GTian5418** [comment]
> 我也一样,1.7.38版本,200延迟直飞4000

开发大佬帮忙看看呀 都三周了
