### ISSUE TITLE
Any Android TV Support Plan?

### ISSUE THREAD

**Issue by sdcg1994** [2dust/v2rayNG#2]
Hi,I am an Android TV  user,but v2rayNG only support Android mobile phones, Android TV support is not good, can not choose nodes (no touch operation, not support remote control).

**Comment by poleices** [comment]
I need Android TV version too.

**Comment by 2dust** [comment]
Planning

**Comment by yuhan6665** [comment]
#300 submitted. It should fix your issue on selecting nodes.

**Comment by pewter77** [comment]
This still doesn't work. Can't hit the connect button in the bottom right for some reason. Nvidia shield of curious.

**Comment by damonZDM** [comment]
不知道新版本是否可以支持？

**Comment by arad-jahandideh** [comment]
Hello, I'm a v2rayNG user on windows & android & android tv platforms. but I can't use v2rayNG on android tv. v2rayNg in android tv is not supported and has some bugs.
please develop v2rayNG for android tv.

**Comment by leoxu1007** [comment]
same to me. really need a tv version

**Comment by amzaf** [comment]
Please consider supporting the client on Google TV

**Comment by leohaghighi** [comment]
I really need this as well

**Comment by nimamirzaalikhan** [comment]
me 2

**Comment by peymannorozimay** [comment]
Please publish v2rayng for Android TV on Google Play

**Comment by ilex2023** [comment]
I really hope that a better version of V2Ray for TV can be developed. Looking forward to it… At present, I can only use Wireguard, which is not bad, but it does not facilitate convenient traffic splitting. It’s a pity!

**Comment by osousa** [comment]
> I really hope that a better version of V2Ray for TV can be developed. Looking forward to it… At present, I can only use Wireguard, which is not bad, but it does not facilitate convenient traffic splitting. It’s a pity!

Have you tried socks5? 

Wondering if there's an "Always on VPN" on Android TV, will test it when i receive the box. 

Thanks!

**Comment by nimamirzaalikhan** [comment]
**guys FYI v2rayNG works on TV. install arm v7 if arm64 v8 did not work for you.**

**Comment by nimagift** [comment]
**guys FYI v2rayNG works on TV. install arm v7 if arm64 v8 did not work for you.**
