### ISSUE TITLE
三星 s10+ 无法使用

### ISSUE THREAD

**Issue by zzefff** [2dust/v2rayNG#20]
机型： 三星 s10+
系统： 9.0
表现：
选择节点连接后点击测速，底部提示： Attempt to invoke virtual method 'java.land.String java.net.InetAddress.toString()' on a null object reference

**Comment by yuhtloveyu** [comment]
我在用10+，我目前可以用。

我用的版本0.5.6。

**Comment by zzefff** [comment]
> 我在用10+，我目前可以用。
> 
> 我用的版本0.5.6。

我用的 0.6.17，我试试换个版本

**Comment by dingwen07** [comment]
三星的自定义配置都这样

**Comment by 2dust** [comment]
Upgrade to the latest version
Custom configuration:
socks port=10808
http port = 10809
