### ISSUE TITLE
MIUI 11，联通4g网络，无法连接V2RAY服务

### ISSUE THREAD

**Issue by dsjasonh** [2dust/v2rayNG#200]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
在4G网络下，开启V2ray后，应该正常可以翻墙

### 实际行为
无法翻墙，网络连接错误。

### 复现方法
1.关闭wifi，连接4G网络就会出现连接了也没法翻墙的问题

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

已经检查过，发现除了V2RAYNG，另一个V2RAY APP也不行。在wifi下没问题，已进入4g网络就会出现问题。
我的另一个iphone，使用shadowrocket，同一个服务器，同一个帐号，4g网络下没问题。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/203
