### ISSUE TITLE
客户端报错用不了，配置和电脑客户端一样，电脑正常，大佬帮忙看看

### ISSUE THREAD

**Issue by xdhan** [2dust/v2rayNG#2001]
前几天换了 vps，服务器安装了最新的 xray，然后手机继续用 v2rayNG,  电脑 v2rayN
但是相同配置：xtls-rprx-vision，电脑使用正常，手机就是用不了
报的错用 Google 搜没有一个结果
那几天还以为是手机客户端 xray-core 不是最新的问题，
直到昨晚看到客户端更新马上就重新安装了，结果还是报错。。
下面是错误信息，一直就是几个错误一直打印：

```
--------- beginning of main
02-09 23:03:31.296 E/com.v2ray.ang( 9290): [onConstructor]: finding createWrapPrototype() failed

02-09 23:03:31.296 E/com.v2ray.ang( 9290): [onProducerConnect]: finding bufferConnectWrapPrototype() failed

02-09 23:03:31.301 E/com.v2ray.ang( 9290): [onDequeue]: finding dequeueBufferTagWrapPrototype() failed
```
求大佬看一眼，哪里都搜不到这个问题😭

**Comment by xdhan** [comment]
提这个问题的时候还看了Issues，没找到解决办法，结果发完返回看到这个：https://github.com/2dust/v2rayNG/issues/1952#issuecomment-1407541904
试了一下，跳过证书校验设置为 true，还真好了，打扰了。。
话说这个证书校验能不能不跳过，需要把服务器证书在手机安装下吗

**Comment by Leao9203** [comment]
> 提这个问题的时候还看了Issues，没找到解决办法，结果发完返回看到这个：[#1952 (comment)](https://github.com/2dust/v2rayNG/issues/1952#issuecomment-1407541904) 试了一下，跳过证书校验设置为 true，还真好了，打扰了。。 话说这个证书校验能不能不跳过，需要把服务器证书在手机安装下吗

没有意义，老老实实买个域名申请 SSL 比啥都强。自己安装CA证书也行，但不建议不会玩证书的安，麻烦且对技术要求比较高。

**Comment by Leao9203** [comment]
@xdhan 你把这个 issue 关掉吧，没有啥意义的 issue 就不要开着了。
