### ISSUE TITLE
服務器端升級了5.2，配置文件換成了v5版本的格式，v2rayNG的TLS握手失敗。

### ISSUE THREAD

**Issue by tannx** [2dust/v2rayNG#2007]
最近幾天服務器端v2ray升級到5.2，服務器和PC端的配置文件也改成了v5版本的，手機v2rayNG的TLS握手失敗，因為v5要使用utls。我手機的v2rayNG版本是1.7.35。請問現在可以支持v5版本的配置文件嗎？

**Comment by 2dust** [comment]
不支持
