### ISSUE TITLE
Adding Capability to Subscribe for CUSTOM JSON v2ray configs

### ISSUE THREAD

**Issue by dragonfly20004** [2dust/v2rayNG#2008]
Hi. The app is already capable to subscribe to a url that contain single json v2ray config. but it seems it cannot add multiple json custom configs with single subscription url.

my proposal is adding capability to add multilpe json config with single subscription url.
like this:

custom://base64encodedjsonconfig
custom://base64encodedjsonconfig
custom://base64encodedjsonconfig
custom://base64encodedjsonconfig

thankyou.

**Comment by its0ka** [comment]
@2dust it doesn't work (i tried "custom://base64JsonConfig" in subscription and clipboard). only regular json works and only in "+ - custom config - import from clipboard/url", doesn't work in subscription

**Comment by Platway** [comment]
I'd like very much to get this feature too. I tested it in the latest v1.8.12 and it doesn't work. When I tapped on "Update subscription", a toast "Failure" was shown. I wish it could be fixed soon. Thanks for your great effort!

**Comment by AliM1988** [comment]
Please add capability to json beside URL link. Json format is needed to support fragment feature.
