### ISSUE TITLE
端口問題

### ISSUE THREAD

**Issue by la8896** [2dust/v2rayNG#201]
您好
如果伺服器端口是1080
客戶端必須把端口設置為10808才可正常連綫
但如果伺服器端口是五位數（例如33333）
客戶端應該如何設置才能正常連綫？
客戶端我嘗試用33333是無法連錢的！
但是用Bifrosv是可正常使用
我意思是導入client.json才有問題

**Comment by 2dust** [comment]
你理解错误了
10808端口是客户端的inboud端口,和你服务器无关
客户端的outbound对应你服务器的inbound
