### ISSUE TITLE
请问如何切换内核

### ISSUE THREAD

**Issue by woncode** [2dust/v2rayNG#2011]
readme页面介绍本软件支持Xray core和v2fly core内核，我想用x2ray，请问怎么切换，翻了整个设置页面都没有找到切换内核的地方，默认内核又是哪一个？

**Comment by 2dust** [comment]
The aar can be compiled from the Golang project [AndroidLibV2rayLite](https://github.com/2dust/AndroidLibV2rayLite) or [AndroidLibXrayLite](https://github.com/2dust/AndroidLibXrayLite). For a quick start, read guide for [Go Mobile](https://github.com/golang/go/wiki/Mobile) and [Makefiles for Go Developers](https://tutorialedge.net/golang/makefiles-for-go-developers/)
