### ISSUE TITLE
手机上80端口 ,报错io read/write on closed pipe

### ISSUE THREAD

**Issue by snoopy33383622** [2dust/v2rayNG#2013]
预期行为
配置了vmess tcp+http伪装  在PC上测试成功，显示Ping值，可以翻墙
在手机上用v2rayng 测试失败。

实际行为
经过测试在PC上使用80端口或其他都测试成功！
在手机上使用v2rayng 80端口报错io read/write on closed pipe，
更换其他端口就没问题。

复现方法
1.重启手机
2.卸载后重新安装

日志信息
无

环境信息
华为mate40pro   鸿蒙3系统

额外信息（可选）

**Comment by asdfghjklz9** [comment]
解决了吗？

**Comment by snoopy33383622** [comment]
搞了半天没搞懂，80端口用pc没问题，手机用v2rayng就是报错，换其他端口又能用。我另外换了台服务器用80端口，pc,手机都可以了。。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [2dust/v2rayNG] 手机上80端口 ,报错io read/write on closed pipe (Issue #2013)




 
解决了吗？

**Comment by XOAMOX** [comment]
昨天使用正常，今天突然就报这个了，另外电脑上节点正常

**Comment by Mydong** [comment]
你直接在issue中搜索 “io read/write on closed pipe”  可以找到对应的解决方法：
如果服务器时间和本地时间同步的话。按照下面就直接解决了：
1，配置里面将  跳过证书验证设置为：True，即可解决。
2，如果是xui，参考这个https://github.com/2dust/v2rayNG/issues/268
不过，我自己的xui是通过降低xray的版本，解决了；初步感觉是xray版本不兼容导致的。因为我证书是新申请的。
![image](https://user-images.githubusercontent.com/14023137/222063900-5bde383d-001e-4781-b442-51329cd43023.png)

**Comment by snoopy33383622** [comment]
好的，谢谢，我去换个xray版本试试！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月1日(周三) 下午2:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [2dust/v2rayNG] 手机上80端口 ,报错io read/write on closed pipe (Issue #2013)




 
你直接在issue中搜索 “io read/write on closed pipe”  可以找到对应的解决方法：
 如果服务器时间和本地时间同步的话。按照下面就直接解决了：
 1，配置里面将  跳过证书验证设置为：True，即可解决。
 2，如果是xui，参考这个#268
 不过，我自己的xui是通过降低xray的版本，解决了；初步感觉是xray版本不兼容导致的。因为我证书是新申请的。

**Comment by Elon-K** [comment]
https://v2rayng.en.uptodown.com/android/download/90324238
请下载低版本的v2rayNG使用，测试1.0.4的版本没这个问题

**Comment by weizhao436** [comment]
手机上 ,报错io read/write on closed pipe

**Comment by gmy123456** [comment]
现在还在报错

**Comment by shiyiqw** [comment]
我现在也有这个问题他还没修

**Comment by kuiblog** [comment]
我也是这个问题 ，刚开始可以，不知道更新了哪个版本后不行了。

**Comment by shiyiqw** [comment]
有没有可能是运营商ssl缓存的问题

**Comment by shiyiqw** [comment]
我发现在配置中设置证书跳过就可以使用
