### ISSUE TITLE
Fingerprint doesn't changed from Go-http-client/1.1

### ISSUE THREAD

**Issue by arashfereydony** [2dust/v2rayNG#2017]
I use vmess and vless with websocket
When I choose Utls, nothing is going to change on request headers User-Agent
It's always Is "Go-http-client/1.1"
I use latest version with xray core 1.75
In desktop after updating to 1.75, i have no problem and User-Agent is changing by select utls.
I think This "Go-http-client/1.1" is very easy to detect as a vpn on firewall

Anyone has same problem?
What's the solution?

**Comment by typ431127** [comment]
我也遇到了这个问题，ua没有改变

**Comment by GFW4Fun** [comment]
Fixer: https://github.com/GFW4Fun/GFW-AntiDPI-UA-Random-Patcher
