### ISSUE TITLE
Split tunneling request

### ISSUE THREAD

**Issue by MuhammadAshouri** [2dust/v2rayNG#2018]
Hi, I'm requesting split tunneling apps and IPs feature. It's a useful feature for such a great app

**Comment by iftsv** [comment]
Hello guys,
First of all, thanks for your great app.
Could you please let me know, how to setup split tunneling per apps using your app? I've installed this version https://github.com/2dust/v2rayNG/releases/download/1.9.9/v2rayNG_1.9.9_universal.apk and can't find this option ...
Thanks in advance


UPD: oh, LOL. No worries. I just need to go Settings -> Per-app Proxy and Voilà
