### ISSUE TITLE
allow_insecure

### ISSUE THREAD

**Issue by hiddify-com** [2dust/v2rayNG#2019]
I would like to request you to allow insecure flag. It is useful when we want to use domain fronting with another domain and cdn.

For example if i want to use cloudflare.com sni and use ws-host as my site,

**Comment by wyx2685** [comment]
已经有这个功能

**Comment by hiddify-com** [comment]
I know it exist but we can not use it in the share link so we can not give to the user a link with allow_insecure=true in the parameters
