### ISSUE TITLE
AndroidLibV2rayLite 可以在ios上编译成 framework使用吗？

### ISSUE THREAD

**Issue by bryant24** [2dust/v2rayNG#202]
如题，是否go代码有针对android vpn的代码？是否兼容ios呢?

**Comment by 2dust** [comment]
这个不熟悉ios,无法回答

**Comment by NetFly-VPN** [comment]
> 这个不熟悉ios,无法回答

AndroidLibV2rayLite 怎么才能编译成功呢, 我想学习一下这部分, 整到iOS上
