### ISSUE TITLE
1.7.38测试全部配置真连接速度超慢

### ISSUE THREAD

**Issue by njtony11** [2dust/v2rayNG#2027]
更新至1.7.38后测试真连接速度超慢，前几个版本速度很快

**Comment by ZhangChuan0** [comment]
现在修复这个问题没有啊，我才下载好

**Comment by 2dust** [comment]
测试的地址从http改成了https
为了安全

**Comment by cfcboy** [comment]
> 测试的地址从http改成了https
> 为了安全

你好，可以自定义测试地址用http或者https吗？我一直停留在1.7.34版本，因为测试速度会比后续版本快很多，而且https测试地址经常会出现tls错误，不好用。但是旧版本很多新功能用不了。希望新版本可以添加一下自定义功能，谢谢。

**Comment by cfcboy** [comment]
@2dust 我没有开新帖，希望作者可以看到。
