### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by iGGrk** [2dust/v2rayNG#203]
订阅链接为单条ss|base64时，端口无法读取，显示端口为0  其他所有信息正常导入
订阅链接为（单条ss\n单条vmess）|base64时，读取正常。
已排除链接格式问题。
v2rayN 2项测试均正常。

**Comment by 2dust** [comment]
测试了没有问题,请找提供者自行测试

**Comment by iGGrk** [comment]
发现是echo输出链接时自动换行问题，其他平台客户端似乎能去除解码后多余换行
