### ISSUE TITLE
关于魔改Rom汇总(Magic rom summary)

### ISSUE THREAD

**Issue by 2dust** [2dust/v2rayNG#203]
问题集中在Android10 的修改版

**Comment by revolutionxuanbei** [comment]
我也是！！！
版本Miui11.04，而且我发现隔壁kitsunsbi也没法用

**Comment by WongLP** [comment]
P20 PRO刚更新Emui10
试了第一个帖里的方法都不行
VPN内测试ping显示正常，但是切换到其它app就用不到了

**Comment by WongLP** [comment]
> P20 PRO刚更新Emui10
> 试了第一个帖里的方法都不行
> VPN内测试ping显示正常，但是切换到其它app就用不到了

解决了，下载了最新版本就可以了
百度搜apk就有了…主要是fan不了qiang不能用play store下载

**Comment by trlanfeng** [comment]
MIUI12开启绕行模式后，发现APP里显示连接成功，但系统没有启用VPN服务。
* 试验后发现，必须使“驾车场景”走代理，系统才能成功启用VPN

**Comment by ochamunaJ** [comment]
UNSUBSCRIBE ME

Thanks Management.
