### ISSUE TITLE
服务无法启动，无法使用

### ISSUE THREAD

**Issue by xyz-one** [2dust/v2rayNG#2033]
更新订阅后，每个节点都 无法使用服务，启动服务失败

**Comment by xyz-one** [comment]
已恢复

**Comment by q874709551** [comment]
> 已恢复

请问大概多久恢复的 我是更新订阅每个几点无法使用 重置订阅更新订阅失败

**Comment by q874709551** [comment]
> 已恢复

请问大概多久回复的 我是更新订阅每个几点无法使用 重置订阅更新订阅失败
