### ISSUE TITLE
建议: 在订阅分组中添加UA设置

### ISSUE THREAD

**Issue by TTsdzb** [2dust/v2rayNG#2035]
一些控制台可以记录更新分组时客户端的User-Agent，以便区分自己的不同客户端。如果能自定义更新分组时使用的UA，这个信息也可以用来判断有没有其他人盗用自己的订阅链接，或者区分自己和朋友的客户端。

在v2rayN中就有这样的设置，用户在配置订阅时可以自定义更新时使用的UA。

**Comment by rezaafzoun** [comment]
> 一些控制台可以记录更新分组时客户端的User-Agent，以便区分自己的不同客户端。如果能自定义更新分组时使用的UA，这个信息也可以用来判断有没有其他人盗用自己的订阅链接，或者区分自己和朋友的客户端。
> 
> 在v2rayN中就有这样的设置，用户在配置订阅时可以自定义更新时使用的UA。

**Comment by 2dust** [comment]
NG的UA固定为v2rayNG
