### ISSUE TITLE
华为荣耀6，连接测试出现：错误 SSL handshake timed out

### ISSUE THREAD

**Issue by Eugenejiang** [2dust/v2rayNG#204]
华为荣耀6，v2rayNG连接测试出现：错误 SSL handshake timed out. 系统Android版本是 5.1.1
同样的帐号在小米4C上用得好好的。

**Comment by qgtxqj** [comment]
那个测试在很多ROM上都会出问题，比如三星，比如MIUI的很多版本。

**Comment by Eugenejiang** [comment]
我用同样的帐号在荣耀6上安装BifrostV，运行是正常的。说明这个v2rayNG兼容性有问题

**Comment by YoulianBoshi** [comment]
比如miui官方加入了某些防翻墙的功能导致翻墙出现问题，解决方法就是刷原生或者降级ui系统

**Comment by 2dust** [comment]
无机器可以测试,这样的问题没有环境将不能解决
