### ISSUE TITLE
v2rayNG无法使用 疑似在下载内容

### ISSUE THREAD

**Issue by yuki1936** [2dust/v2rayNG#205]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

Windows端的v2rayN完全正常。

### 预期行为
描述你认为应该发生什么
通知栏莫名其妙出现下载速度，v2ray使用受影响
### 实际行为
感觉是v2ray在更新或者下载什么东西

### 复现方法
1.切换网络大概率复现
2.
![Screenshot_20191215-220030](https://user-images.githubusercontent.com/44659308/70863975-b28fc000-1f88-11ea-8cd0-9f6421574d7a.jpg)

3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
源码都在还怀疑有问题的请卸载不用即可

**Comment by yuki1936** [comment]
> 源码都在还怀疑有问题的请卸载不用即可

我在想是不是后台更新规则，另外分应用代理里面勾选v2ray会出现这个情况，昨天取消勾选v2ray后到现在还没有出现这个情况。

**Comment by 2dust** [comment]
ng没有自动更新规则或订阅等功能,所有功能都需要使用者自己使用
你可以把你的配置和log发出来看看

**Comment by yuki1936** [comment]
![Screenshot_20191216-082017](https://user-images.githubusercontent.com/44659308/70871712-f14f6580-1fdc-11ea-9bf5-43819a89da81.jpg)
![Screenshot_20191216-082021](https://user-images.githubusercontent.com/44659308/70871714-f14f6580-1fdc-11ea-82b1-8191938c3bf4.jpg)
log只有三分钟左右的，配置如图

**Comment by yuki1936** [comment]
> ng没有自动更新规则或订阅等功能,所有功能都需要使用者自己使用
> 你可以把你的配置和log发出来看看

刚才又遇到一次，
log如下
12-16 11:08:08.501 I/GoLog   (30991): [Info] [4065485935] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
12-16 11:08:08.501 I/GoLog   (30991): [Info] [4065485935] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > context canceled
12-16 11:08:08.551 I/GoLog   (30991): [Debug] [3415514096] v2ray.com/core/proxy/socks: writing back UDP response with 1209 bytes
12-16 11:08:08.583 I/GoLog   (30991): [Debug] [3415514096] v2ray.com/core/proxy/socks: send packet to udp:216.58.197.238:443 with 31 bytes
12-16 11:08:08.583 I/GoLog   (30991): [Debug] [3415514096] v2ray.com/core/transport/internet/udp: dispatch request to: udp:216.58.197.238:443
12-16 11:08:08.667 I/GoLog   (30991): [Debug] v2ray.com/core/transport/internet/kcp: #33460 sending terminating cmd.

**Comment by lixingyang-lxy** [comment]
我这也是正常使用，但就是在chrome play里面下载不了想要的软件呢？
