### ISSUE TITLE
Hp compaq7下闪退

### ISSUE THREAD

**Issue by wanghurui** [2dust/v2rayNG#205]
### 实际行为
添加服务器正常，点连接后出现v2rayng已停止运行

![screenshot_2018-12-30-19-52-42](https://user-images.githubusercontent.com/30315826/50547015-c1dd0700-0c6c-11e9-8c0b-5d930058b822.png)

### 环境信息
![screenshot_2018-12-30-19-48-33](https://user-images.githubusercontent.com/30315826/50546981-4418fb80-0c6c-11e9-9f2b-ba892df93454.png)

**Comment by 2dust** [comment]
试一试最新版,如果不行就放弃
