### ISSUE TITLE
启用本地DNS功能后个别域名解析异常

### ISSUE THREAD

**Issue by jfox52** [2dust/v2rayNG#2050]
版本 1.7.38
协议 vmess
路由模式 绕过大陆和局域网
域名策略 ipifnonmatch
启用本地dns 远程8.8.8.8 直连223.5.5.5
具体表现
访问域名为gfggfdw.0nkaz.com的网址，浏览器报错如下
无法访问此网站检查 gfggfdw.0nkaz.com 中是否有拼写错误。
DNS_PROBE_FINISHED_NXDOMAIN
单独测试直连和远程dns测试都是可以正常解析的
做过的尝试如下
修改域名策略为asis 无效
开关流量探测 无效
修改直连和远程dns地址 无效
关闭本地dns功能 正常

初步认为问题应该出在DNS路由功能，也就是软件里的启用本地DNS功能上。

日志
--------- beginning of system
--------- beginning of main
02-26 20:46:50.433 I/GoLog   (26900): 127.0.0.1:41324 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.434 I/GoLog   (26900): Not Using Prepared: udp,8.8.8.8:53
02-26 20:46:50.436 I/GoLog   (26900): 127.0.0.1:48568 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.438 I/GoLog   (26900): 127.0.0.1:45697 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.444 I/GoLog   (26900): 127.0.0.1:48940 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.445 I/GoLog   (26900): 127.0.0.1:48318 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.449 I/GoLog   (26900): 127.0.0.1:38757 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.452 I/GoLog   (26900): 127.0.0.1:39313 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.455 I/GoLog   (26900): 127.0.0.1:44690 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.457 I/GoLog   (26900): 127.0.0.1:40629 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:50.459 I/GoLog   (26900): 127.0.0.1:45912 accepted udp:8.8.8.8:53 [dns-in -> dns-out]
02-26 20:46:52.396 D/com.v2ray.ang(26900): tun2socks destroy
02-26 20:46:52.398 I/tun2socks(29513): NOTICE(tun2socks): termination requested
02-26 20:46:52.398 I/tun2socks(29513): NOTICE(tun2socks): tearing down
02-26 20:46:52.399 I/tun2socks(29513): NOTICE(tun2socks): Free TCP connections
02-26 20:46:52.403 I/tun2socks(29513): NOTICE(tun2socks): exiting
02-26 20:46:52.405 D/com.v2ray.ang(26900): libtun2socks.so exited

**Comment by suikastar** [comment]
确实有问题，我复现了，跟你表现一样

**Comment by suikastar** [comment]
https://dns.google/resolve?name=gfggfdw.0nkaz.com&type=A

https://mtool.chinaz.com/dns/?host=gfggfdw.0nkaz.com&ip=&accessmode=1

看上面的连接，这个域名国内DNS貌似没法解析，但8.8.8.8能解析，难道是这个原因导致的？
