### ISSUE TITLE
小米不让安装了

### ISSUE THREAD

**Issue by tristesky** [2dust/v2rayNG#2054]
小米手机安装的时候提示：这是违法翻墙软件。

![WechatIMG1687](https://user-images.githubusercontent.com/52591934/221765310-deac3e05-43a7-41ce-817d-51774485da0f.jpeg)

**Comment by TTsdzb** [comment]
你装不上不是因为有风险，那下面都告诉你了啊，删掉再重新装

**Comment by MYan0110** [comment]
> 小米手机安装的时候提示：这是违法翻墙软件。
> 
> ![WechatIMG1687](https://user-images.githubusercontent.com/52591934/221765310-deac3e05-43a7-41ce-817d-51774485da0f.jpeg)

进开发者选项，把MIUI优化关掉，就没这么多事了

**Comment by Mydong** [comment]
安装的时候：
1，断网安装就可以解决这个问题
2，右上角设置，关闭掉这个【应用安全检查】和【安全守护】，个人是直接关闭了。

以上省心完事

**Comment by ygtgco** [comment]
卸载重新装就完事了，我红米K40照样这么提示，哪用得着“进开发者选项，把MIUI优化关掉”，右上角那个里面有个单次风险授权安装的

**Comment by itheabyss** [comment]
这不说了是签名不同吗

**Comment by idragonet** [comment]
OPPO可以直接安装，小米垃圾系统管得太多！！

**Comment by Kavinbrown** [comment]
可以安装的，在安全中关掉电诈防护，在开发者模式中关掉MIUI优化，然后安装v2rayng, 然后打开权限设置，这时多了一个特殊权限设置，开启后，运行v2ray, 会询问增加VPN就OK了。

**Comment by HonJouHashi** [comment]
我能装能连能ping通，但为啥挂上上不去网
