### ISSUE TITLE
The config list should be sorted in reverse order

### ISSUE THREAD

**Issue by pouriaksrvi** [2dust/v2rayNG#2058]
The current ascending order of config list is not recommended by UX design principles.
Also, it is inefficient.
Because, when the list is too long, the user should scroll to the end of the list to access newly added configs.
Or the user should run a test until the end of the list, and then click sort to bring the newly added configs (which are healthy) to the top of the list.
If new configs were added to the top of the list instead of its bottom, the user wouldn't need to wait for the tests to be completed. The user could click sort button once the tests reached the 20th or 30th config. i.e. before testing all list items. Testing half of the list (or even less) is enough when the new configs are at the top of the list and get tested first.
The new added config could be tested first, instead of last. So the user wouldn't need to complete the test.
In most of the cases, the user needs its latest added configs to be clicked instantly without needing to scroll to the end of the list.
Sorting by date added in descending order is better than ascending.
In long lists, adding a new config is a nightmare. Because the user can't wait for a complete test to sort. Scrolling is hard too. (imagine a list with 1000 configs or more)

### Expected Behavior
The latest added configs should be upper in the list and should be tested first. The list should be sorted in descending order.
So the user can click on sort, after testing first 20 items of the list and not waiting for the other items to be tested.
### Actual Behavior
The first added configs are upper in the list and get tested first. The list is sorted in ascending order.
When a new config gets added it goes to the bottom of the list.
The user needs to scroll to the end of the list.
Also, for sorting the 20 or 30 healthy items which are at the top of the list, and the proxies added a moment ago, the user should wait for the test controller to test the entire list while it is not needed to test all items if the added proxies were at top. (so the user could click on sort, before testing more than half of the list)

### Reproducibility method
1. Add too many proxies so that your list becomes too long so that waiting for test to be done to the end is timely.
2. Wait a few days until their quality decreases, their ping value increases, and some of them become unavailable.  
3. Add some new healthy and fresh proxies.
4. After running a test you should wait for a lot of time until the test process reaches them, so you can sort to make them go up.
5. Or you should scroll manually to the end (a too long list) to click and connect them.
6. 4 and 5 are both hard to do. The proxies are not at the top of the list so the user can't click on sort before finishing the test.

**Comment by pouriaksrvi** [comment]
Look at how other proxy managers order their list. For example look at the internal proxy manager of Telegram Desktop as a popular one. The order is not ascending. Its the reverse.

**Comment by pouriaksrvi** [comment]
Similar issue in v2rayn: https://github.com/2dust/v2rayN/issues/3450

**Comment by aryanhv** [comment]
guys how to sort the working configs?
