### ISSUE TITLE
连接socks5 有认证代理有异常

### ISSUE THREAD

**Issue by coofo** [2dust/v2rayNG#206]
连接 gost 起的 socks5代理时如果没有添加用户认证能正常使用。
如果添加了用户认证就无法连接。
我在gost上提了issues [https://github.com/ginuerzh/gost/issues/457](https://github.com/ginuerzh/gost/issues/457)
对方的说法是

> v2rayNG支持认证，但在服务端接收认证信息时，客户端直接关闭连接了。

### 预期行为
在有用户认证的socks5代理上正常使用

### 实际行为
无法正常使用 ，服务端日志显示 EOF

### 复现方法
1.启动代理 gost.exe -D -L root:root@:31080
2.v2rayNG 配置 用户名 root 密码 root 连上
3.v2rayNG显示 io:read/write on closed pipe

**Comment by 2dust** [comment]
请用core测试下,比如在pc上直接用core测试

**Comment by coofo** [comment]
是用v2rayN-Core.zip 么？也是EOF

**Comment by wenqian0812** [comment]
> ### **[coofo](/coofo) ** commented [on 19 Dec 2019](#issue-539786241) •



> 连接 gost 起的 socks5代理时如果没有添加用户认证能正常使用。 如果添加了用户认证就无法连接。 我在gost上提了issues [ginuerzh/gost#457](https://github.com/ginuerzh/gost/issues/457) 对方的说法是
> 
> > v2rayNG支持认证，但在服务端接收认证信息时，客户端直接关闭连接了。
> 
> ### 预期行为
> 在有用户认证的socks5代理上正常使用
> 
> ### 实际行为
> 无法正常使用 ，服务端日志显示 EOF
> 
> ### 复现方法
> 1.启动代理 gost.exe -D -L root:root@:31080 2.v2rayNG 配置 用户名 root 密码 root 连上 3.v2rayNG显示 io:read/write on closed pipe

请问解决了么，刚刚也遇到了这个问题
