### ISSUE TITLE
Create a boolean option in settings for auto sort after tests

### ISSUE THREAD

**Issue by pouriaksrvi** [2dust/v2rayNG#2061]
Create a boolean option in settings which if user enables it, a sort by test result will happen automatically after a test completes.
User needs to press sort after each test. While we know it is needed to be done, most of the times.

**Comment by Hossaini11** [comment]
#2058

**Comment by pouriaksrvi** [comment]
> #2058

That's a link to my another issue. Didn't get it. Is there anything wrong with my issue?

**Comment by pouriaksrvi** [comment]
> #2058

That's a link to my another issue. Didn't get it. Is there anything wrong with my issue?

**Comment by mhmdyousefi** [comment]
hshsh

**Comment by mhmdyousefi** [comment]
shhwhw

**Comment by mhmdyousefi** [comment]
yehehe
