### ISSUE TITLE
Auto test and switch

### ISSUE THREAD

**Issue by pouriaksrvi** [2dust/v2rayNG#2065]
It would be helpful to have a config rotation feature (like proxy rotation in Telegram)

The user can enable this feature for a group or a set of configs or all of them,
So each time a config become unavailable, all configs should be tested to find a connectable config. Then, switch to the found config.
The order of "rotation tests" can be also based to the last sort which was applied to that group, so the user can sort it by "test results" (rotation tests happen many times and the results are not shown to the user. They are different than the tests which user does by clicking in test menu), so each time, the switcher starts its tests from the config which had the best result in last test which where made by the user (the better result a config had in the last test, the more chance it has to work, so it should be tested earlier)

Also a related feature: A column titled date (the date a config has been added) is needed, so the user can sort configs by date in a descending order, so the switcher starts testing from the newest (latest added) config to the oldest. (the older a config is, the less its chance it has to work, so it should be tested later)

**Comment by mortezaghaemi** [comment]
Ygh
