### ISSUE TITLE
自动断开

### ISSUE THREAD

**Issue by suo99** [2dust/v2rayNG#2070]
连接一段时间后，程序没有关闭，但是节点自动断开了，后台自动管理的，也关闭了省电优化。

**Comment by YuzhouZhang** [comment]
Logcat贴上来看看？是不是和我情况一样

**Comment by YuzhouZhang** [comment]
--------- beginning of main
03-07 15:51:47.615 I/GoLog   (28492): Not Using Prepared: tcp,223.109.146.163:443
03-07 15:51:49.732 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:51:49.746 I/GoLog   (28492): Not Using Prepared: udp,223.5.5.5:53
03-07 15:51:50.469 I/GoLog   (28492): Not Using Prepared: tcp,59.82.113.248:80
03-07 15:51:56.919 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:51:58.564 I/GoLog   (28492): Not Using Prepared: tcp,minorshort.weixin.qq.com:80
03-07 15:53:01.883 I/GoLog   (28492): Not Using Prepared: udp,112.48.116.106:443
03-07 15:53:09.234 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:53:13.484 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:53:13.519 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:53:54.095 I/GoLog   (28492): Not Using Prepared: udp,223.5.5.5:53
03-07 15:54:34.574 I/GoLog   (28492): Using Prepared: 54.192.16.193
03-07 15:54:35.276 I/GoLog   (28492): Using Prepared: 54.192.16.193
03-07 15:56:06.148 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:56:14.964 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:56:15.221 I/GoLog   (28492): Not Using Prepared: udp,36.155.214.170:443
03-07 15:56:15.482 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:56:16.057 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:56:16.262 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:57:48.983 I/GoLog   (28492): Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-07 15:57:48.997 I/GoLog   (28492): Not Using Prepared: tcp,dns.weixin.qq.com.cn:443
03-07 15:57:49.009 I/GoLog   (28492): Not Using Prepared: udp,223.5.5.5:53
03-07 15:57:58.767 D/com.v2ray.ang(28492): tun2socks destroy
03-07 15:57:58.769 I/tun2socks(13048): NOTICE(tun2socks): termination requested
03-07 15:57:58.769 I/tun2socks(13048): NOTICE(tun2socks): tearing down
03-07 15:57:58.770 I/tun2socks(13048): NOTICE(tun2socks): Free TCP connections
03-07 15:57:58.785 I/tun2socks(13048): NOTICE(tun2socks): exiting
03-07 15:57:58.801 D/com.v2ray.ang(28492): libtun2socks.so exited
