### ISSUE TITLE
是否可以添加一个功能，根据网络环境自动切换配置

### ISSUE THREAD

**Issue by haomuch** [2dust/v2rayNG#2073]
因为手机经常切换网络环境，而不同的配置在不同网络环境下延迟和速度表现可能是相反的，所以能否开发一个新功能，让软件可以根据网络环境自动切换配置，比如连接到特定WiFi网络就自动切换到配置一，连接到5G网络就自动切换到配置二

**Comment by omidpourkashi1996** [comment]
Omid.iran.ir

**Comment by omidpourkashi1996** [comment]
Omidpourkashi1996
