### ISSUE TITLE
导入两个订阅链接a与b并更新后，取消启用更新其中一个订阅a（没有删除），主界面更新订阅后，订阅a节点列表还在

### ISSUE THREAD

**Issue by Toperlock** [2dust/v2rayNG#2074]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
订阅分组里取消订阅后，主界面不显示这个订阅节点列表
### 实际行为
取消订阅a，订阅内容还会显示
### 复现方法
1.导入两个订阅链接，主界面更新订阅
2.订阅分组里取消一个订阅链接a（没有删除），主界面更新订阅
3.

### 日志信息
<details>

```
C:\Users\Administrator>adb logcat -c

C:\Users\Administrator>adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main
--------- beginning of main
--------- beginning of system
03-07 16:12:00.711  7726  7726 D com.v2ray.ang: https://sub.cute******
03-07 16:12:00.711  7726  7726 D com.v2ray.ang: https://ooi******
03-07 16:12:13.093  7726  7726 D com.v2ray.ang: https://ooi******
03-07 16:12:28.197  7726  7726 D com.v2ray.ang: https://sub.cute******
03-07 16:12:42.831  7726  7726 D com.v2ray.ang: https://sub.cute******
03-07 16:12:42.833  7726  7726 D com.v2ray.ang: https://ooi******
```
</details>

### 环境信息
MI8 MIUI 12.0.4

**Comment by janerainbow123** [comment]
你不会自己主页右上角删除全部节点？然后再去左上角订阅里勾选掉其中一个，然后再更新订阅，不就只有一个订阅的了？

**Comment by Toperlock** [comment]
订阅节点很多操作不方便

**Comment by Toperlock** [comment]
> 你不会自己主页右上角删除全部节点？然后再去左上角订阅里勾选掉其中一个，然后再更新订阅，不就只有一个订阅的了？

订阅节点很多操作繁琐

**Comment by janerainbow123** [comment]
你先右上角三个点删除全部订阅的全部节点。
然后再去左上角订阅里面取消勾选你暂时不用的订阅
最后重新更新订阅，出来的都是你勾选的订阅的节点。怎么会麻烦呢。

Toper ***@***.***> 于 2023年3月28日周二 上午9:09写道：
