### ISSUE TITLE
Its not working on android tv

### ISSUE THREAD

**Issue by mahdavimahan** [2dust/v2rayNG#2077]
Would u please make it work on Android TV

**Comment by ricky52529** [comment]
yes，it's always show the error 'v2rayng tls handshake timeout', but it's ok on my pc~ ping server ip is ok，just error in my sony tv, it's android 10.

**Comment by awaking202002** [comment]
> 

that's ok now~

**Comment by zobeirraisi** [comment]
I also have the same problem, only vless work.
the vmess is working on my phone and PC but not on the android tv; it was ok previously until recently I can not connect and get the following error:
`failed to detect internet connection: net/http TLS handshake timeout`

**Comment by mmrabbani** [comment]
It works on my android TV well. But the app is set incompatible on android TV in play store by the developer. So android TV cannot download it on google play.
When an app is installed from outside of play store, TV launcher doesn't show the app icon.

**Comment by parsibox** [comment]
> yes，it's always show the error 'v2rayng tls handshake timeout', but it's ok on my pc~ ping server ip is ok，just error in my sony tv, it's android 10.

i also exactly have this problem
what should we do ?
config on same internet is ok on PC but on android not work.( failed to detect internet connection: net/http TLS handshake timeout )

**Comment by parsibox** [comment]
Set your phone time automatically.
This solved my problem

**Comment by tkmark** [comment]
Just make sure your client and server has not too sick time unsync
