### ISSUE TITLE
Error building AndroidLibV2rayLite

### ISSUE THREAD

**Issue by sendelbor** [2dust/v2rayNG#2078]
I can't build the project
Please guide me and explain the steps in order. To understand in which step I am wrong.
The main project does not find references. What steps should be taken to build [AndroidLibV2rayLite] ?

**Comment by DanielcoderX** [comment]
Can you say where and what is your problem?
Build way is like that:
```
~> git clone https://github.com/2dust/AndroidLibV2rayLite
~> cd AndroidLibV2rayLite
~> make -j$(nproc)

# After running previous command you need to edit Makefile and change line 28 to this:
   /--- gomobile bind -v -ldflags='-s -w' -androidapi 21 github.com/2dust/AndroidLibV2rayLite ---/
# I used androidapi 21 because it's compatible with most

~> make BuildMobile -j$(nproc) 


# IF you got any error about depenecy needed run comamnd  |-- go mod downlaod --|
```
**BUT** before that you need dependency gomobile which you have to install via: `go get golang.org/x/mobile/cmd/gomobile` 

**Attention**: I've tried Go version 1.20 and 1.16 but failed you need to use version 1.17

## AND you had to create an issue at [AndroidLibV2rayLite](https://github.com/2dust/AndroidLibV2rayLite)
