### ISSUE TITLE
绕过国内/局域网，支持不太好

### ISSUE THREAD

**Issue by Cirooo** [2dust/v2rayNG#209]
Google搜索一个词条，看到某国内站点合适，如百度词条，打开它，这时候应该能直接访问才对，但很慢，我看流量，走的是代理。
app设置的是绕过局域网及国内地址，DNS 8.8.8.8，因为不区分国内外DNS，只能设置这一个，另外就是分应用代理，我用的浏览器是在代理内的，这一点没问题。
其他情况，比如我搜索飞猪，想下载飞猪app，看网址走的是阿里CDN，按理说应该是国内地址，不过还是走了代理。

**Comment by qgtxqj** [comment]
完全取决于geoip:cn和geosite:cn，想解决个例问题，请善用自定义路由。

**Comment by Cirooo** [comment]
@qgtxqj 我从别处找到个绕过本地及国内的ACL规则，可以弄过来用吧？

**Comment by Cirooo** [comment]
我回滚到0.6.7了，希望能避免偶尔拒绝代理。
然后在直连的路由规则加入一堆国内IP的范围，然后试着访问百度词条、阿里云、163，我也不清楚到底有没有绕代理，通知那里显示有流量，下载阿里云app3兆这样，观望

**Comment by Adiwon** [comment]
同样问题，DNS8.8.4.4，绕开局域网及大陆规则对部分国产应用无效，如微博国际版，微信，B站。

我发现这软件绕开规则与正常访问play似乎不能共存，修复了A问题的版本就一定会存在B问题，反之亦然。

**Comment by GavinZhengOI** [comment]
其实我觉得最好的解决方案是加入“gfw_list”的选项。按照ip来分太不稳定了。

**Comment by 2dust** [comment]
请试一试最新版,开启本地dns
本issue关闭,有问题请再开启
