### ISSUE TITLE
WS+TLS 延迟巨大

### ISSUE THREAD

**Issue by chaoxi23** [2dust/v2rayNG#209]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
改善WS+TLS性能

### 实际行为
同一配置(WS+TLS)，在PC v2rayN上测试延迟在170左右，而在手机端则是1秒左右，连的同一路由器。

### 复现方法
1.搬瓦的CN2GIA-E
2.WS+TLS+开启 网站伪装 和 路径分流

**Comment by sunnyrain1990** [comment]
我也遇到相同的情况
