### ISSUE TITLE
v2rayNG点击节点提示启动服务失败

### ISSUE THREAD

**Issue by fayewonghz** [2dust/v2rayNG#2092]
我把v2rayNG的电源管理改为无限制也没作用，手机重启，把V2rayNG都重装都没用，之前也一直没改任何配置，突然就出现这问题

**Comment by zhucoco3** [comment]
节点带XTLS了都失败，只能用TLS了。

**Comment by zj1860** [comment]
已经退回上一版了，还以为vps出了问题
