### ISSUE TITLE
流量探测导致国内网站访问缓慢

### ISSUE THREAD

**Issue by llllllllqq** [2dust/v2rayNG#210]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常打开国内网站，和打开国外网站一样快

### 实际行为
国内网站几乎打不开，加载很慢，时常net::ERR_TIMED_OUT

### 复现方法
1.打开流量探测、绕过局域网大陆、本地dns（其中dns设置为任何值都会触发bug）、关闭ipv6
2.链接任何协议任何节点（支持udp的）
3.用via浏览器（chrome也行）打开https://m.baidu.com/，速度很慢。而打开http://youtube.com/很快。

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
[log.log](https://github.com/2dust/v2rayNG/files/3997161/log.log)

```
</details>

### 环境信息
安卓9 miui11 红米note5
### 额外信息（可选）
关了流量探测立即正常。
另外链接后用nslookup 国内网站会卡住一会，而解析国外站就不卡

**Comment by hyxxsfwy** [comment]
相似的情况，Google Play 最新版本，打开流量探测后国内网站访问缓慢，如果再开启本地 DNS，国内网站直接就无法访问了。

**Comment by Sentsuki** [comment]
我也出现了这个情况，1.1.13

**Comment by 2dust** [comment]
1.1.13更新了主题颜色和core里面的geosite.dat,从理论上说是不应该发生你这种情况的
我还原core发一个版本你们测试反馈

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/213#issuecomment-568843781
