### ISSUE TITLE
小米12su无法使用

### ISSUE THREAD

**Issue by xylove-0704** [2dust/v2rayNG#2101]
miui14,可以订阅，节点也出来了，点了没用，无法连接
![Screenshot_2023-03-15-21-45-53-010_com v2ray ang](https://user-images.githubusercontent.com/127092645/225327685-1598499f-7801-4ee3-a06a-79fa66d3177a.jpg)

**Comment by Vant1032** [comment]
你这描述太模糊，你看你的提问方式里面包含的信息太少了，别人都无法分析问题，不好回答，要么你关了这个问题，要么你描述清楚点

**Comment by featherfly0513** [comment]
> 你这描述太模糊，你看你的提问方式里面包含的信息太少了，别人都无法分析问题，不好回答，要么你关了这个问题，要么你描述清楚点

他说的这个我也遇到了，就是再添加订阅，并更新订阅后，节点信息都刷出来了，但是点击右下角的v，没有反应，不变成绿色。
上面使用的是vmess，我是用的是ss。

设置中的选项都保持默认，点不开，修改远程dns，也点不开。
我是只有将模式从vpn改成仅代理，这个情况下，软件右下角的v点击才有反应，但是仍然上不了网。
如果点击选项中的服务重启，重启之后v字自己点亮，但是测试链接是会提示net/http:TLS handshake timeout. 如果把v点击关闭变成灰色，再点就没反应了。
这是重启服务后的log
![image](https://user-images.githubusercontent.com/33362813/236153935-6445c6d2-ccba-454c-a937-3e5233fab63b.jpeg)
