### ISSUE TITLE
V2ray这个软件现在做的很完美了，如果能实现一下功能就更完美了！

### ISSUE THREAD

**Issue by uposink** [2dust/v2rayNG#211]
我想说的就是多个节点同时在线负载分流，如配置文件中添加了美国的V2ray，韩国的V2ray，国内公司的socks三个节点。
多节点同时在线不同的规则不同的APP走不同的出口
如实现规则自动分流youtube走美国的节点，line走韩国的节点。公司内网ip走国内的socks
若能实现这个功能我愿意付费5美刀

**Comment by brandon3343** [comment]
5 * 7 = 35  太廉价了，主要看作者是否有兴趣，有没有时间吧。
