### ISSUE TITLE
com.v2ray.ang.AppConfig#ANG_CONFIG

### ISSUE THREAD

**Issue by cxw18772827901** [2dust/v2rayNG#2111]
This field is only found in the program to read, not to use this field to save the configuration, is there a problem here? College 1.7.38 and 1.8.0 comes with。

**Comment by cxw18772827901** [comment]
com.v2ray.ang.util.AngConfigManager#migrateLegacyConfig
fun migrateLegacyConfig(c: Context): Boolean? {
        try {
            val defaultSharedPreferences = PreferenceManager.getDefaultSharedPreferences(c)
            val context = defaultSharedPreferences.getString(ANG_CONFIG, "")
            //here will return forever
            if (context.isNullOrBlank()) {
                return null
            }
            val angConfig = Gson().fromJson(context, AngConfig::class.java)
            for (i in angConfig.vmess.indices) {
                upgradeServerVersion(angConfig.vmess[i])
            }

**Comment by 2dust** [comment]
Migrate old version configuration
