### ISSUE TITLE
Add a direct/reject mode like ClashN

### ISSUE THREAD

**Issue by APT-ZERO** [2dust/v2rayNG#2113]
Hello
Please add an option to disable tunneling without need to disable Tun like Direct mode in ClashN
Thanks

**Comment by APT-ZERO** [comment]
I ask this because disabling Tun will cause problems with adapters and devices
not only for me, i heard it from some other users too

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/wiki/Mode

at Setting Mode
