### ISSUE TITLE
生成的配置里 参数 "domainMatcher": "mph", 建议不用写这个 

### ISSUE THREAD

**Issue by chika0801** [2dust/v2rayNG#2117]
原因是  xray [1.4.3](https://github.com/XTLS/Xray-core/releases/tag/v1.4.3) 版本 加了hybrid 做为不写这参数的默认值了。

我给v2rayn提过一次 https://github.com/2dust/v2rayN/issues/2512 生成配置中可以不写这参数

### 预期行为
不用写

### 实际行为
写了这个 "domainMatcher": "mph"

**Comment by 2dust** [comment]
您可以PR

**Comment by chika0801** [comment]
已在 https://github.com/2dust/v2rayNG/releases/tag/1.8.2 修复
