### ISSUE TITLE
生成的配置里 reality 参数 "show", 建议 设置为false

### ISSUE THREAD

**Issue by chika0801** [2dust/v2rayNG#2118]
### 预期行为
现在生成的配置用的是 "show": true,

### 实际行为
建议默认为false吧，一般用户也用不到true。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
欢迎PR

**Comment by chika0801** [comment]
已在https://github.com/2dust/v2rayNG/releases/tag/1.8.2修复
