### ISSUE TITLE
Tasker无法通过v2rayNG插件启动v2rayNG

### ISSUE THREAD

**Issue by mitlearn** [2dust/v2rayNG#2119]
### 预期行为
在Tasker中使用V2RAYNG插件启动V2RayNG的VPN连接

### 实际行为
V2RayNG并没有响应Tasker的启动信号，无法启动VPN。

### 复现方法
1.Tasker内添加任务 搜索v2rayNG
2.设置想要连接的线路
![Screenshot_20230322-120801_Tasker__01](https://user-images.githubusercontent.com/64004444/226800437-7b6fdf3e-03fe-4c33-9cd1-0015635c9741.png)
3.运行任务 没有如预期启动

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android 11
Tasker 6.0.10
v2rayNG 1.8.0 (Play版
### 额外信息（可选）
https://github.com/2dust/v2rayNG/issues/733

**Comment by 2dust** [comment]
是否已经在NG中开启过节点并使用正常？

**Comment by mitlearn** [comment]
> 是否已经在NG中开启过节点并使用正常？

手动开启可以正常使用 但在tasker内调用则不行

_题外话 通知栏内的快捷开关在多线路时无法直接开启 必须进入应用内开启 是否可以默认上次连接线路直接开启？_

**Comment by mitlearn** [comment]
1.8.1可以如预期工作了 有点神奇 先关闭issue 感谢作者
