### ISSUE TITLE
Android4.4.4版本无法启动

### ISSUE THREAD

**Issue by jojoxl01** [2dust/v2rayNG#212]
Android4.4.4版本无法启动，点按启动按钮一直转圈，希望能够解决，谢谢！

12-25 10:11:59.859 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 111 bytes
12-25 10:11:59.859 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 111 bytes
12-25 10:11:59.859 I/GoLog   ( 7334): 2019/12/25 02:11:59 udp:127.0.0.1:47588 accepted udp:216.**:443 
12-25 10:11:59.959 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 21 bytes
12-25 10:12:00.029 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 105 bytes
12-25 10:12:00.029 I/GoLog   ( 7334): 2019/12/25 02:12:00 udp:127.0.0.1:47588 accepted udp:216.*****:443 
12-25 10:12:00.039 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 1350 bytes
12-25 10:12:00.069 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 28 bytes
12-25 10:12:00.069 I/GoLog   ( 7334): 2019/12/25 02:12:00 udp:127.0.0.1:47588 accepted udp:216.****8:443 
12-25 10:12:00.199 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 21 bytes
12-25 10:12:00.239 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 318 bytes
12-25 10:12:00.239 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 93 bytes
12-25 10:12:00.239 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 28 bytes
12-25 10:12:00.239 I/GoLog   ( 7334): 2019/12/25 02:12:00 udp:127.0.0.1:47588 accepted udp:2**:443 
12-25 10:12:00.339 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 21 bytes
12-25 10:12:00.399 D/tun2socks( 7427): INFO(tun2socks): UDP: from udprelay 318 bytes
12-25 10:12:00.419 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 28 bytes
12-25 10:12:00.419 I/GoLog   ( 7334): 2019/12/25 02:12:00 udp:127.0.0.1:47588 accepted udp:21***:443 
12-25 10:12:02.229 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 132 bytes
12-25 10:12:02.229 I/GoLog   ( 7334): 2019/12/25 02:12:02 udp:127.0.0.1:45058 accepted udp:21****9:443 
12-25 10:12:02.409 D/tun2socks( 7427): INFO(tun2socks): UDP: from device 132 bytes

**Comment by 2dust** [comment]
无能力解决低版本的问题,请换个设备吧
