### ISSUE TITLE
Auto test/sort by interval

### ISSUE THREAD

**Issue by pouriaksrvi** [2dust/v2rayNG#2120]
An option which if user enables it, then, the config list will be tested by "real delay" and then sorted, every n seconds, automatically. (disabled by default)

**Comment by aminrzaei** [comment]
I think this feature will be so useful.
And after testing, if current connection is broken auto connect to working one.

**Comment by pouriaksrvi** [comment]
> I think this feature will be so useful. And after testing, if current connection is broken auto connect to working one.

Maybe you wanna like this issue too: https://github.com/2dust/v2rayNG/issues/2116
It is by far the most important problem they should fix.
By fixing that, users no more need to remove their previously added configs each time before adding new ones.
Most of the unavailable configs they remove, may become available again, later (this happens a lot in some countries)

**Comment by subzero9319** [comment]
Yes
This feature so needed
also auto update subscibtion link every n minutes
