### ISSUE TITLE
Add auto update subscription 

### ISSUE THREAD

**Issue by Bazareco** [2dust/v2rayNG#2128]
Hello
Please add auto update subscription link.
For example when open app or add an option in setting. Update time for subscription. For examole every 2 hours

**Comment by Mobinnaz** [comment]
vmess://eyJhZGQiOiJkdWMudXNmYmFiYS54eXoiLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6IiIsImlkIjoiODI4YmFmMDctNWY3Yy00NGZiLWI3MzYtNmNlODMwNDk5ODRhIiwibmV0Ijoid3MiLCJwYXRoIjoiLyIsInBvcnQiOiI0NDMiLCJwcyI6IkB2cG5fc2hvcF9hYWEgLSBkZTYiLCJzY3kiOiJhdXRvIiwic25pIjoiIiwidGxzIjoidGxzIiwidHlwZSI6IiIsInYiOiIyIn0=
