### ISSUE TITLE
1.1.13版本路由分流有问题

### ISSUE THREAD

**Issue by zhongqiujie13** [2dust/v2rayNG#213]
这次更新后，发现打开国内网页非常的慢。我挂台湾机房，就算是台湾机房访问国内地址，也不会这么慢。延迟都几万毫秒了。我的梯子访问 Google 秒开，延迟就是30多 ms ，可是国内网站却是几万毫秒，有时都打不开。本来1.1.12开启本地 dns 后分应用代理正常了，更新了1.1.13后又不正常国内百度这些网站又走了代理，希望解决一下！

**Comment by 2dust** [comment]
1.1.13更新了主题颜色和core里面的geosite.dat,从理论上说是不应该发生你这种情况的
我还原core发一个版本给你测试下

**Comment by zhongqiujie13** [comment]
> 1.1.13更新了主题颜色和core里面的geosite.dat,从理论上说是不应该发生你这种情况的
> 我还原core发一个版本给你测试下

这个版本肯定是有问题的，play评论我也看到好几个反馈的了

**Comment by zhongqiujie13** [comment]
> 1.1.13更新了主题颜色和core里面的geosite.dat,从理论上说是不应该发生你这种情况的
> 我还原core发一个版本给你测试下

麻烦了，请发送到zhongqiujie13@gmail.com这个邮箱里吧，谢谢了

**Comment by 2dust** [comment]
使用1.1.12版lib,测试反馈下


[v2rayNG_1.1.13b1_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/3999706/v2rayNG_1.1.13b1_arm64-v8a.apk.zip)

**Comment by llllllllqq** [comment]
> 使用1.1.12版lib,测试反馈下
> 
> [v2rayNG_1.1.13b1_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/3999706/v2rayNG_1.1.13b1_arm64-v8a.apk.zip)

测试版没问题 ，等待其他人测试结果

**Comment by zhongqiujie13** [comment]
> 使用1.1.12版lib,测试反馈下
> 
> [v2rayNG_1.1.13b1_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/3999706/v2rayNG_1.1.13b1_arm64-v8a.apk.zip)


测试过了，这次没问题了

**Comment by aresbigboy** [comment]
> 使用1.1.12版lib,测试反馈下
> 
> [v2rayNG_1.1.13b1_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/3999706/v2rayNG_1.1.13b1_arm64-v8a.apk.zip)

1.1.13b1 没问题了
