### ISSUE TITLE
浏览器无法访问网页

### ISSUE THREAD

**Issue by cxw18772827901** [2dust/v2rayNG#2131]
telegram正常，但是手机浏览器网页均无法访问

**Comment by yang10560** [comment]
你问错人了。工具没问题，你节点有问题

**Comment by cxw18772827901** [comment]
你们的远程dns要换了，1.1.1.1要换成dns.google

**Comment by zhouluta** [comment]
set allowlnsecure=true

**Comment by github-24** [comment]
> telegram正常，但是手机浏览器网页均无法访问

我也是这样，机场换成ss节点后打不开网页了，但电脑端能正常使用，奇怪

**Comment by cxw18772827901** [comment]
> > telegram正常，但是手机浏览器网页均无法访问
> 
> 我也是这样，机场换成ss节点后打不开网页了，但电脑端能正常使用，奇怪

根据大佬们说法，飞机正常网页有问题有两个解决方案，一是把远程dns1.1.1.1替换成dns.google；二是勾选设置中的跳过证书验证。我这边两种方法都能解决，但是大佬们好像都不是很推荐跳过证书验证。

**Comment by wyrain** [comment]
肯定是DNS问题，死命往这个方向找解决方法就是了，我磨了三天暂时解决，我的环境下尝试如下：
1. 更换远程DNS，❌
2. 跳过证书验证，❌
3. 开启安卓私人DNS，❌
4. 启用虚拟DNS，✅

发现此问题在另一个issue下有讨论与官方回复：https://github.com/2dust/v2rayNG/issues/2135#issuecomment-1492930987
