### ISSUE TITLE
miui14使用v2rayNG无法正常启动VPN

### ISSUE THREAD

**Issue by gengruihuan** [2dust/v2rayNG#2134]
如图，选了节点，点了开关启动没反应，只提示正在开启，然后就没了。节点没问题，用clash正常使用。app也清除数据重装过了，都不行，求解。
![Screenshot_2023-03-27-15-08-24-729_com v2ray ang-edit](https://user-images.githubusercontent.com/28974422/227866650-55457071-6d09-4d29-a5f5-dd73781e00c7.jpg)

**Comment by featherfly0513** [comment]
兄弟，你解决了没有，我现在也遇到同样的问题。

**Comment by gengruihuan** [comment]
解决了，升级新版本就好了，同时关掉分应用控制，关掉adguard之类vpn的控制冲突



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月4日(周四) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [2dust/v2rayNG] miui14使用v2rayNG无法正常启动VPN (Issue #2134)




 
兄弟，你解决了没有，我现在也遇到同样的问题。
