### ISSUE TITLE
安卓10上开启代理无效

### ISSUE THREAD

**Issue by dogourd** [2dust/v2rayNG#214]
开启代理后应用内部测试连接延迟在300ms左右, 但是代理不起作用。logcat中大量日志为
Esortrun Waiting...
EscortRun cmd.Wait err:exit status 1
EscortRun Unexpected Exit
末尾存在大致如下日志: GoLog
Not Using Prepared:tcp ip:port accepted tcp:host:port

**Comment by heham** [comment]
我这里很奇怪的是打开代理再打开浏览器直接输入这时是不行的，但是切到v2ray不进行任何操作再切到浏览器这时候网页又神奇般的可以打开了。但是googleplay是死活打不开的。
荣耀10刚更新的10系统出的这个奇怪问题。

**Comment by aeroxy** [comment]
Google Play (and most Google apps) will shut down the network requests under VPN mode.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/203
