### ISSUE TITLE
V2ray EOF error connection. "Fail to detect internet connection :EOF 

### ISSUE THREAD

**Issue by Aria102** [2dust/v2rayNG#2143]
Hi everyone
I have a vmess protocol on x-ui server and import it to v2ray. But when I connect it to internet it said " Fail to detect internet connection :EOF" and try it to various apps and get the same result.
Does anyone knows how to solve this problem?

**Comment by dngnm** [comment]
This problem occurred due to the time difference between devices time in Iran
Change your timezone and it will be ok

**Comment by Aria102** [comment]
> This problem occurred due to the time difference between devices time in Iran Change your timezone and it will be ok

Thank my dear. Best wishes for you

**Comment by grsr1356-web** [comment]
eror contex v2rayng
