### ISSUE TITLE
add mux

### ISSUE THREAD

**Issue by Marvellous7** [2dust/v2rayNG#2147]
please add mux setting: "on/off"...like gatchang app

**Comment by cuynu** [comment]
does u mean this
![Screenshot_20230401-181636_v2rayNG](https://user-images.githubusercontent.com/90895715/229285568-fcc6c9f1-465a-4fb1-afbc-84193a90404e.png)

**Comment by ssmetall** [comment]
> does u mean this ![Screenshot_20230401-181636_v2rayNG](https://user-images.githubusercontent.com/90895715/229285568-fcc6c9f1-465a-4fb1-afbc-84193a90404e.png)

what is this version?

**Comment by ssmetall** [comment]
> does u mean this ![Screenshot_20230401-181636_v2rayNG](https://user-images.githubusercontent.com/90895715/229285568-fcc6c9f1-465a-4fb1-afbc-84193a90404e.png)

which version have mux.cool?

**Comment by cuynu** [comment]
> > does u mean this ![Screenshot_20230401-181636_v2rayNG](https://user-images.githubusercontent.com/90895715/229285568-fcc6c9f1-465a-4fb1-afbc-84193a90404e.png)
> 
> which version have mux.cool?

my forked v2rayNG app
