### ISSUE TITLE
shadowsocks  手机端无法用http伪装

### ISSUE THREAD

**Issue by xiaodo2099** [2dust/v2rayNG#2148]
shadowsocks  电脑端可以用http伪装,手机端不能用http伪装。手机端少了htttp伪装设置的参数.
![image](https://user-images.githubusercontent.com/129565310/229258263-e2cda774-f73b-4db8-80ed-5e0bfdee4dd6.png)
电脑端伪装不能自动导入，一般要手动开启！

**Comment by 2dust** [comment]
自建还是？
自建建议放弃ss，改用vless

**Comment by xiaodo2099** [comment]
vless 总是很卡，shadowsocks tcl+udp模式很流畅，就是没有伪装很容易封ip

**Comment by xiaodo2099** [comment]
我记错了，之前用的vemss  quic +bbr 优化了会好点，但学是卡的严重。kcp又容易堵塞，之后就下不来了。我去试试vless吧，这个是一定要加ssl吗，之前试了几次都没有成功！

**Comment by 256051** [comment]
我也发现了！
