### ISSUE TITLE
1.82 导出完整配置的 realitySettings 项里，多出了 "allowInsecure": false,

### ISSUE THREAD

**Issue by chika0801** [2dust/v2rayNG#2150]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
根据 https://github.com/XTLS/REALITY 里的示例，不应该有  "allowInsecure": false, 

### 实际行为
查看导出的配置，里面多了 "allowInsecure": false, 

虽然不影响使用

```
      "streamSettings": {
        "network": "tcp",
        "realitySettings": {
          "allowInsecure": false,
          "fingerprint": "chrome",
          "publicKey": "",
          "serverName": "",
          "shortId": "",
          "show": false,
          "spiderX": ""
        },
        "security": "reality",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        }
      },
```

### 复现方法
1.添加一个使用REALITY的配置
2.导出完整配置到剪贴板
3.查看内容

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
理论上没有影响
你实测有问题？

**Comment by chika0801** [comment]
实际是没有问题。我记得是1.81没多出这段，1.82多出来了。
