### ISSUE TITLE
大佬，提一个对于NG的小建议

### ISSUE THREAD

**Issue by xhwwstudio** [2dust/v2rayNG#2157]
程序很好用，我想提一个小小的建议你看看行不行。
就是NG软件，增加一个首页屏，而不是把服务器列表当成第一屏。
第一屏要以用启用或断开，显示当成连接的结点，设置的快捷按钮，分享的按扭等。
我觉得这样软件至少会好看不少。也更加便利吧。
个人意见……2dust大佬，你看看我说得对不对……

**Comment by Ght55** [comment]
Pls 
Add new core v2ray 
Use 2 subscribe link crash app

**Comment by metaforget** [comment]
希望作者不要加所谓首页，那就变成clash那种了，多增加操作，纯粹为了好看不方便没意思
