### ISSUE TITLE
Missing libv2ray.aar Library in Recent Releases

### ISSUE THREAD

**Issue by AmirHosseinCV** [2dust/v2rayNG#2158]
I recently downloaded a few releases of the V2rayNG and noticed that the libv2ray.aar library file was missing in each of them. As this file is crucial to build the application, I would like to request that it be included in future releases of the project.

Additionally, I checked out [AndroidLibXrayLite](https://github.com/2dust/AndroidLibXrayLite), but its source code is outdated and there hasn't been any recent release.

**Comment by SadraRahmani** [comment]
did you resolve the issue AmirHossein?

**Comment by qfewzz** [comment]
just download the latest or desired v2rayng apk file and extract .so file from it.

**Comment by janahnovin** [comment]
I have the same problem, please check, thanks

**Comment by janahnovin** [comment]
v2rayNG-1.8.6/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:30:8 Unresolved reference: libv2ray

**Comment by hesCalledAJ** [comment]
issue is still there why this closed as Completed ? i couldntbuild the aar file on my own for some reason.
isnt it possible to publish the current libv2ray.aar with each release of the project ?

**Comment by FirstVoyager** [comment]
hey guys, did you solve this problem?
