### ISSUE TITLE
大佬好，西部数据机场的trojan节点现在无法连接

### ISSUE THREAD

**Issue by lxtx528** [2dust/v2rayNG#2159]
西部数据的trojan协议现在在v2rayng里无法使用，但是魔戒的trojan协议却能够使用。

**Comment by uioasder** [comment]
虽然这个并不关软件的问题，但是我知道，你设置默认跳过证书验证就好，那是你机场的问题

**Comment by lxtx528** [comment]
非常感谢解惑答疑。

2dust ***@***.***> 于 2023年4月6日周四 08:26写道：
