### ISSUE TITLE
编译最新的1.8.2版本后，使用trojan协议无法连接，提示net/http:TLS handshake timeout

### ISSUE THREAD

**Issue by jimor1234567** [2dust/v2rayNG#2161]
编译最新的1.8.2版本后，使用trojan协议无法连接，提示net/http:TLS handshake timeout，使用旧版本1.5.16该trojan配置可以正常使用。

logcat日志提示：
--------- beginning of main
04-05 22:26:17.699 I/GoLog   ( 4909): udp:127.0.0.1:38974 accepted udp:1.1.1.1:53 [proxy]
04-05 22:26:18.180 D/com.v2ray.ang( 4909): SCREEN_ON, start querying stats
04-05 22:26:18.441 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 386 Err: connection timed out
04-05 22:26:18.441 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 387 Err: connection timed out
04-05 22:26:18.441 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 390 Err: connection timed out
04-05 22:26:18.441 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 375 Err: connection timed out
04-05 22:26:18.441 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 217 Err: connection timed out
04-05 22:26:18.441 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 280 Err: connection timed out
04-05 22:26:18.442 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 197 Err: connection timed out
04-05 22:26:18.442 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 389 Err: connection timed out
04-05 22:26:18.446 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 218 Err: connection timed out
04-05 22:26:18.889 I/GoLog   ( 4909): udp:127.0.0.1:48856 accepted udp:1.1.1.1:53 [proxy]
04-05 22:26:18.891 I/GoLog   ( 4909): udp:127.0.0.1:40870 accepted udp:1.1.1.1:53 [proxy]
04-05 22:26:19.704 I/GoLog   ( 4909): udp:127.0.0.1:52787 accepted udp:180.76.76.76:53 [proxy]
04-05 22:26:19.705 I/GoLog   ( 4909): [Warning] [250614784] app/dispatcher: default route for udp:180.76.76.76:53
04-05 22:26:20.038 I/GoLog   ( 4909): udp:127.0.0.1:57701 accepted udp:1.1.1.1:53 [proxy]
04-05 22:26:20.042 I/GoLog   ( 4909): udp:127.0.0.1:60657 accepted udp:1.1.1.1:53 [proxy]
04-05 22:26:20.489 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 221 Err: connection timed out
04-05 22:26:20.489 I/GoLog   ( 4909): fdConn unix.Connect err, Close Fd: 215 Err: connection timed out
04-05 22:26:20.894 I/GoLog   ( 4909): udp:127.0.0.1:44013 accepted udp:180.76.76.76:53 [proxy]
04-05 22:26:20.894 I/GoLog   ( 4909): [Warning] [1598569524] app/dispatcher: default route for udp:180.76.76.76:53
04-05 22:26:20.894 I/GoLog   ( 4909): [Warning] [3959139239] app/dispatcher: default route for udp:180.76.76.76:53
04-05 22:26:20.894 I/GoLog   ( 4909): udp:127.0.0.1:47708 accepted udp:180.76.76.76:53 [proxy]

**Comment by jimor1234567** [comment]
发现替换使用旧版本的libgojni.so可以正常连接。新的so在调用方法v2rayPoint.measureDelay()时抛出异常：go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout

**Comment by caliban511** [comment]
play上退出beta计划就好，，，🙈🙈🙈

**Comment by caliban511** [comment]
遇到了同样的问题，退出play的beta计划，退回1.7.38版后正常了，，，
