### ISSUE TITLE
谁有编译好的AndroidLibV2rayLite

### ISSUE THREAD

**Issue by caoxingM** [2dust/v2rayNG#2164]
搞了半天 配好了go的环境把代码下载
运行gomobile build -target=android

gomobile: err: exit status 1: stderr: go: github.com/v2fly/v2ray-core/v5@v5.4.1: missing go.sum entry; to add it:
        go mod download github.com/v2fly/v2ray-core/v5
这个可能不能下载到本地编译
那个教程上面的命令很多都提示没有某某某方法根本走不完整个教程
然后go安装环境配置这些东西很离谱 例如教程上面把某某文件复制到某某地方但是因为版本的问题这个路径可能已经没了 

有没有好兄弟发个能用的实在是顶不住进行不下去了  邮箱1627810262@qq.com

**Comment by caoxingM** [comment]
按照提示进行下去 首先会提示没有-w 其次

gomobile: err: exit status 1: stderr: go: github.com/xtls/xray-core@v1.7.2: missing go.sum entry; to add it:
        go mod download github.com/xtls/xray-core

git clone [repo] && cd AndroidLibXrayLite
gomobile init
go mod tidy -v
gomobile bind -v -androidapi 19 -ldflags='-s -w' ./

**Comment by jimor1234567** [comment]
那个编译教程比较模糊，你的提示是缺少编译依赖的v2ray-core库，需要先下载它。
可以执行以下两个命令：
mkdir -p $(shell go env GOPATH)/src/v2ray.com/core
git clone https://github.com/v2fly/v2ray-core.git $(shell go env GOPATH)/src/v2ray.com/core

**Comment by caoxingM** [comment]
已经可以按照上面的教程  gomobile bind -v -androidapi 19 -ldflags='-s -w' ./但是这一句只能是gomobile bind -v -androidapi 19  ./
