### ISSUE TITLE
华为手机无法安装

### ISSUE THREAD

**Issue by GreatLandmark** [2dust/v2rayNG#2169]
华为手机，鸿蒙系统3.0.0，
无法安装v2rayng 1.7.38，
安装界面显示：
v2rayNG
 Installation source : Browser 

 Installation failed 

 Reason for failure :
 The parser did not find any certificates in the installation package .
 Suggestion :
 Install the official version of this app .

**Comment by Deskfrest** [comment]
你是不是下错包了，我使用mate40 pro，鸿蒙3.0测试安装同版本没有问题
![image](https://user-images.githubusercontent.com/63090181/230532853-3cedcca8-3c0c-4ee4-88c7-4122c889baec.png)

**Comment by wdpmm515188** [comment]
我的鸿蒙2.0荣耀10青春版也没有问题。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月07日 11:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [2dust/v2rayNG] 华为手机无法安装 (Issue #2169) |

你是不是下错包了，我使用mate40 pro，鸿蒙3.0测试安装同版本没有问题

**Comment by fanyigao** [comment]
我之前还能翻，现在翻不了了

**Comment by Deskfrest** [comment]
> 我之前还能翻，现在翻不了了

你是不是更新了新版本，我之前更新到最新版后电报一直处于连接断开两种状态，不断切换，但其他软件和google又可以正常使用。后面回退到1.7.38了

**Comment by fanyigao** [comment]
> > 我之前还能翻，现在翻不了了
> 
> 你是不是更新了新版本，我之前更新到最新版后电报一直处于连接断开两种状态，不断切换，但其他软件和google又可以正常使用。后面回退到1.7.38了
没有，之前突然就连不上，后来偶尔能连上，我用一加的对比了一下，相同节点一加就能连上，华为不行。我还以为华为把我制裁了
