### ISSUE TITLE
1.7.38 证书验证问题bug 以及修改节点没有出现确定修改按钮的bug

### ISSUE THREAD

**Issue by tiewtouwa** [2dust/v2rayNG#2175]
证书验证问题bug
1.服务器使用x-ui原版搭建,使用x-ui原版申请的x-ui证书
2.使用vless+ws+tls方式连接
3.当开启cf的cdn的时候,v2rayNG的跳过证书验证为false能够成功连接
4.当关闭cf的cdn的时候,v2rayNG的跳过证书验证为false不能连接
5.当关闭cf的cdn的时候,v2rayNG的跳过证书验证为true能够成功连接

但是v2rayN证书验证正常
所以我怀疑是v2rayNG的证书验证出现了bug

修改节点没有出现确定修改按钮的bug
1.v2rayNG需要重启一遍才能正确修改节点信息,才会出现右上角那个确定修改的勾号

**Comment by ericyyyy** [comment]
这个问题解决了吗
