### ISSUE TITLE
app上显示正常连接，实际上却不能上网是怎么回事

### ISSUE THREAD

**Issue by chhsdjdjsk** [2dust/v2rayNG#2176]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by sceic** [comment]
可能是手机的日期和时间与服务器日期时间误差过大

**Comment by haohaohub** [comment]
我的也是这样，tg可以用但是网页进不了

**Comment by chhsdjdjsk** [comment]
> 我的也是这样，tg可以用但是网页进不了

怎么解决啊

**Comment by chhsdjdjsk** [comment]
> 可能是手机的日期和时间与服务器日期时间误差过大
请问如何解决这个问题呢
