### ISSUE TITLE
自定义路由不在路由模式选项中的层级疑惑

### ISSUE THREAD

**Issue by PaPerseller** [2dust/v2rayNG#218]
设置中自定义路由与路由模式在同一设置层级中，而路由模式中没有自定义路由这一选项。请问进行了自定义路由设置后，路由模式中应选择全局还是其他选项？谢谢

**Comment by pope-L** [comment]
在其他的回答中作者已经解释过优先级了

PaPerseller <notifications@github.com> 于 2019年1月15日周二 18:45写道：

**Comment by 2dust** [comment]
自定义优先级最高
然后是你选择的路由模式
不管你选择哪种路由模式,自定义一定会附加上去
