### ISSUE TITLE
[feature-request] automatic update subscription 

### ISSUE THREAD

**Issue by AliM1988** [2dust/v2rayNG#2180]
Please add automatic update subscription, like as v2rayN, with specific interval that entered by users. Actually, some users forget update subscription.

**Comment by PouryaDe** [comment]
yes please add this feature

**Comment by saeedk1989** [comment]
yes, we're waiting for this feature for a long time. :(

**Comment by SinaHadayati** [comment]
This feature is really needed

**Comment by subzero9319** [comment]
Yes this feature is so important 
Please add this it 🙏🙏🙏

**Comment by pouriaksrvi** [comment]
You may like this too: https://github.com/2dust/v2rayNG/issues/2120

**Comment by AliM1988** [comment]
@2dust 
Why you closed it without any response!
You see it is very useful and important feature.
