### ISSUE TITLE
I cannot find REALITY in the latest version of V2rayNG on android, I have created the server and config but can't use it on android

### ISSUE THREAD

**Issue by alinba82** [2dust/v2rayNG#2184]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Ght55** [comment]
vless://44bc3653-25fd-46dd-aabd-2efbecbaa4c5@194.38.9.99:443?security=reality&encryption=none&pbk=L1SHcUQZTY9utUZqeeO5nPBzb6xoDGSIGbabLs7eIVU&headerType=none&fp=chrome&spx=%2Fstore&type=tcp&flow=xtls-rprx-vision&sni=www.apple.com&sid=f8c6e9b40a9c6f26#FreeNode

Test it ok ✅️✌️

**Comment by Ght55** [comment]
Pls add new version  v2rayNG/V2flyng  Android 
Tanks
