### ISSUE TITLE
设置->自定义规则 中 如何输入IP规则？手机屏幕小，看不到地方

### ISSUE THREAD

**Issue by zen010101** [2dust/v2rayNG#2186]
V2rayN Windows 版本，我们在路由设置中可以设置代理的Domain或IP，界面被分为两部分：Domain and IP，可以分别输入 Domain 规则与 IP 规则。但在手机版的 V2rayNG 中，看不到这样的分栏界面，只有一个输入框。如何输入 IP 规则呢？
![微信图片_20230413173028](https://user-images.githubusercontent.com/60574100/231717369-1688ae79-4ddb-4c38-a115-8c1a37027651.jpg)
![image](https://user-images.githubusercontent.com/60574100/231717423-730f242e-c679-4ecb-9a7e-18ceb3fbe920.png)

**Comment by 2dust** [comment]
domain和ip混合输入即可，app会自动识别
