### ISSUE TITLE
手动添加的配置无法连接

### ISSUE THREAD

**Issue by velade** [2dust/v2rayNG#2190]
在最新版本上手动添加的配置不能连接，或及其偶尔延迟是几秒钟的连接成功。但是通过扫描旧版配置生成的二维码添加的配置就完全正常，疑似旧版中某些隐藏配置的关系（可以在界面编辑的配置都进行过反复的对比，绝对可以保证一致）

**Comment by Vant1032** [comment]
大哥，你好歹说下你添加的配置是啥吧，你这信息太少了怎么排查问题。
