### ISSUE TITLE
无法使用，日志报错

### ISSUE THREAD

**Issue by fcwys** [2dust/v2rayNG#22]
部分日志如下：
--------- beginning of main
06-26 19:24:21.016 E/com.v2ray.ang(18100): Not starting debugger since process cannot load the jdwp agent.
06-26 19:24:21.039 I/com.v2ray.ang(18100): The ClassLoaderContext is a special shared library.
06-26 19:24:21.064 I/com.v2ray.ang(18100): The ClassLoaderContext is a special shared library.
06-26 19:24:29.070 I/com.v2ray.ang(18100): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
06-26 19:24:49.488 I/GoLog   (18362): file exists
06-26 19:24:49.488 I/GoLog   (18362): EnableLocalDNS: false
06-26 19:24:49.488 I/GoLog   (18362): ForwardIpv6: false
06-26 19:24:49.488 I/GoLog   (18362): DomainName: 103.95.221.102:80
06-26 19:24:49.488 I/GoLog   (18362): loading v2ray config
06-26 19:24:49.488 I/GoLog   (18362): /data/user/0/com.v2ray.ang/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
06-26 19:24:49.489 I/GoLog   (18362): Preparing Domain: 103.95.221.102:80
06-26 19:24:49.512 I/GoLog   (18362): Prepare Result:
06-26 19:24:49.512 I/GoLog   (18362):  Ready: true
06-26 19:24:49.512 I/GoLog   (18362):  Domain: 103.95.221.102
06-26 19:24:49.512 I/GoLog   (18362):  Port: 80
06-26 19:24:49.512 I/GoLog   (18362):  IPs: [103.95.221.102]
06-26 19:24:49.524 I/GoLog   (18362): EscortRun cmd.Start err fork/exec /data/user/0/com.v2ray.ang/tun2socks: no such file or directory
06-26 19:24:49.524 I/GoLog   (18362): EscortRun Exit
06-26 19:24:49.835 I/GoLog   (18362): new v2ray core
06-26 19:24:49.845 I/GoLog   (18362): start v2ray core
06-26 19:24:49.848 I/GoLog   (18362): 2019/06/26 11:24:49 [Warning] v2ray.com/core: V2Ray 4.19 started
06-26 19:24:49.938 D/com.v2ray.ang(18362): sendFd tries: 0
06-26 19:24:49.939 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
06-26 19:24:50.039 D/com.v2ray.ang(18362): sendFd tries: 1
06-26 19:24:50.039 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
06-26 19:24:50.240 D/com.v2ray.ang(18362): sendFd tries: 2
06-26 19:24:50.241 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
06-26 19:24:50.642 D/com.v2ray.ang(18362): sendFd tries: 3
06-26 19:24:50.643 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
06-26 19:24:51.443 D/com.v2ray.ang(18362): sendFd tries: 4
06-26 19:24:51.443 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
06-26 19:24:51.728 I/GoLog   (18362): 2019/06/26 11:24:51 127.0.0.1:44626 accepted //www.google.com:443  
06-26 19:24:53.044 D/com.v2ray.ang(18362): sendFd tries: 5
06-26 19:24:53.045 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
06-26 19:24:53.167 I/GoLog   (18362): 2019/06/26 11:24:53 127.0.0.1:44634 accepted //www.google.com:443  
06-26 19:24:54.191 I/GoLog   (18362): 2019/06/26 11:24:54 127.0.0.1:44638 accepted //www.google.com:443  
06-26 19:24:56.246 D/com.v2ray.ang(18362): sendFd tries: 6
06-26 19:24:56.247 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
--------- beginning of system
06-26 19:26:28.359 E/com.v2ray.ang(20282): Not starting debugger since process cannot load the jdwp agent.
06-26 19:26:28.380 I/com.v2ray.ang(20282): The ClassLoaderContext is a special shared library.
06-26 19:26:28.408 I/com.v2ray.ang(20282): The ClassLoaderContext is a special shared library.
06-26 19:26:29.732 I/GoLog   (20309): file exists
06-26 19:26:29.732 I/GoLog   (20309): EnableLocalDNS: false
06-26 19:26:29.732 I/GoLog   (20309): ForwardIpv6: false
06-26 19:26:29.732 I/GoLog   (20309): DomainName: 103.95.221.102:80
06-26 19:26:29.732 I/GoLog   (20309): loading v2ray config
06-26 19:26:29.732 I/GoLog   (20309): /data/user/0/com.v2ray.ang/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
06-26 19:26:29.732 I/GoLog   (20309): Preparing Domain: 103.95.221.102:80
06-26 19:26:29.732 I/GoLog   (20309): Prepare Result:
06-26 19:26:29.732 I/GoLog   (20309):  Ready: true
06-26 19:26:29.732 I/GoLog   (20309):  Domain: 103.95.221.102
06-26 19:26:29.732 I/GoLog   (20309):  Port: 80
06-26 19:26:29.732 I/GoLog   (20309):  IPs: [103.95.221.102]
06-26 19:26:29.746 I/GoLog   (20309): EscortRun cmd.Start err fork/exec /data/user/0/com.v2ray.ang/tun2socks: no such file or directory
06-26 19:26:29.746 I/GoLog   (20309): EscortRun Exit
06-26 19:26:30.002 I/GoLog   (20309): new v2ray core
06-26 19:26:30.007 I/GoLog   (20309): start v2ray core
06-26 19:26:30.007 I/GoLog   (20309): 2019/06/26 11:26:30 [Warning] v2ray.com/core: V2Ray 4.19 started
06-26 19:26:30.074 D/com.v2ray.ang(20309): sendFd tries: 0
06-26 19:26:30.074 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:30.174 D/com.v2ray.ang(20309): sendFd tries: 1
06-26 19:26:30.175 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:30.375 D/com.v2ray.ang(20309): sendFd tries: 2
06-26 19:26:30.376 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:30.776 D/com.v2ray.ang(20309): sendFd tries: 3
06-26 19:26:30.779 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:31.579 D/com.v2ray.ang(20309): sendFd tries: 4
06-26 19:26:31.579 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:33.179 D/com.v2ray.ang(20309): sendFd tries: 5
06-26 19:26:33.180 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:36.380 D/com.v2ray.ang(20309): sendFd tries: 6
06-26 19:26:36.382 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
06-26 19:26:36.408 I/com.v2ray.ang(20282): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000

**Comment by NetFly-VPN** [comment]
这个问题怎么解决的呢?

**Comment by NetFly-VPN** [comment]
> 部分日志如下：
> --------- beginning of main
> 06-26 19:24:21.016 E/com.v2ray.ang(18100): Not starting debugger since process cannot load the jdwp agent.
> 06-26 19:24:21.039 I/com.v2ray.ang(18100): The ClassLoaderContext is a special shared library.
> 06-26 19:24:21.064 I/com.v2ray.ang(18100): The ClassLoaderContext is a special shared library.
> 06-26 19:24:29.070 I/com.v2ray.ang(18100): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
> 06-26 19:24:49.488 I/GoLog (18362): file exists
> 06-26 19:24:49.488 I/GoLog (18362): EnableLocalDNS: false
> 06-26 19:24:49.488 I/GoLog (18362): ForwardIpv6: false
> 06-26 19:24:49.488 I/GoLog (18362): DomainName: 103.95.221.102:80
> 06-26 19:24:49.488 I/GoLog (18362): loading v2ray config
> 06-26 19:24:49.488 I/GoLog (18362): /data/user/0/com.v2ray.ang/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
> 06-26 19:24:49.489 I/GoLog (18362): Preparing Domain: 103.95.221.102:80
> 06-26 19:24:49.512 I/GoLog (18362): Prepare Result:
> 06-26 19:24:49.512 I/GoLog (18362): Ready: true
> 06-26 19:24:49.512 I/GoLog (18362): Domain: 103.95.221.102
> 06-26 19:24:49.512 I/GoLog (18362): Port: 80
> 06-26 19:24:49.512 I/GoLog (18362): IPs: [103.95.221.102]
> 06-26 19:24:49.524 I/GoLog (18362): EscortRun cmd.Start err fork/exec /data/user/0/com.v2ray.ang/tun2socks: no such file or directory
> 06-26 19:24:49.524 I/GoLog (18362): EscortRun Exit
> 06-26 19:24:49.835 I/GoLog (18362): new v2ray core
> 06-26 19:24:49.845 I/GoLog (18362): start v2ray core
> 06-26 19:24:49.848 I/GoLog (18362): 2019/06/26 11:24:49 [Warning] v2ray.com/core: V2Ray 4.19 started
> 06-26 19:24:49.938 D/com.v2ray.ang(18362): sendFd tries: 0
> 06-26 19:24:49.939 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> 06-26 19:24:50.039 D/com.v2ray.ang(18362): sendFd tries: 1
> 06-26 19:24:50.039 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> 06-26 19:24:50.240 D/com.v2ray.ang(18362): sendFd tries: 2
> 06-26 19:24:50.241 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> 06-26 19:24:50.642 D/com.v2ray.ang(18362): sendFd tries: 3
> 06-26 19:24:50.643 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> 06-26 19:24:51.443 D/com.v2ray.ang(18362): sendFd tries: 4
> 06-26 19:24:51.443 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> 06-26 19:24:51.728 I/GoLog (18362): 2019/06/26 11:24:51 127.0.0.1:44626 accepted //www.google.com:443
> 06-26 19:24:53.044 D/com.v2ray.ang(18362): sendFd tries: 5
> 06-26 19:24:53.045 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> 06-26 19:24:53.167 I/GoLog (18362): 2019/06/26 11:24:53 127.0.0.1:44634 accepted //www.google.com:443
> 06-26 19:24:54.191 I/GoLog (18362): 2019/06/26 11:24:54 127.0.0.1:44638 accepted //www.google.com:443
> 06-26 19:24:56.246 D/com.v2ray.ang(18362): sendFd tries: 6
> 06-26 19:24:56.247 D/com.v2ray.ang(18362): java.io.IOException: No such file or directory
> --------- beginning of system
> 06-26 19:26:28.359 E/com.v2ray.ang(20282): Not starting debugger since process cannot load the jdwp agent.
> 06-26 19:26:28.380 I/com.v2ray.ang(20282): The ClassLoaderContext is a special shared library.
> 06-26 19:26:28.408 I/com.v2ray.ang(20282): The ClassLoaderContext is a special shared library.
> 06-26 19:26:29.732 I/GoLog (20309): file exists
> 06-26 19:26:29.732 I/GoLog (20309): EnableLocalDNS: false
> 06-26 19:26:29.732 I/GoLog (20309): ForwardIpv6: false
> 06-26 19:26:29.732 I/GoLog (20309): DomainName: 103.95.221.102:80
> 06-26 19:26:29.732 I/GoLog (20309): loading v2ray config
> 06-26 19:26:29.732 I/GoLog (20309): /data/user/0/com.v2ray.ang/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
> 06-26 19:26:29.732 I/GoLog (20309): Preparing Domain: 103.95.221.102:80
> 06-26 19:26:29.732 I/GoLog (20309): Prepare Result:
> 06-26 19:26:29.732 I/GoLog (20309): Ready: true
> 06-26 19:26:29.732 I/GoLog (20309): Domain: 103.95.221.102
> 06-26 19:26:29.732 I/GoLog (20309): Port: 80
> 06-26 19:26:29.732 I/GoLog (20309): IPs: [103.95.221.102]
> 06-26 19:26:29.746 I/GoLog (20309): EscortRun cmd.Start err fork/exec /data/user/0/com.v2ray.ang/tun2socks: no such file or directory
> 06-26 19:26:29.746 I/GoLog (20309): EscortRun Exit
> 06-26 19:26:30.002 I/GoLog (20309): new v2ray core
> 06-26 19:26:30.007 I/GoLog (20309): start v2ray core
> 06-26 19:26:30.007 I/GoLog (20309): 2019/06/26 11:26:30 [Warning] v2ray.com/core: V2Ray 4.19 started
> 06-26 19:26:30.074 D/com.v2ray.ang(20309): sendFd tries: 0
> 06-26 19:26:30.074 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:30.174 D/com.v2ray.ang(20309): sendFd tries: 1
> 06-26 19:26:30.175 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:30.375 D/com.v2ray.ang(20309): sendFd tries: 2
> 06-26 19:26:30.376 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:30.776 D/com.v2ray.ang(20309): sendFd tries: 3
> 06-26 19:26:30.779 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:31.579 D/com.v2ray.ang(20309): sendFd tries: 4
> 06-26 19:26:31.579 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:33.179 D/com.v2ray.ang(20309): sendFd tries: 5
> 06-26 19:26:33.180 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:36.380 D/com.v2ray.ang(20309): sendFd tries: 6
> 06-26 19:26:36.382 D/com.v2ray.ang(20309): java.io.IOException: No such file or directory
> 06-26 19:26:36.408 I/com.v2ray.ang(20282): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000

你这个问题怎么解决的呢?
