### ISSUE TITLE
v2rayNG手机上延迟高，速度慢

### ISSUE THREAD

**Issue by sunnyrain1990** [2dust/v2rayNG#220]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

预期行为
改善WS+TLS性能

实际行为
同一配置(WS+TLS)，在PC v2rayN上测试延迟在170左右，速度快，而在手机端则是1秒左右，连的同一路由器。

复现方法
1.v2ray手机客户端必出现

**Comment by sunnyrain1990** [comment]
请问有大佬知道原因吗？

**Comment by 2dust** [comment]
ng测试的是本地-节点-google服务器的时间

**Comment by Meilinhost** [comment]
这几天闲来无事，测试了比较热门和冷面的方式，以日常YouTube为测试对象，发现v2rayng手机上确实慢，相同网络，电脑跑10万，手机只能最高4W，然后我卸载了v2ray，装了trojan 两端都能10W，我又卸载了装ss，两端都能10万，再次装回v2ray，并且用ng连接，4-5W再也上不去，电脑端10W，得出结论 ng有问题

**Comment by Lee-7723** [comment]
遇到同一问题，也是ws+tls，不仅是测试延时的问题，YouTube等应用加载速度也很慢

**Comment by heixiyi** [comment]
遇到一个问题，tcp +tls ，链接无限网络都没问题，速度很快；Android手机连接移动网络延迟延迟4000，切换无线网就没事

**Comment by wahahababaozhou** [comment]
> 这几天闲来无事，测试了比较热门和冷面的方式，以日常YouTube为测试对象，发现v2rayng手机上确实慢，相同网络，电脑跑10万，手机只能最高4W，然后我卸载了v2ray，装了trojan 两端都能10W，我又卸载了装ss，两端都能10万，再次装回v2ray，并且用ng连接，4-5W再也上不去，电脑端10W，得出结论 ng有问题

用了多个手机+电脑 简单测试了下，感觉是跟CPU处理性能有关系，同样的网络情况下，性能越高的CPU，速度越快

**Comment by trialman** [comment]
后台优化的问题, 如果是小米的话, 在 开发者 中心关掉    miui优化,  然后就起飞了!

**Comment by HCareLou** [comment]
我也遇到这个问题，换个软件，速度嘎嘎快，我怀疑，V2rayNG必定存在非常隐蔽的BUG

**Comment by dulestar** [comment]
没错，我也是这样，19年的问题到现在居然还没解决，电脑上用其他软件很快，手机贼慢，一直排查不了，后面换了其他软件速度直接起飞了

**Comment by CaptainRat** [comment]
26年依旧没解决
