### ISSUE TITLE
Feature request: Auto switch profile according to wifi ssid. 中文回答也行

### ISSUE THREAD

**Issue by alcatraz-zz** [2dust/v2rayNG#2201]
Hey fellas

Some internet connections are weaker than others. I have a couple of server profiles that I use when the internet is weak (bouncing the traffic over a local server). However I am a bit lazy to switch manually as I travel over these wifi networks.

I would love for you to have a feature like: "preferred default profile - any ssid"  "preferred profile for XXXX ssid" and "preferred profile for YYYY ssid".

It means that v2rayNG automatically switches to the other profile when connected to that ssid. 

I'm using the same server but sometimes it connects over an intermediary, which is unneccessary for certain networks.

Thanks!

**Comment by 2dust** [comment]
请使用 tasker

**Comment by alcatraz-zz** [comment]
![IMG_20230419_182516](https://user-images.githubusercontent.com/250045/233046969-8be75988-5e1c-4a22-a280-35ebad6d8b5d.jpg)
![IMG_20230419_182409](https://user-images.githubusercontent.com/250045/233047000-6c712579-de2a-4dd5-b4f2-34bcb3753e9f.jpg)
Thanks! Love the app!

I'm using Nova Launcher to create a widget (for Macrodroid) and I am able to see this "Tasker" function. Problem is, after creating the widget and choosing the desired profile, nothing happens when pressing it. I press it and the config dialog comes up again (allowing to choose which profile). Hmm...

**Comment by 2dust** [comment]
pls use tasker
Just try it and you'll understand, it's very simple

**Comment by alcatraz-zz** [comment]
> pls use tasker Just try it and you'll understand, it's very simple

I have tasker now. I looked around for 10min but I can't open the v2rayNG shortcut. Hmm... Do you have some info or a guide? 中文教程也行

**Comment by 2dust** [comment]
https://gwokshingcheung.blogspot.com/2017/08/taskerwifissr.html

like this

**Comment by alcatraz-zz** [comment]
> https://gwokshingcheung.blogspot.com/2017/08/taskerwifissr.html
> 
> like this

Thank you so much! 

Tasker costs money. The guide allowed me to find the right "action" in Macrodroid (free) and now it works. It changes profile depending on if it's disconnected from or connected to these weaker wifi networks. 

![IMG_20230420_183738](https://user-images.githubusercontent.com/250045/233342229-99e9731e-b9db-4979-8702-a0c72ac673cb.jpg)

**Comment by 2dust** [comment]
glad you got it
