### ISSUE TITLE
[Feature Request] pinning configs

### ISSUE THREAD

**Issue by pouriaksrvi** [2dust/v2rayNG#2209]
After sorting configs, some important configs which are often used (for example links to the SOCKS port of other local devices which have installed v2rayNG) will get moved down because they may be temporarily unhealthy at that time.
When the list is too long, they'll go to the end of a long list.

This causes them hardly get moved up again in the next sorts, even if they get healthy again.

Let users pin some often used configs to the top of the list.

**Comment by Ght55** [comment]
Pls add Wireguard config into v2rayNG 😉
