### ISSUE TITLE
关于GooglePlay [df-dferh-01]错误

### ISSUE THREAD

**Issue by linzyjx** [2dust/v2rayNG#221]
## 问题背景

国内某些厂商的手机上内置了中国版的GMS服务，但其将服务域名设置成了`*.googleapis.cn`（正常应为`*.googleapis.com`）。这导致Play商店请求报`[df-dferh-01]`，无法正常使用play商店。

测试了目前几个支持vmess的应用，都无法很好地解决这个问题。

## 问题解决建议

是否可以在v2rayNG的DNS转发功能中添加类似于将`googleapis.cn`解析到`googleapis.com`的功能呢？

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.1.15

**Comment by lsave** [comment]
> ## 问题背景
> 
> 国内某些厂商的手机上内置了中国版的GMS服务，但其将服务域名设置成了`*.googleapis.cn`（正常应为`*.googleapis.com`）。这导致Play商店请求报`[df-dferh-01]`，无法正常使用play商店。
> 
> 测试了目前几个支持vmess的应用，都无法很好地解决这个问题。
> ## 问题解决建议
> 
> 是否可以在v2rayNG的DNS转发功能中添加类似于将`googleapis.cn`解析到`googleapis.com`的功能呢？

遇到了同样的问题，现在解决了吗？
