### ISSUE TITLE
            process = proBuilder                     .directory(applicationContext.filesDir)                     .start()

### ISSUE THREAD

**Issue by caoxingM** [2dust/v2rayNG#2218]
真机运行demo 报错

java.io.IOException: Cannot run program "/data/app/~~9rrxyAain7CH-qAH8p5dSQ==/com.example.ss_android-Ogtk7acZbGz2cNP43Lh1kw==/lib/arm64/libtun2socks.so" (in directory "/data/user/0/com.example.ss_android/files"): error=2, No such file or directory
模拟器不会报错

**Comment by lucaswhob** [comment]
I Have Same Problem Any Solution ?

**Comment by yaofclc** [comment]
How to solve this problem?
