### ISSUE TITLE
mate9扫描二维码扫不出来

### ISSUE THREAD

**Issue by fflrichard** [2dust/v2rayNG#222]
mate9扫描二维码很模糊，扫不出来。这是个很低级的问题

**Comment by 2dust** [comment]
低级如何不好评价
并不是所有的轮子都要自己再造
扫描使用的如下的轮子
https://github.com/dm77/barcodescanner

**Comment by 2dust** [comment]
您的问题在我或者其他人有真机可以测试的情况下应该可以解决
反之则

**Comment by 2dust** [comment]
另外，很讨厌这种口气提问题
功能好坏或者是否难易都不是张口就来的
