### ISSUE TITLE
Quic pleas support.

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#222]
Quic pleas support.
Recent test quic, very fast and stable. 
seems the android v2rayNg not support it correct.
would you please support it . 
For simple, leave me a textarea, i can paste the raw json configure file into it. 
that may works like a boss

**Comment by 2dust** [comment]
You can use custom configuration

**Comment by henrypijames** [comment]
I believe the problem may be related to [a similar issue with v2rayN](https://github.com/2dust/v2rayN/issues/362) regarding correctly interpretation `host` and setting `serverName` in JSON config.

On same device, latest version of Kitsunebi is able to connect to the server via QUIC, but only when `TLS > Server Name` is set (to same value as `Address`).

**Comment by bhoppi** [comment]
The same issue.
The author said he won't accept QUIC related issues because of bad experiences. #47 #181 
But after updating to draft-29, the QUIC protocol is highly available and fast (at least for me). So I think maybe it is time to fix it.
Thanks.
