### ISSUE TITLE
华为手机上如何选择v2rayNG使用哪个版本

### ISSUE THREAD

**Issue by fw0037** [2dust/v2rayNG#2220]
华为mate系列的手机(mate8,9,10,10pro,20pro,40pro)，鸿蒙2.0版本，使用如个版本的v2rayNG比较合适？

**Comment by lastlastweek** [comment]
我是从高版本退回到1.6.30 ，觉得好用。你试试

**Comment by alexiaocl** [comment]
> 我是从高版本退回到1.6.30 ，觉得好用。你试试

我安装低版本老是提示已存在高版本，无法安装。可是我已经都卸载了啊。华为p40，鸿蒙4.0

**Comment by alexiaocl** [comment]
> 我是从高版本退回到1.6.30 ，觉得好用。你试试

请问怎么退回低版本呢？
