### ISSUE TITLE
The least version of xray core

### ISSUE THREAD

**Issue by mahmoodshahsavari** [2dust/v2rayNG#2221]
Hello
I need the least version of xray core you used it on v2rayng pre release version
The current version is version 1.7.3
How can i access to least version of xray core ?

**Comment by omidsa596** [comment]
داداش آخرینش 1.8.0 هست و یه سرچ ساده میخواد.نه کامنت issues باز کردن.

https://github.com/2dust/v2rayNG/releases/download/1.8.3/v2rayNG_1.8.3_arm64-v8a.apk

**Comment by mahmoodshahsavari** [comment]
عزیزدل منظورم خروجیشون نبود
داخل کد هاشون وقتی LibV2ray رو بیلدمیگیرم کورش نسخه قدیمی هست. کد رو اپدیت نکردن

**Comment by mahmoodshahsavari** [comment]
عزیزدل کدشون رو آپدیت نکردن و lib v2ray رو وقتی خروجی میگیرم نسخه ی 1.8نیست

**Comment by omidsa596** [comment]
چرا داداش آپدیت شده بیشتر از یک هفته پیش.همین لینک که من دادم دانلود کنید و نصب کنید .پایینش ورژن کور نوشته ۱.۸.۱
و ساپورت ریالیتی داره

شما کور رو جدا میخواهید ؟
یا به همراه برنامه
