### ISSUE TITLE
最新版本关闭屏幕一会就连不上了

### ISSUE THREAD

**Issue by GreatMichaelLee** [2dust/v2rayNG#2222]
xray core 1.8.1 v2rayNG 1.8.3

预期：开关屏幕，应保持连接通顺

实际：屏幕关闭一会（已将v2rayng设为防止安卓自杀），再打开屏幕，就测试和连接都不通了，提示net/https:TLS handshake timeout
需要重新重启服务才能通。而server端是没问题的，其他openwrt的客户端可正常连接。

logcat提示日志：
04-24 09:53:50.956 D/com.v2ray.ang(24400): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout
04-24 09:54:36.998 I/GoLog   (24400): fdConn unix.Connect err, Close Fd: 95 Err: connection timed out
04-24 09:54:45.915 D/com.v2ray.ang(24400): SCREEN_OFF, stop querying stats
04-24 09:54:50.336 W/com.v2ray.ang( 9856): Reducing the number of considered missed Gc histogram windows from 261 to 100
04-24 09:56:49.546 D/com.v2ray.ang(24400): SCREEN_ON, start querying stats
04-24 09:57:01.749 I/GoLog   (24400): fdConn unix.Connect err, Close Fd: 6 Err: connection timed out
04-24 09:57:03.799 I/GoLog   (24400): fdConn unix.Connect err, Close Fd: 101 Err: connection timed out

怀疑也可能是core的问题，麻烦看看。

**Comment by FengkuiChan** [comment]
一模一样的问题。

**Comment by ywx1983cn** [comment]
我也这样，VLESS-XTLS-uTLS-REALITY连接经常提示net/https:TLS handshake timeout，开关一下飞行模式就好了，屏幕关闭一会又断开了

**Comment by ywx1983cn** [comment]
我怀疑是手机客户端的问题啊，电脑客户端和软路由都稳的一批

**Comment by zxcbnmv** [comment]
类似的问题，这边是启动服务30分钟后准时发生，跟开关屏幕没有关系

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.4
试一试这个版本 @zxcbnmv

**Comment by sorasoras** [comment]
一样的问题

**Comment by ywx1983cn** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/1.8.4 试一试这个版本@zxcbnmv

还是会断连

**Comment by GreatMichaelLee** [comment]
> 类似的问题，这边是启动服务30分钟后准时发生，跟开关屏幕没有关系


> 我怀疑是手机客户端的问题啊，电脑客户端和软路由都稳的一批

是的，就是1.8.3出来后出现的问题，我的电脑和软路由也稳的一批

**Comment by GreatMichaelLee** [comment]
> 我也这样，VLESS-XTLS-uTLS-REALITY连接经常提示net/https:TLS handshake timeout，开关一下飞行模式就好了，屏幕关闭一会又断开了

我是停止和重启v2rayNG 服务那个按钮重开一下就能好

**Comment by GreatMichaelLee** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/1.8.4 试一试这个版本 @zxcbnmv

我从日志看，猜测是因为connection 的本地Unix fd被异常关闭导致的断连，具体原因不详，1.8.4好像修复的是media/storage的access问题，可能和这个issue关系不大。

**Comment by dogxgit** [comment]
预览版1.8.6仍旧遇到同样的问题，有人有解决方法吗
