### ISSUE TITLE
Trojan-Reality PublicKey

### ISSUE THREAD

**Issue by papampi** [2dust/v2rayNG#2224]
V2rayNG version 1.8.3 not importing Trojan-Reality PublicKey from Subscription link, direct link or Qr Code.

**Comment by 2dust** [comment]
Reality just support vless

**Comment by papampi** [comment]
But I can connect with v2rayNG if add PublicKey manually.
Both Trojan-Reality-TCP and Trojan-Reality-gRPC working ok if add PublicKey manually.
