### ISSUE TITLE
Automatic subscription update

### ISSUE THREAD

**Issue by Rt5844** [2dust/v2rayNG#2225]
Add automatic subscription update, thanks

**Comment by dopaemon** [comment]
i need it

**Comment by PouryaDe** [comment]
yes its very useful

**Comment by Dev-l0p** [comment]
Its very good idea.

**Comment by mahfiyar03204** [comment]
Yesssss
Please add automatic subscription update feature, I really need it and I'm sure others want the same

**Comment by AmirSe051** [comment]
سلام چطوری سرور بسازم

**Comment by mahfiyar03204** [comment]
> سلام چطوری سرور بسازم

سلام توی یوتیوب سرچ بزنید به راحتی میتونید یاد بگیرید

**Comment by AbasJalali** [comment]
i need it
