### ISSUE TITLE
Android 4.2.2 Unfortunately V2rayNG Has Stopped

### ISSUE THREAD

**Issue by jamesalpera** [2dust/v2rayNG#223]
Hello on Android 4.2.2 not working Unfortunately V2rayNG Has Stopped.

**Comment by yuhan6665** [comment]
#287 may solve this. I haven't test it on 4.2.2 though

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.2.3

**Comment by jamesalpera** [comment]
The problem has been fixed Thanks.
