### ISSUE TITLE
失败： net/http: tls handshake timeout

### ISSUE THREAD

**Issue by ywx1983cn** [2dust/v2rayNG#2232]
1.8.3版本 VLESS-XTLS-uTLS-REALITY 连接后提示 失败： net/http: tls handshake timeout ，目前解决办法是开关下飞行模式就好了。v2rayn和软路由passwall同样的节点没有这个问题，手机上其它类型模式的节点没有这个问题。

**Comment by github-ZH-cn** [comment]
解决了吗
