### ISSUE TITLE
subscription update fails

### ISSUE THREAD

**Issue by netsupcloud** [2dust/v2rayNG#2237]
hi,

subscription update fails when there is only one connection in subscription update and user is connected with that connection before

so its better subscription update automatically disconnect that single connection atleast when only one connection is in v2rayng and do update and reconnect it again

also subscription fail on reality connection sometimes infact it doesnt load all details and parameters of config

it will load only (address) (port) and (id) and will make others empty only atleast on android. in windows is ok at same time

version 1.8.2

**Comment by donnyxray** [comment]
I think the number of connections is not relevant. The update will fail simply if the active connection is not working properly. v2rayNG could do a connectivity check prior to updating the subscription.

That said, automatically disconnecting is also not a good idea. The user may not expect it and traffic may leak as a result.

The easiest solution is to improve the error message: "Subscription update failed. Disconnect v2rayNG and try again".
