### ISSUE TITLE
弱弱地问一下v2rayNG不可以自动更新升级版本吗？

### ISSUE THREAD

**Issue by xeefei** [2dust/v2rayNG#2239]
### 预期行为
每次升级应该可以直接在客户端直接升级到最新版本才方便啊，
并且升级完成之后对应的配置还是保留着，也不需要修改，这样岂不是更方便？

### 实际行为
现在找不到能自动升级的地方，只能有新版本了，然后下载.apk文件，
把旧版本卸载掉，重新安装，关键所有的设置又得重新来一遍，比如像预定义规则什么的那些设置。

**Comment by yidit** [comment]
为什么要卸载旧版本，不是可以直接覆盖安装吗

**Comment by xeefei** [comment]
> 为什么要卸载旧版本，不是可以直接覆盖安装吗

覆盖安装的时候提示要卸载啊？

**Comment by yaleimeng** [comment]
最好是自主检测版本，自主完成下载和增量资源更新，减少用户的操作与麻烦。

**Comment by bangzu-yan** [comment]
google商店有beta版本，可供升级成最新版本，不用重复卸载和安装。。正如楼上所说，最好还是自主完成增量更新最好了。

**Comment by PixMod** [comment]
> 

如果覆盖安装的时候提示要先卸载，那么就先不要安装，很明显新安装包的签名与旧的不一致，说明要么旧的不可靠，要么新的不可靠，你需要排查到底哪个才是真的官方安装包，否则如果装了不明定制的版本，很有可能底裤彻底脱光光
