### ISSUE TITLE
建议给通知栏快捷按钮文字添加二级选项快速切换服务器

### ISSUE THREAD

**Issue by mykeyin** [2dust/v2rayNG#224]
点击通知栏按钮文字出现二级菜单效果类似下图，可以方便快速的切换节点。点详细信息直接打开app. 星际之门三已购
![20190127_114248](https://user-images.githubusercontent.com/10703506/51796262-371b0800-222a-11e9-9f81-b792f304514c.jpg)

**Comment by 2dust** [comment]
无力接受需求
