### ISSUE TITLE
READ_EXTERNAL_STORAGE 该权限拿不到

### ISSUE THREAD

**Issue by Extreme-Icer** [2dust/v2rayNG#2247]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Android13中应当正确获取到该权限

### 实际行为
导入自定义配置发生错误：无法获得权限；且libchecker发现权限未授予

### 复现方法
1.Samsung的Android13手机（ONEUI5.1），最新的NG
2.正常给予权限，并试图导入自定义配置
3.无法导入自定义配置

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
SM-S9080 Android13
### 额外信息（可选）

![image](https://user-images.githubusercontent.com/59390954/235833739-71876b33-7e0f-4fd5-8649-bfa1db6aec60.png)
![image](https://user-images.githubusercontent.com/59390954/235834044-0cad9fc9-31da-4004-a682-9326f21e1c2b.png)
![image](https://user-images.githubusercontent.com/59390954/235834092-fe3104fd-1c6c-46fe-9cb6-681ac0de2c7e.png)

**Comment by yuhan6665** [comment]
@2dust we might need to apply for both permissions here
https://github.com/2dust/v2rayNG/commit/966151d3fe58649a5db0c256cc59e6abfc878711

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.5
