### ISSUE TITLE
go, lib2ray, v2raypoint, Seq, V2RayVPNServiceSupportsSet not Found

### ISSUE THREAD

**Issue by JArsham007** [2dust/v2rayNG#2248]
After cloning the project, in the V2rayServiceManager and some other files the dependencies go, lib2ray, v2raypoint, Seq, V2RayVPNServiceSupportsSet cannot be recognized by the project
how to fix this issue

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite

**Comment by vahid1hdr** [comment]
> https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite

not useful at all. I did all mentioned but still have same issue

**Comment by vahid1hdr** [comment]
> After cloning the project, in the V2rayServiceManager and some other files the dependencies go, lib2ray, v2raypoint, Seq, V2RayVPNServiceSupportsSet cannot be recognized by the project how to fix this issue

Hello, Is your problem resolved? If yes, could you please give me some help?
