### ISSUE TITLE
Unresolved reference: domainName

### ISSUE THREAD

**Issue by xeeoon** [2dust/v2rayNG#225]
编译时报错:
app\src\main\kotlin\com\v2ray\ang\service\V2RayVpnService.kt: (194, 24): Unresolved reference: domainName

**Comment by xeeoon** [comment]
根据[issue#104](https://github.com/2dust/v2rayNG/issues/104)InappBuyActivity等已注释，
v2rayPoint.domainName = domainName 该行注释后可以编译，但运行时点击连接后会出现该进程已闪退。

**Comment by 2dust** [comment]
lib改成
https://github.com/2dust/AndroidLibV2rayLite
