### ISSUE TITLE
Add android compatibility on play store

### ISSUE THREAD

**Issue by mmrabbani** [2dust/v2rayNG#2256]
I installed v2rayNG on my android tv and it works great. But when I want to install it on play store, it says "the app is not compatible with your device". You can find my device model in picture. 

Expected behavior: user can install/update the app in google play store. 

Actual behavior: google play store doesn't Allow installing due to incompatibility. 

![IMG_20230504_231636_945.jpg](https://user-images.githubusercontent.com/56675802/236315313-ba3ee257-3638-4e43-9440-89b7eb25861d.jpg)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases
