### ISSUE TITLE
请库主更新源码

### ISSUE THREAD

**Issue by bannedbook** [2dust/v2rayNG#226]
库主您好，
源码好像停留在1.02版？ 最新源码编译出来的apk 版本号是 1.0.2 啊？
我下载了1.1.12 、1.1.14 、1.1.15   3个版本的源码，经比较这3个版本的源码一模一样，根本没有更新啊？
可否更新一下源码

**Comment by oO0oO0oO0o0o00** [comment]
然后就会被你这样的机场抄去，加上自己的内置推广服上架。
比如你GP发布的ss vpn跟shadowsocks-android区别在哪儿？
有时间还不如把你们以app形式上架的那些电子书提升一下画质，9102年了还停留在安卓2.3时代，下载量也够可怜。

**Comment by bannedbook** [comment]
区别，就是加内置免费服务器哦。

**Comment by bannedbook** [comment]
我们不是机场哦，我们所有软件都是免费提供。
