### ISSUE TITLE
Android10更新订阅失败

### ISSUE THREAD

**Issue by moroal** [2dust/v2rayNG#2260]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
update subscription 正常

### 实际行为
update subscription 在Android10上failure，但是在Android13上success

### 复现方法
1.新安装v2rayNG
2.subscription group setting-> 加号 -> 填写名称及链接-> 保存
3.返回至configuration file-> 右上角update subscription，等待

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android10

**Comment by lemon4636** [comment]
我也发现了 而且一哈可以 然后又不行了  
我遇到了更新订阅失败的情况，我换了地址后突然不行了 但是电脑ipad都可以，就安卓不行，
排除地址问题 我把地址什么换回去都不行  https的订阅地址 返回也是base64编码的  显示更新订阅失败订阅
