### ISSUE TITLE
Big subscription(3000<🤯) causes wait or close dialog

### ISSUE THREAD

**Issue by mablue** [2dust/v2rayNG#2262]
https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt

Matsuri have not this problem I think matsuri using hashmaps instade normal lists

**Comment by Farzi5451** [comment]
سلام چجوری کار میکنه

در شنبه ۶ مهٔ ۲۰۲۳،‏ ۱۶:۰۳ Masoud ***@***.*** نوشت:

**Comment by mablue** [comment]
@Farzi5451  Insert this link inside subscriptions page
![Screenshot_20230510-201708_v2rayNG](https://github.com/2dust/v2rayNG/assets/5004900/0f5e2f59-a07c-4944-a12e-4fe202709fc8)
