### ISSUE TITLE
关于路由优先级的问题

### ISSUE THREAD

**Issue by yang05051** [2dust/v2rayNG#2264]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
自定义路由中，Proxy的优先级应该比Block高

### 实际行为
Block的优先级比Proxy高

### 复现方法
1. 在Block和Proxy中同时添加 `domain:example.com`
2. 访问 `example.com` 被阻止

### 日志信息
略

### 环境信息
软件版本 v1.8.4，系统 One UI 5.1 (Android 13)

### 额外信息（可选）
希望自定义路由能够添加像 V2rayN 和 Matsuri 那样的自定义优先级排序的功能

**Comment by zym013579** [comment]
同样有这个需求，需要能够调整direct，proxy和block优先级的功能
