### ISSUE TITLE
aab包安装后无法连接VPN

### ISSUE THREAD

**Issue by zhengtingguang** [2dust/v2rayNG#2267]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常连接VPN

### 实际行为
无法加载so库导致无法连接VPN

### 复现方法
打包生成aab包，通过命令生成apks包，并且通过命令安装apk包，运行后出现异常

### 日志信息
<details>
java.io.IOException: Cannot run program "/data/app/~~5pfFRC6dBLUIf8OgDZd2fg==/com.tight.remotetools.ghost-kB4KBUwFVAnowuxYjokulg==/lib/arm64/libtun2socks.so" (in directory "/data/user/0/com.tight.remotetools.ghost/files"): error=2, No such file or directory

</details>

### 环境信息
gradle7.0.2

### 额外信息（可选）
android.bundle.enableUncompressedNativeLibs = false 没有效果
并且通过root的设备打印出/data/app/路径，apk包是有so文件的，aab包没有so文件

**Comment by budaowengd** [comment]
遇到同样的问题，请问兄弟是如何解决的？
