### ISSUE TITLE
ws+SSL异常报错

### ISSUE THREAD

**Issue by mlgexyz** [2dust/v2rayNG#227]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常连接
### 实际行为
无法连接

### 复现方法
1.使用安卓版本为5.1.1的手机
2.使用V2RayNG 0.6.x版本
3.使用ws+nginx ssl连接

### 日志信息
<details>

测速报错
```
SSL handshake timed out
```
服务器日志报错
```
rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
```
</details>

### 环境信息
Android 5.1.1
V2RayNG 0.6.8

### 额外信息（可选）
用隔壁的BifrostV以相同的服务器配置文件可以正常连接。

**Comment by mlgexyz** [comment]
#204 的情况也是这样子，共同特征为Android 5.1.1

**Comment by Hiiragi-Yuriko** [comment]
+1

环境信息
Android 8.1.0
V2RayNG 0.6.10

额外信息（可选）
自从0.6.8开始就出现这种情况
通知栏中有网速显示（约1Kb/s）

0.6.7可以正常连接

**Comment by 2dust** [comment]
无机器可以测试,这样的问题没有环境将不能解决
