### ISSUE TITLE
DNS/DoH/DoT/Quic

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#2270]
Please add support for better DNS options for both v2rayNG and v2rayN.

**Comment by meysamzeynali11** [comment]
mobleman beysbndye xbsienxmeydam nnxhwucns

**Comment by meysamzeynali11** [comment]
meyxbafzbnnmmaxdasaxndeysnz ndbazysnshdsaunwnxhs xhudsbdjdnxdgeucjnsnxsuekfoskbdxjudbenzja
