### ISSUE TITLE
pre-release 1.8.4./1.8.5 start service failure

### ISSUE THREAD

**Issue by Ali-Flt** [2dust/v2rayNG#2275]
I'm trying to connect to a grpc network vless connection with reality. v2rayNG version 1.8.4 or 1.8.5 won't start service and say start service failure. 
I tested a normal Vmess on tcp network and it work so it must be cause of this specific connection type.

**Comment by AliZf1d** [comment]
I have the same problem with vless reality, yesterday it was okay, but today it says start service failure.

**Comment by MJavad** [comment]
Removing geosite entries from direct custom rules fixed this for me

**Comment by mahpooya** [comment]
My problem was an already used port. I force closed all my VPNs and "start service failure" never happened again.
