### ISSUE TITLE
release playstore

### ISSUE THREAD

**Issue by xmohammad1** [2dust/v2rayNG#2276]
is been long time since last stable version been released in playstore , pls realse a new version with reality support  in playstore , we need it **badly**

**Comment by pouriaksrvi** [comment]
> is been long time since last stable version been released in playstore , pls realse a new version with reality support in playstore , we need it **badly**

Certainly it is on the way...
Anyway, just curious to know, why not downloading it through releases part in this repo?

**Comment by rezabakhshilaktasaraei** [comment]
Yes, Please update this app in Playstore. Iranian users are in teribble condition.

**Comment by PouryaDe** [comment]
> when i install manually, if google play auto update is enabled, it goes back to the latest version and reality settings don't work!!
> 
> Most users do not know how to disable auto update!

when i install manually, if google play auto update is enabled, it goes back to the latest version and reality settings don't work!!

Most users do not know how to disable auto update!

**Comment by PouryaDe** [comment]
> > is been long time since last stable version been released in playstore , pls realse a new version with reality support in playstore , we need it **badly**
> 
> Certainly it is on the way... Anyway, just curious to know, why not downloading it through releases part in this repo?

when i install manually, if google play auto update is enabled, it goes back to the latest version and Reality Configs don't work!!

Most users dont know how to disable auto update!

**Comment by xmohammad1** [comment]
> > is been long time since last stable version been released in playstore , pls realse a new version with reality support in playstore , we need it **badly**
> 
> Certainly it is on the way... Anyway, just curious to know, why not downloading it through releases part in this repo?

google play update is one of problems , ppl wanna update other apps they update this too and then they back to 1.7.38
i dont use solo i gave my configs to alot of ppls , they pm me hey configs don't connect and i see oh they update from google play and thats why . 
other problem is when you send them last version as file they think is might be unsafe to install elsewhere than google play, 
pls realese google play version we want it bad 
 , is most popular app for xray configs in iran ,
pls release googleplay version , thanks in advance
