### ISSUE TITLE
Please add gfw knocker to v2rayng.

### ISSUE THREAD

**Issue by alipour66m** [2dust/v2rayNG#2283]
main Idea:

in TLS protocol (even latest v1.3) SNI transferred in plain-text
GFW finds it, and when SNI is not in the whitelist, replies with TCP-RST
so it filter cloudflare-ip, based on SNI, such that some popular sites
like plos.org is open, and all other sites closed, through that ip
so we need to hide SNI from GFW
we fragment TLS "client Hello" packet into chunks in a simple manner
we show that it passes the firewall
more importantly, we show that GFW can't fix it because its nearly impossible
to cache TBs of data in high-speed router, so they MUST give up or break the whole network

look at this link
https://github.com/GFW-knocker/gfw_resist_tls_proxy

also v2rayng with gfw
https://github.com/rrouzbeh/v2rayNG

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Fatifan** [comment]
👍🏻

**Comment by Fatifan** [comment]
Please add this feature

**Comment by alipour66m** [comment]
Sir please investigate this idea

**Comment by Fatifan** [comment]
We need this feature to bypass the gfw in Iran

**Comment by khodealib** [comment]
Please add this feature
