### ISSUE TITLE
Error Unresolved reference: libv2ray

### ISSUE THREAD

**Issue by AliZamani-Developer** [2dust/v2rayNG#2286]
Hi, I get ".../com/v2ray/ang/service/V2RayServiceManager.kt:32:8 Unresolved reference: libv2ray" error while compiling
It seems that libv2ray.aar file is missing from the project
![Untitled](https://github.com/2dust/v2rayNG/assets/37456931/5982db50-0efd-476f-bbfe-8a45ade001a9)

**Comment by EliotGhorbani** [comment]
how did you fix it ? i have same error

**Comment by C007G** [comment]
解决了吗

**Comment by Mahdi2425** [comment]
ali chejori dorost kardi ali be manam bego
