### ISSUE TITLE
请求加入gfw-list

### ISSUE THREAD

**Issue by GavinZhengOI** [2dust/v2rayNG#229]
v2rayng的“绕过大陆地址”常常出锅。淘宝，知乎等都会自动代理。导致体验较差。
自定义路由也是很原始的逗号隔开域名，无法使用现有的正则表达式gfw-list。
希望加入gfw-list并支持正则表达式。
感谢

**Comment by qgtxqj** [comment]
ng路由默认是proxy，并不支持设置默认为direct。所以gfwlist实际意义不高。
ng自定义路由器支持正则表达式，直接写进去就好。

**Comment by GavinZhengOI** [comment]
@qgtxqj
我的意思就是能不能加入gfwlist这个选项，默认direct，list内的自动代理。
现在这样经常会代理国内应用，体验不是很好。（也不知道是不是只有我一个人这样）.而且因为你上面说的原因，无法通过自定义路由解决。所以就想请作者修改一下。谢谢

**Comment by GavinZhengOI** [comment]
@2dust 
刚刚去ng的tg群问了一下，不止我一个人有这种问题。很多人都是用的分应用代理+omega。感觉挺麻烦的。包括Google play很多人也在说这个问题。
我觉得如果加入这个功能会极大的优化体验。望大佬能考虑一下。
如果有什么说的不妥的，望大佬轻喷。感谢。

**Comment by LKorint** [comment]
0.6.7对绕过大陆和局域网支持较好，你可以先退到0.6.7

**Comment by llpub** [comment]
同样的问题，“绕过大陆地址”太多bug了，且“分应用模式”对谷歌框架这种复杂的程序很难界定。
希望加入“gfwlist这个选项，默认direct，list内的自动代理”

**Comment by pope-L** [comment]
好奇为何好多人都用分应用代理的

llpub <notifications@github.com> 于 2019年2月17日周日 09:40写道：

**Comment by llpub** [comment]
@pope-L 使用分应用代理是因为没有更好的办法解决许多国内（微信、淘宝etc.）流量走proxy而折中的。
一些不必要的流量走proxy不但加载慢，而且浪费了小鸡的宝贵流量，（还有更耗电？）

**Comment by pope-L** [comment]
我设为全局，绕过大陆地址，在微信里打开ipip.net
显示的都是国内地址呢

llpub <notifications@github.com> 于 2019年2月17日周日 13:24写道：

**Comment by GavinZhengOI** [comment]
> 我设为全局，绕过大陆地址，在微信里打开ipip.net 显示的都是国内地址呢 llpub <notifications@github.com> 于 2019年2月17日周日 13:24写道：
> […](#)

我跟你一样的设置。
我感觉这个东西看脸。我淘宝有的时候是正常的，有的时候问我要不要跳到美国站。
而且浏览器中浏览国内网站常常自动代理。

**Comment by pope-L** [comment]
刚发现ss有v2插件 还没试用，你们可以试下

GavinZhengOI <notifications@github.com> 于 2019年2月17日周日 14:04写道：

**Comment by NatralMicsear** [comment]
还是先用BifrostV吧，这个支持GFWList

**Comment by llpub** [comment]
作者好像说过v2rayNG不会考虑GFWList。
推荐kitsunebi android版，也是开源无广告，规则列表支持自定义（纯文本的规则列表，可以自己弄GFWList）；
好像还有一些其它v2ray的android客户端，大家试用过的可以分享一下。
BifrostV有广告，并且不开源不太敢用。

**Comment by 2dust** [comment]
请用最新版开启本地dns
如果不能解决你的问题真是抱歉了
本app只支持core支持的特性
