### ISSUE TITLE
Trojan-go 开启 forward_proxy ，就出现 “net/http: TLS handshake timeout" 错误，但其他客户端 如 Clash 都能正常使用

### ISSUE THREAD

**Issue by taylorwin** [2dust/v2rayNG#2296]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Trojan-go 开启 forward_proxy  正常使用

### 实际行为

Trojan-go 开启 forward_proxy ，就出现 “net/http: TLS handshake timeout" 错误

### 复现方法
1.Trojan-go 开启 forward_proxy 
2.v2rayNG 点击测试连接

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by zhouxiong100** [comment]
我今天也遇到了，重启了服务器就好了

**Comment by taylorwin** [comment]
我是重起，加证书替换都干过，不行。
