### ISSUE TITLE
编译过程出错

### ISSUE THREAD

**Issue by phoenixxie0** [2dust/v2rayNG#23]
/opt/src/v2rayNG/V2rayNG(master) # bash ./gradlew build                                                                                           root@BuildHost
e: /opt/src/v2rayNG/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/BaseDrawerActivity.kt: (16, 22): Unresolved reference: InappBuyActivity
e: /opt/src/v2rayNG/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/BaseDrawerActivity.kt: (66, 39): Unresolved reference: InappBuyActivity
e: /opt/src/v2rayNG/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/MainActivity.kt: (30, 22): Unresolved reference: InappBuyActivity
e: /opt/src/v2rayNG/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/MainActivity.kt: (564, 31): Unresolved reference: InappBuyActivity
e: /opt/src/v2rayNG/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/SettingsActivity.kt: (12, 22): Unresolved reference: InappBuyActivity

**Comment by 2dust** [comment]
Do it yourself
