### ISSUE TITLE
小米11  系统14.0.9.0无法启动v2rayNG

### ISSUE THREAD

**Issue by hans822418** [2dust/v2rayNG#2301]
最新1.8.5版本显示启动失败![SAVE_20230522_243714.jpg](https://github.com/2dust/v2rayNG/assets/67779256/ad97a580-8e0e-4224-9d83-5ba165dcfce7)

使用最以前的1.7.38版本可以正常启动

**Comment by cairong** [comment]
小米13，miui14.0.24，安卓13，v2rayNG1.8.5，服务启动失败

**Comment by lmzj** [comment]
一加9，安卓13，v2rayNG1.8.5，和你同样的问题服务启动失败，以前都是正常的，昨天晚上自动升级后就启动失败了

**Comment by bjtea** [comment]
红米K50 v2rayNG1.8.5，服务启动失败，同样的问题，原来都能正常使用。

**Comment by xzl31415926** [comment]
1.6.28没办法使用，而且跨越长城的网站也无法登录了

**Comment by Kikyo-chan** [comment]
论原生安卓系统的重要性，国内厂商的安卓都是阉割版，希望对你有帮助。结合这个思路排查问题。

**Comment by Kikyo-chan** [comment]
论原生安卓系统的重要性，国内厂商的安卓都是阉割版，希望对你有帮助。结合这个思路排查问题。

**Comment by oliver-yu** [comment]
论原生安卓系统的重要性，国内厂商的安卓都是阉割版，希望对你有帮助。结合这个思路排查问题。

**Comment by miller-xue** [comment]
论原生安卓系统的重要性，国内厂商的安卓都是阉割版，希望对你有帮助。结合这个思路排查问题。
