### ISSUE TITLE
是否支持选择某些APP通过代理

### ISSUE THREAD

**Issue by Wudelin** [2dust/v2rayNG#231]

**Comment by Palatis** [comment]
it does, in settings.

**Comment by Wudelin** [comment]
我服务端通过https://guide.v2fly.org/basics/shadowsocks.html 配置，客户端手动添加shadowsocks，连接成功,SSL handshake timed out,请问是什么原因

**Comment by Wudelin** [comment]
服务端开启了1024 10086端口

**Comment by Wudelin** [comment]
能否提供您服务端的配置？

**Comment by Palatis** [comment]
> 
> 
> 我服务端通过https://guide.v2fly.org/basics/shadowsocks.html 配置，客户端手动添加shadowsocks，连接成功,SSL handshake timed out,请问是什么原因

you must be in China, blame your government.

try VMess over WebSocket + TLS.

BTW, this is not a good place to ask for server side config.
