### ISSUE TITLE
联发科天玑1100处理器使用V2RAYNG发热延迟高

### ISSUE THREAD

**Issue by HJ1F12** [2dust/v2rayNG#2313]
版本：1.8.5
环境：VLESS+gRPC+TLS（xray）
高通晓龙660&750G处理器使用程序无明显发热，且节点测试连接延迟正常情况下在490-530ms之间；联发科天玑1100使用延迟飙升至790-880ms，而且有明显发热现象。
以上情况为相同设置&测试环境发现

**Comment by HJ1F12** [comment]
PS：尝试过更换旧版本，结果一样

**Comment by zxbiao** [comment]
难道不是一核有难，七核围观的原因吗？
![image](https://github.com/2dust/v2rayNG/assets/4557810/8e9a630e-284a-452e-ad42-75a6dbd558f5)
