### ISSUE TITLE
增加支持geo客户端去广告

### ISSUE THREAD

**Issue by libratwo** [2dust/v2rayNG#233]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
客户端支持geo去广告

### 实际行为
从文件导入配置，路由中增加对
"domain":["geosite:category-ads"]的配置，会导致v2ray无法启动

### 复现方法
1. 导出完整配置
2. 修改配置增加对geosite:category-ads的blackhole的路由规则
3. 无法启动

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
个人期望geosite.dat文件可以UI入口进行后期导入，便于网站列表的更新独立于程序（或者使用其他人的定制化清单），请评估可行性

**Comment by libratwo** [comment]
客户端配置文件：
{
  "dns":{
    "servers":[{
// 强制国内的走alidns
      "address": "223.5.5.5",
      "port":53,
      "domains": ["domain:geosite:cn"]
    },
// 其他的dns丢弃，直接转发到服务器解析（避免访问被墙域名被检测）
    "127.0.0.1"]
  },
  "inbounds":[{
      "port":10808,
      "protocol":"socks",
      "settings":{
        "auth":"noauth","udp":true
      },
      "sniffing":{
        "destOverride":["http","tls"],
        "enabled":true
      }
    }],
  "log":{
    "loglevel":"warning"
  },
  "outbounds":[{
      "mux":{
        "enabled":false
      },
      "protocol":"vmess",
      "settings":{
        "vnext":[{
            "address":"4togo.tk",
            "port":443,
            "users":[{
                "alterId":32,
                "id":"9cd713ac-7b39-4c5d-939b-22e501624882",
                "security":"auto"
              }]
          }]
      },
      "streamSettings":{
        "network":"ws",
        "security":"tls",
        "tlssettings":{
          "allowInsecure":true,
          "serverName":""
        },
        "wssettings":{
          "connectionReuse":true,
          "headers":{
            "Host":""
          },
          "path":"/easygo"
        }
      },
      "tag":"proxy"
    },
    {
      "protocol":"freedom",
      "settings":{},
      "tag":"direct"
    },
    {
      "protocol":"blackhole",
      "settings":{
        "response":{
          "type":"http"
        }
      },
      "tag":"block"
    }],
  "routing":{
    "settings":{
      "domainStrategy":"IPIfNonMatch",
      "rules":[{
// 本地去广告（网站黑名单可用，单geosite无法启动）
          "domain":["geosite:category-ads"],
          "outboundTag":"block",
          "type":"field"
        },
        {
          "ip":["geoip:private"],
          "outboundTag":"direct",
          "type":"field"
        },
        {
          "ip":["geoip:cn"],
          "outboundTag":"direct",
          "type":"field"
        },
        {
          "domain":["geosite:cn"],
          "outboundTag":"direct",
          "type":"field"
        }]
    },
    "strategy":"rules"
  }
}

**Comment by boypt** [comment]
现在版本就可以啊，自定义路由 - 阻止的网址或IP里面加入`geosite:category-ads`即可。

可更新geosite.dat是个不错的建议，看看 @2dust 的意见？

**Comment by 2dust** [comment]
加入`geosite:category-ads`即可。
