### ISSUE TITLE
功能需求：连接按钮位置变更/自定义

### ISSUE THREAD

**Issue by byzod** [2dust/v2rayNG#233]
连接的按钮在最右边, 单左手按不太到...

建议放左边, 或者可自定义位置满足左右撇子

或者像SSR/bifrost一样增加小部件按钮开关

**Comment by hyxxsfwy** [comment]
通知栏有小部件开关，自己找找。

**Comment by byzod** [comment]
> 通知栏有小部件开关，自己找找。

没找到看起来相关的按钮或者小部件, 能否提供图片或视频指引？

**Comment by byzod** [comment]
还是说你指连接后通知栏消息下面那个X？
……没连接前没有通知栏条目，没法操作啊，能操作也只有一个X没法连接啊……

**Comment by hyxxsfwy** [comment]
> > 通知栏有小部件开关，自己找找。
> 
> 没找到看起来相关的按钮或者小部件, 能否提供图片或视频指引？

我指的是这个：

 <img src="https://user-images.githubusercontent.com/3905989/72145351-537d6980-33d5-11ea-84da-f3c88d513e00.jpg" width = "360" alt="通知栏开关" align=center />

**Comment by byzod** [comment]
也就是快捷开关吧
我这里看不到，是因为系统太老吗
是这个→cm-13.0-20160418-SNAPSHOT-ZNH0EAO2NN-ham (android 6.0.1)
