### ISSUE TITLE
手机4G 5G无法连接，WiFi可以连接

### ISSUE THREAD

**Issue by ilhuyi** [2dust/v2rayNG#2335]
最近在手机上无法正常使用，使用移动、联通、电信三个运营商的移动4G 5G网络均无法连接，提示io：read/write on closed pipe，但是连接到宽带WiFi和用PC，都能正常使用，打开反代网站也跳转到了默认的nginx页面，不是之前设置的反代网页了，请高手帮忙指点解决，谢谢！

**Comment by pyyii** [comment]
我和你正好反过来，具体我是移动网络下一切正常，但是使用WIFI的话，无法浏览网页，提示 name not resolved，NG里面什么设置都试过了，包括勾选本地DNS和虚拟DNS，远程DNS改为google的DOH，开启和关闭ipv6，跳过证书验证开和关，统统都试过，还是提示name not resolved。但是，电报或者其他app还是能正常用，就只有浏览器无法打开网页，但同样的节点服务器，PC端上却没有任何问题。搞得我头都大了。

**Comment by pyyii** [comment]
> 我和你正反过来，具体我是移动网络下一级正常，但是是使用WIFI的话，无法浏览网页，提示name not resolved，NG里面什么设置都试过了，包勾选本地DNS和虚拟DNS，远程DNS改为google的DOH，开启和关闭ipv6，跳过证书验证开启和关闭，统计都测试过，还是提示name not resolved。但是，电报或者其他app还是能正常使用，就只有浏览器无法打开网页，但是同样的节点服务器，PC端却没有任何问题。搞得我头都大了。

    解决了，具体原因是我禁用了对应浏览器的流量数据使用权限。
    但是讲道理不应该的，因为我是走的wlan，为啥把流量禁用了，wlan也不能用，必须重新勾上浏览器的流量使用开关，才能用。 
    但是不开v2rayng的话，就不受此操作影响，不过就只能打开国内网站了。

**Comment by jasonyacn** [comment]
我这几天也有类似情况，在wifi环境下，v2rayNG客户端节点连接失败，但如果切换成电信流量上网，却可以连通。不知道是什么问题
