### ISSUE TITLE
鸿蒙系统更新后，VPN方式的分应用无法使用了。

### ISSUE THREAD

**Issue by iclodq** [2dust/v2rayNG#2336]
Mate 30 pro 5G    HarmonyOS 3.0.0 
可能是最近几次的手机系统更新导致分应用代理无法使用了。
无法使用的APP，包括火狐浏览器/twitter/pureAPK
剩下唯一能用的Telegram。
v2rayNG，刚才已经安装最新版1.8.5.

代理服务器是好的，因为Telegram能使用。

**Comment by LJunTing** [comment]
把应用自启动打开就行

**Comment by iclodq** [comment]
> 把应用自启动打开就行

应用自启动打开是指？  v2rayNG 软件吗？  我没看到选项呢。

**Comment by LJunTing** [comment]
手机管家里 自启动管理
