### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by mahdikarimi5509** [2dust/v2rayNG#2343]
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:26:8 Unresolved reference: go
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:30:8 Unresolved reference: libv2ray
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:31:8 Unresolved reference: libv2ray
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:32:8 Unresolved reference: libv2ray
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:44:21 Unresolved reference: V2RayPoint
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:44:34 Unresolved reference: Libv2ray
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:52:13 Unresolved reference: Seq
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:53:13 Unresolved reference: Libv2ray
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:80:35 Unresolved reference: V2RayVPNServiceSupportsSet
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:81:9 'shutdown' overrides nothing
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:93:9 'prepare' overrides nothing
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:97:9 'protect' overrides nothing
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:102:9 'onEmitStatus' overrides nothing
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:107:9 'setup' overrides nothing
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:141:24 Variable expected
e: file:///C:/Users/parsa/Desktop/v2rayNG-master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:142:24 Variable expected

**Comment by janahnovin** [comment]
I have the same problem, please help me
