### ISSUE TITLE
打包成aab包安装，启动vpn报错

### ISSUE THREAD

**Issue by caoxingM** [2dust/v2rayNG#2347]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
打包成aab安装运行成功

### 实际行为
运行
process = proBuilder
                    .directory(applicationContext.filesDir)
                    .start()
完整的cmd
[/data/app/~~LNqwb6bYdPcc9-DEafjB9Q==/com.shuima.devote-wyIX3g2E5LMY8ezHnvQwhQ==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
报错
java.io.IOException: Cannot run program "/data/app/~~LNqwb6bYdPcc9-DEafjB9Q==/com.shuima.devote-wyIX3g2E5LMY8ezHnvQwhQ==/lib/arm64/libtun2socks.so" (in directory "/data/user/0/com.shuima.devote/files"): error=2, No such file or directory

同样的打包出APK没有问题但是打包成AAB包就有问题
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by IceThomas** [comment]
我出现过相同的问题，以下是我的解决方案，看看对你是否有帮助：
检查下你的 minSdkVersion 是多少 如果是23及以上，需要在mainfest文件的app标签下加上android:extractNativeLibs="true"这个属性，API23以上对so解压逻辑做了修改，需要加上这个属性才能解压到正确的位置

**Comment by caoxingM** [comment]
> 

非常感谢，虽然没有给我解决问题但是提供了解决思路(没有解压到指定的位置)。
下面是晚上找的解决办法
https://github.com/2dust/v2rayNG/issues/2347#issuecomment-1590761379

**Comment by llxlpej** [comment]
> 

你好我也是遇到这个问题，麻烦问一下你是怎么解决的谢谢

**Comment by caoxingM** [comment]
原因是因为so库没有解压到正确的位置


今夕何夕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2dust/v2rayNG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月15日(星期二) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [2dust/v2rayNG] 打包成aab包安装，启动vpn报错 (Issue #2347)





   
你好我也是遇到这个问题，麻烦问一下你是怎么解决的谢谢

**Comment by budaowengd** [comment]
你好，解决了吗，遇到同样的问题了，请问你们是如何解决的？
