### ISSUE TITLE
访问google play时从服务器检索信息时出错 [DF-DFERH-01

### ISSUE THREAD

**Issue by Hunerk** [2dust/v2rayNG#235]
S10 最新版固件，刷了极光包。
v2ray默认配置，其它软件都能正常访问，
只有play 一直是
从服务器检索信息时出错

**Comment by Hunerk** [comment]
已试了好几个国家的节点都不行，访问十次有一次能上的样子

**Comment by gayhobuser** [comment]
三星s10（安卓10）升级1.1.15版本完全无法代理

**Comment by ayanamist** [comment]
把`services.googleapis.cn`加入代理列表 from shadowsocks/shadowsocks-android#1016

**Comment by lsave** [comment]
s20同样的问题

**Comment by VarroReve** [comment]
s20 +1
