### ISSUE TITLE
DNS路由没有按预期工作，似乎有dns泄露

### ISSUE THREAD

**Issue by momo20-mo** [2dust/v2rayNG#2351]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Dns按照设置里的查询，远程dns，境内dns都按设置的指定dns服务器查询

### 实际行为

Dns没有按照设置里的查询.
### 复现方法
1.dns服务器设置www.google.com为68.59.9.9

2,,,启动本地dns选项，远程dns，境内dns都设置为上个dns服务器
3.访问www.google.com,竟然可以打开
4.访问百度，dns服务器的日志是返回的国外ip,但是访问百度竟然是国内ip,

通过路由器dns日志发现，软件的每个dns查询都会使用系统dns查询

**Comment by chika0801** [comment]
参考此自定义配置的逻辑

https://github.com/chika0801/Xray-examples/blob/main/v2rayNG_custom.json

**Comment by momo20-mo** [comment]
按照这个逻辑，没看到有要使用系统dns，是默认就是用系统查询吗，所以不用写？按这个逻辑，即使v2rayng的境内外dns都设置错误的（dns服务器可用，但返回结果是错误的）,v2rayng都能获取到正确的ip,（测试了一下，还真是这样啊）

**Comment by chika0801** [comment]
建议你不要管DNS泄露这事，这事不是你VPS端口被封的因素。如果你要研究懂，需要学透明代理环境下DNS请求谁接管，走哪个core比如xray xray配置文件中的处理流程，等于你还要学xray配置的工作原理，最后结果你能在那些检查网站检查是不露。

如果不想学，上面作者提供的示例改改就能用了。
