### ISSUE TITLE
更换手机后发生了根本性的使用问题，无法正常使用

### ISSUE THREAD

**Issue by shizuka612** [2dust/v2rayNG#2352]
目前来看是延迟过高，保底三千以上的延迟，五六千是常态，高的时候八九千，相同的节点相同的apk在其他手机上就没有这个问题。

**Comment by shizuka612** [comment]
就算一直开着应用，也是一样的，想正常使用就得一直点击应用窗口，升级最新版本也无济于事

**Comment by shizuka612** [comment]
原来的手机没有这个问题，pc端没有这个，新手机用ss也没有这个问题

**Comment by cfh-7598** [comment]
有没有可能是升级了最新的安卓系统问题呢？我用的是 oppo，最近也是延迟很高，甚至经常中断，电脑没啥事，而且电脑连手机的热点也没事儿。
