### ISSUE TITLE
境内服务器代理socks5：failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1

### ISSUE THREAD

**Issue by huo108** [2dust/v2rayNG#2354]
问题说明
阿里云自己搭建的socks5服务，服务器是国内的，出口和入口已经配置好，使用自己编译的V2rayNG连接代理

配置：{
                                                                                                                  "dns": {
                                                                                                                    "hosts": {
                                                                                                                      "domain:googleapis.cn": "googleapis.com"
                                                                                                                    },
                                                                                                                    "servers": [
                                                                                                                      "1.1.1.1"
                                                                                                                    ]
                                                                                                                  },
                                                                                                                  "inbounds": [
                                                                                                                    {
                                                                                                                      "listen": "127.0.0.1",
                                                                                                                      "port": 10808,
                                                                                                                      "protocol": "socks",
                                                                                                                      "settings": {
                                                                                                                        "auth": "noauth",
                                                                                                                        "udp": true,
                                                                                                                        "userLevel": 8
                                                                                                                      },
                                                                                                                      "sniffing": {
                                                                                                                        "destOverride": [
                                                                                                                          "http",
                                                                                                                          "tls"
                                                                                                                        ],
                                                                                                                        "enabled": true
                                                                                                                      },
                                                                                                                      "tag": "socks"
                                                                                                                    },
                                                                                                                    {
                                                                                                                      "listen": "127.0.0.1",
                                                                                                                      "port": 10809,
                                                                                                                      "protocol": "http",
                                                                                                                      "settings": {
                                                                                                                        "userLevel": 8
                                                                                                                      },
                                                                                                                      "tag": "http"
                                                                                                                    }
                                                                                                                  ],
                                                                                                                  "log": {
                                                                                                                    "loglevel": "warning"
                                                                                                                  },
                                                                                                                  "outbounds": [
                                                                                                                    {
                                                                                                                      "mux": {
                                                                                                                        "concurrency": 8,
                                                                                                                        "enabled": false
                                                                                                                      },
                                                                                                                      "protocol": "socks",
                                                                                                                      "settings": {
                                                                                                                        "servers": [
                                                                                                                          {
                                                                                                                            "address": "59.110.**.***",
                                                                                                                            "level": 8,
                                                                                                                            "method": "chacha20-poly1305",
                                                                                                                            "ota": false,
                                                                                                                            "password": "",
                                                                                                                            "port": 50101,
                                                                                                                            "users": [
                                                                                                                              {
                                                                                                                                "level": 8,
                                                                                                                                "pass": "xxxxx",
                                                                                                                                "user": "xxxxxx"
                                                                                                                              }
                                                                                                                            ]
                                                                                                                          }
                                                                                                                        ]
                                                                                                                      },
                                                                                                                      "streamSettings": {
                                                                                                                        "network": "tcp",
                                                                                                                        "security": ""
                                                                                                                      },
                                                                                                                      "tag": "proxy"
                                                                                                                    },
                                                                                                                    {
                                                                                                                      "protocol": "freedom",
                                                                                                                      "settings": {},
                                                                                                                      "tag": "direct"
                                                                                                                    },
                                                                                                                    {
                                                                                                                      "protocol": "blackhole",
                                                                                                                      "settings": {
                                                                                                                        "response": {
                                                                                                                          "type": "http"
                                                                                                                        }
                                                                                                                      },
                                                                                                                      "tag": "block"
                                                                                                                    }
                                                                                                                  ],
                                                                                                                  "routing": {
                                                                                                                    "domainStrategy": "IPIfNonMatch",
                                                                                                                    "rules": [
                                                                                                                      {
                                                                                                                        "ip": [
                                                                                                                          "1.1.1.1"
                                                                                                                        ],
                                                                                                                        "outboundTag": "proxy",
                                                                                                                        "port": "53",
                                                                                                                        "type": "field"
                                                                                                                      },
                                                                                                                      {
                                                                                                                        "ip": [
                                                                                                                          "192.168.8.37",
                                                                                                                          "192.168.9.18",
                                                                                                                          "192.168.8.102"
                                                                                                                        ],
                                                                                                                        "outboundTag": "direct",
                                                                                                                        "type": "field"
                                                                                                                      }
                                                                                                                    ]
                                                                                                                  },
                                                                                                                  "stats": {}
                                                                                                                }

### 预期行为
可以在浏览器或者抖音能正常打开页面和浏览视频

### 实际行为
只能打开百度等部分页面，抖音无法正常浏览视频
同样的环境下使用Postern代理，可以正常浏览网页和视频

### 复现方法
1.配置正确的socks5代理信息
2.配置全局代理，开启速度显示，开启流量探测
3.启动代理

### 日志信息
<details>

```
23-06-19 17:14:20.426 24539-24593 GoLog                    I  2023-06-19 09:14:20 114.114.114.114:53
2023-06-19 17:14:20.427 24539-24593 GoLog                    I  [Warning] [2991234899] app/dispatcher: default route for 1 udp:114.114.114.114:53
2023-06-19 17:14:20.427 24539-24595 GoLog                    I  udp:127.0.0.1:43629 accepted udp:114.114.114.114:53 [proxy]
2023-06-19 17:14:20.533 24539-24588 GoLog                    I  [Warning] [2991234899] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:20.686 24539-24588 GoLog                    I  [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:20.909 24539-24595 GoLog                    I  udp:127.0.0.1:44211 accepted udp:1.1.1.1:53 [proxy]
2023-06-19 17:14:21.014 24539-24595 GoLog                    I  [Warning] [528461427] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:21.698 24539-24588 GoLog                    I  udp:127.0.0.1:47250 accepted udp:1.1.1.1:53 [proxy]
2023-06-19 17:14:21.834 24539-24595 GoLog                    I  [Warning] [1664396133] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:21.976 24539-24588 GoLog                    I  2023-06-19 09:14:21 114.114.114.114:53
2023-06-19 17:14:21.979 24539-24588 GoLog                    I  [Warning] [12379164] app/dispatcher: default route for 1 udp:114.114.114.114:53
2023-06-19 17:14:21.979 24539-24588 GoLog                    I  udp:127.0.0.1:38415 accepted udp:114.114.114.114:53 [proxy]
2023-06-19 17:14:22.082 24539-24593 GoLog                    I  [Warning] [12379164] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:22.169 24539-24593 GoLog                    I  udp:127.0.0.1:46356 accepted udp:1.1.1.1:53 [proxy]
2023-06-19 17:14:22.204 24539-24589 GoLog                    I  fdConn unix.Connect err, Close Fd: 125 Err: connection timed out
2023-06-19 17:14:22.207 24539-24593 GoLog                    I  udp:127.0.0.1:47049 accepted udp:1.1.1.1:53 [proxy]
2023-06-19 17:14:22.243 24539-24595 GoLog                    I  [Warning] [719022520] app/dispatcher: default route for 1 tcp:sp1.baidu.com:443
2023-06-19 17:14:22.244 24539-24595 GoLog                    I  tcp:127.0.0.1:40210 accepted tcp:104.193.88.77:443 [proxy]
2023-06-19 17:14:22.247 24539-24589 GoLog                    I  [Warning] [360217593] app/dispatcher: default route for 1 tcp:sp1.baidu.com:443
2023-06-19 17:14:22.249 24539-24589 GoLog                    I  tcp:127.0.0.1:40214 accepted tcp:104.193.88.77:443 [proxy]
2023-06-19 17:14:22.269 24539-24588 GoLog                    I  [Warning] [3456826938] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:22.306 24539-24823 GoLog                    I  Not Using Prepared: tcp,198.18.0.6:80
2023-06-19 17:14:22.323 24539-24589 GoLog                    I  [Warning] [1556603600] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:22.347 24539-24589 GoLog                    I  [Warning] [360217593] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
2023-06-19 17:14:22.348 24539-24592 GoLog                    I  [Warning] [719022520] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects account: 1
```
</details>

### 环境信息
境内阿里云服务器，自行搭建的socks5服务，开启所有进出口作为测试

**Comment by Wanzhu1420** [comment]
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "concurrency": 8,
        "enabled": false
      },
      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "CS2S.YIYONEX.COM",
            "flow": "",
            "level": 8,
            "method": "chacha20-poly1305",
            "ota": false,
            "password": "c654a244-f37a-3a3c-9858-640b13d29538",
            "port": 34500
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "tlsSettings": {
          "allowInsecure": true,
          "serverName": "mpvideo.qpic.cn"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "routing": {
    "domainMatcher": "mph",
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      }
    ]
  }
}
