### ISSUE TITLE
手机端ss类型节点，可否支持使用SagerNet Core，希望支持手机端协议内核绑定

### ISSUE THREAD

**Issue by x64bugreport** [2dust/v2rayNG#2359]
### 预期行为
描述你认为应该发生什么
希望手机端支持如下配置，绑定协议和内核
![555](https://github.com/2dust/v2rayNG/assets/34920463/f757154f-8905-49af-9934-95b0315c391a)

### 实际行为
描述实际发生了什么
部分ss节点需要使用aes-256-cfb模式，只有SagerNet Core支持，手机端默认无法切换内核，导致无法正常使用
### 复现方法
![333](https://github.com/2dust/v2rayNG/assets/34920463/4581e192-50c5-4a08-b9d1-17ad91cc3ffe)

**Comment by ali36000000** [comment]
hello
