### ISSUE TITLE
import trojan reality

### ISSUE THREAD

**Issue by MHCloner** [2dust/v2rayNG#2360]
there is a bug in app that when i import trojan reality config:

publickey,shortid,spiderx are empty, even thought those were in config!
so u need to add it manually after config imported.

i used 1.8.5 version.

**Comment by moh3nat** [comment]
i have this issue too :(

**Comment by RangerRU** [comment]
+++

**Comment by RezaKardoost** [comment]
Same issue

**Comment by RangerRU** [comment]
!!!
