### ISSUE TITLE
Grpc and reality Not working!

### ISSUE THREAD

**Issue by arisalehi** [2dust/v2rayNG#2368]
Dear guys

I wonder why, the latest version of V2rayNG, 1.8.5 does not work properly on some android clients such as Samsung or Xiaomi. In details, some configs based on "grpc" and "reality" does not work in these clients. Anyone had the same issue???

在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by M03ED** [comment]
I had this problem, there was something common between all the clients had this problem, they all installed v2rayng from google play , after they download GitHub version problem solved.

**Comment by arisalehi** [comment]
Ok, 
Firstly, thank you for your answer. But, what if the apk file on GitHub shows an error during installation?

**Comment by M03ED** [comment]
They should delete last version, this is because google play and GitHub have different signature.

**Comment by arisalehi** [comment]
Ok, I got it now.
