### ISSUE TITLE
自己编译的v2rayNG无法连接成功

### ISSUE THREAD

**Issue by LGDhuanghe** [2dust/v2rayNG#2369]
### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
按文档说明在AndroidLibXrayLite编译出libv2ray.aar放到libs后可以编译安装apk，但是填写配置连接后无法正常上网，
安装release里的apk则可以正常联网。代码仅修改了gradle版本7.2.1使得编译可以通过。

### 日志信息
<details>
I/GoLog: new core
I/GoLog: start core
I/GoLog: [Warning] core: Xray 1.8.1 started
I/TetheringManager: registerTetheringEventCallback:com.v2ray.ang
D/com.v2ray.ang: [/data/app/~~kyVwp0CYIG6gwuXC3m26zA==/com.v2ray.ang-4uLnzinQGoWq05jzj4Anlg==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:1080, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
D/com.v2ray.ang: Process[pid=24992, hasExited=false]
D/com.v2ray.ang: libtun2socks.so check
D/com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
D/com.v2ray.ang: sendFd tries: 0
I/GoLog: Not Using Prepared: udp,119.29.29.29:53
I/GoLog: udp:127.0.0.1:42977 accepted udp:119.29.29.29:53 [socks -> direct]
I/GoLog: DNS accepted udp:8.8.8.8:53 [xray.system.3f95dd5b-119b-4c4b-bb00-f413bf919f29 -> proxy]
I/GoLog: DNS accepted udp:8.8.8.8:53 [xray.system.3f95dd5b-119b-4c4b-bb00-f413bf919f29 -> proxy]
I/GoLog: fdConn unix.Connect err, Close Fd: 94 Err: connection timed out
I/GoLog: Not Using Prepared: udp,223.5.5.5:53
I/GoLog: DNS accepted udp:223.5.5.5:53 [xray.system.3f95dd5b-119b-4c4b-bb00-f413bf919f29 -> direct]
I/GoLog: fdConn unix.Connect err, Close Fd: 95 Err: connection timed out
I/GoLog: Not Using Prepared: udp,223.5.5.5:53
I/GoLog: DNS accepted udp:223.5.5.5:53 [xray.system.3f95dd5b-119b-4c4b-bb00-f413bf919f29 -> direct]
I/GoLog: fdConn unix.Connect err, Close Fd: 94 Err: connection timed out
</details>

### 环境信息
AndroidStudio 2021.2.1 patch 1

**Comment by maskedeken** [comment]
问题在这一行
[https://github.com/2dust/AndroidLibXrayLite/blob/607b5526a7c7978b83cd85d60d30e42050be85e5/libv2ray_support.go#L292](https://github.com/2dust/AndroidLibXrayLite/blob/607b5526a7c7978b83cd85d60d30e42050be85e5/libv2ray_support.go#L292)

改成 copy(sa.Addr[:], ip.To16()) 即可

**Comment by sansan-cc** [comment]
bro，aar 能分享一下嘛
