### ISSUE TITLE
希望能提供境内DNS的策略功能

### ISSUE THREAD

**Issue by CharlesWou** [2dust/v2rayNG#2373]
由于223.5.5.5等公共DNS实际上并没有ISP运营商自身提供的DNS优秀，解析到的地址并非本地最佳IP，往往导致国内网页打开较缓慢（即使开了本地DNS及fakedns）

而在Android的Xray-Core配置文件中，即使设置dns为“localhost”，也无法自动获取运营商提供的DNS
所以

希望能提供境内DNS的策略功能，即让用户可以手动配置，对于连接不同的WIFI信号或者数据流量，可以手动设置不同的境内DNS

或者，最差情况，可以在每个连接的配置框中添加本地DNS配置选项，可以使用自定义的境内DNS，而非软件设置里面统一的境内DNS：223.5.5.5（当然，导入完整的配置文件，自己修改是可以，就是比较麻烦，没有界面中修改直观）

**Comment by laaArmy** [comment]
对，我也纳闷，为什么不能设置本地运营商作为DNS？？？

**Comment by Platway** [comment]
localhost实际上没用，我也郁闷了很久。运营商DNS始终还是最快的最好的

**Comment by Platway** [comment]
补充：我用的一个开源的广告域名过滤app叫DNS66（ https://github.com/julian-klode/dns66 ）会自动使用本地运营商DNS，说明这是可以实现的。供参考。谢谢！
