### ISSUE TITLE
PlayStore release

### ISSUE THREAD

**Issue by alivezvar** [2dust/v2rayNG#2375]
Hello
When I get aab output from this source for Play Store, the vpn connection is not established.
If the connection is established well in the apk output.

**Comment by devrx5** [comment]
@alivezvar Did you manage to solve this problem?

**Comment by alivezvar** [comment]
hi
use this code in app build.gradle android block :

 packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
