### ISSUE TITLE
关于访问蓝奏云被代理导致无法访问的问题麻烦解决一下，谢谢

### ISSUE THREAD

**Issue by ahaha122** [2dust/v2rayNG#2383]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
访问蓝奏云时，应该绕过代理。

### 实际行为
被代理了，无法访问

### 复现方法
1.设置一下绕过代理。

### 日志信息
<details>
--------- beginning of main
07-03 18:53:22.987 I/GoLog   (32744): 127.0.0.1:40957 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
07-03 18:53:22.988 I/GoLog   (32744): 127.0.0.1:60091 accepted udp:1.1.1.1:53 [dns-in -> dns-out]
07-03 18:53:22.998 I/GoLog   (32744): tcp:127.0.0.1:44452 accepted tcp:180.95.234.190:443 [socks >> proxy]
07-03 18:53:23.248 I/GoLog   (32744): Using Prepared: 142.4.99.77
07-03 18:53:23.917 I/GoLog   (32744): tcp:127.0.0.1:44458 accepted tcp:13.107.21.200:443 [socks >> proxy]
07-03 18:53:24.166 I/GoLog   (32744): Using Prepared: 142.4.99.77
07-03 18:53:24.948 I/GoLog   (32744): tcp:127.0.0.1:44464 accepted tcp:13.107.21.200:443 [socks >> proxy]
07-03 18:53:25.196 I/GoLog   (32744): Using Prepared: 142.4.99.77
07-03 18:53:25.948 I/GoLog   (32744): tcp:127.0.0.1:44470 accepted tcp:13.107.21.200:443 [socks >> proxy]
07-03 18:53:26.194 I/GoLog   (32744): Using Prepared: 142.4.99.77

</details>

### 环境信息
Android 10.1 V2ray v1.8.5( Lib v24, Xray - core v1.8.1)
### 额外信息（可选）
麻烦解决一下，谢谢啦！
![Screenshot_20230703_185531_com microsoft emmx](https://github.com/2dust/v2rayNG/assets/121830230/bfc54717-934d-4046-bde8-ba4f2f35564a)

**Comment by xiaorong61** [comment]
可以自己到设置里面加白名单
