### ISSUE TITLE
Request Feature to receive input and output with ALLOW INSECURE parameter

### ISSUE THREAD

**Issue by AMiR-SPB** [2dust/v2rayNG#2384]
Hi dear friend
When we set the Allow InSecure option to true in the program, when we get the output, there is no parameter to turn on this feature in the destination client.

Actually, if we use SNI Random in the tunneling method or otherwise, this option must be turned on again manually in the destination client program.

Please add the feature of reading the input of this parameter and also setting the status of this parameter on or off when we export the config link.
This problem exists in both V2RayN and V2RayNG programs.

I hope you understand what I mean.

thank you

parameter like this in link : &allowinsecure=true& OR &allowinsecure=false&

**Comment by hadi-norouzi** [comment]
You can enable or disable this after you import your config in edit.
It could be a security issue if someone share a link with allowinsecure set to true.

**Comment by AMiR-SPB** [comment]
> security issue

WHAT security issue ?
