### ISSUE TITLE
new xray core version

### ISSUE THREAD

**Issue by TKZ700** [2dust/v2rayNG#2385]
hello,please add the new xray core version(1.8.3),
proxy chain and ssh support

**Comment by galaxyskyknight** [comment]
ask the same thing, looks like the auther is now on vacation?:)

**Comment by Saeid008** [comment]
@2dust any news about add new xray core version 1.8.3?

**Comment by SaeedDev94** [comment]
**For you guys that looking for xray 1.8.3**  
Feel free to test my client:  
[**Saeed-Pooyanfar/Xray**](https://github.com/Saeed-Pooyanfar/Xray)  
It's a minimal client for xray (android / arm64)
