### ISSUE TITLE
使用tcp即http启动正常但无数据传输

### ISSUE THREAD

**Issue by Messerschmitt110** [2dust/v2rayNG#239]
服务器端没有问题

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
--------- beginning of system
--------- beginning of main
02-14 17:56:24.184 I/GoLog   (25849): loading v2ray config
02-14 17:56:25.266 I/GoLog   (25849): file exists
02-14 17:56:25.266 I/GoLog   (25849): new v2ray core
02-14 17:56:25.294 I/GoLog   (25849): start v2ray core
02-14 17:56:25.298 I/GoLog   (25849): 2019/02/14 09:56:25 [Warning] v2ray.com/core: V2Ray 4.11 started
02-14 17:56:25.298 I/GoLog   (25849): run vpn apps
02-14 17:56:25.387 I/GoLog   (25849): unforgivenessCloser() <-v.unforgivnesschan
02-14 17:56:25.387 I/GoLog   (25849): /data/user/0/com.v2ray.ang/tun2socks
02-14 17:56:25.387 I/GoLog   (25849): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 39 --tunmtu 1500 --sock-path /dev/null --loglevel 1 --enable-udprelay]
02-14 17:56:25.422 I/GoLog   (25849): EscortRun Waiting....
02-14 17:56:26.426 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41701 accepted tcp:172.217.24.10:443 
02-14 17:56:26.426 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41703 accepted tcp:172.217.27.138:443 
02-14 17:56:26.426 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41704 accepted tcp:172.217.24.10:443 
02-14 17:56:26.426 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41702 accepted tcp:172.217.160.74:443 
02-14 17:56:26.431 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41705 accepted tcp:172.217.160.106:443 
02-14 17:56:26.432 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41706 accepted tcp:172.217.160.74:443 
02-14 17:56:26.449 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41707 accepted tcp:216.58.197.106:443 
02-14 17:56:26.449 I/GoLog   (25849): 2019/02/14 09:56:26 tcp:127.0.0.1:41708 accepted tcp:172.217.24.10:443 
02-14 17:57:22.624 I/GoLog   (25849): 2019/02/14 09:57:22 tcp:127.0.0.1:41710 accepted tcp:173.252.110.21:443 
02-14 17:57:26.481 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41712 accepted tcp:172.217.27.138:443 
02-14 17:57:26.516 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41717 accepted tcp:172.217.24.10:443 
02-14 17:57:26.516 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41718 accepted tcp:172.217.27.138:443 
02-14 17:57:26.516 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41719 accepted tcp:172.217.27.138:443 
02-14 17:57:26.516 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41720 accepted tcp:172.217.27.138:443 
02-14 17:57:26.524 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41722 accepted tcp:172.217.27.138:443 
02-14 17:57:26.565 I/GoLog   (25849): 2019/02/14 09:57:26 tcp:127.0.0.1:41724 accepted tcp:172.217.163.234:443 
02-14 17:58:18.606 I/GoLog   (25849): Not Using Prepared: TCP, a.a.a.a:80
02-14 17:58:18.607 I/GoLog   (25849): Not Using Prepared: TCP, a.a.a.a:80
02-14 17:58:18.810 I/GoLog   (25849): Not Using Prepared: TCP, a.a.a.a:80
02-14 17:58:18.812 I/GoLog   (25849): Not Using Prepared: TCP, a.a.a.a:80
02-14 17:58:18.813 I/GoLog   (25849): Not Using Prepared: TCP, a.a.a.a:80
02-14 17:58:18.815 I/GoLog   (25849): Not Using Prepared: TCP, a.a.a.a:80
02-14 17:58:18.815 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.816 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.816 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.816 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.821 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.823 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.833 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:18.835 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:58:23.649 I/GoLog   (25849): Not Using Prepared: TCP, …:80
02-14 17:59:03.324 I/GoLog   (25849): 2019/02/14 09:59:03 tcp:127.0.0.1:41742 accepted tcp:173.252.110.21:443 

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.18
