### ISSUE TITLE
用过ss节点后不能切换vmess节点

### ISSUE THREAD

**Issue by llllllllqq** [2dust/v2rayNG#239]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
任意切换节点

### 实际行为
使用ss节点后，再切换到vmess节点无法连接，而仅有ss节点能用，强行停止app才能正常用vmess

### 复现方法
1.链接一个正常的ss节点
2.切换vmess节点

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
见附件
[log.log](https://github.com/2dust/v2rayNG/files/4075754/log.log)

```

### 环境信息
miui11 安卓9

### 额外信息（可选）
如果链接了ss节点后，进行一次真链接测速，再用vmess就好了。
怀疑是没有完全停止v2内核

**Comment by cswhatsgit** [comment]
我好像也有类似问题。一般习惯挂在延迟低的ss节点上，但是关键时期ss集体挂了，进app测真延迟，挑一个300ms一下的vmess节点切过去，结果完全上不了Google主页等…
