### ISSUE TITLE
Export to clipboard feature does not preserve case sensitivity

### ISSUE THREAD

**Issue by techieforfun** [2dust/v2rayNG#2397]
There is an issue with exporting to the clipboard. It fails to preserve the case sensitivity of `PublicKey`, resulting in all characters being converted to lowercase. This leads to the configuration being non-functional on the target device.

**Comment by minimayki6232** [comment]
> There is an issue with exporting to the clipboard. It fails to preserve the case sensitivity of `PublicKey`, resulting in all characters being converted to lowercase. This leads to the configuration being non-functional on the target device.

**Comment by Abolfazl1335** [comment]
dmxlc3M6Ly9hNWZmYjNjOC0xZWU3LTRlMTgtODdhZS0yYWUwZWRhZDI5MTBAdGVsZWdyYW0tdnBuaHR0cGluamVjdG9yZnJlZS0xLTEucGFnZXMuZGV2OjQ0Mz9lbmNyeXB0aW9uPW5vbmUmc2VjdXJpdHk9dGxzJnNuaT10ZWxlZ3JhbS12cG5odHRwaW5qZWN0b3JmcmVlLTEtMS5wYWdlcy5kZXYmZnA9cmFuZG9taXplZCZ0eXBlPXdzJmhvc3Q9dGVsZWdyYW0tdnBuaHR0cGluamVjdG9yZnJlZS0xLTEucGFnZXMuZGV2JnBhdGg9JTJGJTNGZWQlM0QyNTYwIyVGMCU5RiU4NyVBOSVGMCU5RiU4NyVBQSUyQkdlcm1hbnklMkIlMjglMkIxJTJCJTI5JTJCJUYwJTlGJTlBJTgwJUUyJTk5JUE1JUVGJUI4JThGLWNsb25lDQo=
