### ISSUE TITLE
建议增加查看路由日志功能

### ISSUE THREAD

**Issue by the-eric-kwok** [2dust/v2rayNG#24]
建议像iOS端的Kitsunemi那样提供查看路由日志，并且可以直接从日志里添加路由规则，还有根据user-agent来路由的功能，Kitsunemi的这个功能很方便，所以稍稍提个需求。
最后，还是感谢开发者给自由上网做出的贡献，谢谢你。

**Comment by 2dust** [comment]
没有用过此app
我会根据自己的想法增加简单的路由设置功能

**Comment by erickwoc** [comment]
嗯……就是从日志里可以直接看到某个请求是否有下载流量，如果没有的话会以红色显示，然后点击这条日志可以查看详情，在详情页中可以为这个域名设置路由规则，我感觉这样很方便，希望可以考虑一下。
