### ISSUE TITLE
使用v2rayNG，如何实现GFW中的网址代理，而其他所有网址直连呢？

### ISSUE THREAD

**Issue by xiayang09** [2dust/v2rayNG#2401]
使用v2rayNG，如何实现GFW中的网址代理，而其他所有网址直连呢？
我试了 自定义规则 geosite:gfw, 代理。似乎不生效

**Comment by CharlesLocke** [comment]
自带的geo文件不行，你先更新geo文件，变成Loyalsoldier的路由规则文件加强版就行。
