### ISSUE TITLE
v2rayNG的日志文件在哪里

### ISSUE THREAD

**Issue by xixuekai1314** [2dust/v2rayNG#2405]
只是单纯的问一下日志文件，现有链接ws+tls的，win和mac都正常使用，但是安卓就是有问题，想看一眼日志是那里的，谢谢

**Comment by GreatMichaelLee** [comment]
左上角，logcat....

**Comment by xixuekai1314** [comment]
> 左上角，logcat....

好的，谢谢

**Comment by tianlongJ** [comment]
> 左上角，logcat....

logcat里没有东西啊，我用的默认info级别的日志
