### ISSUE TITLE
更新订阅失败+io：read/write on closed pipe

### ISSUE THREAD

**Issue by yewuqi** [2dust/v2rayNG#2407]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
成功更新订阅

### 实际行为
某一天起突然无法使用已配置好的vpn，同时更新订阅时发现失败，由于当时使用的是huawei手机自动更新至鸿蒙3.0版本，刷机回退至2.0版本后发现仍不可使用，更新最新版本v2rayG无用，导入别的手机可使用的配置显示io：read/write on closed pipe，同时尝试使用其他vpn 如clash for Android也无法成功

### 复现方法
未知

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Mengjinni** [comment]
我也出现了这样的问题，不知道怎么解决

**Comment by rock-op** [comment]
me too, mac和ipad没问题

**Comment by sunyongke** [comment]
me to

**Comment by MonkeyZ999** [comment]
各位解决了吗？我的也是
