### ISSUE TITLE
建议于设置中添加“流量探测”开关

### ISSUE THREAD

**Issue by Z4HD** [2dust/v2rayNG#242]
### 预期行为

- 2dust/v2rayN#232
- 2dust/v2rayN#152

### 实际行为

什么都没有发生

### 复现方法

无

### 日志信息

无

### 环境信息

- V2RayNG 0.6.11
- Moto X Style （Android 7.1.2）

**Comment by tefiszx** [comment]
流量探测是干什么用的？beat版已经支持这个功能了。

**Comment by Z4HD** [comment]
@tefiszx 建议查阅V2Ray 文档 [SniffingObject](https://v2ray.com/chapter_02/01_overview.html#sniffingobject)

**Comment by Z4HD** [comment]
版本 `0.6.16` 中已经添加了该开关，目测该开关运作正常。
