### ISSUE TITLE
v2rayng的aar依赖编译需要自取

### ISSUE THREAD

**Issue by Mronezc** [2dust/v2rayNG#2430]
这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取
https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1

**Comment by ghost** [comment]
我直接用的是你这个aar文件
真机错误日志显示fdConn unix.Connect err,Close Fd:57 Err:permission denied
没有运行权限

**Comment by Mronezc** [comment]
> 我直接用的是你这个aar文件 真机错误日志显示fdConn unix.Connect err,Close Fd:57 Err:permission returned 没有运行权限

那就不清楚了，你试试模拟器，模拟器9/10，真机11和13系统都没问题

**Comment by ghost** [comment]
> > 我直接用的是你这个aar文件 真机错误日志显示fdConn unix.Connect err,Close Fd:57 Err:permission returned 没有运行权限
> 
> 那就不清楚了，你试试模拟器，模拟器9/10，真机11和13系统都没问题

我解决了 将这行代码
https://github.com/2dust/AndroidLibXrayLite/blob/607b5526a7c7978b83cd85d60d30e42050be85e5/libv2ray_support.go#L292
修改为 copy(sa.Addr[:], ip.To16()) 
然后重新编译新的aar文件即可

**Comment by tristesky** [comment]
> 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1

能解决这个编译错误吗？
![go](https://github.com/2dust/v2rayNG/assets/52591934/91372fad-c662-4a22-974a-a4b8adff59ec)

**Comment by Mronezc** [comment]
> > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> 
> 能解决这个编译错误吗？ ![go](https://user-images.githubusercontent.com/52591934/260221695-91372fad-c662-4a22-974a-a4b8adff59ec.png)

请你确保在lib/libs存放了aar并在gradle正确引入，就不会出现这些问题了

**Comment by tristesky** [comment]
> > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > 
> > 
> > 能解决这个编译错误吗？ ![go](https://user-images.githubusercontent.com/52591934/260221695-91372fad-c662-4a22-974a-a4b8adff59ec.png)
> 
> 请你确保在lib/libs存放了aar并在gradle正确引入，就不会出现这些问题了

我刚刚试了，用你的aar放到libs，编译成功了。内核是1.8.1的，请教一下，想编译最新的1.8.3内核，那个aar文件是怎样编译的？谢谢🙏

**Comment by zjh-db** [comment]
请问我只需要连接的功能，怎么才能让编译出来的aar更小呢？现在编译出来，去掉x86的都有20M

**Comment by zjh-db** [comment]
> 请问我只需要连接的功能，怎么才能让编译出来的aar更小呢？现在编译出来，去掉x86的都有20M

而且已经使用了-ldflags="-w -s"

**Comment by Mronezc** [comment]
> > 请问我只需要连接的功能，怎么才能让编译出来的aar更小呢？现在编译出来，去掉x86的都有20M
> 
> 而且已经使用了-ldflags="-w -s"
这个我也不怎么清楚☺️

**Comment by MrMercedes** [comment]
不太了解go语言，有没有同学能帮忙打包一下最新的aar，谢谢啦

**Comment by qwesdfok** [comment]
赞。还找到一个，不过我看是一年前编译的了，也记录下。
https://github.com/2dust/v2rayNG/blob/09d854dc784365e5499e444aff065055adcc5105/V2rayNG/app/libs/libv2ray.aar

**Comment by kaitoKing** [comment]
> 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1

大佬，请问可以请教下怎么编译出来的嘛？

**Comment by Mronezc** [comment]
> > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> 
> 大佬，请问可以请教下怎么编译出来的嘛？

配置go和gomobile编译即可

**Comment by kaitoKing** [comment]
在安装gomobile的时候出问题，想问下大佬方不方便再发一个v1.8.3版本的核心，万分感谢！

**Comment by kaitoKing** [comment]
> > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > 
> > 
> > 大佬，请问可以请教下怎么编译出来的嘛？
> 
> 配置go和gomobile编译即可
在配置gomobile的时候出现了binary is out of date，re-install it的问题（重新安装和重新配置也还是这个问题），想问下大佬方不方便再发一个v1.8.3的版本，万分感谢！

**Comment by Mronezc** [comment]
> > > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > > 
> > > 
> > > 大佬，请问可以请教下怎么编译出来的嘛？
> > 
> > 
> > 配置go和gomobile编译即可
> > 在配置gomobile的时候出现了binary is out of date，re-install it的问题（重新安装和重新配置也还是这个问题），想问下大佬方不方便再发一个v1.8.3的版本，万分感谢！

xray是1.8.4了索性直接编译1.8.4了自己去发布页拿吧，编译过程有点小问题不知道能不能用自己去测试吧

**Comment by kaitoKing** [comment]
> > > > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > > > 
> > > > 
> > > > 大佬，请问可以请教下怎么编译出来的嘛？
> > > 
> > > 
> > > 配置go和gomobile编译即可
> > > 在配置gomobile的时候出现了binary is out of date，re-install it的问题（重新安装和重新配置也还是这个问题），想问下大佬方不方便再发一个v1.8.3的版本，万分感谢！
> 
> xray是1.8.4了索性直接编译1.8.4了自己去发布页拿吧，编译过程有点小问题不知道能不能用自己去测试吧

万分感谢！

**Comment by kaitoKing** [comment]
> > > > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > > > 
> > > > 
> > > > 大佬，请问可以请教下怎么编译出来的嘛？
> > > 
> > > 
> > > 配置go和gomobile编译即可
> > > 在配置gomobile的时候出现了binary is out of date，re-install it的问题（重新安装和重新配置也还是这个问题），想问下大佬方不方便再发一个v1.8.3的版本，万分感谢！
> 
> xray是1.8.4了索性直接编译1.8.4了自己去发布页拿吧，编译过程有点小问题不知道能不能用自己去测试吧

![90bf27f3c1bd37d9df7b1b438af8e40](https://github.com/2dust/v2rayNG/assets/124793143/2325a0b8-1d29-44bd-8cb6-2dc59138e999)
da   大佬，可以再请教下编译问题吗？我自己再继续尝试编译的时候出现  “gomobile: go build -y -ldflags -s -w -buildmode=c-shared -0=/tmp/gomobile-work-1399508986/android/src/main/jniLibs/arm64-V8a/libgojni.so./gobind failed:exitstatus 1”这个问题，不知道大佬有没有遇到这个问题，然后百度说也可能是JDK、SDK、GO、gomobile的版本问题，想先请问下您使用的的androidSDK版本号、JDK版本号、go、gomobile的版本号（排除版本号的问题）。

**Comment by Mronezc** [comment]
> > > > > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > > > > 
> > > > > 
> > > > > 大佬，请问可以请教下怎么编译出来的嘛？
> > > > 
> > > > 
> > > > 配置go和gomobile编译即可
> > > > 在配置gomobile的时候出现了binary is out of date，re-install it的问题（重新安装和重新配置也还是这个问题），想问下大佬方不方便再发一个v1.8.3的版本，万分感谢！
> > 
> > 
> > xray是1.8.4了索性直接编译1.8.4了自己去发布页拿吧，编译过程有点小问题不知道能不能用自己去测试吧
> 
> ![90bf27f3c1bd37d9df7b1b438af8e40](https://user-images.githubusercontent.com/124793143/282411540-2325a0b8-1d29-44bd-8cb6-2dc59138e999.png) da 大佬，可以再请教下编译问题吗？我自己再继续尝试编译的时候出现 “gomobile: go build -y -ldflags -s -w -buildmode=c-shared -0=/tmp/gomobile-work-1399508986/android/src/main/jniLibs/arm64-V8a/libgojni.so./gobind failed:exitstatus 1”这个问题，不知道大佬有没有遇到这个问题，然后百度说也可能是JDK、SDK、GO、gomobile的版本问题，想先请问下您使用的的androidSDK版本号、JDK版本号、go、gomobile的版本号（排除版本号的问题）。

jdk1.8 sdk忘了 go是官网新版 gomobile是xray核心下go.mod自动下载的，我早上也遇到这种报错清理go临时编译目录缓存就好了，自行搜索

**Comment by kaitoKing** [comment]
感谢大佬！

**Comment by kaitoKing** [comment]
> > > > > > > 这两天找了一些资料很少有对aar有相关编译教程，自己试了一下按照那几条命令就好了，把aar塞进libs就好了新手尝试自取 https://github.com/Mronezc/V2rayNG_Android.aar/releases/tag/v1.8.1
> > > > > > 
> > > > > > 
> > > > > > 大佬，请问可以请教下怎么编译出来的嘛？
> > > > > 
> > > > > 
> > > > > 配置go和gomobile编译即可
> > > > > 在配置gomobile的时候出现了binary is out of date，re-install it的问题（重新安装和重新配置也还是这个问题），想问下大佬方不方便再发一个v1.8.3的版本，万分感谢！
> > > 
> > > 
> > > xray是1.8.4了索性直接编译1.8.4了自己去发布页拿吧，编译过程有点小问题不知道能不能用自己去测试吧
> > 
> > 
> > ![90bf27f3c1bd37d9df7b1b438af8e40](https://user-images.githubusercontent.com/124793143/282411540-2325a0b8-1d29-44bd-8cb6-2dc59138e999.png) da 大佬，可以再请教下编译问题吗？我自己再继续尝试编译的时候出现 “gomobile: go build -y -ldflags -s -w -buildmode=c-shared -0=/tmp/gomobile-work-1399508986/android/src/main/jniLibs/arm64-V8a/libgojni.so./gobind failed:exitstatus 1”这个问题，不知道大佬有没有遇到这个问题，然后百度说也可能是JDK、SDK、GO、gomobile的版本问题，想先请问下您使用的的androidSDK版本号、JDK版本号、go、gomobile的版本号（排除版本号的问题）。
> 
> jdk1.8 sdk忘了 go是官网新版 gomobile是xray核心下go.mod自动下载的，我早上也遇到这种报错清理go临时编译目录缓存就好了，自行搜索
我在进行了清理之后，最后编译依然是这个错误，听您的意思是不需要自己安装gomobile是嘛？我自己安装的gomobile之后，输入gomobile version是返回‘binary is out of date,re-install it’的问题。是不是我gomobile的版本问题

**Comment by omid-official** [comment]
# Download from my github [download link](https://github.com/omid-the-great/AndroidLibXrayLite/releases/tag/main)
- Download libv2ray.aar and libv2ray-sources.jar and place them in /libs
- Rebuild the project
- :)

**Comment by krisna112** [comment]
> # Download from my github [download link](https://github.com/omid-the-great/AndroidLibXrayLite/releases/tag/main)
> 
>     * Download libv2ray.aar and libv2ray-sources.jar and place them in /libs
> 
>     * Rebuild the project
> 
>     * :)

can you update release to version xray core1.8.7 please. yhank you for your help

**Comment by omid-official** [comment]
> > # Download from my github [download link](https://github.com/omid-the-great/AndroidLibXrayLite/releases/tag/main)
> > ```
> > * Download libv2ray.aar and libv2ray-sources.jar and place them in /libs
> > 
> > * Rebuild the project
> > 
> > * :)
> > ```
> 
> can you update release to version xray core1.8.7 please. yhank you for your help

OK. I will update it
EDIT: The new version released bro
