### ISSUE TITLE
Possible bug in v2rayNG or Android version of xray-core v1.8.3

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#2432]
Dear @2dust and @yuhan6665 

After implementation of TLS fragmentation, it is possible to surf the DNS/SNI blocked websites without having a server. Therefore, we can use serverless configs to open YouTube.
These configs work flawlessly on PC using v2rayN v6.27 with xray-core v1.8.3.
Although official v2rayNG hasn't been updated to xray-core v1.8.3 yet, however, there are unofficial distributions like [MahsaNG](https://github.com/GFW-knocker/MahsaNG) and [v2rayNG (DEV)](https://github.com/us254/v2rayNG) that provide the xray-core v1.8.3.
The problem is on both of these clients serverless config disconnects  in a short time (like 15 seconds).
There is temporary solution to this which is connecting to a normal config (with server) at first and then connecting to serverless config after disconneting from the normal config (with server). With this trick I was able to surf on the internet almost for half an hour.

I just wanted to inform you about these incedent before updating official v2rayNG client to xray-core v1.8.3.
The serverless config is provided in the next comment.

**Comment by alidxdydz** [comment]
An example of Serverless config:

`
{
  "dns": {
    "hosts": {
      "dns.cloudflare.com": [
        "104.16.132.229",
        "104.16.133.229",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "cloudflare-dns.com": [
        "104.16.248.249",
        "104.16.249.249",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "domain:youtube.com": [
        "google.com"
      ],
      "domain:youtu.be": [
        "google.com"
      ]
    },
    "servers": [
      "https://dns.cloudflare.com/dns-query",
      "https://cloudflare-dns.com/dns-query"
    ],
    "tag": "dns-in"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "debug"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "fragment",
      "domainStrategy": "UseIP",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "fragment": {
          "packets": "tlshello",
          "length": "100-200",
          "interval": "10-20"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpNoDelay": true,
          "domainStrategy": "UseIP"
        }
      }
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  },
  "stats": {}
}
`

**Comment by alidxdydz** [comment]
An example of Serverless config:

```
{
  "dns": {
    "hosts": {
      "dns.cloudflare.com": [
        "104.16.132.229",
        "104.16.133.229",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "cloudflare-dns.com": [
        "104.16.248.249",
        "104.16.249.249",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "domain:youtube.com": [
        "google.com"
      ],
      "domain:youtu.be": [
        "google.com"
      ]
    },
    "servers": [
      "https://dns.cloudflare.com/dns-query",
      "https://cloudflare-dns.com/dns-query"
    ],
    "tag": "dns-in"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "debug"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "fragment",
      "domainStrategy": "UseIP",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "fragment": {
          "packets": "tlshello",
          "length": "100-200",
          "interval": "10-20"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpNoDelay": true,
          "domainStrategy": "UseIP"
        }
      }
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  },
  "stats": {}
}
```

**Comment by ghost** [comment]
An example of Serverless config:

```
{
  "log": {
    "loglevel": "debug"
  },
  "dns": {
    "hosts": {
      "dns.cloudflare.com": [
        "104.16.132.229",
        "104.16.133.229",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "cloudflare-dns.com": [
        "104.16.248.249",
        "104.16.249.249",
        "1.1.1.1",
        "1.0.0.1"
      ],
      "domain:youtube.com": [
        "google.com"
      ],
      "domain:youtu.be": [
        "google.com"
      ]
    },
    "servers": [
      "https://dns.cloudflare.com/dns-query",
      "https://cloudflare-dns.com/dns-query"
    ],
    "tag": "dns_in"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "domainOverride": [
        "http",
        "tls"
      ],
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks-in"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http-in"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "fragment",
      "domainStrategy": "UseIP",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "fragment": {
          "packets": "tlshello",
          "length": "100-200",
          "interval": "10-20"
        }
      },
      "streamSettings": {
        "sockopt": {
          "tcpNoDelay": true,
          "domainStrategy": "UseIP"
        }
      }
    },
    {
      "tag": "dns-out",
      "protocol": "dns"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "socks-in",
          "http-in"
        ],
        "outboundTag": "fragment",
        "enabled": true
      }
    ],
    "strategy": "rules"
  }
}
```

**Comment by ghost** [comment]
I just tested another unofficial v2rayNG client and I can confirm that this problem also happens on this client.
[v2rayNG by yuhan6665](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.8.5.main.dca57aa.apk)

**Comment by ghost** [comment]
@2dust @yuhan6665 

Just tested the last pre-released version and it has the same bug.
In order to run to the disconnection bug, just force stop the v2rayNG client.
Then, just after opening the client, you should first connect to Serverless json config json.
It will disconnect automatically after 15 seconds.
