### ISSUE TITLE
使用 2.单独安装Reality（无需域名）（注意：使用Reality协议，v2rayN客户端版本需要6.21或以上）安卓v2rayNG1.8.5连不上

### ISSUE THREAD

**Issue by zorn-zhao** [2dust/v2rayNG#2440]
通过该链接部署Reality服务 
https://github.com/Alvin9999/new-pac/blob/master/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B.md

Windows端 v2rayN客户端能正常工作，安卓v2rayNG1.8.5不能正常使用，提示TLS超时。是因为安卓v2rayNG1.8.5版本太低吗？

**Comment by gyumyo** [comment]
伪装域名是微软的吗？是的话换一个，微软域名不支持TLS1.3

**Comment by Element-Square** [comment]
我的也是，win完美连接，安卓v2rayNG连接不上（reality）

**Comment by Element-Square** [comment]
v2rayNG把xtls删除我就想不明白了

**Comment by zorn-zhao** [comment]
> v2rayNG把xtls删除我就想不明白了

他是属于二次开发，应该是人家把调整内核了吧

**Comment by namenulll** [comment]
1.89.也连不上

**Comment by Hmilyhyun** [comment]
7月到现在还是没解决

**Comment by 2dust** [comment]
不发配置
不发日志
需要开发者算命解决吗
