### ISSUE TITLE
v2rayNG的quic协议没法使用

### ISSUE THREAD

**Issue by majia1984** [2dust/v2rayNG#2445]
通过v2rayN生成的xray里面的quic生成二维码，在v2rayNG里面没法使用。单独配置也无法使用。设置里面修改成代理模式可以测试通。但调整成vpn模式，就报tls timeout 错误。望尽快修复

**Comment by majia1984** [comment]
net/http: TLS handshake timeout也是这个错误

**Comment by chika0801** [comment]
建议不要用Xray core里面的QUIC传输方式，主要是不快。你要用QUIC有 hysteria tuic juicity 等，你学一下sing-box这平台，什么协议都能开 这是一个配置示例集合 https://github.com/chika0801/sing-box-examples
