### ISSUE TITLE
trojan reality bug

### ISSUE THREAD

**Issue by moh3nat** [2dust/v2rayNG#2448]
hello
When we import **#Reality Trojan** configurations، the app will not enter the short id public key
And you have to enter it manually. 
This is a very bad problem because reality Trojan It's growing and very efficient.
v2rayn doesn't have this problem and reads config easily
tnx for your awesome app

**Comment by RangerRU** [comment]
confirm!

NecoBox has no problems

**Comment by moh3nat** [comment]
> 

yes
but
nekobox have header problem 😐

**Comment by RangerRU** [comment]
Streisand has no problems
