### ISSUE TITLE
Android 13 VPN Starting Problem

### ISSUE THREAD

**Issue by Lynn3t** [2dust/v2rayNG#2452]
Cannot start v2ray server(crash)
Clash For Android can start successfully
If change into proxy mode, start successfully.
Sorry for not providing logs, I'm travelling outside.

**Comment by Lynn3t** [comment]
EDIT : AFTER RESET NETWORK SETTING, CLASH IS NOT ABLE TO USE.
V2RAYNG : CRASHING
CLASH : 无法启动VPN组件

**Comment by Jimiyara** [comment]
All i need is a vpn

**Comment by 0410811986** [comment]
وقتی وارد vpnمیشم دکمه سبز واسه شروع وجود نداره

**Comment by 0410811986** [comment]
لینک جدید لطفا

**Comment by Lynn3t** [comment]
I recovered my phone. Thanks guys
