### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by Ai6fei** [2dust/v2rayNG#2461]
com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
08-11 08:25:27.754 W/System.err(11811): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
08-11 08:25:27.754 W/System.err(11811): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
08-11 08:25:27.754 W/System.err(11811): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
08-11 08:25:27.754 W/System.err(11811): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
08-11 08:25:27.754 W/System.err(11811): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)

**Comment by webnet918** [comment]
我也遇到了这样的问题，已经挺长时间了，同样的订阅地址在PC端是正常的

**Comment by MonkeyZ999** [comment]
同样问题+1

**Comment by MonkeyZ999** [comment]
> 我也遇到了这样的问题，已经挺长时间了，同样的订阅地址在PC端是正常的

你的问题处理好了吗？

**Comment by lidapao** [comment]
订阅地址不能 301 或 302重定向 可以用 curl命令试一下，如果能直接返回订阅服务器内容就可以，如果返回的是301或302，就不行
