### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by tristesky** [2dust/v2rayNG#2462]
编译的时候有这个提示：e: file:///Users/williamhoward/Desktop/v2rayNG-1.8.5/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt:26:8 Unresolved reference: go

不知道是什么原因。
![go](https://github.com/2dust/v2rayNG/assets/52591934/f26e60be-f2cf-4144-97b8-a49761e1240d)

**Comment by zjh-db** [comment]
这个需要通过gomobile编译AndroidV2rayLite生成aar，项目中引入aar
