### ISSUE TITLE
服务启动失败

### ISSUE THREAD

**Issue by kingekinge** [2dust/v2rayNG#2467]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息

--------- beginning of crash
08-17 01:53:14.850 E/AndroidRuntime(15659): FATAL EXCEPTION: main
08-17 01:53:14.850 E/AndroidRuntime(15659): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 15659
08-17 01:53:14.850 E/AndroidRuntime(15659): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{dd849d8 u0 com.v2ray.ang/.service.V2RayVpnService}
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2168)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2139)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2404)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.os.Looper.loopOnce(Looper.java:240)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.os.Looper.loop(Looper.java:351)
08-17 01:53:14.850 E/AndroidRuntime(15659): at android.app.ActivityThread.main(ActivityThread.java:8416)
08-17 01:53:14.850 E/AndroidRuntime(15659): at java.lang.reflect.Method.invoke(Native Method)
08-17 01:53:14.850 E/AndroidRuntime(15659): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
08-17 01:53:14.850 E/AndroidRuntime(15659): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
08-17 01:54:38.733 E/AndroidRuntime(17512): FATAL EXCEPTION: main
08-17 01:54:38.733 E/AndroidRuntime(17512): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 17512
08-17 01:54:38.733 E/AndroidRuntime(17512): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3fab6b2 u0 com.v2ray.ang/.service.V2RayVpnService}
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2168)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2139)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2404)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.os.Looper.loopOnce(Looper.java:240)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.os.Looper.loop(Looper.java:351)
08-17 01:54:38.733 E/AndroidRuntime(17512): at android.app.ActivityThread.main(ActivityThread.java:8416)
08-17 01:54:38.733 E/AndroidRuntime(17512): at java.lang.reflect.Method.invoke(Native Method)
08-17 01:54:38.733 E/AndroidRuntime(17512): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
08-17 01:54:38.733 E/AndroidRuntime(17512): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
08-18 01:13:37.086 E/AndroidRuntime(22115): FATAL EXCEPTION: main
08-18 01:13:37.086 E/AndroidRuntime(22115): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 22115
08-18 01:13:37.086 E/AndroidRuntime(22115): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{add6504 u0 com.v2ray.ang/.service.V2RayVpnService}
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2168)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2139)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2404)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.os.Handler.dispatchMessage(Handler.java:106)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.os.Looper.loopOnce(Looper.java:240)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.os.Looper.loop(Looper.java:351)
08-18 01:13:37.086 E/AndroidRuntime(22115): at android.app.ActivityThread.main(ActivityThread.java:8416)
08-18 01:13:37.086 E/AndroidRuntime(22115): at java.lang.reflect.Method.invoke(Native Method)
08-18 01:13:37.086 E/AndroidRuntime(22115): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
08-18 01:13:37.086 E/AndroidRuntime(22115): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 环境信息
version  1.8.5

**Comment by yanggqi** [comment]
检查一下配置文件 看看Public key，Short ID 这两个参数是不是完整的
