### ISSUE TITLE
建议增加功能：批量标记或记录失效次数

### ISSUE THREAD

**Issue by sgcell** [2dust/v2rayNG#2469]
部分测试无效的节点，在切换网络或者隔段时间后，再次测试却能连接，所以不宜直接删除无效配置。  
现在我只能通过挨个改别名记录测试失效次数。  
“标记”可以是分组、改名之类的，或者简单地记录失效次数，测试结果“-1ms”替换成失效次数

**Comment by ggjmmshfmsfhkfhmsf** [comment]
I want an excellent filter breaker

**Comment by ggjmmshfmsfhkfhmsf** [comment]
فیلتر شکن عالی میخوام

**Comment by controlledentropy** [comment]
>部分测试无效的节点，在切换网络或者隔段时间后，再次测试却能连接，所以不宜直接删除无效配置。
>现在我只能通过挨个改别名记录测试失效次数。
>“标记”可以是分组、改名之类的，或者简单地记录失效次数，测试结果“-1ms”替换成失效次数
>Some nodes with invalid test results may suddenly become connected after switching networks or waiting for a while, so it is not appropriate to directly delete the invalid configurations. Currently, I can only record the number of failed tests by individually modifying the alias. "Marking" can be done by grouping, renaming, or simply recording the number of failed tests. The test result "-1ms" can be replaced with the number of failed tests. 

这里也是，通过改名来挽留部分高速但断断续续长期可用的结点，使用成本攀升。估计墙里面大多数人都是这样的。现在从软件人机功效上来讲，结点管理的自动化方面高度需求的实用小功能应该加一些

Here too, some nodes with high speed but intermittent long-term availability are retained by renaming, leading to increased usage costs. It is estimated that most people inside the wall are in the same situation. Now, from the perspective of software human-machine effectiveness, there is a high demand for practical small features related to automation of node management.
