### ISSUE TITLE
安卓，已经更新到1.8几版本还是显示成功但是翻不了墙，昨天晚上开始的

### ISSUE THREAD

**Issue by ahri1001** [2dust/v2rayNG#2479]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ahri1001** [comment]
安卓，已经更新到1.8几版本还是显示成功但是翻不了墙，昨天晚上开始的

**Comment by HoeKwan** [comment]
1.8.6的问题，取消了alterid的支持
部分机场会罢工

**Comment by ahri1001** [comment]
请问该如何解决，我的是三星galaxy note20 至今无法使用，还有请问最新的官网地址在哪，可以发给我吗？
&nbsp;


小妮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月22日(星期二) 凌晨0:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [2dust/v2rayNG] 安卓，已经更新到1.8几版本还是显示成功但是翻不了墙，昨天晚上开始的 (Issue #2479)





 
1.8.6的问题，取消了alterid的支持
 部分机场会罢工

**Comment by HoeKwan** [comment]
解决不了 退回去1.8.5
