### ISSUE TITLE
harmonyos4关屏后就无法连接了

### ISSUE THREAD

**Issue by coffilk** [2dust/v2rayNG#2481]
mate40pro系统harmonyos v4.0.0.111
v2rayng v1.8.5
### 预期行为
关屏后正常使用

### 实际行为
开屏后无法连接，即使是direct的目的也无法连接

### 复现方法
1.100%复现，从4.0第二个版本开始就出现这个问题

### 日志信息
<details>
--------- beginning of main
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed
08-22 11:14:37.997 E/tun2socks(12211): ERROR(BDatagram): recv failed

</details>

**Comment by coffilk** [comment]
测试发现锁定v2rayng程序后能正常使用了，之前手机版本并不需要

**Comment by donnyxray** [comment]
How to do it?

**Comment by coffilk** [comment]
> 

手机管家自启动管理里面设置一下允许后台活动

**Comment by Alex051111** [comment]
> > 
> 
> 手机管家自启动管理里面设置一下允许后台活动

非常感谢，已经按您说的解决
我已经被这个问题卡住很久了了。
