### ISSUE TITLE
路由规则似乎不能绕过大陆地址，对应的国内地址打不开

### ISSUE THREAD

**Issue by Cirooo** [2dust/v2rayNG#2491]
### 预期行为
路由设置了 proxy ***** geosite:tld-!cn  
direct **** geosite:cn
并且从app自身下载了默认推荐的路由
分应用代理了浏览器
偏好设置为绕过本地及大陆地址
访问国内地址时，应该能迅速正常打开

### 实际行为
ERR_CONNECTION_CLOSED

### 复现方法
1.app更新推荐路由
2.proxy ***** geosite:tld-!cn              direct **** geosite:cn
3.打开国内地址，如 ip138.com         qq.com

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of main
08-29 11:41:50.509 I/GoLog   ( 3828): Not Using Prepared: tcp,www.qq.com:443
08-29 11:41:50.577 I/GoLog   ( 3828): fdConn unix.Connect err, Close Fd: 101 Err: network is unreachable
```
</details>

### 额外信息（可选）
google可以打开，关掉代理之后，国内地址可以打开。

**Comment by Cirooo** [comment]
原版本：1.8.5 （play store）
刚才卸载了1.8.5，安装了pre-release的1.8.6，能按预期代理了。
不太清楚是不是因为长期从play store更新安装，app里的配置文件有冲突？刚才测试国内地址还是挺快的，从Google搜索结果打开知乎也正常，没有像以前那个是个err页。

**Comment by Cirooo** [comment]
升级安装到1.8.9之后，对国内地址绕开又不好使了。卸载回归1.8.6之后正常。

**Comment by Cirooo** [comment]
会不会是这个的问题？
6a255cdfa48b93fe0ced0c7ad80e0922d6ece474

**Comment by Cirooo** [comment]
1.8.12 再次出现了这个问题。重开一个issue？

**Comment by GilHogan** [comment]
新版本问题不是没解决吗，为啥关闭

**Comment by Cirooo** [comment]
> 新版本问题不是没解决吗，为啥关闭

后来我发现了，是优先使用ipv6可能会有这个问题，把这个选项去掉就可以。要提交bug的话，可能得针对这个提。
