### ISSUE TITLE
联系不上客服

### ISSUE THREAD

**Issue by Joy48219** [2dust/v2rayNG#2492]
联系不上客服，我需要续费，朋友也想用，但是原来的客服一直不回消息

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by akhzz905** [comment]
你应该联系提供节点的网站，这个软件是通用的

**Comment by GleenJi** [comment]
你应该找给你提供节点的商家，而不是这个v2rayng的项目作者，这个v2rayng软件本身是免费的，里面的节点才是你买别人的或者自己搭建的
