### ISSUE TITLE
Update Sub

### ISSUE THREAD

**Issue by Ghasem1243** [2dust/v2rayNG#2493]
Please add the automatic update of the sub link

**Comment by StayAway32** [comment]
+1

**Comment by dorcat** [comment]
+1

**Comment by farid220** [comment]
+1

**Comment by donnyxray** [comment]
Also auto-load the list when the QR code is scanned. It's very confusing to some people that they scan the QR code and the list still does not appear immediately.

**Comment by StayAway32** [comment]
that requires an auto update first to be implemented and then once QR code is scanned or link is copied an auto update triggers automaticaly
we really need the project contributors to respond to this thread and add this auto sub pull

please man this will help alot
thanks

**Comment by Morghak963** [comment]
+1

**Comment by lolminerxmrig** [comment]
+1
