### ISSUE TITLE
老板又消失了~

### ISSUE THREAD

**Issue by GreatMichaelLee** [2dust/v2rayNG#2498]
老板，更xray 1.8.4啦~

**Comment by chika0801** [comment]
https://github.com/2dust/v2rayNG/issues/2502#issuecomment-1712738646

**Comment by GreatMichaelLee** [comment]
建议开发者把app key发给你和R大佬算了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月10日(周日) 下午3:28
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [2dust/v2rayNG] 老板又消失了~ (Issue #2498)




 
#2502 (comment)
