### ISSUE TITLE
软件开机自启动

### ISSUE THREAD

**Issue by jelly0925** [2dust/v2rayNG#25]
可以添加一下手机启动后软件开机自启动？现在每次重启手机都要手动启动v2ray有些不方便呀。

**Comment by 2dust** [comment]
Using tasker

**Comment by jelly0925** [comment]
哦，谢谢后期有打算增加这个功能？

**Comment by joon612** [comment]
> Using tasker

how to do

**Comment by yuhan6665** [comment]
https://tasker.joaoapps.com/
