### ISSUE TITLE
华为p30 pro 显示已连接 可以上国内网，但是无法上you tube

### ISSUE THREAD

**Issue by RoyalBilly** [2dust/v2rayNG#250]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
华为p30 pro
显示已连接 可以上国内网，但是无法上you tube
### 实际行为
描述实际发生了什么
华为p30 pro
显示已连接 可以上国内网，但是无法上you tube
### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
华为p30 pro
显示已连接 可以上国内网，但是无法上you tube

**Comment by pcdogyu** [comment]
你的DNS可能被污染了，使用全局代理试试看

**Comment by RoyalBilly** [comment]
请问如何在手机端使用全局代理呢？

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=blackfire_cn7&uid=blackfire_cn7%40hotmail.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ablackfire_cn7%40hotmail.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
blackfire_cn7
邮箱：blackfire_cn7@hotmail.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2020年02月05日 11:48，pcdogyu<mailto:notifications@github.com> 写道：
你的DNS可能被污染了，使用全局代理试试看

**Comment by RoyalBilly** [comment]
[cid:d6f7576464b94e1cfe93446dd657cf60]
还是不行哈




<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=blackfire_cn7&uid=blackfire_cn7%40hotmail.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ablackfire_cn7%40hotmail.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
blackfire_cn7
邮箱：blackfire_cn7@hotmail.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2020年02月05日 22:10，陈楠<mailto:blackfire_cn7@hotmail.com> 写道：
请问如何在手机端使用全局代理呢？

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=blackfire_cn7&uid=blackfire_cn7%40hotmail.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ablackfire_cn7%40hotmail.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
blackfire_cn7
邮箱：blackfire_cn7@hotmail.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2020年02月05日 11:48，pcdogyu<mailto:notifications@github.com> 写道：
你的DNS可能被污染了，使用全局代理试试看

**Comment by 93Alliance** [comment]
这个我知道，需要讲华为系统设置为走代理就好了，com.android.settings

**Comment by Bakanbu** [comment]
换个机场
