### ISSUE TITLE
xray-core official release and update to 1.8.4

### ISSUE THREAD

**Issue by hawshemi** [2dust/v2rayNG#2502]
_Hi_

Now that the latest official release for `xray-core` is v1.8.4 (https://github.com/XTLS/Xray-core/releases/tag/v1.8.4), the `v2rayng` program can be updated to support this core safely and updateable via Play Store.

_Thanks_

**Comment by StayAway32** [comment]
+1

**Comment by hawshemi** [comment]
@2dust Where are you? Are you OK?!

**Comment by xmohammad1** [comment]
pls update it <3
@2dust

**Comment by ghost** [comment]
not gonna work for go1.20 and above, which xray-core v1.8.4 requires.

**Comment by StayAway32** [comment]
dear admin are you alright ? do you need any help or is there something we can do ?

**Comment by chika0801** [comment]
![Screenshot_2023-09-10-15-27-56-087_com v2ray ang-edit](https://github.com/2dust/v2rayNG/assets/88967758/da0fdd80-3487-4b40-b9ae-cd25493ba27c)

https://github.com/chika0801/v2rayNG

这里有由xray最新提交编译出的ng，你也可以自己尝试进行编译。

**Comment by StayAway32** [comment]
hi
do you also have auto subscription update that is hanging in pull requests ?
that would be a great option along with 1.8.4

**Comment by donnyxray** [comment]
Happy to (regularly) contribute financially if this helps @2dust or other contributors to continue.

**Comment by hawshemi** [comment]
@2dust Nothing yet?

**Comment by StayAway32** [comment]
i think as it seems the owner is waiting for Xray 1.9 which is the next version to come for some big improvements and bug fixes before he updates the core and that is fine :)
we just have to be patient

**Comment by hawshemi** [comment]
@StayAway32 This is not a hard task. the important part is the release of Play Store which is still at `xray-core 1.8.1`. most people just update the app via play store and not external links.

**Comment by chika0801** [comment]
I learned by some means that the author saw everyone's requests and that the author had some personal things going on. Please be patient.

**Comment by donnyxray** [comment]
> I learned by some means that the author saw everyone's requests and that the author had some personal things going on. Please be patient.

Thanks. Hope the author is doing well.

**Comment by StayAway32** [comment]
@chika0801 good to know that he is fine and busy with day to day basis stuff :)
