### ISSUE TITLE
选择v2rayNG还是v2flyNG?

### ISSUE THREAD

**Issue by Firestar-Reimu** [2dust/v2rayNG#2506]
我在安卓手机上使用v2sx.com提供的VMESS节点，我应该选择v2rayNG还是v2flyNG？两者的内核有不同吗（我在电脑上用的是v2fly/v2ray-core）？我似乎用的是v2ray而不是xray，是否应该选择v2flyNG更好？

**Comment by akhzz905** [comment]
最早的项目是v2ray/v2ray-core，但是后来v2ray的创始人联系不上了，其他人没有完整项目权限，所以就又成立了一个v2fly，用来维护v2ray-core（v2fly/v2ray-core），这俩其实都是v2ray。
v2ray-core因为开源协议的问题，没法合并XTLS，所以就成立了一个Project X维护xray-core。按照Project X官网所说，Xray-core 是 v2ray-core 的超集，含更好的整体性能和 XTLS 等一系列增强，且完全兼容 v2ray-core 的功能及配置。
v2flyNG的内核是v2fly（也就是v2fly/v2ray-core），v2rayNG的内核是xray-core。

**Comment by Firestar-Reimu** [comment]
感谢，所以选择v2rayNG应该是更好的
