### ISSUE TITLE
0.6.13版本是否可在自定义路由添加ipv6地址

### ISSUE THREAD

**Issue by PaPerseller** [2dust/v2rayNG#251]
当客户端有使用ipv6条件时，0.6.13支持ipv6是否意味着支持在自定义路由中添加ipv6的cidr地址并使其可用，如一行`240f:8000::/24,`

**Comment by qgtxqj** [comment]
应该还不可以，这儿还是IPV4

**Comment by 2dust** [comment]
0.6.13支持ipv6服务器地址，
至于路由里面可能要问core作者了

**Comment by boypt** [comment]
因为目前的VpnService未配置ipv6的本地连接地址，因此手机上的ipv6流量不会被发到core。
请留意后续版本的支持情况。
