### ISSUE TITLE
Auto Subscription Update 

### ISSUE THREAD

**Issue by iamtheted** [2dust/v2rayNG#2514]
Hello there!
I hope you're all doing well.

I was wondering if It's possible to add "auto subscription update"? 
I am using this: v2rayng://install-config/?url=SubLink 
But this only adds the subscription link and people have to tap on the update subscription button manually.
It's not that hard for me I can click on update but old people and also those who don't know how to update will face problems.
So I think this feature makes v2rayNG user-friendly. 

Please let me know if you'd consider this. 
Thank you so much

**Comment by iamtheted** [comment]
I saw this few minutes ago https://github.com/2dust/v2rayNG/pull/2471 
But It would be better if the auto subscription update is on by default.

**Comment by hadi-norouzi** [comment]
> Hello there! I hope you're all doing well.
> 
> I was wondering if It's possible to add "auto subscription update"? I am using this: v2rayng://install-config/?url=SubLink But this only adds the subscription link and people have to tap on the update subscription button manually. It's not that hard for me I can click on update but old people and also those who don't know how to update will face problems. So I think this feature makes v2rayNG user-friendly.
> 
> Please let me know if you'd consider this. Thank you so much

I could add a boolean query parameter to deep-link for auto-update.

**Comment by iamtheted** [comment]
> > Hello there! I hope you're all doing well.
> > I was wondering if It's possible to add "auto subscription update"? I am using this: v2rayng://install-config/?url=SubLink But this only adds the subscription link and people have to tap on the update subscription button manually. It's not that hard for me I can click on update but old people and also those who don't know how to update will face problems. So I think this feature makes v2rayNG user-friendly.
> > Please let me know if you'd consider this. Thank you so much
> 
> I could add a boolean query parameter to deep-link for auto-update.

Aww, that would be awesome man! 
Please add that if It's possible for you.
We really appreciate you.

**Comment by donnyxray** [comment]
@hadi-norouzi should people be switching to your fork? Or is @2dust expected to return?

**Comment by sbh96** [comment]
Please add support profile-update-interval subscription response header to read auto update interval from response and enable auto update in subscription group if this header exist
@2dust @hadi-norouzi 
This header future is common in hiddify and v2box and Streisand and other v2ray apps so you most add this option in v2rayng
