### ISSUE TITLE
NG对vless支持好像有问题，求指导

### ISSUE THREAD

**Issue by WilliamSerena** [2dust/v2rayNG#2515]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

同一个IP地址，优选IP
配置vlesss协议，只能访问TG，所有流媒体都打不开
配置vmess协议，全可以打开

神奇的是，电脑V2客户端又可以完美匹配该vless节点，速度很快

怀疑是手机端NG客户端对vless错误

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Maizer** [comment]
我有类似问题，好像存在断流问题

**Comment by SpiralTower** [comment]
VPN DNS 1.1.1.1 改成 tls://dns.google 或 tls://dns.cloudflare
