### ISSUE TITLE
Regarding to PR "Enhance Routing Capabilities"

### ISSUE THREAD

**Issue by Chocolate4U** [2dust/v2rayNG#2517]
# Details

There is 4 commits in this PR which i will explain here in detail:
- https://github.com/Chocolate4U/v2rayNG/commit/d2186a4bff379b2eae484b8ad0cdda8f526f3d1a
Currently, V2rayNG is fixed on "Loyalsoldier" repository for downloading Geo files. Although Loyalsoldier's repository is a very good resource, this will limit users who want to use other Geo assets and they have to download and import them manually and it can prove a challenge for non technical users.
For example Iranian users have to download and import custom Geo files which is very inconvenient (which I  previously explained here [NekoBoxForAndroid#330](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/330)) so in this commit I have added the feature to select Geo assets provider with 3 Predefined providers listed below, and users can simply download selected Geofiles within the app.
`Official`: gets Geo files from [v2fly/geoip](https://github.com/v2fly/geoip) and [domain-list-community](https://github.com/v2fly/domain-list-community) [This is default option]
`Loyalsoldier`: gets Geo files from [Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)
`Chocolate4U/Iran-v2ray-rules`: gets Geo files from [Chocolate4U/Iran-v2ray-rules](https://github.com/Chocolate4U/Iran-v2ray-rules)

- https://github.com/Chocolate4U/v2rayNG/commit/192ea417a3622a51216b63c8a92199fe412ad3aa
Added two Predefined routing rules for Iranian users
`Bypass Iran address then proxy`
`Bypassing LAN and Iran address then proxy`

- https://github.com/Chocolate4U/v2rayNG/commit/43b8eebe8ca6aad8b8f64aeb36065e6c118698e3
Currently the app hard codes `domain:googleapis.cn` and `hosts["domain:googleapis.cn"] = "googleapis.com"` and also `geoip:cn` in all situations, with this commit the app set the rules dynamically based on `Predefined rules` and `Geo Assets Provider` . If user selects `Chocolate4U/Iran-v2ray-rules` or one of the Predefined Iran rules, it will set Iran specific rules otherwise will set China specific rules same as before.
addresses these issues: 
#1865 
#2198 
#2265 

- https://github.com/Chocolate4U/v2rayNG/commit/90518588fc6034fd518a1693f8294837733c3b7a
Currently users must be connected to a proxy in order to download Geo files. This in unnecessary in my opinion and also limit users. if a user has a custom configuration that has a routing rule that is not in the current `geosite` or `geoip` the app will fail to start and there is no way to download respective Geo files. without this limitation, users can configure the app before connecting.
If the URL to download Geo files is blocked, then the user can connect to a proxy and download files. There is no need to enforce this on the user.
addresses this issue: 
#1966

## Side Notes
- Translations other than English and Persian are done using `DeepL` and `Google Translate`, sorry if they're not accurate enough.

**Comment by mmrabbani** [comment]
@Chocolate4U 
So great PR, I hope 2dust accept it as soon as possible and we all  benefit from this. I have 2 other recommendation about routing. If you file it useful, I appreciate you add these.
1. Default domestic DNS is 223.5.5.5 that is based ob china. It would be great that the default value is changed to one of Iranian
 or international DNS IPs, if the user choose "bypass Iran" or "bypass LAN and Iran" option.
2. Adding option to update Geo files periodically (for example every month). This option can be enabled by default or not. I think this option is implemented in V2rayN from 2dust and is enabled by default. Geo files are updated everyday and users forget to update them manually.

**Comment by Chocolate4U** [comment]
> @Chocolate4U So great PR, I hope 2dust accept it as soon as possible and we all benefit from this. I have 2 other recommendation about routing. If you file it useful, I appreciate you add these.
> 
>     1. Default domestic DNS is 223.5.5.5 that is based ob china. It would be great that the default value is changed to one of Iranian
>        or international DNS IPs, if the user choose "bypass Iran" or "bypass LAN and Iran" option.
> 
>     2. Adding option to update Geo files periodically (for example every month). This option can be enabled by default or not. I think this option is implemented in V2rayN from 2dust and is enabled by default. Geo files are updated everyday and users forget to update them manually.

number 1 is resolved with latest commits. Please test again.
about number 2 I'm not sure because this can cause battery usage issues. I might be wrong though, would be happy to know others opinion on this.

**Comment by mmrabbani** [comment]
> > @Chocolate4U So great PR, I hope 2dust accept it as soon as possible and we all benefit from this. I have 2 other recommendation about routing. If you file it useful, I appreciate you add these.
> > ```
> > 1. Default domestic DNS is 223.5.5.5 that is based ob china. It would be great that the default value is changed to one of Iranian
> >    or international DNS IPs, if the user choose "bypass Iran" or "bypass LAN and Iran" option.
> > 
> > 2. Adding option to update Geo files periodically (for example every month). This option can be enabled by default or not. I think this option is implemented in V2rayN from 2dust and is enabled by default. Geo files are updated everyday and users forget to update them manually.
> > ```
> 
> number 1 is resolved with latest commits. Please test again. about number 2 I'm not sure because this can cause battery usage issues. I might be wrong though, would be happy to know others opinion on this.

Thank you for resolving number 1. For number 2, what do you think if the feature would be disabled by default (and user can enable it) or the default value would be every 1 or 2 month so the battery would be affected fewer times?
As you said, other opinions would be beneficial.

**Comment by Chocolate4U** [comment]
> For number 2, what do you think if the feature would be disabled by default (and user can enable it) or the default value would be every 1 or 2 month so the battery would be affected fewer times?

Increasing interval can be effective but not too much, another approach can be fetching remote geo files metadata and compare them with local files in the runtime after connection, if the date difference between files is greater than user defined interval, then we proceed to download files. As this PR may get too complicated, let's first wait for this PR to get merged then we can work on implementing auto update feature.
