### ISSUE TITLE
什么时候出ios版本??如果有需要我可以协助开发

### ISSUE THREAD

**Issue by GitCod-Man** [2dust/v2rayNG#2522]
没有ios端是一个瓶颈,appstore中鱼目混珠，垃圾太多了,希望能尽快出ios版本,可以协助开发

**Comment by bike3097a** [comment]
你先开发个框架出来，看看你的实力先。

**Comment by chengjiuxu** [comment]
大佬，是不是 v2rayng 不支持 SSR 节点啊？

**Comment by iKira** [comment]
iOS有Surge、Stash、Loon、Quantumult X、Shadowrocket

**Comment by ghostwolf90** [comment]
可以將 xray-core 封裝成 .xcframework，就能用iOS開發了
