### ISSUE TITLE
Per-app proxy not working 

### ISSUE THREAD

**Issue by zhenek-kreker** [2dust/v2rayNG#2526]
Hi!

Cannot make per-app proxy setting to work. Neither combination of switches is working. I need selected apps to connect directly, bypassing the VLESS, and all the rest should go through the VLESS.
![IMG_20230923_124238](https://github.com/2dust/v2rayNG/assets/23496249/e5fbdd70-8c40-483c-8013-7df54abee712)

**Comment by Sfever** [comment]
The per-app proxy button should be turn on
