### ISSUE TITLE
手机端1.85版本之后出现启动失败，EOF

### ISSUE THREAD

**Issue by tuzkilau** [2dust/v2rayNG#2537]
电脑端无问题，1.85版本之后手机端ping有速度，但是启动之后，就出现，失败，EOF，网上搜索了很多，都说需要设置自动时间，我手机也是自动时间，不是手动时间，不知道怎么回事，为何1.85版本没有问题，之后得版本都有问题？往开发者解决一下
![QQ截图20230927084938](https://github.com/2dust/v2rayNG/assets/146146787/52a16d97-0074-418d-b428-22e81f616fc9)

**Comment by yqyt2014** [comment]
这是什么问题

**Comment by tuzkilau** [comment]
不知道，最新版本无法使用，只能使用1.8.5

yqyt2014 ***@***.***> 于2023年10月2日周一 14:27写道：

**Comment by emuskycn** [comment]
我这边是只能用1.6的版本，以后的版本都是显示启动服务失败

**Comment by fringestyle** [comment]
I get same question!!!
