### ISSUE TITLE
安卓10连接v2rayNG之后导致手机开放的端口被filtered

### ISSUE THREAD

**Issue by huyz-git** [2dust/v2rayNG#254]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
在设置了“绕过局域网”的分流规则之后，是否开启v2rayNG不应该影响局域网内的互联。

### 实际行为
手机和电脑在同一个局域网内，手机用termux开启sshd，电脑也开，在不开v2rayNG时，手机电脑可以互相ssh连接，但开启v2rayNG时，手机可以ssh到电脑上，但电脑不能ssh到手机上。

### 复现方法
1. 安装termux，并开启sshd
2. 在不开v2rayNG时尝试从局域网ssh到手机termux上
3. 在开启v2rayNG时尝试从局域网ssh到手机termux上

### 日志信息

termux的sshd开在8022端口上，如果在电脑上用`nmap`扫描手机ip的端口，则在不开启v2rayNG时，能扫描到开放的8022端口（`nmap`和`nmap -sT`的结果一样）：
```
Nmap scan report for 192.168.0.101
Host is up (0.0036s latency).
Not shown: 999 closed ports
PORT     STATE SERVICE
8022/tcp open  oa-system
```
但是开启v2rayNG后，电脑上再次用`nmap`扫描手机ip的端口，则扫描到8022端口显示filtered（`nmap`和`nmap -sT`的结果一样）：
```
Nmap scan report for 192.168.0.101
Host is up (0.0042s latency).
Not shown: 999 closed ports
PORT     STATE    SERVICE
8022/tcp filtered oa-system
```
在电脑进行nmap时，`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`没有输出任何东西。

无论是否连接v2rayNG，在手机里`nmap localhost`或`nmap 手机的ip`都显示8022端口open。

### 环境信息
安卓10
fdroid上的最新版termux

**Comment by aeroxy** [comment]
Bypassing the LAN only means bypassing the LAN requests from your client device - the phone. It doesn't mean your phone's ports would be available from other devices. You can try to the "per app vpn" mode and only include apps that need VPN connections.

**Comment by huyz-git** [comment]
更新：
这个问题只有开启ipv6才会出现，不开启ipv6不会出现。
这应该是安卓10的问题：https://issuetracker.google.com/issues/149636790
隔壁shadowsocks-android和ClashForAndroid已经修了。
相关信息：
https://github.com/shadowsocks/shadowsocks-android/issues/2361
https://github.com/shadowsocks/shadowsocks-android/commit/cc840c9fddb3f4f6677005de18f1fcb387b84064#diff-e089fe63dcb3674c0a1e459a95508e3e
https://github.com/Kr328/ClashForAndroid/commit/f626a0fc5c571a98df5d1d21152e4f8be88fee5c

**Comment by beacon007** [comment]
> 更新：
> 这个问题只有开启ipv6才会出现，不开启ipv6不会出现。
> 这应该是安卓10的问题：https://issuetracker.google.com/issues/149636790
> 隔壁shadowsocks-android和ClashForAndroid已经修了。
> 相关信息：
> [shadowsocks/shadowsocks-android#2361](https://github.com/shadowsocks/shadowsocks-android/issues/2361)
> [shadowsocks/shadowsocks-android@cc840c9#diff-e089fe63dcb3674c0a1e459a95508e3e](https://github.com/shadowsocks/shadowsocks-android/commit/cc840c9fddb3f4f6677005de18f1fcb387b84064#diff-e089fe63dcb3674c0a1e459a95508e3e)
> [Kr328/ClashForAndroid@f626a0f](https://github.com/Kr328/ClashForAndroid/commit/f626a0fc5c571a98df5d1d21152e4f8be88fee5c)

兄弟最后解决了吗？一模一样的问题，同android10+termux+sshd

**Comment by yuhan6665** [comment]
I understand the problem. Even if you use Freedom outbound, re-routing traffic (especially UDP) will cause some issues. The best way to do bypassing is to bypass at system vpn service level.
I think this would be a good change that should also fix #170 (casting to TV). I plan to fix this a bit later.

**Comment by yuhan6665** [comment]
Should be fix in #517
