### ISSUE TITLE
使用 AndroidLibV2rayLite 报 TLS handshake timeout  

### ISSUE THREAD

**Issue by geekeren** [2dust/v2rayNG#2542]
官方版使用的xray 吗，我使用 AndroidLibV2rayLite 编译后显示 TLS handshake timeout

**Comment by chika0801** [comment]
使用的是xray  lib你要自己编译，老外的教程 https://github.com/2dust/v2rayNG/discussions/2527

或看我这个 https://github.com/chika0801/v2rayNG

**Comment by wc7086** [comment]
#2406

**Comment by Hamzehhasanzadeh** [comment]
78878737887
