### ISSUE TITLE
华为手机 v2rayng在后台运行，放置一段时间后，通过v2rayng联网的app会无法上网

### ISSUE THREAD

**Issue by nogizaka316** [2dust/v2rayNG#2552]
遇到问题：

在后台运行，放置（期间不点开需要通过v2rayng联网的app，或者手机息屏一段时间）一段时间后，通过v2rayng联网的app会无法上网。
在v2rayng内点击下方测试栏，提示连接成功，有延迟。
使用通过v2rayng联网的浏览器进google.com时提示找不到 dns，无法上网。
其他通过v2rayng联网app也无法上网。
重新点启动按钮才能上网。
复现概率很高

补充：
设备：华为mate30
系统：harmonyos 4.0.0
v2rayng版本：目前试过 1.8.5 和 1.8.9  都出现该问题。
在一次系统（华为harmonyos）更新后出现该问题。
服务端无问题
与协议无关，vless ws ，vless reality，vless grpc 都会出现该问题
v2rayng 设置除了分应用代理更改为仅选中应用联网外其余均为默认设置
格式化手机后仍旧出现该问题。

**Comment by Hylouis233** [comment]
荣耀也是，github和google无法连接，限速1kb/s以下

**Comment by Hylouis233** [comment]
> 荣耀也是，github和google无法连接，限速1kb/s以下

换clash测试了一下，还能用

**Comment by itv3** [comment]
我和你情况差不多，手机是mate 60 pro+,系统是鸿蒙4.0升到了最新版：
1、切换订阅的ss连接时，打开chrome搜索，要过大概8秒钟才会连接上显示搜索结果，连上后再次搜索时就非常快了，锁屏过一会后再次用时也是这样的，首次搜索要等几秒钟，感觉就和断连一样，已经关闭电池优化了
2、切换为vless连接就没有这个问题，能立即连上
3、华为mate 60手机在连通后状态栏不显示vpn图标
但ss订阅连接用clash和其它vpn都没有这个问题

**Comment by GreenTeodoro839** [comment]
一样，等个大佬改一下包名再试，看看是不是针对v2

**Comment by mt25cyb** [comment]
Mate40也一样，我猜应该是华为的后台杀死或暂停了进程，重新打开时要重新连接。
后来我设置了“允许自启动”、“允许后台活动”，“允许关联启动”，电池优化设置为“不允许” ，情况有所好转

**Comment by zazitufu** [comment]
华为手表之类如果有智能语音助手的话，如果手机息屏一段时间（大约15分钟以上），使用手表语音助手的时候会显示无网络未连接（手表是通过蓝牙跟手机链接的）

**Comment by steelheadz** [comment]
华为平板使用v2rayng无法打开网页，用clash就行

**Comment by reganology** [comment]
安卓原生也有这个问题

**Comment by RdHuangIk** [comment]
在设置->应用管理->v2rayNG->耗电详情->启动管理
将自动管理取消，把下方三个选项全部勾选，保存
实测可解决

**Comment by hczz** [comment]
> 在设置->应用管理->v2rayNG->耗电详情->启动管理 将自动管理取消，把下方三个选项全部勾选，保存 实测可解决

实测勾选 “允许后台活动” 就可以

**Comment by yexiaoziSAS** [comment]
学习了，同样遇到这个问题。重启也不行

**Comment by kilvn** [comment]
实测勾选 “允许后台活动” 就可以

> > 在设置->应用管理->v2rayNG->耗电详情->启动管理 将自动管理取消，把下方三个选项全部勾选，保存 实测可解决
> 
> 实测勾选 “允许后台活动” 就可以
