### ISSUE TITLE
当订阅链接包含302跳转时会出现更新订阅失败的问题

### ISSUE THREAD

**Issue by 7980963** [2dust/v2rayNG#2553]
假设订阅链接为http://xx.com/sub，但是我需要更换域名到http://yy.com/sub，于是我就在nginx上给xx.com写了一个302跳转，在V2rayN可以正常获取订阅，但是V2rayNG会提示失败。

**Comment by lidapao** [comment]
终于找到问题了 强啊

**Comment by datout** [comment]
这问题还没解决吗。。。
