### ISSUE TITLE
SSL and Domain problem

### ISSUE THREAD

**Issue by AmirF194** [2dust/v2rayNG#2555]
Hi,

First of all, thank you for creating this great application. I would like to use Cloudflare and SSL with domain for vless, trojan, etc links I create in the x-ray panel.
When I installed the application from Google Play, everything worked, but the problem was that when I built the app from this repo, it did not work. I believe I need to configure the v2ray_config.json. How can I adjust the default one : 

```
{
  "stats":{},
  "log": {
    "loglevel": "warning"
  },
  "policy":{
      "levels": {
        "8": {
          "handshake": 4,
          "connIdle": 300,
          "uplinkOnly": 1,
          "downlinkOnly": 1
        }
      },
      "system": {
        "statsOutboundUplink": true,
        "statsOutboundDownlink": true
      }
  },
  "inbounds": [{
    "tag": "socks",
    "port": 10808,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "userLevel": 8
    },
    "sniffing": {
      "enabled": true,
      "destOverride": [
        "http",
        "tls"
      ]
    }
  },
  {
    "tag": "http",
    "port": 10809,
    "protocol": "http",
    "settings": {
      "userLevel": 8
    }
  }
],
  "outbounds": [{
    "tag": "proxy",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "v2ray.cool",
          "port": 10086,
          "users": [
            {
              "id": "a3482e88-686a-4a58-8126-99c9df64b7bf",
              "alterId": 0,
              "security": "auto",
              "level": 8
            }
          ]
        }
      ],
      "servers": [
        {
        "address": "v2ray.cool",
        "method": "chacha20",
        "ota": false,
        "password": "123456",
        "port": 10086,
        "level": 8
      }
      ]
    },
    "streamSettings": {
      "network": "tcp"
    },
    "mux": {
      "enabled": false
    }
  },
  {
    "protocol": "freedom",
    "settings": {},
    "tag": "direct"
  },
  {
    "protocol": "blackhole",
    "tag": "block",
    "settings": {
      "response": {
        "type": "http"
      }
    }
  }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": []
  },
  "dns": {
      "hosts": {},
      "servers": []
  }
}
```

**Comment by qghavami-max** [comment]
{
  "log": {},
  "inbounds": [
      {
        "listen": "127.0.0.1",
        "port": 58424,
        "tag": "socks",
        "settings": {
          "userLevel": 8,
          "auth": "noauth",
          "udp": true
        },
        "sniffing": {
          "domainsExcluded": [
            "courier.push.apple.com"
          ],
          "destOverride": [
            "tls",
            "http",
            "quic"
          ],
          "enabled": true
        },
        "protocol": "socks"
      },
      {
        "tag": "directSocks",
        "port": 1087,
        "listen": "127.0.0.1",
        "settings": {
          "udp": true,
          "auth": "noauth",
          "userLevel": 8
        },
        "protocol": "socks"
      },
      {
        "tag": "api",
        "port": 58425,
        "listen": "[::1]",
        "settings": {
          "address": "[::1]"
        },
        "protocol": "dokodemo-door"
      }
    ],
  "outbounds": [
      {
        "tag": "proxy",
        "streamSettings": {
          "network": "ws",
          "wsSettings": {
            "headers": {
              "Host": "ar.liarashop.ir"
            },
            "path": "/"
          }
        },
        "settings": {
          "vnext": [
            {
              "address": "snapp.ir",
              "port": 80,
              "users": [
                {
                  "id": "39ef2c70-925b-4efb-8e50-2da9a57b24c9",
                  "level": 8,
                  "flow": "",
                  "email": "",
                  "encryption": "none"
                }
              ]
            }
          ]
        },
        "mux": {
          "xudpProxyUDP443": "allow",
          "enabled": false,
          "xudpConcurrency": 128,
          "concurrency": 50
        },
        "protocol": "vless"
      },
      {
        "tag": "fragment",
        "streamSettings": {
          "sockopt": {
            "tcpNoDelay": true
          }
        },
        "settings": {
          "userLevel": 8,
          "fragment": {
            "length": "80-250",
            "interval": "10-100",
            "packets": "tlshello"
          }
        },
        "protocol": "freedom"
      }
    ],
  "api": {
      "tag": "api",
      "services": [
        "StatsService"
      ]
    },
  "dns": {
      "queryStrategy": "UseIP",
      "servers": [
        {
          "skipFallback": false,
          "address": "8.8.8.8"
        }
      ],
      "disableFallbackIfMatch": true,
      "tag": "dnsQuery",
      "hosts": {
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.cloudflare.com": [
          "104.16.132.229",
          "104.16.133.229",
          "2606:4700::6810:84e5",
          "2606:4700::6810:85e5"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "cloudflare-dns.com": [
          "104.16.248.249",
          "104.16.249.249",
          "2606:4700::6810:f8f9",
          "2606:4700::6810:f9f9"
        ]
      },
      "disableCache": true,
      "disableFallback": true
    },
  "stats": {},
  "routing": {
        "balancers": [],
        "domainStrategy": "AsIs",
        "rules": [
            {
              "outboundTag": "api",
              "inboundTag": [
                "api"
              ],
              "type": "field"
            },
            {
              "outboundTag": "proxy",
              "inboundTag": [
                "dnsQuery"
              ],
              "type": "field"
            },
            {
              "outboundTag": "direct",
              "inboundTag": [
                "directSocks"
              ],
              "type": "field"
            }
          ]
      },
  "policy": {
        "system": {
          "statsInboundDownlink": true,
          "statsInboundUplink": true,
          "statsOutboundUplink": true,
          "statsOutboundDownlink": true
        },
        "levels": {
          "8": {
            "bufferSize": 0,
            "handshake": 4,
            "statsUserDownlink": false,
            "statsUserUplink": false,
            "uplinkOnly": 1,
            "downlinkOnly": 1,
            "connIdle": 30
          }
        }
      },
  "transport": {}
}
