### ISSUE TITLE
手机端新版本出现启动失败，EOF

### ISSUE THREAD

**Issue by tuzkilau** [2dust/v2rayNG#2556]
### 实际行为
新版本手机打开，可以ping通，但是测速出现启动失败，EOF

### 环境信息
安卓手机和安卓模拟器均不行

**Comment by x565749716** [comment]
我之前也遇到过这个问题，是不是你的节点是带alterld的？新版本好像取消了这个功能，带alterld的节点只能用1.8.5以及之前的版本。

**Comment by tuzkilau** [comment]
> 我之前也遇到过这个问题，是不是你的节点是带alterld的？新版本想要取消这个功能，带alterld的节点只能用1.8.5以及之前的版本。

不知道啊，也是租得节点，不知道是不是带alterld的，怎么看是不是带alterld的？

**Comment by caliban511** [comment]
我也遇到了，而且是正常使用一段时间后出现的，需要停止进程然后打开重连，就又好了，，，然后再出现，，，🙈

**Comment by fringestyle** [comment]
I  get  same question！！

**Comment by xsfx0313** [comment]
i get same question too!

**Comment by HiweH** [comment]
我网上搜说是时间设置问题，但是我调整时间后再重启服务，还是会有EOF，手机是可以正常
