### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by abysszero** [2dust/v2rayNG#256]
网络好的，本来用的也挺好，突然无法使用，更新软件后更新订阅失败，订阅链接打开是下载个txt文档，现在一直更新订阅失败，无法使用

**Comment by abysszero** [comment]
同一个订阅链接电脑能用，安卓无法使用

**Comment by jw-star** [comment]
我也是遇到了这个问题，很奇怪，订阅地址电脑可以打开，手机打开失败

**Comment by bannedbook** [comment]
我调试了一下，好像有可能是程序Base64.decode 有缺陷

**Comment by jw-star** [comment]
仔细检查你的订阅内容，重新编码，重试

**Comment by databian** [comment]
同样问题+1，之前的版本用着订阅功能一直正常着，然后突然有一次提示更新失败，然后再也没有更新成功过。订阅连接是我自己做的，在win10客户端，mac，ios上都能正常更新，只有安卓手机上不行。

**Comment by Shea11012** [comment]
同样的问题，安卓更新订阅失败

**Comment by ACG1006** [comment]
我也不行有哪位大佬可以告诉我怎么解决

**Comment by SeanTo** [comment]
同一订阅地址，PC端用V2rayN更新正常，手机上V2rayNG更新无反应。手机浏览器上打开订阅地址，复制内容（不做base64转换）直接在V2rayNG中从剪切板导入，正常，链接可用。

**Comment by SeanTo** [comment]
> 同一订阅地址，PC端用V2rayN更新正常，手机上V2rayNG更新无反应。手机浏览器上打开订阅地址，复制内容（不做base64转换）直接在V2rayNG中从剪切板导入，正常，链接可用。
> V2rayNG是play store更新到最新版：1.2.6(Libv2rayLite, Core V4.23.1)

已解决，是因为我分应用代理排除了V2rayNG

**Comment by cbxbw** [comment]
> 已解决，是因为我分应用代理排除了V2rayNG

我取消打勾分应用代理后,点击更新订阅,还是没有反应?请问怎么回事?

**Comment by SeanTo** [comment]
需要先有一个能翻墙的节点

**Comment by ColderCoder** [comment]
不管是否启用，不管有没有将v2rayng加入分应用代理，都失败。电脑可用，打开订阅地址把base64码复制，从剪切板导入可以，更新订阅失败

**Comment by TDSofTM** [comment]
我也遇到这个情况了，电脑开自动配置可以更新订阅，不开更新不了，手机适中更新失败，比较神奇的是换一家机场就都能成功，目前还没找到原因和解决办法

**Comment by SeanTo** [comment]
> > 已解决，是因为我分应用代理排除了V2rayNG
> 
> 我取消打勾分应用代理后,点击更新订阅,还是没有反应?请问怎么回事?

请重启服务试试

**Comment by XFA-33Fenrir** [comment]
> 我也遇到这个情况了，电脑开自动配置可以更新订阅，不开更新不了，手机适中更新失败，比较神奇的是换一家机场就都能成功，目前还没找到原因和解决办法

是否使用了分应用代理，若使用了需要把V2rayNG也勾上然后重启，否则无法直连的订阅地址就会订阅失败

**Comment by Tenerome** [comment]
找到问题了，放在github里面也是相当于需要挂梯子的，最好放在国内的服务器上，比如gitee，博客园等等，只要能放文件的服务器都行

**Comment by XuJ1E** [comment]
https://xn--4gq62f52gdss.com/#/register?code=aP4aWZTz

**Comment by wufei-png** [comment]
> 需要先有一个能翻墙的节点

我先复制订阅链接对应的文件的内容，从剪贴板导入成功了，然后连上vpn时候再更新订阅就成功了，感谢

**Comment by simplove** [comment]
> > 需要先有一个能翻墙的节点
> 
> 我先复制订阅链接对应的文件的内容，从剪贴板导入成功了，然后连上vpn时候再更新订阅就成功了，感谢

我的订阅url没有被墙，理论上不需要勾选 分应用代理吧

**Comment by ronysun** [comment]
遇到相同问题

**Comment by liulianghe** [comment]
我的手机就要更新正常，电视更新失败怎么办？原来一直用的好好的
