### ISSUE TITLE
自從升級到0.6.12後的版本,三星note 8就完全不能用

### ISSUE THREAD

**Issue by la8896** [2dust/v2rayNG#256]
手動及自定義配置也不能連線
以經導出手動配置再導入也不能連線
但用huawei mate 10可連線
但测試速度也慢了很多

**Comment by thorisme** [comment]
我的是华为mate9，os是emui9.0不能用，延时太厉害了，退回0.64版本可以

**Comment by la8896** [comment]
> 我的是华为mate9，os是emui9.0不能用，延时太厉害了，退回0.64版本可以

0.6.14版本, 三星Note 8可正常使用了
