### ISSUE TITLE
trojan tcp reality import problem

### ISSUE THREAD

**Issue by sharif221** [2dust/v2rayNG#2560]
The problem is about importing `(Trojan+Reality)` in the app. If you import this link, for example:

```markdown
trojan://DeawS2VD1@1.1.1.2:35327?type=tcp&security=reality&sni=www.google.com&pbk=cbjojgGFDCA5Y4V5rF4Y84SBmBpqEP23QkPNgZfVThM&sid=&fp=firefox&spx=%2#testTroj
```

the app dont recognize pbk, sid and spx
even if adding it manually and exporting link and agane importing link still it dont recognize this  3 parameter.

app is 1.8.5 google play store build

**Comment by FranzKafkaYu** [comment]
@sharif221 Trojan + Reality is not support officially in Xray Core,so v2rayNG has no reason to support this,plz use VLESS instead.

**Comment by sharif221** [comment]
@FranzKafkaYu 
Thanks,

Because is x-ui panels we have these options to enable reality on trojan but i see that it doesn't work on client side and also not configured correctly by x-ui panels in xray config file.

Maybe its a bug in x-ui panels and need to be fixed in some Combination of protocols

**Comment by RangerRU** [comment]
> Trojan + Reality is not support officially in Xray Core

but 100% working
