### ISSUE TITLE
安卓端所有节点突然消失

### ISSUE THREAD

**Issue by Candiceegg** [2dust/v2rayNG#2562]
![mmexport1697518324522](https://github.com/2dust/v2rayNG/assets/148183863/5a4a437f-1d3e-4500-bd9d-72e656d43106)
重新下载了再按照教程导入也还是这样，一个节点都没有

**Comment by liangrud** [comment]
我也是。。

**Comment by clsddy** [comment]
更换1.8.5版本，

**Comment by clsddy** [comment]
更换1.8.5版本，

**Comment by liuwawa-ops** [comment]
> 我也是。。

解决了吗老兄
