### ISSUE TITLE
关于dns泄漏问题的请教

### ISSUE THREAD

**Issue by shandongtlb** [2dust/v2rayNG#2564]
![Screenshot_20231019_153423_v2rayNG](https://github.com/2dust/v2rayNG/assets/40312509/1ba91df3-a7e6-4a39-868b-c23e91b69cba)

如图这是v2rayng app的配置，使用surfshark检查发现有国内的dns https://surfshark.com/zh/dns-leak-test
这个应该和服务器配置没关系吧，应该就是客户端的问题。我用win端v2rayn就不存在这种泄露。
另外，当我把app中 ipv6优先 选项关闭之后，就不会复现该问题了
另外，在该配置下访问部分国内网站会禁止访问，同样关闭ipv6优先之后问题解决，求教大佬这是为什么呢？

**Comment by shandongtlb** [comment]
重新开启该问题，实测同样配置下，当前release版本1.8.5不会复现该问题，貌似只有1.8.9会导致dns泄露，解决方法可以用ch大佬的模板手动导入

**Comment by changelzj** [comment]
1.8.5也存在DNS泄露的问题，总是有一个到美国的DNS查询，surfboard就没有这个问题，而且使用chrome安卓版才能发现，firefox for android 无法发现
