### ISSUE TITLE
socks5: udp stun packets goes from device directly to destination

### ISSUE THREAD

**Issue by wauzzz** [2dust/v2rayNG#2565]
I see udp leak when connect socks5 tcp proxy. You can see it for example if go on site (browserleaks dot com) at webrtc leak test and see on here ip address   "26.26.26.1", which defined at file V2Ray
VpnService.kt:
       private const val PRIVATE_VLAN4_CLIENT = "26.26.26.1"

 it would be nice to be able to block any udp

**Comment by ShaperXS** [comment]
Is there a solution to this problem？
