### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by Kamiel0110** [2dust/v2rayNG#2568]
啟動連線後出現Net/http: TLS handshake timeout
無法連線

**Comment by cn-taoye** [comment]
存在同样的问题

**Comment by zzp198** [comment]
关闭本地DNS，代理设置为全局。这样就能正常连接了，速度也会恢复正常。
感觉是DNS出现了问题，我的是vmess+ws+cdn。

**Comment by huanwuhan** [comment]
同样的问题。按楼上同学说的，关闭本地DNS，全局代理后测试能连接，实际可仍然不能上网。
试了1.8.9和1.8.5版本，结果一样。
有大佬知道怎么解决嘛 /抱拳

**Comment by huanwuhan** [comment]
> 存在同样的问题

您好，这个问题您解决了吗？

**Comment by YoloLordGrim** [comment]
V1.8.11也有这问题，有知道怎么解决吗？

**Comment by 582583241** [comment]
我的也是同样问题，设置全局能上网了，但是连接国内软件会非常慢！不知道如何解决？
