### ISSUE TITLE
感觉走国内域名ip有时候速度很慢甚至是断开状态

### ISSUE THREAD

**Issue by GleenJi** [2dust/v2rayNG#2571]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

国内域名ip走国内网络直连速度快，国外域名ip走科学上网vps

### 实际行为
描述实际发生了什么

走国外速度没问题，走国内有时候就存在速度很慢甚至断连的状态，但有时候正常

### 复现方法
![Screenshot_2023-10-24-11-26-39-51](https://github.com/2dust/v2rayNG/assets/56299828/d0f75725-9330-477f-bb49-176d80440e77)
这是我的设置

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by GleenJi** [comment]
我用的1.8.9版本，用nekobox差不多同样的设置好像没啥问题

**Comment by Cirooo** [comment]
> 我用的1.8.9版本，用nekobox差不多同样的设置好像没啥问题

试试看1.8.6，新版我用着也对国内地址不好使

**Comment by George-smith66** [comment]
😁

**Comment by zzp198** [comment]
关闭本地DNS，代理设置为全局。这样就能正常连接了，速度也会恢复正常。
感觉是DNS出现了问题，我的是vmess+ws+cdn。

**Comment by GleenJi** [comment]
> 关闭本地DNS，代理设置为全局。这样就能正常连接了，速度也会恢复正常。 感觉是DNS出现了问题，我的是vmess+ws+cdn。

不是，那样的话应该是全局都走科学上网，如果选择绕过局域网和大陆网址并关闭本地dns，那样的话是所有网址都被默认的vpn dns 1.1.1.1解析，虽然这样没问题，但是国内访问1.1.1.1速度慢，所以国内网址相对来说打开速度比国内网址用国内dns解析慢

**Comment by zzp198** [comment]
> > 关闭本地DNS，代理设置为全局。这样就能正常连接了，速度也会恢复正常。 感觉是DNS出现了问题，我的是vmess+ws+cdn。
> 
> 不是，那样的话应该是全局都走科学上网，如果选择绕过局域网和大陆网址并关闭本地dns，那样的话是所有网址都被默认的vpn dns 1.1.1.1解析，虽然这样没问题，但是国内访问1.1.1.1速度慢，所以国内网址相对来说打开速度比国内网址用国内dns解析慢

我开启本地DNS后直接TLS handshake timeout，全局至少还能连上.

**Comment by suzikuo** [comment]
> > 关闭本地DNS，代理设置为全局。这样就能正常连接了，速度也会恢复正常。 感觉是DNS出现了问题，我的是vmess+ws+cdn。
> 
> 不是，那样的话应该是全局都走科学上网，如果选择绕过局域网和大陆网址并关闭本地dns，那样的话是所有网址都被默认的vpn dns 1.1.1.1解析，虽然这样没问题，但是国内访问1.1.1.1速度慢，所以国内网址相对来说打开速度比国内网址用国内dns解析慢

能提供一个v2rayNG的详细配置嘛？家里的wifi（1000M）下访问油管巨慢，流量巨快
