### ISSUE TITLE
在同一个 wifi 下连接同一个服务器，v2rayNG 比 v2rayN 慢很多

### ISSUE THREAD

**Issue by mengyuntian0** [2dust/v2rayNG#2574]

**Comment by zhangjinhui152** [comment]
试试VPN DNS 换成大佬们说的 dns.google

**Comment by mengyuntian0** [comment]
> 试试VPN DNS 换成大佬们说的 dns.google

试了一下，似乎没啥效果。不过后来我不知道怎么还原原来的 dns 配置，就卸载重装了。然后发现测试时延虽然依然有一千多毫秒，但是实际访问网站却流畅了不少。测试了一下各种配置，似乎是因为开了启用虚拟 DNS 导致的网速慢
