### ISSUE TITLE
auto update and auto server selector

### ISSUE THREAD

**Issue by MrVb0** [2dust/v2rayNG#2581]
Hello, good time, thank you for your good application.
By adding these features below, many users will definitely be happy:

- Ability to automatically update the subscription (time interval / or / every time the program is opened)
Important note: If the update is not successful, try again or a specific error will be displayed.

- The option of automatic server selector based on real delay or ping (URLtest), there is an option that by choosing it, the best one will be automatically selected and connected from among all the subscription servers, and it will be constantly updated.

**Comment by MrVb0** [comment]
https://github.com/2dust/v2rayNG/pull/2471

**Comment by vinhma77** [comment]
Cấu hình lỗi liên tục mạng lien quan mobile quá kém
