### ISSUE TITLE
导入的节点用不了

### ISSUE THREAD

**Issue by djjh123** [2dust/v2rayNG#2582]
导入同一批节点，在shadowrocket里面可以用，而在v2rayng里面测试速度全部为-1

**Comment by damschen** [comment]
我也是

**Comment by Amsia** [comment]
一样, 很多节点 电脑上可以, 换手机上就不行

**Comment by CrayonSSR** [comment]
我这更奇怪。

同一个路由器Wifi链接，同一个节点。

v2RayN可以正常访问使用。

v2RayNG却不能访问部分网站，打开就是 err_connection_refused。

类似打开Google搜索没问题，但是打开Youtube就是瞬间返回 err_connection_refused

打开后debug的日志是空的，就像我断网了一样

**Comment by Leevisonline** [comment]
我也一样！

**Comment by KeiraX** [comment]
我也是，电脑可以，手机无法
