### ISSUE TITLE
自定义设置节点无法进行局域网分享

### ISSUE THREAD

**Issue by flamehe** [2dust/v2rayNG#2588]
### 预期行为
自定义设置节点可以进行局域网分享

### 实际行为
自定义设置节点无法进行局域网分享访问

### 复现方法
1. 设置一个vmess或trojan节点，传输为gRPC，本机可以访问
2. 导出完整节点配置到剪贴板，并导入自定义配置
3. 修改自定义配置，grpcSettings里加入  "idle_timeout": 10, "health_check_timeout": 20, 用来解决断流问题
https://github.com/XTLS/Xray-docs-next/blob/5ece68eec9d730047396b76c8463e961da37a236/docs/config/transports/grpc.md#grpcobject
4.保存设置，测试本机可以正常使用自定义节点
5.用局域网机器设置代理访问，测试结果访问失败

**Comment by flamehe** [comment]
我大概知道原因了，自定义节点里的完整配置包含了分流和是否允许局域网访问的配置，如果在导出时没选择局域网访问，则配置里不包含此设置。
而app本身的设置无法覆盖自定义节点的内容，所以app设置了局域网访问也无法生效
最好给自定义节点增加一个选项，可以选择是否由app设置覆盖分流和局域网访问等区段

**Comment by Royalbardsiri65** [comment]
# - [ ] []()**_[]()_**
