### ISSUE TITLE
请问能否将assets目录下的相关文件保存到Android/data目录下呢

### ISSUE THREAD

**Issue by reed0214** [2dust/v2rayNG#259]
目前配置文件和dat文件都在assets目录下,导致对其进行修改都没有办法进行
![图片](https://user-images.githubusercontent.com/13160124/74159265-727e4e00-4c56-11ea-9b6e-74699a20bdb3.png)
所以想问下,能否将配置文件放到Android/data目录下,然后从该目录进行配置的读写呢?

**Comment by oiwl** [comment]
> 目前配置文件和dat文件都在assets目录下,导致对其进行修改都没有办法进行
> ![图片](https://user-images.githubusercontent.com/13160124/74159265-727e4e00-4c56-11ea-9b6e-74699a20bdb3.png)
> 所以想问下,能否将配置文件放到Android/data目录下,然后从该目录进行配置的读写呢?
我看了下最新的版本已经做了规则增强，其次只能考虑自己解包改了
Enhanced v2ray rules dat files from https://github.com/Loyalsoldier/v2ray-rules-dat

**Comment by 2dust** [comment]
开放替换dat文件可能会导致app不稳定
目前内置了 https://github.com/Loyalsoldier/v2ray-rules-dat
已经很全

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/pull/662
