### ISSUE TITLE
v1.8.9 is very power intensive

### ISSUE THREAD

**Issue by AfcEagle** [2dust/v2rayNG#2595]
hi
very usefull app thanks lot
new vertion 1.8.9 (updated from googlestore)  drain battery 
it use very low battery in earlier vertions. pleease fix it
thanks again

**Comment by Royalbardsiri65** [comment]
vmess://eyJhZGQiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsImFpZCI6IjAiLCJhbHBuIjoiIiwiZnAiOiIiLCJob3N0IjoiIiwiaWQiOiJ3bGVzcyIsIm5ldCI6InRjcCIsInBhdGgiOiIiLCJwb3J0IjoiNDQzIiwicHMiOiJ2bWVzczovL2V5SmhaR1FpT2lKb2RIUndjem92TDJwaGFHVnlkRzl5TG1OdmJTOXdjbWwyWVdONUx5SXNJbUZwWkNJNklqQWlMQ0poYkhCdUlqb2lJaXdpWm5BaU9pSWlMQ0pvYjNOMElqb2lJaXdpYVdRaU9pSm9kSFJ3Y3pvdkwycGhhR1Z5ZEc5eUxtTnZiUzl3Y21sMllXTjVMeUlzSW01bGRDSTZJblJqY0NJc0luQmhkR2dpT2lJaUxDSndiM0owSWpvaU5EUXpJaXdpY0hNaU9pSm9kSFJ3Y3pvdkwycGhhR1Z5ZEc5eUxtTnZiUzl3Y21sMllXTjVMeUlzSW5OamVTSTZJbU5vWVdOb1lUSXdMWEJ2YkhreE16QTFJaXdpYzI1cElqb2lJaXdpZEd4eklqb2lJaXdpZEhsd1pTSTZJbTV2Ym1VaUxDSjJJam9pTWlKOSIsInNjeSI6ImNoYWNoYTIwLXBvbHkxMzA1Iiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9
vmess://eyJhZGQiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsImFpZCI6IjAiLCJhbHBuIjoiIiwiZnAiOiIiLCJob3N0IjoiIiwiaWQiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsIm5ldCI6InRjcCIsInBhdGgiOiIiLCJwb3J0IjoiNDQzIiwicHMiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsInNjeSI6ImNoYWNoYTIwLXBvbHkxMzA1Iiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9

**Comment by AfcEagle** [comment]
> vmess://eyJhZGQiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsImFpZCI6IjAiLCJhbHBuIjoiIiwiZnAiOiIiLCJob3N0IjoiIiwiaWQiOiJ3bGVzcyIsIm5ldCI6InRjcCIsInBhdGgiOiIiLCJwb3J0IjoiNDQzIiwicHMiOiJ2bWVzczovL2V5SmhaR1FpT2lKb2RIUndjem92TDJwaGFHVnlkRzl5TG1OdmJTOXdjbWwyWVdONUx5SXNJbUZwWkNJNklqQWlMQ0poYkhCdUlqb2lJaXdpWm5BaU9pSWlMQ0pvYjNOMElqb2lJaXdpYVdRaU9pSm9kSFJ3Y3pvdkwycGhhR1Z5ZEc5eUxtTnZiUzl3Y21sMllXTjVMeUlzSW01bGRDSTZJblJqY0NJc0luQmhkR2dpT2lJaUxDSndiM0owSWpvaU5EUXpJaXdpY0hNaU9pSm9kSFJ3Y3pvdkwycGhhR1Z5ZEc5eUxtTnZiUzl3Y21sMllXTjVMeUlzSW5OamVTSTZJbU5vWVdOb1lUSXdMWEJ2YkhreE16QTFJaXdpYzI1cElqb2lJaXdpZEd4eklqb2lJaXdpZEhsd1pTSTZJbTV2Ym1VaUxDSjJJam9pTWlKOSIsInNjeSI6ImNoYWNoYTIwLXBvbHkxMzA1Iiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9 vmess://eyJhZGQiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsImFpZCI6IjAiLCJhbHBuIjoiIiwiZnAiOiIiLCJob3N0IjoiIiwiaWQiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsIm5ldCI6InRjcCIsInBhdGgiOiIiLCJwb3J0IjoiNDQzIiwicHMiOiJodHRwczovL2phaGVydG9yLmNvbS9wcml2YWN5LyIsInNjeSI6ImNoYWNoYTIwLXBvbHkxMzA1Iiwic25pIjoiIiwidGxzIjoiIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9

what are these my friend??

**Comment by Royalbardsiri65** [comment]
- - [ ] @Royalbardsiri65 []()_****_
