### ISSUE TITLE
使用chatgpt官方app时无法访问网络，但通过chrome的web是可以的

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#2598]
报错如下
```
Something went wrong. You may be connected to a disallowed ISP. If you are using VPN, try disabling it. Otherwise try a different Wi-Fi network or data
connection.
```
 请问是哪里配置不对吗?
chrome \ google play是可以正常使用的。

**Comment by ghost** [comment]
现在又报这个错了，There is a problem with you request.(truyuijokl6789oxxxx-LAX)

**Comment by yuehanwali** [comment]
请问解决了吗，我也碰到这个问题

**Comment by SYTEee** [comment]
upupupup

**Comment by nevertoday** [comment]
感觉是漏掉了一些规则，导致这个 情况。

**Comment by styick** [comment]
把域名策略改成ipIfNonMatch 导入https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml 
就可以使用了

**Comment by styick** [comment]
解析改成IpIfNonMatch  导入https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.yaml
就好了
