### ISSUE TITLE
节点正常，连接之后只有Telegram能连上网，其他的谷歌网页，还是Play商店都翻不了

### ISSUE THREAD

**Issue by Rhett-Cai** [2dust/v2rayNG#2599]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Andywang089** [comment]
跟你的问题一模一样，解决了吗

**Comment by Rhett-Cai** [comment]
沒有，不知道怎么搞，现在在用冲浪板

**Comment by DevinMonster** [comment]
同，用xtls+reality可以正常使用，但是切换到机场的ss节点就只能上tg，感觉是dns模块的问题。
