### ISSUE TITLE
1.1.15版本导致无法打开google.com

### ISSUE THREAD

**Issue by imnuke** [2dust/v2rayNG#261]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
使用Chrome浏览器正常访问google.com

### 实际行为
google.com打不开，google.hk、twitter.com等可以正常访问
卸载重新安装回1.1.14版本之后正常。

**Comment by mrrubiks** [comment]
使用该版本时出现了同样的问题

**Comment by Bakanbu** [comment]
我能打开

**Comment by 2dust** [comment]
try 1.2.2
