### ISSUE TITLE
VPN broken in V2rayNG

### ISSUE THREAD

**Issue by o01eg** [2dust/v2rayNG#2620]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Tun2Socks works.

### 实际行为
No connections in applications selected for VPN.

### 复现方法
1. Start V2rayNG
2. Select some applications.
3. Try to open applications.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
11-18 10:57:10.708 22725 22725 D com.v2ray.ang: [/mnt/asec/com.v2ray.ang-O19F6xUUDn0PIIvn/lib/arm/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
11-18 10:57:10.711 22725 22725 D com.v2ray.ang: java.io.IOException: Cannot run program "/mnt/asec/com.v2ray.ang-O19F6xUUDn0PIIvn/lib/arm/libtun2socks.so" (in directory "/data/user/0/com.v2ray.ang/files"): error=13, Permission denied
```
</details>

### 环境信息

V2RayNG 1.8.10
Android 9

**Comment by Kami267016** [comment]
V2ray confing

**Comment by Kami267016** [comment]
What's your name
