### ISSUE TITLE
google play 用不了

### ISSUE THREAD

**Issue by vipcxj** [2dust/v2rayNG#2624]
服务端没问题，因为用clash一切正常

### 预期行为
google play能访问，能下载应用

### 实际行为
google play能访问，但不能下载应用

### 复现方法
1. 安装google play
2. 下载或更新应用

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
小米14，澎湃os

### 额外信息（可选）
查到类似很多issue，说是国内androi自带google框架有问题，用的host不对，问题是clash就没问题啊。现在只能用clash，但clash已经跑路了，v2rayNG又不可用，好蛋疼~

**Comment by Taoister39** [comment]
是的，我最近也是上不了Google

**Comment by vipcxj** [comment]
这个completed是fixed了还是won‘t fix？

**Comment by dkgks** [comment]
我也出现这个问题了，检测IP没有被送中，大佬能帮忙看一下吗？可以提供问题节点。 @2dust
