### ISSUE TITLE
v2rayNG安卓ARM64版本耗电很高很高

### ISSUE THREAD

**Issue by EmergencyBrake** [2dust/v2rayNG#263]
相比于SSR,BifrostV, v2rayNG的耗电实在太高了，不要说是系统把其他应用的耗电算在它头上了，哪怕只开v2rayNG不开其他应用就这样挂着，手机很快开始发热，耗电量陡增。

**Comment by mr-myq** [comment]
确实如此，希望开发者能看到并解决。尤其是在移动网络的状态下，V2Ray耗电与亮屏耗电接近甚至超过亮屏耗电，即使晚上处于待机状态，一晚耗电20%以上，已经尝试使用分代理等等各种不同设置，耗电还是很高！之前用ss或ssr则无此问题。

**Comment by hijkzzz** [comment]
确实如此

**Comment by 2dust** [comment]
ng已经是v2ray同类中最原生的实现方式了
后台跑了core和tun2socks,已经无优化的空间
