### ISSUE TITLE
1.8.4以后版本ss协议 TLS handshake timeout

### ISSUE THREAD

**Issue by han3sui** [2dust/v2rayNG#2650]
1.8.4版本ss协议可以正常使用

1.8.5开始ss协议出现TLS handshake timeout ，无法使用，望修复

**Comment by AdPang** [comment]
我也遇到该问题，我通过更新geo资源之后，就没出现该问题了

**Comment by ZhuJianglai** [comment]
刚入行，不知道也是遇到这样的情况，之前那可以，后面某天就开始不行了，更新geo资源是怎么操作的？请教下
