### ISSUE TITLE
测速的时候失败跳出一串英文

### ISSUE THREAD

**Issue by Phoenixyihui** [2dust/v2rayNG#266]
![mmexport1581743156833](https://user-images.githubusercontent.com/61074340/74582204-df744980-4fb0-11ea-92eb-3b610dff3d7b.jpg)
![Uploading mmexport1581743154298.jpg…]()

**Comment by Phoenixyihui** [comment]
然后最近都用不了 直接都正常的

**Comment by 839891627** [comment]
我也是这样报错
