### ISSUE TITLE
配置中的直连规则可否优先于代理规则？用于FCM

### ISSUE THREAD

**Issue by wdlid** [2dust/v2rayNG#2667]
Google FCM的域名同时包含在了geosite:google里。

**geosite:google** 规则是在代理规则里的。
**geosite:googlefcm**规则是在直连规则里的。

但是从生成的全量配置来看，自定义的直连规则是在最底部的。
导致FCM域名优先匹配到了proxy。

通过修改顺序然后再导入，可看到FCM的域名可以走直连了。

**Comment by 2dust** [comment]
目前的顺序是 proxy，direct，block
考虑是否设计成可以由用户定义
