### ISSUE TITLE
从1.8.5升级到1.8.12全部TLS handshake timeout什么鬼

### ISSUE THREAD

**Issue by byzod** [2dust/v2rayNG#2669]
仔细看了一下所有服务器设置都正确，和之前完全一致，就是一个也连不上
还好劳资有备份，卸载了1.8.12装回1.8.5又完全正常了

### 预期行为
升级后的v2rayng更快更强更稳定

### 实际行为
完全无法连接

### 复现方法
1. 升级1.8.12
2. 连接

### 环境信息
手机V1981A
系统origin os PD1981_A_8.16.0

### 额外信息（可选）
典型服务器
> 加密：auto
> 协议：h2
> 伪装：无
> tls：tls
> fingerprint：无
> alpn：无
> 跳过证书验证：false

设置
> 启用本地dns：☑
> 域名策略：IPIfNonMatch
> 预定义规则：绕过局域网及大陆地址

**Comment by 2315354556** [comment]
我也有同样的问题，哥们解决了吗

**Comment by kfrepo** [comment]
我小米 1.8.5 装1.8.12 怎么提示无法降级安装

**Comment by github-ZH-cn** [comment]
解决了说下

**Comment by 2315354556** [comment]
> 解决了说下

解决了吗？

**Comment by ayayime** [comment]
看一下服务端和客户端的xray版本匹配吗？我通过升级服务端的版本解决了。

**Comment by dinneXbell** [comment]
我通过切换XRAY版本到最新的稳定版解决了这个问题,但是我现在只有XHTTPreality的新建的可以用 之前老的reality链接就失效了
一部分很早建的VMESS的链接也失效了,以后再也不在Google商店乱更新V2RAYNG了

**Comment by dinneXbell** [comment]
我发现更新到最新的XRAY不是很稳定,我上YouTube经常让我人机验证,所以我切回了XRAY24版,发现我手机上最新的V2RAYNG不能用了,我去找了历史版本,我现在用的是这个 https://v2rayng.en.uptodown.com/android/download/1042501104,  v2rayNG 1.9.25
如果你在安卓应用商店更新V2RAY到最新之后握手失败,就把它卸了,直接安装这个APK,就行了,你的服务器没问题,是最新V2RAY的问题
