### ISSUE TITLE
域名解析失败，最近半个多月来忽然就无法使用

### ISSUE THREAD

**Issue by muyufan** [2dust/v2rayNG#267]
升级服务端和和手机端到最新版，依然这样。
设置里勾选 启用本地DNS，还是域名解析失败
为什么服务端的access.log里都根本没有请求进来？

前几天切成4G还能使用来着，今天开始完全不行4G也不行了，难道我被本地ISP给盯上了？

**Comment by andy19801210** [comment]
我的也是这样

**Comment by wx40217** [comment]
同样问题

**Comment by muyufan** [comment]
晕，郁闷几天，重启路由器就好了

**Comment by stiven-ding** [comment]
一样

**Comment by muyufan** [comment]
终于可以了，服务端端口我以前一直用的80，换了个新端口8080就好了，真是诡异。
