### ISSUE TITLE
Save/Load app settings

### ISSUE THREAD

**Issue by EarlVadim** [2dust/v2rayNG#2670]
It is difficult for me to navigate the questions that have already been asked before.
So I decided to write my own.

This is the best mobile client, but it lacks the ability to save/restore app settings. 
For example through "JSON". 
This is also convenient for helping beginners, just give them a ready-made preset, also when updating the app not through the PlayMarket (you must to delete the old version, then install the new and configure it again).

We are talking only about app settings, but not about vpn-configs. Or the ability to manage them separately.

Thanks..

**Comment by BI7PRK** [comment]
currently, it has export configs functions, but it's not in the form of saving a file. It's exported to clipboard.  although not a  goodddd idea,  for version switching, the application itself does not have many configs that need attention.
can to know that english not good to comment -_-

**Comment by EarlVadim** [comment]
@BI7PRK 
I wrote not about configs, but about program settings.
