### ISSUE TITLE
测试失败 io read/write on closed pipe

### ISSUE THREAD

**Issue by heshang91** [2dust/v2rayNG#268]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
服务端没有问题，我电脑可以用

### 预期行为
测试成功，显示Ping值，可以翻墙

### 实际行为
测试失败并且报错io read/write on closed pipe

### 复现方法
1.重启手机
2.卸载后重新安装
3.更新订阅

### 日志信息
无
</details>

### 环境信息
安卓10 pixel experience10系统

**Comment by jw-star** [comment]
节点没问题的话很可能跟你的时间设定有关系，vmess协议时差不能超过90秒

**Comment by heshang91** [comment]
> 节点没问题的话很可能跟你的时间设定有关系，vmess协议时差不能超过90秒

确实是时间问题，我手机重启后时间就变成2月14日6点40了，手动改下时间就能用了，感谢解答。

**Comment by Phoenixyihui** [comment]
我也是这个问题

**Comment by Phoenixyihui** [comment]
重装吗？

**Comment by Phoenixyihui** [comment]
请问那个时间怎么修改

**Comment by becausemadoka** [comment]
> 请问那个时间怎么修改

如果服务端和客户端都是自动更新时间，那么一般没问题，要是差距过大，可以考虑手动修改手机时间，一般设置里面，把自动更新时间关了，手动调一下（当然服务端和客户端同步UTC时间是最好的了）

**Comment by gitdy** [comment]
成功了，感谢，原来不能超过90秒。。。

**Comment by Phoenixyihui** [comment]
> > 请问那个时间怎么修改
> 
> 如果服务端和客户端都是自动更新时间，那么一般没问题，要是差距过大，可以考虑手动修改手机时间，一般设置里面，把自动更新时间关了，手动调一下（当然服务端和客户端同步UTC时间是最好的了）

要上服务端改吗？我这是别人搭建的 我需要怎么知道手机时间和服务端时间差而去更改

**Comment by becausemadoka** [comment]
> > > 请问那个时间怎么修改
> > 
> > 
> > 如果服务端和客户端都是自动更新时间，那么一般没问题，要是差距过大，可以考虑手动修改手机时间，一般设置里面，把自动更新时间关了，手动调一下（当然服务端和客户端同步UTC时间是最好的了）
> 
> 要上服务端改吗？我这是别人搭建的 我需要怎么知道手机时间和服务端时间差而去更改
原则上都同步时间就行了,手机上一般都是默认同步的,Linux服务器的话,参考一下https://blog.csdn.net/JesseYoung/article/details/43488351
(有可能别人那边服务器爆炸了也说不准:-)

**Comment by pcdogyu** [comment]
服务器运行下
Ntpdate time.windows.com

**Comment by Resol1024** [comment]
> 节点没问题的话很可能跟你的时间设定有关系，vmess协议时差不能超过90秒

终于找到原因了，谢谢你！

**Comment by yuanmingchen** [comment]
果然是这样，太感谢了！！！

**Comment by taohuadongle** [comment]
果然是这样，感谢

**Comment by DaimonBaby** [comment]
我服务端和客户端都是自己的，时间也校正过了，还是出现这个错误，之前一直没事，就是这几次更新就不行了，现在用kit就可以连上

**Comment by liangzhenduo** [comment]
Android 10，时间已同步还是出现这个错误，降级到1.2.4恢复正常，1.2.5及以上版本会出现这个问题

**Comment by yuhan6665** [comment]
@liangzhenduo0608 
1.2.5 changed the default behaviour for "tls" "allowInsecure". Try change "allowInsecure" to true in configuration and global settings

**Comment by DaimonBaby** [comment]
> @liangzhenduo0608
> 1.2.5 changed the default behaviour for "tls" "allowInsecure". Try change "allowInsecure" to true in configuration and global settings

這個方法可以，剛剛在設置裡enable allowInsecure，然後在服務器設置裡面把allowInsecure設置為true，現在可以使用了。

**Comment by liangzhenduo** [comment]
> @liangzhenduo0608
> 1.2.5 changed the default behaviour for "tls" "allowInsecure". Try change "allowInsecure" to true in configuration and global settings

Solved, thanks a lot @yuhan6665 .

**Comment by asfuyao** [comment]
WebSocket+TLS方式配置的，之前一直好用突然就连不上了，时间同步也做了，还是不好用，最后发现是证书过期了，更新了证书搞定！

**Comment by maopixin** [comment]
> WebSocket+TLS方式配置的，之前一直好用突然就连不上了，时间同步也做了，还是不好用，最后发现是证书过期了，更新了证书搞定！

请问如何更新证书。

**Comment by cyliu0** [comment]
最近自动更新了 v2rayNG 的遇到这个错误的去升级一下 server 就行。Play 商店的 release notes 里让升级的。

My v2rayNG client has been updated automatically by Google Play yesterday. And it could not connect to the server anymore. And the test always returns this error. But it's nothing to do with the time diff mentioned above. I updated the server according to the release notes. And everything works right now. Hope this comment could help someones found this issue at this moment。

**Comment by jerryszzhu** [comment]
手机出现这个报错，关闭手机自动同步时间，关闭自动时区后正常工作。

**Comment by yuhan6665** [comment]
@jerryszzhu sounds like your vps time out of sync. Try correct time on server.

**Comment by maopixin** [comment]
> 手机出现这个报错，关闭手机自动同步时间，关闭自动时区后正常工作。

我重新下载了旧版本正常使用。

**Comment by huningbo2023** [comment]
> > @liangzhenduo0608
> > 1.2.5 changed the default behaviour for "tls" "allowInsecure". Try change "allowInsecure" to true in configuration and global settings
> 
> Solved, thanks a lot @yuhan6665 .

1.2.5更改了“tls”“allowInsecure”的默认行为。尝试在配置和全局设置中将“allowInsecure”更改为true

**Comment by EvstBee** [comment]
如果用的是gpc，我选了下allow http和https traffic 就好了。

**Comment by thiefsix** [comment]
我更新了一下CA证书的时间，然后降到1.2.4解决了问题

**Comment by rosefun** [comment]
好像把allow选项打开 加密选择chacha20就好了 
https://github.com/2dust/v2rayNG/issues/369#issuecomment-625712770

**Comment by zhuxiaoyu1231** [comment]
同一个电脑配置的服务器都是同步本地时间了，手机上确有一个出现测试失败。

**Comment by dongdong55188** [comment]
时间都一致了还是手机端还是报错 io read/write on closed pipe

**Comment by Yuwei9291** [comment]
> WebSocket+TLS方式配置的，之前一直好用突然就连不上了，时间同步也做了，还是不好用，最后发现是证书过期了，更新了证书搞定！

我的同样是证书过期，感谢该层朋友，更新后正常使用。

**Comment by qiangua5210** [comment]
怎么更新证书呢

**Comment by BZ666a** [comment]
所以现在呢，有一个新问题，我刚才更新他的最新版本，然后出现了这个问题 io read/write.......怎么搞

**Comment by YapuWang** [comment]
> 手机出现这个报错，关闭手机自动同步时间，关闭自动时区后正常工作。

我这样操作后也正常了，也不知道啥原因，自动同步时间和自动时区难道导致了手机实际真实的时间传递不一致么

**Comment by nb95276** [comment]
感谢 折腾好几天原来是由于手机时间不对

**Comment by EurusX31** [comment]
已经使时间同步正确，防火墙关了，服务器vultr上买的，可以ping通，用finalshell跟着utube上的教程弄好了（v2ray，tcp），v2rayN是最新版本的，端口正确，h2和http都连接上了，可以查看服务器延迟，但是无法连接，咋整呜呜

**Comment by YapuWang** [comment]
> 已经使时间同步，最新防火墙关闭了，服务器vultr上买的，可以ping通，用finalutube上的教程弄好连接（v2ray，tcp），v2rayN正确是版本的，正确端口，h2和http都来了，可以查看服务器延迟，但是无法连接，咋整呜呜

是安卓版的吗你发的这个v2rayN是win版的啊，安卓的如果报上面的错误就把自动同步时间关了，自动时区也关了再试试，win版的没有遇到这种情况，一般遇到了大部分也是时间不一致导致的，检查下时区

**Comment by EurusX31** [comment]
是win7

YapuWang ***@***.***> 於 2022年6月22日 週三 晚上7:28寫道：

**Comment by BegenchDev07** [comment]
The problem in my case occur in my android phone. I use for testing i use v2rayNG 7.1.16 version i had that error and solution in my case was permissions on read/write and allowInsecure  = true, (it was false) after saving it worked like a charm. One thing to mention is this solution didn't work on the other phones (Samsung galaxy edge S6 and Huawei) maybe its because of location or coz above listed 2 phones were located in different country.

**Comment by ansonfish** [comment]
如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！

我是这样设置之后，解决了问题： io read/write on closed pipe

**Comment by BZ666a** [comment]
好的，谢谢

ansonfish ***@***.***> 于2022年11月17日周四 13:36写道：

**Comment by zimiyu** [comment]
跳过证书验证选择True就好了

**Comment by simonlkch** [comment]
> 如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！
> 
> 我是这样设置之后，解决了问题： io read/write on closed pipe

成功了

**Comment by marco1208marco** [comment]
进入SSH模式：
rm -rf /etc/localtime #删除自带的localtime
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime #创建软链接到localtime

**Comment by 2h000** [comment]
> 

Nb

**Comment by leonda2008** [comment]
> 跳过证明书验证选择True就好了

调了时间不行，用你的方法OK的 ，谢谢

**Comment by 626lj** [comment]
我更新了一下电脑客户端的 配置 ，然后将该配置文件导到手机，通过选择该文件在手机添加配置，解决了手机上出现的这个问题，希望可以帮到大家

**Comment by mogan1999** [comment]
> 如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！
> 
> 我是这样设置之后，解决了问题： io read/write on closed pipe

确实是fullchain的问题，改成fullchain就解决了，感谢！

**Comment by fanqie4416** [comment]
> Android 10，时间已同步还是出现这个错误，降级到1.2.4恢复正常，1.2.5及以上版本会出现这个问题
感谢，我也是降到1.2.3就可以了

**Comment by fanqie4416** [comment]
> Android 10，时间已同步还是出现这个错误，降级到1.2.4恢复正常，1.2.5及以上版本会出现这个问题

感谢，我也是降到1.2.4解决的，感觉这个解决方法很适合我这样不是自己搭建服务器没法去改服务器配置的。

**Comment by ikanjaja** [comment]
今天三星手机上v2rayNG版本1.8.12碰到这个问题。退回到1.7.38就好了。

**Comment by LastFl** [comment]
测试了多次，最后成功环境如下
手机关闭自动时间 自动时区，版本 1.7.38
安装后，先不导入，确保全局的外层设置中allowInsecure 为true，之后导入配置，确保点进去 里面的allowInsecure 也是true，此时测试 不再报错。

**Comment by chenyin151** [comment]
我的是UUID错误，修改了UUID就OK了

**Comment by lonngxiang** [comment]
> 1.7.38

也不行这版本

**Comment by FYpanda** [comment]
> 如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！
> 
> 我是这样设置之后，解决了问题： io read/write on closed pipe

如果已经有节点了，就修改已有节点里的“公钥文件路径”，输入fullchain.cer的路径，比如“/root/cert/fullchain.cer”，也可以解决问题： io read/write on closed pipe

**Comment by chenyin151** [comment]
好的，目前问题没出现了



在 2024-07-30 00:24:13，"FYpanda" ***@***.***> 写道：

如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！

我是这样设置之后，解决了问题： io read/write on closed pipe

如果已经有节点了，就修改已有节点里的“公钥文件路径”，输入fullchain.cer的路径，比如“/root/cert/fullchain.cer”，也可以解决问题： io read/write on closed pipe

**Comment by DaDaDalong** [comment]
> 测试了多次，最后成功环境如下 手机关闭自动时间 自动时区，版本 1.7.38 安装后，先不导入，确保全局的外层设置中allowInsecure 为true，之后导入配置，确保点进去 里面的allowInsecure 也是true，此时测试 不再报错。

有效解决问题

**Comment by chenyin151** [comment]
好的，回去试试



在 2024-09-08 10:29:03，"DaDaDalong" ***@***.***> 写道：

测试了多次，最后成功环境如下 手机关闭自动时间 自动时区，版本 1.7.38 安装后，先不导入，确保全局的外层设置中allowInsecure 为true，之后导入配置，确保点进去 里面的allowInsecure 也是true，此时测试 不再报错。

有效解决问题

**Comment by tangxuner** [comment]
> 我更新了一下电脑客户端的 配置 ，然后将该配置文件导到手机，通过选择该文件在手机添加配置，解决了手机上出现的这个问题，希望可以帮到大家

亲测可用，感谢

**Comment by tsunchein** [comment]
> 如果是使用X-UI，在面板设置中，“面板证书公钥文件路径”，不要用带自己域名的证书，的输入fullchain.cer（这是标准的CA证书集的文件之一）的路径，比如“/root/cert/fullchain.cer”。然后重启面板。建立的节点，同理！
> 
> 我是这样设置之后，解决了问题： io read/write on closed pipe

感谢，真是这个问题

**Comment by jiangxiaohuo** [comment]
> 如果服务端和客户端都是自动更新时间，那么一般没问题，要是差距过大，可以考虑手动修改手机时间，一般设置里面，把自动更新时间关了，手动调一下（当然服务端和客户端同步UTC时间是最好的了）

怎么调的？

**Comment by fangfangdiyi** [comment]
> 节点没问题的话很可能跟你的时间设定有关系，vmess协议时差不能超过90秒

修改手机时间就搞定了，非常感谢

**Comment by buptcuky** [comment]
> 测试了多次，最后成功环境如下 手机关闭自动时间 自动时区，版本 1.7.38 安装后，先不导入，确保全局的外层设置中allowInsecure 为true，之后导入配置，确保点进去 里面的allowInsecure 也是true，此时测试 不再报错。

安卓安装V1.7.34后遇到同样问题，按照这个方法解决了，感谢

**Comment by dhwang2** [comment]
太对了，大哥
