### ISSUE TITLE
传输协议为tcp，伪装为http时，伪装域名host，path填的内容不生效

### ISSUE THREAD

**Issue by zhang9709** [2dust/v2rayNG#268]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
host与path应该与填的内容相同

### 实际行为
描述实际发生了什么
实际情况是可能使用软件默认的path(/)与host[www.baidu.com, www.bing.com]

### 环境信息
Android 8.1.0
所有的v2rayNG版本

### 额外信息（可选）
导出的全部配置文件(默认就是这么乱)
{"dns":{"hosts":{"domain:googleapis.cn":"googleapis.com"},"servers":["1.1.1.1",{"address":"223.5.5.5","domains":["geosite:cn"],"port":53}]},"inbounds":[{"port":10808,"protocol":"socks","settings":{"auth":"noauth","udp":true,"userLevel":8},"sniffing":{"destOverride":["http","tls"],"enabled":false},"tag":"socks"}],"log":{"loglevel":"warning"},"outbounds":[{"mux":{"enabled":false},"protocol":"vmess","settings":{"vnext":[{"address":"**********","port":80,"users":[{"alterId":1,"id":"8fd83eb9-0bc8-484e-bdd8-4f7ce2268646","level":8,"security":"chacha20-poly1305"}]}]},"streamSettings":{"network":"tcp","security":"","tcpSettings":{"connectionReuse":true,"header":{"request":{"nameValuePairs":{"version":"1.1","method":"GET","path":{"values":["/"]},"headers":{"nameValuePairs":{"User-Agent":{"values":["Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36","Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"]},"Accept-Encoding":{"values":["gzip, deflate"]},"Connection":{"values":["keep-alive"]},"Pragma":"no-cache","Host":{"values":["whutlinux.xyz"]}}}}},"response":{"nameValuePairs":{"version":"1.1","status":"200","reason":"OK","headers":{"nameValuePairs":{"Content-Type":{"values":["application/octet-stream","video/mpeg"]},"Transfer-Encoding":{"values":["chunked"]},"Connection":{"values":["keep-alive"]},"Pragma":"no-cache"}}}},"type":"http"}}},"tag":"proxy"},{"protocol":"freedom","settings":{},"tag":"direct"},{"protocol":"blackhole","settings":{"response":{"type":"http"}},"tag":"block"},{"protocol":"dns","tag":"dns-out"}],"policy":{"levels":{"8":{"connIdle":60,"downlinkOnly":5,"handshake":4,"uplinkOnly":2}},"system":{"statsInboundUplink":true,"statsInboundDownlink":true}},"routing":{"domainStrategy":"IPIfNonMatch","rules":[{"ip":["26.26.26.2"],"outboundTag":"dns-out","port":"53","type":"field"},{"ip":["223.5.5.5"],"outboundTag":"direct","port":"53","type":"field"},{"ip":["geoip:private"],"outboundTag":"direct","type":"field"},{"ip":["geoip:cn"],"outboundTag":"direct","type":"field"},{"domain":["geosite:cn"],"outboundTag":"direct","type":"field"}]},"stats":{}}

![image](https://user-images.githubusercontent.com/13991774/53893488-3f583580-4069-11e9-8767-b3bc42268b48.png)
![image](https://user-images.githubusercontent.com/13991774/53924497-3b530480-40b7-11e9-8c66-da429657bf84.png)

如图所示

**Comment by FH0** [comment]
软件源码的问题，在V2rayConfigUtil.kt文件的295行下面，你可以叫开发者看一下

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.18
