### ISSUE TITLE
v2rayNG 升级后无法在one ui 6.0中建立vmess连接

### ISSUE THREAD

**Issue by sunpengRvi** [2dust/v2rayNG#2687]
### 预期行为
正常创建并使用并可以创建连接

### 实际行为
连接不可用只有上行速度下行无速度

### 复现方法
Samsumg one ui 6.0下安装v2rayNG v1.8.12(Lib v24, Xray-core v1.8.6)

### 日志信息
--------- beginning of main
12-17 10:15:34.079 D/com.v2ray.ang(14661): {
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "dns": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "hosts": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "domain:googleapis.cn": "googleapis.com"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     },
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "servers": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "1.1.1.1"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     ]
12-17 10:15:34.079 D/com.v2ray.ang(14661):   },
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "inbounds": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):     {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "port": 10808,
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "protocol": "socks",
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "settings": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "auth": "noauth",
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "udp": true,
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "userLevel": 8
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "sniffing": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "destOverride": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):           "http",
12-17 10:15:34.079 D/com.v2ray.ang(14661):           "tls"
12-17 10:15:34.079 D/com.v2ray.ang(14661):         ],
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "enabled": true
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "tag": "socks"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     },
12-17 10:15:34.079 D/com.v2ray.ang(14661):     {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "port": 10809,
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "protocol": "http",
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "settings": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "userLevel": 8
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "tag": "http"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     }
12-17 10:15:34.079 D/com.v2ray.ang(14661):   ],
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "log": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "loglevel": "warning"
12-17 10:15:34.079 D/com.v2ray.ang(14661):   },
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "outbounds": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):     {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "mux": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "concurrency": -1,
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "enabled": false,
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "xudpConcurrency": 0
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "protocol": "vmess",
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "settings": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "vnext": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):           {
12-17 10:15:34.079 D/com.v2ray.ang(14661):             "address": "<xxxxxxxxxxxxxx>",
12-17 10:15:34.079 D/com.v2ray.ang(14661):             "port": 80,
12-17 10:15:34.079 D/com.v2ray.ang(14661):             "users": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):               {
12-17 10:15:34.079 D/com.v2ray.ang(14661):                 "alterId": 64,
12-17 10:15:34.079 D/com.v2ray.ang(14661):                 "encryption": "",
12-17 10:15:34.079 D/com.v2ray.ang(14661):                 "flow": "",
12-17 10:15:34.079 D/com.v2ray.ang(14661):                 "id": "<xxxxxxxxxx>",
12-17 10:15:34.079 D/com.v2ray.ang(14661):                 "level": 8,
12-17 10:15:34.079 D/com.v2ray.ang(14661):                 "security": "auto"
12-17 10:15:34.079 D/com.v2ray.ang(14661):               }
12-17 10:15:34.079 D/com.v2ray.ang(14661):             ]
12-17 10:15:34.079 D/com.v2ray.ang(14661):           }
12-17 10:15:34.079 D/com.v2ray.ang(14661):         ]
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "streamSettings": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "network": "ws",
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "security": "",
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "wsSettings": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):           "headers": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):             "Host": ""
12-17 10:15:34.079 D/com.v2ray.ang(14661):           },
12-17 10:15:34.079 D/com.v2ray.ang(14661):           "path": "/"
12-17 10:15:34.079 D/com.v2ray.ang(14661):         }
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "tag": "proxy"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     },
12-17 10:15:34.079 D/com.v2ray.ang(14661):     {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "protocol": "freedom",
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "settings": {},
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "tag": "direct"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     },
12-17 10:15:34.079 D/com.v2ray.ang(14661):     {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "protocol": "blackhole",
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "settings": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "response": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):           "type": "http"
12-17 10:15:34.079 D/com.v2ray.ang(14661):         }
12-17 10:15:34.079 D/com.v2ray.ang(14661):       },
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "tag": "block"
12-17 10:15:34.079 D/com.v2ray.ang(14661):     }
12-17 10:15:34.079 D/com.v2ray.ang(14661):   ],
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "policy": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "levels": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "8": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "connIdle": 300,
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "downlinkOnly": 1,
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "handshake": 4,
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "uplinkOnly": 1
12-17 10:15:34.079 D/com.v2ray.ang(14661):       }
12-17 10:15:34.079 D/com.v2ray.ang(14661):     },
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "system": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "statsOutboundUplink": true,
12-17 10:15:34.079 D/com.v2ray.ang(14661):       "statsOutboundDownlink": true
12-17 10:15:34.079 D/com.v2ray.ang(14661):     }
12-17 10:15:34.079 D/com.v2ray.ang(14661):   },
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "routing": {
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "domainStrategy": "IPIfNonMatch",
12-17 10:15:34.079 D/com.v2ray.ang(14661):     "rules": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):       {
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "ip": [
12-17 10:15:34.079 D/com.v2ray.ang(14661):           "1.1.1.1"
12-17 10:15:34.079 D/com.v2ray.ang(14661):         ],
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "outboundTag": "proxy",
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "port": "53",
12-17 10:15:34.079 D/com.v2ray.ang(14661):         "type": "field"
12-17 10:15:34.079 D/com.v2ray.ang(14661):       }
12-17 10:15:34.079 D/com.v2ray.ang(14661):     ]
12-17 10:15:34.079 D/com.v2ray.ang(14661):   },
12-17 10:15:34.079 D/com.v2ray.ang(14661):   "stats": {}
12-17 10:15:34.079 D/com.v2ray.ang(14661): }
12-17 10:15:34.081 I/GoLog   (14661): loading core config
12-17 10:15:34.081 I/GoLog   (14661): new core
12-17 10:15:34.082 I/GoLog   (14661): start core
12-17 10:15:34.082 I/GoLog   (14661): Preparing Domain: www.nevermount.run:80
12-17 10:15:34.083 I/GoLog   (14661): [Warning] core: Xray 1.8.6 started
12-17 10:15:34.110 I/GoLog   (14661): Prepare Result:
12-17 10:15:34.110 I/GoLog   (14661):  Domain: www.nevermount.run
12-17 10:15:34.110 I/GoLog   (14661):  Port: 80
12-17 10:15:34.110 I/GoLog   (14661):  IPs: [xxx.xx.xx.98 xxx.xx.xxx.135 2606:4700:3037::6815:5c62 2606:4700:3032::ac43:bf87]
12-17 10:15:34.110 D/com.v2ray.ang(14661): [/data/app/~~03qFo4QNDz4YUcIfkFDpig==/com.v2ray.ang-cfdxmUl8iS1BDzZ3UqCLog==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
12-17 10:15:34.125 D/com.v2ray.ang(14661): Process[pid=25065, hasExited=false]
12-17 10:15:34.125 D/com.v2ray.ang(14661): /data/user/0/com.v2ray.ang/files/sock_path
12-17 10:15:34.132 D/com.v2ray.ang(14661): libtun2socks.so check
12-17 10:15:34.136 I/tun2socks(25065): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
12-17 10:15:34.176 D/com.v2ray.ang(14661): sendFd tries: 0
12-17 10:15:34.176 I/tun2socks(25065): NOTICE(tun2socks): entering event loop
12-17 10:15:34.220 I/GoLog   (14661): udp:127.0.0.1:48554 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:34.285 I/GoLog   (14661): udp:127.0.0.1:52635 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:34.551 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:34.604 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:35.200 I/GoLog   (14661): tcp:127.0.0.1:53994 accepted tcp:1.1.1.1:853 [socks >> proxy]
12-17 10:15:35.878 I/GoLog   (14661): udp:127.0.0.1:42286 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:36.218 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:36.540 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:37.276 I/GoLog   (14661): udp:127.0.0.1:38912 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:37.651 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:39.225 I/GoLog   (14661): udp:127.0.0.1:48554 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:39.288 I/GoLog   (14661): udp:127.0.0.1:52635 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:39.702 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:39.702 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:40.885 I/GoLog   (14661): udp:127.0.0.1:42286 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:41.338 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:42.282 I/GoLog   (14661): udp:127.0.0.1:38912 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:42.669 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:44.214 I/GoLog   (14661): tcp:127.0.0.1:48718 accepted tcp:71.132.57.88:5229 [socks >> proxy]
12-17 10:15:44.297 I/GoLog   (14661): udp:127.0.0.1:37959 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:44.328 I/GoLog   (14661): udp:127.0.0.1:53734 accepted udp:1.1.1.1:53 [socks -> proxy]
12-17 10:15:44.616 I/GoLog   (14661): Using Prepared: xxx.xx.xx.98
12-17 10:15:44.658 I/GoLog   (14661): Using Prepared: xx.xx.xx.98
12-17 10:15:44.669 I/GoLog   (14661): Using Prepared: xxx.xxx.xx.98
...
12-17 10:16:06.372 D/com.v2ray.ang(14661): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": io: read/write on closed pipe
...
</details>

**Comment by lpdswing** [comment]
v1.8.12确实有这样的问题，确认节点没问题，sing-box内核正常使用

**Comment by mcoder2014** [comment]
是新版变更了什么默认行为吗？我升级后也不可用了

**Comment by MCOTF** [comment]
我也有io: read/write on closed pipe的情况，并且同一节点电脑端无问题，可以确定是v2rayNG的锅

**Comment by wunsir** [comment]
出现 context deadline exceeded的报错，但是电脑端可以正常使用

**Comment by philipxyc** [comment]
初步测了下是1.8.6引入的bug。前天play store自动升级以后就挂了，手机断网两天受不了了，看起来也没有最近修的迹象。

🚀临时解决方法先降级回v1.8.5。指路链接：https://github.com/2dust/v2rayNG/releases/tag/1.8.5
