### ISSUE TITLE
希望订阅的节点显示订阅的备注

### ISSUE THREAD

**Issue by ShiraiKurokor** [2dust/v2rayNG#269]
![Screenshot_2020-02-17-19-09-45-625_com v2ray ang](https://user-images.githubusercontent.com/61131877/74650603-0901c080-51bd-11ea-81ee-b3ad420d938d.png)
1.实际行为如果一次性使用5个左右订阅，会更新出太多太多节点，特别乱。所以我希望每一个订阅产生的节点能显示出订阅的备注。
2.目前一个节点占用一排的空间，空间利用率上不如一排两个。特别是不小心横屏时。一排显示一个节点是对显示空间的浪费。
希望可以自适应或改为横屏一排显示3个竖屏一排显示2个节点。

**Comment by yuhan6665** [comment]
Added in 1.5.11
