### ISSUE TITLE
Feature request: adding subscription for custom json configuration ｜ 希望增加自定义配置的订阅

### ISSUE THREAD

**Issue by Platway** [2dust/v2rayNG#2694]
It'll be even more wonderful if we could have any of the following formats in subscription:

custom://base64EncodedCustomJsonConfig1
custom://base64EncodedCustomJsonConfig2
……

OR

https://domain.com/customConfig1.json
https://domain.com/customConfig2.json
……

**Comment by donnyxray** [comment]
Yes please. The current URL-style configurations are really limited. It cripples the true power of xray-core. Importing JSON manually is possible, but too cumbersome to do for every single server and update them regularly.

**Comment by Platway** [comment]
I saw in release notes that this feature has been added in v1.8.14. Anyone knows how to use it? 🙏

**Comment by vfarid** [comment]
I recently added support for multiple custom configs in sub links.
