### ISSUE TITLE
希望增加节点全部测速功能和PAC模式

### ISSUE THREAD

**Issue by willaytoun** [2dust/v2rayNG#270]
现在ssr节点太容易挂掉了所以最近用上了v2ray，感觉稳定很多速度也不错，另外个人很喜欢这个APP的风格 简洁大气赞一个：）下面是我在使用过程中的一点感受和建议，希望能给开发大大接下来的升级过程提供一些帮助:

        1、希望在节点设置和分享旁边增加一个节点测速按钮，在上边加号旁增加一个全部节点测速按钮(这两个按钮测PING之前下边的黑条测速度)，这样有很多节点的时候可以不用每一个都连接上之后再看能不能连上网
        2、希望增加一个类似于PC端的PAC模式，SSRR路由模式有一个自定义ACL文件的功能 感觉蛮好用的，现在路由模式选“绕过局域网和大陆”看腾讯NBA还是提示地区不在大陆
        3、测试节点的PING和PC端的差很多，PC端的只有60多APP上有1800(相同的wifi相同的节点)
        4、个人感觉相同节点没有PC端的快，这个有待验证只是感觉而已

使用时间不长，可能是这些功能已经有了只是我还没发现，也希望用的时间长的小伙伴教我一下

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.17

pac请用core自带的功能
