### ISSUE TITLE
建议反馈：希望右上角的过滤配置文件的功能可以一直保持

### ISSUE THREAD

**Issue by veizei-K** [2dust/v2rayNG#2700]
希望右上角的分组过滤的选择可以一直保持，关闭APP后下次再开启的时候也能保持上次所设置的那样。因为当机场多了之后，可能会有一百多个线路，而且还会有质量参次不齐的机场。但是那些只是备用，一般不会用，目前每次过滤分组后重新启动APP都会恢复默认所有，然后每次测速或者要看主要是用的机场的信息都要去切换一下，比较繁琐。因此希望可以一直保持所选定的分组设置。
![IMG_20231223_020119](https://github.com/2dust/v2rayNG/assets/129288685/ab1de8be-453e-4853-b2c5-68f102ae2fe5)

**Comment by NightShadeXR** [comment]
如果能在主页增加各个订阅分组的快捷切换按钮就更好了。另外，希望每次打开时能快速锁定到上次使用的节点处，省去下滑寻找的步骤。
