### ISSUE TITLE
请问新版如何恢复旧版皮肤

### ISSUE THREAD

**Issue by iseeyo** [2dust/v2rayNG#2701]
新版皮肤变成了全部白色，视觉效果不如旧版的黑色导航任务栏+白色内容好看，请问怎么恢复旧版皮肤呢。

**Comment by zazitufu** [comment]
我也想知道是否有选项可以调整，全白看得好刺眼，而且节点列表和最下面的节点测试没有颜色区分，就是像所有模块都混杂在一起，主观感觉上有点不舒服。

**Comment by 2dust** [comment]
手机开启暗黑模式

**Comment by 2dust** [comment]
手机开启暗黑模式

**Comment by iseeyo** [comment]
主要是不喜欢暗黑模式，哈哈哈哈

**Comment by zazitufu** [comment]
个人感觉不喜欢手机全局开‘暗黑模式’，因为有些app的暗黑模式并不好看。

另外V2rayNG的暗黑模式刚才试了一下，就是全白变全黑。

因为1.8.5和以前，上下状态栏跟节点模块有颜色区分，对比起来看得比较好看清楚布局。

也许作者比较喜欢当前1.8.12的背景颜色布局，但是作为用户恳请作者给回原来的主题作为选项。谢谢
