### ISSUE TITLE
Request function: ECH support 

### ISSUE THREAD

**Issue by dill-shower** [2dust/v2rayNG#2703]
Can will we implemt Encrypted client hello function in this client? This is already support in chrome, Firefox, sing-box proxy, cloudflare force enabled this for all free plans

**Comment by Farazhaji** [comment]
سلام من ناخواسته دکمک حذف را زدم و تمام یکربندیها پاک شد والان روشن نمیشود لطفا کمک کنبد چون به جایی که این vpnرا خریداری کرده ام دسترسی ندارم ممنون
