### ISSUE TITLE
V2rayNG Auto Subscription Update Issue

### ISSUE THREAD

**Issue by StayAway32** [2dust/v2rayNG#2706]
greetings dear support

there is a problem with auto sub update

its off by default in settings
and when you add a sub link its OFF again in the subscription list and you should enable it manualy 2 times for it to work

but if average person was able to do all that they would easily just hit 3 dots and choose update sub !

can you please just turn it on by default in both setting and subscription list ?
its 1 update every 24 hour ! 
thanks alot

**Comment by donnyxray** [comment]
I agree. The complexity of setting up and maintaining the automatic updates defeats the original purpose: providing the end-user with servers that always work without too much hassle.

IMHO, the subscription URL should take a parameter like ```&update_internal=3600``` and the end-user should not have to do anything at all.

**Comment by bahramini** [comment]
also when it updates the selected server will change.

**Comment by reza4fprm** [comment]
Good idea add update on open, and set Default to on
