### ISSUE TITLE
请问v2rayNG在哪里设置本地策略？

### ISSUE THREAD

**Issue by poemsiu** [2dust/v2rayNG#271]
发现NG的默认本地策略timeout只有60s，太短了，无法保持一些长连接，但是找不到哪里可以更改本地策略的，改在哪里改？

**Comment by 2dust** [comment]
暂时无法修改

**Comment by poemsiu** [comment]
> 暂时无法修改

强烈建议加入本地策略配置以解决tcp长连接问题，比如gcm
