### ISSUE TITLE
境内DNS 和 远程DNS 无法同时使用 DoH

### ISSUE THREAD

**Issue by cherinyy** [2dust/v2rayNG#271]
因为近期发现阿里DNS有 DoH 了([https://dns.alidns.com/dns-query](https://dns.alidns.com/dns-query))，所以在境内 DNS 填写了阿里DNS，在远程DNS填写了Google Public DNS(DoH)。
然后发现无法打开 https://nstool.netease.com

故判断无法同时使用 DoH。

**Comment by protonmailv5** [comment]
哪里有远程DNS的选项？

**Comment by cherinyy** [comment]
> 哪里有远程DNS的选项？

![Screenshot_20200310-233454](https://user-images.githubusercontent.com/9050713/76329814-04e24200-6328-11ea-9f77-2e33835d8e7b.jpg)

**Comment by protonmailv5** [comment]
我直接填写的 1.1.1.1  没填域名

**Comment by IceCodeNew** [comment]
把完整配置导出来，这样大家才能帮你看看是不是 app 没有正确生成境内境外 dns 同时使用 doh 的配置。

**Comment by IceCodeNew** [comment]
```
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [{
        "address": "https+local://dns.alidns.com/dns-query",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      },
      "https://1.0.0.1/dns-query",
      {
        "address": "9.9.9.9",
        "port": 9953
      },
      "185.222.222.222",
      "localhost"
    ]
  },
```

我用自定义配置可以做到境内境外 DNS 都走 DOH，没有折腾客户端提供的选项的想法，所以看你要不要也转到自定义配置了（我发现 APP 自动生成的配置很多细节上不合我意

**Comment by cherinyy** [comment]
> 把完整配置导出来，这样大家才能帮你看看是不是 app 没有正确生成境内境外 dns 同时使用 doh 的配置。

测试后发现已修复此问题，我惊讶于没有维护者来告知此事（

**Comment by rurirei** [comment]
impossible to use DoH / DoT https://github.com/2dust/v2rayNG/issues/653
