### ISSUE TITLE
service/V2RayServiceManager.kt:53:81 Too many arguments for public open fun initV2Env(p0: String!): Unit defined in libv2ray.Libv2ray

### ISSUE THREAD

**Issue by Redshado0w** [2dust/v2rayNG#2711]
Hello to all dear teachers
I am planning to build the source for some customizations, and due to my lack of experience in the Go language, I cannot build the libv2ray.aar. As a result, I got help from the links below, 

however, I get the following error during the build.
/com/v2ray/ang/service/V2RayServiceManager.kt:53:81 Too many arguments for public open fun initV2Env(p0: String!): Unit defined in libv2ray.Libv2ray

If possible, if time permits, please suggest me a solution

**Comment by SomayeKhaleghi** [comment]
I had this problem too, but when I looked at  initV2Env function  input arguments in 
https://github.com/2dust/AndroidLibXrayLite/blob/main/libv2ray_main.go
and
https://github.com/2dust/AndroidLibV2rayLite/blob/master/libv2ray_main.go
found that  must build AndroidLibXrayLite project on Linux  to make libv2ray.aar.

for this you must install go with version 21 or above and install  upper and have NDK  version 21+ and must set system environment correctly for go , gomobile, android SDK , and NDK.

**Comment by omid-aram** [comment]
> I had this problem too, but when I looked at initV2Env function input arguments in https://github.com/2dust/AndroidLibXrayLite/blob/main/libv2ray_main.go and https://github.com/2dust/AndroidLibV2rayLite/blob/master/libv2ray_main.go found that must build AndroidLibXrayLite project on Linux to make libv2ray.aar.
> 
> for this you must install go with version 21 or above and install upper and have NDK version 21+ and must set system environment correctly for go , gomobile, android SDK , and NDK.

@SomayeKhaleghi, You saved me a lot of time 🙏
