### ISSUE TITLE
Android TV Icon in missing

### ISSUE THREAD

**Issue by sharon-git** [2dust/v2rayNG#2716]
Was able to install and run v2rayNG on my Android TV v7 and v8 (Oreo)
But it's missing the app icon.
Please add icon for all versions of Android TV.

**Comment by bahramini** [comment]
install "Side Load" or somthing like that. android tv don show icons of apps that are not designed for TV.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.21
