### ISSUE TITLE
建议增加自动选择最优线路功能

### ISSUE THREAD

**Issue by djoiucxaoishe** [2dust/v2rayNG#2723]
如题

**Comment by donnyxray** [comment]
This is a very complicated ask. What is the best server?

The current tests only test latency to Google. But is Google all you need? And is latency all you care about? How about bandwidth for streaming? It's much more difficult to test.

For example: the latency test often leads people to choose Hong Kong servers. But if you want to watch YouTube or Netflix in 4K resolution, you're often better off choosing a Los Angeles server.
