### ISSUE TITLE
app crashing sometimes

### ISSUE THREAD

**Issue by itsDantes** [2dust/v2rayNG#2727]
app crashing sometimes due to this error. i searched xray and v2ray issues in their github but never find anything.

**` libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x200000032 in tid 10830 (zooz.luvpn), pid 10830 (zooz.luvpn)`**

i found that when i disable **[tun2socks](https://github.com/2dust/v2rayNG/blob/5e4d9246c277434b8ea80308893893897e071e72/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L196)** function, app never crashing. whats the problem?

can you guys replace tun2socks with the [**hev-socks5-tunnel**](https://github.com/heiher/hev-socks5-tunnel) lib ?

**Comment by sunzhusz** [comment]
i agree
