### ISSUE TITLE
如果自家路由器也装有代理，能不能手机端自动使用直连模式

### ISSUE THREAD

**Issue by channingbox** [2dust/v2rayNG#273]
有的人自己家路由器也装有代理，但手机也装有代理，能不能连接自家路由器的时候手机端采用直连，连外面路由器又是才用代理。好像ios下小火箭有类似的功能，安卓下还没有。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.17
