### ISSUE TITLE
程序BUG

### ISSUE THREAD

**Issue by Kbstsn** [2dust/v2rayNG#2735]
### 预期行为
应该是提示连接失败的信息，而非程序崩溃

### 实际行为
使用VLESS-XTLS-uTLS-REALITY的配置时，当配置中的Fingerprint为360，android时会触发程序的崩溃

### 复现方法
1.导入VLESS-XTLS-uTLS-REALITY的配置信息
2.修改Fingerprint为非web浏览器，然后保存配置
3.连接该节点，点击测试连接

### 环境信息
三星S10+，1.8.12和1.8.13的版本都会触发

### 额外信息
其他类型的配置暂未测试

**Comment by Tshsbjsoabdidndbiosbjxixbxbjis** [comment]
Không kết nối được mạng

**Comment by ndangho** [comment]
Không thể kết nối internet

**Comment by 2dust** [comment]
确实panic
`panic: runtime error: invalid memory address or nil pointer dereference`

**Comment by 2dust** [comment]
您是否有时间把此问题提交到 https://github.com/XTLS/Xray-core/issues

**Comment by 2dust** [comment]
xray回复：
`对于 Vision 和 REALITY，暂不能选 android 和 360，它们指向的指纹不支持 TLSv1.3`
