### ISSUE TITLE
有几个想法（不是bug）

### ISSUE THREAD

**Issue by bian2022** [2dust/v2rayNG#2738]
1.  希望默认的路由设置>预定义规则可以改为绕过局域网及大陆地址后而代理，而不是全局代理

2.  希望可以让用户通过github的actions编译更简单①希望可以让用过简单的修改配置文件即可实现改软件的包名、软件名称（有些国内应用需要读取应用列表，怕把数据上传上去）（另外，如果每次编译的时候随机加入几个字符，是不是可以绕过某些国产手机安装的时候报毒这一现象）②在编译的时候支持添加订阅连接或节点，在教朋友使用软件的时候，恨不能的能远程控制手机，某些小白真的很适合用一键连接（更新订阅可以提取写好，比方说每天更新一次），暂时就这些想法，希望开发者可以考虑下，谢谢！
如果 没有时间，就算了。

**Comment by bian2022** [comment]
我自己挨着找了下，包名是不是在V2rayNG/build.gradle文件里的第16行，软件名称V2rayNG/settings.gradle第16行修改，如果是的话，是不是只修改这两个，就可以改包名和软件名称了？

**Comment by bian2022** [comment]
> 我修改自己修改弹着找到了下，包名是不是在V2rayNG/build.gradle文件里的第16行，软件名称V2rayNG/settings.gradle第16行，如果是的话，是不是只这两个，就可以改包名和软件名称了？
实测发现，包名可以改成功了，但软件名称没改成功

**Comment by 582583241** [comment]
第一个非常赞同

**Comment by wakaka123wakaka** [comment]
支持，把订阅内置进入直接发给小白，方便好多
