### ISSUE TITLE
[Enhancement] Author's consent of publishing the app on F-Droid

### ISSUE THREAD

**Issue by oksjd** [2dust/v2rayNG#274]
In #109, the author closed the issue on the ground of the lack of time. However because the issue is not resolved, I'm reopening the issue here.
@dimqua has already opened [a inclusion request at F-Droid](https://gitlab.com/fdroid/rfp/issues/1168), only the consent of the author is needed to proceed the inclusion.
So please @2dust , all you need to do is voicing your support and keeping the app FLOSS.
Thanks again for your hard work all along the way to help masses to circumvent the barriers.

**Comment by Korb** [comment]
@oksjd, You failed to publish this app on F-Droid?
