### ISSUE TITLE
TLS handshake timeout 

### ISSUE THREAD

**Issue by skytech-cyber** [2dust/v2rayNG#2743]
Error:
D/com.v2ray.ang(31480): measureV2rayDelay: go.UniverseSproxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout 

Reason:
The Xray-core server is located in the area couldn't reach google

Possible Solutions:
Add options to choose test ping url: google, apple, yahoo or custom

**Comment by github-ZH-cn** [comment]
我也是这个问题,怎么解决

**Comment by ghost** [comment]
我也是这个问题

**Comment by abdulbasetbasher** [comment]
install 1.8.16
[https://github.com/2dust/v2rayNG/releases/tag/1.8.16](https://github.com/2dust/v2rayNG/releases/tag/1.8.16)

**Comment by dawncold** [comment]
我用的是 1.8.17 版，有这个问题，日志能看到一样的错误，但，不影响实际使用，可能就是测试速度受到了影响。不过，我另一个节点测速没问题。。。

**Comment by tkmark** [comment]
it's nothing to do with versions, it's cause by the time unsync between client and server, many ntp server been baned by GFW cause the time on device is far from the real time, that's why HANDSHAKE FAILED.
这个问题是服务器和客户端时间差异过大造成的，要确保客户端时间是基本准确的才行。注意有的系统用了谷歌的时间服务器导致不能准确设置时间，导致这个问题。
