### ISSUE TITLE
User agent when updating subscription

### ISSUE THREAD

**Issue by Zaltapar** [2dust/v2rayNG#2746]
I was using a WAF rule in cloudflare to block certain countries access to my website when i noticed that when V2rayng sends a request to get config info from servers via subscription it introduces itself in the User-agent header asa V2rayng/version(e.g.1.8.12).
I think the app should use regular user-agent (e.g. Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36).
![Screenshot 2024-01-10 234605](https://github.com/2dust/v2rayNG/assets/60172658/b301633f-0888-40d0-ba90-90354ddd3146)

**Comment by karimi12** [comment]
for masking it, please use https. 

when your subscription link uses https, anyone can't read the user agent.

**Comment by Zaltapar** [comment]
I am using https, so im not worried about it.But it would be more secure if it was a different header.
