### ISSUE TITLE
multi custom config

### ISSUE THREAD

**Issue by karimi12** [2dust/v2rayNG#2749]
How can I use multi custom config in a subscription link?

**Comment by AlirezaMoseni** [comment]
This feature does not exist. I also need such a feature

**Comment by M03ED** [comment]
this feature can be very helpful, we get a custom config from sub link and show outbounds separated, so user can choose, like what sing-box do right now , then we can send configs with fragment via sub link to users

**Comment by vfarid** [comment]
https://github.com/2dust/v2rayNG/pull/2827
