### ISSUE TITLE
How to use "custom config" feature?

### ISSUE THREAD

**Issue by S-Tsunemori** [2dust/v2rayNG#275]
My v2ray server is setup using a way not available with the built-in "type manually" feature, so I decide to give custom config feature a try. However, there's little information on how to use the "custom config" feature I have no idea how to even start, could you please provide a minimal documentation on this?

Points of interest:

1. What kind of inbounds should I provide in my config?  
And how do I set them? For example, should I enable auth?

2. Which part of the custom config is used?  
I have ```inbounds```, ```outbounds```, ```routing```, and ```dns``` in my client config file, are the all honored by v2rayNG?

3. While using a custom config, which settings (of v2rayNG) are still in effect, which are not?  
I'm only interested in per-app proxy as other settings seem available via config file directly.

It would be nice if I can export a configuration created with the "type manually" feature (or convert it to a custom config) then modify it to suite my need, however it doesn't seem possible with the current version.

**Comment by 2dust** [comment]
Please use custom configuration
