### ISSUE TITLE
对于需要代理状态下才能更新的订阅链接，无法完成更新

### ISSUE THREAD

**Issue by molinfen** [2dust/v2rayNG#2760]
有些订阅链接在移动端v2rayng（ v1.8.12 - xray-core v1.8.6）中无法更新。
在之前的版本也有该问题，上一个使用的版本大概是v1.8.6（不确定）

### 预期行为
更新并显示出订阅链接下的节点信息。

### 实际行为
底部会弹出**失败。

### 复现方法
0. 准备一个订阅链接，该链接必须在代理状态下才能更新成功（可在pc端测试）
1. 订阅设置添加该链接，并进行更新，地不会弹出**失败。
2. v2rayng已经连接某个可用节点的状态。使用v2flyng添加该链接，依旧会更新失败。
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
harmony 3.0.0

### 额外信息（可选）
该链接在pc端（v2rayn）中已确认可以使用更新。
在pc端更新时，点击【更新当前订阅（不通过代理）】时同样无法更新。但如果已经处于某个可用节点之下，点击【更新当前订阅（通过代理）】可以正常更新。

推测为，该订阅链接 需要处于代理之下才能正常更新成功，但移动端似乎一直处于非代理状态（包括移动端已经连接了节点，可访问google等，并已经在分应用代理中包括了v2rayng）

对于不需要代理状态就能更新的订阅链接，可以正常使用。

**Comment by DavidZHY** [comment]
我也遇到了完全相同的问题，我把电脑上更新订阅后的一个节点信息手动输入到手机上，能让手机成功连接节点，可以从Google Play上面下载内容了，但是在连接的情况下我还是不能更新订阅。

**Comment by AitchHe** [comment]
same

**Comment by CAureliano** [comment]
+1

**Comment by Philzoo** [comment]
+1

**Comment by 2dust** [comment]
[Uploading v2rayNG_1.8.22_arm64-v8a.zip…]()

测试反馈

**Comment by Creeper3222** [comment]
[+1，同样是pc端V2ray能直连正常更新的订阅链接，安卓端v2rayNG一直订阅失败

![Image](https://github.com/user-attachments/assets/e4f9892d-3e47-4a08-a232-d3550aeccde8)

**Comment by joon612** [comment]
一样的问题，有解决方案吗？用的最新的v2.1.5
