### ISSUE TITLE
开启VPN后图标显示黄色

### ISSUE THREAD

**Issue by YUANJIXX** [2dust/v2rayNG#2769]
切无法正常链接网络

**Comment by YUANJIXX** [comment]
![Screenshot_2024-01-19-17-30-20-446_com.v2ray.ang.jpg](https://github.com/2dust/v2rayNG/assets/128463893/5f866138-fd7f-4730-b990-150f5af84fcd)

显示如图，但是无法正常使用

**Comment by MoSeHuangHun** [comment]
一样，不知道是不是新版本不再支持一些机场的协议。我的能更新，但也是不能使用

**Comment by King-Of-Knights** [comment]
节点问题

**Comment by alexiaocl** [comment]
我的也是这样，有解决方案了嘛

**Comment by MoSeHuangHun** [comment]
目前没有，我一直尝试新版本是否复原，但都为成功。
如果需要继续使用，需要退回1.85版本。

alexiaocl ***@***.***> 于 2024年2月18日周日 17:25写道：

**Comment by MoSeHuangHun** [comment]
转换订阅用sing-box或者用surfboard，v2rayng 新版本手机端，用机场的很多人都遇见这种情况，如果一定要v2rayng加机场订阅,
就需要退回老版本。

2dust ***@***.***> 于 2024年4月11日周四 07:58写道：
