### ISSUE TITLE
[BUG] Checking connection doesn't go through proxy (always takes default route)

### ISSUE THREAD

**Issue by S-Tsunemori** [2dust/v2rayNG#277]
I'm playing with the custom config and got some success. In my custom profile, I have two ```inbounds```, one for ```socks``` and one for ```http```, both of them are tagged. In the ```routing``` section I route them to my proxy outbound by matching their tags, and it works fine when I try to access websites using browser.

However, when I try to test connection using v2rayNG ("Connected, tap to check connection"), it fails. Looking at logcat, it shows:

```[Info] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:80```

Appraently, it didn't take either of my two inbounds. Instead it goes through the default route (first outbound), which is ```freedom``` in my custom profile. Since I can't connect to google.com directly, it fails.

**Comment by yuhan6665** [comment]
Are you sure you route the "http" inbound correctly? Can you post your custom config?

**Comment by S-Tsunemori** [comment]
I just updated v2rayNG to 1.4.8 and the problem persists. I did more testing and observed some strange behavior:

> Checking connection **doesn't seem to go through the http inbound I set** in the custom config.

I have this inbound object in my custom config (I have changed HTTP proxy port to 20080 in v2rayNG setting)

```json
{
  "tag": "in-http",
  "listen": "127.0.0.1",
  "port": 20080,
  "protocol": "http"
}
```

and I have the following routing rule:

```json
{
  "type": "field",
  "inboundTag": [
    "in-socks",
    "in-http"
  ],
  "outboundTag": "out-proxy"
}
```

I can confirm this routing rule is correctly applied, since the socks proxy works just fine. All my apps have working proxy.

However, while checking connection via v2rayNG UI, the rule is simply ignored, with log:

```
[Info] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:80
```

Even if I remove the http inbound (I've set v2ray log to "debug" and **confirmed that v2ray-core is only listening on the socks port and dns port**) the above log still appears, which means even if there's no http inbound at all, v2rayNG still checks connection somehow and that causes v2ray-core to dispatch the connection with default route (black-hole in my case)

---

To confirm this connection is actually sent to v2ray-core, I added the following routing object at the end of routing rules (so it catches everything tcp)

```json
{
  "type": "field",
  "network": "tcp",
  "outboundTag": "out-proxy"
}
```

Now checking connection **works even with the http inbound still removed**, log says:
```
[Info] v2ray.com/core/app/dispatcher: taking detour [out-proxy] for [tcp:www.google.com:80]
```
So the catch-all routing rule catches the connections, which means it does goes through v2ray-core, **but how?** Remember, I don't even have a http inbound, and it clearly doesn't have a inbound tag.

**Comment by yuhan6665** [comment]
@S-Tsunemori , I did some tests and some study of the code again. Looks like you are correct. In latest code, the testing is done in a special way by dial connection through the v2ray core directly, not through either inbounds. (~~Although the dns of "google.com" still went through normal inbounds~~ dns of "google.com" use the v2ray dns module directly as well)
Looks like you have to add a routing rule like the one you pointed out. Or just route "google.com" to proxy.
