### ISSUE TITLE
Automatic update subscription not working / improvement idea 

### ISSUE THREAD

**Issue by reza4fprm** [2dust/v2rayNG#2771]
I tested Automatic update subscription in to many phone with v2rayng 1.8.12 bot not working.
Please add automatic update subscription on open app and turn it on by default.
In thia way user no need to active Auto update and default is on, update will work and no need run background work to run update I interval, because in android, battery restrictions blocked background app and Auto update not work.
Update on open will good idea and this option used by many app for example V2box and strainsand in ios and work good.

**Comment by Hesam-Mahmoodi** [comment]
Good idea, please add a feature ....

**Comment by mezhgano** [comment]
Actually this is good idea, because auto-update not working, even if i set battery optimization to «Unrestricted» (Android 16). 
Just add «Auto-Update Subscription when application opens», at least.
