### ISSUE TITLE
手机熄屏后断网络

### ISSUE THREAD

**Issue by qazxswedcx12** [2dust/v2rayNG#2777]
v2rayng开后台是熄屏等几分钟后断网和无法上网的问题。v2rayng再重开就好了可以上网了。可能是第三软件有问题，我的华为手机是HarmonyOS4系统，请你们尽快修复，谢谢！

**Comment by chunlinfan** [comment]
遇到同样的问题

**Comment by 2dust** [comment]
不支持国产手机

**Comment by ItsEricRao** [comment]
去设置里看看是不是开了电池优化，在Harmony OS 4.0上通过关闭对V2Ray NG的电池优化解决了问题

**Comment by qazxswedcx12** [comment]
已经关闭省电模式，回到全部正常的
