### ISSUE TITLE
[启用本地DNS]选项的疑惑

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [2dust/v2rayNG#278]
这个功能的描述太模糊，请问具体作用是什么？把系统默认的DNS用作主DNS，然后远程DNS用作解析吗

**Comment by ShoukakuChuuCC** [comment]
DNS由本地的V2Ray core处理（测试）

**Comment by ShoukakuChuuCC** [comment]
是和BifrostV里的这个设置意思相同吗？
![TIM截图20190318183423](https://user-images.githubusercontent.com/38343280/54524245-76eda880-49ac-11e9-8186-7ea54f4bd559.png)

**Comment by 2dust** [comment]
hi，具体情况你可以启用词此功能后，导出完整配置查看

**Comment by ShoukakuChuuCC** [comment]
非常感谢，学到了

**Comment by ShoukakuChuuCC** [comment]
"inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8

用户等级8，和用户等级0，1有什么区别呢
