### ISSUE TITLE
奇怪的insecure问题

### ISSUE THREAD

**Issue by alcatraz-zz** [2dust/v2rayNG#2784]
因为我的中文有点弱。。。

I maintain a couple of servers and they all work ok except for one. I thought it was my configuration but after a complete reinstall just like I always do the problem remains the same.

With V2rayN (windows) I can use the flag Insecure false and everything works fine. With V2rayNG (android) I can't. It only works with Insecure true. I don't understand why. EVERYTHING on this server is the same as the others. The VM, debian, install script, script/core versions, settings. Everything. On all my other servers I run insecure false on both clients. I'm still on vless+tls+vision and I use the franzkafka x-ui script and standalone cert/key. I tried changing the host name and generating new cert/keys but no difference.

Does anyone have an idea what it could be? How can I supply logs?

Thanks! 2dust哥辛苦了

**Comment by hualayn** [comment]
我也有这样的问题，也是最近才发生的。原来一直是好好的，然后突然就连不上，提示```net/http: TLS handshake timeout```  
已经将ssl证书更新过了，还是这样  
但是CF搭建的vless服务器就没有这样的问题

me too. and this happened recently. it was very good in use but suddenly it didn't work. the error is ````net/http: TLS handshake timeout```
and i renewed the ssl cert, but didn't work
but vless in CF doesn't has this problem
pls help

**Comment by hualayn** [comment]
我也有这样的问题，也是最近才发生的。原来一直是好好的，然后突然就连不上，提示```net/http: TLS handshake timeout```  
已经将ssl证书更新过了，还是这样  
但是CF搭建的vless服务器就没有这样的问题

me too. and this happened recently. it was very good in use but suddenly it didn't work. the error is ````net/http: TLS handshake timeout```
and i renewed the ssl cert, but didn't work
but vless in CF doesn't has this problem
pls help

**Comment by wangwang-code** [comment]
> 我也有这样的问题，也是最近才发生的。原来一直是好好的，然后突然就连不上，提示`net/http: TLS handshake timeout` 已经将ssl证书更新过了，还是这样 但是CF搭建的vless服务器就没有这样的问题
> 
> me too. and this happened recently. it was very good in use but suddenly it didn't work. the error is ````net/http: TLS handshake timeout``` and i renewed the ssl cert, but didn't work but vless in CF doesn't has this problem pls help

当DNS解析失败时同样会发生`net/http: TLS handshake timeout`
可以试试 https://github.com/wangwang-code/v2rayNG/releases/tag/99999

**Comment by hualayn** [comment]
我已经解决了，是证书问题。使用fullchain的证书。
i solved this problem.it is caused by certs.use a fullchain cert
:)

**Comment by alcatraz-zz** [comment]
> 我已经解决了，是证书问题。使用fullchain的证书。 i solved this problem.it is caused by certs.use a fullchain cert :)

Cool! But I generated my certs the same way on all servers. One doesn't work in insecure. (standalone letsencrypt bla bla acme script)

What do you recommend to try?

**Comment by hualayn** [comment]
1.

 1. generate and.install fullchain.cert

acme.sh --installcert -d 〈your domain〉--cert-file /cert/file/path/cert.crt --key-file /cert/file/path/cert.key --fullchain-file /cert/file/path/fullchain.crt --ecc
2.modify xray config.json，find "certificatefile", use the fullchain.cert

发自我的 iPhone

在 2024年5月6日，14:37，alcatraz-zz ***@***.***> 写道：

﻿

我已经解决了，是证书问题。使用fullchain的证书。 i solved this problem.it is caused by certs.use a fullchain cert :)

Cool! But I generated my certs the same on all servers. (standalone letsencrypt bla bla acme script)

What do you recommend to try?

**Comment by hualayn** [comment]
1. install fullchain.cert
```bash
acme.sh --installcert -d 〈your domain〉--cert-file /cert/file/path/cert.crt --key-file /cert/file/path/cert.key --fullchain-file
```
3. modify config.json of xray server, like this:
```json
"inbounds": [
{
...
  "streamsettins": {
  ...
    "certificates": [
            {
              "certificateFile": "/usr/local/etc/xray/xray_cert/fullchain.crt",
              "keyFile": "/usr/local/etc/xray/xray_cert/xray.key"
            }
          ]
...
```
have a try :)

**Comment by alcatraz-zz** [comment]
Thanks for the replies!

To clarify, it's a very easy fix. When using X-UI like FranzKafka's and you use the builtin acme certificate generation script, it actually generates fullchain.cer alongside the other .cer files. 

Simply point to the fullchain.cer file in X-UI web interface. Done!
