### ISSUE TITLE
gRPC initial_windows_size

### ISSUE THREAD

**Issue by nasiriscript** [2dust/v2rayNG#2798]
When using Cloudflare CDN with GRPC, Cloudflare CDN send "unexpected h2 GOAWAY" frames to close existing connections after some time (it is more likely to happen if I visit Cloudflare sites meanwhile), except when initial_windows_size is 35536 or higher to disable the Dynamic Window mechanism
https://xtls.github.io/en/config/transports/grpc.html#grpcobject

So may I ask to add the ability to change this value in configs? or if it could be set in settings for all configs it will be awesome!

**Comment by 2dust** [comment]
Please use custom configuration
