### ISSUE TITLE
hysteria protocol 

### ISSUE THREAD

**Issue by itsDantes** [2dust/v2rayNG#2799]
please add hysteria2 protocol, its fast and stable. also sing-box app support it but v2rayng still miss this protocol

**Comment by mmrabbani** [comment]
v2rayNG uses Xray core. Xray core doesn't support hysteria2. You can use apps with sing-box core.

**Comment by itsDantes** [comment]
@mmrabbani https://github.com/XTLS/Xray-core/issues/2982
