### ISSUE TITLE
More chrome utls fingerprint

### ISSUE THREAD

**Issue by dill-shower** [2dust/v2rayNG#2800]
When selecting an utls fingerprint, it should be possible to choose in addition to the current options

 chrome_psk
 chrome_psk_shuffle
 chrome_padding_psk_shuffle
 chrome_pq
 chrome_pq_psk

Should utls library update to latest version?

**Comment by 2dust** [comment]
Xray-core needs to be supported first

**Comment by dill-shower** [comment]
https://github.com/refraction-networking/utls/releases/tag/v1.5.0

This should be already supported. Xray use utls 1.6.3
