### ISSUE TITLE
谷歌版虎牙app直播会在切换节点，或者关闭开启vpn的时候，直播会中断，要重新加载，还会加载失败

### ISSUE THREAD

**Issue by wzgrx** [2dust/v2rayNG#2801]
软件版本：最新1.8.14
设置：默认设置，开启分应用代理（不选虎牙app） 启用本地dns 预定义规则（绕过局和大陆）其他都是默认
问题：虎牙app直播会在切换节点，或者关闭开启vpn的时候，直播会中断，要重新加载，还会加载失败，其他app直播都是正常的，分应用没有勾选，切换节点不会中断，就虎牙app会，很奇怪，求打佬解惑，非常感谢。

国内版虎牙app，相同设置，不会出现上面的问题

日志：--------- beginning of main
01-29 18:17:17.574 I/GoLog   ( 7388): Using Prepared: 13.57.30.215
01-29 18:17:19.139 I/GoLog   ( 7388): tcp:127.0.0.1:37812 accepted tcp:149.154.175.56:443 [socks -> proxy]
01-29 18:17:19.139 I/GoLog   ( 7388): tcp:127.0.0.1:37824 accepted tcp:149.154.175.56:443 [socks -> proxy]
01-29 18:17:19.306 I/GoLog   ( 7388): Using Prepared: 13.57.30.215
01-29 18:17:19.315 I/GoLog   ( 7388): Not Using Prepared: tcp,ir-sdk.dun.163.com:443
01-29 18:17:19.315 I/GoLog   ( 7388): tcp:127.0.0.1:37832 accepted tcp:60.191.81.66:443 [socks -> direct]
01-29 18:17:19.316 I/GoLog   ( 7388): Using Prepared: 13.57.30.215
01-29 18:17:19.832 I/GoLog   ( 7388): Not Using Prepared: tcp,miwifi.com:443
01-29 18:17:19.833 I/GoLog   ( 7388): tcp:127.0.0.1:37842 accepted tcp:118.26.252.28:443 [socks -> direct]
01-29 18:17:19.982 I/GoLog   ( 7388): DNS accepted udp:1.1.1.1:53 [xray.system.eae4917f-8772-4edf-9246-c3a608eb53d9 -> proxy]
01-29 18:17:20.157 I/GoLog   ( 7388): Using Prepared: 13.57.30.215
01-29 18:17:20.335 I/GoLog   ( 7388): tcp:127.0.0.1:37858 accepted tcp:[2a03:2880:f10c:83:face:b00c:0:25de]:443 [socks >> proxy]
01-29 18:17:20.500 I/GoLog   ( 7388): Using Prepared: 13.57.30.215
01-29 18:17:21.353 I/GoLog   ( 7388): tcp:127.0.0.1:45024 accepted tcp:91.108.56.149:443 [socks -> proxy]
01-29 18:17:21.515 I/GoLog   ( 7388): Using Prepared: 13.57.30.215
01-29 18:17:21.541 I/GoLog   ( 7388): Not Using Prepared: tcp,live-cover.msstatic.com:80
01-29 18:17:21.541 I/GoLog   ( 7388): tcp:127.0.0.1:45030 accepted tcp:[240e:932:c001:3:3::3ef]:80 [socks -> direct]
01-29 18:17:21.644 I/GoLog   ( 7388): Not Using Prepared: tcp,live-cover.msstatic.com:80
01-29 18:17:21.645 I/GoLog   ( 7388): tcp:127.0.0.1:45042 accepted tcp:[240e:932:c001:3:3::3ef]:80 [socks -> direct]
01-29 18:17:21.645 I/GoLog   ( 7388): Not Using Prepared: tcp,tx-live-cover.msstatic.com:443
01-29 18:17:21.645 I/GoLog   ( 7388): tcp:127.0.0.1:45058 accepted tcp:[240e:bf:b800:2811:77::9]:443 [socks -> direct]
01-29 18:17:21.649 I/GoLog   ( 7388): Not Using Prepared: tcp,tx-live-cover.msstatic.com:443
01-29 18:17:21.649 I/GoLog   ( 7388): tcp:127.0.0.1:45068 accepted tcp:[240e:bf:b800:2811:77::9]:443 [socks -> direct]
01-29 18:17:22.482 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:22.483 I/GoLog   ( 7388): tcp:127.0.0.1:45070 accepted tcp:118.180.32.172:80 [socks -> direct]
01-29 18:17:22.500 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 155 Err: connection refused
01-29 18:17:22.500 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:22.511 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 155 Err: connection refused
01-29 18:17:22.534 I/GoLog   ( 7388): Not Using Prepared: udp,113.105.147.29:1464
01-29 18:17:22.534 I/GoLog   ( 7388): udp:127.0.0.1:39644 accepted udp:113.105.147.29:1464 [socks -> direct]
01-29 18:17:22.576 I/GoLog   ( 7388): Not Using Prepared: tcp,113.105.147.29:467
01-29 18:17:22.576 I/GoLog   ( 7388): tcp:127.0.0.1:45072 accepted tcp:113.105.147.29:467 [socks -> direct]
01-29 18:17:22.611 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:22.613 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 159 Err: connection refused
01-29 18:17:22.813 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:22.817 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 157 Err: connection refused
01-29 18:17:23.118 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:23.133 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 157 Err: connection refused
01-29 18:17:23.741 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:23.741 I/GoLog   ( 7388): tcp:127.0.0.1:45082 accepted tcp:118.180.32.173:80 [socks -> direct]
01-29 18:17:23.748 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 155 Err: connection refused
01-29 18:17:23.748 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:23.754 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 155 Err: connection refused
01-29 18:17:23.855 I/GoLog   ( 7388): Not Using Prepared: tcp,hw.p2p.huya.com:80
01-29 18:17:23.863 I/GoLog   ( 7388): fdConn unix.Connect err, Close Fd: 144 Err: connection refused
01-29 18:17:23.869 I/GoLog   ( 7388): Not Using Prepared: udp,113.105.147.29:2464
01-29 18:17:23.869 I/GoLog   ( 7388): udp:127.0.0.1:45038 accepted udp:113.105.147.29:2464 [socks -> direct]
01-29 18:17:23.892 I/GoLog   ( 7388): Not U

**Comment by King-Of-Knights** [comment]
你用V2rayNG开了VPN，相当于在手机上建立了一个TUN网卡，会接管手机绝大部分网络流量，只不过V2rayNG通过分流规则，对国内的域名和IP的请求不会发到你的代理服务器上。你关了V2rayNG，就和WiFi切换到流量一样，中间肯定会卡一下
