### ISSUE TITLE
可以加个开机启动吗

### ISSUE THREAD

**Issue by xiaoxinwangluo** [2dust/v2rayNG#281]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by xiaoxinwangluo** [comment]
？

**Comment by wjfyxk1231** [comment]
你要开机启动干嘛？这是手机版的呀，难道您现在的智能手机还要经常开机关机吗？😂😂😂

**Comment by 2dust** [comment]
不能，请用tasker
