### ISSUE TITLE
感觉分流有点怪

### ISSUE THREAD

**Issue by IntangibleW** [2dust/v2rayNG#281]
从Google Play上下的1.1.14，域名策略IPIfNonMatch，自定义规则使用的默认，预定义规则绕过局域网和大陆地址。使用过程中发现无论走不走代理，个别网站及应用需要很长时间才能打开。需要添加自定义规则才能解决 。

**Comment by xuexiaokang** [comment]
这个地方一直就有BUG，不管用什么规则，大部分都走代理

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/38
