### ISSUE TITLE
设置后自动重连以使设置生效

### ISSUE THREAD

**Issue by MoonASS** [2dust/v2rayNG#282]
提个小建议，切换分应用开关/添加应用和切换路由/自定义路由，返回主界面后可不可以自动重启vpn（自动断开重连）以使设置（分应用切换/添加的应用、路由切换/自定义路由）生效。目前的版本，返回后V按钮有在切换（断开连接的动作），但无实际操作，要手动断开重连才生效。不知看到的动作是刷新状态，还是动作未生效。

### 预期行为
描述你认为应该发生什么
设置
       1. 路由项（切换路由模式/自定义路由）
       2. 分应用项（分应用开关/添加减去应用/及绕行按钮）
       3. 需要重新连接才生效的其他设置
返回主界面后，自动重新连接，以使这些需要重新连接才生效的设置生效，省去手动来回操作。
类同win端V2rayN设置一项就自动重新连接以使生效，
各vpn也有类似设置，设置返回后自动重新连接。

### 实际行为
描述实际发生了什么
从设置返回后，发现，按钮状态有在刷新，由未连变连接，只是在刷新图案而无实际操作（断开重连），不知是是已有该动作还是仅是在刷新图案状态。

### 复现方法
1.进入设置后返回，有发现图案在变化
2.设置一项或多项返回，也有发现图案在变
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
vivo 安卓8.0
无电脑，提取不了detail,
若软件有设置此项（自动重新连接生效设置），
而仅是我个人手机或系统的原因没有复现此功能，
请忽略此issue。
谢谢

**Comment by 2dust** [comment]
请手动重启下服务
