### ISSUE TITLE
WIN10系统下android-studio是否可以编译？？

### ISSUE THREAD

**Issue by make9** [2dust/v2rayNG#282]
WIN10系统下android-studio是否可以编译？？

**Comment by yuhan6665** [comment]
可以，把signingconfigs改了或者删了即可。遇到什么问题？

**Comment by messi06** [comment]
> WIN10系统下android-studio是否可以编译？？

you will need to create a  signing key , let me know if you still need

**Comment by make9** [comment]
感谢大神回答，晚一些有时间我测试一下。。

**Comment by make9** [comment]
> 可以，把signingconfigs改成或者删除了即可。遇到什么问题？



> > WIN10系统下android-studio是否可以编译？？
> 
> 您将需要创建一个签名密钥，如果您仍然需要，请告诉我

感谢大神回答，晚一些有时间我测试一下。
