### ISSUE TITLE
关于鸿蒙4.0无法使用v2rayNG

### ISSUE THREAD

**Issue by alexiaocl** [2dust/v2rayNG#2826]
今早还能正常使用，到了晚上突然发现无法启动节点了，卸载重新换了几个版本也无法配置成功。

pc端证明我的梯子是正常可用的。

各位大佬有知道是怎么一回事的吗？

用clash也配置失败，错误提示为
（Get "https://api.dingyueapi.win/api/v1/client/subscribe?token=0000000000:readtcp 000000000000:read:connection reset bypeer）

**Comment by AelepantB** [comment]
我也是，节点用PC的v2rayN能连上，手机却连不上

**Comment by jsjtwty** [comment]
Same issue
