### ISSUE TITLE
UUID用户ID验证失败

### ISSUE THREAD

**Issue by ttc0419** [2dust/v2rayNG#2843]
### 预期行为
UUID验证通过

### 实际行为
UUID无法通过验证，大小写都不行，但是纯文本密码可以。

### 复现方法
1. 使用UUID为用户ID
2. 测试连接
3. I/o closed on write

### 日志信息
N/A

### 环境信息
v2rayNG 1.8.15

**Comment by 2dust** [comment]
配置呢

**Comment by ttc0419** [comment]
卸载之后重装好像又好了。
