### ISSUE TITLE
Add a way for assigning subscription's remark when importing from clipboard/QRCode

### ISSUE THREAD

**Issue by a-pav** [2dust/v2rayNG#2845]
Right now everything imported from clipboard is assigned [`"import sub"`](https://github.com/2dust/v2rayNG/blob/09fc20794e73ebf4753caf213fba6d9c80315c12/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/MmkvManager.kt#L125) as its remark.

I have a long list of subscription that I share with my family. It's very hard and time consuming to go through them all and change the remarks manually. 
Please consider adding a way for defining the remark name before importing.

The easiest way seems to be adding a custom parameter name like `?remark-name=` to subscription url.
```
https://example.com/main/subs/vmess/list01?remark-name=example-vmess-list01
```
or it can be done like
```shell
REMARK_NAME SUB_URL # please note the white space
example-vmess-list01 https://example.com/main/subs/vmess/list01
```

**Comment by 2dust** [comment]
https://example.com/main/subs/vmess/list01#example-vmess-list01

**Comment by a-pav** [comment]
Thank you. I just tested and it works great.
