### ISSUE TITLE
Save/Load APP settings

### ISSUE THREAD

**Issue by EarlVadim** [2dust/v2rayNG#2847]
Hello.
Please support the request to the developers to add the ability to save/restore all application settings (not keys). 
A lot of people don't want to figure out how to properly configure an application. And the default settings are far from ideal. And manuals in pictures scare many people. 
You would make the application closer to beginners if you could import by app pre-configs. 
they differ for different countries, and even for different Internet providers.

I'm about it:

![изображение](https://github.com/2dust/v2rayNG/assets/26113954/a929f0ef-16fb-42ef-93dc-3283aab176de)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.20
