### ISSUE TITLE
feat request: 希望添加Shadowsocks的混淆以及SIP002的支持

### ISSUE THREAD

**Issue by Utaea** [2dust/v2rayNG#2849]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
v2rayN目前已支持Shadowsocks+v2ray-plugin混淆（即transport部分可以设为tcp+http混淆/ws/quic），从技术上来说v2rayNG也完全可以支持Shadowsocks+混淆，希望可以添加这一支持

### 实际行为
目前v2rayNG的Shadowsocks协议仅支持传统的原生Shadowsocks，即便在订阅链接中加入SIP002包含混淆参数的订阅，v2rayNG在解析时依旧会将混淆参数舍去

### 复现方法
无

### 日志信息
无

**Comment by qingminghuang** [comment]
+1
