### ISSUE TITLE
Connection URL Test Option

### ISSUE THREAD

**Issue by DrAmirB** [2dust/v2rayNG#2850]
Hi.
Please add an option for connection test URL, so we can edit it.
The current URL does not work properly in Iran

**Comment by Arslnmhi** [comment]
> Hi.
> Please add an option for connection test URL, so we can edit it.
> The current URL does not work properly in Iran

> yes .im from this country.pls help

**Comment by CipherVasat** [comment]
good idea if we can edit the test url and set it for ourselves

**Comment by APT-ZERO** [comment]
Bruh all generate_204 urls are same, and it's going to get done using the proxy to check connectivity, what you mean by NOT WORK IN IRAN!! even in Iran servers all generate_204 urls are OK

**Comment by X-Oracle** [comment]
> Hi.
> Please add an option for connection test URL, so we can edit it.
> The current URL does not work properly in Iran

The test is a http test to google 204 page.
If your server can't connect to it means it is blocked by google or your configurations blocks it.

I agree with you tho but I don't like it's downside. Having a standard url for test makes it easier to benchmark configs across devices.
