### ISSUE TITLE
v2rayNG配置文件启动失败

### ISSUE THREAD

**Issue by Ro-ger8** [2dust/v2rayNG#2854]
正常情况下直接点击右下角的对勾符号就可以启动服务，然后正常使用，
但是今天使用时发现点击对勾符号，每个配置文件都启动失败
![Screenshot_20240219_111057_com v2ray ang](https://github.com/2dust/v2rayNG/assets/160450349/109082ec-c8a4-43af-a9d3-d72877c62045)

**Comment by rem3233** [comment]
how to slave it?
