### ISSUE TITLE
logcat中ip信息被隐藏

### ISSUE THREAD

**Issue by oliverYoung2001** [2dust/v2rayNG#2858]
### 预期行为
logcat中应当可以看到ip信息，但被隐藏为***

### 实际行为
logcat中应当可以看到ip信息，但被隐藏为***

### 日志信息
![3561708401696_ pic](https://github.com/2dust/v2rayNG/assets/55433595/390a98be-9271-41bf-97cc-7216d4bd9b7c)

**Comment by 2dust** [comment]
这是手机系统的问题，国产部分手机为了隐私原因，默认不显示手机号，ip等信息
你可以google下就明白了
