### ISSUE TITLE
link open app and add config

### ISSUE THREAD

**Issue by saeidpour80** [2dust/v2rayNG#2859]
Hello

I use this link for add config to app :
v2rayng://install-config/?url=vless://53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net:46740?type=tcp&path=%2F&headerType=http&security=none#test-z8c813dh

But it only enters up to this part :
v2rayng://install-config/?url=vless://53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net:46740?type=tcp

**Comment by hossein-mohseni** [comment]
> Hello
> 
> I use this link for add config to app : v2rayng://install-config/?url=vless://[53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net](mailto:53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net):46740?type=tcp&path=%2F&headerType=http&security=none#test-z8c813dh
> 
> But it only enters up to this part : v2rayng://install-config/?url=vless://[53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net](mailto:53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net):46740?type=tcp

try URL encode the vless part

**Comment by X-Oracle** [comment]
> v2rayng://install-config/?url=vless://53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net:46740?type=tcp

The problem is it will separate it like this :

- url=vless://53e2f779-899c-4305-9e46-f8e7c7f42d96@sne-01.sl-network.net:46740

- ?type=tcp

You need to some how make it a single line without `?` or use some thing like `" "` to put it there.

Using base64 is an option too if v2rayng supports it.
