### ISSUE TITLE
(功能请求）请求外置配置文件与geoip.dat与geosite.dat

### ISSUE THREAD

**Issue by txyyh** [2dust/v2rayNG#286]
求外置到内部存储目录下的Android/data中，方便编辑
外置以上文件并不会对普通用户造成任何困惑（因为gui并没变）但会极大地方便具有一定能力的用户配置规则。
感谢

**Comment by 2dust** [comment]
暂时无法实现

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/pull/662
