### ISSUE TITLE
[ FR ] (fragmentation) enable/disable for individual config 

### ISSUE THREAD

**Issue by X-Oracle** [2dust/v2rayNG#2860]
Fragmentation is a new good feature which @vfarid  developed it .

It is a good point to configured it's settings in settings section but having them globally enable is not appropriate. as not all configs need or benefit from having it enable.

So my suggestion is to have it behave like `allow insecure` option.
What I meant is have it preferable and can be disabled/enable in each config settings.

Good luck.

**Comment by APT-ZERO** [comment]
that global fragment option was a bad idea!

**Comment by AliM1988** [comment]
Also, I suggest add the ability to control fragment and mux settings via URI config. So the configs can be used in subscription as well. 
Here is a sample that supported by iOS client , Streisand:
`vless://uuid@address:443?path=/&security=tls&encryption=none&alpn=http/1.1&host=myhost&fp=chrome&type=ws&sni=mysni&fragment=100-200,10-15,tlshello&mux=8#test`

**Comment by X-Oracle** [comment]
> Also, I suggest add the ability to control fragment and mux settings via URI config. So the configs can be used in subscription as well. 

As of now uris doesn't have permission to changing v2ray settings.

With my suggestion it can be possible to pass `fr=true ` to ensure fragmentation if the option implanted.

**Comment by AliM1988** [comment]
My 

> > Also, I suggest add the ability to control fragment and mux settings via URI config. So the configs can be used in subscription as well.
> 
> As of now uris doesn't have permission to changing v2ray settings.
> 
> With my suggestion it can be possible to pass `fr=true ` to ensure fragmentation if the option implanted.

My suggestion is about changing current config's settings not main settings of app.

**Comment by X-Oracle** [comment]
> My suggestion is about changing current config's settings not main settings of app.

Well duh.
Right now Fragment settings are in v2ray settings.

@2dust already rejected the pr related to having it in config settings. So talking about it is pointless in my opinion.

When we can't set fragment settings, at least we can send a config uri with the ability to set fragmentation on for the related config.

**Comment by X-Oracle** [comment]
@2dust 
I'm confused. So is it a `not planned` or `done` or `in mind`?
