### ISSUE TITLE
希望在下一个版本中增加用DOH方式来请求域名解析的设置选项

### ISSUE THREAD

**Issue by ckula9** [2dust/v2rayNG#2864]
就是在 VPN DNS那一栏设置的选项能支持DOH的方式, 

因为我发现如果勾了 启用本地DNS 来直接返回fake ip后会导致有些程序的功能失败,

比如 wifi calling 就会失败(它会直接就假IP198.18.x.x连接wifi calling服务器的500和4500端口), 

VPN DNS那一栏直接填1.1.1.1后wifi calling功能恢复正常, 
但是直接填1.1.1.1会导致电信运营商(电信联通移动), 知道我在访问哪些网站(解析了哪些域名),

希望在下一个版本中增加用DOH方式来请求域名解析的设置选项, 影响导致速度慢点也没关系

**Comment by ckula9** [comment]
测试用的是安卓手机, v2rayNG开启后, 手机的DNS请求确实会通过v2rayNG,

但是手机系统有些内置的程序会无视手机上设置的一切代理, 比如 wifi calling这个程序, 他就会直接走wifi宽带连接(DNS请求会通过v2rayng), 无视里手机上设置的一切代理, 所以勾选了fake ip后, 导致wifi calling失败

**Comment by CharlesLocke** [comment]
本地DNS你设置境外的也没用啊，不如直接用：
https://223.5.5.5/dns-query
或者
h3://223.5.5.5/dns-query
远程的你填写：
https://1.1.1.1/dns-query
https://8.8.8.8/dns-query
https://dns.google/dns-query
任何一个就行。

**Comment by ckula9** [comment]
> 本地DNS你设置境外的也没用啊，不如直接用： https://223.5.5.5/dns-query 或者 h3://223.5.5.5/dns-query 远程的你填写： https://1.1.1.1/dns-query https://8.8.8.8/dns-query https://dns.google/dns-query 任何一个就行。



VPN DNS那一栏可以直接填https地址?  DOH还要专门的请求域名解析类型等等参数啊, 它会自动识别支持?


已测试, 不支持直接填https://1.1.1.1/dns-query, 全部解析失败

**Comment by 2dust** [comment]
VPN DNS是不支持的，这个是tun接口不支持
远程DNS是支持的，这个是core的行为

**Comment by v4ray** [comment]
@ckula9 你好。我也碰到类似的问题：打开v2rayNG的话境外手机卡的wifi calling就失效了，关上VPN就能wifi calling。可能跟wifi calling的DNS走了代理有关？请问有什么解决方案吗？谢谢
