### ISSUE TITLE
启动绕过大陆及局域网后，baidu搜索ip显示出vps的ip

### ISSUE THREAD

**Issue by a2232189** [2dust/v2rayNG#287]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
启动绕过大陆及局域网后，baidu搜索ip不显示出vps的ip，而是显示我手机的ip

### 实际行为
启动绕过大陆及局域网后，baidu搜索ip显示出vps的ip

**Comment by a2232189** [comment]
自定义路由没有设置过，为空。

**Comment by a2232189** [comment]
published了这个issue之后，为了测试，我在自定义路由的三个页面中均点击了“设置默认路由规则”，并在每个页面点了“√”来保存。我期望这样也许能够解决此问题，然而百度搜ip仍然出现vps的ip

**Comment by 2dust** [comment]
版本多少
https://github.com/2dust/v2rayNG/releases/tag/0.6.18.2

**Comment by a2232189** [comment]
0.16.17
I will install the latest and feedback later.

**Comment by a2232189** [comment]
After installing https://github.com/2dust/v2rayNG/releases/tag/0.6.18.2, the problem is still not solved.

**Comment by a2232189** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.18.2安装之后问题依旧

**Comment by 2dust** [comment]
你开启本地dns测试下

**Comment by a2232189** [comment]
tested, no luck.

2dust <notifications@github.com> 于 2019年3月28日周四 上午11:13写道：

**Comment by boypt** [comment]
没能重现，0.6.18.2。

另外一个较好的测试方法是打开 http://ip111.cn ，可同时显示不同路由的出口IP。

关键配置：
- 域名策略：IPIfNonMatch
- 路由模式： 绕过局域网及大陆地址
- 自定义路由：全空白

![photo_2019-04-07_13-51-49](https://user-images.githubusercontent.com/1033514/55679338-51651680-593c-11e9-922e-268c800ee3e3.jpg)

![photo_2019-04-07_13-51-43](https://user-images.githubusercontent.com/1033514/55679337-4f9b5300-593c-11e9-8081-70cf5df5ac4d.jpg)

**Comment by 2dust** [comment]
本人也测试了,ip正常
