### ISSUE TITLE
手机端提示connection closed by peer

### ISSUE THREAD

**Issue by asdfcjf** [2dust/v2rayNG#289]
电脑端是正常的 手机端最新版软件 一直提示connection closed by peer是什么原因

**Comment by windias** [comment]
同样问题，旧版本无效

**Comment by liaong** [comment]
同样的问题，在yota3+上有这个情况，安卓8.1，一样的配置在pc端没问题，小米6和我其他手机也没问题

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/296
