### ISSUE TITLE
MultiConfig Json Import Bug (Early Data Failed)

### ISSUE THREAD

**Issue by APT-ZERO** [2dust/v2rayNG#2894]
Hello there
In Xray-core's Websocket configs we set `?ed=2048` to end of ws path to enable Early Data ( https://github.com/XTLS/Xray-core/pull/375 )
But when i add multi custom config from remote, v2rayNG 1.8.17 url-encodes the Path and early data will not work
Here is proof, add this link as sub and try :
`https://pastebin.com/raw/EAHGeNSu`

![image](https://github.com/2dust/v2rayNG/assets/41063376/05aec2fd-bdbb-4001-b3b2-fb3a03482180)

**Comment by 2dust** [comment]
Please solve the custom configuration yourself

**Comment by APT-ZERO** [comment]
custom config have no problem, check it yourself in browser then import and check config from v2rayNG @2dust 

Config in browser :
![image](https://github.com/2dust/v2rayNG/assets/41063376/1f2ba23f-45cf-41ba-a867-bafae6d4d89f)
When imported from remote to v2rayNG :
![image](https://github.com/2dust/v2rayNG/assets/41063376/05aec2fd-bdbb-4001-b3b2-fb3a03482180)

**Comment by APT-ZERO** [comment]
@vfarid is it just a visual bug?
