### ISSUE TITLE
请问libv2ray.aar怎么获得？编译时弹出Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'libv2ray.aar'

### ISSUE THREAD

**Issue by Arcobaleno0** [2dust/v2rayNG#29]
详细报错日志：
Unable to resolve dependency for ':app@debug/compileClasspath': Failed to transform file 'libv2ray.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Failed to transform file 'libv2ray.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
 > java.io.FileNotFoundException: /home/***/AndroidStudioProjects/v2rayNG/V2rayNG/libv2ray/libv2ray.aar (没有那个文件或目录)
    > /home/***/AndroidStudioProjects/v2rayNG/V2rayNG/libv2ray/libv2ray.aar (没有那个文件或目录)

**Comment by xiaokangwang** [comment]
你可以到这里下载 https://github.com/xiaokangwang/AndroidLibV2ray/releases

**Comment by 2dust** [comment]
从上面下载

**Comment by yueyihui** [comment]
2dust/AndroidLibV2rayLite is better
