### ISSUE TITLE
[BUG]Android 9.0 运行闪退

### ISSUE THREAD

**Issue by 2220209876** [2dust/v2rayNG#290]
第三方类原生ROM，启动服务器时就会闪退，打开软件不会闪退，好几个版本都出现过这种情况
Google play 最新版（测试版也试过）
--------- beginning of crash
--------- beginning of main
03-30 11:23:23.468 I/GoLog   (20897): loading v2ray config
03-30 11:23:23.539 E/GoLog   (20897): panic: runtime error: invalid memory address or nil pointer dereference

**Comment by boypt** [comment]
估计是输出的JSON给core时候的解析出问题了，那个地方的错误处理不完善，后续版本改进

**Comment by 2dust** [comment]
请用最新版测试再反馈

**Comment by 2220209876** [comment]
> 请用最新版测试再反馈

最新测试版正常使用了（期间已换ROM）
