### ISSUE TITLE
能不能把默认设置改一下

### ISSUE THREAD

**Issue by bingotl** [2dust/v2rayNG#2906]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

默认是全局代理，没啥问题，
但是如果想开绕过大陆，
那还得把域名策略改为asis，再把1.1.1.1改为国内dns（或者开启本地dns+虚拟dns），
很多机场都是推荐用你这个客户端的，但是对机场小白真的很不友好，每天被客户问烦了。
求求改一下这些默认设置吧

**Comment by 2dust** [comment]
您可以PR过来

**Comment by bingotl** [comment]
1、把自定义规则改为：绕过局域网及大陆后代理，作为鸡场主用了这么客户端，从来没有一个客户端是默认开全局代理的
2、如果域名策略改为：asis
3、VPN DNS改为223.5.5.5国内的，否则会出现TLS handshake timeout，连微信国内app都用不了。这个平时分地区偶尔会出现，最近开会DNS污染出现大面积问题，被问烦了。而且这个问题已经存在一年了，希望默认配置符合大多数国人的使用习惯https://github.com/2dust/v2rayNG/issues/2044

以下是近几天的客户咨询，
https://pic.sl.al/gdrive/pic/2024-03-12/65efc53983d89.png
https://pic.sl.al/gdrive/pic/2024-03-12/65efc53899c4e.png
https://pic.sl.al/gdrive/pic/2024-03-12/65efc537d5916.png
https://pic.sl.al/gdrive/pic/2024-03-12/65efc5387bfb8.png
https://pic.sl.al/gdrive/pic/2024-03-12/65efc538888ce.png

**Comment by bingotl** [comment]
笑死，刚刚看https://github.com/2dust/v2rayNG/issues/2044 这个issues，也是去年2会期间被污染然后大面积出现问题

**Comment by wangwang-code** [comment]
请 https://github.com/wangwang-code/v2rayNG/releases/tag/99999
