### ISSUE TITLE
希望支持Hysteria2协议

### ISSUE THREAD

**Issue by wr360adfgsd** [2dust/v2rayNG#2907]
### 实际行为
无法更新拥有Hysteria2协议的节点，导致节点缺失

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
v2rayNG v.1.8.17

**Comment by dbguo** [comment]
附议~

**Comment by 2dust** [comment]
需要xray-core支持

**Comment by Elda1994** [comment]
希望增加支持hysteria2协议

**Comment by cooler1987** [comment]
不支HY2和TUIC是非常遗憾的，所以不得不放弃此软，使用nekobox。
但nekobox（包括其它变体）的稳定性又不如此软件。
左也不是，右也不是，头疼。
