### ISSUE TITLE
Conversion of Integers to Decimals in JSON Causing Error in xray Startup

### ISSUE THREAD

**Issue by AC-Lover** [2dust/v2rayNG#2912]
درود
بعضی از اعداد صحیح در جیسون تبدیل به اعداد اعشار می شوند و این باعث خطا و استارت نشدن xray میشه لطفا بررسی کنید
نمونه :
"fakedns":[
      {
         "ipPool":"198.18.0.0/15",
         "poolSize":10000
      }
   ]

این مورد تبدیل میشه به :

"fakedns":[
      {
         "ipPool":"198.18.0.0/15",
         "poolSize":10000.0
      }
   ]

----------------------

Hello
 Some integers in json are converted to decimal numbers, and this causes errors and xray not starting. Please check.
 Sample :
 "fakedns":[
       {
          "ipPool":"198.18.0.0/15",
          "poolSize": 10000
       }
    ]

 This becomes:

 "fakedns":[
       {
          "ipPool":"198.18.0.0/15",
          "poolSize": 10000.0
       }
    ]

@vfarid

**Comment by MrMalekfar** [comment]
#2886

**Comment by AC-Lover** [comment]
> #2886
Oh, thank you
