### ISSUE TITLE
小米Hyperos代理无法使用

### ISSUE THREAD

**Issue by yaopeng1** [2dust/v2rayNG#2914]
`电脑用的也是v2rayN，电脑正常使用，但是手机无法连接外网，两个设备用的机场链接都一致。`

### 预期行为
我认为手机端应该可以正常上网。

### 实际行为
手机无法上网，并且测试所有真连接，结果都是-1ms

### 复现方法
1.订阅连接转换为v2ray专用，故障依旧；
2.换用另一家的链接，故障依旧。

### 日志信息
<details>
PS D:\ADB\platform-tools_r35.0.0-windows\platform-tools> adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main
* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
--------- beginning of main
03-09 09:26:40.506  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:40.529  2363  4434 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:40.567  2363  2668 I GoLog   : Not Using Prepared: tcp,123.125.102.184:443
03-09 09:26:40.741  2363  2668 I GoLog   : Not Using Prepared: tcp,miui-xiaomishop.retail.mi.com:443
03-09 09:26:40.743  2363  2466 I GoLog   : Not Using Prepared: tcp,miui-xiaomishop.retail.mi.com:443
03-09 09:26:40.743  2363  2466 I GoLog   : Not Using Prepared: tcp,port.sec.miui.com:443
03-09 09:26:40.747  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:40.748  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:41.450  2363  2466 I GoLog   : Not Using Prepared: tcp,157.148.47.172:8002
03-09 09:26:43.736  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:44.013  2363  2466 I GoLog   : Not Using Prepared: tcp,cdn.exp.xiaomi.com:443
03-09 09:26:44.016  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:44.031  2363  2763 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:44.210  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:44.213  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:44.417  2363  2668 I GoLog   : Not Using Prepared: tcp,config-p2p-other.vcloud.ks-live.com:443
03-09 09:26:44.419  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:45.079  2363  3637 I GoLog   : fdConn unix.Connect err, Close Fd: 143 Err: no route to host
03-09 09:26:45.179  2363  2466 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:26:46.334  2363  3660 I GoLog   : Not Using Prepared: tcp,cdn.exp.xiaomi.com:443
03-09 09:26:49.741  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:26:55.271  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:00.800  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:09.361  2363  3708 I GoLog   : fdConn unix.Connect err, Close Fd: 138 Err: connection timed out
03-09 09:27:09.362  2363  3708 I GoLog   : fdConn unix.Connect err, Close Fd: 136 Err: connection timed out
03-09 09:27:09.362  2363  3660 I GoLog   : fdConn unix.Connect err, Close Fd: 141 Err: connection timed out
03-09 09:27:09.363  2363  3708 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:27:09.363  2363  3660 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:27:09.464  2363  3637 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:27:10.329  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:11.246  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:12.059  2363  3637 I GoLog   : Not Using Prepared: tcp,tracking.miui.com:443
03-09 09:27:12.618  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:14.218  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:15.632  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:15.721  2363  3738 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:16.529  2363  2452 I GoLog   : fdConn unix.Connect err, Close Fd: 132 Err: connection timed out
03-09 09:27:16.730  2363  3738 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:27:17.084  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:18.618  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:20.052  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:21.182  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:21.453  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:22.827  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:23.056  2363  2363 D com.v2ray.ang: SCREEN_OFF, stop querying stats
03-09 09:27:24.250  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:25.791  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:26.556  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:27.322  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:28.549  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:32.138  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:37.668  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:40.847  2363  3660 I GoLog   : fdConn unix.Connect err, Close Fd: 111 Err: connection timed out
03-09 09:27:40.848  2363  3660 I GoLog   : fdConn unix.Connect err, Close Fd: 113 Err: connection timed out
03-09 09:27:40.849  2363  2668 I GoLog   : fdConn unix.Connect err, Close Fd: 109 Err: connection timed out
03-09 09:27:40.950  2363  2668 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:27:40.951  2363  2466 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:27:41.050  2363  3708 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:27:43.197  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:48.273  2363  3660 I GoLog   : fdConn unix.Connect err, Close Fd: 122 Err: connection timed out
03-09 09:27:48.575  2363  3660 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:27:48.613  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:27:54.155  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:07.668  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:12.336  2363  2668 I GoLog   : fdConn unix.Connect err, Close Fd: 109 Err: connection timed out
03-09 09:28:12.337  2363  2466 I GoLog   : fdConn unix.Connect err, Close Fd: 111 Err: connection timed out
03-09 09:28:12.538  2363  3738 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:28:12.539  2363  2668 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:28:12.591  2363  3708 I GoLog   : fdConn unix.Connect err, Close Fd: 110 Err: connection timed out
03-09 09:28:12.688  2363  2668 I GoLog   : fdConn unix.Connect err, Close Fd: 113 Err: no route to host
03-09 09:28:12.893  2363  2466 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:28:12.990  2363  3708 I GoLog   : Not Using Prepared: tcp,203.100.92.99:443
03-09 09:28:13.199  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:18.729  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:20.016  2363  3660 I GoLog   : fdConn unix.Connect err, Close Fd: 116 Err: connection timed out
03-09 09:28:25.894  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:26.119  2363  2363 D com.v2ray.ang: SCREEN_ON, start querying stats
03-09 09:28:26.369  2363  3660 I GoLog   : Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-09 09:28:28.233  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:29.254  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:29.448  2363  2466 I GoLog   : Not Using Prepared: tcp,mmbiz.qpic.cn:443
03-09 09:28:29.452  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:29.893  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:29.902  2363  3660 I GoLog   : Not Using Prepared: udp,223.5.5.5:53
03-09 09:28:30.301  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:30.845  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:30.908  2363  3660 I GoLog   : Not Using Prepared: tcp,157.148.47.172:8002
03-09 09:28:31.245  2363  2466 I GoLog   : Not Using Prepared: tcp,extshort.weixin.qq.com:80
03-09 09:28:31.322  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:32.345  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:32.757  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:33.770  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:34.193  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:35.215  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:35.626  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:36.386  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:36.467  2363  2363 D com.v2ray.ang: SCREEN_OFF, stop querying stats
03-09 09:28:36.648  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:36.653  2363  2466 I GoLog   : Not Using Prepared: tcp,tracking.miui.com:443
03-09 09:28:36.657  2363  2668 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:37.028  2363  2463 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:38.081  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:38.490  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:39.460  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:39.926  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:40.946  2363  2466 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:41.361  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:41.639  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:44.081  2363  2469 I GoLog   : fdConn unix.Connect err, Close Fd: 109 Err: connection timed out
03-09 09:28:44.335  2363  3708 I GoLog   : fdConn unix.Connect err, Close Fd: 114 Err: connection timed out
03-09 09:28:44.336  2363  2452 I GoLog   : fdConn unix.Connect err, Close Fd: 113 Err: connection timed out
03-09 09:28:44.383  2363  3660 I GoLog   : Not Using Prepared: tcp,203.100.92.99:80
03-09 09:28:48.562  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:48.564  2363  3708 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:48.569  2363  2363 D com.v2ray.ang: SCREEN_ON, start querying stats
03-09 09:28:48.704  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:49.962  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:49.962  2363  3637 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:51.594  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:51.594  2363  3708 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:53.031  2363  3738 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:28:53.032  2363  2452 I GoLog   : Using Prepared: 120.204.94.70
0
03-09 09:33:37.767  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.767  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.767  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.771  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12304
03-09 09:33:37.771  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20050
03-09 09:33:37.771  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12306
03-09 09:33:37.771  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20037
03-09 09:33:37.774  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.776  2363  3738 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20032
03-09 09:33:37.776  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.779  2363  2463 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12000
03-09 09:33:37.781  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.783  2363  3637 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20038
03-09 09:33:37.788  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.789  2363  2463 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12305
03-09 09:33:37.790  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:37.791  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12002
03-09 09:33:37.881 27396 32410 I com.v2ray.ang: This is non sticky GC, maxfree is 33554432 minfree is 8388608
03-09 09:33:38.014  2363  2454 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.115  2363  2763 I GoLog   : fdConn FileConn Close Fd: 143 Err: file file+net Socket: getsockopt: bad file descriptor
03-09 09:33:38.115  2363  2763 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20050
03-09 09:33:38.117  2363  2469 I GoLog   : udp:127.0.0.1:44775 accepted udp:1.1.1.1:53 [socks -> proxy]
03-09 09:33:38.118  2363  3737 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.206  2363  3620 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.206  2363  3622 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.206  2363  3619 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.207  2363  3623 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.207  2363  3621 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.207  2363  3627 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.207  2363  3626 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.208  2363  3624 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.209  2363  3618 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.344  2363  3637 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.345  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.345  2363  3637 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:13116
03-09 09:33:38.347  2363  4434 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12727
03-09 09:33:38.348  2363  2469 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.348  2363  2469 I GoLog   : udp:127.0.0.1:41103 accepted udp:1.1.1.1:53 [socks -> proxy]
03-09 09:33:38.355  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.357  2363  2454 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.358  2363  2463 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12003
03-09 09:33:38.358  2363  2463 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:13182
03-09 09:33:38.362  2363  2463 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.368  2363  3738 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.370  2363  3738 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:13184
03-09 09:33:38.370  2363  2452 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12726
03-09 09:33:38.372  2363  2454 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.373  2363  2454 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20039
03-09 09:33:38.373  2363  2454 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:13132
03-09 09:33:38.374  2363  3738 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.382  2363  3738 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.383  2363  2452 I GoLog   : Not Using Prepared: tcp,bronze-north.ctrips.win:13135
03-09 09:33:38.386  2363  4434 I GoLog   : udp:127.0.0.1:42657 accepted udp:1.1.1.1:53 [socks -> proxy]
03-09 09:33:38.386  2363  2763 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.387  2363  4434 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.388  2363  3738 I GoLog   : udp:127.0.0.1:41651 accepted udp:1.1.1.1:53 [socks -> proxy]
03-09 09:33:38.472  2363  3625 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.529  2363  4434 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.530  2363  3708 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12701
03-09 09:33:38.783  2363  3618 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.783  2363  3625 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.783  2363  3626 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.784  2363  3622 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.784  2363  3619 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.784  2363  3623 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.784  2363  3624 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.785  2363  3620 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.797  2363  3621 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
03-09 09:33:38.912  2363  2668 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.914  2363  3738 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12313
03-09 09:33:38.920  2363  2763 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.920  2363  2763 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.921  2363  3637 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:13137
03-09 09:33:38.921  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12316
03-09 09:33:38.931  2363  2454 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.933  2363  2668 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.934  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.934  2363  2763 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:12700
03-09 09:33:38.934  2363  4434 I GoLog   : Not Using Prepared: tcp,bronze-east.ctrips.win:12011
03-09 09:33:38.935  2363  3737 I GoLog   : Not Using Prepared: tcp,bronze-east.ctrips.win:12012
03-09 09:33:38.936  2363  3737 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.937  2363  2668 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:20047
03-09 09:33:38.937  2363  3737 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.938  2363  2763 I GoLog   : udp:127.0.0.1:38362 accepted udp:1.1.1.1:53 [socks -> proxy]
03-09 09:33:38.940  2363  3660 I GoLog   : Using Prepared: 120.204.94.70
03-09 09:33:38.940  2363  2763 I GoLog   : udp:127.0.0.1:43701 accepted udp:1.1.1.1:53 [socks -> proxy]
03-09 09:33:38.948  2363  3660 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.948  2363  3660 I GoLog   : [Warning] core: Xray 1.8.8 started
03-09 09:33:38.949  2363  3708 I GoLog   : Not Using Prepared: tcp,bronze-south.ctrips.win:13138
03-09 09:33:38.949  2363  3660 I GoLog   : Not Using Prepared: tcp,bronze-east.ctrips.win:12010
03-09 09:33:39.039  2363  3627 D com.v2ray.ang: realPing: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
3219
03-09 09:37:24.176  2363  2668 I GoLog   : Not Using Prepared: tcp,bronze-east.ctrips.win:13218
0
</details>

### 环境信息
安卓手机：RedMi K50 至尊版   系统信息：XiaoMi Hyper OS 1.2.0.ULFCNXM

**Comment by cheungxi** [comment]
同样的现象，但是我都是真连接，但是不能上网

**Comment by yaopeng1** [comment]
> 同样的现象，但是我都是真连接，但是不能上网

和我一个手机型号，一样的系统吗？如果是这样那就不排除是手机的问题了。

**Comment by Sssssoma** [comment]
手机型号红米k50,系统xiaomi hyperos 1.0.2.0ULNCNXM,此问题频繁出现，有时却可以正常代理，版本更新前（miui）代理均可正常使用

**Comment by yaopeng1** [comment]
> 手机型号红米k50,系统xiaomi hyperos 1.0.2.0ULNCNXM,此问题频繁出现，有时却可以正常代理，版本更新前（miui）代理均可正常使用

目前已更新到1.0.3.0 ulncnxm，问题依旧，怀疑是xiaomi的问题。

**Comment by Sssssoma** [comment]
> > 手机型号红米k50,系统xiaomi hyperos 1.0.2.0ULNCNXM,此问题频繁出现，有时却可以正常代理，版本更新前（miui）代理均可正常使用
> 
> 目前已更新到1.0.3.0 ulncnxm，问题依旧，怀疑是xiaomi的问题。

还没有升级，但是最近感觉问题发生频率明显降低，推测是hyperos的问题吧，有点像退回miui了但是很麻烦。。

**Comment by zhyang-dev** [comment]
<s>记得刚买来那个版本可以用，升级一个版本之后就不行了。测试真连接延迟正常。目前发现tele可以用（可能因为通过直接指定本地代理），谷歌全家桶、X全部没流量</s> 重新配置恢复正常

---
更新：
- 20240408 目前是偶尔不能用，有时候又能用，很奇怪

**Comment by yaopeng1** [comment]
> 记得刚买来那个版本可以用，升级一个版本之后就不行了。测试真连接延迟正常。目前发现tele可以用（可能因为通过直接指定本地代理），谷歌全家桶、X全部没流量 重新配置恢复正常
目前看来，只能舍弃V2Ray了。

**Comment by cheungxi** [comment]
> > 记得刚买来那个版本可以用，升级一个版本之后就不行了。测试真连接延迟正常。目前发现tele可以用（可能因为通过直接指定本地代理），谷歌全家桶、X全部没流量 重新配置恢复正常
> 目前看来，只能舍弃V2Ray了。
> 

那用什么？

**Comment by yaopeng1** [comment]
> > > 记得刚买来那个版本可以用，升级一个版本之后就不行了。测试真连接延迟正常。目前发现tele可以用（可能因为通过直接指定本地代理），谷歌全家桶、X全部没流量 重新配置恢复正常
> > 目前看来，只能舍弃V2Ray了。
> > 
> 
> 那用什么？

surf board或者clash mate都行。

**Comment by wujiesixing** [comment]
> > 同样的现象，但是我都是真连接，但是不能上网
> 
> 和我一个手机型号，一样的系统吗？如果是这样那就不排除是手机的问题了。

我也是k50，更新澎湃os之后，原来能用的v2rayNG现在不能用了。

**Comment by zzultc** [comment]
小米变坏了！不见你翻墙了！
关键是小米环境下，还有哪些可以用的？

**Comment by zzyun10** [comment]
型号 RedmiK50U HyperOS  1.0.7.0 ，同样存在不定时断连情况，而且只有重启系统后v2rayng才能使用正常，一天重启次数太多了，不知道逻辑是什么，还是决定刷回MIUI14了

**Comment by lihailin9073** [comment]
> 型号 RedmiK50U HyperOS 1.0.7.0 ，同样存在不定时断连情况，而且只有重启系统后v2rayng才能使用正常，一天重启次数太多了，不知道逻辑是什么，还是决定刷回MIUI14了

兄弟你刷回MIUI14能正常用v2rayNG了吗？我今年5月份开始，发现我的小米13（澎湃OS 2.x.x系统）和小米8（MIUI 12.5）都会频繁断开v2rayNG的链接，只要一打开链接外网的APP（包括在小米自带浏览器上访问 www.facebook.com 这样的国外网站）就会马上被系统断开v2rayNG链接。
我估计你的手机刷回MIUI 14也解决不聊问题，小米的这个断开v2rayNG的问题貌似是针对同一个小米账户的，不受手机系统版本的限制。

**Comment by zzyun10** [comment]
期间升级过HyperOS2，连接也不是很好。还是刷回MIUI14，解锁并且通过ADB删除了不必要的组件。
现在当前版本使用很稳定后期不考虑升级了。
v2rayNG可以做到常驻后台使用，不会无故断连

**Comment by zzyun10** [comment]
> > 型号 RedmiK50U HyperOS 1.0.7.0 ，同样存在不定时断连情况，而且只有重启系统后v2rayng才能使用正常，一天重启次数太多了，不知道逻辑是什么，还是决定刷回MIUI14了
> 
> 兄弟你刷回MIUI14能正常用v2rayNG了吗？我今年5月份开始，发现我的小米13（澎湃OS 2.x.x系统）和小米8（MIUI 12.5）都会频繁断开v2rayNG的链接，只要一打开链接外网的APP（包括在小米自带浏览器上访问 [www.facebook.com](http://www.facebook.com) 这样的国外网站）就会马上被系统断开v2rayNG链接。 我估计你的手机刷回MIUI 14也解决不聊问题，小米的这个断开v2rayNG的问题貌似是针对同一个小米账户的，不受手机系统版本的限制。

期间升级过HyperOS2，连接也不是很好。还是刷回MIUI14，现在使用很稳定后期不考虑升级了。
当前v2rayNG可以做到常驻后台使用，不会无故断连。

另外不推荐使用小米浏览器（adb删除小米无用的程序），推荐chrome或者Via
