### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by Serpent0102** [2dust/v2rayNG#292]
### 预期行为
通过url或二维码导入配置（windows的v2rayN、ios的shadowrocket都可用），安卓的v2rayNG也应该可用。

### 实际行为
安卓的v2rayNG 0.6.18 arm v7a无法联网（包括国内网站也打不开），改用BifrostV（下载自apkpure）就没问题，两者都是默认设置。

**Comment by 2dust** [comment]
什么配置和log都未提供
