### ISSUE TITLE
v2rayNG invalid:“net/http:TLS handshake timeout”

### ISSUE THREAD

**Issue by 374171823** [2dust/v2rayNG#2920]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
无法使用vpn登入，testing后显示http: TLS HANDSHAKE TIMEOUT

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by bingotl** [comment]
https://github.com/2dust/v2rayNG/issues/2044

**Comment by wangwang-code** [comment]
代理chrome，访问任意网站，如果错误为找不到ip，则是DNS的问题
可以去试试https://github.com/wangwang-code/v2rayNG/releases/tag/99999

**Comment by 138161** [comment]
订阅地址
主界面--右上角---错误，会timeout
主界面--左上角--菜单---订阅--正确
