### ISSUE TITLE
url decode解码不正确

### ISSUE THREAD

**Issue by PowerfulRichard** [2dust/v2rayNG#2922]
### 预期行为
正确解码remarks

### 实际行为

一个小bug，V2rayNG解码url encode不正确，测试链接中的%2B被解析为空格
`I+.TW.HiNet`被解析成了`I .TW.HiNet`
### 复现方法
1.导入链接

### 日志信息
> 无相关错误日志

### 环境信息
Android 14

### 额外信息（可选）

测试配置链接
```
trojan://aaaaaaaaaaaaaaa@a.com:11111?security=tls&type=tcp&headerType=none#I%2B.TW.HiNet
```

注：V2rayN当中是正常的

**Comment by 2dust** [comment]
确实有这个问题
是因为解析后对#I%2B.TW.HiNet 重复做了一次decode，这样做是为了避免一些问题
配置中尽量不要加入一些特殊字符，比如+，%这样的
