### ISSUE TITLE
麻烦加上 gRPC authority 并更新 gRPC 分享链接

### ISSUE THREAD

**Issue by RPRX** [2dust/v2rayNG#2924]
gRPC authority 挺有用的，~~但不好多说~~，把它放到 host 那里就行了

gRPC serviceName 通常比较“干净”，所以改成 encodeURIComponent 是兼容的

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.9, https://github.com/XTLS/Xray-core/discussions/716, https://github.com/XTLS/Xray-core/pull/3076, https://github.com/XTLS/Xray-core/pull/1815

**Comment by yuhan6665** [comment]
I'm on it

**Comment by RPRX** [comment]
感谢 @yuhan6665 https://github.com/2dust/v2rayNG/commit/92d3136a2383bc226ca08767d541d5f0b44b3384
