### ISSUE TITLE
 Visibility of V2rayNG App Icon on Xiaomi TV Apps

### ISSUE THREAD

**Issue by savyjs** [2dust/v2rayNG#2929]
Hello
The app icon of V2rayNG is not visible and accessible from the home screen of Xiaomi TVs with Google Android (ARMv7). Additionally, on certain occasions, the app is visible and accessible from the "All Apps" list on Android TV, while other times it is not.

I guess it could be because of commenting the "android.intent.category.LEANBACK_LAUNCHER" (potentially due to a build error?). I want to find a solution for that so I can open and use this amazing app on my TV. I'd love to see the icon on my TV home screen as well (I understand it may not be possible, but it would be nice.)

I wanted to ask for the reason first, and if I can help with fixing the issue. I'll probably try that in another fork.

https://github.com/2dust/v2rayNG/blob/c34f332771cce4d602ac3ef57528d80c0a39d68f/V2rayNG/app/src/main/AndroidManifest.xml#L57

**Comment by savyjs** [comment]
I just updated the Android manifest file and added a banner and logo to the activity of LEANBACK_LAUNCHER, and it works now.

![image](https://github.com/2dust/v2rayNG/assets/24469125/07bbd601-2364-4c75-bcdb-399ddcd9588c)

I haven't submitted a PR yet, but if you think this would help others, let me know. The changes can be found here:

https://github.com/2dust/v2rayNG/compare/master...savyjs:v2rayNG-android-tv:master#diff-13af3025dfabfdde09ec4a939181810806e0a591a38e43937b7b716d03167d39

**Comment by mh292929** [comment]
Please create pr. Thanks

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.21
