### ISSUE TITLE
recompiling v2rayNG with custom v2ray-core

### ISSUE THREAD

**Issue by gitamenet** [2dust/v2rayNG#293]
hi ,
i'm trying to recompile v2rayNG with my specific v2ray-core that implements utls for fingerprinting resistance.
for this purpose i tried to compile DEFAULT Libv2rayLite source and it compile with no error .
but when using it , android studio gives some errors as shown in screenshot.
![aar problem](https://user-images.githubusercontent.com/61662197/75795400-7f8aea80-5d87-11ea-8b9c-b60795b46ae3.png)

using generated libv2ray.aar provided by you ( precompiled) works fine with no error .

is it possible to help me about this problem ?
thanks

**Comment by 2dust** [comment]
do it yourself

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/tree/master/AndroidLibV2rayLite

**Comment by yuhan6665** [comment]
@gitamenet I found out why: you can compare the interface "V2RayPoint" defined in 
https://github.com/2dust/v2rayNG/blob/master/AndroidLibV2rayLite/interact.go
vs.
https://github.com/2dust/AndroidLibV2rayLite/blob/master/interact.go
You can try compile the AndroidLibV2rayLite under v2rayNG project for now.
