### ISSUE TITLE
vless node in cloudflare doesn't work correctly on v2rayNG

### ISSUE THREAD

**Issue by bobwang3** [2dust/v2rayNG#2930]
The same configured node is working fine on other software on other platforms.
This problem was discovered probably since yesterday.
The nodes in cloudflare are not completely not working on v2rayNG, the mobile browser can't open the Google home page and youtube, but gmail works and telegrams work.
I've tried v1.8.17 and v1.8.18 and neither of them work properly.
Also I tried importing the same cloudflare node configuration into another android app and after testing it I found that it is also working fine.
So I came up with the result that the node in cloudflare works fine, but not in v2rayng.

**Comment by gh168** [comment]
有同样的问题，PC上用V2RAYN用同样的节点一起正常，手机上YouTube app无法联网，手机浏览器无法打开 Google ，twitter能正常联网，文字图片都正常，但是视频无法播放。卸载重装，重新导入节点，重启手机都试过还是不行。之前都是好的，突然就不行了。百思不得其解

**Comment by rwat1** [comment]
It didn't work for me, until I tried these settings:

Under 'Settings':
- Disable per-app proxy
- Enable local DNS
- Enable Fake DNS

Under 'Predefined Rules', select 'Bypass the LAN address then proxy' 
Make sure 'Mode' = 'VPN' (all the way at the bottom of settings)

Make sure you do this while VPN is off. 

For some reason, this worked for me.

**Comment by gh168** [comment]
it works! thank you so much.

2dust ***@***.***> 于2024年4月11日周四 08:00写道：
