### ISSUE TITLE
path dont copy when exporting a vless tcp + header

### ISSUE THREAD

**Issue by xmohammad1** [2dust/v2rayNG#2939]
hi there , hope u guys doing good
when i export my Vless + TCP + Header config from v2rayng it dont write path in url
like if my config is
```
vless://35e6809b-d4fe-40c8-9828-b6f90f72a80f@example.com:8080?security=none&encryption=none&host=fast.com&headerType=http&type=tcp&path=%2Fapi#example
```
after i export that from list gives me 
```
vless://35e6809b-d4fe-40c8-9828-b6f90f72a80f@example.com:8080?security=none&encryption=none&host=fast.com&headerType=http&type=tcp#example
```

**Comment by xmohammad1** [comment]
My v2rayng version is 1.8.17

Uploading Screenrecorder-2024-03-18-21-40-53-678.mp4…

**Comment by xmohammad1** [comment]
My v2rayng version is 1.8.17

https://github.com/2dust/v2rayNG/assets/117955130/541fe383-e628-4f81-b787-5314b4c63e3a

**Comment by 2dust** [comment]
https://github.com/XTLS/Xray-core/discussions/716

tcp has no path
