### ISSUE TITLE
Not open YouTube ( fixed version 1.2.2)

### ISSUE THREAD

**Issue by tigerbit85** [2dust/v2rayNG#295]
v2rayng  for android
After version  1.1.14  can't open  the  site "YouTube"
I test 1.1.15 and 1.2.0
 Some sites  and "YouTube" do not open "YouTube" ، While the 1.1.14  version working without problems.
I use vmess "https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray" for connection
Android 6 Samsung
Please fix the problems.
Thank you

**Comment by revolutionxuanbei** [comment]
这个中式英文异常亲切

**Comment by tigerbit85** [comment]
Duplicate of #295

> v2rayng for android
> After version 1.1.14 can't open the site "YouTube"
> I test 1.1.15 and 1.2.0
> Some sites and "YouTube" do not open "YouTube" ، While the 1.1.14 version working without problems.
> I use vmess "https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray" for connection
> Android 6 Samsung
> Please fix the problems.
> Thank you

Thanks for great app,  but still  can't open the site YouTube ( new version1.2.1)🙁

**Comment by tigerbit85** [comment]
> Duplicate of #295
> 
> > v2rayng for android
> > After version 1.1.14 can't open the site "YouTube"
> > I test 1.1.15 and 1.2.0
> > Some sites and "YouTube" do not open "YouTube" ، While the 1.1.14 version working without problems.
> > I use vmess "https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray" for connection
> > Android 6 Samsung
> > Please fix the problems.
> > Thank you
> 
> Thanks for great app, but still can't open the site YouTube ( new version1.2.1)


Now working in the version 1.2.2
Thank you @2dust

**Comment by nathanielhawthorne** [comment]
same question

**Comment by nathanielhawthorne** [comment]
my cell phone is mi,i can not open youtube on my cell phone,but my pc can do that,i doubt it is the problem of my phone,maybe dns leads to that,i heard about there are CGW function problem on MI,some domain from foreign can not be analysed

**Comment by nathanielhawthorne** [comment]
there are DNS cache pollution problem on some chinese cell phone

**Comment by XZN401339** [comment]
i can not open youtub by qv2ray in windows 10 x64
