### ISSUE TITLE
Add option to get backup or restore of settings

### ISSUE THREAD

**Issue by m3hdiclub** [2dust/v2rayNG#2951]
Can you put a part to backup the settings and subscription links and also a part to restore that file in another phone?

**Comment by questionzx** [comment]
![Uploading 991e88a62775a350a88303d645f0bf1a.jpg…]()

**Comment by questionzx** [comment]
03-23 22:31:13.519 D/com.v2ray.ang(24718): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.20
