### ISSUE TITLE
可否将libs目录下的libv2ray.aar更新到Core v4.22.1版本？

### ISSUE THREAD

**Issue by zdm2008** [2dust/v2rayNG#296]
可否将libs目录下的libv2ray.aar更新到Core v4.22.1版本？

**Comment by 2dust** [comment]
do it yourself

**Comment by zdm2008** [comment]
我不知道如何编译，请问哪里有编译的教程？

**Comment by zdm2008** [comment]
请问这个链接可以编译吗？

https://yuanmomo.net/2019/12/02/v2ray-android-build-aar/

**Comment by yuhan6665** [comment]
@zdm2008 
Try read 
https://github.com/golang/go/wiki/Mobile
https://tutorialedge.net/golang/makefiles-for-go-developers/

**Comment by vcheckzen** [comment]
On Windows

1. install latest android sdk, android ndk, golang, gomobile, git
2. set environment variables of `ANDROID_HOME` and `ANDROID_NDK_HOME`
3. exec the following commands

```bash
git clone https://github.com/2dust/AndroidLibV2rayLite.git
cd AndroidLibV2rayLite
# go mod download github.com/v2fly/v2ray-core/v4
gomobile bind -v
```
