### ISSUE TITLE
Images error on browse some mainland websites, if use "bypass mainland websites" route policy.

### ISSUE THREAD

**Issue by NagisaEfi** [2dust/v2rayNG#2963]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
1. Images error if connect V2RayNG, and browse Zhihu, Baidu Tieba.

![Screenshot_20240330-105915_Samsung Internet](https://github.com/2dust/v2rayNG/assets/141222574/bc171ca2-60c7-4c18-8800-c32918008f19)

![Screenshot_20240331-090002_Samsung Internet](https://github.com/2dust/v2rayNG/assets/141222574/a516d69f-f078-405a-a211-e032aaa0b05d)

![Screenshot_20240330-110010_v2rayNG](https://github.com/2dust/v2rayNG/assets/141222574/7789c022-9c25-4f7b-8aef-5c2c0ecc8261)

2. After disconnect V2RayNG, or use "global" route policy, it's OK.

![Screenshot_20240330-112344_Samsung Internet](https://github.com/2dust/v2rayNG/assets/141222574/1350e303-53a2-4cda-83bc-9ea75ee1e8d1)

![Screenshot_20240331-090621_Samsung Internet](https://github.com/2dust/v2rayNG/assets/141222574/60ae0b4a-f553-4127-a47b-7475190c132a)

![Screenshot_20240331-090756_v2rayNG](https://github.com/2dust/v2rayNG/assets/141222574/31d06316-c30a-4ef6-ba5b-1ddced1abb43)

3. Change the "Domestic DNS" to 119.29.29.29 (V2RayNG default is 223.5.5.5), and use "bypass mainland websites" route policy, problem temporary solved.

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Latest version of V2RayNG

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.20
