### ISSUE TITLE
Share VPN Connection via Hotspot (Feature Requests)

### ISSUE THREAD

**Issue by Phoenix-999** [2dust/v2rayNG#2976]
@2dust Hey! Just wanted to say a big thank you for all your hard work and dedication.
We really appreciate everything you do!

I have a suggestion that I think could make the app even better: what do you think about adding a feature to **`share the VPN connection via hotspot`**?
Do you reckon it's something that could be added?

Thanks a bunch for considering it!

**Comment by 2dust** [comment]
This feature requires root and there is already such an app
