### ISSUE TITLE
两个华为手机安装这个客户端都连接不稳定

### ISSUE THREAD

**Issue by yi122415905** [2dust/v2rayNG#298]
两个华为手机安装这个客户端都连接不稳定，软件内测试连接一会一千多，一会两千多，一会三千多，没有五百以内的，电脑端没有这个问题，用ws+TLS，安卓客户端换成bifrostv后连接稳定了，希望能解决这个问题，谢谢！

**Comment by 2dust** [comment]
无解,请能用啥用啥

**Comment by yi122415905** [comment]
> 无解,请能用啥用啥

已经用bifrostv，稳定多了
