### ISSUE TITLE
希望改进更新订阅机制

### ISSUE THREAD

**Issue by VVaraiotoko** [2dust/v2rayNG#30]
订阅列表越来越长，可每次更新订阅后，选择的节点都会跳回订阅列表第一项。ShadowsocksR更新订阅就不会出现这样的情况，只会修改或新增节点信息，希望有可能的话，借鉴一下其订阅更新机制。

**Comment by DavidpYau** [comment]
他是每次更新就增加一次列表，所以不断更新不断增加！
