### ISSUE TITLE
有方法可以在android 用openvpn 經 v2rayng嗎?

### ISSUE THREAD

**Issue by pavehawk** [2dust/v2rayNG#300]
### 预期行为
於android 可用openvpn 經 v2ray

### 实际行为
只可用其一 不可同時啟用

### 复现方法
NA

### 日志信息
NA

### 环境信息
Android 5.0
### 额外信息（可选）
windows 可於openvpn中設定proxy，並可經v2ray連上openvpn server

**Comment by 2dust** [comment]
android系统只允许一个vpnservice
剩下你自由发挥
