### ISSUE TITLE
建议加入流量探测高级功能

### ISSUE THREAD

**Issue by shandongtlb** [2dust/v2rayNG#3000]
https://xtls.github.io/config/inbound.html#sniffingobject

建议加入xray sniff嗅探流量中的 routeOnly 参数开关
默认应该是关闭的
谢谢！

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/commit/e053db3dff9aeedcfeabd1e164cdec7fad9c1f21

**Comment by luis1111111111** [comment]
请问能否解释一下RouteOnly的作用？

代理目标地址使用“嗅探到的域名”和使用“原始IP”之间有什么区别？

如果想要不论ip，只要是国外域名一律代理，是否应该关闭RouteOnly并且选择AsIs？
