### ISSUE TITLE
电脑能翻墙，手机翻不了，换其他软件客户端能翻

### ISSUE THREAD

**Issue by missbouo** [2dust/v2rayNG#3012]
同一个节点，电脑能用，手机突然用不了，苹果和安卓都不能用，也同步时间了，没效果，换个其他翻墙软件，手机也能正常翻，这到底是怎么回事啊？求大佬告知，摆弄快一周了，还是不行

**Comment by sancdvs** [comment]
是不是因为用了最新版的xray的缘故
