### ISSUE TITLE
建议在订阅功能处添加特定user agent

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#302]
建议
v2rayNG中的订阅功能，其访问订阅地址时的user agent能否修改为其他，目前为Dalvik，kitsunebi的user agent也是这个，两者相同，而两个软件的订阅内容格式却不同，导致无法根据用户UA判断其使用的v2ray客户端类型而返回对应的订阅内容

**Comment by 2dust** [comment]
可以做,但是这样的结果就是增加订阅提供者的负担和难度,导致此功能不稳定性
所以不推荐这样做,还是单独提供多个订阅更合适

**Comment by ghost** [comment]
个人认为不会增加订阅提供者的负担和难度，不会影响采用单独提供多个订阅的条约提供者，因为其在链接上就已经存在不同。
另外，还可以达到用户客户端分析的的效果，能够对客户更多使用哪种客户端有一定了解，目前主流的ios系统的v2ray客户端的订阅模块均使用自己的user agent。
我说的特定user agent并非开放给客户自己手动修改，而是客户端特定的，例如v2rayNG
