### ISSUE TITLE
using project codes inside our app

### ISSUE THREAD

**Issue by angry-mob** [2dust/v2rayNG#3022]
we are developing a program where we've used your core and some parts of the v2rayng project source code, along with a few other cores. The way it works is that when the user enters the app, the configs are received from the server side. That means we provide the configs ourselves. Do we have to publish the source code of our app? If we have to do this, can we remove the server related codes from our project and in that case publish the source code?

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/blob/master/LICENSE
