### ISSUE TITLE
一加5t android9.0上无法开启服务

### ISSUE THREAD

**Issue by muryliang** [2dust/v2rayNG#303]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
服务开启

### 实际行为
服务无法开启

### 复现方法
1.使用版本0.6.18.2
2.使用windows客户端可以正常开启服务，到处vmess url后，在客户端上无法开启

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

--------- beginning of crash
--------- beginning of system
--------- beginning of main
04-13 09:56:43.927 30527 30527 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
04-13 09:56:43.951 30527 30539 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 09:56:43.960 30527 30539 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 09:56:51.666 30557 30557 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
04-13 09:56:51.683 30557 30570 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 09:56:51.692 30557 30557 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 10:03:28.425 31156 31156 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
04-13 10:03:28.436 31156 31169 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 10:03:28.445 31156 31156 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 10:13:07.833 32461 32461 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
04-13 10:13:07.848 32461 32474 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 10:13:07.859 32461 32461 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 10:19:11.945  1026  1026 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
04-13 10:19:11.960  1026  1066 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
04-13 10:19:11.967  1026  1026 I com.v2ray.ang: The ClassLoaderContext is a special shared library.

### 环境信息
一加5t 9.0

**Comment by 2dust** [comment]
无法帮你解决特定机型问题,
