### ISSUE TITLE
速度显示异常，显示了局域网流量速度

### ISSUE THREAD

**Issue by pzh200707** [2dust/v2rayNG#303]
播放局域网文件（SAMBA）的时候，V2rayng显示了局域网的速度。
尝试切换了慢速卡顿的节点，局域网本地文件依旧播放流畅，V2rayng显示5M/s的高速。机场后台显示没有流量使用。
尝试自定义规则将192.168.123.111, 192.168.123.1加入直连列表，问题依旧。

### 预期行为
局域网播放文件时，V2ray绕过，不显示速度

### 实际行为
局域网播放文件时，V2ray绕过，但显示速度

### 复现方法
局域网播放文件

### 日志信息
<details>

</details>
![image](https://user-images.githubusercontent.com/26104496/76179518-2ba05b80-61f6-11ea-819e-c6821fb66c94.png)

### 环境信息
android 8.1.0 一加5
主路由ip 192.168.123.1
电脑（局域网文件储存位置）ip 192.168.123.111

**Comment by 2dust** [comment]
只要app走了core,不管有没有走远程vps,都会算到流量中来,暂时无解
