### ISSUE TITLE
How do I set up auto boot?如何设置自动启动？

### ISSUE THREAD

**Issue by CAI5201314** [2dust/v2rayNG#3030]
如何实现开机后自动启动v2RayNG的VPN？

How can I implement a VPN that automatically starts v2RayNG after booting?

كيف يمكنني تنفيذ VPN يبدأ تشغيل v2RayNG تلقائيًا بعد الإقلاع؟

Как реализовать VPN, которая автоматически запускает v2RayNG после загрузки?

Comment puis-je mettre en place un VPN qui démarre automatiquement v2RayNG après le démarrage ?

起動後に自動的にv2RayNGを起動するVPNを導入するにはどうすればよいですか？

**Comment by 2dust** [comment]
没有此功能

**Comment by hzy132** [comment]
我的手机有这个功能，安卓13，在设置->更多连接设置->VPN->齿轮图标->始终开启的VPN

**Comment by TheLordOfTheKings** [comment]
> There is no such feature

@2dust Now that we have Android TV support i believe this option is much needed.
