### ISSUE TITLE
Data folder can't be accessed on Android 12+

### ISSUE THREAD

**Issue by V2Persia** [2dust/v2rayNG#3048]
Hi 👋 
Thanks for adding the backup and restore feature, it'll be very useful and handy specially for geting people who aren't tech savvy up and running quickly.

Unfortunately I can't access the backup file in data folder due to a restriction Google implemented since Android 12.
It shows you some nonsense starting with "To protect your privacy...", is it possible to change the backup file path? Or it'll be great if we can choose a folder.
"Streisand" on iOS has a feature to export and import settings using links (Streisand://) if changing the folder isn't possible please do consider this option.
Thanks again

**Comment by 2dust** [comment]
https://play.google.com/store/apps/details?id=com.alphainventor.filemanager

Install this app
should be accessible

**Comment by V2Persia** [comment]
Thank you for responding
I have tried this app and many more but it's the same issue.
This happens:
https://github.com/2dust/v2rayNG/assets/130739509/062bb000-cbfe-4820-a527-a2ea0dc0ca8f

I'm using Galaxy S21 Ultra 5G (SM-G998B/DS)
Android 14 (OneUI 6)

**Comment by 2dust** [comment]
The development and testing device is pixel6a Android14, everything is ok
Waiting for oneui device verification

**Comment by V2Persia** [comment]
Thanks❤️

**Comment by 2dust** [comment]
[v2rayNG_1.8.22_arm64-v8a.zip](https://github.com/2dust/v2rayNG/files/15141988/v2rayNG_1.8.22_arm64-v8a.zip)

Add share configuration

**Comment by V2Persia** [comment]
Works flawlessly
Thank you❤️
