### ISSUE TITLE
希望能支持 armv7 abi

### ISSUE THREAD

**Issue by jimmygc** [2dust/v2rayNG#305]
有一些设备比如kindle fire stick装不上，希望能支持

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/releases/download/1.2.2/v2rayNG_1.2.2_armeabi-v7a.apk

**Comment by al1az1z1** [comment]
> https://github.com/2dust/v2rayNG/releases/download/1.2.2/v2rayNG_1.2.2_armeabi-v7a.apk

Hi sir,
Is this version working yet or not?
