### ISSUE TITLE
希望增加类似BifrostV中流量记录的功能

### ISSUE THREAD

**Issue by cjl3230** [2dust/v2rayNG#305]
希望可以增加流量记录的功能，这样可以方便知道哪些流量走了代理，哪些流量走了直连

**Comment by channingbox** [comment]
BifrostV 界面确实会更胜一筹，功能看起来也合理，但用起来会卡卡的，目前安卓客户端v2rayNG还是最好的选择。

**Comment by 2dust** [comment]
NG定位于简单使用,如需要高级功能只能换个app了
