### ISSUE TITLE
[BUG] external geoip/site will be recognized as domain rule

### ISSUE THREAD

**Issue by X-Oracle** [2dust/v2rayNG#3060]
Version: V2rayng 1.8.22

When these rules added to direct rules, it will be recognized as domains thus x-ray will redirect all traffic to direct outbound.
```
ext:chocogeosite.dat:ir,
ext:chocogeoip.dat:ir,
ext:chocogeoip.dat:private
```

Results In:
```json
      {
        "domain": [
          "ext:chocogeosite.dat:ir",
          "ext:chocogeoip.dat:ir",
          "ext:chocogeoip.dat:private"
        ],
        "outboundTag": "direct"
      }
```
If we put the IP related rules in "ip" array it will work fine.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/commit/bdc3212f385a906fd03ee1b93656b2c56da13a77
