### ISSUE TITLE
1.8.20+ Custom Config被强制直连LAN

### ISSUE THREAD

**Issue by Platway** [2dust/v2rayNG#3074]
### 预期行为
我的Custom Config配置了LAN走代理，如下：

```
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "ip": [
          "192.168.1.0/24"
        ],
        "outboundTag": "proxy"
      }
    ]
  }
```

在1.8.19或之前的版本一直可以正常让192.168.1.x走代理（以便远程连接我的服务器所在的LAN）。

### 实际行为
从1.8.20开始，配置没有任何改动，无法连接远端的192.168.1.x，也就是LAN地址被强制直连而不理会Custom Config里的路由配置。

换句话说，按我理解，对于使用Custom Config的情况，v2rayNG理应完全只遵从Custom Config里的路由配置而不应前置其他规则。不知我的理解对不对？谢谢！

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/blob/f624bd651eaddb927822ac392dd9bd3f1aa50d4a/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L43

代码在这里，Custom config完全没有改变。
您退回到1.8.20之前和使用1.8.22对比测试下

**Comment by Platway** [comment]
> https://github.com/2dust/v2rayNG/blob/f624bd651eaddb927822ac392dd9bd3f1aa50d4a/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L43
> 
> 代码在这里，Custom config完全没有改变。 您退回到1.8.20之前和使用1.8.22对比测试下

我找到源头了，是“设置→预定义规则”的默认选项在1.8.20版本发生了改变造成的。如果该项设置成“绕过局域网……”就会出现顶楼所述问题。

但是我理解，当使用Custom Config JSON配置时，app设置里面的路由规则是不是不应该生效，不应该前置在Custom Config的路由规则之前？谢谢解答🙏

**Comment by 2dust** [comment]
预定义规则确实有改变，如果用户没有设置过这个值，原来是默认全局代理，现在是默认绕过大陆和LAN，你手工设置成全局代理吧。

这个值不会改变core自定义配置，但是会影响启用vpn的参数，可能问题在这里

**Comment by Platway** [comment]
> 预定义规则确实有改变，如果用户没有设置过这个值，原来是默认全局代理，现在是默认绕过大陆和LAN，你手工设置成全局代理吧。
> 
> 这个值不会改变core自定义配置，但是会影响启用vpn的参数，可能问题在这里

我发现只要把该项设置成“绕过局域网……”以外的选项，就都没问题。

**Comment by Platway** [comment]
> 预定义规则确实有改变，如果用户没有设置过这个值，原来是默认全局代理，现在是默认绕过大陆和LAN，你手工设置成全局代理吧。
> 
> 这个值不会改变core自定义配置，但是会影响启用vpn的参数，可能问题在这里

我在想，对于Custom  Config的情况，是否该项设置成“全局直连”效率最高？

**Comment by 2dust** [comment]
预定义规则会影响vpn的一些选项，你选择一个能用的就行了，关闭了
