### ISSUE TITLE
关于谷歌翻译App无法使用v2rayNG正常代理的解决方法

### ISSUE THREAD

**Issue by timeneverdie** [2dust/v2rayNG#308]
发现谷歌翻译App在没有代理的时候也能使用，挂了代理反而无法使用，所以判断谷歌翻译使用了translate.google.cn这个地址。

但是不知道为什么就算把语言切换为英文，还是会使用translate.google.cn而不是translate.google.com。

我之前成功切换过，只要把系统语言改为英文，谷歌翻译App就会自动使用translate.google.com，但不知道为什么又自动切回来了。由于谷歌翻译App的设置里无法手动选择国家和区域，因此只能在v2rayNG上动脑筋。

既然锁定了问题的关键，那解决办法就是把translate.google.cn强制走代理。在`设置-自定义规则-代理的Domain或IP`中填写`translate.google.cn`，点击上方的`√`保存，然后重新连接代理以使配置文件生效，这样就可以正常使用谷歌翻译App了。

但这只是一个临时的办法，找到出现问题的原因才是根本，因为按理说通过判断IP地址实现分流的话，是不会出现这样的情况的。

另外就是v2ray访问百度也特别慢，可以尝试把`www.baidu.com`加入强制直连的规则中。
> 经过查询v2ray文档参数，请勿使用`*.baidu.com`这样的写法。如果想要把百度的网站都直连，直接使用`baidu.com`即可。

电脑版的v2ray客户端除了要重启服务外，还需要重新设置下系统代理，才会使新配置的规则生效。

**Comment by huduobao** [comment]
解决了 感谢大佬

**Comment by IceCodeNew** [comment]
```
"dns": {
  "hosts": {
    "domain:googleapis.cn": "googleapis.com",
    "translate.google.cn": "translate.google.com"
  },
},
"routing": {
  "domainStratedy": "IPIfNonMatch",
  "rules": [{
    "type": "field",
    "domain": [
      "domain:googleapis.cn"
      "translate.google.cn"
    ],
    "outboundTag": "proxy"
  },{
    "type": "field",
    "domain": [
      "geosite:cn"
    ],
    "outboundTag": "direct"
  },{
    "type": "field",
    "ip": [
      "geoip:private",
      "geoip:cn"
    ],
    "outboundTag": "direct"
  },{
    "type": "field",
    "domain": [
      "geosite:category-ads-all"
    ],
    "outboundTag": "block"
  }]
}
```

一种思路，供参考。

**Comment by IceCodeNew** [comment]
另外不知道这样可不可行（没试过从国内直连 Google翻译.cn），和上面是相反的一种思路：
```
"dns": {
  "servers": [{
      "address": "https+local://dns.alidns.com/dns-query",
      "domains": [
        "geosite:cn",
        "translate.google.cn"
      ],
      "expectIPs": [
        "geoip:cn"
      ]
    },
    "localhost"
  ]
},
"routing": {
  "domainStratedy": "IPIfNonMatch",
  "rules": [{
    "type": "field",
    "domain": [
      "geosite:cn",
      "translate.google.cn"
    ],
    "outboundTag": "direct"
  },{
    "type": "field",
    "ip": [
      "geoip:private",
      "geoip:cn"
    ],
    "outboundTag": "direct"
  },{
    "type": "field",
    "domain": [
      "geosite:category-ads-all"
    ],
    "outboundTag": "block"
  }]
}
```

**Comment by CuCuCheung** [comment]
感谢！！！

**Comment by SekiBetu** [comment]
IPOnDemand，绕过局域网及大陆地址，解决

**Comment by conray002** [comment]
v2ray设置google翻译的技巧：

1、首先设置V2RAY全局模式，待google翻译正常以后可以设置为“不改变系统代理”模式。
2、非常重要：V2RAY设置----路由设置--路由规则--添加规则---outbandtag设置 proxy   domain设置“translate.googleapis.com,
*.googleapis.com”（备注直接复制引号里面的内容，别复制引号）--保存确定。
3、最最重要：将刚刚设置的第二步上移置顶。

完成上述三步骤，完美解决chrome内置google翻译与V2RAY的完美匹配。

给我点赞吧，我研究了好几个小时，才搞明白。多谢

**Comment by WizLiang** [comment]
> v2ray设置google翻译的技巧：
> 
> 1、首先设置V2RAY全局模式，待google翻译正常以后可以设置为“不改变系统代理”模式。 2、非常重要：V2RAY设置----路由设置--路由规则--添加规则---outbandtag设置 proxy domain设置“translate.googleapis.com, *.googleapis.com”（备注直接复制引号里面的内容，别复制引号）--保存确定。 3、最最重要：将刚刚设置的第二步上移置顶。
> 
> 完成上述三步骤，完美解决chrome内置google翻译与V2RAY的完美匹配。
> 
> 给我点赞吧，我研究了好几个小时，才搞明白。多谢

感谢，实测可用（我习惯是清除系统代理），第一步可以省略，但是一定要顶置。
