### ISSUE TITLE
Feature Request: App-specific VPN control

### ISSUE THREAD

**Issue by pooryas98** [2dust/v2rayNG#3082]
Hello and thank you for your hard work on V2RayNG!
Issue: Frequently turning the app on and off to accommodate local apps that don't require VPN connectivity is inconvenient.
Request: Please consider adding a feature that allows users to configure which apps are routed through V2RayNG and which ones are not. This would be a great enhancement to the app's functionality.

**Comment by Alireza78na** [comment]
This option is already available from "Per-app Proxy" in Settings.

**Comment by lzy1960** [comment]
> This option is already available from "Per-app Proxy" in Settings.

But the latest version 1.8.22 seems to be unable to search for any app, only "v2rayNG"
