### ISSUE TITLE
分应用代理列表中仅有“v2rayNG”，无法筛选出其他app

### ISSUE THREAD

**Issue by lzy1960** [2dust/v2rayNG#3084]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

https://github.com/2dust/v2rayNG/issues/3082#issuecomment-2094560189

### 预期行为
分应用代理列表中应当展示系统中的所有应用，并可搜索筛选

### 实际行为
分应用代理列表中仅有“v2rayNG”，并且无法筛选出任何其他app

### 复现方法
1. 进入设置菜单
2. 点击分应用代理
3. 进入了列表页，即可触发上述行为

### 日志信息
无

### 额外信息（可选）
机型：小米10 pro hyperOS 1.0.3.0
应用版本：1.8.22

![5d5a2c44345ff957ae962e246515186](https://github.com/2dust/v2rayNG/assets/40552111/d39f823a-ee38-47df-ae88-4d76bc4b56bb)

**Comment by lzy1960** [comment]
试了老版本和隔壁app也有相同的问题了，但之前miui是正常的，猜测可能是澎湃os的锅

先关闭了

**Comment by 2dust** [comment]
测试机中无此类型，暂时无法解决

**Comment by lzy1960** [comment]
已解决，是因为更新系统后app的“读取应用列表”权限变成了“禁用”，开启此权限后正常了

**Comment by Poseiden** [comment]
> 已解决，是因为更新系统后app的“读取应用列表”权限变成了“禁用”，开启此权限后正常了

顺便也把读写clipboard开启了
