### ISSUE TITLE
可否考虑增加自定义测速参数的功能

### ISSUE THREAD

**Issue by hld9726** [2dust/v2rayNG#3087]
比如自定义测速地址和超时延迟 

因为目前在使用过程中出现了部分节点是能联通的 但是测试的时候出现-1ms

**Comment by 2dust** [comment]
默认是google的地址，这个自定义你会改成什么地址？

**Comment by hld9726** [comment]
> 默认是google的地址，这个自定义你会改成什么地址？

http://www.gstatic.com/generate_204或者是http://www.apple.com/library/test/success.html

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/commit/f0f9da0f1b8f4cc3cf4a1eaff6f55b3ad6f2a050
