### ISSUE TITLE
控制中心v2rayNG开关按钮（控制栏控件）无法正常运行

### ISSUE THREAD

**Issue by F0ksay** [2dust/v2rayNG#3088]
### 预期行为
1.控制中心开关按钮应随手机桌面开关按钮的打开而亮起，并随其关闭而熄灭。
即，当点亮手机桌面的v2rayNG开关按钮时，控制中心原本熄灭的v2rayNG按钮应当亮起；当熄灭手机桌面的v2rayNG开关按钮时，控制中心原本高亮的v2rayNG开关按钮应当熄灭。
2.当控制中心开关按钮高亮时，打开控制中心，点击按钮一次，按钮应当熄灭。

### 实际行为
1.当点亮手机桌面的v2rayNG开关按钮时，控制中心原本熄灭的v2rayNG按钮没有亮起；当熄灭手机桌面的v2rayNG开关按钮时，控制中心原本高亮的v2rayNG开关按钮没有熄灭。
2.当控制中心开关按钮高亮时，每次打开控制中心，点击按钮一次，按钮无法熄灭。只有连续按两次，按钮才能熄灭。

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
1.我的两台安卓设备都存在同样的问题（一台华为P40pro和一台matepad11，都是鸿蒙4.0，基于安卓12）。我猜想可能是控制中心控件无法读取连接状态导致的？
2.我尝试过升级到最新版本（1.8.22），问题同样存在。
3.尊敬的开发者，旧版本的桌面开关颜色和我的壁纸相当契合。假如可以，我想请你未来添加一个桌面开关颜色的可选项。
Dear developer, the color of the old-version desktop switch button matches my wallpaper quite well. I would appreciate it if you can add a color option of the button in the future.

https://github.com/2dust/v2rayNG/assets/68806296/15495899-9061-41f6-afa3-fecc1325a400

**Comment by 2dust** [comment]
这个一般都是某手机系统的问题，开发设备中无法复现

**Comment by 2dust** [comment]
特别鸿蒙，估计要说88了
