### ISSUE TITLE
已捐赠，但是推广链接还是在显示

### ISSUE THREAD

**Issue by leolevel** [2dust/v2rayNG#309]
预期行为
更新0.6.19版并且捐赠后底部推广消失

实际行为
捐赠后并无变化，推广依旧存在，与之前一样

**Comment by 2dust** [comment]
捐赠后,再次进入捐赠界面再返回主页面就会消失

**Comment by leolevel** [comment]
抱歉，还是没有用。

**Comment by 2dust** [comment]
您是否登录了多个google账号?
进入捐赠界面十分有出现感谢您的捐赠?

**Comment by leolevel** [comment]
并没有登录多个Google账号，当时捐赠后提示ok，然后主界面推广还是存在。现在打开捐赠显示的还是三个捐赠选项，点按无反应。

**Comment by 2dust** [comment]
根据你的描述,应该是获取不到google的结果

**Comment by leolevel** [comment]
嗯嗯，等等正式版吧。

**Comment by leolevel** [comment]
谢谢！刚刚利用这个思路解决了问题。
当时购买捐赠时就点不开捐赠按钮，我以为是支付问题，就打开play商店让其留在后台，再进入就可以购买了。现在用同样的方法，先打开 play商店，再打开软件，果然在捐赠界面提示“感谢您的捐赠”，返回主界面推广已经消失，看来是与google连接的原因。
谢谢回复，此问题已解决，谢谢！
希望这个方法能解决有和我一样问题用户的困惑。

**Comment by 2dust** [comment]
应该是需要google的服务在后台运行才能正确获取结果
多谢你的反馈
我会加多一个检查,在捐赠提示后多获取一次结果

**Comment by leolevel** [comment]
嗯嗯，多谢作者耐心解答！
