### ISSUE TITLE
请教Wireguard节点的pre_shared_key预共享密码怎么输入？

### ISSUE THREAD

**Issue by egg1234** [2dust/v2rayNG#3094]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

没有相同的问题提出

### 预期行为
描述你认为应该发生什么

手动输入[Wireguard]节点配置时，可以输入Wireguard节点的pre_shared_key预共享密码

### 实际行为
描述实际发生了什么

手动输入[Wireguard]节点配置时，没有看到这个栏目，就是没有地方可以输入Wireguard节点的pre_shared_key预共享密码

### 复现方法
1.点击手动输入[Wireguard]
2.配置文件项目里面没有地方可以输入Wireguard节点的pre_shared_key预共享密码
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
默认不需要
如果有需要请用自定义配置解决

**Comment by egg1234** [comment]
了解，谢谢！
当然warp这些节点是不需要的，但现在已经有一些供应商开始设置这个密码项了，希望大大以后有精力的时候能够在配置界面加入这个选项
