### ISSUE TITLE
实际执行的预定义规则可能与设置不同

### ISSUE THREAD

**Issue by Urliuo** [2dust/v2rayNG#3096]
我的预定义规则一般设置为全局代理。最近，通过IP检测工具发现当前的实际配置是境内外分流。经过重启软件和设备，依然具有此特征。如果在预定义规则手动改为其他又改回，重启软件后实际就变为全局代理了。

我有另一设备同样出现了显示设置为全局代理实际为境内外分流的情况。我未测试在全新的安装后如何复现，有可能默认有这个问题，或是配置为全局后升级所致。

**Comment by 2dust** [comment]
节点上有个导出完整配置功能
你分别设置全局和绕过大陆后，导出完整配置对比最下面路由部分，发出来

**Comment by Urliuo** [comment]
修改为全局：


  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53"
      },
      {
        "outboundTag": "proxy",
        "port": "0-65535"
      }
    ]
  }


修改为绕过局域网和大陆：


"routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "domain": [
          "geosite:geolocation-cn"
        ],
        "outboundTag": "direct"
      },
      {
        "outboundTag": "proxy",
        "port": "0-65535"
      }
    ]
  }


另一设备，未修改过，显示为全局是实测为分流：


  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct"
      },
      {
        "domain": [
          "geosite:geolocation-cn"
        ],
        "outboundTag": "direct"
      },
      {
        "outboundTag": "proxy",
        "port": "0-65535"
      }
    ]
  },

**Comment by 2dust** [comment]
> 另一设备，未修改过，显示为全局是实测为分流：

应该是app修改了默认值导致的，你手工设置下预定义值返回后应该就正确了。

**Comment by Urliuo** [comment]
> > 另一设备，未修改过，显示为全局是实测为分流：
> 
> 应该是app修改了默认值导致的，你手工设置下预定义值返回后应该就正确了。
> 
> 

这就是我主贴所说的情况，我已经知道如何手动修复。只是建议增加配置和显示的一致性检查，以免其他用户意外暴露大陆IP地址。

**Comment by 2dust** [comment]
如果用户没有手工设置过，那么现在默认值是正常分流的。
如果用户设置过，那和以前没有区别
所以不用处理

**Comment by Urliuo** [comment]
> 如果用户没有手工设置过，那么现在默认值是正常分流的。
> 如果用户设置过，那和以前没有区别
> 所以不用处理

我指的是过去使用默认全局的用户，可能在不知情的情况下变成绕过大陆。

我测试了1.8.19，此时配置中显示为全局，实际也为全局。当我升级到1.8.22后，就出现了配置中显示为全局实际为绕过大陆的情况。

用户仅仅升级了应用就改变了分流配置，且这种改变在界面上看不出来，使用户误以为没变。我认为这应该是需要关注的问题。

**Comment by 2dust** [comment]
你说的对，目前在升级的说明中有提示用户了

**Comment by Urliuo** [comment]
> 你说的对，目前在升级的说明中有提示用户了

我看到当前升级提示里只说“优化预定义规则”，而且有的人是开自动升级的，可能会掉进坑里。我建议对于升级用户应该保留原始设置，如果要修改最好在应用内有显著提示。无论是否有提示，显示分流设置和实际不一致的情况还是应该避免。

**Comment by 2dust** [comment]
确实挺难决定的，你可以看下这个 https://github.com/2dust/v2rayNG/issues/3110
有人希望小白点，先把发布说明写清楚点吧，

**Comment by ShawnaStewart2000** [comment]
> > 如果用户没有手工设置过，那么现在默认值是正常分流的。
> > 如果用户设置过，那和以前没有区别
> > 所以不用处理
> 
> 我指的是过去使用默认全局的用户，可能在不知情的情况下变成绕过大陆。
> 
> 我测试了1.8.19，此时配置中显示为全局，实际也为全局。当我升级到1.8.22后，就出现了配置中显示为全局实际为绕过大陆的情况。
> 
> 用户仅仅升级了应用就改变了分流配置，且这种改变在界面上看不出来，使用户误以为没变。我认为这应该是需要关注的问题。

偶然发现升级后有些APP打开变快了，一直没在意，这两天才发现IP是国内了，还以为节点出问题了
