### ISSUE TITLE
希望可以支持安卓TV

### ISSUE THREAD

**Issue by CarmenBeta** [2dust/v2rayNG#31]
现在APP在TV上需要使用空鼠才能操作。希望开放TV版，并能在 launcher上显示。。

**Comment by poleices** [comment]
这个可以自己写一个版本么？最近我也想在TV上使

**Comment by FreeTigerman** [comment]
前列支持推出TV版，目前的版本用在TV上我试了，只有两个小问题：服务器选择按下去有反应，但选不中，另外就是有些选项没有焦点，所以遥控器选不上，只能拿鼠标去点。。。

**Comment by poleices** [comment]
> 前列支持推出TV版，目前的版本用在TV上我试了，只有两个小问题：服务器选择按下去有反应，但选不中，另外就是有些选项没有焦点，所以遥控器选不上，只能拿鼠标去点。。。

你确定么？我装的时候说什么不匹配，直接装不上

**Comment by CarmenBeta** [comment]
鼠标是可以点的，但是每次接鼠标很麻烦。
希望有个TV UI的app。

iPhoneから送信

2019/08/06 9:43、poleices <notifications@github.com>のメール:

**Comment by xiaolilir** [comment]
点赞~！！！希望有个tv的

**Comment by velade** [comment]
> 前列支持推出TV版，目前的版本用在TV上我试了，只有两个小问题：服务器选择按下去有反应，但选不中，另外就是有些选项没有焦点，所以遥控器选不上，只能拿鼠标去点。。。

我的是强制装上后，其他都正常，唯独右下角开关没有......

**Comment by yihonge** [comment]
可以用啊！universal

**Comment by velade** [comment]
可能是因為我的是pc裝的 Android TV for x86吧

**Comment by chenye3814** [comment]
我是安卓TV点右下角的连接，一直在转，就是连不上，tv的版本是安卓9，请问是什么原因呢

**Comment by b0070** [comment]
1、目前的版本在小米盒子国际版上用遥控无法开启服务器，必须用鼠标。
2、在小米盒子无法开机自启动，每次开了盒子需要手动连接以下。
3、还希望尽快适配tv版。

**Comment by zolopp** [comment]
期待有tv版，目前盒子可以安卓，但是界面不太适配，填完信息无法保存

**Comment by zhangyufei49** [comment]
关注一下。我也希望有这个功能。但是我发现我家里的小米电视不能后台运行应用。可能有什么白名单。安装的通用版本的 v2ray 客户端。到了后台就推出了

**Comment by imsjz** [comment]
同关注一波

**Comment by xsunghost** [comment]
> 我是安卓TV点右下角的连接，一直在转，就是连不上，tv的版本是安卓9，请问是什么原因呢

我的也是，神盾TV，arm64的處理器，運行一直轉。希望能解決

**Comment by chenzefeng09** [comment]
同需求

**Comment by pcdogyu** [comment]
使用悟空遥控器 电视超人等软件可以从手机控制安卓电视，并且手机推送安装v2ray。
小米盒子3增强版，小米电视4a 测试通过

**Comment by vodott** [comment]
同求。肯请大神增益！

**Comment by yuhan6665** [comment]
#300 submitted. It should fix the UI issues like highlighting and selection with tv remote.

**Comment by yelosheng** [comment]
同需求！

**Comment by PB101010** [comment]
同求啊，，，，大佬们

**Comment by chloeh94** [comment]
> 前列支持推出TV版，目前的版本用在TV上我试了，只有两个小问题：服务器选择按下去有反应，但选不中，另外就是有些选项没有焦点，所以遥控器选不上，只能拿鼠标去点。。。

我也是在电视用遥控器选择不了节点，fire tv遥控器又没有鼠标功能....一直都只能使用第一个节点

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.2.5

**Comment by 2dust** [comment]
但是由于盒子的特殊性，很容易切到后台被kill

**Comment by west110** [comment]
> 关注一下。我也希望有这个功能。但是我发现我家里的小米电视不能后台运行应用。可能有什么白名单。安装的通用版本的 v2ray 客户端。到了后台就推出了

老哥我也是这种情况切到后台就退出，有什么解决办法吗？

**Comment by maidmeow4** [comment]
Phicomm N1 刷了 Lilin Android 7，除了启动按钮和状态条被选中时焦点不明显外都能用

因为这个ROM带原生Android设置，可以把v2rayNG设置为“始终开启的VPN”，可以保住后台

**Comment by hadifarnoud** [comment]
is android TV support here? what can I do to use this on Mi Box? and will it be available on Play Store?

**Comment by adamhuang666** [comment]
求支持TV版本的啊，感谢感谢

**Comment by laisimiao** [comment]
> 关注一下。我也希望有这个功能。但是我发现我家里的小米电视不能后台运行应用。可能有什么白名单。安装的通用版本的 v2ray 客户端。到了后台就推出了

我也是

**Comment by hfhzzdx** [comment]
同求

**Comment by orrzz** [comment]
> 但是由于盒子的特殊性，很容易切到后台被kill

测试过许多次，只要能装进system目录下，也就是转换成系统软件就能后台运行。
唯一问题，运行程序能不能默认开启，是否还需要手动开启？

**Comment by al1az1z1** [comment]
> is android TV support here? what can I do to use this on Mi Box? and will it be available on Play Store?

Hi, Hadi. You have been using this protocol since 2020. How did you recognize these days?
Have you found any solution to this problem yet?

**Comment by hadifarnoud** [comment]
> > is android TV support here? what can I do to use this on Mi Box? and will it be available on Play Store?
> 
> Hi, Hadi. You have been using this protocol since 2020. How did you recognize these days? Have you found any solution to this problem yet?

Vless is excellent, and you can use that with Clash Meta on any device. Works just fine
