### ISSUE TITLE
多次重启v2ray链接以后无法再打开链接

### ISSUE THREAD

**Issue by johnnyzhangcd** [2dust/v2rayNG#310]
日志
--------- beginning of system
--------- beginning of crash
--------- beginning of main
04-17 07:18:28.137 I/GoLog   ( 3659): loading v2ray config
04-17 07:18:28.416 E/GoLog   ( 3659): panic: runtime error: invalid memory address or nil pointer dereference
04-17 07:18:30.558 I/GoLog   ( 3716): loading v2ray config
04-17 07:18:30.939 E/GoLog   ( 3716): panic: runtime error: invalid memory address or nil pointer dereference
04-17 07:19:29.310 I/GoLog   ( 3868): loading v2ray config
04-17 07:19:29.664 E/GoLog   ( 3868): panic: runtime error: invalid memory address or nil pointer dereference
04-17 07:19:29.665 E/GoLog   ( 3868): [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x7c30d67904]
04-17 07:19:30.969 I/GoLog   ( 3930): loading v2ray config
04-17 07:19:31.303 E/GoLog   ( 3930): panic: runtime error: invalid memory address or nil pointer dereference
04-17 07:19:32.983 I/GoLog   ( 4016): loading v2ray config
04-17 07:19:33.217 E/GoLog   ( 4016): panic: runtime error: invalid memory address or nil pointer dereference

**Comment by boypt** [comment]
配置出错导致无法启动的问题在0.6.19.2里面会弹提示而不是崩溃，请更新后截图反馈

**Comment by 2dust** [comment]
更新到最新版,再次反馈
