### ISSUE TITLE
Reading QRs from Gallery

### ISSUE THREAD

**Issue by dani96102** [2dust/v2rayNG#3106]
There is a problem reading QRs through the gallery.  When we try to enter the QR photo through the gallery, it gives a null error.  This problem exists in the use of the latest version of the MHSanaei/3x-ui panel QRs.  Specifically in the use of QRs of Reality configs
![Screenshot_20240510_040201_v2rayNG](https://github.com/2dust/v2rayNG/assets/68426583/26220b63-829e-441a-ba50-07cbc188dee6)

**Comment by FranzKafkaYu** [comment]
typically it's because the config is not compatible with v2rayNG QR parser,you should paste your config link gernerated by MHSanaei/3x-ui,so we can check it whether the problem is your panel or v2rayNG

**Comment by dani96102** [comment]
Ok i sent you the QR and the config link.
Please check and find the problem.
I must say i tested the QR from gallery in V2box App and it was ok, but in V2rayNG and V2rayN we have null error for reading the QR code from gallery...but there is no problem in picture scan with camera...the problem is just in gallery QRs

vless://ff0951ee-6ddd-4d56-b2a7-52848139dfc2@us.vpnetpro.com:2030?type=grpc&serviceName=&authority=&security=reality&pbk=sHEjew9Cl7YL7f2PWVPNFQoL8Skh4uJEwYJVvXqlDgA&fp=firefox&sni=discord.com&sid=1d73b7a5&spx=%2F#QR-Test-ecqo6qcp
![Screenshot_20240511_164954_Firefox](https://github.com/2dust/v2rayNG/assets/68426583/84fdf952-0024-4639-9462-2a061e7f7382)

**Comment by dani96102** [comment]
MHsanaei/3x-ui said the problem is because of the dark panel theme is not supported by v2ray programs.  Please solve this problem in the next updates in V2rayNG and V2rayN.

**Comment by 2dust** [comment]
Please scan with camera first
