### ISSUE TITLE
关于使用自定义配置（custom config）的重要提示

### ISSUE THREAD

**Issue by IceCodeNew** [2dust/v2rayNG#311]
提这个 issue 是希望开发者能考虑把这个 issue 置顶，免得其他用自定义配置的人继续走弯路。

refer：https://github.com/2dust/v2rayNG/issues/307#issuecomment-598658229

因为 4.22.1 内核开始支持 DOH，所以我也开始动了自定义配置的想法，然而写好配置以后发现 PC 上 V2rayN 客户端能通，但是安卓上 V2rayNG 怎么都连不上。
后来先扫二维码重新添加了同样的服务器，再导出完整配置出来与我写的配置进行比较，最后一点一点排除找到了造成问题的原因：inbounds 里缺少名为 http 和 socks 的 tag 会导致安卓上自定义配置虽然连接服务器成功，但是实际上不会有任何流量正确走 socks/http 代理。
这个小细节花去了我半天时间，希望后面的人不会再走这个弯路。

**Comment by 4piu** [comment]
Thanks for the tip. I also found the speed display only works if the mentioned two tags exist.

**Comment by yuhan6665** [comment]
#363 will warn you if you don't have tags in custom config. Plus you will be able to define any custom name for the tag.

**Comment by IceCodeNew** [comment]
> #363 will warn you if you don't have tags in custom config. Plus you will be able to define any custom name for the tag.

Good works, thanks for your contribution!

**Comment by rurirei** [comment]
> #363 will warn you if you don't have tags in custom config. Plus you will be able to define any custom name for the tag.

how about query the first outbound of vmess, etc protocol?
