### ISSUE TITLE
能否考虑更换测试URL

### ISSUE THREAD

**Issue by axuanqwq** [2dust/v2rayNG#3110]
v2rayng目前默认测试URL为https://www.google.com/generate_204
在部分特定环境下，如使用中国大陆境内节点，将会出现无法测试的情况，能否考虑更换为以下列其一测试链接，可以解决此问题
https://www.gstatic.com/generate_204
https://www.apple.com/library/test/success.html
我个人认为后者(apple)更佳，望作者考虑采纳

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/commit/f0f9da0f1b8f4cc3cf4a1eaff6f55b3ad6f2a050

**Comment by axuanqwq** [comment]
请问是否可以考虑更改默认URL为gstatic呢？让用户自定义不能从根原上解决这种"小白"问题。

**Comment by 2dust** [comment]
你是否已经会用了？

**Comment by axuanqwq** [comment]
"我"会用，但不见得"聪明"的用户会用，他们更相信v2rayNG上的延迟测试，但在特定情况（如使用中国大陆节点），使用www.google.com/generate_204会导致无法测试延迟。

**Comment by 2dust** [comment]
你考虑的是小白，开发者考虑的是所有用户，所以要取一个中庸的方案
方案一，默认值和以前一致，如果有需要的用户自行输入更改
方案二，默认值和以前一致，如果有需要的用户自行从列表中选择一个
方案二，默认值改成CDN URL（比如cloudflare)，如果有需要的用户自行输入更改

**Comment by axuanqwq** [comment]
我认为，将www.google.com改为www.gstatic
.com即可，两者均为Google官方服务，两者区别在于后者可以在中国大陆网络环境下正常测试真链接延迟，而海外网络两者体验均为一致。

我认为这是一个再合理且正确的解决方案，不会对任何正常用户造成影响，同时可以兼顾特殊用途下用户的使用体验。

望采纳。

**Comment by 2dust** [comment]
下一版发布默认 https://www.gstatic.com/generate_204
看看用户的反馈

**Comment by axuanqwq** [comment]
感谢采纳意见。

**Comment by Phoenix-999** [comment]
Users who use the V2rayNG application to access unrestricted internet, and encounter a connection error in the lower status section of the application after updating to version 1.8.25 or 1.8.24, even though your connection is correctly established and your VPN is working well, but still face this error when trying to obtain the ping status, please follow the instructions below to resolve this issue.

`"Fail to detect internet connection: io: read/write on closed pipe"`

Steps to Resolve the Issue:
Open the V2rayNG application and go to the `settings` by clicking on the hamburger menu at the top right corner.
Scroll to the bottom of the settings page and select "`Advanced settings.`"
In this section, find the option "`True delay test URL (http/https)`" and click on it to open a small window.
As you will see, the following URL is displayed:

`https://www.gstatic.com/generate_204`
Delete this URL and replace it with the following link:
`https://www.google.com/generate_204`

Click the OK button, then restart the application. Perform the connection status test again to ensure the application is working correctly. After clicking on the status bar at the bottom of the screen, you should see the ping number.

Please note, friends who are not facing this issue do not need to change this setting.
![Wrong displays status - V2rayNG](https://github.com/2dust/v2rayNG/assets/127796122/e6ea3c56-1960-4eda-9f72-7afe37578c15)
