### ISSUE TITLE
Version 1.8.23 takes longer to connect (comparing to 1.8.22)

### ISSUE THREAD

**Issue by SaeedKhalifi** [2dust/v2rayNG#3114]
Hello there and thank you for this nifty software.
Version 1.8.23 takes longer to connect to different configurations (VLESS, VMESS, ...). Also the connection speed is slower compared to 1.8.22.
Thanks in advance

**Comment by Mozafar2024** [comment]
Mozi3kaloo

**Comment by Mozafar2024** [comment]
### mozi3kaloo

**Comment by Mozafar2024** [comment]
Mozafar
