### ISSUE TITLE
分应用代理和绕过大陆地址同时使用的相关问题

### ISSUE THREAD

**Issue by bigdeeer** [2dust/v2rayNG#312]
系统：
LG-V30 (LGM-V300L) Android 9.0
LG-G4 (LG-F500K)  Android 7.0

设置：
分应用代理开启，并设定为绕行模式。
淘宝微信QQ均绕行
谷歌全家桶包括chrome浏览器不绕行。
预定义规则设定为“绕过局域网和大陆地址”。

预期：
1.
国产软件全部不代理
2.
chrome浏览器走代理
但是大陆网站例如百度不代理

实际情况：
1.
国产软件全部不代理
2.
chrome浏览器走代理
大陆网站例如百度也走了代理，导致速度很慢

疑惑：
对于预定义规则我不太理解。
预定义规则实际作用是什么？
预定义规则和分应用代理互相之间是什么关系？

问题：
如何让chrome浏览器实现“预定义规则”？
也就是大陆网站不代理，非大陆网站走代理？

谢谢！

**Comment by pcdogyu** [comment]
增加domain:baidu.com 直连

[cid:image001.png@01D5FA2E.7BD6C510]

**Comment by bigdeeer** [comment]
> 增加domain:baidu.com 直连 [cid:image001.png@01D5FA2E.7BD6C510]

也就是说预定义规则是没有用的，我必须给每个chrome使用的国内网站加上domain设定？

**Comment by junjieyuan** [comment]
需要再开启“启用本地DNS”。
