### ISSUE TITLE
请教 | 想仅代理特定的域名，其他域名全部走直连，应该如何设置？

### ISSUE THREAD

**Issue by thomasTAT** [2dust/v2rayNG#3125]
想实现类似V2RAYN windows 上的这个功能：
![image](https://github.com/2dust/v2rayNG/assets/109513632/0b1362c4-1ae6-4ae1-aa81-5073c43be333)

人在香港，不需要代理那么多网站，只想代理特定domain。

**Comment by 2dust** [comment]
设置中预定义规则选择全局直连
自定义中增加你的特定domain

**Comment by thomasTAT** [comment]
改成全局直连之后，无法连上互联网。
![image](https://github.com/2dust/v2rayNG/assets/109513632/8be0f466-5d2c-4b06-b382-c2c805b1c4ef)

**Comment by 2dust** [comment]
自定义中增加你的特定domain
自定义中增加你的特定domain
自定义中增加你的特定domain
包括测试的地址google
