### ISSUE TITLE
mux does not set correctly from menu setting

### ISSUE THREAD

**Issue by mr-shunshine** [2dust/v2rayNG#3135]
After enabling MUX in the menu settings and entering the TCP connection and UDP (default value is 8), the settings are not applied correctly. For example, if you set the value to 8, when you export the full configuration, the JSON file shows that "concurrency" and "xudpConcurrency" are not set to 8; they are set to 1 instead.

**Comment by 2dust** [comment]
version?

**Comment by mr-shunshine** [comment]
i  tested on version 1.8.23 and 1.8.24

**Comment by 2dust** [comment]
Uninstalling the app and reinstalling it, does it still happen
