### ISSUE TITLE
v2rayNG 1.8.24 - Bug Report 

### ISSUE THREAD

**Issue by Phoenix-999** [2dust/v2rayNG#3141]
Hi @2dust 
Firstly, thank you for your ongoing dedication to enhancing this excellent application.

After the latest update of v2rayNG 1.8.24, I noticed a bug.
Despite a successful connection, the bottom bar displays the status
"`Fail to detect internet connection: io: read/write on closed pipe,`" which is **inaccurate.**

![photo_5933575909191828200_y (1)](https://github.com/2dust/v2rayNG/assets/127796122/a852aca2-94a9-4dd4-88c3-e3724b90f4e7)

I have tested the connection thoroughly, and everything is functioning correctly, but the bottom bar continues to show this incorrect status despite the strong, **successful connection**.

![photo_5933575909191828199_y (1)](https://github.com/2dust/v2rayNG/assets/127796122/2e32d114-1e24-4e60-ad22-26afc7c82895)

I've cleared the app storage cache, but the bottom bar still displays the wrong status. Despite this, the proxy connection works correctly. I'm not sure if anyone else has encountered this issue, but I thought I should report it.

Thank you in advance.

**Comment by Adversary1337** [comment]
Same issue.
Despite a successful connection, the bottom bar displays the status "Fail to detect internet connection: io: read/write on closed pipe," or "net/http:TLS handshake timeout" which is inaccurate.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/3110

Change delayed test URL  https://www.google.com/generate_204

**Comment by mobagheri** [comment]
Hi. In the Beta version of v2RayNG, we have an EOF error in some connections, like Reverse Tls Tunnel. But it is correct in version 1.8.22. Please check the issue. Thanks.

**Comment by Phoenix-999** [comment]
@2dust 
Just an update: The issue persists in [v2rayNG version 1.8.25](https://github.com/2dust/v2rayNG/releases/tag/1.8.25) as well.

**Comment by mobagheri** [comment]
Yeah, the problem is continued in the 1.8.25 version. Other users and I are using the stable version 1.8.22 now.

**Comment by Phoenix-999** [comment]
@mobagheri

Thanks for your clarification, but we already know version 1.8.22 is stable and functioning properly. The issue of `"Fail to detect internet connection: io: read/write on closed pipe"` goes back to earlier discussions, which you can find [here](https://github.com/2dust/v2rayNG/issues/3110). This issue is caused by changing the delayed test URL to https://www.google.com/generate_204.

In some regions like China, it works without any problems, while in other regions it comes with errors. Just to clarify, I reported the bug to help improve this amazing application. As I mentioned before, the connection is successful, but the display bar is showing the wrong status in recent versions as explained above.

I hope that's clear.

**Comment by Phoenix-999** [comment]
Users who use the V2rayNG application to access unrestricted internet, and encounter a connection error in the lower status section of the application after updating to version 1.8.25 or 1.8.24, even though your connection is correctly established and your VPN is working well, but still face this error when trying to obtain the ping status, please follow the instructions below to resolve this issue.

`"Fail to detect internet connection: io: read/write on closed pipe"`

Steps to Resolve the Issue:
Open the V2rayNG application and go to the `settings` by clicking on the hamburger menu at the top right corner.
Scroll to the bottom of the settings page and select "`Advanced settings.`"
In this section, find the option "`True delay test URL (http/https)`" and click on it to open a small window.
As you will see, the following URL is displayed:

`https://www.gstatic.com/generate_204`
Delete this URL and replace it with the following link:
`https://www.google.com/generate_204`

Click the OK button, then restart the application. Perform the connection status test again to ensure the application is working correctly. After clicking on the status bar at the bottom of the screen, you should see the ping number.

Please note, friends who are not facing this issue do not need to change this setting.
![Wrong displays status - V2rayNG](https://github.com/2dust/v2rayNG/assets/127796122/e6ea3c56-1960-4eda-9f72-7afe37578c15)

**Comment by mobagheri** [comment]
> @mobagheri
> 
> Thanks for your clarification, but we already know version 1.8.22 is stable and functioning properly. The issue of `"Fail to detect internet connection: io: read/write on closed pipe"` goes back to earlier discussions, which you can find [here](https://github.com/2dust/v2rayNG/issues/3110). This issue is caused by changing the delayed test URL to https://www.google.com/generate_204.
> 
> In some regions like China, it works without any problems, while in other regions it comes with errors. Just to clarify, I reported the bug to help improve this amazing application. As I mentioned before, the connection is successful, but the display bar is showing the wrong status in recent versions as explained above.
> 
> I hope that's clear.

Thanks for your instructions. The problem had been identified and can now be easily fixed.

**Comment by mobagheri** [comment]
> Users who use the V2rayNG application to access unrestricted internet, and encounter a connection error in the lower status section of the application after updating to version 1.8.25 or 1.8.24, even though your connection is correctly established and your VPN is working well, but still face this error when trying to obtain the ping status, please follow the instructions below to resolve this issue.
> 
> `"Fail to detect internet connection: io: read/write on closed pipe"`
> 
> Steps to Resolve the Issue:
> Open the V2rayNG application and go to the `settings` by clicking on the hamburger menu at the top right corner.
> Scroll to the bottom of the settings page and select "`Advanced settings.`"
> In this section, find the option "`True delay test URL (http/https)`" and click on it to open a small window.
> As you will see, the following URL is displayed:
> 
> `https://www.gstatic.com/generate_204`
> Delete this URL and replace it with the following link:
> `https://www.google.com/generate_204`
> 
> Click the OK button, then restart the application. Perform the connection status test again to ensure the application is working correctly. After clicking on the status bar at the bottom of the screen, you should see the ping number.
> 
> Please note, friends who are not facing this issue do not need to change this setting.
> ![Wrong displays status - V2rayNG](https://github.com/2dust/v2rayNG/assets/127796122/e6ea3c56-1960-4eda-9f72-7afe37578c15)
> 
> 

Thanks a lot. Your instructions are complete. We appreciate your time and efforts.

**Comment by Phoenix-999** [comment]
You can also us url below for True delay test 

### Google's URLs:
 - http://clients3.google.com/generate_204
 - http://www.gstatic.com/generate_204

### Cloudflare's URL:
- http://cp.cloudflare.com/

### Microsoft's URL:
- http://www.msftconnecttest.com/connecttest.txt

### Apple's URL:
-http://captive.apple.com/hotspot-detect.html

### Xiaomi's URL:
-http://connect.rom.miui.com/generate_204

### Samsung's URL:
-http://clients3.samsung.com/generate_204

**Comment by X-Oracle** [comment]
@Phoenix-999 

I suggest you troubleshoot `https://www.gstatic.com/generate_204`
connectivity with tools like curl and see if you get status 204.

If the connection succeeded then it is v2rayng problem if not then it is server side.

As you succeeded to connect with `https://www.google.com/generate_204`
I can say these might be the problem:

Your server blocks gstatic.com

Your VPS provider blocked gstatic.com

gstatic.com blocked your VPS IP

You have some xray rules blocking gstatic.com.

Your dns server can't resolve gstatic.com.


I said it because both gstatic and Google is the same and if v2rayng had a problem with gstatic then it should not be able to connect to Google to.

Good luck.
