### ISSUE TITLE
开启连接到第二天早上会出现无法解析域名

### ISSUE THREAD

**Issue by xingzhuanxing** [2dust/v2rayNG#315]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常连接服务器，正常转发数据

### 实际行为
实际上挂机一个晚上后，ip方式访问的可以转发，域名方式访问提示无法解析。

### 复现方法
1.长时间启用连接
2.达到一定时间的挂机休眠，我是大概4-5个小时出现问题
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by cpstar** [comment]
我在bifrostv出现了类似情况，华为
主要是是连接wifi（纯4G反而不发生），有休眠，然后不光是域名问题，直接到console进行ping，直接报connect: Try again，好似网络直接没有了，开飞行之后再回来才可以。

**Comment by xingzhuanxing** [comment]
> 我在bifrostv出现了类似情况，华为
> 主要是是连接wifi（纯4G反而不发生），有休眠，然后不光是域名问题，直接到console进行ping，直接报connect: Try again，好似网络直接没有了，开飞行之后再回来才可以。

我刚才又出现了一次。 主进程被系统Kill了，vpn进程还在但是无法解析域名访问外网，ip访问外网没问题

**Comment by xingzhuanxing** [comment]
又是一个早上，无法解析域名，Ip正常访问；查看日志出现大量的Not Using Prepared

**Comment by xingzhuanxing** [comment]
发现解析域名失败是由于udp问题引起，日志内没有转发 udp 到 1.1.1.1的任何记录。也没有udp相关的其他转发

**Comment by xingzhuanxing** [comment]
![15847576473025930175632980464217](https://user-images.githubusercontent.com/27891303/77217596-aa828600-6b5e-11ea-9d80-05905a8b69b9.jpg)
