### ISSUE TITLE
Partial Import of nodes from subscription

### ISSUE THREAD

**Issue by xxamr** [2dust/v2rayNG#3153]
Hi
I have created subscription for my users, each subscription contains 4 "Connection Link"
Every link is entered in a seperate line and then ebcoded in Base64
It is working perfect in all iOS apps like v2box, Streisand  and etc. 
But when using these subscription urls is v2rayng, it only imports the two first links available in subscription and the other two does not import. 

What shall I do?

**Comment by dbb987** [comment]
Debugging and packaging always report an error: Unresolved reference: libv2ray. If you put the old aar in the libs directory, you can build and install it on your mobile phone, but you get an error when you start it. Do you need to turn the libtun2socks.so dynamic library into aar to use this project? Or is there an interface name mismatch in libtun2socks.so at present?
