### ISSUE TITLE
使用Socks的时候，报错io:read/write on closed pipe

### ISSUE THREAD

**Issue by gaoqionglou** [2dust/v2rayNG#3157]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
预期可以正常链接，能上google. 

### 实际行为
报错io:read/write on closed pipe

### 复现方法
1. 右上角+号，选择手动输入[Socks]
2. 填写IP和端口
3. 启动

### 日志信息
--------- beginning of main
05-23 14:44:56.340 I/GoLog   ( 4349): loading v2ray config
05-23 14:44:56.340 I/GoLog   ( 4349): Preparing Domain: 43.***.**.199:10052
05-23 14:44:56.340 I/GoLog   ( 4349): Prepare Result:
05-23 14:44:56.340 I/GoLog   ( 4349):  Domain: 43.***.**.199
05-23 14:44:56.340 I/GoLog   ( 4349):  Port: 10052
05-23 14:44:56.340 I/GoLog   ( 4349):  IPs: [43.***.**.199]
05-23 14:44:56.341 I/GoLog   ( 4349): new v2ray core
05-23 14:44:56.341 I/GoLog   ( 4349): start v2ray core
05-23 14:44:56.342 I/GoLog   ( 4349): [Warning] v2ray.com/core: V2Ray 4.23.1 started
05-23 14:44:56.405 D/com.v2ray.ang( 4349): [/data/app/~~vKtNlwxbil2D79UXRUY8iw==/com.v2ray.ang-qjGMf0MUk4zmW_L9C_sKKw==/lib/x86_64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --dnsgw, 127.0.0.1:10853]
05-23 14:44:56.406 D/com.v2ray.ang( 4349): Process[pid=5453, hasExited=false]
05-23 14:44:56.406 D/com.v2ray.ang( 4349): /data/user/0/com.v2ray.ang/files/sock_path
05-23 14:44:56.450 I/tun2socks( 5453): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
05-23 14:44:56.457 D/com.v2ray.ang( 4349): sendFd tries: 0
05-23 14:44:56.458 I/tun2socks( 5453): NOTICE(tun2socks): entering event loop
05-23 14:44:56.470 I/GoLog   ( 4349): tcp:127.0.0.1:59830 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59820 accepted tcp:172.217.160.106:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59826 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59828 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59832 accepted tcp:172.217.163.42:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59814 accepted tcp:172.217.163.42:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59836 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59818 accepted tcp:142.251.42.234:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59824 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59822 accepted tcp:172.217.160.106:443 [proxy] 
05-23 14:44:56.472 I/GoLog   ( 4349): tcp:127.0.0.1:59834 accepted tcp:142.251.42.234:443 [proxy] 
05-23 14:44:56.536 I/GoLog   ( 4349): tcp:127.0.0.1:59862 accepted tcp:114.250.48.139:443 [proxy] 
05-23 14:44:56.709 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.716 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.717 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.717 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.717 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.717 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.719 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.719 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.721 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.721 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.722 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.783 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:56.955 I/GoLog   ( 4349): [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.963 I/GoLog   ( 4349): [Warning] [2991113379] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.963 I/GoLog   ( 4349): [Warning] [3570095032] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.963 I/GoLog   ( 4349): [Warning] [1924279789] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.964 I/GoLog   ( 4349): [Warning] [120309428] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.964 I/GoLog   ( 4349): [Warning] [2129657481] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.966 I/GoLog   ( 4349): [Warning] [4218456258] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.968 I/GoLog   ( 4349): [Warning] [1279161359] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.970 I/GoLog   ( 4349): [Warning] [651038441] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:56.971 I/GoLog   ( 4349): [Warning] [816177461] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.033 I/GoLog   ( 4349): [Warning] [1261658752] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.036 I/GoLog   ( 4349): tcp:127.0.0.1:59870 accepted tcp:114.250.48.139:443 [proxy] 
05-23 14:44:57.219 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.282 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.451 I/GoLog   ( 4349): tcp:127.0.0.1:59884 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:57.452 I/GoLog   ( 4349): tcp:127.0.0.1:59882 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:57.452 I/GoLog   ( 4349): tcp:127.0.0.1:59878 accepted tcp:172.217.160.106:443 [proxy] 
05-23 14:44:57.452 I/GoLog   ( 4349): tcp:127.0.0.1:59880 accepted tcp:172.217.163.42:443 [proxy] 
05-23 14:44:57.452 I/GoLog   ( 4349): tcp:127.0.0.1:59876 accepted tcp:26.26.26.2:853 [proxy] 
05-23 14:44:57.468 I/GoLog   ( 4349): [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.470 I/GoLog   ( 4349): tcp:127.0.0.1:59896 accepted tcp:172.217.160.74:443 [proxy] 
05-23 14:44:57.529 I/GoLog   ( 4349): [Warning] [1637718241] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.535 I/GoLog   ( 4349): tcp:127.0.0.1:59902 accepted tcp:114.250.48.139:443 [proxy] 
05-23 14:44:57.671 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.698 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.699 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.699 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.699 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.717 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.728 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:57.755 I/GoLog   ( 4349): tcp:127.0.0.1:59908 accepted tcp:172.217.160.106:443 [proxy] 
05-23 14:44:57.838 I/GoLog   ( 4349): tcp:127.0.0.1:59914 accepted tcp:142.251.42.234:443 [proxy] 
05-23 14:44:57.880 I/GoLog   ( 4349): tcp:127.0.0.1:59920 accepted tcp:142.251.42.234:443 [proxy] 
05-23 14:44:57.920 I/GoLog   ( 4349): [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.920 D/com.v2ray.ang( 4349): measureV2rayDelay: Get http://www.google.com/gen_204: io: read/write on closed pipe
05-23 14:44:57.946 I/GoLog   ( 4349): [Warning] [3889683109] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.946 I/GoLog   ( 4349): [Warning] [490656972] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.947 I/GoLog   ( 4349): [Warning] [607792550] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.950 I/GoLog   ( 4349): [Warning] [2433806374] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:57.952 I/GoLog   ( 4349): tcp:127.0.0.1:59926 accepted tcp:172.217.160.106:443 [proxy] 
05-23 14:44:57.977 I/GoLog   ( 4349): [Warning] [3577944056] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.002 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.085 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.128 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.156 I/GoLog   ( 4349): tcp:127.0.0.1:59932 accepted tcp:172.217.163.42:443 [proxy] 
05-23 14:44:58.207 I/GoLog   ( 4349): tcp:127.0.0.1:59938 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:58.218 I/GoLog   ( 4349): tcp:127.0.0.1:59944 accepted tcp:172.217.163.42:443 [proxy] 
05-23 14:44:58.226 I/GoLog   ( 4349): tcp:127.0.0.1:59950 accepted tcp:142.251.42.234:443 [proxy] 
05-23 14:44:58.253 I/GoLog   ( 4349): [Warning] [3529009127] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.272 I/GoLog   ( 4349): tcp:127.0.0.1:59956 accepted tcp:172.217.163.42:443 [proxy] 
05-23 14:44:58.335 I/GoLog   ( 4349): [Warning] [2366680868] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.374 I/GoLog   ( 4349): tcp:127.0.0.1:59962 accepted tcp:142.251.43.10:443 [proxy] 
05-23 14:44:58.375 I/GoLog   ( 4349): [Warning] [2561818887] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.404 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.464 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.473 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.476 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.523 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.626 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.705 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.715 I/GoLog   ( 4349): [Warning] [1764900702] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.727 I/GoLog   ( 4349): [Warning] [403560778] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.774 I/GoLog   ( 4349): [Warning] [367466472] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:58.786 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:58.880 I/GoLog   ( 4349): [Warning] [4071413095] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.036 I/GoLog   ( 4349): [Warning] [2961641962] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.041 I/GoLog   ( 4349): tcp:127.0.0.1:59968 accepted tcp:114.250.48.139:443 [proxy] 
05-23 14:44:59.200 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:59.243 I/GoLog   ( 4349): [Warning] [4108272201] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.249 I/GoLog   ( 4349): tcp:127.0.0.1:59974 accepted tcp:172.217.160.74:443 [proxy] 
05-23 14:44:59.295 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:59.449 I/GoLog   ( 4349): [Warning] [553004036] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.504 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:59.548 I/GoLog   ( 4349): [Warning] [2607338511] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.556 I/GoLog   ( 4349): tcp:127.0.0.1:59980 accepted tcp:114.250.48.139:443 [proxy] 
05-23 14:44:59.567 I/GoLog   ( 4349): tcp:127.0.0.1:59986 accepted tcp:120.78.74.132:8080 [proxy] 
05-23 14:44:59.752 I/GoLog   ( 4349): [Warning] [3850381326] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.758 I/GoLog   ( 4349): [Warning] [4263598434] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.804 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:59.817 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:44:59.892 I/GoLog   ( 4349): tcp:127.0.0.1:59992 accepted tcp:172.217.160.106:443 [proxy] 
05-23 14:44:59.913 I/GoLog   ( 4349): [Warning] [2000441615] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:44:59.980 I/GoLog   ( 4349): [Warning] [2416699637] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:45:00.044 I/GoLog   ( 4349): [Warning] [3806441832] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:45:00.047 I/GoLog   ( 4349): tcp:127.0.0.1:59998 accepted tcp:114.250.48.139:443 [proxy] 
05-23 14:45:00.062 I/GoLog   ( 4349): [Warning] [2992025015] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: unexpected server version: 72
05-23 14:45:00.125 I/GoLog   ( 4349): Using Prepared: 43.***.**.199
05-23 14:45:00.204 D/com.v2ray.ang( 4349): tun2socks destroy
05-23 14:45:00.204 I/tun2socks( 5453): NOTICE(tun2socks): termination requested
05-23 14:45:00.204 I/tun2socks( 5453): NOTICE(tun2socks): tearing down
05-23 14:45:00.205 I/tun2socks( 5453): NOTICE(tun2socks): Free TCP connections
05-23 14:45:00.205 I/tun2socks( 5453): NOTICE(tun2socks): exiting
05-23 14:45:00.288 I/GoLog   ( 4349): Using Prepared: 43.***.**.199

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
IP 端口已排查无问题，能连通。

**Comment by FranzKafkaYu** [comment]
@gaoqionglou similiar issue:https://github.com/v2fly/v2ray-core/issues/2619

**Comment by linhongjun** [comment]
前一个版本正常，更新版本后出现此问题 1.8.24
