### ISSUE TITLE
在已连接代理的情况下更新订阅，主界面代理选择出错

### ISSUE THREAD

**Issue by chara26** [2dust/v2rayNG#316]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
订阅后选择的绿色标志应留在你已链接的服务器上

### 实际行为
绿色标志一到第一个服务器

### 复现方法
1.在已连接代理的情况下订阅
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
#335 should fix it.
