### ISSUE TITLE
Import sub failure when using cdn in subscription domain!

### ISSUE THREAD

**Issue by banisaeed** [2dust/v2rayNG#3171]
Deleted...

**Comment by pulsarice** [comment]
Have you set a minimum TLS version (like 1.3) on your CDN?

**Comment by banisaeed** [comment]
> Have you set a minimum TLS version (like 1.3) on your CDN?

Yes, I use TLS 1.3!

**Comment by pulsarice** [comment]
try TLS 1.2 and see if it helps
