### ISSUE TITLE
v2flyNG延迟检验错误

### ISSUE THREAD

**Issue by Makitoid** [2dust/v2rayNG#3178]
我没找到flyNG的反馈通道，但考虑到两个软件用的同样的UI，应该都有这个问题

### 预期行为
真连接测试应该都为有效
协议都是shadowsocket，Haita Cloud(https://haita.link)

### 实际行为
而程序显示tls handshake error

### 环境信息
Android10

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/3141
参考下

**Comment by Makitoid** [comment]
好的，谢谢你的帮助
