### ISSUE TITLE
Update Subscription Failure 

### ISSUE THREAD

**Issue by ImMahdi** [2dust/v2rayNG#3181]
Hi 
I can add subscription link but when I want to update it , it fail. I try 1.8.22-24-25 and both arm v7 and v8 but not working .
Phone : Honor 6X - Android 7

https://github.com/2dust/v2rayNG/assets/98653839/9fecb494-db54-4ee6-ab6e-a7b4ddb7d640

**Comment by 2dust** [comment]
If you use a free subscription, please send the address

**Comment by ImMahdi** [comment]
> If you use a free subscription, please send the address

Sorry but it's not free. but it's not for the subscription because I test it on newer mobile and worked but again in the older device it fail.

Also I use other subscription and didn't work.

**Comment by pulsarice** [comment]
Some older mobile phones don't work with Let's Encrypt issued certificates.
@2dust 
Is it a good idea to add an Allow Insecure option for subscription updates?

**Comment by 2dust** [comment]
log

**Comment by sobhankazemi** [comment]
facing the same issue when trying to update the subscription on an android 7.0 phone.
