### ISSUE TITLE
Socket5协议无法使用

### ISSUE THREAD

**Issue by CoderCore** [2dust/v2rayNG#319]
点击左下角测试显示连接成功，但实际任何应用都无法连接网络。

**Comment by CoderCore** [comment]
补充一下，我连接的SOCK5 ip是内网IP

**Comment by heheheaa** [comment]
我也遇到这问题，有的软件可以，有的不可以

**Comment by zhezh** [comment]
same here，猜测是dns的问题，但是不知如何解决。 pc端是可以直接用socks5的
