### ISSUE TITLE
自用服务器测试延迟为-1ms

### ISSUE THREAD

**Issue by demo0102** [2dust/v2rayNG#319]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
自用服务器配置测试延迟正常
### 实际行为
描述实际发生了什么
自用服务器右上角测试延迟为－1ms，实际使用正常，连接后点击下方测试延迟正常，右上角测试仍为－1ms
### 复现方法
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "1.1.1.1",
      {
        "address": "223.5.5.5",
        "domains": [
          "geosite:cn"
        ],
        "port": 53
      }
    ]
  },
  "inbounds": [
    {
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": false
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10807,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "1.1.1.1",
        "network": "tcp,udp",
        "port": 53
      },
      "tag": "dns-in"
    }
  ],
  "log": {
    "loglevel": "warning"
  },
  "outbounds": [
    {
      "mux": {
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "",
            "port": 33485,
            "users": [
              {
                "alterId": 32,
                "id": "",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "kcpsettings": {
          "congestion": false,
          "downlinkCapacity": 100,
          "header": {
            "type": "wechat-video"
          },
          "mtu": 1350,
          "readBufferSize": 1,
          "tti": 50,
          "uplinkCapacity": 12,
          "writeBufferSize": 1
        },
        "network": "kcp",
        "security": ""
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 60,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "dns-in"
        ],
        "outboundTag": "dns-out",
        "type": "field"
      },
      {
        "ip": [
          "1.1.1.1"
        ],
        "outboundTag": "proxy",
        "port": "53",
        "type": "field"
      },
      {
        "ip": [
          "223.5.5.5"
        ],
        "outboundTag": "direct",
        "port": "53",
        "type": "field"
      },
      {
        "domain": [
          "domain:googleapis.cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "stats": {}
}

以上为我的配置文件省去ip和userID，在另一台设备上测试结果相同，机场的ws梯子正常，是不是kcp协议问题

**Comment by xianren78** [comment]
用的tcping测速，kcp用的udp

**Comment by demo0102** [comment]
> 用的tcping测速，kcp用的udp
那是否可以加一个判断呢？检测是kcp就用udpping测速，其他用tcpping测速

**Comment by 2dust** [comment]
现在NG用的socks连接多次的方式来测试速度,只能表示此目标端口可用否,并不准备
