### ISSUE TITLE
请问Geo全家桶指的是？

### ISSUE THREAD

**Issue by ihcbbs** [2dust/v2rayNG#32]
如题，路由模式中的 Geo全家桶，这个描述实在让人摸不着头脑。
我知道core内置了各国ip段和本地ip段，以geo：开头。
但是这个全家桶指的是？
绕过中国？绕过除中国外所有国家？绕过所有国家？绕过美国？
我在github搜索也没有信息。
希望能得到解答！

**Comment by valn97** [comment]
同问

**Comment by 2dust** [comment]
https://github.com/KafuuChinoQ/V2RayGeoKit
看这里,合并gfw和surge规则

**Comment by ihcbbs** [comment]
看到了，谢谢！

**Comment by c1024** [comment]
用这个到底有什么好处？看了那个项目，不是太明白

**Comment by 2dust** [comment]
能去部分广告,更精准判断国内外域名

**Comment by c1024** [comment]
稍微看了一下工程代码，如果是导入自定义配置，使用websocket+ tls,应该是没有办法使用这个是吧

**Comment by 2dust** [comment]
可以用,但是要自己写rule,要写对

**Comment by kirbyzhu** [comment]
这个全家桶直接选取了就可以生效？

**Comment by sjx95** [comment]
乍一看还是莫名其妙，来 issue 看了才看明白，如果可以的话希望能在 APP 中加上一点说明。

**Comment by thank243** [comment]
今天试了下geo全家桶,,似乎只是绕过中国地址.国外ip全程代理

**Comment by wsdd977** [comment]
用了分应用代理模式代理了全部google的APP 路由加了services.googleapis.cn 添加谷歌账号时候就显示通讯问题 关了分应用模式就没事
