### ISSUE TITLE
Mux自定義連接術與配置中不匹配

### ISSUE THREAD

**Issue by rootmelo92118** [2dust/v2rayNG#3216]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
在設置中啟用Mux並將TCP與XUDP連接數設為1024，配置內Mux項也應為1024

### 实际行为
在設置中設置Mux為1024配置內Ｍux項無論TCP與XUDP項僅為4
在設置中設置Mux為9配置內Ｍux項無論TCP與XUDP項僅為1
在設置中設置Mux為90配置內Ｍux項無論TCP與XUDP項僅為2
（匯出完整配置檔得出此結果）

疑似判讀字串長度而非數字本身。

**Comment by 2dust** [comment]
自定義不受设置影响
