### ISSUE TITLE
"Connection":["keep-alive"] caused problem when using ipv6 on mci isp

### ISSUE THREAD

**Issue by kingjan123** [2dust/v2rayNG#3220]
Please troubleshoot server-side issues yourself before raising a question, and also search to see if anyone else has asked the same question.
**expected behavior**
connection should work in both ipv4 and ipv6
Describe what you think should happen
**actual behavio**r
when using ipv6 on mci (one of iran isps) the ipv6 connection didnt work
**describe what actually happened**
**Reproduction method**
make a server config with this inbound
`{"listen": null, "port": 8004, "protocol": "vmess", "settings": {"clients": [{"email" : "example@example.com", "id" : "UR_UUID"}], "disableInsecureEncryption": false}, "streamSettings": {"network": "tcp", "security": "none", "tcpSettings": {"header": {"type": "http", "request": {"method": "GET", "path": ["/"], "headers": {"Host": ["fast.com"], "Connection":["keep-alive"]}}, "response": {"version": "1.1", "status": "200", "reason": "OK", "headers": {}}}}}, "tag": "vmess", "sniffing": {"destOverride": ["http", "tls", "quic"], "enabled": true}}`
if u share the config on v2rayng [this line](https://github.com/2dust/v2rayNG/blob/1363846ac42d37c8ab5eb118aa134a42f4419cf5/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L551) adds "Connection":["keep-alive"] to client xray core's config and for this reason and some how the ipv6 version of config not works
when i copy the config and remove that header then i add it again to v2rayng the config works fine
**Log information**
**environmental information**
**Additional information (optional)**
what is the purpose of the mentioned line? why v2rayng adds this lines to core configs?

**Comment by mahdisalehivand** [comment]
I have this problem for two months now, exactly with mci
Hasn't a solution been found?

**Comment by 2dust** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive
