### ISSUE TITLE
编译出Core 4.22.1版本，无法正确加载geoip.dat和geosite.dat

### ISSUE THREAD

**Issue by xingzichen** [2dust/v2rayNG#323]
### 预期行为
成功加载json配置文件并连接成功

### 实际行为
加载配置文件时报geoip 和 geosite无法解析

### 复现方法
1. 使用1.0.2版本脚本编译AndroidLibV2ray，得到core版本为4.22.1的aar
2.调用runloop接口

### 日志信息
<details>

```
2020-03-20 01:02:13.240 15733-15793/***** I/GoLog: EscortRun Waiting....
2020-03-20 01:02:13.423 15733-15733/***** I/GoLog: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > proto: can't skip unknown wire type 6
2020-03-20 01:02:13.424 15733-15733/***** D/com.****.vpn: go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to load GeoIP: private > proto: can't skip unknown wire type 6
2020-03-20 01:02:18.069 15733-15733/***** D/AwareBitmapCacher: handleInit disable *****
```
</details>

### 环境信息
配置信息如下
```
{
	"dns": {
		"hosts": {
			"domain:googleapis.cn": "googleapis.com"
		},
		"servers": ["8.8.8.8", {
			"address": "114.114.114.114",
			"domains": ["geosite:cn"],
			"port": 53
		}]
	},
	"outbounds": [{
			"此处省略": "此处省略",
			"tag": "proxy"
		},
		{
			"protocol": "freedom",
			"settings": {},
			"tag": "direct"
		}, {
			"protocol": "blackhole",
			"settings": {
				"response": {
					"type": "http"
				}
			},
			"tag": "block"
		}, {
			"protocol": "dns",
			"tag": "dns-out"
		}
	],
	"inbounds": [{
		"port": 10808,
		"protocol": "socks",
		"settings": {
			"auth": "noauth",
			"udp": true,
			"userLevel": 8
		},
		"sniffing": {
			"destOverride": ["http", "tls"],
			"enabled": true
		},
		"tag": "socks"
	}, {
		"port": 10809,
		"protocol": "http",
		"settings": {
			"userLevel": 8
		},
		"tag": "http"
	}, {
		"port": 10807,
		"protocol": "dokodemo-door",
		"settings": {
			"address": "8.8.8.8",
			"network": "tcp,udp",
			"port": 53
		},
		"tag": "dns-in"
	}],
	"log": {
		"loglevel": "warning"
	},
	"policy": {
		"levels": {
			"8": {
				"connIdle": 300,
				"downlinkOnly": 1,
				"handshake": 4,
				"uplinkOnly": 1
			}
		},
		"system": {
			"statsInboundUplink": true,
			"statsInboundDownlink": true
		}
	},
	"stats": {}
}
```
### 额外信息（可选）
初步判断为加载geoip.dat和geosite.dat失败，因为当把上述配置文件中的含有geoip和geosite条目都去掉后，可以正常运行。
使用您项目中的当前版本（1.0.2）aar，使用上述配置能够正确加载，排除配置问题。
望不吝赐教～非常感谢

**Comment by xingzichen** [comment]
interact.go 的 initV2Env() 方法，assetperfix = "/dev/libv2rayfs0/asset" ，v2ray新版中传进来的是否还是这个路径前缀。如果不匹配的话，我怀疑这个可能会导致我这边加载assets下面的geoip.dat geosite.dat失败

**Comment by yuhan6665** [comment]
@xingzichen Can you unzip and verify the aar file you built doesn't have geoip and geosite dat file in assets folder?
I believe you need to change assetperfix to your local path

**Comment by xingzichen** [comment]
<img width="225" alt="Screenshot 2020-03-23 at 12 08 16 AM" src="https://user-images.githubusercontent.com/2193597/77442207-3af1ec80-6e25-11ea-92a4-f2e0d2e20f0a.png">
The aar has geoip and geosite dat file in assets.  I don't know what's the assetperfix stands for which folder : the folder of dat files when I build the aar  ?  Or the folder in the android system?

**Comment by xingzichen** [comment]
> @xingzichen Can you unzip and verify the aar file you built doesn't have geoip and geosite dat file in assets folder?
> I believe you need to change assetperfix to your local path

Or is there any way to test the interact.go in AndroidV2rayLib project? I can print logs in the initV2Env function. THX A LOT!

**Comment by yuhan6665** [comment]
@xingzichen I tried to build an aar
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/libv2ray.aar
Can you try if you see this problem with it?

**Comment by xingzichen** [comment]
> @xingzichen I tried to build an aar
> https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/libv2ray.aar
> Can you try if you see this problem with it?

Problem solved!!! How did u do that?  Just follow the .travis.yml ? Have u changed any code in the AndroidLibV2ray?
I really want to know what the mistake I have made... 
THX!!!   
xzc2116@gmail.com

**Comment by yuhan6665** [comment]
@xingzichen I just compile with plain Go.. I didn't change anything. I believe it will grab latest Core (4.23.1) but has obsolete geoip and geosite assets.
Yes, you better figure out how to build. You can try contact me via tg Yuhan6665

**Comment by WebDNAcorp** [comment]
2021-04-27 15:05:30.677 9666-9666/com.v2ray.ang I/GoLog: infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /system/bin/geoip.dat: no such file or directory
2021-04-27 15:05:30.677 9666-9666/com.v2ray.ang D/com.v2ray.ang: go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /system/bin/geoip.dat: no such file or directory


I'm getting this error while i have geopip.dat and geosite.dat in my asset folder

Please help me with this

![image](https://user-images.githubusercontent.com/76512992/116220303-2b508000-a76a-11eb-90a7-6904f450d774.png)

**Comment by yuhan6665** [comment]
/system/bin/geoip.dat.. the environment variable is not set?
https://github.com/2dust/v2rayNG/blob/9b8a810445c113fc2de9a31d113e343f2fe75647/AndroidLibV2rayLite/interact.go#L193
Note I recently change core to xray which updated it.
