### ISSUE TITLE
新版本的v2rayNG 在华为mate50手机和Matepadpad平板中，下拉状态栏的开关需要点击两次才能关闭

### ISSUE THREAD

**Issue by MC-1997** [2dust/v2rayNG#3231]
在给v2rayNG 在下拉状态栏里设置快捷开关后，每次关闭时，需要点击两下才能关闭

系统：HarmonyOS  4.2

设备：华为Mate50、华为Matepad2023

发生频率：总是

**Comment by 2dust** [comment]
华为你就放过它吧

**Comment by MC-1997** [comment]
好吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月22日(周六) 上午9:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [2dust/v2rayNG] 新版本的v2rayNG 在华为mate50手机和Matepadpad平板中，下拉状态栏的开关需要点击两次才能关闭 (Issue #3231)




 
华为你就放过它吧
