### ISSUE TITLE
subscription doesn't automatically updated immediately

### ISSUE THREAD

**Issue by AliM1988** [2dust/v2rayNG#3235]
In version 1.8.26, you mentioned:
After adding a new URL subscription, the subscription will be automatically updated immediately

It works just the subscription added via QRcode. If we add it directly via Subscription group setting, we still need to update it manually.

**Comment by 2dust** [comment]
If we add it directly via Subscription group setting, we still need to update it manually.

Considering that more than one subscription may be added here, please click on Update in the upper right corner when you are done adding it!
