### ISSUE TITLE
[Bug] wireguard protocol does not work for tunnel 

### ISSUE THREAD

**Issue by m0x61h0x64i** [2dust/v2rayNG#3252]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
Alright

### 预期行为
描述你认为应该发生什么
connect to internet using v2rayng wireguard protocol which is a tunnel config not a warp config

### 实际行为
v2rayng supports wireguard since 1.8.13 but it does not work for tunnel configs, but same config works well on wireguard app itself

### 复现方法
1. create a wireguard tunnel config
2. use wireguard config with wireguard app and make sure that it works
3. copy and paste the following v2rayng wireguard config into v2rayng and change the parameters with wireguard app config parameters:
`wireguard://GFgEN9sNFowxzoTIwXMnVyfLoJHoqw%2FmUXUa2GwYllw%3D@162.159.192.22:928?address=172.16.0.2%2F32%2C2606%3A4700%3A110%3A8f81%3Ad551%3Aa0%3A532e%3Aa2b3%2F128&reserved=240%2C48%2C254&publickey=bmXOC%2BF1FxEMF9dyiK2H5%2F1SUtzH0JuVo51h2wPfgyo%3D&mtu=1280#test`

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of main
--------- beginning of system
06-25 23:49:39.295 15775 15775 I GoLog   : loading core config
06-25 23:49:39.295 15775 15802 I GoLog   : Preparing Domain: ***.***.***:36012
06-25 23:49:39.303 15775 15802 I GoLog   : Prepare Result:
06-25 23:49:39.303 15775 15802 I GoLog   :  Domain: ***.***.***
06-25 23:49:39.303 15775 15802 I GoLog   :  Port: 36012
06-25 23:49:39.303 15775 15802 I GoLog   :  IPs: [***.***.17.35]
06-25 23:49:39.544 15775 15775 I GoLog   : new core
06-25 23:49:39.645 15775 15775 I GoLog   : start core
06-25 23:49:39.657 15775 15775 D com.v2ray.ang: [/data/app/~~jBWrMd8zEl3mr9mcKV4xbg==/com.v2ray.ang-WdqZyX3y0jgkT-f2q4KbnQ==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
06-25 23:49:39.659 15775 15775 D com.v2ray.ang: Process[pid=16824, hasExited=false]
06-25 23:49:39.659 15775 15775 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
06-25 23:49:39.660 15775 16825 D com.v2ray.ang: libtun2socks.so check
06-25 23:49:39.712 15775 15943 D com.v2ray.ang: sendFd tries: 0
06-25 23:49:40.133 15775 15811 I GoLog   : Not Using Prepared: tcp,tracking.intl.miui.com:443
06-25 23:49:46.603 15775 15943 D com.v2ray.ang: measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout
06-25 23:49:47.982 15775 15775 D com.v2ray.ang: tun2socks destroy
06-25 23:49:47.991 15775 16825 D com.v2ray.ang: libtun2socks.so exited
```
</details>

### 额外信息（可选）

Here is how i filled the v2rayng wireguard protocol parameters using working wg config parameters:
| v2rayng parameter | wg value | v2rayng value |
| --------------- | --------------- | --------------- |
| address   |wg config address  | wg config address   |
| port   | wg config port   |  wg config port   |
| SecretKey   | wg config interface privateKey (self generated)   | wg config interface privateKey   |
| PublicKey   | wg config interface PublicKey | wg config interface PublicKey   |
| reserved   | not available   | 0,0,0   |
| local address   | 10.8.0.2/32   | 10.8.0.2/32   |
| mtu   | 1420   | 1420   |

In v2rayng i have reserved parameter which i dont have it in wireguard app, so i used 0,0,0 and 1,2,3 and some random numbers which was working for warp configs but i still get "TLS handshake timeout" error.

I also tried using wg config peer publicKey as v2rayng parameter value but still gives error.
I also tried using wg server interface privateKey (using `wg show wg0  private-key`) and used it as v2rayng SecretKey value but still gives error.
I also tried all possible ways that u think u can place these keys as the parameters for v2rayng wireguard config but that didnt work.
**The wireguard protocol of v2rayng works for wg warp configs but it does not work for wg tunnel configs, thats all i understood.**

v2rayng version: `1.8.25`

**Comment by caliban511** [comment]
同样问题，折腾很久就是用不了。直接扫二维码得到的配置也用不了，提示：失败： net/http: TLS handshake timeout
