### ISSUE TITLE
EOF error in latest version

### ISSUE THREAD

**Issue by iamfarhad** [2dust/v2rayNG#3255]
hi

i got EOF error with latest version and i have not this error on 1.8.22

**Comment by saeedm1997** [comment]
It’s true, for some phones the latest version displays an EOF error. Please fix it as soon as possible with a new update. I receive this error with the following protocol: vless+tcp+tls+sni.

**Comment by iamfarhad** [comment]
what was the problem?
@2dust

**Comment by GeekSquirrel** [comment]
@iamfarhad 1.8.26 pre-release works for me
