### ISSUE TITLE
一直不稳定而且很慢请问是怎么回事？

### ISSUE THREAD

**Issue by LAlexandra01** [2dust/v2rayNG#326]
### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
一直很卡，用一小会就断了，试了换了账号，重新下载app，换了套餐，都不行

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ghost** [comment]
此问题与该软件无关。
一般是因为当地运营商的原因导致的。可能是对应代理服务器节点对当地运营商不友好。
也有可能是使用的单纯的vmess，没有任何伪装导致的被限速。当然，后者因素较低。
