### ISSUE TITLE
启用更新以及启用自动更新二者之间的关系问题

### ISSUE THREAD

**Issue by keengrass** [2dust/v2rayNG#3265]
在设置里已有订阅分组设置-自动更新的选项。
不太理解为什么在订阅分组设置-订阅编辑里还是会出现启用更新和启用自动更新这两个选项。
我的理解是设置里的这个是针对所有订阅都要自动更新的，而订阅分组设置里的是针对每一条订阅单独做的设置？不知道是否理解正确。
那么订阅编辑里启用更新和启用自动更新这两个选项的区别又是什么呢？
感觉软件在这个更新功能上带来了理解上的混乱。

**Comment by 2dust** [comment]
启用更新，开启后手工更新订阅和自动更新订阅才能生效
启用自动更新，在设置中开启了自动更新后，此属性开启时生效
