### ISSUE TITLE
手机版的log看不到和pc上那种域名地址，显示的都是ip，能不能修一下

### ISSUE THREAD

**Issue by 1265578519** [2dust/v2rayNG#327]
手机版的log看不到和pc上那种域名地址，显示的都是ip，能不能修一下

**Comment by yuhan6665** [comment]
If you turn on debug log you should see them:

> 05-29 23:06:18.182 23225-23434/? I/GoLog: [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 querying DNS for: www.google.com.
05-29 23:06:18.182 23225-23434/? I/GoLog: [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
05-29 23:06:18.182 23225-23434/? I/GoLog: [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
05-29 23:06:18.182 23225-23434/? I/GoLog: [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
05-29 23:06:18.182 23225-23434/? I/GoLog: [Info] v2ray.com/core/app/dispatcher: default route for udp:1.1.1.1:53
05-29 23:06:18.182 23225-23250/? I/GoLog: [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:MYSERVER:PORT
05-29 23:06:18.432 23225-23252/? I/GoLog: Using Prepared: MYSERVER
05-29 23:06:18.433 23225-23250/? I/GoLog: [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:1.1.1.1:53 via tcp:MYSERVER:PORT
05-29 23:06:18.752 23225-23361/? I/GoLog: [Info] v2ray.com/core/app/dns: UDP:1.1.1.1:53 got answere: www.google.com. TypeA -> [172.217.24.68] 567.009584ms
05-29 23:06:18.752 23225-23361/? I/GoLog: [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 updating IP records for domain:www.google.com.
05-29 23:06:18.752 23225-23361/? I/GoLog: [Info] v2ray.com/core/app/dns: UDP:1.1.1.1:53 got answere: www.google.com. TypeAAAA -> [[2404:6800:4005:802::2004]] 567.251042ms
05-29 23:06:18.753 23225-23361/? I/GoLog: [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 updating IP records for domain:www.google.com.
05-29 23:06:18.753 23225-23361/? I/GoLog: [Info] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:80
05-29 23:06:18.753 23225-23361/? I/GoLog: [Info] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:MYSERVER:PORT
05-29 23:06:19.055 23225-23250/? I/GoLog: Using Prepared: MYSERVER
05-29 23:06:19.056 23225-23361/? I/GoLog: [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to tcp:www.google.com:80 via tcp:MYSERVER:PORT
