### ISSUE TITLE
是否可以优化一下下拉栏里的图标状态判断逻辑？

### ISSUE THREAD

**Issue by wyfang** [2dust/v2rayNG#3277]
![Screenshot_2024-06-30-21-22-26-226_com android chrome-edit](https://github.com/2dust/v2rayNG/assets/17900420/90b82e32-74aa-4864-bbec-9a56978a7958)

当我开启v2ray时，在下拉的一段时间内（大约500ms至3秒）图标还是会处于未激活状态。

**Comment by 2dust** [comment]
启动需要时间，启动成功后才会变化
启动时间和你的资源文件大小有关，你看下自己设备上资源文件多大

**Comment by wyfang** [comment]
> 启动需要时间，启动成功后才会变化 启动时间和你的资源文件大小有关，你看下自己设备上资源文件多大

我指的是已经启动成功后。再下拉的时候。
