### ISSUE TITLE
wireguard ipv6订阅格式问题

### ISSUE THREAD

**Issue by congyong** [2dust/v2rayNG#3278]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
wire guard 订阅的IPV6 地址 应该带 []

### 实际行为
base64 订阅的地址 在app里没有 []

### 复现方法
1.手动创建一个 wireguard ipv6
2.复制链接  base64加密 ，结果存储到文件 作为订阅
3. 导入订阅即可复现

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

流程如下 先复制手动的wireguard 配置，得到 wireguard://xxx 格式 ，base64 后 存储到服务器文件  
当做订阅导入后 发现 IPV6地址 缺少 中括号 []，导致工作异常………   
图片如下 
![image](https://github.com/2dust/v2rayNG/assets/32157609/f0be02ae-e456-488d-915e-5a0a849ce8e2)

**Comment by 2dust** [comment]
在界面上显示的时候，ipv6是不需要`[]`
点击分享时，会自动在分享中加入`[]`

**Comment by congyong** [comment]
> 在界面上显示的时候，ipv6是不需要`[]`
> 
> 点击分享时，会自动在分享中加入`[]`

实际测试… 手动加上中括号 代理可以使用，不加上 ping 不通。

**Comment by 2dust** [comment]
那就不是订阅格式问题了，而是ipv6在连接时的问题
把你的配置分享出来

**Comment by congyong** [comment]
> 那就不是订阅格式问题了，而是ipv6在连接时的问题
> 
> 把你的配置分享出来

我做了个脚本 可以 自动更新 wireguard节点，原理是 用 warp IP优选工具 筛选可用的IP(这意味着和网络环境相关，配置给你未必能用) 
不过我可以 贴一下 

**_BUG 已确认 手动删除节点_**

制作订阅的流程为  把上述节点贴到A 文件中，  cat A | base64 > B 
将B的路径作为订阅节点

**Comment by 2dust** [comment]
确实有问题
配置文件中wireguard的endpoint是把address和port合并在一起的，不加[]会出错
你暂时自己先加上，等修复
