### ISSUE TITLE
困惑，一切都好，就是不能用 谷歌学术，但隔壁的行

### ISSUE THREAD

**Issue by wang20150419** [2dust/v2rayNG#328]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
   能上谷歌学术
### 实际行为
描述实际发生了什么
   无法使用谷歌学术。但同样的 vmess,  或者 ss 机场，用 kitsunebi 就可以。
### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by semilitrary** [comment]
IP问题

**Comment by MicePilot** [comment]
我也遇到了这个问题，是403拒绝访问，后来发现是谷歌把vps的ipv6地址给禁用了，我把服务器的ipv6禁用了，然后重启就好了

**Comment by wang20150419** [comment]
我的服务器 ipv6 访问谷歌正常。SS 就是开了 ipv6，并在 hosts 加了 谷歌学术的 ipv6 地址才能用的。

**Comment by ghost** [comment]
这个与软件问题无关，仅仅是代理服务器的问题，换家服务商或者ip一般就会好。
