### ISSUE TITLE
Can't update my subscribe via TLS1.3 connection

### ISSUE THREAD

**Issue by bclswl0827** [2dust/v2rayNG#329]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
Update my V2Ray subscribed nodes via TLS1.3 connection
### 实际行为
描述实际发生了什么
Can't update my subscribe via TLS1.3 connection
### 复现方法
1. Configure TLS 1.3 ONLY in subscribe server.
2. Update V2Ray subscribed nodes via TLS1.3 connection

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
https://developer.android.com/reference/javax/net/ssl/SSLSocket
It is only supported on Android 10+

**Comment by bclswl0827** [comment]
Got it, thanks so much!
