### ISSUE TITLE
Subscription command 

### ISSUE THREAD

**Issue by aliahmt83** [2dust/v2rayNG#3299]
Hi there 
Looks like that add subscription command changed in 1.8.28 version 

In 1.8.27 was this command:
2rayng://install-config?url=

But in 1.8.28 version it says failed when i try

**Comment by 2dust** [comment]
v2rayng://install-config/url=https://

**Comment by aliahmt83** [comment]
> v2rayng://install-config/url=https://

now this command just opens app and do nothing

**Comment by 2dust** [comment]
protocol format `v2rayng://install-config/?url=urlencode(url)`

example  `v2rayng://install-config/?url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2%23name`

html
`<a href="v2rayng://install-config/?url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2%23name">link v2rayng</a>`
