### ISSUE TITLE
想贡献代码碰到一些问题

### ISSUE THREAD

**Issue by eprendre** [2dust/v2rayNG#33]
你好，我fork了一份代码，但是发现对 PR 不太友好。

- `build.gradle` 这个文件貌似没有更新，少了一个 `fabprogresscircle` 的库。
- 某些项目文件被 gitignore 了，咱得注释掉代码才能跑，但会导致协作不方便。
- `google-services.json` 可以造一个假的，否则编译不通过。

**Comment by 2dust** [comment]
感谢你的热心
本意是不接受pr,因为我没有时间验证别人的代码

**Comment by eprendre** [comment]
好吧 :sob::sob::sob:
