### ISSUE TITLE
1.8.26及以上版本"从剪贴板导入"base64编码后的url链接失败

### ISSUE THREAD

**Issue by KyU-fly** [2dust/v2rayNG#3300]
原来可以粘贴base64编码后的url导入订阅分组，自从1.8.26更新后，
现在导入失败了。希望此功能在以后的版本中恢复！谢谢！
![S40708-19075318](https://github.com/2dust/v2rayNG/assets/175011678/4ce01601-36c8-4211-b545-94e095a13a23)

**Comment by 2dust** [comment]
把你的链接发到 captainIronng@protonmail.com

**Comment by KyU-fly** [comment]
> 把你的链接发到 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

这应该不是链接本身的问题。我试过随便粘贴一个base64编码后的完整链接，在1.8.26以下版本中都可以被识别然后导入订阅分组并自动命名为import sub。但在1.8.26及以上，根本导入不了订阅分组里，导入失败。

**Comment by KyU-fly** [comment]
> 把你的链接发到 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

这应该不是链接本身的问题。我试过随便粘贴一个base64编码后的完整链接，在1.8.26以下版本中都可以被识别然后导入订阅分组并自动命名为import sub。但在1.8.26及以上，根本导入不了订阅分组里，导入失败。

**Comment by KyU-fly** [comment]
1

**Comment by 2dust** [comment]
找到一个bug，如果链接被强了会更新失败，你下载下面这个更新反馈

[v2rayNG_1.8.28_arm64-v8a.zip](https://github.com/user-attachments/files/16137969/v2rayNG_1.8.28_arm64-v8a.zip)

**Comment by KyU-fly** [comment]
> 已经安装了你发的这个版本。我这边出现的问题依然是"从剪贴板导入"base64编码后的链接，软件识别不到，不能添加到订阅分组里。
> 
> > 找到一个bug，如果链接被强了会更新失败，你下载下面这个更新反馈
> > [v2rayNG_1.8.28_arm64-v8a.zip](https://github.com/user-attachments/files/16137969/v2rayNG_1.8.28_arm64-v8a.zip)

[已经安装了这个版本。我这边出现的问题依然是"从剪贴板导入"base64编码后的链接，软件识别不到，不能添加到订阅分组里。]

https://github.com/2dust/v2rayNG/assets/175011678/3fa51c99-38f9-4ced-9c45-80e76b9ce39e

**Comment by 2dust** [comment]
你的网址是编码的，这个不支持

**Comment by KyU-fly** [comment]
> 你的网址是编码的，这个不支持

好吧，只是1.8.26之前的版本支持，昨天偶然发现的。您如果觉得可以就重新加上这功能，不行的话就算了。

**Comment by KyU-fly** [comment]
> 你的网址是编码的，这个不支持

好吧，只是1.8.26之前的版本支持，昨天偶然发现的。您如果觉得可以就重新加上这功能，不行的话就算了。谢谢。

**Comment by KyU-fly** [comment]
> 如果很容易，下版本加上 只是很奇怪的用法，什么时候需要这样编码用

好的。有些节点分享者会分享base64编码后的订阅链接，而不是链接明文。如果加上这功能的话，用户能省去自己解码链接的步骤吧。
