### ISSUE TITLE
建议增加对节点分组、排序和搜索功能

### ISSUE THREAD

**Issue by OXERIS** [2dust/v2rayNG#331]
第一   既然有对节点测速的功能，我认为按测出的速度排序很有必要，特别是在节点众多的情况下。
第二    在有多个订阅来源的情况下，按照来源分组也可以有效帮助查找。
第三    同样是在节点众多的情况下，用户能通过搜索节点名称，更快地查找到自己想要用的节点。

**Comment by 0xCABBA6E** [comment]
建议增加开机自启，自动连接的功能

**Comment by yuhan6665** [comment]
#345 add auto sort when testing speed
