### ISSUE TITLE
无法启动配置，点了按钮没反应

### ISSUE THREAD

**Issue by yyqz28** [2dust/v2rayNG#3317]
配置好了但是v2和clash都无法启动连接
手机是小米，有人知道怎么解决吗

![mmexport1720755711508](https://github.com/user-attachments/assets/866132c6-b3f8-4ed5-bea4-76b08a02a048)

**Comment by harvey-git** [comment]
遇到了一样的问题，测试发现似乎自己手动添加的节点无法启动，点击按钮没反应，但是通过订阅得到的节点可以，大概，应该，眉笔，有可能应该是强制使用订阅了吧。降级到1.8.25已经可以运行了！
