### ISSUE TITLE
客户端远程dns及请求会被解析两次的问题

### ISSUE THREAD

**Issue by fafa777** [2dust/v2rayNG#332]
### 预期行为
需求：所有dns请求使用vps的dns解析，而不使用v2rayNG的远程dns

### 实际行为
情况一：v2rayNG客户端远程dns为1.1.1.1，vps系统dns不变，此时从vps上抓53端口的包查看，此时在vps上会通过one.one.one.one.domain解析，并且有时会出现dns请求会被解析两次的情况，一次通过one.one.one.one.domain,一次通过vps的系统dns解析；
情况二：v2rayNG客户端远程dns为空，vps系统dns不变，此时在vps上仍然会通过one.one.one.one.domain解析；
情况三：v2rayNG客户端远程dns为8.8.8.8，vps系统dns不变，此时在vps上会通过dns.google解析
情况四：v2rayNG客户端远程dns为<https://dns.google/dns-query>，是谷歌的加密doh解析器，vps系统dns不变，抓包发现dns请求在vps上会被解析两次，一次通过vps的系统dns，一次通过dns.google的加密doh
问题一：客户端上显示远程dns是可选的，但就算设置为空，在服务器端还是默认通过1.1.1.1解析，那么v2rayNG中可选的意思是什么？是“可以选择是否使用远程DNS”还是“必须使用远程dns，但服务提供商可选（1.1.1.1或8.8.8.8）都可以”？
问题二：在情况四中，为什么会出现dns请求被解析两次的情况？如果我想只使用加密dns，而不使用服务器的系统dns的话，该如何设置？
问题三：如果我想只使用自己服务器中 /etc/resolv.conf配置的dns进行解析（为了后期在自己的服务器上配置doh/dot等），禁用v2rayNG客户端提供的远程dns，是否可行？如何设置？是在客户端设置还是服务器端配置文件中呢？

补充：之所以想只用服务器的系统dns进行解析，是因为我发现客户端远程dns使用<https://dns.google/dns-query>非常慢，我想在自己的vps上搭建一个doh速度可能会快点，不知道如何禁用客户端的远程dns？
非常感谢！！！

### 环境信息
v2rayNG客户端版本：1.2.2
vps系统：谷歌云，系统ubuntu 18.04
服务器上的/etc/v2ray/config.json配置如下：
`{
  "inbounds": [{

    "port": xx,

    "protocol": "vmess",

    "settings": {

      "clients": [

        {

          "id": "xx",

          "level": 1,

          "alterId": 64

        }

      ]

    }

  }],

  "outbounds": [{

    "protocol": "freedom",

    "settings": {

    }

  },{

    "protocol": "blackhole",

    "settings": {},

    "tag": "blocked"

  }],

  "routing": {

    "rules": [

      {

        "type": "field",

        "ip": ["geoip:private"],

        "outboundTag": "blocked"

      }

    ]

  }

}

`

**Comment by YanpengGu** [comment]
同样遇到这个问题，而且就算客户端用自定义配置，删去dns配置，客户端也会向设置里的远端地址请求解析。

**Comment by yuhan6665** [comment]
DNS is rather complicated. What you want is possible but you need to understand more to do the right configuration on client and server side.
https://medium.com/@TachyonDevel/%E6%BC%AB%E8%B0%88%E5%90%84%E7%A7%8D%E9%BB%91%E7%A7%91%E6%8A%80%E5%BC%8F-dns-%E6%8A%80%E6%9C%AF%E5%9C%A8%E4%BB%A3%E7%90%86%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-62c50e58cbd0

**Comment by rurirei** [comment]
>> 情况二：v2rayNG客户端远程dns为空，vps系统dns不变，此时在vps上仍然会通过one.one.one.one.domain解析；
情况三：v2rayNG客户端远程dns为8.8.8.8，vps系统dns不变，此时在vps上会通过dns.google解析

because v2rayNG uses 1.1.1.1 / 8.8.8.8 as default value, even when you delete text value. and you can not use DoT server at this `remote dns` setting.

https://github.com/2dust/v2rayNG/blob/df3f1ca3efdd5b6e9115cbe7ecdb4260541ab732/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L602-L616

**Comment by xiaozhezi** [comment]
> 

v2rayNG客户端远程dns设置为空，则依然会使用1.1.1.1。
如果不想使用这个功能，你可以在远程dns设置里面随便写一个网络不通的地址，甚至随便一个数字1。  此时因为网络不通，就相当于不使用v2rayNG客户端远程dns功能了。

**Comment by xiaozhezi** [comment]
@YanpengGu  
v2rayNG客户端远程dns设置为空，则依然会使用1.1.1.1。
如果不想使用这个功能，你可以在远程dns设置里面随便写一个网络不通的地址，甚至随便一个数字1。  此时因为网络不通，就相当于不使用v2rayNG客户端远程dns功能了。
