### ISSUE TITLE
please change the true delay test url to cf

### ISSUE THREAD

**Issue by plasticgholam** [2dust/v2rayNG#3325]
please change the true delay test url to http://cp.cloudflare.com/

**Comment by 2dust** [comment]
You can modify it yourself.

**Comment by plasticgholam** [comment]
> You can modify it yourself.

I know I can modify it myself but why not changing it as a default url test? it is far better and shows a better delay
or do you have any idea how can I change it in the customized config that every user uses that config automaticly uses cf url for ping test?

**Comment by plasticgholam** [comment]
as a matter of fact, sing-box uses this cf url for delay test and users are very happy with that
http://cp.cloudflare.com/
