### ISSUE TITLE
Implement SSH  Connection to passthrough Traffic

### ISSUE THREAD

**Issue by MTF96zn** [2dust/v2rayNG#3327]
Hello and thanks for the effort you are putting into this app
I have a suggestion I didn't know where to send this ... So...

We need a SSH vpn client on Android and iOS for using as VPN .
We wanted to see if it is possible for you to implement and integrate this capability into your app ? Because it is very hard to block SSH protocol in a country's infrastructure as they them selves using and utilizing the SSH protocol to mange their own network devices...
Thanks for your help

**Comment by 2dust** [comment]
https://github.com/XTLS/Xray-core
