### ISSUE TITLE
手机和平板设置allowInsecure=false 无法正常使用

### ISSUE THREAD

**Issue by txwdzxq** [2dust/v2rayNG#3329]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
正常连接

### 实际行为
显示连接成功
但是测试连接 :失败 io: read/write on closed pipe

### 复现方法
1.allowInsecure=false
2.点击连接按钮
3.显示已连接后,点击测试连接

### 日志信息
<details>
```
(tls: failed to verify certificate: x509: certificate signed by unknown authority)
```
</details>

### 环境信息
Android11

### 额外信息（可选）
自建服务器
相同配置win10/win11下v2rayN正常
平板和手机同样的问题，只有设置allowInsecure=true才能正常使用
域名使用的是 Let's Encrypt 证书

**Comment by 2dust** [comment]
证书要fullchain

**Comment by SenyFish** [comment]
最后咋解决的，我朋友的手机也是这个情况

**Comment by yige38** [comment]
> 最后解决的，我朋友的手机也是这个情况

修复方法，选中你的连接，点击和笔一样的修改按钮，滑到底找到allowinsecure设置成true，重新连接服务器就能通了

**Comment by txwdzxq** [comment]
> > 最后解决的，我朋友的手机也是这个情况
> 
> 修复方法，选中你的连接，点击和笔一样的修改按钮，滑到底找到allowinsecure设置成true，重新连接服务器就能通了

如果是自己的服务器，设置fullchain证书。
不是或者只需要简单方法，allowinsecure=true即可解决。
