### ISSUE TITLE
Reverse listing of serversv1.8.30

### ISSUE THREAD

**Issue by mehrdadtopme** [2dust/v2rayNG#3331]
In version 1.8.30 when we update the subscription link
Servers are numbered in reverse

**Comment by plasticgholam** [comment]
yes it is reversed :/

**Comment by 2dust** [comment]
Please provide a link to the test

**Comment by mehrdadtopme** [comment]
We update the subscription link and there is a fragment, there is a json title, servers or full X-ray, this happens.


[[](url)](https://uupload.ir/view/video_2024-07-14_12-55-06_zs7q.mp4/)

**Comment by mehrdadtopme** [comment]
This problem does not seem to be from v2rayng!  And now the Hiddify panel has been updated and the problem has been solved, but there is still a problem, when we update the subscription link, after the update, the server selection indicator goes to the last server, for example, if I am server 1 and update the subscription link, the sign is next to the server.  It will be transferred to the last server
