### ISSUE TITLE
请问如何设置回国规则（已知国内有服务器）

### ISSUE THREAD

**Issue by cottonthread** [2dust/v2rayNG#334]
### 预期行为
如果我在直连规则里面输入 `regexp:\\*`，应该默认优先**全部直连**

### 实际行为
可是实际上我的连接请求还是被传到了v2Ray服务器上

### 复现方法
1. 域名策略：`IPifNonMatch`
2. 代理的网址或者IP：`geosite:cn,geoip:cn`
3. 直连的网址或者IP：`geosite:geolocation-!cn,regexp:\\*`

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
03-27 17:27:25.857 I/GoLog   (12851): Using Prepared: 我的服务器IP 
03-27 17:27:27.432 I/GoLog   (12851): udp:127.0.0.1:49275 accepted udp:8.8.8.8:53 [proxy]  
03-27 17:27:27.751 I/GoLog   (12851): Using Prepared: 我的服务器IP 
**03-27 17:27:28.044 I/GoLog   (12851): Not Using Prepared: tcp,www.google.com:80** 
03-27 17:27:28.185 I/GoLog   (12851): tcp:127.0.0.1:39918 accepted tcp:161.117.97.84:443 [proxy]  
03-27 17:27:28.500 I/GoLog   (12851): Using Prepared: 我的服务器IP 
03-27 17:27:29.300 I/GoLog   (12851): udp:127.0.0.1:47423 accepted udp:173.194.202.127:19302 [proxy]  
03-27 17:27:29.910 I/GoLog   (12851): Using Prepared: 我的服务器IP
```
</details>

### 环境信息
v2rayNG 1.2.4 谷歌商店版本
小米POCO F1
MIUI Global 11.0.5
安卓 9
### 额外信息（可选）
服务器在国内，想用来回国的。所以希望除了国内常见IP地址需要代理以外其它流量还是保持直连。

**Comment by yuhan6665** [comment]
Can you try this:
1. Use custom config.
2. Change your "outbounds", "direct" to be the first item, so that it is default.
3. In "routing", put "geoip:cn" and "geosite:cn" to "proxy"

**Comment by cottonthread** [comment]
> Can you try this:
> 
> 1. Use custom config.
> 2. Change your "outbounds", "direct" to be the first item, so that it is default.
> 3. In "routing", put "geoip:cn" and "geosite:cn" to "proxy"

Maybe you indicanting me about the Server side? Because in the Client side there is not an config.json.

Now I am having this issue only with v2rayNG, in my PC side I am using v2rayN and with this rule I am going very well. Thanks in advance for your help.

![微信图片_20200327222050](https://user-images.githubusercontent.com/62510349/77801727-b946cc80-7079-11ea-819f-34e86defc7f8.jpg)
![微信图片_20200327222059](https://user-images.githubusercontent.com/62510349/77801737-bc41bd00-7079-11ea-9e3d-7418b932fcd1.jpg)
![微信图片_20200327222104](https://user-images.githubusercontent.com/62510349/77801745-bea41700-7079-11ea-93aa-11d8a260966d.jpg)

**Comment by yuhan6665** [comment]
@cottonthread I tried your configuration and realise why it didn't match all traffic. When you type the "regexp:\\*", it effectively add this block to the routing:

"domain": ["regexp:\\*"],
"outboundTag": "direct"

As a result, all request with domain name will not go through proxy. But request to ip will still go through. I think this is what you see in the log.
BTW, you can access "custom config" in the top right menu button "+".

**Comment by cottonthread** [comment]
> @cottonthread I tried your configuration and realise why it didn't match all traffic. When you type the "regexp:\*", it effectively add this block to the routing:
> 
> "domain": ["regexp:\*"],
> "outboundTag": "direct"
> 
> As a result, all request with domain name will not go through proxy. But request to ip will still go through. I think this is what you see in the log.
> BTW, you can access "custom config" in the top right menu button "+".

Finally I got this working, thank you very much @yuhan6665! 🥇 👍  It was somehow difficult for noobs like me. But I got it by your help. Here is what I've done:

I had to delete the default DNS setting when I export the template and any pre-existing routing rules in the program to clean up no senses domain checks and put not just **outbounds->direct(Tag)->freedom(Protocol)** to the first item **and**, put `regexp:\\S*` in the last part in the **routing** part.

Here is my working template, may help others to do the same thing:

```
{
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "protocol": "socks",
      "settings": {
        "auth": "noauth",
        "udp": true,
        "userLevel": 8
      },
      "sniffing": {
        "destOverride": [
          "http",
          "tls"
        ],
        "enabled": true
      },
      "tag": "socks"
    },
    {
      "listen": "127.0.0.1",
      "port": 10809,
      "protocol": "http",
      "settings": {
        "userLevel": 8
      },
      "tag": "http"
    }
  ],
  "log": {
    "loglevel": "error"
  },
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "mux": {
        "concurrency": -1,
        "enabled": false
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "SERVERADDRESS",
            "port": 9000,
            "users": [
              {
                "alterId": 64,
                "id": "UUID",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": ""
      },
      "tag": "proxy"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "port": null,
        "inboundTag": null,
        "outboundTag": "direct",
        "ip": [
          "geoip:private"
        ],
        "domain": null
      },
      {
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "proxy",
        "type": "field"
      },
      {
        "domain": [
          "regexp:\\S*"
        ],
        "outboundTag": "direct",
        "type": "field"
      }
    ]
  },
  "stats": {}
}
```

Maybe some day in this program there will be an function to do all I've down now in few clicks, like v2rayN already did. But anyways. Thank you all for the magnific program and accurately help! 👍 🍾

**Comment by okudayukiko** [comment]
推荐用GeoIP，不要用GeoSite和sniffing。
