### ISSUE TITLE
xxx.men is an invalid ip or doamin

### ISSUE THREAD

**Issue by wangvation** [2dust/v2rayNG#3341]
我更新app到版本1.8.29后出现bug，app的logcat打印“xxx.men is an invalid ip or doamin“。
xxx.men是我服务器的域名的别称(顶级域名是men)。
我将域名改成xxx.com之后app能够正常连接，但是xxx.com不是我的域名。
而且我的节点在旧版的app上是可以正常连接的。
通过搜索日志信息，发现问题应该是出现在V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt文件的56-58行。

### 预期行为
能够正常连接xxx.men的服务器

### 实际行为
无法连接xxx.men的服务器

### 复现方法
1. 将服务器配置的address改为xxx.men, 然后连接，就能复现改问题。
2. 将服务器配置的address改为xxx.com, 然后连接，则不会出现这个问题，但是xxx.com不是我的域名。

### 日志信息

--------- beginning of untrustedapp
07-17 18:41:13.592 D/com.v2ray.ang( 9181): tun2socks destroy
--------- beginning of main
07-17 18:41:13.593 I/tun2socks(13998): NOTICE(tun2socks): termination requested
07-17 18:41:13.593 I/tun2socks(13998): NOTICE(tun2socks): tearing down
07-17 18:41:13.593 I/tun2socks(13998): NOTICE(tun2socks): Free TCP connections
07-17 18:41:13.595 I/tun2socks(13998): NOTICE(tun2socks): exiting
07-17 18:41:13.600 D/com.v2ray.ang( 9181): libtun2socks.so exited
07-17 18:41:30.442 D/com.v2ray.ang(10097):xxx.men is an invalid ip or domain

### 环境信息
OS:Android 10
APP VERSION:v1.8.29

### 额外信息（可选）
相关代码：
```kotlin
            val outbound = config.getProxyOutbound() ?: return Result(false, "")
            val address = outbound.getServerAddress() ?: return Result(false, "")
            if (!Utils.isIpAddress(address) && !Utils.isValidUrl(address)) {
                Log.d(ANG_PACKAGE, "$address is an invalid ip or domain")
                return Result(false, "")
            }
```

**Comment by 2dust** [comment]
这个控制确实是最近加上的
能否把你的域名发出来，让开发复现下问题

**Comment by wangvation** [comment]
> 这个控制确实是最近加上的 能否把你的域名发出来，让开发复现下问题

kanban.luckdehun.men

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.32

试一试

**Comment by wangvation** [comment]
我这边测试了一下，这个问题已经修复了。
