### ISSUE TITLE
手机安卓v2rayNg最新版启动服务失败

### ISSUE THREAD

**Issue by gusttur** [2dust/v2rayNG#3342]
提示启动服务失败，状态栏不出VPN图标，标志不变色，卸载重装亦是如此。

**Comment by gusttur** [comment]
日志
--------- beginning of main
07-17 19:57:43.708 I/GoLog   (25678): loading core config
07-17 19:57:43.709 I/GoLog   (25678): Preparing Domain: 82459cb0.pnd6xm1ljcfpc3b-fbnode.6pzfwf.com:56002
07-17 19:57:43.765 I/GoLog   (25678): Prepare Result:
07-17 19:57:43.765 I/GoLog   (25678):  Domain: 82459cb0.pnd6xm1ljcfpc3b-fbnode.6pzfwf.com
07-17 19:57:43.765 I/GoLog   (25678):  Port: 56002
07-17 19:57:43.765 I/GoLog   (25678):  IPs: [************* *************** *************** ***************]
07-17 19:57:43.891 I/GoLog   (25678): new core
07-17 19:57:44.069 I/GoLog   (25678): start core
07-17 19:57:44.070 I/GoLog   (25678): app/proxyman/inbound: failed to listen TCP on 10808 > transport/internet: failed to listen on address: *********:10808 > transport/internet/tcp: failed to listen TCP on *********:10808 > listen tcp *********:10808: bind: address already in use
07-17 19:57:48.805 I/com.v2ray.ang(17827): Open vivo delay for GC JIT .
07-17 19:57:48.853 W/com.v2ray.ang(17827): type=1400 audit(0.0:62547): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=12922 scontext=u:r:untrusted_app:s0:c86,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.v2ray.ang

**Comment by wangvation** [comment]
从日志上看，应该是端口被占用了，你重启一下手机试试？

**Comment by 2dust** [comment]
: bind: address already in use
