### ISSUE TITLE
No connection if i use new v2rayng versions,  the last working version is 1.8.30...

### ISSUE THREAD

**Issue by firestarter7924** [2dust/v2rayNG#3346]
Hello. 1.8.30 is the last best workin version for me. i use it on android 14. all works well. but new versions just kill my internet. no connection with any vless server. have tried to make the log but didn't find in this log any info about v2rayng...

**Comment by firestarter7924** [comment]
In log i see "tls handshakre timeout"
That error is in every version newer than 1.8.30.

**Comment by XiaoHuaCheung-GitHub** [comment]
disable geosite:category-ads-all ,it will be ok
