### ISSUE TITLE
http/1.1 + tls error

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3355]
https://github.com/XTLS/Xray-core/releases/tag/v1.8.20

SplitHTTP 服务端支持 H2C，客户端支持 HTTP/1.1+TLS
english : SplitHTTP server supports H2C, client supports HTTP/1.1+TLS

http/1.1 + tls has been added here, but why it doesn't connect when I change alpn to http/1.1

error: io read/write on closed pipe

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/pull/3567
