### ISSUE TITLE
Add this app in F-DROID Platform 

### ISSUE THREAD

**Issue by Greatz08** [2dust/v2rayNG#3358]
F-droid is open source app repos for apps so this must be there and u must add that link in main repo of this project :-)

**Comment by yuhan6665** [comment]
@2dust 
@Fangliding 提到有人搞了收录请求但是还缺个点头
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16106

**Comment by ghost** [comment]
> @2dust @Fangliding 提到有人搞了收录请求但是还缺个点头 https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16106

Hello, don't be tired dear
Sorry, I am asking here because you are one of the main agents,When will the seed reality be released?
