### ISSUE TITLE
绕过大陆地址分流建议

### ISSUE THREAD

**Issue by YanpengGu** [2dust/v2rayNG#336]
dns由本地解析，使用国内dns，例如223.5.5.5，开启流量探测，geoip:cn  direct，其余proxy。
本方案不使用geosite分流，完全依靠ip分流，规则简单，且可以抗dns污染，污染解析的ip多为境外ip，根据ip分流依旧会走proxy。
缺点是会造成dns泄露。

**Comment by YanpengGu** [comment]
本方案可以解决现有绕过大陆地址造成的国内网址访问缓慢问题

**Comment by cmmqqt** [comment]
小白一枚，请问具体怎么设置？

**Comment by jiahaoliang** [comment]
请问这个issue有解决方法吗，使用v2rayNG作为客户端，正如前述：

> ...现有绕过大陆地址造成的国内网址访问缓慢问题

即使访问国内网址，在服务器端能看到大量1.1.1.1的dns代理记录，由于dns的延时导致访问国内网站的延迟很大。

只在v2rayNG发现该情况，windows下的v2rayN，ios的shadowrocket，以及linux下直接用v2ray作为客户端都不会上述情况。

**Comment by even0306** [comment]
```
"dns": {
    "servers": [
      "223.5.5.5",
      {
        "address": "1.1.1.1",
        "port": 53,
        "domains": [
          "geosite:geolocation-!cn"
        ]
      }
    ]
  },
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": [
          "geosite:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": [
          "geoip:cn",
          "geoip:private"
        ]
      },
      {
        "type": "field",
        "outboundTag": "proxy",
        "network": "udp,tcp"
      }
    ]
  }
```
我用这个规则，在v2rayng上访问国内网站就很慢，在其他软件上正常

**Comment by jiahaoliang** [comment]
@even0306 我用下列方法解决了我自己遇到的问题https://github.com/2dust/v2rayNG/issues/336#issuecomment-658726183：
1.进入设置-》自定义规则-》右上角三圆点-》设置默认规则-》打勾
2.进入设置-》预定义规则-》选择绕过局域网和大陆地址
3.进入设置-》勾选本地DNS，境内dns默认为223.5.5.5，本地dns端口默认为10853
4.回到v2rayNG连接界面，断开连接之后重新连接即可。

**Comment by ghost** [comment]
> @even0306 我用下列方法解决了我自己遇到的问题[https://github.com/2dust/v2rayNG/issues/336#issuecomment-658726183：](https://github.com/2dust/v2rayNG/issues/336#issuecomment-658726183%EF%BC%9A)
> 1.进入设置-》自定义规则-》右上角三圆点-》设置默认规则-》打勾
> 2.进入设置-》预定义规则-》选择绕过局域网和大陆地址
> 3.进入设置-》勾选本地DNS，境内dns默认为223.5.5.5，本地dns端口默认为10853
> 4.回到v2rayNG连接界面，断开连接之后重新连接即可。


我这效果依旧不好, 国内应用还是走了代理..

**Comment by zix-gg** [comment]
> @even0306 我用下列方法解决了我自己遇到的问题[https://github.com/2dust/v2rayNG/issues/336#issuecomment-658726183：](https://github.com/2dust/v2rayNG/issues/336#issuecomment-658726183%EF%BC%9A) 1.进入设置-》自定义规则-》右上角三圆点-》设置默认规则-》打勾 2.进入设置-》预定义规则-》选择绕过局域网和大陆地址 3.进入设置-》勾选本地DNS，境内dns默认为223.5.5.5，本地dns端口默认为10853 4.回到v2rayNG连接界面，断开连接之后重新连接即可。

感谢，访问国内应用延迟高的问题已解决。
