### ISSUE TITLE
更新订阅失败（1.8.33预发行版本）

### ISSUE THREAD

**Issue by fuhuojie123** [2dust/v2rayNG#3360]
### 预期行为
更新订阅显示成功

### 实际行为
更新订阅显示失败

### 复现方法
1.开着代理的情况更新
2.关闭代理使用广电的流量更新
3.关闭代理使用移动的WiFi更新

### 日志信息
通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
beginning of main
07-22 09:32:54.456 I/com.v2ray.ang(17508): This is sticky GC, maxfree is 8388608 minfree is 524288
```
</details>

### 环境信息
1.8.33

### 额外信息（可选）
我可以正常测速和访问网页，但不知道为什么更新订阅会失败，这个日志我看不太懂

**Comment by 2dust** [comment]
订阅更新的问题请自己解决，保证订阅能被手机正常无代理访问
