### ISSUE TITLE
无法从订阅链接更新

### ISSUE THREAD

**Issue by wy353208214** [2dust/v2rayNG#3363]
### 预期行为
同一个订阅链接，1.8.25版本可以拉取配置，1.8.29版本无法拉取配置

### 实际行为
无法从订阅链接拉取配置

### 日志信息
- 1.8.29版本日志如下：
```
-------- beginning of main 
07-22 17:59:02.938 D/com.v2ray.ang(23601): https://s1 .trojanflare.one/subscription/shadowrocket/XXXXXX
07-22 17:59:03.839 |/com.v2ray.ang(23601):This is non sticky GC, maxfree is 33554432 minfree is 2097152
```

- 1.8.25版本日志如下：
```
--------- beginning of main
07-22 18:10:44.681 I/com.v2ray.ang(25519): Using CollectorTypeCC GC.
07-22 18:10:44.685 E/com.v2ray.ang(25519): Not starting debugger since process cannot load the jdwp agent.
07-22 18:10:44.774 E/com.v2ray.ang(25519): 
07-22 18:10:44.962 I/com.v2ray.ang(25519): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
07-22 18:10:44.997 I/com.v2ray.ang(25519): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
07-22 18:10:45.039 D/com.v2ray.ang(25519): MiuiProcessManagerServiceStub setSchedFifo
07-22 18:10:54.935 I/com.v2ray.ang(25519): This is non sticky GC, maxfree is 33554432 minfree is 2097152
07-22 18:11:07.746 D/com.v2ray.ang(25519): https://s1.trojanflare.one/subscription/shadowrocket/XXXXXX
07-22 18:11:09.036 I/com.v2ray.ang(25519): This is sticky GC, maxfree is 33554432 minfree is 2097152
```

</details>

### 环境信息
Android 14 
小米13

**Comment by yaleimeng** [comment]
正式版还好一点，我每次一安装pre-release版本就报废了。。折腾半天也不能用。后来才发现是v2NG问题。卸载安装老的正式版就正常了。
已经好多次了。真是搞怕了。。再也不敢试pre-release了。
确实有些订阅链接在电脑端正常更新，但是手机上更新不了。莫名其妙。。没办法忍了，有多个机场。

**Comment by wy353208214** [comment]
> 正式版还好一点，我每次一安装pre-release版本就报废了。。折腾半天也不能用。后来才发现是v2NG问题。卸载安装老的正式版就正常了。 已经好多次了。真是搞怕了。。再也不敢试pre-release了。 确实有些订阅链接在电脑端正常更新，但是手机上更新不了。莫名其妙。。没办法忍了，有多个机场。

1.8.29就是是google play最新版呀，我切回去了，不过另外一个机场没问题协议是vmess的，有问题的是trojan的

**Comment by wy353208214** [comment]
另外，补充一下，订阅地址可以直接访问，没有被墙

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.34
这个版本试一试
如果还不行，请发订阅到邮箱 captainIronng@protonmail.com

**Comment by 2dust** [comment]
[v2rayNG_1.8.34_arm64-v8a.zip](https://github.com/user-attachments/files/16377078/v2rayNG_1.8.34_arm64-v8a.zip)

试一试

**Comment by wy353208214** [comment]
> [v2rayNG_1.8.34_arm64-v8a.zip](https://github.com/user-attachments/files/16377078/v2rayNG_1.8.34_arm64-v8a.zip)
> 
> 试一试

已试，还是不行，订阅地址已发邮箱。

**Comment by wy353208214** [comment]
> [v2rayNG_1.8.34_arm64-v8a.zip](https://github.com/user-attachments/files/16377078/v2rayNG_1.8.34_arm64-v8a.zip)
> 
> 试一试

这个压缩包的版本可以，但我从tag那里下载的那个版本就不行，很奇怪

**Comment by 2dust** [comment]
等下版
https://github.com/2dust/v2rayNG/commit/322b6ec615289c1541c3cc6b11244436bd3494cb

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.35

**Comment by 1753135250** [comment]
> ### 预期行为
> 同一个订阅链接，1.8.25版本可以拉取配置，1.8.29版本无法拉取配置
> 
> ### 实际行为
> 无法从订阅链接拉取配置
> 
> ### 日志信息
> * 1.8.29版本日志如下：
> 
> ```
> -------- beginning of main 
> 07-22 17:59:02.938 D/com.v2ray.ang(23601): https://s1 .trojanflare.one/subscription/shadowrocket/XXXXXX
> 07-22 17:59:03.839 |/com.v2ray.ang(23601):This is non sticky GC, maxfree is 33554432 minfree is 2097152
> ```
> 
> * 1.8.25版本日志如下：
> 
> ```
> --------- beginning of main
> 07-22 18:10:44.681 I/com.v2ray.ang(25519): Using CollectorTypeCC GC.
> 07-22 18:10:44.685 E/com.v2ray.ang(25519): Not starting debugger since process cannot load the jdwp agent.
> 07-22 18:10:44.774 E/com.v2ray.ang(25519): 
> 07-22 18:10:44.962 I/com.v2ray.ang(25519): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
> 07-22 18:10:44.997 I/com.v2ray.ang(25519): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
> 07-22 18:10:45.039 D/com.v2ray.ang(25519): MiuiProcessManagerServiceStub setSchedFifo
> 07-22 18:10:54.935 I/com.v2ray.ang(25519): This is non sticky GC, maxfree is 33554432 minfree is 2097152
> 07-22 18:11:07.746 D/com.v2ray.ang(25519): https://s1.trojanflare.one/subscription/shadowrocket/XXXXXX
> 07-22 18:11:09.036 I/com.v2ray.ang(25519): This is sticky GC, maxfree is 33554432 minfree is 2097152
> ```
> 
> ### 环境信息
> Android 14 小米13

朋友你好，我想询问一下s1.trojanflare.one开头的订阅链接的梯子的购买网站，万分感谢
