### ISSUE TITLE
一键对国内某一应用进行代理

### ISSUE THREAD

**Issue by lmflya** [2dust/v2rayNG#3366]
大佬好，不知道可否一键对国内某一应用进行代理。举一个例子：
       当我使用v2rayng的**分应用代理**以及**绕过大陆的预定义规则**后，我手机只有b站和google等共计5个应用有代理，其中b站因为是国内应用默认不走代理，其余四款默认代理。但是当我想用b站看某一港台限制动漫时，需要先去自定义规则中将b站添加到代理的网址或IP里，然后看完后再进行删除。
        一两个应用还好，但是当所需要添加的应用较多时，这种方案还需要手动输入较多规则，因此，对于这种情况，不知大佬可否有**额外的一键选择几个国内应用**进行代理，或者说对于这种情况是否有其他较好的方案？感谢回复。

**Comment by RaziGitHubAccount** [comment]
***@***.***

**Comment by lmflya** [comment]
不知这个写在这里是否合适，若是不合适删除就好，因此对你造成的麻烦提前抱歉
