### ISSUE TITLE
ss下启动服务失败

### ISSUE THREAD

**Issue by BrilliantSeirios** [2dust/v2rayNG#337]
已排除服务端的问题，路由器下正常使用

日志如下：

--------- beginning of system
--------- beginning of main
05-09 23:06:05.519 I/GoLog   (15985): EnableLocalDNS: false
05-09 23:06:05.519 I/GoLog   (15985): ForwardIpv6: false
05-09 23:06:05.519 I/GoLog   (15985): DomainName: 
05-09 23:06:05.519 I/GoLog   (15985): loading v2ray config
05-09 23:06:05.519 I/GoLog   (15985): Preparing Domain: 
05-09 23:06:05.519 I/GoLog   (15985): PrepareDomain DomainName Err: missing port in address|strconv.Atoi: parsing "": invalid syntax
05-09 23:06:06.086 I/GoLog   (15985): file exists
05-09 23:06:06.086 I/GoLog   (15985): new v2ray core
05-09 23:06:06.094 I/GoLog   (15985): start v2ray core
05-09 23:06:06.095 I/GoLog   (15985): Prepare Result:
05-09 23:06:06.095 I/GoLog   (15985):  Ready: false
05-09 23:06:06.095 I/GoLog   (15985):  Domain: 
05-09 23:06:06.095 I/GoLog   (15985):  Port: 
05-09 23:06:06.095 I/GoLog   (15985):  IPs: []
05-09 23:06:06.095 I/GoLog   (15985): 2019/05/09 15:06:06 [Warning] v2ray.com/core: V2Ray 4.19 started
05-09 23:07:55.486 I/GoLog   (16642): EnableLocalDNS: false
05-09 23:07:55.486 I/GoLog   (16642): ForwardIpv6: false
05-09 23:07:55.486 I/GoLog   (16642): DomainName: 
05-09 23:07:55.486 I/GoLog   (16642): loading v2ray config
05-09 23:07:55.486 I/GoLog   (16642): Preparing Domain: 
05-09 23:07:55.486 I/GoLog   (16642): PrepareDomain DomainName Err: missing port in address|strconv.Atoi: parsing "": invalid syntax
05-09 23:07:56.081 I/GoLog   (16642): file exists
05-09 23:07:56.081 I/GoLog   (16642): new v2ray core
05-09 23:07:56.097 I/GoLog   (16642): start v2ray core
05-09 23:07:56.101 I/GoLog   (16642): Prepare Result:
05-09 23:07:56.101 I/GoLog   (16642):  Ready: false
05-09 23:07:56.101 I/GoLog   (16642):  Domain: 
05-09 23:07:56.101 I/GoLog   (16642):  Port: 
05-09 23:07:56.101 I/GoLog   (16642):  IPs: []
05-09 23:07:56.106 I/GoLog   (16642): 2019/05/09 15:07:56 [Warning] v2ray.com/core: V2Ray 4.19 started
05-09 23:09:16.404 I/GoLog   (16866): EnableLocalDNS: false
05-09 23:09:16.404 I/GoLog   (16866): ForwardIpv6: false
05-09 23:09:16.404 I/GoLog   (16866): DomainName: 
05-09 23:09:16.404 I/GoLog   (16866): loading v2ray config
05-09 23:09:16.404 I/GoLog   (16866): Preparing Domain: 
05-09 23:09:16.405 I/GoLog   (16866): PrepareDomain DomainName Err: missing port in address|strconv.Atoi: parsing "": invalid syntax
05-09 23:09:17.053 I/GoLog   (16866): file exists
05-09 23:09:17.053 I/GoLog   (16866): new v2ray core
05-09 23:09:17.062 I/GoLog   (16866): start v2ray core
05-09 23:09:17.063 I/GoLog   (16866): Prepare Result:
05-09 23:09:17.063 I/GoLog   (16866):  Ready: false
05-09 23:09:17.063 I/GoLog   (16866):  Domain: 
05-09 23:09:17.063 I/GoLog   (16866):  Port: 
05-09 23:09:17.063 I/GoLog   (16866):  IPs: []
05-09 23:09:17.063 I/GoLog   (16866): 2019/05/09 15:09:17 [Warning] v2ray.com/core: V2Ray 4.19 started

**Comment by BrilliantSeirios** [comment]
手机: 小米 mix2
系统: MIUI 10.3.1.0
安卓版本: 8.0.0

**Comment by 2dust** [comment]
提供下你的客户端节点配置
可以掩藏部分域名关键字

**Comment by BrilliantSeirios** [comment]
![20190510161354](https://user-images.githubusercontent.com/16205195/57512627-bbf3e280-733e-11e9-94d5-13117320e01d.jpg)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.20.2

**Comment by 2dust** [comment]
测试下这个版本

**Comment by BrilliantSeirios** [comment]
启动成功！！感谢！！
