### ISSUE TITLE
tun2socks的端口10808好像是写死的，不能通过代码设置？

### ISSUE THREAD

**Issue by zdm2008** [2dust/v2rayNG#337]
tun2socks的端口10808好像是写死的，不能通过代码设置？

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/blob/3ea04c076cac6428dd7596f946b789c736bd7a58/AndroidLibV2rayLite/CoreI/Status.go#L32

**Comment by zdm2008** [comment]
在Java里没有地方可以设置
