### ISSUE TITLE
【建议】建议添加前置代理功能

### ISSUE THREAD

**Issue by anysoft** [2dust/v2rayNG#338]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为

在连接V2ray服务器之前先连接一个HTTP或者Sock5/4的代理服务器，再通过该代理服务器连接V2ray服务器。
在ss和SSR的客户端都有实现叫前置代理，也就是代理链。可以通过多次代理跳转。
1、实现前置代理功能，其中支持配置代理类型，代理IP端口，代理认证信息，代理header自定义(混淆自定义header项或者有些HTTP代理需要Base auth的request header项)

### 实际行为
目前只能直接client直连接V2ray服务端，一些情况小导致V2ray对外暴露，容易封闭。
另外一些情况下，本地网络只能通过http代理访问外网，这时候就没法直接连接v2ray服务器了。

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by if1y** [comment]
同样需要，希望能够支持

**Comment by AngelFalse** [comment]
希望能够支持+1

**Comment by rurirei** [comment]
https://www.v2fly.org/config/outbounds.html#proxysettingsobject

**Comment by anysoft** [comment]
> https://www.v2fly.org/config/outbounds.html#proxysettingsobject
自定义脚本是可以添加的。界面配置以及vmess 都不支持

**Comment by yogurt7771** [comment]
> > https://www.v2fly.org/config/outbounds.html#proxysettingsobject
> > 自定义脚本是可以添加的。界面配置以及vmess 都不支持

我试了一下没有成功，本地开启clash，端口7890，再用裸vmess协议，设置proxySettings，然后无法访问网络
