### ISSUE TITLE
这两天这软件连不上了

### ISSUE THREAD

**Issue by moonwater** [2dust/v2rayNG#34]
是不是哪里有变化了呢, 用的是vmess协议，苹果上同样的设置可以工作。

### 预期行为
软件应该可以工作的

### 实际行为
实际上昨天开始就连不上了。
排除了网络问题和服务端的问题，v2rayNG客户端也没做什么修改。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by silentstage** [comment]
关掉快速域名解析，应该就可以了

**Comment by 2dust** [comment]
快速域名解析,app直接连dns服务,可能会被部分运营商污染.
关掉这个功能就走远程服务器解析,速度会慢一点,但是无污染
