### ISSUE TITLE
后台占用网速很大

### ISSUE THREAD

**Issue by yukun1109** [2dust/v2rayNG#34]
打开代理时，有时候后台占用网速很高，YouTube等软件无网速可用

**Comment by 2dust** [comment]
是否使用的kcp?

**Comment by yukun1109** [comment]
是的，传输协议是kcp，要怎么解决



Thank you!
CHEN Yukun
 
发件人： 2dust
发送时间： 2019-08-21 08:34
收件人： 2dust/v2rayNG
抄送： CHEN Yukun; Author
主题： Re: [2dust/v2rayNG] 后台占用网速很大 (#34)
是否使用的kcp?

**Comment by 2dust** [comment]
kcp多倍发包,可以自己google了解下
无解,

**Comment by yukun1109** [comment]
感谢解答



Thank you!
CHEN Yukun
 
发件人： 2dust
发送时间： 2019-08-21 09:19
收件人： 2dust/v2rayNG
抄送： CHEN Yukun; Author
主题： Re: [2dust/v2rayNG] 后台占用网速很大 (#34)
Closed #34.
