### ISSUE TITLE
一加手机7连接不上VPN

### ISSUE THREAD

**Issue by 568240761** [2dust/v2rayNG#340]
日志里报了很多这个：
2020-04-01 22:06:36.117 I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.v2ray.ang/tun2socks: permission denied
2020-04-01 22:06:36.117 I/GoLog: EscortRun Unexpected Exit, Restart now.

**Comment by yuhan6665** [comment]
Is it possible for you to get full adb log without any filtering? There might be more details about this error a few line above this.

**Comment by 568240761** [comment]
I installed my own APP to connect to the VPS with three physical mobile phones, which caused a problem with the OnePlus mobile phone. It's no problem to install V2Ray APP to connect to VPS with OnePlus mobile phone. I don't know why? Yesterday's log is incomplete, here is the full log without any filtering:
I/om.meow.vpn:vp: Late-enabling -Xcheck:jni
E/om.meow.vpn:vp: Unknown bits set in runtime_flags: 0x8000
I/Perf: Connecting to perf service.
I/om.meow.vpn:vp: [GL_OOM] ClampGrowthLimit 268435456
D/Meow: VpnApplication-attachBaseContext
V/Font: Change font:1
V/Font: Default family:android.graphics.Typeface@f2145c77
E/Perf: Fail to get file list com.meow.vpn
E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
E/Perf: Fail to get file list com.meow.vpn
E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
W/om.meow.vpn:vp: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
W/om.meow.vpn:vp: Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
D/MeowService: v2rayPoint=V2RayPoint{
SupportSet:com.meow.vpn.service.MeowService$V2RayCallback@fbccb60,
PackageName:/data/user/0/com.meow.vpn/,
DomainName:www******:***,
ConfigureFileContent:{
      "dns": {
        "servers": [
          "1.1.1.1"
        ]
      },
      "inbounds": [
        {
          "listen": "127.0.0.1",
          "port": 10808,
          "protocol": "socks",
          "settings": {
            "auth": "noauth",
            "udp": true,
            "userLevel": 8
          },
          "sniffing": {
            "destOverride": [
              "http",
              "tls"
            ],
            "enabled": true
          },
          "tag": "socks"
        },
        {
          "listen": "127.0.0.1",
          "port": 10809,
          "protocol": "http",
          "settings": {
            "userLevel": 8
          },
          "tag": "http"
        }
      ],
      "log": {
        "loglevel": "warning"
      },
      "outbounds": [
        {
          "mux": {
            "enabled": false
          },
          "protocol": "vmess",
          "settings": {
            "vnext": [
              {
                "address": "www.******",
                "port": ***,
                "users": [
                  {
                    "alterId": 64,
                    "id": "*********",
                    "level": 8,
                    "security": "auto"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "security": "tls",
            "tlssettings": {
              "allowInsecure": true,
              "serverName": ""
            },
            "wssettings": {
              "connectionReuse": true,
              "headers": {
                "Host": ""
              },
              "path": "********"
            }
          },
          "tag": "proxy"
        },
        {
          "protocol": "freedom",
          "settings": {},
          "tag": "direct"
        },
        {
          "protocol": "blackhole",
          "settings": {
            "response": {
              "type": "http"
            }
          },
          "tag": "block"
        }
      ],
      "policy": {
        "levels": {
          "8": {
            "connIdle": 300,
            "downlinkOnly": 1,
            "handshake": 4,
            "uplinkOnly": 1
          }
        },
        "system": {
          "statsInboundUplink": true,
          "statsInboundDownlink": true
        }
      },
      "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": []
      },
      "stats": {}
    },EnableLocalDNS:false,ForwardIpv6:false,}
I/GoLog: [holder]
I/GoLog: /data/user/0/com.meow.vpn/ArchIndep/holder
I/GoLog: Preparing Domain: www.*******:***
I/GoLog: <nil>
I/GoLog: remove /data/user/0/com.meow.vpn/holder: no such file or directory
I/GoLog: <nil>
I/GoLog: [arm64]
I/GoLog: ArchDep/arm64
I/GoLog: /data/user/0/com.meow.vpn/ArchDep/arm64/tun2socks
I/GoLog: remove /data/user/0/com.meow.vpn/tun2socks: no such file or directory
I/GoLog: <nil>
I/GoLog: EnableLocalDNS: false
    ForwardIpv6: false
    DomainName: www.********:***
I/GoLog: loading v2ray config
I/GoLog: /data/user/0/com.meow.vpn/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.meow.vpn/sock_path]
I/GoLog: new v2ray core
I/GoLog: start v2ray core
I/GoLog: [Warning] v2ray.com/core: V2Ray 4.20.0 started
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: EscortRun cmd.Start err fork/exec /data/user/0/com.meow.vpn/tun2socks: permission denied
I/GoLog: EscortRun Unexpected Exit, Restart now.
I/GoLog: Prepare Result:
     Domain: www.***********
     Port: ****
     IPs: [192.***.***.**]

**Comment by 568240761** [comment]
Find out why, the privacy of Android 10 has changed (https://developer.android.google.cn/about/versions/10/privacy/changes), just change the value of targetSdkVersion from 29 to 28.
