### ISSUE TITLE
[Feature Request] Adding speed test and subscription link tabs

### ISSUE THREAD

**Issue by p19lord** [2dust/v2rayNG#3403]
Dear 2dust,

First and foremost I would like to thank you for the incredible software that you have created.
I would like to request the following features to be added to this outstanding software:
1. Speed Test: a similar feature that we have in V2RAYN where using ctrl+T we can test the speed of the config.
2. Customizable real delay and speed test links: a similar feature that again we have in V2rayN.
3. Sub link tabs: this again is a feature that we have in V2rayN and it helps to organize the configs. I think this would be a convenient feature in this application for lack of space and screen size.

Thank you for the efforts and I wish you a very great day.
Regards

**Comment by 2dust** [comment]
Adding speed test not plan
Added tabs
