### ISSUE TITLE
Configs real delay test inaccuracy issue

### ISSUE THREAD

**Issue by p19lord** [2dust/v2rayNG#3404]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
Real delay tests should show the configs that are working by showing the delay time and those not working with a -1 delay time. After connecting to the config, testing the real delay by tapping the area beside the connect button will confirm the working state of the config either by showing the delay time or by showing the error.

### 实际行为
描述实际发生了什么
After adding a sub link and updating the link to import the configs (about 80 configs), when performing the real delay test shows that all configs are working by showing a delay time however performing the same test in V2rayN (considering that the configuration and internet connections are the same) shows that some of them are not working and this is expected. So this shows V2rayNG test results are not accurate and this makes it hard for the user to find the config that is working. So the user ends up connecting every single config to figure out which one is really working as the real delay test result is not correct.
### 复现方法
1. Performing a Real delay test from the menu which shows the config is working
2. Doing the same test after connecting to the config by tapping the area beside the connect button shows that it is not.

### 日志信息
<details>
--------- beginning of main
08-02 11:44:40.818 D/com.v2ray.ang(28212): https://sublink1.com
08-02 11:44:43.444 D/com.v2ray.ang(28212): https://sublink2.com
08-02 11:45:16.398 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.398 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.419 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.419 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.543 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.569 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.571 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.599 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.679 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:16.819 I/GoLog   (32750): 2024/08/02 08:15:16 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.494 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.556 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.597 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.675 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.727 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.748 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.762 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.765 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:21.852 I/GoLog   (32750): 2024/08/02 08:15:21 [Warning] core: Xray 1.8.23 started
08-02 11:45:22.218 I/GoLog   (32750): 2024/08/02 08:15:22 [Warning] core: Xray 1.8.23 started
08-02 11:45:26.810 I/GoLog   (32750): 2024/08/02 08:15:26 [Warning] core: Xray 1.8.23 started
08-02 11:45:26.930 I/GoLog   (32750): 2024/08/02 08:15:26 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.012 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.053 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.069 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.157 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.176 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.251 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.573 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:27.575 I/GoLog   (32750): 2024/08/02 08:15:27 [Warning] core: Xray 1.8.23 started
08-02 11:45:31.611 I/GoLog   (32750): 2024/08/02 08:15:31 [Warning] core: Xray 1.8.23 started
08-02 11:45:31.786 I/GoLog   (32750): 2024/08/02 08:15:31 [Warning] core: Xray 1.8.23 started
08-02 11:45:31.890 I/GoLog   (32750): 2024/08/02 08:15:31 [Warning] core: Xray 1.8.23 started
08-02 11:45:31.947 I/GoLog   (32750): 2024/08/02 08:15:31 [Warning] core: Xray 1.8.23 started
08-02 11:45:32.154 I/GoLog   (32750): 2024/08/02 08:15:32 [Warning] core: Xray 1.8.23 started
08-02 11:45:32.373 I/GoLog   (32750): 2024/08/02 08:15:32 [Warning] core: Xray 1.8.23 started
08-02 11:45:32.402 I/GoLog   (32750): 2024/08/02 08:15:32 [Warning] core: Xray 1.8.23 started
08-02 11:45:32.464 I/GoLog   (32750): 2024/08/02 08:15:32 [Warning] core: Xray 1.8.23 started
08-02 11:45:32.816 D/com.v2ray.ang(32750): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
08-02 11:45:32.927 D/com.v2ray.ang(32750): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
08-02 11:45:37.073 I/GoLog   (32750): 2024/08/02 08:15:37 [Warning] core: Xray 1.8.23 started
08-02 11:45:37.223 I/GoLog   (32750): 2024/08/02 08:15:37 [Warning] core: Xray 1.8.23 started
08-02 11:45:37.313 I/GoLog   (32750): 2024/08/02 08:15:37 [Warning] core: Xray 1.8.23 started
08-02 11:45:37.473 I/GoLog   (32750): 2024/08/02 08:15:37 [Warning] core: Xray 1.8.23 started
08-02 11:45:37.750 I/GoLog   (32750): 2024/08/02 08:15:37 [Warning] core: Xray 1.8.23 started
08-02 11:45:38.057 I/GoLog   (32750): 2024/08/02 08:15:38 [Warning] core: Xray 1.8.23 started
08-02 11:45:38.064 I/GoLog   (32750): 2024/08/02 08:15:38 [Warning] core: Xray 1.8.23 started
08-02 11:45:38.131 I/GoLog   (32750): 2024/08/02 08:15:38 [Warning] core: Xray 1.8.23 started
08-02 11:45:38.158 I/GoLog   (32750): 2024/08/02 08:15:38 [Warning] core: Xray 1.8.23 started
08-02 11:45:38.349 I/GoLog   (32750): 2024/08/02 08:15:38 [Warning] core: Xray 1.8.23 started
08-02 11:45:42.437 I/GoLog   (32750): 2024/08/02 08:15:42 [Warning] core: Xray 1.8.23 started
08-02 11:45:42.793 I/GoLog   (32750): 2024/08/02 08:15:42 [Warning] core: Xray 1.8.23 started
08-02 11:45:42.830 I/GoLog   (32750): 2024/08/02 08:15:42 [Warning] core: Xray 1.8.23 started
08-02 11:45:43.355 I/GoLog   (32750): 2024/08/02 08:15:43 [Warning] core: Xray 1.8.23 started
08-02 11:45:43.474 I/GoLog   (32750): 2024/08/02 08:15:43 [Warning] core: Xray 1.8.23 started
08-02 11:45:43.475 I/GoLog   (32750): 2024/08/02 08:15:43 [Warning] core: Xray 1.8.23 started
08-02 11:45:43.537 I/GoLog   (32750): 2024/08/02 08:15:43 [Warning] core: Xray 1.8.23 started
08-02 11:45:43.553 I/GoLog   (32750): 2024/08/02 08:15:43 [Warning] core: Xray 1.8.23 started
08-02 11:45:44.735 I/GoLog   (32750): 2024/08/02 08:15:44 [Warning] core: Xray 1.8.23 started
08-02 11:45:44.985 I/GoLog   (32750): 2024/08/02 08:15:44 [Warning] core: Xray 1.8.23 started
08-02 11:45:48.069 I/GoLog   (32750): 2024/08/02 08:15:48 [Warning] core: Xray 1.8.23 started
08-02 11:45:48.429 I/GoLog   (32750): 2024/08/02 08:15:48 [Warning] core: Xray 1.8.23 started
08-02 11:45:48.430 I/GoLog   (32750): 2024/08/02 08:15:48 [Warning] core: Xray 1.8.23 started
08-02 11:45:48.874 I/GoLog   (32750): 2024/08/02 08:15:48 [Warning] core: Xray 1.8.23 started
08-02 11:45:49.001 I/GoLog   (32750): 2024/08/02 08:15:48 [Warning] core: Xray 1.8.23 started
08-02 11:45:49.429 I/GoLog   (32750): 2024/08/02 08:15:49 [Warning] core: Xray 1.8.23 started
08-02 11:45:49.472 I/GoLog   (32750): 2024/08/02 08:15:49 [Warning] core: Xray 1.8.23 started
08-02 11:45:49.509 I/GoLog   (32750): 2024/08/02 08:15:49 [Warning] core: Xray 1.8.23 started
08-02 11:45:51.876 I/GoLog   (32750): 2024/08/02 08:15:51 [Warning] core: Xray 1.8.23 started
08-02 11:45:52.763 I/GoLog   (32750): 2024/08/02 08:15:52 [Warning] core: Xray 1.8.23 started
08-02 11:45:53.943 I/GoLog   (32750): 2024/08/02 08:15:53 [Warning] core: Xray 1.8.23 started
08-02 11:45:53.956 I/GoLog   (32750): 2024/08/02 08:15:53 [Warning] core: Xray 1.8.23 started
08-02 11:45:54.128 I/GoLog   (32750): 2024/08/02 08:15:54 [Warning] core: Xray 1.8.23 started
08-02 11:45:54.240 I/GoLog   (32750): 2024/08/02 08:15:54 [Warning] core: Xray 1.8.23 started
08-02 11:45:54.782 I/GoLog   (32750): 2024/08/02 08:15:54 [Warning] core: Xray 1.8.23 started
08-02 11:45:55.896 I/GoLog   (32750): 2024/08/02 08:15:55 [Warning] core: Xray 1.8.23 started
08-02 11:45:56.521 I/GoLog   (32750): 2024/08/02 08:15:56 [Warning] core: Xray 1.8.23 started
08-02 11:45:56.758 I/GoLog   (32750): 2024/08/02 08:15:56 [Warning] core: Xray 1.8.23 started
08-02 11:45:58.171 I/GoLog   (32750): 2024/08/02 08:15:58 [Warning] core: Xray 1.8.23 started
08-02 11:45:58.431 I/GoLog   (32750): 2024/08/02 08:15:58 [Warning] core: Xray 1.8.23 started
08-02 11:45:59.765 I/GoLog   (32750): 2024/08/02 08:15:59 [Warning] core: Xray 1.8.23 started
08-02 11:45:59.976 I/GoLog   (32750): 2024/08/02 08:15:59 [Warning] core: Xray 1.8.23 started
08-02 11:46:00.181 I/GoLog   (32750): 2024/08/02 08:16:00 [Warning] core: Xray 1.8.23 started
08-02 11:46:00.459 I/GoLog   (32750): 2024/08/02 08:16:00 [Warning] core: Xray 1.8.23 started
08-02 11:46:00.594 I/GoLog   (32750): 2024/08/02 08:16:00 [Warning] core: Xray 1.8.23 started
08-02 11:46:02.401 I/GoLog   (32750): 2024/08/02 08:16:02 [Warning] core: Xray 1.8.23 started
08-02 11:46:03.339 I/GoLog   (32750): 2024/08/02 08:16:03 [Warning] core: Xray 1.8.23 started
08-02 11:46:03.766 I/GoLog   (32750): 2024/08/02 08:16:03 [Warning] core: Xray 1.8.23 started
08-02 11:46:04.359 I/GoLog   (32750): 2024/08/02 08:16:04 [Warning] core: Xray 1.8.23 started
08-02 11:46:04.522 I/GoLog   (32750): 2024/08/02 08:16:04 [Warning] core: Xray 1.8.23 started
08-02 11:46:05.466 I/GoLog   (32750): 2024/08/02 08:16:05 [Warning] core: Xray 1.8.23 started
08-02 11:46:06.242 I/GoLog   (32750): 2024/08/02 08:16:06 [Warning] core: Xray 1.8.23 started
08-02 11:46:06.829 I/GoLog   (32750): 2024/08/02 08:16:06 [Warning] core: Xray 1.8.23 started
08-02 11:46:06.846 I/GoLog   (32750): 2024/08/02 08:16:06 [Warning] core: Xray 1.8.23 started
08-02 11:46:07.154 I/GoLog   (32750): 2024/08/02 08:16:07 [Warning] core: Xray 1.8.23 started
08-02 11:46:07.419 I/GoLog   (32750): 2024/08/02 08:16:07 [Warning] core: Xray 1.8.23 started
08-02 11:46:07.823 I/GoLog   (32750): 2024/08/02 08:16:07 [Warning] core: Xray 1.8.23 started
</details>

### 环境信息
V2rayNg v1.8.35 (lib v27, Xray-core v1.8.23)

**Comment by 2dust** [comment]
This is just a reference, the reality is very complicated, so as long as it works old don't get hung up on it
