### ISSUE TITLE
谷歌商店软件没办法更新，其他软件的内置下载也无法进行，但是换其他加速器就可以，但速度很慢

### ISSUE THREAD

**Issue by mengqiDyi** [2dust/v2rayNG#342]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

确认过，貌似没有

**Comment by overprince** [comment]
自从更新到android 10 以后有同样的问题.
我这里取消分应用代理(不管你分应用代理里有没有打开play store的开关), 开全局就可以了

**Comment by yuhan6665** [comment]
"Android System" or "settings" need to go through proxy. See #503 for details

**Comment by 1human** [comment]
> "Android System" or "settings" need to go through proxy. See #503 for details

I have set per-app proxy with Android system and settings apk，still wrong......
After I turn off it and open google play store one time,and everything seems ok. But I need repeat several times per day

**Comment by uui23** [comment]
> > "Android System" or "settings" need to go through proxy. See #503 for details
> 
> I have set per-app proxy with Android system and settings apk，still wrong......
> After I turn off it and open google play store one time,and everything seems ok. But I need repeat several times per day

thanks inspired me, I turn off per-app proxy which at setting page and it work. when I click into it there are per-app proxy and bypass mode both turn on. obvious confilict.
