### ISSUE TITLE
希望增加分组前置代理功能

### ISSUE THREAD

**Issue by heibailiangxiangwang20** [2dust/v2rayNG#3420]
因为现在我们的使用场景是电商养号，都是买的那种静态ip或者动态ip，都是socks或者http协议，这些买的在大陆是无法直接连接过去的，必须借助前置或者链式！因为现在养号都是用手机养！所以还恳请增加此功能

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.1
