### ISSUE TITLE
希望能增加一个多节点负载均衡功能

### ISSUE THREAD

**Issue by tyy840913** [2dust/v2rayNG#3429]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
用v2rayN先生成配置，拷贝过来用用。

**Comment by tyy840913** [comment]
使用v2ray负载均衡配置，链接一致，启动后可以测试延迟，但是无法上网

**Comment by 2dust** [comment]
暂时没有计划，原因是需要修改lib部分，有此需求的可以试一试用cmfa

**Comment by 2dust** [comment]
使用最新版，可以导入v2rayN的负载了
