### ISSUE TITLE
Fragment packet does not set correctly from Fragment menu setting

### ISSUE THREAD

**Issue by babak6262** [2dust/v2rayNG#3431]
When Fragment Packets set to 1-2 (or 1-3 or 1-5) in Fragment menu setting then all of them run in tlshello mode and run config with tlshello instead of 1-2 (the setting is not applied correctly). When you export the full configuration, the JSON file shows that "packets" is not set to 1-2 and it is set to tlshello instead. Fragment Packets modes setting is not applied correctly and config run with tls hello mode.
Version is 1.8.35
Please fix it

**Comment by 2dust** [comment]
Since development devices can't test slicing, we'll have to wait for your international developers to handle it

**Comment by 2dust** [comment]
Since development devices can't test Fragment , we'll have to wait for your international developers to handle it
