### ISSUE TITLE
Support for profile-update-interval Parameter in Subscription Links

### ISSUE THREAD

**Issue by imanenter** [2dust/v2rayNG#3438]
### Expected behavior
The V2RayNG client should support the profile-update-interval parameter in subscription links, similar to how other clients like Karing, Clash Meta, etc., handle it. This allows the client to automatically update subscriptions at specified intervals, improving user experience by keeping their profiles up to date without manual intervention.

Actual behavior
Currently, the V2RayNG client does not support the profile-update-interval parameter in subscription links. Users have to manually refresh their subscriptions, which can lead to outdated profiles and potential connectivity issues.

### Reproduction method

Generate a subscription link with the profile-update-interval parameter using a server that supports it (e.g., Marzban panel).
Add the subscription link to the V2RayNG client.
Observe that the subscription does not automatically update according to the interval specified.
### Log information

Additional information
Here is an example of the subscription headers from the Marzban panel that supports the profile-update-interval:

```
response_headers = {
    "content-disposition": f'attachment; filename="{user.username}"',
    "profile-web-page-url": str(request.url),
    "support-url": SUB_SUPPORT_URL,
    "profile-title": encode_title(SUB_PROFILE_TITLE),
    "profile-update-interval": SUB_UPDATE_INTERVAL,
    "subscription-userinfo": "; ".join(
        f"{key}={val}"
        for key, val in get_subscription_user_info(user).items()
        if val is not None
    )
}
```
By adding support for this feature, the V2RayNG client can automatically update profiles based on the interval provided in the subscription, enhancing usability.

### Thank you!
Thank you for considering this feature request and for your continued work on improving the V2RayNG client.

**Comment by fedorov-xyz** [comment]
@2dust Hello! Can we please get back to this issue?

We cannot assume all users are technically literate and expect them to follow the steps to enable subscription auto-update exactly.

A typical “Turn on subscription auto-update” instruction looks like this. 8 steps in different screens.

```
1. Go to the menu, select “Settings”.
2. Scroll down to “Groups” and expand the item.
3. Activate automatic update.
4. Enter a value of 90 in the interval .
5. Go back to the menu and select the “Groups” item.
6. Click the pencil next to the configuration.
7. Enable the two items about updating.
8. Save via the check mark in the header.
```

My suggestion is to automatically set subscription auto-update options as soon as a subscription with the `profile-update-interval` header is received.

https://github.com/2dust/v2rayNG/blob/30a4c2199a49cb9fb599fd0c9e16bf54da1a0c1d/V2rayNG/app/src/main/java/com/v2ray/ang/ui/SettingsActivity.kt#L56

1. Enable `autoUpdateCheck` option.
2. Set `autoUpdateInterval` option as the header value multiplied by 60 (it indicates the time in hours).

This will incredibly improve and simplify the user experience. Again, not all users are technically proficient. Thank you

**Comment by abwbkrdshty-code** [comment]
vless://cfe4968b-e6e0-434d-a4a4-2ad31b6159f5@185.143.233.166:2082?path=%2Fassets%2Fvarzesh3&security=&encryption=none&host=hpavash1.digikalajets.ir&type=ws#%F0%9F%87%A9%F0%9F%87%AA%5B%20nano_2ac5%20%5D%7C%F0%9F%94%8B19.52%20GB%2F20.0%20GB%7C%F0%9F%8F%86%40
