### ISSUE TITLE
[FR] Have an 'update current subscription' option.

### ISSUE THREAD

**Issue by X-Oracle** [2dust/v2rayNG#3445]
With the new way of showing subscription groups, this came to mind.

Currently the only way to update one subscription is 
1- going to subscription settings
2. Disable all subscriptions update except the one we want to update 
3- Hit `update subscription`.

My opinion about the behaviour of the new option `update current subscription`:

1- hit `update current subscription`
2- (optional) show a dialogue which tells user are you sure to `update {{SUBSCRIPTION NAME}}?`
3- update current subscription regardless of having its update option disabled in subscription settings.( If the user is in `all subscription groups` then the behaviour can be like the old `update subscription` option )

It already existed in V2rayN and I use it a lot since I have a lot of groups, think about it in your free time.

Good luck.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases
