### ISSUE TITLE
app updating 

### ISSUE THREAD

**Issue by iyf577ge6** [2dust/v2rayNG#3462]
Greetings
first of all i want to thank you for this interesting app.

i wanted to know if it is possible to add a feature for updating program from inside of app via github link?

just like when the new updates got released a dialogue box shown up while opening the app and ask the users that there is a new version for the app if they want to update it or not.

thanks.

**Comment by yasbija** [comment]
Great, this is a useful option.

**Comment by codewithtamim** [comment]
@2dust Sounds useful. Should I  add this ? ::)

**Comment by 2dust** [comment]
We don't need this feature
And with this feature it will not be allowed on googleplay.
