### ISSUE TITLE
Subscription Name Not Added in v2RayNG via Standard URL Scheme

### ISSUE THREAD

**Issue by DigneZzZ** [2dust/v2rayNG#3470]
**Issue: Subscription Name Not Added in v2RayNG via Standard URL Scheme**

In the latest versions of v2RayNG, the subscription name is not being added when using the standard URL scheme:

`v2rayng://install-sub?url=URL&name=NAME`

Previously, there was an enhancement that enabled this functionality:

- Related commit: [4d4a454](https://github.com/2dust/v2rayNG/pull/2273/commits/4d4a4543c51340eb75283a6580bfc73349209c88)
- Code reference: [UrlSchemeActivity.kt#L51](https://github.com/hadi-norouzi/v2rayNG/blob/4d4a4543c51340eb75283a6580bfc73349209c88/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/UrlSchemeActivity.kt#L51)

However, this functionality seems to be missing in the latest releases:

- Current code reference: [UrlSchemeActivity.kt#L39](https://github.com/2dust/v2rayNG/blob/d9f0854c27e9a4852da54c26437dba4f8ebcab90/V2rayNG/app/src/main/kotlin/com/v2ray/ang/ui/UrlSchemeActivity.kt#L39)

It is unclear whether this functionality has been moved elsewhere or if it was unintentionally omitted from the recent releases. Could you please look into this issue?

**Comment by 2dust** [comment]
v2rayng://install-sub?url=URL#NAME

**Comment by DigneZzZ** [comment]
> v2rayng://install-sub?url=URL#NAME

@2dust, Not working
![image](https://github.com/user-attachments/assets/930c4139-0347-42b3-be1c-0293ae3f6f0e)

**Comment by 2dust** [comment]
v2rayng://install-config?url=URL#NAME

**Comment by 2dust** [comment]
`<a href="v2rayng://install-config/?url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2%23name">link v2rayng</a>`

**Comment by DigneZzZ** [comment]
> `<a href="v2rayng://install-config/?url=https%3A%2F%2Fraw.githubusercontent.com%2Faiboboxx%2Fv2rayfree%2Fmain%2Fv2%23name">link v2rayng</a>`

Yes, but..

`v2rayng://install-sub?url=https://domain.com/sub/QsgjhsdGDshkHgdzIzNTQ4NjceDSGyoLHw8P#name`
dont work
`v2rayng://install-config?url=https://domain.com/sub/QsgjhsdGDshkHgdzIzNTQ4NjceDSGyoLHw8P#name`
dont work
`v2rayng://install-config/?url=https://domain.com/sub/QsgjhsdGDshkHgdzIzNTQ4NjceDSGyoLHw8P#name`
dont work
`v2rayng://install-sub/?url=https://domain.com/sub/QsgjhsdGDshkHgdzIzNTQ4NjceDSGyoLHw8P#name`
dont work

![image](https://github.com/user-attachments/assets/a2973ab2-2014-4626-9af5-61e1dc78fe3e)

**Comment by DigneZzZ** [comment]
@2dust reopen this issue please.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/3299

**Comment by 2dust** [comment]
urlencode(url)

**Comment by DigneZzZ** [comment]
Great
encode url work good
