### ISSUE TITLE
Geo资源文件下载是否提供进度条或类似的提示

### ISSUE THREAD

**Issue by wukan1986** [2dust/v2rayNG#3473]
由于资源文件一个6MB、一个12MB，下载要一定的时间，但更新时一点提示都没有，不知道是否正在更新，建议加上进度条，或弹出通知

v2rayN在这一点就做得比较好

**Comment by 2dust** [comment]
0a09966e817730719db9d4e3f917cfd81f4807d4

**Comment by wukan1986** [comment]
谢谢，就是功能太简单了，只知道正在下载，但不知道下载的进度。
还有下载两个文件，只有第一个文件有显示提示框，第二个文件没有提示。
