### ISSUE TITLE
name app

### ISSUE THREAD

**Issue by elifian** [2dust/v2rayNG#3475]
Hello,

I would like to request a change to the button label in the application dropdown. Currently, the button is labeled "Переключить" (russian language), but I would prefer it to be updated to "v2rayNG".

This change would help in better identifying the application

Thanks for the work done
<img src="https://github.com/user-attachments/assets/3bd72d87-c8d2-4944-8fd4-5c4deacdc047" width="300" />

**Comment by 2dust** [comment]
<string name="app_widget_name">Переключить</string>
    <string name="app_tile_name">Переключить</string>

Please pr fix
