### ISSUE TITLE
最近手机V2rayNG共两个问题如下

### ISSUE THREAD

**Issue by lssmoon2019** [2dust/v2rayNG#3476]
1.V2rayNG启用后不久无法正常上网使用，速度均为0。退回1.8.29后正常上网。
2.手机下拉快捷开关失效
(日志如下)
![9F29F796FFF434F191C7891B952C0B3E](https://github.com/user-attachments/assets/c004db56-1c65-4924-845f-c8c684dbffeb)

**Comment by 110560** [comment]
补充 更新订阅失败 ，同一个地址
电脑上的 v2rayN 能成功的订阅。
手机上目前最新版本 提示订阅失败 
从剪贴板导入单个节点 成功使用。

旧的版本 可成功正常订阅

**Comment by yhdxczz** [comment]
+1，我就说最近网络不行，X一直刷不出来，查了聊天记录，退回到6月份的版本立马没问题了，就是最近更新的版本有问题！

**Comment by lionel126** [comment]
我是8月初升级了playstore的版本1.8.35后, 开始出问题了 我的配置都是vmess ws的连不上了 用回了tcp

**Comment by 743859910** [comment]
Google 应用商店都更新到 1.8.40 了![Screenshot_2024-09-12-04-38-45-309_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/36c653a7-c5de-4001-b7fc-21bc6785b833)

**Comment by yhdxczz** [comment]
不敢更新，旧版本用的好好的，新版本没法用
