### ISSUE TITLE
几个建议，如果可以的话。节点管理。

### ISSUE THREAD

**Issue by wengzhenquan** [2dust/v2rayNG#3479]
v2rayNG是非常好的APP，在我看来比clash好太多了，但现在市面上像v2ray这样的貌似是唯一一个，我找了很久都找不到。
在我看来，v2最大的优点就是可以对多个订阅进行混合对比，以便于用户选用。
clash仅仅只能对单个订阅进行应用，管理节点非常不便。
我希望2能够尽量发挥这方面的优势，所以提几个建议，当然，如果开发者觉得没有意义，可以无视。

由于本人日常除了自己使用，也会整合筛选，保证质量和可用性的节点进行分享。

建议：
1、订阅分组显示当前剩余节点数量。

2、支持单独节点测试真链接操作。
（好像目前只有批量操作，只有PC端的v2rayN可以单独节点。但我发现经常-1的节点也是可用的，重新测试又没问题了，但“全部测试”时间太久，我需要单独测试，生成延迟数值，以便于重新排序。）

3、多选操作。
（有时候需要对指点的多个节点进行删除、测试真链接、分享等操作。关于分享操作，我可以自定义选用几十个优质节点，进行分享，而不是全部导出。）

另外，提一个貌似有点问题之处。
当我切换到某个订阅分组下，点击测试真链接事，是测试本分组下的节点真链接，这个逻辑没问题。但在同一个分组下，点击“删除全部配置”，导致其它分组也全删掉了，不是应该跟测试真链接的逻辑一样才对吗？
以至于现在，我需要单独删除分组内的全部节点，必须连整个分组都删除掉。

以上是我的所有建议，祝愿V2能够越做越好，发挥自己的优势，不会被clash类型的智障式“一键连接”打败。

**Comment by 2dust** [comment]
分组的一些问题在此已经处理 https://github.com/2dust/v2rayNG/releases/tag/1.8.37
