### ISSUE TITLE
[FR] Setting option to disable internet check.

### ISSUE THREAD

**Issue by X-Oracle** [2dust/v2rayNG#3486]
Hi,
I see in recent commits there is one which forced users to have connected to a network before connecting.

It is good for most cases but when it comes to local connections like local Lan or hotspot. It won't work.

My suggestion is to have an option in settings which we can configure if this check happens or not.

Suggested option name: 
`Disable Connectivity Check`

Behaviour:
Default is Unchecked.
When enabled, the related code should not run when the user hits the start button.

**Comment by codewithtamim** [comment]
@2dust Is this important? If yes then I can make the change and submit a pr, Thanks

**Comment by X-Oracle** [comment]
this network check is good for Client usage but I as a config provider, need to test deferent types of configs in deferent operating systems and in android I usually do this locally with JSON input capability of V2rayNG.

this Network Checking Feature is not Xray core related and makes these tests harder.

with the option to disable this feature, there should be no problem.

Plus, not all android devices are smartphones and may result in some unexpected `network unavailable` messages.

Well, I tried to give my opinion to you guys.
the final decision is yours.

Good Luck

**Comment by codewithtamim** [comment]
@X-Oracle got your point 👍let's see is he agrees I will just do it 🫶

**Comment by 2dust** [comment]
Just remove the feature, there is no need to add an option!

Revert https://github.com/2dust/v2rayNG/pull/3439

**Comment by codewithtamim** [comment]
okk
