### ISSUE TITLE
Please add an option to generate QR code and link using the standard syntax

### ISSUE THREAD

**Issue by arinc9** [2dust/v2rayNG#3487]
Please add an option to generate QR code and link using the standard syntax. An example link is below.

```
vmess://uuid@IP:port?encryption=zero&host=example.com&path=%2Fpath&security=tls&sni=example.com&type=ws&allowInsecure=1#VMess%20over%20WebSocket%20over%20TLS
```

Please also apply the "encryption" variable. I see that both v2rayN and v2rayNG will ignore encryption=zero.

**Comment by arinc9** [comment]
@2dust why have you closed the issue?

**Comment by 2dust** [comment]
not planned

**Comment by arinc9** [comment]
I can see that. The question is will you bother to represent a valid reason as to why you won't do what I've reported.
