### ISSUE TITLE
无法对分组内搜索筛选得到结果进行测试。

### ISSUE THREAD

**Issue by ZZXIXI** [2dust/v2rayNG#3495]
新版1.8.37已经实现手动输入条件筛选条件进行过滤，谢谢您的帮助。但是手动输入搜索筛选之后无法对搜索结果进行测速，寻找测速按钮时我需要退出搜索结果才能点到测速按钮，无法只对搜索过的这一小部分结果进行测速和其他操作。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.8.38
