### ISSUE TITLE
Please add regular WireGuard configuration parsing. 

### ISSUE THREAD

**Issue by phenomenonRT** [2dust/v2rayNG#3497]
Please add regular WireGuard configuration parsing. 
Example:
```
[Interface]
PrivateKey = 
Address = 
DNS = 
MTU =

[Peer]
PublicKey =
AllowedIPs =
Endpoint = 
```

**Comment by 2dust** [comment]
Waiting for someone to pr

**Comment by codewithtamim** [comment]
@2dust  I have done this before, should I do it and submit a pr?

**Comment by APT-ZERO** [comment]
Please add the same thing to v2rayN too

**Comment by 2dust** [comment]
> @2dust I have done this before, should I do it and submit a pr?

Thank you for your work.
Since there is no protocol header to recognize, consider handling it here
https://github.com/2dust/v2rayNG/blob/b8939763d4f67d5c28950d18da3ced9da88bbb6d/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/AngConfigManager.kt#L467

**Comment by codewithtamim** [comment]
> > @2dust I have done this before, should I do it and submit a pr?
> 
> Thank you for your work. Since there is no protocol header to recognize, consider handling it here
> 
> https://github.com/2dust/v2rayNG/blob/b8939763d4f67d5c28950d18da3ced9da88bbb6d/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/AngConfigManager.kt#L467

Hi guys Im little busy now, but I'm giving code for parsing the wireguard config, Just use it and it will work fine.

This is the data class for wireguard config 
```kotlin 
data class WireGuardConfig(
    val interface: WireGuardInterface,
    val peer: WireGuardPeer
)

data class WireGuardInterface(
    val privateKey: String,
    val address: String
)

data class WireGuardPeer(
    val publicKey: String,
    val presharedKey: String,
    val allowedIPs: List<String>,
    val persistentKeepalive: Int,
    val endpoint: String
)
```
This is the function which will take string config and returns data class
```kotlin
fun parseWireGuardConfig(config: String): WireGuardConfig {
    val lines = config.split("\n").map { it.trim() }.filter { it.isNotEmpty() }

    var interfaceSection = true
    val interfaceMap = mutableMapOf<String, String>()
    val peerMap = mutableMapOf<String, String>()

    for (line in lines) {
        when {
            line.startsWith("[Interface]") -> {
                interfaceSection = true
            }
            line.startsWith("[Peer]") -> {
                interfaceSection = false
            }
            interfaceSection -> {
                val (key, value) = line.split("=", limit = 2).map { it.trim() }
                interfaceMap[key] = value
            }
            else -> {
                val (key, value) = line.split("=", limit = 2).map { it.trim() }
                peerMap[key] = value
            }
        }
    }

    val `interface` = WireGuardInterface(
        privateKey = interfaceMap["PrivateKey"] ?: "",
        address = interfaceMap["Address"] ?: ""
    )

    val peer = WireGuardPeer(
        publicKey = peerMap["PublicKey"] ?: "",
        presharedKey = peerMap["PresharedKey"] ?: "",
        allowedIPs = peerMap["AllowedIPs"]?.split(",")?.map { it.trim() } ?: emptyList(),
        persistentKeepalive = peerMap["PersistentKeepalive"]?.toIntOrNull() ?: 0,
        endpoint = peerMap["Endpoint"] ?: ""
    )

    return WireGuardConfig(`interface`, peer)
}
```

**Comment by TitanComputer** [comment]
you should add default remark with unix time or endpoint to prevent empty config names.

**Comment by codewithtamim** [comment]
> you should add default remark with unix time or endpoint to prevent empty config names.

yeah I saw it shows blank name

**Comment by TitanComputer** [comment]
> > you should add default remark with unix time or endpoint to prevent empty config names.
> 
> yeah I saw it shows blank name

now, if you go to edit mode, you have to set a remark to submit that.

**Comment by codewithtamim** [comment]
ok fix in new pr

**Comment by Saje95** [comment]
data class WireGuardConfig(
    val interface: WireGuardInterface,
    val peer: WireGuardPeer
)

data class WireGuardInterface(
    val privateKey: String,
    val address: String
)

data class WireGuardPeer(
    val publicKey: String,
    val presharedKey: String,
    val allowedIPs: List<String>,
    val persistentKeepalive: Int,
    val endpoint: String
)

**Comment by m0x61h0x64i** [comment]
still when i import a wireguard config which was created using wireguard core, the wireguard config does not work #3252
