### ISSUE TITLE
希望加入直连路由模式

### ISSUE THREAD

**Issue by ttttmr** [2dust/v2rayNG#35]
默认的绕过局域网及大陆地址路由效果比较差，很多国内域的服务器不在大陆

分应用能解决一些问题，但对浏览器类型的通用应用就不行了，而且没有流量日志，自己加路由也很难，尤其是卡CDN的时候

希望能有直连路由模式的话会好处理些，毕竟被ban是少数

直连模式+自定义路由代理导入，体验会好很多

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/38
