### ISSUE TITLE
分应用代理无效？

### ISSUE THREAD

**Issue by MyBackups-Home** [2dust/v2rayNG#35]
上一个版本也有这个问题，开了分应用代理，结果还是全局的，那些没有勾选的应用也可以翻墙（用了两个浏览器测试，一个勾选一个不勾选），然后开了绕行模式也是一样无效，希望能解决该问题

手机：魅族MX4 Pro
系统：Flyme6
Android版本：5.1.1

**Comment by ncs19960831** [comment]
是否是自定义文件导入？

**Comment by Arcobaleno0** [comment]
是的，不过就算不是自定义文件导入也不行
