### ISSUE TITLE
1.8.35 _arm64-v8a 版本，更新订阅失败

### ISSUE THREAD

**Issue by lgw79674057** [2dust/v2rayNG#3500]
如标题，在电脑上同样地址可以更新订阅，手机端不行
并且报错误 parse base64 standard failed
Parse base64 url safe failed 
java.lang.illegalArgumentException:bad base64

**Comment by lostsnow** [comment]
我这里手机 APP 上订阅链接使用 Basic Auth 时更新订阅失败, 日志里提示 FileNotFound, 但是在 PC 端使用 V2rayN 同样链接更新成功, 然后换成非 Basic Auth 的链接更新成功

**Comment by 2dust** [comment]
每个客户端最少开发语言不同，所以报错很正常，只能说你们的订阅不规范
可以把订阅发到 captainIronng@protonmail.com

**Comment by lostsnow** [comment]
> 每个客户端最少开发语言不同，所以报错很正常，只能说你们的订阅不规范 可以把订阅发到 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

同样的内容, 只是把 basic auth 去掉了就成功了, 应该不是订阅内容本身格式的问题, 而是获取内容时出现的问题

**Comment by lostsnow** [comment]
https://android.googlesource.com/platform/external/okhttp/+/6e50afa29a5967de446c5992b5c89a75acb63c55/okhttp-urlconnection/src/main/java/com/squareup/okhttp/internal/huc/HttpURLConnectionImpl.java#251

只要 response status >= 400 就是这异常, 估计是 basic auth encode 错误返回 401

**Comment by lostsnow** [comment]
`172.70.214.129 - - [21/Aug/2024:08:51:09 +0000] "GET /xxxxx HTTP/2.0" 401 172 "-" "v2rayNG/1.8.38"`
