### ISSUE TITLE
订阅分组是否可以支持一个分组内添加多个订阅地址

### ISSUE THREAD

**Issue by jiangtongxueya** [2dust/v2rayNG#3502]
我发现v2rayN可以在可选地址输入框中通过逗号分隔，填写多个订阅地址。我按照同样的方式在v2rayNG中填写，但是发现v2rayNG这么填会导致这个分组订阅失败。翻了好多issue没有找到相关的问题，不知道v2rayNG是否支持这个功能
![image](https://github.com/user-attachments/assets/16c3ed27-9d12-446c-b23b-f144b0030feb)

**Comment by 2dust** [comment]
不支持
手机的很多操作都比不上pc的
