### ISSUE TITLE
Imported socks configs from subscription link are not functional

### ISSUE THREAD

**Issue by armanshahrisa** [2dust/v2rayNG#3503]
Hi,

Firstly, thanks for all your efforts in maintaining the v2RayNG. I appreciate them.

I use text files containing configs to distribute them between family members.

I have a text file with one VLESS and two SOCKS configs without usernames and passwords. SOCKS configs are imported correctly into v2RayNG (the latest beta release from Google Play Store) but are not functional. They are meant to connect to the target v2RayNG on another Android phone. The easiest solution is to edit and save them without any changes. The problem is reproducible. If I update from the subscription link, I have to edit the SOCKS configs to make them work again.

I have SOCKS configs in another subscription text file with usernames and passwords meant to connect to a v2RayN client. These are functional upon updating from the subscription link.

**Comment by 2dust** [comment]
Please give examples of what doesn't work

**Comment by armanshahrisa** [comment]
I have prepared screenshots with the same order of events needed to reproduce the problem:

![1](https://github.com/user-attachments/assets/50285ad9-bcd5-4477-bacc-86ccb3c00d51)
![2](https://github.com/user-attachments/assets/89f3c963-de37-4e79-a026-9c3a580e4c6d)
![3](https://github.com/user-attachments/assets/bcbbf8b3-61f5-4b87-b957-c03542feb943)
![4](https://github.com/user-attachments/assets/9279706b-d729-4a6d-9669-bfb634ac77e2)
![5](https://github.com/user-attachments/assets/6390cf45-8c05-4a9d-8728-c565cce0fb2d)
![6 1](https://github.com/user-attachments/assets/30971202-2286-48fc-b26a-01f43877a53f)
![7](https://github.com/user-attachments/assets/a51c1646-cc54-42cd-983d-e5cd49269b22)
