### ISSUE TITLE
p30Pro更新emui10.0.0.188后能启动v2rayN但无法连接网络

### ISSUE THREAD

**Issue by antidada** [2dust/v2rayNG#351]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
p30Pro夜里自动更新emui10.0.0.188后v2rayN能启动但无法连接，测速后显示失败：：io：read/write on closed pipe

### 预期行为
连接后开始翻墙

### 实际行为
v2rayN能启动但无法连接网络，测速后显示
失败：：io：read/write on closed pipe

使用chrome连接YouTube显示DNS_PROBE_FINISHED_NO_INTERNET
### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by downyolo** [comment]
华为mate20p一样

**Comment by ohcrfpv** [comment]
荣耀30s 一样

**Comment by antidada** [comment]
不知道是否是运营商的问题

**Comment by ohcrfpv** [comment]
我试了另外一个v2ray的客户端 Kitsunebi 正常，同一台服务器，另外iOS的客户端也是正常的

**Comment by antidada** [comment]
> 我试了另外一个v2ray的客户端 Kitsunebi 正常，同一台服务器，另外iOS的客户端也是

> 我试了另外一个v2ray的客户端 Kitsunebi 正常，同一台服务器，另外iOS的客户端也是正常的

你试下凌晨连接看看，我凌晨6点左右能连上，但是速度越来越慢，没几分钟就又连不上了

**Comment by okudayukiko** [comment]
考虑隐私，V2Ray最好不要用国产品牌手机，最好用非国行手机（我用的是日版手机）。

**Comment by valetzx** [comment]
荣耀magic2更新3.1在没更新新版v2时可以用在gp更新后好像就不能用了？应该是支持tv的那个版本，然后提个别的，googleplay服务系统更新后不能被冰箱冻结了不知道楼上有没有遇到的，有点小难受
