### ISSUE TITLE
Add WireGuard PreSharedKey in UI

### ISSUE THREAD

**Issue by TitanComputer** [2dust/v2rayNG#3512]
Hello

I'm Talking About A Wireguard Config File Like This :

```
[Interface]
PrivateKey = 6AJWDDOYXMOamJ6SaXt03V4tnIpCQcADdS/NjBQAJkQ=
Address = 10.66.66.6/32,fd42:42:42::6/128
DNS = 1.1.1.1,1.0.0.1

[Peer]
PublicKey = uHpbdcEvqslm70pxNaaxMGHzy5LC2h1QoENstML4Y0Q=
PresharedKey = f7HdycIK1A8rOm8aD3IluF6xVFb5HRQ4nOl9kN7Tf7o=
Endpoint = xxx.xxx.xxx.xxx:51820
AllowedIPs = 0.0.0.0/0,::/0
```

As You Know, We Have Three Key Parameters In Wireguard Config Files Which Two Of Them Are Mandatory (PrivateKey & PublicKey) And Another Key Which Known As PresharedKey Is Optional.
But If The Provider Tells You A PresharedKey In It's Config, You Must Set It On Your's Or You Can't Use It!

Since You Have Added The Wireguard Support So Far, And Xray Core Supports PresharedKey As JSON Config With This Codes :
```
"publicKey": "uHpbdcEvqslm70pxNaaxMGHzy5LC2h1QoENstML4Y0Q=",
"preSharedKey": "f7HdycIK1A8rOm8aD3IluF6xVFb5HRQ4nOl9kN7Tf7o="
          }
        ],
"secretKey": "6AJWDDOYXMOamJ6SaXt03V4tnIpCQcADdS/NjBQAJkQ="
```

And You Didn't Make A Field On Wireguard Config Setup In UI , All Of Users With These Types Of Configs Had To Use It With JSON Custom Config And It Makes Difficulties.

Please Add A Field After PublicKey And Before Reserved For PreSharedKey (Optional) Parameter. (Default = Empty)

P.S. : [3x-ui](https://github.com/MHSanaei/3x-ui) Panel Already Supports Wireguard with PreSharedKey.

Best Regards

**Comment by codewithtamim** [comment]
Soon

**Comment by TitanComputer** [comment]
@CodeWithTamim any updates?

**Comment by codewithtamim** [comment]
> @CodeWithTamim any updates?

working on it will pr soon
