### ISSUE TITLE
请问V2rayNG怎么用DoT/DoH?

### ISSUE THREAD

**Issue by ihidao** [2dust/v2rayNG#3514]
V2rayNG上面提示的只支持ipv4/ipv6,直接填IP是有效的我知道,但要用DoT/DoH地话是填https://ip/dns-query还是可以填https://域名/dns-query?

![Screenshot_2024_0823_151513](https://github.com/user-attachments/assets/f71d6b1d-e48a-4848-8b1f-02b5b7a31412)

![Screenshot_2024_0823_151532](https://github.com/user-attachments/assets/8e3b0282-923a-4e91-8558-7ef1d97a4d19)

**Comment by 2dust** [comment]
vpn dns只支持ip，这个是系统原因
其他两个dns可以用
