### ISSUE TITLE
Fingerprint problem

### ISSUE THREAD

**Issue by mhkdreamware** [2dust/v2rayNG#3516]
当我们使用现实方法将一个配置输入到v2rayNG中时，如果这个配置的指纹设置为随机化，那么这个配置大多数情况下会崩溃，特别是当手机休息几分钟后重新连接网络时，这个问题以前是不存在的，请修复指纹为随机化

When we enter a configuration into v2rayNG using the reality method.  If the Fingerprint of this configuration is set to Randomized, the configuration will crash most of the time.(ping -1)  Especially when the mobile phone reconnects to the Internet after a few minutes of rest.  This problem did not exist before. Please fix the fingerprint for Randomized

**Comment by Mehdistr70** [comment]
Mehdistr

**Comment by 2dust** [comment]
https://github.com/XTLS/Xray-core
