### ISSUE TITLE
[Bug]左侧选项卡显示不正确

### ISSUE THREAD

**Issue by HaoTian22** [2dust/v2rayNG#353]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
应该在切换页面后把该页面高亮显示
如图
![Screenshot_20200407-121719](https://user-images.githubusercontent.com/48882584/78629461-c3fb3000-78c9-11ea-81f1-7049e3813977.jpg)

### 实际行为
总是会错误地高亮显示了上一个使用的页面
如图
![Screenshot_20200407-121025](https://user-images.githubusercontent.com/48882584/78629478-cf4e5b80-78c9-11ea-8ec0-6d469275f187.jpg)

### 复现方法
1.打开软件
2.点进订阅设置或设置
3.按左上角返回按钮

**Comment by yuhan6665** [comment]
fixed in #432
