### ISSUE TITLE
 Issue with Importing Subscription Content

### ISSUE THREAD

**Issue by Eyepurples** [2dust/v2rayNG#3531]
I have encountered an issue with importing subscription content related to the VLESS protocol in v2rayNG versions 1.8.36 to 1.8.39. Specifically, certain characters in the path field, such as the question mark (?) and equals sign (=), are not being imported correctly. Additionally, the alpn field is not imported at all.

This issue seems to be specific to older Android devices. While testing, I noticed that the VLESS protocol fails to import correctly on these devices, leading to connection issues. However, the VMESS protocol does not exhibit the same problem and works as expected across both older and newer devices.

Steps to Reproduce:

Use an older Android device (with an older version of the OS).
Attempt to import a subscription using the VLESS protocol that includes a path with ? or = characters and an alpn field.
Observe that the path field is incorrectly imported, and the alpn field is missing.
Expected Behavior: The subscription content for the VLESS protocol should be imported correctly on all devices, regardless of the Android version.

Actual Behavior: On older Android devices, the path and alpn fields for VLESS are not imported correctly, while VMESS imports without any issues.

Affected Versions:

v2rayNG 1.8.36 to 1.8.39
Additional Information: This issue does not occur in earlier versions of v2rayNG and seems to have been introduced in versions 1.8.36 onwards. Testing and debugging on older Android devices are recommended to ensure consistent performance across different OS versions.

Thank you for addressing this issue.

**Comment by 2dust** [comment]
Please provide the test case, that is share the link

**Comment by Eyepurples** [comment]
It doesn't matter what type of subscription link is used. Let's assume we got a free subscription link from a donor. Follow the images: 
![photo_2024-09-05_14-53-49](https://github.com/user-attachments/assets/9b777405-7ea5-4696-a059-a528159c79e1)
 in version 1.8.35, the ws path and alpn values were manually set. Now, in the last image, I update my V2RayNG to version 1.8.39 without updating the subscription, and everything works fine. Now, follow the last image: I update the subscription, and what happens is shown in the image. 
![photo_2024-09-05_14-53-52](https://github.com/user-attachments/assets/d96ea337-8e42-4278-a228-cdfeca6f8134)
