### ISSUE TITLE
Issues With Importing Custom Configurations - App Crashes

### ISSUE THREAD

**Issue by Yadollah** [2dust/v2rayNG#3534]
Hi 
After installing versions of 1.3.38 and 1.3.39 , I tested them with importing custom configs because they look more stable and are a stronger Anti-filter protocol and they been used more in IRAN recently.
So here's the issue , V2rayNG App Crashes the moment a custom config has the simplest mistake and instead of showing " Failure " , App crashes and closes.
Please fix this bug.
Thanks

**Comment by 2dust** [comment]
Please provide the configuration file that caused the crash

**Comment by 3486139137** [comment]
这个有没有Windows版的，我目前是用的手机，一直在手机上用，但是不知道怎么在Windows上下载

**Comment by Yadollah** [comment]
> Please provide the configuration file that caused the crash

Hi
Here's the configuration :
except a ` was at the begining and then the crash happened , instead of "Failure" error app crashes.

{"dns":{"hosts":{"domain:googleapis.cn":"googleapis.com"},"servers":[{"address":"fakedns","domains":["geosite:cn"]},"https://94.140.14.14/dns-query",{"address":"https://94.140.14.14/dns-query","domains":["geosite:cn","geosite:geolocation-cn"],"expectIPs":["geoip:cn"],"port":53}]},"fakedns":[{"ipPool":"198.18.0.0/15","poolSize":10000}],"inbounds":[{"listen":"127.0.0.1","port":10808,"protocol":"socks","settings":{"auth":"noauth","udp":true,"userLevel":8},"sniffing":{"destOverride":["http","tls","fakedns"],"enabled":true,"routeOnly":true},"tag":"socks"},{"listen":"127.0.0.1","port":10809,"protocol":"http","settings":{"userLevel":8},"tag":"http"},{"listen":"127.0.0.1","port":10853,"protocol":"dokodemo-door","settings":{"address":"1.1.1.1","network":"tcp,udp","port":53},"tag":"dns-in"}],"log":{"loglevel":"none"},"outbounds":[{"mux":{"concurrency":8,"enabled":true,"xudpConcurrency":8,"xudpProxyUDP443":"reject"},"protocol":"vless","settings":{"vnext":[{"address":"c.88981401.xyz","port":443,"users":[{"encryption":"none","flow":"","id":"5bdf790f-0af2-4481-a624-41b66e7e3489","level":8,"security":"auto"}]}]},"streamSettings":{"network":"ws","security":"tls","sockopt":{"dialerProxy":"fragment"},"tlsSettings":{"allowInsecure":false,"alpn":["http/1.1"],"fingerprint":"firefox","publicKey":"","serverName":"cdn.55994421.xyz","shortId":"","show":false,"spiderX":""},"wsSettings":{"headers":{"Host":"cdn.55994421.xyz","User-Agent":"Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"},"path":"/@ln2ray?ed=2560"}},"tag":"proxy"},{"protocol":"freedom","settings":{"domainStrategy":"UseIP"},"tag":"direct"},{"protocol":"blackhole","settings":{"response":{"type":"http"}},"tag":"block"},{"protocol":"freedom","settings":{"fragment":{"packets":"1-2","length":"4-6","interval":"8-15"}},"streamSettings":{"network":"tcp","security":"","sockopt":{"tcpfastopen":true,"TcpNoDelay":true,"mark":255}},"tag":"fragment"},{"protocol":"dns","tag":"dns-out"}],"remarks":"@FreeStrongVpn - 🇩🇪","routing":{"domainStrategy":"AsIs","rules":[{"inboundTag":["dns-in"],"outboundTag":"dns-out"},{"domain":["domain:googleapis.cn"],"outboundTag":"proxy"},{"ip":["geoip:private"],"outboundTag":"direct"},{"ip":["geoip:cn"],"outboundTag":"direct"},{"domain":["geosite:cn"],"outboundTag":"direct"},{"domain":["geosite:geolocation-cn"],"outboundTag":"direct"},{"outboundTag":"proxy","port":"0-65535"}]}}

**Comment by Yadollah** [comment]
Hi
I installed version 1.9.0 and tested the issue , it was the same and app crashed.

**Comment by Yadollah** [comment]
Hi
I installed version 1.9.1 and tested the issue , it was the same and app crashed.
Please fix this bug.
Thanks

**Comment by 2dust** [comment]
Unable to reproduce the problem. Please try another device.

**Comment by Yadollah** [comment]
Tried and the issue persists.
![Screenshot_۲۰۲۴۰۹۲۷_۰۲۵۱۵۹_v2rayNG](https://github.com/user-attachments/assets/925a45a4-bc11-4b81-91d6-3818a539e448)
![Screenshot_20240927_025107_One UI Home](https://github.com/user-attachments/assets/488b894a-a095-4450-ac2d-82ff0efdcd37)
In the photos you can see that the V2rayNG Crashes.

I installed 1.9.3 and the issue is still there.
For more clarification look in the other picture , error happens when i import using option 1 , and when i use custom config option 2  the issue doesn't happen.

Check it out using this customize config : (there`s an extra { at the begining)

{{"dns":{"hosts":{"domain:googleapis.cn":"googleapis.com"},"servers":[{"address":"fakedns","domains":["geosite:cn"]},"https://94.140.14.14/dns-query",{"address":"https://94.140.14.14/dns-query","domains":["geosite:cn","geosite:geolocation-cn"],"expectIPs":["geoip:cn"],"port":53}]},"fakedns":[{"ipPool":"198.18.0.0/15","poolSize":10000}],"inbounds":[{"listen":"127.0.0.1","port":10808,"protocol":"socks","settings":{"auth":"noauth","udp":true,"userLevel":8},"sniffing":{"destOverride":["http","tls","fakedns"],"enabled":true,"routeOnly":true},"tag":"socks"},{"listen":"127.0.0.1","port":10809,"protocol":"http","settings":{"userLevel":8},"tag":"http"},{"listen":"127.0.0.1","port":10853,"protocol":"dokodemo-door","settings":{"address":"1.1.1.1","network":"tcp,udp","port":53},"tag":"dns-in"}],"log":{"loglevel":"none"},"outbounds":[{"mux":{"concurrency":8,"enabled":true,"xudpConcurrency":8,"xudpProxyUDP443":"reject"},"protocol":"vless","settings":{"vnext":[{"address":"c.88981401.xyz","port":443,"users":[{"encryption":"none","flow":"","id":"5bdf790f-0af2-4481-a624-41b66e7e3489","level":8,"security":"auto"}]}]},"streamSettings":{"network":"ws","security":"tls","sockopt":{"dialerProxy":"fragment"},"tlsSettings":{"allowInsecure":false,"alpn":["http/1.1"],"fingerprint":"firefox","publicKey":"","serverName":"cdn.55994421.xyz","shortId":"","show":false,"spiderX":""},"wsSettings":{"headers":{"Host":"cdn.55994421.xyz","User-Agent":"Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"},"path":"/@ln2ray?ed=2560"}},"tag":"proxy"},{"protocol":"freedom","settings":{"domainStrategy":"UseIP"},"tag":"direct"},{"protocol":"blackhole","settings":{"response":{"type":"http"}},"tag":"block"},{"protocol":"freedom","settings":{"fragment":{"packets":"1-2","length":"4-6","interval":"8-15"}},"streamSettings":{"network":"tcp","security":"","sockopt":{"tcpfastopen":true,"TcpNoDelay":true,"mark":255}},"tag":"fragment"},{"protocol":"dns","tag":"dns-out"}],"remarks":"@FreeStrongVpn - 🇩🇪","routing":{"domainStrategy":"AsIs","rules":[{"inboundTag":["dns-in"],"outboundTag":"dns-out"},{"domain":["domain:googleapis.cn"],"outboundTag":"proxy"},{"ip":["geoip:private"],"outboundTag":"direct"},{"ip":["geoip:cn"],"outboundTag":"direct"},{"domain":["geosite:cn"],"outboundTag":"direct"},{"domain":["geosite:geolocation-cn"],"outboundTag":"direct"},{"outboundTag":"proxy","port":"0-65535"}]}}

**Comment by 2dust** [comment]
Adding exception handling solves the problem
You can check for json formatting errors with vscode
