### ISSUE TITLE
启动服务后，不能正常访问谷歌

### ISSUE THREAD

**Issue by 648480505** [2dust/v2rayNG#3535]
### 预期行为
服务启动后，可以正常访问谷歌等网站

### 实际行为
服务启动后，测试访问谷歌失败，net/http: TLS handshake timeou
### 复现方法
1.shadowsocks协议
2.选中一个在PC端可正常使用的节点并启动服务
3.修改真连接测试链接为 https://www.google.com
4.失败：net/http: TLS handshake timeou

### 日志信息
```
--------- beginning of main
09-05 20:13:30.172 E/com.v2ray.ang(19228): Not starting debugger since process cannot load the jdwp agent.
09-05 20:53:31.265 I/GoLog (19565): Not Using Prepared: tcp,main.gamecenter.vivo.com.cn:443
```
</details>

### 环境信息
vivo oriainos系统，安卓12

**Comment by wengzhenquan** [comment]
换个节点试试，不能排除节点的问题，因为不知道你节点的属性。
建议在设置中，启用以下配置，再进行尝试：
1、启用本地dns
2、启用分片
3、跳过证书验证

如果启用以上配置依旧不行，可能节点失效，或者节点信息配置错误。
2ray支持ss协议，理论上不存在内核不兼容问题

**Comment by bytrix** [comment]
> 换个节点试试，不能排除节点的问题，因为不知道你节点的属性。 建议在设置中，启用以下配置，再进行尝试： 1、启用本地dns 2、启用分片 3、跳过证书验证
> 
> 如果启用以上配置依旧不行，可能节点失效，或者节点信息配置错误。 2ray支持ss协议，理论上不存在内核不兼容问题

同样的节点（分享二维码），在PC端可以正常使用，安卓端就提示超时

**Comment by wengzhenquan** [comment]
> > 换个节点试试，不能排除节点的问题，因为不知道你节点的属性。 建议在设置中，启用以下配置，再进行尝试： 1、启用本地dns 2、启用分片 3、跳过证书验证
> > 如果启用以上配置依旧不行，可能节点失效，或者节点信息配置错误。 2ray支持ss协议，理论上不存在内核不兼容问题
> 
> 同样的节点（分享二维码），在PC端可以正常使用，安卓端就提示超时

检查节点配置，看看加载到软件里面，是否有信息没加载出来，对比一下，比如SNI信息等等。
另外，电脑版功能确实比较多，比如兼容了sing-box内核。我把同一个节点，放在不同软件里面，也有存在差异的情况，这很正常。
你不把节点发出来测试，别人也不知道是什么问题。
如果你仅使用机场节点，建议使用机场APP，保证可用性。
v2rayNG目前还是有不少缺点，适应最好的还是vless、Trojan、vmess。大概你的ss节点的传输协议在这款APP里支持的不是很好，换个APP试试
Nekobox的功能更接近电脑版v2rayN，可以尝试一下。

如果是某个节点不支持，你可以把节点发出来，我们节点的ss节点可以使用，你单单这样说，根本无法进行测试，因为我们是正常的。
如果你是购买的节点，可以联系卖你节点的人问问
