### ISSUE TITLE
v2rayNG新版本在Andriod TV上无法使用

### ISSUE THREAD

**Issue by atkins126** [2dust/v2rayNG#3537]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

发现v2rayNG_1.8.29_armeabi-v7a.apk 之后的版本无法在Andriod TV上正常使用，原来的节点测速都超慢。
无法代理上网，回退旧版本后恢复正常

### 预期行为
描述你认为应该发生什么

在给Andriod TV上的v2rayNG升级版本时发现新版本都无法使用

v2rayNG_1.8.29 之后的版本无法在Andriod TV上正常使用
节点测试速度慢十倍，几乎无法使用。

### 实际行为
描述实际发生了什么

**Comment by ZeusMax1130** [comment]
有些年头的小米电视3，1.8.39通用版本，能安装，能TCping，延迟也都在80ms左右，能启动，一切都看起来很好。。。。但是，不出意外就还是意外了，换了好几个版本，无论怎么也不能上网。。。。有大神指导一下吗

**Comment by 2dust** [comment]
哪个版本能用就先用着，因为此app并未在tv上测试过
