### ISSUE TITLE
function requested 

### ISSUE THREAD

**Issue by lotus6808** [2dust/v2rayNG#3538]
When there're many configurations, Threre always will be some of them become no longer available,then I'll have to change it to others once I notice.So I guess It might be perfect if v2rayng done this automatically.Of cause it's good app already,thank you.

**Comment by codewithtamim** [comment]
You mean auto sorting the working configs and remove the expired once ? I mean configs that are not working?

**Comment by lotus6808** [comment]
Once the node we're connecting expired, I wish v2rayng itself has an option to switch to other available nodes by itself,or push notification on statu bar rather then nothing happens,like"connection timeout",but please let users decide to keep or remove unavailable configurations.
