### ISSUE TITLE
全局直连逻辑有问题

### ISSUE THREAD

**Issue by xzlosats111** [2dust/v2rayNG#3544]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
自定义规则里面填写走代理的域名走代理，其余所有流量走直连

### 实际行为
按照如下设置项设置全局直连，自定义规则里面有写代理的域名可以走代理访问，剩下来的所有网址无法访问，后删除了自定义规则里面的直连和拦截，依旧是这样的情况
并且写在直连规则里的网址也没法直连访问，显示连接超时，使用其他预定规则可以正常按照规则里描述的分流方式上网，且自定义规则也能覆盖生效

![365444610-ac60c87a-b175-4d04-bfa5-0672ebd88e32](https://github.com/user-attachments/assets/6bbbd19a-e4b6-4672-8a65-1d9e08f3f0e2)

![365444612-a4616370-e62d-4578-9129-94a7213d4a11](https://github.com/user-attachments/assets/0b65d7b2-2ff7-4caf-a681-2cd68dbed048)

![365444615-a22cf75b-68ab-4fc9-9182-de5df0f6186d](https://github.com/user-attachments/assets/d0323e2c-1c70-47c5-9048-12d49fd98aa0)

![365444975-715e7428-6fc1-43cf-bcd2-0d3400336f02](https://github.com/user-attachments/assets/1ab2a460-62c6-49e5-a9e4-d22902961ac7)

### 日志信息
<details>

</details>

### 额外信息（可选）
版本1.8.36/38都试了

**Comment by wengzhenquan** [comment]
确实如此，我也发现了，自定义规则之中的直连逻辑并不生效。
测试版本:1.8.38
我使用了两个网站测试。
1、www.daoyunai.com（该网站只能直连访问，走代理就会403）
2、谷歌，（该网站必须成功走代理才能访问）
我将两个地址全配置在直连里面。
预期效果：
测试地址1：可以正常访问。
测试地址2：无法正常访问。

实际效果：
测试地址1：无法正常访问。
测试地址2：正常访问。

测试结果：全部错误，直连无法生效。

场景：因为打开国内网站的时候，发现打开速度很慢，但去掉代理，或者改成“全部直连”，才能恢复速度。
本来我没有使用自定义规则，一直使用预定义规则，“绕过局域网和大陆地址后代理”，为此，我开始尝试使用自定义规则进行测试。
在这个测试过程中，预定义规则反复在“全部代理”、“绕过……后代理”、以及“全部直连”三个选项中切换，发现，不论自定义规则如何配置，只能选择“全部直连”才能完全实现直连上面两个网站的效果。

最终发现，自定义规则中的直连逻辑不生效。

www.daoyunai.com无法进行绕过，除非改成“全部直连”，即便手动配置直连，也无法实现。
然后用谷歌地址测试直连，理论上直连谷歌应该打不开才算正常，但却依旧打开了。

**如果是因为我设置错误导致的问题，还请指出，谢谢。**

配置截图：
![IMG_20240911_152512](https://github.com/user-attachments/assets/842ff527-3f85-43e6-a8cd-32c06988a7cf)

**Comment by 2dust** [comment]
等下一版，路由改变了
