### ISSUE TITLE
安卓端v2rayng如何设置仅代理gfw

### ISSUE THREAD

**Issue by veizei-K** [2dust/v2rayNG#3545]
希望可以和电脑端的v2rayn一样，有三种代理模式，全局，绕过和只代理gfw。这样国内的这些网站不会出现异常，比如123和兰奏等其他的不知名的网站会被代理从而导致打不开。

还有我的红米澎湃OS系统的控制栏的图标加载慢，每次下滑控制栏的时候，图标都会重新打开，但是功能是正常的，只是显示不正常，是软件的问题还是系统的问题？但是我测试clash和nekobox都没有这个问题。
![video2gif_20240910_150444](https://github.com/user-attachments/assets/0f7adb8d-fc1b-4b74-892e-829f179399c8)

**Comment by wengzhenquan** [comment]
本来就存在你需要的模式。
预定义规则里的两种模式都能满足你，建议使用“绕过局域网和大陆地址后代理”。
记得更新Geo资源文件，这里涉及绕过规则
![IMG_20240911_165658](https://github.com/user-attachments/assets/556be2a1-d5f2-40e0-b876-e161881cf0a7)

**Comment by veizei-K** [comment]
> 本来就存在你需要的模式。 预定义规则里的两种模式都能满足你，建议使用“绕过局域网和大陆地址后代理”。 记得更新Geo资源文件，这里涉及绕过规则 ![IMG_20240911_165658](https://private-user-images.githubusercontent.com/23743586/366378678-556be2a1-d5f2-40e0-b876-e161881cf0a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjE2MTUsIm5iZiI6MTcyNjA2MTMxNSwicGF0aCI6Ii8yMzc0MzU4Ni8zNjYzNzg2NzgtNTU2YmUyYTEtZDVmMi00MGUwLWI4NzYtZTE2MTg4MWNmMGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEzMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NTcwYTY4ODIxMDhmNmZjNDUzMmYyYzNlZDQ2NWVhMDYyNjc2MmI5NGVhMGZjMGViMmJjZjU0NDIyZDljZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smzgMHBhRJk2h4fVAQUSlYWgS6W4zLZOREahTaZz3ZM)

这里的绕过大陆地址是白名单模式吧，也就是只有大陆网站的域名不走代理。我想要的是只让在中国大陆防火墙的那些黑名单走代理
![image](https://github.com/user-attachments/assets/f6623a14-8048-42c9-9471-70e5e7940401)

**Comment by wengzhenquan** [comment]
> > 本来就存在你需要的模式。 预定义规则里的两种模式都能满足你，建议使用“绕过局域网和大陆地址后代理”。 记得更新Geo资源文件，这里涉及绕过规则 ![IMG_20240911_165658](https://private-user-images.githubusercontent.com/23743586/366378678-556be2a1-d5f2-40e0-b876-e161881cf0a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjE2MTUsIm5iZiI6MTcyNjA2MTMxNSwicGF0aCI6Ii8yMzc0MzU4Ni8zNjYzNzg2NzgtNTU2YmUyYTEtZDVmMi00MGUwLWI4NzYtZTE2MTg4MWNmMGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEzMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NTcwYTY4ODIxMDhmNmZjNDUzMmYyYzNlZDQ2NWVhMDYyNjc2MmI5NGVhMGZjMGViMmJjZjU0NDIyZDljZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smzgMHBhRJk2h4fVAQUSlYWgS6W4zLZOREahTaZz3ZM)
> 
> 这里的绕过大陆地址是白名单模式吧，也就是只有大陆网站的域名不走代理。我想要的是只让在中国大陆防火墙的那些黑名单走代理 ![image](https://private-user-images.githubusercontent.com/129288685/366476577-f6623a14-8048-42c9-9471-70e5e7940401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjg2NzEsIm5iZiI6MTcyNjA2ODM3MSwicGF0aCI6Ii8xMjkyODg2ODUvMzY2NDc2NTc3LWY2NjIzYTE0LTgwNDgtNDJjOS05NDcxLTcwZTVlNzk0MDQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNTI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjNjMjhjYWUyMDJkM2RjOTEwYWMyNTY1NmI1ZWUyOThjOGNiMGNlMjNkYzk4MGFlN2ZjYzE4MTgxZjM1ODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.297_2bwJx0Js3hNTLE0S65XdNIi9ToHDnP-O0HAIxIQ)

那你可以自己去整理网站。
被强的网站是整个世界那么多国家，那些网站你自己去收集吧。
目前网友能做到的仅仅是收集国内的网站，然后绕过国内那些网站，仅仅是一个国家的网站，都收集的不齐全，别说全世界几百个国家了。
这些项目而且都是公益的免费项目，已经很耗费精力了。
用户如果有特殊需求，可以在“自定义规则”里面添加，每个人的上网需求都不一样，私人定制会比统一的收集好，因为去匹配也需要耗费时间，收集越多，访问速度越慢，延迟越高，最终会得不偿失。

**Comment by veizei-K** [comment]
> > > 本来就存在你需要的模式。 预定义规则里的两种模式都能满足你，建议使用“绕过局域网和大陆地址后代理”。 记得更新Geo资源文件，这里涉及绕过规则 ![IMG_20240911_165658](https://private-user-images.githubusercontent.com/23743586/366378678-556be2a1-d5f2-40e0-b876-e161881cf0a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjE2MTUsIm5iZiI6MTcyNjA2MTMxNSwicGF0aCI6Ii8yMzc0MzU4Ni8zNjYzNzg2NzgtNTU2YmUyYTEtZDVmMi00MGUwLWI4NzYtZTE2MTg4MWNmMGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEzMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NTcwYTY4ODIxMDhmNmZjNDUzMmYyYzNlZDQ2NWVhMDYyNjc2MmI5NGVhMGZjMGViMmJjZjU0NDIyZDljZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smzgMHBhRJk2h4fVAQUSlYWgS6W4zLZOREahTaZz3ZM)
> > 
> > 
> > 这里的绕过大陆地址是白名单模式吧，也就是只有大陆网站的域名不走代理。我想要的是只让在中国大陆防火墙的那些黑名单走代理 ![image](https://private-user-images.githubusercontent.com/129288685/366476577-f6623a14-8048-42c9-9471-70e5e7940401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjg2NzEsIm5iZiI6MTcyNjA2ODM3MSwicGF0aCI6Ii8xMjkyODg2ODUvMzY2NDc2NTc3LWY2NjIzYTE0LTgwNDgtNDJjOS05NDcxLTcwZTVlNzk0MDQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNTI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjNjMjhjYWUyMDJkM2RjOTEwYWMyNTY1NmI1ZWUyOThjOGNiMGNlMjNkYzk4MGFlN2ZjYzE4MTgxZjM1ODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.297_2bwJx0Js3hNTLE0S65XdNIi9ToHDnP-O0HAIxIQ)
> 
> 那你可以自己去整理网站。 被强的网站是整个世界那么多国家，那些网站你自己去收集吧。 目前网友能做到的仅仅是收集国内的网站，然后绕过国内那些网站，仅仅是一个国家的网站，都收集的不齐全，别说全世界几百个国家了。 这些项目而且都是公益的免费项目，已经很耗费精力了。 用户如果有特殊需求，可以在“自定义规则”里面添加，每个人的上网需求都不一样，私人定制会比统一的收集好，因为去匹配也需要耗费时间，收集越多，访问速度越慢，延迟越高，最终会得不偿失。

你是不是不懂啊，算了，说的驴唇不对马嘴。

**Comment by wengzhenquan** [comment]
> > > > 本来就存在你需要的模式。 预定义规则里的两种模式都能满足你，建议使用“绕过局域网和大陆地址后代理”。 记得更新Geo资源文件，这里涉及绕过规则 ![IMG_20240911_165658](https://private-user-images.githubusercontent.com/23743586/366378678-556be2a1-d5f2-40e0-b876-e161881cf0a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjE2MTUsIm5iZiI6MTcyNjA2MTMxNSwicGF0aCI6Ii8yMzc0MzU4Ni8zNjYzNzg2NzgtNTU2YmUyYTEtZDVmMi00MGUwLWI4NzYtZTE2MTg4MWNmMGE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDEzMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NTcwYTY4ODIxMDhmNmZjNDUzMmYyYzNlZDQ2NWVhMDYyNjc2MmI5NGVhMGZjMGViMmJjZjU0NDIyZDljZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smzgMHBhRJk2h4fVAQUSlYWgS6W4zLZOREahTaZz3ZM)
> > > 
> > > 
> > > 这里的绕过大陆地址是白名单模式吧，也就是只有大陆网站的域名不走代理。我想要的是只让在中国大陆防火墙的那些黑名单走代理 ![image](https://private-user-images.githubusercontent.com/129288685/366476577-f6623a14-8048-42c9-9471-70e5e7940401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjg2NzEsIm5iZiI6MTcyNjA2ODM3MSwicGF0aCI6Ii8xMjkyODg2ODUvMzY2NDc2NTc3LWY2NjIzYTE0LTgwNDgtNDJjOS05NDcxLTcwZTVlNzk0MDQwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxNTI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjNjMjhjYWUyMDJkM2RjOTEwYWMyNTY1NmI1ZWUyOThjOGNiMGNlMjNkYzk4MGFlN2ZjYzE4MTgxZjM1ODc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.297_2bwJx0Js3hNTLE0S65XdNIi9ToHDnP-O0HAIxIQ)
> > 
> > 
> > 那你可以自己去整理网站。 被强的网站是整个世界那么多国家，那些网站你自己去收集吧。 目前网友能做到的仅仅是收集国内的网站，然后绕过国内那些网站，仅仅是一个国家的网站，都收集的不齐全，别说全世界几百个国家了。 这些项目而且都是公益的免费项目，已经很耗费精力了。 用户如果有特殊需求，可以在“自定义规则”里面添加，每个人的上网需求都不一样，私人定制会比统一的收集好，因为去匹配也需要耗费时间，收集越多，访问速度越慢，延迟越高，最终会得不偿失。
> 
> 你是不是不懂啊，算了，说的驴唇不对马嘴。

你要的不就是黑名单模式吗？
gfw墙的那些网站，全世界那么多。
你跟白名单模式反着来，就是黑名单模式，gfw墙的网站就是黑名单。

**Comment by 2dust** [comment]
黑名单这样做， 设置全局直连，然后把下面的加入到代理页面中
```
geosite:gfw,
geosite:greatfire
```

**Comment by 2dust** [comment]
其实本app最好直接设置分应用代理，那样性能好更省电，不需要用路由规则

**Comment by veizei-K** [comment]
> 其实本app最好直接设置分应用代理，那样性能好更省电，不需要用路由规则

我已经是分应用代理了。但是浏览器还是需要分流，除了浏览器别的倒是不用规则。而且浏览器有时候下载的时候会提示ssl错误

**Comment by veizei-K** [comment]
> 黑名单这样做， 设置全局直连，然后把下面的加入到代理页面中
> 
> ```
> geosite:gfw,
> geosite:greatfire
> ```

感谢，确实可行。
但是电报APP不能用了

**Comment by 2dust** [comment]
```
1.0.0.1,
1.1.1.1,
8.8.8.8,
8.8.4.4,
geoip:facebook,
geoip:fastly,
geoip:google,
geoip:netflix,
geoip:telegram,
geoip:twitter
```
加入到代理页面中

**Comment by freedomspiritJohn** [comment]
> ```
> 1.0.0.1,
> 1.1.1.1,
> 8.8.8.8,
> 8.8.4.4,
> geoip:facebook,
> geoip:fastly,
> geoip:google,
> geoip:netflix,
> geoip:telegram,
> geoip:twitter
> ```
> 
> 加入到代理页面中

把这些规则加到自定义规则后启动服务的时候提示启动服务失败

**Comment by veizei-K** [comment]
> ```
> 1.0.0.1,
> 1.1.1.1,
> 8.8.8.8,
> 8.8.4.4,
> geoip:facebook,
> geoip:fastly,
> geoip:google,
> geoip:netflix,
> geoip:telegram,
> geoip:twitter
> ```
> 
> 加入到代理页面中

可以了，谢谢。
