### ISSUE TITLE
增加多DNS支持 或 直接由服务器来解析DNS

### ISSUE THREAD

**Issue by if1y** [2dust/v2rayNG#355]
希望能够支持填写多个DNS地址，之间通过逗号隔开，就和v2rayN那样。

有这个想法的原因是：
手头有一台纯IPV6的机器，APP默认的dns是v4的，解析失败，导致节点没网。把APP内的dns手动填写为ipv6就解决了问题。
但是这样改了之后，需要暂时用其他节点，就很麻烦，要来回切换修改APP的dns设置。
如果能填写多个就好了。
或者如果能让APP不指定dns，而是直接向节点服务器请求其系统本地dns，应该是最好的，不知道v2ray能不能有这样的支持。

当然，多dns的目的应该是多个返回取最优，利于优化网络速度。

**Comment by jarvanh** [comment]
+1

**Comment by xianren78** [comment]
支持一下，希望可以设置

**Comment by yuhan6665** [comment]
It is already supported. You can input more than one DNS and separate them by ","

"Enable local DNS" should make most of your DNS request sent through proxy server.

**Comment by if1y** [comment]
> It is already supported. You can input more than one DNS and separate them by ","
> 
> "Enable local DNS" should make most of your DNS request sent through proxy server.

是现在开始支持的么

**Comment by yuhan6665** [comment]
@yesmiley from what I can tell this is supported for a long time

**Comment by rurirei** [comment]
> I hope to support multiple DNS addresses, separated by commas, just like v2rayN

already done as Yuhan6665 said

> If you can let the APP not specify the dns, but directly request the local dns of its system from the node server, it should be the best, I don’t know if v2ray can have such support

simply impossible (differences of mobile platform), unless enables to LocalDNS (super less performance #709 )

> I hope to support multiple DNS addresses, separated by commas, just like v2rayN

impossible as check document of dns of v2ray
