### ISSUE TITLE
Subscription Update not working !

### ISSUE THREAD

**Issue by Aryxgraphy** [2dust/v2rayNG#3556]
Hello, have good time
auto update not working for Subscription at all the time 15 min or 1 hour
can you add an option for
when apps open , then update sub everytime when app open?
like iphones apps ..
and one more thing
can you add singbox core too?
thanks a lot have a great day 🌹❤️

**Comment by 2dust** [comment]
Auto-update is affected by the system of the device, he may not always be able to activate it
