### ISSUE TITLE
自定义规则的优先级是自前至后吗？

### ISSUE THREAD

**Issue by Trudeau566** [2dust/v2rayNG#3557]
我想让bing.com走代理。cn.bing.com及rewards.bing.com走直连，好像目前的规则实现不了？

**Comment by 2dust** [comment]
你的规则模式选择了什么？

**Comment by Trudeau566** [comment]
> 你的规则模式选择了什么？

我设置了自定义规则bing.com走代理，rewards.bing.com走直连，在全局代理及绕过大陆下rewards.bing.com都会走代理，全局直连下rewards.bing.com可以直连。同样的设置电脑版就没问题
