### ISSUE TITLE
Double Ping System (Direct & Tunneling Ping)

### ISSUE THREAD

**Issue by ItzGlace** [2dust/v2rayNG#3558]
I’d like to propose a feature enhancement for V2RayNG that would provide users with a more comprehensive view of their internet and VPN connection quality through a **double ping system**.

### Feature Overview:
The double ping system would perform two HTTP ping requests each time a user connects to a server:

1. **Direct HTTP Ping**: This would be a standard ping to the server outside of the VPN tunnel, showing the regular latency between the user’s device and the google.com / cp.cloudflare.com (without VPN interference). This reflects the user's overall internet connection quality.
   
2. **Tunneled HTTP Ping**: This ping would occur through the VPN tunnel, displaying the latency within the VPN network. This provides insight into the VPN's impact on latency and connection quality.

### Benefits:
- **Internet Quality Check**: By seeing both the direct and tunneled pings, users can gauge the quality of their internet connection in addition to the VPN's performance.
- **Better Troubleshooting**: Users will be able to differentiate if latency issues stem from their internet service provider or from the VPN service itself.
- **Informed Server Selection**: With both ping results available, users can make more informed decisions about which server to connect to, based on both server latency and overall network quality.

I believe this feature would add a lot of value for users who need to monitor both their internet quality and VPN performance in real-time. It would also help identify any bottlenecks, ensuring a smoother browsing or streaming experience.

Thank you for considering this suggestion!

**Comment by 2dust** [comment]
Sorry, no plans.
