### ISSUE TITLE
三处与预期不符的行为

### ISSUE THREAD

**Issue by RPRX** [2dust/v2rayNG#356]
最新版 v2rayNG（1.2.4）和 v2rayN（3.14）

### 预期行为
1.扫二维码导入PC端配置时，”加密方式“与PC端配置相同
2.底层传输安全选”tls“时，有”allowInsecure“选项
3.”传输协议“应决定”伪装类型“的可选范围，像PC端一样

### 实际行为
1.扫二维码导入PC端配置时，”加密方式“会变为”auto“
2.底层传输安全选”tls“时，无”allowInsecure“选项
3.”伪装类型“的可选范围不受”传输协议“影响

感谢作者为此项目的付出，希望修改为与预期行为一致

（其中第3点非必要）

**Comment by RPRX** [comment]
补充：均为 VMess 协议

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)
