### ISSUE TITLE
Add warp ability in setting core

### ISSUE THREAD

**Issue by softmaj7** [2dust/v2rayNG#3562]
Hi there
Warp is an important ability which could be usefull. Sometimes we use it in terminal or xui panel but have some issues. I wonder if you could add warp in v2rayNG which user can switch on or off with one button. like Mahsang Software you can find it here
https://play.google.com/store/apps/details?id=com.MahsaNet.MahsaNG
![Screenshot_2024-09-15-13-07-13-176_com MahsaNet MahsaNG](https://github.com/user-attachments/assets/464ba54b-f6a4-4ec6-be63-d692cf0f2c0a)

Thanks 😊

**Comment by 2dust** [comment]
not plan
