### ISSUE TITLE
[Feature request] browser dialer support

### ISSUE THREAD

**Issue by mmmray** [2dust/v2rayNG#3571]
https://xtls.github.io/config/features/browser_dialer.html

Quite a few iranian users have reported that this performs better than *any* uTLS fingerprint. However, the usage with various GUIs is not convenient. The exclave Android client by @dyhkwong has support for v2fly's browser forwarder, which does the same thing and brings similar improvements over utls.

Right now it's not possible to use this from v2rayNG at all, because an environment variable has to be set. I think v2rayNG can expose the env var as yet another global setting, so that users can:

1. launch v2rayng and enable browser dialer in settings
2. then open localhost in their Chrome for Android
3. exclude Chrome for Android from TUN in v2rayNG

Ideally, v2rayNG would have its own hidden webview to launch the full browser dialer itself, like Exclave, but this seems harder to achieve.

If there are any changes necessary in xray (such as, moving away from an env var), please let me know.

I have no idea how battery optimization can be addressed.

**Comment by SoldierFace** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by iambabyninja** [comment]
It’s good idea 👍

**Comment by mmmray** [comment]
is a PR welcome or not?

**Comment by 2dust** [comment]
Too complex to implement and too complex for mobile users to operate
And cell phones have many limitations that make it difficult to achieve the goal

**Comment by dyhkwong** [comment]
The traffic of browser dialer is out of core's control, so it is difficult to prevent traffic loopback. In SagerNet's code, it only bypasses SNI, Host and server address in routing. This is not enough and will still cause issues in some cases.
If you say "dedicated browser with VPN bypassed" is acceptable, I guess you need either v2rayNG supports filling environment variables, or xray supports configuring browser dialer through config file.

And AFAIK Xray's browser dialer does not support SNI or "Host".

**Comment by 2dust** [comment]
> The traffic of browser dialer is out of core's control, so it is difficult to prevent traffic loopback. In SagerNet's code, it only bypasses SNI, Host and server address in routing. This is not enough and will still cause issues in some cases. If you say "dedicated browser with VPN bypassed" is acceptable, I guess you need either v2rayNG supports filling environment variables, or xray supports configuring browser dialer through config file.
> 
> And AFAIK Xray's browser dialer does not support SNI or "Host".

Thank you for your work.
There's no need to spend time on this feature when other ways are still available

**Comment by salehMomtaz** [comment]
As i see by other ways you mean only utls?
