### ISSUE TITLE
v2flyNG 安卓端，部分应用能上网，部分应用不能上网

### ISSUE THREAD

**Issue by zijietang** [2dust/v2rayNG#3574]
同一个节点（ss和vmess），PC端可以正常科学上网，但是安卓端部分可以上（x、telegram），部分不能上(google,via浏览器)

使用的是v2flyNG

设置的是分应用代理，确定这些应用都勾选了

xray版本是：1.8.24

跳过安全验证为ture

点击测试连接，能显示连接成功，延时xx毫秒

### 日志信息
--------- beginning of main
09-20 01:40:47.875 I/GoLog   (10628): 127.0.0.1:54533 accepted udp:1.1.1.1:53 [dns-out]
09-20 01:40:47.877 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:49.007 I/GoLog   (10628): tcp:127.0.0.1:50888 accepted tcp:69.195.177.128:443 [proxy]
09-20 01:40:49.007 I/GoLog   (10628): tcp:127.0.0.1:50884 accepted tcp:69.195.177.128:443 [proxy]
09-20 01:40:49.007 I/GoLog   (10628): tcp:127.0.0.1:50886 accepted tcp:69.195.177.128:443 [proxy]
09-20 01:40:49.010 I/GoLog   (10628): tcp:127.0.0.1:50900 accepted tcp:69.195.177.128:443 [proxy]
09-20 01:40:49.014 I/GoLog   (10628): tcp:127.0.0.1:50916 accepted tcp:69.195.177.128:443 [proxy]
09-20 01:40:49.018 I/GoLog   (10628): 127.0.0.1:47399 accepted udp:1.1.1.1:53 [dns-out]
09-20 01:40:49.166 I/GoLog   (10628): tcp:127.0.0.1:50930 accepted tcp:69.195.177.128:443 [proxy]
09-20 01:40:49.197 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:49.198 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:49.212 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:49.214 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:49.219 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:49.374 I/GoLog   (10628): Using Prepared: 137.220.42.38
09-20 01:40:50.365 I/GoLog   (10628): 127.0.0.1:41430 accepted udp:1.1.1.1:53 [dns-out]
09-20 01:40:53.862 I/GoLog   (10628): 127.0.0.1:37048 accepted udp:1.1.1.1:53 [dns-out]
09-20 01:40:59.031 I/GoLog   (10628): 127.0.0.1:52504 accepted udp:1.1.1.1:53 [dns-out]
09-20 01:40:59.042 I/GoLog   (10628): 127.0.0.1:52062 accepted udp:1.1.1.1:53 [dns-out]
09-20 01:41:00.380 I/GoLog   (10628): 127.0.0.1:49841 accepted udp:1.1.1.1:53 [dns-out]

**Comment by ddjdhshs** [comment]
ss://YWVzLTI1Ni1nY206ZXo3akJOc005SEQ1OWVWcUA2NS40OS4xOTcuMjA4Ojc1ODI=#JMS-620150%40c83s1.portablesubmarines.com%3A7582
ss://YWVzLTI1Ni1nY206ZXo3akJOc005SEQ1OWVWcUA5Ny42NC4yNC4xNTk6NzU4Mg==#JMS-620150%40c83s2.portablesubmarines.com%3A7582
vmess://eyJhZGQiOiIyMy4xMDUuMTkzLjUiLCJhaWQiOiIwIiwiaG9zdCI6IiIsImlkIjoiYmM1MTc3NDItZDdmZC00YWI4LTgxOTktNzBhZDdjZTk5NDQ2IiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiI3NTgyIiwicHMiOiJKTVMtNjIwMTUwQGM4M3MzLnBvcnRhYmxlc3VibWFyaW5lcy5jb206NzU4MiIsInNjeSI6ImF1dG8iLCJzbmkiOiIiLCJ0bHMiOiJub25lIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiJ9
vmess://eyJhZGQiOiIxNzguMTU3LjYzLjIzMSIsImFpZCI6IjAiLCJob3N0IjoiIiwiaWQiOiJiYzUxNzc0Mi1kN2ZkLTRhYjgtODE5OS03MGFkN2NlOTk0NDYiLCJuZXQiOiJ0Y3AiLCJwYXRoIjoiIiwicG9ydCI6Ijc1ODIiLCJwcyI6IkpNUy02MjAxNTBAYzgzczQucG9ydGFibGVzdWJtYXJpbmVzLmNvbTo3NTgyIiwic2N5IjoiYXV0byIsInNuaSI6IiIsInRscyI6Im5vbmUiLCJ0eXBlIjoibm9uZSIsInYiOiIyIn0=
vmess://eyJhZGQiOiIxMDQuMjQ1Ljk5LjQ5IiwiYWlkIjoiMCIsImhvc3QiOiIiLCJpZCI6ImJjNTE3NzQyLWQ3ZmQtNGFiOC04MTk5LTcwYWQ3Y2U5OTQ0NiIs
