### ISSUE TITLE
V2RayNG Android版，界面对IP地址的隐私保护格式有误

### ISSUE THREAD

**Issue by xubeiyan** [2dust/v2rayNG#3577]
对IP地址的星号隐私保护显示有误，但影响不大

### 预期行为
对123.123.123.12:8080这样的IP地址的隐私保护后应该为123.123.123.***:8080

### 实际行为
实际保护后为123.123.123***:8080

### 复现方法
1. 任意添加一个形如123.123.123.12:8080的节点
2. 在主界面上，对IP地址的星号隐私保护不正确，变成了123.123.123***:8080，如下图所示
![Screenshot_20240920-110323](https://github.com/user-attachments/assets/d29858f6-87a5-468b-a6d9-e9a6aee8d20e)

### 日志信息
无

### 环境信息
![Screenshot_20240920-110615](https://github.com/user-attachments/assets/fddb6994-f432-4745-a282-b27cba7c14e1)

### 额外信息（可选）
无

**Comment by 2dust** [comment]
没有分割处理，只是简单的替换了3个字符
