### ISSUE TITLE
V2RayN增加了一个新的功能，可以选择“多服务器负载均衡”，希望可以在V2RayNG中实现

### ISSUE THREAD

**Issue by iswhat** [2dust/v2rayNG#3578]
V2RayN增加了一个新的功能，可以选择“多服务器负载均衡”
在使用后发现这是一个极其好用的功能设计，希望可以在V2RayNG中实现

![屏幕截图 2024-09-20 145040](https://github.com/user-attachments/assets/41b1db4a-1e86-4fdf-b80a-27ac1f00f8dc)

**Comment by likaifenkeng** [comment]
分组多服务器最低延迟也重要。

**Comment by 2dust** [comment]
暂时没有计划，原因是需要修改lib部分，有此需求的可以试一试用cmfa
