### ISSUE TITLE
分应用代理无法扫描到全部应用

### ISSUE THREAD

**Issue by Hakoyu** [2dust/v2rayNG#3581]
### 预期行为
扫描到tachiyomi的扩展应用

### 实际行为
未扫描出tachiyomi的扩展应用

### 额外信息（可选）
v2rayng扫描结果
![Screenshot_20240921_200406_v2rayNG](https://github.com/user-attachments/assets/efeb928d-6e09-4a51-b954-5dcc8bdd81cb)

FIClash扫描结果
![Screenshot_20240921_200422](https://github.com/user-attachments/assets/240935a1-b36e-40ac-a991-47106bc37564)

**Comment by 2dust** [comment]
请提供几个app来测试

**Comment by Hakoyu** [comment]
[TachiyomYS](https://github.com/jobobby04/TachiyomiSY)
扩展插件: 
[Kemono.zip](https://github.com/user-attachments/files/17089980/Kemono.zip)

**Comment by 2dust** [comment]
已经找到原因，是因为本app过滤掉了无联网权限的app
下一版把这个限制去掉即可
