### ISSUE TITLE
DNS over QUIC 异常

### ISSUE THREAD

**Issue by X-Z-GitHub** [2dust/v2rayNG#3584]
我已经测试过quic+local://dns.alidns.com:853是可用的DNS服务器，是用ClashN的“当前连接”检测向此DNS服务器的连接。

### 预期行为
向此DNS over QUIC服务器的查询不应当出现日志中的错误。

### 实际行为
出现了日志中的读取服务器送回的报文的错误。

### 复现方法

按照如下配置设置v2rayNG。
[配置.txt](https://github.com/user-attachments/files/17090212/default.txt)

然后向路由规则到direct/freedom的任一域名发起连接。

### 日志信息

[日志.txt](https://github.com/user-attachments/files/17090216/default.txt)

**Comment by dyhkwong** [comment]
使用 Xray 配置向 Xray 反馈此问题，反馈内容以及修复方法参考 v2fly/v2ray-core#3024
