### ISSUE TITLE
DNS请求被错误地发送至26.26.26.2:853

### ISSUE THREAD

**Issue by HeXis-YS** [2dust/v2rayNG#3586]
出问题的代码应该是https://github.com/2dust/v2rayNG/blob/0501de1658728596e7efd0664a5a64271ded3859/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L141

这部分代码更新于一年前，猜测应该是想利用tun2socks的dnsgw功能将请求发送至Xray-core的DNS服务器。Xray-core的DNS服务器将会忽视IP地址，按照用户配置的服务器进行查询。只要系统发出的DNS查询请求是基于传统UDP的，就不会有太大问题。

但是现在默认的请求方式变为了DoT，dnsgw就不会处理这些请求，而是直接发送至设定的IP。

出于安全方面的考虑，建议把tun2socks使用的虚拟IP全部更换为内网IP，即使出现类似这样的问题，请求也不会被发送到公网。

**Comment by 2dust** [comment]
如果可以请PR下
