### ISSUE TITLE
Auto start and connect on boot

### ISSUE THREAD

**Issue by TheLordOfTheKings** [2dust/v2rayNG#3587]
Hi dear @2dust ,
Auto-start/Auto-connect is very handy, especially for Android TV.
Please consider implementing it.
Much regards.

**Comment by 2dust** [comment]
welcome PR

**Comment by codewithtamim** [comment]
@2dust I do a pr? it's quite easy lol

**Comment by codewithtamim** [comment]
added please close this issue

**Comment by iamhere2** [comment]
Finally, is the option for auto start and connect after boot implemented? Can't find it in the app settings
