### ISSUE TITLE
新版本还是不能连tiktok，还是要退回1.8.19

### ISSUE THREAD

**Issue by lys52** [2dust/v2rayNG#3595]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 13098724567** [comment]
tiktok是会检测sim卡的，跟v2rayng没关系

**Comment by V4444** [comment]
经过测试，还真是版本问题！之前一直怀疑是其他原因。
刚刚用相同节点测试。使用1.8.19版本，就可以正常打开看。使用最新版及1.9.x都不行
