### ISSUE TITLE
v1.9.1版本封鎖域名或ip失效

### ISSUE THREAD

**Issue by la8896** [2dust/v2rayNG#3596]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
Bug
### 实际行为
描述实际发生了什么
在自定规則設定封鎖域名及IP時失效
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

在自定规則設定封鎖域名及IP時失效

當滙出完整配置及從剪貼簿滙入配置后

查看配置發現
"domain":[
"abc.com",
"/n cde.com,
"/n fgh.com
]
即除了第一個域名或ip外
之后全部域名或ip開頭都多了/n

用手動配置也无法封鎖

**Comment by la8896** [comment]
大神您好,
剛剛測試了v1.9.3版本
雖然解決了域名前多了/n問題
但發現仍然是失效的
我嘗試導出配置
{
"domain":[
"abc.com"
],
"Ip": [
"1.2.3.4"
],
"outboundTag": "block",
"type": field"
},

但改為下面就能夠正常封鎖域名及ip
{
"domain":[
"abc.com"
],
"outboundTag": "block",
"type": "field"
},
"Ip": [
"1.2.3.4"
],
"outboundTag": "block",
"type": field"
},

**Comment by 2dust** [comment]
ray系列的路由规则条件是AND
所以一条规则里面不要同时放入domain和ip

**Comment by la8896** [comment]
> ray系列的路由规则条件是AND 所以一条规则里面不要同时放入domain和ip

分開规则正常了
谢谢大神
