### ISSUE TITLE
连接成功但无法上网？

### ISSUE THREAD

**Issue by ImSunshineYan** [2dust/v2rayNG#3597]
本人纯小白，还请大佬们指导
![4bfd613336a30bf5ab6821a11cd416b0](https://github.com/user-attachments/assets/e8480052-389f-4cc5-86c3-b6112aeb9b99)
![3954324c6aa862b3cb113444373ee0f4](https://github.com/user-attachments/assets/13c87731-b193-4138-a99c-acc77d08a266)
![ca7a25b014a9527932cc3c1fcb7ab5fc](https://github.com/user-attachments/assets/a56fe288-e099-4a85-a628-0f98edb427a4)

### 预期行为
显示连接成功并且成功进入YouTube网站与其他外网（瞬间进入）

### 实际行为
显示连接成功，但无法进入YouTube与其他外网（网速极慢）

### 复现方法
1.
2.
3.

### 日志信息
--------- beginning of main
09-24 19:19:11.442 I/GoLog   (22725): Using Prepared: 8.210.4.54
09-24 19:19:12.774 I/GoLog   (22725): Using Prepared: 8.210.4.54
09-24 19:19:19.610 I/com.v2ray.ang(22683): Settings ViewModel is cleared
09-24 19:19:20.044 I/GoLog   (22725): Using Prepared: 8.210.4.54
09-24 19:19:21.159 I/tun2socks(23045): NOTICE(tun2socks): termination requested
09-24 19:19:21.159 I/tun2socks(23045): NOTICE(tun2socks): tearing down
09-24 19:19:21.159 I/tun2socks(23045): NOTICE(tun2socks): Free TCP connections
09-24 19:19:21.159 I/tun2socks(23045): NOTICE(tun2socks): exiting
09-24 19:19:22.358 I/GoLog   (22725): loading core config
09-24 19:19:22.359 I/GoLog   (22725): Preparing Domain: 8.210.4.54:333
09-24 19:19:22.359 I/GoLog   (22725): Prepare Result:
09-24 19:19:22.359 I/GoLog   (22725):  Domain: 8.210.4.54
09-24 19:19:22.359 I/GoLog   (22725):  Port: 333
09-24 19:19:22.359 I/GoLog   (22725):  IPs: [8.210.4.54]
09-24 19:19:22.669 I/GoLog   (22725): new core
09-24 19:19:22.788 I/GoLog   (22725): start core
09-24 19:19:22.790 I/GoLog   (22725): [Warning] core: Xray 24.9.19 started
09-24 19:19:22.886 I/tun2socks(23311): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
09-24 19:19:22.906 I/tun2socks(23311): NOTICE(tun2socks): entering event loop
09-24 19:19:23.526 I/GoLog   (22725): Using Prepared: 8.210.4.54
09-24 19:20:11.141 I/GoLog   (22725): Using Prepared: 8.210.4.54
09-24 19:25:42.495 I/GoLog   (22725): Using Prepared: 8.210.4.54
通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

**Comment by reminx** [comment]
我也有这个问题

**Comment by bush911** [comment]
我是Google 家的都上不了，商店最新版这样子
升级到1.9.4后还是老样子。

**Comment by bush911** [comment]
无法访问Google 家，其他正常，日志如下

麻烦给看一下

--------- beginning of main
09-30 09:06:14.017 E/com.v2ray.ang(22026): Invalid resource ID 0x00000000.
09-30 09:06:18.627 W/com.v2ray.ang(22026): Cleared Reference was only reachable from finalizer (only reported once)
09-30 09:06:19.528 E/GoLog   (22026): Could not open module param file '/sys/module/mali_kbase/parameters/large_page_conf'
09-30 09:06:19.529 E/GoLog   (22026): Could not open module param file '/sys/module/mali_kbase/parameters/large_page_conf'
09-30 09:06:19.554 E/com.v2ray.ang(22026): Invalid resource ID 0x00000000.

**Comment by dylanleesky** [comment]
我遇到过类似问题，但我的网页能打开，GMS套件除了Chrome浏览器能打开网页外什么都失败。最后是想尽办法把GMS和play的数据清空了才恢复正常。单纯的设置里带的数据管理是无法清空的。必须是用户数据为0那种清空。另外，建议使用GMS时关掉定位和数据。

**Comment by SpaceForceX** [comment]
设置里面有一个关键选项：追加HTTP代理至VPN，这个钩上就好了

**Comment by coolcoolam** [comment]
> 设置里面有一个关键选项：添加HTTP代理至VPN，这个钩上就可以了

牛
