### ISSUE TITLE
搞个列表一键自动检测所有服务器存活怎么样，话说现在的检测延迟很大，是为什么？

### ISSUE THREAD

**Issue by 1265578519** [2dust/v2rayNG#36]
搞个列表一键自动检测所有服务器存活怎么样，话说现在的检测延迟很大，是为什么？

**Comment by deadlineOvO** [comment]
像是 shadowsocks/shadowsocksr 手机客户端那种？

**Comment by 1265578519** [comment]
对的，一个一个连接测试检测太麻烦。电脑端那边的V2RAYN不弄，，说就搞个ping检测

**Comment by deadlineOvO** [comment]
> 对的，一个一个连接测试检测太麻烦。电脑端那边的V2RAYN不弄，，说就搞个ping检测

检测的话，应该参考 shadowsocks 那边怎么检测的了

**Comment by minexss11** [comment]
> 像是 shadowsocks/shadowsocksr 手机客户端那种？

需要一个这样的检测工具

**Comment by deadlineOvO** [comment]
> 对的，一个一个连接测试检测太麻烦。电脑端那边的V2RAYN不弄，，说就搞个ping检测
顺便一提，ping 在这边检测不是很好，应该使用 tcp/udp ping 测试
