### ISSUE TITLE
google play无法下载软件

### ISSUE THREAD

**Issue by maplefz** [2dust/v2rayNG#36]
开的全局模式，其他应用都能走代理。google play自身也能正常浏览，但是就是下载软件没有速度

手机：nokia6二代
系统版本：android 8.0

软件版本是play上最新的0.3.10，上一版也是一样的问题

**Comment by kirbyzhu** [comment]
我的是google play不能正常浏览也无法导入个人信息，提示 无法检索服务器信息

**Comment by kirbyzhu** [comment]
@maplefz 清除v2rayng数据 清除谷歌play store数据。重新设置v2rayng的配置，分应用代理中勾选上下载管理器，设备认证**的。勾选mux，路由选择全局，千万不要选择绕过大陆或者geo全家桶。然后启动服务试试看。

**Comment by sofs2005** [comment]
全局了还要设置分应用代理吗？

**Comment by LKsworld** [comment]
不仅是谷歌商店，谷歌翻译也出现类似的问题，只有在全局和mux下才能正常工作

**Comment by 2dust** [comment]
终于弄清为何在路由绕开大陆地址时其他app正常翻墙，唯独PLAY会出现连接超时。只要把services.googleapis.cn加入v2rayNG的需代理列表，就行了。

**Comment by LKsworld** [comment]
@2dust 但是我设置绕过大陆，且开启绕行模式仅绕过国产应用， 同样无法下载谷歌商店应用和使用谷歌翻译

**Comment by kirbyzhu** [comment]
@LKsworld 设置全局代理 设置下载管理器通过v2ray

**Comment by yunfan** [comment]
能否提供个直接的apk文件下载呢 毕竟如果是完全没有代理的情况下 play访问不了呀 这是鸡生蛋 蛋生鸡的问题

**Comment by c0ldcat** [comment]
有可能是因为Play Store在Android 8.0+开了v2rayNG后不认WiFi导致的
shadowsocksrr/shadowsocksr-android/issues/89

**Comment by linhua55** [comment]
在应用设置里，清空 google  play的全部数据

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/issues/200

**Comment by WKZD** [comment]
> @maplefz 清除v2rayng数据 清除谷歌play store数据。重新设置v2rayng的配置，分应用代理中勾选上下载管理器，设备认证**的。勾选mux，路由选择全局，千万不要选择绕过大陆或者geo全家桶。然后启动服务试试看。
> 
> 可能你的问题是没有在分应用代理中没有勾选下载管理器。

请问分应用代理里面的绕行模式和路由有什么区别吗，或者说这两个功能各自的用法是什么，不是很懂，谢谢你。

**Comment by TrojanAZhen** [comment]
**我的解决办法是：**
* 1. 设置路由模式“全局”
* 2. 点“分应用代理”，选中“分应用代理”和“绕行模式”
* 3. 点右上角“自动选中需代理应用”
* 4. 清理所有后台程序，重新打开v2rayNG和谷歌商店
