### ISSUE TITLE
无法找到全局代理的选项

### ISSUE THREAD

**Issue by chenhaichen1002** [2dust/v2rayNG#3603]
升级版本后无法找到全局代理的选项，能否提供下打开全局代理的方法或者添加选项

目前版本号为 V1.92

**Comment by la8896** [comment]
![Screenshot_20240926_120548_v2rayNG](https://github.com/user-attachments/assets/0de29905-19dc-4850-99fb-c7a51a1cc806)

**Comment by chenhaichen1002** [comment]
> ![スクリーンショット_20240926_120548_v2rayNG](https://private-user-images.githubusercontent.com/35804411/370984425-0de29905-19dc-4850-99fb-c7a51a1cc806.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjc0NTQsIm5iZiI6MTcyNzMyNzE1NCwicGF0aCI6Ii8zNTgwNDQxMS8zNzA5ODQ0MjUtMGRlMjk5MDUtMTlkYy00ODUwLTk5ZmItYzdhNTFhMWNjODA2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA1MDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNWE2M2Y3M2NhOGY2OTM3ZWNlZDY4NWZiMTJmYWNjYjY3MmY5ZmRkOThhYmExOGUzYzBlYWZmOTZhOGQ3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fLNM26QPtb1MjU-NV0lwdGwByYjUuMREutJKAfERYfg)

感谢回复，请问您是怎么打开的。找不到打开的方案

**Comment by 2dust** [comment]
右上角点击导入，点击，选择

**Comment by ysqllake** [comment]
1.9.32版本可以按照以下操作：主界面左上角三条横线，路由设置，右上角三个点，导入预定义规则集，确定，全局（Global）
