### ISSUE TITLE
1.9.3版本切换全局后再切回来无法保留自定义路由

### ISSUE THREAD

**Issue by flamehe** [2dust/v2rayNG#3606]
### 预期行为
保留自定义路由

### 实际行为
导入预定义数据会删除现有

### 复现方法
1.路由设置
2.导入预设规则
3.

### 额外信息（可选）
建议加入自定义规则集profile用来保存自定义规则。否则就无法像之前版本一样方便的切换全局和自定义了。

**Comment by 2dust** [comment]
设置每条规则是否启用来达到全局和自定义切换

**Comment by flamehe** [comment]
这样的话切换就比较麻烦，得去切每一条规则

**Comment by 2dust** [comment]
如果做的类似v2rayN那样，在手机上操作过于复杂了

**Comment by 2dust** [comment]
如果给每条规则增加一个属性，比如叫永久保留（永不删除）
每次导入预定义规则的时候，这些规则就不删除，永远保留在最上面（因为保留在最下面就不起作用了）

你想想这样对你有帮助吗？

**Comment by flamehe** [comment]
这样应该也可以解决。或者给每条规则加个tag进行分组保存，然后可以导入某个tag的规则，是不是更方便一点。
