### ISSUE TITLE
Google Play 商店版本更新 测速 -1 无法正常启动

### ISSUE THREAD

**Issue by E-one-LLC** [2dust/v2rayNG#3608]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
启动服务失败，测速均为-1ms

### 实际行为
启动服务失败，测速均为-1ms
能添加订阅，能更新订阅 

### 复现方法
1. google play 商店版本更新 1.9.3（Lib V27,Xray-core V24.9.19）
2.出现启动服务失败，
3.测速均为-1ms

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
--------- beginning of crash
09-27 18:42:26.284 E/AndroidRuntime( 2461): FATAL EXCEPTION: main
09-27 18:42:26.284 E/AndroidRuntime( 2461): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 2461
09-27 18:42:26.284 E/AndroidRuntime( 2461): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9036dae u0 com.v2ray.ang/.service.V2RayProxyOnlyService c:com.v2ray.ang}
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.os.Looper.loopOnce(Looper.java:232)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.os.Looper.loop(Looper.java:317)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-27 18:42:26.284 E/AndroidRuntime( 2461): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
09-27 18:43:18.400 E/AndroidRuntime( 3013): FATAL EXCEPTION: main
09-27 18:43:18.400 E/AndroidRuntime( 3013): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 3013
09-27 18:43:18.400 E/AndroidRuntime( 3013): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a7f0763 u0 com.v2ray.ang/.service.V2RayProxyOnlyService c:com.v2ray.ang}
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.os.Looper.loopOnce(Looper.java:232)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.os.Looper.loop(Looper.java:317)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-27 18:43:18.400 E/AndroidRuntime( 3013): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
09-27 18:44:18.682 E/AndroidRuntime( 4000): FATAL EXCEPTION: main
09-27 18:44:18.682 E/AndroidRuntime( 4000): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 4000
09-27 18:44:18.682 E/AndroidRuntime( 4000): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{9206498 u0 com.v2ray.ang/.service.V2RayProxyOnlyService c:com.v2ray.ang}
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.os.Looper.loopOnce(Looper.java:232)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.os.Looper.loop(Looper.java:317)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-27 18:44:18.682 E/AndroidRuntime( 4000): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
09-27 18:44:52.241 E/AndroidRuntime( 4276): FATAL EXCEPTION: main
09-27 18:44:52.241 E/AndroidRuntime( 4276): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 4276
09-27 18:44:52.241 E/AndroidRuntime( 4276): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d1b626 u0 com.v2ray.ang/.service.V2RayProxyOnlyService c:com.v2ray.ang}
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.os.Looper.loopOnce(Looper.java:232)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.os.Looper.loop(Looper.java:317)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-27 18:44:52.241 E/AndroidRuntime( 4276): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
09-27 18:46:03.610 E/AndroidRuntime( 5281): FATAL EXCEPTION: main
09-27 18:46:03.610 E/AndroidRuntime( 5281): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 5281
09-27 18:46:03.610 E/AndroidRuntime( 5281): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{69bea9b u0 com.v2ray.ang/.service.V2RayProxyOnlyService c:com.v2ray.ang}
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.os.Looper.loopOnce(Looper.java:232)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.os.Looper.loop(Looper.java:317)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-27 18:46:03.610 E/AndroidRuntime( 5281): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
09-27 18:54:24.228 E/AndroidRuntime( 5518): FATAL EXCEPTION: main
09-27 18:54:24.228 E/AndroidRuntime( 5518): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 5518
09-27 18:54:24.228 E/AndroidRuntime( 5518): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1cdae0c u0 com.v2ray.ang/.service.V2RayProxyOnlyService c:com.v2ray.ang}
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2243)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2214)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2520)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.os.Looper.loopOnce(Looper.java:232)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.os.Looper.loop(Looper.java:317)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at java.lang.reflect.Method.invoke(Native Method)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
09-27 18:54:24.228 E/AndroidRuntime( 5518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
--------- beginning of main
09-27 22:28:31.109 E/com.v2ray.ang(29490): Invalid resource ID 0x00000000.

### 环境信息
v2rayNG 版本：1.9.3（Lib V27,Xray-core V24.9.19）
设备：pixel 7
Android 版本：14 
Build号：AP2A.240905.003

**Comment by 2dust** [comment]
把配置信息发出来

**Comment by E-one-LLC** [comment]
> 把配置信息发出来

谢谢大佬回复，恕我愚昧，您说的配置信息是指
路由设置的，
还是订阅分组的
还是关于里面的备份配置

**Comment by E-one-LLC** [comment]
> 把配置信息发出来

问题似乎是解决了 应该是我在路由配置里面添加的自定义规则， 隔开空格导致不能测速 
![Screenshot_20240928-123831](https://github.com/user-attachments/assets/9d8d77d4-58a3-4dad-ab03-50a35f39bbf3)
修改之后 就能测速 连接了

**Comment by E-one-LLC** [comment]
> 把配置信息发出来

请问大佬，新版本的路由规则设置，是不是不支持这样的单独一行了

下图规则设置，有两个问题，一是分隔有空格，二是一行一个

![Screenshot_20240928-125817](https://github.com/user-attachments/assets/58747a2f-6420-45ff-88ed-f9fca48fab1d)

我还是有点不懂，这个直连规则，无非就不生效，怎么会导致无法测速

期待大佬的解答

**Comment by E-one-LLC** [comment]
> 把配置信息发出来

请问大佬，新版本的路由规则设置，是不是不支持这样的单独一行了

下图规则设置，有两个问题，一是分隔有空格，二是一行一个

![Screenshot_20240928-130252](https://github.com/user-attachments/assets/429508c3-c80d-4bf6-938d-4cbe1ebedbd5)


我还是有点不懂，这个直连规则，无非就不生效，怎么会导致无法测速

期待大佬的解答

**Comment by 2dust** [comment]
空格问题新版已经解决了
你的设置有问题，xray的路由规则是AND关系，所以domain和ip一般不要同时填写，分开两条规则写

**Comment by E-one-LLC** [comment]
> 空格问题新版已经解决了 你的设置有问题，xray的路由规则是AND关系，所以domain和ip一般不要同时填写，分开谨慎写规则

懂了，谢谢大佬解惑！

Google play store 坐等更新。该问题，就关闭了
