### ISSUE TITLE
TLS能否加入allowinsecure和servername选项

### ISSUE THREAD

**Issue by okudayukiko** [2dust/v2rayNG#361]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
TLS能否加入allowinsecure选项和servername选项，避免MITM。V2RayNG的allowinsecure是true。
![20200411_201741](https://user-images.githubusercontent.com/17502357/79043452-d78ff900-7c31-11ea-9fac-a852ad8738c1.jpg)
![Screenshot_20200407-192204_v2rayNG](https://user-images.githubusercontent.com/17502357/79043463-e4145180-7c31-11ea-8447-c3325f700e82.jpg)

https://www.v2ray.com/chapter_02/05_transport.html

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by xianren78** [comment]
MIMT还是应该要防范于未然的

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.2.5

**Comment by okudayukiko** [comment]
但Google Play Store还没有更新最新的V2RayNG
