### ISSUE TITLE
建议把WebRTC这个值26.26.26.1修改为任意一个私有地址

### ISSUE THREAD

**Issue by h7g6b2v8cv** [2dust/v2rayNG#3617]
已经搜索过，以前没有人提出过类似的问题

### 预期行为
建议把WebRTC这个值26.26.26.1修改为任意一个随机变化的私有地址

### 实际行为
实际使用中WebRTC这个值老是显示为26.26.26.1，这导致本软件在网络上的特征很明显

### 复现方法
1.正常使用本软件。
2.打开浏览器，
3.访问ipleak.net.在WebRTC检测内容中始终可见26.26.26.1

### 日志信息
无

### 环境信息
Android13

**Comment by Ynkcc** [comment]
@2dust 希望能够提供设置入口，自定义tun网卡ip地址
10.10.10.1/30与我内网地址冲突，我使用v2rayng作为socks客户端连接内网的socks服务器

**Comment by Ynkcc** [comment]
> @2dust 希望能够提供设置入口，自定义tun网卡ip地址 10.10.10.1/30与我内网地址冲突，我使用v2rayng作为socks客户端连接内网的socks服务器

内网地址冲突，导致无法使用最新版本v2rayng连接内网socks服务器

**Comment by 2dust** [comment]
自定义不做了，选一个没有人用的地址
