### ISSUE TITLE
1.9.4 Hysteria2 missing obfuscation password input field (salamander).

### ISSUE THREAD

**Issue by FreestyleSasuke** [2dust/v2rayNG#3619]
As the title says there is no field in the app for input of the obfs password for hysteria2.

![image](https://github.com/user-attachments/assets/67e362fa-6b19-4f54-91f6-42221a3fc2ec)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/commit/ed8fb7fa82712d4dd4a403746f9f3810766c982d
