### ISSUE TITLE
bug：启用更新，自动勾选

### ISSUE THREAD

**Issue by wengzhenquan** [2dust/v2rayNG#3625]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
手动开启自动更新功能。

### 实际行为
编辑其它分组保存以后，退出分组管理页面，再

重新进入分组管理页面，发现下面这几个分组的“自动更新”被开启。
实际上这三个分组的“自动更新”已经被我关闭，并且没有手动打开。

我反复尝试，都是如此。
根本没有勾选这三个，但编辑其它分组保存过后，重新进入这个页面，却发现这三个分组的“自动更新”被勾上了
![IMG_20240929_135743](https://github.com/user-attachments/assets/cee6331b-9439-4710-8be6-56d4d68d28b4)

**Comment by 2dust** [comment]
一直是这三个的勾选有问题，还是随机？
另外你是否有另外的设备，帮忙操作下是否也会这样？

**Comment by wengzhenquan** [comment]
此前一直是那三个。
但刚刚我发现变成了只有后面两个，少了一个。
这期间我操作：我添加了一个hy2节点，并且更新了一个分组的订阅。

啊不对，我发现第一个开启状态的，现在变成会自动关闭了。。

编辑一个分组，啥也不改，返回到主页，重新进入分组管理页面，又变了。。

**Comment by rasa68** [comment]
I have this problem too!
I noticed that when the number of groups is large and we need to scroll down or up on the groups page, the update of groups is activated or deactivated.

**Comment by wengzhenquan** [comment]
> 我也有这个问题！ 我注意到，当群组数量很大并且我们需要在群组页面上向下或向上滚动时，群组的更新将被激活或停用。


调整顺序，滚动的问题，我都还没发现。听你说的，刚刚玩了一下，好像真是如此。

我的分组有10个，此前你没提到数量，我也没往这方面考虑，开发者可以参考一下数量问题

**Comment by rasa68** [comment]
> > 我也有这个问题！ 我注意到，当群组数量很大并且我们需要在群组页面上向下或向上滚动时，群组的更新将被激活或停用。
> 
> 调整顺序，滚动的问题，我都还没发现。听你说的，刚刚玩了一下，好像真是如此。
> 
> 我的分组有10个，此前你没提到数量，我也没往这方面考虑，开发者可以参考一下数量问题

I checked more carefully now!
I have 17 groups, when I activate or deactivate the update of one of the first 4 groups or the last 4 groups and scroll up or down on the groups page, the changes I made go back to before!
I emphasize that I have this problem only with the first 4 groups and the last 4 groups
