### ISSUE TITLE
1.9.3+更新订阅问题

### ISSUE THREAD

**Issue by clevercjl** [2dust/v2rayNG#3627]
预期行为
正常更新

实际行为
更新速度极慢，需要几分钟

复现方法
1.打开1.9.3以前的版本，几秒钟就能更新
2.更新到1.9.3+版本
3.保持原有配置不变，使用同一节点，更新同一订阅地址，更新速度极慢，需要几分钟

我试了几个不同的订阅链接，发现部分订阅链接有这个问题，而且不是偶发的
是不是1.9.3改了什么东西

**Comment by clevercjl** [comment]
我的日志差不多也是这样的

**Comment by APT-ZERO** [comment]
Your subscription is on Cloudflare and for sure your country limited access to Cloudflare ip ranges

**Comment by ghost** [comment]
已解决需要把ng加入代理。

**Comment by 2dust** [comment]
1.9.3版本确实有修改
把app自己排除在vpn代理之外了，主要是防止死循环；
现在更新订阅会先直连更新，失败后用http代理更新。

下一版改成先用代理更新再直连更新

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.5

**Comment by simplove** [comment]
> https://github.com/2dust/v2rayNG/releases/tag/1.9.5

还是用不了，订阅地址正常访问，没有被墙，手机浏览器都可以正常打开。
订阅内容是用v2rayn输出的base64，苹果小火箭都可以正常更新

而且我在服务器上面根本就没有看到来自手机端的请求。
用手机浏览器打开能看到请求。
这说明什么？

说明它压根就没有把请求发送到服务器
