### ISSUE TITLE
hy2 hysteria2是仅用于v2fly内核？

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3628]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
https://z.upk.icu/apk/go/client/banzou?token=已删除
订阅的节点能够在v2rayng使用
### 实际行为
描述实际发生了什么
测速提示 失败: io: read/write on closed pipe
### 复现方法
1.
2.
3.

### 日志信息
<details>
无 暂时没有工具。
通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
用开发测试，原版hy2客户端也无法连接，你问下是什么服务端

**Comment by ghost** [comment]
> 用开发测试，原版hy2客户端也无法连接，你问下是什么服务端

没有回复。测试了另一个jc的hy2，发现必须跳过验证测试链接有延迟反馈，但是无法上网网页提示not_resolved，开启虚拟dns能够上网。订阅的那个以上流程试了一边都不行，只有clash.mate singbox等内核支持了的正常即用。

09-30 06:11:13.207 I/GoLog   (26257): from DNS accepted https://1.1.1.1/dns-query [xray.system.1c44b48b-5f69-41c4-a714-1ca41097399c -> proxy]
09-30 06:11:13.208 I/GoLog   (26257): Using Prepared: 127.0.0.1
09-30 06:11:13.302 I/GoLog   (26257): [Info] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 4
09-30 06:11:13.302 I/GoLog   (26257): [Error] app/dns: failed to retrieve response for github.com. > Post "https://1.1.1.1/dns-query": io: read/write on closed pipe

**Comment by 2dust** [comment]
暂时哪个能用你用哪个吧
需要时间优化

**Comment by ghost** [comment]
> 暂时哪个能用你用哪个吧 需要时间优化

好的 感谢。
