### ISSUE TITLE
Add Toggle Icon for Menu Button to Indicate Open/Close State

### ISSUE THREAD

**Issue by Vinay-Khanagavi** [2dust/v2rayNG#3631]
**Description:**
The sidebar menu currently lacks a visual indicator to show whether it is open or closed. Adding a toggle icon to the menu button can improve user experience by providing immediate visual feedback. The feature will switch between a hamburger icon when the menu is closed and a close (X) icon when the menu is open.

We can use MUI (Material-UI) to implement this feature, utilizing the following component:

> import CloseIcon from '@mui/icons-material/Close';

**Screenshot:**
<img src="https://github.com/user-attachments/assets/f1fd482e-b0ab-4097-bd39-56de072ac4e7" width="300"/>

**Why is it Needed:**

- Enhanced Usability: Users can easily identify the state of the sidebar (open/closed).

- Visual Feedback: Reduces confusion by providing immediate visual feedback during interaction.

- Modern Design Practice: Aligns with UI/UX trends, improving consistency and intuitiveness.

**Feature Scope:**

- Add Icon Toggle: Change the icon between a hamburger and close (X) icon based on the sidebar state.

- Cross-Device Compatibility: Ensure seamless functionality across both desktop and mobile views.

- Optional Animation: Add smooth transitions when toggling between icons for better user experience.

**Comment by 2dust** [comment]
Welcome PR
Please PR
