### ISSUE TITLE
已经订阅 可测速 但是不可以链接。

### ISSUE THREAD

**Issue by ming187** [2dust/v2rayNG#3633]
首先：电脑端链接的一个节点。可以正常使用。说明节点没有问题
然后：手机端正常订阅 ，正常测试但是无法点击开始链接。点击开始链接无反应

**Comment by bush911** [comment]
我遇到类似的问题，都是清空app缓存甚存储空间来解决。重启也可以破。 我目前的问题是安卓上google的服务都访问不了，包括油管

**Comment by ming187** [comment]
尝试了 清空缓存 以及手机重启 都没有用。就是启动的三角点了 没有反应

**Comment by ming187** [comment]
麻烦作者看一下。这个是日志。
--------- beginning of main
09-30 14:16:20.633 I/com.v2ray.ang( 5834): Using CollectorTypeCMC GC.
09-30 14:16:20.635 E/com.v2ray.ang( 5834): Not starting debugger since process cannot load the jdwp agent.
09-30 14:16:20.658 W/com.v2ray.ang( 5834): Entry not found
09-30 14:16:20.659 W/com.v2ray.ang( 5834): Entry not found
09-30 14:16:20.659 W/com.v2ray.ang( 5834): Entry not found
09-30 14:16:20.780 E/com.v2ray.ang( 5834): Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
09-30 14:16:20.781 I/com.v2ray.ang( 5834): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
09-30 14:16:20.801 I/com.v2ray.ang( 5834): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
09-30 14:16:36.422 I/com.v2ray.ang( 5834): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
09-30 14:16:36.422 I/com.v2ray.ang( 5834): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
09-30 14:16:36.422 I/com.v2ray.ang( 5834): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
09-30 14:16:36.422 I/com.v2ray.ang( 5834): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
09-30 14:16:36.425 D/com.v2ray.ang( 5834): https://m2dy.zhunchuanpb.com/api/v1/client/subscribe?token=862b16933cc5bb9fa990ed1d2c24a226
09-30 14:16:42.757 W/com.v2ray.ang( 5834): Cleared Reference was only reachable from finalizer (only reported once)
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_per_app_proxy
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_local_dns_enabled
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_fake_dns_enabled
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_mux_enabled
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_fragment_enabled
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_auto_update_subscription
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_local_dns_port
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_vpn_dns
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_mux_concurrency
09-30 14:16:50.903 D/com.v2ray.ang( 5834): Observe settings changed: pref_mux_xudp_concurrency
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_fragment_length
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_fragment_interval
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_auto_update_interval
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_socks_port
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_http_port
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_remote_dns
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_domestic_dns
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_delay_test_url
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_speed_enabled
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_confirm_remove
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_start_scan_immediate
09-30 14:16:50.904 D/com.v2ray.ang( 5834): Observe settings changed: pref_prefer_ipv6
09-30 14:17:05.645 W/com.v2ray.ang( 5834): Checksum mismatch for dex base.apk!classes3.dex
09-30 14:17:05.646 W/com.v2ray.ang( 5834): Could not merge the profile. Clearing the profile data.
09-30 14:19:07.285 I/com.v2ray.ang(10322): Using CollectorTypeCMC GC.
09-30 14:19:07.287 E/com.v2ray.ang(10322): Not starting debugger since process cannot load the jdwp agent.
09-30 14:19:07.306 W/com.v2ray.ang(10322): Entry not found
09-30 14:19:07.307 W/com.v2ray.ang(10322): Entry not found
09-30 14:19:07.308 W/com.v2ray.ang(10322): Entry not found
09-30 14:19:07.421 E/com.v2ray.ang(10322): Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
09-30 14:22:16.083 W/com.v2ray.ang(10322): Cleared Reference was only reachable from finalizer (only reported once)
09-30 14:22:18.200 I/com.v2ray.ang(10322): Settings ViewModel is cleared
09-30 14:22:29.204 I/com.v2ray.ang(10322): Settings ViewModel is cleared

**Comment by 2dust** [comment]
无配置，无日志

**Comment by ming187** [comment]
https://github.com/user-attachments/assets/0a402b66-bc3d-45b9-87dc-630dadf1ea2c

可以看看视频

**Comment by paolo8341** [comment]
我与楼主问题一样，没法解决。现在用油管上UP主推荐的免费高速VPN。

**Comment by AsuradaGo** [comment]
> 我与楼主问题一样，没法解决。现在用油管上UP主推荐的免费高速VPN。

我的手机安装最新版的1.9.8遇到和你一样的问题，我的是浏览器可以打开Google，但是Google play商店无法下载应用。后来，回退到1.8.X或者是1.9.7都是可以了

**Comment by 2dust** [comment]
升级到最新版，然后重置下路由规则
