### ISSUE TITLE
安卓上Google 服务无法使用

### ISSUE THREAD

**Issue by bush911** [2dust/v2rayNG#3634]
**试过多个版本1.9.3, 1.9.4， 甚至1.8.5结果都一样**

### 预期行为
节点正常，预期可以Google搜索和访问YouTube   

### 实际行为

- 在手机上使用搜索时马上显示 no data connection  

- 火狐浏览器访问Google 或油管时显示：The site could be temporarily unavailable or too busy. Try again in a few moments. 
 
以为是路由规则的问题，试了全局代理还是依旧。维基百科等正常，包括现在访问这个页面也是用了代理的。

### 复现方法
1.配置好节点
2. 连接
3.使用Google 搜索，或访问油管网站

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of main
09-30 11:51:36.210 I/GoLog   (31895): from tcp:127.0.0.1:47314 accepted tcp:142.250.76.138:443 [socks -> proxy]
09-30 11:51:36.440 I/GoLog   (31895): Using Prepared: 144.34.186.116
09-30 11:52:31.698 I/GoLog   (31895): from tcp:127.0.0.1:46236 accepted tcp:1.1.1.1:853 [socks -> proxy]
09-30 11:52:31.928 I/GoLog   (31895): Using Prepared: 144.34.186.116
09-30 11:53:42.966 I/GoLog   (31895): from tcp:127.0.0.1:39276 accepted tcp:142.251.33.106:443 [socks -> proxy]
09-30 11:53:43.052 I/GoLog   (31895): from tcp:127.0.0.1:39286 accepted tcp:1.1.1.1:853 [socks -> proxy]
09-30 11:53:43.261 I/GoLog   (31895): Using Prepared: 144.34.186.116
09-30 11:53:43.283 I/GoLog   (31895): Using Prepared: 144.34.186.116
09-30 11:54:19.245 I/GoLog   (31895): from tcp:127.0.0.1:36508 accepted tcp:1.1.1.1:853 [socks -> proxy]
09-30 11:54:19.553 I/GoLog   (31895): Using Prepared: 144.34.186.116
09-30 11:54:19.849 E/GoLog   (31826): Could not open module param file '/sys/module/mali_kbase/parameters/large_page_conf'
09-30 11:54:19.850 E/GoLog   (31826): Could not open module param file '/sys/module/mali_kbase/parameters/large_page_conf'
09-30 11:54:19.876 E/com.v2ray.ang(31826): Invalid resource ID 0x00000000.
09-30 11:54:20.439 I/GoLog   (31895): from tcp:127.0.0.1:36522 accepted tcp:172.217.12.138:443 [socks -> proxy]
09-30 11:54:20.652 I/GoLog   (31895): Using Prepared: 144.34.186.116

```
</details>

### 环境信息
Pixel 6  安卓14
### 额外信息（可选）
用sagernet 正常

**Comment by bush911** [comment]
刚刚测试了新鲜的 1.9.6，问题依旧。V2RayNG目前比整体比Sagernet 靠谱，有时候同样节点后者不能成功代理，但V2RAYNG 就可以。
V2RAYNG 目前唯一困扰我的就是Google 服务用不了。
大佬麻烦看看吧  @2dust

**Comment by 2dust** [comment]
这个比较复杂，不一定是app问题，有时候和节点ip也有关系

**Comment by bush911** [comment]
> 这个比较复杂，不一定是app问题，有时候和节点ip也有关系

应该不是节点的问题，同一订阅几乎同一时间用sagernet访问Google 则正常。电脑端也正常。  
23年之前我用1.7.21也正常。后来一直没用V2RayNG，最近重新用回新版本确实整体好很多，就是Google 这个郁闷

**Comment by bush911** [comment]
确实很奇怪，现在用老的1.7.21也不行了。似乎所有版本都不行。
用仅代理模式 不用VPN模式暂时正常了。先用着看

**Comment by bush911** [comment]
看来是使用姿势问题。

今天下载最新v2flyng用了一下，回头再试V2RAYNG 就正常了。

**Comment by zlaxyao** [comment]
我现在也是这样子其他可以，就是谷歌play和youtuber不行，梯子坑定没问题用着来的，让后我电脑也是正常的

**Comment by zlaxyao** [comment]
我下载了v2flayng直接连不上梯子奇怪

**Comment by zlaxyao** [comment]
清楚数据也不行

**Comment by lixingyang-lxy** [comment]
可以访问谷歌地图 谷歌邮箱 message 就是谷歌play跟google.cn用不了  小米手机  v2rayng
