### ISSUE TITLE
关于 allowInsecure

### ISSUE THREAD

**Issue by RPRX** [2dust/v2rayNG#364]
最新版 v2rayNG（1.2.5）和 v2rayN（3.14）

0.请问v2rayNG中allowInsecure为空时是默认false吗

1.目前发现，v2rayNG扫码导入v2rayN配置时，allowInsecure均为false（即使v2rayN的allowInsecure为空或为true），不清楚是哪边的问题

2.“加密方式”仍有类似的问题，扫码导入均会变为auto

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)

**Comment by 2dust** [comment]
allowInsecure为空时是默认false
