### ISSUE TITLE
hysteria端口跳跃

### ISSUE THREAD

**Issue by swxk521** [2dust/v2rayNG#3645]
希望增加hysteria端口跳跃功能

**Comment by salomejou** [comment]
google play更新到最新版后，版本没有显示最新1.9.6，还是显示旧版本1.9.5

**Comment by 2dust** [comment]
google play还在审核中

**Comment by 2dust** [comment]
端口跳跃请给一个客户端的例子

**Comment by swxk521** [comment]
> 端口跳跃请给一个客户端的例子

![image](https://github.com/user-attachments/assets/b05b498b-37ac-40c0-b74b-9a0e9ae76223)
这是官方的例子

**Comment by salomejou** [comment]
> google play还在审核中

一天了审核通过了吗，还是不能更新

**Comment by salomejou** [comment]
> google play还在审核中

是不是版本号弄错了，没有更新，虽然app已经更新到1.9.6，但版本号还是显示1.9.5

**Comment by yzyz5840** [comment]
> 端口跳跃请给一个客户端的例子

![Screenshot_20241006_221450.jpg](https://github.com/user-attachments/assets/21efae3d-7757-47b5-ac80-26f905fe9b45)

**Comment by humbass** [comment]
@2dust 能否支持 hy2 的端口跳跃了？

**Comment by denniszzg** [comment]
hy2在v2rayN上的配置参考下面例子，除了端口跳跃，还有pinSHA256

server: 11.11.11.11:30000-30100
auth: HoplB11skPShioUypJaxEL

bandwidth:
  up: 25 mbps
  down: 100 mbps
  
tls:
  sni: bing.com
  insecure: true
  pinSHA256: CB:03:FC:10:2B:C7:AB:30:AE:AE:C2:98:5A:5A:84:70:48:EF:E8:33:71:FF:8B:89:71:E1:FE:A5:0E:58:A7:5D

socks5:
  listen: 127.0.0.1:1080
http:
  listen: 127.0.0.1:8080

**Comment by yw-2020** [comment]
大佬，现在v2rayNG支持端口跳跃了吗

**Comment by iopq** [comment]
> > 端口跳跃请给一个客户端的例子

Note that h-ui will generate a link like server:443/?mport=20000-50000 because that's a valid URL, but server:20000-50000 is not

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.10
