### ISSUE TITLE
Routing Setting Improvement (Suggestion)

### ISSUE THREAD

**Issue by Phoenix-999** [2dust/v2rayNG#3646]
Hi @2dust,

Thanks a lot for improving the Routing Settings section! I really appreciate the changes.

I was wondering if it’s possible to add support for `regexp` along with the current options for domains and IPs. I think this would make it much easier to categorize direct and proxy connections.

For example: `regexp:.*\\.cn$`

Also, what do you think about adding `keywords` to manage routing in a more advanced way? It could be a nice addition to the current setup with domains and IPs.

Thanks again for your time and support.

**Comment by 2dust** [comment]
Regular expressions have poor performance and are prone to errors. They are not recommended for use on mobile devices.

**Comment by Phoenix-999** [comment]
> Regular expressions have poor performance and are prone to errors. They are not recommended for use on mobile devices.

Thank you for the clarification 🙏🏾
