### ISSUE TITLE
Per-app proxy not showing apps (as it used to)

### ISSUE THREAD

**Issue by colibris79** [2dust/v2rayNG#3648]
Hi
I've been using for a long time V2rayNG and V2flyNG but I've just changed to an Android 13 Rom (Hyperos 1.0.6) and I cannot configure Per-app proxy anymore. The list of apps is empty, I can only see V2rayNG/V2flyNG
The app is working and it connects fine but I need selected apps to connect directly
I am using last versions from Play store: V2rayNG 1.8.39 and V2flyNG 1.8.25 (both have the same problem)
Is it expected to work like this with Android 13?
Thanks

![Screenshot_2024-10-03-18-23-55-187_com v2ray v2fly](https://github.com/user-attachments/assets/d079ae04-5477-4754-a9f2-9b4e5cc44fff)

**Comment by bush911** [comment]
It seems that V2RayNG lacks the relevant permissions to get installed Apps list

**Comment by colibris79** [comment]
That's it. Thanks @bush911

**Comment by fdmsh** [comment]
> It seems that V2RayNG lacks the relevant permissions to get installed Apps list 

all permissions given, I still don't see some apps
