### ISSUE TITLE
服务端所在局域网IP无法被代理，进core前已被直连

### ISSUE THREAD

**Issue by sjwlm** [2dust/v2rayNG#3653]
本人因考虑安全问题，通过xray支持的某代理协议在外出时访问软路由，进而访问局域网中的nas设备。客户端自1.9.1更新至1.9.6后，服务端所在局域网IP无法走代理，经研究发现进core前已被直连。

### 预期行为
VPN模式下，服务端所在局域网IP流量可以进core，进core后由xray路由规则分流

### 实际行为
局域网IP流量进core前已被直连。

### 复现方法
1.路由设置--导入预设规则集--全局
2.编辑“绕过局域网IP”、“绕过局域网域名”两规则，将outboundtag设为“proxy”
3.手动添加ip为“192.168.0.0/16”、outboundtag为“proxy”的路由规则并置顶
4.在外网环境（如移动蜂窝数据）下连接代理，发现无法访问服务端所在局域网的内网ip
5.在和服务端共同内网环境下连接代理，发现可以访问服务端所在局域网的内网ip
由于之前已设置全局代理，故在此可初步判断局域网IP已走直连未代理

### 日志信息

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志

根据日志显示，启动时未见异常，启动VPN后，尝试连接局域网IP时，xray core未显示任何有关局域网IP（192.168.x.x）的流量，故推断局域网流量未进core

### 环境信息
ColorOS 11.2, Android 11
### 额外信息（可选）
已排除服务端问题，旧版v2rayng客户端及nekobox均可代理局域网ip

**Comment by sjwlm** [comment]
自定义配置文件并更改xray loglevel后显示如下日志：10-05 19:32:21.411  6349  8422 I GoLog   : [Info] [712345843] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled

**Comment by IDSSC** [comment]
我也遇到这个同样的问题

**Comment by CC342** [comment]
我把“绕过局域网IP”改为proxy，geoip：private改为192.168.0.0/16,就成功了。1.9.6版本

**Comment by 2dust** [comment]
应该是在vpnservice中就已经被绕过了
所以有这样需求的，把规则中的绕过局域网IP和域名都删除掉，然后增加自己的局域网ip进去

**Comment by 2dust** [comment]
应该修复了，
