### ISSUE TITLE
golog: EscortRun cmd.start err

### ISSUE THREAD

**Issue by niezhuofu** [2dust/v2rayNG#366]
我在学习您的项目。在我学习测试的应用中。进行连接时，VpnService日志报告。EscortRun cmd.start err fork/exec /data/user/0/"packagename"/tun2sock : permission denied。
VpnService显示连接成功，无法进行网络访问。

### 日志信息
EscortRun cmd.start err fork/exec /data/user/0/"packagename"/tun2sock : permission denied

java.io.IOException:No such file or directory

### 环境信息
huawei p20 pro
huawei navo 5 pro

**Comment by PingerAI** [comment]
请问这个问题已经得到解决了吗？
