### ISSUE TITLE
建议信息：希望可以添加“链式代理”功能

### ISSUE THREAD

**Issue by amydesun** [2dust/v2rayNG#3667]
v2rayng软件已经开发的很好了，只是使用链式代理一直需要自定义配置信息，或者使用SagerNet才可以，如果可以像SagerNet一样直接使用住宅ip套节点的链式代理玩法就好了，谢谢！

**Comment by 2dust** [comment]
目前此app已有个简单功能的前置和落地代理功能，完整的链式功能过于复杂，并不在计划内，并且已有其他app支持了，如果有此要求可用使用它们

**Comment by piaoliuhe** [comment]
订阅分组设置中的前置代理别名和后置代理别名分别怎么用呢，我很想知道。链式代理现在用的越来越多了，这个功能非常使用，我也很希望能够开发这样的功能，用于静态住宅IP的代理，或者只能换其他app了。

**Comment by piaoliuhe** [comment]
> https://github.com/2dust/v2rayN/wiki/Description-of-proxy-chain

我是按照这样设置的，前置代理名称填上我VPN常用节点的名称，落地代理是sock5代理的名称，确定后连接也没反应啊。能不能出个图形化设置方便点的。

**Comment by piaoliuhe** [comment]
> 你填好后，可以点击导出完整配置，看看产生的配置文件。可以去掉敏感信息发出来

你好，之前我测试，不知道什么原因没有成功，现在按照文档的测试，链式代理连接成功，非常感谢！
