### ISSUE TITLE
某个版本开始从Actions下载最新的app 点击软件的开始连接按钮没办法启动VPN

### ISSUE THREAD

**Issue by kafeixiang** [2dust/v2rayNG#3673]
--------- beginning of main
10-09 08:20:43.207 I/com.v2ray.ang( 6269): This is non sticky GC, maxfree is 33554432 minfree is 8388608
10-09 08:20:43.207 I/com.v2ray.ang( 6269): CollectorTransition concurrent copying GC freed 187479(9294KB) AllocSpace objects, 18(488KB) LOS objects, 75% free, 8401KB/32MB, paused 154us,12us total 117.033ms
10-09 08:20:43.207 W/com.v2ray.ang( 6269): Reducing the number of considered missed Gc histogram windows from 210 to 100
10-09 08:20:44.496 I/GoLog   (24165): Preparing Domain: 127.0.0.1:10908
10-09 08:20:44.497 I/GoLog   (24165): Prepare Result:
10-09 08:20:44.497 I/GoLog   (24165):  Domain: 127.0.0.1
10-09 08:20:44.497 I/GoLog   (24165):  Port: 10908
10-09 08:20:44.497 I/GoLog   (24165):  IPs: [127.0.0.1]
10-09 08:20:44.497 I/GoLog   (24165): loading core config
10-09 08:20:44.593 I/GoLog   (24165): new core
10-09 08:20:44.635 I/GoLog   (24165): start core
10-09 08:20:44.636 I/GoLog   (24165): [Warning] core: Xray 24.9.30 started
10-09 08:20:44.655 D/com.v2ray.ang(24165): [/data/app/~~ZMlZ5HbQ3186Jp1xe4DRIA==/com.v2ray.ang-k3XCe8K8nLUkdH4HSEnNKw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-09 08:20:44.658 D/com.v2ray.ang(24165): Process[pid=24214, hasExited=false]
10-09 08:20:44.658 D/com.v2ray.ang(24165): libtun2socks.so check
10-09 08:20:44.658 D/com.v2ray.ang(24165): /data/user/0/com.v2ray.ang/files/sock_path
10-09 08:20:44.662 E/GoLog   (24165): runtime: newstack at runtime.printlock+0x78 sp=0x4000f0fa10 stack=[0x4000ef0000, 0x4000f10000]
10-09 08:20:44.662 E/GoLog   (24165): 	morebuf={pc:0x70c00e49a0 sp:0x4000f0fa10 lr:0x0}
10-09 08:20:44.662 E/GoLog   (24165): 	sched={pc:0x70c011c0c8 sp:0x4000f0fa10 lr:0x70c00e49a0 ctxt:0x0}
10-09 08:20:44.662 E/GoLog   (24165): runtime.callbackUpdateSystemStack(0x400006e008, 0x7fc1549dd0, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:241 +0x90 fp=0x4000f0fa70 sp=0x4000f0fa10 pc=0x70c00e49a0
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallbackg(0x70c0b78140, 0x7fc1549ec8, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:306 +0x68 fp=0x4000f0faf0 sp=0x4000f0fa70 pc=0x70c00e4b68
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallbackg(0x70c0b78140, 0x7fc1549ec8, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	<autogenerated>:1 +0x1c fp=0x4000f0fb20 sp=0x4000f0faf0 pc=0x70c01593dc
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallback(0x4000f0fb98, 0x70c0b76184, 0x70c0b79808)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1130 +0xb0 fp=0x4000f0fb50 sp=0x4000f0fb20 pc=0x70c0157250
10-09 08:20:44.662 E/GoLog   (24165): runtime.systemstack_switch()
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:200 +0x8 fp=0x4000f0fb60 sp=0x4000f0fb50 pc=0x70c0154e18
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocall(0x70c0b79808, 0x4000f0fbd8)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:175 +0x70 fp=0x4000f0fba0 sp=0x4000f0fb60 pc=0x70c00e48b0
10-09 08:20:44.662 E/GoLog   (24165): main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
10-09 08:20:44.662 E/GoLog   (24165): 	_cgo_gotypes.go:167 +0x34 fp=0x4000f0fbd0 sp=0x4000f0fba0 pc=0x70c0b76184
10-09 08:20:44.662 E/GoLog   (24165): main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x4000010018, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
10-09 08:20:44.662 E/GoLog   (24165): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x4000f0fc30 sp=0x4000f0fbd0 pc=0x70c0b77738
10-09 08:20:44.662 E/GoLog   (24165): main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x4000010018, {0x0?, 0x2?})
10-09 08:20:44.662 E/GoLog   (24165): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:302 +0x44 fp=0x4000f0fc70 sp=0x4000f0fc30 pc=0x70c0b77684
10-09 08:20:44.662 E/GoLog   (24165): github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).pointloop(0x40000b2000)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/work/v2rayNG/v2rayNG/build/AndroidLibXrayLite/libv2ray_main.go:164 +0x450 fp=0x4000f0fd60 sp=0x4000f0fc70 pc=0x70c0b70950
10-09 08:20:44.662 E/GoLog   (24165): github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).RunLoop(0x40000b2000, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/work/v2rayNG/v2rayNG/build/AndroidLibXrayLite/libv2ray_main.go:101 +0x210 fp=0x4000f0fde0 sp=0x4000f0fd60 pc=0x70c0b6fe60
10-09 08:20:44.662 E/GoLog   (24165): main.proxylibv2ray_V2RayPoint_RunLoop(0xffffff01?, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:196 +0x4c fp=0x4000f0fe10 sp=0x4000f0fde0 pc=0x70c0b76e8c
10-09 08:20:44.662 E/GoLog   (24165): _cgoexp_6f524d1d87fa_proxylibv2ray_V2RayPoint_RunLoop(0x7fc154baa4)
10-09 08:20:44.662 E/GoLog   (24165): 	_cgo_gotypes.go:383 +0x2c fp=0x4000f0fe30 sp=0x4000f0fe10 pc=0x70c0b7853c
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallbackg1(0x70c0b78510, 0x7fc154baa4, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:420 +0x228 fp=0x4000f0ff00 sp=0x4000f0fe30 pc=0x70c00e4ee8
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallbackg(0x70c0b78510, 0x7fc154baa4, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:339 +0x10c fp=0x4000f0ff80 sp=0x4000f0ff00 pc=0x70c00e4c0c
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallbackg(0x70c0b78510, 0x7fc154baa4, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	<autogenerated>:1 +0x1c fp=0x4000f0ffb0 sp=0x4000f0ff80 pc=0x70c01593dc
10-09 08:20:44.662 E/GoLog   (24165): runtime.cgocallback(0x0, 0x0, 0x0)
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1130 +0xb0 fp=0x4000f0ffe0 sp=0x4000f0ffb0 pc=0x70c0157250
10-09 08:20:44.662 E/GoLog   (24165): runtime.goexit({})
10-09 08:20:44.662 E/GoLog   (24165): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x4000f0ffe0 sp=0x4000f0ffe0 pc=0x70c0157344
10-09 08:20:44.662 E/GoLog   (24165): fatal error: runtime: stack split at bad time
10-09 08:20:44.665 I/tun2socks(24214): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-09 08:20:47.302 I/GoLog   (24409): Preparing Domain: 127.0.0.1:10908
10-09 08:20:47.302 I/GoLog   (24409): loading core config
10-09 08:20:47.302 I/GoLog   (24409): Prepare Result:
10-09 08:20:47.302 I/GoLog   (24409):  Domain: 127.0.0.1
10-09 08:20:47.302 I/GoLog   (24409):  Port: 10908
10-09 08:20:47.302 I/GoLog   (24409):  IPs: [127.0.0.1]
10-09 08:20:47.393 I/GoLog   (24409): new core
10-09 08:20:47.440 I/GoLog   (24409): start core
10-09 08:20:47.442 I/GoLog   (24409): [Warning] core: Xray 24.9.30 started
10-09 08:20:47.473 D/com.v2ray.ang(24409): [/data/app/~~ZMlZ5HbQ3186Jp1xe4DRIA==/com.v2ray.ang-k3XCe8K8nLUkdH4HSEnNKw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-09 08:20:47.475 D/com.v2ray.ang(24409): Process[pid=24458, hasExited=false]
10-09 08:20:47.475 D/com.v2ray.ang(24409): /data/user/0/com.v2ray.ang/files/sock_path
10-09 08:20:47.476 D/com.v2ray.ang(24409): libtun2socks.so check
10-09 08:20:47.479 I/tun2socks(24458): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-09 08:20:51.735 I/GoLog   (24619): Preparing Domain: 127.0.0.1:10908
10-09 08:20:51.737 I/GoLog   (24619): loading core config
10-09 08:20:51.737 I/GoLog   (24619): Prepare Result:
10-09 08:20:51.737 I/GoLog   (24619):  Domain: 127.0.0.1
10-09 08:20:51.737 I/GoLog   (24619):  Port: 10908
10-09 08:20:51.737 I/GoLog   (24619):  IPs: [127.0.0.1]
10-09 08:20:51.898 I/GoLog   (24619): new core
10-09 08:20:51.978 I/GoLog   (24619): start core
10-09 08:20:51.981 I/GoLog   (24619): [Warning] core: Xray 24.9.30 started
10-09 08:20:52.019 D/com.v2ray.ang(24619): [/data/app/~~ZMlZ5HbQ3186Jp1xe4DRIA==/com.v2ray.ang-k3XCe8K8nLUkdH4HSEnNKw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-09 08:20:52.023 D/com.v2ray.ang(24619): Process[pid=24662, hasExited=false]
10-09 08:20:52.023 D/com.v2ray.ang(24619): /data/user/0/com.v2ray.ang/files/sock_path
10-09 08:20:52.023 D/com.v2ray.ang(24619): libtun2socks.so check
10-09 08:20:52.026 E/GoLog   (24619): runtime: newstack at runtime.printlock+0x78 sp=0x40011a9a10 stack=[0x400119a000, 0x40011aa000]
10-09 08:20:52.026 E/GoLog   (24619): 	morebuf={pc:0x70bf0ee9a0 sp:0x40011a9a10 lr:0x0}
10-09 08:20:52.026 E/GoLog   (24619): 	sched={pc:0x70bf1260c8 sp:0x40011a9a10 lr:0x70bf0ee9a0 ctxt:0x0}
10-09 08:20:52.026 E/GoLog   (24619): runtime.callbackUpdateSystemStack(0x400006e008, 0x7fc1549dd0, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:241 +0x90 fp=0x40011a9a70 sp=0x40011a9a10 pc=0x70bf0ee9a0
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallbackg(0x70bfb82140, 0x7fc1549ec8, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:306 +0x68 fp=0x40011a9af0 sp=0x40011a9a70 pc=0x70bf0eeb68
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallbackg(0x70bfb82140, 0x7fc1549ec8, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	<autogenerated>:1 +0x1c fp=0x40011a9b20 sp=0x40011a9af0 pc=0x70bf1633dc
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallback(0x40011a9b98, 0x70bfb80184, 0x70bfb83808)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1130 +0xb0 fp=0x40011a9b50 sp=0x40011a9b20 pc=0x70bf161250
10-09 08:20:52.026 E/GoLog   (24619): runtime.systemstack_switch()
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:200 +0x8 fp=0x40011a9b60 sp=0x40011a9b50 pc=0x70bf15ee18
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocall(0x70bfb83808, 0x40011a9bd8)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:175 +0x70 fp=0x40011a9ba0 sp=0x40011a9b60 pc=0x70bf0ee8b0
10-09 08:20:52.026 E/GoLog   (24619): main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
10-09 08:20:52.026 E/GoLog   (24619): 	_cgo_gotypes.go:167 +0x34 fp=0x40011a9bd0 sp=0x40011a9ba0 pc=0x70bfb80184
10-09 08:20:52.026 E/GoLog   (24619): main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x400029e000, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
10-09 08:20:52.026 E/GoLog   (24619): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x40011a9c30 sp=0x40011a9bd0 pc=0x70bfb81738
10-09 08:20:52.026 E/GoLog   (24619): main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x400029e000, {0x0?, 0x2?})
10-09 08:20:52.026 E/GoLog   (24619): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:302 +0x44 fp=0x40011a9c70 sp=0x40011a9c30 pc=0x70bfb81684
10-09 08:20:52.026 E/GoLog   (24619): github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).pointloop(0x40002a4000)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/work/v2rayNG/v2rayNG/build/AndroidLibXrayLite/libv2ray_main.go:164 +0x450 fp=0x40011a9d60 sp=0x40011a9c70 pc=0x70bfb7a950
10-09 08:20:52.026 E/GoLog   (24619): github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).RunLoop(0x40002a4000, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/work/v2rayNG/v2rayNG/build/AndroidLibXrayLite/libv2ray_main.go:101 +0x210 fp=0x40011a9de0 sp=0x40011a9d60 pc=0x70bfb79e60
10-09 08:20:52.026 E/GoLog   (24619): main.proxylibv2ray_V2RayPoint_RunLoop(0xffffff01?, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:196 +0x4c fp=0x40011a9e10 sp=0x40011a9de0 pc=0x70bfb80e8c
10-09 08:20:52.026 E/GoLog   (24619): _cgoexp_6f524d1d87fa_proxylibv2ray_V2RayPoint_RunLoop(0x7fc154baa4)
10-09 08:20:52.026 E/GoLog   (24619): 	_cgo_gotypes.go:383 +0x2c fp=0x40011a9e30 sp=0x40011a9e10 pc=0x70bfb8253c
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallbackg1(0x70bfb82510, 0x7fc154baa4, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:420 +0x228 fp=0x40011a9f00 sp=0x40011a9e30 pc=0x70bf0eeee8
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallbackg(0x70bfb82510, 0x7fc154baa4, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:339 +0x10c fp=0x40011a9f80 sp=0x40011a9f00 pc=0x70bf0eec0c
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallbackg(0x70bfb82510, 0x7fc154baa4, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	<autogenerated>:1 +0x1c fp=0x40011a9fb0 sp=0x40011a9f80 pc=0x70bf1633dc
10-09 08:20:52.026 E/GoLog   (24619): runtime.cgocallback(0x0, 0x0, 0x0)
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1130 +0xb0 fp=0x40011a9fe0 sp=0x40011a9fb0 pc=0x70bf161250
10-09 08:20:52.026 E/GoLog   (24619): runtime.goexit({})
10-09 08:20:52.026 E/GoLog   (24619): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40011a9fe0 sp=0x40011a9fe0 pc=0x70bf161344
10-09 08:20:52.026 E/GoLog   (24619): fatal error: runtime: stack split at bad time
10-09 08:20:52.028 I/tun2socks(24662): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-09 08:22:02.293 I/com.v2ray.ang(24969): Late-enabling -Xcheck:jni
10-09 08:22:02.304 I/com.v2ray.ang(24969): Using CollectorTypeCC GC.
10-09 08:22:02.466 W/com.v2ray.ang(24969): type=1400 audit(0.0:411517): avc:  denied  { read } for  name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=492 scontext=u:r:untrusted_app:s0:c78,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
10-09 08:22:02.491 W/com.v2ray.ang(24969): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
10-09 08:22:02.800 D/com.v2ray.ang(24969): MiuiProcessManagerServiceStub setSchedFifo
10-09 08:22:04.465 I/GoLog   (25040): loading core config
10-09 08:22:04.465 I/GoLog   (25040): Preparing Domain: 127.0.0.1:10908
10-09 08:22:04.465 I/GoLog   (25040): Prepare Result:
10-09 08:22:04.465 I/GoLog   (25040):  Domain: 127.0.0.1
10-09 08:22:04.465 I/GoLog   (25040):  Port: 10908
10-09 08:22:04.465 I/GoLog   (25040):  IPs: [127.0.0.1]
10-09 08:22:04.573 I/GoLog   (25040): new core
10-09 08:22:04.620 I/GoLog   (25040): start core
10-09 08:22:04.622 I/GoLog   (25040): [Warning] core: Xray 24.9.30 started
10-09 08:22:04.642 D/com.v2ray.ang(25040): [/data/app/~~ZMlZ5HbQ3186Jp1xe4DRIA==/com.v2ray.ang-k3XCe8K8nLUkdH4HSEnNKw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-09 08:22:04.644 D/com.v2ray.ang(25040): Process[pid=25079, hasExited=false]
10-09 08:22:04.644 D/com.v2ray.ang(25040): libtun2socks.so check
10-09 08:22:04.644 D/com.v2ray.ang(25040): /data/user/0/com.v2ray.ang/files/sock_path
10-09 08:22:04.648 E/GoLog   (25040): runtime: newstack at runtime.printlock+0x78 sp=0x4000e61a10 stack=[0x4000e42000, 0x4000e62000]
10-09 08:22:04.648 E/GoLog   (25040): 	morebuf={pc:0x70b94e99a0 sp:0x4000e61a10 lr:0x0}
10-09 08:22:04.648 E/GoLog   (25040): 	sched={pc:0x70b95210c8 sp:0x4000e61a10 lr:0x70b94e99a0 ctxt:0x0}
10-09 08:22:04.648 E/GoLog   (25040): runtime.callbackUpdateSystemStack(0x400006e008, 0x7fc1549dd0, 0x0)
10-09 08:22:04.648 E/GoLog   (25040): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:241 +0x90 fp=0x4000e61a70 sp=0x4000e61a10 pc=0x70b94e99a0
10-09 08:22:04.648 E/GoLog   (25040): runtime.cgocallbackg(0x70b9f7d140, 0x7fc1549ec8, 0x0)
10-09 08:22:04.648 E/GoLog   (25040): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:306 +0x68 fp=0x4000e61af0 sp=0x4000e61a70 pc=0x70b94e9b68
10-09 08:22:04.648 E/GoLog   (25040): runtime.cgocallbackg(0x70b9f7d140, 0x7fc1549ec8, 0x0)
10-09 08:22:04.648 E/GoLog   (25040): 	<autogenerated>:1 +0x1c fp=0x4000e61b20 sp=0x4000e61af0 pc=0x70b955e3dc
10-09 08:22:04.648 E/GoLog   (25040): runtime.cgocallback(0x4000e61b98, 0x70b9f7b184, 0x70b9f7e808)
10-09 08:22:04.648 E/GoLog   (25040): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:1130 +0xb0 fp=0x4000e61b50 sp=0x4000e61b20 pc=0x70b955c250
10-09 08:22:04.648 E/GoLog   (25040): runtime.systemstack_switch()
10-09 08:22:04.648 E/GoLog   (25040): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/asm_arm64.s:200 +0x8 fp=0x4000e61b60 sp=0x4000e61b50 pc=0x70b9559e18
10-09 08:22:04.648 E/GoLog   (25040): runtime.cgocall(0x70b9f7e808, 0x4000e61bd8)
10-09 08:22:04.648 I/tun2socks(25079): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-09 08:22:04.648 E/GoLog   (25040): 	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.8.linux-amd64/src/runtime/cgocall.go:175 +0x70 fp=0x4000e61ba0 sp=0x4000e61b60 pc=0x70b94e98b0
10-09 08:22:04.648 E/GoLog   (25040): main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
10-09 08:22:04.648 E/GoLog   (25040): 	_cgo_gotypes.go:167 +0x34 fp=0x4000e61bd0 sp=0x4000e61ba0 pc=0x70b9f7b184
10-09 08:22:04.648 E/GoLog   (25040): main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x400012e000, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
10-09 08:22:04.648 E/GoLog   (25040): 	/tmp/gomobile-work-3389618097/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x4000e61c30 sp=0x4000e61bd0 pc=0x70b9f7c738
10-09 08:22:04.648 E/GoLog   (25040): main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x400012e000, {0x0?, 0x2?})

**Comment by 2dust** [comment]
actions中无法保证能用，很多pr不一定经过测试
