### ISSUE TITLE
1.9.6 no support for quic + vmess

### ISSUE THREAD

**Issue by oopschen** [2dust/v2rayNG#3678]
v2rayng 使用quic + vmess 组合， v2rayng 报错，无法找到quic协议

### 预期行为
正常连接

### 实际行为
启动错误

### 复现方法
1. 配置quic内容
2.启动服务

### 日志信息

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
10-09 22:49:23.733 25402 25402 I GoLog   : infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: quic
10-09 22:49:23.733 25402 25402 D com.v2ray.ang: go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: quic

```
</details>

### 环境信息
服务端 debia64 64位
 
v2rayng 1.9.6
coloros14

**Comment by donnyxray** [comment]
xray-core removed QUIC support. https://github.com/XTLS/Xray-core/pull/3754

**Comment by 2dust** [comment]
https://play.google.com/store/apps/details?id=com.v2ray.v2fly
