### ISSUE TITLE
Can't connect because TLS handshake timeout

### ISSUE THREAD

**Issue by Muayaoi** [2dust/v2rayNG#3679]
![Screenshot_20241010_000039_v2rayNG](https://github.com/user-attachments/assets/d445fa0d-849c-4b9c-a5bd-3a6eef026b68)

--------- beginning of main
10-10 02:30:14.664 I/com.v2ray.ang(13738): Using CollectorTypeCMC GC.
10-10 02:30:14.668 E/com.v2ray.ang(13738): Not starting debugger since process cannot load the jdwp agent.
10-10 02:30:14.689 W/com.v2ray.ang(13738): Entry not found
10-10 02:30:14.690 W/com.v2ray.ang(13738): Entry not found
10-10 02:30:14.691 W/com.v2ray.ang(13738): Entry not found
10-10 02:30:14.691 W/com.v2ray.ang(13738): Entry not found
10-10 02:30:16.701 I/com.v2ray.ang(14614): Using CollectorTypeCMC GC.
10-10 02:30:16.703 E/com.v2ray.ang(14614): Not starting debugger since process cannot load the jdwp agent.
10-10 02:30:16.728 W/com.v2ray.ang(14614): Entry not found
10-10 02:30:16.729 W/com.v2ray.ang(14614): Entry not found
10-10 02:30:16.730 W/com.v2ray.ang(14614): Entry not found
10-10 02:30:16.731 W/com.v2ray.ang(14614): Entry not found
10-10 02:30:17.017 E/com.v2ray.ang(14614): Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
10-10 02:30:34.720 I/com.v2ray.ang(16725): Using CollectorTypeCMC GC.
10-10 02:30:34.723 E/com.v2ray.ang(16725): Not starting debugger since process cannot load the jdwp agent.
10-10 02:30:34.741 W/com.v2ray.ang(16725): Entry not found
10-10 02:30:34.741 W/com.v2ray.ang(16725): Entry not found
10-10 02:30:34.742 W/com.v2ray.ang(16725): Entry not found
10-10 02:30:34.743 W/com.v2ray.ang(16725): Entry not found
10-10 02:30:34.891 E/com.v2ray.ang(16725): Unable to open libpenguin.so: dlopen failed: library "libpenguin.so" not found.
10-10 02:30:34.909 I/com.v2ray.ang(16725): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
10-10 02:30:34.925 I/com.v2ray.ang(16725): Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
10-10 02:30:38.281 D/com.v2ray.ang(16725): Observe settings changed: pref_per_app_proxy
10-10 02:30:38.281 D/com.v2ray.ang(16725): Observe settings changed: pref_local_dns_enabled
10-10 02:30:38.281 D/com.v2ray.ang(16725): Observe settings changed: pref_fake_dns_enabled
10-10 02:30:38.281 D/com.v2ray.ang(16725): Observe settings changed: pref_mux_enabled
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_fragment_enabled
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_auto_update_subscription
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_local_dns_port
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_vpn_dns
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_mux_concurrency
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_mux_xudp_concurrency
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_fragment_length
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_fragment_interval
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_auto_update_interval
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_socks_port
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_http_port
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_remote_dns
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_domestic_dns
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_delay_test_url
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_is_booted
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_speed_enabled
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_confirm_remove
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_start_scan_immediate
10-10 02:30:38.282 D/com.v2ray.ang(16725): Observe settings changed: pref_prefer_ipv6
10-10 02:30:58.870 I/com.v2ray.ang(16725): Settings ViewModel is cleared
10-10 02:31:00.703 I/com.v2ray.ang(16725): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.703 I/com.v2ray.ang(16725): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.703 I/com.v2ray.ang(16725): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.703 I/com.v2ray.ang(16725): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.715 I/com.v2ray.ang(16725): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.715 I/com.v2ray.ang(16725): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.715 I/com.v2ray.ang(16725): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:00.715 I/com.v2ray.ang(16725): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
10-10 02:31:04.025 I/GoLog   (17325): loading core config
10-10 02:31:04.029 I/GoLog   (17325): Preparing Domain: cu6.ainivp.com:33402
10-10 02:31:04.058 I/GoLog   (17325): Prepare Result:
10-10 02:31:04.058 I/GoLog   (17325):  Domain: cu6.ainivp.com
10-10 02:31:04.058 I/GoLog   (17325):  Port: 33402
10-10 02:31:04.058 I/GoLog   (17325):  IPs: [120.82.70.82]
10-10 02:31:04.105 I/GoLog   (17325): new core
10-10 02:31:04.152 I/GoLog   (17325): start core
10-10 02:31:04.157 I/GoLog   (17325): [Warning] core: Xray 24.9.30 started
10-10 02:31:04.184 D/com.v2ray.ang(17325): [/data/app/~~sObwmDB6U4xDZmMWaX-MbA==/com.v2ray.ang-S0jgM3oTTk6kXRvGbn-1Nw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-10 02:31:04.189 D/com.v2ray.ang(17325): Process[pid=17664, hasExited=false]
10-10 02:31:04.189 D/com.v2ray.ang(17325): /data/user/0/com.v2ray.ang/files/sock_path
10-10 02:31:04.191 D/com.v2ray.ang(17325): libtun2socks.so check
10-10 02:31:04.201 I/tun2socks(17664): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-10 02:31:04.205 D/com.v2ray.ang(17325): runPlugin
10-10 02:31:04.242 D/com.v2ray.ang(17325): sendFd tries: 0
10-10 02:31:04.243 I/tun2socks(17664): NOTICE(tun2socks): entering event loop
10-10 02:31:04.282 I/GoLog   (17325): from udp:127.0.0.1:38061 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.287 I/GoLog   (17325): from udp:127.0.0.1:45615 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.287 I/GoLog   (17325): from udp:127.0.0.1:57008 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.287 I/GoLog   (17325): from udp:127.0.0.1:37126 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.296 I/GoLog   (17325): from udp:127.0.0.1:36502 accepted udp:81.69.116.102:443 [socks -> block]
10-10 02:31:04.300 I/GoLog   (17325): from udp:127.0.0.1:39296 accepted udp:119.45.2.92:443 [socks -> block]
10-10 02:31:04.302 I/GoLog   (17325): from udp:127.0.0.1:49383 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.312 I/GoLog   (17325): from tcp:127.0.0.1:57886 accepted tcp:180.130.113.210:443 [socks -> direct]
10-10 02:31:04.312 I/GoLog   (17325): from tcp:127.0.0.1:57888 accepted tcp:81.69.116.102:443 [socks -> direct]
10-10 02:31:04.313 I/GoLog   (17325): from tcp:127.0.0.1:57890 accepted tcp:119.45.2.92:443 [socks -> direct]
10-10 02:31:04.315 I/GoLog   (17325): from DNS accepted udp:223.5.5.5:53 [xray.system.de2a925f-4cc1-4e47-924d-938bdd324ca9 -> direct]
10-10 02:31:04.315 I/GoLog   (17325): Not Using Prepared: udp,223.5.5.5:53
10-10 02:31:04.333 I/GoLog   (17325): from udp:127.0.0.1:53177 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.336 I/GoLog   (17325): from udp:127.0.0.1:57416 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.360 I/GoLog   (17325): Not Using Prepared: tcp,180.130.113.207:443
10-10 02:31:04.360 I/GoLog   (17325): Not Using Prepared: tcp,[2402:4e00:1410::9890:edfe:f13a]:443
10-10 02:31:04.361 I/GoLog   (17325): Not Using Prepared: tcp,81.69.116.86:443
10-10 02:31:04.368 I/GoLog   (17325): [Warning] [1581755714] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > malformed HTTP request "\x00"
10-10 02:31:04.435 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.435 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.435 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.436 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.436 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.442 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.442 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:04.900 I/GoLog   (17325): from udp:127.0.0.1:44736 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:04.951 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:05.171 I/GoLog   (17325): Not Using Prepared: udp,198.19.245.169:19000
10-10 02:31:05.171 I/GoLog   (17325): from udp:127.0.0.1:42547 accepted udp:198.19.245.169:19000 [socks -> direct]
10-10 02:31:05.188 I/GoLog   (17325): Not Using Prepared: tcp,43.231.161.163:5226
10-10 02:31:05.188 I/GoLog   (17325): from tcp:127.0.0.1:57916 accepted tcp:43.231.161.163:5226 [socks -> direct]
10-10 02:31:05.225 I/GoLog   (17325): from tcp:127.0.0.1:57932 accepted tcp:1.1.1.1:853 [socks -> proxy]
10-10 02:31:05.275 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:05.333 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:05.373 I/GoLog   (17325): from tcp:127.0.0.1:57910 accepted tcp:124.71.110.242:7002 [socks -> direct]
10-10 02:31:05.373 I/GoLog   (17325): Not Using Prepared: tcp,124.71.110.242:7002
10-10 02:31:05.742 I/GoLog   (17325): from udp:127.0.0.1:36502 accepted udp:81.69.116.102:443 [socks -> block]
10-10 02:31:05.846 I/GoLog   (17325): from udp:127.0.0.1:42681 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:05.907 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:06.014 I/GoLog   (17325): from udp:127.0.0.1:39296 accepted udp:119.45.2.92:443 [socks -> block]
10-10 02:31:06.439 I/GoLog   (17325): Not Using Prepared: tcp,47.101.67.88:5333
10-10 02:31:06.439 I/GoLog   (17325): from tcp:127.0.0.1:57940 accepted tcp:47.101.67.88:5333 [socks -> direct]
10-10 02:31:06.685 I/GoLog   (17325): Not Using Prepared: tcp,157.148.61.140:8080
10-10 02:31:06.685 I/GoLog   (17325): from tcp:127.0.0.1:57942 accepted tcp:157.148.61.140:8080 [socks -> direct]
10-10 02:31:07.172 I/GoLog   (17325): Not Using Prepared: udp,198.19.245.189:19000
10-10 02:31:07.172 I/GoLog   (17325): from udp:127.0.0.1:52291 accepted udp:198.19.245.189:19000 [socks -> direct]
10-10 02:31:07.281 I/GoLog   (17325): from udp:127.0.0.1:36502 accepted udp:81.69.116.102:443 [socks -> block]
10-10 02:31:07.772 I/GoLog   (17325): from tcp:127.0.0.1:57946 accepted tcp:91.108.56.124:443 [socks -> proxy]
10-10 02:31:07.839 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:07.841 I/GoLog   (17325): from udp:127.0.0.1:39296 accepted udp:119.45.2.92:443 [socks -> block]
10-10 02:31:08.300 I/GoLog   (17325): from udp:127.0.0.1:36502 accepted udp:81.69.116.102:443 [socks -> block]
10-10 02:31:08.850 I/GoLog   (17325): from udp:127.0.0.1:40797 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:08.915 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:09.173 I/GoLog   (17325): from udp:127.0.0.1:57976 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:09.219 I/GoLog   (17325): from udp:127.0.0.1:52043 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:09.266 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:09.272 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:11.172 I/GoLog   (17325): Not Using Prepared: udp,198.19.245.205:19000
10-10 02:31:11.173 I/GoLog   (17325): from udp:127.0.0.1:48553 accepted udp:198.19.245.205:19000 [socks -> direct]
10-10 02:31:11.283 D/com.v2ray.ang(17325): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
10-10 02:31:11.353 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:13.174 I/GoLog   (17325): from udp:127.0.0.1:40166 accepted udp:123.60.92.210:19000 [socks -> proxy]
10-10 02:31:13.234 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:13.725 I/GoLog   (17325): from udp:127.0.0.1:60299 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:13.728 I/GoLog   (17325): from tcp:127.0.0.1:50382 accepted tcp:1.13.117.181:443 [socks -> direct]
10-10 02:31:13.766 I/GoLog   (17325): Not Using Prepared: tcp,212.129.159.173:443
10-10 02:31:13.789 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.047 I/GoLog   (17325): from tcp:127.0.0.1:50394 accepted tcp:140.207.56.254:80 [socks -> direct]
10-10 02:31:14.047 I/GoLog   (17325): from tcp:127.0.0.1:50418 accepted tcp:81.69.116.86:80 [socks -> direct]
10-10 02:31:14.047 I/GoLog   (17325): from tcp:127.0.0.1:50400 accepted tcp:81.69.116.87:80 [socks -> direct]
10-10 02:31:14.047 I/GoLog   (17325): from tcp:127.0.0.1:50408 accepted tcp:81.69.116.102:80 [socks -> direct]
10-10 02:31:14.055 I/GoLog   (17325): Not Using Prepared: tcp,[2402:4e00:1410::9890:edfe:f13a]:80
10-10 02:31:14.056 I/GoLog   (17325): Not Using Prepared: tcp,[2402:4e00:1410::9890:edfe:f13a]:80
10-10 02:31:14.056 I/GoLog   (17325): Not Using Prepared: tcp,[2402:4e00:1410::9890:edfe:f13a]:80
10-10 02:31:14.057 I/GoLog   (17325): Not Using Prepared: tcp,[2402:4e00:1410::9890:edfe:f13a]:80
10-10 02:31:14.220 I/GoLog   (17325): Not Using Prepared: tcp,47.97.66.48:80
10-10 02:31:14.221 I/GoLog   (17325): Not Using Prepared: tcp,81.69.116.86:80
10-10 02:31:14.222 I/GoLog   (17325): from tcp:127.0.0.1:50450 accepted tcp:119.45.249.52:80 [socks -> direct]
10-10 02:31:14.222 I/GoLog   (17325): from tcp:127.0.0.1:50434 accepted tcp:182.50.13.254:80 [socks -> direct]
10-10 02:31:14.223 I/GoLog   (17325): from tcp:127.0.0.1:50462 accepted tcp:119.45.2.92:80 [socks -> direct]
10-10 02:31:14.224 I/GoLog   (17325): from tcp:127.0.0.1:50458 accepted tcp:1.13.12.27:80 [socks -> direct]
10-10 02:31:14.224 I/GoLog   (17325): Not Using Prepared: tcp,1.13.12.27:80
10-10 02:31:14.224 I/GoLog   (17325): Not Using Prepared: tcp,114.55.236.88:80
10-10 02:31:14.298 I/GoLog   (17325): from udp:127.0.0.1:52518 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:14.299 I/GoLog   (17325): from udp:127.0.0.1:51027 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:14.299 I/GoLog   (17325): from udp:127.0.0.1:33697 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:14.299 I/GoLog   (17325): from udp:127.0.0.1:36026 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:14.308 I/GoLog   (17325): from udp:127.0.0.1:53260 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:14.349 I/GoLog   (17325): from udp:127.0.0.1:38037 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:14.355 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.355 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.355 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.356 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.362 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.370 I/GoLog   (17325): from tcp:127.0.0.1:50474 accepted tcp:1.13.12.27:80 [socks -> direct]
10-10 02:31:14.370 I/GoLog   (17325): from tcp:127.0.0.1:50506 accepted tcp:182.50.13.254:80 [socks -> direct]
10-10 02:31:14.370 I/GoLog   (17325): from tcp:127.0.0.1:50486 accepted tcp:119.45.249.52:80 [socks -> direct]
10-10 02:31:14.371 I/GoLog   (17325): from tcp:127.0.0.1:50496 accepted tcp:119.45.2.92:80 [socks -> direct]
10-10 02:31:14.405 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:14.412 I/GoLog   (17325): Not Using Prepared: tcp,114.55.236.88:80
10-10 02:31:14.412 I/GoLog   (17325): Not Using Prepared: tcp,47.97.66.48:80
10-10 02:31:14.412 I/GoLog   (17325): Not Using Prepared: tcp,81.69.116.86:80
10-10 02:31:14.412 I/GoLog   (17325): Not Using Prepared: tcp,81.69.116.102:80
10-10 02:31:14.558 I/GoLog   (17325): from tcp:127.0.0.1:50508 accepted tcp:1.13.111.166:80 [socks -> direct]
10-10 02:31:14.559 I/GoLog   (17325): from tcp:127.0.0.1:50518 accepted tcp:1.13.117.83:80 [socks -> direct]
10-10 02:31:14.602 I/GoLog   (17325): Not Using Prepared: tcp,1.13.111.166:80
10-10 02:31:14.603 I/GoLog   (17325): Not Using Prepared: tcp,106.15.236.125:80
10-10 02:31:14.770 I/GoLog   (17325): from tcp:127.0.0.1:50546 accepted tcp:106.15.236.125:80 [socks -> direct]
10-10 02:31:14.770 I/GoLog   (17325): from tcp:127.0.0.1:50530 accepted tcp:101.133.161.114:80 [socks -> direct]
10-10 02:31:14.809 I/GoLog   (17325): Not Using Prepared: tcp,101.133.161.114:80
10-10 02:31:14.810 I/GoLog   (17325): Not Using Prepared: tcp,106.15.236.125:80
10-10 02:31:14.948 I/GoLog   (17325): from tcp:127.0.0.1:50552 accepted tcp:106.15.236.125:80 [socks -> direct]
10-10 02:31:14.949 I/GoLog   (17325): from tcp:127.0.0.1:50564 accepted tcp:101.133.161.114:80 [socks -> direct]
10-10 02:31:14.985 I/GoLog   (17325): Not Using Prepared: tcp,106.15.236.125:80
10-10 02:31:14.986 I/GoLog   (17325): Not Using Prepared: tcp,101.133.161.114:80
10-10 02:31:15.129 I/GoLog   (17325): from tcp:127.0.0.1:50578 accepted tcp:1.13.117.181:80 [socks -> direct]
10-10 02:31:15.161 I/GoLog   (17325): Not Using Prepared: tcp,212.129.159.173:80
10-10 02:31:15.170 I/GoLog   (17325): Not Using Prepared: udp,139.159.137.254:19000
10-10 02:31:15.170 I/GoLog   (17325): from udp:127.0.0.1:34817 accepted udp:139.159.137.254:19000 [socks -> direct]
10-10 02:31:15.380 I/GoLog   (17325): Not Using Prepared: tcp,27.44.204.147:21000
10-10 02:31:15.380 I/GoLog   (17325): from tcp:127.0.0.1:50580 accepted tcp:27.44.204.147:21000 [socks -> direct]
10-10 02:31:17.286 D/com.v2ray.ang(17325): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout
10-10 02:31:18.140 I/GoLog   (17325): from tcp:127.0.0.1:50598 accepted tcp:119.45.249.168:80 [socks -> direct]
10-10 02:31:18.140 I/GoLog   (17325): from tcp:127.0.0.1:50584 accepted tcp:1.13.111.59:80 [socks -> direct]
10-10 02:31:18.189 I/GoLog   (17325): Not Using Prepared: tcp,47.98.53.142:80
10-10 02:31:18.189 I/GoLog   (17325): Not Using Prepared: tcp,1.13.111.59:80
10-10 02:31:18.341 I/GoLog   (17325): from tcp:127.0.0.1:50612 accepted tcp:1.13.111.166:80 [socks -> direct]
10-10 02:31:18.341 I/GoLog   (17325): from tcp:127.0.0.1:50628 accepted tcp:1.13.117.83:80 [socks -> direct]
10-10 02:31:18.377 I/GoLog   (17325): Not Using Prepared: tcp,175.24.253.110:80
10-10 02:31:18.377 I/GoLog   (17325): Not Using Prepared: tcp,47.97.26.4:80
10-10 02:31:18.549 I/GoLog   (17325): from tcp:127.0.0.1:50666 accepted tcp:1.13.12.27:80 [socks -> direct]
10-10 02:31:18.549 I/GoLog   (17325): from tcp:127.0.0.1:50640 accepted tcp:182.50.13.254:80 [socks -> direct]
10-10 02:31:18.550 I/GoLog   (17325): from tcp:127.0.0.1:50650 accepted tcp:119.45.249.52:80 [socks -> direct]
10-10 02:31:18.550 I/GoLog   (17325): from tcp:127.0.0.1:50632 accepted tcp:119.45.2.92:80 [socks -> direct]
10-10 02:31:18.589 I/GoLog   (17325): Not Using Prepared: tcp,119.45.2.92:80
10-10 02:31:18.589 I/GoLog   (17325): Not Using Prepared: tcp,47.100.99.108:80
10-10 02:31:18.590 I/GoLog   (17325): Not Using Prepared: tcp,47.100.99.108:80
10-10 02:31:18.590 I/GoLog   (17325): Not Using Prepared: tcp,47.97.64.97:80
10-10 02:31:19.729 W/com.v2ray.ang(16725): Checksum mismatch for dex base.apk!classes3.dex
10-10 02:31:19.729 W/com.v2ray.ang(16725): Could not merge the profile. Clearing the profile data.
10-10 02:31:26.972 I/GoLog   (17325): from udp:127.0.0.1:47860 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:27.043 I/GoLog   (17325): Using Prepared: 120.82.70.82
10-10 02:31:27.061 I/GoLog   (17325): from udp:127.0.0.1:50809 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:27.061 I/GoLog   (17325): from udp:127.0.0.1:58804 accepted udp:1.1.1.1:53 [socks -> proxy]
10-10 02:31:27.062 I/GoLog   (17325):

**Comment by jack003007** [comment]
+1

**Comment by jack003007** [comment]
大佬什么时候有空分析一下这个问题

**Comment by qianL93** [comment]
是小米吗？

**Comment by Muayaoi** [comment]
> 是小米吗？

不是，是三星S24Ultra，但在三星平板和宏碁电脑上也用不了

**Comment by creazy412** [comment]
> 是小米吗？

咋？小米被优待了吗？
