### ISSUE TITLE
缺少import go.Seq和import libv2ray.Libv2ray

### ISSUE THREAD

**Issue by HTT7-BZ** [2dust/v2rayNG#3686]
缺少的这几个依赖是什么情况？应该如何解决？
import go.seg
import libv2ray.Libv2ray
import libv2ray.V2RayPoint
import libv2ray.V2RayVPNServicesupportsset
![fcf05d1430f1de4a753462c4c3e6dda](https://github.com/user-attachments/assets/17922c7e-f82d-4a04-81bd-db81c9969b07)

**Comment by ali-koohi** [comment]
I have the same problem. Did you find any solution
