### ISSUE TITLE
希望可以增加自动测速的选项

### ISSUE THREAD

**Issue by veizei-K** [2dust/v2rayNG#3688]
安卓端的karing可以设置时间后自动测试服务器的连接延迟。希望v2rayng也可以支持此选项，最好加上更新订阅链接后立即测试服务器连接延迟。
![Screenshot_2024-10-12-22-59-32-712_com nebula karing-edit](https://github.com/user-attachments/assets/c844afe9-08e5-4cc8-842c-3d29cc805f50)

**Comment by veizei-K** [comment]
如果可以增加自动选择节点的功能就更好了

**Comment by wengzhenquan** [comment]
> 如果可以增加自动选择节点的功能就更好了

其实这个功能并不好，自动选择都是选择延迟低的，但不能保证可用性、网速、ip纯净度，能否解锁奈飞、chatGPT等。

除非能勾选自动选择的优先级，各种条件任用户勾选，但显然是做不到的，检测ip纯净度和测网速不一定会做。

这也是我坚持不使用自动选择的APP的原因，因为自动选择，还不如自己手动选的节点好用，有的网页根本打不开，有的页面图片刷出来跟乌龟爬一样，单单延迟低，没有网速真不行。

如果你需要，现在市面上这种类型的APP已经很多了，不差这一个，而且那些很多sing-box内核的，肯定足够你使用的。

**Comment by 2dust** [comment]
自动选择的请用clash系类app吧
