### ISSUE TITLE
安卓端v2rayNG连接报错

### ISSUE THREAD

**Issue by miaodd98** [2dust/v2rayNG#369]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
连接成功

### 实际行为
连接时报错：io: read/write on closed pipe

### 环境信息
MIUI11.0.5系统，安卓10内核

### 额外信息（可选）
同样的配置在iOS客户端及网页SwitchyOmega均可用，仅安卓端不可用

**Comment by pharmcube** [comment]
遇到了同样的问题，升级3.15之后就出现了这个问题 原先3.14版本可正常使用

**Comment by teamoonlit** [comment]
同样的问题，升级之前还可用，升级之后就一直是io: read/write on closed pipe

**Comment by xkgg** [comment]
？？？？？？

teamoonlit <notifications@github.com> 于 2020年4月15日周三 09:35写道：

**Comment by tjc0726** [comment]
俺也一样 俺是h2的配置

**Comment by 810535323** [comment]
同上。但是版本不同我是MIUI开发版11 20.1.2

**Comment by xkgg** [comment]
我的很正常

810535323 <notifications@github.com> 于 2020年4月16日周四 11:34写道：

**Comment by leanagainstwall** [comment]
我也是这种情况，苹果端小火箭翻墙完全正常，安卓端就不行，系统是魅族pro5 Flyme 7.8.7.24 beta

**Comment by 810535323** [comment]
> 我也是这种情况，苹果端小火箭翻墙完全正常，安卓端就不行，系统是魅族pro5 Flyme 7.8.7.24 beta

我后来转clash可以用，你也可以考虑以下

**Comment by tjc0726** [comment]
> 俺也一样 俺是h2的配置

几天后突然好了……
PS：之前连不上的时候显示的是SSL insercure handshake 什么什么？
PSS：现在又坏了 服务端显示：remote error: tls: bad certificate
allow insercure无论是true还是false都不行
之前服务端有一段日志显示tls:unsupported version【300】 还说没有解密芯片balabalabala不知道有没有关系

**Comment by matterwind** [comment]
我也是更新了最新版1.2.5，连接以后，测试显示io: read/write on closed pipe

**Comment by xkgg** [comment]
ImageAssistant

matterwind <notifications@github.com> 于 2020年4月18日周六 14:39写道：

**Comment by kotori2** [comment]
貌似新装的1.2.4也可以复现这个问题
回退到了1.1.14可行，~~暂时懒得研究到底是哪个版本开始炸的~~

**Comment by 810535323** [comment]
> 貌似新装的1.2.4也可以复现这个问题
> 回退到了1.1.14可行，~暂时懒得研究到底是哪个版本开始炸的~

回退到1.2.1 第一次可以但是之后又不行了

**Comment by kotori2** [comment]
也是很神奇，我用另一台设备的备份还原过去，貌似是可以用的。
另一台设备是GP版更新到1.2.5的，不知道是不是哪里有区别

**Comment by zhuwei** [comment]
跟楼主一样, 死活就是报这错误

**Comment by misakaok** [comment]
一个外国朋友的手机也这样

**Comment by zhuwei** [comment]
> 我也是这种情况，苹果端小火箭翻墙完全正常，安卓端就不行，系统是魅族pro5 Flyme 7.8.7.24 beta

苹果端? 手机吗? 我ios用91vpn也不行

**Comment by mr-cn** [comment]
tls+websocket方案
io: read/write on closed pipe
使用相同配置在同网络下iPhone和PC都可用。
MIUI11 Android 9，MIUI12 Android 10均100%复现

**Comment by Wentong-Liu** [comment]
都一个月了还没修复么？

**Comment by pharmcube** [comment]
今天升级到1.2.6问题还是没有解决 连接时报错：io: read/write on closed pipe 没办法还要再回退至1.2.4 所有的设置要重新设置 好麻烦 请求开发者排查一下是什么原因

**Comment by misakaok** [comment]
好像把allow选项打开 加密选择chacha20就好了

**Comment by pharmcube** [comment]
我是用的H2+tls PC电脑端可以正常使用 android端用1.2.4正常 升级1.2.5之后的版本就不能用了

**Comment by jiusanzhou** [comment]
这个情况发生在配置QR过来的情况，alertId, ws相关的参数会丢失，手动加上就可以了。

出现问题，仔细检查下设置的参数是否和服务端配置的一致。

**Comment by pharmcube** [comment]
检查了一下参数没有错误 1.2.6还是不能用

**Comment by mr-cn** [comment]
并不是配置参数的问题，我是从老版本升级时遇到的问题，之前一直正常使用。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送
________________________________

**Comment by 1265578519** [comment]
新版本确实有这个问题，，，因为默认改了TLS核心代码的缘故

**Comment by imoonkin** [comment]
> 好像把allow选项打开 加密选择chacha20就好了

我的是配置里面最下面的allowinsecure设置成true就能用了

**Comment by laichihwei** [comment]
> > 好像把allow选项打开 加密选择chacha20就好了
> 
> 我的是配置里面最下面的allowinsecure设置成true就能用了

確認可行喔!感謝

**Comment by delicopper** [comment]
> > 好像把allow选项打开 加密选择chacha20就好了
> 
> 我的是配置里面最下面的allowinsecure设置成true就能用了

正解

**Comment by 1265578519** [comment]
修复方法，点击和笔一样的修改按钮，找到allowinsecure设置成true，重新连接服务器就能通了

**Comment by WNZhao** [comment]
> > 好像把allow选项打开 加密选择chacha20就好了
> 
> 我的是配置里面最下面的allowinsecure设置成true就能用了

正解

**Comment by shrimpbighead** [comment]
> 我也是更新了最新版1.2.5，连接以后，测试显示io: read/write on closed pipe

卸载后重新安装新版本，我也出现这个问题，然后更改设置跳过证书认证（allowInsecure）为true后就可以了

**Comment by leifengcomrade** [comment]
捡来的杂牌安卓手机，这几天我也这情况，上面的没效果，最后在手机设置里还原网络设置就可以了

**Comment by fschenkun22** [comment]
注意！ 伪装域名要填写你的域名；path要填写 “/你的路径” ； SNI填写你的域名；这些都要填，时间不准可能造成这个原因，但是不填写这些表现出来的现象和时间证书正确都一样

**Comment by alex89924** [comment]
节点中，跳过证书验证(allowlnsecure)，默认是false，改成true就ok了。
![image](https://user-images.githubusercontent.com/18138788/157637497-f3ef0a6b-4502-4bea-8f89-7045827cb88e.png)

**Comment by PolarisTime** [comment]
出现这个问题可以尝试修复下服务器证书链

**Comment by Mydong** [comment]
除了上面，设置跳过证书验证：true外。
我将 xui里面的xray 状态，【且换成高版本】然后在切换成了【最低版本】后，恢复了；
囧
![image](https://user-images.githubusercontent.com/14023137/222061215-fcb49fa7-910b-4128-9d9a-afb9abdce213.png)

**Comment by lisinwang** [comment]
把分片（Fragment）设置打开就可以
