### ISSUE TITLE
当hysteria2协议的配置密码存在特殊符号时，导入此类配置会失败 (video attached)

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3690]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

hysteria2协议的分享链接或者二维码应当能正常导入导出，并且能够还原预期的配置。

### 实际行为
描述实际发生了什么

实际情况是当连接密码存在特殊符号时，导入包含此类密码的配置会失败。

### 复现方法

1.寻找或通过应用程式生成一个带有符合条件的配置文件
2.将获取的信息通过链接或者二维码导入
3.您将看到导入错误的结果

### 日志信息

此行为没有产生任何报错信息，即便是将日志级别调整到debug也如此。

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

已附加萤幕录影来说明问题。

应用程式版本为 1.9.7

https://github.com/user-attachments/assets/8cf08239-d3c0-4bc3-8f72-56049067aee2

**Comment by 2dust** [comment]
分享链接URI要按照原始规范生成，请不要使用保留字符

**Comment by 2dust** [comment]
不是规范的字符串，即使在这个app做了修改，其他app一样会有问题

**Comment by 2dust** [comment]
URI中，比如`@，/，?` 这些都是保留的字符，使用后很多开发语言的函数解析都会报错

**Comment by 2dust** [comment]
35063db3e6fc296bbce433dc7ea4132edcb800bd
