### ISSUE TITLE
tcping是通的但是无法上网，同一节点clash可以上

### ISSUE THREAD

**Issue by myCodingTrip** [2dust/v2rayNG#3691]
![SmartSelect_20241019_124837_v2rayNG](https://github.com/user-attachments/assets/27216b28-6162-42c3-9ea2-ae0e59b297d4)

--------- beginning of main
10-14 20:56:27.791 I/GoLog   (26363): loading core config
10-14 20:56:27.791 I/GoLog   (26363): Preparing Domain: 3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:27.821 I/GoLog   (26363): Prepare Result:
10-14 20:56:27.821 I/GoLog   (26363):  Domain: 3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net
10-14 20:56:27.821 I/GoLog   (26363):  Port: 8808
10-14 20:56:27.821 I/GoLog   (26363):  IPs: [192.74.229.119]
10-14 20:56:27.887 I/GoLog   (26363): new core
10-14 20:56:27.887 I/GoLog   (26363): [Debug] app/log: Logger started
10-14 20:56:27.897 I/GoLog   (26363): [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
10-14 20:56:27.897 I/GoLog   (26363): [Info] app/dns: DNS: created UDP client initialized for 1.1.1.1:53
10-14 20:56:27.897 I/GoLog   (26363): [Info] app/dns: DNS: created UDP client initialized for 223.5.5.5:53
10-14 20:56:27.908 I/GoLog   (26363): [Debug] app/router: MphDomainMatcher is enabled for 2 domain rule(s)
10-14 20:56:27.909 I/GoLog   (26363): [Debug] app/router: MphDomainMatcher is enabled for 719 domain rule(s)
10-14 20:56:27.910 I/GoLog   (26363): [Debug] app/router: MphDomainMatcher is enabled for 138 domain rule(s)
10-14 20:56:27.915 I/GoLog   (26363): [Debug] app/router: MphDomainMatcher is enabled for 10676 domain rule(s)
10-14 20:56:27.915 I/GoLog   (26363): [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:10808
10-14 20:56:27.915 I/GoLog   (26363): [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:10809
10-14 20:56:27.915 I/GoLog   (26363): start core
10-14 20:56:27.916 I/GoLog   (26363): [Info] transport/internet/tcp: listening TCP on 127.0.0.1:10809
10-14 20:56:27.916 I/GoLog   (26363): [Info] transport/internet/tcp: listening TCP on 127.0.0.1:10808
10-14 20:56:27.916 I/GoLog   (26363): [Info] transport/internet/udp: listening UDP on 127.0.0.1:10808
10-14 20:56:27.916 I/GoLog   (26363): [Warning] core: Xray 24.9.30 started
10-14 20:56:27.931 D/com.v2ray.ang(26363): [/data/app/~~R_BN-p7A46QuCBYkmqtjjw==/com.v2ray.ang-JgiPDz3omdqaC8El-FFINg==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
10-14 20:56:27.933 D/com.v2ray.ang(26363): Process[pid=477, hasExited=false]
10-14 20:56:27.933 D/com.v2ray.ang(26363): libtun2socks.so check
10-14 20:56:27.933 D/com.v2ray.ang(26363): /data/user/0/com.v2ray.ang/files/sock_path
10-14 20:56:27.938 D/com.v2ray.ang(26363): runPlugin
10-14 20:56:27.945 I/tun2socks(  477): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
10-14 20:56:27.984 D/com.v2ray.ang(26363): sendFd tries: 0
10-14 20:56:27.984 I/tun2socks(  477): NOTICE(tun2socks): entering event loop
10-14 20:56:27.986 I/GoLog   (26363): [Info] [3835942565] proxy/socks: client UDP connection from udp:127.0.0.1:42579
10-14 20:56:27.986 I/GoLog   (26363): [Debug] [3835942565] proxy/socks: send packet to udp:1.1.1.1:53 with 39 bytes
10-14 20:56:27.986 I/GoLog   (26363): [Debug] [3835942565] transport/internet/udp: dispatch request to: udp:1.1.1.1:53
10-14 20:56:27.986 I/GoLog   (26363): [Info] [3835942565] transport/internet/udp: establishing new connection for udp:1.1.1.1:53
10-14 20:56:27.986 I/GoLog   (26363): [Info] [3835942565] app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
10-14 20:56:27.986 I/GoLog   (26363): [Info] [3835942565] transport/internet/websocket: creating connection to tcp:3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:27.986 I/GoLog   (26363): from udp:127.0.0.1:42579 accepted udp:1.1.1.1:53 [socks -> proxy]
10-14 20:56:28.016 I/GoLog   (26363): [Info] [1851773300] proxy/socks: client UDP connection from udp:127.0.0.1:36547
10-14 20:56:28.016 I/GoLog   (26363): [Debug] [1851773300] proxy/socks: send packet to udp:1.1.1.1:53 with 34 bytes
10-14 20:56:28.016 I/GoLog   (26363): [Debug] [1851773300] transport/internet/udp: dispatch request to: udp:1.1.1.1:53
10-14 20:56:28.016 I/GoLog   (26363): [Info] [1851773300] transport/internet/udp: establishing new connection for udp:1.1.1.1:53
10-14 20:56:28.016 I/GoLog   (26363): [Info] [1851773300] app/dispatcher: taking detour [proxy] for [udp:1.1.1.1:53]
10-14 20:56:28.016 I/GoLog   (26363): [Info] [1851773300] transport/internet/websocket: creating connection to tcp:3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:28.016 I/GoLog   (26363): from udp:127.0.0.1:36547 accepted udp:1.1.1.1:53 [socks -> proxy]
10-14 20:56:28.201 I/GoLog   (26363): Using Prepared: 192.74.229.119
10-14 20:56:28.220 I/GoLog   (26363): Using Prepared: 192.74.229.119
10-14 20:56:28.426 I/GoLog   (26363): [Info] [3835942565] proxy/vmess/outbound: tunneling request to udp:1.1.1.1:53 via 3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:28.426 I/GoLog   (26363): [Info] [1851773300] proxy/vmess/outbound: tunneling request to udp:1.1.1.1:53 via 3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:28.700 I/GoLog   (26363): [Info] [3835942565] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > websocket: close 1005 (no status) > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1005 (no status)
10-14 20:56:28.700 I/GoLog   (26363): [Info] [3835942565] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
10-14 20:56:28.705 I/GoLog   (26363): [Info] [1851773300] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > websocket: close 1005 (no status) > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1005 (no status)
10-14 20:56:28.705 I/GoLog   (26363): [Info] [1851773300] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
10-14 20:56:28.967 I/GoLog   (26363): [Info] [2741470285] proxy/socks: TCP Connect request to tcp:1.1.1.1:853
10-14 20:56:28.968 I/GoLog   (26363): [Info] [2741470285] app/dispatcher: taking detour [proxy] for [tcp:1.1.1.1:853]
10-14 20:56:28.968 I/GoLog   (26363): [Info] [2741470285] transport/internet/websocket: creating connection to tcp:3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:28.968 I/GoLog   (26363): from tcp:127.0.0.1:52364 accepted tcp:1.1.1.1:853 [socks -> proxy]
10-14 20:56:29.204 I/GoLog   (26363): Using Prepared: 192.74.229.119
10-14 20:56:29.416 I/GoLog   (26363): [Info] [2741470285] proxy/vmess/outbound: tunneling request to tcp:1.1.1.1:853 via 3d2d1ca8-slicg0-spbci0-glzt.sja.plebai.net:8808
10-14 20:56:29.723 I/GoLog   (26363): [Info] [2741470285] app/proxyman/outbound: app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > common/drain: common/drain: unable to drain connection > websocket: close 1005 (no status) > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1005 (no status)
10-14 20:56:29.723 I/GoLog   (26363): [Info] [2741470285] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

系统安卓14 one ui 6.1

**Comment by 2dust** [comment]
开跳过证书验证

**Comment by myCodingTrip** [comment]
> 开跳过证书验证

开了，还是不行
