### ISSUE TITLE
安卓无法使用的问题

### ISSUE THREAD

**Issue by xwlcn** [2dust/v2rayNG#3700]
在android5上面一些低版本(1.8.x)的可以使用，android9根本找不到可用的版本，要么报io错误，要么显示连接上测试也通过，但就是任何网站都打不开。

看到有不少人报告这个问题，是不是故意不修复这个问题的？

全网找了半天终于找到了一个可用的基于v2ray的第三方版本，算是一个古老的版本了，由于v2rayNG版本太多我就没去一个一个试了，估计有些很老的版本也是可以的。

**Comment by joker8818** [comment]
![Screenshot_20241016_161903.jpg](https://github.com/user-attachments/assets/05f07fc4-2bc8-4086-bdf2-014ea57a7b75)

![Screenshot_20241016_161707.jpg](https://github.com/user-attachments/assets/ae545d9b-77b8-4c20-be26-a0a1e25b137d)

![Screenshot_20241016_161705.jpg](https://github.com/user-attachments/assets/2efae3fc-d2d5-4f10-bcc6-7ab8b52897bb)

完全无法解决吗？

**Comment by xwlcn** [comment]
> ![Screenshot_20241016_161903.jpg](https://private-user-images.githubusercontent.com/90705578/376989419-05f07fc4-2bc8-4086-bdf2-014ea57a7b75.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzM1NzEsIm5iZiI6MTcyOTA3MzI3MSwicGF0aCI6Ii85MDcwNTU3OC8zNzY5ODk0MTktMDVmMDdmYzQtMmJjOC00MDg2LWJkZjItMDE0ZWE1N2E3Yjc1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEwMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NzJhMDMxZmQwYWY1NDA5ZGE4OGY4YTM1ZDYwYTcyOWZjNDcxY2RhNDllODU2NmMzNjAxNWE2YjRlMzdiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZtSPWvqdyMJNVkVRFdDouXstdV6CidV8tD6H-RtUEDw)
> 
> ![Screenshot_20241016_161707.jpg](https://private-user-images.githubusercontent.com/90705578/376989434-ae545d9b-77b8-4c20-be26-a0a1e25b137d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzM1NzEsIm5iZiI6MTcyOTA3MzI3MSwicGF0aCI6Ii85MDcwNTU3OC8zNzY5ODk0MzQtYWU1NDVkOWItNzdiOC00YzIwLWJlMjYtYTBhMWUyNWIxMzdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEwMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZjg2N2YzMDQ0ZDAyNzI0YTQyYzc3MmIxNmQ1YzE0ZjU5N2RkYmMyNTNkYThlNzFjY2RjMDE2ZjJmYzdkYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0us_2GBJxsXxR4SKI3aft6sbopRlwVrErCNf8w3Txlg)
> 
> ![Screenshot_20241016_161705.jpg](https://private-user-images.githubusercontent.com/90705578/376989449-2efae3fc-d2d5-4f10-bcc6-7ab8b52897bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzM1NzEsIm5iZiI6MTcyOTA3MzI3MSwicGF0aCI6Ii85MDcwNTU3OC8zNzY5ODk0NDktMmVmYWUzZmMtZDJkNS00ZjEwLWJjYzYtN2FiOGI1Mjg5N2JiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEwMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWU0ODVhMzZlYmQyYTMyY2NjNmMyMDFmNjNhMjRmMWIxNjM1YTQ0OGJkMDk3Y2I2MzBlOThjNTI2NTlmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Q8U4WyF6yLvZk2LArRc83MDdFj-CTkZbDosgso_WdVU)
> 
> 完全无法解决吗？

我现在用的SagerNet 0.8.1版本，在android9上面正常使用，但这个好像不支持订阅，界面基本上就是V2RayNG一样的。

**Comment by 2dust** [comment]
启动失败，看下是否有日志

**Comment by masoncli** [comment]
> 在android5上面一些低版本(1.8.x)的可以使用，android9根本找不到可用的版本，要么报io错误，要么显示连接上测试也通过，但就是任何网站都打不开。
> 
> 看到有不少人报告这个问题，是不是故意不修复这个问题的？
> 
> 全网找了半天终于找到了一个可用的基于v2ray的第三方版本，算是一个古老的版本了，由于v2rayNG版本太多我就没去一个一个试了，估计有些很老的版本也是可以的。

同样的问题，请问下是哪个软件
