### ISSUE TITLE
删除节点操作改进建议

### ISSUE THREAD

**Issue by Plus-xu** [2dust/v2rayNG#3705]
切换程序或解锁等操作后误触删除按钮导致节点消失。特别是很多自己手动输入的自建节点，一不小心就删除了。

### 预期行为
删除节点可在几秒钟内撤销或多一步确认操作或者增加节点或界面锁定功能。

### 实际行为
误触删除按键导致节点消失，甚至不知道自己误删除了哪一个。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
设置中有选项
