### ISSUE TITLE
建议加个信任用户证书的功能吧。

### ISSUE THREAD

**Issue by cuihao777** [2dust/v2rayNG#371]
### 预期行为
当 allowInsecure 为 false 时从用户证书中获取证书。

### 实际行为
因为找不到证书导致无法翻墙。

### 环境信息
MIUI 11, Android 10

### 额外信息（可选）
通常我们使用免费的 SSL 颁发机构 Let's Encrypt 颁发的证书。 但是因为 Android 中没有 Let's Encrypt 的根证书，所以需要自己导入用户级别的证书。 但是听说从 Android 7 开始如果不加以指定，那么只信任系统自带的证书，而不信任用户证书。导致 allowInsecure 属性形同虚设。

**Comment by cuihao777** [comment]
我觉得可以加导入本地证书的功能。 我发现 V2ray 中可以指定证书文件。

https://v2ray.com/chapter_02/05_transport.html#certificateobject

**Comment by yuhan6665** [comment]
Can you try https://support.google.com/pixelphone/answer/2844832?hl=en

**Comment by okudayukiko** [comment]
三星手机导入自签名CA证书后总有不安全提示。
iOS不信任导入的自签名CA证书。

**Comment by xianren78** [comment]
没看明白，全部都是Let's Encrypt的免费证书，allowInsecure false没问题啊

**Comment by cuihao777** [comment]
> Can you try https://support.google.com/pixelphone/answer/2844832?hl=en

还是不行.

你可以参考这个页面。
https://developer.android.com/training/articles/security-config#trust-anchors

**Comment by cuihao777** [comment]
从 Android 7 开始，应用只信任系统自带证书。
用户级别的证书只能用于浏览器。

但是我估计大部分机器都不自带 Let's Encrypt 的 CA 证书。

**Comment by yuhan6665** [comment]
> 从 Android 7 开始，应用只信任系统自带证书。
> 用户级别的证书只能用于浏览器。
> 
> 但是我估计大部分机器都不自带 Let's Encrypt 的 CA 证书。

Thanks for your information. Looks like you are right. I will try to make a pull request.

**Comment by okudayukiko** [comment]
> 从 Android 7 开始，应用只信任系统自带证书。
> 用户级别的证书只能用于浏览器。
> 
> 但是我估计大部分机器都不自带 Let's Encrypt 的 CA 证书。

Samsung、SONY手机更新系统后都有Let's Encrypt。

**Comment by yuhan6665** [comment]
#380 submitted

**Comment by cuihao777** [comment]
> #380 submitted

Thanks for your feedback.

**Comment by xsunghost** [comment]
用MIUI还是别翻墙了吧，多危险

**Comment by primelyw** [comment]
> Can you try https://support.google.com/pixelphone/answer/2844832?hl=en

添加用户级CA后，app仍显示"certificate signed by unknown authority"
