### ISSUE TITLE
改进繁体中文翻译

### ISSUE THREAD

**Issue by okudayukiko** [2dust/v2rayNG#372]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
繁体中文翻译要改进
V2RayNG將「Configuration file」翻譯為「組態」，其實應該翻譯為「設定檔」。
![Screenshot_20200415-223038_v2rayNG](https://user-images.githubusercontent.com/17502357/79376069-3041f780-7f8c-11ea-8a19-ebf2ca9df386.jpg)
![Screenshot_20200415-223426_v2rayNG](https://user-images.githubusercontent.com/17502357/79376085-36d06f00-7f8c-11ea-8fc5-31b29b0e4c2f.jpg)
![Screenshot_20200415-223934_Shadowsocks](https://user-images.githubusercontent.com/17502357/79376096-3b952300-7f8c-11ea-84c2-bef7cf03b9a0.jpg)

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
@okudayukiko Thanks for your feedback. Can you help fill in the following translation?
Configuration file <-> 配置文件 <-> 設定檔
Add config <-> 添加配置 <-> ?
Import config from Clipboard <-> 从剪贴板导入配置 <-> ?
Import custom config from URL <-> 剪贴板URL导入自定义配置 <-> ?

**Comment by okudayukiko** [comment]
> @okudayukiko Thanks for your feedback. Can you help fill in the following translation?
> Configuration file <-> 配置文件 <-> 設定檔
> Add config <-> 添加配置 <-> ?
> Import config from Clipboard <-> 从剪贴板导入配置 <-> ?
> Import custom config from URL <-> 剪贴板URL导入自定义配置 <-> ?

Clipboard=剪貼簿
Config=設定/組態
Setting=設定
Setup=設定/安裝
Config file=設定檔

**Comment by yuhan6665** [comment]
Got it. So "Configuration" with "file" should be "設定檔". But "Customize Config" should stay as "自訂組態"
I will push a commit to fix it.

**Comment by yuhan6665** [comment]
Fix in #425

**Comment by okudayukiko** [comment]
https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/res/values-zh-rTW/strings.xml

`代理共享已啟用，請確保處於受信網絡` -> `代理共享已啟用，請確保處於受信網路`
`協議`（Protocol）一般叫`協定`。
`局域網`（一般簡體中文叫局域網）->`區域網路`（繁體中文作業系統一般叫區域網路）
`默認`（Default）一般叫`預設`
`可选`->`可選`
`端口`（Port）->`連接埠`
@yuhan6665

**Comment by yuhan6665** [comment]
@okudayukiko thanks for your suggestion. I've pushed a new version to fix all of the text you mentioned.
