### ISSUE TITLE
Migrate to jetpack compose ?

### ISSUE THREAD

**Issue by codewithtamim** [2dust/v2rayNG#3722]
Migrate to jetpack compose ?

**Comment by 2dust** [comment]
The workload is huge. 
You can migrate some simple pages to see the effect.
https://developer.android.com/codelabs/basic-android-kotlin-training-compose-add-compose-to-a-view-based-app#0

**Comment by ghost** [comment]
> Migrate to jetpack compose ?

Hello, if you can implement this project, thank you
