### ISSUE TITLE
Some changes according to the latest ‌xray kernel 

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3725]
Hi 
I request to make these changes according to the latest ‌xray kernel.
Delete quic protocol,alias TCP(raw),Alternative h3 protocol to http protocol,.... 

https://github.com/XTLS/Xray-core/commit/d8485bd5afdec44654460b58d6a4bfb89cfc7786

https://github.com/XTLS/Xray-core/commit/3632e83faa70f2bdd08507c54b251ecd22092e6c

https://github.com/XTLS/Xray-core/commit/75729ce77902d3da2b95c53bb3c87676a6482dff

HTTP 传输层的 H3：https://xtls.github.io/config/transports/http.html 
Transport: Add HTTP3 to HTTP 
https://github.com/XTLS/Xray-core/commit/3632e83faa70f2bdd08507c54b251ecd22092e6c

TCP 传输层更名为 RAW：https://xtls.github.io/config/transports/raw.html

https://github.com/XTLS/Xray-core/pull/3754

Add udp noise gui Similar fragment in app

https://github.com/XTLS/Xray-core/commit/363e86c5857eb963b23183a19024d1d28ebbd03f

Transport: Remove GUN (an alias of gRPC) 

https://github.com/XTLS/Xray-core/commit/8809cbda817006f8d33c4c9993014d146f7e1138

XMUX: Change to non-infinity-reuse default values
Add xmux value gui Similar fragment in app

https://github.com/XTLS/Xray-core/commit/897521defdfeb610ec0d7608b4f11ed55780485a

REALITY config: Add target as an alias of dest

https://github.com/XTLS/Xray-core/commit/75729ce77902d3da2b95c53bb3c87676a6482dff
 
Thanks a lot

@CodeWithTamim @2dust

**Comment by codewithtamim** [comment]
Okay will do soon

**Comment by DECORATIVEFAMILYNG** [comment]
Bro lib v27 is not Expired?!

**Comment by DECORATIVEFAMILYNG** [comment]
> Okay will do soon

fix(deps): Update Go version to 1.23.2 for Xray compatibility (24.10.6)

.github/workflows/build.yml

**Comment by 2dust** [comment]
> TCP 传输层更名为 RAW：https://xtls.github.io/config/transports/raw.html

Do not modify this yet

**Comment by codewithtamim** [comment]
> > Okay will do soon
> 
> Bro lib v27 is not old?! (AndroidLibV2rayLite)
> 
> Update Go version to 1.23.2 for Xray compatibility (24.10.6)
> 
> .github/workflows/build.yml
> 
> Added dependabot to app🤔

It uses AndroidLibXrayLite
