### ISSUE TITLE
V2ray paste

### ISSUE THREAD

**Issue by Mrbrdia** [2dust/v2rayNG#3742]
Hi,
I have a problem with v2ray, I can't paste my configs on it, I uptaded it but still I can't paste, and I use the last version of this app.
Wait for hear from you.

**Comment by Mrbrdia** [comment]
.

**Comment by codewithtamim** [comment]
Send a video screen recording the issue

**Comment by Mrbrdia** [comment]
If you want to see in english language, tell me to record again.

**Comment by 2dust** [comment]
no config
no log
