### ISSUE TITLE
Invalid dns

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3743]
Hello to all those involved in the program
In previous versions, when local DNS was active at the same time as remote DNS and the VPN DNS section was empty, when checking DNS, I noticed that only the DNS that I had set in the server and adgaurd Home returned, but in the current version, if local DNS and remote DNS are active and the DNS server is empty, only Google and Cloudflare DNS are returned, so I have to fill in the VPN DNS section so that my server DNS is returned at the same time. And if I activate the Iranian rules and GeoIP and Geosite Direct are used, Alibaba DNS is also added, which I have to disable so that Alibaba DNS is not used.
If it is possible, this situation can be returned to the previous version of these events.
Versions 1.9.2 and earlier are OK, I think this pull request was effective.

https://github.com/2dust/v2rayNG/commit/c61595eb0d5c9feb9559ed9f22c150bd2a1aa80d

So I need to solve the problem of adding Alibaba's DNS and only returning my own server's DNS and adgaurd Home. I hope I've explained it clearly.
Thanks

**Comment by 2dust** [comment]
Please set it up and send out the full configuration
Did you remove the alibaba dns from your configuration?
