### ISSUE TITLE
Starting the V2RayVpnService issue

### ISSUE THREAD

**Issue by itsAmirhossein** [2dust/v2rayNG#3748]
Hello, I encountered an issue when starting the service. It shows the following error, preventing the connection to the server. Could you advise me on how to solve this problem?

runtime: newstack at runtime.printlock+0x78 sp=0x4000db5a70 stack=[0x4000da6000, 0x4000db6000]
04:51:05.190  E  	morebuf={pc:0x7b9aaec7e0 sp:0x4000db5a70 lr:0x0}
04:51:05.190  E  runtime: newstack at runtime.printlock+0x78 sp=0x4000db5a70 stack=[0x4000da6000, 0x4000db6000]
04:51:05.190  E  	sched={pc:0x7b9ab22048 sp:0x4000db5a70 lr:0x7b9aaec7e0 ctxt:0x0}
04:51:05.190  E  	morebuf={pc:0x7b9aaec7e0 sp:0x4000db5a70 lr:0x0}
04:51:05.190  E  	sched={pc:0x7b9ab22048 sp:0x4000db5a70 lr:0x7b9aaec7e0 ctxt:0x0}
04:51:05.190  E  runtime.callbackUpdateSystemStack(0x4000072008, 0x7fdf1e3e80, 0x0)
04:51:05.190  E  runtime.callbackUpdateSystemStack(0x4000072008, 0x7fdf1e3e80, 0x0)
04:51:05.190  E  	/usr/local/go/src/runtime/cgocall.go:257 +0x90 fp=0x4000db5ad0 sp=0x4000db5a70 pc=0x7b9aaec7e0
04:51:05.190  E  	/usr/local/go/src/runtime/cgocall.go:257 +0x90 fp=0x4000db5ad0 sp=0x4000db5a70 pc=0x7b9aaec7e0
04:51:05.190  E  runtime.cgocallbackg(0x7b9b5a1a60, 0x7fdf1e3f78, 0x0)
04:51:05.190  E  runtime.cgocallbackg(0x7b9b5a1a60, 0x7fdf1e3f78, 0x0)
04:51:05.190  E  	/usr/local/go/src/runtime/cgocall.go:322 +0x68 fp=0x4000db5b20 sp=0x4000db5ad0 pc=0x7b9aaec9a8
04:51:05.190  E  	/usr/local/go/src/runtime/cgocall.go:322 +0x68 fp=0x4000db5b20 sp=0x4000db5ad0 pc=0x7b9aaec9a8
04:51:05.190  E  runtime.cgocallbackg(0x7b9b5a1a60, 0x7fdf1e3f78, 0x0)
04:51:05.190  E  runtime.cgocallbackg(0x7b9b5a1a60, 0x7fdf1e3f78, 0x0)
04:51:05.190  E  	<autogenerated>:1 +0x1c fp=0x4000db5b50 sp=0x4000db5b20 pc=0x7b9ab65a7c
04:51:05.190  E  	<autogenerated>:1 +0x1c fp=0x4000db5b50 sp=0x4000db5b20 pc=0x7b9ab65a7c
04:51:05.190  E  runtime.cgocallback(0x4000db5bc8, 0x7b9b59fab4, 0x7b9b5a3128)
04:51:05.190  E  runtime.cgocallback(0x4000db5bc8, 0x7b9b59fab4, 0x7b9b5a3128)
04:51:05.190  E  	/usr/local/go/src/runtime/asm_arm64.s:1131 +0xb0 fp=0x4000db5b80 sp=0x4000db5b50 pc=0x7b9ab639d0
04:51:05.190  E  	/usr/local/go/src/runtime/asm_arm64.s:1131 +0xb0 fp=0x4000db5b80 sp=0x4000db5b50 pc=0x7b9ab639d0
04:51:05.190  E  runtime.systemstack_switch()
04:51:05.190  E  runtime.systemstack_switch()
04:51:05.190  E  	/usr/local/go/src/runtime/asm_arm64.s:201 +0x8 fp=0x4000db5b90 sp=0x4000db5b80 pc=0x7b9ab61598
04:51:05.190  E  	/usr/local/go/src/runtime/asm_arm64.s:201 +0x8 fp=0x4000db5b90 sp=0x4000db5b80 pc=0x7b9ab61598
04:51:05.190  E  runtime.cgocall(0x7b9b5a3128, 0x4000db5c08)
04:51:05.190  E  runtime.cgocall(0x7b9b5a3128, 0x4000db5c08)
04:51:05.190  E  	/usr/local/go/src/runtime/cgocall.go:185 +0x70 fp=0x4000db5bd0 sp=0x4000db5b90 pc=0x7b9ab54850
04:51:05.190  E  	/usr/local/go/src/runtime/cgocall.go:185 +0x70 fp=0x4000db5bd0 sp=0x4000db5b90 pc=0x7b9ab54850
04:51:05.190  E  main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
04:51:05.191  E  main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
04:51:05.191  E  	_cgo_gotypes.go:167 +0x34 fp=0x4000db5c00 sp=0x4000db5bd0 pc=0x7b9b59fab4
04:51:05.191  E  	_cgo_gotypes.go:167 +0x34 fp=0x4000db5c00 sp=0x4000db5bd0 pc=0x7b9b59fab4
04:51:05.191  E  main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x4000010018, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
04:51:05.191  E  main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x4000010018, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
04:51:05.191  E  	/tmp/gomobile-work-2783945812/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x4000db5c60 sp=0x4000db5c00 pc=0x7b9b5a1068
04:51:05.191  E  	/tmp/gomobile-work-2783945812/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x4000db5c60 sp=0x4000db5c00 pc=0x7b9b5a1068
04:51:05.191  E  main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x4000010018, {0x0?, 0x2?})
04:51:05.191  E  main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x4000010018, {0x0?, 0x2?})
04:51:05.191  E  	/tmp/gomobile-work-2783945812/src-android-arm64/gobind/go_libv2raymain.go:302 +0x44 fp=0x4000db5ca0 sp=0x4000db5c60 pc=0x7b9b5a0fb4
04:51:05.191  E  github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).pointloop(0x40000b2000)
04:51:05.191  E  	/tmp/gomobile-work-2783945812/src-android-arm64/gobind/go_libv2raymain.go:302 +0x44 fp=0x4000db5ca0 sp=0x4000db5c60 pc=0x7b9b5a0fb4
04:51:05.191  E  github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).pointloop(0x40000b2000)
04:51:05.191  E  	/home/amirhossein/Android/Projects/v2rayNG/V2rayNG/AndroidLibXrayLite/libv2ray_main.go:164 +0x42c fp=0x4000db5d90 sp=0x4000db5ca0 pc=0x7b9b59a29c
04:51:05.191  E  	/home/amirhossein/Android/Projects/v2rayNG/V2rayNG/AndroidLibXrayLite/libv2ray_main.go:164 +0x42c fp=0x4000db5d90 sp=0x4000db5ca0 pc=0x7b9b59a29c
04:51:05.191  E  github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).RunLoop(0x40000b2000, 0x0)
04:51:05.191  E  github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).RunLoop(0x40000b2000, 0x0)
04:51:05.191  E  	/home/amirhossein/Android/Projects/v2rayNG/V2rayNG/AndroidLibXrayLite/libv2ray_main.go:101 +0x20c fp=0x4000db5e10 sp=0x4000db5d90 pc=0x7b9b5997dc
04:51:05.191  E  	/home/amirhossein/Android/Projects/v2rayNG/V2rayNG/AndroidLibXrayLite/libv2ray_main.go:101 +0x20c fp=0x4000db5e10 sp=0x4000db5d90 pc=0x7b9b5997dc
04:51:05.191  E  main.proxylibv2ray_V2RayPoint_RunLoop(0xffffff01?, 0x0)
04:51:05.191  E  main.proxylibv2ray_V2RayPoint_RunLoop(0xffffff01?, 0x0)
04:51:05.191  E  	/tmp/gomobile-work-2783945812/src-android-arm64/gobind/go_libv2raymain.go:196 +0x4c fp=0x4000db5e40 sp=0x4000db5e10 pc=0x7b9b5a07bc
04:51:05.191  E  	/tmp/gomobile-work-2783945812/src-android-arm64/gobind/go_libv2raymain.go:196 +0x4c fp=0x4000db5e40 sp=0x4000db5e10 pc=0x7b9b5a07bc
04:51:05.191  E  _cgoexp_6f524d1d87fa_proxylibv2ray_V2RayPoint_RunLoop(0x7fdf1e57c4)
04:51:05.191  E  _cgoexp_6f524d1d87fa_proxylibv2ray_V2RayPoint_RunLoop(0x7fdf1e57c4)
04:51:05.191  E  	_cgo_gotypes.go:383 +0x2c fp=0x4000db5e60 sp=0x4000db5e40 pc=0x7b9b5a1e5c
04:51:05.191  E  	_cgo_gotypes.go:383 +0x2c fp=0x4000db5e60 sp=0x4000db5e40 pc=0x7b9b5a1e5c
04:51:05.191  E  runtime.cgocallbackg1(0x7b9b5a1e30, 0x7fdf1e57c4, 0x0)
04:51:05.191  E  runtime.cgocallbackg1(0x7b9b5a1e30, 0x7fdf1e57c4, 0x0)
04:51:05.191  E  	/usr/local/go/src/runtime/cgocall.go:442 +0x21c fp=0x4000db5f30 sp=0x4000db5e60 pc=0x7b9aaeccdc
04:51:05.191  E  	/usr/local/go/src/runtime/cgocall.go:442 +0x21c fp=0x4000db5f30 sp=0x4000db5e60 pc=0x7b9aaeccdc
04:51:05.192  E  runtime.cgocallbackg(0x7b9b5a1e30, 0x7fdf1e57c4, 0x0)
04:51:05.192  E  runtime.cgocallbackg(0x7b9b5a1e30, 0x7fdf1e57c4, 0x0)
04:51:05.192  E  	/usr/local/go/src/runtime/cgocall.go:361 +0xf4 fp=0x4000db5f80 sp=0x4000db5f30 pc=0x7b9aaeca34
04:51:05.192  E  	/usr/local/go/src/runtime/cgocall.go:361 +0xf4 fp=0x4000db5f80 sp=0x4000db5f30 pc=0x7b9aaeca34
04:51:05.192  E  runtime.cgocallbackg(0x7b9b5a1e30, 0x7fdf1e57c4, 0x0)
04:51:05.192  E  runtime.cgocallbackg(0x7b9b5a1e30, 0x7fdf1e57c4, 0x0)
04:51:05.192  E  	<autogenerated>:1 +0x1c fp=0x4000db5fb0 sp=0x4000db5f80 pc=0x7b9ab65a7c
04:51:05.192  E  	<autogenerated>:1 +0x1c fp=0x4000db5fb0 sp=0x4000db5f80 pc=0x7b9ab65a7c
04:51:05.192  E  runtime.cgocallback(0x0, 0x0, 0x0)
04:51:05.192  E  runtime.cgocallback(0x0, 0x0, 0x0)
04:51:05.192  E  	/usr/local/go/src/runtime/asm_arm64.s:1131 +0xb0 fp=0x4000db5fe0 sp=0x4000db5fb0 pc=0x7b9ab639d0
04:51:05.192  E  	/usr/local/go/src/runtime/asm_arm64.s:1131 +0xb0 fp=0x4000db5fe0 sp=0x4000db5fb0 pc=0x7b9ab639d0
04:51:05.192  E  runtime.goexit({})
04:51:05.192  E  runtime.goexit({})
04:51:05.192  E  	/usr/local/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x4000db5fe0 sp=0x4000db5fe0 pc=0x7b9ab63ac4
04:51:05.192  E  	/usr/local/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x4000db5fe0 sp=0x4000db5fe0 pc=0x7b9ab63ac4
04:51:05.192  E  fatal error: runtime: stack split at bad time
04:51:05.192  E  fatal error: runtime: stack split at bad time

**Comment by 2dust** [comment]
https://github.com/golang/go/issues/68285
