### ISSUE TITLE
Change default user-agent 

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3751]
Hi

https://github.com/XTLS/Xray-core/pull/3884#issuecomment-2424381244

change default user-agent for ws, http, httpupgrade, splithttp 

https://github.com/GFW-knocker/MahsaNG/commit/3bcb9aa33ee1a446e83b6be259feed8de11607cd

add DNS cache in DoH

https://github.com/GFW-knocker/MahsaNG/commit/134bc67d585473aeb9aa4c6c4e64dc7405476ae2

before turn to kotlin

https://github.com/GFW-knocker/MahsaNG/commit/8c1a44ab36a5897541496ba48dd0da9d2342f489

add fragmentor java files

https://github.com/GFW-knocker/MahsaNG/commit/7ce471c56eb5db2a45bc1264ef84224fdf76828d

https://github.com/GFW-knocker/MahsaNG/commit/c6a890af372efe288f59a04606ec7e3b47b40404

Quote:
我可以建议 @2dust @yuhan6665 删除对明文 HTTP 订阅的支持，已私发给后者，同样，我相信他们会遵循安全建议

Dear 2dust, is it possible to run it?!

If anyone has anything to add to the Dependencies update, please do so.🙏

@2dust @CodeWithTamim

**Comment by vitalyster** [comment]
I see default "Go-http-client/1.1" for ws transport, how to change it?
