### ISSUE TITLE
Changed minimum SDK for v2rayNG API to Android 6.0 (API level 23) or higher.

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3753]
Hello friends
As you know, there is a minimum SDK. According to my search, Google ended support for Android 5 in Jul 11 2024, so it is better to upgrade at least v2rayNG support for Android 6.0 (API level 23) or higher. 

Reference:
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://developer.android.com/tools/releases/platforms&ved=2ahUKEwjb6tDQhKWJAxUe9rsIHWKJA2kQFnoECBAQAQ&usg=AOvVaw0jCKBpK1xQezGY8beqAERS

Footnote:
Updates to Google Play services are currently available for Android 6.0 (API level 23) or higher.

https://github.com/2dust/v2rayNG/pull/3757

 @2dust @CodeWithTamim

**Comment by codewithtamim** [comment]
Raising the minimum support to Android 6.0 (API level 23) makes sense, as Google ended support for Android 5.0 in July 2024, making it more vulnerable to security risks. However, if we want to keep the app running on Android 5.0, we can continue supporting it, but we should be aware of the potential risks and limitations.

**Comment by ghost** [comment]
> Raising the minimum support to Android 6.0 (API level 23) makes sense, as Google ended support for Android 5.0 in July 2024, making it more vulnerable to security risks. However, if we want to keep the app running on Android 5.0, we can continue supporting it, but we should be aware of the potential risks and limitations.

My opinion is subject to change, but we respect whatever decision they make in the end.

**Comment by 2dust** [comment]
can't just consider whether it's officially supported or not
