### ISSUE TITLE
Program coding upgrade

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3754]
Available Issue

https://www.codefactor.io/repository/github/2dust/v2rayng/issues/master

@2dust @CodeWithTamim

**Comment by codewithtamim** [comment]
> > Available Issue
> > https://www.codefactor.io/repository/github/2dust/v2rayng/file/master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/dto/V2rayConfig.kt
> > @2dust @CodeWithTamim
> 
> You had no opinion.?! @CodeWithTamim

check pr #3766
