### ISSUE TITLE
我在安卓10上无法使用socks5代理

### ISSUE THREAD

**Issue by whp98** [2dust/v2rayNG#378]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

访问google
### 实际行为
描述实际发生了什么
我是用这个不能访问google
### 复现方法
1.添加一个socks5代理
2.启动代理
3.打开google页面

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
日志我看了并没有明显的报错
```
</details>

### 环境信息
安卓10 miui11 黑鲨游戏手机2
### 额外信息（可选）

使用我的电脑上的v2ray是可以使用的安卓上使用
BifrostV也是很不错的
log我查看了，这个并不会报错，没啥明显的问题

**Comment by okudayukiko** [comment]
我也遇到同样问题，局域网的SOCKS5，Kitsunebi可以代理，V2RayNG不行

**Comment by whp98** [comment]
局域网连v2 pc的socks5代理是可以的

**Comment by whp98** [comment]
我是用链接的远程服务器的trojan客户端的socks5，应该不是trojan的问题，我用浏览器是没问题的

**Comment by 2dust** [comment]
ng默认已经开启了socks5，端口号在设置里面可以找到

**Comment by whp98** [comment]
不是吧 我不是这个意思 我要使用这个客户端连接一个socks5节点，结果发现添加结点之后并不能成功上网 节点 是这样的    socks5.xxxx.com  32000 也就是使用普通的socks节点上网

**Comment by QiangJony** [comment]
我也碰到了这个问题，同样的配置文件 kitsunebi 1.8.0 可以 ，ng 提示 io read/write on closed pipe

**Comment by whp98** [comment]
我建议使用glider转换协议之后用ss，纯socks5有点不安全

**Comment by QiangJony** [comment]
> 我建议使用glider转换协议之后用ss，纯socks5有点不安全

不考虑安全问题，Android 端 纯socks5 有参考实现方案和代码吗？谢谢

**Comment by whp98** [comment]
这个不知道，我了解的有一个BifrostV是支持纯socks5的，不过速度一般，没有ss速度快
