### ISSUE TITLE
貌似最新的1.9.8版本兼容有一点问题

### ISSUE THREAD

**Issue by AsuradaGo** [2dust/v2rayNG#3792]
一、遇到的问题
恢复出厂重置Android手机，顺手下载了最新的1.9.8版本安装并输入配置后，浏览器能够正常打开外网，Google play也能打开浏览应用详情页面，但点击安装应用，一直显示等待，最终无法下载

二、尝试排除方法
1、手机系统不变，都是Redmi手机，系统是澎湃os，之前一直正常用V2rayNG，排除了系统和手机问题；
2、第一次安装1.9.8版本无法正常下载Google play应用之后，本人再次恢复了出厂状态，仍然复现如上述（一）的问题；
3、重置Android系统里的网络设置、重置系统应用设置，无法解决；
4、检查v2rayNG客户端设置配置和服务器状态，都正常，排除；
5、最后，想到把移动sim卡换成联通sim卡，仍无果。

三、最终个人解决办法
最后，我翻箱倒柜找到最初下载的1.8.7版本，一安装和配置，立即一切正常了；且卸载后安装1.9.7版本，也是能够正常使用的。
综上，也就是说明，1.9.8版本及之前的版本，在Redmi（澎湃os）上都能正常使用

四、推测的原因
可能是Redmi 澎湃os的兼容问题，抑或是1.9.8版本的某个小问题影响

ps.小白非正式程序员一枚，提交的反馈比较凌乱，望见谅

**Comment by Asttear** [comment]
小米14与三星平板S10+均复现，应该是新版本的问题

**Comment by 2dust** [comment]
问题可能存在，但是看这些信息无法确认问题所在
1.8.7到1.9.7跨度太长，无法定位是哪里的问题

**Comment by VahidRafieiPour** [comment]
Yahoo Mail: Search, Organize, Conquer 
 
  On یکشنبه, اکتبر ۲۷, ۲۰۲۴ at ۲۲:۴۵, ***@***.***> wrote:   


一、遇到的问题
恢复出厂重置Android手机，顺手下载了最新的1.9.8版本安装并输入配置后，浏览器能够正常打开外网，Google play也能打开浏览应用详情页面，但点击安装应用，一直显示等待，最终无法下载

二、尝试排除方法
1、手机系统不变，都是Redmi手机，系统是澎湃os，之前一直正常用V2rayNG，排除了系统和手机问题；
2、第一次安装1.9.8版本无法正常下载Google play应用之后，本人再次恢复了出厂状态，仍然复现如上述（一）的问题；
3、重置Android系统里的网络设置、重置系统应用设置，无法解决；
4、检查v2rayNG客户端设置配置和服务器状态，都正常，排除；
5、最后，想到把移动sim卡换成联通sim卡，仍无果。

三、最终个人解决办法
最后，我翻箱倒柜找到最初下载的1.8.7版本，一安装和配置，立即一切正常了；且卸载后安装1.9.7版本，也是能够正常使用的。
综上，也就是说明，1.9.8版本及之前的版本，在Redmi（澎湃os）上都能正常使用

四、推测的原因
可能是Redmi 澎湃os的兼容问题，抑或是1.9.8版本的某个小问题影响

ps.小白非正式程序员一枚，提交的反馈比较凌乱，望见谅

**Comment by VahidRafieiPour** [comment]
***@***.***

Yahoo Mail: Search, Organize, Conquer 
 
  On یکشنبه, اکتبر ۲۷, ۲۰۲۴ at ۲۲:۴۵, ***@***.***> wrote:   


一、遇到的问题
恢复出厂重置Android手机，顺手下载了最新的1.9.8版本安装并输入配置后，浏览器能够正常打开外网，Google play也能打开浏览应用详情页面，但点击安装应用，一直显示等待，最终无法下载

二、尝试排除方法
1、手机系统不变，都是Redmi手机，系统是澎湃os，之前一直正常用V2rayNG，排除了系统和手机问题；
2、第一次安装1.9.8版本无法正常下载Google play应用之后，本人再次恢复了出厂状态，仍然复现如上述（一）的问题；
3、重置Android系统里的网络设置、重置系统应用设置，无法解决；
4、检查v2rayNG客户端设置配置和服务器状态，都正常，排除；
5、最后，想到把移动sim卡换成联通sim卡，仍无果。

三、最终个人解决办法
最后，我翻箱倒柜找到最初下载的1.8.7版本，一安装和配置，立即一切正常了；且卸载后安装1.9.7版本，也是能够正常使用的。
综上，也就是说明，1.9.8版本及之前的版本，在Redmi（澎湃os）上都能正常使用

四、推测的原因
可能是Redmi 澎湃os的兼容问题，抑或是1.9.8版本的某个小问题影响

ps.小白非正式程序员一枚，提交的反馈比较凌乱，望见谅

**Comment by VahidRafieiPour** [comment]
***@***.***

Yahoo Mail: Search, Organize, Conquer 
 
  On دوشنبه, اکتبر ۲۸, ۲۰۲۴ at ۴:۵۶, ***@***.******@***.***> wrote:   ***@***.***

Yahoo Mail: Search, Organize, Conquer 
 
  On یکشنبه, اکتبر ۲۷, ۲۰۲۴ at ۲۲:۴۵, ***@***.***> wrote:   


一、遇到的问题
恢复出厂重置Android手机，顺手下载了最新的1.9.8版本安装并输入配置后，浏览器能够正常打开外网，Google play也能打开浏览应用详情页面，但点击安装应用，一直显示等待，最终无法下载

二、尝试排除方法
1、手机系统不变，都是Redmi手机，系统是澎湃os，之前一直正常用V2rayNG，排除了系统和手机问题；
2、第一次安装1.9.8版本无法正常下载Google play应用之后，本人再次恢复了出厂状态，仍然复现如上述（一）的问题；
3、重置Android系统里的网络设置、重置系统应用设置，无法解决；
4、检查v2rayNG客户端设置配置和服务器状态，都正常，排除；
5、最后，想到把移动sim卡换成联通sim卡，仍无果。

三、最终个人解决办法
最后，我翻箱倒柜找到最初下载的1.8.7版本，一安装和配置，立即一切正常了；且卸载后安装1.9.7版本，也是能够正常使用的。
综上，也就是说明，1.9.8版本及之前的版本，在Redmi（澎湃os）上都能正常使用

四、推测的原因
可能是Redmi 澎湃os的兼容问题，抑或是1.9.8版本的某个小问题影响

ps.小白非正式程序员一枚，提交的反馈比较凌乱，望见谅

**Comment by chen-xiao-yu** [comment]
我的小米14，都装不了，老版本也不行。 说是安装包与系统不兼容
![Screenshot_2024-10-29-08-50-13-275_com miui packageinstaller](https://github.com/user-attachments/assets/c72e76a7-70be-436a-ba21-a28e391fe881)
![Screenshot_2024-10-29-08-49-59-794_com miui packageinstaller](https://github.com/user-attachments/assets/6c88c63b-d7cc-4a1e-891f-0893af8f88d7)
