### ISSUE TITLE
1.9.8新建订阅里的节点问题

### ISSUE THREAD

**Issue by lindberg0218** [2dust/v2rayNG#3793]
新建一个订阅，命名为A，然后复制粘贴的方法在该订阅里添加节点，所有节点都不可用，同样的节点在所有分组里，就是正常的，可用

#

### 日志信息

--------- beginning of crash
10-28 10:55:10.143 E/AndroidRuntime( 6389): FATAL EXCEPTION: main
10-28 10:55:10.143 E/AndroidRuntime( 6389): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 6389
10-28 10:55:10.143 E/AndroidRuntime( 6389): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{fedbcc2 u0 com.v2ray.ang/.service.V2RayVpnService c:com.v2ray.ang}
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2483)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2451)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2807)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.os.Looper.loopOnce(Looper.java:282)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.os.Looper.loop(Looper.java:387)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at android.app.ActivityThread.main(ActivityThread.java:9501)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at java.lang.reflect.Method.invoke(Native Method)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
10-28 10:55:10.143 E/AndroidRuntime( 6389): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)

**Comment by lindberg0218** [comment]
这是单独一个节点的测试

--------- beginning of main
10-28 13:54:56.154 I/GoLog   (14324): fdConn unix.Connect err, Close Fd: 127 Err: connection refused
10-28 13:54:57.576 I/GoLog   (14324): Not Using Prepared: tcp,[2a01:4f8:1c1b:7df::1]:443
10-28 13:54:57.895 I/GoLog   (14324): fdConn unix.Connect err, Close Fd: 127 Err: connection refused
10-28 13:54:58.386 I/GoLog   (14324): Not Using Prepared: tcp,[2a01:4f8:1c1b:7df::1]:443
10-28 13:54:58.713 I/GoLog   (14324): fdConn unix.Connect err, Close Fd: 127 Err: connection refused
10-28 13:54:59.743 W/com.v2ray.ang(13903): Cleared Reference was only reachable from finalizer (only reported once)
10-28 13:55:00.208 D/com.v2ray.ang(14324): realPing: go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: failed to parse to outbound detour config. > infra/conf: unknown config id: hysteria2
10-28 13:55:00.814 I/GoLog   (14324): from udp:127.0.0.1:56714 accepted udp:1.1.1.1:53 [socks -> proxy]
10-28 13:55:00.879 I/GoLog   (14324): Using Prepared: 183.240.196.236
10-28 13:55:04.854 D/com.v2ray.ang(14324): tun2socks destroy
10-28 13:55:04.854 I/tun2socks(16598): NOTICE(tun2socks): termination requested
10-28 13:55:04.854 I/tun2socks(16598): NOTICE(tun2socks): tearing down
10-28 13:55:04.854 I/tun2socks(16598): NOTICE(tun2socks): Free TCP connections
10-28 13:55:04.859 I/tun2socks(16598): NOTICE(tun2socks): exiting
10-28 13:55:04.867 D/com.v2ray.ang(14324): libtun2socks.so exited
10-28 13:55:04.879 D/com.v2ray.ang(14324): libhysteria2.so destroy
10-28 13:55:04.879 D/com.v2ray.ang(14324): kotlin.UninitializedPropertyAccessException: lateinit property procService has not been initialized
10-28 13:55:05.444 I/GoLog   (14324): loading core config
10-28 13:55:05.445 I/GoLog   (14324): Preparing Domain: 66.135.11.68:443
10-28 13:55:05.445 I/GoLog   (14324): Prepare Result:
10-28 13:55:05.445 I/GoLog   (14324):  Domain: 66.135.11.68
10-28 13:55:05.445 I/GoLog   (14324):  Port: 443
10-28 13:55:05.445 I/GoLog   (14324):  IPs: [66.135.11.68]
10-28 13:55:05.562 I/GoLog   (14324): infra/conf/serial: failed to parse json config > infra/conf: failed to parse to outbound detour config. > infra/conf: unknown config id: hysteria2
10-28 13:55:05.563 D/com.v2ray.ang(14324): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: failed to parse to outbound detour config. > infra/conf: unknown config id: hysteria2
10-28 13:55:09.381 I/GoLog   (14324): Not Using Prepared: tcp,91.107.232.209:32864
10-28 13:55:09.777 I/GoLog   (14324): Not Using Prepared: tcp,[2a01:4f8:1c1b:7df::1]:443
10-28 13:55:10.001 I/GoLog   (14324): fdConn unix.Connect err, Close Fd: 116 Err: connection refused

**Comment by 2dust** [comment]
你的这个分组是否设置了前置和落地代理？这个功能不支持hysteria2

**Comment by lindberg0218** [comment]
> 你的这个分组是否设置了前置和落地代理？这个功能不支持hysteria2

没有，就新建了订阅，除了名称都是空白，或者关闭状态

**Comment by 2dust** [comment]
能否发下配置？可以脱敏
