### ISSUE TITLE
1.9.8谷歌Play无法下载或更新应用

### ISSUE THREAD

**Issue by dashuaibi45678** [2dust/v2rayNG#3794]
在使用相同的节点和前后时间相差不久的情况下，clash meta可以在Play商店下载更新应用，但是在v2rayng 1.9.8版本下无法进行下载更新，降级到1.9.7下该节点又可以重新再Play商店下载更新应用了。

**Comment by dashuaibi45678** [comment]
其他应用例如nekobox，hiddify也是出现了无法再Play商店更新应用的问题

**Comment by 2dust** [comment]
1.9.8，你看下路由规则，有一条`Goole cn`，请拖动到最上面，重启试一试

**Comment by dashuaibi45678** [comment]
> 1.9.8，你看下路由规则，有一条`Goole cn`，请拖动到最上面，重启试一试

解决了，一开始在最终代理上一格，拖动到“绕过中国IP”和“绕过中国域名”之上后可以下载更新了。

**Comment by 2dust** [comment]
感谢反馈，已经修改了预设值
https://github.com/2dust/v2rayNG/releases/tag/1.9.9

**Comment by AsuradaGo** [comment]
> 1.9.8，你看下路由规则，有一条`Goole cn`，请拖动到最上面，重启试一试

大佬神速，几小时内就发出新版本了，666

**Comment by a7066593** [comment]
说个手机上解决的方法，在左上角settings 中，将Enable Sniffing 复选框取消勾选后，重新连接后解决了。
这个方法我也是找了好多帖子才找到的。。。不知道原理是啥。
