### ISSUE TITLE
Russia preset / Пресет для России

### ISSUE THREAD

**Issue by HuntezWOTB** [2dust/v2rayNG#3795]

**Comment by HuntezWOTB** [comment]
(RUSSIAN GUIDE)
v2rayNG (Андроид) — Пресет для России
Шаги по настройке:

1) Загрузите приложение: Скачайте последнюю версию v2rayNG из раздела Releases на GitHub (на момент написания — версия пре-релиз 1.9.9): https://github.com/2dust/v2rayNG
2) Скачайте файлы geoip.dat и geosite.dat: https://github.com/runetfreedom/russia-v2ray-rules-dat/releases
Эти файлы необходимы для маршрутизации. Загружайте их из этого репозитория, регулярно проверяя обновления:
GeoIP и Geosite файлы на GitHub
3) Запустите приложение и перейдите в раздел "Маршрутизация":
Откройте v2rayNG, нажмите на иконку меню в верхнем левом углу, и выберите "Маршрутизация".
4) Добавьте загруженные файлы георесурсов:
Нажмите на значок с тремя точками в верхнем правом углу, затем выберите "Файлы георесурсов".
Нажмите на кнопку "+" и выберите "Добавить файлы".
Загрузите ранее скачанные файлы geoip и geosite. Добавляйте их поочередно, порядок не важен.
Вернитесь в раздел "Маршрутизация":
После добавления файлов откройте этот раздел для настройки конфигурации.
5) Скопируйте и вставьте конфигурацию: Скопируйте предложенный ниже конфиг:

[{"domain":["geosite:category-ads-all"],"enabled":false,"looked":false,"outboundTag":"block","remarks":"RU-1 [Блокировка рекламы]"},{"enabled":false,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"RU-1 [Приватные сети напрямую]"},{"domain":["geosite:private"],"enabled":false,"looked":false,"outboundTag":"direct","remarks":"RU-1 [Приватные домены напрямую]"},{"enabled":false,"looked":false,"outboundTag":"proxy","port":"0-65535","remarks":"RU-1 [Остальное в прокси]"},{"enabled":false,"looked":false,"outboundTag":"direct","protocol":["bittorrent"],"remarks":"RU-2 [Торрент напрямую]"},{"domain":["geosite:category-ads-all"],"enabled":false,"looked":false,"outboundTag":"block","remarks":"RU-2 [Блокировка рекламы]"},{"enabled":false,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"RU-2 [Приватные сети напрямую]"},{"domain":["geosite:private"],"enabled":false,"looked":false,"outboundTag":"direct","remarks":"RU-2 [Приватные домены напрямую]"},{"enabled":false,"ip":["geoip:ru"],"looked":false,"outboundTag":"direct","remarks":"RU-2 [Доступные только в России напрямую]"},{"enabled":false,"looked":false,"outboundTag":"proxy","port":"0-65535","remarks":"RU-2 [Остальное в прокси]"},{"enabled":false,"looked":false,"outboundTag":"direct","protocol":["bittorrent"],"remarks":"RU-3 [Торрент напрямую]"},{"domain":["geosite:category-ads-all"],"enabled":false,"looked":false,"outboundTag":"block","remarks":"RU-3 [Блокировка рекламы]"},{"enabled":false,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"RU-3 [Приватные сети напрямую]"},{"domain":["geosite:private"],"enabled":false,"looked":false,"outboundTag":"direct","remarks":"RU-3 [Приватные домены напрямую]"},{"enabled":false,"ip":["1.0.0.1","1.1.1.1","8.8.8.8","8.8.4.4"],"looked":false,"outboundTag":"proxy","remarks":"RU-3 [DNS в прокси]"},{"enabled":false,"looked":false,"network":"udp","outboundTag":"proxy","port":"50000-65535","remarks":"RU-3 [Дискорд (Голосовой) в прокси]"},{"enabled":false,"ip":["geoip:ru-blocked"],"looked":false,"outboundTag":"proxy","remarks":"RU-3 [Заблокированные сети в прокси]"},{"domain":["geosite:ru-blocked"],"enabled":false,"looked":false,"outboundTag":"proxy","remarks":"RU-3 [Заблокированные домены в прокси]"},{"enabled":false,"looked":false,"outboundTag":"direct","port":"0-65535","remarks":"RU-3 [Остальное напрямую]"}]

6) Импортируйте конфигурацию:
Нажмите на значок с тремя точками в верхнем правом углу и выберите "Импорт правил из буфера обмена".
Подтвердите удаление существующих правил.
7) Измените доменную стратегию:
Измените "Доменная стратегия" с "AsIs" на "IPOnDemand".
8) Выбор режима работы:
Выберите один из трех режимов работы:

RU-1: Проксировать весь трафик.
RU-2: Проксировать все, кроме трафика из РФ.
RU-3: Проксировать только заблокированные ресурсы.

Важно: выбирайте только один из пресетов — RU-1, RU-2 или RU-3. Не включайте их одновременно или в комбинации друг с другом; активен должен быть только один пресет на выбор.

**Comment by 2dust** [comment]
wellcome pr

**Comment by ErMaKv666** [comment]
Не находит в этих dat файлах geoip:ru-blocked и geosite:ru-blocked. Журнал сообщает следующее:
11-13 00:07:29.503 I/GoLog   (28212): infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: ru-blocked > infra/conf: code not found in geoip.dat: RU-BLOCKED
11-13 00:07:29.503 D/com.v2ray.ang(28212): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: ru-blocked > infra/conf: code not found in geoip.dat: RU-BLOCKED

**Comment by VertaKhan** [comment]
Возможно кому то будет полезно:
Можно добавить ссылки вместо файлов, и обновлять георесурсы одной кнопкой из приложения.
Далее изменные шаги, все остальные без изменений.

- Пропускаем шаг 2
- На этапе 4 выбираем вместо  "Добавить файлы" - "Добавить URL" 

название (надо написать именно такое, с расширением) - ссылка:

- geoip.dat - https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/geoip.dat
- geosite.dat - https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/geosite.dat

Новые файлы должны заменить уже существующие, то есть там как было две позиции в списке, так должно и остаться.
Далее нажимаем на значок облака со скачиванием в правом верхнем углу, скачиваем и обновляем по мере необходимости.

**Comment by SignFinder** [comment]
> * geoip.dat - https://raw.githubusercontent.com/runetfreedom/russia-blocked-geoip/release/geoip.dat
> 
> * geosite.dat - https://raw.githubusercontent.com/runetfreedom/russia-blocked-geosite/release/geosite.dat

Здесь официальные под v2ray-n 
https://github.com/runetfreedom/russia-v2ray-rules-dat

**Comment by Phoenix-999** [comment]
FYI

https://github.com/2dust/v2rayNG/issues/4085#issuecomment-2544797629

**Comment by WeTUR** [comment]
А как использовать отдельные geoip файлы например: geosite:ru-blocked, geoip:ru-blocked?

**Comment by 4saw** [comment]
> (RUSSIAN GUIDE) v2rayNG (Андроид) — Пресет для России Шаги по настройке:
> 
> 1. Загрузите приложение: Скачайте последнюю версию v2rayNG из раздела Releases на GitHub (на момент написания — версия пре-релиз 1.9.9): https://github.com/2dust/v2rayNG
> 2. Скачайте файлы geoip.dat и geosite.dat: https://github.com/runetfreedom/russia-v2ray-rules-dat/releases
>    Эти файлы необходимы для маршрутизации. Загружайте их из этого репозитория, регулярно проверяя обновления:
>    GeoIP и Geosite файлы на GitHub
> 3. Запустите приложение и перейдите в раздел "Маршрутизация":
>    Откройте v2rayNG, нажмите на иконку меню в верхнем левом углу, и выберите "Маршрутизация".
> 4. Добавьте загруженные файлы георесурсов:
>    Нажмите на значок с тремя точками в верхнем правом углу, затем выберите "Файлы георесурсов".
>    Нажмите на кнопку "+" и выберите "Добавить файлы".
>    Загрузите ранее скачанные файлы geoip и geosite. Добавляйте их поочередно, порядок не важен.
>    Вернитесь в раздел "Маршрутизация":
>    После добавления файлов откройте этот раздел для настройки конфигурации.
> 5. Скопируйте и вставьте конфигурацию: Скопируйте предложенный ниже конфиг:
> 
> [{"domain":["geosite:category-ads-all"],"enabled":false,"looked":false,"outboundTag":"block","remarks":"RU-1 [Блокировка рекламы]"},{"enabled":false,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"RU-1 [Приватные сети напрямую]"},{"domain":["geosite:private"],"enabled":false,"looked":false,"outboundTag":"direct","remarks":"RU-1 [Приватные домены напрямую]"},{"enabled":false,"looked":false,"outboundTag":"proxy","port":"0-65535","remarks":"RU-1 [Остальное в прокси]"},{"enabled":false,"looked":false,"outboundTag":"direct","protocol":["bittorrent"],"remarks":"RU-2 [Торрент напрямую]"},{"domain":["geosite:category-ads-all"],"enabled":false,"looked":false,"outboundTag":"block","remarks":"RU-2 [Блокировка рекламы]"},{"enabled":false,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"RU-2 [Приватные сети напрямую]"},{"domain":["geosite:private"],"enabled":false,"looked":false,"outboundTag":"direct","remarks":"RU-2 [Приватные домены напрямую]"},{"enabled":false,"ip":["geoip:ru"],"looked":false,"outboundTag":"direct","remarks":"RU-2 [Доступные только в России напрямую]"},{"enabled":false,"looked":false,"outboundTag":"proxy","port":"0-65535","remarks":"RU-2 [Остальное в прокси]"},{"enabled":false,"looked":false,"outboundTag":"direct","protocol":["bittorrent"],"remarks":"RU-3 [Торрент напрямую]"},{"domain":["geosite:category-ads-all"],"enabled":false,"looked":false,"outboundTag":"block","remarks":"RU-3 [Блокировка рекламы]"},{"enabled":false,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"RU-3 [Приватные сети напрямую]"},{"domain":["geosite:private"],"enabled":false,"looked":false,"outboundTag":"direct","remarks":"RU-3 [Приватные домены напрямую]"},{"enabled":false,"ip":["1.0.0.1","1.1.1.1","8.8.8.8","8.8.4.4"],"looked":false,"outboundTag":"proxy","remarks":"RU-3 [DNS в прокси]"},{"enabled":false,"looked":false,"network":"udp","outboundTag":"proxy","port":"50000-65535","remarks":"RU-3 [Дискорд (Голосовой) в прокси]"},{"enabled":false,"ip":["geoip:ru-blocked"],"looked":false,"outboundTag":"proxy","remarks":"RU-3 [Заблокированные сети в прокси]"},{"domain":["geosite:ru-blocked"],"enabled":false,"looked":false,"outboundTag":"proxy","remarks":"RU-3 [Заблокированные домены в прокси]"},{"enabled":false,"looked":false,"outboundTag":"direct","port":"0-65535","remarks":"RU-3 [Остальное напрямую]"}]
> 
> 6. Импортируйте конфигурацию:
>    Нажмите на значок с тремя точками в верхнем правом углу и выберите "Импорт правил из буфера обмена".
>    Подтвердите удаление существующих правил.
> 7. Измените доменную стратегию:
>    Измените "Доменная стратегия" с "AsIs" на "IPOnDemand".
> 8. Выбор режима работы:
>    Выберите один из трех режимов работы:
> 
> RU-1: Проксировать весь трафик. RU-2: Проксировать все, кроме трафика из РФ. RU-3: Проксировать только заблокированные ресурсы.
> 
> Важно: выбирайте только один из пресетов — RU-1, RU-2 или RU-3. Не включайте их одновременно или в комбинации друг с другом; активен должен быть только один пресет на выбор.

Почему в проге по умолчанию не появляются русские списки?

**Comment by yelloduxx** [comment]
Ничего против не имею, но я спросил у Gemini 3 pro про этот конфиг и он мне выдал следующее. Прошу покритиковать.

Я провел **критический технический анализ** конфигурации, предложенной пользователем HuntezWOTB в Issue #3795.

Мой вердикт: **Конфиг рабочий, но «тяжелый» и перестраховочный.** Автор пошел по пути «грубой силы», чтобы гарантированно работало у всех новичков, пожертвовав производительностью и приватностью DNS-запросов.

Вот подробный разбор его настроек (режим **RU-3**) и почему я советовал иначе:

### 1. Стратегия `IPOnDemand` (как в гайде) против `IPIfNonMatch` (мой совет)

*   **В гайде (`IPOnDemand`):** Эта настройка заставляет телефон **сначала** делать DNS-запрос к каждому сайту (превращать `yandex.ru` в цифры `77.88.55.77`), и только потом проверять правила.
    *   *Плюс:* Это надежно ловит блокировки по IP, даже если домена нет в списке.
    *   *Минус:* Вы «светите» DNS-запросами своему провайдеру (если не настроен DoH), и вы теряете 50–200 мс на каждом открытии страницы, ожидая ответа DNS.
*   **Мой совет (`IPIfNonMatch`):** Сначала проверяет текст домена.
    *   *Плюс:* Если сайт в списке, он уходит в прокси мгновенно, без DNS-запроса. Это быстрее и скрытнее.

### 2. Порядок правил: почему у него `GeoIP` выше?

В конфиге с Гитхаба:
1.  `geoip:ru-blocked` (IP-адреса) — В прокси
2.  `geosite:ru-blocked` (Домены) — В прокси

**Почему он так сделал?**
Так как он включил стратегию `IPOnDemand`, телефон **уже** потратил время и вычислил IP-адрес сайта. Раз IP уже на руках, автору логичнее проверить его первым. Это согласуется с его стратегией, но сама стратегия — медленная.

### 3. Что в его конфиге ХОРОШО (стоит оставить)

В пресете есть полезные правила, которых не было в вашем вопросе, но их стоит добавить:
*   **Правило для Discord:**
    `network: udp, port: 50000-65535` -> **Proxy**.
    *Это критически важно.* Голосовая связь в Discord часто идет по UDP на высоких портах. Без этого правила чат будет работать, а голос — нет.
*   **Блокировка рекламы:**
    `domain: geosite:category-ads-all` -> **Block**.
    Это встроенная резалка рекламы. Полезно, если вы не используете отдельный блокировщик.

### 4. Что в его конфиге СПОРНО

*   **Правило для DNS:**
    `ip: 1.1.1.1, 8.8.8.8` -> **Proxy**.
    Он жестко заворачивает популярные DNS-серверы в прокси. Если вы используете их на телефоне, ваши запросы пойдут через заграницу.
    *   Для заблокированных сайтов — это хорошо.
    *   Для Яндекса/Кинопоиска — это плохо (CDN могут решить, что вы в Европе, и скорость скачивания упадет).

### Итоговый вердикт: Что делать вам?

У вас есть два пути.

**Путь 1: «Сделать как в гайде» (Простой, но медленный)**
Если вы просто скопируете его конфиг, у вас всё заработает. Вы не заметите проблем, если у вас быстрый интернет, но батарея будет уходить чуть быстрее из-за постоянного резолвинга DNS.

**Путь 2: «Сделать профессионально» (Оптимизированный)**
Смешайте мой подход и его полезные фишки.

Настройте правила в таком порядке:
1.  **Блокировка рекламы** (если нужно) -> `Block`
2.  **Discord (голос)**: `udp` порты `50000-65535` -> `Proxy` *(взято из гайда)*
3.  **Заблокированные ДОМЕНЫ**: `geosite:ru-blocked` -> `Proxy` *(Мой совет: ставим выше)*
4.  **Заблокированные IP**: `geoip:ru-blocked` -> `Proxy`
5.  **Остальное**: `port: 0-65535` -> `Direct`

И обязательно поставьте стратегию **`IPIfNonMatch`**.

Это даст вам скорость открытия российских сайтов (без лишних DNS-запросов) и работающий голосовой чат Discord.

Источники

**Comment by novikovpashka** [comment]
> Ничего против не имею, но я спросил у Gemini 3 pro про этот конфиг и он мне выдал следующее. Прошу покритиковать.

Ничего против не имею, но я попросил покритиковать chat gpt 5.2 и он мне выдал следующее.

Спасибо за разбор, в целом он выглядит продуманным и полезным, особенно для тех, кто хочет понять логику конфига, а не просто скопировать его.
Несколько замечаний и уточнений:
IPOnDemand vs IPIfNonMatch
Ты корректно описал различие стратегий, но формулировки местами выглядят слишком категорично. IPOnDemand действительно может добавлять задержку из-за раннего DNS-резолвинга, однако величина задержки сильно зависит от кеша, используемого DNS и реализации клиента. Для части пользователей разница будет минимальной, особенно при включённом DoH.
Приватность DNS-запросов
Утверждение про «светите DNS провайдеру» справедливо только при отсутствии DoH/DoT. Во многих клиентах DoH включён по умолчанию, поэтому здесь, скорее, вопрос корректной настройки, а не inherent-проблема стратегии IPOnDemand.
Порядок GeoIP / geosite
Пояснение, почему GeoIP стоит выше при IPOnDemand, логичное. В этом контексте порядок правил не является ошибкой — он просто оптимизирован под выбранную стратегию. Возможно, стоит явно подчеркнуть, что это осознанный выбор, а не технический недостаток.
Проксирование DNS (1.1.1.1 / 8.8.8.8)
Замечание валидное, но и здесь всё зависит от сценария. Да, это может негативно влиять на CDN-локализацию для российских сервисов, но при этом повышает предсказуемость резолвинга и устойчивость к блокировкам. Это скорее design decision, чем спорная настройка сама по себе.
Итоговые рекомендации
Предложенный тобой вариант с IPIfNonMatch и приоритетом доменных правил действительно выглядит более оптимизированным для опытных пользователей. Возможно, стоит обозначить это именно как альтернативу для тех, кто понимает, что и зачем он меняет, а не как «правильный» и «неправильный» подходы.

**Comment by NGVTN35** [comment]
Пожалуйста помогите удалить geoip и geosite с телефона, множество способов пробовал все равно не получается

**Comment by bytapok** [comment]
Здравствуйте, очень далек от темы ВПН, возникла такая проблема, после запуска спустя пару минут возникает такая ошибка и впн перестает работать

![Image](https://github.com/user-attachments/assets/60dab9de-7b77-40e1-b524-9b503fec1396)

На телефоне этот же конфиг работает нормально, но на пк такая вот фигня
