### ISSUE TITLE
v1.9.9编译提示不兼容

### ISSUE THREAD

**Issue by guodf** [2dust/v2rayNG#3797]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 实际行为
![image](https://github.com/user-attachments/assets/27941dc5-c1d4-4d9c-b51c-7ae2a2c459e6)

### 复现方法
1.  使用tag：1.9.9

### 环境信息

使用android-studio-2024.1.2.12-windows.exe

**Comment by ghost** [comment]
> 在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
> 
> ### 预期行为
> ### 实际行为
> ![image](https://private-user-images.githubusercontent.com/7540349/380657229-27941dc5-c1d4-4d9c-b51c-7ae2a2c459e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjQwOTQsIm5iZiI6MTczMDEyMzc5NCwicGF0aCI6Ii83NTQwMzQ5LzM4MDY1NzIyOS0yNzk0MWRjNS1jMWQ0LTRkOWMtYjUxYy03YWUyYTJjNDU5ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTM1NjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJhMmM3ZTAxZWM3ZGM3MjY0OGFjYWVkOTU1NzQyOThjNDQ4ZTg3OTViMmUwZjMxY2U0YjM0NGE5NzZjMWM5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lMAZeGo82Kqc3JbyO_d-PZGszzoBFFjEFLF-rImLilk)
> 
> ### 复现方法
> 1. 使用tag：1.9.9
> 
> ### 日志信息
> ### 环境信息
> 使用android-studio-2024.1.2.12-windows.exe

Hi 

Read the reference lnks  below 

https://github.com/nightscout/AndroidAPS/issues/3489#issuecomment-2435504627

https://mvnrepository.com/artifact/com.android.tools.build/gradle
