### ISSUE TITLE
关于路由模式汇总(Routing mode summary)

### ISSUE THREAD

**Issue by 2dust** [2dust/v2rayNG#38]
很多关于路由的问题,做一个总结
 1.android系统vpn可以绑定app,所以第一个开启是分应用代理,并设置好
 2.这个app需要部分走代理,启用路由的绕过大陆,可以尝试开启本地dns
 3.浏览器可以安装两个,一个代理,一个不代理
 4.如果123不能解决你的问题,只能换个代理app了
 
 v2rayNG设计时尽力简化设置和使用,所以那些复杂的规则设置是永远不会做的
 只有ios这种无法分应用的系统才会使用规则

**Comment by 2dust** [comment]
PAC也是分流,也是不会支持的

**Comment by deadlineOvO** [comment]
也就是说不会出现类似 gfwlist/大陆常见域名 之类的代理模式？

**Comment by xianren78** [comment]
ng本身还有个自带的默认自定义路由模式，已经非常完善了。我也认同那些规则只适用于iOS，实际用于ng时，并没有多少意义。

**Comment by CharlesLocke** [comment]
又是设置分应用，又是安装俩浏览器的。感觉不如添加一个gfwlist路由更方便吧。况且似乎绕过局域网和大陆以及本地dns没效果。

**Comment by joexzh** [comment]
绕过大陆比全局快，但又明显比直连慢

**Comment by FFFcat** [comment]
我在服务器上设置了ban国内域名和国内IP，电脑和iOS端测试百度都打不开，然后用v2rayNG可以打开，百度里搜IP是服务器IP，均开全局。真的很神奇，客户端绕过服务端？补充一下NG对cn域名是全ban了。

**Comment by hldh214** [comment]
请问一下, 设置了分应用代理, 但是没起效是咋回事
比如我没勾选 chrome, 但是实际上 chrome 还是会走代理

**Comment by oO0oO0oO0o0o00** [comment]
> 我在服务器上设置了ban国内域名和国内IP，电脑和iOS端测试百度都打不开，然后用v2rayNG可以打开，百度里搜IP是服务器IP，均开全局。真的很神奇，客户端绕过服务端？补充一下NG对cn域名是全ban了。

好像是安卓vpn拿不到域名，只有ip，发送到服务器也只有ip。试试那个什么override从流量中还原域名。
Chrome + Chrome Dev / Yandex它不香吗

**Comment by FFFcat** [comment]
> > 我在服务器上设置了ban国内域名和国内IP，电脑和iOS端测试百度都打不开，然后用v2rayNG可以打开，百度里搜IP是服务器IP，均开全局。真的很神奇，客户端绕过服务端？补充一下NG对cn域名是全ban了。
> 
> 好像是安卓vpn拿不到域名，只有ip，发送到服务器也只有ip。试试那个什么override从流量中还原域名。
> Chrome + Chrome Dev / Yandex它不香吗

嗯，我之前加了这个就好了…很神奇

**Comment by xinxijishuwyq** [comment]
在不开启本地dns的情况下通常会出现许多问题。能否考虑修改为默认情况下是开启的。

**Comment by NewUserHa** [comment]
假如 绕过无用, 提议移除选项消误会.

**Comment by oO0oO0oO0o0o00** [comment]
> 假如 绕过无用, 提议移除选项消误会.

何种意义的无用？

1. 不开dns覆盖，按域名绕没用，否则半残
2. 按ip段总是有用，但不可靠，不一定对应实际地区

**Comment by NewUserHa** [comment]
>2.这个app需要部分走代理,启用路由的绕过大陆,可以尝试开启本地dns

>在不开启本地dns的情况下通常会出现许多问题。能否考虑修改为默认情况下是开启的。

> 启用本地DNS: DNS由本地设备的..处理 (同时(会)设置..绕过..)
或上选项和该指不同路由?

或 默认本地dns 或 添一两句注释 消除误会.

**Comment by txyyh** [comment]
问题在于分应用代理很容易出问题。。。比如本人魔趣，启用后就跟断网了差不多

**Comment by HiXiJu** [comment]
现在已经有很多成熟的规则可以直接订阅，顺带还能附赠拦广告功能
就比如ssr的acl，放弃着实可惜

**Comment by cryyin** [comment]
问题是我安两个浏览器不比用规则麻烦多了，分应用还老出问题，再者了需要简化的都用现成的app了谁会用节点啊，人家一键不比用v2ray简单

**Comment by dukong** [comment]
V2RayNG v1.6.28中的自定义规则和预定义规则的关系是？
前者覆盖后者？
前者and后者？
还是其他什么关系？
