### ISSUE TITLE
节点排序问题

### ISSUE THREAD

**Issue by GoodLisa01** [2dust/v2rayNG#3807]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
我将手动将导入的节点排了一下顺序，比如之前是1-3-2，现在排成3-2-1
### 实际行为
描述实际发生了什么
排好之后是3-2-1，但最小化之后再打开又变成了1-3-2了
### 复现方法
1.每次最小话之后，再打开就恢复到了原状
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
应该是增加分组之后产生的bug，你在全部里面操作应该正常
等修复
