### ISSUE TITLE
(Android)设置相关“路由规则”似乎不能让“bittorrent协议”直连（新建并配置规则“protocol:bittorrent,bittorrent”为“direct”并置顶该规则）

### ISSUE THREAD

**Issue by luis1111111111** [2dust/v2rayNG#3809]
(Android)

### 预期行为
设置相关"路由规则"，V2rayNG应该让“bittorrent协议”直连

### 实际行为
V2rayNG似乎没有正确对“bittorrent协议”进行分流

### 复现方法
![4103501](https://github.com/user-attachments/assets/27b5b524-6afb-44a1-9b88-ad0e8288cf59)

1. 如图，新建一条规则，在“protocol”下方空格内填入“protocol:bittorrent,bittorrent”，配置"outboundTag"为“direct”，点界面右上"对号"图标保存该规则，在规则表置顶该规则（也试过了只填“protocol:bittorent”或"bittorrent"后分别测试）；
2. Android"系统VPN设置"开启"Always-on VPN"和"Block connections without VPN"，确认无其他下载存在，使用BT软件进行下载；
3. 观察V2rayNG在通知栏显示的下载速度和BT软件显示的下载速度，对比两个速度，两者基本一致；
4. 另外，如果启用V2rayNG的“Per-APP proxy”和"bypass mode"并选择V2rayNG，在Android"系统VPN设置"关闭“Block connections without VPN”，再进行BT下载，BT软件显示正常下载速度，通知栏V2rayNG显示无下载速度，此时”系统VPN设置“启用“Block connections without VPN”则BT软件立即显示无速度。

（如此看来，“路由规则”功能不正常，“Per-APP proxy”功能正常）

### 环境信息

V2rayNG 1.9.8 (Google Play最新版本)

**Comment by dyhkwong** [comment]
v2ray/xray 的 bittorrent 嗅探功能本来就不能正常工作。原始的 BitTorrent 协议嗅探可能是正常的，但是据说 uTP 嗅探并不能正常工作，也没有去嗅探 DHT。

**Comment by 2dust** [comment]
应该是这样的
建议直接用分应用代理模式，不选bittorrent 相关应用
