### ISSUE TITLE
无法访问国内软件

### ISSUE THREAD

**Issue by AlaG0852** [2dust/v2rayNG#3812]
之前更新使用的1.9.9版本，经常出现节点在其他软件可以使用但是在v2rayNG里所有节点测速失败或者仅有一两个可以使用的情况

之后退回到1.8.5版本，节点大部分可以正常使用，因为有使用异地ip的需求，但是出现国内软件连不上网的情况，尝试了一下其他问题里的解决办法好像还是不行，这种情况应该如何解决呢（之前使用1.8.X忘记具体几了是可以正常使用国内软件的，1.9.X的版本虽然网速慢但是也可以正常使用柜内软件的）

**Comment by 2dust** [comment]
全新安装一次1.9.9版本，

**Comment by AlaG0852** [comment]
> 全新安装一次1.9.9版本，

更新完所有节点测速失败，不知道需不需要提供什么截图之类的以方便解决这个问题呢
<img width="116" alt="0101" src="https://github.com/user-attachments/assets/ceaae387-3a65-4c48-9762-bcf1df92926a">

**Comment by AlaG0852** [comment]
随机抽了1.8.15安装了也是所有测速失败，又安装了1.8.5才测速正常

**Comment by AlaG0852** [comment]
随机抽了1.8.15安装了也是所有测速失败，又安装了1.8.5才测速正常，但是国内软件还是不能使用

**Comment by 2dust** [comment]
你开分应用吧，这样国内软件就不会走vpn了

**Comment by AlaG0852** [comment]
> 你开分应用吧，这样国内软件就不会走vpn了

但是想国内软件走海外ip呢

**Comment by 2dust** [comment]
那就把你的国内软件在分应用中选中就行了
