### ISSUE TITLE
1.9.9 内存占用异常 启动速度慢

### ISSUE THREAD

**Issue by lyrnya** [2dust/v2rayNG#3816]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
节点无问题，使用其他软件并不会出现内存占用异常
第一次使用v2rayng 查看issue区发现曾经出现过 启动慢 测试真连接占用大量ram的情况[#306](https://github.com/2dust/v2rayNG/issues/306)

### 预期行为
描述你认为应该发生什么
在不杀死v2rayng的情况下，多次测试真连接或者多次开关节点情况下内存占用正常，启动速度正常

### 实际行为
描述实际发生了什么
在不杀死v2rayng的情况下，多次测试真连接或者多次开关节点情况下内存占用异常，并且v2rayng开启节点的时间大幅增加。强行停止v2rayng后开启节点需要4s，内存占用异常后开启连接需要10-15s
![Screenshot_20241101-085627_Trebuchet](https://github.com/user-attachments/assets/f407af5c-fd8d-4632-9feb-86f078eae97d)

### 复现方法
1.强行停止v2rayng
2.打开scene进程管理
3.多次进行节点真连接测试 或者 多次开关节点
4.可以看到v2rayng的daemon进程内存占用逐渐增加，且无法自行减少
5.后期内存占用异常后，开启节点的时间也会大幅度增加
6.强行停止v2rayng后恢复正常
7.重复上述操作，内存占用依旧异常，测试过3次，100%复现

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
LineageOS21 Android14
v2rayng 1.9.9

### 额外信息（可选）
并不是短时间进行多次连接或多次真连接测试会出现问题，正常使用下开关节点次数上来也会异常

**Comment by lyrnya** [comment]
更新过geo文件，那我试试静置1小时

**Comment by lyrnya** [comment]
1.9.9清除数据不更新geo，现在内存占用没那么大了，启动速度也正常了。
继续测试看看会不会回落

**Comment by lyrnya** [comment]
![Screenshot_20241101-132226_v2rayNG](https://github.com/user-attachments/assets/78e49e00-b8eb-423a-a3c9-0198fea733d6)
![Screenshot_20241101-133149_Scene](https://github.com/user-attachments/assets/d082ef73-e610-4ba8-bb19-4d1fd80b377d)
确实会自动变小

**Comment by 2dust** [comment]
本app新安装时的geo文件是比较小的，在app内更新geo则会下载最大最全的版本，这个时候会比较占用内存和启动慢。
如果你平时都是用分应用模式，可以不用更新geo，因为这个时候很少用到路由规则

**Comment by Kissycat** [comment]
QAQ, 最新版更新geo文件后也还是会占用1G运存，看来重写内核确实有所必要

![Image](https://github.com/user-attachments/assets/988d25aa-4a57-45de-b327-997be8a5384b)

**Comment by lyrnya** [comment]
> QAQ, 最新版更新geo文件后也还是会占用1G运存，看来重写内核确实有所必要
> 
> ![Image](https://github.com/user-attachments/assets/988d25aa-4a57-45de-b327-997be8a5384b)

![Image](https://github.com/user-attachments/assets/08e39d90-8321-482a-8b7f-a16f31985519)
可以尝试将geo文件更换成小的，应该会有所改善，我目前没有安装Scene所以不清楚内存占用情况如何，不过多次启动速度基本没有减慢
geoip https://cdn.jsdelivr.net/gh/v2fly/geoip@release/geoip-only-cn-private.dat
geosite https://cdn.jsdelivr.net/gh/v2fly/domain-list-community@release/dlc.dat
