### ISSUE TITLE
建议为国内DNS添加skipFallBack选项

### ISSUE THREAD

**Issue by Fangliding** [2dust/v2rayNG#3824]
在开启IPv6的时候会有如下问题
睿智ray的处理流程是 如果DNS查询没有结果 尝试fallback查询 假设这样一个场景
解析一个不存在AAAA记录的外国域名 比如 pixiv.net
浏览器查询试图查询AAAA 核心尝试通过国外DNS查询AAAA 很不幸它没找到ipv6
这时候它会fallback到国内DNS 到这一步其实就产生DNS泄露了（虽然也是问题不过 不是重点） 国内DNS回复了 但是回复的是一个被污染的ipv6 更不幸的是 它有一个expected ip:cn 导致这个请求被打回去 这样这个请求会无限卡住无法处理直至超时 造成性能问题也造成DNS泄露
解决办法：给国内的DNS加一行 `"skipFallback": true` 即可 几行代码的事
急速复现：开启ipv6的情况下 dig pixiv.net AAAA 会卡住

晚上躺床上看手机发现加载速度不对越想越不对然后爬起来打开电脑测试的

**Comment by 2dust** [comment]
这样是否可以？没有测试过
https://github.com/2dust/v2rayNG/commit/9c92fdc2573530523cfa70af7efb46990cf00d35
