### ISSUE TITLE
[实用特性] 分组中增加未分组节点的分组选项卡

### ISSUE THREAD

**Issue by moe-rgb** [2dust/v2rayNG#3826]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
能否增加一个分组专门存放单独导入的节点，即未分组节点的分组。

### 实际行为
单独导入的节点，在更新几个订阅连接后，位置会被顶到后边，且容易划半天且找不到。

### 复现方法
1.如上
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
你可以新建立一个组叫做未分组，然后把你的单独点放进去即可，和用代码实现的效果是一样
