### ISSUE TITLE
crash auto switch

### ISSUE THREAD

**Issue by farzadkamali20** [2dust/v2rayNG#3831]
你好，我想添加自动切换功能。这样，如果一台服务器出现故障并且无法 ping 通，它将转到下一台服务器。
我在每次自动切换之间间隔了大约 0.5 到 1 秒。

一切正常，但问题是，如果连续 20-30 个服务器不 ping，应用程序就会崩溃。出现的错误如下：

`Cmdline: com.*.*:RunSoLibV2RayDaemon`
`pid: 20000, tid: 20154, name: Thread-18  >>> com.*.*:RunSoLibV2RayDaemon <<<`
`      #00 pc 000000000053df48  /data/app/~~eUPr5_M9hbVEg0iPVUTLhA==/com.*.*-aMwp9uXgZwcsCXoGi7hriA==/lib/arm64/libgojni.so`

`report:open miev fail, EventId 901001003 -t 1730560852 -paraList {"CrashType":"100000000","CurrentTime":1730560851000,"Digest":"0f8f49f88a2de71fde5ceef3bc6ad9f6","Keyword":"{\"vn\":\"\",\"vc\":\"\",\"isRoot\":false,\"count\":1,\"preInstalled\":false,\"unfold\":false}","PackageName":"com.*.*:RunSoLibV2RayDaemon","Stacktrace":"Build fingerprint: 'Redmi/xun_global/xun:14/UKQ1.231003.002/V816.0.4.0.UMUMIXM:user/release-keys'##Revision: '0'##ABI: 'arm64'##Process uptime: 123s##Cmdline: com.*.*:RunSoLibV2RayDaemon##pid: 20000, tid: 20154, name: Thread-18  >>> com.*.*:RunSoLibV2RayDaemon <<<##uid: 10338##tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)##signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------##    x0  0000000000000000  x1  0000000000004eba  x2  0000000000000006  x3  0000000000000008##    x4  0000000000000001  x5  0000000000000002  x6  0000000000000000  x7  0000000000000000##    x8  0000000000000083  x9  000000000000001f  x10 0000000000000000  x11 0000007eec907038##
`

我还从应用程序中下面的链接添加了 libv2ray.aar 文件
[https://github.com/2dust/AndroidLibXrayLite/releases/tag/v24.10.5](url)

然后有时我会收到以下错误 (此错误有时会发生，并且不是永久性的)：
`java.lang.SecurityException: Unable to start service Intent { cmp=com.*.*/.v2ray.service.V2RayVpnService }: Unable to launch app com.*.*/10338 for service Intent { cmp=com.*.*/.v2ray.service.V2RayVpnService }: process is bad`

虽然我在清单中添加了该服务的所有必要权限 : 

![Screenshot 2024-11-02 190954](https://github.com/user-attachments/assets/9b6e3b65-6900-49a1-ac4e-699e06e5a05e)

**Comment by codewithtamim** [comment]
Send a video

**Comment by 2dust** [comment]
请发代码

**Comment by xiaoming007** [comment]
SecurityException 我也有同样的问题，通过观察，发生这个问题都是小米系统，android版本是13或者14
