### ISSUE TITLE
开启后报“无法取得权限”

### ISSUE THREAD

**Issue by hzexe** [2dust/v2rayNG#3832]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
不报这个错误的

### 实际行为
类似toast的消息弹出   “无法取得权限”   ，然后连接梯子后，点击测试，还是通的，可以反应出延时，但分应用勾选的应用无法走代理。

### 复现方法
1.红米K40，,android 13, xiaomi hyperos 1.0.6.0.tkhcnxm版本
2.使用google play升级的v2rayNG v1.9.9版本
3.系统的应用权限，全部都给了

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of main
11-03 00:05:03.606 E/com.v2ray.ang(30816): Not starting debugger since process cannot load the jdwp agent.
11-03 00:05:03.611 W/System.err(30816): android.system.ErrnoException: open failed: ENOENT (No such file or directory)
11-03 00:05:03.611 W/System.err(30816): 	at libcore.io.Linux.open(Native Method)
11-03 00:05:03.611 W/System.err(30816): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
11-03 00:05:03.611 W/System.err(30816): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
11-03 00:05:03.611 W/System.err(30816): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
11-03 00:05:03.611 W/System.err(30816): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8381)
11-03 00:05:03.611 W/System.err(30816): 	at android.system.Os.open(Os.java:494)
11-03 00:05:03.611 W/System.err(30816): 	at android.os.perfdebug.PerfDebugMonitorImpl.monitorVersionControl(PerfDebugMonitorImpl.java:206)
11-03 00:05:03.611 W/System.err(30816): 	at android.os.perfdebug.PerfDebugMonitorImpl.prepareMonitor(PerfDebugMonitorImpl.java:187)
11-03 00:05:03.611 W/System.err(30816): 	at android.app.ActivityThread.main(ActivityThread.java:8468)
11-03 00:05:03.611 W/System.err(30816): 	at java.lang.reflect.Method.invoke(Native Method)
11-03 00:05:03.611 W/System.err(30816): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
11-03 00:05:03.611 W/System.err(30816): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
11-03 00:05:03.639 W/com.v2ray.ang(30816): Entry not found
11-03 00:05:03.639 W/com.v2ray.ang(30816): Entry not found
11-03 00:05:03.639 W/com.v2ray.ang(30816): Entry not found
11-03 00:05:03.641 W/com.v2ray.ang(30816): JIT profile information will not be recorded: profile file does not exist.
11-03 00:05:03.641 W/com.v2ray.ang(30816): JIT profile information will not be recorded: profile file does not exist.
11-03 00:05:03.641 W/com.v2ray.ang(30816): JIT profile information will not be recorded: profile file does not exist.
11-03 00:05:03.651 D/com.v2ray.ang(30816): JNI_OnLoad success
11-03 00:05:03.787 D/com.v2ray.ang(30816): MiuiProcessManagerServiceStub setSchedFifo
```
</details>

### 环境信息
1.红米K40，,android 13, xiaomi hyperos 1.0.6.0.tkhcnxm版本
2.使用google play升级的v2rayNG v1.9.9版本
3.系统的应用权限，全部都给了

### 额外信息（可选）

似乎
https://github.com/2dust/v2rayNG/issues/2247
这个问题在某些情况下死灰复燃了?

**Comment by 2dust** [comment]
请截图

**Comment by Char-CN** [comment]
> 请截图

我的也是1.9.9，小米15pro，就是软件下方显示了一下  “无法取得权限”  然后闪了一下就没了，没来得及截图。也不知道等多久，他会又弹出来一下。

**Comment by 2dust** [comment]
实在无法截图的，请到应用管理中找到，然后把一些权限都给加上，相机，存储，读取应用列表等

**Comment by Char-CN** [comment]
> 实在无法截图的，请到应用管理中找到，然后把一些权限都给加上，相机，存储，读取应用列表等

我的也是一下载就全给了权限，也会出现的。是不是小米系统更新了啥不能选择的权限？

**Comment by Char-CN** [comment]
<img src="https://github.com/user-attachments/assets/edd5b089-028d-4e84-aecd-73380a24b93d" height="600" width="300" />
终于截到图了

**Comment by Char-CN** [comment]
<img src="https://github.com/user-attachments/assets/c48fbf12-7ab0-44d2-a3b3-df96e081ab84" height="600" width="300" />
<img src="https://github.com/user-attachments/assets/dfc4b48c-1819-469b-add3-844283dd10b4" height="600" width="300" />


权限也都给了的。

**Comment by Char-CN** [comment]
<img src="https://github.com/user-attachments/assets/edd5b089-028d-4e84-aecd-73380a24b93d" height="500" width="200" />

**Comment by 2dust** [comment]
查了下代码，这个是检查的通知的运行时权限，查看下是否给了通知权限？

**Comment by Char-CN** [comment]
好吧，我把所有通知都关掉了

**Comment by hzexe** [comment]
> 好吧，我把所有通知都关掉了

确实是屏蔽通知造成的。。
至于分应用不好使是另外一回事了，不是由此造成的

**Comment by aojie654** [comment]
> 查了下代码，这个是检查的通知的运行时权限，查看下是否给了通知权限？

同样被这个问题困扰了好久... 是否可以对无法取得权限提示详细一点呢？🤣
