### ISSUE TITLE
真连接测速-1无法使用

### ISSUE THREAD

**Issue by dead03648** [2dust/v2rayNG#3836]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
v2rayn可以使用的，在ng上无法使用

### 实际行为
真连接测速-1无法使用，更换1.9.8 1.9.9 1.8.39均无法使用

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
--------- beginning of system
--------- beginning of main
11-03 15:53:15.360 E/com.v2ray.ang(13015): Not starting debugger since process cannot load the jdwp agent.
11-03 15:54:06.802 D/com.v2ray.ang(13015): https://freev2ray.top/V2raygjdsnew106854.txt
11-03 15:54:17.469 I/GoLog   ( 9135): 2024/11/03 07:54:17 [Warning] core: Xray 1.8.24 started
11-03 15:54:17.532 I/GoLog   ( 9135): 2024/11/03 07:54:17 [Warning] core: Xray 1.8.24 started
11-03 15:54:17.572 I/GoLog   ( 9135): 2024/11/03 07:54:17 [Warning] core: Xray 1.8.24 started
11-03 15:54:17.583 I/GoLog   ( 9135): 2024/11/03 07:54:17 [Warning] core: Xray 1.8.24 started
11-03 15:54:18.315 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:18.316 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:18.316 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:18.333 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:18.727 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:18.949 I/GoLog   ( 9135): 2024/11/03 07:54:18 [Warning] core: Xray 1.8.24 started
11-03 15:54:19.097 I/GoLog   ( 9135): 2024/11/03 07:54:19 [Warning] core: Xray 1.8.24 started
11-03 15:54:19.098 I/GoLog   ( 9135): 2024/11/03 07:54:19 [Warning] core: Xray 1.8.24 started
11-03 15:54:19.362 I/GoLog   ( 9135): 2024/11/03 07:54:19 [Warning] core: Xray 1.8.24 started
11-03 15:54:19.589 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:19.913 I/GoLog   ( 9135): 2024/11/03 07:54:19 [Warning] core: Xray 1.8.24 started
11-03 15:54:20.207 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:20.568 I/GoLog   ( 9135): 2024/11/03 07:54:20 [Warning] core: Xray 1.8.24 started
11-03 15:54:23.392 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
11-03 15:54:23.533 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
11-03 15:54:23.585 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
11-03 15:54:23.589 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
11-03 15:54:23.769 I/GoLog   ( 9135): 2024/11/03 07:54:23 [Warning] core: Xray 1.8.24 started
11-03 15:54:24.059 I/GoLog   ( 9135): 2024/11/03 07:54:24 [Warning] core: Xray 1.8.24 started
11-03 15:54:24.114 I/GoLog   ( 9135): 2024/11/03 07:54:24 [Warning] core: Xray 1.8.24 started
11-03 15:54:24.135 I/GoLog   ( 9135): 2024/11/03 07:54:24 [Warning] core: Xray 1.8.24 started
11-03 15:54:24.210 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:24.415 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:24.420 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:24.703 I/GoLog   ( 9135): 2024/11/03 07:54:24 [Warning] core: Xray 1.8.24 started
11-03 15:54:24.936 I/GoLog   ( 9135): 2024/11/03 07:54:24 [Warning] core: Xray 1.8.24 started
11-03 15:54:24.936 I/GoLog   ( 9135): 2024/11/03 07:54:24 [Warning] core: Xray 1.8.24 started
11-03 15:54:25.118 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
11-03 15:54:25.290 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:25.314 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-03 15:54:25.653 I/GoLog   ( 9135): 2024/11/03 07:54:25 [Warning] core: Xray 1.8.24 started
11-03 15:54:25.857 I/GoLog   ( 9135): 2024/11/03 07:54:25 [Warning] core: Xray 1.8.24 started
11-03 15:54:25.867 I/GoLog   ( 9135): 2024/11/03 07:54:25 [Warning] core: Xray 1.8.24 started
11-03 15:54:26.582 D/com.v2ray.ang( 9135): realPing: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": net/http: TLS handshake timeout
11-03 15:54:26.904 I/GoLog   ( 9135): 2024/11/03 07:54:26 [Warning] core: Xray 1.8.24 started
11-03 15:54:29.782 D/com.v2ray.ang( 9135): 
</details>

### 环境信息
miui13.0.1

**Comment by dead03648** [comment]
> 设置->进阶设置->真连接延迟测试网址修改为 https://www.google.com 就可以了

和N用的一样的https://www.google.com/generate_204也是不行。不单单是测速，tls handshake timeout

**Comment by wukan1986** [comment]
设置->进阶设置->真连接延迟测试网址修改为
https://www.google.com
就可以了

**Comment by wukan1986** [comment]
> > 设置->进阶设置->真连接延迟测试网址修改为 https://www.google.com 就可以了
> 
> 和N用的一样的[https://www.google.com/generate_204也是不行。不单单是测速，tls](https://www.google.com/generate_204%E4%B9%9F%E6%98%AF%E4%B8%8D%E8%A1%8C%E3%80%82%E4%B8%8D%E5%8D%95%E5%8D%95%E6%98%AF%E6%B5%8B%E9%80%9F%EF%BC%8Ctls) handshake timeout

是`https://www.google.com`，没有`generate_204`

**Comment by dead03648** [comment]
> > > 设置->进阶设置->真连接延迟测试网址修改为 https://www.google.com 就可以了
> > 
> > 
> > 和N用的一样的[https://www.google.com/generate_204也是不行。不单单是测速，tls](https://www.google.com/generate_204%E4%B9%9F%E6%98%AF%E4%B8%8D%E8%A1%8C%E3%80%82%E4%B8%8D%E5%8D%95%E5%8D%95%E6%98%AF%E6%B5%8B%E9%80%9F%EF%BC%8Ctls) handshake timeout
> 
> 是`https://www.google.com`，没有`generate_204`

也是不行的

**Comment by 2dust** [comment]
把配置发出来，可以去掉ip

**Comment by 2dust** [comment]
io: read/write on closed pipe
就是core提示连接不上，如果你的配置是WS，可以看看是否开不安全连接

**Comment by dead03648** [comment]
> io: read/write on closed pipe 就是core提示连接不上，如果你的配置是WS，可以看看是否开不安全连接

是跳过证书验证吗？

**Comment by 2dust** [comment]
大概就是证书，时间等问题
