### ISSUE TITLE
建议更新订阅后先执行【删除当前组重复配置】

### ISSUE THREAD

**Issue by wukan1986** [2dust/v2rayNG#3837]
最近升级1.9.9后，发现更新订阅后会自动进行真连接测试了

建议真连接测试之前先【删除当前组重复配置】，因为部分源每次更新都有十几条是重复地址

**Comment by 2dust** [comment]
自动进行真连接测试这个将在下一版移除掉，因为有订阅特别长，自动测花太多时间
删除当前组重复配置，这个功能在v2rayN已经加入，但是用户也有人反对这样做，所以下一版也将移除
所以这些自动的功能近期都不会增加了，众口难调

**Comment by 2dust** [comment]
如果做参数控制，感觉参数又太多了

**Comment by wukan1986** [comment]
是的。
1. 没有`更新订阅后自动真连测试`
2. 有`更新订阅后自动真连测试`，但`自动真连测试`前执行`删除当前组重复配置`

我也支持第1种，取消`自动真连测试`
