### ISSUE TITLE
Add support of `vgc://`-keys

### ISSUE THREAD

**Issue by Korb** [2dust/v2rayNG#3840]
### Expected behavior
The v2rayNG application can import configurations by pasting a link starting with `vgc://` [1].

### Actual behavior
The v2rayNG application does not recognize a link starting with `vgc://` as a valid configuration to import.

### Reproduction method
1. Copy the link starting with `vgc://` to the clipboard.
2. Click on the "+" symbol in the upper right corner of v2rayNG.
3. Select "Import config from Clipboard".
4. See the message "v2rayNG pasted from your clipboard".
5. See the message "Failure".

### Log information
Empty.

### Environmental information

v2rayNG 1.9.9 (Oct 29, 2024)

OS version: Funtouch OS 14
Model: Vivo T1 (4G,  V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.9.0.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107
Kernel version: 4.19.157-perf+, 1 Sat Oct 12 11:14:50 CST 2024
Compile time: 12 Oct 2024 06:06:30
Android security update: 1 October 2024
Google Play system update: 1 September 2024
Software parameter update: 15 October 2024

[1] [VPN Generator](https://play.google.com/store/apps/details?id=org.iedn.vpngenerator) and [Amnezia VPN](https://github.com/amnezia-vpn/amnezia-client/issues) configuration.

**Comment by aleksannikit** [comment]
> ### Expected behavior
> The v2rayNG application can import configurations by pasting a link starting with `vgc://` [1].
> 
> ### Actual behavior
> The v2rayNG application does not recognize a link starting with `vgc://` as a valid configuration to import.
> 
> ### Reproduction method
> 1. Copy the link starting with `vgc://` to the clipboard.
> 2. Click on the "+" symbol in the upper right corner of v2rayNG.
> 3. Select "Import config from Clipboard".
> 4. See the message "v2rayNG pasted from your clipboard".
> 5. See the message "Failure".
> 
> ### Log information
> Empty.
> 
> ### Environmental information
> v2rayNG 1.9.9 (Oct 29, 2024)
> 
> OS version: Funtouch OS 14 Model: Vivo T1 (4G, V2153) Hardware version: MP_0.1 Build number: PD22010F_EX_A_14.2.9.0.W20 Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107 Kernel version: 4.19.157-perf+, 1 Sat Oct 12 11:14:50 CST 2024 Compile time: 12 Oct 2024 06:06:30 Android security update: 1 October 2024 Google Play system update: 1 September 2024 Software parameter update: 15 October 2024
> 
> [1] [VPN Generator](https://play.google.com/store/apps/details?id=org.iedn.vpngenerator) and [Amnezia VPN](https://github.com/amnezia-vpn/amnezia-client/issues) configuration.

It's not necessary, it's a proprietary format. Simple base58 encoding. I wrote a code snippet for decoding, try it!
https://jsfiddle.net/aleksannikit/ofm7nbwx
