### ISSUE TITLE
`IPv6 Connection Disabled` - Bug in (1.9.10 Pre-release)

### ISSUE THREAD

**Issue by Phoenix-999** [2dust/v2rayNG#3851]
Hi @2dust,

In the latest V2rayNG update `(1.9.10 Pre-release)`, any connection that uses  **`IPv6`** instead of **`IPv4 `or a `subdomain.domain`** in the **address field** no longer connects. Specifically, the play button won’t turn orange or become active, It looks like the **`connection and play button is disabled`** whenever an IPv6 configuration file is selected.

![IPv6 Connection Disabled - Bug in (1 9 10 Pre-release)](https://github.com/user-attachments/assets/cbff0cc9-f6e8-48c1-bc98-c50cb9c79d9e)

Could you please look into resolving this issue? Many V2rayNG users rely on IPv6 addresses to bypass GFW filtering, and it’s still working on some VPS servers where IPv4 is blocked by the GFW.

Thank you in advance!

FYI: @CodeWithTamim

**Comment by Phoenix-999** [comment]
@decorativefamily,

I have tested different protocols on IPv4 with a subdomain/domain as the address, and it seems to connect and show the ping. I also cleared the application cache in case there was a temporary bug, but that didn’t fix the problem.

Also, I conducted tests on different protocols using various VPS and regions to ensure it wasn’t a configuration file issue, and I confirmed that IPv6 is enabled on the device. However, I still get the same result: the **`Stop/Play button is disabled`** as soon as you select the configuration from the list.

Perhaps deleting the app and reinstalling it, or clearing the storage and cache, might help at least to fix the IPv4 issue.

**Comment by codewithtamim** [comment]
okay

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.11

**Comment by Phoenix-999** [comment]
Thank you all for the fixes in the new update!
You guys are amazing! ⭐
