### ISSUE TITLE
multiple json subscription not working in 1.9.10 and 1.9.11

### ISSUE THREAD

**Issue by ssmetall** [2dust/v2rayNG#3852]
Hello, the version 1.9.10 app is giving a JSON subscrption error, all previus version no problem with multiple json please check. 

i have https subscrption link with this example : 

[
json1
,
json2
,
json3
]

example my subscription json :

[
{
"log": {
"access": "",
"error": "",
"loglevel": "warning"
},
"dns": {
"servers": [
"1.1.1.1",
"8.8.8.8"
],
"queryStrategy": "UseIPv4"
},
"inbounds": [
{
"tag": "socks",
"port": 10808,
"listen": "127.0.0.1",
"protocol": "socks",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
},
{
"tag": "http",
"port": 10809,
"listen": "127.0.0.1",
"protocol": "http",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
}
],
"outbounds": [
{
"tag": "proxy",
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "",
"port": 443,
"users": [
{
"id": "",
"alterId": 0,
"email": "t@t.tt",
"security": "auto",
"encryption": "none"
}
]
}
]
},
"streamSettings": {
"network": "ws",
"security": "tls",
"tlsSettings": {
"allowInsecure": true,
"fingerprint": "chrome",
"serverName": ""
},
"wsSettings": {
"headers": {
"Host": "",
"User-Agent": ""
},
"path": "/"
},
"sockopt": {
"dialerProxy": "fragment0",
"tcpKeepAliveIdle": 100,
"mark": 255,
"tcpNoDelay": true
}
},
"mux": {
"concurrency": 8,
"enabled": true,
"xudpConcurrency": 16,
"xudpProxyUDP443": "reject"
}
},
{
"tag": "fragment0",
"protocol": "freedom",
"settings": {
"domainStrategy": "AsIs",
"fragment": {
"packets": "",
"length": "",
"interval": ""
}
},
"streamSettings": {
"sockopt": {
"tcpNoDelay": true,
"tcpKeepAliveIdle": 100
}
}
}
],
"routing": {
"domainStrategy": "AsIs"
},
"remarks": "json1"
},
{
"log": {
"access": "",
"error": "",
"loglevel": "warning"
},
"dns": {
"servers": [
"1.1.1.1",
"8.8.8.8"
],
"queryStrategy": "UseIPv4"
},
"inbounds": [
{
"tag": "socks",
"port": 10808,
"listen": "127.0.0.1",
"protocol": "socks",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
},
{
"tag": "http",
"port": 10809,
"listen": "127.0.0.1",
"protocol": "http",
"sniffing": {
"enabled": true,
"destOverride": [
"http",
"tls"
],
"routeOnly": false
},
"settings": {
"auth": "noauth",
"udp": true,
"allowTransparent": false
}
}
],
"outbounds": [
{
"tag": "proxy",
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "",
"port": 443,
"users": [
{
"id": "",
"alterId": 0,
"email": "t@t.tt",
"security": "auto",
"encryption": "none"
}
]
}
]
},
"streamSettings": {
"network": "ws",
"security": "tls",
"tlsSettings": {
"allowInsecure": true,
"fingerprint": "chrome",
"serverName": ""
},
"wsSettings": {
"headers": {
"Host": "",
"User-Agent": ""
},
"path": "/"
},
"sockopt": {
"dialerProxy": "fragment0",
"tcpKeepAliveIdle": 100,
"mark": 255,
"tcpNoDelay": true
}
},
"mux": {
"concurrency": 8,
"enabled": true,
"xudpConcurrency": 16,
"xudpProxyUDP443": "reject"
}
},
{
"tag": "fragment0",
"protocol": "freedom",
"settings": {
"domainStrategy": "AsIs",
"fragment": {
"packets": "",
"length": "",
"interval": ""
}
},
"streamSettings": {
"sockopt": {
"tcpNoDelay": true,
"tcpKeepAliveIdle": 100
}
}
}
],
"routing": {
"domainStrategy": "AsIs"
},
"remarks": "json2"
}
]

**Comment by ssmetall** [comment]
update
 only one json work with my subscription

[
json
]


multiple not working
[
json1
,
json2
,
json3
]

**Comment by Sky9424** [comment]
I have same situation 

![Screenshot_2024-11-04-15-31-02-495_com.v2ray.ang.jpg](https://github.com/user-attachments/assets/3ce6cb99-cb56-465c-8a4b-7a7d72ab4a4b)

**Comment by 2dust** [comment]
waiting for fix

**Comment by Sky9424** [comment]
Same here ![Screenshot_2024-11-04-15-31-49-417_com.v2ray.ang.jpg](https://github.com/user-attachments/assets/69149e7f-c183-4748-9a63-36c7d8ba25e5)

**Comment by sssagsag** [comment]
logcat :

**Comment by ssmetall** [comment]
logcat : 
--------- beginning of main
11-04 15:32:10.544 W/com.v2ray.ang(17751): type=1400 audit(0.0:18292): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=13242 scontext=u:r:untrusted_app:s0:c40,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-04 15:32:12.312 W/com.v2ray.ang(17751): type=1400 audit(0.0:18361): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=13242 scontext=u:r:untrusted_app:s0:c40,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-04 15:32:13.856 W/com.v2ray.ang(17751): type=1400 audit(0.0:18423): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=13242 scontext=u:r:untrusted_app:s0:c40,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-04 15:32:15.440 D/com.v2ray.ang(17751): https://users.sshh.......
11-04 15:32:15.445 E/com.v2ray.ang(17751): Update subscription: proxy not ready or other error, try……
11-04 15:32:16.194 I/com.v2ray.ang(17751): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
11-04 15:32:16.194 I/com.v2ray.ang(17751): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
11-04 15:32:16.194 I/com.v2ray.ang(17751): Parse base64 standard failed java.lang.IllegalArgumentException: bad base-64
11-04 15:32:16.194 I/com.v2ray.ang(17751): Parse base64 url safe failed java.lang.IllegalArgumentException: bad base-64
11-04 15:32:16.210 W/System.err(17751): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
11-04 15:32:16.210 W/System.err(17751): See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520)
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1361)
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1262)
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1171)
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1107)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.util.JsonUtil.fromJson(JsonUtil.kt:19)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.fmt.CustomFmt.parse(CustomFmt.kt:12)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.handler.AngConfigManager.parseCustomConfigServer(AngConfigManager.kt:280)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.handler.AngConfigManager.parseConfigViaSub(AngConfigManager.kt:380)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.handler.AngConfigManager.updateConfigViaSub(AngConfigManager.kt:367)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.viewmodel.MainViewModel.updateConfigViaSubAll(MainViewModel.kt:159)
11-04 15:32:16.210 W/System.err(17751):  at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1.invokeSuspend(MainActivity.kt:622)
11-04 15:32:16.210 W/System.err(17751):  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
11-04 15:32:16.210 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
11-04 15:32:16.210 W/System.err(17751): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
11-04 15:32:16.210 W/System.err(17751): See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.stream.JsonReader.unexpectedTokenError(JsonReader.java:1768)
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:469)
11-04 15:32:16.210 W/System.err(17751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509)
11-04 15:32:16.210 W/System.err(17751):  ... 19 more
11-04 15:32:16.211 W/System.err(17751): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
11-04 15:32:16.211 W/System.err(17751): See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520)
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1361)
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1262)
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1171)
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.Gson.fromJson(Gson.java:1107)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.util.JsonUtil.fromJson(JsonUtil.kt:19)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.fmt.CustomFmt.parse(CustomFmt.kt:12)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.handler.AngConfigManager.parseCustomConfigServer(AngConfigManager.kt:294)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.handler.AngConfigManager.parseConfigViaSub(AngConfigManager.kt:380)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.handler.AngConfigManager.updateConfigViaSub(AngConfigManager.kt:367)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.viewmodel.MainViewModel.updateConfigViaSubAll(MainViewModel.kt:159)
11-04 15:32:16.211 W/System.err(17751):  at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1.invokeSuspend(MainActivity.kt:622)
11-04 15:32:16.211 W/System.err(17751):  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
11-04 15:32:16.211 W/System.err(17751):  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
11-04 15:32:16.211 W/System.err(17751): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
11-04 15:32:16.211 W/System.err(17751): See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.stream.JsonReader.unexpectedTokenError(JsonReader.java:1768)
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:469)
11-04 15:32:16.211 W/System.err(17751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509)
11-04 15:32:16.211 W/System.err(17751):  ... 19 more
11-04 15:32:18.596 W/com.v2ray.ang(17751): type=1400 audit(0.0:18495): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=13242 scontext=u:r:untrusted_app:s0:c40,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.v2ray.ang

**Comment by ssmetall** [comment]
update
same in 1.9.11

**Comment by 2dust** [comment]
Fixed, waiting for the next release

**Comment by ssmetall** [comment]
> Fixed, waiting for the next release

thank you , are you releasing a new version at the moment?

**Comment by 2dust** [comment]
Maybe tomorrow

**Comment by ssmetall** [comment]
> Maybe tomorrow

dr

> Maybe tomorrow

Dear friend, the last two versions practically destroy all connections. Because many users are members of the beta version on Google Play.

**Comment by 2dust** [comment]
The test group has only about 10,000 people, and the official group has 20 million people. If you join the test group, there will be unpredictable problems.
