### ISSUE TITLE
Add Tab Management and Swipe Navigation Features

### ISSUE THREAD

**Issue by BiMaghz** [2dust/v2rayNG#3854]
I have a suggestion for the program that allows users to manage tabs more effectively and have better control over the addition of configurations.

- Tab Customization
Users should be able to create new tabs and customize each tab according to their own grouping preferences. a customization option would allow users to control whether newly updated configurations from subscription links are automatically added to the "All Groups" tab or only appear in their designated tabs. This helps prevent clutter in the first tab

- Swipe Navigation Between Tabs
To improve usability, users should be able to swipe left or right to switch between tabs. This swipe gesture would offer a smoother, more intuitive experience, similar to modern Android apps, allowing users to navigate between groups with ease

**Comment by ghost** [comment]
@2dust

**Comment by ghost** [comment]
@CodeWithTamim
