### ISSUE TITLE
导出规则到剪贴板后部分信息丢失

### ISSUE THREAD

**Issue by flamehe** [2dust/v2rayNG#3855]
### 预期行为
导出时包含节点全部信息

### 实际行为
部分节点信息丢失，包括协议，path等

### 复现方法
1.导出节点信息到剪贴板
2.粘贴到记事本
3.从记事本复制并导入

### 日志信息
<details>
```
</details>

### 环境信息

### 额外信息（可选）
1.9.11版本

**Comment by 2dust** [comment]
给个例子

**Comment by flamehe** [comment]
> 给个例子
我猜可能是1.9.9升级1.9.11上来导致的信息丢失，然后我发现节点不能用了后导出配置备份，里面保存的信息也就缺失了。而并不是1.9.11本身备份会导致配置丢失

**Comment by 2dust** [comment]
升级确实存在bug，请删除掉配置文件，重新导入一次吧

**Comment by milktoffee** [comment]
我发现导出到剪贴板后，有些数据被进行了多余的uri编码，导致出错。
例如ss协议的，@前的内容是base64编码的密码，由于多进行了一次uri编码，=会变成%3D，造成了导出的数据有误。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.14
