### ISSUE TITLE
v1.9.10使用IPv6无法正常连接

### ISSUE THREAD

**Issue by kasei0** [2dust/v2rayNG#3859]
### 预期行为
正常进行连接

### 实际行为
摁下连接按钮无任何反应。

### 复现方法
- 使用VLESS+Reality，其它配置均一致，使用IPv6作为服务器地址无法正常连接，使用IPv4作为服务器地址连接正常；

- 使用v1.9.9正常，v1.9.10异常

### 日志信息
<details>
11-04 23:30:07.427 28880 28880 I com.v2ray.ang: Main ViewModel is cleared
11-04 23:30:09.920 31200 31200 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
11-04 23:30:09.971 31200 31200 W com.v2ray.ang: JIT profile information will not be recorded: profile file does not exits.
11-04 23:30:09.971 31200 31200 W com.v2ray.ang: JIT profile information will not be recorded: profile file does not exits.
11-04 23:30:10.002 31200 31200 W com.v2ray.ang: type=1400 audit(0.0:74973): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=20555 scontext=u:r:untrusted_app:s0:c116,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
11-04 23:30:10.002 31200 31200 W com.v2ray.ang: type=1400 audit(0.0:74974): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20553 scontext=u:r:untrusted_app:s0:c116,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
11-04 23:30:10.075 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
11-04 23:30:10.077 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/View;->getWindowInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
11-04 23:30:10.078 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsetsController;->show(I)V (blacklist, linking, denied)
11-04 23:30:10.078 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsetsController;->hide(I)V (blacklist, linking, denied)
11-04 23:30:10.244 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getTypes()I (blacklist, linking, denied)
11-04 23:30:10.244 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getShownStateInsets()Landroid/graphics/Insets; (blacklist, linking, denied)
11-04 23:30:10.244 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets$Builder;->setInsets(ILandroid/graphics/Insets;)Landroid/view/WindowInsets$Builder; (blacklist, linking, denied)
11-04 23:30:10.244 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets$Builder;->setVisible(IZ)Landroid/view/WindowInsets$Builder; (blacklist, linking, denied)
11-04 23:30:10.245 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/Window;->getInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
11-04 23:30:10.245 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets;->isVisible(I)Z (blacklist, linking, denied)
11-04 23:30:10.246 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
11-04 23:30:10.246 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getCurrentInsets()Landroid/graphics/Insets; (blacklist, linking, denied)
11-04 23:30:10.246 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getHiddenStateInsets()Landroid/graphics/Insets; (blacklist, linking, denied)
11-04 23:30:10.246 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets$Type;->systemGestures()I (blacklist, linking, denied)
11-04 23:30:10.246 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets$Type;->mandatorySystemGestures()I (blacklist, linking, denied)
11-04 23:30:10.246 31200 31200 W com.v2ray.ang: Accessing hidden method Landroid/view/WindowInsets$Type;->tappableElement()I (blacklist, linking, denied)
</details>

**Comment by 2dust** [comment]
v1.9.11
