### ISSUE TITLE
1.9.11 全局代理

### ISSUE THREAD

**Issue by ltzqwe** [2dust/v2rayNG#3861]
各位大佬，最新版1.9.11如何设置全局代理呀？

**Comment by 2dust** [comment]
菜单选择导入预设，选择全局

**Comment by ysqllake** [comment]
1.9.32版本可以按照以下操作：主界面左上角三条横线，路由设置，右上角三个点，导入预定义规则集，确定，全局（Global）

**Comment by leywey0129** [comment]
> 1.9.32版本可以按照以下操作：主界面左上角三条横线，路由设置，右上角三个点，导入预定义规则集，确定，全局（Global）

搜了这么多终于找到了，对于一些手机app还是全局安全些

**Comment by EA7-A** [comment]
那1.9.37怎么开全局？也是那样吗？

**Comment by ASCII0x77** [comment]
> 1.9.32版本可以按照以下操作：主界面左上角三条横线，路由设置，右上角三个点，导入预定义规则集，确定，全局（Global）

谢谢指正
