### ISSUE TITLE
feature request : update subscription on open

### ISSUE THREAD

**Issue by ssmetall** [2dust/v2rayNG#3862]
please provide a way to update the subscription every time the v2rayng is opened, like the feature available in Streinsand.

![7](https://github.com/user-attachments/assets/61ea8b38-e44c-48eb-8237-87284ffb0cf1)

**Comment by moh3nat** [comment]
i have problem with none TLS config with http header disconnected &app crashed 
without headers it connected

**Comment by Astiyaxh** [comment]
> please provide a way to update the subscription every time the v2rayng is opened, like the feature available in Streinsand.

I have the same problem as well, specifically with versions 1.9.10 and 1.9.11. but v1.9.9 works just fine and having no problems with http configs.

**Comment by 2dust** [comment]
Each mobile phone system has different strategies for keeping apps alive, so it is not suitable for all mobile phones when turned on. Either manually or use a scheduled task

**Comment by ssmetall** [comment]
> Each mobile phone system has different strategies for keeping apps alive, so it is not suitable for all mobile phones when turned on. Either manually or use a scheduled task

I know!  But adding the update on open key in the subscription section is not difficult!
