### ISSUE TITLE
With 1.9.10 and 1.9.11 V2rayNG fails to import multiple json configs (updating json config subscription fails)

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [2dust/v2rayNG#3863]
Hello and Many thanks.

With  the last 2 releases (1.9.10 and 1.9.11),  V2rayNG fails to import multiple json/custom configs from a subscription link. It simply prints failure. And it also cannot update subscriptions which contains multiple custom/json configs.

Updating json/custom config subscriptions worked fine up to and including version 1.9.9.  Some functionality seems to have broken in 1.9.10 (if this was not intentional,, e.g. due to a change in json config format)

Also v2rayN (including the latest build v7.0.6) does NOT have this problem.
Thanks.

**Comment by ghost** [comment]
گ

> Hello and Many thanks.
> 
> With the last 2 releases (1.9.10 and 1.9.11), V2rayNG fails to import multiple json/custom configs from a subscription link. It simply prints failure. And it also cannot update subscriptions which contains multiple custom/json configs.
> 
> Updating json/custom config subscriptions worked fine up to and including version 1.9.9. Some functionality seems to have broken in 1.9.10 (if this was not intentional,, e.g. due to a change in json config format)
> 
> Also v2rayN (including the latest build v7.0.6) does NOT have this problem. Thanks.

https://github.com/2dust/v2rayNG/issues/3852#issuecomment-2454579500
