### ISSUE TITLE
Http (no tls) configs not connecting in v1.9.10 & v1.9.11

### ISSUE THREAD

**Issue by Astiyaxh** [2dust/v2rayNG#3865]
In versions 1.9.10 and 1.9.11, a serious problem was found with HTTP configurations (no TLS). The pings of HTTP TCP configurations that were 500 or 400 ms before in the new version either do not connect at all or connect with a ping above 5000 or 6000 with a very high delay and terrible speed. But the http ws configs are not a problem! In version 1.9.9, none of these problems existed and both HTTP TCP and HTTP WS configurations work well and without problems and at high speed.

**Comment by Alireza78na** [comment]
Same issue in v1.9.11 

For all TLS and noTLS Configs, it has Connection issue with Error " Fail to detect Internet Connection: EOF "

Also has bug in Logcat, when we try to Open it, App Crashs and Closed.

I tried to fix it by Clearing app data , Clean Install and Import Configs again , but problem not solved

**Comment by Alireza78na** [comment]
I uninstalled the v1.9.11 and install the v1.9.9 again
But Funnily enough, the problem still persists
It seems that the software files are not deleted completely
I am sure that the config and other variables are correct, because in another program and also before updating, everything works correctly.

**Comment by 2dust** [comment]
The v1.9.10 release didn't make behavioral changes to these features, it may be that xray-core changed it and you can submit the configuration and log to core

**Comment by 2dust** [comment]
> I uninstalled the v1.9.11 and install the v1.9.9 again But Funnily enough, the problem still persists It seems that the software files are not deleted completely I am sure that the config and other variables are correct, because in another program and also before updating, everything works correctly.

If you reinstall the old version and the problem is still the same, that means it's not the new version, because the app doesn't have a cache

**Comment by Alireza78na** [comment]
Update:

I reinstall the version 1.9.11 , and this time, i import the Configs Directly from Server and all of Problems be Solved !

I think there is a bug in Update Process, because when i  update it from 1.9.9 to 1.9.11, Configs not work in any other app or version!

**Comment by Photowalk** [comment]
Exactly the same problem here, gotta roll back to v1.9.9

**Comment by artoor32** [comment]
After the update, delete the config and add it again, the config will work correctly. I think this bug is related to the configuration migration

**Comment by xifen16** [comment]
相同的问题，最新版本一直EOF，回退到1.99就好了
