### ISSUE TITLE
ON/OFF Slide Switches - (Interface Improvement & suggestion)

### ISSUE THREAD

**Issue by Phoenix-999** [2dust/v2rayNG#3866]
Hi @2dust,
Thank you, as always, for your consistent updates and improvements to this amazing app!

I have a suggestion that could enhance the app's user-friendly interface and make it easier for a variety of users, including those with disabilities and older age groups.

I’ve noticed that the **`ON/OFF slide switches`**, particularly in the subscription and routing sections, lack sufficient contrast, making it difficult for some users with visual impairments to distinguish between the ON and OFF states. This can be especially challenging for users who rely on screen enhancement tools due to eyesight issues.
Would it be possible to add a bit more contrast or color to the ON/OFF slide switches to make them more visible and clearly define their status? 

![photo_5857442472794376832_y](https://github.com/user-attachments/assets/7c83d1d1-43d0-4226-9b1e-a87db9543e99)

With over 20 million users now, I’m sure this change would benefit a wide range of users, including those with disabilities and older generations.

Thank you in advance!

**Comment by 2dust** [comment]
Welcome pr

**Comment by Phoenix-999** [comment]
@2dust Thank Sir! 
As always, you guys are stars! ⭐

**Comment by 2dust** [comment]
No one has PR'd so far.

**Comment by ghost** [comment]
> 至今为止还没有人获得过 PR。

呜呜呜，我的建议呢

**Comment by Phoenix-999** [comment]
@2dust
Looks amazing—appreciate it, guys! 
⭐⭐⭐⭐⭐

![photo_5879533297778934295_x](https://github.com/user-attachments/assets/e4ed7984-f7a4-4c7f-9829-53359a13fa98)
