### ISSUE TITLE
升级到新版本反馈

### ISSUE THREAD

**Issue by lxtx528** [2dust/v2rayNG#3885]
升级到新版本后，部分订阅删除后重新导入还是无法使用。

**Comment by 2dust** [comment]
可以把不能用的配置发出来看看

**Comment by Nicolas-One** [comment]
> 可以把不能用的配置发出来看看

我这也有严重的问题，那就是启动一会儿后，会自动断开，然后就会发现状态栏vpn图标消失，于是打开app去发现状态是启动的，这时候怎么点按钮都没用了，只能杀死app然后重启才能用，不过过一会儿又会断开。

**Comment by 2dust** [comment]
1.9.12版本有bug，升级到1.9.13

**Comment by Nicolas-One** [comment]
> 1.9.12版本有bug，升级到1.9.13

昨天你刚更新就试了1.9.13，还是存在有很多节点无法使用，我卸载重装，然后重新导入也不行，至于会不会自动断开没试那么久不知道了，已经退回到1.9.9了，没有任何问题。

**Comment by 2dust** [comment]
最近几个版本是因为接受了很多PR，加上存储变更导致很多bug，但是不改存储不行了，因为core那边在后面会改配置格式
如果有时间，还是要多反馈是哪里有问题，方便开发者修复

**Comment by prowong** [comment]
升级了1.9.14，更新订阅之后，原先的ss协议的节点消失，只剩下vmess协议的节点

**Comment by 2dust** [comment]
> 升级了1.9.14，更新订阅之后，原先的ss协议的节点消失，只剩下vmess协议的节点

如果可以，你把订阅地址发  captainIronng@protonmail.com

**Comment by prowong** [comment]
> > 升级了1.9.14，更新订阅之后，原先的ss协议的节点消失，只剩下vmess协议的节点
> 
> 如果可以，你把订阅地址发 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

已发送，谢谢
