### ISSUE TITLE
add new language to app

### ISSUE THREAD

**Issue by hosseinabaspanah** [2dust/v2rayNG#3886]
Hello, don't be bored...

I want to translate your program into Luri Bakhtiari (bqi) language...

where do i start???

**Comment by 2dust** [comment]
You can google how to add，
https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/res/values/strings.xml
Here's an example
https://github.com/2dust/v2rayNG/tree/master/V2rayNG/app/src/main/res/values-ru/strings.xml

**Comment by hosseinabaspanah** [comment]
> You can google how to add， https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/res/values/strings.xml Here's an example https://github.com/2dust/v2rayNG/tree/master/V2rayNG/app/src/main/res/values-ru/strings.xml

Thank you... so I will prepare the translation file for you soon and send it to you...
Please give me an email address or contact method to send it...

Or tell me if I can add it to the source code myself...

**Comment by 2dust** [comment]
Using github's pr

**Comment by 2dust** [comment]
`Luri Bakhtiari (bqi) language...`
 Can you take a screenshot of the language settings on your phone?

**Comment by hosseinabaspanah** [comment]
If you want to check with my screenshot whether Luri Bakhtiari's language is available for the Android operating system or not...

I have to tell you that it is not in the phone's language list...

**Comment by hosseinabaspanah** [comment]
This does not cause a problem for your program because your program uses the in-program language selector and I have translated other projects into Luri Bakhtiari's language and there have been no problems...

**Comment by hosseinabaspanah** [comment]
@2dust 
Shall I start the translation work???

**Comment by 2dust** [comment]
I'd advise you not to do this job
Just use English

**Comment by hosseinabaspanah** [comment]
why???
Adding a new language to the program is more beneficial to the programmer and can satisfy the audience...

**Comment by 2dust** [comment]
Then download the source code and translate it.

**Comment by hosseinabaspanah** [comment]
great...
I will always get the new strings from the English language source file and do the translation for Luri Bakhtiari's language...
