### ISSUE TITLE
Custom profile for routing

### ISSUE THREAD

**Issue by shahramdll** [2dust/v2rayNG#3891]
add custom profile for routing like nekobox routing to choose custom config for routing profile.
![Screenshot_2024-11-06-14-33-26-976_moe nb4a_1_1](https://github.com/user-attachments/assets/5c58d3b2-eddf-4387-84a8-bc71acc62c06)

**Comment by VahidRafieiPour** [comment]
Yahoo Mail: Search, samsung, Conquer 
 
  On چهارشنبه, نوامبر ۶, ۲۰۲۴ at ۱۴:۴۱, ***@***.***> wrote:   


add custom profile for routing like nekobox routing to choose custom config for routing profile.
Screenshot_2024-11-06-14-33-26-976_moe.nb4a_1_1.jpg (view on web)
