### ISSUE TITLE
Android15 Target API 35 布局问题

### ISSUE THREAD

**Issue by lyrnya** [2dust/v2rayNG#3892]
Android15下1.9.13布局出现问题，部分页面最上方位菜单与状态栏叠加导致无法点击
![Screenshot_20241106-205638](https://github.com/user-attachments/assets/db518c20-4829-4cd1-9364-33484f0de24d)
![Screenshot_20241106-205704](https://github.com/user-attachments/assets/e18c44fa-1255-43fa-9b04-844173f8ae9b)
![Screenshot_20241106-205714](https://github.com/user-attachments/assets/76666607-9bee-4463-859a-cb5c94449d2b)

1.9.13 Target API 为35即A15，在A15出现布局错误
降级为1.9.9 Target API为34，无此问题

系统是HelluvaOS15

**Comment by 2dust** [comment]
目前开发没有api35的真机，等等是否有人能处理否？

**Comment by lyrnya** [comment]
> 目前开发没有api35的真机，等等是否有人能处理否？

有点怀疑是不是谷歌自己的问题，拨号输入*#*#4636#*#* [电话服务]应用API35 中的手机信息也有此问题

**Comment by ShosGithub** [comment]
在Pixel上同样能复现这个问题，包括手机信息中的布局也不正常

**Comment by lyrnya** [comment]
应该是api35默认开启无边框导致的
[应对 Android 15 强制执行的无边框措施](https://developer.android.com/codelabs/edge-to-edge?hl=zh-cn)
![图片](https://github.com/user-attachments/assets/123f3bc4-665d-4a93-ad27-55b5bb690d79)
![图片](https://github.com/user-attachments/assets/a1aee76c-4af2-40dd-98bf-c505a80d108d)

**Comment by 2dust** [comment]
问题应该存在，如果有人PR解决就好，不然等开发准备设备了

**Comment by dyhkwong** [comment]
在未适配 edge-to-edge 的情况下可以暂时先 `<item name="android:windowOptOutEdgeToEdgeEnforcement" tools:targetApi="35">true</item>` 强制禁用 edge-to-edge。

**Comment by 2dust** [comment]
使用 `android:fitsSystemWindows="true"` 有效
