### ISSUE TITLE
Vless subscription can use in v2ray box but not v2rayng

### ISSUE THREAD

**Issue by mactrash** [2dust/v2rayNG#3893]
V2rayng 1.9.12

**Comment by mactrash** [comment]
@decorativefamily installed 1.9.13 still not work

**Comment by mactrash** [comment]
@decorativefamily 

Fail to detect internet connection EOF

--------- beginning of main
11-07 13:23:19.758 D/com.v2ray.ang( 5446): {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   "dns": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     "hosts": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "geosite:category-ads-all": "127.0.0.1",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "domain:googleapis.cn": "googleapis.com",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "dns.pub": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "1.12.12.12",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "120.53.53.53"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "dns.alidns.com": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "223.5.5.5",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "223.6.6.6",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "2400:3200::1",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "2400:3200:baba::1"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "one.one.one.one": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "1.1.1.1",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "1.0.0.1",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "2606:4700:4700::1111",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "2606:4700:4700::1001"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "dns.google": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "8.8.8.8",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "8.8.4.4",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "2001:4860:4860::8888",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "2001:4860:4860::8844"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       ]
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     "servers": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "94.140.14.14",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "address": "94.140.14.14",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domains": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:googleapis.cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:gstatic.com"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ]
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "address": "223.5.5.5",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domains": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:dns.alidns.com",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:doh.pub",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:dot.pub",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:doh.360.cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:dot.360.cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geosite:cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geosite:geolocation-cn"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "expectIPs": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geoip:cn"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "skipFallback": true
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     ]
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   "inbounds": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "port": 10808,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "socks",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "settings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "auth": "noauth",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "udp": true,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "userLevel": 8
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "sniffing": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "destOverride": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "http",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "tls"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "enabled": true,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "routeOnly": false
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "socks"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "port": 10809,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "http",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "settings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "userLevel": 8
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "http"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "listen": "127.0.0.1",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "port": 10853,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "dokodemo-door",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "settings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "address": "94.140.14.14",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "network": "tcp,udp",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "port": 53
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "dns-in"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   "log": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     "loglevel": "warning"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   "outbounds": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "mux": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "concurrency": 1,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "enabled": true,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "xudpConcurrency": 1,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "xudpProxyUDP443": "reject"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "vless",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "settings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "vnext": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):             "address": "test.com",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):             "port": 443,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):             "users": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):               {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):                 "encryption": "none",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):                 "id": "xxxxx-xxxxx-xxxxx-xxxxx",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):                 "level": 8
11-07 13:23:19.758 D/com.v2ray.ang( 5446):               }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):             ]
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ]
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "streamSettings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "network": "ws",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "security": "tls",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "tlsSettings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "allowInsecure": false,
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "fingerprint": "randomized",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "serverName": "test.com",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "show": false
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "wsSettings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "headers": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):             "Host": "test.com"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "path": "/?ed=test"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "proxy"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "freedom",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "settings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domainStrategy": "UseIP"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "direct"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "blackhole",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "settings": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "response": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "type": "http"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "block"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "protocol": "dns",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       "tag": "dns-out"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   "remarks": "test.com",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   "routing": {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     "domainStrategy": "IPIfNonMatch",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     "rules": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "inboundTag": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "dns-in"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "dns-out",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "ip": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "94.140.14.14"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "proxy",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "port": "53",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "ip": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "223.5.5.5"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "direct",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "port": "53",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domain": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:googleapis.cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:gstatic.com"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "proxy",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "network": "udp",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "block",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "port": "443",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domain": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geosite:category-ads-all"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "block",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "ip": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geoip:private"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "direct",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domain": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geosite:private"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "direct",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "domain": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:dns.alidns.com",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:doh.pub",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:dot.pub",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:doh.360.cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "domain:dot.360.cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geosite:cn",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geosite:geolocation-cn"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "direct",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "ip": [
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "223.5.5.5/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "223.6.6.6/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "2400:3200::1/128",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "2400:3200:baba::1/128",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "119.29.29.29/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "1.12.12.12/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "120.53.53.53/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "2402:4e00::/128",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "2402:4e00:1::/128",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "180.76.76.76/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "2400:da00::6666/128",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "114.114.114.114/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "114.114.115.115/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "180.184.1.1/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "180.184.2.2/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "101.226.4.6/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "218.30.118.6/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "123.125.81.6/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "140.207.198.6/32",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):           "geoip:cn"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         ],
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "direct",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       },
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       {
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "outboundTag": "proxy",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "port": "0-65535",
11-07 13:23:19.758 D/com.v2ray.ang( 5446):         "type": "field"
11-07 13:23:19.758 D/com.v2ray.ang( 5446):       }
11-07 13:23:19.758 D/com.v2ray.ang( 5446):     ]
11-07 13:23:19.758 D/com.v2ray.ang( 5446):   }
11-07 13:23:19.758 D/com.v2ray.ang( 5446): }
11-07 13:23:19.761 I/GoLog   ( 5446): loading core config
11-07 13:23:19.761 I/GoLog   ( 5446): Preparing Domain: test.com:443
11-07 13:23:19.767 I/GoLog   ( 5446): Prepare Result:
11-07 13:23:19.767 I/GoLog   ( 5446):  Domain: test.com
11-07 13:23:19.767 I/GoLog   ( 5446):  Port: 443
11-07 13:23:19.767 I/GoLog   ( 5446):  IPs: [2606:4700:3035::6815:4b5f 2606:4700:3031::ac43:db61 172.67.219.97 104.21.75.95]
11-07 13:23:19.960 I/GoLog   ( 5446): new core
11-07 13:23:19.995 I/GoLog   ( 5446): start core
11-07 13:23:19.996 I/GoLog   ( 5446): [Warning] core: Xray 24.10.31 started
11-07 13:23:20.021 D/com.v2ray.ang( 5446): [/data/app/~~Z5LwG9U78x7Ffvu7rGdUOA==/com.v2ray.ang-guS8fSjEGuKRCOVjfx3SmA==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2, --dnsgw, 127.0.0.1:10853]
11-07 13:23:20.022 D/com.v2ray.ang( 5446): Process[pid=6574, hasExited=false]
11-07 13:23:20.023 D/com.v2ray.ang( 5446): /data/user/0/com.v2ray.ang/files/sock_path
11-07 13:23:20.025 D/com.v2ray.ang( 5446): libtun2socks.so check
11-07 13:23:20.036 D/com.v2ray.ang( 5446): runPlugin
11-07 13:23:20.041 I/tun2socks( 6574): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
11-07 13:23:20.073 D/com.v2ray.ang( 5446): sendFd tries: 0
11-07 13:23:20.074 I/tun2socks( 6574): NOTICE(tun2socks): entering event loop
11-07 13:23:20.160 I/GoLog   ( 5446): from 127.0.0.1:47870 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
11-07 13:23:20.163 I/GoLog   ( 5446): fdConn unix.Connect err, Close Fd: 101 Err: network is unreachable
11-07 13:23:20.163 I/GoLog   ( 5446): switched to next IP: 2606:4700:3031::ac43:db61
11-07 13:23:20.165 I/GoLog   ( 5446): from DNS accepted udp:94.140.14.14:53 [xray.system.88ce1199-658d-4375-9bac-6174b49da4a1 -> proxy]
11-07 13:23:20.165 I/GoLog   ( 5446): [Error] transport/internet/websocket: failed to dial to test.com:443 > network is unreachable
11-07 13:23:20.165 I/GoLog   ( 5446): [Warning] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://test.com/):  > network is unreachable
11-07 13:23:20.167 I/GoLog   ( 5446): from 127.0.0.1:45498 accepted udp:94.140.14.14:53 [dns-in -> dns-out]
11-07 13:23:20.168 I/GoLog   ( 5446): from DNS accepted udp:94.140.14.14:53 [xray.system.88ce1199-658d-4375-9bac-6174b49da4a1 -> proxy]
11-07 13:23:20.169 I/GoLog   ( 5446): fdConn unix.Connect err, Close Fd: 101 Err: network is unreachable
11-07 13:23:20.169 I/GoLog   ( 5446): switch too quickly
11-07 13:23:20.170 I/GoLog   ( 5446): [Error] transport/internet/websocket: failed to dial to test.com:443 > network is unreachable
11-07 13:23:20.170 I/GoLog   ( 5446): [Warning] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://test.com/):  > network is unreachable
11-07 13:23:20.206 I/GoLog   ( 5446): from tcp:127.0.0.1:46106 accepted tcp:94.140.14.14:853 [socks -> proxy]
11-07 13:23:20.207 I/GoLog   ( 5446): fdConn unix.Connect err, Close Fd: 108 Err: network is unreachable
11-07 13:23:20.207 I/GoLog   ( 5446): switch too quickly
11-07 13:23:20.208 I/GoLog   ( 5446): [Error] transport/internet/websocket: failed to dial to test.com:443 > network is unreachable
11-07 13:23:20.208 I/GoLog   ( 5446): [Warning] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://test.com/):  > network is unreachable
11-07 13:23:20.650 I/GoLog   ( 5446): from tcp:127.0.0.1:46112 accepted tcp:47.241.16.242:443 [socks -> proxy]
11-07 13:23:20.651 I/GoLog   ( 5446): fdConn unix.Connect err, Close Fd: 112 Err: network is unreachable
11-07 13:23:20.651 I/GoLog   ( 5446): switch too quickly
11-07 13:23:20.652 I/GoLog   ( 5446): [Error] transport/internet/websocket: failed to dial to test.com:443 > network is unreachable
11-07 13:23:20.652 I/GoLog   ( 5446): [Warning] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://test.com/):  > network is unreachable
11-07 13:23:24.163 I/GoLog   ( 5446): from DNS accepted udp:94.140.14.14:53 [xray.system.88ce1199-658d-4375-9bac-6174b49da4a1 -> proxy]
11-07 13:23:24.167 I/GoLog   ( 5446): fdConn unix.Connect err, Close Fd: 101 Err: network is unreachable
11-07 13:23:24.169 I/GoLog   ( 5446): switch too quickly
11-07 13:23:24.170 I/GoLog   ( 5446): [Error] transport/internet/websocket: failed to dial to test.com:443 > network is unreachable
11-07 13:23:24.170 I/GoLog   ( 5446): [Warning] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://test.com/):  > network is unreachable
11-07 13:23:25.168 I/GoLog   ( 5446): from DNS accepted udp:94.140.14.14:53 [xray.system.88ce1199-658d-4375-9bac-6174b49da4a1 -> proxy]
11-07 13:23:25.171 I/GoLog   ( 5446): fdConn unix.Connect err, Close Fd: 101 Err: network is unreachable
11-07 13:23:25.172 I/GoLog   ( 5446): switched to next IP: 172.67.219.97
11-07 13:23:25.173 I/GoLog   ( 5446): [Error] transport/internet/websocket: failed to dial to test.com:443 > network is unreachable
11-07 13:23:25.173 I/GoLog   ( 5446): [Warning] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > proxy/vless/outbound: failed to write A request payload > transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://test.com/):  > network is unreachable
11-07 13:23:25.297 I/GoLog   ( 5446): Using Prepared: 172.67.219.97
11-07 13:23:25.396 D/com.v2ray.ang( 5446): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": EOF
11-07 13:23:25.419 I/GoLog   ( 5446): Using Prepared: 172.67.219.97
11-07 13:23:25.508 D/com.v2ray.ang( 5446): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.google.com/generate_204": EOF
11-07 13:23:27.054 D/com.v2ray.ang( 5446): tun2socks destroy
11-07 13:23:27.054 I/tun2socks( 6574): NOTICE(tun2socks): termination requested
11-07 13:23:27.054 I/tun2socks( 6574): NOTICE(tun2socks): tearing down
11-07 13:23:27.054 I/tun2socks( 6574): NOTICE(tun2socks): Free TCP connections
11-07 13:23:27.055 I/tun2socks( 6574): NOTICE(tun2socks): exiting
11-07 13:23:27.057 D/com.v2ray.ang( 5446): libtun2socks.so exited
11-07 13:23:27.062 D/com.v2ray.ang( 5446): libhysteria2.so destroy
11-07 13:23:27.062 D/com.v2ray.ang( 5446): runProcess destroy

**Comment by laperuz92** [comment]
test.com?

It doesn't exist, check your config and use existing domains.

**Comment by mactrash** [comment]
@laperuz92 how can I post real domain and setup here？

**Comment by mactrash** [comment]
@2dust the vless link can be used in Android v2raybox and Mac os v2rayng and just don't wort wit Android v2rayng
