### ISSUE TITLE
V2rayNG无法更新Google Play商店内应用

### ISSUE THREAD

**Issue by FattyDG** [2dust/v2rayNG#3897]
我看到Google cn已经在第一行了 但是google play应用商店里的应用还是无法更新 现在的v2rangNG是1.9.9

在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by coldblood1980** [comment]
这个和V2rayNG没啥关系，是Google脑残明明知道自己的服务被封还把域名解析到中国的ip上，把xn--ngstr-ira8j.com这个域名添加到代理列表里面试试。

**Comment by 2dust** [comment]
这个问题有时候很简单，有时候很复杂。和域名解析/你的节点/还有缓存等都有关系

**Comment by lixingyang-lxy** [comment]
> 这个问题有时候很简单，有时候很复杂。和域名解析/你的节点/还有缓存等都有关系

我也知道有关系，请要么给出方案，谢谢
