### ISSUE TITLE
host只能一个一个改。

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3898]
这个host啊，我加混淆只能一个一个加。
有人提出：订阅转换可以统一加啊！
我：那也不好用啊！这个订阅转换过一段时间就失效过一段时间就失效，又得重新转换一次。
我建议v2开发者加个统一的host设置的选项，这个选项特性：
host加入混淆后就全部节点生效。

这个方案的好处：
1.（不用手动一个一个加了）
2.（不用订阅转换这种鸡肋的工具了）
3.（想用哪个混淆就改一次就行了，大大的节约时间，大大的便利）

**Comment by 2dust** [comment]
看不懂

**Comment by ghost** [comment]
> 不明白

![Screenshot_2024-11-08-13-17-01-445_com android chrome](https://github.com/user-attachments/assets/1eaa6451-5a95-4e77-8ba1-d04dd26d1cdf)
就是字面意思啊！加个一键修改host的选项，就不用挨个改了。

**Comment by ghost** [comment]
> 不明白

![IMG_20241108_132125](https://github.com/user-attachments/assets/4c816b04-6571-424f-9616-95b019d1d53f)

**Comment by ghost** [comment]
> 不明白

你好，清楚了吗？可以参考我的建议吗？
