### ISSUE TITLE
在配置文件界面滑动配置时其中内容抖动

### ISSUE THREAD

**Issue by landexiang9** [2dust/v2rayNG#3899]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
左右滑动时正常淡化显示内容随着滑动而移动

### 实际行为
在滑动时内容来回闪动

### 复现方法
1.滑动配置时在后半程停止并保持长按

### 日志信息
<details>显示问题应该没有日志吧

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
（应该不是什么大问题）

**Comment by 2dust** [comment]
这个目前是只能自己解决下了，目前配置界面用的也比较少。
这么做的原因是很多下拉框使用了非弹出模式，这样能减少弹出

**Comment by landexiang9** [comment]
> 这个目前是只能自己解决下了，目前配置界面用的也比较少。 这么做的原因是很多下拉框使用了非弹出模式，这样能减少弹出

谢谢大佬的回复，但是可能是因为我的描述不准确，你可能有一点点没太看懂，或者是因为我的知识浅陋我没有看懂你说的

我说的界面是打开软件后的那个选择配置的界面，大概情况我录了个屏，希望能够提供一些帮助

https://github.com/user-attachments/assets/919e5675-b4ed-424a-9f8b-466480d04db4

但这也不是什么大问题，如果太浪费时间也没有修的必要

**Comment by 2dust** [comment]
^_^，你说的是这个功能啊，这个是有网友PR过来的。
他的本意是要解决左右滑动时配置会被选中的问题；这个不影响使用，暂时不处理；如果有人PR那也接收
