### ISSUE TITLE
Xmux

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3904]
Hello, the xmux control is used in the client, if possible, add it to the program
https://github.com/XTLS/Xray-docs-next/commit/3b280cfb1a6bb474f08439d4e770b89cc6538eba
Apply these items if possible
https://github.com/2dust/v2rayNG/issues/3725
Thanks
@2dust @CodeWithTamim

**Comment by 2dust** [comment]
Please use the custom configuration first
It may be adapted when it stabilizes and doesn't change anymore
