### ISSUE TITLE
强烈建议加个「一键修改host」的功能

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3906]
![Screenshot_2024-11-08-18-33-55-481_com v2ray ang](https://github.com/user-attachments/assets/963b44e3-babe-473b-aff7-fda3a3c8528d)
![IMG_20241108_183442](https://github.com/user-attachments/assets/bec511ed-1c01-4251-a2fa-2fdafc772cd5)
![IMG_20241108_183503](https://github.com/user-attachments/assets/75f6773a-ac69-461d-9ba2-1c04a5afca64)
如图所示，逐一修改host非常繁琐，所以强烈建议增加一个「一键修改host」功能。

**Comment by 2dust** [comment]
终于明白你的意思了，这个没有计划做
这种你应该在订阅源那边修改，app手机上不会做的

**Comment by ghost** [comment]
> 终于明白你的意思了，这个没有 你应该在订阅源那边做的计划修改，app手机上不会做的

呜呜呜～，那不好用，订阅源是机场主决定的，所以我还是需要逐个修改，太难受了。
