### ISSUE TITLE
更新完好多节点都不能用了而且节点速度很慢

### ISSUE THREAD

**Issue by Eric465-bit** [2dust/v2rayNG#3907]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
版本？
配置？
日志？

**Comment by Andywang089** [comment]
我也是升级到最新版以后，节点全部失效
日志如下：
--------- beginning of main
11-09 19:57:16.878 I/GoLog   (19313): Not Using Prepared: tcp,202.89.233.101:443
11-09 19:57:17.371 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:17.547 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:17.623 I/GoLog   (19313): Not Using Prepared: tcp,202.89.233.101:443
11-09 19:57:17.836 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:17.849 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:17.855 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:17.919 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.001 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.097 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.123 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.161 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.163 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.164 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.170 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.173 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.174 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.176 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.178 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.178 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.355 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.356 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:18.581 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:19.372 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:19.982 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:20.699 I/GoLog   (19313): Not Using Prepared: tcp,202.89.233.101:443
11-09 19:57:20.737 I/GoLog   (19313): Not Using Prepared: tcp,202.89.233.101:443
11-09 19:57:21.040 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:21.554 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:21.668 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:22.217 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:22.556 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:22.557 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:23.048 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:23.065 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:23.177 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:23.562 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:31.459 E/com.v2ray.ang(15386): Invalid resource ID 0x00000000.
11-09 19:57:31.587 I/GoLog   (19313): Not Using Prepared: tcp,202.89.233.101:443
11-09 19:57:36.959 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:57:48.430 I/com.v2ray.ang(15386): This is sticky GC, maxfree is 33554432 minfree is 8388608
11-09 19:57:48.965 I/com.v2ray.ang(15386): Settings ViewModel is cleared
11-09 19:58:01.491 I/com.v2ray.ang(15386): This is non sticky GC, maxfree is 33554432 minfree is 8388608
11-09 19:58:02.015 I/com.v2ray.ang(15386): Settings ViewModel is cleared
11-09 19:58:28.604 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:28.910 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:28.922 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:28.922 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:28.937 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:29.588 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:29.589 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:30.219 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:30.531 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:31.656 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:31.783 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:58:34.123 I/GoLog   (19313): Not Using Prepared: udp,223.5.5.5:53
11-09 19:58:34.158 I/GoLog   (19313): Not Using Prepared: tcp,125.38.212.52:80
11-09 19:59:37.696 I/GoLog   (19313): Using Prepared: 38.121.43.204
11-09 19:59:38.284 I/GoLog   (19313): Using Prepared: 38.121.43.204


设置基本保持默认，开启了分应用代理，启动了本地DNS

![Uploading 微信图片_20241109195858.jpg…]()
