### ISSUE TITLE
1.9.9之后的版本部分无法连接

### ISSUE THREAD

**Issue by ChooseBetterr** [2dust/v2rayNG#3908]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
1.9.9 1.9.8都可以正常使用

### 实际行为
.12 .13 .14都有Trojan协议无法连接，hy2 splithtttp reality似乎可以

### 复现方法
清理掉节点重新加入依然不行

**Comment by DandelionPromises** [comment]
1.9.9版本确实trojan节点能ping通，但上不了网的情况。需要在设置中关闭“启用本地DNS”。并在路由设置中取消直连局域网，大陆IP。（应该是全局代理吧）就可以用了。

**Comment by 2dust** [comment]
确保节点是能正常连接的，然后对比下导入之前和导出分享做下对比是否有不同的地方
都自检后请把节点发 captainIronng@protonmail.com

**Comment by fcjxxl** [comment]
> 在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
> 
> ### 预期行为
> 1.9.9 1.9.8都可以正常使用
> 
> ### 实际行为
> .12 .13 .14都有Trojan协议无法连接，hy2 splithtttp reality似乎可以
> 
> ### 复现方法
> 清理掉节点重新加入依然不行

我升级到＞1.9.9的版本之后也连不了了, 然后又重新安装了1.9.9

**Comment by qqw1231** [comment]
> 确保节点是能正常连接的，然后对比下导入之前和导出分享做下对比是否有不同的地方 都自检后请把节点发 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

Trojan  12 13 14 15都不可用，1.9.9可用

**Comment by 2dust** [comment]
亲，这么多人反馈，没人给个配置或前后截图对比下吗？

**Comment by neduic** [comment]
> 亲，这么多人反馈，没人给个配置或前后截图对比下吗？

你的邮箱我好像发不进去 我先发一下log 1.9.15-1是升级后第一次连接的log，1.9.15-2是删除配置后重新更新订阅的log
[log.zip](https://github.com/user-attachments/files/17710544/log.zip)

**Comment by neduic** [comment]
> 亲，这么多人反馈，没人给个配置或前后截图对比下吗？

你的邮箱我好像发不进去 我先发一下log
[1.9.15.log](https://github.com/user-attachments/files/17710644/1.9.15.log)

**Comment by 2dust** [comment]
> > 亲，这么多人反馈，没人给个配置或前后截图对比下吗？
> 
> 你的邮箱我好像发不进去 我先发一下log [1.9.15.log](https://github.com/user-attachments/files/17710644/1.9.15.log)

能否这样操作下，把1.9.15的应用数据清空，然后重新导入你用不了的节点，测试下

**Comment by 2dust** [comment]
@neduic 
看到你的日志里面的测试连接走了直连，你设置下测试连接 为 `https://www.google.com/generate_204`

```
11-12 11:07:19.569 I/GoLog   (19372): from tcp:127.0.0.1:60054 accepted tcp:117.128.102.7:5222 [socks -> direct]
11-12 11:07:21.159 I/GoLog   (19372): Using Prepared: 120.233.171.84
11-12 11:07:21.322 D/com.v2ray.ang(19372): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
11-12 11:07:21.376 I/GoLog   (19372): Using Prepared: 120.233.171.84
```

**Comment by neduic** [comment]
> @neduic 看到你的日志里面的测试连接走了直连，你设置下测试连接 为 `https://www.google.com/generate_204`
> 
> ```
> 11-12 11:07:19.569 I/GoLog   (19372): from tcp:127.0.0.1:60054 accepted tcp:117.128.102.7:5222 [socks -> direct]
> 11-12 11:07:21.159 I/GoLog   (19372): Using Prepared: 120.233.171.84
> 11-12 11:07:21.322 D/com.v2ray.ang(19372): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
> 11-12 11:07:21.376 I/GoLog   (19372): Using Prepared: 120.233.171.84
> ```

我清除数据后并修改测试链接后依旧显示EOF，访问网站显示关闭链接。
[V2rayng.log](https://github.com/user-attachments/files/17711020/V2rayng.log)

**Comment by neduic** [comment]
> @neduic 看到你的日志里面的测试连接走了直连，你设置下测试连接 为 `https://www.google.com/generate_204`
> 
> ```
> 11-12 11:07:19.569 I/GoLog   (19372): from tcp:127.0.0.1:60054 accepted tcp:117.128.102.7:5222 [socks -> direct]
> 11-12 11:07:21.159 I/GoLog   (19372): Using Prepared: 120.233.171.84
> 11-12 11:07:21.322 D/com.v2ray.ang(19372): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
> 11-12 11:07:21.376 I/GoLog   (19372): Using Prepared: 120.233.171.84
> ```

我清除数据
[V2rayng.log](https://github.com/user-attachments/files/17711023/V2rayng.log)
并修改测试链接后依旧显示EOF，访问网站显示关闭链接。

**Comment by neduic** [comment]
> @neduic 看到你的日志里面的测试连接走了直连，你设置下测试连接 为 `https://www.google.com/generate_204`
> 
> ```
> 11-12 11:07:19.569 I/GoLog   (19372): from tcp:127.0.0.1:60054 accepted tcp:117.128.102.7:5222 [socks -> direct]
> 11-12 11:07:21.159 I/GoLog   (19372): Using Prepared: 120.233.171.84
> 11-12 11:07:21.322 D/com.v2ray.ang(19372): measureV2rayDelay: go.Universe$proxyerror: Get "https://www.gstatic.com/generate_204": io: read/write on closed pipe
> 11-12 11:07:21.376 I/GoLog   (19372): Using Prepared: 120.233.171.84
> ```

我清除数据后并修改测试链接后依旧显示EOF，访问网站显示关闭链接
[V2rayng.log](https://github.com/user-attachments/files/17711028/V2rayng.log)

**Comment by 2dust** [comment]
全新安装，重新更新订阅
https://github.com/2dust/v2rayNG/releases/tag/1.9.16

**Comment by foolishamn** [comment]
> 全新安装，重新更新订阅 https://github.com/2dust/v2rayNG/releases/tag/1.9.16

你好，按照要求，清除数据，删除旧版本app，重新下载了[v2rayNG_1.9.16_arm64-v8a.apk](https://github.com/2dust/v2rayNG/releases/download/1.9.16/v2rayNG_1.9.16_arm64-v8a.apk)，还是报错：io: read/write on closed pipe。

我的基本情况：
1.服务端是自己用xray布的，windows上的V2rayN V6.45可以正常连接；
2.手机是huawei mate60pro; 一个多星期前V2rayNG V1.8.22可以正常使用，后来就不行了，连接时报io: read/write on closed pipe。错误；
3.按照上面回复，下载了1.9.16，使用【测试当前组配置Tcping】时正常返回响应时间，使用【测试当前组配置真连接】时返回-1ms。

请问这个是什么原因？还有在哪儿能看到日志文件？

**Comment by 2dust** [comment]
@foolishamn 前面的回复是针对其他提供了日志的修复

你是自建的请提供的配置和日志吧，日志可以复制所有出来，操作前先清理下

**Comment by Jonnyan404** [comment]
```
--------- beginning of main
11-12 20:41:45.540 I/GoLog   (12465): loading core config
11-12 20:41:45.541 I/GoLog   (12465): Preparing Domain: 43.2.2.87:443
11-12 20:41:45.541 I/GoLog   (12465): Prepare Result:
11-12 20:41:45.541 I/GoLog   (12465):  Domain: 43.2.2.87
11-12 20:41:45.541 I/GoLog   (12465):  Port: 443
11-12 20:41:45.541 I/GoLog   (12465):  IPs: [43.2.2.87]
11-12 20:41:45.607 I/GoLog   (12465): infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: aes-256-cfb
11-12 20:41:45.607 D/com.v2ray.ang(12465): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: aes-256-cfb

```

查了一下，这个是因为xray高版本移除了此加密方式，但是mihomo内核是支持的.

**Comment by 2dust** [comment]
> ```
> --------- beginning of main
> 11-12 20:41:45.540 I/GoLog   (12465): loading core config
> 11-12 20:41:45.541 I/GoLog   (12465): Preparing Domain: 43.2.2.87:443
> 11-12 20:41:45.541 I/GoLog   (12465): Prepare Result:
> 11-12 20:41:45.541 I/GoLog   (12465):  Domain: 43.2.2.87
> 11-12 20:41:45.541 I/GoLog   (12465):  Port: 443
> 11-12 20:41:45.541 I/GoLog   (12465):  IPs: [43.2.2.87]
> 11-12 20:41:45.607 I/GoLog   (12465): infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: aes-256-cfb
> 11-12 20:41:45.607 D/com.v2ray.ang(12465): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: unknown cipher method: aes-256-cfb
> ```
> 
> 查了一下，这个是因为xray高版本移除了此加密方式，但是mihomo内核是支持的.

aes-256-cfb，几年前就从v2ray中移除了，可以换一个加密或换一个app
