### ISSUE TITLE
bug: clear real delay test results automatically

### ISSUE THREAD

**Issue by soundsnow** [2dust/v2rayNG#3910]
After updating to the latest version, every time I open the app, it will automatically prompt "data migration successful!" and clear all the "real delay" test results, causing me to re-check "real delay" every time I open the app.
更新到最新版本之后，每次打开APP都会自动提示“数据迁移成功！”并且清除所有“真实延迟”的测试结果，导致我每次打开APP都要重新检查“真实延迟”。

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/commit/6914b9ee1bce6a57bf26737d7565d49648e913a1
