### ISSUE TITLE
duplicate servers after update v2rayng 1.9.10 from 1.9.15

### ISSUE THREAD

**Issue by ssmetall** [2dust/v2rayNG#3915]
From version 1.9.10 to now, which is 1.9.15, after every update of the v2rayng version and opening the v2rayng, a data migration message appears and all servers become duplicates And when we update the subscription, the duplicates disappear. What is the problem? Please fix it.

**Comment by 2dust** [comment]
Handle it yourself
The data has been generated and the app will not delete it for you

**Comment by sssagsag** [comment]
I don't understand what you mean, now I have 13 servers in the json subscription, and every new update that comes for v2rayng will increase to 26 servers after installation.  And I have to update the server so that 13 duplicate servers are deleted

**Comment by ssmetall** [comment]
> Handle it yourself The data has been generated and the app will not delete it for you

I don't understand what you mean, now I have 13 servers in the json subscription, and every new update that comes for v2rayng will increase to 26 servers after installation. And I have to update the server so that 13 duplicate servers are deleted
