### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3920]
W/com.v2ray.ang(13264): type=1400 audit(0.0:40024): avc:  denied  { read } for  name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=426 scontext=u:r:untrusted_app:s0:c60,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 21:34:33.509 D/com.v2ray.ang(13264): MiuiProcessManagerServiceStub setSchedFifo

Using CollectorTypeCMC GC.
11-11 21:34:33.278 E/com.v2ray.ang(13264): Not starting debugger since process cannot load the jdwp agent.
11-11 21:34:33.368 W/com.v2ray.ang(13264): type=1400 audit(0.0:40024): avc:  denied  { read } for  name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=426 scontext=u:r:untrusted_app:s0:c60,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-11 21:34:33.509 D/com.v2ray.ang(13264): MiuiProcessManagerServiceStub setSchedFifo
11-11 21:34:49.272 W/com.v2ray.ang(13264): Missing inline cache for void android.view.InputEventManagerImpl.logOnInputEvent(android.view.InputEvent, java.lang.String)

Hi
Whats problem?!
Is it bug?!
@2dust @CodeWithTamim

**Comment by CodeWithTamim** [comment]
In general, these messages are typical for apps that may be attempting operations restricted by the device’s security settings, especially on devices with customized ROMs like MIUI. Unless it’s causing actual functional issues, they may be safe to ignore.

**Comment by ghost** [comment]
> In general, these messages are typical for apps that may be attempting operations restricted by the device’s security settings, especially on devices with customized ROMs like MIUI. Unless it’s causing actual functional issues, they may be safe to ignore.

Thanks
Pr also check if possible

**Comment by ghost** [comment]
> W/com.v2ray.ang(13264): type=1400 audit(0.0:40024): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=426 scontext=u:r:untrusted_app:s0:c60,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang 11-11 21:34:33.509 D/com.v2ray.ang(13264): MiuiProcessManagerServiceStub setSchedFifo
> 
> Using CollectorTypeCMC GC. 11-11 21:34:33.278 E/com.v2ray.ang(13264): Not starting debugger since process cannot load the jdwp agent. 11-11 21:34:33.368 W/com.v2ray.ang(13264): type=1400 audit(0.0:40024): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=426 scontext=u:r:untrusted_app:s0:c60,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang 11-11 21:34:33.509 D/com.v2ray.ang(13264): MiuiProcessManagerServiceStub setSchedFifo 11-11 21:34:49.272 W/com.v2ray.ang(13264): Missing inline cache for void android.view.InputEventManagerImpl.logOnInputEvent(android.view.InputEvent, java.lang.String)
> 
> Hi Whats problem?! Is it bug?! @2dust @CodeWithTamim

@2dust
