### ISSUE TITLE
小米手机都显示不兼容

### ISSUE THREAD

**Issue by heiniao998** [2dust/v2rayNG#3925]
这个原因是手机原因还是软件原因
下载了64版本
86版本 都是不兼容 见鬼了
这垃圾小米手机

![8857](https://github.com/user-attachments/assets/e63d9a52-7876-453d-a849-f0cfcb420341)

**Comment by neduic** [comment]
> 这个原因是手机原因还是软件原因 下载了64版本 86版本 都是不兼容 见鬼了 这垃圾小米手机
> 
> ![8857](https://private-user-images.githubusercontent.com/50224856/385180353-e63d9a52-7876-453d-a849-f0cfcb420341.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDcyNDUsIm5iZiI6MTczMTQwNjk0NSwicGF0aCI6Ii81MDIyNDg1Ni8zODUxODAzNTMtZTYzZDlhNTItNzg3Ni00NTNkLWE4NDktZjBjZmNiNDIwMzQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYjY5NmUwM2M4YmFhMTc4YzVhYTlmOWYyYjZlMzE2MmY4YzNhYTYwYjQ0MjFlMGU4MWQwYWQ1ZGU3MjhiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OUrwHROfPoiM-MJD6Tg9PMbdbSr7aTXh-flLCb7quZE)

你下载的是arm64v8a的版本吗

**Comment by neduic** [comment]
> 这个原因是手机原因还是软件原因 下载了64版本 86版本 都是不兼容 见鬼了 这垃圾小米手机
> 
> ![8857](https://private-user-images.githubusercontent.com/50224856/385180353-e63d9a52-7876-453d-a849-f0cfcb420341.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDc1NTksIm5iZiI6MTczMTQwNzI1OSwicGF0aCI6Ii81MDIyNDg1Ni8zODUxODAzNTMtZTYzZDlhNTItNzg3Ni00NTNkLWE4NDktZjBjZmNiNDIwMzQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YjNhNDRlMjJiNTk0NzE0MWM3Nzc2NGFlZmVjMzBiYmU2OGZiYThjYTJkYTk0ZDhjMzk0OGZiMmM5NGVkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tRe8uFU7yw9xsoqVSdMTM5kcHt_Qg0cYd6mqInhUlKM)

你下载的是arm64v8a的版本吗，手机要下载arm64v8a的版本

**Comment by heiniao998** [comment]
> > 这个原因是手机原因还是软件原因 下载了64版本 86版本 都是不兼容 见鬼了 这垃圾小米手机
> > ![8857](https://private-user-images.githubusercontent.com/50224856/385180353-e63d9a52-7876-453d-a849-f0cfcb420341.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDc1NTksIm5iZiI6MTczMTQwNzI1OSwicGF0aCI6Ii81MDIyNDg1Ni8zODUxODAzNTMtZTYzZDlhNTItNzg3Ni00NTNkLWE4NDktZjBjZmNiNDIwMzQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YjNhNDRlMjJiNTk0NzE0MWM3Nzc2NGFlZmVjMzBiYmU2OGZiYThjYTJkYTk0ZDhjMzk0OGZiMmM5NGVkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tRe8uFU7yw9xsoqVSdMTM5kcHt_Qg0cYd6mqInhUlKM)
> 
> 你下载的是arm64v8a的版本吗，手机要下载arm64v8a的版本

好了 我下载下边的那两个APK  怎么装都不对 ！多谢了
