### ISSUE TITLE
MIUI12新版控制中心快捷开关无法使用

### ISSUE THREAD

**Issue by AEHURH** [2dust/v2rayNG#393]
![Screenshot_2020-04-29-16-46-49-637_com miui home](https://user-images.githubusercontent.com/37244641/80577201-10eda480-8a39-11ea-83a7-2ae9568156c9.jpg)

**Comment by niceguycc** [comment]
右上角编辑

**Comment by AEHURH** [comment]
> 右上角编辑

怎么编辑？编辑了也没用啊

**Comment by niceguycc** [comment]
> > 右上角编辑
> 
> 怎么编辑？编辑了也没用啊
点右上角的那个像笔一样的按钮，再添加开关，第一次开着v2点了可能没反应，是灰色的，退出v2一次就可以了

**Comment by AEHURH** [comment]
> > > 右上角编辑
> > 
> > 
> > 怎么编辑？编辑了也没用啊
> > 点右上角的那个像笔一样的按钮，再添加开关，第一次开着v2点了可能没反应，是灰色的，退出v2一次就可以了

没看懂你说的什么意思，是开着添加还是还是怎么着？

**Comment by ferryman11** [comment]
楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢

**Comment by AEHURH** [comment]
> 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢

我是11开发版升上来的，数据没清，所以没弹窗，也就没这个问题

**Comment by ghost** [comment]
> 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢

蛋疼的一笔！

**Comment by AEHURH** [comment]
> 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢

我去小米社区搜了下，有人发帖下面评论说重启几次就好了，重启直接打开应用，或者全面屏切换三大金刚键再切回来，仅供参考，我不知道有没有用

**Comment by AEHURH** [comment]
> > 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢
> 
> 蛋疼的一笔！

我上面发的你看看

**Comment by ghost** [comment]
> > 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢
> 
> 我去小米社区搜了下，有人发帖下面评论说重启几次就好了，重启直接打开应用，或者全面屏切换三大金刚键再切回来，仅供参考，我不知道有没有用

果然是全面屏优化问题，可以了谢谢你！

**Comment by ferryman11** [comment]
> > 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢
> 
> 我去小米社区搜了下，有人发帖下面评论说重启几次就好了，重启直接打开应用，或者全面屏切换三大金刚键再切回来，仅供参考，我不知道有没有用

谢谢！解决了

**Comment by parcool** [comment]
这个软件的适配问题，跟MIUI没啥关系

**Comment by AEHURH** [comment]
> 这个软件的适配问题，跟MIUI没啥关系

那怎么解决，作者都不知道看没看到这条

**Comment by kltk** [comment]
> > 楼主我想问一下在第一次运行的时候给你发请求网络连接的弹窗，但我点不了确认，你是怎么解决的呢
> 
> 我去小米社区搜了下，有人发帖下面评论说重启几次就好了，重启直接打开应用，或者全面屏切换三大金刚键再切回来，仅供参考，我不知道有没有用

谢谢！切换全面屏可以。
----
确认不让点，取消可以点~感觉不是bug呢
