### ISSUE TITLE
能否像ssr一样加一个开关的活动？

### ISSUE THREAD

**Issue by Mr54233** [2dust/v2rayNG#394]
加一个ssr类似的活动可以直接从类似xposed edge的软件中启动，这样就能做到双击打开v2ray了
做一个桌面小部件也行，也能从这里调用这个开关
![Screenshot_2020-04-29-19-53-54-830_com jozein xedgepro](https://user-images.githubusercontent.com/46802509/80602683-fbd93b80-8a61-11ea-92de-01f90d1c1291.jpg)

**Comment by yuhan6665** [comment]
Try TaskerActivity

**Comment by Mr54233** [comment]
> Try TaskerActivity

i tried，but i think it not convenience enough

**Comment by yuhan6665** [comment]
Add widget in #453

**Comment by SekiBetu** [comment]
你是指这种功能吗？安卓自带的啊，V2rayN已经集成到安卓的服务里了，不需要打开APP，点一下即可
![image](https://user-images.githubusercontent.com/38283893/88457495-9e913280-ce76-11ea-86bb-858744d3b2b1.png)

**Comment by Mr54233** [comment]
> 你是指这种功能吗？安卓自带的啊，V2rayN已经集成到安卓的服务里了，不需要打开APP，点一下即可
> ![image](https://user-images.githubusercontent.com/38283893/88457506-b799e380-ce76-11ea-8f3e-5a718900ff7a.png)

这个是磁贴，我要的是像ssr一样的“activity”，能直接调用的那种，或者桌面小部件，这样就能不用像你这样打开控制栏，通过手势就能直接打开了

**Comment by yuhan6665** [comment]
@Mr54233 for activity you can also try ScSwitchActivity. Also the 桌面小部件 is added in latest versions
