### ISSUE TITLE
请问大大在后续版本有计划追加sing-box内核吗？

### ISSUE THREAD

**Issue by kissnature** [2dust/v2rayNG#3944]
PC端用的也是大大的V2RayN，支持sing-box并且可以自己选择一些节点设置最低延迟或负载均衡模式。

想知道大大在未来版本是否有计划把这些功能也加到Android端的V2RayNG里。

目前理论上也是支持hy2节点的？（因为看到更新描述里有hy2相关功能的描述。）不过我的梯子里的hy2节点好像看不到。（用sing-box内核的客户端或电脑版V2RayN的时候都能正常使用。）

**Comment by 2dust** [comment]
没有计划换
