### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3945]
common/mux: failed to fetch all input > io: read/write on closed pipe
11-15 08:20:24.930 I/GoLog   (24504): [Info] [104668635] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
11-15 08:20:29.557 I/GoLog   (24504): [Info] common/mux: failed to read metadata > io: read/write on closed pipe
11-15 08:20:30.561 I/GoLog   (24504): [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > context canceled

common/mux: dispatching request to tcp:mtalk.google.com:5228
11-15 08:06:44.592 I/GoLog   ( 8297): [Info] common/mux: failed to read metadata > io: read/write on closed pipe
11-15 08:06:45.595 I/GoLog   ( 8297): [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > context canceled
11-15 08:06:46.747 I/GoLog   ( 8297): [Info] common/mux: failed to read metadata > io: read/write on closed pipe
11-15 08:06:47.748 I/GoLog   ( 8297): [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > context canceled

Using CollectorTypeCMC GC.
11-15 08:01:57.767 E/com.v2ray.ang(10339): Not starting debugger since process cannot load the jdwp agent.
11-15 08:01:57.823 W/com.v2ray.ang(10339): type=1400 audit(0.0:5129): avc:  denied  { read } for  name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=426 scontext=u:r:untrusted_app:s0:c60,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang
11-15 08:01:57.929 D/com.v2ray.ang(10339): MiuiProcessManagerServiceStub setSchedFifo
11-15 08:02:02.539 I/com.v2ray.ang(10339): Settings ViewModel is cleared

Hello,Don't be tired, dear, What is the meaning of these types of errors, are they solvable?

**Comment by ghost** [comment]
Hi
Please add commit below same v2rayn
https://github.com/2dust/v2rayN/commit/04efed2079caba7adb32244f4df7dea39147f498
https://github.com/2dust/v2rayN/commit/b8a0293b52ea30b295055afdb89da2c5f6c47f57
https://github.com/2dust/v2rayN/commit/d781c768e9f0bd4de9eef4ea67018d1419afb9d2
Thanks
@2dust

**Comment by 2dust** [comment]
hi
We still have formal jobs 
We will update as long as we have time, please don't rush

**Comment by ghost** [comment]
> common/mux: failed to fetch all input > io: read/write on closed pipe 11-15 08:20:24.930 I/GoLog (24504): [Info] [104668635] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled 11-15 08:20:29.557 I/GoLog (24504): [Info] common/mux: failed to read metadata > io: read/write on closed pipe 11-15 08:20:30.561 I/GoLog (24504): [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > context canceled
> 
> common/mux: dispatching request to tcp:mtalk.google.com:5228 11-15 08:06:44.592 I/GoLog ( 8297): [Info] common/mux: failed to read metadata > io: read/write on closed pipe 11-15 08:06:45.595 I/GoLog ( 8297): [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > context canceled 11-15 08:06:46.747 I/GoLog ( 8297): [Info] common/mux: failed to read metadata > io: read/write on closed pipe 11-15 08:06:47.748 I/GoLog ( 8297): [Info] common/mux: failed to handler mux client connection > proxy/vless/outbound: connection ends > context canceled
> 
> Using CollectorTypeCMC GC. 11-15 08:01:57.767 E/com.v2ray.ang(10339): Not starting debugger since process cannot load the jdwp agent. 11-15 08:01:57.823 W/com.v2ray.ang(10339): type=1400 audit(0.0:5129): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=426 scontext=u:r:untrusted_app:s0:c60,c257,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0 app=com.v2ray.ang 11-15 08:01:57.929 D/com.v2ray.ang(10339): MiuiProcessManagerServiceStub setSchedFifo 11-15 08:02:02.539 I/com.v2ray.ang(10339): Settings ViewModel is cleared
> 
> Hello,Don't be tired, dear, What is the meaning of these types of errors, are they solvable?

@2dust

**Comment by ghost** [comment]
> hi We still have formal jobs We will update as long as we have time, please don't rush

Thanks

**Comment by 2dust** [comment]
There's key information in the error report mux
If you can't use mux, close it and try again.

**Comment by ghost** [comment]
![Screenshot_۲۰۲۴-۱۱-۱۷-۰۹-۵۰-۴۵-۵۶۹_com v2ray ang-edit](https://github.com/user-attachments/assets/6c871231-131a-4a28-ac13-e8b30b60ce10)
![Screenshot_۲۰۲۴-۱۱-۱۷-۰۹-۵۳-۱۲-۱۹۷_com v2ray ang-edit](https://github.com/user-attachments/assets/3748bac4-6928-4d4a-9399-cf31fc7fc4d2)
![Screenshot_۲۰۲۴-۱۱-۱۷-۰۹-۵۶-۳۸-۹۴۹_com v2ray ang-edit](https://github.com/user-attachments/assets/af7b9aa5-06c2-4a3c-9535-890fe42ab71a)
Error again
I have these errors
@2dust

**Comment by ghost** [comment]
> Task :app:compileDebugKotlin
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/extension/_Ext.kt:98:1 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of function types.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/handler/V2rayConfigManager.kt:243:17 Condition is always 'true'.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/plugin/PluginManager.kt:225:76 'fun get(p0: String!): Any?' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/plugin/ResolvedPlugin.kt:36:78 'field versionCode: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/service/V2RayServiceManager.kt:352:17 'fun stopForeground(p0: Boolean): Unit' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/MainActivity.kt:389:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/MainActivity.kt:409:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/MainActivity.kt:428:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/MainRecyclerAdapter.kt:146:65 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/RoutingEditActivity.kt:98:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/RoutingSettingActivity.kt:105:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/RoutingSettingActivity.kt:134:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/ServerActivity.kt:601:61 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/ServerCustomConfigActivity.kt:109:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/SubEditActivity.kt:116:53 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/UserAssetActivity.kt:336:57 'static field no: Int' is deprecated. Deprecated in Java.
w: file:///home/runner/work/v2rayNG/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/ui/UserAssetUrlActivity.kt:119:53 'static field no: Int' is deprecated. Deprecated in Java.


> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libbarhopper_v3.so, libgojni.so, libimage_processing_util_jni.so, libmmkv.so, libtun2socks.so.

Process build apk 
@2dust @CodeWithTamim
