### ISSUE TITLE
New Feature In App

### ISSUE THREAD

**Issue by codewithtamim** [2dust/v2rayNG#3946]
Hi,
I have a feature idea to allow users to host a SOCKS or HTTP server directly on their phone, eliminating the need for an external server. This would enable users to share their proxy setup with others seamlessly.
What do you think of this idea? Do you find it relevant and useful?

Thanks!

**Comment by 2dust** [comment]
Do you want to open a server similar to FTP on the app so that users can manage it through this service?
This is not the target function of this app

**Comment by codewithtamim** [comment]
> Do you want to open a server similar to FTP on the app so that users can manage it through this service? This is not the target function of this app

Nope, its like for VPN service not ftp. We suppose create a socks 5 proxy  and share with friends so they can use proxy through our router, some maybe someone left home but needs to use internet from his home wifi he can use old phone of his to host a server there is very less apps with this feature.

**Comment by 2dust** [comment]
This is not the target function of this app
You can develop a new app to implement this function

**Comment by codewithtamim** [comment]
> This is not the target function of this app You can develop a new app to implement this function

k
