### ISSUE TITLE
去除当前组重复配置好像无效

### ISSUE THREAD

**Issue by wukan1986** [2dust/v2rayNG#3948]
之前用的1.8.39版本，订阅了某个源，每次能去重10条。
最近更新成了1.9.13版，每次去重0条，还以为源服务质量变好了。

今天偶然发现排序后，前几条的IP和端口很像，点开编辑一看，的确除了别名，其他都一样。
所以我又降级成1.8.39版，又能成功去重12条。

**Comment by wukan1986** [comment]
我怀疑是 https://github.com/2dust/v2rayN/discussions/5951 这个地方引入的bug

**Comment by 2dust** [comment]
1.9.x版本的对比确实修改过，现在对比是会比较所有的参数的包括别名
这个会影响使用吗？不影响就暂时不处理了

**Comment by wukan1986** [comment]
建议比较时忽略别名。因为连接服务器时别名是用不到的。

您可以用`https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt`测试，每次有10~12条重复。

**Comment by wukan1986** [comment]
我发现1.8.39版其实也有参数相同别名不同没有被剔除重复的现像。不过总体上比1.9.13一条都剔除不了要好很多
