### ISSUE TITLE
能否支持App内导入证书？

### ISSUE THREAD

**Issue by okudayukiko** [2dust/v2rayNG#395]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
能否支持App内导入证书（.crt，.p12或.pfx），部分手机厂商的Android如果往系统证书储存区导入自签名证书，手机总是出现“不安全”提示，除非删掉自签名证书。
Android系统的证书设置。
![Screenshot](https://user-images.githubusercontent.com/17502357/80669054-0c2afe00-8ad6-11ea-9f35-d4ec17903ae5.jpg)
下图是某VPN App的导入证书功能。
![Screenshot](https://user-images.githubusercontent.com/17502357/80642129-8341a180-8a98-11ea-8214-d2e7f6d19849.jpg)
### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Samsung Android 10

**Comment by yuhan6665** [comment]
#380 submitted to address this
