### ISSUE TITLE
A new idea/feature to show contributos on app about page

### ISSUE THREAD

**Issue by codewithtamim** [2dust/v2rayNG#3951]
Hi,

I had an idea to enhance the app by adding a contributors list feature. 

The idea is to display the profile pictures of contributors, and when users long-press on a profile picture, a tooltip with additional details about the contributor would appear. This feature is inspired by apps like [AndroidIDE](https://github.com/AndroidIDEOfficial/AndroidIDE), which has a similar functionality.

What do you think about this feature? Do you feel it would be an important addition to the app? 

Thanks!

**Comment by 2dust** [comment]
This feature can be done, but it's not very useful and a waste of your time

**Comment by codewithtamim** [comment]
> This feature can be done, but it's not very useful and a waste of your time

I have time until death. Will do pr
