### ISSUE TITLE
请问可以出一个功能让配置文件保存在别的目录吗？

### ISSUE THREAD

**Issue by CCCCCCCCCC333** [2dust/v2rayNG#3953]
由于国产安卓TV系统普遍不给第三方应用访问DATA文件夹的权限，所以即便成功安装了v2rayng，输入了订阅链接也无法下载成配置文件（链接没问题）。导致无法使用
我想也许不要把配置文件放在data下面，而是自定义比如就放在根目录下，或许就可以用了

**Comment by 2dust** [comment]
系统限制了，不允许存放到其他目录

**Comment by 2dust** [comment]
不管什么系统，应用内存储都是可以的
你的问题是订阅无法下载，这个和存储无关，你把订阅先在浏览器打开，然后复制内容进去看看

**Comment by CCCCCCCCCC333** [comment]
感谢，已经解决了！
