### ISSUE TITLE
新版本在开启dot之后出现dns泄露

### ISSUE THREAD

**Issue by xzlosats111** [2dust/v2rayNG#3958]
### 预期行为
所有DNS请求走代理端绕过系统dot

### 实际行为
之前1.8.几版本时，系统开启腾讯dot后，连接未出现DNS泄露,
更新后没有动设置，发现出现dns泄露，同时有的走代理有的走腾讯的
关闭dot后不再出现dns泄露

### 复现方法
不知道为什么之前可以绕过系统dot，现在尝试拦截853端口会导致直接无法上网
没法一直挂着代理，平常还是有开dot的需求的，一直开关太麻烦

**Comment by xzlosats111** [comment]
不知道为什么，虽然IPleak测出来有DNS泄露，显示是腾讯dot国内的节点，但是应该已经用了挺长一段时间了，没有发现DNS污染
现在尝试把853端口直接写成走代理，用腾讯dot国外的节点，暂时没有发现什么问题，分流什么的，先凑合用吧

**Comment by 2dust** [comment]
dns泄露app无法处理，抱歉

**Comment by VahidRafieiPour** [comment]
Cabn you spic person plieez
