### ISSUE TITLE
关于安卓TV的安装问题

### ISSUE THREAD

**Issue by Aerytgophilis** [2dust/v2rayNG#396]
家里是索尼的KD55X7066D,8.0.0系统，尝试安装apk pure上下载的安装包，加载后提示未安装应用，我想知道是不是只有我自己是这样的一种情况？

**Comment by ghost** [comment]
是国行电视机吗？如果是的话下载最旧的的版本（例如1.0.1）再试试。可能会解决你遇到的问题，不过因此一些新版本的特性就无法使用了。

**Comment by yuhan6665** [comment]
@Aerytgophilis  I found apk pure downloads ARM64 by default. Your TV probably is not ARM64. Please check your device or try universal version:
https://github.com/2dust/v2rayNG/releases/download/1.2.6/v2rayNG_1.2.6.apk
