### ISSUE TITLE
无法 正确更新版本   

### ISSUE THREAD

**Issue by Super1Windcloud** [2dust/v2rayNG#3963]
##  无法正确更新版本  

#  重启之后 版本没有变化 , 还是6.55  下载的7.0.9 最新版本 

![图片](https://github.com/user-attachments/assets/21b883ed-c527-437a-a014-a78f729a4659)
  

![图片](https://github.com/user-attachments/assets/fb973133-405f-439f-8bfd-ffd78bff8aa3)

**Comment by 2dust** [comment]
虽然你发错地方了
跨版本更新容易出问题，这个时候手工更新一次吧

**Comment by VahidRafieiPour** [comment]
![۲۰۲۴۱۰۲۶_۱۸۱۰۳۷](https://github.com/user-attachments/assets/1de63ece-4f16-40ec-9ed0-841012f702b9)
![pwa9c4X_w1080_h2340_s3119846](https://github.com/user-attachments/assets/64fa65f6-d9c4-413f-83f2-ad2149bcfb1a)
![17318964932903279027041321161282](https://github.com/user-attachments/assets/be1f5141-46b2-4e32-9c56-996ddffcdce4)
![sojud ir  General-soleimani4chafye_com-853x1024](https://github.com/user-attachments/assets/d1466608-4f8e-402c-a90d-1e1f2442810d)

https://github.com/user-attachments/assets/3f1dcd10-75d3-4470-8ed4-38fd348b586f
