### ISSUE TITLE
A long time unimportant question.

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#3973]
Click Set for the first time and return to Set Remote DNS.The other text classes also have problems.Multiple invalid resource IDs 0x00000000 are displayed in the debug mode of Logcat.Seems like from 1.2.0.

**Comment by 2dust** [comment]
config and logs？

**Comment by ghost** [comment]
> config and logs？
Sorry, I mischaracterized it.an error message is displayed when options you need to change then open the dialog box displayed on the setting page. 
such as remote dns.But the change is successful, so it not important.
~ $ adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main
--------- beginning of main
11-20 16:27:40.805 21741 21750 I com.v2ray.ang: _Desupression native alloc  gc_urgency: 42626expectation: 895146 native bytes: 38394743
11-20 16:28:15.207 21741 21741 I com.v2ray.ang: Settings ViewModel is cleared
11-20 16:28:24.422 21741 21750 I com.v2ray.ang: _Desupression native alloc gc_urgency: 71310 native bytes: 35099247
11-20 16:28:28.172 21741 21741 I com.v2ray.ang: _Desupression native alloc gc_urgency: 71123 native bytes: 34844287
11-20 16:28:29.437 21741 21741 I com.v2ray.ang: _Desupression native alloc  gc_urgency: 50539expectation: 116339 native bytes: 36787315
11-20 16:28:34.425 21741 21741 I com.v2ray.ang: _Desupression native alloc gc_urgency: 70776 native bytes: 42214983
11-20 16:28:36.589 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.589 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.590 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.590 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.590 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.590 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.590 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.590 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.591 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:28:36.591 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.330 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.330 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.330 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:01.331 21741 21741 E com.v2ray.ang: Invalid resource ID 0x00000000.
11-20 16:29:15.342 21741 21750 I com.v2ray.ang: _Desupression native alloc  gc_urgency: 49510expectation: 940690 native bytes: 39113111
