### ISSUE TITLE
ActivityNotFoundException: Unable to find explicit activity class com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog

### ISSUE THREAD

**Issue by CNTeslatrooper** [2dust/v2rayNG#3978]
### 预期行为
点击节点，运行，连接

### 实际行为
点击节点，闪退

### 复现方法
尝试更换节点、启用禁用本地DNS、启用禁用分应用代理，仍然闪退

### 日志信息
<details>
--------- beginning of system
--------- beginning of main
11-18 22:54:17.447 D/AndroidRuntime(22891): Shutting down VM
11-18 22:54:17.457 E/AndroidRuntime(22891): FATAL EXCEPTION: main
11-18 22:54:17.457 E/AndroidRuntime(22891): Process: com.v2ray.ang, PID: 22891
11-18 22:54:17.457 E/AndroidRuntime(22891): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}; have you declared this activity in your AndroidManifest.xml?
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1855)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1546)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.app.Activity.startActivityForResult(Activity.java:4284)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.kt:704)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:244)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at androidx.activity.ComponentActivity$activityResultRegistry$1.onLaunch(ComponentActivity.kt:225)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at androidx.activity.result.ActivityResultRegistry$register$2.launch(ActivityResultRegistry.kt:137)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.kt:37)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at com.v2ray.ang.ui.MainActivity.onCreate$lambda$2(MainActivity.kt:95)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at com.v2ray.ang.ui.MainActivity.$r8$lambda$5_AhYbKjoA0eiKRx41ZZnUkXZWs(MainActivity.kt)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at com.v2ray.ang.ui.MainActivity$$ExternalSyntheticLambda5.onClick(D8$$SyntheticClass:0)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.view.View.performClick(View.java:5698)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.view.View$PerformClick.run(View.java:22557)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.os.Handler.handleCallback(Handler.java:739)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.os.Looper.loop(Looper.java:158)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at android.app.ActivityThread.main(ActivityThread.java:7238)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at java.lang.reflect.Method.invoke(Native Method)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
11-18 22:54:17.457 E/AndroidRuntime(22891): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</details>

### 环境信息
机型三星SM-A9100
系统Android 6.0.1
已解锁Bootloader 已Root 使用SuperSU
获取SU权限的应用仅有ACCA BusyBox ViperFX

### 额外信息（可选）
古董机器，老家地里挖出来的
后续更换为Magisk仍然闪退

**Comment by CNTeslatrooper** [comment]
解决了，不是V2rayNG的问题。
三星SM-A9100作为大陆特供机型，移除了VPN功能的API
通过恢复vpndialog.apk解决了闪退问题

**Comment by 2265290305** [comment]
> 解决了，不是V2rayNG的问题。 三星SM-A9100作为大陆特供机型，移除了VPN功能的API 通过恢复vpndialog.apk解决了闪退问题

怎么恢复啊
