### ISSUE TITLE
最新版本不再支持在安卓4.4.2上安装了么？

### ISSUE THREAD

**Issue by naogula** [2dust/v2rayNG#3992]
用adb install安装v2rayNG_1.9.6_armeabi-v7a.apk的时候报错：
Failure [INSTALL_FAILED_OLDER_SDK]
安卓版本是4.4.2
但是安装v2rayNG_1.2.3_armeabi-v7a.apk是可以正常安装的，但是1.2.3版本不支持vless节点。。。
不知道哪个版本能支持vless节点又可以装在4.4.2的安卓上？

**Comment by 2dust** [comment]
你找下1.8.0版本试一试

**Comment by naogula** [comment]
> 你找下1.8.0版本试一试

1.8.0也不行，1.7.0也不行，试到1.6.0，可以安装了，也支持vless节点，问题解决了。多谢！
