### ISSUE TITLE
Per-app proxy doesn't works on Quora, Reddit, PlayStore

### ISSUE THREAD

**Issue by sysescool** [2dust/v2rayNG#3993]
I'm using V2rayNG v1.9.9 (Lib v27, Xray-core v24.10.16)

I have installed Quora, Reddit, Telegram, Play Store.

### 预期行为

1. Open Per-app proxy(分应用代理)
2. select Quora, Reddit, Telegram, Play Store.
3. All of them access net through proxy.

### 实际行为

Only Telegram works.
Quora, Reddit, Play Store doesn't works.

### 复现方法
1. Open Per-app proxy
2. select Quora, Reddit, Telegram, Play Store.
3. start a proxy node.
4. Open Quora, Reddit, Play Store to test.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息

V2rayNG v1.9.9 (Lib v27, Xray-core v24.10.16)

### 额外信息（可选）

XiaoMi 15

### What I try

I try to close all the options in Routing Settings, but it doesn't works.

I'm looking for `Predefined rules: Global Proxy`
![Screenshot from 2024-11-20 11-11-18](https://github.com/user-attachments/assets/3f6e8f10-d7a9-4f4d-9682-19ed65edd4a6)

But there's no this option in the v1.9.9 app.

**Comment by 2dust** [comment]
分应用代理启用后，你可以设置路由规则为全局即可
