### ISSUE TITLE
华为手机v2rayNG配置vmess报错io:read/write on closed pipe

### ISSUE THREAD

**Issue by lumoshhx** [2dust/v2rayNG#3994]
华为手机
v2rayNG最新版1.9.16
配置vmess
报错io:read/write on closed pipe
但在ios上运行正常
请教如何解决该问题？

**Comment by Leao9203** [comment]
换手机解决100%问题。

**Comment by KrisCenGH** [comment]
[#3129](https://github.com/2dust/v2rayNG/issues/3129)
开启设置-进阶设置，跳过证书验证，然后重新更新一次订阅
