### ISSUE TITLE
请教一个技术问题

### ISSUE THREAD

**Issue by leetomlee123** [2dust/v2rayNG#3996]
我参考你的so文件启动方法 在debugger情况下可以执行成功  但是release模式下
` java.io.IOException: Cannot run program "/data/app/~~YxrgSgM30wXb9o9v_lr4zQ==/com.example.wx_reader-KkaJrsiH9Mvh6ofwIwbnDA==/lib/arm64/net.so" (in directory "/data/user/0/com.example.wx_reader/files"): error=2, No such file or directory
11-20 13:28:35.925 21619 21668 E ProxyServiceImpl: Unexpected error:`
net.so 是一个golang交叉编译得来的 
![image](https://github.com/user-attachments/assets/acdbc177-4940-40ee-8ce3-28b6142d0c21)
打开release包 也发现打包进去了

`            Log.d(TAG, "Starting Go Proxy...")
            val context = applicationContext
//            val execPath = context.getDir("libs", Context.MODE_PRIVATE).absolutePath + "/net.so"
            val execPath =   File(context.applicationInfo.nativeLibraryDir, "net.so").absolutePath

            try {
                val proBuilder = ProcessBuilder(execPath, "-p", "4568")
                proBuilder.redirectErrorStream(true)
                process = proBuilder
                    .directory(context.filesDir)
                    .start()

                CoroutineScope(Dispatchers.IO).launch {
                    Thread.sleep(50L)
                    Log.d(TAG, "runProcess check")
                    process?.waitFor()
                    Log.d(TAG, "runProcess exited")
                }
                Log.d(TAG, process.toString())

            } catch (e: Exception) {
                Log.d(TAG, e.toString())
            }`
            
            请指教一下 🙏

**Comment by codewithtamim** [comment]
Add this inside the android block in build.gradle.kts app level module 
```kotlin
 packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

```
this should solve the issue in release.

**Comment by leetomlee123** [comment]
i do ,not works
tks
