### ISSUE TITLE
最新版无法打开vpn连接

### ISSUE THREAD

**Issue by luq885** [2dust/v2rayNG#4]
升级了最新版，无法连上vpn，锤子坚果pro2，系统版本7.1.1，上一个版本还能用，ss客户端可以连上

**Comment by 2dust** [comment]
最新版请标明是哪个版本？可以尝试删除app重装等方式来确认下是什么问题

**Comment by luq885** [comment]
google play上下载的0.2.5版本，更新日期2017年11月23日

**Comment by 2dust** [comment]
0.2.6可能已解决

**Comment by luq885** [comment]
升级了到0.2.6版本还是不行，卸载重新安装也一样

**Comment by 2dust** [comment]
哪个版本是你最后能用的?
如有有条件可以连接pc把日志搞出来或等我后面加入日志查看

**Comment by luq885** [comment]
上次安装的是0.2.4版本可以打开, 感觉应该是锤子系统版本升级造成的, 刚才试过安装0.2.1版本也是一样的错误
另外日志如何导出

**Comment by 2dust** [comment]
搜索下adb logcat
或等我集成UI

**Comment by 2dust** [comment]
测试下0.3.1,里面带有logcat

**Comment by luq885** [comment]
0.3.1版本已经可以用了，锤子系统也升级过，问题解决，多谢
