### ISSUE TITLE
开启代理后断流或国内网站没连接

### ISSUE THREAD

**Issue by Linqing0808** [2dust/v2rayNG#4]
刚开启代理那会还可以用，过一会就断流了

**Comment by Ryan-fai** [comment]
> 刚开启代理那会还可以用，过一会就断流了

用的什么组合的配置？

**Comment by Linqing0808** [comment]
> > 刚开启代理那会还可以用，过一会就断流了
> 
> 用的什么组合的配置？

这个就不知道了，机场给我节点，具体在哪里看也不知道，请告知

**Comment by Hana-ame** [comment]
请检查系统设置里面有没有对应用限制后台。例如省电模式。

**Comment by Linqing0808** [comment]
> 请检查系统设置里面有没有对应用限制后台。例如省电模式。

**Comment by Linqing0808** [comment]
> 請檢查系統設置裡面有沒有對應用限制後台。例如省電模式。

没有，已经检查过了，是程式的问题
