### ISSUE TITLE
关于DNS服务器设置的一些想法

### ISSUE THREAD

**Issue by ChengChung** [2dust/v2rayNG#40]
偶尔会有在服务端通过DNS来做策略路由的需求，因此需要把DNS设置为服务器的某个接口地址（外部可能不可达）
而就之前的观察来看，客户端的DNS设置会被应用于作为连接时服务器地址的查询和连接建立后访问其它页面的地址查询，而对于前者来说，如果将DNS设置为某个外部不可访问的地址会导致连接无法建立
平时多是用ws来连接的，前端一般使用nginx之类的，还需要承载其它的页面访问流量，因此将地址从域名改为IP地址不太可行。
因此如果有可能，希望能将DNS查询分开，查询服务器地址时的DNS通过手机默认的DNS进行查询，而连接后的流量通过设置的DNS来进行，以及如果方便的话，希望能为每条配置分开设置DNS。（这两样似乎也是以前某飞机客户端的做法）

另外的话，传输层使用ws时是否能考虑增加自定义UA字段的功能？

**Comment by 2dust** [comment]
hi,感谢你的建议
但是本app核心功能都依赖lib,所以我也无力做这些功能
