### ISSUE TITLE
Any way to allow Automate app to start/stop the service? 

### ISSUE THREAD

**Issue by bruor** [2dust/v2rayNG#4002]
### Expected behavior
I'm attempting to use Automate by llamalab (https://play.google.com/store/apps/details?id=com.llamalab.automate&referrer=utm_source%3Dhomepage) to start/stop v2ray,  I currently use it to automate wireguard on Android. 

I noticed that there's an app shortcut that allows me to easily start/stop v2ray, and that there's a tasker activity.   I attempted to activate the tasker activity but the pop up window that results doesn't do anything when I click the check box manually. 

If I use Automate I can run com.v2ray.ang.ui.MainActivity and it'll open the app,
but if I call com.v2ray.ang.ui.ScSwitchActivity I get a permission error. 

Is there a way that this activity can be opened up so it can be called?
Alternatively, is there an broadcast I can send to trigger an intent similar to how the wireguard client for android works?

**Comment by 2dust** [comment]
https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid
https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

**Comment by 2dust** [comment]
use Tasker plug-in

**Comment by bruor** [comment]
Wow, I had no idea that Automate could use tasker plugins, works great!

**Comment by ergdfrte** [comment]
thank you ,it's very helpful
