### ISSUE TITLE
路由规则不生效

### ISSUE THREAD

**Issue by awkoo** [2dust/v2rayNG#4012]
路由规则正常设置为跳过，但是没有正确生效，代理vpn配置均正常
![Screenshot_20241121-195921_v2rayNG](https://github.com/user-attachments/assets/ebccf7bd-a9ca-4c40-bf46-5d429a46f062)
![Screenshot_20241121-195553_Chrome](https://github.com/user-attachments/assets/d37f4fdf-d6f8-4491-8dc4-1b660c6e8f70)
![Screenshot_20241121-195546_Chrome](https://github.com/user-attachments/assets/04af1939-d81e-4c71-b871-76dae27c108a)

**Comment by 2dust** [comment]
新添加的规则位于最后面，你是否有移到最上面？

**Comment by wqj6** [comment]
那应该是0-65535干扰了规则，谢谢

**Comment by awkoo** [comment]
那应该是0-65535干扰了规则，谢谢
