### ISSUE TITLE
新增功能探讨

### ISSUE THREAD

**Issue by shandongtlb** [2dust/v2rayNG#4017]
安卓14 oneui6.1.1
目前遇到了点小问题，使用v2rayng全局连接启动后，Google play商店无法连接网络，其他均无问题

使用nekobox这个软件，同样会复现，但是开启下图开关之后一切正常，想问问能不能给v2rayng也增加此类功能啊，谢谢！

![Screenshot_20241122_175838_NekoBox](https://github.com/user-attachments/assets/618abb1c-3468-4d16-8deb-313dc18a9684)

**Comment by 2dust** [comment]
下一版增加，不做参数了，直接把功能加上

**Comment by shandongtlb** [comment]
牛逼大佬
