### ISSUE TITLE
I/O READ WRITE ERROR ON CLOSED PIPE

### ISSUE THREAD

**Issue by JUPITER-KOU** [2dust/v2rayNG#402]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.I/O READ WRITE ERROR ON CLOSED PIPE
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by kexunli** [comment]
遇到一样的问题   更新了最新的 1.2.6  启动服务后 没收数据传输  看下方提示是已连接 点击下方测试连接提示I/O READ WRITE ERROR ON CLOSED PIPE     降级1.2.5 还是一样   然后降级1.2.4  解决问题   服务器没有改动    就1.2.5之后的版本都提示I/O READ WRITE ERROR ON CLOSED PIPE  安卓版本 9

**Comment by pharmcube** [comment]
遇到同样的问题 降级到1.2.4可以解决问题

**Comment by xianren78** [comment]
偶尔遇到这个问题，后来没再遇到

**Comment by lickety** [comment]
我在电脑上可以正常连接的节点,安卓里测速提示I/O READ WRITE ERROR ON CLOSED PIPE
但是依然可以正常使用,只是测试那里显示失败

**Comment by misakaok** [comment]
allowInsecure 选择true就行了 这是服务器用了自签发证书的问题 和客户端没有关系

**Comment by githubxinshou** [comment]
不行  怎么都不行，上面两位说的也是不行，也是报上面同样的错误

**Comment by misakaok** [comment]
重新搭你的v2ray 开启ws 伪装域名那里填解析的域名 然后申请证书 默认allowInsecure=false 直接可以用

**Comment by jqqjj** [comment]
ws+tls，一个服务器，两个域名(两个域名都是通过Nginx转发至同一个v2ray实例)，一个域名是let's encrypt 的证书，一个是cloudflare的证书，后者正常，前者提示I/O READ WRITE ERROR ON CLOSED PIPE(需要allowInsecure 选择true才可以使用)。

**Comment by jqqjj** [comment]
> ws+tls，一个服务器，两个域名(两个域名都是通过Nginx转发至同一个v2ray实例)，一个域名是let's encrypt 的证书，一个是cloudflare的证书，后者正常，前者提示I/O READ WRITE ERROR ON CLOSED PIPE(需要allowInsecure 选择true才可以使用)。

另外亲测，降级到1.2.4可以解决问题

**Comment by starksong** [comment]
同样是pc端一切正常连接，Android上报这个问题  求大佬解惑啊
