### ISSUE TITLE
1.9.9 版本后 Shadowsocks-gRPC-TLS 应用无法使用

### ISSUE THREAD

**Issue by lxhao61** [2dust/v2rayNG#4020]
### 预期行为
测试报错EOF。

### 实际行为
gRPC及TLS配置丢失。

### 复现方法
1.导出配置，发现无gRPC配置及TLS没有启用。
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
升级到最新的1.9.19版本，重新导入一次配置

**Comment by lxhao61** [comment]
> 升级到最新的1.9.19版本，重新导入一次配置

升级到1.9.19版本，重新配置问题依旧。
出错问题见下:
```
      "streamSettings": {
        "network": "tcp",
        "security": ""
      },
```
使用自定义设置后可正常使用。

**Comment by 2dust** [comment]
你是怎么导入的？分享链接？

**Comment by lxhao61** [comment]
就是导出完整配置，修改为正确的，再完整导回去，可正常使用。

**Comment by 2dust** [comment]
我大概明白你的意思了
如果这样，是因为没有考虑会有人用Shadowsocks套传输层，因为 这样的组合并不合适，不过下版给改回来吧。
Shadowsocks 用最简单的方式比较好，要套传输层用vmess和vless

**Comment by lxhao61** [comment]
> 你是怎么导入的？分享链接？
> 

我设置没有使用导入，是删除后直接重新配置。

自定义设置：就是导出完整配置，修改为正确的，再完整导回去，可正常使用。

**Comment by lxhao61** [comment]
> 我大概明白你的意思了
> 如果这样，是因为没有考虑会有人用Shadowsocks套传输层，因为 这样的组合并不合适，不过下版给改回来吧。
> Shadowsocks 用最简单的方式比较好，要套传输层用vmess和vless

是的，但 Shadowsocks-gRPC-TLS 应用有点特殊，可兼容 Shadowsocks 加 v2ray-plugin 或 xray-plugin 插件的 grpc-tls 模式。
