### ISSUE TITLE
无法使用shadowsocks+http伪装的节点

### ISSUE THREAD

**Issue by trTvT** [2dust/v2rayNG#4024]
v2rayn和v2flyng都可以使用，唯独v2rayng无法使用。

**Comment by nortsnow** [comment]
我也有这个问题

**Comment by 2dust** [comment]
给出配置和日志

**Comment by sztkkk** [comment]
确实无法使用ss节点

**Comment by nortsnow** [comment]
退回1.9.9可以使用
________________________________
发件人: sztkkk ***@***.***>
发送时间: Sunday, November 24, 2024 2:30:59 PM
收件人: 2dust/v2rayNG ***@***.***>
抄送: nortsnow ***@***.***>; Comment ***@***.***>
主题: Re: [2dust/v2rayNG] 无法使用shadowsocks+http伪装的节点 (Issue #4024)


确实无法使用ss节点

―

**Comment by lxhao61** [comment]
应该与[我之前报的 BUG 一样](https://github.com/2dust/v2rayNG/issues/4020) ,由同一个问题引起的，等待下一版本吧。

**Comment by nortsnow** [comment]
1.9.20版本已修复

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
