### ISSUE TITLE
tls

### ISSUE THREAD

**Issue by shiyiqw** [2dust/v2rayNG#4031]
我使用了trojan和ss都套了tls没有用但是我用wemess却可以其中的配置我在电脑上可以直接使用
11-24 20:13:45.256 23136 23176 D com.v2ray.ang:measureV2rayDelay:go.Universe $proxyerror：获取“ https://www.gstatic.com/generate_204 ”：io：在封闭管道上读/写
11-24 20:13:45.461 23136 23340 I GoLog ：使用准备好的：我的ip
11-24 20:13:45.462 23136 23159 I GoLog ：来自 udp:127.0.0.1:45812 接受udp:1.1.1.1:53 [袜子 -> 代理]
11-24 20：13：45.462 23136 23342 I GoLog：使用已准备：154.12.37.247
11-24 20：13：45.473 23136 23342 I GoLog：来自 tcp：127.0.0.1：39626 接受 tcp：142.250.69.202：443 [socks -> 代理]
11-24 20:13:45.475 23136 23170 I GoLog : 来自 tcp:127.0.0.1:39610 接受 tcp:142.250.69.202:443 [socks -> 代理]
11-24 20:13:45.601 23136 23159 I GoLog : 来自 udp:127.0.0.1:46554 接受 udp:1.1.1.1:53 [socks -> proxy]
11-24 20:13:45.632 23136 23162 I GoLog : 使用准备好的： 我的ip
11-24 20：13：45.635 23136 23176 D com.v2ray.ang：measureV2rayDelay：go.Universe$proxyerror：获取“ [https://www.google.com/generate_204”：io](https://www.google.com/generate_204)：关闭时读/写pipe
这是我在用木马中的日志，其中我在测试真连接

**Comment by Pterosaur** [comment]
Got a same error on trojan
