### ISSUE TITLE
启动服务失败

### ISSUE THREAD

**Issue by SenTomoHiro** [2dust/v2rayNG#4033]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
启动服务

### 实际行为
启动服务失败

### 复现方法
1.点右下角三角形
2.无法启动，三角形还是灰色
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of main
11-25 15:13:44.279 I/com.v2ray.ang( 2686): Using CollectorTypeCC GC.
11-25 15:13:44.286 E/com.v2ray.ang( 2686): Not starting debugger since process cannot load the jdwp agent.
11-25 15:13:44.613 I/com.v2ray.ang( 2686): Support FEAS: false
11-25 15:13:44.804 E/com.v2ray.ang( 2686): Invalid resource ID 0x00000000.
11-25 15:13:46.746 I/GoLog   ( 6508): loading core config
11-25 15:13:46.748 I/GoLog   ( 6508): Preparing Domain:XXXXXXXX:47427
11-25 15:13:46.761 I/GoLog   ( 6508): Prepare Result:
11-25 15:13:46.761 I/GoLog   ( 6508):  Domain: XXXXXXXX
11-25 15:13:46.761 I/GoLog   ( 6508):  Port: 47427
11-25 15:13:46.761 I/GoLog   ( 6508):  IPs: [XXXXXXXX]
11-25 15:13:46.977 I/GoLog   ( 6508): infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol:
```
</details>

### 环境信息
v2rayNG_1.9.20
MI 10 安卓14（非官方MIUI系统，第三方rom，名叫EVOLUTION X，ROM版本9.5）

### 额外信息（可选）
可以排除节点问题，因为问题出现在play store更新了V2RayNG版本之后。
并且我测试回退[1.9.16](https://github.com/2dust/v2rayNG/releases/tag/1.9.16)版本，问题不会出现。

**Comment by codewithtamim** [comment]
whats the transport protocol you using?

**Comment by xfish33** [comment]
same problem when transport protocol is shadowsocks

**Comment by clevercjl** [comment]
好像shadowsocks协议的都显示启动服务失败

**Comment by codewithtamim** [comment]
Custom configuration or uri ?

**Comment by stormfat** [comment]
同样问题，更新到1.9.20后出现启动服务失败

**Comment by codewithtamim** [comment]
Found !, this bug fix maybe created the issue lol https://github.com/2dust/v2rayNG/commit/934cf5d21c02b53ffb983a3cde847b3eda3dc900#diff-879b1352266f54b69b8cb77f95c0a7ffec4a32f65352bc4d8117dcaf764ebb2aR112

**Comment by 2dust** [comment]
那么谁能发一个全点的日志和配置？

**Comment by panshuhan** [comment]
logs here: (IP, Port and Domain were hidden)

--------- beginning of main
11-26 11:03:08.430 I/GoLog   (29210): loading core config
11-26 11:03:08.431 I/GoLog   (29210): Preparing Domain: <hide>
11-26 11:03:08.436 I/GoLog   (29210): Prepare Result:
11-26 11:03:08.436 I/GoLog   (29210):  Domain: <hide>
11-26 11:03:08.436 I/GoLog   (29210):  Port: <hide>
11-26 11:03:08.436 I/GoLog   (29210):  IPs: [<hide>]
11-26 11:03:08.474 I/GoLog   (29210): infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: 
11-26 11:03:08.474 D/com.v2ray.ang(29210): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: 
11-26 11:03:28.306 D/AndroidRuntime(29210): Shutting down VM
--------- beginning of crash
11-26 11:03:28.313 E/AndroidRuntime(29210): FATAL EXCEPTION: main
11-26 11:03:28.313 E/AndroidRuntime(29210): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 29210
11-26 11:03:28.313 E/AndroidRuntime(29210): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{a4ddc32 u0 com.v2ray.ang/.service.V2RayVpnService}
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2323)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2294)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.os.Handler.dispatchMessage(Handler.java:106)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.os.Looper.loopOnce(Looper.java:230)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.os.Looper.loop(Looper.java:319)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at android.app.ActivityThread.main(ActivityThread.java:9063)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at java.lang.reflect.Method.invoke(Native Method)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
11-26 11:03:28.313 E/AndroidRuntime(29210):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by panshuhan** [comment]
配置在这里
![Uploading WechatIMG49.jpg…]()

**Comment by panshuhan** [comment]
![WechatIMG49](https://github.com/user-attachments/assets/81f1a2fb-d17f-4f1d-b279-38330612fbfb)
配置在这里

**Comment by vnobo** [comment]
我也遇到了,这个问题如何解决

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.21
