### ISSUE TITLE
安卓版默认代理模式使用不了Instagram app

### ISSUE THREAD

**Issue by shanleyH** [2dust/v2rayNG#4034]
安卓版默认代理模式使用不了Instagram app，并且不知该怎么为Instagram app开启代理。（网页版Instagram没问题）现版本：1.9.16

**Comment by 2dust** [comment]
在设置中找分应用代理，选择此app，然后重启

**Comment by shanleyH** [comment]
谢谢，可以了，“重启”这一步很关键（我杀了v2rayNG后台再重新打开都没有用，点击“重启”后就可以了）

**Comment by shanleyH** [comment]
再次打开Instagram app后又出现了不走代理的情况，点击重启也没有用
**日志信息**
`--------- beginning of main
11-28 00:39:43.810 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:44.350 I/com.v2ray.ang( 6528): dgc_arg: 4096KB,16MB,0.5
11-28 00:39:47.410 I/com.v2ray.ang( 6528): Open vivo delay for GC JIT .
11-28 00:39:47.541 I/com.v2ray.ang( 6528): Close vivo delay for GC JIT .
11-28 00:39:49.423 I/GoLog   (30330): from udp:*********:35288 accepted udp:***********:443 [socks -> block]
11-28 00:39:49.448 I/GoLog   (30330): from udp:*********:45038 accepted udp:*******:53 [socks -> proxy]
11-28 00:39:49.454 I/GoLog   (30330): from udp:*********:47285 accepted udp:*******:53 [socks -> proxy]
11-28 00:39:49.457 I/GoLog   (30330): from tcp:*********:38382 accepted tcp:***********:443 [socks -> proxy]
11-28 00:39:49.611 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:49.618 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:49.622 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:49.957 I/GoLog   (30330): from udp:*********:57486 accepted udp:***********:443 [socks -> block]
11-28 00:39:49.960 I/GoLog   (30330): from tcp:*********:38390 accepted tcp:***********:443 [socks -> proxy]
11-28 00:39:50.159 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:50.563 I/com.v2ray.ang( 6528): dgc_arg: request backgroud gc, has_act=1, state=0
11-28 00:39:50.590 I/com.v2ray.ang( 6528): dgc_arg: 2048KB,16MB,0.75
11-28 00:39:50.724 I/GoLog   (30330): from udp:*********:57623 accepted udp:***********:443 [socks -> block]
11-28 00:39:50.726 I/GoLog   (30330): from udp:*********:43163 accepted udp:*******:53 [socks -> proxy]
11-28 00:39:50.728 I/GoLog   (30330): from tcp:*********:38398 accepted tcp:***********:443 [socks -> proxy]
11-28 00:39:50.894 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:50.896 I/GoLog   (30330): Using Prepared: ***************
11-28 00:39:51.511 I/GoLog   (30330): from udp:*********:57486 accepted udp:***********:443 [socks -> block]
11-28 00:39:52.266 I/GoLog   (30330): from udp:*********:57623 accepted udp:***********:443 [socks -> block]
11-28 00:39:53.117 I/GoLog   (30330): from udp:*********:57486 accepted udp:***********:443 [socks -> block]
11-28 00:39:53.760 I/com.v2ray.ang( 6528): dgc_arg: has_act=1, state=1
11-28 00:39:53.868 I/GoLog   (30330): from udp:*********:57623 accepted udp:***********:443 [socks -> block]
11-28 00:39:54.252 I/com.v2ray.ang( 6528): Open vivo delay for GC JIT .
11-28 00:39:54.760 I/com.v2ray.ang( 6528): dgc_arg: has_act=1, state=1
11-28 00:39:55.518 I/com.v2ray.ang( 6528): Close vivo delay for GC JIT .
11-28 00:39:55.951 I/com.v2ray.ang( 6528): Open vivo delay for GC JIT .
11-28 00:39:56.335 I/GoLog   (30330): from udp:*********:57486 accepted udp:***********:443 [socks -> block]
11-28 00:39:57.081 I/GoLog   (30330): from udp:*********:57623 accepted udp:***********:443 [socks -> block]`

**Comment by 2dust** [comment]
其他app是否正常？
考虑是否你的服务器是否被App屏蔽了？

**Comment by shanleyH** [comment]
其他app都正常
应该也不是的服务器被app屏蔽（因为ios的shadowrocket打开Instagram是正常的）
