### ISSUE TITLE
请求可以自定义节点的分组

### ISSUE THREAD

**Issue by Deepseaon** [2dust/v2rayNG#4036]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
我希望可以对手动添加的节点进行分组，每次进去都得搜索或者找半天很麻烦

### 实际行为
每次进入程序都得找手动添加进去的节点

### 复现方法
略

### 日志信息
略

### 额外信息（可选）
希望可以手动设置节点的分组而不是仅靠订阅进行划分

**Comment by 2dust** [comment]
你可以添加一个非订阅的分组啊，然后把你的节点都导入到这个组就行了

**Comment by Deepseaon** [comment]
> 你可以添加一个非订阅的分组啊，然后把你的节点都导入到这个组就行了

原来还可以这样，已经搞定了，感谢。
不过我是希望最好能有个迁移分组的功能，毕竟如果存在比较多想要转移组别的节点还得全部一个个重新添加一遍，尤其你得点进对应组添加才行，之前就是没理解这点所以不知道手机可以给手动添加的节点分组，不然就是没分组，像从旧版本升级上来的，除了订阅链接的，其他就全得重建。所以希望作者能考虑一下，不过如果您觉得这个功能还是比较小众的话您就直接关掉我的issue吧😂
