### ISSUE TITLE
运行无法启动服务，不确定是编译xray-core不正确还是项目配置不正确

### ISSUE THREAD

**Issue by XiangWahaha** [2dust/v2rayNG#4037]
无法启动vpn服务，请大佬帮忙看下，谢谢
1 AndroidLibXrayLite 自行编译的出libv2ray.aar 导入工程编译运行正常
2 导入节点列表：https://oneclash.githubrowcontent.com/2024/11/20241125.txt 正常
3 选择节点：启动无反应或者失败，日志

但是我们直接从googleplay下载的客户端是没问题，所以不确定是项目配置还是编译的libv2ray.aar有问题，期待您的回复

### 预期行为
连接节点成功

### 实际行为
报错，无法连接

### 复现方法
1.
2.
3.

### 日志信息
<details>
11-26 19:33:31.498  8719  8774 I GoLog   : from udp:127.0.0.1:38187 accepted udp:1.1.1.1:53 [socks -> proxy]
11-26 19:33:31.566  8719  8767 I GoLog   : Using Prepared: 151.101.194.228
11-26 19:33:32.098  8719  8767 I GoLog   : from udp:127.0.0.1:35326 accepted udp:1.1.1.1:53 [socks -> proxy]
11-26 19:33:32.157  8719  8774 I GoLog   : Using Prepared: 151.101.194.228
11-26 19:33:32.874  8719  8774 I GoLog   : Not Using Prepared: udp,223.5.5.5:53
11-26 19:33:32.875  8719  8767 I GoLog   : from tcp:127.0.0.1:49154 accepted tcp:121.40.206.159:443 [socks -> direct]
11-26 19:33:32.875  8719  8767 I GoLog   : from DNS accepted udp:223.5.5.5:53 [xray.system.12d31773-ddb0-483e-a7bc-1fd23d600b4a -> direct]
11-26 19:33:32.885  8719  8770 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:34:03.959  8719  8770 I GoLog   : fdConn unix.Connect err, Close Fd: 71 Err: connection timed out
11-26 19:34:03.984  8719  8764 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:34:35.039  8719  8767 I GoLog   : fdConn unix.Connect err, Close Fd: 63 Err: connection timed out
11-26 19:34:35.165  8719  8774 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:35:06.243  8719  8774 I GoLog   : fdConn unix.Connect err, Close Fd: 63 Err: connection timed out
11-26 19:35:06.469  8719  8774 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:35:37.519  8719  8774 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: connection timed out
11-26 19:35:37.847  8719  8764 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:35:56.224  8719  8719 D com.v2ray.ang: tun2socks destroy
11-26 19:35:56.227  8719  8781 D com.v2ray.ang: libtun2socks.so exited
11-26 19:35:56.233  8719  8719 D com.v2ray.ang: libhysteria2.so destroy
11-26 19:35:56.234  8719  8719 D com.v2ray.ang: runProcess destroy
11-26 19:36:36.989  9456  9488 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
11-26 19:36:37.016  9456  9488 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
11-26 19:36:41.385  9456  9488 D com.v2ray.ang: https://oneclash.githubrowcontent.com/2024/11/20241125.txt
11-26 19:36:41.393  9456  9488 E com.v2ray.ang: Update subscription: proxy not ready or other error, try……
11-26 19:37:02.111  9551  9551 I GoLog   : loading core config
11-26 19:37:02.111  9551  9582 I GoLog   : Preparing Domain: 151.101.194.228:80
11-26 19:37:02.111  9551  9582 I GoLog   : Prepare Result:
11-26 19:37:02.111  9551  9582 I GoLog   :  Domain: 151.101.194.228
11-26 19:37:02.111  9551  9582 I GoLog   :  Port: 80
11-26 19:37:02.111  9551  9582 I GoLog   :  IPs: [151.101.194.228]
11-26 19:37:02.303  9551  9551 I GoLog   : new core
11-26 19:37:02.405  9551  9551 I GoLog   : start core
11-26 19:37:02.407  9551  9583 I GoLog   : [Warning] core: Xray 24.11.11 started
11-26 19:37:02.439  9551  9551 D com.v2ray.ang: [/data/app/com.v2ray.ang-1/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
11-26 19:37:02.445  9551  9551 D com.v2ray.ang: Process[pid=9593, hasExited=false]
11-26 19:37:02.445  9551  9551 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
11-26 19:37:02.446  9551  9596 D com.v2ray.ang: libtun2socks.so check
11-26 19:37:02.457  9551  9583 E GoLog   : runtime: newstack at runtime.printlock+0x78 sp=0x4000991a70 stack=[0x400098a000, 0x4000992000]
11-26 19:37:02.457  9551  9583 E GoLog   :      morebuf={pc:0x7f8fe49bb0 sp:0x4000991a70 lr:0x0}
11-26 19:37:02.457  9551  9583 E GoLog   :      sched={pc:0x7f8fe7f418 sp:0x4000991a70 lr:0x7f8fe49bb0 ctxt:0x0}
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.callbackUpdateSystemStack(0x4000062008, 0x7fe50e70a0, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/cgocall.go:257 +0x90 fp=0x4000991ad0 sp=0x4000991a70 pc=0x7f8fe49bb0
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocallbackg(0x7f90908120, 0x7fe50e7198, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/cgocall.go:322 +0x68 fp=0x4000991b20 sp=0x4000991ad0 pc=0x7f8fe49d78
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocallbackg(0x7f90908120, 0x7fe50e7198, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      <autogenerated>:1 +0x1c fp=0x4000991b50 sp=0x4000991b20 pc=0x7f8fec29dc
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocallback(0x4000991bc8, 0x7f90906174, 0x7f909097e8)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/asm_arm64.s:1131 +0xb0 fp=0x4000991b80 sp=0x4000991b50 pc=0x7f8fec0930
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.systemstack_switch()
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/asm_arm64.s:201 +0x8 fp=0x4000991b90 sp=0x4000991b80 pc=0x7f8febe4f8
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocall(0x7f909097e8, 0x4000991c08)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/cgocall.go:185 +0x70 fp=0x4000991bd0 sp=0x4000991b90 pc=0x7f8feb1b00
11-26 19:37:02.457  9551  9583 E GoLog   : main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
11-26 19:37:02.457  9551  9583 E GoLog   :      _cgo_gotypes.go:167 +0x34 fp=0x4000991c00 sp=0x4000991bd0 pc=0x7f90906174
11-26 19:37:02.457  9551  9583 E GoLog   : main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x4000139960, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
11-26 19:37:02.457  9551  9583 E GoLog   :      /tmp/gomobile-work-2458144383/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x4000991c60 sp=0x4000991c00 pc=0x7f90907728
11-26 19:37:02.457  9551  9583 E GoLog   : main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x4000139960, {0x0?, 0x2?})
11-26 19:37:02.457  9551  9583 E GoLog   :      /tmp/gomobile-work-2458144383/src-android-arm64/gobind/go_libv2raymain.go:302 +0x44 fp=0x4000991ca0 sp=0x4000991c60 pc=0x7f90907674
11-26 19:37:02.457  9551  9583 E GoLog   : github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).pointloop(0x40002b4930)
11-26 19:37:02.457  9551  9583 E GoLog   :      /home/huke/下载/AndroidLibXrayLite/libv2ray_main.go:164 +0x42c fp=0x4000991d90 sp=0x4000991ca0 pc=0x7f9090095c
11-26 19:37:02.457  9551  9583 E GoLog   : github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).RunLoop(0x40002b4930, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /home/huke/下载/AndroidLibXrayLite/libv2ray_main.go:101 +0x20c fp=0x4000991e10 sp=0x4000991d90 pc=0x7f908ffe9c
11-26 19:37:02.457  9551  9583 E GoLog   : main.proxylibv2ray_V2RayPoint_RunLoop(0xffffff01?, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /tmp/gomobile-work-2458144383/src-android-arm64/gobind/go_libv2raymain.go:196 +0x4c fp=0x4000991e40 sp=0x4000991e10 pc=0x7f90906e7c
11-26 19:37:02.457  9551  9583 E GoLog   : _cgoexp_6f524d1d87fa_proxylibv2ray_V2RayPoint_RunLoop(0x7fe50e9194)
11-26 19:37:02.457  9551  9583 E GoLog   :      _cgo_gotypes.go:383 +0x2c fp=0x4000991e60 sp=0x4000991e40 pc=0x7f9090851c
--------- beginning of crash

</details>

### 环境信息
1.9.20版本 android 7.1.1系统

**Comment by XiangWahaha** [comment]
上面的日志太乱了，重发一下日志信息
--------- beginning of system
--------- beginning of main
11-26 19:33:31.498  8719  8774 I GoLog   : from udp:127.0.0.1:38187 accepted udp:1.1.1.1:53 [socks -> proxy]
11-26 19:33:31.566  8719  8767 I GoLog   : Using Prepared: 151.101.194.228
11-26 19:33:32.098  8719  8767 I GoLog   : from udp:127.0.0.1:35326 accepted udp:1.1.1.1:53 [socks -> proxy]
11-26 19:33:32.157  8719  8774 I GoLog   : Using Prepared: 151.101.194.228
11-26 19:33:32.874  8719  8774 I GoLog   : Not Using Prepared: udp,223.5.5.5:53
11-26 19:33:32.875  8719  8767 I GoLog   : from tcp:127.0.0.1:49154 accepted tcp:121.40.206.159:443 [socks -> direct]
11-26 19:33:32.875  8719  8767 I GoLog   : from DNS accepted udp:223.5.5.5:53 [xray.system.12d31773-ddb0-483e-a7bc-1fd23d600b4a -> direct]
11-26 19:33:32.885  8719  8770 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:34:03.959  8719  8770 I GoLog   : fdConn unix.Connect err, Close Fd: 71 Err: connection timed out
11-26 19:34:03.984  8719  8764 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:34:35.039  8719  8767 I GoLog   : fdConn unix.Connect err, Close Fd: 63 Err: connection timed out
11-26 19:34:35.165  8719  8774 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:35:06.243  8719  8774 I GoLog   : fdConn unix.Connect err, Close Fd: 63 Err: connection timed out
11-26 19:35:06.469  8719  8774 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:35:37.519  8719  8774 I GoLog   : fdConn unix.Connect err, Close Fd: 59 Err: connection timed out
11-26 19:35:37.847  8719  8764 I GoLog   : Not Using Prepared: tcp,121.40.206.159:443
11-26 19:35:56.224  8719  8719 D com.v2ray.ang: tun2socks destroy
11-26 19:35:56.227  8719  8781 D com.v2ray.ang: libtun2socks.so exited
11-26 19:35:56.233  8719  8719 D com.v2ray.ang: libhysteria2.so destroy
11-26 19:35:56.234  8719  8719 D com.v2ray.ang: runProcess destroy
11-26 19:36:36.989  9456  9488 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
11-26 19:36:37.016  9456  9488 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
11-26 19:36:41.385  9456  9488 D com.v2ray.ang: https://oneclash.githubrowcontent.com/2024/11/20241125.txt
11-26 19:36:41.393  9456  9488 E com.v2ray.ang: Update subscription: proxy not ready or other error, try……
11-26 19:37:02.111  9551  9551 I GoLog   : loading core config
11-26 19:37:02.111  9551  9582 I GoLog   : Preparing Domain: 151.101.194.228:80
11-26 19:37:02.111  9551  9582 I GoLog   : Prepare Result:
11-26 19:37:02.111  9551  9582 I GoLog   :  Domain: 151.101.194.228
11-26 19:37:02.111  9551  9582 I GoLog   :  Port: 80
11-26 19:37:02.111  9551  9582 I GoLog   :  IPs: [151.101.194.228]
11-26 19:37:02.303  9551  9551 I GoLog   : new core
11-26 19:37:02.405  9551  9551 I GoLog   : start core
11-26 19:37:02.407  9551  9583 I GoLog   : [Warning] core: Xray 24.11.11 started
11-26 19:37:02.439  9551  9551 D com.v2ray.ang: [/data/app/com.v2ray.ang-1/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
11-26 19:37:02.445  9551  9551 D com.v2ray.ang: Process[pid=9593, hasExited=false]
11-26 19:37:02.445  9551  9551 D com.v2ray.ang: /data/user/0/com.v2ray.ang/files/sock_path
11-26 19:37:02.446  9551  9596 D com.v2ray.ang: libtun2socks.so check
11-26 19:37:02.457  9551  9583 E GoLog   : runtime: newstack at runtime.printlock+0x78 sp=0x4000991a70 stack=[0x400098a000, 0x4000992000]
11-26 19:37:02.457  9551  9583 E GoLog   :      morebuf={pc:0x7f8fe49bb0 sp:0x4000991a70 lr:0x0}
11-26 19:37:02.457  9551  9583 E GoLog   :      sched={pc:0x7f8fe7f418 sp:0x4000991a70 lr:0x7f8fe49bb0 ctxt:0x0}
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.callbackUpdateSystemStack(0x4000062008, 0x7fe50e70a0, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/cgocall.go:257 +0x90 fp=0x4000991ad0 sp=0x4000991a70 pc=0x7f8fe49bb0
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocallbackg(0x7f90908120, 0x7fe50e7198, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/cgocall.go:322 +0x68 fp=0x4000991b20 sp=0x4000991ad0 pc=0x7f8fe49d78
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocallbackg(0x7f90908120, 0x7fe50e7198, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      <autogenerated>:1 +0x1c fp=0x4000991b50 sp=0x4000991b20 pc=0x7f8fec29dc
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocallback(0x4000991bc8, 0x7f90906174, 0x7f909097e8)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/asm_arm64.s:1131 +0xb0 fp=0x4000991b80 sp=0x4000991b50 pc=0x7f8fec0930
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.systemstack_switch()
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/asm_arm64.s:201 +0x8 fp=0x4000991b90 sp=0x4000991b80 pc=0x7f8febe4f8
11-26 19:37:02.457  9551  9583 E GoLog   : runtime.cgocall(0x7f909097e8, 0x4000991c08)
11-26 19:37:02.457  9551  9583 E GoLog   :      /usr/local/go/src/runtime/cgocall.go:185 +0x70 fp=0x4000991bd0 sp=0x4000991b90 pc=0x7f8feb1b00
11-26 19:37:02.457  9551  9583 E GoLog   : main._Cfunc_cproxylibv2ray_V2RayVPNServiceSupportsSet_Setup(0x2a, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
11-26 19:37:02.457  9551  9583 E GoLog   :      _cgo_gotypes.go:167 +0x34 fp=0x4000991c00 sp=0x4000991bd0 pc=0x7f90906174
11-26 19:37:02.457  9551  9583 E GoLog   : main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup.func1(0x4000139960, {0x0, 0x0, {0x0, 0x0, 0x0, 0x0}})
11-26 19:37:02.457  9551  9583 E GoLog   :      /tmp/gomobile-work-2458144383/src-android-arm64/gobind/go_libv2raymain.go:302 +0x78 fp=0x4000991c60 sp=0x4000991c00 pc=0x7f90907728
11-26 19:37:02.457  9551  9583 E GoLog   : main.(*proxylibv2ray_V2RayVPNServiceSupportsSet).Setup(0x4000139960, {0x0?, 0x2?})
11-26 19:37:02.457  9551  9583 E GoLog   :      /tmp/gomobile-work-2458144383/src-android-arm64/gobind/go_libv2raymain.go:302 +0x44 fp=0x4000991ca0 sp=0x4000991c60 pc=0x7f90907674
11-26 19:37:02.457  9551  9583 E GoLog   : github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).pointloop(0x40002b4930)
11-26 19:37:02.457  9551  9583 E GoLog   :      /home/huke/下载/AndroidLibXrayLite/libv2ray_main.go:164 +0x42c fp=0x4000991d90 sp=0x4000991ca0 pc=0x7f9090095c
11-26 19:37:02.457  9551  9583 E GoLog   : github.com/2dust/AndroidLibXrayLite.(*V2RayPoint).RunLoop(0x40002b4930, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /home/huke/下载/AndroidLibXrayLite/libv2ray_main.go:101 +0x20c fp=0x4000991e10 sp=0x4000991d90 pc=0x7f908ffe9c
11-26 19:37:02.457  9551  9583 E GoLog   : main.proxylibv2ray_V2RayPoint_RunLoop(0xffffff01?, 0x0)
11-26 19:37:02.457  9551  9583 E GoLog   :      /tmp/gomobile-work-2458144383/src-android-arm64/gobind/go_libv2raymain.go:196 +0x4c fp=0x4000991e40 sp=0x4000991e10 pc=0x7f90906e7c
11-26 19:37:02.457  9551  9583 E GoLog   : _cgoexp_6f524d1d87fa_proxylibv2ray_V2RayPoint_RunLoop(0x7fe50e9194)
11-26 19:37:02.457  9551  9583 E GoLog   :      _cgo_gotypes.go:383 +0x2c fp=0x4000991e60 sp=0x4000991e40 pc=0x7f9090851c
--------- beginning of crash

**Comment by Dasauto00** [comment]
我在Android15的设备上使用1.9.20版本也出现了无法启动服务的问题，在release中下载1.9.21版本安装后就没问题了

**Comment by hkfires** [comment]
我也是升级到1.9.20之后出问题，vless协议可以用，ss协议不行，日志提示failed to parse json config > infra/conf: Config: unknown transport protocol;

**Comment by XiangWahaha** [comment]
不需要自己编译，直接使用就可以了，应该是自己编译的库有bug，谢谢
库的下载地址：
https://github.com/2dust/AndroidLibXrayLite/releases
