### ISSUE TITLE
1.9.9版本后tls问题

### ISSUE THREAD

**Issue by iefnuy** [2dust/v2rayNG#4038]
Google play 更新到1.9.16后部分节点（vmess+ws+tls）不能使用，回退1.9.9可以使用。

新版本发现不带tls的可以使用，带tls的必须服务器连接地址和tls的SNI相同才能使用。
1.9.21问题依旧。

**Comment by 2dust** [comment]
你能否在v1.9.9和v1.9.21都导出完整配置，对比下outbound部分是否有不同？
你可以发出来让开发者参考下

**Comment by 2dust** [comment]
或者说因原来的服务器SNI这里是没有填写的？

**Comment by iefnuy** [comment]
1.9.21

  "outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false,
        "xudpConcurrency": 8,
        "xudpProxyUDP443": ""
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "node.domain.uk",
            "port": 443,
            "users": [
              {
                "id": "xxxxxx",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": true,
          "fingerprint": "",
          "serverName": "",
          "show": false
        },
        "wsSettings": {
          "headers": {
            "Host": "node.domain.cf"
          },
          "path": "/path"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],
  "policy": {
    "levels": {
      "8": {
        "connIdle": 300,
        "downlinkOnly": 1,
        "handshake": 4,
        "uplinkOnly": 1
      }
    },
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },

**Comment by iefnuy** [comment]
1.9.9
  "outbounds": [
    {
      "mux": {
        "concurrency": -1,
        "enabled": false,
        "xudpConcurrency": 8,
        "xudpProxyUDP443": ""
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "node.domain.uk",
            "port": 443,
            "users": [
              {
                "alterId": 0,
                "encryption": "",
                "flow": "",
                "id": "xxxxxx",
                "level": 8,
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "tlsSettings": {
          "allowInsecure": false,
          "fingerprint": "",
          "serverName": "`node.domain.cf`",
          "show": false
        },
        "wsSettings": {
          "headers": {
            "Host": "node.domain.cf"
          },
          "path": "/path"
        }
      },
      "tag": "proxy"
    },
    {
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "block"
    },
    {
      "protocol": "dns",
      "tag": "dns-out"
    }
  ],

**Comment by 2dust** [comment]
确实不同
"serverName": "node.domain.cf",这个值你在旧版本里面是填在哪里的呢？

**Comment by 2dust** [comment]
试一试 
https://github.com/2dust/v2rayNG/releases/tag/1.9.22

**Comment by iefnuy** [comment]
fixed
