### ISSUE TITLE
invalid character 'ï' looking for beginning of value

### ISSUE THREAD

**Issue by kamiomisuzu888** [2dust/v2rayNG#404]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
Start service

### 实际行为
Start services failure

### 复现方法
1.导入config（旧版格式，下列）
2.成功导入，无法开始代理
3.相同做法于kitsunebi可行

### 日志信息
<details>

--------- beginning of main
--------- beginning of system
05-05 16:52:01.812 I/GoLog   ( 6925): loading v2ray config
05-05 16:52:01.812 I/GoLog   ( 6925): Preparing Domain: 1.1.1.1:443
05-05 16:52:01.812 I/GoLog   ( 6925): v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 1 > invalid character 'ï' looking for beginning of value
05-05 16:52:01.812 I/GoLog   ( 6925): Prepare Result:
05-05 16:52:01.812 I/GoLog   ( 6925):  Domain: 1.1.1.1
05-05 16:52:01.812 I/GoLog   ( 6925):  Port: 443
05-05 16:52:01.812 I/GoLog   ( 6925):  IPs: [1.1.1.1]
05-05 16:52:01.812 D/com.v2ray.ang( 6925): go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to read config file at line 1 char 1 > invalid character 'ï' looking for beginning of value

</details>

### 环境信息

Google Pixel 2

### 额外信息（可选）
导入的config file（已去敏感）
<details>

﻿{
  "inbound": {
    "port": 10808,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "sniffing": {
      "enabled": false
    },
    "settings": {
      "auth": "noauth",
      "udp": true,
      "timeout": 0
    }
  },
  "outbound": {
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "address": "1.1.1.1",
          "port": 443,
          "users": [
            {
              "user": "…",
              "pass": "…"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "ws",
      "security": "tls",
      "tlsSettings": {
        "serverName": "…",
        "allowInsecure": false,
        "allowInsecureCiphers": false
      },
      "wsSettings": {
        "path": "…",
        "headers": {
          "Host": "…",
          "User-Agent": "…"
        }
      }
    }
  }
}

</details>

**Comment by 2dust** [comment]
https://www.v2fly.org/chapter_02/01_overview.html
