### ISSUE TITLE
geosite文件太旧，导致无法启动

### ISSUE THREAD

**Issue by jiuqianyuan** [2dust/v2rayNG#4040]
V2rayNG v1.9.21版本，初始GEO资源文件太旧或过于精简。导致直接导入黑名单规则集的话，服务会启动失败。

日志显示找不到 geoip:facebook 子集。

建议版本中 修改预定义规则时，及时更新geo文件。

**Comment by 2dust** [comment]
你先自己更新下geo文件

**Comment by rasa68** [comment]
Is it possible to include a timed update option, like an subscription automatic update , to update geo files?
