### ISSUE TITLE
v1.9.20 shadowsocks订阅链接不包含network type时无法启动

### ISSUE THREAD

**Issue by wyx2685** [2dust/v2rayNG#4043]
### 预期行为
自动填充默认tcp 服务正常启动

### 实际行为
启动失败，日志报unknown protocol:
(传输方式为空)

### 复现方法
使用ss://订阅链接导入，不带传输方式

### 日志信息
<details>
--------- beginning of system
--------- beginning of main
11-27 08:09:02.629 I/GoLog   (24175): loading core config
11-27 08:09:02.629 I/GoLog   (24175): Preparing Domain: 1:1
11-27 08:09:02.630 I/GoLog   (24175): Prepare Result:
11-27 08:09:02.630 I/GoLog   (24175):  Domain: 1
11-27 08:09:02.630 I/GoLog   (24175):  Port: 1
11-27 08:09:02.630 I/GoLog   (24175):  IPs: [1]
11-27 08:09:03.401 I/GoLog   (24175): infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol: 
11-27 08:09:03.401 D/com.v2ray.ang(24175): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: Config: unknown transport protocol:
</details>

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.21
