### ISSUE TITLE
订阅解析问题

### ISSUE THREAD

**Issue by zhangsan946** [2dust/v2rayNG#4046]
### 预期行为
根据 https://github.com/XTLS/Xray-core/discussions/716 描述，部分字段使用`encodeURIComponent`转义，例如：host, path, extra, alpn, spx

### 实际行为
v2rayNG在解析的时候并没有对该部分字段进行接码。
https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/java/com/v2ray/ang/fmt/FmtBase.kt

**Comment by 2dust** [comment]
```
fun getQueryParam(uri: URI): Map<String, String> {
        return uri.rawQuery.split("&")
            .associate { it.split("=").let { (k, v) -> k to Utils.urlDecode(v) } }
    }
```
