### ISSUE TITLE
自定义规则中的网址格式应该怎么填？

### ISSUE THREAD

**Issue by benjinXie** [2dust/v2rayNG#405]
### 预期行为
自定义规则中直连网址生效

### 实际行为
在自定义规则中填入的网址依然走代理了

### 复现方法
1.在任意的全局代理或者是绕过大陆地址的规则下
2.在自定义规则中直连网址一项中填入了FCM的HOST
3.FCM的连接依然不是直连而是走代理

不知道是服务端还是哪里的问题，反正FCM的长连接到了一定的时间就会断开，所以唯一的方法就是把FCM的的HOST，也就是mtalk.google.com这个地址填入直连列表中。但是我填入后重新连接，FCM依然还是定时断开，基本可以判断为FCM的这个连接并没有直连。那么请问是我填入的这个网址的格式错误了还是什么原因？

同样隔壁的B开头的那个应用也是有这样的问题，自定义路由中的规则本身添加了绕过大陆和代理GFW的规则的前提下，再单独添加一个FCM的直连规则，然而不知道是不是跟GFW列表中GOOGLE的域名有冲突，导致了这个直连的规则不生效，同样也是会定期重连

**Comment by somelee** [comment]
在右上角有设置默认路由，用那个就行。

有特殊需要仿写一下不就可以了

**Comment by Supremewoman** [comment]
和你一样的问题，现在只能分应用代理取消了框架和谷歌服务。这样FCM就能稳定了，不过设置里的Google连接就会不通了

**Comment by yuhan6665** [comment]
Try enable sniffing in settings.
If doesn't work, then you can use custom config in #403
