### ISSUE TITLE
"Use for all apps" option in Routing rules

### ISSUE THREAD

**Issue by backqu0te** [2dust/v2rayNG#4053]
This is not an issue, this is a suggestion.

## Description suggestions

Please add a check-box option "Use for all apps" (or "Ignore global app filter") in each Routing rule setting. When this option is enabled then the routing rule must be applied for all applications, ignoring global "Pre-app proxy" settings.

## Necessity of recommendations

I need to use VPN only for special set of websites in all applications. And for all websites in specified applications.

E.g. youtube.com in Browser, YouTube app, in-app browsers (e.g. inside messengers) and devices, connected to my phone via WiFi translation. And also all traffic in Discord, Notion apps, etc.

I can't set up v2rayNG this way right now.

**Comment by 2dust** [comment]
Set up a proxy for each application in Settings

**Comment by 2dust** [comment]
Routing rules do not have attributes for app

**Comment by backqu0te** [comment]
> Routing rules do not have attributes for app

That's why I'm asking you to add this option.

How else can I enable a proxy for separate websites (in all applications) and for separate applications (working with any websites)?

**Comment by 2dust** [comment]
xray-core routing rules do not have the process-name attribute, and the application is provided by android vpnservice, 
so it cannot achieve the function you want. 
You can use sing-box, this app has this function

**Comment by lakmalab** [comment]
It would be great if this can be added somehow 

> Set up a proxy for each application in Settings
