### ISSUE TITLE
How to include Hysteria2 config in my Custom Config Subscription

### ISSUE THREAD

**Issue by APT-ZERO** [2dust/v2rayNG#4067]
Is it supported?
Please give me a template of Hy2 json config that v2rayNG supports
if it's not supported, then how can i include Hy2 in my Custom Config JSON Subscription?

**Comment by 2dust** [comment]
不支持自定义配置HY2

**Comment by APT-ZERO** [comment]
So i can't add Hy2 config to my JSON Custom Config subscription until i switch my subscription to v2ray link type subscription

Can't you just support for json custom Hy2 or make it possible to send custom config along with v2ray link configs? @2dust

this problem just made Hy2 Support of v2rayNG useless for any proxy provider who uses JSON Custom Configs for v2rayNG
