### ISSUE TITLE
希望v2rayng能添加负载均衡功能能，谢谢!

### ISSUE THREAD

**Issue by xinycq** [2dust/v2rayNG#4068]
节点多，在安卓设备中手动挑选最快的节点太麻烦，不知道何时能在v2rayng中使用上负载均衡功能，或者象karing一样可以后台定时测速自动切换最快的服务器.
谢谢

**Comment by 2dust** [comment]
你可以从v2rayN生成配置后发送来用
手机上用复杂配置大概率会特耗电

**Comment by 2dust** [comment]
主要是在手机上多选节点等操作会比较复杂，所以在UI上不好做，所以暂时没有计划做
