### ISSUE TITLE
Feature Request: Add "Reset Connection" Button in Notification

### ISSUE THREAD

**Issue by maknajeb** [2dust/v2rayNG#4069]
I have not been using v2rayNG for a while, but the recent changes to the routing settings layout caught my attention and brought me back to the app. However, as someone who has been using NB4A for quite some time, I’ve grown accustomed to its simple yet highly functional “Reset Connection” button in the notification area.

This feature is extremely useful, especially when encountering connection issues. Instead of opening the app to reset the connection, users can simply tap the button in the notification, which saves time and avoids interrupting other app usage.

Suggestion:
Please consider adding a "Reset Connection" button to the notification area in v2rayNG. This addition would make the app more convenient for users, especially in situations where quick action is needed without navigating back to the app itself.

Thank you for your attention and for continuously improving v2rayNG

![20241129_111701](https://github.com/user-attachments/assets/91df1eb1-bd3d-47d0-aa60-2d56d10e83fc)

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.9.23
