### ISSUE TITLE
电视机上不能常驻后台运行

### ISSUE THREAD

**Issue by hwt88** [2dust/v2rayNG#408]
电视机上不能常驻后台运行，即使开了权限。具体表现是：刚看YouTube不到30秒钟就被杀了，也有可能是V2Ray程序本身闪退了。

YouTube电视机版本apk下载链接https://m.apkpure.com/youtube-for-android-tv/com.google.android.youtube.tv

@yuhan6665

**Comment by yuhan6665** [comment]
@UsherBaby not much we can do for TV. Please check:
- Turn off any device optimisation
- Turn off any energy saving settings
- Turn on allow app to auto start if there is such settings
- If possible, flash your firmware to Google's Android TV
