### ISSUE TITLE
xhttp订阅下发后默认mode值为"gun"导致启动失败

### ISSUE THREAD

**Issue by wyx2685** [2dust/v2rayNG#4082]
### 预期行为
订阅下发vless+xhttp默认mode为auto

### 实际行为
无法启动

### 日志信息
<details>
12-02 08:55:22.993 I/GoLog   ( 4835): infra/conf/serial: failed to parse json config > infra/conf: Failed to build XHTTP config. > infra/conf: unsupported mode: gun
12-02 08:55:22.993 D/com.v2ray.ang( 4835): go.Universe$proxyerror: infra/conf/serial: failed to parse json config > infra/conf: Failed to build XHTTP config. > infra/conf: unsupported mode: gun

</details>

**Comment by 2dust** [comment]
给个例子订阅吧

**Comment by wyx2685** [comment]
是我的问题，傻逼了
