### ISSUE TITLE
在默认设置下，仅更改路由设置为黑名单模式时xray-core无法启动

### ISSUE THREAD

**Issue by justlagom** [2dust/v2rayNG#4084]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
路由设置-黑名单模式
服务启动成功

### 实际行为
服务启动失败

### 复现方法
1.导入预定义规则集-黑名单
2.服务启动失败

### 额外信息（可选）
在黑名单规则下，不启用代理IP与代理GFW两条规则，xray正常启动但由于缺失规则而失去翻墙能力

**Comment by 2dust** [comment]
1.目前内置的geo文件使用白名单是正常的，推荐用
2.如果要用黑名单，需要更新geo文件；为啥不直接内置呢，因为这个geo文件比较大，资源占用多
自己取舍

**Comment by justlagom** [comment]
> 1.目前内置的geo文件使用白名单是正常的，推荐使用 2.如果使用黑名单，需要更新geo文件；为啥不直接内置呢，因为这个geo文件比较大，资源占用多 自己取舍

是的在更新geo资源后xray正常启动真连接延迟也测出正常延迟（测试网站我更换为google）

但是还是存在问题

设置里启用本地dns与虚拟dns其他无更改

路由设置为asis黑名单模式，b站等国内app无法联网

**Comment by 2dust** [comment]
你需要把前面的规则都禁用掉测试下
比如禁用广告
正常要是你app走了代理也是可以联网的，只是内容变了

**Comment by justlagom** [comment]
> 你需要把前面的规则都禁用掉测试下 比如禁用广告 正常要是你app走了代理也是可以联网的，只是内容变了

正常来说黑名单白名单国内都该正常直连，不会出现app无法连接网络问题
此外我在pc上使用V2rayN的黑名单模式，仅系统代理未使用tun模式下完全正常，国内与部分国外直连，GFW列表正常代理

**Comment by 2dust** [comment]
手机使用了系统vpn，有些功能和pc不同；
需要你排查一下，如果实在解决不了，你可以启用分应用代理；其实推荐用这个，更省电和资源

**Comment by justlagom** [comment]
> 手机使用了系统vpn，有些功能和pc不同； 需要你排查一下，如果实在解决不了，你可以启用分应用代理；其实推荐用这个，更省电和资源

找到问题所在了
不启用“最终直连”port：0-65535规则黑名单就能正常运行了
