### ISSUE TITLE
Geoip:ru direct not working rule

### ISSUE THREAD

**Issue by Ilya87** [2dust/v2rayNG#4092]
1. Download suggested geoip.dat from https://github.com/v2fly/geoip
2. Add rule in V2rayNG – geoip:ru, outbound direct (I want to load russian ips traffic without proxy)
3. Put the rule on top, and expect russian ips will have direct access, but https://www.reg.ru/web-tools/myip shows VPS (not direct) ip.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
You need to solve the routing rules and files yourself, the app cannot help you

**Comment by Ilya87** [comment]
The v2rayng must rely on country ip data that is stored in geoip.dat. geoip.dat was added to V2rayNg using menu in routing (obviously). But V2rayng does NOT apply (understand) data from from imported geoip.dat file.
![Screenshot_20241204-114321~2](https://github.com/user-attachments/assets/9ddd2a81-782a-47cc-854b-b69cb279919d)
![Screenshot_20241204-114353](https://github.com/user-attachments/assets/a9e5245f-50a5-4a8a-a4e8-8af7b55789c6)

**Comment by 2dust** [comment]
把你自己的geoip文件改名成geoip.dat

**Comment by Ilya87** [comment]
The uploaded file is **already** geoip.dat
UPD: I even manually added rules from V2rayN (Windows), in Windows all work great, the same rules in V2rayNG , Android do not work.
![Screenshot_20241204-124939~2](https://github.com/user-attachments/assets/863d06dc-f9c4-4cfc-a12a-fff73c4f7dc5)

**Comment by 2dust** [comment]
Your entry is wrong
Remark: geoip.dat
URL:  real url

Update

**Comment by 2dust** [comment]
![image](https://github.com/user-attachments/assets/8690913d-8ce8-4baa-a7d8-03d17d9a7379)

**Comment by Ilya87** [comment]
Thank you for response, but I still with right remarks can't make russian ips go direct:
[{"enabled":true,"looked":false,"outboundTag":"direct","protocol":["bittorrent"],"remarks":"bittorrent"},{"domain":["geosite:category-ads-all"],"enabled":true,"looked":false,"outboundTag":"block","remarks":"阻断广告"},{"enabled":true,"ip":["geoip:private"],"looked":false,"outboundTag":"direct","remarks":"绕过局域网IP"},{"domain":["geosite:private"],"enabled":true,"looked":false,"outboundTag":"direct","remarks":"绕过局域网域名"},{"domain":["geoip:ru"],"enabled":true,"looked":false,"outboundTag":"direct","remarks":"RussianIp"},{"enabled":true,"looked":false,"network":"udp","outboundTag":"block","port":"443","remarks":"阻断udp443"},{"enabled":true,"looked":false,"outboundTag":"proxy","port":"0-65535","remarks":"最终代理"}]

Visiting https://www.reg.ru/web-tools/myip show vps ip
![Screenshot_20241205-003504~2](https://github.com/user-attachments/assets/011bb1e8-8014-4e02-be7b-90530d4850f6)
![Screenshot_20241205-003616~2](https://github.com/user-attachments/assets/fac09d47-a00c-401e-a9e3-8a4ea5c7f668)

**Comment by 2dust** [comment]
```
 "domain": [
            "geoip:ru"
        ],
```
This is wrong
The following is correct
```
 "ip": [
            "geoip:ru"
        ],
```

**Comment by Ilya87** [comment]
Thank you. Stupid typo. But still doesn't work.
UPD: WORK IN IPONDEMAND MODE
