### ISSUE TITLE
[Feature request]: Add new features

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#4093]
![IMG_۲۰۲۴۱۲۰۴_۰۹۳۹۳۶](https://github.com/user-attachments/assets/dacd8cb6-faa0-4379-895e-b5a942b175df)
![IMG_۲۰۲۴۱۲۰۴_۰۹۳۹۲۱](https://github.com/user-attachments/assets/bd8604c5-7b18-47e7-9ebc-96f2a617f65e)
![IMG_۲۰۲۴۱۲۰۴_۰۹۳۸۵۹](https://github.com/user-attachments/assets/2de470f8-2179-4f14-9bb9-e4326fbeaf62)
![IMG_۲۰۲۴۱۲۰۴_۰۹۳۸۴۳](https://github.com/user-attachments/assets/d9c89dd6-2359-465e-9a3a-66d11558f905)
Hi boss
If it is possible to add these features with a red line next to them same nekobox, we will be grateful
Thanks
@2dust

**Comment by 2dust** [comment]
不是商业软件，不接受定制需求
