### ISSUE TITLE
请问 1.9.24在仅代理模式下 如何配置 HTTP代理端口？

### ISSUE THREAD

**Issue by E-one-LLC** [2dust/v2rayNG#4098]
![Screenshot_20241205-075430](https://github.com/user-attachments/assets/edc32872-5412-47fb-8e07-d9d8d01a0017)

我的天要塌了

在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
填Socks5端口值就行
下版把文字描述改下
