### ISSUE TITLE
新版没有全局模式设置了吗？

### ISSUE THREAD

**Issue by freesit** [2dust/v2rayNG#4115]
新版没有全局模式设置了吗？

**Comment by lewisbatmanarnold** [comment]
同问，新版的路由设置该如何设置才能全局？

**Comment by ZhangSir9901** [comment]
改到路由设置里面了。真的非常不好用。已经建议改进了。

**Comment by owo10086** [comment]
> 同问，新版的路由设置该如何设置才能全局？

同问 如何设置啊

**Comment by ysqllake** [comment]
1.9.32版本可以按照以下操作：主界面左上角三条横线，路由设置，右上角三个点，导入预定义规则集，确定，全局（Global）
