### ISSUE TITLE
vmess xhttp bug

### ISSUE THREAD

**Issue by zuiwuchang** [2dust/v2rayNG#4116]
### 预期行为
vmess 能夠完整的支持 xhttp

### 实际行为
我使用發現 vless 已經完整支持了 xhttp，但是 vmess 生成的配置設裏面沒有 mode，因爲沒有 mode 所以無論ui中設置 'stream-one' 或是 'packet-up'，xray 核心都會按照默認的 mode 工作。

此外 vmess 在ui中設定了 extra 數據時，匯出訂閲信息中不會有 extra (所以我不確定匯入 extra 是否可以正常工作)，vless 沒有這一問題(是不是忘了更新 vmess 中關於 xhttp 新模式的代碼了)。 我想使用 extra 在訂閱中配置與上行不同的下行服務器地址，故 extra 匯入對我意義重大。

### 复现方法
1. 手動創建一個 vmess xhttp 代理，mode 設置爲 'auto' 之外的值，設置上任意 extra  數據
2. 啓動代理查看日誌，會發現core始終會打印使用默認模式，我這裏是 'stream-up'
3. 在ui中 匯出至剪貼簿，會發現匯出的數據中沒有包含 extra  數據
4. 將剪貼簿的數據重新匯入到程序後打開編輯，會發現 mode 一覽始終顯示爲 'auto' 模式

### 环境信息

v1.9.24 (Lib v27, Xray-core v24.11.30)

**Comment by 2dust** [comment]
vmess 不支持 xhttp，用vless

**Comment by zuiwuchang** [comment]
> vmess 不支持 xhttp，用vless

好吧！但是我測試桌面端的 xray vmess是可以正常工作的。
此外 雖然tls是加密的但是vless沒有加密，如果手機有邪惡的後門證書 tls+vless可能會被中間人攻擊。鑑於China政府的一貫作風，讓我覺得China產的設備會自帶後門證書也是不讓人意外的事情。
故希望能添加上對vmess的xhttp支持。（這應該不會費太多事情 xray core可以正常工作去，只需要正確的為它生成設定即可）
