### ISSUE TITLE
Subscription First config

### ISSUE THREAD

**Issue by Scaleeta** [2dust/v2rayNG#4122]
in a subscription link, there  are  two same config at the top. v2rayng 1.9.22 and later just recognize second one. what problem can be?
those two config exampale:
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTotSG9tZS0%3D@localhost:59734#11.10GB%2F100.00GB
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTotSG9tZS0%3D@localhost:59734#1403%2F10%2F15
(first one isn't adding)

**Comment by 2dust** [comment]
Duplicate configurations will be removed
