### ISSUE TITLE
当手机开启v2ray-ng并连接一个ipv6的vmess服务器时，手机热点的ipv4 dhcp服务无法正常工作

### ISSUE THREAD

**Issue by solachenclever** [2dust/v2rayNG#4125]
### 预期行为
其他设备连接手机热点时可以正常dhcp取得ipv4和ipv6的地址与路由配置

### 实际行为
仅获取到ipv6地址，无法获取ipv4地址

### 复现方法
1、连接一个仅有ipv6的vmess服务器
2、开启手机热点
3、其他设备连接手机热点

### 日志信息
NA
### 环境信息
我当前版本为v1.9.22，理论上其他版本也能复现
我当前以验证可以复现的设备为红米poco x5和honor 10A，但理论上其他手机也能复现。

**Comment by 2dust** [comment]
不支持
