### ISSUE TITLE
切换节点速度很慢

### ISSUE THREAD

**Issue by wb624** [2dust/v2rayNG#4129]
你好，现在的v2rayng连接节点和切换节点速度都太慢了，而且有时候还连接失败，节点测试真连接的时候速度也有点慢了，希望开发者修复

**Comment by 2dust** [comment]
因为geo文件很大，启动就是这样
你可以删除geo文件，try

**Comment by wb624** [comment]
删除geo文件之后，确实变快了，谢谢您！

2dust ***@***.***> 于 2024年12月15日周日 12:08写道：

**Comment by Jieoz** [comment]
> 因为geo文件很大，启动就是这样
> 你可以删除geo文件，try

大佬我现在发现切换节点很慢的同时com.v2ray.ang:RunSoLibV2RayDaemon这个进程的内存占用也很异常，有时候可以吃掉2g的ram。程序停止运行之后再打开就恢复正常。请问是软件的问题还是我配置有问题呢

**Comment by 2dust** [comment]
先删除你自己下载的 geo 文件。
然后路由规则全部删除掉，测试是否还是一样？ 
@Jieoz

**Comment by Jieoz** [comment]
> 先删除你自己下载的 geo 文件。 然后路由规则全部删除掉，测试是否还是一样？ [@Jieoz](https://github.com/Jieoz)

感谢回复，我重启了一下手机现在暂时正常，等再出现问题的时候我试一下这个方法
