### ISSUE TITLE
如软件开启时无网络连接 后续恢复网络之后域名不会自动重新解析

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#413]
系统版本：Android 10 - Pixel XL
v2rayNG版本：1.2.5
使用场景：在移动设备正常使用该软件代理上网
遇到的问题：当配置里填写的节点地址为域名时。如果开启本软件时没有网络连接，则后续设备网络连接恢复后，配置中相应的域名不会自动重新解析。
此时的期望现象是什么：如果配置中的地址为域名，则应在第一次尝试解析失败（dns服务器未应答）后，增加继续重试的间隔，直到解析到ip为止

**Comment by rurirei** [comment]
confirm starting connection after you can parse your domain correctly. https://github.com/2dust/v2rayNG/blob/45805d6df7d9da41b06d465be0c694671348397e/AndroidLibV2rayLite/interact.go#L78-L89
