### ISSUE TITLE
盗版软件获取用户信息

### ISSUE THREAD

**Issue by fghqwertttfgh** [2dust/v2rayNG#4133]
在https://v2rayng-cn.net/这个看着很像官方的网站上下载的安卓版本的v2rayng会获取用户文件并且请求录屏权限
希望在软件中多增加一些告示，github链接

**Comment by 2dust** [comment]
感谢。其实app里面有关于页面里面有
但如果已经下载了其他渠道版本，那在这里增加提示或链接也没有用
