### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#4135]
Hi
I have problem , when updating subscriptions, instead of xhttp, tcp it is placed in the host
@2dust
![Screenshot_۲۰۲۴-۱۲-۱۵-۱۰-۵۶-۵۵-۰۴۰_com v2ray ang-edit](https://github.com/user-attachments/assets/89c161fe-29db-471e-84e3-213727957095)
https://github.com/2dust/v2rayNG/issues/4118

**Comment by 2dust** [comment]
type=splithttp 请改成 type=xhttp 本app是按core的正式内容更新；如果一定要用旧的请用回前面一些的版本

**Comment by 2dust** [comment]
把你的分享URL发出来

**Comment by mh292929** [comment]
How can I share the configuration with you privately? Posting configuration here is not correct.

**Comment by 2dust** [comment]
Change the IP information and send it out @MH140000

**Comment by mh292929** [comment]
vless://121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com:443?type=xhttp&path=%2F&host=www.speedtest.net&mode=auto&security=reality&pbk=xxx&fp=random&sni=www.speedtest.net&sid=b1a101&spx=%2F#htf245lc

**Comment by 2dust** [comment]
> vless://[121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com](mailto:121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com):443?type=xhttp&path=%2F&host=www.speedtest.net&mode=auto&security=reality&pbk=xxx&fp=random&sni=www.speedtest.net&sid=b1a101&spx=%2F#htf245lc

No problem with the test

**Comment by ghost** [comment]
> > vless://[121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com](mailto:121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com):443?type=xhttp&path=%2F&host=www.speedtest.net&mode=auto&security=reality&pbk=xxx&fp=random&sni=www.speedtest.net&sid=b1a101&spx=%2F#htf245lc
> 
> No problem with the test

Hi, The problem is when mux is active, it is almost ok without Mux
https://github.com/XTLS/Xray-core/issues/4172

**Comment by 2dust** [comment]
> > > vless://[121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com](mailto:121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com):443?type=xhttp&path=%2F&host=www.speedtest.net&mode=auto&security=reality&pbk=xxx&fp=random&sni=www.speedtest.net&sid=b1a101&spx=%2F#htf245lc
> > 
> > 
> > No problem with the test
> 
> Hi, The problem is when mux is active, it is almost ok without Mux [XTLS/Xray-core#4172](https://github.com/XTLS/Xray-core/issues/4172)

So many of you have reported, but none of you mentioned the mux issue.
Waiting for testing and fix

**Comment by ghost** [comment]
> > > > vless://[121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com](mailto:121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com):443?type=xhttp&path=%2F&host=www.speedtest.net&mode=auto&security=reality&pbk=xxx&fp=random&sni=www.speedtest.net&sid=b1a101&spx=%2F#htf245lc
> > > 
> > > 
> > > No problem with the test
> > 
> > 
> > Hi, The problem is when mux is active, it is almost ok without Mux [XTLS/Xray-core#4172](https://github.com/XTLS/Xray-core/issues/4172)
> 
> So many of you have reported, but none of you mentioned the mux issue. Waiting for testing and fix

https://github.com/XTLS/Xray-core/commit/46d8d9ef02f61ac22c629a3fc7373b20c13c2608
Maybe this is related

**Comment by ghost** [comment]
> > > > vless://[121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com](mailto:121ba87b-8f08-40eb-8f9b-b5e30d570fcd@xxx.com):443?type=xhttp&path=%2F&host=www.speedtest.net&mode=auto&security=reality&pbk=xxx&fp=random&sni=www.speedtest.net&sid=b1a101&spx=%2F#htf245lc
> > > 
> > > 
> > > No problem with the test
> > 
> > 
> > Hi, The problem is when mux is active, it is almost ok without Mux [XTLS/Xray-core#4172](https://github.com/XTLS/Xray-core/issues/4172)
> 
> So many of you have reported, but none of you mentioned the mux issue. Waiting for testing and fix

If you can publish the new version, I had to disable mux completely to connect to the xhttp configuration. Now that you have given a PR to fix it, please publish it.
