### ISSUE TITLE
Regarding v2rayng app itself not using vpn service 

### ISSUE THREAD

**Issue by lakmalab** [2dust/v2rayNG#4136]
I noticed that vpn itself cannot use the vpn service it gives. This only happens when the vpn is started with VPN mode . When using proxy only mode v2rayng able to access the vpn routed internet.

**Comment by scShan** [comment]
I encountered similar issue. v2rayNG VPN mode, no VPN icon and cannot detect internet on closed pipe. But proxy mode test successfully. What's the solution? I tried version 1.9.24 , problem persists.

**Comment by lakmalab** [comment]
My issue was i couldn't add features that uses the internet to the my modded v2rayNG app (things like speedtest, Find IP etc)
after some digging i realized i had to retrieve http port from the system and  use this 
val response = Utils.getUrlContentWithCustomUserAgent(url, 30000, httpPort)
