### ISSUE TITLE
Add `Auto-Update` to Geo Asset Files (Suggestion)

### ISSUE THREAD

**Issue by Phoenix-999** [2dust/v2rayNG#4139]
Hi @2dust,
I’d like to suggest an enhancement for the `Geo Asset Files` section.

Given that these files are frequently updated, adding an `Auto-Update` feature would significantly improve user convenience.
This feature could allow users to schedule updates, ensuring their Geo Asset Files stay current without needing to manually check and update them every time a new release is available.
I’ve included examples and design mockups for your reference.

![Auto Update-01](https://github.com/user-attachments/assets/b3c04437-5814-463c-a8eb-04d01543084b)

Thank you in advance

**Comment by 2dust** [comment]
The content of the geo file may not change for several months.
Mobile devices need to save power and data traffic, so generally they don’t have this function.

**Comment by Phoenix-999** [comment]
> The content of the geo file may not change for several months. Mobile devices need to save power and data traffic, so generally they don’t have this function.

I understand and agree with you on the default Geosite and GeoIP, as well as their role in optimizing battery usage and reducing overall data traffic.

However, I believe that `custom-made Geosite & GeoIP files`, specifically designed for certain regions or purposes, require more frequent attention. We’ve observed that these files are updated or see new releases at least every week to 15 days.

Thank you again!

**Comment by APT-ZERO** [comment]
Auto update feature is always annoying and a waste of resources
It's better if you app just notify the user when a new version of the app or geo files are available and allow them to ignore it for days or disable it from settings

also an unrelated but good idea is to bring `Tcping / Real Delay / Sort / Update` options to the bottom of the main page like how a fork did it for another options
![image](https://github.com/user-attachments/assets/51a24920-c58f-47f8-a8d4-aced46e7ddf2)

**Comment by 2dust** [comment]
If someone PR this feature, will accept it
