### ISSUE TITLE
请问，设置里的流量探测有什么用，打开或者关闭有什么影响？

### ISSUE THREAD

**Issue by somelee** [2dust/v2rayNG#414]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by cuihao777** [comment]
可以在分析流量中的域名，这样就能路由规则。

**Comment by somelee** [comment]
> 可以在分析流量中的域名，这样就能路由规则。

好的，谢谢~

**Comment by rurirei** [comment]
what about if disable both trafficSniffing and localDNS, dirty-dns will received? @yuhan6665 https://github.com/2dust/v2rayNG/blob/df3f1ca3efdd5b6e9115cbe7ecdb4260541ab732/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L163

**Comment by yuhan6665** [comment]
You are right, You can take a look at the document I wrote
https://github.com/2dust/v2rayNG/wiki/Mode

**Comment by rurirei** [comment]
> You are right, You can take a look at the document I wrote
> https://github.com/2dust/v2rayNG/wiki/Mode

i'm finding for a Fake DNS implementation. do you have some idea about this for tun2socks (c-lang (BadVPN), v2rayNG uses it).

**Comment by yuhan6665** [comment]
I know Kisunebi has it. Not sure how he code it. I think the best approach at the moment is to use this pr (as a branch or push to merge it) which support fake DNS in v2ray core 
https://github.com/v2ray/v2ray-core/pull/2237
