### ISSUE TITLE
Innfra/conf not load

### ISSUE THREAD

**Issue by LoST202** [2dust/v2rayNG#4143]
Apparently I'm so unlucky or what I don't understand. When trying to activate the routing rule from geosite:ru, the logs give me this error, although 6 hours ago everything was fine and started. Magic) 
Error: 
```
infra/conf: failed to analyze domain rule: geosite: RU > infra/conf: failed to load geosite: RU > infra/conf: the list was not found in geosite.dat: RU
```
P.S May it depend on the routing rules in the panel itself?

**Comment by MK0ltra** [comment]
Looks like `geosite:ru` is not in the geosite. Try using `geosite:category-ru` for domain and `geoip:ru` in ip section.
