### ISSUE TITLE
新版本的代理规则到底要如何才能生效

### ISSUE THREAD

**Issue by iammsf** [2dust/v2rayNG#4145]
### 预期行为
访问打上了direct标签的域名时走直连，而非代理节点

### 实际行为
依然会走代理，但实际上某些网址走直连反而会更快

### 复现方法
1.
![Screenshot_2024-12-17-22-29-06-361_com v2ray ang](https://github.com/user-attachments/assets/e6d623db-5bd0-4276-806e-f54503b33d2f)
2.
![Screenshot_2024-12-17-22-30-18-553_com kiwibrowser browser-edit](https://github.com/user-attachments/assets/f7862667-f5a9-44a7-9b20-fc2eff82b5be)
3.
![Screenshot_2024-12-17-22-42-17-497_com v2ray ang](https://github.com/user-attachments/assets/2eca638e-bab7-4042-b5c9-e5cdcca5b53c)

### 环境信息
红米K70 澎湃OS2.0.5.0 Android 14 
### 额外信息（可选）
未更新之前自定义设置工作正常，可以绕开不需要代理的域名和IP，但是自从代理规则设置成为独立设置页面以后再也没生效过。已关闭issue列表里看到一堆反应这个问题的，照着里面提供的解决方案挨个试了，没一个有用的

**Comment by HCareLou** [comment]
换软件吧，这个软件已死，作者不积极，更新除了BUG

**Comment by 2dust** [comment]
实在搞不掂就换成旧版或换个软件吧

**Comment by aawwsslll** [comment]
> 实在搞不掂就换成旧版或换个软件吧

重新试了下，例如需要让漫画人这个漫画插件默认走代理。需要添加两个网址的规则即可。cdndm5.com,manhuaren.com ，不需要添加前面的domain就可以正常生效。
