### ISSUE TITLE
Add XMUX

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#4146]
Hello, in the last version of the 3xui panel, it is going to be impossible to use the new features of xhttp like xmux and..... in the form of json. If possible, please add these features to the client, thanks.@2dust
https://github.com/MHSanaei/3x-ui/commit/0df85cc3d9d418d3abc335047c7bd2c8794685fa
XHTTP: server & client
Remove scMinPostsIntervalMs, xmux, noGRPCHeader from the server side and add them to the client side.
Before you could have them on sub json but I decided to remove them.

**Comment by 2dust** [comment]
https://github.com/XTLS/Xray-core/pull/4000

**Comment by ghost** [comment]
> [XTLS/Xray-core#4000](https://github.com/XTLS/Xray-core/pull/4000)

Thanks, 
It should be used in json xhttp Extra?!

**Comment by 2dust** [comment]
yes

**Comment by ghost** [comment]
> yes

The main problem is that these items must be entered separately for each configuration. What is the solution?
Is it possible to add this extra through the panel and tell them to press pr?!
When I enter Json, it is not saved, what is the solution?

**Comment by 2dust** [comment]
https://github.com/XTLS/Xray-core/discussions/4113
```
{
    "headers": {
        // "key": "value"
    },
    "xPaddingBytes": "100-1000",
    "noGRPCHeader": false, // stream-up/one, client only
    "noSSEHeader": false, // server only
    "scMaxEachPostBytes": 1000000, // packet-up only
    "scMinPostsIntervalMs": 30, // packet-up, client only
    "scMaxBufferedPosts": 30, // packet-up, server only
    "xmux": { // h2/h3 mainly, client only
        "maxConcurrency": "16-32",
        "maxConnections": 0,
        "cMaxReuseTimes": "64-128",
        "cMaxLifetimeMs": 0,
        "hMaxRequestTimes": "800-900",
        "hKeepAlivePeriod": 0
    },
    "downloadSettings": { // client only
        "address": "", // another domain/IP
        "port": 443,
        "network": "xhttp",
        "security": "tls",
        "tlsSettings": {
                ...
        },
        "xhttpSettings": {
            "path": "/yourpath", // must be the same
                ...
        }
    }
}
```
