### ISSUE TITLE
请为DOH选项，提供配置hosts

### ISSUE THREAD

**Issue by aabbccgg** [2dust/v2rayNG#4147]
### 相关问题

当使用DOH配合xray内核时，无法访问DOH所属域名。假设DOH为my.dns.com，则开启v2rayn后会导致my.dns.com本身无法访问。报错：errors.LogError(ctx, s.name, " tries to resolve itself! Use IP or set \"hosts\" instead.")

xray相关代码所在位置：[https://github.com/XTLS/Xray-core/blob/7d0a80b501d430542ae851043de3da4d68335325/app/dns/nameserver_doh.go#L232](https://github.com/XTLS/Xray-core/blob/7d0a80b501d430542ae851043de3da4d68335325/app/dns/nameserver_doh.go#L232)

**假设**：我将海外dns设置为 https://my.dns.com/dns-query ，而 https://my.dns.com/admin 同时也是dns自己的后台管理系统。
**现状**：xray为了防治出现doh/dot等的dns回环查询，拒绝将被设置为dns服务器的域名作为被查询对象查询，即：被设置为dns服务器的域名不能自己解析自己，代码位置在issue开头链接中。
**问题**：在假设的情况下，访问我自己的dns后台，会触发my.dns.com的dns查询，而解析服务器就是他自己，于是dns请求被xray干烂了，导致无法查询。

### 描述你希望的解决方案

在设置中增加hosts设置，这样就不会触发自己解析自己。或者是默认增加一个安全的dns回退，比如8.8.8.8（当然这样处理会导致用户预期之外的dns泄漏）

### 我确认已查询历史issues

- [X] 是

**Comment by 2dust** [comment]
做一个设置不难，麻烦的是移动设备上要如何操作设置？
比如做一个json格式的输入框，让用户自己随意输入？或其他？

**Comment by aabbccgg** [comment]
我想象中是：侧边栏（左侧划出的菜单里面加一个hosts选项），然后用户输入ip domain即可。例如：
127.0.0.1 ad.google.com,
8.8.8.8 dns.google,
127.0.0.1 localhost,

**Comment by 2dust** [comment]
baidu.com:127.0.0.0.1,ads.com:127.0.0.0.1,baidu.com:127.0.0.0.1,ads.com:127.0.0.0.1,

**Comment by aabbccgg** [comment]
> baidu.com:127.0.0.0.1,ads.com:127.0.0.0.1,baidu.com:127.0.0.0.1,ads.com:127.0.0.0.1,

我觉得直接用linux hosts的格式也不错，这样从别的地方抄hosts过来就能直接用，不需要在手机上调整了

**Comment by 2dust** [comment]
这个格式是按照xray-core的配置格式去掉了引号的结果，尽量要和目标配置保持一致，这样节省解释的时间。

**Comment by 2dust** [comment]
https://xtls.github.io/config/dns.html

**Comment by aabbccgg** [comment]
emm，这个我知道，我的意思是如果用户复制了其他的hosts文件，理论上是通用的。而xray是因为用了json，没办法。在手机上把通用的hosts改成xray的json格式还挺麻烦的。不过，能有这个功能用就很好了，感谢🙏。
