### ISSUE TITLE
Russia preset from v2rayN to v2rayNG

### ISSUE THREAD

**Issue by HuntezWOTB** [2dust/v2rayNG#4154]
Good afternoon. Is there a plan to add a built-in Preset of Russia to the application? This is already built into the v2rayN desktop program
I know I've already written a whole guide on how to add a preset to the mobile version myself, but will it be built in? Here is a link to my old post: https://github.com/2dust/v2rayNG/issues/3795

**Comment by Phoenix-999** [comment]
@HuntezWOTB 
https://github.com/2dust/v2rayNG/issues/4085#issuecomment-2544797629
