### ISSUE TITLE
会有计划支持 naiveproxy 吗？

### ISSUE THREAD

**Issue by YinsenHo** [2dust/v2rayNG#4159]
rt

v2rayn 是很多年之前用的客户端了，最近发现支持 hy2 了，毫不犹豫换回来了，还是那个简洁，清晰，高效的的风格，感觉自己的青春都回来了。

除了 hy2 之外，还常用 naiveproxy，也非常稳定，简洁，所以想问一下是否有计划支持 naiveproxy 呢？

不支持也没有关系，已经非常好了，再次感谢

**Comment by 2dust** [comment]
naiveproxy 已经无人维护了，没有计划做

**Comment by YinsenHo** [comment]
> naiveproxy 已经无人维护了，没有计划做

naiveproxy 应该还在维护吧？每个月都有更新

https://github.com/klzgrad/naiveproxy

**Comment by 2dust** [comment]
先记着，暂时不处理

**Comment by YinsenHo** [comment]
> 先记着，暂时不处理

哈哈好的，记着就让人有个盼头
