### ISSUE TITLE
[功能请求]从文件中加载域名

### ISSUE THREAD

**Issue by elvisw** [2dust/v2rayNG#416]
V2ray Core具备从文件中加载域名的功能，在文档(https://v2ray.com/chapter_02/03_routing.html#ruleobject) 中有如下描述：

> 从文件中加载域名: 形如"ext:file:tag"，必须以ext:（小写）开头，后面跟文件名和标签，文件存放在资源目录中，文件格式与geosite.dat相同，标签必须在文件中存在。

但是此app似乎没有这个功能。希望能够提供此功能，以方便用户引入第三方geosite文件更加灵活地配置路由。

**Comment by even0306** [comment]
自定义配置中可以定义，但在安卓上不知如何替换更新geosite.dat文件

**Comment by elvisw** [comment]
> 自定义配置中可以定义，但在安卓上不知如何替换更新geosite.dat文件

@even0306
不需要替换更新，只是希望能够具有引入第三方geosite文件的功能。

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/pull/662
