### ISSUE TITLE
all private ips are forcibly bypassed

### ISSUE THREAD

**Issue by patterniha** [2dust/v2rayNG#4192]
10.10.34.36 is a private ip that return from iran filtering firewall when you request ip of blocked domain via (direct) dns.
i want to block this ip.
but in new version of v2rayng all private ips are bypassed  and they dont pass through vpn 
so you cant block(or other works) private ip in routing section of your config .
so there is no way to block 10.10.34.36.

in Previous versions there is option in settings that you can choose route mode between "Global Mode" and "Bypass Lan then Proxy Mode" and with global mode this problem was solved before.

but after move routing settings to main menu this item removed (and if you set a rule to block private ips, this rule not work.)

**Comment by 2dust** [comment]
In the routing settings, delete the following two and then configure your own rules
```
  {
    "remarks": "绕过局域网IP",
    "outboundTag": "direct",
    "ip": [
      "geoip:private"
    ]
  },
  {
    "remarks": "绕过局域网域名",
    "outboundTag": "direct",
    "domain": [
      "geosite:private"
    ]
  },
```

**Comment by patterniha** [comment]
> In the routing settings, delete the following two and then configure your own rules
> 
> ```
>   {
>     "remarks": "绕过局域网IP",
>     "outboundTag": "direct",
>     "ip": [
>       "geoip:private"
>     ]
>   },
>   {
>     "remarks": "绕过局域网域名",
>     "outboundTag": "direct",
>     "domain": [
>       "geosite:private"
>     ]
>   },
> ```

i know what you say. i explain exactly what happen.
i delete the default rules and add my own routing rules in my custom config.
but this rule not work.
even if you use non-custom config and delete default rule for private ips in routing menu and add your own rule, this rule not work again.

because privates ip are bypased before pass through vpn and config(in custom scenario) or block-rule(in non-custom scenario) has no effect.

you can test this easily:
for test you can block the router ip(192.168.1.1) in your custom config (or add block rule in menu for non-custom config) and you see you can accsee 192.168.1.1 again!!!.
