### ISSUE TITLE
custom config conflict with v2rayng ui routing settings!!!

### ISSUE THREAD

**Issue by patterniha** [2dust/v2rayNG#4196]
logically if you use custom-config all v2rayng-ui-settings related to config of xray-core should be ignored and should be completely controlled by custome-config.

so when you use custom-config, settings like sniffing, fragment, mux, fakedns, routing and all other settings related to configuration of xray-core  should be affected by custome-config only and settings in the v2rayng-ui-menu should be ignored.

but there is a conflict about routing settings:
for example if you block geoip:private in your custom config but 
add a rule for direct geoip:private in v2rayng-ui-routing-settings 
the ui-rule applies and custom-config-rule ignored!!! and you can access to private IPs!!!.
(I tested several cases in some cases custom-config-rule applies but in some other cases ui-rule applies!!!)

the solution is to delete(or disable) all ui-rules.(so there will be no conflict)
but i have several custome-configs and several-non-custom-configs and i want to use ui-rules for my non-custom-configs and i dont want to delete(or disable) ui-rules.

**Comment by 2dust** [comment]
You are right, the routing rules are indeed used in the VPN code, and this problem will be fixed later.

**Comment by patterniha** [comment]
> You are right, the routing rules are indeed used in the VPN code, and this problem will be fixed later.

and what about two other bugs(I reported in other issue)
