### ISSUE TITLE
routing settings have at least 3 bugs!!!

### ISSUE THREAD

**Issue by patterniha** [2dust/v2rayNG#4199]
if you delete all routing rules in v2rayng-routing-settings-menu 
then foce stop and clear cache of v2rayng and then reopen v2rayng 
all default rules returned!!!.(should returned after clear-data but not force-stop and clear- cache)

another bug is if you delete all rules you can't add any rule!!!.

and the last one is these rules conflict with custome-config-rules 
(i explain this in another issue)

**Comment by 2dust** [comment]
1. This is not a bug, it is a feature
2. This needs to be tested before deciding, if there is a problem, it will be fixed

**Comment by patterniha** [comment]
> 1. This is not a bug, it is a feature
> 2. This needs to be tested before deciding, if there is a problem, it will be fixed

returning default settings after clear-data is a feature but not after clear-cache and force-stop!

**Comment by patterniha** [comment]
> 1. This is not a bug, it is a feature
> 2. This needs to be tested before deciding, if there is a problem, it will be fixed

even if you delete all rules and then restart your phone all default rules returned!!!
