### ISSUE TITLE
新版本无法更新订阅了

### ISSUE THREAD

**Issue by swfz2008** [2dust/v2rayNG#42]
新版本无法更新订阅了

**Comment by 2dust** [comment]
并没有变,自己检查下

**Comment by swfz2008** [comment]
经过谷歌商店更新后就无法更新订阅，退回到1.0.0能正常更新订阅。

2dust <notifications@github.com> 于2019年7月29日周一 上午10:16写道：

**Comment by viqbgrg** [comment]
新版的不支持http了

**Comment by FirstJavaMaster** [comment]
@2dust 所以这是feature还是?? 将来都不支持http了吗?

**Comment by 2dust** [comment]
targetSdkVersion 28 默认情况下启用网络传输层安全协议 (TLS)
所以订阅的连接是http的就不支持了

**Comment by FirstJavaMaster** [comment]
> targetSdkVersion 28 默认情况下启用网络传输层安全协议 (TLS)
> 所以订阅的连接是http的就不支持了

原来如此, 因为订阅链接不敢放在github这种大平台上(担心被其他人看到),因此放在了小鸡上,再整个域名配SSL太麻烦了,就直接走的http

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.0.6
