### ISSUE TITLE
there are still bugs in the routing settings.

### ISSUE THREAD

**Issue by patterniha** [2dust/v2rayNG#4203]
(tested on new version 1.9.28)
assume that user add these two rules in order(for non-custom-config/or custome-config):

geoip:private --> block
geoip:private --> direct

because the block-rule is the first and the priority is from top to bottom 
the block rule should apply but direct rule apply and private ips bypassed!!!

(another example is that if you rename direct tag from
 "direct" to for example "direct2" in custom config bypass-lan not actived!)
(and another example is that if user bypass private IPs for a specific port it will be bypassed for all ports!)

i read your code you parse the rules and  
if geoip:private(or geo site:private) exist (and route to direct) you active bypass-lan.

but these examples proves that this approach is wrong.

you should not parsing the rules.
the correct approach is add checkbox in routing settings for active bypass-lan.(And it shouldn't matter whether  custom config or non-custom config)
or like previous versions add combobox for "global mode" or "bypass lan then proxy" mode.

**Comment by patterniha** [comment]
the most important reason why this code should be changed is if the user bypass private Ips for specific port it will be bypassed for all ports! 
and this is critical security bug!

meanwhile my main problem not solved yet:
i wanted to block 10.10.34.36 private ip and bypass all other private ips.
so i should add these rules in order:

10.10.34.36 -> block 
geoip:private-> direct

but 10.10.34.36 bypassed!

**Comment by patterniha** [comment]
why bypass lan in vpn code is important? 
why lan-ips needs to be bypassed in vpn-code(before reach xray-core) while can bypassed by xray-core without add any code?

Anyway if it is import you should add checkbox for it, not parsing the xray-core configuration routing rules!

**Comment by 2dust** [comment]
如果觉得代码逻辑有问题，你可以自己修改一个给自己用
原来你提的是自定义配置的问题修复后，目前的代码逻辑是没有问题的

**Comment by patterniha** [comment]
> If you think there is a problem with the code logic, you can modify it for your own use. The problem you mentioned is about custom configuration. After the problem is fixed, the current code logic is fine.

no the problem is not about custome-config  the problem is you use routing-rules in vpn code  in a unreasonable manner.
routing rules is for xray-core only, you should not use it for vpn-code.
i can give you more examples that show this approach is wrong.
