### ISSUE TITLE
there are still bugs in the routing settings number 2

### ISSUE THREAD

**Issue by patterniha** [2dust/v2rayNG#4204]
even in version 1.9.28
if you delete all rules in routing settings and close v2rayng and reopen it
the default rules returned!

i dont want to have any rules, every time tha app closed or  phone restarted i have to delete rules again!

**Comment by 2dust** [comment]
The app is for regular users and cannot function properly without routing rules. 
Users like you please define a useless rule yourself to bypass this restriction.
