### ISSUE TITLE
海思麒麟810芯片手机无法安装，显示cpu不兼容

### ISSUE THREAD

**Issue by zhzhyu** [2dust/v2rayNG#424]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
Please check your device (ARM, x86..) for the right apk or try universal version:
https://github.com/2dust/v2rayNG/releases/download/1.2.6/v2rayNG_1.2.6.apk

**Comment by AngelFalse** [comment]
你使用的是arm64架构的安装包吗？如果不是，请换成arm64的

**Comment by sky-wdl** [comment]
麒麟810用户，没遇到这个问题，应该不是手机的问题，是你选择的包有问题
