### ISSUE TITLE
v2ray还更新吗？

### ISSUE THREAD

**Issue by QZX991** [2dust/v2rayNG#426]
这个20多天没有更新了是不是作者弃坑了？因为看着以前更新的频率都是10多天更新一次。最重要的是NG还有很多的bug这个基本的我都没法用。比如连接一段时间后，网络延迟非常高、自动掉线、等等的bug。要是再不更新可咋办？有没有其他还在更新的V2ray手机客户端?

**Comment by QZX991** [comment]
这个问题关乎着我们所有用这个客户端的人。

**Comment by cuihao777** [comment]
clash for android 还行。
