### ISSUE TITLE
V2Ray开启时FCM频繁中断

### ISSUE THREAD

**Issue by Amaterasu33** [2dust/v2rayNG#43]
![Screenshot_20190729-122207](https://user-images.githubusercontent.com/28757641/62022482-2a8a6300-b1ff-11e9-91c5-8aeb0ee76a5c.jpg)

如图所示，用ss就没有这个问题。

**Comment by if1y** [comment]
把fcm相关服务器排除？

**Comment by 2dust** [comment]
请试用最新版1.1.1
