### ISSUE TITLE
[建议]在设置中增加“只开启代理端口”的选项

### ISSUE THREAD

**Issue by AngelFalse** [2dust/v2rayNG#430]
建议在设置中增加“只开启代理端口”的选项，以在支持某些可以自定义代理设置的程序的同时，让使用VPN Framework的程序可以正常运行（如NetGuard等使用VPN完成防火墙功能的程序）。

**Comment by pongfcnkl** [comment]
https://github.com/2dust/v2rayNG/issues/160

**Comment by yuhan6665** [comment]
Added in #587
