### ISSUE TITLE
使用v2rayNG点击代理成功后实际没有连接

### ISSUE THREAD

**Issue by Yoshino1942** [2dust/v2rayNG#434]
如题，按照设置弄好了，点击v启动代理成功后实际是没连上的。
![Screenshot_20200526-183101](https://user-images.githubusercontent.com/65952113/82890802-52616900-9f7f-11ea-907b-0acdcaa3b21d.png)
![Screenshot_20200526-183024](https://user-images.githubusercontent.com/65952113/82890810-57261d00-9f7f-11ea-98ef-bef173dd331b.png)

**Comment by Yoshino1942** [comment]
android10

**Comment by 7616821** [comment]
我的也是

**Comment by 892003867** [comment]
我的也是，安卓机，mac电脑全是ping测试-1ms，真后悔搞年会员，如果还解决不了，也没法退款，就到处论坛帖子宣传这坑人的vpn了。劝一个别买就少一个人上当，当做好事了！

**Comment by ghost** [comment]
> 我的也是，安卓机，mac电脑全是ping测试-1ms，真后悔搞年会员，如果还解决不了，也没法退款，就到处论坛帖子宣传这坑人的vpn了。劝一个别买就少一个人上当，当做好事了！

v2rayNG并不是某个商业公司的vpn，而是由社区力量支持开发的反网络审查的代理工具。
你所遇到的问题一般来说并不是因为软件有什么问题，而是提供这类服务的商家存在某些问题，问题跟商家有关，跟软件作者无关。

**Comment by ghost** [comment]
> 我的也是，安卓机，mac电脑全是ping测试-1ms，真后悔搞年会员，如果还解决不了，也没法退款，就到处论坛帖子宣传这坑人的vpn了。劝一个别买就少一个人上当，当做好事了！

如果你购买商家的服务不满意的话，有条件也可以自行搭建服务器。
