### ISSUE TITLE
订阅地址如果重定向了，APP订阅会失败

### ISSUE THREAD

**Issue by DeathInTheAir** [2dust/v2rayNG#436]
pc端能订阅成功，但APP上提示订阅失败

订阅地址重定向用的nginx的rewrite，没加其他的，不知道有没其他解决办法

**Comment by yuhan6665** [comment]
What is your subscription page http status code? I did a quick test with 301 and 302. It was working for me.

**Comment by shi-yue-sl** [comment]
我也是，同一个订阅链接，电脑上可以更新订阅，手机端一直订阅失败

**Comment by CodeFly16** [comment]
我也是 电脑上面能更新，但是手机端有问题，各位解决了吗

**Comment by xietao1233** [comment]
我两个手机, nokia能更新订阅成功, sony更新订阅失败
