### ISSUE TITLE
可能由于DNS解析引发的问题

### ISSUE THREAD

**Issue by daiaji** [2dust/v2rayNG#437]
我在V2rayNG里指定了一个中继V2服务器
而且我在中继V2服务端的路由配置里做了gfwlist
问题来了
V2rayNG似乎默认会用1.1.1.1当远程DNS作解析（姑且我在中继路由器上将1.1.1.1的流量全代理了）
然后客户端可以获取到google的正确ip地址……
但这显然没卵用……
因为gfwlist里面显然没有google的IP地址……

服务端日志
```
2020/05/27 19:37:38 *.*.*.*:58539 accepted tcp:172.217.8.131:443 [direct] 
2020/05/27 19:37:59 *.*.*.*:58540 accepted tcp:142.250.64.78:443 [direct] 

```
这没有任何意义……
因为如果没有匹配到gfwlist的话当然不可能被代理啦……

我该怎么办？

**Comment by rurirei** [comment]
configure one routing for domain ["dns.google"].
