### ISSUE TITLE
V2ray ng开启时投屏软件搜不到dlna设备问题

### ISSUE THREAD

**Issue by darkninjya** [2dust/v2rayNG#439]
本软件开启vpn时，设置走vpn的投屏app搜索不到dlna设备,也设置了bypassing LAN and mainland address，但是用clash for Android开vpn时就没有问题。请问v2ray ng设置的绕过LAN和clash里设置的bypass private network addresses有什么不同，能不能也做的和clash一样能开vpn用投屏软件。

**Comment by zjudongze** [comment]
遇到类似的问题了，几个月前还能把netflix  投屏到电视上观看，最近投屏到电视上就很卡花屏，各种问题；关了v2rayng，投屏就没问题，已经设置绕过局域网了；

logcat中也显示走direct，但是一直udp out  of  buffer。
会不会是udp  fd的send  buffer设的太小了？

**Comment by yuhan6665** [comment]
Should be fixed in #517
