### ISSUE TITLE
Import customize config format?

### ISSUE THREAD

**Issue by miyorineko** [2dust/v2rayNG#44]
Hello there,
What's the correct format for the customize config? Is it the config.json format or a vmess:// URL?

**Comment by DrakeTsui** [comment]
Correct me if I'm wrong
If you're trying to import a config.json file, you can do so by

>  "+" → "Import custom config from locally" 
to choose a local config.json file to import

or 
> "Import custom config from URL"
to import a config.json file from the URL of your clipboard

or
> "Import custom config from scan URL"
to import a config.json file from a QR code scan, however this feature is not the same as the first option "Import config from QRcode" which is meant for a vmess://*
