### ISSUE TITLE
能否增加DNS over TLS或DNS over HTTPS功能？

### ISSUE THREAD

**Issue by okudayukiko** [2dust/v2rayNG#441]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
使用DNS over TLS或DNS over HTTPS後，看視頻明顯加快。
原因可能是因為，GFW的深度包檢測，或日本梯子訪問8.8.8.8（8.8.8.8伺服器在美國）導致的UDP丟包？
Android 9內建DNS over TLS功能。Firefox PC版內建DNS over HTTPS功能。

**Comment by rurirei** [comment]
use localDNS for configure custom dns servive. https://github.com/2dust/v2rayNG/issues/332#issuecomment-703075531

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/issues/647
