### ISSUE TITLE
建议增加TLS证书的域名设定

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#445]
在allowInsecure关闭，即不允许不安全的证书链接情况下，若要链接一个http/ws，其header里面携带的host与TLS证书的host不同的配置则无法建立链接。
下列情况则无法正常使用V2RAYNG链接
服务器域名a.com 落地机b.com,希望利用a.com来中转流量到b.com。此时最上面的地址填写a.com,ws下面的header填写b.com.这时无法建立任何链接，证书错误。而其他客户端可分开设置TLS域名和ws header域名则不会出现这种问题。
希望能够增加该功能。

**Comment by lzghzr** [comment]
在多个服务器使用同一域名时也有用，希望可以增加
