### ISSUE TITLE
能否考虑增加对Trojan的支持

### ISSUE THREAD

**Issue by zxq1002** [2dust/v2rayNG#446]
相比而言速度比WebSocket+TLS要快不少，但安全性差不多。速度上TCP最快，但是已经有个端口被封了。。

**Comment by phlinhng** [comment]
可以用 V2Ray TCP+TLS

**Comment by Hikpy** [comment]
同问

**Comment by zxq1002** [comment]
clash for Android支持trojan，只是配置略麻烦
