### ISSUE TITLE
从本项目releases页面下载的universal apk无法被安装

### ISSUE THREAD

**Issue by maidmeow4** [2dust/v2rayNG#448]
未按照模板提交issue，抱歉。

1. 从releases页面选择下载1.2.8 universal apk （`v2rayNG_1.2.8.apk`）
2. 传输到Android设备上进行正常安装
3. 装有Android 7.1.2的N1盒子在点击安装后，正在安装进度条走了一会后，提示“该软件包似乎已损坏”
  装有Android 9的Sony XZ1在点击安装后，界面一直卡在正在安装

7zip测试压缩包功能提示“未发现错误”；下载了两次的apk的SHA1都为 `1DC073E9801EE7459F8CF0D5FF8750464E6395CA`

**Comment by madlaxcb** [comment]
> 
> 
> 未按照模板提交issue，抱歉。
> 
>     1. 从releases页面选择下载1.2.8 universal apk （`v2rayNG_1.2.8.apk`）
> 
>     2. 传输到Android设备上进行正常安装
> 
>     3. 装有Android 7.1.2的N1盒子在点击安装后，正在安装进度条走了一会后，提示“该软件包似乎已损坏”
>        装有Android 9的Sony XZ1在点击安装后，界面一直卡在正在安装
> 
> 
> 7zip测试压缩包功能提示“未发现错误”；下载了两次的apk的SHA1都为 `1DC073E9801EE7459F8CF0D5FF8750464E6395CA`

我的oneplus 7的安卓10在这下的也无法安装，在谷歌商店那成功更新了。

**Comment by mclovin-2k** [comment]
PackageInstaller 给的信息不足。
用adb install 安装，看看到底报的什么错误。

**Comment by maidmeow4** [comment]
经过测试，这个问题发生在从 `1.2.6` 更新到 `1.2.8` 时；删除并全新安装是成功的

`adb install` 报告错误
`Failed to install files\1_v2rayNG_1.2.8.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]`

**Comment by mclovin-2k** [comment]
> 经过测试，这个问题发生在从 `1.2.6` 更新到 `1.2.8` 时；删除并全新安装是成功的
> 
> `adb install` 报告错误
> `Failed to install files\1_v2rayNG_1.2.8.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]`

你找个apk信息查看工具看一下2个APK的VersionCode。
你这个错误是因为你手上的1.2.8的VersionCode小于1.2.6造成的。

**Comment by maidmeow4** [comment]
releases 下载的 1.2.8 universal apk 的 VersionCode 值是 292；
这个 1.2.6 好像是 Play 商店的，VersionCode 值是 2000290
