### ISSUE TITLE
华为荣耀智慧屏使用V2RayNg打开节点加速时闪退

### ISSUE THREAD

**Issue by hsuhoo** [2dust/v2rayNG#452]
华为的智慧屏，安卓TV，可以正常添加节点，但是一点击开启按钮就会闪退😭求求作者优化下，感激不尽

**Comment by yuhan6665** [comment]
Please upload adb log

**Comment by fniks** [comment]
我也一样，华为智慧屏，一点连接就闪退

**Comment by yocus** [comment]
感觉荣耀智慧屏X1根本不能用，哎，应该是华为的问题。

**Comment by yfq512** [comment]
华为v75 同样的问题，猫咪、机场也是一样，不是连接闪退就是中间哪步报错，看来只能从路由器下功夫了

**Comment by yocus** [comment]
> 華為v75 同樣的問題，貓咪、機場也是一樣，不是連接閃退就是中間哪步報錯，看來只能從路由器下功夫了

在鸿蒙系统的电视机上这个问题无解，只能搞软路由来解决了。
