### ISSUE TITLE
作者大大有没有考虑加个多路复用mux功能？

### ISSUE THREAD

**Issue by GleenJi** [2dust/v2rayNG#456]
感觉mux好像挺好的，而且明显感觉网页打开速度变快了，当然也许是其他原因导致的

**Comment by ghost** [comment]
这个选项没有什么用处，如果打开这个功能的话会导致传输速度大幅下降，因为请求全部塞到一个连接里了。弊大于利。

**Comment by GleenJi** [comment]
> 
> 
> 这个选项没有什么用处，如果打开这个功能的话会导致传输速度大幅下降，因为请求全部塞到一个连接里了。弊大于利。

是吗，小白不太懂，感觉加不加差别不大，只是作为一个功能单纯觉得功能越多越好，可选择性越多越好
