### ISSUE TITLE
能否增加个“不显示”状态栏的icon

### ISSUE THREAD

**Issue by delphinuz** [2dust/v2rayNG#457]
不希望状态栏出现v2rayng的icon，能否设个开关，谢谢。

**Comment by yuhan6665** [comment]
In order to run proxy in the background, we need a foreground service with a visible notification. Otherwise, v2rayNG will be killed by Android.

**Comment by ghost** [comment]
Android系统本身就支持这个功能，设置一下通知优先级就好。方法大概是这样的（举例）：
原生Android10：进入设置-应用与通知-查看全部应用-v2rayNG-通知-v2ray background service-最小化通知
其他定制系统：长按桌面上的图标-应用信息-通知管理-v2ray background service-通知优先级-低：不在屏幕上弹出通知，也不在屏幕上显示通知

**Comment by delphinuz** [comment]
通知栏(Alarting notifications)出现没问题，因至少要下拉才知道，也可以知道是否正在运行。
状态栏(StatusBar)会占个位置，而且也不希望出现。

原生Android10的通知管理，是同时不显示在通知栏与状态栏，但我希望状态栏不显示，但下拉的通知可以显示，方便知道是否正在使用与使用哪个服务器。

更新：
刚发现可以用QS的VPN來表示目前VPN情况，可解决显示V2RayNG是否正在运行。

**Comment by ghost** [comment]
Android 10的通知管理本身就支持把通知最小化的，也就是你提到的状态栏不显示，通知栏显示。
Android 8开始就可以这样了，调整通知优先级就行。

[Image]


[Image]
________________________________
