### ISSUE TITLE
mac全部无法连接，安卓机也是全部无法连接

### ISSUE THREAD

**Issue by 892003867** [2dust/v2rayNG#459]
安卓手机和电脑端mac上，测试ping全是-1ms，选择任何一个都是无法连接，无法上google，是真的心累，唉。。。

![1326A741-852E-42CE-A194-F7FFC534B34E](https://user-images.githubusercontent.com/21984927/84010228-f6e3a200-a9a6-11ea-9b9f-2e62f362f9dd.png)

**Comment by ghost** [comment]
如果电脑上也是这样的话，说明节点已经被封了。与软件问题无关，建议去服务商那里问问解决方式。
