### ISSUE TITLE
let's encrypt TLS加密在Android手机端无法连接

### ISSUE THREAD

**Issue by ysmintor** [2dust/v2rayNG#46]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。填写完问题模板后请删除提示，否则可能会被直接关闭问题。

### 预期行为
描述你认为应该发生什么
在电脑端的v2rayN可以正常配置可以连接，但手机端无法连接，更换为无TLS的配置后正常。
### 实际行为
描述实际发生了什么

### 复现方法
1.将电脑端的信息配置到手机上使用
2.服务端添加TLS和无TLS的TCP inbound
3. 电脑上的v2rayN可以正常连接，手机上连接后实际无法访问。

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by kirbyzhu** [comment]
我实测没问题，应该是你哪里设置有误。

**Comment by matterwind** [comment]
我也遇到了同样的问题，开启tls后，手机端无法链接，同样的配置在电脑端正常。

**Comment by ysmintor** [comment]
我就是如此的，检查设置几次。最后换成了WS+TLS方式，手机和电脑都能用

**Comment by ZhouZiY** [comment]
It may the problem in #58 .

**Comment by ysmintor** [comment]
@ZhouZiY 并不是这个原因，我最后采用了WS+TLS来解决的。
