### ISSUE TITLE
请问能给本地dns加入edns功能吗？

### ISSUE THREAD

**Issue by LittleGrocery** [2dust/v2rayNG#460]
请问能给本地dns加入edns功能吗？无论对本地还是远程都有意义

**Comment by ghost** [comment]
这个问题与软件无关。是选择的dns服务器问题。dns服务器支持就行。
举个例子来说，当dns解析方式选择为远程dns，地址为8.8.8.8的时候，dns请求时本身就会带上vps的ip地址。
如果选择为v2ray-core处理本地dns的话，只要设置的dns服务器支持这个功能，那道理同上。
