### ISSUE TITLE
udp包无法被正常解析

### ISSUE THREAD

**Issue by 469312306** [2dust/v2rayNG#462]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
均用最新版的v2ray-core和v2rayNG，手机连接电脑v2ray-core服务器，允许来自局域网连接。

### 实际行为
udp包无法被正常解析，电脑端报错。

### 复现方法
1.电脑端新建socks服务器（本地socks5服务器默认127.0.0.1:10808）
2.手机端新建socks客户端连接电脑端socks服务器（电脑ip:10808）
3.udp包报错

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
2020/06/11 06:49:46 tcp:10.20.194.182:49210 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
2020/06/11 06:49:47 tcp:10.20.194.182:38191 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
2020/06/11 06:49:48 tcp:10.20.194.182:38797 rejected  v2ray.com/core/proxy/socks: insufficient header > EOF
2020/06/11 06:49:49 tcp:10.20.194.182:39031 rejected  v2ray.com/core/proxy/socks: failed to read request > EOF
```
</details>

### 环境信息
win10 19.09 18363.836+android 9 miui 11.0.7

**Comment by xja** [comment]
很早就发现了这个问题，现在还是不能连接v2rayN开放的socks端口

**Comment by rurirei** [comment]
use 0.0.0.0:10808 at your computer.
