### ISSUE TITLE
connectionReuse 是否为无效配置

### ISSUE THREAD

**Issue by rhjdvsgsgks** [2dust/v2rayNG#464]
虽然不影响使用，官方更新日志说在 [2.23](https://www.v2fly.org/chapter_00/01_versions.html#20170415-v223) 中就已经移除了 connectionReuse 的配置，但默认生成的配置中还是包含了 connectionReuse 一项，这算是无效的配置吗

**Comment by yuhan6665** [comment]
@rhjdvsgsgks thanks for your feedback. You are right, this option is no longer valid. It will be cleaned up in #468
