### ISSUE TITLE
请问安卓版的配置文件在哪里

### ISSUE THREAD

**Issue by galaxyskyknight** [2dust/v2rayNG#466]
请告知安卓版的配置文件路径，4.24.2如果要启用vmessAEAD,好像需要手动写配置文件加入testsEnable:true,  客户端界面没给这个配置选项啊？求告知配置文件路径，只能自己加了。

**Comment by supermagicianck** [comment]
应该是在添加服务器中选择自定义配置，然后导入本地配置文件

**Comment by ymcoming** [comment]
1、配置选中相应节点-分享-复制完整配置
2、新增节点-导入自定义配置-从剪贴板导入
3、修改文本，增加这行代码，保存
