### ISSUE TITLE
客户端能不能增加个一键连接的功能？

### ISSUE THREAD

**Issue by bestAmericanlife** [2dust/v2rayNG#467]
为啥客户端都搞的这么复杂，我想要找个一键连接的移动端源码，我的Telegram： t010100

**Comment by ymcoming** [comment]
把V2添加到系统图标上，每次下滑-点击Ⅴ2就打开了。跟你开数据流量、GPS、蓝牙一样方便。
下拉-点击-开，下拉-点击-关

**Comment by ghost** [comment]
建议通过添加通知栏快捷开关的方式来快速连接。v2rayNG不太可能会在以后提供一键连接最快节点的功能。
这不是商业vpn，只是一个由社区力量支持开发的反网络审查的代理工具，并且软件作者本身也并不经营任何代理或vpn类业务。
