### ISSUE TITLE
QUIC方式连不上

### ISSUE THREAD

**Issue by ymangu163** [2dust/v2rayNG#47]
我服务端安装的是v2ray core 4.20.0版本，v2rayng是1.0.3版本，core应该也是4.20.0   但是采用QUIC方式拨不上号，其它方式可以。请问是什么问题呢？

**Comment by 2dust** [comment]
提供log
quic目前体验很差,暂时不继续了

**Comment by mem0rz** [comment]
same config is work on v2rayn.but not work on v2ng.
[v2ngquiclog.txt](https://github.com/2dust/v2rayNG/files/3883239/v2ngquiclog.txt)
