### ISSUE TITLE
Google Play Store商店显示“从服务器检索信息时出错”

### ISSUE THREAD

**Issue by zsbstephen** [2dust/v2rayNG#47]
Samsung S7，Android 7.0.1系统。用SSR从Google Play下载下来的0.3.10最新版，服务器和客户端的参数均无误，PC可以正常用，手机上面浏览器、Telegram、facebook、twitter、youtube、gmail的app都正常工作，就唯独Google Play商店显示出错。分应用代理、路由（全局/绕过大陆/GEO全家桶）功能都试了遍依然如此。同样的参数下用Actinium倒是能正常用Google Play商店（但Actinium只能全局，改配置文件加入domain override和chinasite等等全都无效，完全没法比绕过大陆，非常蛋疼）

**Comment by zsbstephen** [comment]
![screenshot_20180223-004117](https://user-images.githubusercontent.com/19226303/36552710-7f1e7d30-1835-11e8-97d9-1239c49e6fb0.png)
上个截图~

**Comment by zsbstephen** [comment]
配置文件如下
`{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "listen": "127.0.0.1",
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    },
    "domainOverride": [
      "http",
      "tls"
    ]
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "192.168.0.1",
          "port": 12345,
          "users": [
            {
              "id": "377c6594-4868-4454-ac6f-88de6124afe8",
              "alterId": 64,
              "level": 0
            }
          ]
        }
      ]
    },
    "tag": "proxy",
    "streamSettings": {
      "network": "tcp",
      "security": "none",
      "tlsSettings": {
        "serverName": "",
        "allowInsecure": false
      },
      "tcpSettings": {
        "header": {
          "type": "none",
          "request": {}
        }
      },
      "kcpSettings": {
        "mtu": 1350,
        "tti": 50,
        "uplinkCapacity": 5,
        "downlinkCapacity": 20,
        "congestion": false,
        "readBufferSize": 2,
        "writeBufferSize": 2,
        "header": {
          "type": "none"
        }
      },
      "wsSettings": {
        "path": "",
        "headers": {}
      }
    },
    "mux": {
      "enabled": false,
      "concurrency": 8
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        }
      ]
    }
  }
}`

**Comment by sofs2005** [comment]
我也是同样的问题，其他都没问题，就是play store不行，但是我改成全局的话是可以打开的，但是下载速度超级慢。不知道什么原因，我是0.3.6版本，华为cpu装不了新版本。。。

**Comment by ncs19960831** [comment]
可以添加自定义路由：google.com

**Comment by 2dust** [comment]
终于弄清为何在路由绕开大陆地址时其他app正常翻墙，唯独PLAY会出现连接超时。只要把services.googleapis.cn加入v2rayNG的需代理列表，就行了。

**Comment by zsbstephen** [comment]
@2dust 感谢作者~！果然把这串域名放routing里面让强制走vmess出去，的确就可以正常开Google Play商店了~这个ticket可以close了~
另外参考Telegram群里其他人的配置，额外加了ggpht.cn、1e100.net着2个个域名，上whois一查的确都是还没重返中国的服务的域名，都是“假”的cn域名~

``{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "listen": "127.0.0.1",
    "port": 1080,
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true
    },
    "domainOverride": [
      "http",
      "tls"
    ]
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "127.0.0.1",
          "port": 12345,
          "users": [
            {
              "id": "377c6594-4868-4454-ac6f-88de6124afe8",
              "alterId": 64,
              "security": "aes-128-gcm",
              "level": 0
            }
          ]
        }
      ]
    },
    "tag": "proxy",
    "streamSettings": {
      "network": "tcp",
      "security": "none",
      "tlsSettings": {
        "serverName": "",
        "allowInsecure": false
      },
      "tcpSettings": {
        "header": {
          "type": "none",
          "request": {}
        }
      },
      "kcpSettings": {
        "mtu": 1350,
        "tti": 50,
        "uplinkCapacity": 5,
        "downlinkCapacity": 20,
        "congestion": false,
        "readBufferSize": 2,
        "writeBufferSize": 2,
        "header": {
          "type": "none"
        }
      },
      "wsSettings": {
        "path": "",
        "headers": {}
      }
    },
    "mux": {
      "enabled": false,
      "concurrency": 8
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "dns": {
    "servers": [
      "208.67.222.222",
      "208.67.222.220",
      "208.67.220.123",
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "googleapis.cn",
			"ggpht.cn",
			"1e100.net"
          ],
          "outboundTag": "proxy"
        },
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "direct"
        },
        {
          "type": "chinaip",
          "outboundTag": "direct"
        },
        {
          "type": "chinasites",
          "outboundTag": "direct"
        }
      ]
    }
  }
}
``

**Comment by kirbyzhu** [comment]
@2dust 能否请在系统提示栏目里面增加上下行网速的显示？ss系列都有，看着比较舒服。

**Comment by ygfly** [comment]
这个问题目前好像只有影梭能搞定。
