### ISSUE TITLE
1.2.10 在Android 11 beta1 下是否有耗电问题？

### ISSUE THREAD

**Issue by Cirooo** [2dust/v2rayNG#470]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

前几天我的pixel2更新用上了Android 11，没感觉耗电上有什么问题，昨天从play store更新了ng到1.2.10版，睡一觉从100%降到了37%，系统内电池用量统计面版全是ng的。现在充电时发热量也比以往的大。有其他使用着Android11的也请关注一下耗电情况。我已经先给Google团队提交了bug反馈，ng这边我先回退到旧版试试。

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ghost** [comment]
如果在Android11上，不明确指定加密方式为chacha20的话，的确会存在耗电问题。只能看开发者后续怎么解决了。

**Comment by Cirooo** [comment]
> 如果在Android11上，不明确指定加密方式为chacha20的话，的确会存在耗电问题。只能看开发者后续怎么解决了。

我回退到1.2.8之后，不存在这个问题咧，电池使用压根就不显示ng了

**Comment by Cirooo** [comment]
好吧，旧版的也出现了，果断更新并改成chacha看看
