### ISSUE TITLE
貌似会强制缓存DNS多达数天？服务器解析了新的IP后，客户端不杀死进程重开app的话，，会一直解析之前的IP

### ISSUE THREAD

**Issue by 1265578519** [2dust/v2rayNG#472]
貌似会强制缓存DNS多达数天？服务器解析了新的IP后，客户端不杀死进程重开app的话，，会一直解析之前的IP
导致客户端连接还是老的服务器，没有换到新的上面

**Comment by yuhan6665** [comment]
@1265578519 looks like it is an issue in AndroidLibV2rayLite, the prepared domain is not cleared unless service is restarted. I will try to put a fix. Do you think 1 hour is a reasonable time for DNS cache?

**Comment by 1265578519** [comment]
如果开发难度不大的话，可以的话，我认为遵守域名本身DNS TTL时间为佳。
或者采用DNS默认的600 ttl = 10分钟。而不是1小时

**Comment by yuhan6665** [comment]
I understand many DNS TTL can give shorter than 5 minutes. Making it to too short will be a performance hit for all proxy traffic. That's why I prefer longer cache. You won't change your IP too often right?

**Comment by 1265578519** [comment]
一个DNS查询不到0.1KB，大约85字节左右。感觉不太会引起流量损耗。而且这一部分是向DNS查询的，而不是通过代理服务器。当到了突然想要更换IP的时候，他却没变动，，这个是比较坑的，而不是经常更换不同的IP，是有需要更换的时候，他却迟迟不生效

**Comment by yuhan6665** [comment]
Ok I will consider it.

**Comment by yuhan6665** [comment]
Submit #474 to fix this.

**Comment by eroxs** [comment]
I connect to the tls + ws or http + tcp configuration and everything looks good at first
But suddenly (maybe a few hours or minutes later) when I try to open a site in a browser, I get an error I can not find the DNS address.
This error is very weak in the Chrome browser (sometimes displayed but the site suddenly opens)
This is also true for applications that use domains.
You have to think and have a solution
This does not look good at all

**Comment by 1265578519** [comment]
主要重连也是老的IP引起的，，必须退了客户端，不知道新版修复了没我还没测试
看官方提交的PR，应该没有解决，，，因为产生了一个新的BUG所以直接还原了代码
https://github.com/2dust/v2rayNG/pull/537

**Comment by eroxs** [comment]
What exactly should be done? In version 1.2.14, I noticed a change of domain every 30 minutes, but in less than 30 minutes we may have a problem.
And it was written that it creates a bug, which of course had a technical solution, but its build was never published (by fixing the bug)
Let me know if it is possible to change it from 30 minutes to 5-10 minutes and we will fix the problem, because my customers are very upset.

**Comment by eroxs** [comment]
@yuhan6665 @1265578519 could you build a version  that fix that ? same 1.2.14 with fix issue in  [903352e](https://github.com/2dust/v2rayNG/commit/903352ec9c4231131ea2ad75b68661526a47d156) [2dust/AndroidLibV2rayLite#16](https://github.com/2dust/AndroidLibV2rayLite/pull/16) with Refresh prepared domain every 5 minutes ?? with last libv2raylite .
i edit libv2raylite but dont know how set in V2rayNG/app/libs/libv2ray.aar 
help.

**Comment by 1265578519** [comment]
@eroxs 目前的解决办法就是杀死app，重新打开

**Comment by eroxs** [comment]
@1265578519 In version 1.2.14 the situation has improved and when I encounter a problem, it will be resolved after half an hour
I want to reduce the time. [Refresh prepared domain every 30 minutes will work well](https://github.com/2dust/v2rayNG/commit/903352ec9c4231131ea2ad75b68661526a47d156)

**Comment by eroxs** [comment]
i just need more help for build with  Refresh prepared domain every 5 minutes and with bugs

**Comment by 1265578519** [comment]
我解决不了这个问题，我不是开发者，要等其它人来操作
我认为降低间隔时间到5分钟的同时，应该启动服务重连的时候要立即刷新DNS。

**Comment by eroxs** [comment]
In the new versions ( core 4.31.2 i test ) , the problem is resolved after reconnecting (find DNS problem will resolved)
But when someone does not know, it is an annoying issue.
