### ISSUE TITLE
使用v2rayNG Google play store 服务器连接失败

### ISSUE THREAD

**Issue by RobinUgly** [2dust/v2rayNG#473]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
使用应用分流，Google play 服务器连接成功并登陆使用

### 实际行为
描述实际发生了什么
怎么设置（除全局没试）google play store 从服务器检索信息时出错。DF-DFERH-01

### 复现方法
1.应用分流
2.取消应用分流

### 日志信息
<details>
无日志
</details>

### 环境信息
小米6 安装Google套件，apkpure可以连接使用
v2rayNG V1.2.10

**Comment by ghost** [comment]
此问题与v2ray无关。按应用分流的话，估计也无法解决。如果按地址分流的话则不存在该问题。
导致该问题的真正原因是Google Play服务检测到这台手机是国行手机，之后就会去请求 googleapis.cn 网域下的一个域名才出现的这种现象。
如果不使用代理的话解析出来的ip是北京的，而因为众所周知的原因，北京的ip已经好长时间不再提供服务了，所以返回的状态码就只能是404了。因此在Google Play商店里就看到出错了。

**Comment by RobinUgly** [comment]
之前，可以连接成功并使用的

**Comment by RobinUgly** [comment]
现在可以正常使用
我关闭miui优化
使用apkpure更新了Google play服务
然后国行小米6正常使用Google play store
