### ISSUE TITLE
WS+TLS模式下无法从Google Play下载和更新APP（全局也不行）

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#477]
WS+TLS模式下谷歌商店无法下载和更新应用（全局也不行）
测试过几台安卓设备都无法下载更新

**Comment by RobinUgly** [comment]
可以尝试apkpure 下载更新Google play 服务，也许能够正常访问Google play store

**Comment by ghost** [comment]
> 可以尝试apkpure下载更新Google play服务，也许能够正​​常访问Google play store

我其他软件都能正常访问、更新、下载
V2RayNG能访问但是不能下载更新
Google框架是没有问题的

**Comment by ghost** [comment]
WS节点倒是可以正常下载更新APP
WS+TLS就不行了
测试过其他两款支持V2Ray的APP
在WS+TLS模式下是可以正常在Play商店下载更新APP的

**Comment by pscj** [comment]
我去，遇到一个和我一样问题的，我也是ws+tls,然后其它都正常，就是google商店下载不了，google商店能访问，就是不能下载

**Comment by ghost** [comment]
解决了

额外ID改成0就可以了

**Comment by pscj** [comment]
> 解决了
> 
> 额外ID改成0就可以了

我改了也没变化，只好弃坑

**Comment by dadadamimi** [comment]
不知道你们的ws+tls安卓为什么能用，我的电脑端能用，手机端反而不能用，很愁

**Comment by LiHang941** [comment]
bifrostv可以下，刚刚试的

**Comment by WinRec** [comment]
试遍能找到的各种方法，最后从这个帖子中找到解决方法（https://www.v2ex.com/t/696735?p=1）：从apkpure.com上重新下载google play service 和store覆盖安装原国内手机上的这两个app就能下载app了。我的情况和那个帖子中描述的症状一模一样，原线路一直好用，自从系统升级后就不能下载只能浏览。应该就是国内版本的google框架还是不一样

**Comment by freehuoshan** [comment]
我也遇到了该问题，最终通过，在左上角settings 中，将Enable Sniffing 复选框取消勾选后，重新连接后解决了。

**Comment by dbguo** [comment]
> 我也遇到了该问题，最终通过，在左上角settings 中，将Enable Sniffing 复选框取消勾选后，重新连接后解决了。

牛批，解决了

**Comment by shyboy0415** [comment]
> > 我也遇到了该问题，最终通过，在左上角settings 中，将Enable Sniffing 复选框取消勾选后，重新连接后解决了。
> 
> 牛批，解决了

我还是有问题唉

**Comment by TioeAre** [comment]
设置关闭 “启用本地dns”即可

**Comment by moejun** [comment]
> 我也遇到了该问题，最终通过，在左上角settings 中，将Enable Sniffing 复选框取消勾选后，重新连接后解决了。

解决了！

但是为什么呢。。。

**Comment by maxinzheng** [comment]
换节点解决的，美国的就是不行，香港的马上OK

**Comment by miao-o** [comment]
> 换节点解决的，美国的就是不行，香港的马上OK

是这样 而且上面的启用嗅探关了也没有，我美西的不能下香港的直接就能，怀疑是把下载的CDN代理了，因为我美西的如果下载等待中关闭VPN有时候就能裸连下载play商店的软件了

**Comment by a7066593** [comment]
> 我也遇到了该问题，最终通过，在左上角settings 中，将Enable Sniffing 复选框取消勾选后，重新连接后解决了。

谢谢，我用了你的方法也解决了，中文版的是嗅探默认开启，关闭了就可以直接下载了。
