### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by dna1982** [2dust/v2rayNG#48]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。填写完问题模板后请删除提示，否则可能会被直接关闭问题。

### 预期行为
描述你认为应该发生什么
占用内存不超过50M

### 实际行为
描述实际发生了什么
占用内存近500M

### 复现方法
1.打开“设置”
2.打开“正在运行的程序”
3.查看V2RayNG的内存占用

### 日志信息
<details>
无
</details>

### 环境信息
server version：3.10
V2RayNG version：0.3.10
android version：Resurrection Remix (android 7.1)

### 额外信息（可选）
![_20180223153053](https://user-images.githubusercontent.com/5440567/36582968-8ebd1ad4-18ae-11e8-86e0-e8eeb4472a9a.jpg)

**Comment by ncs19960831** [comment]
v2ray-core作者曾说过v2ray服务器占用内存高的原因。
感觉有可能是这个问题。你可以试试打开mux

**Comment by dna1982** [comment]
我又研究了一下，感觉不是因为v2ray core占用高的原因。
因为重启手机后，第一次打开V2RayNG建立链接，内存占用只有80多MB。随着使用时间的增长，内存占用会越来越高，最后能占到将近1GB。
感觉有点像内存泄露。

SS/SSR的Android客户端就没有这个问题……在PC上直接用V2Ray Core也没有这个问题……

**Comment by ITBINGCHENG** [comment]
太他妈费电了，手机一直烫手，现在夏天就换回ss了，等冬天再用
