### ISSUE TITLE
[Feature Request] Support for VLess Protocol

### ISSUE THREAD

**Issue by liamcos** [2dust/v2rayNG#480]
> 总而言之，相较于 VMess，基于 TLS 或内网等可信通路时用 VLess 性能更好，更省双边的内存和 CPU、耗电更少。 游戏等对性能要求高的场景需要它，手机等移动设备、配置低的服务器也需要它，路由器、树莓派等透明代理更是需要它

https://github.com/v2ray/v2ray-core/issues/2583

**Comment by RPRX** [comment]
目前 VLess 还处于测试、修改阶段，暂不着急加入图形客户端

等相关代码正式并入 v2ray-core 后，图形客户端加个协议不是难事

**Comment by 2dust** [comment]
等Vless合并入core后再处理.
此协议很符合现在的真实情况.我们关注中

**Comment by 2dust** [comment]
[v2rayNG_1.2.12-vless_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/4851889/v2rayNG_1.2.12-vless_arm64-v8a.apk.zip)

打包了个版本，暂时只能使用自定义配置使用vless，有需要的可以尝试下

**Comment by 2dust** [comment]
[v2rayNG_1.2.13-vless_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/4861325/v2rayNG_1.2.13-vless_arm64-v8a.apk.zip)

https://github.com/rprx/v2ray-vless/releases/tag/clean2

使用自定义配置使用Vless, 有需要的可以尝试

**Comment by 2dust** [comment]
inbouds/outbouds
{
    "protocol": "vless",
    "settings": {
        "vnext": [
            {
                "address": "address.com",
                "port": 443,
                "users": [
                    {
                        "encryption":"none",
                        "id": "11f1523b-27f2-4c2d-9553-6d29138f735b",
                        "level": 8
                    }
                ]
            }
        ]
    }
}

**Comment by rprx** [comment]
@2dust 

这个是 Outbound 的配置，Inbound 的类似于 VMess Inbound

**Comment by 2dust** [comment]
```
outbouds
{
    "protocol": "vless",
    "settings": {
        "vnext": [
            {
                "address": "address.com",
                "port": 443,
                "users": [
                    {
                        "encryption":"none",
                        "id": "11f1523b-27f2-4c2d-9553-6d29138f735b",
                        "level": 8
                    }
                ]
            }
        ]
    }
}
```

```
inbouds
{
    "port": 23456,
    "protocol": "vless",
    "settings": {     
       "encryption":"none",
        "clients":
        [
            {
                   
                "id":"30f1523a-27f2-4c2d-9553-6d29138f735b"
            }]
    }
}
```

**Comment by changyp6** [comment]
@2dust 

测试了，可以用！

> [v2rayNG_1.2.13-vless_arm64-v8a.apk.zip](https://github.com/2dust/v2rayNG/files/4861325/v2rayNG_1.2.13-vless_arm64-v8a.apk.zip)
> 
> https://github.com/rprx/v2ray-vless/releases/tag/clean2
> 
> 使用自定义配置使用Vless, 有需要的可以尝试

**Comment by changyp6** [comment]
@2dust 
你这个里面的inbounds写错了。

“encryption": "none",应该是outbounds里面的, 要写在每一个”users"里面。
和"clients":是同级的是“decryption"，只用和“clients"同级
应该是
```
"inbounds" {
     "settings": {
        "decryption": "none",
        "clients": [
            {
                "id": "xxxx-xxxx-xxx-xx-xxxxxx-xxxxxxxxx",
                "level": 0
            }
        ]
    }
}
```
> outbouds
> {
> "protocol": "vless",
> "settings": {
> "vnext": [
> {
> "address": "address.com",
> "port": 443,
> "users": [
> {
> "encryption":"none",
> "id": "11f1523b-27f2-4c2d-9553-6d29138f735b",
> "level": 8
> }
> ]
> }
> ]
> }
> }
> 
> inbouds
> {
> "port": 23456,
> "protocol": "vless",
> "settings": {
> "clients":
> [
> {
> "encryption":"none",
> "id":"30f1523a-27f2-4c2d-9553-6d29138f735b"
> }]
> }
> }

**Comment by rprx** [comment]
客户端 Outbound：

```javascript
{
  "protocol": "vless",
  "settings": {
    "vnext": [
      {
        "address": "address.com",
        "port": 443,
        "users": [
          {
            "id": "27848739-7e62-4138-9fd3-098a63964b6b",
            "encryption": "none",
            "level": 0
          }
        ]
      }
    ]
  },
  ...
}
```

服务端 Inbound：

```javascript
{
  "port": 10000,
  "protocol": "vless",
  "settings": {
    "clients": [
      {
        "id": "27848739-7e62-4138-9fd3-098a63964b6b",
        "level": 0,
        "email": "vless@v2fly.org"
      }
    ],
    "decryption": "none"
  },
  ...
}
```

**Comment by RPRX** [comment]
客户端 Outbound：

```javascript
{
  "protocol": "vless",
  "settings": {
    "vnext": [
      {
        "address": "example.com",
        "port": 443,
        "users": [
          {
            "id": "27848739-7e62-4138-9fd3-098a63964b6b",
            "encryption": "none",
            "level": 0
          }
        ]
      }
    ]
  },
  ...
}
```

服务端 Inbound：

```javascript
{
  "port": 10000,
  "protocol": "vless",
  "settings": {
    "clients": [
      {
        "id": "27848739-7e62-4138-9fd3-098a63964b6b",
        "level": 0,
        "email": "vless@v2fly.org"
      }
    ],
    "decryption": "none"
  },
  ...
}
```

encryption 和 decryption 的位置不同，是因为若套一层约定加密，服务端需要先解密才能知道是哪个用户

**Comment by changyp6** [comment]
@2dust 可不可以编译一个V2rayCore是4.26.0，并且打了VLess Patch的版本？

**Comment by johnwigley** [comment]
Please could you upload a new current version of V2RayNG with the VLess patch please?

**Comment by ochamunaJ** [comment]
Unsubscribe me please from these notifications

**Comment by rprx** [comment]
@changyp6 @johnwigley 

不必着急，VLESS PREVIEW 将很快并入 v2ray-core

**Comment by RPRX** [comment]
@changyp6 @johnwigley 

不必着急，VLESS PREVIEW 将很快并入 v2ray-core

其实 CLEAN 2 与现在的版本还是兼容的，且它基于 v2ray-core v4.25.1+，但和 v4.26.0 实际上没有区别，因为从那个时间点到 v4.26.0，实际运行的代码没有任何改动

**Comment by johnwigley** [comment]
@rprx Thank you, look forward to seeing it integrated into v2ray-core soon

**Comment by ochamunaJ** [comment]
Thanks please. Just help me

**Comment by twzchi** [comment]
三星安卓10系统 用了上面编译的安卓客户端
 无法正常连接，日志最后显示 
 logcat 最后一直显示:Using Prepared: xx(IP地址)
                                  Using Prepared: xx
同样的配置v2ray 4.25.1的版本 ,不是最新的v4.26.0 
在电脑上的正常使用, 安卓无法连接
