### ISSUE TITLE
v2ray-core v4.25.1: Improve ARM platform stability.

### ISSUE THREAD

**Issue by RPRX** [2dust/v2rayNG#482]
https://github.com/v2fly/v2ray-core/releases/tag/v4.25.1

以及考虑一下 #455

**Comment by Warborn123** [comment]
而且能加一个选项 让我们以后手动更新core吗，就像V2rayN 那样。谢谢

**Comment by yuhan6665** [comment]
@jixiangyuan This is almost impossible (especially on newer Android) because:
1. We need to compile v2ray-core into .so library
2. Google has enforced that .so library must be baked in apk at compile time (to prevent code injection in general)

**Comment by Warborn123** [comment]
> @jixiangyuan This is almost impossible (especially on newer Android) because:
> 
> 1. We need to compile v2ray-core into .so library
> 2. Google has enforced that .so library must be baked in apk at compile time (to prevent code injection in general)

That make sense. Thank you.

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.2.12
