### ISSUE TITLE
[feature]使用标准DNS服务器时可以指定端口

### ISSUE THREAD

**Issue by MonNomSontPasUtile** [2dust/v2rayNG#485]
### 预期行为
允许指定特定的DNS端口，来允许将DNS请求发送到指定服务器的指定端口上（建议配置里采用格式为 127.0.0.1:11053 ，在使用时转换为合理配置）
可以与本地完整功能的DNS客户端（例如DoT/DoH客户端Nebulo一起使用） [Enable users to just start a local DNS server](https://git.frostnerd.com/PublicAndroidApps/smokescreen/-/issues/227)

![IMG_20200629_063329_552](https://user-images.githubusercontent.com/15964383/85959988-7bd44100-b9d2-11ea-8b66-2df30a8ad0a0.jpg)
![IMG_20200629_063654](https://user-images.githubusercontent.com/15964383/85960044-f69d5c00-b9d2-11ea-948b-7a1b2c4ae2a1.jpg)

### 实际行为
DNS请求通过系统默认/服务器默认DNS发送

### 复现方法
1. 启动Nebulo，打开Non-VPN mode
2. 启动V2Ray，指定DNS服务器为本地服务器
3. 重启V2Ray连接

### 日志信息
<details>
无计算机，无法调用adb日志
</details>

### 环境信息
Android 8.0

### 额外信息（可选）
Nebulo version 59 beta build 87b4c56

**Comment by yuhan6665** [comment]
Please try custom config and manually change DNS with your port. You can find the config format:
https://www.v2fly.org/chapter_02/04_dns.html

**Comment by MonNomSontPasUtile** [comment]
> Please try custom config and manually change DNS with your port. You can find the config format:
> https://www.v2fly.org/chapter_02/04_dns.html

The problem is if I directly write configuration files to use with V2RayNG, will I have to write 23 files or contain 23 profiles in one? It's a lot of work rather than providing a single option to edit.

It's not about capability, it's about complexity. I wrote configs, but they are hard to distribute.

**Comment by yuhan6665** [comment]
Ok, I just thought of another way you can try. I don't know what will happen though:
You can change Nebulo port to be 10853 and start it FIRST and then turn on v2rayNG. Internally the data flow is "system dns request" ->Tun2Socks -> 127.0.0.1:10853 -> V2 dns inbound -> V2 dns module..
If Nebulo can listen port 10853 and NG won't complain then that might work.

**Comment by MonNomSontPasUtile** [comment]
Failed

![IMG_20200701_202025](https://user-images.githubusercontent.com/15964383/86243110-5add3d00-bbd8-11ea-891d-5cf856c845be.jpg)

**Comment by yuhan6665** [comment]
Looks like you can only use custom config for now :(

**Comment by MonNomSontPasUtile** [comment]
> Looks like you can only use custom config for now :(

Tested for several months. When v2rayNG uses custom configs, DNS requests just get leaked to remote. After the first five requests, all others gets transmitted into default server-side DNS.
The benefit with a custom DoH client however, is that it makes sure the DNS results do not get polluted halfway. **And the most beneficial use of this is with Nebulo (F-Droid), which already has a DNS rule set to block ads and tracking domains. You can do nearly effortless ad blocking even without ```inboundSniffing``` and ```destinationOverride``` enabled.**
Nebulo does way better than the built-in V2Ray DNS module. Please re-consider adding the option to let us customize the port of remote DNS, because Android won't allow any service to listen to port such as 53 (all ports below 1024 I guess?).

**Comment by rurirei** [comment]
what you needed is not `Remote DNS` (this worked for standard VPN service), but custom dns service. do it with custom config and doing yourself.

**Comment by rurirei** [comment]
so you ask for a wrong question. please do not spam as 3 issues..

**Comment by MonNomSontPasUtile** [comment]
> so you ask for a wrong question. please do not spam as 3 issues..

Well then, could you please tell me by modifying remote DNS, which part of the config file is modified?

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/issues/653

**Comment by rurirei** [comment]
>> could you please tell me by modifying remote DNS

input 8.8.8.8 and leave it.


>> which part of the config file is modified?

not related to your v2ray conf. remote dns used for your Android system.

**Comment by MonNomSontPasUtile** [comment]
then, does there exist any possibility that there will be an option which can allow users to quickly modify custom DNS settings?

**Comment by rurirei** [comment]
> then, does there exist any possibility that there will be an option which can allow users to quickly modify custom DNS settings?

custom config needed. try it yourself.

**Comment by rurirei** [comment]
for details see https://github.com/2dust/v2rayNG/issues/653
