### ISSUE TITLE
自定义规则问题

### ISSUE THREAD

**Issue by ouyangyilang** [2dust/v2rayNG#487]
![Screenshot_2020-06-29-18-59-32-385_com v2ray ang](https://user-images.githubusercontent.com/48618950/85996750-36982980-ba3b-11ea-8f89-024a50cbd0c8.jpg)
设置自定义规则后不能生效，导出完整配置后发现规则前面多了"/r",后来发现是复制了软件生成的默认规则做模板，软件生成的规则带有"/r"换行符，在编辑的界面看不到，退格从新换行能解决

**Comment by yuhan6665** [comment]
fixed in https://github.com/2dust/v2rayNG/pull/866
