### ISSUE TITLE
google play上的版本安装不了

### ISSUE THREAD

**Issue by 2huYa0** [2dust/v2rayNG#49]
我在这下载的app-universal-release.apk可以安装，安装包是20多M；而google play上的安装包只有10多M，下载了也安装不了，是不是传错包了还是怎么样？

**Comment by pemm** [comment]
app-universal-release.apk 从哪下载

**Comment by 2huYa0** [comment]
release里面有啊

**Comment by dna1982** [comment]
play上的安装包API分开了，所以小。
另外这里release的APK和Play上的APK，VersionCode不同，所以不能互相覆盖。
