### ISSUE TITLE
在智能电视上使用遥控器无法选中启动按钮

### ISSUE THREAD

**Issue by brick2008** [2dust/v2rayNG#490]
夏普智能电视，使用遥控器上的上下左右ok键可以选择节点，设置菜单等，唯独右下角的启动按钮无法被选中，导致app无法使用，每个节点右侧的编辑和删除按钮是可以选中的，建议每个节点后面都添加一个互斥的启动按钮。

**Comment by 2dust** [comment]
点菜单中的"服务重启"

**Comment by songyuyx** [comment]
> 点菜单中的"服务重启"

可以用，谢谢大佬
