### ISSUE TITLE
为什么这个应用要获取我的内存卡数据，访问相册，打开相机权限，而且都是不用获取用户同意

### ISSUE THREAD

**Issue by dm66** [2dust/v2rayNG#493]

**Comment by dm66** [comment]
![Screenshot_20200704_111856_com android packageinstaller](https://user-images.githubusercontent.com/24384381/86504191-3e175400-bde8-11ea-9bb7-329bd6b6bfb2.jpg)

**Comment by yuhan6665** [comment]
v2rayNG uses storage permission when you want to import config json files. It uses camera if you want to scan a "vmess://" QR code. If you don't need these features, you can safely turn off these permissions.

**Comment by changyp6** [comment]
读config，需要用到storage permission
扫QRCode，需要用到Camera
