### ISSUE TITLE
[Feature Request] 建议App中包含h2y.dat文件

### ISSUE THREAD

**Issue by changyp6** [2dust/v2rayNG#494]
建议在App中包含 h2y.dat文件，这样以便自定义config中引用"ext:h2y.dat:gfw"

h2y.dat 文件可以从 https://github.com/ToutyRater/V2Ray-SiteDAT/raw/master/geofiles/h2y.dat 下载

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/pull/662
