### ISSUE TITLE
华为Mate10翻墙失败，连接成功访问不了谷歌

### ISSUE THREAD

**Issue by WangYuana** [2dust/v2rayNG#496]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
打开按钮连接成功访问谷歌应该能进去

### 实际行为
打开按钮连接成功访问谷歌失败不能访问。

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by Hodge-Zhang** [comment]
目前我的mate20可以正常使用v2rayng，不过【分应用代理】设置很迷，有时这里的设置会失效或有其他问题导致部分网络不能访问。
不过题主的问题我觉得很大可能是服务器端的问题，题主应该提供更详细的信息。

**Comment by WangYuana** [comment]
> 目前我的mate20可以正常使用v2rayng，不过【分应用代理】设置很迷，有时这里的设置会失效或有其他问题导致部分网络不能访问。
> 不过题主的问题我觉得很大可能是服务器端的问题，题主应该提供更详细的信息。

节点没问题，我用clash就可以访问，用v2ray就打不开谷歌了。

**Comment by eveloki** [comment]
> 目前我的mate20可以正常使用v2rayng，不过【分应用代理】设置很迷，有时这里的设置会失效或有其他问题导致部分网络不能访问。
> 不过题主的问题我觉得很大可能是服务器端的问题，题主应该提供更详细的信息。

#503  是否有帮助？

**Comment by Jc826** [comment]
华为 呵呵

**Comment by Takea3** [comment]
解决办法很简单，扔掉你手中的华为。
