### ISSUE TITLE
源码不开源了吗

### ISSUE THREAD

**Issue by ZeroTale** [2dust/v2rayNG#498]
releases中只有apk是新的，源码都是1.0.2版本的

**Comment by WangYuana** [comment]
> releases中只有apk是新的，源码都是1.0.2版本的

也是我想问的

**Comment by changyp6** [comment]
我也想问这个问题。同步下来的源码，老得都不能跑。

**Comment by JamesWynnReal** [comment]
也是我想问的

**Comment by pongfcnkl** [comment]
https://github.com/2dust/v2rayNG/issues/172

**Comment by ZeroTale** [comment]
> [＃172](https://github.com/2dust/v2rayNG/issues/172)

谢谢解答
