### ISSUE TITLE
更新core v4.26.0

### ISSUE THREAD

**Issue by heheheaa** [2dust/v2rayNG#499]
https://github.com/v2fly/v2ray-core/releases/tag/v4.26.0
1.2.12不更新用不了自定义配置VMessAEAD

**Comment by 1265578519** [comment]
自定义配置怎么用啊，能不能教教我

**Comment by heheheaa** [comment]
> 自定义配置怎么用啊，能不能教教我

你先正常在gui里添加配置可以连通，然后分享选导出完整配置到剪贴板，然后在选添加自定义配置>从剪贴板导入自定义配置就可以转换成自定义配置自己改了

**Comment by 1265578519** [comment]
@heheheaa 好的感谢大佬！懂了懂了
