### ISSUE TITLE
能增加对ssr的支持吗?

### ISSUE THREAD

**Issue by laoasl** [2dust/v2rayNG#5]
好多机场用的还是ssr , 可play商店一个支持ssr的都没有.

**Comment by lgy330335** [comment]
同意

**Comment by ghost** [comment]
铜球，强烈支持。

**Comment by Hana-ame** [comment]
安卓ssr可以到这里下载
~~https://github.com/shadowsocksr-backup/shadowsocksr-android/releases~~

https://github.com/shadowsocksrr/shadowsocksr-android/releases

**Comment by ghost** [comment]
> 安卓ssr可以到这里下载
> https://github.com/shadowsocksr-backup/shadowsocksr-android/releases

这个2017年的了……

**Comment by Hana-ame** [comment]
> 
> 
> > 安卓ssr可以到这里下载
> > https://github.com/shadowsocksr-backup/shadowsocksr-android/releases
> 
> 这个2017年的了……

SSR本身作者停更，本身也是闭源，理应没有更新的版本。

**Comment by ghost** [comment]
> > > 安卓ssr可以到这里下载
> > > https://github.com/shadowsocksr-backup/shadowsocksr-android/releases
> > 
> > 
> > 这个2017年的了……
> 
> SSR本身作者停更，本身也是闭源，理应没有更新的版本。

闭源？老黄历了，因为闭源被怼，早开源了…
breakwa11 被人肉停更，Akkariiin宣称接手，更名为SSRR，然而半死不活，几近无更……
https://github.com/shadowsocksrr

**Comment by Hana-ame** [comment]
> 
> 
> > > > 安卓ssr可以到这里下载
> > > > https://github.com/shadowsocksr-backup/shadowsocksr-android/releases
> > > 
> > > 
> > > 这个2017年的了……
> > 
> > 
> > SSR本身作者停更，本身也是闭源，理应没有更新的版本。
> 
> 闭源？老黄历了，因为闭源被怼，早开源了…
> breakwa11 被人肉停更，Akkariiin宣称接手，更名为SSRR，然而半死不活，几近无更……
> https://github.com/shadowsocksrr

当时也没怎么关注这些，感谢指摘。总之就期待一下有整合后的客户端吧。
上面的链接也一道修改了。

**Comment by 2dust** [comment]
Not accepted r
