### ISSUE TITLE
 Suggestions for enhancement

### ISSUE THREAD

**Issue by RedDragonFalcon1** [2dust/v2rayNG#5]
环境：Android 8.0
设备：Nexus 6P

改进功能：
1，改善耗电，现有版本的耗电一般会占到全天（12小时）的15%左右。
2，适配Android 8.0起引入的Adaptive Icons

增加功能：
1，增加开机自启动功能选项
2，增加清理DNS缓存功能选项
3，增加PAC导入和应用
4，增加V2Ray核心程序自动更新功能
5，增加完整的KCP、TCP设置功能

错误修正：
1，设置菜单内Enable ux应为Enable Mux

**Comment by gloomy-ghost** [comment]
> 现有版本的耗电一般会占到全天（12小时）的15%左右
Android 的耗电统计会把所有网络请求都算到 VPN 头上，最好还是做个对比实验看看实际耗电

> 增加V2Ray核心程序自动更新功能
自更新会违反大多数应用商店的分发协议

**Comment by 2dust** [comment]
感谢建议
1，增加开机自启动功能选项
不确定是否会增加
2，增加清理DNS缓存功能选项
这个可以尝试
3，增加PAC导入和应用
v2ray自动路由，可用尝试
4，增加V2Ray核心程序自动更新功能
这个肯定是不能实现的
5，增加完整的KCP、TCP设置功能
请用导入配置文件功能
