### ISSUE TITLE
android8.0 没有通知

### ISSUE THREAD

**Issue by coocat** [2dust/v2rayNG#50]
我只有一台小米6设备,开启后没有任务栏通知,运行或者没有运行查看麻烦,望添加,谢谢

**Comment by OROKIN** [comment]
我这边8.0是有通知栏的，请检查软件的通知栏权限是否受限

**Comment by maryjeck** [comment]
小米6确实没有

**Comment by sisx** [comment]
Mi6同样没有，我还以为是专门这么设置的。

**Comment by chong198512** [comment]
我用的华为手机，通知栏有没流量显示兰栏

**Comment by sunjie21** [comment]
小米 6 没有通知，也没有 VPN 开启的 ICON。在 Sony 上有。

**Comment by haigeoo** [comment]
同样没有通知栏，这个bug很伤
