### ISSUE TITLE
when compiling it gives me version 1.0.2

### ISSUE THREAD

**Issue by demianrey** [2dust/v2rayNG#501]
well that, I'm with android studio and in any version of the source code brings version 1.0.2, you can upload the latest source code please

**Comment by superhero75** [comment]
I also notice the same issue. I checked that any source code version has the old promotiourl.
const val promotionUrl = "https://1.2345345.xyz/ads.html"
With the old v2rayng version, I also tried to load the latest libv2ray.aar i.e. v2raycore 4.26.0,  the setting menu would hang the app. They are not compatible.

**Comment by demianrey** [comment]
> I also notice the same issue. I checked that any source code version has the old promotiourl.
> const val promotionUrl = "https://1.2345345.xyz/ads.html"
> With the old v2rayng version, I also tried to load the latest libv2ray.aar i.e. v2raycore 4.26.0, the setting menu would hang the app. They are not compatible.

apparently the developer is no longer interested in leaving the source code, it may be due to the plagiarism in the playstore, but in my case it is for personal use and by my people, anyway maybe one day he decides to give us the code ...  by the way you can leave me your telegram I would like to see a problem I have, if you can help me
