### ISSUE TITLE
android 使用 socks 连接 (有用户验证)无法连接

### ISSUE THREAD

**Issue by xxjjnuo** [2dust/v2rayNG#502]
### 预期行为
使用v2rayNG 1.2.12 进行 socks 连接 上网

### 实际行为
可以连接 但是无法上网, 实测 window 可以使用这个socks 节点 上网

### 环境信息
手机型号:荣耀 10 

### 备注
后来更换为 bifrostV 进行 连接这个socks节点 是可以在手机上面使用 并上网

**Comment by xxjjnuo** [comment]
但是bifrostV 没有开源代码, bifrostV 导出 配置 到 v2rayNG 里面使用 也无法上网

**Comment by cym9921** [comment]
我也碰到了这个问题，vmess没有问题，但是socks代理无法上网。点击测试是能显示连接延迟的，但是无法上网。没有用户验证。同样的配置在电脑上是可以上网的，用wifi配置里的pac，或者局域网代理里的自动配置都可以上网，应该是软件的问题

**Comment by twzchi** [comment]
socks配置 电脑端正常吗？
Sock端口要和你的NG(默认10808)端口一致
你看看

**Comment by yxzwym** [comment]
socks代理在电脑端是正常的。在手机上不行。

**Comment by yxzwym** [comment]
我刚刚又重新搭了个试了下，电脑可以，手机不行。

**Comment by twzchi** [comment]
> 我刚刚又重新搭了个试了下，电脑可以，手机不行。
> 
> socks://OkAzMzIxMDAueHl6OjIzMDY1#%E6%AF%9B%E5%AD%90%E4%BC%AF%E5%8A%9Bsocks

你手机上的NG的 logcat 看看  我是用sock +TLS 正常使用，电脑和安卓

**Comment by yxzwym** [comment]
--------- beginning of main
07-31 12:25:27.980 I/GoLog   ( 5671): udp:127.0.0.1:37489 accepted udp:114.114.114.114:53 [proxy] 
07-31 12:25:28.039 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:28.091 I/GoLog   ( 5671): udp:127.0.0.1:45063 accepted udp:114.114.114.114:53 [proxy] 
07-31 12:25:28.130 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:28.330 I/GoLog   ( 5671): udp:127.0.0.1:44954 accepted udp:114.114.114.114:53 [proxy] 
07-31 12:25:28.373 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:28.419 I/GoLog   ( 5671): [Warning] [857912512] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:28.513 I/GoLog   ( 5671): [Warning] [2275828309] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:28.563 I/GoLog   ( 5671): udp:127.0.0.1:46835 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:28.563 I/GoLog   ( 5671): udp:127.0.0.1:37669 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:28.617 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:28.622 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:28.722 I/GoLog   ( 5671): [Warning] [2615218727] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:28.985 I/GoLog   ( 5671): [Warning] [1144406428] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:28.992 I/GoLog   ( 5671): [Warning] [2268785149] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:29.698 I/GoLog   ( 5671): udp:127.0.0.1:43589 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:29.759 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:30.180 I/GoLog   ( 5671): [Warning] [3081810983] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:31.343 I/GoLog   ( 5671): udp:127.0.0.1:47469 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:31.405 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:31.814 I/GoLog   ( 5671): [Warning] [522015682] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:32.073 I/GoLog   ( 5671): udp:127.0.0.1:41862 accepted udp:114.114.114.114:53 [proxy] 
07-31 12:25:32.165 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:32.542 I/GoLog   ( 5671): [Warning] [1960812011] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:32.988 I/GoLog   ( 5671): udp:127.0.0.1:41590 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:33.041 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:33.093 I/GoLog   ( 5671): udp:127.0.0.1:39486 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:33.143 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:33.337 I/GoLog   ( 5671): udp:127.0.0.1:49577 accepted udp:1.1.1.1:53 [proxy] 
07-31 12:25:33.379 I/GoLog   ( 5671): Using Prepared: 125.46.40.189
07-31 12:25:33.396 I/GoLog   ( 5671): [Warning] [117907221] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:33.524 I/GoLog   ( 5671): [Warning] [579779520] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: server rejects request: 7
07-31 12:25:33.568 I/GoLog   ( 5671): udp:127.0.0.1:39473 accepted udp:114.114.114.11

**Comment by twzchi** [comment]
你把远程DNS取消 本地DNS取消 使用sock模式，我实验了 无法使用本地DNS ，会无法连接网络
不知道是什么原因。但是VMESS 模式下 ，是可以使用本地DNS实现分流的，sock模式没办法，一直是全局模式

**Comment by twzchi** [comment]
sock唯一的好处是降低了延迟，如果线路不好，延迟降低了，貌似网速没多打改善
最近在使用VLESS 新协议，速度，稳定性，貌似在垃圾服务器上还可以

**Comment by xxjjnuo** [comment]
VMESS 咋个分流,我都还没搞懂

**Comment by phoon** [comment]
令我不解的是，通过抓包分析，为何v2rayNG在连接SOCKS时会将验证方法选择消息同时与用户名密码验证信息合并发送？
比如正常应该为： 
```
client -> [ 0x05 0x01 0x02 ]
server ->[ 0x05 0x02 ]
client -> [ 0x01 0x03 0x66 0x6f 0x6f 0x03 0x62 0x61 0x72 ] # 发送用户名/密码验证消息 （foo:bar）
server -> [ 0x01 0x00 ] # 认证成功
```
实际抓包为：
```
client -> [ 0x05 0x01 0x02  0x01 0x03 0x66 0x6f 0x6f 0x03 0x62 0x61 0x72 ]
server -> [ 0x05 0x02 ]
server -> [ 0x01 0x00 ]
```
