### ISSUE TITLE
华为 /荣耀最新 10.1 系统 分应用代理 youtube 失效

### ISSUE THREAD

**Issue by eveloki** [2dust/v2rayNG#503]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
使用v2rayNG 1.2.12的分应用代理功能 勾选了youtube app 并且开启了链接
youtube app能够正常打开使用

### 实际行为

youtube app一直转圈圈 完全无法使用 使用浏览器（edge chrome 均能正常访问 youtube 和谷歌 的web页面 ）

### 日志信息
<details>
--------- beginning of main
07-12 01:26:58.525 I/GoLog   ( 8143): udp:127.0.0.1:59857 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:26:58.526 I/GoLog   ( 8143): udp:127.0.0.1:44868 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:26:58.526 I/GoLog   ( 8143): udp:127.0.0.1:35301 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:26:58.527 I/GoLog   ( 8143): udp:127.0.0.1:38344 accepted udp:172.217.26.138:443 [proxy] 
07-12 01:26:58.555 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.562 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.563 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.564 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.638 I/GoLog   ( 8143): tcp:127.0.0.1:50656 accepted tcp:140.82.113.3:443 [proxy] 
07-12 01:26:58.638 I/GoLog   ( 8143): tcp:127.0.0.1:50658 accepted tcp:140.82.113.3:443 [proxy] 
07-12 01:26:58.659 I/GoLog   ( 8143): tcp:127.0.0.1:50666 accepted tcp:185.199.108.154:443 [proxy] 
07-12 01:26:58.674 I/GoLog   ( 8143): udp:127.0.0.1:46122 accepted udp:172.217.161.170:443 [proxy] 
07-12 01:26:58.675 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.678 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.696 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:58.709 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:59.531 I/GoLog   ( 8143): udp:127.0.0.1:35111 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:26:59.535 I/GoLog   ( 8143): udp:127.0.0.1:45633 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:26:59.535 I/GoLog   ( 8143): udp:127.0.0.1:59079 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:26:59.568 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:59.569 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:26:59.572 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:09.933 I/GoLog   ( 8143): udp:127.0.0.1:39330 accepted udp:172.217.161.170:443 [proxy] 
07-12 01:27:09.967 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:13.533 I/GoLog   ( 8143): udp:127.0.0.1:38344 accepted udp:172.217.26.138:443 [proxy] 
07-12 01:27:13.566 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:27.832 I/GoLog   ( 8143): udp:127.0.0.1:46122 accepted udp:172.217.161.170:443 [proxy] 
07-12 01:27:27.869 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:42.912 I/GoLog   ( 8143): udp:127.0.0.1:38344 accepted udp:172.217.26.138:443 [proxy] 
07-12 01:27:42.947 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:47.192 I/GoLog   ( 8143): udp:127.0.0.1:39817 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:27:47.229 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:47.336 I/GoLog   ( 8143): tcp:127.0.0.1:50712 accepted tcp:172.217.26.138:443 [proxy] 
07-12 01:27:47.368 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:48.928 I/GoLog   ( 8143): udp:127.0.0.1:33782 accepted udp:1.1.1.1:53 [proxy] 
07-12 01:27:48.975 I/GoLog   ( 8143): Using Prepared: 42.157.196.137
07-12 01:27:49.070 I/GoLog   ( 8143): tcp:127.0.0.1:50720 accepted tcp:140.82.113.6:443 [proxy] 
07-12 01:27:49.104 I/GoLog   ( 8143): Using Prepared: 42.157.196.137

</details>

### 环境信息
荣耀v20 Magic 3.1.0 对应 emui 10.1 
安卓10.1.0.160C00
（之前可以 最新系统推送了个补丁包 打了补丁之后不行了 ）
youtube已经更新到最新

建议增加至 #203

**Comment by luckiestone** [comment]
把`设置`也增加到分应用代理中再尝试一下。

**Comment by pjeunng** [comment]
> 把`设置`也增加到分应用代理中再尝试一下。
卧槽，解决了，真tm神奇！谢谢大神 你是咋发现的

**Comment by eveloki** [comment]
> 把`设置`也增加到分应用代理中再尝试一下。

问题解决了（还有这种骚操作？） 这个能不能修复呢 如果程序不修复我觉得应该分应用代理那边做个提示比较好吧

**Comment by luckiestone** [comment]
> > 把`设置`也增加到分应用代理中再尝试一下。
> > 卧槽，解决了，真tm神奇！谢谢大神 你是咋发现的

因为我也被困扰了很久，以为是软件的原因，后来多番尝试和搜索发现这个是因为新系统中谷歌系软件会通过`设置`读取和登录当前的Google账号，设置中就有相关的Google账号设置。

**Comment by luckiestone** [comment]
> > 把`设置`也增加到分应用代理中再尝试一下。
> 
> 问题解决了（还有这种骚操作？） 这个能不能修复呢 如果程序不修复我觉得应该分应用代理那边做个提示比较好吧

这个不是bug，所以不存在修复一说，是因为新系统需要通过`设置`读取登录当前账号，安卓10的新变化。。。

**Comment by yuhan6665** [comment]
In latest version 1.3.0, you can see a separate "Android System" in the app list. Selecting it will behave the same as you select "设置"  (com.android.settings). This is because Android per-app vpn is using uid internally while settings and system package share the same uid.

**Comment by kowenzhang** [comment]
问题解决，太棒了

**Comment by yethoo** [comment]
牛逼啊，刚换的荣耀魔法6，一直无法打开油管。开全局就行，我感觉是哪里没勾选到，结果是设置。之前用小米的只勾选谷歌的即可。话说荣耀真JB难用，不如小米好用。

**Comment by nkbai** [comment]
> 把`设置`也增加到分应用代理中再尝试一下。

没看明白，到底怎么设置？是代理里面也要配置分应用么？
