### ISSUE TITLE
能否提供批量删除重复节点、无效节点的功能？

### ISSUE THREAD

**Issue by himandy** [2dust/v2rayNG#505]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
批量删除重复节点、无效节点(真链接测试连不上的节点)

### 实际行为
每次更新订阅，似乎没有自动删除旧的节点，导致有不少重复。最近手动一个一个点击删除，删除了300个无效的。剩下估计100个，有很多是重复的。

v2rayNG复制粘贴批量导入节点真的很方便。希望能增加批量删除的功能，谢谢

**Comment by bigrain2007** [comment]
确实，加上会方便不少。
