### ISSUE TITLE
启动代理之后无法使用

### ISSUE THREAD

**Issue by JackyNiu** [2dust/v2rayNG#507]
连接成功后，无法代理，测试连接时出现io:read/write on closed pipe;
连接方式vmess，websocket
目前电脑使用v2rayN和iphone使用showrrocket连接没有问题；
安卓下载的是armv8版本

**Comment by JackyNiu** [comment]
手机为pixel 系统为安卓8.1,有使用xposed。

**Comment by viablecell** [comment]
@JackyNiu 你好，问题解决了吗？遇到同样的问题
