### ISSUE TITLE
使用私人DNS后，地址如果是域名会无法解析

### ISSUE THREAD

**Issue by Loukky** [2dust/v2rayNG#510]
V2rayNG目前版本，1.2.13
android 10.索尼xz3
私人DNS填写为 dns.google
如果连接地址是ip的话表现正常或者不使用私人DNS的话也正常。
部分日志
--------- beginning of main
07-19 01:51:01.696 I/GoLog   ( 5162): Preparing Domain: ip.bldon.club:2053
07-19 01:51:01.696 I/GoLog   ( 5162): loading v2ray config
07-19 01:51:02.068 I/GoLog   ( 5162): new v2ray core
07-19 01:51:02.072 I/GoLog   ( 5162): start v2ray core
07-19 01:51:02.073 I/GoLog   ( 5162): [Warning] v2ray.com/core: V2Ray 4.26.0 started
07-19 01:51:02.108 D/com.v2ray.ang( 5162): [/data/app/com.v2ray.ang-N5dnL34Jr-4eZBBUBaP08A==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice, --netif-ip6addr, da26:2626::2]
07-19 01:51:02.110 D/com.v2ray.ang( 5162): Process[pid=7548, hasExited=false]
07-19 01:51:02.110 D/com.v2ray.ang( 5162): /data/user/0/com.v2ray.ang/files/sock_path
07-19 01:51:02.132 I/tun2socks( 7548): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
07-19 01:51:02.160 D/com.v2ray.ang( 5162): sendFd tries: 0
07-19 01:51:02.161 I/tun2socks( 7548): NOTICE(tun2socks): entering event loop
07-19 01:51:02.162 I/GoLog   ( 5162): Dial pending prepare  ... ip.bldon.club:2053
07-19 01:51:02.162 I/GoLog   ( 5162): udp:127.0.0.1:41322 accepted udp:8.8.8.8:53 [proxy] 
07-19 01:51:02.186 I/GoLog   ( 5162): Dial pending prepare  ... ip.bldon.club:2053
07-19 01:51:02.186 I/GoLog   ( 5162): tcp:127.0.0.1:38134 accepted tcp:149.154.171.5:5222 [proxy] 
07-19 01:51:02.685 I/GoLog   ( 5162): Dial pending prepare  ... ip.bldon.club:2053
07-19 01:51:02.686 I/GoLog   ( 5162): tcp:127.0.0.1:38138 accepted tcp:[2001:b28:f23f:f005::a]:5222 [proxy]

**Comment by yuhan6665** [comment]
Don't include port in the address.

**Comment by Loukky** [comment]
> Don't include port in the address.

地址没有包含端口，端口号是填写在端口的选项里面

**Comment by yuhan6665** [comment]
Ok, maybe your DNS doesn't resolve your domain "ip.bldon.club". Please check log for details. You can upload more logs too.

**Comment by Loukky** [comment]
不知道怎么又可以正常解析出来了。

**Comment by confession0816** [comment]
请问怎么在v2rayNG中使用私人dns
