### ISSUE TITLE
DNS not forwarded to server

### ISSUE THREAD

**Issue by matroot** [2dust/v2rayNG#514]
Hi,
I'm using the latest version from Play Store and dns is not forwarded to server. I tried socks and shadowsocks mode and the problem occurs. The system goes broken and don't lookup addresses.

Another issue, if i setup DNS-Over-TLS on android is also not forwarded and error message is shown "Couldn't Forwarded". 

My phone runs Android 10.

**Comment by rurirei** [comment]
impossible. https://github.com/2dust/v2rayNG/issues/332#issuecomment-703075531
