### ISSUE TITLE
#511 更新后，下拉菜单速度显示0（自定义配置文件）

### ISSUE THREAD

**Issue by appstestacc** [2dust/v2rayNG#519]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
上下行速度分proxy、direct，分别计速

### 实际行为
描述实际发生了什么
上下行速度显示永远为0

用的是1.2.15 #511 更新之前的自定义配置。
（问题明显，我就不按模板写了）

**Comment by yuhan6665** [comment]
Thanks for reporting. Please put "**proxy**" as tag for your server outbound and "**direct**" as tag for your freedom outbound.

**Comment by appstestacc** [comment]
谢谢！但好像不仅仅是这两个tag的问题（之前版本已经用了这两个tag）

**Comment by appstestacc** [comment]
问题解决了，需要加
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true

先前版本好像不加这个也可以计速

**Comment by yuhan6665** [comment]
@appstestacc In previous version it needed "statsInboundUplink" and "statsInboundDownlink". I totally forgot this setting :)
Thanks for your reply again

**Comment by changyp6** [comment]
如果用了balancer的话，还是不会显示速度的。因为balancer里面有多个不同的outbound，不可能每个outbound的tag都是proxy
所以，如果用了balancer，proxy的速度还是显示为0，或者是，只会显示tag为proxy的outbound的速度。

**Comment by yuhan6665** [comment]
@changyp6 thanks for reporting this issue. Yes, this is currently a limitation, speed display only works for one outbound with tag "proxy" and another with "direct"
Show speed for all outbounds is possible but would take some time to fix. I will plan it for a bit later

**Comment by yuhan6665** [comment]
Fix balancer speed display in #574
