### ISSUE TITLE
V2rayNG使用geo相关规则会导致play市场无法更新和下载

### ISSUE THREAD

**Issue by LittleGrocery** [2dust/v2rayNG#520]
> 解决了
> 
> 额外ID改成0就可以了

我改了也没变化，只好弃坑

_Originally posted by @pscj in https://github.com/2dust/v2rayNG/issues/477#issuecomment-657186854_

**Comment by LittleGrocery** [comment]
V2rayNG使用路由规则为全局 自定义规则直连只写:geosite:cn,geoip:cn 的情况，play市场无法更新下载，后查阅NG 17年有人提到的issue 把domain:google.cn,domain:googleapis.cn加入直连列表，故障依旧，后来把上述两条规则加入代理列表，play市场能下载更新了，猜测是这俩域名部分子域名被block了导致的，故开个issue提醒下大家

**Comment by 94run** [comment]
好像还是不行。可以正常浏览谷歌，不能下载。

**Comment by LittleGrocery** [comment]
@94run  新改进:直连那里，直接写google就行，自定义规则支持关键字 
如果仍然不行，建议执行步骤一，再不行就执行步骤一和二
步骤一:清除play商店数据
步骤二:删除手机google账号重新登陆

**Comment by LiHang941** [comment]
确实是v2rayng的问题，我用隔壁的bifrostv就能下，我是ws+tls

**Comment by LittleGrocery** [comment]
> 确实是v2rayng的问题，我用隔壁的bifrostv就能下，我是ws+tls

你用我的方法试过不行了吗？bifrostv已经不更新了，以后v2像上次那样爆有什么漏洞它也没法补了，而且这软件设置有点不方便，远程dns要一个个服务器点配置

**Comment by LiHang941** [comment]
> > 确实是v2rayng的问题，我用隔壁的bifrostv就能下，我是ws+tls
> 
> 你用我的方法试过不行了吗？bifrostv已经不更新了，以后v2像上次那样爆有什么漏洞它也没法补了，而且这软件设置有点不方便，远程dns要一个个服务器点配置

确实不行，我试了你的方法，根本不走流量，换上bifrostv秒下

**Comment by LiHang941** [comment]
我现在是用google play下载的时候使用bifrostv，平常使用还是v2ray ng

**Comment by SekiBetu** [comment]
预置的规则已经能满足大多数情况了，没必要自己写geoip的规则

**Comment by akiirui** [comment]
Can you post your full configuration (Export full configuration), v2rayNG and Android version?
Of course, hide important information.

**Comment by LittleGrocery** [comment]
> Can you post your full configuration (Export full configuration), v2rayNG and Android version?
> Of course, hide important information.

I don't know how to export full configuration.

**Comment by akiirui** [comment]
> I don't know how to export full configuration.

Tap the share icon, Export full configuration to clipboard.
Hide your important information (eg. IP address, UUID) before reply.

And, tell me your Android and v2rayNG version.

**Comment by LittleGrocery** [comment]
> > I don't know how to export full configuration.
> 
> Tap the share icon, Export full configuration to clipboard.
> Hide your important information (eg. IP address, UUID) before reply.
> 
> And, tell me your Android and v2rayNG version.

{ 
"dns": { 
"hosts": { 
"domain:googleapis.cn": "googleapis.com" 
}, 
"servers": [ 
"https://cloudflare-dns.com/dns-query", 
{ 
"address": "119.29.29.29", 
"domains": [ 
"geosite:cn" 
], 
"expectIPs": [ 
"geoip:cn" 
], 
"port": 53 
} 
] 
}, 
"inbounds": [ 
{ 
"listen": "127.0.0.1", 
"port": 10808, 
"protocol": "socks", 
"settings": { 
"auth": "noauth", 
"udp": true, 
"userLevel": 8 
}, 
"sniffing": { 
"destOverride": [ 
"http", 
"tls" 
], 
"enabled": true 
}, 
"tag": "socks" 
}, 
{ 
"listen": "127.0.0.1", 
"port": 10809, 
"protocol": "http", 
"settings": { 
"userLevel": 8 
}, 
"tag": "http" 
}, 
{ 
"listen": "127.0.0.1", 
"port": 10853, 
"protocol": "dokodemo-door", 
"settings": { 
"address": "1.1.1.1", 
"network": "tcp,udp", 
"port": 53 
}, 
"tag": "dns-in" 
} 
], 
"log": { 
"loglevel": "warning" 
}, 
"outbounds": [ 
{ 
"mux": { 
"concurrency": -1, 
"enabled": false 
}, 
"tag": "proxy" 
}, 
{ 
"protocol": "freedom", 
"settings": {}, 
"tag": "direct" 
}, 
{ 
"protocol": "blackhole", 
"settings": { 
"response": { 
"type": "http" 
} 
}, 
"tag": "block" 
}, 
{ 
"protocol": "dns", 
"tag": "dns-out" 
} 
], 
"policy": { 
"levels": { 
"8": { 
"connIdle": 300, 
"downlinkOnly": 1, 
"handshake": 4, 
"uplinkOnly": 1 
} 
}, 
"system": { 
"statsOutboundUplink": true, 
"statsOutboundDownlink": true 
} 
}, 
"routing": { 
"domainStrategy": "IPIfNonMatch", 
"rules": [ 
{ 
"inboundTag": [ 
"dns-in" 
], 
"outboundTag": "dns-out", 
"type": "field" 
}, 
{ 
"ip": [ 
"119.29.29.29" 
], 
"outboundTag": "direct", 
"port": "53", 
"type": "field" 
}, 
{ 
"domain": [ 
"google" 
], 
"outboundTag": "proxy", 
"type": "field" 
}, 
{ 
"domain": [ 
"geosite:cn" 
], 
"outboundTag": "direct", 
"type": "field" 
}, 
{ 
"ip": [ 
"geoip:cn", 
"geoip:private" 
], 
"outboundTag": "direct", 
"type": "field" 
}, 
{ 
"domain": [ 
"000dn.com", 
"001union.com", 
"0086555.com", 
"00880808.com", 
"00oo00.com", 
"01.gxso.net", 
"010teacher.com", 
"010xk.com", 
"018520.com", 
"01daa.lubih.com", 
"01daa.lutci.com", 
"01daa.lutgh.com", 
"01daa.luvbr.com", 
"01daa.luytr.com", 
"022aifang.com", 
"023hysj.com", 
"025suyu.com", 
"0313413.com", 
"0451106.com", 
"0531kt.com", 
"0592weixin.com", 
"0594003.com", 
"06362.com", 
"0756sjlm.com.cn", 
"09_19.supfree.net", 
"0aqpqdju.me", 
"0x01e7.website", 
"0xxd.com", 
"1.1010pic.com", 
"1.201980.com", 
"1.21shebao.com", 
"1.51sxue.cn", 
"1.aili.com", 
"1.bashenghuo.com", 
"1.chcx.cn", 
"1.cjcp.cn", 
"1.codesdq.com", 
"1.feihua.com", 
"1.glook.cn", 
"1.hao123.com", 
"1.hnyouneng.com", 
"1.i1766.com", 
"1.iqeq.com.cn", 
"1.jeasyui.net", 
"1.letvlive.com", 
"1.mgff.com", 
"1.nanrenwo.net", 
"1.panduoduo.net", 
"1.rengshu.com", 
"1.soufy.cn", 
"1.tulaoshi.com", 
"1.tuxi.com.cn", 
"1.win7china.com", 
"1.win7sky.com", 
"1.wps.cn", 
"1.xiaopin5.com", 
"1.xiaozhizhijia.com", 
"1.xilu.com", 
"1.zw3e.com", 
"1000dy.com", 
"100fenlm.com", 
"1017.cn", 
"10up.com", 
"11.hydcd.com", 
"111111qb.com", 
"111cn.net", 
"1133.cc", 
"114la.com", 
"1178.shucong.com", 
"11g.yiqig.cn", 
"1224.dxsbb.com", 
"123.sogou.com", 
"12306media.com", 
"1234xm.com", 
"12365chia.com", 
"123hala.com", 
"123juzi.net", 
"13023.url.7wkw.com", 
"138138138.top", 
"142904.com", 
"144.dragonparking.com", 
"1495039.com", 
"163ren.com", 
"168.it168.com", 
"1680go.com", 
"168ad.cc", 
"170yy.com", 
"175bar.com", 
"176um.com", 
"178gg.com", 
"17gouwuba.com", 
"17leyi.com", 
"17un.co", 
"17un.com", 
"17zhaole.com", 
"189zj.cn", 
"18av.mm-cg.co", 
"18dusun.com", 
"18tzx.com", 
"1933000.com", 
"1cef.playfabapi.com", 
"1d1px.net", 
"1e2hyl3b.wq42211.com", 
"1i580.com", 
"1kmb.cn", 
"1kxun.mobi", 
"1kzh.com", 
"1l1.cc", 
"1lib.cn", 
"1mp.mobi", 
"1o26.com", 
"1phads.com", 
"1qwe3r.com", 
"1tlm.cn", 
"1uandun.com", 
"1x1rank.com", 
"1x3x.com", 
"2.1010pic.com", 
"2.21shebao.com", 
"2.5aigushi.com", 
"2.aili.com", 
"2.bashenghuo.com", 
"2.heiyange.com", 
"2.letvlive.com", 
"2.mobixs.cn", 
"2.nanrenwo.net", 
"2.rengshu.com", 
"2.tuxi.com.cn", 
"201071.com", 
"2012.8684.com", 
"2012ui.com", 
"20150930.cf", 
"2016.sina.cn", 
"2016bobo.cf", 
"2017img.myxh999.com", 
"202m.com", 
"203710.com", 
"204.scloud.lfengmobile.com", 
"20min.app.tamedia.click", 
"2144.cn", 
"21union.com", 
"22.qingsongbar.com", 
"22222jsc.com", 
"222627.com", 
"22lm.cc", 
"233wo.com", 
"2345.cn", 
"2345api.dftoutiao.com", 
"2345apicode.dftoutiao.com", 
"2345at.com", 
"235123.net", 
"247realmedia.com", 
"24haitao.net", 
"24s.ru", 
"256ppp.com", 
"268mob.cn", 
"272829.cc", 
"272xb.com", 
"285680.com", 
"28acglz.com", 
"29627a66.api.splkmobile.com", 
"2a.com.cn", 
"2cnt.net", 
"2m2n.com", 
"2mdnsys.com", 
"2o7.net", 
"3.guidaye.com", 
"3.ssqzj.com", 
"30350f.com", 
"30407799.com", 
"30ampj.com", 
"31.media.tumblr.com", 
"312036.com", 
"3180555.com", 
"32414.com", 
"32666099.com", 
"33.autohome.com.cn", 
"33.pcpop.com", 
"33544444.com", 
"336.com", 
"3388pjdc.com", 
"339.cn", 
"3393.com", 
"33lm.cc", 
"33shangyou.com", 
"35baba.cn", 
"3600.com", 
"360640.com", 
"360baidus.com", 
"360in.com", 
"360jiaquan.com", 
"360safego.com", 
"360shopping.com.cn", 
"360vip.front99.com", 
"361315.cc", 
"365bibi.com", 
"365safego.com", 
"366safego.com", 
"36pn.com", 
"3721zh.com", 
"376zf.com", 
"37cs.com", 
"37mnm.com", 
"37pk49.com", 
"37see.com", 
"37wan.cn", 
"37wan.com", 
"3808010.com", 
"38330.bet", 
"3839168.com", 
"38499.com", 
"38c99.com", 
"39330.bet", 
"3975lm.com", 
"39xc.net", 
"3cinteractive.com", 
"3dm.huya.com", 
"3dns-2.adobe.com", 
"3dns-3.adobe.com", 
"3dwwwgame.com", 
"3g.990.net", 
"3gl.net", 
"3gmimo.com", 
"3gmtr.com", 
"3htai.com", 
"3pt.placelocal.com", 
"3qmh.com", 
"3rd.t.sohu.com", 
"3wz6z.bchuangpi.cn", 
"3ygww.com", 
"4009997658.com", 
"404.safedog.cn", 
"4207008.com", 
"4242jj.com", 
"4242lll.com", 
"4242uuu.com", 
"4336wang.cn", 
"456juhd.com", 
"46sg.com", 
"49wanwan.com", 
"4d83.playfabapi.com", 
"4dle.info", 
"4dsply.com", 
"4ggww.com", 
"4mads.com", 
"4seeresults.com", 
"4wad.com", 
"4xhyr.shuimujinggong.com", 
"504pk.com", 
"5066.net", 
"50bang.org", 
"51.la", 
"5125129.com", 
"513hch.com", 
"517m.cn", 
"518.sdinfo.net", 
"5188yy.com", 
"519397.com", 
"51ads.com", 
"51chumoping.com", 
"51dql.com", 
"51gxqm.com", 
"51jumintong.com", 
"51la.net", 
"51link.com", 
"51mld.cn", 
"51network.com", 
"51vipedu.com", 
"51weidashi.com", 
"51xumei.com", 
"51yes.com", 
"51zhanzhuang.cn", 
"5207470.com", 
"5269120.com", 
"526d.uunice.com", 
"526dimg.uunice.com", 
"5293.com", 
"52kmh.com", 
"52kmk.com", 
"52lubo.cn", 
"5345ll.com", 
"537901.com", 
"55.la", 
"555p555p.com", 
"559gp.com", 
"55lu.com", 
"5634.com", 
"5675146.com", 
"57.com.cn", 
"57union.com", 
"58.xgo.com.cn", 
"5814889.com", 
"5857.com", 
"588yw.com", 
"58lm.vip", 
"58mingri.cn", 
"58mingtian.cn", 
"592man.com", 
"5dg.me", 
"5dian.org", 
"5egk.com", 
"5imoney.com", 
"5jcom.com.cn", 
"5vz3cfs0yd.me", 
"5y9nfpes.52pk.com", 
"5yrra.deshuangwang.cn", 
"600ad.com", 
"601654.com", 
"60608787.com", 
"626uc.com", 
"644446.com", 
"649558.com", 
"64si.com", 
"654mmm.com", 
"65c6.playfabapi.com", 
"6615338.cn", 
"6666349.com", 
"6669667.com", 
"66992949.com", 
"66san.com", 
"6711.com", 
"6728812.com", 
"685wo.com", 
"68665565.com", 
"69duk.com", 
"6a4cc.lubue.com", 
"6a4cc.luvbq.com", 
"6a4cc.luvbr.com", 
"6a4cc.luytr.com", 
"6boou.voluumtrk.com", 
"6d63d3.com", 
"6dad.com", 
"6dvip.com", 
"6huu.com", 
"6kwan.com", 
"6tsbe1zs.me", 
"700900.com", 
"706529.com", 
"7080555.com", 
"70e.com", 
"70lm.com", 
"711kk.com", 
"716703.com", 
"71sem.com", 
"73.sinawap.com", 
"743m1.11a12.com", 
"749558.com", 
"749808.com", 
"7540.com", 
"75to.com", 
"7631.com", 
"766ba.net", 
"76802.net", 
"77455.com", 
"778669.com", 
"7794.com", 
"77power.com", 
"77u.com", 
"77xtv.com", 
"7891655.cn", 
"79423.analytics.edgekey.net", 
"7car.com.cn", 
"7clink.com", 
"7dah8.com", 
"7gg.cc", 
"7jiajiao.com", 
"7mad.7m.cn", 
"7pk.com", 
"7wen.cn", 
"7xz3.com", 
"7z66.com", 
"8.dramafeverw2.appspot.com", 
"8.jrj.com", 
"801.tianyaui.com", 
"8066hg.com", 
"80sjw.com", 
"813690.top", 
"8184.cc", 
"818mov.com", 
"81c.cn", 
"8269996.com", 
"8368661.com", 
"846.move7.com", 
"849558.com", 
"85058s.com", 
"8521448.com", 
"85655095.com", 
"859377.com", 
"85tgw.com", 
"86.cc", 
"860010.com", 
"86kx.com", 
"878090.com", 
"8800271.com.cn", 
"88210212.com", 
"8866786.com", 
"888.izhufu.net", 
"888.jiuwanwang.com", 
"888.tv.sohu.com", 
"88818122.cn", 
"888zr022.com", 
"88cncc.com", 
"88rpg.net", 
"88shu.cn", 
"892155.com", 
"89h8.com", 
"8dulm.com", 
"8hykthze.cricket", 
"8jd2lfsq" 
], 
"outboundTag": "block", 
"type": "field" 
} 
] 
}, 
"stats": {} 
}

**Comment by akiirui** [comment]
@LittleGrocery Looks no wrong in your configuration. But I found a point to reproduce this issues.

In `dns`: 

```
"dns": {
  "hosts": {
    "domain:googleapis.cn": "googleapis.com"
  }
}
```

These lines are automatically added by v2rayNG.

Domain `googleapis.cn` hosts to `googleapis.com`. And `googleapis.com` is blocked by GFW.

And in `Settings - Routing - Predefined rules` select `Bypassing LAN and mainland address`, v2rayNG will be added a rule automatically:

```
{
  "domain": ["domain:googleapis.cn"],
  "outboundTag": "proxy",
  "type": "field"
}
```

But, If select `Global`. you need to add this rule manually.

**Comment by LittleGrocery** [comment]
> @LittleGrocery Looks no wrong in your configuration. But I found a point to reproduce this issues.
> 
> In `dns`:
> 
> ```
> "dns": {
>   "hosts": {
>     "domain:googleapis.cn": "googleapis.com"
>   }
> }
> ```
> 
> These lines are automatically added by v2rayNG.
> 
> Domain `googleapis.cn` hosts to `googleapis.com`. And `googleapis.com` is blocked by GFW.
> 
> And in `Settings - Routing - Predefined rules` select `Bypassing LAN and mainland address`, v2rayNG will be added a rule automatically:
> 
> ```
> {
>   "domain": ["domain:googleapis.cn"],
>   "outboundTag": "proxy",
>   "type": "field"
> }
> ```
> 
> But, If select `Global`. you need to add this rule manually.

@2dust please fix this bug.

**Comment by nidear1024** [comment]
> 确实是v2rayng的问题，我用隔壁的bifrostv就能下，我是ws+tls

有解决吗, 我和你一样,  v2rayng   google play能访问, 不能下载, 三星S20+, 有人说和三星手机系统有关,

**Comment by LiHang941** [comment]
> > 确实是v2rayng的问题，我用隔壁的bifrostv就能下，我是ws+tls
> 
> 有解决吗, 我和你一样, v2rayng google play能访问, 不能下载, 三星S20+, 有人说和三星手机系统有关,

不要全局就OK了

**Comment by q350976501** [comment]
> V2rayNG使用路由规则为全局 自定义规则直连只写:geosite:cn,geoip:cn 的情况，play市场无法更新下载，后查阅NG 17年有人提到的issue 把domain:google.cn,domain:googleapis.cn加入直连列表，故障依旧，后来把上述两条规则加入代理列表，play市场能下载更新了，猜测是这俩域名部分子域名被block了导致的，故开个issue提醒下大家

请问按照这个规则的话，自定义路由和路由策略应该选什么吗？

**Comment by lzplzp001** [comment]
这个BUG目前还是没有解决

**Comment by Joeypixiu** [comment]
我也遇到了同样问题,试了很多方法,最后 关闭 流量探测,解决了
