### ISSUE TITLE
避免将开关页面显示在最近任务列表

### ISSUE THREAD

**Issue by Vixb1122** [2dust/v2rayNG#524]
### 预期行为
在从最近列表中移除当前应用后，点击'开关'快捷方式，最近任务列表不出现当前应用

### 实际行为
在从最近列表中移除当前应用后，点击'开关'快捷方式，最近任务列表出现了当前应用

### 复现方法
1. 从最近列表中移除当前应用
2. 长按桌面图标
3. 点击'开关'快捷方式
4. 查看最近列表

**Comment by yuhan6665** [comment]
@Vixb1122 can't reproduce this issue with my device. Can you provide adb log?

**Comment by Vixb1122** [comment]
@yuhan6665 
### 复现方法
1. 从最近列表清除当前应用
2. 长按应用图标
3. 点击'开关'快捷方式
4. 查看最近列表，发现应用又出现在最近列表中了

（ss在杀死后台，点击开关后就不会出现在最近列表）

**Comment by Vixb1122** [comment]
@yuhan6665 
我看 ss 代码里面开关对应的界面加了
```
android:excludeFromRecents="true"
android:taskAffinity=""
android:process=":bg"
```

我提了个PR，你看看能达到类似效果不

**Comment by yuhan6665** [comment]
Oooh I see what you are saying, I thought you were saying the switch doesn't work at all. Yes there is a visual glitch.
I checked your PR I think it will fix the issue with "recents". But I believe if you want to fix the UI we need to change the white background to transparent and try to get rid of the action bar. Maybe https://stackoverflow.com/a/33251468/5495739
Anyway, thanks for your effort!

**Comment by Vixb1122** [comment]
@yuhan6665 我问题描述错了，已经把标题和描述修正了。我后台开关是没问题的。反馈的就是最近列表的问题。
