### ISSUE TITLE
连不上了，中午可以了，忽略这个问题吧，希望能够24小时都正常

### ISSUE THREAD

**Issue by KangDuoLa** [2dust/v2rayNG#529]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
成功连接

### 实际行为
无法连接

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by KangDuoLa** [comment]
手机测试说 context deadline exceeded

**Comment by twzchi** [comment]
> 手机测试说 context deadline exceeded

alterId 没有填错？

**Comment by tinyXiongGG** [comment]
我电脑端能正常使用，手机段不行了。
