### ISSUE TITLE
1.2.16 not work after sleep?

### ISSUE THREAD

**Issue by mactrash** [2dust/v2rayNG#536]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
It should be keep connection as long as I disconnect

### 实际行为
The connection broken after sometime after sleep... sometime it do work normally, need restart the app to reconnect

**Comment by mactrash** [comment]
Anyone meet the same after upgrade? of just me?

**Comment by yuhan6665** [comment]
Can you post the adb log when you experience connection broken?

**Comment by Loukky** [comment]
同样的问题，不过刚刚推送了一个新版本，看更新日志是bug fix，不知道有没有修复这个问题

**Comment by yuhan6665** [comment]
@Loukky yes it is fixed in 1.2.17
