### ISSUE TITLE
严重的bug

### ISSUE THREAD

**Issue by 2857584289** [2dust/v2rayNG#540]
规则改成绕过局域网和中国大陆地址或者绕过局域网这两个模式后，测试延迟，就占用1g多运行内存，而全局模式不会这样

**Comment by yuhan6665** [comment]
It should be fixed in 1.3.0. Can you test?

**Comment by 2857584289** [comment]
Yes

**Comment by 2857584289** [comment]
> It should be fixed in 1.3.0. Can you test?

但是测试一个节点延迟花费的时间变长了。

现在绕过模式测试延迟占用内存300多mb，全局模式是35mb。

**Comment by yuhan6665** [comment]
@2857584289 , yes the new change is to limit the testing to 3 v2ray-cores. So it will take longer to test all servers.

**Comment by 2857584289** [comment]
> @2857584289 , yes the new change is to limit the testing to 3 v2ray-cores. So it will take longer to test all servers.

But this seems to make v2rayng difficult to use, and I like v2rayng because it tests latency faster than SSR.

**Comment by yuhan6665** [comment]
Yeah in general it is a trade-off between speed and memory. Tcp test is quite fast. We want to make real test "real" so it apply almost the full configuration.

**Comment by 2857584289** [comment]
> Yeah in general it is a trade-off between speed and memory. Tcp test is quite fast. We want to make real test "real" so it apply almost the full configuration.

OK.But that doesn't seem to fix it per se,It only solves the problem from the side.
Also, the number of test connections v2ray-cores does not affect global mode memory.It just affect “绕过中国大陆和局域网” memory.
