### ISSUE TITLE
希望在分应用代理中加入Android system

### ISSUE THREAD

**Issue by tjc0726** [2dust/v2rayNG#543]
### 预期行为
描述你认为应该发生什么
分应用代理列表中显式显示android system

### 实际行为
分应用代理列表中没有有android system

### 额外信息（可选）
未选中Android system时会导致部分手机无法访问谷歌商城等，原因是因为谷歌会ping自己家域名，在无法连接的情况下，会对 GMS 实施 3 个限制，包括只允许访问解析 checkin.gstatic.com 得到的 IP，推迟 alarm，限制 wakelock。

https://github.com/shadowsocks/shadowsocks-android/issues/2138

**Comment by yuhan6665** [comment]
Added in #544

**Comment by tjc0726** [comment]
感谢
