### ISSUE TITLE
VLESS PREVIEW 1.3 无法在V2rayNG 下使用

### ISSUE THREAD

**Issue by twzchi** [2dust/v2rayNG#545]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
服务端正常，配置可以在WIN10 下运行

安卓端(10)：使用V2rayNG 版本号为1.2.18 (CoreV4.27.0)
1.v2rayNG_1.2.18.apk
 
2.v2rayNG_1.2.18_arm64-v8a.apk
两个客户端都无法正常使用VLESS 
### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息

通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
08-09 13:24:55.244 I/GoLog   (10172): loading v2ray config
08-09 13:24:55.244 I/GoLog   (10172): Preparing Domain: Web:443
08-09 13:24:55.245 I/GoLog   (10172): new v2ray core
08-09 13:24:55.245 I/GoLog   (10172): start v2ray core
08-09 13:24:55.251 I/GoLog   (10172): [Warning] v2ray.com/core: V2Ray 4.27.0 started
08-09 13:24:55.329 D/com.v2ray.ang(10172): [/data/app/com.v2ray.ang--3atWKNY_WSHdeKll3BKvw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
08-09 13:24:55.334 D/com.v2ray.ang(10172): Process[pid=10225, hasExited=false]
08-09 13:24:55.334 D/com.v2ray.ang(10172): /data/user/0/com.v2ray.ang/files/sock_path
08-09 13:24:55.341 I/tun2socks(10225): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
08-09 13:24:55.385 D/com.v2ray.ang(10172): sendFd tries: 0
08-09 13:24:55.386 I/tun2socks(10225): NOTICE(tun2socks): entering event loop
08-09 13:24:56.121 I/GoLog   (10172): Dial pending prepare  ... Web:443
08-09 13:24:56.168 I/GoLog   (10172): Dial pending prepare  ... Web:443
08-09 13:24:56.239 I/GoLog   (10172): Dial pending prepare  ... Web:443
08-09 13:24:56.449 I/GoLog   (10172): Dial pending prepare  ... Web:443
08-09 13:24:57.439 I/GoLog   (10172): Prepare Result:
08-09 13:24:57.439 I/GoLog   (10172):  Domain: Web
08-09 13:24:57.439 I/GoLog   (10172):  Port: 443
08-09 13:24:57.439 I/GoLog   (10172):  IPs: [WebIP]
08-09 13:24:57.503 I/GoLog   (10172): Using Prepared: WebIP
08-09 13:24:57.509 I/GoLog   (10172): Using Prepared: WebIP
08-09 13:24:57.513 I/GoLog   (10172): Using Prepared: WebIP
08-09 13:24:57.515 I/GoLog   (10172): Using Prepared: WebIP

**Comment by hibobmaster** [comment]
我用了最新发布的Pre-release v1.3，发现软件显示正常连接服务器，但是发现dns出错了
打开任何网站都是找不到ip

**Comment by twzchi** [comment]
> 我用了最新发布的Pre-release v1.3，发现软件显示正常连接服务器，但是发现dns出错了
> 打开任何网站都是找不到ip

是的 可以ping通 就是链接不上任何网站~

**Comment by hibobmaster** [comment]
我解决了，把手机的Private DNS关闭就正常使用起了

**Comment by twzchi** [comment]
> 我解决了，把手机的Private DNS关闭就正常使用起了

你是安卓系统9 还是10？我是安卓10

**Comment by hibobmaster** [comment]
我也是安卓10，我把Private DNS关掉，其他都正常了

**Comment by RPRX** [comment]
服务端证书要用 fullchain

**Comment by Trendyshuai** [comment]
> 我也是安卓10，我把Private DNS关掉，其他都正常了

打扰，请假一下怎么关闭Private DNS

**Comment by Trendyshuai** [comment]
> 我也是安卓10，我把Private DNS关掉，其他都正常了

打扰，请教一下怎么关闭Private DNS
