### ISSUE TITLE
v2rayng 如何保持 fcm 的长连接？

### ISSUE THREAD

**Issue by om2mo** [2dust/v2rayNG#546]
在v2rayng中无论怎么配置，都无法让fcm保持长连接，通常在10-15分钟就断开了（然后自动重连）。图片显示我已经把fcm的所有可能的域名和IP都添加了白名单（direct），但结果并不是预期的。
![Screenshot_20200810-035454](https://user-images.githubusercontent.com/4419299/89740851-14281000-dabf-11ea-8efb-ce544b41c04a.jpg)

甚至我把fcm端口也加入了规则，结果一样是最多15分钟断开。
 {
"port": "5228", 
"outboundTag": "direct",
        "type": "field"
},

而我在使用shadowsocks-android，gfwlist规则下，fcm可以一直保持连接。见图。
![Screenshot_20200810-041207__01](https://user-images.githubusercontent.com/4419299/89740916-ba741580-dabf-11ea-8cb0-40216c59fd6d.jpg)

所以我认为v2rayng也应该可以让fcm保持长连接，那么问题出在哪？

**Comment by yuhan6665** [comment]
@om2mo if you see the routing is direct connection, maybe you can play with "connIdle" for freedom outbound. See:
https://www.v2fly.org/config/policy.html#levelpolicyobject

**Comment by om2mo** [comment]
我的理解是既然fcm加入了白名单，它就和v2rayng没有直接关系了，本机的dns解析，本机的ip直连。
"policy": {"connIdle": 900}值改成0或300都不起作用fcm10分钟就自动断开了。

**Comment by yuhan6665** [comment]
@om2mo adding to direct means the traffic will handled by "freedom" outbound. Have you change the user level for that?

**Comment by reeceyng** [comment]
> 我的理解是既然fcm加入了白名单，它就和v2rayng没有直接关系了，本机的dns解析，本机的ip直连。 "policy": {"connIdle": 900}值改成0或300都不起作用fcm10分钟就自动断开了。

我在v2rayng的自定义配置中加了以下policy解决了
```
  "policy": {
    "levels": {
      "8": {
        "connIdle": 3000
      }
    }
  }
```

**Comment by lsjiaowo** [comment]
你好，请教一下，这个自定义配置怎样导入v2rayNG中呢？直接从剪切板导入提示错误。刚开始用，还不太熟悉功能。

**Comment by lsjiaowo** [comment]
@reeceyng 你好，请教一下，这个自定义配置怎样导入v2rayNG中呢？直接从剪切板导入提示错误。刚开始用，还不太熟悉功能。

**Comment by wdlid** [comment]
> > 我的理解是既然fcm加入了白名单，它就和v2rayng没有直接关系了，本机的dns解析，本机的ip直连。 "policy": {"connIdle": 900}值改成0或300都不起作用fcm10分钟就自动断开了。
> 
> 我在v2rayng的自定义配置中加了以下policy解决了
> 
> ```
>   "policy": {
>     "levels": {
>       "8": {
>         "connIdle": 3000
>       }
>     }
>   }
> ```

请问如何在v2rayNG怎么添加自定义配置？

**Comment by Narlim** [comment]
> > > 我的理解是既然fcm加入了白名单，它就和v2rayng没有直接关系了，本机的dns解析，本机的ip直连。 "policy": {"connIdle": 900}值改成0或300都不起作用fcm10分钟就自动断开了。
> > 
> > 
> > 我在v2rayng的自定义配置中加了以下policy解决了
> > ```
> >   "policy": {
> >     "levels": {
> >       "8": {
> >         "connIdle": 3000
> >       }
> >     }
> >   }
> > ```
> 
> 请问如何在v2rayNG怎么添加自定义配置？

#403
