### ISSUE TITLE
[FEATURE REQUEST] 希望增加开机自启的功能

### ISSUE THREAD

**Issue by ma-chengyuan** [2dust/v2rayNG#547]
如果使用类原生系统的话，GApps从系统启动开始就会开始同步，因此希望增加V2ray随系统自启的选项。和国内流量分流/分应用代理的特性结合使用的话也不会显著影响到日常的使用。如果这个实现起来过于琐碎也可以expose一些相关的API，例如可以用`Intent`的方式以一定的配置启动代理服务等。

**Comment by yuhan6665** [comment]
You can try integrate with `TaskerReceiver`. See source code for details.

**Comment by if1y** [comment]
You can enable 'Always-on VPN' in system settings.
It's a feature on the level of system, which makes vpn turn on faster than the app itself (if the app supports autostart).
