### ISSUE TITLE
使用vless协议，tcp+tls时必须开启allowinsecure否则无法连接，显示证书由未知机构签发

### ISSUE THREAD

**Issue by betaback** [2dust/v2rayNG#549]
证书是certbot安装的lets encrypt证书，在使用vless协议，tcp+tls时无法连接，显示证书由未知机构签发，打开allowinsecure选项即可使用，但是使用windows端v2rayn时一切正常，allowinsecure为false，可以使用
### 日志信息
<details>
08-11 13:07:47.551 I/GoLog   (31234): [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vless/outbound: connection ends > v2ray.com/core/proxy/vless/outbound: failed to decode response header > v2ray.com/core/proxy/vless/encoding: failed to read response version > x509: certificate signed by unknown authority

### 环境信息
server:
debian 10 stable
v2ray core 4.27.0
client:
android 10
v2rayNG 1.3.0

**Comment by RPRX** [comment]
服务端证书要用 fullchain

**Comment by betaback** [comment]
> 服务端证书要用 fullchain

是用的fullchain证书

**Comment by RPRX** [comment]
> 
> 
> > 服务端证书要用 fullchain
> 
> 是用的fullchain证书

那么，可能又是 OCSP Stapling 相关问题。。。N 和 NG 在同一网络下吗？

**Comment by betaback** [comment]
> > 
> > 
> > > 服务端证书要用 fullchain
> > 
> > 是用的fullchain证书
> 
> 那么，可能又是 OCSP Stapling 相关问题。。。N 和 NG 在同一网络下吗？

是的，同一个路由器
