### ISSUE TITLE
一加6点更新订阅会闪退

### ISSUE THREAD

**Issue by deepsky000** [2dust/v2rayNG#550]
但是通知栏显示软件还在运行，也可以正常使用
--------- beginning of main
--------- beginning of crash
08-12 08:21:34.934 E/com.v2ray.ang( 5813): Not starting debugger since process cannot load the jdwp agent.
08-12 08:21:34.976 I/com.v2ray.ang( 5813): [GL_OOM] ClampGrowthLimit 268435456

**Comment by yuhan6665** [comment]
@deepsky000 what is your v2rayNG version? What is your Android version? Can you try crash it again and see if possible to get more detailed log?

**Comment by deepsky000** [comment]
> @ deepsky000您的v2rayNG版本是什么？您的Android版本是什么？您可以再次尝试使其崩溃，看看是否有可能获得更详细的日志吗？

v2rayNG：1.3.0(Libv2rayLite V21，core V4.27.0)
android：10.0.3
试了很多次，日志只有那两条

**Comment by 2dust** [comment]
方便的话把你的订阅地址发到 captainIronng@protonmail.com

**Comment by deepsky000** [comment]
> 
> 
> 方便的话把你的订阅地址发到 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

已发

**Comment by deepsky000** [comment]
> 
> 
> 方便的话把你的订阅地址发到 [captainIronng@protonmail.com](mailto:captainIronng@protonmail.com)

已发

**Comment by deepsky000** [comment]
打扰了，卸载重装就好了
