### ISSUE TITLE
希望远程DNS能使用自定义端口（非53端口）

### ISSUE THREAD

**Issue by Loukky** [2dust/v2rayNG#551]
远程DNS一栏如果填写成IP:port （非标准端口），这时候查看日志会发现DNS实际上是请求的1.1.1.1:853
### 预期行为
应该支持其他端口

### 实际行为
使用的内置的1.1.1.1:853
### 复现方法
1.远程DNS随便填写一个IP:端口
2.连接服务器，访问网页，查看日志

### 日志信息
<details>

不需要
</details>

### 环境信息
Android 10
### 额外信息（可选）

app 版本1.2.18

**Comment by MonNomSontPasUtile** [comment]
Oh man I got my issue filed here #485 months ago but still without a proper response.
