### ISSUE TITLE
v2rayng 电脑端油管跑10W，手机只有8千

### ISSUE THREAD

**Issue by Meilinhost** [2dust/v2rayNG#552]
### 预期行为
v2rayng 电脑端油管跑10W，手机只有8千

### 实际行为
v2rayng 电脑端油管跑10W，手机只有8千，重装无数次 问题依旧

### 复现方法
1.
2.
3.

### 日志信息
功能正常，日志无报错，就是手机速度上不去，WIFI 单线程200M不存在WIFI问题
PC端跑10W不存在配置出错问题

### 环境信息
debian9 系统
vless-tls-web
vmess-tle-web
 

### 额外信息（可选）

https://i.loli.net/2020/08/13/fno6WlZRyCS1xpw.jpg
https://i.loli.net/2020/08/13/v7za1iCN6AmGqsP.jpg
https://i.loli.net/2020/08/13/L3yglWOuIJRBapz.jpg
https://i.loli.net/2020/08/13/173PvCNW4f9nGir.jpg

**Comment by 1265578519** [comment]
根据你的贴图 不是同一个视频没有参考价值，可能谷歌的CDN没有缓存，而且手机输出VP9编码，可能是CPU性能跟不上导致

**Comment by Meilinhost** [comment]
> 根据你的贴图不是同一个视频没有参考价值，可能谷歌的CDN没有缓存，而且手机输出VP9编码，可能是CPU性能跟不上导致

相同视频我也试过，我这个截图还是特意错开不同视频截取的，
如果是CPU限制的话好吧，我可以试试将835定在最高主频跑看看，问题是，你们没有遇到过？

**Comment by tom110111** [comment]
手机分辨率多少？手机分辨率低，像素点少，8k说不定就是已经满了的。。。。
