### ISSUE TITLE
Feature Request: resolve request host to a configurable set of ip addresses

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#553]
See more in this similar issue: [https://github.com/shadowsocks/shadowsocks-android/issues/2256](https://github.com/shadowsocks/shadowsocks-android/issues/2256)
Cloaking is not necessary though.

shadowsocks-android v5.0.6 has a 'hosts' option which makes it possible to resolve request host to a set of randum_shuffle()ed ip addresses but was removed in v5.1.0, is this possible in v2rayNG?

**Comment by yuhan6665** [comment]
Maybe you can just separately put the IPs you want in configuration, like,
https://guide.v2fly.org/app/balance.html#%E9%85%8D%E7%BD%AE
or
https://guide.v2fly.org/routing/balance2.html

**Comment by yuhan6665** [comment]
Thanks for your contribution btw
