### ISSUE TITLE
Routing in custom config failed due to predefined rules

### ISSUE THREAD

**Issue by 4piu** [2dust/v2rayNG#556]
- [x] 在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### Custom config
```json
{
	//...
	"outbounds":[
		//...
		{
			"tag":"REVERSE_PROXY",
			"protocol":"vmess",
			//...
		}
	],
	"routing":{
		"domainStrategy":"IPIfNonMatch",
		"rules":[
			//...
			{
				"outboundTag":"REVERSE_PROXY",
				"ip":[
					"10.10.0.0/16"
				],
				"type":"field"
			}
		]
	}
}
```

### 预期行为

* Traffic to 10.10.1.1 be dispatched to `REVERSE_PROXY` according to the custom config. 

### 实际行为

When `Settings > Routing > Predefined rules` set to `Bypassing the LAN address` or `Bypassing the LAN and mainland address`, the traffic to 10.10.1.1 will be considered as LAN address and sent out directly, without being routed by v2ray-core, so the rules `10.10.0.0/16` in the custom config is ineffective in this case. 

Set `Predefined rules` to `Global` gives the desired result, but it breaks non-custom config (eg. subscriptions)

### 环境信息

Version 1.3.1 (Libv2rayLite V21, Core V4.27.0) @ Android Q

### 额外信息（可选）

The config imported to v2RayNG works with v2ray-core on Linux.

**Comment by 4piu** [comment]
Break by #517

**Comment by yuhan6665** [comment]
What is the purpose of your configuration? Do you want to connect to 10.10.1.1 of the proxy server? Bypass means the phone should connect to this address directly, either not through core, or to take the freedom outbound.

**Comment by 4piu** [comment]
> What is the purpose of your configuration? Do you want to connect to 10.10.1.1 of the proxy server? Bypass means the phone should connect to this address directly, either not through core, or to take the freedom outbound.

Yes, `10.10.1.1` is a private address, but in my case, it is not a host in my LAN, the address is used to access a remote host behind NAT which is reverse proxied by v2ray. So direct access `10.10.1.1` will result nothing. It has to be processed by the routing rules. 

Here's my configuration: 
The `REVERSE_PROXY`: a v2ray portal with public IP. 
`10.10.1.1`(NAS): a v2ray bridge with private IP and locate in another LAN behind NAT. 

I want to enable secured access to my NAS using v2ray. 

What I previous achieved: 
Traffic from client to `10.10.1.1` is redirect to `REVERSE_PROXY`, then routing rules on the `REVERSE_PROXY` redirect request through portal/bridge to my NAS behind the firewall. Now I can access my NAS anywhere using `10.10.1.1` on any of my devices with v2ray installed. 

It works fine until the merge of #517 

The problem could be solved if I use another non-private IP address to refer to my NAS, for example `123.123.1.1`, so bypassing private address at VPN level will not affect my routing rules of `10.10.1.1` in v2ray, but I concern that it may cause conflict with real IPs on the Internet. 

May be it would be helpful if v2rayNG could offer user an option like "Bypass LAN at VPN service", so some user can still control the private address routing using custom config. 

Affixed my config if anyone's interested. 

### Config on REVERSE_PROXY

```json
{
  "reverse": {
    "portals": [
      {
        "tag": "portal",
        "domain": "somerandomshit"
      }
    ]
  },
  "inbounds": [
    {
      "port": 1234,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "2ebd3c1a-18fa-4fcb-8770-9b91b97f886b",
            "level": 0,
            "alterId": 4,
            "email": "client@local"
          },
          {
            "id": "9ebd32be-a7b8-48f3-987a-962945d1d137",
            "level": 0,
            "alterId": 4,
            "email": "tunnel@local"
          }
        ]
      },
      "streamSettings": { //... }
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "user": [
          "client@local"
        ],
        "ip": [
          "10.10.1.0/24"
        ],
        "outboundTag": "portal"
      },
      {
        "type": "field",
        "user": [
          "tunnel@local"
        ],
        "outboundTag": "portal"
      }
    ]
  }
}
```

### Config on NAS

```json
{
  "reverse": {
    "bridges": [
      {
        "tag": "bridge",
        "domain": "samerandomshit"
      }
    ]
  },
  "outbounds": [
    {
      "tag": "loopback",
      "protocol": "freedom",
      "settings": {
        "redirect": "127.0.0.1:0"
      }
    },
    {
      "tag": "tunnel",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "REVERSE_PROXY_PUBLIC_IP",
            "port": 1234,
            "users": [
              {
                "alterId": 4,
                "id": "9ebd32be-a7b8-48f3-987a-962945d1d137",
                "security": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": { //... }
    }
  ],
  "routing": {
    "rules": [
      {
        "type": "field",
        "inboundTag": [
          "bridge"
        ],
        "domain": [
          "full:samerandomshit"
        ],
        "outboundTag": "tunnel"
      },
      {
        "type": "field",
        "inboundTag": [
          "bridge"
        ],
        "ip": [
          "10.10.1.1"
        ],
        "outboundTag": "loopback"
      }
    ]
  }
}
```

**Comment by yuhan6665** [comment]
If I understand you correctly it is like https://guide.v2fly.org/app/reverse2.html#%E5%8E%9F%E7%90%86
You need to think from the client perspective. For the client, it is simple, There are two addresses, a destination address, a proxy server address. Bypass means the it should ignore proxy and connect to the destination directly.

In any case, note that predefined rule is just a convenience, you can:
1. select "Bypass Mainland address" or "Global"
2. add bypass "geoip:private" as a custom rule (if needed)
3. make sure your "10.10.0.0/16" rank higher than "geoip:private" in routing

**Comment by 4piu** [comment]
Use “Bypass Mainland address” is the recommended solution in the use case. Thanks @yuhan6665
