### ISSUE TITLE
手机端能不能加个默认跳过证书的功能？订阅的都用不了，要手动一个一个去改很麻烦，更新订阅又直接冲掉变成不允许又要去修改

### ISSUE THREAD

**Issue by 1265578519** [2dust/v2rayNG#558]
手机端能不能加个默认跳过证书的功能？订阅的都用不了，要手动一个一个去改很麻烦，更新订阅又直接冲掉变成不允许又要去修改
![image](https://user-images.githubusercontent.com/6442439/90321033-c147d000-df78-11ea-837d-6921a9c1c4da.png)

**Comment by yuhan6665** [comment]
there is a global settings in the menu

**Comment by RPRX** [comment]
所以我一直建议把“允许不安全连接”的表述都改为“跳过证书验证”，与 v2rayN 一致

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/90332845-04468980-dff3-11ea-971c-529efe3bd754.jpg)

好吧，找到了，中文翻译不一样，，，一会没看明白
