### ISSUE TITLE
windows正常工作的config.json导入NG后不工作

### ISSUE THREAD

**Issue by qingfengshi** [2dust/v2rayNG#56]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。填写完问题模板后请删除提示，否则可能会被直接关闭问题。

### 预期行为
描述你认为应该发生什么

导入电脑端正常工作的json文件后能够正常工作。

### 实际行为
描述实际发生了什么

导入电脑端正常工作的json文件后不能上网。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>
03-21 22:38:38.575 I/GoLog   ( 2022): (map[string]*net.TCPAddr) (len=2) {
03-21 22:38:38.575 I/GoLog   ( 2022):  (string) (len=25) "**********************:***": (*net.TCPAddr)(<nil>),
03-21 22:38:38.575 I/GoLog   ( 2022):  (string) (len=25) "**********************:***": (*net.TCPAddr)(<nil>)
03-21 22:38:38.575 I/GoLog   ( 2022): }
03-21 22:38:38.590 I/GoLog   ( 2022): Protecting Sock: 47
03-21 22:38:38.592 I/GoLog   ( 2022): (*net.TCPAddr)(0x8b5acdc0)(**********************:***)
03-21 22:38:38.592 I/GoLog   ( 2022): (map[string]*net.TCPAddr) (len=2) {
03-21 22:38:38.592 I/GoLog   ( 2022):  (string) (len=25) "**********************:***": (*net.TCPAddr)(<nil>),
03-21 22:38:38.592 I/GoLog   ( 2022):  (string) (len=25) "**********************:***": (*net.TCPAddr)(<nil>)
03-21 22:38:38.592 I/GoLog   ( 2022): }
03-21 22:38:40.560 I/GoLog   ( 2022): Protecting Sock: 834
03-21 22:38:40.561 I/GoLog   ( 2022): (*net.TCPAddr)(0x8b69eb00)(**********************:***)
03-21 22:38:40.561 I/GoLog   ( 2022): (map[string]*net.TCPAddr) (len=2) {
03-21 22:38:40.561 I/GoLog   ( 2022):  (string) (len=25) "**********************:***": (*net.TCPAddr)(<nil>),
03-21 22:38:40.569 I/GoLog   ( 2022):  (string) (len=25) "**********************:***": (*net.TCPAddr)(<nil>)
03-21 22:38:40.569 I/GoLog   ( 2022): }

其中我的ip和服务器ip被我隐藏了
### 环境信息
系统：Android 7.0
### 额外信息（可选）
我的json文件中使用了http伪装，服务器ip有3个。config.json在电脑端使用v2ray.exe正常，但是导入到v2rayNG后不能正常使用。
另外，v2ray的request host中，是填入json文件中host的内容吗？举例来说，是填为 “"www.cloudflare.com", "www.amazon.com", "www.bing.com"”吗？“”内为输入NG的内容。

**Comment by ZhouZiY** [comment]
It may the problem in #58 .

**Comment by spatgit** [comment]
@ZhouZiY where to get cert.pem and chain.pem, and what's the relationship between these two and v2rayNG?
