### ISSUE TITLE
不知道什么原因无法使用

### ISSUE THREAD

**Issue by yhjuigr** [2dust/v2rayNG#567]
这里是图片，我也不知道怎么描述，如果有什么不对的地方，包涵一下吧
![Screenshot_2020-08-24-09-30-21-185_com v2ray ang](https://user-images.githubusercontent.com/70120096/90995101-7881be00-e5ed-11ea-8e55-ccfaf82b2cac.jpg)

**Comment by testttt0** [comment]
我也遇到了同样的问题，原因不明，v2rayNG以及服务端之前一直是正常使用的，并非全新安装。在windows平台下使用v2rayN验证，排除服务端出问题的可能。
![微信图片_20200824120547](https://user-images.githubusercontent.com/6056581/91003048-d40a7680-e602-11ea-8541-f65aebc9a680.jpg)
![微信图片_20200824120558](https://user-images.githubusercontent.com/6056581/91003052-d5d43a00-e602-11ea-8fe3-51c665ef3c00.png)

**Comment by yhjuigr** [comment]
> 我也遇到了同样的问题，原因不明，v2rayNG以及服务端之前一直是正常使用的，并非全新安装。在Windows平台下使用v2rayN验证，排除服务端出问题的可能。
> ![微信图片_20200824120547](https://user-images.githubusercontent.com/6056581/91003048-d40a7680-e602-11ea-8541-f65aebc9a680.jpg)
> ![微信图片_20200824120558](https://user-images.githubusercontent.com/6056581/91003052-d5d43a00-e602-11ea-8fe3-51c665ef3c00.png)

那就可能是线路的问题了吗？
