### ISSUE TITLE
仅ipv4环境下如果启用了ipv6会导致双栈域名无法fallback到ipv4

### ISSUE THREAD

**Issue by Loukky** [2dust/v2rayNG#569]
本机仅有ipv4，服务器v4+v6，因此有打开设置里面的ipv6，使用中发现a.app.qq.com为双栈域名，DNS设置为223.6.6.6，开启ipv6的情况下，会解析到ipv6地址，然后因为国内域名+本机只有ipv4直连，最后导致无法连接。

### 预期行为
正常回落至ipv4，或者在本地网络环境ipv4 only请求DNS解析的时候只解析到ipv4地址。
经过比较PC版的行为，似乎是v2rayng代理流量的时候直接连接的IP，而不是转发的域名，所以会有不回落ipv4的情况发生。同时请求DNS不应该由设置的开关来限定，实际测试不打开ipv6路由的情况下，请求DNS的结果只有ipv4，打开以后，双栈域名只有ipv6。正常的情况下应该是打开以后同时能解析到ipv4地址与ipv6地址。这样才能保证回落的效果。
### 实际行为
网络不可达，未回落至ipv4

### 复现方法
1.双栈服务器
2.本地ipv4 only坏境，dns设置成阿里的。
3.访问，a.app.qq.com

### 日志信息
<details>
--------- beginning of main
08-26 01:31:59.080 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.080 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.080 I/GoLog   (25417): [Info] [1071607199] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.080 I/GoLog   (25417): [Info] [3932267078] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.085 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 79 Err: network is unreachable
08-26 01:31:59.086 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:31:59.386 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.387 I/GoLog   (25417): [Info] [1071607199] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.387 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.387 I/GoLog   (25417): [Info] [3932267078] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.396 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 78 Err: network is unreachable
08-26 01:31:59.396 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:31:59.798 I/GoLog   (25417): [Info] [3932267078] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:a.app.qq.com:443 > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
08-26 01:31:59.798 I/GoLog   (25417): [Info] [1071607199] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:a.app.qq.com:443 > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
08-26 01:31:59.798 I/GoLog   (25417): [Info] [1071607199] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
08-26 01:31:59.798 I/GoLog   (25417): [Info] [3932267078] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
08-26 01:31:59.822 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.822 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/proxy/socks: TCP Connect request to tcp:[2409:8c54:1003:1019::af]:443
08-26 01:31:59.822 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/proxy/socks: TCP Connect request to tcp:[2409:8c54:1003:1019::af]:443
08-26 01:31:59.822 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.822 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/app/dispatcher: sniffed domain: a.app.qq.com
08-26 01:31:59.822 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:a.app.qq.com:443]
08-26 01:31:59.822 I/GoLog   (25417): tcp:127.0.0.1:45294 accepted tcp:[2409:8c54:1003:1019::af]:443 [direct] 
08-26 01:31:59.823 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/proxy/freedom: opening connection to tcp:a.app.qq.com:443
08-26 01:31:59.823 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.823 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/app/dispatcher: sniffed domain: a.app.qq.com
08-26 01:31:59.823 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:a.app.qq.com:443]
08-26 01:31:59.823 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/proxy/freedom: opening connection to tcp:a.app.qq.com:443
08-26 01:31:59.823 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.823 I/GoLog   (25417): tcp:127.0.0.1:45298 accepted tcp:[2409:8c54:1003:1019::af]:443 [direct] 
08-26 01:31:59.827 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:31:59.828 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 79 Err: network is unreachable
08-26 01:31:59.828 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.828 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.828 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.828 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.833 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 78 Err: network is unreachable
08-26 01:31:59.833 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:31:59.934 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.934 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.936 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:31:59.936 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:31:59.941 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 78 Err: network is unreachable
08-26 01:31:59.942 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:32:00.142 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:32:00.142 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:32:00.142 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:32:00.142 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:32:00.146 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:32:00.146 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:32:00.447 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:32:00.447 I/GoLog   (25417): Not Using Prepared: tcp,a.app.qq.com:443
08-26 01:32:00.448 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:32:00.448 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:a.app.qq.com:443
08-26 01:32:00.456 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 77 Err: network is unreachable
08-26 01:32:00.456 I/GoLog   (25417): fdConn unix.Connect err, Close Fd: 79 Err: network is unreachable
08-26 01:32:00.791 I/GoLog   (25417): [Info] [3061492625] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
08-26 01:32:00.791 I/GoLog   (25417): [Info] [3061492625] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
08-26 01:32:00.857 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:a.app.qq.com:443 > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
08-26 01:32:00.857 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:a.app.qq.com:443 > v2ray.com/core/common/retry: [network is unreachable] > v2ray.com/core/common/retry: all retry attempts failed
08-26 01:32:00.857 I/GoLog   (25417): [Info] [711443456] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
08-26 01:32:00.857 I/GoLog   (25417): [Info] [2519025948] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

</details>

### 环境信息
Android 10，app版本1.31

**Comment by yuhan6665** [comment]
Try "UseIPv4" for your freedom outbound
https://www.v2fly.org/config/protocols/freedom.html#outboundconfigurationobject

**Comment by Loukky** [comment]
@yuhan6665 实际上，由于该域名属于国内地址，又是双栈解析，由于本机没有ipv6地址，在v2rayng中启用优先使用ipv6路由以后，v2rayng会一直优先使用ipv6进行直连，导致网络不可达，该域名由于没有经v2rayng处理以传送至服务端，所以修改服务端设置应该不起作用…

**Comment by yuhan6665** [comment]
@Loukky I meant change the v2rayNG config on your phone. (Need custom configuration)

**Comment by Loukky** [comment]
@yuhan6665 是的，如果使用仅ipv4确实可以解决该问题，但是并没有从根源上来解决。
另外日志中也有显示，在开启ipv6路由优先的情况下，dns实际上是也有解析到ipv6和ipv4的地址，但是由于v2rayNG的内部路由原因，ipv6不可达时，不会fallback到ipv4。这就是我所反映的问题。

**Comment by laaArmy** [comment]
我不但用v2rayng会这样，nekobox也会这样

**Comment by laaArmy** [comment]
现在你还有没有遇到这个问题？

**Comment by Loukky** [comment]
> 现在你还有没有遇到这个问题？

我现在基本上都在双栈环境下，没有关注这个了。
