### ISSUE TITLE
The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by Mkurbanov** [2dust/v2rayNG#570]
Who can help me?

When i run app this problem:
```
08/26 01:21:34: Launching 'app' on samsung SM-G960U.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER
Installation failed due to: 'null'
Retry
```

I changed AplicationID. But can't run. V2RayNG is installed. I need install my app and V2rayNG.

**Comment by yuhan6665** [comment]
It is caused by this line

https://github.com/2dust/v2rayNG/blob/8efdab43d7cc9c137e3c68557a4f24b76275e381/V2rayNG/dpreference/src/main/AndroidManifest.xml#L11

You can simply refactor this authorities name (in code as well)

**Comment by Mkurbanov** [comment]
> It is caused by this line
> 
> https://github.com/2dust/v2rayNG/blob/8efdab43d7cc9c137e3c68557a4f24b76275e381/V2rayNG/dpreference/src/main/AndroidManifest.xml#L11
> 
> You can simply refactor this authorities name (in code as well)

Bro, are you know? why project is old version? I just downloded project and run app. But i see the app is older version 1.0.2.
And app not working normally?

**Comment by Mkurbanov** [comment]
version of 2019. 

`versionName "1.0.2"`

**Comment by Mkurbanov** [comment]
look:
https://github.com/2dust/v2rayNG/blob/8efdab43d7cc9c137e3c68557a4f24b76275e381/V2rayNG/app/build.gradle#L20
