### ISSUE TITLE
无法登陆或查看节点

### ISSUE THREAD

**Issue by SYQsb** [2dust/v2rayNG#571]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
今天晚上使用时PC（win10）端无法查看节点列表，退出登陆后试图重新登入也一直失败（如下图），借了别人的电脑也一样
![image](https://user-images.githubusercontent.com/70281223/91327424-13e67f00-e7f8-11ea-8da1-a7cdf6b02dcf.png)
试了一下手机和ipad都可以正常使用。我前两天用的时候还正常，是这两天服务器在维修吗？

**Comment by ghost** [comment]
v2ray及其衍生软件的开发者不提供任何代理节点服务，v2box网站属于第三方，与软件作者无关。
请去对应服务官网寻找客服联系方式。谢谢。
