### ISSUE TITLE
使用Source code1.3.1编译问题

### ISSUE THREAD

**Issue by fxfxy** [2dust/v2rayNG#572]
第一行用来感谢作者无私奉献。

使用仓库最新版本1.3.1版本的Source code编译apk，
发现安装出来的v2rayNG与仓库最新版1.3.1的apk不一样.

Source code编译的apk安装后v2rayNG的版本是
1.0.2(Libv2rayLite V20,Core V4.20.0)
而使用仓库最新版1.3.1的apk安装后v2rayNG的版本是
1.3.1(Libv2rayLite V21,Core V4.27.0)

这是因为仓库源码不是最新版吗？小白不解。

**Comment by Mkurbanov** [comment]
@2dust 

我也有这样的问题。
源版本1.0.2。
最新版本是 V2Ray 1.3.1


需要源代码1.3.1！

**Comment by pyengwoei** [comment]
是的，我也出现了这个问题
