### ISSUE TITLE
希望能添加“仅代理”模式

### ISSUE THREAD

**Issue by kolicime** [2dust/v2rayNG#578]
未root的用户使用adguard的同时想要使用代理会用到这个功能
shadowsocks和clash for android都有这个功能，但是比较习惯用v2rayng，不知道未来会不会实现该功能

**Comment by yuhan6665** [comment]
I have a good news for you. I'm working on this feature and probably send pr next week.

**Comment by kolicime** [comment]
> I have a good news for you. I'm working on this feature and probably send pr next week.

Good job! I am looking forward.

**Comment by yuhan6665** [comment]
Added in #587

**Comment by om2mo** [comment]
> I have a good news for you. I'm working on this feature and probably send pr next week.

这个方式是怎么用的呢

**Comment by yuhan6665** [comment]
@om2mo I will add some simple guide, probably next week. You can get some ideas:
https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy
https://www.howtogeek.com/295048/how-to-configure-a-proxy-server-on-android/

**Comment by wsickid** [comment]
请问新版v2rayng安卓版的仅代理和vpn模式有什么区别

**Comment by wsickid** [comment]
请问新版v2rayng安卓版的仅代理和vpn模式有什么区别。我改成仅代理后重启v2ray，就上不了了，该回vpn模式才能上
