### ISSUE TITLE
[Feature Request] Service Mode

### ISSUE THREAD

**Issue by chromer030** [2dust/v2rayNG#582]
Hi , Thanks for this great app.
Please add Service mode , so user can choose between ( Proxy only , VPN , Transproxy )
For some apps Proxy only mode is essential while it's not needed to tunnel all traffic throughout VPN when you just want use an app like twitter.
For some apps like Gapps . which doesnt service while VPN is ON , using Proxy mode in other apps.
This feature is present in android version of Shadowsocks and its really good and useful.
I think V2rayNG also need this feature.

**Comment by yuhan6665** [comment]
Added in #587

**Comment by chromer030** [comment]
confirm working well , thank you very much.
