### ISSUE TITLE
各位您好，我想知道这个软件如何下载，订阅号如何购买，哪里有教程吗？跪求  真的不懂

### ISSUE THREAD

**Issue by 1075997402** [2dust/v2rayNG#583]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ghost** [comment]
1.前往releases（版本发布）页面（目前是这个页面：https://github.com/2dust/v2rayNG/releases ） ，在Assets（资源）中点击 v2rayNG_x.x.x.apk 这样的名称就可以下载了，每次更新都会在这里发布。armeabi-v7a后缀为32位版本，arm64-v8a为64位版本，较新的手机需要下载后者。（在中国大陆可能无法直接下载，需要另外的代理）
2.订阅号的话，可以在搜索引擎中输入“v2ray机场” “机场支持v2ray”这样的关键词，寻找自己满意的选择（在这里“机场”一词是指专门提供代理服务的商家）。一般来说，在支持此协议的机场的用户后台页面中会提供节点的导入网址，如果要使用的话，将对应网址添加到客户端中的“订阅设置”选项中即可。

**Comment by smallqiang007** [comment]
需要订阅号的可以联系我，高速稳定，价格超低！

**Comment by zyx945945** [comment]
我用的vcross.cf，这家不错
