### ISSUE TITLE
私人DNS设置为阿里DNS时，无法解析出来任意域名

### ISSUE THREAD

**Issue by Loukky** [2dust/v2rayNG#586]
首先这个问题很奇怪，在系统选项里面把私人DNS开启并设置成dns.alidns.com时，系统日志会出现无法解析这个域名，换成谷歌的google.dns又正常。
补充一下：如果不打开v2rayn，直接使用阿里DNS的情况下，是可以正常解析地址，打开网页的。
同时我也测试了国外多地的服务器，均无法在私人DNS设置成阿里DNS的情况下打开网页。

### 预期行为
应该可以正常使用阿里DNS的DOT功能

### 实际行为
无法解析阿里DNS的域名，导致无法使用，详见日志

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
--------- beginning of main

09-04 09:53:42.870 I/GoLog   (24314): [Debug] [1903740147] v2ray.com/core/proxy/socks: writing back UDP response with 41 bytes
09-04 09:53:43.192 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:53:43.193 I/GoLog   (24314): [Info] [170454248] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:53:43.193 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:53:43.194 I/GoLog   (24314): [Info] [2267178724] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:53:45.836 I/GoLog   (24314): [Info] [2474034925] v2ray.com/core/app/proxyman/inbound: connection ends > EOF
09-04 09:53:45.836 I/GoLog   (24314): [Info] [942104038] v2ray.com/core/app/proxyman/inbound: connection ends > EOF
09-04 09:53:50.759 I/GoLog   (24314): [Info] [1903740147] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: connection ends > context canceled
09-04 09:53:50.760 I/GoLog   (24314): [Info] [1903740147] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
09-04 09:53:51.716 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:53:51.716 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:53:51.716 I/GoLog   (24314): [Info] [2267178724] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:53:51.716 I/GoLog   (24314): [Info] [170454248] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:54:00.344 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:54:00.344 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:54:00.344 I/GoLog   (24314): [Info] [2267178724] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:54:00.344 I/GoLog   (24314): [Info] [170454248] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:54:01.837 I/GoLog   (24314): [Info] [1903740147] v2ray.com/core/app/proxyman/inbound: connection ends > EOF
09-04 09:54:09.070 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:54:09.070 I/GoLog   (24314): [Info] [2267178724] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:54:09.070 I/GoLog   (24314): [Info] [170454248] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:dns.alidns.com:853
09-04 09:54:09.071 I/GoLog   (24314): Not Using Prepared: tcp,dns.alidns.com:853
09-04 09:54:17.898 I/GoLog   (24314): [Info] [170454248] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:dns.alidns.com:853 > v2ray.com/core/common/retry: [lookup dns.alidns.com: No address associated with hostname] > v2ray.com/core/common/retry: all retry attempts failed
09-04 09:54:17.898 I/GoLog   (24314): [Info] [2267178724] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/freedom: failed to open connection to tcp:dns.alidns.com:853 > v2ray.com/core/common/retry: [lookup dns.alidns.com: No address associated with hostname] > v2ray.com/core/common/retry: all retry attempts failed
09-04 09:54:17.898 I/GoLog   (24314): [Info] [2267178724] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
09-04 09:54:17.898 I/GoLog   (24314): [Info] [170454248] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/socks: connection ends > v2ray.com/core/proxy/socks: failed to transport all TCP response > io: read/write on closed pipe

```
</details>

**Comment by yuhan6665** [comment]
Maybe you can try 223.5.5.5?
https://developer.aliyun.com/article/757592

**Comment by Loukky** [comment]
@yuhan6665 dot地址必须是域名，不能填写ip，另外，不启用v2rayng的情况下是可以使用该dot地址。

**Comment by yuhan6665** [comment]
@Loukky I read from the link suggest ip is ok too and it saves a step

> 1.终端设备配置DoT的解析服务器dns.alidns.com 或alidns_ip
2.如果配置的是alidns.com，客户端先解析alidns.com获得地址alidns_ip
3.获得DoT解析服务器IP地址之后，终端设备再建立与DoT解析服务器在端口853 的TCP连接

**Comment by Loukky** [comment]
@yuhan6665 事实上如果不开启v2rayNG的情况下，dot服务器填写为dns.alidns.com确实是可以生效的。
现在的issue是把系统的私人dns设置dns.alidns.com的情况下，v2rayNG无法获取到解析地址包括国内国外的网站

**Comment by IceCodeNew** [comment]
是这样的，我遇到过同样的问题。
这个问题首先和安卓版本有关，安卓 9 上私人 DNS 会在开启 VPN 时把解析交给 VPN 处理
而安卓 10 及以上即使开始 VPN 也不会把解析交给 VPN 处理
而在我遇到问题的场景里，手机操作系统是安卓 9。v2rayNG 虽然启动内核没有遇到问题，但是不能访问任何网站。一查日志看到里面不少我设置的私人 DNS 的域名地址……这等于是个死循环，因为我填的私人 DNS 服务器域名被策略选择了走代理路由，而代理要开始工作需要先解析成功服务器域名。
我觉得从根本上来说，安卓上私人 DNS 实现只支持 DoT，又莫名其妙不允许填 IP 地址是最大的问题。
我已经放弃使用私人 DNS 了，改为 ADGuard 配合 v2rayNG。这里要感谢 @yuhan6665 的工作，让 v2rayNG 的 proxy only 模式成为现实。

**Comment by Loukky** [comment]
> 是这样的，我遇到过同样的问题。
> 这个问题首先和安卓版本有关，安卓 9 上私人 DNS 会在开启 VPN 时把解析交给 VPN 处理
> 而安卓 10 及以上即使开始 VPN 也不会把解析交给 VPN 处理
> 而在我遇到问题的场景里，手机操作系统是安卓 9。v2rayNG 虽然启动内核没有遇到问题，但是不能访问任何网站。一查日志看到里面不少我设置的私人 DNS 的域名地址……这等于是个死循环，因为我填的私人 DNS 服务器域名被策略选择了走代理路由，而代理要开始工作需要先解析成功服务器域名。
> 我觉得从根本上来说，安卓上私人 DNS 实现只支持 DoT，又莫名其妙不允许填 IP 地址是最大的问题。
> 我已经放弃使用私人 DNS 了，改为 ADGuard 配合 v2rayNG。这里要感谢 @yuhan6665 的工作，让 v2rayNG 的 proxy only 模式成为现实。

我遇到的问题是私人DNS设置为dns.google能正常使用，设置成阿里DNS无法正常使用，查看相关日志发现无法解析到阿里DNS的地址。所以确实是一个奇怪的问题，当然也有可能谷歌DNS的地址由Android系统内置了。不过如果不开启v2rayng的话，仅私人DNS设置成阿里DNS，是可以正常使用。

**Comment by rurirei** [comment]
it's bug of system Android. see logcat of ConnectivityService. i will check it out.

**Comment by rurirei** [comment]
that's bug of Android (10 included).

maybe Private DNS overrides DnsServer as problems occurred. see logcat of ConnectivityService to point this.

i found this when i worked on FakeDns.

**Comment by xxllllll** [comment]
> 是这样的，我遇到过同样的问题。
> 这个问题首先和安卓版本有关，安卓 9 上私人 DNS 会在开启 VPN 时把解析交给 VPN 处理
> 而安卓 10 及以上即使开始 VPN 也不会把解析交给 VPN 处理
> 而在我遇到问题的场景里，手机操作系统是安卓 9。v2rayNG 虽然启动内核没有遇到问题，但是不能访问任何网站。一查日志看到里面不少我设置的私人 DNS 的域名地址……这等于是个死循环，因为我填的私人 DNS 服务器域名被策略选择了走代理路由，而代理要开始工作需要先解析成功服务器域名。
> 我觉得从根本上来说，安卓上私人 DNS 实现只支持 DoT，又莫名其妙不允许填 IP 地址是最大的问题。
> 我已经放弃使用私人 DNS 了，改为 ADGuard 配合 v2rayNG。这里要感谢 @yuhan6665 的工作，让 v2rayNG 的 proxy only 模式成为现实。

我也遇到了这个问题，想改用adguard+v2rayng，但请问他们两个都是通过VPN连接，如何共存？感谢！

**Comment by yuhan6665** [comment]
@xxllllll https://github.com/2dust/v2rayNG/wiki/Mode
