### ISSUE TITLE
软件点击右下角按钮没有任何响应

### ISSUE THREAD

**Issue by Ibluesoul** [2dust/v2rayNG#59]
### 预期行为
正常使用

### 实际行为
点击连接按钮没有任何响应

### 日志信息
软件的logcat显示

```
-------beginning of main
-------beginning of system
```

只有这两句

### 环境信息
国行三星note8 官方系统 v2rayng 0.3.12

### 额外信息（可选）
我还尝试过用BifrostV，也是点击连接没有任何响应，不知道是什么情况 日志也没任何报错信息， 我的配置信息在电脑端配置可以使用。提这个issue主要是想知道我接下去解决问题的方向。另外  我手机能正常使用影梭。

**Comment by scream7** [comment]
same issue

**Comment by dawndiy** [comment]
在 Android 系统中 Settings -> VPN 里将其他应用的 "Always-on VPN" 关闭。如果还不行就是系统有问题了。

**Comment by Ibluesoul** [comment]
我重置了一下系统 之后就正常了。
