### ISSUE TITLE
能否提供一份编译指南?

### ISSUE THREAD

**Issue by HiColinn** [2dust/v2rayNG#593]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
非BUG或者建议反馈
-----
能否提供一份windows或者MacOS的编译指南?需要搭建什么环境.谢谢大佬

**Comment by likky** [comment]
不需要搭建任何环境，如果你入门了安卓开发hello world，那么这个就那样编译生成APK。

**Comment by HiColinn** [comment]
> 不需要搭建任何环境，如果你入门了安卓开发hello world，那么这个就那样编译生成APK。

你编译过?
隔壁ShdowSocks编译环境及其复杂,需要搭建Go语言等好几种语言的编译环境.

**Comment by likky** [comment]
当然编译过几十次了

**Comment by HiColinn** [comment]
> 当然编译过几十次了

好的,我编译一下试试

**Comment by HiColinn** [comment]
> 当然编译过几十次了

确实,v2ray比shadowsocks好编译多了,有些需要的so文件,作者直接将二进制放进源码了,一次成功.谢谢.
shadowsocks玛德需要go环境,c++编译链,rust环境,一大堆...android studio不用预览版的都编译不成

**Comment by Woxiee** [comment]
> > 当然编译过几十次了
> 
> 确实,v2ray比shadowsocks好编译多了,有些需要的so文件,作者直接将二进制放进源码了,一次成功.谢谢. shadowsocks玛德需要go环境,c++编译链,rust环境,一大堆...android studio不用预览版的都编译不成

可以发一份能编译的 v2ray 代码发我邮箱吗  15989467261@163.com
