### ISSUE TITLE
WhatsApp视频通话频繁断开自动重连

### ISSUE THREAD

**Issue by wybzd12** [2dust/v2rayNG#594]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
我前天开始使用WhatsApp打视频电话，但是不知道是什么原因。视频过程中频繁出现断流，reconnection, 出现频率大概是一分钟三次。

### 预期行为
一开始我以为是机场的问题，但是我观看YouTube和任何其他网站，速度和流畅性都没问题。即使我在和朋友用WhatsApp文字聊天的时候，或者发图片的时候，也没有出现断流的问题。只有在视频中出现问题。

### 实际行为
实际就是断流发生了

### 复现方法
1.只要一视频通话，WhatsApp就会一会儿就断开，然后自动重新连接。
2.
3.

### 环境信息
安卓，华为，国外买的，自带Google play

谢谢你

**Comment by nakululusatuva** [comment]
猜测中断可能是由于延迟过高导致的。
YouTube看视频带宽够就行了无所谓延迟多大，但是实时视频对延迟很敏感所以一般是走udp协议，开启v2ray的话udp流量会被包装成tcp传输，所以导致频繁中断。

Reference：https://toutyrater.github.io （1.2.8. 刚开始使用 V2Ray，有什么需要注意的吗？）
“VMess 是基于 TCP 的协议，对于 UDP 包 V2Ray 会转成 TCP 再传输的，即 UDP over TCP。要 UDP 转发功能在客户端的 socks 协议中开启 UDP 即可。“

**Comment by wybzd12** [comment]
> 猜测中断可能是由于延迟过高导致的。
> YouTube看视频带宽够就行了无所谓延迟多大，但是实时视频对延迟很敏感所以一般是走udp协议，开启v2ray的话udp流量会被包装成tcp传输，所以导致频繁中断。
> 
> Reference：https://toutyrater.github.io （1.2.8. 刚开始使用 V2Ray，有什么需要注意的吗？）
> “VMess 是基于 TCP 的协议，对于 UDP 包 V2Ray 会转成 TCP 再传输的，即 UDP over TCP。要 UDP 转发功能在客户端的 socks 协议中开启 UDP 即可。“

您好，谢谢回复。不过，我想问一下，我在安卓上的客户端的设置的地方在哪儿呢？麻烦告知我一下您说的需要在客户端的socks协议中开启udp即可，是在哪儿找到这个设置呢？

**Comment by ghost** [comment]
> > 猜测中断可能是由于延迟过高导致的。
> > YouTube看视频带宽够就行了无所谓延迟多大，但是实时视频对延迟很敏感所以一般是走udp协议，开启v2ray的话udp流量会被包装成tcp传输，所以导致频繁中断。
> > Reference：https://toutyrater.github.io （1.2.8. 刚开始使用 V2Ray，有什么需要注意的吗？）
> > “VMess 是基于 TCP 的协议，对于 UDP 包 V2Ray 会转成 TCP 再传输的，即 UDP over TCP。要 UDP 转发功能在客户端的 socks 协议中开启 UDP 即可。“
> 
> 您好，谢谢回复。不过，我想问一下，我在安卓上的客户端的设置的地方在哪儿呢？麻烦告知我一下您说的需要在客户端的socks协议中开启udp即可，是在哪儿找到这个设置呢？

默认是已经开启的。
