### ISSUE TITLE
How to build v2rayNG apk from repository

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#599]
How to build v2rayNG apk from repository

Is there any document?

授人以鱼不如授人以渔，请大大指点一下。

**Comment by likky** [comment]
不需要搭建任何环境，如果你入门了Android studio安卓开发hello world，那么这个就那样编译生成APK。

**Comment by ghost** [comment]
没那么简单。 go需要单独编译

**Comment by likky** [comment]
go编译的libv2ray.aar直接用就行了，反正我是直接生成apk。

**Comment by SekiBetu** [comment]
用gradle编译即可，你甚至不用下载Android studio

**Comment by om2mo** [comment]
> go编译的libv2ray.aar直接用就行了，反正我是直接生成apk。

版本是最新的吗？

**Comment by superhero75** [comment]
The latest v2ray-core directory has changed to https://github.com/v2fly/v2ray-core. Also Golang version 1.15 is being used to build v2ray.
In order to build the latest 4.28.1 libv2ray.aar, within interact.go: 
v2core "v2ray.com/core"
 Do codes need to be modified?

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/issues/688
