### ISSUE TITLE
Pixel 3XL能ping出速度，但是app无法联网

### ISSUE THREAD

**Issue by brunofeng** [2dust/v2rayNG#60]
Pixel 3XL, Android 9
分应用代理，绕行模式
配置好了之后，测速正常，但是绕行之外的app都无法连网。
同样配置的Pixel 2一切正常，是什么问题呢
非常感谢

**Comment by 2dust** [comment]
--------- beginning of system
--------- beginning of main
08-13 07:35:26.139 I/GoLog   (21890): Preparing Domain: aaaaaaaaaaaaaa:21556
08-13 07:35:26.139 I/GoLog   (21890): file exists
08-13 07:35:26.139 I/GoLog   (21890): EnableLocalDNS: true
08-13 07:35:26.139 I/GoLog   (21890): ForwardIpv6: false
08-13 07:35:26.139 I/GoLog   (21890): DomainName: aaaaaaaaaaaaaa:21556
08-13 07:35:26.139 I/GoLog   (21890): loading v2ray config
08-13 07:35:26.139 I/GoLog   (21890): /data/user/0/com.v2ray.ang/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path --dnsgw 127.0.0.1:10807]
08-13 07:35:26.166 I/GoLog   (21890): EscortRun cmd.Start err fork/exec /data/user/0/com.v2ray.ang/tun2socks: no such file or directory
08-13 07:35:26.166 I/GoLog   (21890): EscortRun Exit
08-13 07:35:26.567 I/GoLog   (21890): new v2ray core
08-13 07:35:26.587 I/GoLog   (21890): start v2ray core
08-13 07:35:26.592 I/GoLog   (21890): [Warning] v2ray.com/core: V2Ray 4.20.0 started
08-13 07:35:26.680 D/com.v2ray.ang(21890): sendFd tries: 0
08-13 07:35:26.681 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:26.688 I/GoLog   (21890): Prepare Result:
08-13 07:35:26.688 I/GoLog   (21890):  Domain: aaaaaaaaaaaaaa
08-13 07:35:26.688 I/GoLog   (21890):  Port: 21556
08-13 07:35:26.688 I/GoLog   (21890):  IPs: [45.63.89.86]
08-13 07:35:26.782 D/com.v2ray.ang(21890): sendFd tries: 1
08-13 07:35:26.783 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:26.983 D/com.v2ray.ang(21890): sendFd tries: 2
08-13 07:35:26.987 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:27.388 D/com.v2ray.ang(21890): sendFd tries: 3
08-13 07:35:27.389 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:28.189 D/com.v2ray.ang(21890): sendFd tries: 4
08-13 07:35:28.207 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:29.314 I/GoLog   (21890): 127.0.0.1:39796 accepted //www.google.com:443  
08-13 07:35:29.609 I/GoLog   (21890): Using Prepared: 45.63.89.86
08-13 07:35:29.807 D/com.v2ray.ang(21890): sendFd tries: 5
08-13 07:35:29.809 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:30.256 I/GoLog   (21890): Using Prepared: 45.63.89.86
08-13 07:35:33.010 D/com.v2ray.ang(21890): sendFd tries: 6
08-13 07:35:33.011 D/com.v2ray.ang(21890): java.io.IOException: No such file or directory
08-13 07:35:42.247 E/com.v2ray.ang(21705): Invalid ID 0x00000000.
08-13 07:35:42.896 E/com.v2ray.ang(21705): Invalid ID 0x00000000.
08-13 07:36:31.836 D/com.v2ray.ang(21890): SCREEN_OFF, stop querying stats
08-13 07:36:52.387 D/com.v2ray.ang(21890): SCREEN_ON, start querying stats
08-13 07:38:15.407 I/GoLog   (21890): 127.0.0.1:39870 accepted //www.google.com:443  
08-13 07:38:15.862 I/GoLog   (21890): Using Prepared: 45.63.89.86

**Comment by brunofeng** [comment]
是系统备份的问题，关闭备份，重装软件就解决了
