### ISSUE TITLE
请求提供关闭udp以及远程dns的功能

### ISSUE THREAD

**Issue by kaller5000** [2dust/v2rayNG#600]
导出配置文件，发现入口socks的udp是默认开启的，希望能加入自主选择是否开启udp的选项，同时远程dns虽然写着“可选”，实际上无法关闭，希望提供相关选项

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/issues/332#issuecomment-703075531

**Comment by rurirei** [comment]
1. you cannot unreceive udp data in socks inbound, or you'll lose those udp connection
2. you cannot disable remote dns as intended in fact
