### ISSUE TITLE
speedtest测试速度受限

### ISSUE THREAD

**Issue by zjudongze** [2dust/v2rayNG#603]
### 实际行为
一.
1.手机mix2s开启 v2ray（设置选项：开启分应用代理（选中speedtest），开启速度显示，启用流量探测；域名策略：ipifnonmatch; 预定义规则：绕过局域网及大陆地址；启用本地DNS；下面v2ray开启的时候都是一样的设置）
2. 使用speedtest，选中国内测试节点，只能达到180Mbps（单线程/多线程都是这个速度）；

二.
1. 手机关闭v2ray
2. 使用speedtest，选中国内测试节点，只能达到500Mbps（家里宽带限速500mbps；单线程/多线程都是这个速度）；

三.
1. 手机开启v2ray
2. 使用speedtest，选中bwg dc9所在地区节点，只能达到140mbps左右；（之前的版本，具体哪个版本，无从查证了，可以达到400mbps）

四
1. 电脑开启v2ray
2.使用speedtest 测试dc9所在节点，可以400mbps

纯粹好奇，对于日常使用，影响不大。
从日志看，speedtest测试时，应该是绕过了节点
09-15 15:40:35.355 24012 24543 I GoLog   : Not Using Prepared: tcp,120.221.94.86:8080
09-15 15:40:35.355 24012 26261 I GoLog   : tcp:127.0.0.1:37598 accepted tcp:120.221.94.86:8080 [direct] 
09-15 15:40:35.356 24012 16121 I GoLog   : Not Using Prepared: tcp,120.221.94.86:8080
09-15 15:40:35.357 24012 26261 I GoLog   : tcp:127.0.0.1:37594 accepted tcp:120.221.94.86:8080 [direct] 
09-15 15:40:35.358 24012 24539 I GoLog   : Not Using Prepared: tcp,120.221.94.86:8080
09-15 15:40:35.358 24012 15224 I GoLog   : tcp:127.0.0.1:37604 accepted tcp:120.221.94.86:8080 [direct] 
09-15 15:40:35.358 24012 26261 I GoLog   : Not Using Prepared: tcp,120.221.94.86:8080
09-15 15:40:35.358 24012 24540 I GoLog   : Not Using Prepared: tcp,120.221.94.86:8080
09-15 15:40:35.359 24012 24541 I GoLog   : tcp:127.0.0.1:37602 accepted tcp:120.221.94.86:8080 [direct] 
09-15 15:40:35.359 24012 24541 I GoLog   : tcp:127.0.0.1:37600 accepted tcp:120.221.94.86:8080 [direct] 
09-15 15:40:35.470 24012 24541 I GoLog   : Not Using Prepared: udp,120.221.94.86:8080
09-15 15:40:35.472 24012 26261 I GoLog   : udp:127.0.0.1:44991 accepted udp:120.221.94.86:8080 [direct]

**Comment by yuhan6665** [comment]
I don't have environment to do this test. If you are interested, you can do the following tests. It will help us understand where is the bottle neck.
- keep everything else the same, try different security, "chacha20-poly1305", "aes-128-gcm"
- keep everything else the same, try proxy only mode
- keep everything else the same, try VLESS + xtls

**Comment by PPPss** [comment]
I have the same question.
