### ISSUE TITLE
Subscription features

### ISSUE THREAD

**Issue by nielspeen** [2dust/v2rayNG#605]
Any chance the following is (or will be) supported?

1. Adding subscription URL through a QR code. (Currently have to use copy&paste, which is less user-friendly.)
2. Allow for subscription to load custom configs. (For load-balancing configuration, which is not possible with current QR schemes.)

**Comment by yuhan6665** [comment]
1 is already supported. You can put the URL (http or https) in QR code.
For 2, you can provide the full Json in a URL link. Then user can import this custom config from menu

**Comment by nielspeen** [comment]
Thanks. 1 works great! Did not know that was possible. 2 is still a bit hassle for the user. Would be nice if the subscription list could accept something like https://xyx.com/abc.json links in addition to the current vmess://xyz links.
