### ISSUE TITLE
安卓10的无限retry修复

### ISSUE THREAD

**Issue by DametLiu** [2dust/v2rayNG#609]
1.在VpnService类中，高版本的kotlin有一个mInterface没有被初始化的异常，必须初始化为可空变量?
2.在setup函数中，以下代码
`try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                connectivity.requestNetwork(defaultNetworkRequest, defaultNetworkCallback)
                listeningForDefaultNetwork = true
            }
        } catch(e:Exception) {}`
必须用try catch包裹。因为这段代码会导致后续代码无法执行，也没有抛异常（顶层抓住了）。
这段代码就算是有问题，也不影响后续代码，否则得话，sendFd就会无限retry。这个逻辑应该可以优化。

**Comment by DametLiu** [comment]
我猜测他们报告得一部分vpn可以连接但没有网络得问题多半是因为这个，我在本地查看localsocket得文件，因为文件描述符被close，后续得establish没有赋值导致sendFd出现了bad 异常。所以文件是没有数据写入得。

**Comment by yuhan6665** [comment]
@DametLiu looks like I can't reproduce this issue. Can you post adb log?
You seems to have a good understanding of the problem. You are welcome to push a fix also :)

**Comment by DametLiu** [comment]
> @DametLiu looks like I can't reproduce this issue. Can you post adb log?
> You seems to have a good understanding of the problem. You are welcome to push a fix also :)

u can replace codes in V2RayVpnService.setup, i havent this project permission 

        // fix sometimes this code will throw an exception, then vpn cannot work correctly
        // the exception must catch here, else will get a bad file descriptor,
        // because after this code thrown, mInterface cannot get a new value, it's null
        // we'll get two kinds of logs
        // 1. Bad descriptor then sendFd retry 1234512345
        // 2. lateinit var mInterface not initialized and retry 1234512345
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                connectivity.requestNetwork(defaultNetworkRequest, defaultNetworkCallback)
                listeningForDefaultNetwork = true
            }
        } catch (e: Exception) {}

**Comment by yuhan6665** [comment]
@DametLiu, thanks for your suggestion. Though, I'm more interested in what is the original exception throw by requestNetwork(). Try catch is ok but we should understand the root cause.
