### ISSUE TITLE
建议添加xtls支持

### ISSUE THREAD

**Issue by jisoo109** [2dust/v2rayNG#614]
![Screenshot_20200922_160103_mh1600761701785](https://user-images.githubusercontent.com/36189114/93898188-82e6c300-fd25-11ea-8afd-9d440b75ccc8.jpg)

详细出处https://github.com/rprx/v2ray-vless/releases

**Comment by Fhokud** [comment]
顶

**Comment by RPRX** [comment]
https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80

XTLS 将会出现在 v2ray-core v4.29.0 中，v2rayN & v2rayNG 只需进行这两项修改：

1. VLESS 与 id 同级的新参数：流控(flow)，输入框，默认为空
2. “底层传输安全”增加 xtls 选项，对应 xtlsSettings，目前参数与 tlsSettings 完全相同
