### ISSUE TITLE
同样的设置为什么 Youtube 这些 APP 无法连接？

### ISSUE THREAD

**Issue by 5Dimen** [2dust/v2rayNG#615]
电脑上用的是 V2rayN，手机上用的是 V2rayNG。两边的配置都和自己架的 VPS 一模一样，用的是 Vmess+WS+TLS+nginx。

电脑上一切正常。手机是安卓10，用 Chrome 没问题。但是其他 APP 比如 Youtube, Goold Play, Ins 这些全部无法连接，显示没有联网。

请教下这是什么原因以及如何解决？

**Comment by muryliang** [comment]
I have exactly the same problem,  and solved by disable local dns and change remote dns from 8.8.8.8 to others like 8.8.4.4.  I dont't know why but it works. You may have a try.

**Comment by 5Dimen** [comment]
> I have exactly the same problem, and solved by disable local dns and change remote dns from 8.8.8.8 to others like 8.8.4.4. I dont't know why but it works. You may have a try.

It worked, thank you very much.
