### ISSUE TITLE
PC端连接正常，安卓端无网络连接

### ISSUE THREAD

**Issue by Tuskumo233** [2dust/v2rayNG#618]
## 预期行为
手机端v2rayNG正常连接到目标ip节点

### 实际行为
PC端启动连接正常，手机安卓端启动连接无网络连接
### 复现方法
手机端V2rayNg:
1.正常启动app，正常配置节点，（已确定本节点于电脑端V2rayNG正常使用无异常时间校准情况正常）
2.弹窗，“启动服务成功”下方栏“已连接，点击测试连接”
3.此时连接的wifi和数据流量情况为持续的10-20kb/s，实际为无任何网络连接
4.点击测试连接为“失败:"http://www.google.com/gen_204":io,read/wrtie on closed pipe”
5.测试Tcping为-1ms，
（wifi和数据流量情况相同）
### 日志信息
<details>
--------- beginning of system
--------- beginning of main
09-24 23:32:23.125 I/GoLog   (30121): [Warning] [1810382732] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > file file+net Socket: setnonblock: bad file descriptor v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:19Z is after 2020-01-30T09:08:51Z v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:20Z is after 2020-01-30T09
09-24 23:32:23.125 I/GoLog   (30121): :08:51Z v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:21Z is after 2020-01-30T09:08:51Z v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:22Z is after 2020-01-30T09:08:51Z] > v2ray.com/core/common/retry: all retry attempts failed
09-24 23:32:23.183 I/GoLog   (30121): tcp:127.0.0.1:39224 accepted tcp:111.30.178.75:80 [proxy] 
09-24 23:32:23.203 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.296 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.326 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.386 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.526 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.770 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.783 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:23.974 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.214 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.291 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.491 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.492 I/GoLog   (30121): 127.0.0.1:49255 accepted udp:1.1.1.1:53 [dns-out] 
09-24 23:32:24.499 I/GoLog   (30121): 127.0.0.1:38170 accepted udp:1.1.1.1:53 [dns-out] 
09-24 23:32:24.511 I/GoLog   (30121): 127.0.0.1:46126 accepted udp:1.1.1.1:53 [dns-out] 
09-24 23:32:24.631 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.691 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.733 I/GoLog   (30121): Using Prepared: 18.179.206.22
09-24 23:32:24.810 I/GoLog   (30121): [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:16Z is after 2020-01-30T09:08:51Z v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:19Z is after 2020-01-30T09:08:51Z v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or is not yet valid: current t
09-24 23:32:24.811 I/GoLog   (30121): ime 2020-09-24T15:32:22Z is after 2020-01-30T09:08:51Z v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://v2-jp1.acgab.org:11133/RUtkAN3P/):  > x509: certificate has expired or 
```
</details>

### 环境信息
红米k30 speed
Android 10 
MIUI 12.0.5.0
补充:V2rayNG版本为1.3.3

**Comment by LaplasAlter** [comment]
同。我手机是华为p30，昨天开始就连不上了

**Comment by yuhan6665** [comment]
x509: certificate has expired or is not yet valid: current time 2020-09-24T15:32:19Z is after 2020-01-30T09:08:51Z.
Your server need to fix the certificate.
If you can't fix you can try allow insecure at the moment.

**Comment by two4mamba** [comment]
同样 的问题

**Comment by Sopiha** [comment]
换了新的网站也要邀请码啊

**Comment by Zihaoxm** [comment]
我也是一样的问题一样的复现方法，服务器在电脑端正常，并且在荣耀20上使用节点也是正常的，但是另一台安卓设备（LG G
6）就无法使用

**Comment by zxfandyy** [comment]
我也遇到类似的问题，同样的节点，PC、iOS都可以正常连接，但是v2rayNG却无法连接，延迟测试-1ms

**Comment by hannaiqigxn** [comment]
一样，我是红米pro8

**Comment by zxfandyy** [comment]
我的问题解决了，因为手机时间不准导致，你们查下手机时间有没有打开自动对时

**Comment by ma1li** [comment]
pc和手机都无法连接是什么原因呢
