### ISSUE TITLE
分应用代理能否移至profile

### ISSUE THREAD

**Issue by evopen** [2dust/v2rayNG#62]
每个profile可能有不同的分应用代理设置，不同的代理地域对网络内容的监管也是不同的。

而且分应用代理还可以用来穿透内网，当在内网的时候要使用全局代理，外网则具体情况具体分析。

所以逻辑上分应用代理应该是一个profile属性，而不是全局属性。

谢谢

**Comment by uoox** [comment]
我认为反倒全局属性好一点，也许可以在每个profile里面提供一个自定义分应用代理/使用全局设置的开关，来满足需求，而不是一棍子分开，不然每导入一个节点就要设置一次分应用规则。

**Comment by cpdyj** [comment]
赞同，只开telegram时不想挂chrome，每次都得去列表改…
