### ISSUE TITLE
更新后自动订阅不好使了

### ISSUE THREAD

**Issue by ltl7826354** [2dust/v2rayNG#623]
v2rayng软件更新后https://flashlight.network的订阅更新不好使了，新的订阅地址在哪，怎么查询还有多久的使用期限

**Comment by haha125** [comment]
解决了吗大佬

**Comment by xietao1233** [comment]
某次使用时, 突然订阅链接丢失了, 再添加订阅链接也是更新失败, 无奈只能先用着clash for android, 就是耗电量大了点
