### ISSUE TITLE
网速显示不一致

### ISSUE THREAD

**Issue by selcarpa** [2dust/v2rayNG#624]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
使用软件的时候网速显示一致

### 实际行为
任务栏的网速与梯子的网速不一致，大约是实际网速的三倍左右，不知道是MIUI的网速显示有问题，还是怎么回事
![XM7 {TVF UZFC` DZVKS5}Y](https://user-images.githubusercontent.com/25505798/94361547-a32cce00-00e7-11eb-8632-6b3ac4be06cf.jpg)

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
MIUI12，Android9.0
### 额外信息（可选）
后台并无其他太过影响这个结果的程序正在运行

**Comment by 1265578519** [comment]
这好像是miui12的bug，我提交过给miui了，以前miui11正常

**Comment by lss4** [comment]
I'm currently on Havoc 3.8 GSI and it exhibits similar behavior.

It seems the method v2ray uses to count the data rate is different from the one used by the system, as this difference in data rate has been observed since day one (regardless of the ROM or GSI I'm using). However, it appears the rate displayed by v2rayNG is the correct one.

**Comment by NekoCompiler** [comment]
我来和你解释一下吧，v2ray会把数据经过加密然后传输，加密过的数据往往比加密前的偏大。
还有不止miui有这个“问题”，vivo手机也是一样的。
数据走vpn时，尚不知系统如何定义网速，总是比实际网速大的。

**Comment by selcarpa** [comment]
> 我来和你解释一下吧，v2ray会把数据经过加密然后传输，加密过的数据经常比加密前的偏大。
> 还有不止miui有这个“问题”，vivo手机也是一样的。
> 数据走vpn时，尚不知系统如何定义网速，总是比实际网速大的。

不是这回事，实际上在之前的版本中是正常的，目前的版本显示的网络带宽基本是实际带宽的三倍，而且超过我在运营商办理的实际带宽，应该是软件在内部又从网络统计那块走了几次，这个确实是问题，你可以参考Iss4的回复，这个问题在更早之前并不存在。

**Comment by lss4** [comment]
Edited the previous comment as I might have not explained it accurately back then.

This difference in data has always been there regardless of ROM or GSI. I was surprised to see some stock ROMs were able to report accurate data rate even behind an active VPN.

Actually v2ray counts the actual (unencrypted) data rate which is the correct value. You can compare this value with apps that are receiving the data.

The data rate reported by the system is wrong. One needs to check the amount of data transmitted at server side to see if the difference is indeed the encryption overhead, or that Android is simply not able to report an accurate data rate when VPN is involved (that it's counting something that doesn't need to be counted).

**Comment by selcarpa** [comment]
> Edited the previous comment as I might have not explained it accurately back then.
> 
> This difference in data has always been there regardless of ROM or GSI. I was surprised to see some stock ROMs were able to report accurate data rate even behind an active VPN.
> 
> Actually v2ray counts the actual (unencrypted) data rate which is the correct value. You can compare this value with apps that are receiving the data.
> 
> The data rate reported by the system is wrong. One needs to check the amount of data transmitted at server side to see if the difference is indeed the encryption overhead, or that Android is simply not able to report an accurate data rate when VPN is involved (that it's counting something that doesn't need to be counted).

但更奇怪的问题是，这个显示的带宽超过了我的实际带宽，我目前用的是websocket那一套，数据传输量会大一些，但是大了三倍，这确实有点奇怪。
另外，我是直接从play store上面那个版本升级到目前的版本，在play上面的那个版本不存在这个问题，显示的带宽大小符合预期。

**Comment by 1265578519** [comment]
https://www.xiaomi.cn/post/21678216
在miui上已经反映过了的，等待miui12官方更新修复就行了
MIUI12.0.8开始出现的问题，MIUI12.0.2没有这个现象

可以很明显的看到是系统BUG
![image](https://user-images.githubusercontent.com/6442439/94548627-95ac4b00-0283-11eb-870c-847bfaa7c655.png)

**Comment by 1265578519** [comment]
> 目前已有小伙伴反馈了该问题，也进行了提案。这边帮您归纳一下。可以留意后续优化的版本哈～

官方人员回复，说明了已经确认了miui12有这个问题，已经提案归纳了，等待后续miui12更新就行了

**Comment by nukemiko** [comment]
我用华为的时候也是这种情况，系统统计的网速总是比v2rayNG显示网速大2-3倍

**Comment by github-office** [comment]
2022年07月17日报告，miui13 开发版依然是3倍网速。

**Comment by 1265578519** [comment]
> 2022年07月17日报告，miui13 开发版依然是3倍网速。

miui12开始增加的BUG，要联系miui系统负责人去修复

**Comment by 1265578519** [comment]
今天有幸见到小米开发人员，经过一番交流后，，，说这个miui12开始的流量显示问题后续也不会修复
是指启用了游戏加速器之类，导致的任务栏流量统计叠加显示，实际上跑100KB/s网速，却统计成2MB/s
小米开发人员说是安卓底层的问题，，，他们修复不了，但是也没见miui11的时候有问题，其它手机厂商也没这个问题。

**Comment by JZSTAR01** [comment]
miui13也有这个问题，不修就算了

**Comment by ghost** [comment]
> 

问题是现实的三倍网速，我一个月20G的流量岂不是只能当7个G使用吗😰

**Comment by ZerOri** [comment]
MIUI14依然如此，我还以为是小米的流量显示用的单位有什么不一样

**Comment by psychoever** [comment]
oppo系统，用的clash，也有这个问题，状态栏网速显示是三倍于clash的网速

**Comment by hn-kitty** [comment]
数据从服务器到手机 手机再传给代理软件的虚拟网卡 代理软件的虚拟网卡再传给应用，这不就是3倍么
理论上所有手机都有这个现象，除非不统计虚拟网卡

**Comment by lss4** [comment]
> 数据从服务器到手机 手机再传给代理软件的虚拟网卡 代理软件的虚拟网卡再传给应用，这不就是3倍么 理论上所有手机都有这个现象，除非不统计虚拟网卡

I think your speculation is correct. IIRC the traffic monitor was indeed reporting about 3x the actual rate back then.

On the other hand, on my current device, Edge 20 Pro with crDroid 10.2 (Android 14), the ROM's built-in traffic monitor is reporting the actual traffic correctly, matching the values shown on the v2flyNG notification.

So yes, the issue depends on how the traffic monitor works. If the traffic monitor you're using, be it ROM's built-in, or a third-party app, is also counting the traffic in virtual adapters, then you will have this issue with the monitor in question reporting 3x the actual rate.

**Comment by ZerOri** [comment]
> 数据从服务器到手机 手机再传给代理软件的虚拟网卡 代理软件的虚拟网卡再传给应用，这不就是3倍么
> 理论上所有手机都有这个现象，除非不统计虚拟网卡

以前还以为是miui的问题，原来大家都一样啊😂
