### ISSUE TITLE
Need help on using v2rayNG for ad-blocking.

### ISSUE THREAD

**Issue by lss4** [2dust/v2rayNG#627]
For now I've been using AdAway for blocking ads in a rooted environment. However, I'm about to use it on a device that I don't intend to root for the time being, and it doesn't appear to be practically possible to use a non-root adblocker alongside v2ray (since they all utilize the VPN interface and only one can be active at a time).

Actually v2ray can be configured to block certain ad domains, and in v2rayNG there seems to be a "Custom Rules" section for this purpose, so if possible to configure and maintain this, there would be no need to use a separate ad blocker.

~~However, it appears I need to either manually add/remove stuffs to the list, or scan a QR code to import/append. Can anyone explain the format of QR code the "Custom Rules" section expects so one can import/update rules list easily?~~

EDIT: After some initial analysis of the code and some experiments it seems to just accept IPs/domains separated by commas. Not sure if regexps (that some ad blocking tools utilize) would work.

Also, I've confirmed that you can just get a hosts file, taking just the domains and separate them with commas, then convert the contents using `qrencode` and scan it.

EDIT 2: Unfortunately the scan part is not practical. The information a QR code can hold is very limited, while a hosts file usually carries hundreds of kilobytes of information. I used the ad blocking list from [here](https://github.com/jerryn70/GoodbyeAds) and after some processing (to filter out other stuffs so it'll only contain the domains and commas), it's still about 3.5MB large.

EDIT 3: Not sure if this can be made possible using [this project](https://github.com/Loyalsoldier/v2ray-rules-dat). Using that would make it possible to configure v2ray to block anything matching ad-related `geosite` tags. Not sure if the same can be done on v2rayNG.

EDIT 4: It seems `geosite:category-ads-all` can be accepted in the "Blocked URL or IP" section. However, this needs further testing as my phone currently uses AdAway and it may affect test results.

EDIT 5: I think I cannot provide an accurate result regarding whether this works or not here, as actually, I've configured ad domain blocking on the server side as well. (NOTE: 233's v2ray script can generate such configs that include a very long list of blocked domains, though I haven't really updated that list since initial configuration, and recently just included the `geosite:category-ads-all` to make use of the data file as well).

**Comment by alcatraz-zz** [comment]
Did you find a way to do it?

I'm in the same situation. Use v2rayng to simulate host file adblocking.

geosite:category-ads-all

in the block page does very very little. How can we generate a proper block list from the official adblock hosts files?

**Comment by lss4** [comment]
Sorry but I never really cared about it afterwards.

My phone is rooted and I'm currently using AdAway to manage Hosts file.

It works, though it kinda caused some sites to break due to the blocking of certain domains. The broken sites are not important for my phone usage, however.
