### ISSUE TITLE
建议增加开机自启动功能

### ISSUE THREAD

**Issue by nukemiko** [2dust/v2rayNG#628]
### 预期行为
开机时v2rayNG能够自动建立连接
### 实际情况
经过在MIUI11和Android-x86上的测试，
不会开机自启，v2rayNG设置中没有控制开机自启动的选项，即便在系统设置里允许v2rayNG自启动也没有用
隔壁的SSR可以设置开机自启，希望v2rayNG能够尽早加入这一功能。

**Comment by lss4** [comment]
Android at some point supported Always-on VPN which can achieve this purpose, and v2rayNG supports it.

If not, you may need to rely on tools like Tasker. I asked a similar question a long time ago and the author pointed me to that, but in the end I used Always-on VPN.

**Comment by SekiBetu** [comment]
下拉控制中心点一下V2rayNG的图标就能开启，不太需要开机启动

**Comment by zhou8899** [comment]
希望增加开机自启动并自动链接预设节点,

**Comment by 238Ver** [comment]
是的，目前来看该功能还没有实现，我是红米手机，安卓12,还是不可以的 :(
