### ISSUE TITLE
希望能在锁屏界面隐藏通知

### ISSUE THREAD

**Issue by Leo-Z-Li** [2dust/v2rayNG#63]
想像ssrr那一样，解锁后通知栏有显示状态和网速，锁屏上没有。但发现在设置里打开通知设置以后，没有单项可以设置，只有v2Ray background service。

**Comment by aorosora** [comment]
V2RayNG，通知，v2Ray background service，在锁定屏幕上，完全不显示通知。
你系统要是被魔改了的话那就另说
