### ISSUE TITLE
最新版1.4.2服务端要求应该是vless preview2.1而不是4.29.0

### ISSUE THREAD

**Issue by xianren78** [2dust/v2rayNG#631]
最新源码vless有一个breaking udp改动，所以用4.29.0会导致dns解析失败，需要改用下面这个服务端。

https://github.com/charlieethan/vless-build/releases

**Comment by yuhan6665** [comment]
Wait for v2fly 4.30.0

**Comment by xianren78** [comment]
> Wait for v2fly 4.30.0

 2dust released this 3 hours ago

请注意:升级到此版本需同时升级服务端版本至v4.29.0

https://github.com/v2fly/v2ray-core/releases/tag/v4.29.0

主要是发布说明有错误

**Comment by yuhan6665** [comment]
You are talking about https://github.com/v2fly/v2ray-core/pull/239 right?
v2rayNG 1.4.2 has core version 4.29.0 which doesn't contain this change. Once 4.30.0 is released we will have new version as well.

**Comment by xianren78** [comment]
> You are talking about [v2fly/v2ray-core#239](https://github.com/v2fly/v2ray-core/pull/239) right?
> v2rayNG 1.4.2 has core version 4.29.0 which doesn't contain this change. Once 4.30.0 is released we will have new version as well.

不，实际上今天编译的这个版本已经含有#239了。在#v2fly tg群已经确认了，只能升级到preview2.1才能正常使用vless udp功能

[图片查看](https://i.niupic.com/images/2020/09/30/8KNb.jpg)

**Comment by yuhan6665** [comment]
Ok, looks like you are right. @2dust maybe we should hide this release for now or edit the release message to say it is only compatible with latest VLESS

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.4.3
