### ISSUE TITLE
v2rayNG 1.4.3 启动服务失败

### ISSUE THREAD

**Issue by RPRX** [2dust/v2rayNG#634]
1.4.2 不小心编译了 VLESS PREVIEW 2.1，而 1.4.3 经 TG 群友反馈，普遍存在启动服务失败的问题

~覆盖安装会启动失败，有的用户卸载重装后可以解决问题~

PS：1.4.2 不存在此问题，也可以等明天的 v2ray-core v4.30.0

**Comment by RPRX** [comment]
已确认问题由 geosite 和 geoip 引起，和是否卸载重装无关

**Comment by RPRX** [comment]
（个人建议跳过 v4.29.0，等明天的 v4.30.0）

**Comment by IceCodeNew** [comment]
这个问题挺烦的，前面几个版本都支持的 category-dev/media/anticensorship 分类，升级以后突然又不能用了，感觉就好像是虽然发布新版，但是却用了比旧版更老，老到不知道什么时候的 assets 一样。
这种不协调搞得无论是用自定义配置还是普通节点都会遇到因为找不到对应域名分类无法启动内核的问题。

到现在发布的时候包含在 apk 里的域名数据都没有一个明确的更新机制（之前在 [另一个问题](https://github.com/2dust/v2rayNG/issues/527#issuecomment-669656010) 里询问过作者，没有得到回应
希望能早日解决。
