### ISSUE TITLE
IOException: localSocket connection refused

### ISSUE THREAD

**Issue by rurirei** [2dust/v2rayNG#636]
EDIT: removed

**Comment by rurirei** [comment]
moved https://github.com/2dust/v2rayNG/pull/635/commits/e2d667e0bb4d3190a0c8cd213cd0c1210841b7e0

**Comment by rurirei** [comment]
@yuhan6665 error will always met even if there is a available network connection (v2rayNG works good), seems it is not relavant to https://github.com/2dust/v2rayNG/pull/635#pullrequestreview-501540965 . tested on android 10 and 11
```
W/System.err: java.io.IOException: Connection refused
W/System.err:     at android.net.LocalSocketImpl.connectLocal(Native Method)
W/System.err:     at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
W/System.err:     at android.net.LocalSocket.connect(LocalSocket.java:147)
```
https://github.com/2dust/v2rayNG/blob/45805d6df7d9da41b06d465be0c694671348397e/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L187

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/pull/645/commits/eb3d79179b0895692de2d5a210b1e09958075368

**Comment by coderhe** [comment]
hello，I met the same problem. It's about IOException: localSocket connection refused. I wanna know how do you solve it. Thx.

**Comment by rurirei** [comment]
@coderhe the issue was fixed for a long while. it's error of your code maybe.

**Comment by rurirei** [comment]
@coderhe see https://github.com/2dust/v2rayNG/commits?author=rurirei

**Comment by coderhe** [comment]
@rurirei  I got it. Thx!
