### ISSUE TITLE
Google Play中可以访问app内容页面，但是无法下载和更新

### ISSUE THREAD

**Issue by wind23** [2dust/v2rayNG#637]
Google Play中可以访问app内容页面，但是无法下载和更新，更新app时一直停留在“正在等待下载”的状态
无论是否勾选分应用代理，均无效

下载管理器里面一直处在“等待网络”的状态

![pic1](https://user-images.githubusercontent.com/5688695/94797558-e2725c00-0412-11eb-9cfa-ceb72dbd35fe.jpg)

![pic2](https://user-images.githubusercontent.com/5688695/94797565-e43c1f80-0412-11eb-91e1-9ba933224d28.jpg)

**Comment by akiirui** [comment]
Fixed in https://github.com/2dust/v2rayNG/pull/584, try 1.4.0 and later.

**Comment by fei5seven** [comment]
这波啊，这波可能是换手机or刷机警告。我之前的索尼就是，刷机完前几天能正常，后面就永远的等待下载（然后我就头疼的换了手机）。可能和软件没关系。当然如果是app的问题那是最好的，，，最好的。。。

**Comment by akiirui** [comment]
> 这波啊，这波可能是换手机or刷机警告。我之前的索尼就是，刷机完前几天能正常，后面就永远的等待下载（然后我就头疼的换了手机）。可能和软件没关系。当然如果是app的问题那是最好的，，，最好的。。。

v2rayNG upgrade to API 29 (Android 10) in 1.3.2 and later.

In API 29, Android mark VPN as metered connection by default.

**Comment by yuhan6665** [comment]
#520

**Comment by wind23** [comment]
> Fixed in #584, try 1.4.0 and later.

Problem solved by updating the version of v2rayNG

**Comment by yooofei** [comment]
打开应用管理，清除“google服务框架”和“google play服务”这两个应用数据，重新登录google账户后，再次打开google play store就可以正常下载更新了

**Comment by nztraveler** [comment]
我用了这个方法解决了问题
https://github.com/2dust/v2rayNG/issues/336#issuecomment-665394594
