### ISSUE TITLE
there is 

### ISSUE THREAD

**Issue by crmmc** [2dust/v2rayNG#639]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
因为服务端更新了4.30版本，vless协议更新了，协议udp部分改了，用的1.4.4版本的V2rayNG不能使用vless协议。因为协议更新是修复了一个vless协议的udp传输的bug，所以希望作者跟进更新一下吧。
### 实际行为
描述实际发生了什么
确认服务端4.30版本，客户端1.4.4版本vless协议不能正常使用了
### 复现方法
1.服务端更新最新版4.30，使用vless+ws配置服务
2.客户端更新1.4.4版本，配置服务连接，测试谷歌链接正常，但是实际连接后无法使用。
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by RPRX** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.4.5

**Comment by crmmc** [comment]
Thank you for your contribution. After updating the v2ray-core version, the latest version of the vless protocol can be used normally.
