### ISSUE TITLE
开机自启动功能

### ISSUE THREAD

**Issue by uoox** [2dust/v2rayNG#64]
希望有这个，另外也希望能加入acl规则，还有就是geo全家桶默认不代理谷歌翻译，gstatic等，这些最近似乎被墙了

**Comment by 2dust** [comment]
开机功能请用tasker
其他的功能不保证增加

**Comment by fcying** [comment]
tasker 启动后是前台打开, 而且默认是没启用状态, 在电视上用有点麻烦.

**Comment by yflwz** [comment]
这个开机自动连接的功能是很实用的，并不单单是说用上电视上，手机上其实也是，很期待。
