### ISSUE TITLE
v2fly core instead of v2ray.com/core

### ISSUE THREAD

**Issue by superhero75** [2dust/v2rayNG#640]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
FIle:
v2rayNG/AndroidLibV2rayLite/interact.go 
 
Code:
	v2core "v2ray.com/core"
	v2filesystem "v2ray.com/core/common/platform/filesystem"
	v2stats "v2ray.com/core/features/stats"
	v2serial "v2ray.com/core/infra/conf/serial"
	_ "v2ray.com/core/main/distro/all"
	v2internet "v2ray.com/core/transport/internet"

	v2applog "v2ray.com/core/app/log"
	v2commlog "v2ray.com/core/common/log"

does the source 'v2ray.com/core' need to be changed to 'github.com/v2fly/v2ray-core'?

### 预期行为
描述你认为应该发生什么
trying to build latest 4.30 libv2ray.aar
### 实际行为
描述实际发生了什么
old version of libv2ray.aar has been built
### 复现方法
1. 
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
ubuntu

**Comment by rurirei** [comment]
you should not change those package name.

look for gomobile docs yourself.
