### ISSUE TITLE
我的笔记本可以用v2N连上打开油管  但台式启动了代理却连不上网。

### ISSUE THREAD

**Issue by DemianEmier** [2dust/v2rayNG#642]
求帮助，手机和笔记本也能连上。但台式不知道为什么连不上
。

**Comment by Zerxoi** [comment]
看看是不是台式机时间没有校准

**Comment by DemianEmier** [comment]
> 看看是不是台式机时间没有校准

台式时间是校准了的，还怀疑是app版本问题，专门复制了笔记本上的V2N过来，结果还是只有台式连不上。

**Comment by crmmc** [comment]
V2rayNG是安卓版本的v2ray代理软件，请问您的台式机是安卓系统吗？跑错地方了吧
v2rayN连接不上，可能是：
时间错误，忘记切换代理模式（开启全局试一下），配置文件错误（检查一下配置文件）

**Comment by DemianEmier** [comment]
> 的v2ray代理软件，请问您的台式机是安卓系统吗？跑错地方了吧
> v2rayN连接不上，可能是：

额，我是在酸酸乳用户中心看到的V2rayN的windows版本，笔记本就下载了那个软件能连上（当然我对这个软件确实不够了解，通过手机版反馈找到论坛的）0.0
