### ISSUE TITLE
一个建议：在使用4.30.0及以上版本v2ray-core的v2rayNG上加入trojan协议配置文件支持

### ISSUE THREAD

**Issue by crmmc** [2dust/v2rayNG#643]
能否加入基于v2ray-core 4.30.0的Trojan配置文件支持呢？
v2ray-core在更新了4.30.0版本后就原生支持了trojan协议，可以用v2ray来搭建trojan服务，当然也可以用v2ray-core来连接trojan服务。而trojan的官方安卓客户端比较难用，如果v2rayNG加入trojan配置文件支持，那就能让trojan用户也用上好用的v2rayNG了!
v2ray-core的4.30.0版本内置支持trojan，而且trojan本身的客户端配置参数就很少，因此希望作者考虑一下这个请求。
谢谢

**Comment by rurirei** [comment]
custom config please.

**Comment by crmmc** [comment]
Thank you for providing a solution, but adding graphical parameters can let others know that "v2rayNG can also connect to trojan. I can use the more efficient v2rayNG instead of the less efficient igniter. Sincerely hope you can consider it. Thank you

**Comment by meymself** [comment]
clashfa不香吗

**Comment by 2dust** [comment]
请把可用的配置信息发email给我们

**Comment by crmmc** [comment]
妙！最新版的V2rayNG已经加入了完美的Trojan配置文件支持，谢谢所有开发者的付出！
