### ISSUE TITLE
Custom configurations don't work properly.

### ISSUE THREAD

**Issue by DanyTPG** [2dust/v2rayNG#646]
The config file below works perfectly fine in kitsunebi app but in v2rayNG it only works with the socks tunnel (device full tunnel doesn't work.)
Even the testing option in v2rayNG returns success with around 500ms ping.

So I guess this is just a misconfiguration in the app ?
```

{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "proxy",
      "port": 10808,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "auth": "noauth",
        "udp": true,
        "ip": null,
        "address": null,
        "clients": null,
        "decryption": null
      },
      "streamSettings": null
    }
  ],
  "outbounds": [
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "a.b.c",
            "method": "aes-256-gcm",
            "ota": false,
            "password": "****",
            "port": 443
          }
        ]
      },
      "proxySettings": {
        "tag": "transit"
      }
    },
    {
      "protocol": "shadowsocks",
      "settings": {
        "servers": [
          {
            "address": "b.c.d",
            "method": "aes-256-gcm",
            "ota": false,
            "password": "****",
            "port": 443
          }
        ]
      },
      "tag": "transit"
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:category-ads"
        ],
        "outboundTag": "blocked"
      }
    ]
  },
  "dns": {
    "servers": [
      "176.103.130.130",
      "1.1.1.1",
      "8.8.8.8",
      "localhost"
    ]
  },
  "policy": null
}
```

**Comment by rurirei** [comment]
>> The config file below works perfectly fine in kitsunebi app

configuration is ok.

>> but in v2rayNG it only works with the socks tunnel (device full tunnel doesn't work.)

what tunnel, details needed.

>> Even the testing option in v2rayNG returns success with around 500ms ping.

do you know `adb logcat`?

**Comment by rurirei** [comment]
it should work.. https://github.com/2dust/v2rayNG/blob/45805d6df7d9da41b06d465be0c694671348397e/AndroidLibV2rayLite/CoreI/Status.go#L33

**Comment by DanyTPG** [comment]
> what tunnel, details needed.

When you enable v2rayNG with the **V** button in the bottom right of the app, v2ray core will start working and all of the android apps traffic will pass through v2rayNG right? 
Well no not with this custom config. I can only use it with the socks proxy that it provides. for example in telegram I have to make a socks proxy 127.0.0.1:10808 and that's the only way I can connect to internet using v2rayNG. non of the apps that don't have proxy support can connect to the internet.

> do you know `adb logcat`?

I worked with it a long time ago

**Comment by rurirei** [comment]
weird, it should work. do you know `adb logcat`, we need logs?

**Comment by DanyTPG** [comment]
yes I can get logs for you.

**Comment by DanyTPG** [comment]
[logcat.txt](https://github.com/2dust/v2rayNG/files/5342374/logcat.txt)
I enabled v2rayNG at 20:19 and then tried some apps which none of them worked (chrome twitter instagram)

**Comment by rurirei** [comment]
do not use https://kb.adguard.com/en/general/dns-providers port-5443 dns at v2rayng app `remote dns`, input 8.8.8.8 and try again.

**Comment by DanyTPG** [comment]
it made no difference.
and yes its probably DNS settings problem (in v2rayNG). I am getting DNS_PROBE_FINISHED_NO_INTERNET error in chrome.

**Comment by DanyTPG** [comment]
> do not use https://kb.adguard.com/en/general/dns-providers port-5443 dns at v2rayng app `remote dns`, input 8.8.8.8 and try again.

Also Adguard DNS works perfectly fine with non-costum v2ray configs.

**Comment by rurirei** [comment]
> > do not use https://kb.adguard.com/en/general/dns-providers port-5443 dns at v2rayng app `remote dns`, input 8.8.8.8 and try again.
> 
> Also Adguard DNS works perfectly fine with non-costum v2ray configs.

do not use non-port-53 dns as remote dns, even you find it work, but it did not work in fact.

**Comment by rurirei** [comment]
> it made no difference.
> and yes its probably DNS settings problem (in v2rayNG). I am getting DNS_PROBE_FINISHED_NO_INTERNET error in chrome.

logs needed with 8.8.8.8

**Comment by DanyTPG** [comment]
> do not use non-port-53 dns as remote dns, even you find it work, but it did not work in fact.

I was using default port 53 adguard dns `176.103.130.130` and I did confirm with dns leak tests that it was working.



> logs needed with 8.8.8.8

log attached. enabled v2rayNG at 01:01
[logcat.txt](https://github.com/2dust/v2rayNG/files/5343969/logcat.txt)

**Comment by rurirei** [comment]
ok if dns server support port 53.

i have no idea. ask help for @2dust

**Comment by yuhan6665** [comment]
maybe your server is not accepting udp traffic.
BTW, you probably want to remove the existing attachments as the log exposed your server address. Set log level to debug and hide your ip and domain next time.
