### ISSUE TITLE
if add DoT DNS support

### ISSUE THREAD

**Issue by rurirei** [2dust/v2rayNG#647]
i'm interested, and too many issues opens here in questions about advanced DNS: non-standard remote dns, and Dns over TLS. the first is impossible (ask Android), the second could be done (with localDNS prepared), but makes less sense. ~~if youre willing, i'll write a commit to.~~ it is part of user interface, needs be done by @2dust  ~~though this intent maybe much complicated of your users?..~~ just warn user to differ from ip and DoT uri

**Comment by yuhan6665** [comment]
@rurirei is there a way to contact you (email or tg)(my tg is Yuhan6665), want to discuss about making future v2rayNG

**Comment by rurirei** [comment]
@yuhan6665 if i could be.. callmerurirei@protonmail.com

**Comment by rurirei** [comment]
DoT could be used already in localDNS mode and specify remote-dns or domestic-dns settings to like `https://dns.google/dns-query` https://github.com/2dust/v2rayNG/blob/45805d6df7d9da41b06d465be0c694671348397e/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L503-L519

**Comment by rurirei** [comment]
no, there are  something leave to do. https://github.com/rurirei/v2rayNG/commits/dns

**Comment by rurirei** [comment]
https://github.com/rurirei/v2rayNG/commit/620a8b8

**Comment by rurirei** [comment]
> @rurirei is there a way to contact you (email or tg)(my tg is Yuhan6665), want to discuss about making future v2rayNG

i'd told my email address, check your github notification mail please.

**Comment by yuhan6665** [comment]
> > @rurirei is there a way to contact you (email or tg)(my tg is Yuhan6665), want to discuss about making future v2rayNG
> 
> i'd told my email address, check your github notification mail please.

Sorry for the late reply, 2dust should contact you directly

**Comment by rurirei** [comment]
not easy to do this for setings UI. closed.

manual https://github.com/rurirei/Kitsunebi/issues/6
