### ISSUE TITLE
“flow”项也应为可填写选项

### ISSUE THREAD

**Issue by simpleandstupid** [2dust/v2rayNG#648]
### 预期行为
“flow”项可输入

### 实际行为
仅可选择

### 复现方法
1.手动输入［VLESS］
### 额外信息（可选）
据v2fly文档：https://www.v2fly.org/config/protocols/vless.html#%E6%96%B0%E5%9E%8B%E5%8D%8F%E8%AE%AE%E5%9B%9E%E8%90%BD%E6%A8%A1%E5%BC%8F%E8%A7%A3%E6%9E%90
中客户端指引3
encryption 应做成输入框而不是选择框，新配置的默认值应为 none，若用户置空则应代填 none。flow 也应做成输入框，新配置的默认值应为空

**Comment by onlyJinx** [comment]
Flow这一项如果不选(留空)的话好像会让app v1.4.6崩溃
![20201007_003451](https://user-images.githubusercontent.com/21324835/95230957-214e4a80-0835-11eb-98f3-fa26e350df0c.jpg)
