### ISSUE TITLE
ss协议能不能也从ws+tls走？

### ISSUE THREAD

**Issue by mo-han** [2dust/v2rayNG#65]
看v2ray官网资料感觉是可行的？
隔壁kitsunebi也支持这样设置？
咱也弄一个呗？
我猜vmess已经实现的代码稍微改改就成？

**Comment by 2dust** [comment]
你可以用自定义配置
也可以继续用kit
ng的设计是简单实用,不提供这种比较奇怪的配置用法

**Comment by mo-han** [comment]
你不想改就直说，这是你的自由。
阴阳怪气也是你的自由。
偏偏要把别人的需求贴上“奇怪”这样的标签，从而给自己寻找合理性，这就是此地无银。

硬要说奇怪的话，你才是奇怪。
你的默认配置里先是false了早就被弃用的`reuseConnection`选项，然后又默认开启了mux，还不给提示和开关。官网上明确注明了mux会严重影响性能，实际使用经验也支持官网上这一结论。
你这种莫名其妙的配置才是真正的“奇怪”，然而有谁说你不好听的了吗？没有，大家给予你宽容和谅解。
你又是用怎样的心态来回报这个社区的？

NG目前是最好的v2ray安卓端应用，但不是因为NG完美无缺，而是同行衬托，前有BifrostV那恶心人的广告，后有kitsunebi的尚不完善。
但kitsunebi的进步神速，而且kitsunebi增加了诸多选项开关的同时并没有变得复杂，因为它知道如何安排选项的层级合理布局，而且不厌其烦地给所有选项加上了通俗且详细的说明。我个人压根不需要这些说明，但是很多用户在它的评论中都表达了对其的赞许和认可。你看，复杂并不与易用相矛盾，多样化也不应该用一个“奇怪”来敷衍。
觉得少见就是“奇怪”？怕不是某人能力有限？哦不行，这么说太伤人了，混gayhub的十有八九是玻璃心对吧？换个切入点：怕不是某人想象力不足~

你别辩驳什么“我不是我没有”，你要真不是怀着我所描述的心态的话，怎么会回复上面三句话的？
针对你“善意”的建议，我也给个回礼：要不你别搞这个项目了，反正如果追求“简单”的话，NG已经够简单了不是嘛？细数所有平台，还有哪个客户端有你的NG简单吗？（笑

**Comment by 2dust** [comment]
首先,我并没有阴阳怪气的意思,这个是前提,也感谢你提的要求
然后我确实觉得这个配置是很奇怪的,理由如下
v2ray确实配置自由,想怎么玩都行,但是我做ng的时候,UI配置只保留了主流的功能
要用ss的话,我的想法是只兼容ss原始的功能,其他的配置最好是都用vmess这样的做法的好处是你可以用ss的客户端连接v2ray的ss配置.其他的vmess配置肯定就得用v2ray的客户端了.

所以ss+tls的配置,肯定得用v2ray客户端,那么为什么不直接用vmess呢

**Comment by mo-han** [comment]
你知道用vmess，那很好，我便考你一考，vmess有个最大的缺点，是什么。这个应该知道，将来长大了用得着的（笑

**Comment by 2dust** [comment]
我已经说明了我想法
另外确实我有权决定是否做某功能

**Comment by mo-han** [comment]
你看，这就看出一个人心虚不虚了呗。
你问，我答。
我问，你避而不答。

**Comment by IDSSC** [comment]
能在socks上进行认证就好

**Comment by if1y** [comment]
有点无聊，撕逼战场现在都扩大到 github 了吗？
按作者的意思，通过自定义配置应该可以实现，到此为止就够了，何必说那么多。

**Comment by yesmiley** [comment]
有点无聊，撕逼战场现在都扩大到 github 了吗？
按作者的意思，通过自定义配置应该可以实现，到此为止就够了，何必说那么多。

**Comment by mo-han** [comment]
> 
> 
> 有点无聊，撕逼战场现在都扩大到 github 了吗？
> 按作者的意思，通过自定义配置应该可以实现，到此为止就够了，何必说那么多。

那就掰掰呗，做得没别人好，又不肯改，我当天就换用kitsunebi了，服务端改成socks over ws，他不肯回复了么我就放弃这个应用喽。
