### ISSUE TITLE
0.41版本导入自定义配置文件，修改名称后配置文件内容会丢失

### ISSUE THREAD

**Issue by zsbstephen** [2dust/v2rayNG#65]
GooglePlay自动更新到最新0.41版本后，从PC上拷贝正常可用的自定义配置文件到手机存储空间，导入到v2ray里面。然而，修改配置文件名称后（因为导入后，配置文件名是一堆不知道是什么的数字……），整个配置文件内容会丢失，点击预览一看，变成了一个新建、待填内容的空白配置文件……

期待作者修正这个bug。同时建议导入自己写好的配置文件后，配置名称沿用配置文件的名字，而不要变成一堆乱码数字了，这样就免去要自己手动更改配置文件名字的繁琐。（bitfrostv好像就是这样的）

PS：PC版的GUI客户端V2RayNG也有这个问题……导入自己写的配置文件后文件名是一堆乱码……

**Comment by 2dust** [comment]
0.4.2已修复
