### ISSUE TITLE
连接上v2ray以后，会把wifi识别成 metered network

### ISSUE THREAD

**Issue by jordanpui** [2dust/v2rayNG#650]
连接上v2ray以后，很多app会把wifi识别成 metered network (移动网络）。 比如，google photo，如果设置为移动网络下不备份，那么连接上wifi和v2ray以后，会需要手动去备份，因为识别成移动网络了。

三星s10+ Android10

**Comment by yuhan6665** [comment]
fixed by #584.
Please try pre-released version 1.4.0+

**Comment by jordanpui** [comment]
> fixed by #584.
> Please try pre-released version 1.4.0+

Tried and problem fixed, thanks.

**Comment by jordanpui** [comment]
> fixed by #584.
> Please try pre-released version 1.4.0+

Tried and problem fixed, thanks.
