### ISSUE TITLE
请提供新UI的源码

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#651]
目前的[build.gradle](https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/build.gradle#L20)显示 @2dust 只发布了 1.0.2 版本的源码，并且实际编译的结果也确实如此

贵项目使用[GPL 3.0](https://github.com/2dust/v2rayNG/blob/master/LICENSE)授权，此协议并不允许开发者在
发布软件时并不提供源码，并且即使是基于此项目源码的衍生项目，一样要提供源码

目前这个项目正在违反自己选择的授权协议

我已翻阅 issue 历史，#498 #500 #572 都已提到了此问题但均被忽略，所以我开了这个新的 issue

**Comment by rurirei** [comment]
>> This project is currently violating the license agreement of its choice.

though i'm willing to see newer codes too.. actually but, do you know what means **author**? author defines his rule.

**Comment by ghost** [comment]
即使如此，他也应先移除 LICENSE 文件，在使用 GPL 授权时不提供源码是不可接受的

**Comment by Fhokud** [comment]
#172

**Comment by Fhokud** [comment]
v2rayN的UI源码是最新的？

https://github.com/2dust/v2rayN/blob/3697de973c83e3abe1e08df402a361872980fecb/v2rayN/v2rayN/Properties/AssemblyInfo.cs

**Comment by Fhokud** [comment]
v2rayN的UI源码是最新的（我没细看
https://github.com/2dust/v2rayN/blob/3697de973c83e3abe1e08df402a361872980fecb/v2rayN/v2rayN/Properties/AssemblyInfo.cs

但 #172

**Comment by showgood163** [comment]
恳请作者重视这个问题

**Comment by wc7086** [comment]
> 
> 
> 即使如此，他也应先移除 LICENSE 文件，在使用 GPL 授权时不提供源码是不可接受的

后续版本已转向闭源，发布的程序包中并未提到GPL协议。版权所有者有权更改后续开发的版本的开源协议，也有权将后续版本转为闭源私有软件。
#172
