### ISSUE TITLE
[小问题]v2rayNG的远程DNS

### ISSUE THREAD

**Issue by NekoCompiler** [2dust/v2rayNG#652]
v2rayNG的远程DNS默认是1.1.1.1，一种UDP的DNS地址。
请问一下支持填DoH(DNS over HTTPS)还是DoT(DNS over TLS)？
DoH例子：
```
https://cloudflare-dns.com/dns-query
```
DoT例子
```
1dot1dot1dot1.cloudflare-dns.com
```

**Comment by rurirei** [comment]
none of two supported, you can use ipv4/ipv6 non-encrypted dns server only, and this server runs with port 53. https://github.com/2dust/v2rayNG/issues/647

**Comment by rurirei** [comment]
so use 8.8.8.8 as remote dns anyway please, too much issues opens here...

**Comment by gundaz-aghayev** [comment]
> none of two supported, you can use ipv4/ipv6 non-encrypted dns server only, and this server runs with port 53. #647

I have seen v2fly's query logs in my own DNS's log while using DoH protocol, the Logcat of v2fly also has 'DOH' word. DoH is surly supported.

**Comment by rurirei** [comment]
> > none of two supported, you can use ipv4/ipv6 non-encrypted dns server only, and this server runs with port 53. #647
> 
> I have seen v2fly's query in my own DNS's log while using DoH protocol, the Logcat of v2fly also appeared `DOH` word. DoH is surly supported.

are you a developer, could you code review? or stop your guessing and say sorry please.

**Comment by gundaz-aghayev** [comment]
> > > none of two supported, you can use ipv4/ipv6 non-encrypted dns server only, and this server runs with port 53. #647
> > 
> > 
> > I have seen v2fly's query in my own DNS's log while using DoH protocol, the Logcat of v2fly also appeared `DOH` word. DoH is surly supported.
> 
> are you a developer, could you code review? or stop your guessing and say sorry please.

No, i cant. That's not gussing.
Look, I'm using NextDNS and passing its test for ensuring the device is using NextDNS, the test will ask the client to solve `33q4y8frava-xxxxxx.test.nextdns.io`, a unique domain that only NextDNS can resolve. Like OpenDNS, Cloudflare DNS test does. Also I've seen the domain in v2fly' s logcat.

**Comment by NekoCompiler** [comment]
https://guide.v2fly.org/basics/dns.html#dns-over-https

**Comment by rurirei** [comment]
> https://guide.v2fly.org/basics/dns.html#dns-over-https

did all you know the fact that `remote dns` is not `v2ray dns`? did all you know what v2ray dns affects really? @gundaz-aghayev i have no more to explain, sorry.

**Comment by rurirei** [comment]
> so use 8.8.8.8 as remote dns anyway please, too much issues opens here...

so there is the only truth. i have no patience to explain more. try to see code or my commits and issues please.

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/issues/653

**Comment by rurirei** [comment]
the manual to use `v2ray dns` https://github.com/rurirei/Kitsunebi/issues/6

**Comment by rurirei** [comment]
you can make request for @2dust to do this, though no reply appeared from him as #647
