### ISSUE TITLE
suggestions to user interface of dns settings

### ISSUE THREAD

**Issue by rurirei** [2dust/v2rayNG#653]
1. ~~enforced trafficSniffing, as remove `traffic sniffing` switch~~ warn user to commonly enable sniffing https://github.com/2dust/v2rayNG/pull/645/commits/f16ca9e3c3750330fdd52f8ead17dc76f2f7c235

2. warn user to use only port-53 and ip-address non-encrypted dns server at `remote dns` setting https://github.com/2dust/v2rayNG/issues/652

3. recommended to enforced remote dns to 8.8.8.8, as remove `remote dns` too https://github.com/2dust/v2rayNG/issues/652

4. there are much DoT request, could you consider https://github.com/2dust/v2rayNG/issues/647

5. warn user to always disable `Private DNS` when using v2rayNG, as it causes updateDNSServer() issue, to catch log of ConnectivityService to see this

6. one of trafficSniffing or FakeDns had been choosen and applied, you should not allow user to disable trafficSniffing (as item first)

7. i had finished work for v2rayNG to use Fake Dns, if you would interested in, see it  https://github.com/rurirei/go-libv2ray

**Comment by rurirei** [comment]
there is all about dns @yuhan6665 @2dust

**Comment by MonNomSontPasUtile** [comment]
Enforced inboundSniffing breaks functionality of Tor and I2P services on Android.

**Comment by rurirei** [comment]
> Enforced inboundSniffing breaks functionality of Tor and I2P services on Android.

does it needs considered for a v2ray client? and when you use custom config, app settings won't affect you.

**Comment by MonNomSontPasUtile** [comment]
> > Enforced inboundSniffing breaks functionality of Tor and I2P services on Android.
> 
> does it needs considered for a v2ray client? and when you use custom config, app settings won't affect you.

Why doesn't a V2Ray client need to let its users to choose whether to enable inboundSniffing? And what about those who does not use a customized configuration file? By forcefully enabling this, ESNI/ECH (upcoming standard included in TLS 1.3), Tor and I2P will be rendered unusable.
The app setting is provided to simplify configuration, not to dump existing shortcuts back into config files. There are a lot of users who need to leave inboundSniffing disabled, while some need to have it enabled. Are you suggesting them to write a configuration file for each V2Ray connection? Not all V2Ray users have the ability to self-customize the config file.
A feature which seems not useful to you doesn't mean it is not useful to others.

**Comment by rurirei** [comment]
>> Why doesn't a V2Ray client need to let its users to choose whether to enable inboundSniffing? And what about those who does not use a customized configuration file?
> The app setting is provided to simplify configuration, not to dump existing shortcuts back into config files. There are a lot of users who need to leave inboundSniffing disabled, while some need to have it enabled. Are you suggesting them to write a configuration file for each V2Ray connection? Not all V2Ray users have the ability to self-customize the config file.

this requirement could be excepted. will edit.

**Comment by rurirei** [comment]
@EdChdX addition, as a developer, i won't leave much options to user, causing much wrong usage and wrong issues. but those are suggestions only to 2dust.

**Comment by rurirei** [comment]
guide of DNS over TLS https://github.com/rurirei/Kitsunebi/issues/6#issuecomment-719161499

**Comment by rurirei** [comment]
DNS advanced features of all included. https://github.com/rurirei/Kitsunebi/issues/6

**Comment by rurirei** [comment]
much complicated for users. closed.
