### ISSUE TITLE
【功能请求】测试完配置真连接后，能否对配置排序

### ISSUE THREAD

**Issue by happybird12** [2dust/v2rayNG#655]
用户一旦测试配置真连接，完毕后，能否增加自动排序功能（可选项），这样可以从ping值小到大，再后面是非真连接。
或者手动排序（可选项）。

**Comment by rurirei** [comment]
what is **true connection**

**Comment by happybird12** [comment]
> what is **true connection**

![Screenshot_20201009_174201.jpg](https://user-images.githubusercontent.com/72309141/95568475-da3f9f80-0a56-11eb-9f29-24eb501a2721.jpg)
点击“测试全部配置真连接”，完成后，有ping 值显示的我理解是“真连接”（也确实可以越墙）。
而连不上的“配置”代理会出现 “-1ms;” （个别无效的配置会显示空白，不显示-1ms） 手动连接任一个负一毫秒的配置代理似乎都会显示连接成功，但再次点击下部的测试，会出现链接失败的（如下图），实际也确实无法越墙。
![Screenshot_20201009_175235.jpg](https://user-images.githubusercontent.com/72309141/95569544-4cfd4a80-0a58-11eb-9a91-dd588d22eaac.jpg)

背景说明：轻度扶墙用户，使用电报分发的免费节点（一次可能几百个），部分免费节点会逐步失效（失效原因可能是时限到了，或者是包流量触发上限），为区分和快速找出有效节点（真连接节点）中的最好的节点，故而提出此请求。

**Comment by happybird12** [comment]
不急迫的功能实现
