### ISSUE TITLE
Issue with app bundle (aab) version

### ISSUE THREAD

**Issue by mahmoodshahsavari** [2dust/v2rayNG#656]
Hi 
I published i app with your code in play store with app bundles (aab)
When i install apk versions from android studio its ok.
But when i install aab version vpn connected and unfortunately it's not working

My issue : when i create a aab version from your code i have to set any configurations to app works perfectly ?

**Comment by thebadgateway** [comment]
This git is missing many pieces of code. Therefore, you will not be able to use the application.

**Comment by jianxiansining** [comment]
Is there a solution? Why close this question?
