### ISSUE TITLE
xtls+direct mode?

### ISSUE THREAD

**Issue by delphinuz** [2dust/v2rayNG#658]
Direct Mode (xtls-rprx-direct, vless preview v2.3+)，能否加入，方便测试效果，谢谢。

**Comment by KGB333** [comment]
同样期待，开发者辛苦，感谢

**Comment by delphinuz** [comment]
@2dust 2dust released this 3 hours ago

https://github.com/v2fly/v2ray-core/releases/tag/v4.31.0

感谢，马上测试！
