### ISSUE TITLE
MIUI12中play商店下载问题 （版本：1.3.3）

### ISSUE THREAD

**Issue by NKZYX** [2dust/v2rayNG#659]
目前，将下载管理和下载管理程序加入代理应用后，WIFI网络下play 商店下载提示文件较大，等待网络，切换至数据流量后可正常下载。

### 预期行为
两者应对调，甚至应将数据流量下载识别为WIFI

### 实际行为
WIFI情况下play商店识别为数据流量，数据流量情况下反而可下载

### 复现方法
1.小米手机，更新至MIUI12；v2rayNG 1.3.3
2.无线网络和数据网络
3.下载管理和下载管理程序加入代理应用
4.play商店下载app即可出现上述情况

**Comment by ssbty** [comment]
曾经遇到过，在应用商店更新play商店后恢复正常。

**Comment by yuhan6665** [comment]
fixed by #584.
Please try pre-released version 1.4.0+

**Comment by TanMusong** [comment]
我也是，包括下载管理、FiirefoxFocu，我去试试1.4
