### ISSUE TITLE
8.0通知栏的系统应用显示的流量是所有流量还是走代理的流量

### ISSUE THREAD

**Issue by mrzenwell** [2dust/v2rayNG#66]
使用全家桶方案，通知栏顶部自动出现Android系统应用vpn字样，点开显示连接时常，上传和下载流量统计

### 预期行为
国内应用这个流量不该增加的吧？

### 实际行为
使用所有app都会增加流量

### 复现方法
1.选择全家桶方案
2.查看通知栏统计
3.随意打开国内应用

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
NG本身不带流量统计功能
您提到的估计是rom自带的统计

**Comment by mrzenwell** [comment]
是的 但是在开启分应用代理后使用国内应用时流量统计不会增加，不开分应用代理使用国内应用流量统计就会增加。
