### ISSUE TITLE
小米10Pro使用v2rayNG无法正常使用VLESS

### ISSUE THREAD

**Issue by jimmychen726** [2dust/v2rayNG#660]
### 预期行为
使用PC端相同配置信息配置安卓端v2rayNG，PC端可以正常使用，vps正常，安卓应该可以正常使用

### 实际行为
点击v2rayNG连接，点击测试显示正常连接，但是无法访问网络（例如无法访问YouTube，Google等）

### 复现方法
1.vps正常配置
2.PC端测试vps正常
3.安卓端打开v2rayNG，建立链接，点击连接

### 日志信息
<details>
```
</details>

### 环境信息
vps：谷歌云
v2ray：vless+ws+tls+nginx
安卓：10
手机：小米10Pro
MIUI：12.0.4
v2rayNG：1.3.3（Libv2rayLiteV21，Core V4.27.4）

### 额外信息（可选）

**Comment by smdx** [comment]
你用1.3.3版怎么可能用得了........

**Comment by KGB333** [comment]
升级客户端到1.4.4版本以上即可解决，如果是用xtls还要升级到1.4.6版本以上

**Comment by haha125** [comment]
在哪里下载最新版本呀

**Comment by yuhan6665** [comment]
https://github.com/2dust/v2rayNG/releases

**Comment by haha125** [comment]
不知道点击哪里下载哪个 哭了 我已经好久用不了了

**Comment by haha125** [comment]
大佬方便加个联系方式吗

**Comment by haha125** [comment]
已经下载过了  还有 订阅设置的地址在哪里找？

**Comment by cqlp1314** [comment]
redmik30 pro表示也是用不了，而且app版本是最新的1.4.8
