### ISSUE TITLE
不使用界面备份与修复配置

### ISSUE THREAD

**Issue by LoveMissXY** [2dust/v2rayNG#663]
MIUI12.0.6
v2rayNG 1.3.3, 1.4.6, 1.4.7
没有注意之前使用的是什么版本,升级到1.3.3发现无法启动界面,后升级到1.4.6和1.4.7都无法启动界面.长按应用图标可以启用开关.
我准备卸载重装,但是需要备份配置,请问配置备份与修复方法,
谢谢

**Comment by rurirei** [comment]
reported as good. @2dust https://github.com/2dust/v2rayNG/blob/45805d6df7d9da41b06d465be0c694671348397e/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/AngConfigManager.kt#L25

**Comment by rurirei** [comment]
no extra backup, unless you call Root method. suggested wait for 2dust's update.

**Comment by LoveMissXY** [comment]
话说不应该是在应用的安装目录的doc下吗? 我不知道应用目录名是什么

**Comment by LoveMissXY** [comment]
> 没有额外的备份，除非您调用Root方法。建议等待2dust更新。

话说不应该是在应用的安装目录的doc下吗？我不知道应用目录名是什么

**Comment by rurirei** [comment]
>> Shouldn't it be in the doc of the application installation directory?  I don't know what the application directory name is

you thought on something wrong. no backup without launching app, unless your phone had Rooted.
