### ISSUE TITLE
发现一个关于导入导出vless协议链接的bug

### ISSUE THREAD

**Issue by crmmc** [2dust/v2rayNG#665]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

导出已配置好的vless连接，得到的内容是“TODO”而不是链接

### 实际行为
描述实际发生了什么

和预期一样

### 复现方法
1.新建一个vless配置
2.导出链接
3.查看当前剪切板内容，发现是TODO而不是链接（随便找个地方粘贴一下就知道了）

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息

截止2020.10.11 11:20 A.M. 最新版v2rayNg V1.4.8

### 额外信息（可选）
建议作者也检查一下vless链接导入部分有没有问题。手动添加vless协议可以正常使用，就是分享配置（通过url）无法使用了

**Comment by RPRX** [comment]
VLESS 暂未推出分享标准，所以客户端还不支持分享。

（为了防止这样的误解，建议开发者把 TODO 改成更详细的说明）

**Comment by crmmc** [comment]
好的，看了下最新的v2官网的介绍，把vless协议分享标准划到vless协议正式版出来以后了。
