### ISSUE TITLE
疑似高耗电量

### ISSUE THREAD

**Issue by BreakshadowCN** [2dust/v2rayNG#668]
### 预期行为
v2rayNG客户端应以较低的耗电量运行在后台

### 实际行为
重度使用时，v2rayNG客户端耗电量超过亮屏耗电量和手机信号耗电量

### 复现方法
1.正常使用v2rayNG代理访问网络。使用了Twitter App最新版，但使用时间并非很长；大部分时间是在使用Chrome浏览中国大陆网站。
2.查看手机耗电统计和应用使用时间管理，比较耗电情况

### 日志信息
<details>
</details>
现在电脑不在身边，不能提供LOG。如需要，下次遇到这种情况会提供LOG。

![Screenshot_2020-10-13-13-46-04-524_com_xiaomi misettings](https://user-images.githubusercontent.com/9458793/95820741-3c501b80-0d5b-11eb-912e-f2cf2c5646eb.jpg)

![Screenshot_2020-10-13-13-47-22-147_com_miui securitycenter](https://user-images.githubusercontent.com/9458793/95820746-3eb27580-0d5b-11eb-8435-7e38126adf08.jpg)

![Screenshot_2020-10-13-13-47-30-789_com_miui_securitycenter](https://user-images.githubusercontent.com/9458793/95820749-407c3900-0d5b-11eb-9d2b-098839bb7772.jpg)

### 环境信息
小米9，Qualcomm Snapdragon 855，MIUI 12.0.4 稳定版/Android 10。设置成分应用代理，绕过中国大陆和局域网。

**Comment by yuhan6665** [comment]
1. try VLESS xtls
2. try [Proxy only mode](https://github.com/2dust/v2rayNG/wiki/Mode#how-to-configure-proxy-only-mode)

**Comment by BreakshadowCN** [comment]
> 1. try VLESS xtls
> 2. try [Proxy only mode](https://github.com/2dust/v2rayNG/wiki/Mode#how-to-configure-proxy-only-mode)

Thanks!
我需要“绕过局域网和中国大陆地址”，请问Proxy only mode可以使用这条路由规则吗？

**Comment by yuhan6665** [comment]
Yes you can. The only thing you can't use in Proxy only mode is per-app proxy.
