### ISSUE TITLE
v1.3.2开始导入某些自定义配置文件会导致应用闪退

### ISSUE THREAD

**Issue by tonylu00** [2dust/v2rayNG#669]
routing rules 中 "inboundTag"为字符串时会出现闪退，在旧的官方文档中这个字段可以为字符串，而目前这样写可以通过v2ray-core的配置文件检查并且正常使用，根据日志猜测是v2rayNG没有没有处理该字段为字符串时的情况，也没有考虑配置文件数据类型异常时的错误处理，导致闪退
这个问题对基于新版文档写出的配置文件没有影响，但是从老版本升级的用户可能会遇到升级之后闪退的问题，只能清空数据才能解决，对于手搓配置文件的用户影响很大

### 预期行为
导入配置文件后正常使用，或者弹出配置文件有误的提示

### 实际行为
导入配置文件后应用卡死，重新打开会一直闪退无法打开

### 复现方法
1.安装打开v1.3.2版本
2.导入配置文件
3.应用卡死

### 日志信息
<details>
AndroidRuntime: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 73 column 24 path $.routing.rules[0].inboundTag
</details>

### 环境信息
Android 9

###示例配置文件：可以复现此问题的配置文件，与实际使用时不同
{
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 10808,
      "tag": "proxy-inbound",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "userLevel": 10,
        "udp": true
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "dns-out",
      "protocol": "dns"
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "network": "tcp,udp",
        "port": "53",
        "inboundTag": "proxy-inbound", // "proxy-inbound"改为["proxy-inbound"]之后可以正常导入
        "outboundTag": "dns-out"
      },
      {
        "type": "field",
        "network": "tcp,udp",
        "outboundTag": "direct"
      }
    ]
  }
}

**Comment by yuhan6665** [comment]
Thanks for reporting this bug. Will fix in next version.

**Comment by yuhan6665** [comment]
Fixed in https://github.com/2dust/v2rayNG/pull/670
