### ISSUE TITLE
摄像头扫二维码太模糊

### ISSUE THREAD

**Issue by winds365** [2dust/v2rayNG#67]
v2rayNG调用摄像头扫二维码太模糊，都识别不出来
Shadowsocks识别的很清晰
我的手机是荣耀v8，后置双摄

**Comment by 2dust** [comment]
NG自带的是使用的开源方案
如果实在不行,暂时先安装一个條碼掃描器,NG会优先调用
https://play.google.com/store/apps/details?id=com.google.zxing.client.android
