### ISSUE TITLE
VLESS协议无法启动服务，VMESS协议正常

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#671]
### 实际行为

同样是安卓客户端，A手机配置和B手机配置一致，但是B手机VLESS协议显示启动服务失败，换成VMESS正常
清除数据，卸载安装最新1.4.8还是一样

### 日志信息

--------- beginning of system
--------- beginning of main
10-15 01:09:12.070 E/com.v2ray.ang(32766): Not starting debugger since process cannot load the jdwp agent.
10-15 01:09:12.160 I/com.v2ray.ang(32766): type=1400 audit(0.0:26783): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=28755 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=1
10-15 01:09:12.160 I/com.v2ray.ang(32766): type=1400 audit(0.0:26784): avc: denied { open } for path="/dev/__properties__/u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=28755 scontext=u:r:untrusted_app:s0:c197,c256,c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=1
10-15 01:09:12.160 I/com.v2ray.ang(32766): type=1400 audit(0.0:26785): avc: denied { getattr } for path="/dev/__properties__/u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=28755 scontext=u:r:untrusted_app:s0:c197,c256,c512

### 环境信息

协议: VLESS TCP TLS

**Comment by Fhokud** [comment]
你不把手机参数留一下？

**Comment by SekiBetu** [comment]
服务端和客户端的VLESS配置必须吻合，再次检查下你的配置
