### ISSUE TITLE
修改app的包名后 点击下边的按钮 不能建立连接 圈儿一直转圈儿

### ISSUE THREAD

**Issue by alijhen** [2dust/v2rayNG#673]
下载源码修改包名和项目路径并修改provider的authority运行程序，点击下边的按钮 结果是 不能建立连接 圈儿一直转圈儿

### 预期行为
能够像源码那样正常连接

### 实际行为
不能建立连接 圈儿一直转圈儿

### 复现方法
1. build.gradle 修改为自己的包名 manifest里修改为自己的包名
2，修改com.v2ray.ang包路径为自己的包名
3，修改provider 的 authority为自己的包名

### 日志信息

```

### 环境信息
设备：华为P20
版本：1.0.2

### 额外信息（可选）

**Comment by yuhan6665** [comment]
Adb log?

**Comment by alijhen** [comment]
after i modify the variable ANG_PACKAGE of the class AppConfig to my own package name everything then work perfect thx.
a little suggestion that if the packageName dynamicly asign the value better than hard code.

**Comment by yuhan6665** [comment]
PR is welcomed :)

**Comment by git4pl** [comment]
遇到了同样的问题，怎么解决的呢，源码是最新版的
