### ISSUE TITLE
http伪装多host时问题

### ISSUE THREAD

**Issue by zqs125** [2dust/v2rayNG#674]
比如我的域名为www.mydomain.com，在使用tcp+tls，并选择http伪装后，当填多个host，用逗号分隔，比如像这样www.aaa.com,www.bbb.com,www.ccc.com时，tlsSettings里的serverName会变成这样"serverName": "www.aaa.com,www.bbb.com,www.ccc.com"，这个serverName不应该是我的证书对应的域名吗，这是不是一个bug？

### 预期行为
描述你认为应该发生什么
serverName应该是这样"serverName": "www.mydomain.com"
### 实际行为
描述实际发生了什么
"serverName": "www.aaa.com,www.bbb.com,www.ccc.com"
### 复现方法
开启http伪装，并填入多个host，有逗号分隔

### 环境信息
目前版本为v1.4.8

**Comment by 2dust** [comment]
https://github.com/v2fly/v2ray-core/issues/337

**Comment by 2dust** [comment]
请暂时用一个域名填入 伪装域名(host)
