### ISSUE TITLE
安卓5.0打开绕过局域网无法真正代理

### ISSUE THREAD

**Issue by Genglxy** [2dust/v2rayNG#675]
设备：Venue 7840 x86架构，安卓5.0.2
描述：此前设备在安卓5.1的时候没有这个问题，最近刷机到5.0后，在开启绕过局域网时通知栏不显示VPN开启图标，也没有真正代理。
Previously, the device did not have this problem with Android 5.1, but recently, after downgrading to 5.0, it does not show the VPN icon in the notification bar when "bypass LAN" is enabled, and there is no real proxy.
开关绕过局域网产生的日志没有区别。
There is no difference in the log generated by the switch "Bypass LAN".
提问者注：这里开始下面的问题已经得到解决。下面的情况中，无法开启的原因不是不支持较高的端口号，而是因为在config内xxx.xxx.xxx.xxx/xx“尾数是路由掩码（通常称为网络掩码）中前1位的计数（来自维基百科）”。欲添加IP地址，不需要填写端口。
下面是原issue的后半段：
鉴于在自定义规则中不能添加过高的端口号，否则无法开启服务，目前找不到合适的解决办法…
其他客户端没有这个问题，可以开启“绕过局域网”并正常使用。
下面是端口号过高时的log：
10-15 20:31:14.530 I/GoLog   ( 5788): v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: invalid IP: 172.16.0.32/8080 > v2ray.com/core/infra/conf: invalid network mask for router: 8080
10-15 20:31:14.530 D/com.v2ray.ang( 5788): go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: invalid IP: 172.16.0.32/8080 > v2ray.com/core/infra/conf: invalid network mask for router: 8080

10-15 20:31:40.070 I/GoLog   ( 5788): loading v2ray config
10-15 20:31:40.870 I/GoLog   ( 5788): v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: invalid IP: 172.16.0.32/80 > v2ray.com/core/infra/conf: invalid network mask for router: 80
10-15 20:31:40.880 D/com.v2ray.ang( 5788): go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: invalid IP: 172.16.0.32/80 > v2ray.com/core/infra/conf: invalid network mask for router: 80

**Comment by yuhan6665** [comment]
172.16.0.32/8080??

**Comment by Genglxy** [comment]
> 172.16.0.32/8080??

这是我们的WiFi验证系统的地址…如果不能绕过这个的话，每次登WiFi就都要手动关闭

**Comment by yuhan6665** [comment]
that is invalid ip
https://www.v2fly.org/config/routing.html
Try use UI option instead of writing custom config

**Comment by Genglxy** [comment]
> that is invalid ip
> https://www.v2fly.org/config/routing.html
> Try use UI option instead of writing custom config

Thank you for your help!I did add it within the UI, I think the problem is below: i found the meaning of xxx.xxx.xxx.xxx/xx in your link, it is CIDR, the xx in the second half is not the meaning of port, it has another meaning.Presumably config doesn't support IP addresses with ports, I think I can fix that by just entering the IP.
Of course, the first part of my question, which is that on my Android 5.0.2, x86 device, the problem of not being able to actually connect (even though the software shows a successful connection) after "LAN bypass" is enabled, is still there and may need to be fixed.This is because the feature will work fine on another Android client.

**Comment by mengmo** [comment]
同样是 Android 5.0，使用带`绕过局域网`的规则时通知栏不显示 VPN 图标，没有真正代理。
使用的都是默认的设置，有人知道怎么解决吗？
以下是 log
```
03-24 00:07:09.086 I/GoLog   ( 1253): loading core config
03-24 00:07:09.416 I/GoLog   ( 1253): new core
03-24 00:07:09.496 I/GoLog   ( 1253): start core
03-24 00:07:09.496 I/GoLog   ( 1253): [Warning] core: Xray 1.3.1 started
03-24 00:07:09.506 D/com.v2ray.ang( 1253): java.lang.IllegalArgumentException: Bad LinkAddress params /224.0.0.0/3
```

**Comment by mengmo** [comment]
查了下，[有的地方](https://stackoverflow.com/a/29576319)是这样说的
> since lollipop, multicast address can't add to route, 224.0.0.0 is a multicast base address

https://en.wikipedia.org/wiki/Reserved_IP_addresses

@yuhan6665 https://github.com/2dust/v2rayNG/commit/d1466ba4b20d75405de83ddb42be6cbdded111d7

**Comment by yuhan6665** [comment]
@mengmo, thanks for the info. Plan to fix later. PR welcome also :)

**Comment by yuhan6665** [comment]
fix in https://github.com/2dust/v2rayNG/pull/1070

**Comment by xqdoo00o** [comment]
多播地址 只影响android5.0以及之前的版本，从android6.0开始就没影响了。

https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-5.0.0_r1/core/java/android/net/VpnService.java#436

https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-6.0.0_r1/core/java/android/net/VpnService.java#505
