### ISSUE TITLE
希望增加dns over tcp/udp的相关设置

### ISSUE THREAD

**Issue by EsuRt** [2dust/v2rayNG#676]
### 预期行为
使用shadowsocks协议时，如果ss服务器端没有开通udp，v2rayng也能正确解析，避免dns被污染。

### 实际行为
使用shadowsocks协议时，如果ss服务器端没有开通udp，v2rayng会默认使用本地dns，当本地dns为国内dns时，会被污染；当本地dns为国外dns时，解析速度非常慢，有时会丢包。希望对于shadowsocks协议，能够增加下dns over tcp或udp的相关设置。
使用vmess协议时，解析是正常的。

### 环境信息
系统：MIUI 11
V2rayNG版本：1.3.3

**Comment by rurirei** [comment]
local dns needed https://github.com/2dust/v2rayNG/issues/653

**Comment by rurirei** [comment]
to overwrite your dns to tcp, simply enable `Local DNS` in v2rayNG app settings https://github.com/rurirei/v2rayNG/commit/ccea264d5e84a7bcf732bf296599e9ef21d789f0#diff-09186e738d44a2f099f72eea382b422755d3ba352908da2015895bff508c51e8

**Comment by rurirei** [comment]
#709
