### ISSUE TITLE
被运营商墙，如何解决？

### ISSUE THREAD

**Issue by Rock-Law** [2dust/v2rayNG#677]
现象
1、华为手机，v2rayNG连接自建的Server成功，测试连接可成功反馈延时时间。
2、v2rayNG连接自建Server成功后的5秒左右时间，可以正常使用。
3、几秒钟后，浏览器、APP，所有客户端都不能访问大陆网和外网。（v2rayNG启用“绕过局域网及大陆地址”）
4、电信、移动、wifi网络下均如此。
5、关闭v2rayNG后大陆网访问正常。

尝试1
1、卸载v2rayNG重装
2、升级v2rayNG到新版1.3.3
未能解决问题

尝试2
1、双清华为手机，重新安装全部app
v2rayNG正常使用

重现
1、v2rayNG正常使用约1-2周
2、手机接收到推送的强制更新，无法取消或延迟，如不更新，手机则一直是此界面（怀疑是数据网络服务商中国电信推送，因为推送界面没有明确推送方，也怀疑是华为）
3、为使手机可用，更新后重启
4、重启后，问题现象复现（电信、移动、wifi网络下均如此）

尝试3
1、更新v2rayNG到最新版1.4.8
未能解决问题

**Comment by yuhan6665** [comment]
Please post log when you see connection issue

**Comment by yuhan6665** [comment]
#679
Try turn off any "battery/notification optimisation" or use system feature "always on VPN" to keep the proxy process.

**Comment by Fhokud** [comment]
提供下配置文件信息，可以吗

**Comment by Fhokud** [comment]
提供下配置文件信息和手机型号，可以吗？
以方便调试

**Comment by SekiBetu** [comment]
服务端客户端的v2ray-core版本必须一致，配置文件也必须吻合，再自查下

**Comment by Rock-Law** [comment]
感谢大家提供的尝试方法，需要补充另外的信息：
1、我的手机上有v2rayNG，也有BifostV，两个app都是一样的现象。无论哪个app刚连上的5秒左右使用正常，超过这个时间，就不能用了。
2、用的vmess+ws+tls。
3、除手机外，v2ray在PC、AC88U、软路由、OpenWrt各个客户端均使用正常。

所以怀疑是手机端被运营商或厂商强制更新了v2ray（或包括ss等其他）的控制程序

**Comment by if1y** [comment]
强制更新 v2rayNG？奇奇怪怪的表述（难道想说华为有后门检测？）

---

就给定的信息来判断：

1. **运营商或厂商强制更新是不太可能的**，除非应用市场类APP的自动更新没有关闭。但国内应用市场也不太可能提供此类应用，大概率排除被更新的可能（没有实测华为应用市场，不保证）

2. 考虑到 BifrostV 很久没更新过也无法连接，基本可以**排除 v2ray-core 高低版本兼容问题**，同时也印证上一点：v2rayNG 不可能被更新过（二者矛盾）

3. 给定信息的移动、电信是指数据流量吗？wifi又是什么运营商？这一点也很关键，在不明确此信息前提下，**有理由怀疑服务器线路问题，运营商二次拦截**

4. 除开以上，直觉告诉我更有可能是服务端问题。如果全部尝试无果，建议检查服务端运行问题，甚至**重装系统和最新版服务端，并升级所有客户端至最新版**。

**Comment by ghost** [comment]
你是不是下错了版本了？一般来说手机应该下载arm64-v8a这个后缀的版本。
另外，一些中国大陆国产手机由于对后台应用限制严格（例如oppo和小米）的缘故，因此还需要关闭类似于“后台冻结/异常时自动优化” ”限制app在后台运行“这样的选项才能正常使用哦。

**Comment by SekiBetu** [comment]
服务端的core版本是多少？这个你不说估计永远也解决不了

**Comment by if1y** [comment]
> 你是不是下错了版本了？一般来说手机应该下载arm64-v8a这个后缀的版本。
> 另外，一些中国大陆国产手机由于对后台应用限制严格（例如oppo和小米）的缘故，因此还需要关闭类似于“后台冻结/异常时自动优化” ”限制app在后台运行“这样的选项才能正常使用哦。

这个问题倒是不太会有，目前主流 Android 机型都支持 v8a 和 v7a，2016年左右的机型也最起码支持 v7a。
如果不支持运行库，应用是直接无法安装的。

**Comment by Rock-Law** [comment]
感谢大家的响应，在我的手机上并不只有V2rayNG是这样的表现，BifostV也是同样的表现。最近尝试了自建OpenVPN服务器，然后手机用OpenVPN客户端。手机OpenVPN连接国内的服务器，网速和操作全部正常，连接V2ray所在的服务器，流量为4B/s。不知道怎么解决了。这里不能黏贴图片，以下链接是openvpn的截图，可以看到最高速率近100K/s，超过5秒就速率就接近于无。
https://seeworld.xyz/index.php/s/jioaXf5i4SodDM9

**Comment by SekiBetu** [comment]
此issue无中生有，没有任何价值，多半为内核不匹配，配置没写对，软件不会用造成的

**Comment by Rock-Law** [comment]
环境信息如下：

> 服务器端：`
        CentOS Linux release 7.7.1908 (Core)
        Linux kernel 5.6.2-1.el7.elrepo.x86_64
        Docker version 19.03.8, build afacb8b
        Docker image:
             v2ray:     v2fly/v2fly-core:v4.31.3
             caddy2:  caddy:2.2.1

> 客户端：
        华为Mate 20 Pro(LYA-AL00)
        EMUI 10.1.0
        V2rayNG v1.4.8(Lib v22, Core v4.31.0)

@if1y 建议的第4点在以前做过两次，服务器端从AWS换到GCP，再换到Aliyun，对解决移动端的问题都无效。

**Comment by SekiBetu** [comment]
10月份的issue，12月了还没贴过连接失败的日志，如何解决问题

**Comment by ghost** [comment]
如果都无效，那估计提问者的isp是ChinaMobile，或者二级运营商。

**Comment by Rock-Law** [comment]
@SekiBetu 
1、确实不知道在不启用工程模式下，如何在手机上拿v2rayNG中的日志，看v2rayNG的设置中是有日志级别的。
2、手机上的v2rayNG不是连接失败，连接服务器是成功的（点击v2rayNG中的测试连接，提升“连接成功：延时XX毫秒”）
3、手机在连接成功的情况下，访问不了外网。（v2rayNG，BifostV，OpenVPN均这样）

**Comment by SekiBetu** [comment]
> @SekiBetu
> 1、确实不知道在不启用工程模式下，如何在手机上拿v2rayNG中的日志，看v2rayNG的设置中是有日志级别的。
> 2、手机上的v2rayNG不是连接失败，连接服务器是成功的（点击v2rayNG中的测试连接，提升“连接成功：延时XX毫秒”）
> 3、手机在连接成功的情况下，访问不了外网。（v2rayNG，BifostV，OpenVPN均这样）

没有日志，没有任何人能帮你，你只能在黑暗中自己摸索

**Comment by if1y** [comment]
OpenVPN 早就被识别了，被阻断很正常，拿来比较毫无意义

**Comment by thezhang98** [comment]
我的情况和你一模一样。
最后我解决了。
原因是我在某次应用权限设置时将它的后台权限给干掉了，所以它只有前几秒钟能翻墙，一旦我切到其它应用开始试时，它已经被冻结了。
你可以看看它的后台权限。
@Rock-Law
