### ISSUE TITLE
无法正常连接

### ISSUE THREAD

**Issue by weasonn** [2dust/v2rayNG#679]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
手机端正常连接

### 实际行为
描述实际发生了什么
点击开启后，进入浏览器app第一次访问谷歌大概率正常，第二次访问就无法再访问任何网站

### 复现方法
同上，疑似也有人发生差不多的情况。

### 日志信息
日志在最下方截图
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

![Screenshot_2020-10-17-02-49-20-085_com v2ray ang](https://user-images.githubusercontent.com/27633819/96298042-6bfb5f80-0fb7-11eb-8c34-c9c1ed9be986.jpg)

**Comment by yuhan6665** [comment]
Is your VPN service running?
try [Proxy only mode](https://github.com/2dust/v2rayNG/wiki/Mode#how-to-configure-proxy-only-mode)?

**Comment by weasonn** [comment]
> Is your VPN service running?
> try [Proxy only mode](https://github.com/2dust/v2rayNG/wiki/Mode#how-to-configure-proxy-only-mode)?

Yes the v2ray service is running and my pc is ok to connect with v2rayn. And the proxy mode is also not ok.

**Comment by yuhan6665** [comment]
https://github.com/shadowsocks/shadowsocks-android/issues/1414
Some say it is because the proxy process is killed somehow. That's why it worked for a second and then failed. Try turn off any "battery/notification optimisation" or use system feature "always on VPN" to keep the proxy process.

**Comment by weasonn** [comment]
Tried to reboot my phone and it's ok now. I will focus on this thread if it happens in future. Thanks.
