### ISSUE TITLE
AndroidLibV2rayLite这个go项目怎么编译呢

### ISSUE THREAD

**Issue by alijhen** [2dust/v2rayNG#682]
我在win10上的subSystem 也就是ubuntu18 LTS 进入项目根目录 执行make命令 结果打印出 pb start 之后就没有任何输出了

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
windows10下的子系统ubuntu18LTS

**Comment by yuhan6665** [comment]
read **whole** guide for [Go Mobile](https://github.com/golang/go/wiki/Mobile) and [Makefiles for Go Developers](https://tutorialedge.net/golang/makefiles-for-go-developers/)

**Comment by rurirei** [comment]
make sure you are a developer first.

**Comment by alijhen** [comment]
> make sure you are a developer first.

make sure not every developer can write android application.

**Comment by rurirei** [comment]
> > make sure you are a developer first.
> 
> make sure not every developer can write android application.

sorry to hear this.

**Comment by myflyingfish** [comment]
我一点 也不懂 go，但是 我编译通过了，我是 安卓开发的。1 go 环境，2 gomobile 环境 3 ndk 环境 4 gomobile  的demo 通过。 5 编译 v2raylibrary  查看什么问题，然后 在解决，缺少依赖，下载依赖，这个过程 很烦。 然后你就会发现 编译通过了。

**Comment by giftedunicorn** [comment]
## Compile V2rayNG libv2ray.aar

### Preparation
1. A Ubuntu 20 machine
2. At lease 100G free space

### Get Repo
1. `git clone https://github.com/2dust/v2rayNG.git`
2. `cd v2rayNG/AndroidLibV2rayLite`

### Prepare Go
1. Go to https://golang.org/doc/install and download go 1.16
2. `rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz`
3. Extract the archive you downloaded into /usr/local
4. `export PATH=$PATH:/usr/local/go/bin`

### Prepare gomobile
1. `go get golang.org/x/mobile/cmd/gomobile`
2. `export PATH=$PATH:~/go/bin`
3. `gomobile init`

### Make
1. `sudo apt install make`
2. `make all`
3. `make downloadGoMobile`
4. `make BuildMobile`

It will be nice if we can auto build this with Travis CI

**Comment by Woxiee** [comment]
> 我一点 也不懂 go，但是 我编译通过了，我是 安卓开发的。1 go 环境，2 gomobile 环境 3 ndk 环境 4 gomobile 的demo 通过。 5 编译 v2raylibrary 查看什么问题，然后 在解决，缺少依赖，下载依赖，这个过程 很烦。 然后你就会发现 编译通过了。

老哥,可以能运行的源码发我邮箱吗?  15989467261@163.com,  我下载最新的代码跑不起来,搞了好久,人麻了

**Comment by isold23** [comment]
NDK 用哪个版本， 最新版本好像有问题？
