### ISSUE TITLE
 Class 'V2RayCallback' is not abstract and does not implement abstract member public abstract fun sendFd()

### ISSUE THREAD

**Issue by kingvpn859** [2dust/v2rayNG#688]
Task :app:compileDebugKotlin FAILED
e: /Users/jeremy/test/v2rayNG/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayServiceManager.kt: (72, 13): Class 'V2RayCallback' is not abstract and does not implement abstract member public abstract fun sendFd(): Long defined in libv2ray.V2RayVPNServiceSupportsSet

**Comment by rurirei** [comment]
make sure clone the latest repo.

**Comment by rurirei** [comment]
library pre-release update needed @yuhan6665

**Comment by yuhan6665** [comment]
Fixed in ~~#689~~#698.
@rurirei I encountered a gomobile compile issue with unused import path. Please make sure you compile it next time ;)

**Comment by rurirei** [comment]
> library pre-release update needed @yuhan6665

https://github.com/2dust/v2rayNG/tree/master/V2rayNG/app/libs

**Comment by kingvpn859** [comment]
So, how should I solve this problem...?
which commit or tag I could build successfully?

**Comment by rurirei** [comment]
wait for update or until 24d105a

**Comment by rurirei** [comment]
> Fixed in #689.
> @rurirei I encountered a gomobile compile issue with unused import path. Please make sure you compile it next time ;)

![](https://64.media.tumblr.com/6a6e762cf806e8954b586a62867f19d2/tumblr_mnr0na1LY41r1a9yfo3_500.jpg)

**Comment by rurirei** [comment]
example https://github.com/rurirei/v2rayNG/releases/download/prelease/libv2ray.aar https://github.com/rurirei/v2rayNG/runs/1298737796
