### ISSUE TITLE
Core version number incorrect

### ISSUE THREAD

**Issue by Platway** [2dust/v2rayNG#69]
v2rayNG 0.4.3: in Settings->Version, it displays V2Ray 3.22. I think it is core version 3.21 actually because core 3.22 was released later than v2rayNG 0.4.3.

And I hope v2rayNG can make an immediate new release with the latest core 3.22, in which a major network flash/cut-off bug has been fixed.

Thanks and have a nice day!

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.4.4
