### ISSUE TITLE
请问如何获取使用的流量值啊

### ISSUE THREAD

**Issue by WangYuana** [2dust/v2rayNG#692]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
获取当前用户所使用的流量值。

### 实际行为
不知道如何操作获取，代码里面有没有什么方法能获取流量值得啊。

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/blob/51b97b64f235dd168c590dc950f530d8cf03f916/AndroidLibV2rayLite/interact.go#L114-L123

**Comment by WangYuana** [comment]
感谢提示




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rurirei"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 中午1:08
收件人: "2dust/v2rayNG"<v2rayNG@noreply.github.com&gt;; 
抄送: "咕叽咕叽"<1918765432@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [2dust/v2rayNG] 请问如何获取使用的流量值啊 (#692)





 
https://github.com/2dust/v2rayNG/blob/51b97b64f235dd168c590dc950f530d8cf03f916/AndroidLibV2rayLite/interact.go#L114-L123

**Comment by rurirei** [comment]
https://github.com/2dust/v2rayNG/issues/333
