### ISSUE TITLE
1.4.8版本无法区分识别不同端口下，相同UUID的用户。

### ISSUE THREAD

**Issue by flyingwp** [2dust/v2rayNG#693]
服务器端设置2个端口，相同的UUID，协议完全相同都是VMESS。例如：

port:18180
uuid:b4894c68-0b48-403f-8a18-0a3b054948d3
"email": "18180@mail.com"

port:12345
uuid:b4894c68-0b48-403f-8a18-0a3b054948d3
"email": "12345@mail.com"

使用旧版v2rayNG1.2.13 连接，可以正常区分不同端口下，不同用户。
而使用1.4.8连接，12345端口的UUID为b4894c68-0b48-403f-8a18-0a3b054948d3 用户，应该显示为email": "12345@mail.com。
但显示的是18180端口的用户email": "18180@mail.com 访问。

结论：无法区分不同端口下 相同UUID的用户。 旧版v2rayNG和电脑v2rayN则无此问题。
1.4.8版本 客户端UUID：b4894c68-0b48-403f-8a18-0a3b054948d3用端口12345连接，错误识别为 服务器端 config.json里（从上到下的）第一个符合UUID的用户"email": "use18180@mail.com"访问。

**Comment by yuhan6665** [comment]
It must be a server issue. Since "email" only exist in server config
