### ISSUE TITLE
建议增加故障转移和负载均衡

### ISSUE THREAD

**Issue by if1y** [2dust/v2rayNG#696]
建议增加上述两个功能。

其中故障转移更重要，有时候节点故障了根本不知道，导致一些即时通讯软件都收不到消息，必须自己发现问题再去手动切换。

**Comment by rurirei** [comment]
>> to add failover and load balancing

rarely considerable.

**Comment by ghost** [comment]
短期内应该不会增加（因为上游v2ray-core的缘故）。
还有如果在移动设备上使用这个功能的话有可能会造成额外的大量耗电。

**Comment by if1y** [comment]
@devinstever 
其实core本身就有负载均衡功能，填写多个outbound vnext就可以了，只不过需要手动调整，所以本帖意思是希望通过ui便捷实现。
多个加入负载均衡之后，其实也算是故障转移。

**Comment by rurirei** [comment]
is there other apps done this feature? maybe i will try make an copy from Clash.

**Comment by if1y** [comment]
> is there other apps done this feature? maybe i will try make an copy from Clash.

- Clash
- Kitsunebi (if I remember correctly)

**Comment by rurirei** [comment]
i won't do this as waiting for https://github.com/v2fly/v2ray-core/issues/377

**Comment by ghost** [comment]
@devinstever  @rurirei 
I am using https://github.com/v2fly/v2ray-core/issues/377#issuecomment-723527556 on my phone, it's working nicely and I have not yet seen a significant shortening of the battery life when setting a large speed-test period.

**Comment by rurirei** [comment]
> @devinstever @rurirei
> I am using [v2fly/v2ray-core#377 (comment)](https://github.com/v2fly/v2ray-core/issues/377#issuecomment-723527556) on my phone, it's working nicely and I have not yet seen a significant shortening of the battery life when setting a large speed-test period.

review will be later.

**Comment by rurirei** [comment]
@acc557 could you create a repo with patch you used for my review?

**Comment by rurirei** [comment]
> @devinstever @rurirei
> I am using [v2fly/v2ray-core#377 (comment)](https://github.com/v2fly/v2ray-core/issues/377#issuecomment-723527556) on my phone, it's working nicely and I have not yet seen a significant shortening of the battery life when setting a large speed-test period.

could you say what commits you used? there are much pull request related.

**Comment by rurirei** [comment]
failover of v2ray-core https://github.com/v2fly/v2ray-core/issues/377#issuecomment-727136897
