### ISSUE TITLE
绕过大路ip地址不能用

### ISSUE THREAD

**Issue by octowhale** [2dust/v2rayNG#7]
安卓7.1.1，
绕过大路ip现在不论是否勾选都处于代理状态。

**Comment by octowhale** [comment]
补充， v2rayng版本为 0.2.5

**Comment by 2dust** [comment]
这种情况我会去测试下。你自己可以先用导入自定义配置的方式来看看是否能正常使用

**Comment by crackself** [comment]
遇到类似问题，安卓6，勾选绕过大陆IP后代理无法启动（配置文件手动填入）

**Comment by octowhale** [comment]
你好，经测试。
坚果pro。

firefox 及默认浏览器支持绕过大路ip，但chrome不行。

请问哪里可以收集日志，反馈给你

**Comment by 2dust** [comment]
0.2.6可能已解决

**Comment by octowhale** [comment]
从 play 更新到 0.2.6 后，所有浏览器都不能使用  绕过大陆ip 了，全部走代理

**Comment by ruan11223344** [comment]
不能绕过+1

**Comment by 2dust** [comment]
测试下0.3.1

**Comment by ncs19960831** [comment]
Android 7.1，lineageos。
v2rayng0.3.1，远程DNS8.8.8.8，8.8.4.4。
路由为geo全家桶，设置为自定义文件导入。
测试问题依旧是无法分流

**Comment by ncs19960831** [comment]
测试浏览器Chrome 63.0.3239.111，firefox focus。
测试浏览器访问ip.cn；baidu.com搜索"ip"关键词；皆为代理IP。

**Comment by ncs19960831** [comment]
有种可能，是否自定义文件导入会出现无法分流的情况？

**Comment by March-happy** [comment]
同样的问题出现在 Mokee 71 上，测试浏览器 Firefox ，无法分流。

**Comment by ncs19960831** [comment]
经过测试，自定义文件导入几乎百分百出现上述问题，但是在我的手机上使用的是0.3.11。且在该版本中使用软件添加的配置都可以实现分流。

**Comment by ncs19960831** [comment]
@2dust 可以在软件上面添加一下提示吗？
就是如果自定义文件导入的话很可能 不能使用软件设置内的绕行模式。

**Comment by kirbyzhu** [comment]
增加一个情况 如果设置自定义路由，结果反而导致访问自定义路由中网站的时候全局设置失效

比如说自定义谷歌商店的大陆地址走代理  然后开全局 这时候谷歌商店反而无法连接升级下载服务器
