### ISSUE TITLE
同样设备同样网络一台成功一台失败

### ISSUE THREAD

**Issue by tolves** [2dust/v2rayNG#7]
同一个WiFi，同样设备（essential ph-1 Android 9）
一台始终正常，一台显示 connection closed by peer。
同网络下的电脑亦正常连接。
真是百思不得其解

**Comment by yihuanZhang** [comment]
或许你可以看下你的设备的时间设置, 改成使用网络时间可能就会好了, 我在v2ray上面看到有一句客户端与服务端的时间差不能超过90s, 希望对你有帮助

**Comment by dongbingliu** [comment]
同样也遇到此问题：
HuaWei Mate 9 ，Android 9 系统，连接成功后，点击测试连接：

时间设置为与网络同步

提示：
失败：Connection closed by peer;

**Comment by yihuanZhang** [comment]
HuaWei pad m5, android 9系统, 用着蛮正常的。不过有一点, 我之前有问题的samsung note 8国行, 在没有开时间同步之前只有1个节点(BifrostV)可以用, v2rayNG节点能测速成功, 也能连接, 连接后测试显示connection closed by peer, 之后我开了时间同步, 同步了一次时间之后我有关同步了, 之后所有节点都正常了(BifrostV, v2rayNG), 所以我这里不负责任的推测下是不是服务器时间不同步了, 手动滑稽..

**Comment by dongbingliu** [comment]
估计需要对于android 9 特别优化下！

测试偶尔成功，但大部分时间失败：Connection closed by peer;

**Comment by KGB333** [comment]
@JerrryLiu 解决，调时间，同步时间就好

**Comment by dongbingliu** [comment]
> @JerrryLiu 解决，调时间，同步时间就好

同步时间也没有解决，找商家给换了节点连接正常。

**Comment by eycu3366** [comment]
怎么找商家换节点啊

**Comment by eromoe** [comment]
同样的问题，不同设备  一加可以用，红米刷了个国外的9.0 rom就不行了
