### ISSUE TITLE
OPPO R5 Android 4.4.4 Couldn't load gojni from loader  findLibrary returned null

### ISSUE THREAD

**Issue by dzw** [2dust/v2rayNG#700]
--------- beginning of /dev/log/main
10-24 01:35:23.083 D/AndroidRuntime(17507): Shutting down VM
--------- beginning of /dev/log/system
10-24 01:35:23.083 E/AndroidRuntime(17507): FATAL EXCEPTION: main
10-24 01:35:23.083 E/AndroidRuntime(17507): Process: com.v2ray.ang:RunSoLibV2RayDaemon, PID: 17507
10-24 01:35:23.083 E/AndroidRuntime(17507): java.lang.UnsatisfiedLinkError: Couldn't load gojni from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.v2ray.ang-1.apk", zip file "/data/data/com.v2ray.ang/code_cache/secondary-dexes/com.v2ray.ang-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/com.v2ray.ang-1, /vendor/lib, /system/lib]]]: findLibrary returned null
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at java.lang.System.loadLibrary(System.java:526)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at go.Seq.<clinit>(Seq.java:37)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at libv2ray.Libv2ray.<clinit>(Libv2ray.java:12)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at com.v2ray.ang.service.V2RayVpnService.<init>(V2RayVpnService.kt:63)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at java.lang.Class.newInstanceImpl(Native Method)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at java.lang.Class.newInstance(Class.java:1208)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2564)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at android.app.ActivityThread.access$1800(ActivityThread.java:143)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1291)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at android.os.Looper.loop(Looper.java:136)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at android.app.ActivityThread.main(ActivityThread.java:5120)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
10-24 01:35:23.083 E/AndroidRuntime(17507): 	at dalvik.system.NativeStart.main(Native Method)
10-24 01:35:24.543 W/System.err(17507): java.lang.Throwable
10-24 01:35:24.543 W/System.err(17507): 	at android.os.Process.killProcess(Process.java:972)
10-24 01:35:24.543 W/System.err(17507): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:94)
10-24 01:35:24.543 W/System.err(17507): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
10-24 01:35:24.543 W/System.err(17507): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
10-24 01:35:24.543 W/System.err(17507): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by yuhan6665** [comment]
Try universal version: https://github.com/2dust/v2rayNG/releases/download/1.3.3/v2rayNG_1.3.3.apk. If that doesn't work you need to take a look why so lib is not copied..

**Comment by dzw** [comment]
v2rayNG_1.5.8_armeabi-v7a this version is ok!
