### ISSUE TITLE
建议增加订阅分组功能

### ISSUE THREAD

**Issue by tnyjy** [2dust/v2rayNG#703]
像SSRRAY这个项目一样。这样订阅多就容易管理了。项目地址https://github.com/xxf098/shadowsocksr-v2ray-trojan-android

**Comment by HaroldLoui** [comment]
对，加个节点树这样的进行各个订阅的管理，还有如果能加上按照延迟进行排序的功能就好了

**Comment by bigrain2007** [comment]
确实，如果能加上就太方便了。

**Comment by xixiri** [comment]
是的，我一般不用ng来订阅，没有分组太长了，不方便找节点
