### ISSUE TITLE
昨天开始，很多v2ray节点被堵

### ISSUE THREAD

**Issue by lin4007** [2dust/v2rayNG#705]
昨天开始，很多v2ray节点被堵，软件得升级了。

**Comment by happybird12** [comment]
是呀，vmess的节点一早发现全部阵亡，只留下了VLESS和trojan节点

**Comment by aliitt** [comment]
所有节点都连不上了，下载速度都是0M

**Comment by tomdog2016** [comment]
失败: Get "http://www.google.com/gen-204":context deandline exceeded

**Comment by pch9527** [comment]
最近这几天五中全会  vmess节点阵亡几率很高  建议找trojan节点

**Comment by ronghms** [comment]
同样的服务器地址链接，v2rayN可以正常使用，v2rayNG不能正常使用

**Comment by showgood163** [comment]
vless未受明显影响

**Comment by xiaopanggege** [comment]
我的v2rayNG是vless出现失败: Get "http://www.google.com/gen-204":context deandline exceeded，vmess正常

**Comment by tislam8888** [comment]
27号 就开始了
被识别干扰得很严重
经常断ping 
蔷太厉害了

**Comment by xiaopanggege** [comment]
@tislam8888 建议改用vmess+tls+ws，我改后一直正常

**Comment by devinstever** [comment]
> 27号 就开始了
> 被识别干扰得很严重
> 经常断ping
> 蔷太厉害了

其实墙的主动探测一直都有的，这些年下来，我成功地拉黑了上万个干这种事的ip：https://connect.51kly.net/ip-list-bot.txt
