### ISSUE TITLE
dns if not udp-allowed server

### ISSUE THREAD

**Issue by rurirei** [2dust/v2rayNG#709]
met this when i'm doing some test with a remote with udp-allow disabled. though i'm aware of Local DNS (point to #676)  to solve it, this is not i wanted (met other problems with Fake DNS i'm working on). is there other solution possible? addition, Fake DNS solves this, but there are other problems i have to take.
```
[Info] v2ray.com/core/app/dispatcher: sniffed domain: gist.github.com
[Debug] v2ray.com/core/proxy/socks: send packet to udp:8.8.8.8:53 with 32 bytes
[Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.8.8:53
[Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:8.8.8.8:53
[Info] udp:127.0.0.1:40547 accepted udp:8.8.8.8:53 [proxy-out]
[Info] v2ray.com/core/proxy/shadowsocks: tunneling request to udp:8.8.8.8:53 via tcp:server.address:server.port
[Info] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: connection ends > context canceled
[Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
[tun2socks] read remote failed: read udp [::]:40547: i/o timeout
```
https://github.com/2dust/v2rayNG/blob/6c199c1687c2e5ab532190079d8f8285908c4e5e/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L604-L618 https://github.com/2dust/v2rayNG/blob/6c199c1687c2e5ab532190079d8f8285908c4e5e/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt#L123-L128

**Comment by rurirei** [comment]
the request do not round in `routing`
```
{
   "port": "53",
   "network": "udp",
   "outboundTag": "proxy-out"
}
```
```
[Info] v2ray.com/core/app/dispatcher: default route for udp:8.8.8.8:53
```

**Comment by rurirei** [comment]
Local DNS provides less performance and query rate.
```
{
  "outboundTag": "dns"
}
```

**Comment by yuhan6665** [comment]
Yeah either sniffing or fake DNS, it only solve the problem for the first DNS (at VPNServer). For second DNS (routing), traffic should be handled by remote server to ensure correctness.
I understand the best way is to use UDP over TCP. If on the server side you installed shadowsocks you probably need v2 plugin?

**Comment by rurirei** [comment]
udp over tcp makes less sense if Local DNS, it is better to remains udp in fact.

seems no better idea. closed.

**Comment by rurirei** [comment]
i found a great way — `dns fallback` to solve this and done it on my own repo. you can find it out for v2rayNG as well if interested. @yuhan6665
