### ISSUE TITLE
配置WS + TLS + CDN 后连不上网

### ISSUE THREAD

**Issue by kodear** [2dust/v2rayNG#71]
不知道是不是我的配置原因，在 Windows, Mac, iPhone 上配置都可以使用，但是在安卓上总是连不上网，用BifrostV配置也失败，请问可以给个配置示例么，感谢!

**Comment by lidakang1** [comment]
怀疑你跟我遇到了是相同的问题，我仔细逐渐排除问题，发现跟选择路由模式是否包含绕过大陆地址有关，从而可以断定是Android内没能成功加载 geoip.dat、geosite.dat 有关，应该是跟最近 @2dust 频繁的merge别人的代码以及更新代码有关。

**Comment by kodear** [comment]
> 怀疑你跟我遇到了是相同的问题，我仔细逐渐排除问题，发现跟选择路由模式是否包含绕过大陆地址有关，从而可以断定是Android内没能成功加载 geoip.dat、geosite.dat 有关，应该是跟最近 @2dust 频繁的merge别人的代码以及更新代码有关。

@lidakang1，你搞定了么？麻烦帮忙看看配置有无问题呢？我使用的默认全局代理。
![v2rayNG](https://user-images.githubusercontent.com/42135362/63785407-e3d57900-c922-11e9-9f5c-c3986256689a.jpg)
![v2rayNG2](https://user-images.githubusercontent.com/42135362/63785413-e6d06980-c922-11e9-8cbc-b41ef6b3e836.jpg)

**Comment by kodear** [comment]
已经搞定了，之前大半年时间折腾了好几次都连不上，以为是哪里配置问题，就放弃了。感谢@lidakang1回复，又继续折腾了一下，虽然修改了代理模式几次，还是连不上。然后看了下日志
发现很多
 rejected  v2ray.com/core/proxy/vmess/encoding: invalid user
 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
这类错误，也搞不懂啥意思。最后偶然意外发现手机时间比电脑时间快10多分钟，想起了很多应用会验证时间戳，手机和服务器的时间不同，不知道是不是这个问题，就抱着试试的心态，把手机时间设为自动获取，（这个安卓是备用机，平时都关机的，也不知道为何这半年多时间就慢了10多分钟）然后重新连接，点击测试，居然连成功了！甚至意外！

**Comment by JonathanHuInfo** [comment]
> 已经搞定了，之前大半年时间折腾了好几次都连不上，以为是哪里配置问题，就放弃了。感谢@lidakang1回复，又继续折腾了一下，虽然修改了代理模式几次，还是连不上。然后看了下日志
> 发现很多
> rejected v2ray.com/core/proxy/vmess/encoding: invalid user
> rejected v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
> 这类错误，也搞不懂啥意思。最后偶然意外发现手机时间比电脑时间快10多分钟，想起了很多应用会验证时间戳，手机和服务器的时间不同，不知道是不是这个问题，就抱着试试的心态，把手机时间设为自动获取，（这个安卓是备用机，平时都关机的，也不知道为何这半年多时间就慢了10多分钟）然后重新连接，点击测试，居然连成功了！甚至意外！

哥日志目录在哪？

**Comment by JonathanHuInfo** [comment]
> 已经搞定了，之前大半年时间折腾了好几次都连不上，以为是哪里配置问题，就放弃了。感谢@lidakang1回复，又继续折腾了一下，虽然修改了代理模式几次，还是连不上。然后看了下日志
> 发现很多
> rejected v2ray.com/core/proxy/vmess/encoding: invalid user
> rejected v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
> 这类错误，也搞不懂啥意思。最后偶然意外发现手机时间比电脑时间快10多分钟，想起了很多应用会验证时间戳，手机和服务器的时间不同，不知道是不是这个问题，就抱着试试的心态，把手机时间设为自动获取，（这个安卓是备用机，平时都关机的，也不知道为何这半年多时间就慢了10多分钟）然后重新连接，点击测试，居然连成功了！甚至意外！

我也是套了CDN 就不能用了

**Comment by superabbite1** [comment]
我也是套了cdn 安卓就不行了，但是电脑就正常的

**Comment by superabbite1** [comment]
> 怀疑你跟我遇到了是相同的问题，我仔细逐渐排除问题，发现跟选择路由模式是否包含绕过大陆地址有关，从而可以断定是Android内没能成功加载 geoip.dat、geosite.dat 有关，应该是跟最近 @2dust 频繁的merge别人的代码以及更新代码有关。

的确，我把路由设置里改成绕过大陆地址和局域网地址后，就正常了
