### ISSUE TITLE
可以在节点的周围添加它的订阅备注吗

### ISSUE THREAD

**Issue by 2857584289** [2dust/v2rayNG#710]
订阅多了不好区分

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
Added in 1.5.11
