### ISSUE TITLE
新的引用外部geo文件功能的建议

### ISSUE THREAD

**Issue by even0306** [2dust/v2rayNG#711]
最新预览版的引入外部geo文件功能，引入的文件发现无法删除，希望给个最低限度的删除功能。另外通过一些工具能够实现自动更新geo文件了，v2rayng也能引用外部geo文件了，却发现v2rayng应用的文件不会随外部文件更新而更新，望能优化一下，实现全自动更新geo文件，使其保持最新

**Comment by rurirei** [comment]
> 最新预览版的引入外部geo文件功能，引入的文件发现无法删除，希望给个最低限度的删除功能

Android 11?

> 另外通过一些工具能够实现自动更新geo文件了，v2rayng也能引用外部geo文件了，却发现v2rayng应用的文件不会随外部文件更新而更新

`Will not be updated with external file updates` what it with? 

@yuhan6665 you need to add one `check update` btn to update their files.

**Comment by even0306** [comment]
> > 最新预览版的引入外部geo文件功能，引入的文件发现无法删除，希望给个最低限度的删除功能
> 
> Android 11?

Android 10 我随意添加了一个其他文件，添加成功了，然后发现无法删掉
> 
> > 另外通过一些工具能够实现自动更新geo文件了，v2rayng也能引用外部geo文件了，却发现v2rayng应用的文件不会随外部文件更新而更新
> 
> `Will not be updated with external file updates` what it with?
> 
> @yuhan6665 you need to add one `check update` btn to update their files.

需要geo文件自动随外部文件的改变而改变，或者定时更新文件(如一天更新一次文件)。只是添加检查更新的按钮还是无法实现自动化

**Comment by yuhan6665** [comment]
On Android 10 you can just delete the files in `Android/data/com.v2ray.ang/files/assets`. I can probably add a delete button for Android 11.
Please manually update the files. No plan to support auto update at the moment.

**Comment by Miroxyz** [comment]
> 最新预览版的引入外部geo文件功能，引入的文件发现无法删除，希望给个最低限度的删除功能。另外通过一些工具能够实现自动更新geo文件了，v2rayng也能引用外部geo文件了，却发现v2rayng应用的文件不会随外部文件更新而更新，望能优化一下，实现全自动更新geo文件，使其保持最新

请问是如何实现自动更新 geo 文件的？

**Comment by even0306** [comment]
> > 最新预览版的引入外部geo文件功能，引入的文件发现无法删除，希望给个最低限度的删除功能。另外通过一些工具能够实现自动更新geo文件了，v2rayng也能引用外部geo文件了，却发现v2rayng应用的文件不会随外部文件更新而更新，望能优化一下，实现全自动更新geo文件，使其保持最新
> 
> 请问是如何实现自动更新 geo 文件的？

我是vps定时下载最新文件到网盘，然后网盘定时同步到各平台相应目录下，安卓用foldersync同步。但v2ray不会定时添加最新的文件

**Comment by Miroxyz** [comment]
> > > 最新预览版的引入外部geo文件功能，引入的文件发现无法删除，希望给个最低限度的删除功能。另外通过一些工具能够实现自动更新geo文件了，v2rayng也能引用外部geo文件了，却发现v2rayng应用的文件不会随外部文件更新而更新，望能优化一下，实现全自动更新geo文件，使其保持最新
> > 
> > 
> > 请问是如何实现自动更新 geo 文件的？
> 
> 我是vps定时下载最新文件到网盘，然后网盘定时同步到各平台相应目录下，安卓用foldersync同步。但v2ray不会定时添加最新的文件

感谢分享

**Comment by aplixy** [comment]
这文件有什么用？我在设置里已经添加了自定义规则，跟这个冲突吗？哪个在起作用？
