### ISSUE TITLE
新版测试延迟pin太慢了

### ISSUE THREAD

**Issue by tnyjy** [2dust/v2rayNG#712]
真链接，Tcping都一样。节,点多测试半天也测试不完。旧版1.1.5就很快

**Comment by tislam8888** [comment]
同样一个节点 PC最新版可以用
安卓 旧版 可以用
但是用1.4.10 就是ping都ping不通

**Comment by yuhan6665** [comment]
fixed in 1.5.6, thanks to xray-core
