### ISSUE TITLE
纯ipv6连接后用不了

### ISSUE THREAD

**Issue by yzzfzd2** [2dust/v2rayNG#716]
纯ipv6的EUSERV套cf，pc端v2rayn正常，安卓下pharos也正常，v2rayng最新版，不管是vmess还是vless连接后都打不开网页。

**Comment by Loukky** [comment]
你需要一个把远程DNS设置成一个DNS64的IP

**Comment by yzzfzd** [comment]
> 你需要一个把远程DNS设置成一个DNS64的IP

已经设置了NAT64了，PC端的v2rayn, 和Android下的pharos是可以正常使用的，只有v2rayng用不了。设置里勾选了IPV6优先也没用。

**Comment by Loukky** [comment]
> > 你需要一个把远程DNS设置成一个DNS64的IP
> 
> 已经设置了NAT64了，PC端的v2rayn, 和Android下的pharos是可以正常使用的，只有v2rayng用不了。设置里勾选了IPV6优先也没用。

我半年以前可以成功使用，你应该贴上相关日志

**Comment by zzx396** [comment]
> 你需要一个把远程DNS设置成一个DNS64的IP

请问还有其他方法吗？因为修改远程DNS后，IPV4节点又用不了了。

**Comment by Choutouketsu** [comment]
目前也碰到这个问题，貌似这个是bug，电脑端和pharospro都可以，期待大神解决😋
