### ISSUE TITLE
v1.4.10 绕过局域网和大陆地址后启动失败

### ISSUE THREAD

**Issue by wilinz** [2dust/v2rayNG#717]
logcat:
--------- beginning of system
--------- beginning of main

10-30 00:00:48.003 I/GoLog   ( 4233): v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:cn > v2ray.com/core/infra/conf: failed to load geosite: CN > unexpected EOF
10-30 00:00:48.003 D/com.v2ray.ang( 4233): go.Universe$proxyerror: v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: invalid field rule > v2ray.com/core/infra/conf: failed to parse domain rule: geosite:cn > v2ray.com/core/infra/conf: failed to load geosite: CN > unexpected EOF

**Comment by yuhan6665** [comment]
Looks like your geosite file is broken. Try replace it by '+' button or delete and re-install v2rayNG.

**Comment by even0306** [comment]
刚更新后第一次使用原本里面的geo文件使用不了，手动添加一下geosite和geoip文件就好

**Comment by SekiBetu** [comment]
你的IP和端口漏出来了，你是否有编写过自定义规则，自定义规则是否编写正确？

**Comment by wilinz** [comment]
> 你的IP和端口漏出来了，你是否有编写过自定义规则，自定义规则是否编写正确？

geoip文件有问题
