### ISSUE TITLE
[FeatureRequest]请求加入Trojan over XTLS支持

### ISSUE THREAD

**Issue by maskedeken** [2dust/v2rayNG#718]
v4.31.3+的trojan协议已经支持XTLS，设置方法跟VLESS一样

**Comment by tpfeng** [comment]
怎么设置？有参考吗？

**Comment by maskedeken** [comment]
> 
> 
> 怎么设置？有参考吗？

[https://github.com/v2fly/v2ray-core/pull/334](https://github.com/v2fly/v2ray-core/pull/334)

**Comment by 2dust** [comment]
为什么不用vless

**Comment by maskedeken** [comment]
> 为什么不用vless

因为XTLS是通用的传输层，应该在配置上足够flexible，不应该跟特定协议绑死

**Comment by yjwskj** [comment]
trojan 安卓找不到怎添加 测试好几个方法都不行 建议加上增加trojan选项

**Comment by 2dust** [comment]
1.如果你用的trojan-go等做服务端，那么客户端不需要支持xtls
2.如果你用的v2ray做服务端，那么请直接用vless
我们这么做也是为了简化操作，你可以参考ss

**Comment by xkgg** [comment]
111

2dust <notifications@github.com> 于 2020年11月5日周四 11:52写道：
