### ISSUE TITLE
Manage routing and advanced settings in per node.

### ISSUE THREAD

**Issue by lxsjgzs** [2dust/v2rayNG#719]
Is there any feasible solution to manage each node's advanced settings and routings but not use a merged config lead to a unmanageable situation for users. Thanks!

**Comment by yuhan6665** [comment]
Use custom config

**Comment by lxsjgzs** [comment]
> Use custom config

You mean that I can export the config file to the clipboard then import the config files again? I’ll try it, thx.

**Comment by lxsjgzs** [comment]
It works, thanks a lot!
