### ISSUE TITLE
1.4.10 速度很慢 很容易断流 断ping

### ISSUE THREAD

**Issue by tislam8888** [2dust/v2rayNG#721]
挂 1.4.10 版本
用 ADM 下载 速度 只有两三百KB
挂 旧版本 1.2.9
下载 速度能满速 10MB/s
差距太远了 同样一个 节点
而且 我发现 这个 新版本 1.4.10 非常容易断流
看youtube 经常刷不出东西来
半天都是在转圈圈
我之前一直是用旧版本的
为了支持 trojan 才升级用这个
好难用

**Comment by yuhan6665** [comment]
If it is easy to tell the difference, can you test from which version it started to become slow?

**Comment by SekiBetu** [comment]
你应该先自己排查问题，比如你的服务端和客户端版本是否一致，配置是否设置正确，因为很多情况下都是因为客户端服务端不对口才会造成速度很慢甚至断流的

**Comment by ghost** [comment]
如果是纯udp断流的话这很正常，因为v2ray-core就是把udp包在tcp里发送的，遇到常见的tcp丢包环境时就会自然发生这种情况，唯一解决它的办法就是换个更好的线路。（例如有时候就会出现开网页正常，但是youtube app看视频特别卡之类的情况）
但如果是干什么都断流的话，那问题大概率出在服务器和客户端v2ray-core版本差的太大，或者手机下错了版本这种情况（关键词armeabi-v7a为32位版本arm64-v8a为64位版本），如果连接模式为websocket的话，则还需要考虑是不是前端代理（例如nginx）的超时时间设置问题。
