### ISSUE TITLE
[建议] 请求添加配置选项，允许选择默认代理模式

### ISSUE THREAD

**Issue by silverzhaojr** [2dust/v2rayNG#723]
希望可以选择默认代理模式：direct, proxy, block

当前是默认选中了 proxy 模式，不可更改，希望可以让用户自定义。因为通常大部分网站是可以直接访问的，只有在 gfw list 里的才需要代理。

**Comment by rurirei** [comment]
> direct, proxy, block

are you user of client Clash ?

**Comment by silverzhaojr** [comment]
> > direct, proxy, block
> 
> are you user of client Clash ?

No, I used "[BifrostV](https://play.google.com/store/apps/details?id=com.github.dawndiy.bifrostv&hl=zh)": 
![Screenshot_2020-11-01-16-18-08-068_com github dawndiy bifrostv](https://user-images.githubusercontent.com/4557341/97798159-8ba0b200-1c5e-11eb-923e-8fa8a6c28bce.jpg)

**Comment by rurirei** [comment]
though no update at all, it's a good client especially.

**Comment by lxsjgzs** [comment]
Use V2rayNG instead

**Comment by yesmiley** [comment]
v2rayNG is designed to be **a tool to break GFW as simple as possible**, which is not the same as the outdated BifrostV.

Nowadays GFW updates quickly, therefore **the list cannot cover every sites blocked by GFW**.
The most reliable way should be `bypassing LAN and Mainland China`, which is what v2rayNG exactly doing right now.

If you persist on doing what you want, try `edit custom config`.

**Comment by silverzhaojr** [comment]
same request in #768 .

**Comment by silverzhaojr** [comment]
> v2rayNG is designed to be **a tool to break GFW as simple as possible**, which is not the same as the outdated BifrostV.
> 
> Nowadays GFW updates quickly, therefore **the list cannot cover every sites blocked by GFW**.
> The most reliable way should be `bypassing LAN and Mainland China`, which is what v2rayNG exactly doing right now.
> 
> If you persist on doing what you want, try `edit custom config`.

有些情况下，可能机场流量有所限制，想要大部分还是直连。希望可以提供这样的选择供有需要的人使用。

我看了下，好像可以在这个界面加上一个新选项如「默认直连」：
![977162478](https://user-images.githubusercontent.com/4557341/101135815-50234a00-3647-11eb-968d-d423e55ee4b4.jpg)

对应的代码应该是这个位置：

https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/V2rayConfigUtil.kt#L395
```
            when (routingMode) {
                "0" -> {
                }
                "1" -> {
                    routingGeo("ip", "private", AppConfig.TAG_DIRECT, v2rayConfig)
                }
                "2" -> {
                    routingGeo("", "cn", AppConfig.TAG_DIRECT, v2rayConfig)
                    v2rayConfig.routing.rules.add(0, googleapisRoute)
                }
                "3" -> {
                    routingGeo("ip", "private", AppConfig.TAG_DIRECT, v2rayConfig)
                    routingGeo("", "cn", AppConfig.TAG_DIRECT, v2rayConfig)
                    v2rayConfig.routing.rules.add(0, googleapisRoute)
                }
            }
```

需要加上一段如：
```
    {
     "type": "field",
     "outboundTag": "Direct",
     "network": "tcp,udp"
    }
```

**Comment by if1y** [comment]
1. That option should means routing almost everything to `direct` (except what in `custom rules`).

2. Already said at https://github.com/2dust/v2rayNG/issues/723#issuecomment-726589303: try `edit custom config` if u really want to do so.
I'm sure this is **the quickest and the easiest solution** before the developers deciding to add this function for u~

**Comment by silverzhaojr** [comment]
1. Yes, the user will need edit "custom rules" to add something like "geosite:gfw" for "Proxy";
2. Yes, I'm using "custom config" for now, thanks for your previous suggestion. But it's not very easy if I have to switch between different servers because of service unstability. If it's integrated into the official package, it would be quite helpful!
