### ISSUE TITLE
非常费电，手机发烫。extreme cpu/power use and cause overheat

### ISSUE THREAD

**Issue by leohougmail** [2dust/v2rayNG#724]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
电池/cpu使用过渡，手机发烫

### 复现方法
1.链接服务器后就开始
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

![Screenshot_2020-11-02-06-50-35-912_com miui securitycenter](https://user-images.githubusercontent.com/73801091/97817529-f4784080-1cd7-11eb-972e-55a542d47880.jpg)

**Comment by yuhan6665** [comment]
1. try VLESS xtls
2. try [Proxy only mode](https://github.com/2dust/v2rayNG/wiki/Mode#how-to-configure-proxy-only-mode)

**Comment by rurirei** [comment]
though i had never met this. (i uses core implementation of v2rayNG)
![20201102_023912](https://user-images.githubusercontent.com/72071920/97824857-0d90e980-1cf8-11eb-8cb4-67bd6595edcd.jpg)

**Comment by ghost** [comment]
可能是加密模式的问题，此时建议把加密模式调整为 chacha20-poly1305再试试看。
也有可能是配置的问题，如果有条件的话建议把alterid服务器和客户端同时设置为双数倍。
最后最最最不太可能的原因是客户端这边v2ray-core已经是最新，但是服务器端的版本停留在很久很久以前。如果检查一下确实是这种情况的话建议给服务器升下级。

**Comment by rurirei** [comment]
> 可能是加密模式的问题，此时建议把加密模式调整为 chacha20-poly1305再试试看。
> 也有可能是配置的问题，如果有条件的话建议把alterid服务器和客户端同时设置为双数倍。
> 最后最最最不太可能的原因是客户端这边v2ray-core已经是最新，但是服务器端的版本停留在很久很久以前。如果检查一下确实是这种情况的话建议给服务器升下级。

to `none` excryption and `tls` transport is of recommendation. use `auto` algirihm please.

**Comment by if1y** [comment]
**Android 特性：流量经过 VPN 的耗电数据均会被计算在 VPN 上**

另外，使用 VPN 发烫也是很正常的情况。这和机器素质、后台应用、全局路由都有关系。
