### ISSUE TITLE
Qv2ray订阅更新失败

### ISSUE THREAD

**Issue by yinitian** [2dust/v2rayNG#726]
订阅的地址,数据的base64解析不了,通过正常的脚本base64对比发现,订阅内的base64 / 对应的是_ (下划线), 我使用linux的base64命令可以解开,但是apk订阅更新失败

c3NyOi8vZW1wamRTNXBaR011ZEdZNk1UTXlORFU2YjNKcFoybHVPbkpqTkMxdFpEVTZhSFIwY0Y5emFXMXdiR1U2WTBkR2VtTXpaR3N2UDI5aVpuTndZWEpoYlQxTlZGRXhUa1JuTUU1cVozVlpiVVp3V2toVmRWa3lPWFFtY0hKdmRHOXdZWEpoYlQwbWNtVnRZWEpyY3oxUk1EUm5UbVZYUVdwVFFYUkpSRVY2VFdwUk1TWm5jbTkxY0QxVWJUa3dZVWRzZFZwMwpzc3I6Ly9lbXBqZFM1cFpHTXVkR1k2TVRZME56UTZiM0pwWjJsdU9uSmpOQzF0WkRVNmFIUjBjRjl6YVcxd2JHVTZZMGRHZW1NelpHc3ZQMjlpWm5Od1lYSmhiVDFOVkZFeFRrUm5NRTVxWjNWWmJVWndXa2hWZFZreU9YUW1jSEp2ZEc5d1lYSmhiVDBtY21WdFlYSnJjejFSTURSblRtVlhRV3BUUVhSSlJFVXlUa1JqTUNabmNtOTFjRDFVYlRrd1lVZHNkVnAzCnNzcjovL2VtcGpkUzVwWkdNdWRHWTZNekl4TlRjNmIzSnBaMmx1T25Kak5DMXRaRFU2YUhSMGNGOXphVzF3YkdVNlkwZEdlbU16WkdzdlAyOWlabk53WVhKaGJUMU5WRkV4VGtSbk1FNXFaM1ZaYlVad1draFZkVmt5T1hRbWNISnZkRzl3WVhKaGJUMG1jbVZ0WVhKcmN6MVJNRFJuVG1WWFFXcFRRWFJKUkUxNVRWUlZNeVpuY205MWNEMVViVGt3WVVkc2RWcDMKc3NyOi8vWTIweUxtNXZaR1V1YUd0MGIyOXZMblJ2Y0RveE1EUXpNanB2Y21sbmFXNDZjbU0wTFcxa05UcG9kSFJ3WDNOcGJYQnNaVHBqUjBaNll6TmtheThfYjJKbWMzQmhjbUZ0UFUxVVVURk9SR2N3VG1wbmRWbHRSbkJhU0ZWMVdUSTVkQ1p3Y205MGIzQmhjbUZ0UFNaeVpXMWhjbXR6UFZFd01HZE9aVmRCYWxOQmRFbEVSWGRPUkUxNUptZHliM1Z3UFZSdE9UQmhSMngxV25jCnNzcjovL1kyMHlMbTV2WkdVdWFHdDBiMjl2TG5SdmNEb3hNRFF6TVRwdmNtbG5hVzQ2Y21NMExXMWtOVHBvZEhSd1gzTnBiWEJzWlRwalIwWjZZek5rYXk4X2IySm1jM0JoY21GdFBVMVVVVEZPUkdjd1RtcG5kVmx0Um5CYVNGVjFXVEk1ZENad2NtOTBiM0JoY21GdFBTWnlaVzFoY210elBWRXdNR2RPWlZkQmFsTkJkRWxFUlhkT1JFMTRKbWR5YjNWd1BWUnRPVEJoUjJ4MVduYwpzc3I6Ly9ZMjB5TG01dlpHVXVhR3QwYjI5dkxuUnZjRG94TURRek1EcHZjbWxuYVc0NmNtTTBMVzFrTlRwb2RIUndYM05wYlhCc1pUcGpSMFo2WXpOa2F5OF9iMkptYzNCaGNtRnRQVTFVVVRGT1JHY3dUbXBuZFZsdFJuQmFTRlYxV1RJNWRDWndjbTkwYjNCaGNtRnRQU1p5WlcxaGNtdHpQVkV3TUdkT1pWZEJhbE5CZEVsRVJYZE9SRTEzSm1keWIzVndQVlJ0T1RCaFIyeDFXbmMKc3NyOi8vWTIweUxtNXZaR1V1YUd0MGIyOXZMblJ2Y0RveE1EUXpNenB2Y21sbmFXNDZjbU0wTFcxa05UcG9kSFJ3WDNOcGJYQnNaVHBqUjBaNll6TmtheThfYjJKbWMzQmhjbUZ0UFUxVVVURk9SR2N3VG1wbmRWbHRSbkJhU0ZWMVdUSTVkQ1p3Y205MGIzQmhjbUZ0UFNaeVpXMWhjbXR6UFZFd01HZE9aVmRCYWxOQmRFbEVSWGRPUkUxNkptZHliM1Z3UFZSdE9UQmhSMngxV25jCnNzcjovL1kzVXlMbTV2WkdVdWFHdDBiMjl2TG5SdmNEb3hNRFF6TURwdmNtbG5hVzQ2Y21NMExXMWtOVHBvZEhSd1gzTnBiWEJzWlRwalIwWjZZek5rYXk4X2IySm1jM0JoY21GdFBVMVVVVEZPUkdjd1RtcG5kVmx0Um5CYVNGVjFXVEk1ZENad2NtOTBiM0JoY21GdFBTWnlaVzFoY210elBWRXhWV2RPWlZkQmFsTkJkRWxFUlhkT1JFMTNKbWR5YjNWd1BWUnRPVEJoUjJ4MVduYwpzc3I6Ly9ZM1V5TG01dlpHVXVhR3QwYjI5dkxuUnZjRG94TURRek1qcHZjbWxuYVc0NmNtTTBMVzFrTlRwb2RIUndYM05wYlhCc1pUcGpSMFo2WXpOa2F5OF9iMkptYzNCaGNtRnRQVTFVVVRGT1JHY3dUbXBuZFZsdFJuQmFTRlYxV1RJNWRDWndjbTkwYjNCaGNtRnRQU1p5WlcxaGNtdHpQVkV4VldkT1pWZEJhbE5CZEVsRVJYZE9SRTE1Sm1keWIzVndQVlJ0T1RCaFIyeDFXbmMKc3NyOi8vWTNVeUxtNXZaR1V1YUd0MGIyOXZMblJ2Y0RveE1EUXpORHB2Y21sbmFXNDZjbU0wTFcxa05UcG9kSFJ3WDNOcGJYQnNaVHBqUjBaNll6TmtheThfYjJKbWMzQmhjbUZ0UFUxVVVURk9SR2N3VG1wbmRWbHRSbkJhU0ZWMVdUSTVkQ1p3Y205MGIzQmhjbUZ0UFNaeVpXMWhjbXR6UFZFeFZXZE9aVmRCYWxOQmRFbEVSWGRPUkUwd0ptZHliM1Z3UFZSdE9UQmhSMngxV25jCnRyb2phbjovL3liYkglMkIlN0JvJTI5JTdDTXhpQGhrMS5ub2RlLmhrdG9vby50b3A6MTIwMDI_c25pPXplcm9zc2wubm9kZS5oa3Rvb28udG9wI0hLIC0gMTIwMDIKdHJvamFuOi8vTnpCTkMlMkFiUUg1JTI5UEBqcDIubm9kZS5oa3Rvb28udG9wOjEwMDg2P3NuaT16ZXJvc3NsLm5vZGUuaGt0b29vLnRvcCNKUCAyIC0gMTAwODYKdHJvamFuOi8vZXMlMjNkQVhDVThVVUpAc2cxLm5vZGUuaGt0b29vLnRvcDo0NDM_c25pPXplcm9zc2wubm9kZS5oa3Rvb28udG9wI1NHIDEgLSA0NDMKdHJvamFuOi8vYlc4JTIzc0xQUGIlN0NlSEB1czEubm9kZS5oa3Rvb28udG9wOjQ0Mz9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjVVMgMSAtIDQ0Mwp0cm9qYW46Ly95YmJIJTJCJTdCbyUyOSU3Q014aUBoazIubm9kZS5oa3Rvb28udG9wOjQ0Mz9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjSEsgMiAtIDQ0Mwp0cm9qYW46Ly9iVzglMjNzTFBQYiU3Q2VIQGNtMi5ub2RlLmhrdG9vby50b3A6MTMwMDU_c25pPXplcm9zc2wubm9kZS5oa3Rvb28udG9wI0NNMiBVUzEgLSAxMzAwNQp0cm9qYW46Ly8lMjNpem4lM0VKTiUzQ2ZkZiUyOEBjbTIubm9kZS5oa3Rvb28udG9wOjEzMDA0P3NuaT16ZXJvc3NsLm5vZGUuaGt0b29vLnRvcCNDTTIgSlAxIC0gMTMwMDQKdHJvamFuOi8vRFolNUJSQ1U5JTI4ZVpvZ0BydTEubm9kZS5oa3Rvb28udG9wOjQ0Mz9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjUlUgMSAtIDQ0Mwp0cm9qYW46Ly8lMjNpem4lM0VKTiUzQ2ZkZiUyOEBqcDIubm9kZS5oa3Rvb28udG9wOjEwMDEwP3NuaT16ZXJvc3NsLm5vZGUuaGt0b29vLnRvcCNKUDItMSAtIDEwMDEwCnRyb2phbjovL2JXOCUyM3NMUFBiJTdDZUhAY3UyLm5vZGUuaGt0b29vLnRvcDoxMjEwND9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjQ1UyIFVTMSAtIDEyMTA0CnRyb2phbjovL3liYkglMkIlN0JvJTI5JTdDTXhpQGNtMi5ub2RlLmhrdG9vby50b3A6MTMwMDE_c25pPXplcm9zc2wubm9kZS5oa3Rvb28udG9wI0NNMiBISzIgLSAxMzAwMQp0cm9qYW46Ly8lMjNpem4lM0VKTiUzQ2ZkZiUyOEBqcDEubm9kZS5oa3Rvb28udG9wOjQ0Mz9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjSlAgMSAtIDQ0Mwp0cm9qYW46Ly95YmJIJTJCJTdCbyUyOSU3Q014aUBjbTIubm9kZS5oa3Rvb28udG9wOjEzMDAwP3NuaT16ZXJvc3NsLm5vZGUuaGt0b29vLnRvcCNDTTIgSEsxIC0gMTMwMDAKdHJvamFuOi8vZXMlMjNkQVhDVThVVUpAY20yLm5vZGUuaGt0b29vLnRvcDoxMzAwMz9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjQ00yIFNHMSAtIDEzMDAzCnRyb2phbjovL0RaJTVCUkNVOSUyOGVab2dAY3UyLm5vZGUuaGt0b29vLnRvcDoxMjEwMD9zbmk9emVyb3NzbC5ub2RlLmhrdG9vby50b3AjQ1UyIFJVMSAtIDEyMTAwCnRyb2phbjovLyUyM2l6biUzRUpOJTNDZmRmJTI4QGN1Mi5ub2RlLmhrdG9vby50b3A6MTIxMDE_c25pPXplcm9zc2wubm9kZS5oa3Rvb28udG9wI0NVMiBKUDItMSAtIDEyMTAxCg

NO_WRAP：这个参数意思是略去所有的换行符（设置后CRLF就没用了）

URL_SAFE：这个参数意思是编码时不使用对URL和文件名有特殊意义的字符来作为编码字符，具体就是以-和_取代+和/

    fun decode(text: String): String {
        try {
            return Base64.decode(text, Base64.NO_WRAP).toString(charset("UTF-8"))
        } catch (e: Exception) {
            e.printStackTrace()
            return ""
        }
    }

    /**
     * base64 encode
     */
    fun encode(text: String): String {
        try {
            return Base64.encodeToString(text.toByteArray(charset("UTF-8")), Base64.NO_WRAP)
        } catch (e: Exception) {
            e.printStackTrace()
            return ""
        }
    }

是否可以搞个兼容啊, NO_WARP和URL_SAFE都支持一下啊

**Comment by ggsmmm** [comment]
楼主兄弟可以共享一下订阅地址吗
