### ISSUE TITLE
红米1S 安卓6.1 启动成功后仍然不能科学上网

### ISSUE THREAD

**Issue by abc906093117** [2dust/v2rayNG#73]
需要说明的是
1、这个手机多年不用，原始版本是安卓4.4，但是在安卓4.4版本下打开APP就会闪退。
2、经过刷机后换成6.0.1安卓版本可以运行，经过扫码以及准确地调整了参数（和另一部可以正常科学上网的VIVO手机一模一样的参数），发现不能访问被墙的网站。
3、在4.4版本下，我也尝试了其它软件，例如BifrostV，同样是一个问题，能够启动，并且提示建立连接成功，但是无法访问被墙网站。
系统UI为CM，安卓版本为6.0.1，CPU为MT6582。
APP版本为最新版v2rayNg（50兆左右的那个）

**Comment by istraw** [comment]
我刚换了只一加7，也遇到类似这个问题，用wifi就能访问，用4G就不行，后来下了BifrostV也是一样的状态，研究了一下，把远程DNS改成8.8.8.8就可以了，默认是1.1.1.1

**Comment by abc906093117** [comment]
非常感谢，但无论wifi还是4g都无法访问，刚才试着把v2rayng的远程dns改成8.8.8.8还是不行，哎。境内dns是223.5.5.5------------------ 原始邮件 ------------------
发件人: "istraw"<notifications@github.com>
发送时间: 2019年8月19日(星期一) 下午5:26
收件人: "2dust/v2rayNG"<v2rayNG@noreply.github.com>;
抄送: "abc906093117"<906093117@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [2dust/v2rayNG] 红米1S 安卓6.1 启动成功后仍然不能科学上网 (#73)



我刚换了只一加7，也遇到类似这个问题，用wifi就能访问，用4G就不行，后来下了BifrostV也是一样的状态，研究了一下，把远程DNS改成8.8.8.8就可以了，默认是1.1.1.1
 
&mdash;
