### ISSUE TITLE
不定期上不了网，需手动断开重连

### ISSUE THREAD

**Issue by Platway** [2dust/v2rayNG#73]
每过一段时间(几分钟至上小时不等)就上不了任何网站，表现为：用浏览器连接任意URL，过几十秒后超时提示无法解析域名。需要将v2rayNG断开再重连才能恢复。最新0.4.4版。十分感谢，祝愉快！

**Comment by sunjie21** [comment]
我遇到的情况是：在电梯或者地下停车场这些没有网络的地方出来后，不能连网。需要手动断开重新连接

**Comment by Platway** [comment]
这个问题挺影响使用的，过一会就要手动重连，感觉是某个进程被杀了

**Comment by Platway** [comment]
现在很少出现，不知是不是新版本改进了，先close了。谢谢关注！
