### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by 0xtechDev** [2dust/v2rayNG#736]
"Development guide
Android project under V2rayNG folder can be compiled directly in Android Studio, or using Gradle wrapper. But the v2ray core inside the aar is (probably) outdated.
The aar can be compiled from the Golang project under AndroidLibV2rayLite folder. For a quick start, read guide for Go Mobile and Makefiles for Go Developers

v2rayNG can run on Android Emulators, with minimum Android 5.0"

i have downloaded the latest source code , but after making the apk and opening the app , the app is still in version 1.0.2 or sthg , and the ui is different than the apk in the release ! , do i need to compile this aar golang thingy  ? if so how to do it please ? i downloaded gomobile etc , when i try >>>> gomobile build -target=android C:\Users\user\Desktop\go\v2rayNG-22\v2rayNG-22\v2rayNG-22\v2rayNG-1.4.11\v2rayNG-1.4.11\AndroidLibV2rayLite\libv2ray
C:\Users\user\go\bin\gomobile.exe: go build C:\Users\user\Desktop\go\v2rayNG-22\v2rayNG-22\v2rayNG-22\v2rayNG-1.4.11\v2rayNG-1.4.11\AndroidLibV2rayLite\libv2ray failed: exit status 1
cannot find package "C:\\Users\\user\\Desktop\\go\\v2rayNG-22\\v2rayNG-22\\v2rayNG-22\\v2rayNG-1.4.11\\v2rayNG-1.4.11\\AndroidLibV2rayLite\\libv2ray" in any of:
        c:\go\src\C:\Users\user\Desktop\go\v2rayNG-22\v2rayNG-22\v2rayNG-22\v2rayNG-1.4.11\v2rayNG-1.4.11\AndroidLibV2rayLite\libv2ray (from $GOROOT)
        C:\Users\user\go\src\C:\Users\user\Desktop\go\v2rayNG-22\v2rayNG-22\v2rayNG-22\v2rayNG-1.4.11\v2rayNG-1.4.11\AndroidLibV2rayLite\libv2ray (from $GOPATH)

**Comment by rurirei** [comment]
#682
