### ISSUE TITLE
不支持导入一些url

### ISSUE THREAD

**Issue by jdfq** [2dust/v2rayNG#738]
比如这个订阅地址：jiang.netlify.app/，v2rayn是支持导入其现在当中的ss的，但是v2rayng不支持。其中一个ss url如下：
ss://YWVzLTI1Ni1nY206eHBRd3lWNFc1RmRBNk5NQU5KSng3M1VTQDIuNTguMjQyLjQ1OjM4MDMz#shadowsocks%2F2.58.242.45%3A38033-ekytg

**Comment by xianren78** [comment]
我测试最新的1.4.12可以正常导入啊

**Comment by jdfq** [comment]
但是放在这个订阅地址中就不行：jiang.netlify.app/

**Comment by jdfq** [comment]
这个就不行：ss://YWVzLTI1Ni1nY206eHBRd3lWNFc1RmRBNk5NQU5KSng3M1VTQDIuNTguMjQxLjI3OjM4MDMz/#shadowsocks%2F2.58.241.27%3A38033-iwcqe
