### ISSUE TITLE
当订阅内容的alterId为空时，订阅失败，希望可以默认补为0

### ISSUE THREAD

**Issue by athenakia** [2dust/v2rayNG#739]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
当alterId为空时，自动补充为默认值0

### 实际行为
描述实际发生了什么
显示订阅失败

### 复现方法
1. 自行写一个简单的接口，返回一个alterId值为空字符串的节点链接的base64编码
2. 在v2rayNG添加订阅
3. 在v2rayNG更新订阅，显示“失败”

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by rurirei** [comment]
`alterId` must be nonNull, as works expected. makes ensure contents of your subscription.
