### ISSUE TITLE
更新1.4.12后使用xtls-rprx-direct模式连接，v2rayNG没法正确显示下载流量

### ISSUE THREAD

**Issue by zeratulcheng** [2dust/v2rayNG#741]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
启用v2rayNG的流量探测，能正常显示代理的下载流量

### 实际行为
更新1.4.12后，服务器也更新到了v2ray 4.32.1，配置使用xtls-rprx-direct模式连接
v2rayNG能正常使用，但是没法正确显示下载流量
之前使用1.4.11时，配置xtls-rprx-origin，能正常显示下载流量

### 复现方法
1.打开youtube，随便选择一个4k视频，一遍观看视频一遍查看v2rayNG流量显示，proxy和direct中均无下载流量显示
2.打开一个需要代理的网站，随便下载一个文件，proxy和direct中均无下载流量显示
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android 10，v2rayNG 1.4.12 服务器v2ray 4.32.1

**Comment by rurirei** [comment]
#684

**Comment by zeratulcheng** [comment]
> #684

感谢回复，我好像和他的环境不一样，我并没有使用自定义配置，是通过添加VLESS选项来添加远程服务器的，也没有他的那些配置参数

**Comment by 2dust** [comment]
https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80
流量统计问题可能和此功能有关

**Comment by RPRX** [comment]
v4.32.1 版本的 VLESS XTLS Direct Mode 自动切换到 ReadV 后会绕过读数据时的流量统计功能（可能会修复）

**Comment by zeratulcheng** [comment]
> v4.32.1 版本的 VLESS XTLS Direct Mode 自动切换到 ReadV 后会绕过读数据时的流量统计功能（可能会修复）

原来如此，感谢回复

**Comment by yuhan6665** [comment]
@rprx If you have ideas and wanna give me a few points, I can try to fix it.

**Comment by RPRX** [comment]
https://github.com/v2fly/v2ray-core/commit/f06ede1bc10be37acc18b6243d43d805c7a36c0b 应该修复了此问题，等待下个版本即可。

顺便发现的问题是，至少 v4.32.1 的流量统计存在非常神奇的全局降性能情况：具体表现为开启流量统计功能后，即使绕过了它的 Conn（即不统计）且有 ReadV，性能还是会大打折扣，很可能是它背后一直在做其它的事情。

其它传输组合开启流量统计后性能也会大减，除了有时多了一层 Conn 无法 ReadV 外，肯定还有流量统计带来的其它原因。

另外，我不确定 v2rayNG 关闭流量统计后是删掉 `"stats": {}` 了还是只是不收集数据了（正常应为前者）。

**Comment by RPRX** [comment]
发现直接向 `syscall.Conn` 写数据时，v2 实际上还会用到 WriteV，但同样是加一层 Conn（如统计的）就没此优化了，破案了。

具体来说，对于裸协议如 VMess，开哪边的统计（inbound、outbound），哪边就同时没 ReadV 和 WriteV。

流量统计还存在其它问题，等下会在 https://github.com/v2fly/v2ray-core/issues 发个 issue 说明。

**Comment by rurirei** [comment]
> In addition, I'm not sure if v2rayNG deletes "stats": {} after closing traffic statistics or just not collecting data (normally it should be the former)

@rprx the latter. object "stats" could be remain unless policy "uplink/downlink" enables to register stat counters when stat noneed.
