### ISSUE TITLE
测试全部配置真连接不好使

### ISSUE THREAD

**Issue by xixiri** [2dust/v2rayNG#742]
#519 # 预期行为
如果节点过多，点击测试全部配置真连接，应该自动完成，不需要再手工干预

### 实际行为
如果不干预，手机一会就灭屏，过会再打开，没完成，而且完成的不连续，中间有落下一部分节点，末尾也没完成。如果手工跟随进度向下滑动保持屏幕常亮，可以完成

### 复现方法
1.有一个很长的列表节点
2.点击测试全部配置真连接
3.问题如上所述出现了

### 日志信息
<details>
--------- beginning of system
--------- beginning of main
11-12 11:39:15.811 I/GoLog   (21474): 2020/11/12 03:39:15 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:19.775 I/GoLog   (21474): 2020/11/12 03:39:19 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:21.187 I/GoLog   (21474): 2020/11/12 03:39:21 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:21.783 I/GoLog   (21474): 2020/11/12 03:39:21 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:22.009 I/GoLog   (21474): 2020/11/12 03:39:22 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/shadowsocks: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp 104.224.141.225:700: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
11-12 11:39:22.136 I/GoLog   (21474): 2020/11/12 03:39:22 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:23.214 I/GoLog   (21474): 2020/11/12 03:39:23 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:23.654 I/GoLog   (21474): 2020/11/12 03:39:23 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:24.877 I/GoLog   (21474): 2020/11/12 03:39:24 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:25.715 I/GoLog   (21474): 2020/11/12 03:39:25 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:39:25.975 I/GoLog   (21474): 2020/11/12 03:39:25 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:13.363 I/GoLog   (21474): 2020/11/12 03:43:13 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:13.897 I/GoLog   (21474): 2020/11/12 03:43:13 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:14.350 I/GoLog   (21474): 2020/11/12 03:43:14 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:16.328 I/GoLog   (21474): 2020/11/12 03:43:16 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:16.705 I/GoLog   (21474): 2020/11/12 03:43:16 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:16.811 I/GoLog   (21474): 2020/11/12 03:43:16 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:18.708 I/GoLog   (21474): 2020/11/12 03:43:18 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:21.870 I/GoLog   (21474): 2020/11/12 03:43:21 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:21.885 I/GoLog   (21474): 2020/11/12 03:43:21 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:21.941 I/GoLog   (21474): 2020/11/12 03:43:21 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:23.884 I/GoLog   (21474): 2020/11/12 03:43:23 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:25.052 I/GoLog   (21474): 2020/11/12 03:43:25 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:25.363 I/GoLog   (21474): 2020/11/12 03:43:25 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
11-12 11:43:26.476 I/GoLog   (21474): 2020/11/12 03:43:26 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:28.054 I/GoLog   (21474): 2020/11/12 03:43:28 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:35.153 I/GoLog   (21474): 2020/11/12 03:43:35 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:35.947 I/GoLog   (21474): 2020/11/12 03:43:35 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://usa.usaxyz.xyz/7b233/):  > dial tcp 198.23.236.132:443: i/o timeout v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://usa.usaxyz.xyz/7b233/):  > dial tcp: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
11-12 11:43:39.638 I/GoLog   (21474): 2020/11/12 03:43:39 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:40.492 I/GoLog   (21474): 2020/11/12 03:43:40 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://13.248.177.18:40205/honda):  > dial tcp 13.248.177.18:40205: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
11-12 11:43:41.268 I/GoLog   (21474): 2020/11/12 03:43:41 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:42.058 I/GoLog   (21474): 2020/11/12 03:43:42 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://13.248.155.0:40206/honda):  > dial tcp 13.248.155.0:40206: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed
11-12 11:43:48.346 I/GoLog   (21474): 2020/11/12 03:43:48 [Warning] v2ray.com/core: V2Ray 4.32.1 started
11-12 11:43:49.157 I/GoLog   (21474): 2020/11/12 03:43:49 [Warning] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (ws://76.223.42.214:40204/honda):  > dial tcp 76.223.42.214:40204: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by xixiri** [comment]
这是中间一部分的截屏

![Screenshot_20201112_115844](https://user-images.githubusercontent.com/19706511/98893916-8a814780-24de-11eb-9e3b-073fbdf2def3.jpg)

**Comment by yuhan6665** [comment]
Thanks for reporting this issue. I will plan to fix it.

**Comment by AnotiaWang** [comment]
还有个建议，希望能保存测试延迟结果，每次重启App之后结果都没了，需要重新测试

**Comment by xixiri** [comment]
> 还有个建议，希望能保存测试延迟结果，每次重启App之后结果都没了，需要重新测试

没有啊，现在就是会保存的呀

**Comment by AnotiaWang** [comment]
> > 还有个建议，希望能保存测试延迟结果，每次重启App之后结果都没了，需要重新测试
> 
> 没有啊，现在就是会保存的呀

如果没有测试完就关闭APP就不会保存。

主要是测试一次用的时间太长，并且如你最开始所说，还要保持始终亮屏，还要手动滚动列表…很麻烦

**Comment by xixiri** [comment]
> > > 还有个建议，希望能保存测试延迟结果，每次重启App之后结果都没了，需要重新测试
> > 
> > 
> > 没有啊，现在就是会保存的呀
> 
> 如果没有测试完就关闭APP就不会保存。
> 
> 主要是测试一次用的时间太长，并且如你最开始所说，还要保持始终亮屏，还要手动滚动列表…很麻烦

它是有bug，这个问题解决后，你说的那个问题应该也就消失了

**Comment by yuhan6665** [comment]
fixed in https://github.com/2dust/v2rayNG/pull/750

**Comment by xixiri** [comment]
> fixed in #750

thank you! ni xin ku le
