### ISSUE TITLE
如果先开启代理后联网会导致无法使用

### ISSUE THREAD

**Issue by AnotiaWang** [2dust/v2rayNG#743]
未连WiFi情况下，先开启代理，然后打开移动数据，代理无法使用
Android 10
测试版1.4.12

**Comment by rurirei** [comment]
it is of expected as not bug.

**Comment by yesmiley** [comment]
Make sure the `address` in your configuration is a real IP, instead of a domain name, then thing should be solved.

**Comment by AnotiaWang** [comment]
okay
But why won't it work when I am using a domain name?

**Comment by if1y** [comment]
> okay
> But why won't it work when I am using a domain name?

V2ray need to query the dns server to get the real IP first

**Comment by rurirei** [comment]
good answer as above.
