### ISSUE TITLE
安卓版本分应用代理添加新应用没有立即刷新，手动关闭代理后再打开才生效

### ISSUE THREAD

**Issue by thrt520asd** [2dust/v2rayNG#744]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
添加应用后立即生效，不需要重启代理

### 实际行为
重启代理后才生效

### 复现方法
1.
2.
3.

### 环境信息
v2rayNG版本1.3.3 
手机型号小米10pro
系统版本 MIUI 11.0.18

**Comment by rurirei** [comment]
won't apply as impossible.
