### ISSUE TITLE
read proxy from another proxy app like adguard

### ISSUE THREAD

**Issue by yuanshdn** [2dust/v2rayNG#746]
Hi
the new adguard vpn in android has the ability to be on socks 5 mode
I want to use adguard vpn with V2ray rules is that possible?

**Comment by rurirei** [comment]
set up your Adguard http proxy mode: 127.0.0.1:10809

**Comment by rurirei** [comment]
> set up your Adguard to VPN loaded and its http proxy mode: 127.0.0.1:10809

it is:
- v2rayNG: Proxy-Only mode
- Adguard: VPN mode and enables it HTTP Proxy to 127.0.0.1:10809 (is this port right? @yuhan6665 )

**Comment by yuanshdn** [comment]
I wanted the oppsite. This way will send all traffic through adguard first while rules are implemented on the second round. So rules won't work.
I made adguard with sock5 mode and connected to a location. Then added a socks5 proxy in v2ray with server:127.0.0.1 port:1080
And it worked.
Now ím using adguard proxy with v2ray rules.

**Comment by rurirei** [comment]
you need custom config:
```jsonc
  // routing to your adguard
  {
     "redirect": "127.0.0.1:port"  // your adguard socks port
  }
```

**Comment by rurirei** [comment]
> I wanted the oppsite. This way will send all traffic through adguard first while rules are implemented on the second round. So rules won't work.
> I made adguard with sock5 mode and connected to a location. Then added a socks5 proxy in v2ray with server:127.0.0.1 port:1080
> And it worked.
> Now ím using adguard proxy with v2ray rules.

no, it worked. you must use v2rayNG as second.

**Comment by yuanshdn** [comment]
> I wanted the oppsite. This way will send all traffic through adguard first while rules are implemented on the second round. So rules won't work.
> I made adguard with sock5 mode and connected to a location. Then added a socks5 proxy in v2ray with server:127.0.0.1 port:1080
> And it worked.
> Now ím using adguard proxy with v2ray rules.

This way it works actually
Sock5 proxy mode on adguard
Vpn mode on v2ray
Add sock5 manually in v2ray

**Comment by rurirei** [comment]
your outbound is adguard not v2rayNG, you cannot use v2rayNG now in fact..

**Comment by rurirei** [comment]
> > set up your Adguard to VPN loaded and its http proxy mode: 127.0.0.1:10809
> 
> it is:
> 
> * v2rayNG: Proxy-Only mode
> * Adguard: VPN mode and enables it HTTP Proxy to 127.0.0.1:10809 (is this port right? @yuhan6665 )

this worked as your expected, no issue of any rule of adguard or v2ray.

**Comment by yuanshdn** [comment]
> > > set up your Adguard to VPN loaded and its http proxy mode: 127.0.0.1:10809
> > 
> > 
> > it is:
> > 
> > * v2rayNG: Proxy-Only mode
> > * Adguard: VPN mode and enables it HTTP Proxy to 127.0.0.1:10809 (is this port right? @yuhan6665 )
> 
> this worked as your expected, no issue of any rule of adguard or v2ray.

how do I enable adguard http proxy?
there is no such option

**Comment by yuhan6665** [comment]
https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy

**Comment by yuanshdn** [comment]
> https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy

this app is not a proxy or vpn
what I meant was this new app
https://adguard-vpn.com/en/welcome.html

**Comment by yuhan6665** [comment]
I suspect you can't use v2ray with this app. But check with them as well.

**Comment by yuanshdn** [comment]
> I suspect you can't use v2ray with this app. But check with them as well.

I set the mode on adguard vpn as: socks5 and connected to a server
then added a socks5 proxy manually in v2ray with server:localhost port:1080 (from adguard)
then set the mode on v2ray as vpn
it works
