### ISSUE TITLE
我想使用其它vpn应用，然后用手机作为代理服务器给电脑fq

### ISSUE THREAD

**Issue by ggsmmm** [2dust/v2rayNG#749]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

以前用servers ultimate pro是可以的，现在不行了，不知道是不是android 10的原因。v2rayNG的代理服务器功能也不能单独使用🤔

**Comment by ghost** [comment]
如果是以纯http代理的方式想要分享给其他设备使用的话，那么先开启“允许来自局域网的连接”，之后其他设备连上该设备的热点，把代理设置成 网关ip+本地端口（在v2rayng设置中显示的本地http代理端口）就行了，目前无需借助任何三方软件。
不过，透明代理的话（就是设备连接后不需要做任何设置就可以自动代理）则需要Android设备root，且使用中继vpn的软件才能实现这样的效果。
