### ISSUE TITLE
Customize the method field on Protocol Trojan

### ISSUE THREAD

**Issue by lxsjgzs** [2dust/v2rayNG#751]
1. The time I customize the config file of trojan, the field ''method'' occured me and the default set to ''chacha20'' (by export full configuration to clipboard). I wonder if I can change this method such as "aes-128-gcm" or other fields.
2. If it can be changed, what accessible field can be filled, and be extended to v2ray-core?

Here is the key configuration.

      "protocol": "trojan",
      "settings": {
        "servers": [
          {
            "address": "a.b.x.y",
            "level": 8,
            "method": "chacha20",  // This is what I want to consult.
            "ota": false,
            "password": "*********",
            "port": 443
          }
        ]

**Comment by yuhan6665** [comment]
Only fields defined in v2ray are supported. https://www.v2fly.org/config/protocols/trojan.html#outboundconfigurationobject

**Comment by lxsjgzs** [comment]
> Only fields defined in v2ray are supported. https://www.v2fly.org/config/protocols/trojan.html#outboundconfigurationobject

Thanks for reply, and in fact I tried to force the method to aes-128-gcm it also works. I learned in TG's Group that the method can filled with the field "chacha20", "aes-128-gcm" and "aes-256-gcm".
