### ISSUE TITLE
issues with reading proxy from another app

### ISSUE THREAD

**Issue by fsheidaiee** [2dust/v2rayNG#752]
Hi I have two questions
1. in windows 10 I open tor program and then it connects to a server
then I add a socks5 proxy manually in v2rayN with these specifications;
server:localhost
port:9050
which are for tor.
I have no problem
but in android I use tor and then set a similar socks5 proxy like I did in windows 10
but I get many errors and many site won't open. only telegram works well.
whats the reason? is it because in android, v2rayNG sets proxy on dns?
2. how can I prevent v2rayNG from proxify dns on vpn mode? (or both vpn and proxy mode?)
thanks

**Comment by yuhan6665** [comment]
What is the purpose of v2ray in this use case?

**Comment by yuanshdn** [comment]
> What is the purpose of v2ray in this use case?

using rules

**Comment by fsheidaiee** [comment]
> What is the purpose of v2ray in this use case?

using v2ray specific rules

**Comment by yuhan6665** [comment]
Ok, probably is the issue with UDP traffic, I would redirect all UDP to Freedom outbound. DNS can be handled separately.

**Comment by fsheidaiee** [comment]
> Ok, probably is the issue with UDP traffic, I would redirect all UDP to Freedom outbound. DNS can be handled separately.

can you help me with both answers?
for the first question you are suggesting that in the next update the udp traffic will be redirected to freedom outbound?
for the second question; how can I handle dns separately?

**Comment by yuhan6665** [comment]
You need to customise your configuration. Documentation has all the answers
https://www.v2fly.org/config/overview.html

**Comment by fsheidaiee** [comment]
> You need to customise your configuration. Documentation has all the answers
> https://www.v2fly.org/config/overview.html

I have no experties in these codings. but Can I use my v2rayN configuration in v2rayNG? because in windows I don't have this problem.
and for the DNS what should I exactly do?

**Comment by fsheidaiee** [comment]
> You need to customise your configuration. Documentation has all the answers
> https://www.v2fly.org/config/overview.html

the problem was these lines in the config;
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
      "8.8.8.8"
    ]
  },
I removed these lines in custom config and the problem got fixed.
