### ISSUE TITLE
配置文件里的所有地址都无法使用

### ISSUE THREAD

**Issue by zoeyu666** [2dust/v2rayNG#753]
### 预期行为
我的vpn之前一直都是正常的，配置好订阅设置后，只需要更新订阅，就可以使用VPN了

### 实际行为
但是最近这些连接全部都失效了。我可以连接上，但是点击测试后，都报错connection closed by peer，我无法使用VPN了

**Comment by BreakshadowCN** [comment]
建议不要提供完整的vmess，可能会导致他人使用你的VPN服务。如果愿意的话请删去这些vmess信息。
从connection closed by peer看可能是被墙，但是我这边可以正常Ping通，也可以访问80端口，因此我猜测可能是被短时间封锁了。
可以稍后再试，或者向VPN服务的提供者反馈。

**Comment by zoeyu666** [comment]
> 建议不要提供完整的vmess，可能会导致他人使用你的VPN服务。如果愿意的话请删去这些vmess信息。
> 从connection closed by peer看可能是被墙，但是我这边可以正常Ping通，也可以访问80端口，因此我猜测可能是被短时间封锁了。
> 可以稍后再试，或者向VPN服务的提供者反馈。

**Comment by zoeyu666** [comment]
我尝试了联系之前VPN服务的提供者，已经失联了，想问问是否有其他渠道可以提供VPN的服务呢
