### ISSUE TITLE
连接成功后，有时会断线的问题

### ISSUE THREAD

**Issue by ali99188** [2dust/v2rayNG#755]
连接成功后，在网速很好的时候，有时也会突然断线，比如正在play商店下载软件，本来挺好的，有时就下载不动了，一检查，原来是这个软件自动停线了，再次点击即可再次连接成功。
日志我没有找到，我是用电脑登录反馈的，只有这一点问题，其它都很好，这个软件比别的能用v2ray订阅的代理软件速度更快更好，只是有时出现这个问题，有时就很好。希望能改進稳定性，谢谢！

**Comment by ali99188** [comment]
日志：
**--------- beginning of main
11-22 10:50:37.941 D/com.v2ray.ang(19924): sendFd tries: 0
11-22 10:50:37.949 I/tun2socks(24928): NOTICE(tun2socks): entering event loop
11-22 10:50:38.011 I/GoLog   (19924): udp:127.0.0.1:42284 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:50:38.022 I/GoLog   (19924): udp:127.0.0.1:55932 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:50:38.254 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:38.264 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:38.799 I/GoLog   (19924): tcp:127.0.0.1:52558 accepted tcp:172.217.170.35:443 [proxy] 
11-22 10:50:38.804 I/GoLog   (19924): tcp:127.0.0.1:52562 accepted tcp:172.217.170.35:443 [proxy] 
11-22 10:50:39.062 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:39.063 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:39.465 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:40.471 I/GoLog   (19924): udp:127.0.0.1:60471 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:50:40.723 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:41.251 I/GoLog   (19924): tcp:127.0.0.1:52580 accepted tcp:172.217.170.46:443 [proxy] 
11-22 10:50:41.496 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:44.995 I/GoLog   (19924): udp:127.0.0.1:51313 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:50:45.234 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:45.719 I/GoLog   (19924): tcp:127.0.0.1:52590 accepted tcp:172.217.170.74:443 [proxy] 
11-22 10:50:45.958 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:47.075 I/GoLog   (19924): udp:127.0.0.1:44384 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:50:47.319 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:47.813 I/GoLog   (19924): udp:127.0.0.1:34074 accepted udp:41.206.98.14:443 [proxy] 
11-22 10:50:48.056 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:50:52.546 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:10.113 I/GoLog   (19924): tcp:127.0.0.1:52626 accepted tcp:172.217.170.74:443 [proxy] 
11-22 10:51:10.358 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:18.361 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:22.561 I/GoLog   (19924): udp:127.0.0.1:58913 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:22.805 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:23.323 I/GoLog   (19924): udp:127.0.0.1:45454 accepted udp:41.206.98.13:443 [proxy] 
11-22 10:51:23.572 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:26.367 I/GoLog   (19924): udp:127.0.0.1:57259 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:26.615 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:26.745 I/GoLog   (19924): udp:127.0.0.1:39290 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:26.768 I/GoLog   (19924): udp:127.0.0.1:59351 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:26.777 I/GoLog   (19924): udp:127.0.0.1:51573 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:26.985 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.011 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.017 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.107 I/GoLog   (19924): udp:127.0.0.1:52339 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:27.153 I/GoLog   (19924): udp:127.0.0.1:36000 accepted udp:8.8.8.8:53 [proxy] 
11-22 10:51:27.154 I/GoLog   (19924): udp:127.0.0.1:50441 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:27.181 I/GoLog   (19924): udp:127.0.0.1:42235 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:27.350 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.392 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.395 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.431 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:27.849 I/GoLog   (19924): tcp:127.0.0.1:52670 accepted tcp:216.58.223.131:443 [proxy] 
11-22 10:51:27.935 I/GoLog   (19924): udp:127.0.0.1:56682 accepted udp:172.217.170.36:443 [proxy] 
11-22 10:51:27.940 I/GoLog   (19924): udp:127.0.0.1:60281 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:28.092 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:28.175 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:28.181 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:28.185 I/GoLog   (19924): udp:127.0.0.1:51370 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:28.424 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:28.688 I/GoLog   (19924): udp:127.0.0.1:51618 accepted udp:172.217.170.45:443 [proxy] 
11-22 10:51:28.919 I/GoLog   (19924): tcp:127.0.0.1:52684 accepted tcp:140.82.121.3:443 [proxy] 
11-22 10:51:28.933 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:29.041 I/GoLog   (19924): tcp:127.0.0.1:52690 accepted tcp:172.217.170.45:443 [proxy] 
11-22 10:51:29.166 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:29.281 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:30.913 I/GoLog   (19924): udp:127.0.0.1:49912 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:30.917 I/GoLog   (19924): udp:127.0.0.1:48677 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:30.917 I/GoLog   (19924): udp:127.0.0.1:47182 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:30.920 I/GoLog   (19924): udp:127.0.0.1:40473 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:31.151 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:31.157 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:31.158 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:31.165 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:31.818 I/GoLog   (19924): udp:127.0.0.1:45448 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:31.838 I/GoLog   (19924): tcp:127.0.0.1:52706 accepted tcp:185.199.109.154:443 [proxy] 
11-22 10:51:31.838 I/GoLog   (19924): tcp:127.0.0.1:52714 accepted tcp:185.199.109.154:443 [proxy] 
11-22 10:51:31.838 I/GoLog   (19924): tcp:127.0.0.1:52710 accepted tcp:185.199.109.154:443 [proxy] 
11-22 10:51:31.838 I/GoLog   (19924): udp:127.0.0.1:55409 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:31.838 I/GoLog   (19924): udp:127.0.0.1:37199 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:32.063 I/GoLog   (19924): udp:127.0.0.1:47635 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:32.159 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.160 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.160 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.160 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.161 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.161 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.311 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:32.830 I/GoLog   (19924): udp:127.0.0.1:58692 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:32.838 I/GoLog   (19924): tcp:127.0.0.1:52730 accepted tcp:172.217.170.35:443 [proxy] 
11-22 10:51:32.846 I/GoLog   (19924): udp:127.0.0.1:40829 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:32.848 I/GoLog   (19924): udp:127.0.0.1:46645 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:33.073 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:33.075 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:33.086 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:33.090 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:33.725 I/GoLog   (19924): udp:127.0.0.1:54896 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:33.728 I/GoLog   (19924): udp:127.0.0.1:51621 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:33.730 I/GoLog   (19924): udp:127.0.0.1:44622 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:33.967 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:33.972 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:33.972 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:34.321 I/GoLog   (19924): udp:127.0.0.1:50976 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:34.349 I/GoLog   (19924): udp:127.0.0.1:43618 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:34.364 I/GoLog   (19924): udp:127.0.0.1:35384 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:34.446 I/GoLog   (19924): tcp:127.0.0.1:52760 accepted tcp:185.199.109.154:443 [proxy] 
11-22 10:51:34.448 I/GoLog   (19924): tcp:127.0.0.1:52756 accepted tcp:140.82.121.3:443 [proxy] 
11-22 10:51:34.565 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:34.593 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:34.605 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:34.687 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:34.691 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:34.781 I/GoLog   (19924): udp:127.0.0.1:40135 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:35.027 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:35.128 I/GoLog   (19924): tcp:127.0.0.1:52778 accepted tcp:216.58.223.138:443 [proxy] 
11-22 10:51:35.128 I/GoLog   (19924): tcp:127.0.0.1:52776 accepted tcp:216.58.223.138:443 [proxy] 
11-22 10:51:35.174 I/GoLog   (19924): udp:127.0.0.1:42449 accepted udp:216.58.223.138:443 [proxy] 
11-22 10:51:35.370 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:35.373 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:35.389 I/GoLog   (19924): udp:127.0.0.1:51414 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:35.423 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:35.550 I/GoLog   (19924): tcp:127.0.0.1:52792 accepted tcp:140.82.121.5:443 [proxy] 
11-22 10:51:35.579 I/GoLog   (19924): tcp:127.0.0.1:52798 accepted tcp:3.212.155.99:443 [proxy] 
11-22 10:51:35.654 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:35.794 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:35.819 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:36.678 I/GoLog   (19924): udp:127.0.0.1:41775 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:36.923 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:37.433 I/GoLog   (19924): udp:127.0.0.1:40344 accepted udp:216.58.223.138:443 [proxy] 
11-22 10:51:37.679 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:38.621 I/GoLog   (19924): udp:127.0.0.1:47317 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:38.622 I/GoLog   (19924): udp:127.0.0.1:34188 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:51:38.862 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:38.864 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:39.381 I/GoLog   (19924): tcp:127.0.0.1:52812 accepted tcp:172.217.170.3:443 [proxy] 
11-22 10:51:39.394 I/GoLog   (19924): tcp:127.0.0.1:52818 accepted tcp:216.58.223.142:443 [proxy] 
11-22 10:51:39.626 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:39.634 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:51:54.779 I/GoLog   (19924): udp:127.0.0.1:40357 accepted udp:41.206.98.14:443 [proxy] 
11-22 10:51:55.031 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:26.337 I/GoLog   (19924): tcp:127.0.0.1:52872 accepted tcp:172.217.170.74:443 [proxy] 
11-22 10:52:26.338 I/GoLog   (19924): tcp:127.0.0.1:52870 accepted tcp:172.217.170.74:443 [proxy] 
11-22 10:52:26.582 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:26.583 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:26.778 I/GoLog   (19924): udp:127.0.0.1:50188 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:52:27.017 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:27.503 I/GoLog   (19924): tcp:127.0.0.1:52882 accepted tcp:172.217.170.35:443 [proxy] 
11-22 10:52:27.742 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:28.965 I/GoLog   (19924): udp:127.0.0.1:37065 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:52:29.211 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:29.700 I/GoLog   (19924): tcp:127.0.0.1:52890 accepted tcp:172.217.170.14:80 [proxy] 
11-22 10:52:29.940 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:30.599 I/GoLog   (19924): udp:127.0.0.1:57768 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:52:30.844 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:31.342 I/GoLog   (19924): tcp:127.0.0.1:52898 accepted tcp:41.206.98.12:80 [proxy] 
11-22 10:52:31.586 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:33.018 I/GoLog   (19924): udp:127.0.0.1:49551 accepted udp:172.217.170.35:443 [proxy] 
11-22 10:52:33.257 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:37.074 I/GoLog   (19924): udp:127.0.0.1:60951 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:52:37.318 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:37.850 I/GoLog   (19924): tcp:127.0.0.1:52912 accepted tcp:172.217.170.80:80 [proxy] 
11-22 10:52:38.055 I/GoLog   (19924): tcp:127.0.0.1:52914 accepted tcp:172.217.170.80:80 [proxy] 
11-22 10:52:38.096 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:38.305 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:39.840 I/GoLog   (19924): udp:127.0.0.1:59839 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:52:40.086 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:40.575 I/GoLog   (19924): tcp:127.0.0.1:52928 accepted tcp:41.206.98.13:80 [proxy] 
11-22 10:52:40.819 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:42.638 I/GoLog   (19924): tcp:127.0.0.1:52942 accepted tcp:172.217.170.80:443 [proxy] 
11-22 10:52:42.877 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:49.554 I/GoLog   (19924): udp:127.0.0.1:43282 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:52:49.795 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:52:50.290 I/GoLog   (19924): tcp:127.0.0.1:52950 accepted tcp:172.217.170.3:443 [proxy] 
11-22 10:52:50.532 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:53:02.383 I/GoLog   (19924): udp:127.0.0.1:37597 accepted udp:1.1.1.1:53 [proxy] 
11-22 10:53:02.628 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:53:03.144 I/GoLog   (19924): tcp:127.0.0.1:52972 accepted tcp:216.58.223.136:443 [proxy] 
11-22 10:53:03.387 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:53:38.910 I/GoLog   (19924): [Warning] [3341742760] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1006 (abnormal closure): unexpected EOF
11-22 10:54:00.398 I/GoLog   (19924): tcp:127.0.0.1:53036 accepted tcp:172.217.170.74:443 [proxy] 
11-22 10:54:00.647 I/GoLog   (19924): Using Prepared: 102.223.72.247
11-22 10:54:14.685 D/com.v2ray.ang(19924): tun2socks destroy
11-22 10:54:14.686 I/tun2socks(24928): NOTICE(tun2socks): termination requested
11-22 10:54:14.686 I/tun2socks(24928): NOTICE(tun2socks): tearing down
11-22 10:54:14.687 I/tun2socks(24928): NOTICE(tun2socks): Free TCP connections
11-22 10:54:14.687 I/tun2socks(24928): NOTICE(tun2socks): exiting
**

**Comment by rurirei** [comment]
#728 @yuhan6665
