### ISSUE TITLE
在小米10 miui12上，不能使用。

### ISSUE THREAD

**Issue by kusobao** [2dust/v2rayNG#757]
### 预期行为
其他手机上ping是200ms，能正常使用。

### 实际行为
在小米10的miui12上，安装最新版本，能连接服务器，但ping是8000ms，网页都无法浏览。

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
手机小米10，miui12

**Comment by even0306** [comment]
请检查自己相关配置，我的miui12运行良好

**Comment by ramocky** [comment]
同样  很奇怪 ..

**Comment by GarfieldR** [comment]
我的小米10也是，低位的端口号被禁了，443都不能用，能ping节点不能做业务，小米就是垃圾中的垃圾

**Comment by lpxnvk** [comment]
我的也不能用 配置是从qr扫v2rayng的 rom是欧版miui12 
报错： fail to detect internet connection: io : read/write on closed pipe
