### ISSUE TITLE
安卓9-VLESS协议，不能解析域名IP

### ISSUE THREAD

**Issue by taohuadongle** [2dust/v2rayNG#765]
安卓9，添加了VLESS协议，能够正常测速，但是浏览器等无法打开任何域名，使用IP可以；
同手机，添加VMESS协议的节点，正常使用；

安卓10，电脑端以上问题都不存在……

目前已经检查了，私人DNS没有开启

**Comment by rurirei** [comment]
do you confirmed not work only on vless? log needed.

**Comment by RPRX** [comment]
建议升级版本

**Comment by taohuadongle** [comment]
> 建议升级版本

升级最新后问题已解决，之前在市场下载的没有注意版本
