### ISSUE TITLE
建议添加黑名单模式与白名单模式

### ISSUE THREAD

**Issue by lyaaz** [2dust/v2rayNG#768]
黑名单模式默认直连，规则代理；
白名单模式默认代理，规则直连。

或者开放配置文件编辑。

**Comment by ghost** [comment]
设置-路由设置-自定义规则 可以按照ip域名设置分流。
设置-分应用代理 可以按照app进行分流设置。

一直都有配置文件编辑的，只要导入配置的方式为 “从剪贴板导入完整配置” 就行。
