### ISSUE TITLE
VMESS正常 VLESS连接后不通

### ISSUE THREAD

**Issue by r-eee** [2dust/v2rayNG#771]
搭的vless tcp xtls direct
手机安卓10  NG用过1.5和1.4.13版本vless都不通 都装的arm64-v8a 其他版本装不上
有另外一个VPS是vmess手机上工作正常 
有问题的VLESS在电脑上正常
手机上配置没输错
在NG上测试TCPING能通 测试真连接不通
手机的私人VPN无论开关外网都不通

### 日志信息
--------- beginning of main
--------- beginning of system
12-01 15:01:54.399 I/GoLog   (27128): loading core config
12-01 15:01:54.399 I/GoLog   (27128): Preparing Domain: glxradio.ml:443
12-01 15:01:54.403 I/GoLog   (27128): Prepare Result:
12-01 15:01:54.403 I/GoLog   (27128):  Domain: glxradio.ml
12-01 15:01:54.403 I/GoLog   (27128):  Port: 443
12-01 15:01:54.403 I/GoLog   (27128):  IPs: [67.230.168.27]
12-01 15:01:54.756 I/GoLog   (27128): new core
12-01 15:01:54.763 I/GoLog   (27128): start core
12-01 15:01:54.764 I/GoLog   (27128): [Warning] github.com/xtls/xray-core/v1/core: Xray 1.0.0 started
12-01 15:01:54.799 D/com.v2ray.ang(27128): [/data/app/com.v2ray.ang-2nvFyNkjIMaGYd8RPUV0gQ==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
12-01 15:01:54.802 D/com.v2ray.ang(27128): Process[pid=14121, hasExited=false]
12-01 15:01:54.802 D/com.v2ray.ang(27128): /data/user/0/com.v2ray.ang/files/sock_path
12-01 15:01:54.812 I/tun2socks(14121): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
12-01 15:01:54.852 D/com.v2ray.ang(27128): sendFd tries: 0
12-01 15:01:54.854 I/tun2socks(14121): NOTICE(tun2socks): entering event loop
12-01 15:01:57.353 I/GoLog   (27128): Using Prepared: 67.230.168.27
12-01 15:01:58.845 I/GoLog   (27128): tcp:127.0.0.1:44200 accepted tcp:91.108.56.196:443 [proxy] 
12-01 15:01:59.040 I/GoLog   (27128): Using Prepared: 67.230.168.27
12-01 15:02:01.341 I/GoLog   (27128): Using Prepared: 67.230.168.27
12-01 15:02:03.344 I/GoLog   (27128): tcp:127.0.0.1:44216 accepted tcp:91.108.56.196:443 [proxy] 
12-01 15:02:03.546 I/GoLog   (27128): Using Prepared: 67.230.168.27
12-01 15:02:05.348 I/GoLog   (27128): Using Prepared: 67.230.168.27
12-01 15:02:05.551 D/com.v2ray.ang(27128): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe
12-01 15:02:07.769 I/GoLog   (27128): tcp:127.0.0.1:44228 accepted tcp:91.108.56.196:443 [proxy] 
12-01 15:02:07.991 I/GoLog   (27128): Using Prepared: 67.230.168.27

**Comment by ghost** [comment]
看日志文件没有发现任何连接问题。请检查以下 设置-远程dns 的选定吧。把它修改成 8.8.8.8 看看？这可能是无法打开网页的原因。

**Comment by r-eee** [comment]
也还是不行 我改这些设置测试的过程中 那另外一个vmess一直是通的 
就是vless的打不开外网 测试真连接显示-1ms

**Comment by RPRX** [comment]
需要提供服务端版本号及配置文件

**Comment by HibernantBear** [comment]
4.33和4.22之间无法互通，桌面版最新版匹配，但是这个客户端只到了4.32
