### ISSUE TITLE
V2rayng无法ping，但是tcping可以，流量探测已关闭

### ISSUE THREAD

**Issue by sachmx001** [2dust/v2rayNG#772]
如题
但是开clash可以ping通外网，（都是安卓版）
是V2rayng关闭了icmp协议么？按道理已经转发全部流量了，就算ping是链路层，也应该有效的啊……你看clash就可以

**Comment by RPRX** [comment]
其实现在流行的这些代理协议都不支持 ICMP

**Comment by sachmx001** [comment]
但是开clash就可以ping，这又怎么说呢？同一个协议，同一个节点，同一个配置



---原始邮件---
发件人: "RPRX"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 凌晨1:53
收件人: "2dust/v2rayNG"<v2rayNG@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [2dust/v2rayNG] V2rayng无法ping，但是tcping可以，流量探测已关闭 (#772)




 
其实现在流行的这些代理协议都不支持 ICMP

**Comment by RPRX** [comment]
比如什么样的协议+传输组合，以及 ping 哪里？

**Comment by sachmx001** [comment]
协议传输组合？v2ray trojan，传输是什么意思？ping的肯定是外网了，翻墙才能访问的外网，你看我上下文意思不就明白了？
反正有一点，我上面说了，同样的节点线路，用clash就可以的，那说明就不是节点线路的问题了



---原始邮件---
发件人: "RPRX"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 上午7:33
收件人: "2dust/v2rayNG"<v2rayNG@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [2dust/v2rayNG] V2rayng无法ping，但是tcping可以，流量探测已关闭 (#772)




 
比如什么样的协议+传输组合，以及 ping 哪里？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "RPRX"<notifications@github.com&gt;
发送时间: 2020年12月2日(周三) 上午7:33
收件人: "2dust/v2rayNG"<v2rayNG@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"sachmx001"<sachmx001@qq.com&gt;;
主题: Re: [2dust/v2rayNG] V2rayng无法ping，但是tcping可以，流量探测已关闭 (#772)




 
比如什么样的协议+传输组合，以及 ping 哪里？

**Comment by ailenli** [comment]
ping 是ICMP协议，v2ray代理不了。
clash是全局代理，ICMP可以代理。
如果想用v2ray，还想ping。可以用tun2sock方案

**Comment by yuhan6665** [comment]
It is not supported with current tun2socks
https://github.com/ambrop72/badvpn/issues/33
Looks like go-tun2socks support it?
https://github.com/eycorsican/go-tun2socks/blob/master/core/c/core/ipv4/icmp.c

**Comment by sachmx001sb** [comment]
![image](https://user-images.githubusercontent.com/80387117/110602329-dc9e5500-81c0-11eb-9715-24393f181346.png)
![image](https://user-images.githubusercontent.com/80387117/110602360-e4f69000-81c0-11eb-88bf-c9c5168f255f.png)
![image](https://user-images.githubusercontent.com/80387117/110602424-f770c980-81c0-11eb-9ef5-ee6c7ad386ab.png)
![image](https://user-images.githubusercontent.com/80387117/110602735-3ef75580-81c1-11eb-873c-f316bdac9b51.png)
https://github.com/Dreamacro/clash/discussions/969
http://bbs.lytmh.com.cn/thread-363503-1-1.html

**Comment by huweitianc** [comment]
老毛子固件v2不能用tcping通，ping不通的节点
