### ISSUE TITLE
升级到新版本后无法使用

### ISSUE THREAD

**Issue by rorymw** [2dust/v2rayNG#773]
PC端可正常使用，手机升级到最新版本后无法使用，手机端配置无误，提示 Get "http://www.google.com/gen_204": io: read/write on closed pipe，重新下载旧版本后还是无法使用。

**Comment by RPRX** [comment]
需要更多信息

**Comment by NichtsHsu** [comment]
我也是。
手机和MUMU模拟器都是报同样的错。服务器是买的just my socks。

**Comment by yxhit** [comment]
我的也一样，最新版无法使用，服务器核心4.33.

**Comment by RPRX** [comment]
现在的情况比较复杂：

1. Play 版升到了 v1.4.13，VMess breaking，比如 @NichtsVonChaos 的情况
2. v2ray-core v4.33.0 移除了 XTLS，@yxhit 可能是这个情况
3. v2rayNG v1.5.0 用的是 Xray-core v1.0.0，此时需要换 NG v1.4.13 试试

所以需要指出是哪里的最新版（即 v1.4.13 还是 v1.5.0），并注明服务端版本、用的什么协议组合，这样才是有效反馈。

**Comment by rorymw** [comment]
补充：Play最新版（Play 商店目前无法登陆，看不到版本号），服务端版本为 4.20.0，协议为 vmess

**Comment by RPRX** [comment]
@wumr967 

VMess 有过一次 breaking，升级服务端到最新版即可。

**Comment by rorymw** [comment]
已解决，服务端更新即可，谢谢！

**Comment by NichtsHsu** [comment]
@rprx 我是1.4.13版的，是VMess，服务器毕竟是买的不是自己搭的，自己目前先用BifrostV凑合着

**Comment by 1265578519** [comment]
我不想用Xray核心。。。能不能出个普通版本的

**Comment by NichtsHsu** [comment]
补充：这边发现回退到1.3版可以正常连接，不知道新版能不能考虑一下兼容

**Comment by 1265578519** [comment]
> 补充：这边发现回退到1.3版可以正常连接，不知道新版能不能考虑一下兼容

这个你要找机场升级服务端核心，v2核心v4.28.0或者以上版本默认启用AEAD加密，更安全，机场服务端也要同步的版本，如果机场服务端为v4.27.5，那么你用的v2rayNG最高版本为1.3.3（Core V4.27.4）可用

**Comment by 2dust** [comment]
无法升级服务端的请退回客户端到1.3.3
https://github.com/2dust/v2rayNG/releases/tag/1.3.3
从1.3.3到1.4.13间隔了有3个月时间了

**Comment by danerlt** [comment]
@2dust 服务端v2ray 4.31.2的版本客户端要用什么版本的呀,我手机升级到最新之后就不能用了.

**Comment by 1265578519** [comment]
> @2dust 服务端v2ray 4.31.2的版本客户端要用什么版本的呀,我手机升级到最新之后就不能用了.

服务端v2ray v4.31.2，可以用最新的1.5.2版本
https://github.com/2dust/v2rayNG/releases/tag/1.5.2-v2fly-core

**Comment by danerlt** [comment]
@1265578519 我更新一下试试 谢谢啦

**Comment by danerlt** [comment]
> > @2dust 服务端v2ray 4.31.2的版本客户端要用什么版本的呀,我手机升级到最新之后就不能用了.
> 
> 服务端v2ray v4.31.2，可以用最新的1.5.2版本
> https://github.com/2dust/v2rayNG/releases/tag/1.5.2-v2fly-core
@1265578519 @2dust 
更新1.5.2-v2fly-core也不行 我是自己的服务器搭建的v2ray

**Comment by 1265578519** [comment]
> > > @2dust 服务端v2ray 4.31.2的版本客户端要用什么版本的呀,我手机升级到最新之后就不能用了.
> > 
> > 
> > 服务端v2ray v4.31.2，可以用最新的1.5.2版本
> > https://github.com/2dust/v2rayNG/releases/tag/1.5.2-v2fly-core
> > @1265578519 @2dust
> > 更新1.5.2-v2fly-core也不行 我是自己的服务器搭建的v2ray

你是不是套了TLS？

**Comment by danerlt** [comment]
@1265578519 是的 用了tls

**Comment by danerlt** [comment]
> > > > @2dust 服务端v2ray 4.31.2的版本客户端要用什么版本的呀,我手机升级到最新之后就不能用了.
> > > 
> > > 
> > > 服务端v2ray v4.31.2，可以用最新的1.5.2版本
> > > https://github.com/2dust/v2rayNG/releases/tag/1.5.2-v2fly-core
> > > @1265578519 @2dust
> > > 更新1.5.2-v2fly-core也不行 我是自己的服务器搭建的v2ray
> 
> 你是不是套了TLS？
@1265578519 
v2ray很久没关注 最近用不了才上github上看看 有没有最新版的搭建教程之类的

**Comment by 1265578519** [comment]
> @1265578519 是的 用了tls

![image](https://user-images.githubusercontent.com/6442439/102686694-39264f80-4224-11eb-8e69-38b022cccfe7.png)
手机上打开设置，找到这个功能，选择运行，就可以使用了

**Comment by kqq038** [comment]
> 
> 
> > @1265578519 是的 用了tls
> 
> ![image](https://user-images.githubusercontent.com/6442439/102686694-39264f80-4224-11eb-8e69-38b022cccfe7.png)
> 手机上打开设置，找到这个功能，选择运行，就可以使用了

熊弟，你这图片打不开啊

**Comment by pinkcoala** [comment]
我手机用的v2rayNG很奇怪，上周某天突然就报错read/write on closed pipe，但是电脑Mac端用V2ray没问题，另个手机用的v2rayNG也没问题。然后给手机删了装了低版本的v2rayNG以后不报错，可以正常用，但是过一晚上第二天，又不行了，反复几次，后来发现是因为V2rayNG自己更新了版本和内核...可是我没找到能够关闭它自己偷偷升级lib和内核的设置，我也没设置任何订阅信息...很迷。

**Comment by hellebores001** [comment]
我手机用的v2rayNG很奇怪，上周某天突然就报错read/write on closed pipe，但是电脑Mac端用V2ray没问题，另个手机用的v2rayNG也没问题。然后给手机删了装了低版本的v2rayNG以后不报错，可以正常用，但是过一晚上第二天，又不行了，反复几次，后来发现是因为V2rayNG自己更新了版本和内核...可是我没找到能够关闭它自己偷偷升级lib和内核的设置，我也没设置任何订阅信息...很迷。

**Comment by RPRX** [comment]
@hellebores001 Play 商店关掉自动更新

**Comment by hellebores001** [comment]
> @hellebores001 Play 商店关掉自动更新

好的，Thx！的确自己偷偷更新版本的这台手机装了play商店，另一台没装。

**Comment by fanwz** [comment]
> 我也是。
> 手机和MUMU模拟器都是报同样的错。服务器是买的just my socks。

原来alterId 是0，改成1就OK了

**Comment by nicolasking84** [comment]
手机端v2rayng看了是Core v4.32.1可以用，电视端不能用无论新版旧版本v2rayng都提示io:read/write on closed pipe

**Comment by XGsimple** [comment]
需要填写SNI，值为域名
