### ISSUE TITLE
切换配置bug

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#775]
手动添加配置A后把配置输出到粘贴板，再从粘贴板导入两次简单修改后得到配置B与C
程序界面切换到B或者C后，从状态栏快捷方式关闭再开启有机率回到配置A(通知显示A,而程序界面点亮的却是B或者C)

**Comment by yuhan6665** [comment]
Thanks for reporting this issue. I will fix it.

**Comment by yuhan6665** [comment]
Fixed in https://github.com/2dust/v2rayNG/pull/783
