### ISSUE TITLE
v8版本异常

### ISSUE THREAD

**Issue by wpf973** [2dust/v2rayNG#777]
V8版本异常
华为  nova7  麒麟985 
使用V8版本 闪断  
更换为V7版本  恢复正常

故障重现，可协助测试

**Comment by yuhan6665** [comment]
If you have ADB setup on computer, please connect phone and get full ADB log if possible.
If not please try upload from NG's logcat activity.

**Comment by wpf973** [comment]
在谷歌play 下载安装正常。。。。。。。

**Comment by RPRX** [comment]
请测试近期的几个版本，以及看下 play 版是 v7a 还是 v8a（因为这种情况有可能是 CPU 的问题）

**Comment by wpf973** [comment]
这个在哪能可以到版本？

**Comment by RPRX** [comment]
请分别测试 NG 近四个版本的 v8a

https://github.com/2dust/v2rayNG/releases

**Comment by wpf973** [comment]
1.51版本测试正常

**Comment by RPRX** [comment]
是玄学了

**Comment by wpf973** [comment]
华为 nova7  麒麟985...

**Comment by RPRX** [comment]
此 issue 可以关闭，之后若有新的异常，请开新的 issue
