### ISSUE TITLE
V2rayNG 1.50版本vless无法上网

### ISSUE THREAD

**Issue by NicolasChamllet** [2dust/v2rayNG#779]
手机端安卓9，v2rayng 1.50 core1.0.0

同样的vless+ws+tls和vless+tcp+xtls配置，win10+v2rayN可以正常使用

在上述手机端可启动服务并测试延迟，但无法正常上网。手机chrome上被墙网站提示offline。

开关本地dns不能解决。
设置远程dns不能解决。

回退play版本1.3.3，vless+ws+tls恢复正常，tcp+xtls理所应当的无法使用。

服务器端版本
vless+ws+tls对应V2ray 4.28.2
vless+tcp+xtls rprx direct 对应xray 1.0.0

**Comment by wpf973** [comment]
个人感觉你的问题 和我的一样 你试试安装V7版本的 1.5    
我用V8和你的客户端表现一样 ，V7就正常

**Comment by NicolasChamllet** [comment]
> 个人感觉你的问题 和我的一样 你试试安装V7版本的 1.5
> 我用V8和你的客户端表现一样 ，V7就正常

我测试了你说的v7版本，以及play最新版，都不行。

1.5.0v7版本甚至会造成国内网站也无法连接

**Comment by NicolasChamllet** [comment]
vless+ws+tls在服务器端更新到core 4.33.0之后，更新google play V2rayNG 1.4.13版本正常。

vless+xtls在服务器端xray core 1.0.0情况下，win10 v2rayN工作正常，安卓9 V2rayNG 1.4.13仍然无法正常使用。

**Comment by rprx** [comment]
@NicolasChamllet 

确认一下手机和电脑是配置完全相同

**Comment by RPRX** [comment]
@NicolasChamllet 

确认一下手机和电脑的配置完全相同

**Comment by hyqaqw** [comment]
> @NicolasChamllet
> 
> 确认一下手机和电脑的配置完全相同

相同也很难连接上，反复重启很多次才能连上

**Comment by chafer516** [comment]
我也遇到同样的问题，求解决方法。

**Comment by RPRX** [comment]
@hyqaqw @chafer516 

请具体描述，每个人的情况都不一样

**Comment by RPRX** [comment]
https://github.com/2dust/v2rayNG/issues/777#issuecomment-739256692

请测试下 1.5.1

**Comment by NicolasChamllet** [comment]
> @NicolasChamllet
> 
> 确认一下手机和电脑的配置完全相同

确认。

**Comment by NicolasChamllet** [comment]
> [#777 (comment)](https://github.com/2dust/v2rayNG/issues/777#issuecomment-739256692)
> 
> 请测试下 1.5.1

服务器端也升级到XRaycore1.1.1，然后安装1.5.1 v2rayng v8a。
测试结果很诡异。 vless+ws+tls正常。
vless+xtls+direct可以给telegram代理，但是浏览器不能正常上网。在v2rayng里头直接更换为其他代理就没问题，不用改动设置，应该不是v2rayng设置的问题。

**Comment by RPRX** [comment]
@NicolasChamllet 

试试用普通 TLS，以便确认是否是 DNS 相关的问题（目前已知 Direct 无此问题）

保险起见问一下：是否开了 DoH？

**Comment by NicolasChamllet** [comment]
> @NicolasChamllet
> 
> 试试用普通 TLS，以便确认是否是 DNS 相关的问题（目前已知 Direct 无此问题）
> 
> 保险起见问一下：是否开了 DoH？

打开本地dns，关闭ipv6优先，再次测试正常了。

**Comment by NicolasChamllet** [comment]
> @NicolasChamllet
> 
> 试试用普通 TLS，以便确认是否是 DNS 相关的问题（目前已知 Direct 无此问题）
> 
> 保险起见问一下：是否开了 DoH？

感谢大佬耐心跟进

**Comment by 3cobblers** [comment]
Android端同样的情况，预定义规则选择绕过局域网及大陆代理，打开本地dns，关闭ipv6，远程dns填8.8.8.8，可开始访问学习资料

**Comment by LJH183183** [comment]
本人也遇到这个问题，已尝试关闭ipv6完美解决，感谢！
