### ISSUE TITLE
小米6 MIUI10 Android P 一键测速失败全部显示-1

### ISSUE THREAD

**Issue by LokeyZ** [2dust/v2rayNG#78]
![TIM图片20190819235206](https://user-images.githubusercontent.com/54281485/63279967-87e47200-c2dc-11e9-9c44-a66813d8b68c.jpg)

**Comment by MrBenWang** [comment]
同一个ip 地址，tcp 没有问题，kcp 就是-1

**Comment by 2dust** [comment]
tcping无法测试kcp
