### ISSUE TITLE
软件自动切换设置

### ISSUE THREAD

**Issue by dfliaoyue** [2dust/v2rayNG#780]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
保持选定的设置

### 实际行为
程序会时不时自己切换成其他设置

### 复现方法
未知，可能和网络切换有关

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）
目前为play版，1.4.13。实际上此问题在之前多个版本（含直接从GitHub下载的预发布版）都存在。

**Comment by dfliaoyue** [comment]
补充：似乎我搞错了，是利用快捷设置开启服务，就会出现问题，不是软件中选择的设置。

**Comment by yuhan6665** [comment]
Yes I'm able to reproduce. Will fix this issue in next version.

**Comment by yuhan6665** [comment]
Fixed in https://github.com/2dust/v2rayNG/pull/783
