### ISSUE TITLE
disable dns resolving in vpn mode

### ISSUE THREAD

**Issue by fsheidaiee** [2dust/v2rayNG#781]
Hi
is there anyway to disable dns resolving in vpn mode?
thanks

**Comment by rurirei** [comment]
?

**Comment by rurirei** [comment]
```jsonc
{
    "port": "53",
    "network": "udp",
    "outboundTag": "reject"
}
```

**Comment by fsheidaiee** [comment]
according to this https://github.com/2dust/v2rayNG/wiki/Mode
there is one less DNS in proxy mode
is there anyway to remove that extra DNS in vpn mode in setting?

**Comment by rurirei** [comment]
i don't know what you're misunderstanded on. ask @yuhan6665

**Comment by yuhan6665** [comment]
@fsheidaiee I think you are talking about fake DNS. I actually have a pending change in core. Once that is merged (to both v2fly and xray), we will be able to reduce the time for the first DNS, almost like removing it.

**Comment by fsheidaiee** [comment]
> @fsheidaiee I think you are talking about fake DNS. I actually have a pending change in core. Once that is merged (to both v2fly and xray), we will be able to reduce the time for the first DNS, almost like removing it.

Yes thats what i mean.
Thanks
