### ISSUE TITLE
点击测试真连接就崩溃！！

### ISSUE THREAD

**Issue by GaranYeon** [2dust/v2rayNG#782]
我在电视盒子上用一直都相安无事，但1.4.12之后的版本
只要点测试真连接就直接崩溃退出
系统版本  W大 7.1.2
斐讯N1盒子

**Comment by RPRX** [comment]
请分别测试 1.4.13、1.5.0、1.5.1

**Comment by heheheaa** [comment]
> 请分别测试 1.4.13、1.5.0、1.5.1

1.5.1启用splice后各种崩溃

**Comment by RPRX** [comment]
@heheheaa 

Splice 还是测试阶段，目前和过代理的 DoH 有冲突，下个版本解决

**Comment by RPRX** [comment]
https://github.com/2dust/v2rayNG/releases/tag/1.5.2

**Comment by GaranYeon** [comment]
除了1.4.12之外，之後的所有版本點“測試全部配置真連接”都崩潰並退出，包括最新的1.5.2

**Comment by heheheaa** [comment]
> @heheheaa
> 
> Splice 还是测试阶段，目前和过代理的 DoH 有冲突，下个版本解决

我也发现是doh的问题了，去掉doh就没问题了

**Comment by RPRX** [comment]
@heheheaa 

Xray-core v1.1.2 和 v2rayNG 1.5.2 解决了此问题，用新版即可

**Comment by RPRX** [comment]
@GaranYeon 

1.4.13 呢？

**Comment by GaranYeon** [comment]
> @GaranYeon
> 
> 1.4.13呢？

1.4.13也一样崩溃，我手机ANDROID 10这几个版本都没有问题，盒子ANDROID 7.1.2就崩溃退出

**Comment by RPRX** [comment]
@GaranYeon 

看了下，core 应该没有引起此变化的改动，NG 的变动比较多，麻烦 @yuhan6665

**Comment by yuhan6665** [comment]
@GaranYeon maybe it is a magic rom that doesn't support ViewModel?? Though I need your log to understand the issue. Please try getting logs from NG.

**Comment by GaranYeon** [comment]
> @GaranYeon也许是不支持ViewModel的魔术ROM？虽然我需要您的日志来了解问题。请尝试从NG获取日志。

好的，我尝试把日志导出来

**Comment by GaranYeon** [comment]
> @GaranYeon也许是不支持ViewModel的魔术ROM？虽然我需要您的日志来了解问题。请尝试从NG获取日志。

--------- beginning of system
--------- beginning of crash
12-09 03:18:43.243 E/AndroidRuntime( 8366): FATALEXCEPTION: main
12-09 03:18:43.243 E/AndroidRuntime( 8366): Process: com.v2ray.ang, PID: 8366
12-09 03:18:43.243 E/AndroidRuntime( 8366): android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@123cc5e is not valid; is your activity running?
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.widget.Toast$TN.handleShow(Toast.java:459)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.os.Looper.loop(Looper.java:154)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at java.lang.reflect.Method.invoke(Native Method)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
12-09 03:18:43.243 E/AndroidRuntime( 8366): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by GaranYeon** [comment]
> @GaranYeon也许是不支持ViewModel的魔术ROM？虽然我需要您的日志来了解问题。请尝试从NG获取日志。

![Uploading phibox_2020-12-09-03-45-35.jpg…]()

**Comment by GaranYeon** [comment]
![phibox_2020-12-09-03-45-35](https://user-images.githubusercontent.com/18183124/101533908-662b6480-39d1-11eb-9402-4db0eea6fcc4.jpg)

**Comment by yuhan6665** [comment]
@GaranYeon thanks for getting the key logs! I found a potential fix and re-compiled 1.5.2. Will you be willing to do a test for me? (Note you will need to delete current version to install this)
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null.apk

**Comment by GaranYeon** [comment]
> @GaranYeon感谢您获取关键日志！我找到了一个可能的修复程序，然后重新编译了1.5.2。您愿意为我做测试吗？（请注意，您需要删除当前版本才能安装此版本）
> https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null.apk

好的，我试试

**Comment by GaranYeon** [comment]
> @GaranYeon感谢您获取关键日志！我找到了一个可能的修复程序，然后重新编译了1.5.2。您愿意为我做测试吗？（请注意，您需要删除当前版本才能安装此版本）
> https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null.apk

还是崩溃😩💔
![phibox_2020-12-09-11-32-05](https://user-images.githubusercontent.com/18183124/101570937-5d0eb780-3a12-11eb-8844-4f55c4c24f2b.jpg)

**Comment by yuhan6665** [comment]
@GaranYeon try this 
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null-2.apk

**Comment by GaranYeon** [comment]
> @GaranYeon试试这个
> https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null-2.apk

这个版本连更新都奔溃
![phibox_2020-12-10-17-44-32](https://user-images.githubusercontent.com/18183124/101756143-ac3b1200-3b10-11eb-8aca-0968a4ef4ddc.jpg)
![phibox_2020-12-10-17-44-24](https://user-images.githubusercontent.com/18183124/101756152-af360280-3b10-11eb-84a3-c94f03699647.jpg)

**Comment by yuhan6665** [comment]
@GaranYeon now I'm a little lost. Need to do more tests :) Please test 3 and 4. Let me know exactly what did you do if you encounter crash.
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-3.apk
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-4.apk

**Comment by GaranYeon** [comment]
> @GaranYeon现在我有点迷路了。需要做更多的测试：）请测试3和4。如果遇到崩溃，请告诉我您的确切做法。
> [https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-3.apk ](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-3.apk)
> [https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1。 4.10_null-4.apk](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-4.apk)

null_3可以正常使用
null_4崩溃
![phibox_2020-12-10-22-16-01](https://user-images.githubusercontent.com/18183124/101784501-8e80a380-3b36-11eb-8e3d-0fd0174ad9c1.jpg)

**Comment by GaranYeon** [comment]
> @GaranYeon现在我有点迷路了。需要做更多的测试：）请测试3和4。如果遇到崩溃，请告诉我您的确切做法。
> [https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-3.apk ](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-3.apk)
> [https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1。 4.10_null-4.apk](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-4.apk)

我用1.4.12 版本能够流畅的正常使用

**Comment by yuhan6665** [comment]
@GaranYeon 查了一下这个问题基本上是被7.1.2版本的安卓坑的娘都不认。。关键我这边没办法复现你的问题，你能说一下在以下哪些步骤会崩溃？
添加节点，更新订阅，连接，点击测试，服务重启，导出全部，测试全部tcping，测试全部真连接

https://stackoverflow.com/questions/52649353/android-view-windowmanagerbadtokenexception-unable-to-add-window-at-toast

**Comment by GaranYeon** [comment]
> @关键是我这边没办法复现你的问题，你能说一下在以下某些步骤会崩溃吗？
> 添加了东西。@GaranYeon查了一下这个问题基本上是被7.1.2版本的安卓坑的娘都不认。。，，更新订阅，连接，点击测试，服务重启，更新全部，测试全部tcping，测试全部真连接
> 
> https://stackoverflow.com/questions/52649353/android-view-windowmanagerbadtokenexception-unable-to-add-window-at-toast

好的，感谢你们的一直付出！没办法我就用回1.4.12
谢谢！

**Comment by yuhan6665** [comment]
@GaranYeon please don't quit yet, I didn't give up I was just making a joke ;)
Please help test
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-5.apk

**Comment by GaranYeon** [comment]
> @GaranYeon请不要退出，我没有放弃，我只是在开玩笑;）
> 请帮助测试
> [https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null -5.apk](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-5.apk)

> @GaranYeon请不要退出，我没有放弃，我只是在开玩笑;）
> 请帮助测试
> [https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null -5.apk](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.4.10_null-5.apk)

感谢不离不弃与付出。这个版本没有奔溃退出，开心😄！我还多试了几次，可以顺利更新订阅与测试连接，只是有点小问题，打开测试连接时有点卡顿然后假死（按任何按键都没反应），稍等会就显示测试结果，如果能修改下就完美了

**Comment by yuhan6665** [comment]
@GaranYeon 也要感谢你的耐心测试，我已经提交了一个修复。
至于你说的卡死问题，你是在哪种测试的时候会出现这个现象：是屏幕下方的测试，还是菜单里的测试全部tcping，测试全部真连接？

**Comment by GaranYeon** [comment]
> @于
> 你说的卡死问题，你是在这种测试的时候会出现这个现象：是屏幕上方的测试，还是菜单里的测试全部tcping，测试全部真连接？

是在菜单里测试全部真连接时出现，无论是用外接鼠标还是用遥控，只要点测试真连接就会出现卡顿跟着假死，要等会才有测试结果出来

**Comment by GaranYeon** [comment]
然后又再次崩溃
![phibox_2020-12-14-19-58-18](https://user-images.githubusercontent.com/18183124/102088082-60ac9f00-3e55-11eb-80da-24ffc885eb31.jpg)

**Comment by yuhan6665** [comment]
@GaranYeon I need to thank you again since you found yet another bug in the code ;)
Can you do the test for https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null-6.apk

**Comment by GaranYeon** [comment]
> @GaranYeon我再次感谢您，因为您在代码中又发现了一个错误；）
> 您可以对[https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null-](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null-6.apk)做测试[6.apk](https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.2_null-6.apk)

感谢你的付出，最后这个版本我测试了更新订阅还有测试真连接，暂时没有遇到bug。还能找回之前版本的丝滑操作感。再次感谢你！我再使用一段时间如果还有什么问题会回来反馈

**Comment by GaranYeon** [comment]
@yuhan6665 
下午尝试安装新版本1.5.5 
在测试真连接时同样出现奔溃
设备还是7.1.2
![phibox_2020-12-20-16-48-04](https://user-images.githubusercontent.com/18183124/102710347-a2719580-42ec-11eb-8095-d2ed3cc93992.jpg)

**Comment by yuhan6665** [comment]
@GaranYeon I think 1.5.5 only contain one of the fix, not the second. Will fix in next version.

**Comment by GaranYeon** [comment]
> @GaranYeon我认为1.5.5仅包含一个修复程序，而不包含第二个。将在下一个版本中修复。

好的，感谢     期待下个版本
