### ISSUE TITLE
希望可以自定义监听 ip

### ISSUE THREAD

**Issue by joebnb** [2dust/v2rayNG#784]
手机分享的热点无法通过 v2ray 上网，还需要挂代理，感觉这个不符合逻辑，v2ray 全局了，那应该是我这台设备包括通过我这台设备上网的其它设备都应该可以通过 v2ray 的规则上网，但是现在不可以

希望v2ray 可以增加自定义监听设备ip的功能，可以自定义选择需要监听并代理的网络

https://github.com/v2ray/v2ray-core/issues/210

**Comment by rurirei** [comment]
do you know VPN hotspot?

**Comment by joebnb** [comment]
谢谢啦💅
