### ISSUE TITLE
Speed indicator in notification

### ISSUE THREAD

**Issue by aztecrabbit** [2dust/v2rayNG#785]
Hi,

I think i need to tell you this, speed indicator design in notification is soo bad, i think the speed indicator design sould change like in shadowsocks android app created by Max Lv (https://github.com/shadowsocks/shadowsocks-android)

**Comment by rurirei** [comment]
?

**Comment by aztecrabbit** [comment]
From this

![Screenshot_20201205-135504~2](https://user-images.githubusercontent.com/27699984/101236377-6098fa80-3703-11eb-9a23-85a35bbd56a6.jpg)

To this

![Screenshot_20201205-135641~2](https://user-images.githubusercontent.com/27699984/101236394-70184380-3703-11eb-9d3e-d70ff984cba5.jpg)

**Comment by rurirei** [comment]
@yuhan6665
