### ISSUE TITLE
还是没给socks添加认证功能，太失望了，不解决只能重新下载bifrostv了，

### ISSUE THREAD

**Issue by uposink** [2dust/v2rayNG#79]
在提出问题前请先自行排除服务器端问题，同时也

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
不接受需求
