### ISSUE TITLE
安卓客户端订阅更新一直失败，回退到1.3版本依旧无法更新订阅

### ISSUE THREAD

**Issue by SKkai** [2dust/v2rayNG#793]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by pinssrr** [comment]
同样这个问题，其他客户端没有一个问题

**Comment by bushi1107** [comment]
我也是这样一直订阅失败，版本是v2rayNG_1.5.6_armeabi-v7a.apk

**Comment by wierli** [comment]
参考[https://blog.csdn.net/nidongde521/article/details/86496804](url)

**Comment by yuhan6665** [comment]
@wierli using clear text to transfer sensitive information like subscription is never a good idea. ng will not support unsafe link like that.
