### ISSUE TITLE
能不能优化下通知栏流量显示Can you optimize the notification column flow display?

### ISSUE THREAD

**Issue by GaoMeng1126** [2dust/v2rayNG#794]
以前的流量显示很简洁，现在的不怎么好，能不能把direct去掉，让我们自定义显示proxy还是direct,并且显示中文
The previous traffic display is very simple, now it is not very good, can we remove the direct, let us customize the display proxy or direct, and display Chinese

**Comment by if1y** [comment]
`direct` is also a outbound.

It displays just according to the outbounds' tag. So if you really want to, modify the tag with custom configs.

**Comment by yuhan6665** [comment]
With the current version, you need to ensure freedom outbound's tag is "direct" for the flow display to work correctly. Though you can customise other outbounds tag.
