### ISSUE TITLE
版本 “1.5.2: Merge pull request #787 from yuhan6665/fix-selected” 选择xtls无法启动

### ISSUE THREAD

**Issue by tianlichunhong** [2dust/v2rayNG#797]
安卓安装了v2rayNG_1.5.2_arm64-v8a.apk 版本后，流控选择“xtls-rprx-splice”后，底层传输安全选择”xtls“，无法工作。
将底层传输安全选择”tls“，工作正常。

提示：失败：io:read/write on closed pipe

服务器端是最新版本1.1.2的xray，配置是xtls-rprx-direct + tcp +xtls，运行正常。

**Comment by hnliuzesen** [comment]
不知道 xray 是啥，但是 v2ray 那边 xtls 好像已经不再被支持了

**Comment by RPRX** [comment]
试试 v1.5.3

**Comment by RPRX** [comment]
@hnliuzesen 不是这个问题

**Comment by tianlichunhong** [comment]
新版已经修正了该bug
