### ISSUE TITLE
国内DNS和远程DNS无法同时使用DoHL

### ISSUE THREAD

**Issue by yahaha-233** [2dust/v2rayNG#798]
### 预期行为
国内和远程DNS应当可以同时使用DoHL

导出的DNS服务器配置文件为：
```
"servers": [
      "https+local://xxx",
      {
        "address": "https+local://xxx",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ],
        "port": 53
      }
    ]
```

### 实际行为
国内和远程DNS无法同时使用DoHL

### 复现方法
1. 将国内和远程DNS都设置为https+local://xxx
2. 打开代理
3. 复现问题，无法使用

### 日志信息
日志中DNS查询报错，显示境内外DNS无法查询，context deadline exceeded

**Comment by rurirei** [comment]
...

#653

https://github.com/2dust/v2rayNG/issues?q=is%3Aissue+commenter%3Arurirei+dns

**Comment by yahaha-233** [comment]
> ...
> 
> #653
> 
> https://github.com/2dust/v2rayNG/issues?q=is%3Aissue+commenter%3Arurirei+dns

哈哈哈哈有好多一样的询问，又测了下好像是代理服务器的问题，就先关了。
