### ISSUE TITLE
请问CentOS7下怎么编译apk

### ISSUE THREAD

**Issue by viagram** [2dust/v2rayNG#8]
如题，作者能提供个一键编译的sh脚本吗？谢谢！

**Comment by Hana-ame** [comment]
我觉得这么做不是个好主意。如果你确定你必须要这么做的话，可能先找一个教程来帮助你在Linux上搭建Android编译环境会好些。

**Comment by viagram** [comment]
@Hana-ame 试过了，成功编译shadowsocksr-android。
我之所以这么做是因众所周知的原因，国产的一些app会扫描手机应用安装列表，难免会受到某些方面的影响，从而向相关方面... ...此处省略N千字，简单来说就是修改app的一些相关敏感字(如: v2ray,wireguard,vpn,shadowsocks等等)，从而增大翻墙的安全性。

**Comment by Hana-ame** [comment]
@viagram 
如果没有人尝试写bash，而这个需求又实在有必要的话，你可以尝试使用Android studio进行编译。
libv2ray.aar 可以在这个作者的另一个仓库里找到
key.jks用下面的语句生成
```
keytool -genkey -v -keystore ./key.jks -validity 1000 -alias ang -keypass 123456 -storepass 123456 -keyalg RSA -keysize 2048
```
