### ISSUE TITLE
QUIC不兼容

### ISSUE THREAD

**Issue by catdog** [2dust/v2rayNG#802]
### 日志信息
<details>
...
12-13 13:48:26.261 D/com.v2ray.ang(13407): measureV2rayDelay: go.Universe$proxyerror: Get "http://www.google.com/generate_204": io: read/write on closed pipe
12-13 13:48:26.262 I/GoLog   (13407): [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [draft-32 draft-29 0x3acaba7a]. No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [draft-32 draft-29 0x9aaa0afa]. No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [draft-32 draft-29 0x7a2a4a0a]. No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [draft-32 draft-29 0xaada5aca]. No compatible QUIC version found. We support [TLS dev version (WIP)], server offered [0x8aba0a6a draft-32 draft-29].] > common/retry: all retry attempts failed

</details>

### 环境信息
v2rayNG v1.5.2
服务器版本 v4.33.0

### 服务器配置 streamSettings 部分
"streamSettings": {
                "network": "quic",
                "quicSettings":{
                    "security": "none",
                    "header": {
                        "type": "srtp"
                    }
                },
                "security": "none"

### 客户端设定
![Screenshot_20201213-140605_v2rayNG](https://user-images.githubusercontent.com/1482575/102004529-81d59880-3d4c-11eb-9eda-af43ea6427a6.png)

**Comment by yuhan6665** [comment]
Please use the latest fly version
https://github.com/2dust/v2rayNG/releases/tag/1.5.2-v2fly-core

**Comment by RPRX** [comment]
不应存在此问题

**Comment by catdog** [comment]
> Please use the latest fly version
> https://github.com/2dust/v2rayNG/releases/tag/1.5.2-v2fly-core

fixed

**Comment by RPRX** [comment]
稍等，Xray-core 和 v2fly-core 用的是同一个 QUIC 库，为什么会这样？我等等测试下

**Comment by RPRX** [comment]
经测试，直接用 core 没问题，但用 NG 的确会出现这样的情况（即使自定义配置），应该是编译上的问题，现在可以用 go.mod 了
