### ISSUE TITLE
v2rayNG 1.5.4版本小米6安卓9安装失败

### ISSUE THREAD

**Issue by bubuqing99** [2dust/v2rayNG#805]
望改进，谢谢。
![Screenshot_2020-12-19-19-23-21-977_com miui packageinstaller](https://user-images.githubusercontent.com/57699051/102688166-c8853000-422f-11eb-8ae0-27df0b940aad.jpg)

**Comment by NIKTTOP** [comment]
同小米6安卓9，1.5.5可正常安装
