### ISSUE TITLE
On Android TV, How tap on make connection button?

### ISSUE THREAD

**Issue by hamedsbt** [2dust/v2rayNG#807]
On Android TV, How tap on make connection button?

**Comment by xenstar** [comment]
So this one I am telling the developer for long time. You have to connect with a mouse, then you can click on the connect button. Really wish developer, can just fix this small issue, that with smart tv remote control, we can click the connect button. It would make life more easier.

**Comment by rendaa** [comment]
I'm not sure if this would help... On my device, I can move the focus (in a very slightly lighter gray) with the up/down/right/left arrow keys on the remote control unit, use down arrow key to move the focus to the bottom of the UI, then press the up arrow key ONCE, now the focus is on the grey V button at the bottom-right corner, now just press the OK key on the remote control to connect VPN.

**Comment by rendaa** [comment]
> On Android TV, How tap on make connection button?

I'm not sure if this would help... On my device, I can move the focus (in a very slightly lighter gray) with the up/down/right/left arrow keys on the remote control unit, use down arrow key to move the focus to the bottom of the UI, then press the up arrow key ONCE, now the focus is on the grey V button at the bottom-right corner, now just press the OK key on the remote control to connect VPN.

**Comment by xenstar** [comment]
This is a very easy fix for the developers, I hope they will take some action against it, asking this for last 1 year.

**Comment by ghost** [comment]
Hi, i have great idea.
You can go to system settings try "always enabled vpn". if turn on, v2rayng will be connected on TV boot. to make sure connected, first you need connected internet.
I am already use this, it working very perfect with my Android TV.

**Comment by xenstar** [comment]
> Hi, i have great idea.
> You can go to system settings try "always enabled vpn". if turn on, v2rayng will be connected on TV boot. to make sure connected, first you need connected internet.
> I am already use this, it working very perfect with my Android TV.

So the issue is, I am using Android 9, Xiaomi TV Box 4 (Global Version), and I don't see that VPN setting as you mentioned. I have this setting on my phone, where I have selected "always enabled VPN". But on my TV Box, there is no setting like this :(

**Comment by yuhan6665** [comment]
The other option you can try is to use "service restart" from top right menu
