### ISSUE TITLE
【讨论】VPN外的DNS查询是否不可避免？

### ISSUE THREAD

**Issue by Platway** [2dust/v2rayNG#81]
通过测试，我发现即便我导入的json文件配置了全局代理，v2rayNG仍然要使用Settings里面的Remote DNS进行一次DNS查询。实际上这个DNS查询是没有用的，因为配置了全局代理，并不会使用这个DNS查询结果来访问网站（即便只配置了部分走代理，如果最终访问的网站是路由到了代理去访问，这个VPN外的DNS查询也是没有用的）。我在想，这次VPN外的DNS查询是否可以避免？我不太清楚运作机理，如果说的不对请指正。十分感谢，并祝愉快！

**Comment by imaqine** [comment]
新更新的订阅设置是什么意思啊

**Comment by FH0** [comment]
vpn的dns查询是流经tun网卡的，通过vpn代理查询，并没有通过rmnet网卡
