### ISSUE TITLE
【求指点】v2rayNG 全局 VPN 模式似乎不能完全转发流量，PC 端 v2rayN 和 iOS 小火箭则都没问题

### ISSUE THREAD

**Issue by rendaa** [2dust/v2rayNG#811]
安卓上 v2rayNG 版本 1.4.13， 用的是自己的服务器，路由策略里域名策略用的是 IPIfNonMatch，预定义规则选的是全局，最后那个选项用的是VPN模式（不是仅代理）。启动后 google、youtube 等都能正常访问，但 zinitevi 和 Tune In Radio 则不能正常工作。

在安卓电视的 zinitevi 客户端里看视频，进app后主界面的海报都正常显示，但播放视频则一直在转圈，视频流的来源列表一直是空的。

类似的，安卓版的 Tune In Radio 主界面里的电台也显示不出来。

电脑上客户端是 v2rayN，服务器是用同一个。按 zinitevi  的官方方法，启动安卓电视的 zinitevi 客户端后，用电脑浏览器访问电视的 web 服务（应该是 zinitevi 运行时提供的），那些一直转圈的视频都可在电脑浏览器里播放，视频流来源列表里也有很多条内容。

在iOS设备上我用的是小火箭的客户端，服务器也是同个。启动 VPN 后直接运行 iOS 版的zinitevi客户端，一切正常；运行 Tune In Radio，主界面电台列表显示正常，播放电台也正常。

我对安卓的设备不太熟，请各位大侠帮忙指点一下安卓上 v2rayNG 该怎么弄。谢谢各位了！

**Comment by ailenli** [comment]
zinitevi这个有勾选吗？

**Comment by rendaa** [comment]
> zinitevi这个有勾选吗？

谢谢帮忙关注这问题并回复！

我是一直关着分应用代理那个开关的，刚刚试了打开这开关并确认也勾上了zinitev后面的框，效果仍然没变化。

**Comment by wzl0904** [comment]
同样的问题，有的网站图片显示不出来，关闭优先IPV6后变正常
