### ISSUE TITLE
v2rayng 安卓客户端 各种问题。

### ISSUE THREAD

**Issue by pinssrr** [2dust/v2rayNG#812]
更新订阅问题，有时不能更新订阅 提示失败，其他客户端没有问题秒订阅。
测试连接状态问题，经常连不上io: read/write on closed pipe，有时换节点同样全部连不上，其他客户端没有问题。
批量测试真延时问题，节点多的情况下 软件有时崩溃，有的节点会显示-1ms 实际是可以连接

**Comment by ghost** [comment]
更新订阅失败一般来说是由于代理服务的提供商屏蔽了ua导致的。
显示 io: read/write on closed pipe，代表软件无法完全建立连接，你可以首先关掉手机上v2rayng的电池优化功能（或者类似的后台限制功能）再试。应该问题就没有了。（如果相同节点使用其他软件正常的话）
“真延迟“测试失败是一个普遍问题，许多人都遇到了，目前暂时还无解。

**Comment by pinssrr** [comment]
谢谢
