### ISSUE TITLE
tag 1.4.13 打出来的安装包与google play有些差异，是需要配置什么东西才能打出那个包么

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#814]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
1.4.13打出的包与线上一致

### 实际行为
1.4.13打出的包与google play线上包，有一些界面差异，菜单也不一样。

### 复现方法
1.下载项目
2.更改包名
3.更改`dpreference/src/main/AndroidManifest.xml`中`authorities`字段

**Comment by wansellbusiness** [comment]
本地apk打包没问题，但发布到google play后无法连接。
导出从google play上下载的包，发现包里面缺失libtun2socks.so文件。
--------- beginning of main
01-14 21:22:59.141 I/GoLog   (25653): EscortingDown() Killing all escorted process 
01-14 21:23:10.983 I/GoLog   (25653): Preparing Domain: ang.v2ray.com:2040
01-14 21:23:10.983 I/GoLog   (25653): loading v2ray config
01-14 21:23:11.000 I/GoLog   (25653): new v2ray core
01-14 21:23:11.003 I/GoLog   (25653): start v2ray core
01-14 21:23:11.004 I/GoLog   (25653): [Warning] v2ray.com/core: V2Ray 4.31.2 started
01-14 21:23:11.021 I/GoLog   (25653): Prepare Result:
01-14 21:23:11.021 I/GoLog   (25653):  Domain: ang.v2ray.com
01-14 21:23:11.021 I/GoLog   (25653):  Port: 2040
01-14 21:23:11.021 I/GoLog   (25653):  IPs: [139.217.218.28]
01-14 21:23:11.056 I/GoLog   (25653): EnableLocalDNS: false
01-14 21:23:11.056 I/GoLog   (25653): ForwardIpv6: false
01-14 21:23:11.056 I/GoLog   (25653): DomainName: ang.v2ray.com:2040
01-14 21:23:11.056 I/GoLog   (25653): /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so [--netif-ipaddr 126.26.226.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
01-14 21:23:11.065 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.065 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.065 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.065 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.066 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.066 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.067 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.067 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.067 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.067 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.067 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.
01-14 21:23:11.067 I/GoLog   (25653): EscortRun cmd.Start err fork/exec /data/app/com.v2ray.ang-_5s_sKT_sADuph3BxAFmCw==/lib/arm64/libtun2socks.so: no such file or directory
01-14 21:23:11.067 I/GoLog   (25653): EscortRun Unexpected Exit, Restart now.

**Comment by ghost** [comment]
@wansellbusiness 你打出来的界面跟Google play 上的一样么

**Comment by wansellbusiness** [comment]
打出来的包，上传到GOOGLE PLAY后，下载到手机上发现缺少lib文件夹（里面包含了libgojni.so和libtun2socks.so）。问题出在这里。

**Comment by yuhan6665** [comment]
@wansellbusiness missing both .so files? Sounds like an issue with uploading to Play store

**Comment by wansellbusiness** [comment]
@yuhan6665 缺失了libgojni.so和libtun2socks.so。本地打包APK没问题，但打包成aab上传到Goole Play后，手机端下载的包就缺失这2个so文件。

**Comment by wansellbusiness** [comment]
@erDaren 你打出来的界面跟Google play 上的一样么。答：不一样。

**Comment by DDoSolitary** [comment]
@erDaren 我遇到了相同的问题，本地编译出来的界面和 Play 上的以及在 GitHub Releases 中发布的版本不一致

**Comment by AnmLobby** [comment]
I encountered the same problem, is there a solution?

**Comment by devrx5** [comment]
Я столкнулся с такой же проблемой, есть ли решение?

**Comment by devrx5** [comment]
我有同样的问题，我已经尝试解决这个问题两个星期了，对不起，我不知道该怎么办。

**Comment by devrx5** [comment]
我还注意到，当通过代理连接到 127.0.0.1:10808 的应用程序时，应用程序可以正常工作

**Comment by myfreax** [comment]
> @yuhan6665 缺失了libgojni.so和libtun2socks.so。本地打包APK没问题，但打包成aab上传到Goole Play后，手机端下载的包就缺失这2个so文件。

有解决方案吗？

**Comment by devrx5** [comment]
Я решил эту проблему

**Comment by jianxiansining** [comment]
请问这个问题有解决方案吗？

**Comment by jianxiansining** [comment]
Is there a solution? Why close this question?

**Comment by alsojin0806** [comment]
有大佬解决没？请指点？

**Comment by alsojin0806** [comment]
读取文件 写入到相应目录是否是一种解决方案？

**Comment by PingerAI** [comment]
尝试过使用bundletool将aab打包成apks，里面包含了上述的两个so文件
但是最后还是报错no such file or directory

**Comment by zhengtingguang** [comment]
> 

how to resolve？

**Comment by zhengtingguang** [comment]
> 

怎么解决的
