### ISSUE TITLE
android x86 9.0会闪退

### ISSUE THREAD

**Issue by NaphSl** [2dust/v2rayNG#815]
在Android x86 9.0上打开V2RayNG,会立刻闪退，无法使用。
设备是surface3
(救命啊，这玩意的日志怎么找)

**Comment by yuhan6665** [comment]
Please take a look at the "logcat" in the menu and copy the log here when you experience this issue.

**Comment by youling257** [comment]
please install v2rayNG_1.5.5_x86_64.apk or v2rayNG_1.5.5_x86.apk

**Comment by NaphSl** [comment]
> Please take a look at the "logcat" in the menu and copy the log here when you experience this issue.

It crashes before I click the menu, so I cannot copy the logcat.

**Comment by NaphSl** [comment]
> please install v2rayNG_1.5.5_x86_64.apk or v2rayNG_1.5.5_x86.apk

Version 1.2.10 runs but version 1.5.5 does not.

**Comment by yuhan6665** [comment]
@NaphSl unfortunately I can't reproduce your issue and I don't have that devices. It will be very hard to fix unless you can provide a log. Do you know how to use ADB?

**Comment by ghost** [comment]
怎么使用adb logcat获得日志？
1.在电脑上下载adb工具包，如果是windows则需要把该包全部解压到 C:/windows 下，如果是based on debian的linux系统，直接 sudo apt install adb fastboot就可以。
2.需要设备root，前往设备的“开发者选项”中，打开“usb调试”功能。
3.连接到电脑，如果是windows，此时需要打开”命令提示符“，如果是Linux或者mac则需要打开终端，输入adb devices后，在设备上的新弹窗中勾选“一律允许使用该电脑进行调试”后点击确定。
4.再输入 adb logcat > log.txt，再返回到桌面，复现一次操作，按下ctrl+c即可，此时找到 log.txt这个文件，里面记录的内容就是所需要的日志。

**Comment by NaphSl** [comment]
> 怎么使用adb logcat获得日志？
> 1.在电脑上下载adb工具包，如果是windows则需要把该包全部解压到 C:/windows 下，如果是based on debian的linux系统，直接 sudo apt install adb fastboot就可以。
> 2.需要设备root，前往设备的“开发者选项”中，打开“usb调试”功能。
> 3.连接到电脑，如果是windows，此时需要打开”命令提示符“，如果是Linux或者mac则需要打开终端，输入adb devices后，在设备上的新弹窗中勾选“一律允许使用该电脑进行调试”后点击确定。
> 4.再输入 adb logcat > log.txt，再返回到桌面，复现一次操作，按下ctrl+c即可，此时找到 log.txt这个文件，里面记录的内容就是所需要的日志。

okok，非常感谢。我会试一下的

**Comment by yuhan6665** [comment]
@NaphSl another thing might be easier to test.. you mentioned 1.2.10 is ok. What is the FIRST version that have this issue?

**Comment by NaphSl** [comment]
> @NaphSl another thing might be easier to test.. you mentioned 1.2.10 is ok. What is the FIRST version that have this issue?

The first version that have this issue is 1.4.10.
Verion 1.4.8 runs but 1.4.10 does not.

**Comment by NaphSl** [comment]
> 怎么使用adb logcat获得日志？
> 1.在电脑上下载adb工具包，如果是windows则需要把该包全部解压到 C:/windows 下，如果是based on debian的linux系统，直接 sudo apt install adb fastboot就可以。
> 2.需要设备root，前往设备的“开发者选项”中，打开“usb调试”功能。
> 3.连接到电脑，如果是windows，此时需要打开”命令提示符“，如果是Linux或者mac则需要打开终端，输入adb devices后，在设备上的新弹窗中勾选“一律允许使用该电脑进行调试”后点击确定。
> 4.再输入 adb logcat > log.txt，再返回到桌面，复现一次操作，按下ctrl+c即可，此时找到 log.txt这个文件，里面记录的内容就是所需要的日志。

我的这个android x86_64找不到usb调试模式。插到电脑以后只能充电。
啊，为了方便，我干脆直接给一个Android的下载地址：https://osdn.net/projects/android-x86/downloads/71931/android-x86_64-9.0-r2.iso
不知道为什么甚至没有开发者选项。离谱。

**Comment by NaphSl** [comment]
也许问题是出在surface3上？因为它确实非常旧了.

**Comment by yuhan6665** [comment]
@NaphSl I might be able to fix this issue. Are you willing to do some test with my build?
https://github.com/yuhan6665/v2rayNG/releases/download/aar-test/v2rayNG_1.5.6_x86.apk
1. delete current version
2. install and launch
3. if it doesn't crash, take a look in "Geo asset files" see if there is any files
4. take a look in "logcat" and post your log in Github

**Comment by swordsmile** [comment]
> 在Android x86 9.0上打开V2RayNG,会立刻闪退，无法使用。
> 设备是surface3
> (救命啊，这玩意的日志怎么找)

我也发生闪退，后面安装商店版本也一样。
我通过日志发现闪退的原因是缺少数据文件。
我的解决办法：
adb push geoip.dat /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/
adb push geosite.dat /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/

日志：
AndroidRuntime: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat (Permission denied)

**Comment by yuhan6665** [comment]
@swordsmile thanks for providing key logs. Will fix in next version.
