### ISSUE TITLE
远程dns问题

### ISSUE THREAD

**Issue by GGttyyy** [2dust/v2rayNG#816]
### 预期行为
默认使用vps自带dns

### 实际行为
默认为1.1.1.1

**Comment by ghost** [comment]
v2ray-core的远程dns本身设置的就是如果无自定义设置的情况下使用1.1.1.1的。
目前，上游的v2ray-core没有自动获取vps的dns自动下发到客户端的功能，因此你的需求无法实现。因为v2rayng只是一个图形界面客户端。并不负责维护v2ray-core。

**Comment by yuhan6665** [comment]
If your vps has a DOH server you can use that in v2rayNG. Otherwise your vps need to be configured to "hijack" all DNS traffic.

**Comment by GGttyyy** [comment]
> v2ray-core的远程dns本身设置的就是如果无自定义设置的情况下使用1.1.1.1的。
> 目前，上游的v2ray-core没有自动获取vps的dns自动下发到客户端的功能，因此你的需求无法实现。因为v2rayng只是一个图形界面客户端。并不负责维护v2ray-core。

windows 的 v2rayN 就是用的vps的DNS吧。
有个纯ipv6 的vps 要用专门的DNS ,默认1.1.1.1上不了网v2rayng只能手动设置那个dns，v2rayN就不用额外设置。

**Comment by ghost** [comment]
同样的问题，WIN不用额外设置。
