### ISSUE TITLE
部分vmess链接无法识别

### ISSUE THREAD

**Issue by miaopasimiao** [2dust/v2rayNG#818]
vmess://eyJ2IjoiMiIsInBzIjoi6Ieq55SoTElOT0RF5pel5pysMiAtIGhraXjnm7Tov54gQ0xPVURGTEFSRSAgQ0ROMeenu-WKqOWuveW4puS4k-eUqCIsImFkZCI6InRlc3QudGVzdCIsInBvcnQiOjQ0MywiaWQiOiIyMmI3NTQ3NC00MzI4LTRkYzUtYWRlNC0wOTIzMzY2ZmUzYTEiLCJhaWQiOjAsIm5ldCI6IndzIiwidHlwZSI6IiIsImhvc3QiOiJ0ZXN0LnRlc3QiLCJwYXRoIjoiL3YycmF5L2QwYzkxYWIvIiwidGxzIjoidGxzIn0
类似这样的链接，pc端可以导入，但是手机端无法识别

**Comment by yuhan6665** [comment]
Fix in https://github.com/2dust/v2rayNG/pull/1116
