### ISSUE TITLE
安卓10每次从下拉状态栏快速连接显示初次使用要到APP配置文件

### ISSUE THREAD

**Issue by KouyaOsamu** [2dust/v2rayNG#819]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
应该直接连接成功

### 实际行为
显示初次使用要到APP配置文件

### 复现方法
1.点击状态栏的V图标
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
For first time usage, you need to start from the app to accept the VPN prompt.

**Comment by KouyaOsamu** [comment]
> For first time usage, you need to start from the app to accept the VPN prompt.

But I am not using it for the first time, it also shows the same prompt

**Comment by yuhan6665** [comment]
hmm.. might be a problem in DPreference. Did you find anyway to workaround this issue? like start connection multiple times, change active server, change settings, re-start v2rayNG, re-install v2rayNG?

**Comment by KouyaOsamu** [comment]
> hmm.. might be a problem in DPreference. Did you find anyway to workaround this issue? like start connection multiple times, change active server, change settings, re-start v2rayNG, re-install v2rayNG?

Oh, after I stopped it forcibly in the application information of v2rayNG, it returned to normal, thank you！！！

**Comment by yuhan6665** [comment]
No problem, let us know if anyone see similar issues
