### ISSUE TITLE
我用的极米投影 GMUI 基于 Android 6.0 系统，点击按钮后，app直接关闭。

### ISSUE THREAD

**Issue by MrBenWang** [2dust/v2rayNG#82]
我把1.1.0 的五个版本全部下载试了一遍，下面的三个版本都是安装成功，配置也成功，在点击链接按钮的时候，app直接关闭，没有任何提示。 
app-arm64-v8a-release.apk
app-armeabi-v7a-release.apk
app-universal-release.apk

我印象中，使用 去年的版本好像是可以的，在releases 中也没有找到老版本了。。不知道是已经放弃Android低版本，还是因为 GMUI 系统的升级导致的。

**Comment by MrBenWang** [comment]
我用adb 捕捉到了 日志，全文如下：

`--------- beginning of crash

08-25 00:05:35.717 13225 13225 E AndroidRuntime: FATAL EXCEPTION: main
08-25 00:05:35.717 13225 13225 E AndroidRuntime: Process: com.v2ray.ang, PID: 13225
08-25 00:05:35.717 13225 13225 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}; have you declared this activity in your AndroidManifest.xml?
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1803)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1521)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:3917)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:3877)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at com.v2ray.ang.ui.MainActivity$onCreate$1.onClick(MainActivity.kt:76)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.View.performClick(View.java:5198)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.View.onKeyUp(View.java:9879)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.KeyEvent.dispatch(KeyEvent.java:2805)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.View.dispatchKeyEvent(View.java:9234)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2460)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1740)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v4.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:130)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2375)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
08-25 00:05:35.717 13225 13225 E AndroidRuntime:        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodM
08-25 00:05:35.719  2145  2157 W ActivityManager:   Force finishing activity com.v2ray.ang/.ui.MainActivity`

**Comment by MrBenWang** [comment]
折腾到凌晨两点，终于搞定了。是因为ROM 被精简了vpn模块导致的，我单独安装了，com.android.vpndialogs 还是提示缺少  com.sec.android.app.CscFeature。 在网上找不到改apk，我在Android 6.0 里面，也没有找到。 无奈，使用了最简单的方法，我退回了GMUI的系统，vpn软件使用成功。

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sec.android.app.CscFeature" on path: DexPathList[[zip file "/data/app/com.android.vpndialogs-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.vpndialogs-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by chenjun1206** [comment]
大佬，我也碰到了这个问题，是怎么解决的呢？

**Comment by GuoYuefei** [comment]
NEW Z6X是不是不能刷固件啊，我一直失败~~~根本到不了升级界面

**Comment by BlueNoob** [comment]
不能解ADB了好像，你们有啥法子不？
