### ISSUE TITLE
websockt + TLS + 域名 + CDN 此情况下无法使用绕过大陆或GOE路由

### ISSUE THREAD

**Issue by miaojianbin** [2dust/v2rayNG#82]
### 预期行为
大陆地址直连，国外地址走v2ray

### 实际行为
大陆地址可以访问，国外地址不通

### 复现方法
1.
2.
3.

### 日志信息
<details>
06-24 10:46:21.291 I/GoLog   (24331): 2018/06/24 02:46:21 udp:127.0.0.1:54731 accepted udp:8.8.8.8:53 
06-24 10:46:21.334 I/GoLog   (24331): Using Prepared Domain Name: TCP, v2.mjbbwg.tk:443
06-24 10:46:21.334 I/GoLog   (24331): Protecting Sock: 167
06-24 10:46:21.335 I/GoLog   (24331): (*net.TCPAddr)(0x44235cb740)(104.27.188.147:443)
06-24 10:46:21.335 I/GoLog   (24331): (map[string]*net.TCPAddr) (len=1) {
06-24 10:46:21.335 I/GoLog   (24331):  (string) (len=16) "xxxxxx.tk:443": (*net.TCPAddr)(0x44235cb740)(104.27.188.147:443)
06-24 10:46:21.335 I/GoLog   (24331): }

</details>

以上隐藏了真实域名。怀疑是域名和CDN匹配问题导致。看服务端日志，请求没有到达v2ray

### 环境信息
Android 8.0.0

**Comment by levilovearch** [comment]
我使用该配置出现无限自动连接断开的现象
在linux pc上能正常使用
