### ISSUE TITLE
远程dns实际行为不符

### ISSUE THREAD

**Issue by simpleandstupid** [2dust/v2rayNG#822]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
将远程dns设为localhost时应使用vps的dns

### 实际行为
实际仍然向1.1.1.1发送请求

### 复现方法
1.远程dns设为localhost
2.连接节点
3.日志中dns仍然走1.1.1.1

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
Android10 v2rayng1.5.6
### 额外信息（可选）
在将远程dns设为localhost后将节点导出完整配置，发现json中“servers"内容仍为1.1.1.1，而非预期的localhost。
自定义配置中将servers项内容改为localhost后实际使用日志中仍向1.1.1.1发送dns请求。
在qv2ray中将dns设为localhost的行为正常，ng则不生效

**Comment by guanhemeng** [comment]
vps的dns指向adguardhome

**Comment by rurirei** [comment]
v2fly/v2ray-core#572

**Comment by Hubedge** [comment]
`1.6.22`版本，远程 DNS 和 境内 DNS 均仍未支持填写`localhost`（生成的配置文件内DNS服务器为上次设置的），希望修复

https://www.v2ray.com/chapter_02/04_dns.html#dnsobject
