### ISSUE TITLE
Trojan协议验证问题

### ISSUE THREAD

**Issue by mglwolf** [2dust/v2rayNG#825]
请问trojan-go 协议是否支援？
在Trojan的安卓客户端有个位置可以关掉”证书验证“，v2ray-ng是怎样实现的？
谢谢

**Comment by yuhan6665** [comment]
https://www.v2fly.org/config/transport.html#tlsobject

**Comment by mglwolf** [comment]
{
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
        {
            "port": 10800,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "trojan",
            "settings": {
                "servers": [
                    {
                        "address": "mydomain",
                        "port": the port,
                        "password": "mypassword"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls"
                "tlsSettings": {
                "serverName": "mydomain",
                "allowInsecure": false
                }               
            }
        }
    ]
}

**Comment by mglwolf** [comment]
> https://www.v2fly.org/config/transport.html#tlsobject
这是我的客户端配置，请指教


{
    "log": {
        "loglevel": "info"
    },
    "inbounds": [
        {
            "port": 10800,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "trojan",
            "settings": {
                "servers": [
                    {
                        "address": "mydomain",
                        "port": the port,
                        "password": "mypassword"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "tls",
                "tlsSettings": {
                "serverName": "mydomain",
                "allowInsecure": true
                }               
            }
        }
    ]
}
