### ISSUE TITLE
希望加入开机自动启动功能

### ISSUE THREAD

**Issue by PowerWordTree** [2dust/v2rayNG#829]
我习惯一直开着代理，以方便访问反向代理。
希望加入开机自动启动功能，谢谢。

**Comment by ghost** [comment]
你可以尝试在系统里打开”始终开启的VPN“功能，它可以变相实现该需求。
![](https://i.imgur.com/hLJoz0k.png)

**Comment by PowerWordTree** [comment]
试过以后确实解决了，十分感谢。
