### ISSUE TITLE
使用带验证的sock无法连接，user:pass@ip

### ISSUE THREAD

**Issue by brick2008** [2dust/v2rayNG#83]
使用带验证的sock无法连接，服务器地址填的是：user:pass@ip

08-25 23:13:16.493 I/GoLog (26793): Dial pending prepare ... user:pass@ip:port
08-25 23:13:16.982 I/GoLog (26793): PrepareDomain SplitHostPort Err: address user:pass@ip:port: too many colons in address
08-25 23:13:16.982 I/GoLog (26793): PrepareDomain err: address user:pass@ip:port: too many colons in address

另外希望添加socks配置时可以有填写用户名和密码的地方

**Comment by 2dust** [comment]
到1.10版本,不支持此功能
下一版加上
