### ISSUE TITLE
大量 avc: denied {ioctl} 问题，没有流量

### ISSUE THREAD

**Issue by cortis007** [2dust/v2rayNG#831]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为

配置完毕后，点击V按钮启动代理

### 实际行为

相同配置、相同版本V2rayNG在低版本Android系统(EMUI 9) 中可正常代理，在高版本Android系统中（EMUI 11），启动代理后，
V2rayNG界面中提示服务启动成功，在手机提示信息栏也出现V2rayNG和代理标识，但其他程序仍无法走代理，无科学流量
同时在日志中出现大量avc: denied {ioctl} 问题

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
XX-XX XX:XX:XX.XXX W/com.v2ray.ang(28679): type=1400 audit(0.0:43559): avc: denied { ioctl } for pid=28679 path="/proc/28679/rtg" dev="proc" ino=278564 ioctlcmd=0xab20 scontext=u:r:untrusted_app:s0:c9,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c9,c257,c512,c768 tclass=file permissive=0
```
</details>

### 环境信息

Android 10, EMUI 11.0.0, Kyrin 9000, 无法解锁
v2rayNG_1.4.13_x86_64.apk, v2rayNG_1.5.7_arm64-v8a.apk

**Comment by yuhan6665** [comment]
Thanks for reporting this issue. Can you do some test on your device?
1. run command `dumpsys | grep 28679` in adb shell and paste the output here
2. try [proxy only mode](https://github.com/2dust/v2rayNG/wiki/Mode) and see if it works on that device
