### ISSUE TITLE
在电脑和路由器上都有效的链接在手机上就联不上网

### ISSUE THREAD

**Issue by NilvalueReset** [2dust/v2rayNG#833]
点击测试连接就弹出
Get "http://www.google.com/gen_204": io: read/write on closed pipe

### 日志信息
--------- beginning of main
01-07 14:34:48.794 I/GoLog   (16950): loading v2ray config
01-07 14:34:48.795 I/GoLog   (16950): Preparing Domain: 66.42.73.62:886
01-07 14:34:48.801 I/GoLog   (16950): Prepare Result:
01-07 14:34:48.801 I/GoLog   (16950):  Domain: 66.42.73.62
01-07 14:34:48.801 I/GoLog   (16950):  Port: 886
01-07 14:34:48.801 I/GoLog   (16950):  IPs: [66.42.73.62]
01-07 14:34:48.822 I/GoLog   (16950): new v2ray core
01-07 14:34:48.824 I/GoLog   (16950): start v2ray core
01-07 14:34:48.824 I/GoLog   (16950): [Warning] v2ray.com/core: V2Ray 4.31.3 started
01-07 14:34:48.881 D/com.v2ray.v2fly(16950): [/data/app/com.v2ray.v2fly-Ak-7IBE3ptYOkbw18BGcNw==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, notice]
01-07 14:34:48.887 D/com.v2ray.v2fly(16950): Process[pid=27562, hasExited=false]
01-07 14:34:48.887 D/com.v2ray.v2fly(16950): /data/user/0/com.v2ray.v2fly/files/sock_path
01-07 14:34:48.897 I/tun2socks(27562): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
01-07 14:34:48.939 D/com.v2ray.v2fly(16950): sendFd tries: 0
01-07 14:34:48.942 I/tun2socks(27562): NOTICE(tun2socks): entering event loop
01-07 14:34:49.090 I/GoLog   (16950): udp:127.0.0.1:46028 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:49.094 I/GoLog   (16950): tcp:127.0.0.1:57434 accepted tcp:52.81.112.53:5229 [proxy] 
01-07 14:34:49.103 I/GoLog   (16950): udp:127.0.0.1:38554 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:49.306 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:49.306 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:49.323 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:49.862 I/GoLog   (16950): udp:127.0.0.1:54394 accepted udp:61.132.163.68:53 [proxy] 
01-07 14:34:50.070 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:50.880 I/GoLog   (16950): udp:127.0.0.1:57985 accepted udp:202.102.213.68:53 [proxy] 
01-07 14:34:51.096 I/GoLog   (16950): udp:127.0.0.1:46028 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:51.104 I/GoLog   (16950): udp:127.0.0.1:38554 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:51.312 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:51.902 I/GoLog   (16950): udp:127.0.0.1:60939 accepted udp:61.132.163.68:53 [proxy] 
01-07 14:34:52.107 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:52.141 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:52.345 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:52.913 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:53.929 I/GoLog   (16950): udp:127.0.0.1:36248 accepted udp:202.102.213.68:53 [proxy] 
01-07 14:34:54.100 I/GoLog   (16950): udp:127.0.0.1:57862 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:54.107 I/GoLog   (16950): udp:127.0.0.1:52399 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:54.145 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:54.169 I/GoLog   (16950): udp:127.0.0.1:56515 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:54.319 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:54.388 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:55.215 D/com.v2ray.v2fly(16950): measureV2rayDelay: Get "http://www.google.com/gen_204": io: read/write on closed pipe
01-07 14:34:55.336 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:55.971 I/GoLog   (16950): udp:127.0.0.1:46767 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:56.161 I/GoLog   (16950): udp:127.0.0.1:56515 accepted udp:1.1.1.1:53 [proxy] 
01-07 14:34:56.186 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:56.366 I/GoLog   (16950): Using Prepared: 66.42.73.62
01-07 14:34:56.476 D/com.v2ray.v2fly(16950): tun2socks destroy
01-07 14:34:56.477 I/tun2socks(27562): NOTICE(tun2socks): termination requested
01-07 14:34:56.477 I/tun2socks(27562): NOTICE(tun2socks): tearing down
01-07 14:34:56.477 I/tun2socks(27562): NOTICE(tun2socks): Free TCP connections
01-07 14:34:56.477 I/tun2socks(27562): NOTICE(tun2socks): exiting

**Comment by FightToDawn** [comment]
同样问题。求解

**Comment by 0x8f701** [comment]
same here

**Comment by nicolasking84** [comment]
索尼电视上装的v2rayng1.5.11突然也出现这个问题io:read/write on closed pipe，卸载重装老版本也没用

**Comment by daniuwo** [comment]
我也是io: read/write on closed pipe，手机连不上，电脑可以连，手机时间与服务器时间分秒不差

**Comment by ynnie** [comment]
同样问题，电脑可以正常使用，手机APP连不上，手机和服务器时间都已经联网同步过。

**Comment by daniuwo** [comment]
> 同样问题，电脑可以正常使用，手机APP连不上，手机和服务器时间都已经联网同步过。

我下载最新版解决了，先删除旧版
