### ISSUE TITLE
不知道下载哪一个版本

### ISSUE THREAD

**Issue by pangfeiyo** [2dust/v2rayNG#834]
看了下发布里，一共有4个版本可供选择：
v2rayNG_1.5.8_arm64-v8a.apk
v2rayNG_1.5.8_armeabi-v7a.apk
v2rayNG_1.5.8_x86.apk
v2rayNG_1.5.8_x86_64.apk
使用的是米11，请问应该下载哪一个版本？这4个版本有什么区别？

感谢！

**Comment by kolicime** [comment]
v2rayNG_1.5.8_arm64-v8a.apk

**Comment by pangfeiyo** [comment]
> v2rayNG_1.5.8_arm64-v8a.apk
感谢，能再帮忙解释下这4个版本的区别吗

**Comment by yuhan6665** [comment]
https://www.howtogeek.com/339665/how-to-find-your-android-devices-info-for-correct-apk-downloads/
