### ISSUE TITLE
无法全局代理

### ISSUE THREAD

**Issue by bestmikecat** [2dust/v2rayNG#835]
仅ipv6的vps，使用dns64,采用vless+ws+tls+cdn,在电脑上的v2ray客户端使用一切正常，但在手机端按全局配置操作却不行，然后我将设置中的"ipv6优先"打开，再将远程DNS改为ipv6的Dns，发现只有google等国外网站可以打开，国内网站均不行，只有关闭上述，使用绕过大陆网站模式，才能直连国内网站同时代理国外网站。
用vmess+ws+tls+cdn时也有上述问题，但换用Kitsunebi后一切正常，感觉应该是v2rayng的问题

**Comment by RPRX** [comment]
https://github.com/XTLS/Xray-core/issues/149#issuecomment-759347514

**Comment by yuhan6665** [comment]
@bestmikecat good to know you fix the issue by custom config. If you can put in details what is the change you made. I can potentially make it default for "prefer ipv6"
