### ISSUE TITLE
希望作者考虑增加配置删除确认步骤，以防误触错删配置，感谢

### ISSUE THREAD

**Issue by KGB333** [2dust/v2rayNG#836]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
点击配置删除按钮时，能弹出一个确认框

### 实际行为
点击删除配置按钮，配置立马被删除

### 复现方法
1.点击配置删除按钮

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by iKira** [comment]
配置列表的删除按钮就应该去掉，通过长按某个条目触发多选 (可单选) 进行删除。
