### ISSUE TITLE
libv2ray.aar

### ISSUE THREAD

**Issue by superhero75** [2dust/v2rayNG#837]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

Trying to compile v2ray the latest 4.34 libv2ray.aar  but compilation failed. is there any need for code to accommodate quic modification?
### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么
error message:
# v2ray.com/core/transport/internet/quic
../v2ray.com/core/transport/internet/quic/dialer.go:153:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
../v2ray.com/core/transport/internet/quic/hub.go:109:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by yuhan6665** [comment]
Try go mod like this one
https://github.com/2dust/AndroidLibV2rayLite/blob/master/go.mod

**Comment by myflyingfish** [comment]
same question i have solved

**Comment by rurirei** [comment]
same as here.

**Comment by rurirei** [comment]
same as here.
```golang
Error: ../../../v2ray.com/core/app/dns/nameserver_quic.go:365:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
Error: ../../../v2ray.com/core/transport/internet/quic/dialer.go:153:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
Error: ../../../v2ray.com/core/transport/internet/quic/hub.go:108:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
```
how could i fix this on tree (before new module name) v2fly/v2ray-core@108546a

**Comment by myflyingfish** [comment]
unknown field 'HandshakeTimeout' in struct literal of type quic.Config    

change  HandshakeTimeout to   HandshakeDefaultTimeout   try

**Comment by rurirei** [comment]
@myflyingfish thanks for reply. i met this on commit v4.33.0 too as this does not wrong of codes.

**Comment by rurirei** [comment]
> unknown field 'HandshakeTimeout' in struct literal of type quic.Config
> 
> change HandshakeTimeout to HandshakeDefaultTimeout try

unknown field 'HandshakeDefaultTimeout'.

**Comment by rurirei** [comment]
> same as here.
> 
> ```go
> Error: ../../../v2ray.com/core/app/dns/nameserver_quic.go:365:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
> Error: ../../../v2ray.com/core/transport/internet/quic/dialer.go:153:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
> Error: ../../../v2ray.com/core/transport/internet/quic/hub.go:108:3: unknown field 'HandshakeTimeout' in struct literal of type quic.Config
> ```
> 
> how could i fix this on tree (before new module name) [v2fly/v2ray-core@108546a](https://github.com/v2fly/v2ray-core/commit/108546a)

just delete three lines with `HandshakeTimeout` to solve this oL.
