### ISSUE TITLE
移动4g经常断流，重新开关飞行模式就正常了，用其他软件很少出现，应该不是节点问题，能优化一下吗？

### ISSUE THREAD

**Issue by csgowdnmd** [2dust/v2rayNG#841]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by danerlt** [comment]
我也遇到了这个问题,v2rayN1.4.13,1.5.9,1.5.10这三个版本都是一样的,同一个trojan连接,在电脑上使用正常,手机上使用开始正常,用一段时间之后就不行了,重启APP,重启连接之后还是不行.重新开个一下飞行模式之后居然重启连接又可以了.

**Comment by danerlt** [comment]
重新测试了一下 不止是trojan协议,vless也会出现电脑能用,手机不能用,重新开关飞行模式之后能使用. 
vless协议使用的,xray 1.2.1 
trojan协议使用的,trojan-go 0.8.2
V2rayN 1.5.10版本
小米10 Pro 安卓11

**Comment by TianhuaJu** [comment]
我也遇到这样的问题，我用的是v2fly。同时使用的bifrostv软件没这种问题。

**Comment by ghost** [comment]
这个跟软件没有关系，是运营商的决策原因。他们觉得这些TCP连接有问题于是就限制了（我跟地市级的运营商技术人员聊过，如果某个用户长时间连接同一个ip并且不产生任何其他流量的话，则会被激进一些的模板判断为正在使用云免流），这也是为什么开启飞行模式（换一个出口ip）就好的原因。其实这个问题在有线宽带下也是有概率发生的。只不过相对于4G网络较少罢了。

可能有人觉得是不是v2rayng的软件问题把本地的65535个端口全都占满了所以从而导致出现这样的问题？其实跟软件真的没有关系。（如果真的占满了，你会发现通过强行停止方式关掉软件后，vpn模块断开也是照样上不去网的，而据我实际测试，当发生断流现象时，此时通过这种方式关掉软件，并尝试访问一个中国大陆能打开的网站时还是能打开的）

**Comment by danerlt** [comment]
> 这个跟软件没有关系，是运营商的决策原因。他们觉得这些TCP连接有问题于是就限制了（我跟地市级的运营商技术人员聊过，如果某个用户长时间连接同一个ip并且不产生任何其他流量的话，则会被激进一些的模板判断为正在使用云免流），这也是为什么开启飞行模式（换一个出口ip）就好的原因。其实这个问题在有线宽带下也是有概率发生的。只不过相对于4G网络较少罢了。
> 
> 可能有人觉得是不是v2rayng的软件问题把本地的65535个端口全都占满了所以从而导致出现这样的问题？其实跟软件真的没有关系。（如果真的占满了，你会发现通过强行停止方式关掉软件后，vpn模块断开也是照样上不去网的，而据我实际测试，当发生断流现象时，此时通过这种方式关掉软件，并尝试访问一个中国大陆能打开的网站时还是能打开的）

@devinstever ，我前两天有又买了一个ss的帐号，用v2rayn使用开始也是正常的，使用中会出现断流，然后这个时候启动shadowsock，就又可以使用了，(ss协议的配置v2rayn和ss里面都是一样的)。

**Comment by TianhuaJu** [comment]
我遇到的情况是不仅仅在4G网络下，在宽带下也有发生。出现此种情况的时候往往是需要代理的网站刷不出来（比如刷Twitter时无法更新），而直连的网站完全没问题。

> 这个跟软件没有关系，是运营商的决策原因。他们觉得这些TCP连接有问题于是就限制了（我跟地市级的运营商技术人员聊过，如果某个用户长时间连接同一个ip并且不产生任何其他流量的话，则会被激进一些的模板判断为正在使用云免流），这也是为什么开启飞行模式（换一个出口ip）就好的原因。其实这个问题在有线宽带下也是有概率发生的。只不过相对于4G网络较少罢了。
> 
> 可能有人觉得是不是v2rayng的软件问题把本地的65535个端口全都占满了所以从而导致出现这样的问题？其实跟软件真的没有关系。（如果真的占满了，你会发现通过强行停止方式关掉软件后，vpn模块断开也是照样上不去网的，而据我实际测试，当发生断流现象时，此时通过这种方式关掉软件，并尝试访问一个中国大陆能打开的网站时还是能打开的）

**Comment by bhoppi** [comment]
我最近也遇到了这个问题，不限于移动网络。更奇怪的是我用的是UDP（mKCP、QUIC），如果这事跟TCP有关的话，我唯一的TCP连接就是DoH，明天检查一下是不是跟DoH相关。

**Comment by csgowdnmd** [comment]
> 这个跟软件没有关系，是运营商的决策原因。他们觉得这些TCP连接有问题于是就限制了（我跟地市级的运营商技术人员聊过，如果某个用户长时间连接同一个ip并且不产生任何其他流量的话，则会被激进一些的模板判断为正在使用云免流），这也是为什么开启飞行模式（换一个出口ip）就好的原因。其实这个问题在有线宽带下也是有概率发生的。只不过相对于4G网络较少罢了。
> 
> 可能有人觉得是不是v2rayng的软件问题把本地的65535个端口全都占满了所以从而导致出现这样的问题？其实跟软件真的没有关系。（如果真的占满了，你会发现通过强行停止方式关掉软件后，vpn模块断开也是照样上不去网的，而据我实际测试，当发生断流现象时，此时通过这种方式关掉软件，并尝试访问一个中国大陆能打开的网站时还是能打开的）

那我使用ss clash之类的就稳定的多，几乎没有断流，是软件的实现策略不一样？
