### ISSUE TITLE
V2RAYNG解析订阅地址出现失败或者无法解析部分地址

### ISSUE THREAD

**Issue by heptaspirit** [2dust/v2rayNG#843]
使用V2rayNG订阅功能拉取服务器列表，出现部分TROJAN服务器无法解析

### 预期行为
V2rayNG能够正常解析所有trojan服务器

### 实际行为
V2rayNG无法解析部分trojan服务器
尝试使用V2rayN订阅没有任何问题

### 复现方法
1.使用订阅功能
2.主界面点击更新订阅
3.无法拉取全部服务器，查看logcat有相应报错

### 日志信息
<details>

--------- beginning of system
--------- beginning of main
01-14 09:35:06.467 W/System.err(14735): java.net.URISyntaxException: Illegal character in authority at index 9: trojan://【服务器地址】[��[��X�\�OLI�Y\�X���[����\]K���H�QT	P̉P��QM�P��P�IQM�P�	PQ��P̉P��M
01-14 09:35:06.469 W/System.err(14735): 	at java.net.URI$Parser.fail(URI.java:2893)
01-14 09:35:06.469 W/System.err(14735): 	at java.net.URI$Parser.parseAuthority(URI.java:3231)
01-14 09:35:06.469 W/System.err(14735): 	at java.net.URI$Parser.parseHierarchical(URI.java:3142)
01-14 09:35:06.469 W/System.err(14735): 	at java.net.URI$Parser.parse(URI.java:3098)
01-14 09:35:06.469 W/System.err(14735): 	at java.net.URI.<init>(URI.java:584)
01-14 09:35:06.469 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:399)
01-14 09:35:06.469 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:1009)
01-14 09:35:06.469 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:344)
01-14 09:35:06.469 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:457)
01-14 09:35:06.469 W/System.err(14735): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-14 09:35:06.469 W/System.err(14735): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
01-14 09:35:06.469 W/System.err(14735): 	at android.os.Handler.handleCallback(Handler.java:883)
01-14 09:35:06.469 W/System.err(14735): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-14 09:35:06.469 W/System.err(14735): 	at android.os.Looper.loop(Looper.java:214)
01-14 09:35:06.469 W/System.err(14735): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
01-14 09:35:06.469 W/System.err(14735): 	at java.lang.reflect.Method.invoke(Native Method)
01-14 09:35:06.470 W/System.err(14735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 09:35:06.470 W/System.err(14735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-14 09:35:06.473 W/System.err(14735): java.net.URISyntaxException: Illegal character in authority at index 9: trojan://【服务器地址】[��[��X�\�OLI�Y\�Y�ۛ�Y��[����\]K���H�QNIPP�NN	QNIN	NQ�P̉P��QNIPM�NNIQM�P�	PQ��P̉P��̌�	P̉P��QM�PNIP�IQNINM�P��P̉P��IQMIN	N	P̉P��QN	N�N�QMINL	N	QM	P�	PQ	QN	P�	PP�QM	P��NN	QMIN�NM�P̉P��LB��ژ[���ې�՝ݐ��M͋�݋��[���̌O�[��[��X�\�OLI�Y\�X���[����\]K���H�QNIPP�NN	QNIN	NQ�P̉P��QNIPM�NNIQM�P�	PQ��P̉P��̌�IP̉P��QM�PNIP�IQNINM�P��P̉P��IQMIN	N	P̉P��QN	N�N�QMINL	N	QM	P�	PQ	QN	P�	PP�QM	P��NN	QMIN�NM�P̉P��LB��ژ[���ې�՝ݐڞ���]���[���LO�[��[��X�\�OLI�Y\�X���[����\]K���H�QNIPP�NN	QNIN	NQ�P̉P��QNIPM�NNIQM�P�	PQ��P̉P��̌N	P̉P��QM�PNIP�IQNINM�P��P̉P��IQMIN	N	P̉P��QM	P�	NIQM�P�IP��QM	P�	PQ	QN	P�	PP�QM	P��NN	QMIN�NM�P̉P��LB��ژ[���ې�՝ݐ���K�
01-14 09:35:06.473 W/System.err(14735): 	at java.net.URI$Parser.fail(URI.java:2893)
01-14 09:35:06.473 W/System.err(14735): 	at java.net.URI$Parser.parseAuthority(URI.java:3231)
01-14 09:35:06.473 W/System.err(14735): 	at java.net.URI$Parser.parseHierarchical(URI.java:3142)
01-14 09:35:06.473 W/System.err(14735): 	at java.net.URI$Parser.parse(URI.java:3098)
01-14 09:35:06.473 W/System.err(14735): 	at java.net.URI.<init>(URI.java:584)
01-14 09:35:06.473 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:399)
01-14 09:35:06.473 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:1009)
01-14 09:35:06.473 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:344)
01-14 09:35:06.473 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:457)
01-14 09:35:06.473 W/System.err(14735): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-14 09:35:06.473 W/System.err(14735): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
01-14 09:35:06.473 W/System.err(14735): 	at android.os.Handler.handleCallback(Handler.java:883)
01-14 09:35:06.473 W/System.err(14735): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-14 09:35:06.473 W/System.err(14735): 	at android.os.Looper.loop(Looper.java:214)
01-14 09:35:06.473 W/System.err(14735): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
01-14 09:35:06.473 W/System.err(14735): 	at java.lang.reflect.Method.invoke(Native Method)
01-14 09:35:06.474 W/System.err(14735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 09:35:06.474 W/System.err(14735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-14 09:35:06.474 W/System.err(14735): java.net.URISyntaxException: Illegal character in authority at index 9: trojan://【服务器地址】[��[��X�\�OLI�Y\�Y�ۛ�Y��[����\]K���H�QNIPP�NN	QNIN	NQ�P̉P��QNIPM�NNIQM�P�	PQ��P̉P�̌
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.fail(URI.java:2893)
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.parseAuthority(URI.java:3231)
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.parseHierarchical(URI.java:3142)
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.parse(URI.java:3098)
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI.<init>(URI.java:584)
01-14 09:35:06.474 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:399)
01-14 09:35:06.474 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:1009)
01-14 09:35:06.474 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:344)
01-14 09:35:06.474 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:457)
01-14 09:35:06.474 W/System.err(14735): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-14 09:35:06.474 W/System.err(14735): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
01-14 09:35:06.474 W/System.err(14735): 	at android.os.Handler.handleCallback(Handler.java:883)
01-14 09:35:06.474 W/System.err(14735): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-14 09:35:06.474 W/System.err(14735): 	at android.os.Looper.loop(Looper.java:214)
01-14 09:35:06.474 W/System.err(14735): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
01-14 09:35:06.474 W/System.err(14735): 	at java.lang.reflect.Method.invoke(Native Method)
01-14 09:35:06.474 W/System.err(14735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 09:35:06.474 W/System.err(14735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-14 09:35:06.474 W/System.err(14735): java.net.URISyntaxException: Illegal character in authority at index 9: trojan://【服务器地址】[��[��X�\�OLI�Y\�Y�ۛ�Y��[����\]K���H�QMININQ�QM�NM	NQ�P̉P��QM�NM�PMIQM�NP�PPҔ	P̉P��LIP̉P��QM�PNIP�IQNINM�P��P̉P��IQMIN	N	P̉P��QM	P�	NIQM�P�IP��QM	P�	PQ	QN	P�	PP�QM	P��NN	QMIN�NM�P̉P�̌B��ژ[���ې�՝ݐLˍ̋��̎�
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.fail(URI.java:2893)
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.parseAuthority(URI.java:3231)
01-14 09:35:06.474 W/System.err(14735): 	at java.net.URI$Parser.parseHierarchical(URI.java:3142)
01-14 09:35:06.475 W/System.err(14735): 	at java.net.URI$Parser.parse(URI.java:3098)
01-14 09:35:06.475 W/System.err(14735): 	at java.net.URI.<init>(URI.java:584)
01-14 09:35:06.475 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:399)
01-14 09:35:06.475 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:1009)
01-14 09:35:06.475 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:344)
01-14 09:35:06.475 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:457)
01-14 09:35:06.475 W/System.err(14735): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-14 09:35:06.475 W/System.err(14735): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
01-14 09:35:06.475 W/System.err(14735): 	at android.os.Handler.handleCallback(Handler.java:883)
01-14 09:35:06.475 W/System.err(14735): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-14 09:35:06.475 W/System.err(14735): 	at android.os.Looper.loop(Looper.java:214)
01-14 09:35:06.475 W/System.err(14735): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
01-14 09:35:06.475 W/System.err(14735): 	at java.lang.reflect.Method.invoke(Native Method)
01-14 09:35:06.475 W/System.err(14735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 09:35:06.475 W/System.err(14735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-14 09:35:06.480 W/System.err(14735): java.net.URISyntaxException: Illegal character in authority at index 9: trojan://【服务器地址】[��[��X�\�OLI�Y\�Y�ۛ�Y��[����\]K���H�QM�P�INIQMIPPINL�QM	P�	NL�P̉P��QM�P�INIQMINP�P�T�P̉P��LM�P̉P��QM�PNIP�IQNINM�P��P̉P��QM	P�	N	QNINNINL	QM�P�INIQNIN
01-14 09:35:06.480 W/System.err(14735): 	at java.net.URI$Parser.fail(URI.java:2893)
01-14 09:35:06.480 W/System.err(14735): 	at java.net.URI$Parser.parseAuthority(URI.java:3231)
01-14 09:35:06.480 W/System.err(14735): 	at java.net.URI$Parser.parseHierarchical(URI.java:3142)
01-14 09:35:06.480 W/System.err(14735): 	at java.net.URI$Parser.parse(URI.java:3098)
01-14 09:35:06.480 W/System.err(14735): 	at java.net.URI.<init>(URI.java:584)
01-14 09:35:06.480 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:399)
01-14 09:35:06.480 W/System.err(14735): 	at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:1009)
01-14 09:35:06.480 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:344)
01-14 09:35:06.480 W/System.err(14735): 	at com.v2ray.ang.ui.MainActivity$importConfigViaSub$1$1.invokeSuspend(MainActivity.kt:457)
01-14 09:35:06.480 W/System.err(14735): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-14 09:35:06.480 W/System.err(14735): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
01-14 09:35:06.480 W/System.err(14735): 	at android.os.Handler.handleCallback(Handler.java:883)
01-14 09:35:06.480 W/System.err(14735): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-14 09:35:06.480 W/System.err(14735): 	at android.os.Looper.loop(Looper.java:214)
01-14 09:35:06.480 W/System.err(14735): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
01-14 09:35:06.480 W/System.err(14735): 	at java.lang.reflect.Method.invoke(Native Method)
01-14 09:35:06.481 W/System.err(14735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 09:35:06.481 W/System.err(14735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

</details>

### 环境信息
一加7pro
安卓10
v2rayNG 1.5.9

### 额外信息（可选）v2
额外测试的v2rayN版本3.29

**Comment by yuhan6665** [comment]
Illegal character in authority at index 9

**Comment by heptaspirit** [comment]
> 
> 
> Illegal character in authority at index 9

奇怪的是同一订阅地址拉取，桌面版的V2rayN可以完整解析，没有任何报错
但安卓的V2rayNG就会有描述的illegal character导致无法解析部份地址
我可以提供订阅拉取的内容协助测试

**Comment by qihang518887** [comment]
我也同样出现了这个问题，将小火箭的订阅托管为v2ray再导入后，会提示失败

**Comment by South-J** [comment]
类似的情况，仍未解决，gtneo报错是5223
