### ISSUE TITLE
v2ray core  v4.34已经发布十多天了...但是我仍旧只能找到v4.33的版本，请大佬更新Orz

### ISSUE THREAD

**Issue by OsM3rcury** [2dust/v2rayNG#845]

**Comment by beatbaozi** [comment]
同求更新

**Comment by Fhokud** [comment]
xray-core完全兼容v2ray-core，且v2ray core v4.34.0更新的内容xray-core v1.1.3就有了。
目前v2rayNG最新版v1.5.11已经xray-core v1.2.2了

v2ray-core v4.34的版本似乎没有必要

**Comment by Tomhoney** [comment]
我都他妈不会下载   我手机下载就提示我不可下载

**Comment by haomuch** [comment]
用xray core版本你会被开除国籍吗？

**Comment by OsM3rcury** [comment]
> 用xray core版本你会被开除国籍吗？

你真有趣...你知道就代表所有人都知道了?我就爱用v2ray core行不行？在哪都能口嗨,纯sb

**Comment by haomuch** [comment]
> > 用xray core版本你会被开除国籍吗？
> 
> 你真有趣...你知道就代表所有人都知道了?我就爱用v2ray core行不行？在哪都能口嗨,纯sb

你他妈脑子可能早就被狗吃了，ng早就不用v2ray core，就你这种喜欢吃屎的狗，还一直念念不忘，大佬需要理会你这种傻逼吗？滚你妈逼的吧

**Comment by OsM3rcury** [comment]
> > > 用xray core版本你会被开除国籍吗？
> > 
> > 
> > 你真有趣...你知道就代表所有人都知道了?我就爱用v2ray core行不行？在哪都能口嗨,纯sb
> 
> 你他妈脑子可能早就被狗吃了，ng早就不用v2ray core，就你这种喜欢吃屎的狗，还一直念念不忘，大佬需要理会你这种傻逼吗？滚你妈逼的吧

你真丢人,可别再跟我扯皮了
