### ISSUE TITLE
请问如何去掉手机设置里面始终和vpn保持莲姐姐状态变得不可点击啊

### ISSUE THREAD

**Issue by WangYuana** [2dust/v2rayNG#851]
请问如何不能通过安卓手机设置里面的vpn-始终和vpn保持连接状态变得不可点击即啊，我们借助你们的源码做了个vpn不想用户通过这个漏洞造成损失，谢谢。

> 

-

**Comment by ghost** [comment]
系统问题一个普通软件无法控制哦。建议如果是特殊用途，能自行控制设备系统的话，修改一下系统。
