### ISSUE TITLE
vless分享链接问题

### ISSUE THREAD

**Issue by Butterflyflower** [2dust/v2rayNG#852]
### 预期行为
正常导入分享链接

### 实际行为
失败

### 复现方法
1
自定义id使用"#""@"等符号
2
vless://#7544@@udhdhjv.xyz:443?security=xtls&encryption=none&headerType=none&type=tcp&flow=xtls-rprx-splice#%F0%9F%87%B8%F0%9F%87%AC%E6%96%B0%E5%8A%A0%E5%9D%A1

**Comment by Butterflyflower** [comment]
Trojan 协议也有此问题

**Comment by 2dust** [comment]
https://github.com/XTLS/Xray-core/issues/91

**Comment by 2dust** [comment]
按照现有的分享提案,id只能不要用特殊符号.
分享使用json格式并适当的转码更合适也更容易解码,但是大部分人都觉得太土了.

**Comment by 2dust** [comment]
我个人觉得分享使用json格式并适当的转码更合适,但是大部分人都觉得太土了.
