### ISSUE TITLE
电视盒子下用遥控器点不到连接按钮

### ISSUE THREAD

**Issue by quuboo** [2dust/v2rayNG#856]
电视盒子下安了app，其他都ok，但是用遥控器挪不到开始连接那个圆按钮，希望改进，多谢。

**Comment by lhy0838** [comment]
+1

**Comment by 2dust** [comment]
右上角点服务重启

**Comment by libook** [comment]
上面这个回答是正解。用遥控器可以用方向键选到右上角，然后在菜单里选择服务重启。

不过前提是你已经选好了可用的连接，否则还是得接鼠标搞。

**Comment by liuzhuo12** [comment]
我一般都是把焦点用遥控器方向键调整到最下面测试连接的地方,然后安一下遥控器方向键的上按键,这时候焦点就在连接的圆形图标上了,点击遥控器的确定键就可以连接了.
