### ISSUE TITLE
仅代理中国大陆IP策略

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#857]
### 预期行为
预定义规则新加一个仅代理中国大陆IP地址/域名的策略  让境外的人可以在翻回去的同时不影响上Google等被大陆政府审计的站点

**Comment by ghost** [comment]
代理规则方面Android这边能用的几乎只有clash了..

**Comment by haomuch** [comment]
自定义配置规则里完全可以实现

**Comment by hardywu** [comment]
@haomuch  怎么设置？ 新版本默认全proxy

**Comment by haomuch** [comment]
> @haomuch 怎么设置？ 新版本默认全proxy

可以设置默认直连啊，geoip:cn走代理

**Comment by hardywu** [comment]
> > @haomuch 怎么设置？ 新版本默认全proxy
> 
> 可以设置默认直连啊，geoip:cn走代理

我还纠结 geosite:cn direct 怎么走不通。 谢了。
