### ISSUE TITLE
io: read/write on closed pipe

### ISSUE THREAD

**Issue by dulm** [2dust/v2rayNG#859]
我有两台 v2ray 服务器,  电脑上两台都能连.

手机上 v2rayng, 只能连 国外的 域名 cloudra加密 +ws 的,   国内 直接ip+ws的测试会报错:`io: read/write on closed pipe`

**Comment by panyang05** [comment]
我也有同样问题

**Comment by ghost** [comment]
当出现 io: read/write on closed pipe 时 代表tcp连接建立不成功。如确定服务器正常的话，此时使用者应首先检查设备网络连接问题，若为海外出口，其次应该检查代理服务器节点是否被封。

关于你提到的问题，其实任何一个CDN服务商都是不允许裸ip访问的。

**Comment by dulm** [comment]
> 当出现 io: read/write on closed pipe 时 代表tcp连接建立不成功。如确定服务器正常的话，此时使用者应首先检查设备网络连接问题，若为海外出口，其次应该检查代理服务器节点是否被封。
> 
> 关于你提到的问题，其实任何一个CDN服务商都是不允许裸ip访问的。

没法解释电脑可以, 手机不可以啊

**Comment by 62019** [comment]
一样

**Comment by xeniumlee** [comment]
可能的原因：服务端证书不是fullchain，手机App没法验证完整证书链。windows上有预装证书，所以电脑客户端可以验证证书链。

**Comment by yuchuanxi** [comment]
一样的问题，有啥解决办法没。ss可以用

**Comment by truenetyes** [comment]
有解决方法了吗

**Comment by truenetyes** [comment]
能私聊一下么

**Comment by itisit2** [comment]
证书问题
