### ISSUE TITLE
三星note20u 与google服务器通信是出现问题

### ISSUE THREAD

**Issue by zhejiulipu** [2dust/v2rayNG#861]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
应该正常连接

### 实际行为
无法连接google

### 复现方法
1.同样的服务器使用华为p10可以上，但是note20u却不可以
2.
3.

### 额外信息（可选）
用老王vpn可以上，但是这个不行，怀疑是我的配置问题

**Comment by ghost** [comment]
这不是软件问题，目前软件已经解决了因为代理规则不精细导致的 从服务器检索信息出错 问题了。
看上去像是使用者用了阿里云腾讯云这种会被Google识别为中国大陆ip地址的出口导致的此问题，或者客户端没有更新到最新导致的。

**Comment by zhejiulipu** [comment]
> 这不是软件问题，目前软件已经解决了因为代理规则不完全导致其从服务器检索信息出错问题了。
> 看起来像是用户用了阿里云腾讯云这种会被Google识别为中国大陆IP地址的出口导致的此问题，或者客户端没有更新到最新导致的。。

两个手机用同样的服务器但是有不同表现，客户端已经更新到最新了的。

**Comment by zhejiulipu** [comment]
> 这不是软件问题，目前软件已经解决了因为代理规则不完全导致其从服务器检索信息出错问题了。
> 看起来像是用户用了阿里云腾讯云这种会被Google识别为中国大陆IP地址的出口导致的此问题，或者客户端没有更新到最新导致的。。
现在出现了与google服务器通信是出现问题，同样的服务器，华为p10可以上，但note20却不可以，已经是最新客户端。怎么解决？

**Comment by suki-on-git** [comment]
既然用了三星，别告诉我你没安装在KNOX里边..

**Comment by zhejiulipu** [comment]
> 既然用了三星，别告诉我你没安装在KNOX里边..

knox是安全文件夹吗？如果是的话，我安装进去依旧不可以链接google，依旧是通信出现问题
