### ISSUE TITLE
V2rayNG new storage design

### ISSUE THREAD

**Issue by yuhan6665** [2dust/v2rayNG#865]
Over the past year of development, I had some discussion with @2dust. A few shortcomings of the current storage have been identified:

- [DPreference](https://github.com/DozenWang/DPreference) is an obsolete implementation.
- DPreference redirect multi-process access to main process. As a result, it can occupy a lot of redundant memory even when user is not looking at the MainActivity.
- Currently all server list data is stored under one key “ang_config”. This was ok for simple display the list in MainActivity. As the business logic grow, it become very inconvenient for updating single entry, like test results.
- Other useful feature, like sort, grouping, filtering, search is more difficult with current storage.

I plan to use [MMKV](https://github.com/Tencent/MMKV) to replace the DPreference. (AndroidX Datastore was also considered but I don’t believe it support multi-process access) I have done some profiling. MMKV shows good performance with similar memory usage, though it will increase APK size.

Currently v2rayNG has only one sharedPreference xml file. I plan to break it logically into 5 different files. The side benefit is that with true multi-process support from MMKV, it makes the file locking with smaller granularity.

`Key --> value`
1.	Main:
`ang_config --> [Id1, Id2..]` // Id is current guid. Duplicated server config is still allowed, I plan to add a new isSameServer() function to help with identify duplicated servers in the future
`pref_v2ray_config --> Id` //current selected server, plan to get rid of some of the redundant fields, like `pref_v2ray_config_domain`, `pref_v2ray_config_name`

2.	Server: (this is server data usually updated with subscription. Expect few changes)
`Id --> gson.toJson { remarks, configType, configVersion, subId, gson.toJson { V2rayConfig.OutboundBean}, addedTime }` //`addedTime `is a new field used to help sorting in the future
// in case of custom config, the gson.toJson will be full V2rayConfig. Reader will need to check configType before parse the json

3.	Server affiliation info: (this is server related data that potentially change very frequently, currently only testResult, consider to add traffic statistics, server health score in the future)
`Id --> gson.toJson { testResult }`

4.	Subscription:
`SubId --> gson.toJson { remarks, url, enabled, addedTime }`  //`addedTime `is a new field used to sort subscription

5.	Settings:
I plan to keep the default setting shared preference as is, but map the needed key value to MMIKV
pref_mode
pref_per_app_proxy
pref_per_app_proxy_set
pref_bypass_apps
pref_speed_enabled
pref_sniffing_enabled
pref_proxy_sharing_enabled
pref_local_dns_enabled
pref_remote_dns
pref_domestic_dns
pref_local_dns_port
pref_allow_insecure
pref_socks_port
pref_http_port
pref_routing_domain_strategy
pref_routing_mode
pref_v2ray_routing_agent
pref_v2ray_routing_direct
pref_v2ray_routing_blocked
pref_core_loglevel
pref_prefer_ipv6

Some existing keys will not be copied to MMKV:
pref_inapp_buy_is_premium
pref_last_version
pref_routing_custom

**Comment by yuhan6665** [comment]
TODO list:

- ~~add MMKV, trim old arm so lib~~
- ~~add new parser for OutboundBean~~
- ~~add new storage~~
- ~~add new storage for subscription~~
- ~~map settings~~
- ~~add data migration~~
- ~~add google backup for new files~~
- ~~cleanup legacy classes and DPreference~~

Done

**Comment by DonZheng** [comment]
@yuhan6665 Thanks heaps for your upcoming great contributions. Just curious do you have an approx. timeline for these great improvements? Cheers.

**Comment by yuhan6665** [comment]
@DonZheng I will start a new branch and link it here so that all can see the progress.
You can provide valuable suggestion while the draft is not finalised yet.

**Comment by DonZheng** [comment]
Hi @yuhan6665 Thanks for your prompt reply. Just curious here, the V2rayNG App on Google Play store seems to be a few versions advanced than the github repo? With a quick look, didn't see any reference of 'vless' protocol within project. Am I missing anything here? Cheers.

**Comment by yuhan6665** [comment]
yeah, VLESS, trojan, and a couple of new features are not in this repo at the moment

**Comment by DonZheng** [comment]
Is there any roadblocker for updating the repo? Or the app on Google Play is your proprietary app?

**Comment by yuhan6665** [comment]
Implementation in progress: https://github.com/yuhan6665/v2rayNG/commits/new-storage
