### ISSUE TITLE
vless分享链接“sni”段不符合标准。

### ISSUE THREAD

**Issue by Butterflyflower** [2dust/v2rayNG#869]
### 预期行为
TLS SNI正常导入其他客户端，比如ShadowSocksR Plus+。
### 实际行为
由于链接不符合标准导致导入失败，
原文标准如下

4.4 TLS 相关段
4.4.1 sni
TLS SNI，对应配置文件中的 serverName 项目。

**Comment by AkinoKaede** [comment]
补充下，在 v2rayNG 中 serverName 对应的字段为 host，不过根据提案应为 sni
