### ISSUE TITLE
建议修改滑动删除节点，经常会误删除

### ISSUE THREAD

**Issue by wgzeyu** [2dust/v2rayNG#87]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
上下滑动列表
更换节点时触碰配置

### 实际行为
被识别为横向滑动，配置没了

### 复现方法
1.滑动列表
2.点击配置(节点)
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

### 环境信息
Android 8.0.0
Mi 6 MIUI10 8.7.5

### 额外信息（可选）
建议改为像QQ那样滑动后点击删除，不然经常会误删除很麻烦。。
或者增加一个设置项关闭滑动删除配置，反正编辑配置里也能删

**Comment by myjensen1973** [comment]
是有这种问题 望2大下个版本改进一下 还有 分应用代理里面 已勾选的应用可以置顶排序 就是排到最上面去  @2dust
