### ISSUE TITLE
如何编译libv2ray.arr文件？

### ISSUE THREAD

**Issue by fandeus** [2dust/v2rayNG#87]
我安装 go moblie 去运行编译 libvray.go 这个文件提示找不到文件。我翻了作者的代码找到一个文件 makefile 内容如下：
`
pb:
	  go get -u github.com/golang/protobuf/protoc-gen-go
		@echo "pb Start"
asset:
	bash gen_assets.sh download
	mkdir assets
	cp -v data/*.dat assets/
	# cd assets;curl https://raw.githubusercontent.com/2dust/AndroidLibV2rayLite/master/data/geosite.dat > geosite.dat		
	# cd assets;curl https://raw.githubusercontent.com/2dust/AndroidLibV2rayLite/master/data/geoip.dat > geoip.dat

shippedBinary:
	cd shippedBinarys; $(MAKE) shippedBinary

fetchDep:
	-go get  github.com/2dust/AndroidLibV2rayLite
	go get github.com/2dust/AndroidLibV2rayLite

ANDROID_HOME=$(HOME)/android-sdk-linux
export ANDROID_HOME
PATH:=$(PATH):$(GOPATH)/bin
export PATH
downloadGoMobile:
	go get golang.org/x/mobile/cmd/...
	sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
	cd ~ ;curl -L https://raw.githubusercontent.com/2dust/AndroidLibV2rayLite/master/ubuntu-cli-install-android-sdk.sh | sudo bash - > /dev/null
	ls ~
	ls ~/android-sdk-linux/
	gomobile init ;gomobile bind -v  -tags json github.com/2dust/AndroidLibV2rayLite

BuildMobile:
	@echo Stub

all: asset pb shippedBinary fetchDep
	@echo DONE
`
这个这个大概的意思能看懂，但是不知道怎么操作。
如果作者不愿意直接提供 arr 文件，能否将编译过程写的详细些？

**Comment by fandeus** [comment]
这是Go官网的编译方式
[Go 编译 apk](https://github.com/golang/go/wiki/Mobile)
我能编译成Apk，运行在手机上，但是作者这个项目我就无法编译成功。

**Comment by 2dust** [comment]
过程还是很复杂的。下面这里有现成的
https://github.com/2dust/AndroidLibV2rayLite/releases/tag/r73

**Comment by fandeus** [comment]
非常感谢！！
现在项目可以成功运行起来了，不过链接VPN失败。如果链接成功的时候会小钥匙，但是这个代码没有连接上。

**Comment by fandeus** [comment]
可否有偿提供技支持?
developer.fandeus@gmail.com

**Comment by PlexPt** [comment]
https://yuanmomo.net/2019/12/02/v2ray-android-build-aar/
