### ISSUE TITLE
可否做不同节点设置不同的路由规则

### ISSUE THREAD

**Issue by dwj0** [2dust/v2rayNG#873]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

比如，我设置几个节点，其中一个节点用于全局上网，一个节点用于GFW， 还有一个节点只是想连接到家里的路由器做内网穿透
安卓的Shadowsocks能做到这个，但只支持SS

**Comment by yuhan6665** [comment]
Please use custom config for now

**Comment by haomuch** [comment]
需要导入编辑自定义配置

**Comment by dwj0** [comment]
我知道用自定义配置可以做到， 但当我把自定义配置设置为 连接到家里的路由器做内网穿透 后， 如果我要切换为别的路由模式，就要重新设置自定义配置。  
如果可以每个节点设置不同路由模式，就方便了。
