### ISSUE TITLE
NG是否有多路复用的功能

### ISSUE THREAD

**Issue by ChenMoGe2** [2dust/v2rayNG#878]
如题

**Comment by simpleandstupid** [comment]
首先，不建议开启mux。

ng默认关闭mux，如有需要请导入自定义配置

**Comment by ChenMoGe2** [comment]
@guanhemeng 感谢您的回复，我这边有个内部服务使用到v2ray，连接的客户端比较多，每台机器都有很多tcp连接，我怕连接太多会拖垮服务器资源，所以想使用多路复用，每一个用户只使用一个连接
