### ISSUE TITLE
为什么有的节点 V2aryN 能用 V2aryNG用不了

### ISSUE THREAD

**Issue by tislam8888** [2dust/v2rayNG#879]
在PC上面可以用
V2aryNG 上面 真链接 可以看到 正常的延时
但是 就是用不了 没有任何 流量
发现了 好几个这种节点
是V2aryNG 的问题吗

**Comment by l3617** [comment]
> 在PC上面可以用
> V2aryNG上面的真链接可以看到正常的
> 连续但是就是用不了没有任何流量
> 发现了好
> 几个这样的是V2aryNG的问题吗

朋友，你用的V2aryNG的x2ray核心版本，有些协议和服务端为v2ray核心不通用，能连接但是不能上网，我也是遇到过，比如VLESS_XTLS就是

**Comment by tislam8888** [comment]
> > 在PC上面可以用
> > V2aryNG上面的真链接可以看到正常的
> > 连续但是就是用不了没有任何流量
> > 发现了好
> > 几个这样的是V2aryNG的问题吗
> 
> 朋友，你用的V2aryNG的x2ray核心版本，有些协议和服务端为v2ray核心不通用，能连接但是不能上网，我也是遇到过，比如VLESS_XTLS就是
我试过了 电脑 也切换 core 可是 还是能用 ，手机安卓端就是不能用

**Comment by tislam8888** [comment]
上面有人反映说是 因为 核心版本的问题
可是 我试过 同样是 Xray 1.2.4
PC就能用 安卓 的 v2rayNG就是有链接 但是没有流量
用不了 怎么搞的啊

**Comment by Fhokud** [comment]
请贴出你的配置/错误日志以便复现/测试/修复，谢谢。
不然你可以关了，这种Issues毫无意义

**Comment by dozinggiraffe** [comment]
同样的问题我也遇到了。能用电脑端链接，但是无法用安卓的v2rayNG链接用的就是VLESS_XTLS的模式。

**Comment by sdshdv** [comment]
v2ray-core和xray-core的vless_xtls链接不能通用，除非在PC上也把核心更换成xray，两者保持一致

**Comment by st0nnne** [comment]
> > 在PC上面可以用
> > V2aryNG上面的真链接可以看到正常的
> > 连续但是就是用不了没有任何流量
> > 发现了好
> > 几个这样的是V2aryNG的问题吗
> 
> 朋友，你用的V2aryNG的x2ray核心版本，有些协议和服务端为v2ray核心不通用，能连接但是不能上网，我也是遇到过，比如VLESS_XTLS就是

是的没错，V2rayN可以用，V2rayNG不行，后面使用vmess协议就可以了
