### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by AlienEU** [2dust/v2rayNG#882]
I've been using V2RayNG for 2 years without a single problem. Since yesterday, I can't connect anymore. Here is the reason:

Fail to detect internet connection: Context deadline exceeded.

I've updated V2RayNG to v.1.5.13 without result.
Same outcome under 4G or Wi-Fi.

Do you know how to fix that? Thx

**Comment by ywg663** [comment]
今天开始类似问题

**Comment by AlienEU** [comment]
I fixed the problem by assigning a new IP address

**Comment by manyfew** [comment]
> 
> 
> I fixed the problem by assigning a new IP address

I have the same problem. What do you mean 'assigning a new IP address'? Thank you

**Comment by tagoton** [comment]
how to assigned a new IP?

**Comment by mmoradi15** [comment]
Same problem for me on android 10 and v2rayng1.6.8 with server Xray 1.4.2
when testing it says "Fail to detect internet connection: Context deadline exceeded."
in the logcat:
"failed to dial WebSocket"
Also, the same VLESS Configuration works on my PC with v2rayN 4.17 without any problem

**Comment by jxjsky45-wq** [comment]
这个问题有解决方案吗？ 各位大佬

**Comment by zuohl** [comment]
同样有这个问题,android11 1.6.23 使用ws就不正常,另一台机器同样配置Android10 1.2.2正常

**Comment by Bom234** [comment]
So how to fix? context deadline exceeded v2ray

**Comment by mo979** [comment]
The system time of my phone is nine minutes faster than normal. After I adjust time, the app works well.

**Comment by p-CXTN** [comment]
Uninstalling and reinstalling v2rayNG on play store solved the problem for me

**Comment by web-elite** [comment]
i have same problem ...
any idea ?

**Comment by imirsay** [comment]
I change xray version and fix this problem.

**Comment by EvgexaK** [comment]
**Reinstalling the app fixes the issue**, other methods like cleaning app cache doesn't help. Not sure how the issue occurs though.
