### ISSUE TITLE
Cannot Use the app in iran , Broken TLS

### ISSUE THREAD

**Issue by e3lz** [2dust/v2rayNG#884]
Hello i cannot connect to any network with the app , no trojan no v2ray no xray ..
but do not have any problem with the PC Version .

02-12 12:12:00.638 I/com.v2ray.ang(28050): Reinit property: dalvik.vm.checkjni= false
02-12 12:12:00.638 I/com.v2ray.ang(28050): ReInitProperties: persist.vm.debug.dumpapi= false
02-12 12:12:00.643 E/com.v2ray.ang(28050): Not starting debugger since process cannot load the jdwp agent.
02-12 12:12:00.678 I/com.v2ray.ang(28050): QarthPatchMonintor::Init
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::StartWatch
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/com.v2ray.ang
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::Run
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::Reading
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::CheckNotifyEvent
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:00.679 I/com.v2ray.ang(28050): QarthPatchMonintor::CheckNotifyEvent before read
02-12 12:12:00.679 I/com.v2ray.ang(28050): 
02-12 12:12:02.886 I/GoLog   (28051): loading v2ray config
02-12 12:12:02.887 I/GoLog   (28051): Preparing Domain: ns3.eranku.com:443
02-12 12:12:02.893 I/GoLog   (28051): new v2ray core
02-12 12:12:02.895 I/GoLog   (28051): start v2ray core
02-12 12:12:02.897 I/GoLog   (28051): [Warning] v2ray.com/core: V2Ray 4.32.1 started
02-12 12:12:02.944 I/tun2socks(29144): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
02-12 12:12:02.996 I/tun2socks(29144): NOTICE(tun2socks): entering event loop
02-12 12:12:03.077 I/GoLog   (28051): Prepare Result:
02-12 12:12:03.077 I/GoLog   (28051):  Domain: ns3......
02-12 12:12:03.077 I/GoLog   (28051):  Port: 443
02-12 12:12:03.077 I/GoLog   (28051):  IPs: [160.119.69.150]
02-12 12:12:03.316 I/GoLog   (28051): tcp:127.0.0.1:33612 accepted tcp:49.51.20.176:80 [proxy] 
02-12 12:12:03.594 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:03.965 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:04.011 I/GoLog   (28051): tcp:127.0.0.1:33618 accepted tcp:18.195.50.190:5222 [proxy] 
02-12 12:12:04.276 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:05.211 I/GoLog   (28051): tcp:127.0.0.1:33636 accepted tcp:69.171.250.20:443 [proxy] 
02-12 12:12:05.576 I/GoLog   (28051): udp:127.0.0.1:58073 accepted udp:1.1.1.1:53 [proxy] 
02-12 12:12:05.640 I/GoLog   (28051): udp:127.0.0.1:58549 accepted udp:1.1.1.1:53 [proxy] 
02-12 12:12:05.650 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:05.829 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:05.905 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:06.705 I/GoLog   (28051): tcp:127.0.0.1:33646 accepted tcp:149.154.167.92:443 [proxy] 
02-12 12:12:06.972 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:07.102 I/GoLog   (28051): udp:127.0.0.1:56261 accepted udp:1.1.1.1:53 [proxy] 
02-12 12:12:07.136 I/GoLog   (28051): tcp:127.0.0.1:33654 accepted tcp:49.51.20.176:8080 [proxy] 
02-12 12:12:07.302 I/GoLog   (28051): udp:127.0.0.1:44402 accepted udp:1.1.1.1:53 [proxy] 
02-12 12:12:07.365 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:07.418 I/GoLog   (28051): fdConn unix.Connect err, Close Fd: 94 Err: software caused connection abort
02-12 12:12:07.564 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:07.576 I/GoLog   (28051): udp:127.0.0.1:52089 accepted udp:8.8.8.8:53 [proxy] 
02-12 12:12:07.643 I/GoLog   (28051): udp:127.0.0.1:42686 accepted udp:8.8.8.8:53 [proxy] 
02-12 12:12:07.687 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:07.863 I/GoLog   (28051): Using Prepared: 160.119.69.150
02-12 12:12:07.906 I/GoLog   (28051): Using Prepared: 160.119.69.150
==================================
Fail to detect internet connection : context deadline exceeded

**Comment by 2444989513** [comment]
Please update  https://github.com/2dust/v2rayNG/releases/tag/1.5.13

**Comment by e3lz** [comment]
**after update i had another error , it seems that the problem is with iran dns server , Iran government blocked all UDP access to none domestic dns servers and allow only tcp or tls access .** 
this problem was solved by Trojan client ignitor but v2rayNG have it . 
02-13 17:35:54.923 I/GoLog   (23407): [Info] [315368987] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:54.923 I/GoLog   (23407): [Info] [315368987] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:55.009 I/GoLog   (23407): [Info] [971494424] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:55.010 I/GoLog   (23407): [Info] [971494424] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:55.011 I/GoLog   (23407): [Info] [1693416557] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:55.011 I/GoLog   (23407): [Info] [1693416557] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:55.011 I/GoLog   (23407): [Info] [82674540] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:55.011 I/GoLog   (23407): [Info] [82674540] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:55.089 I/GoLog   (23407): [Info] [71833292] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:55.089 I/GoLog   (23407): [Info] [71833292] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:55.248 I/GoLog   (23407): [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context deadline exceeded
02-13 17:35:56.467 I/GoLog   (23407): [Debug] [886323439] proxy/socks: send packet to udp:8.8.8.8:53 with 32 bytes
02-13 17:35:56.467 I/GoLog   (23407): [Debug] [886323439] transport/internet/udp: dispatch request to: udp:8.8.8.8:53
02-13 17:35:56.928 I/GoLog   (23407): [Info] [1798226524] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:56.928 I/GoLog   (23407): [Info] [1798226524] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:57.012 I/GoLog   (23407): [Info] [255147762] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:57.012 I/GoLog   (23407): [Info] [255147762] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:57.013 I/GoLog   (23407): [Info] [590288434] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:57.013 I/GoLog   (23407): [Info] [590288434] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:57.014 I/GoLog   (23407): [Info] [3397834783] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:57.014 I/GoLog   (23407): [Info] [3397834783] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:57.092 I/GoLog   (23407): [Info] [2546764392] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:57.092 I/GoLog   (23407): [Info] [2546764392] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
02-13 17:35:58.128 I/GoLog   (23407): [Info] [3817909323] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: connection ends > context canceled
02-13 17:35:58.128 I/GoLog   (23407): [Info] [3817909323] transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe

**Comment by paulgrammer** [comment]
i'm new to git, I have tried cloning https://github.com/2dust/v2rayNG/releases/tag/1.5.13 but all i get is the old repo of the project. how can I clone the latest repo.
