### ISSUE TITLE
Please add a clear list button 

### ISSUE THREAD

**Issue by CoresenYan** [2dust/v2rayNG#885]
please add a clear server list button, one by one to handle delete item from list is look like stupid, 😄

**Comment by Acytoo** [comment]
有时候我也觉得一个一个删除很麻烦，但是添加多余的代码可能会导致app代码增加，更多bug，实用性却不大。如果你的配置是订阅添加的，删除订阅后更新订阅，那些配置就没有了。或者，你可以先备份需要的配置，然后清空应用数据再导入。

--------------------------------------

Sometimes I find that deleting configurations one by one is tiring, too. But adding more unnecessary methods can make apps fragile. If your "items" are added by subscriptions, delete subscription and update subcription. Also, you can backup items you want, and clear app storage, and then import the wanted configutations.

**Comment by CoresenYan** [comment]
but when i update subscriptions whatever I enabled one of subscription and disabled others. the others server never clear from list.

**Comment by Acytoo** [comment]
I don't know what you mean by "disable other subscriptions". I can't find a disable button, I deleted subscription links in the subscription setting and the configurations fetched by subscription did disapear. I am using 1.4.13 version downloaded from Google Play.

**Comment by yuhan6665** [comment]
> but when i update subscriptions whatever I enabled one of subscription and disabled others. the others server never clear from list.

seems a legit issue. Will plan to fix..
