### ISSUE TITLE
导入某些vmess失败

### ISSUE THREAD

**Issue by ChuJian2** [2dust/v2rayNG#886]
导入某些vmess失败，如下列链接。
vmess://eyJ2IjoiMiIsInBzIjoidGVzdCIsImFkZCI6InRlc3QuY29tIiwicG9ydCI6MTAwNTMsImlkIjoiZjc2ZTk4ZTktNjQ1OC00NjRjLThjN2EtOWU5NTQxYzMzNDU0IiwiYWlkIjoxNiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsImhvc3QiOm51bGwsInBhdGgiOiJcL2xyajFnajNxbG1kcWRqbWkiLCJ0bHMiOiIifQ==

### 日志信息
<details>

--------- beginning of main
02-13 10:06:51.123 W/System.err(10464): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <set-?>
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.dto.AngConfig$VmessBean.setRequestHost(AngConfig.kt)
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.util.AngConfigManager.importConfig(AngConfigManager.kt:314)
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.util.AngConfigManager.importBatchConfig(AngConfigManager.kt:883)
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:391)
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:390)
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:382)
02-13 10:06:51.123 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:222)
02-13 10:06:51.123 W/System.err(10464): at android.app.Activity.onMenuItemSelected(Activity.java:3256)
02-13 10:06:51.123 W/System.err(10464): at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
02-13 10:06:51.123 W/System.err(10464): at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
02-13 10:06:51.123 W/System.err(10464): at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-13 10:06:51.123 W/System.err(10464): at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
02-13 10:06:51.123 W/System.err(10464): at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
02-13 10:06:51.124 W/System.err(10464): at android.widget.AbsListView$3.run(AbsListView.java:4043)
02-13 10:06:51.124 W/System.err(10464): at android.os.Handler.handleCallback(Handler.java:751)
02-13 10:06:51.124 W/System.err(10464): at android.os.Handler.dispatchMessage(Handler.java:95)
02-13 10:06:51.124 W/System.err(10464): at android.os.Looper.loop(Looper.java:154)
02-13 10:06:51.124 W/System.err(10464): at android.app.ActivityThread.main(ActivityThread.java:6227)
02-13 10:06:51.124 W/System.err(10464): at java.lang.reflect.Method.invoke(Native Method)
02-13 10:06:51.124 W/System.err(10464): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
02-13 10:06:51.124 W/System.err(10464): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
02-13 10:06:51.124 W/System.err(10464): java.lang.IllegalArgumentException: bad base-64
02-13 10:06:51.127 W/System.err(10464): at android.util.Base64.decode(Base64.java:161)
02-13 10:06:51.127 W/System.err(10464): at android.util.Base64.decode(Base64.java:136)
02-13 10:06:51.127 W/System.err(10464): at android.util.Base64.decode(Base64.java:118)
02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.util.Utils.decode(Utils.kt:98)
02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig(MainActivity.kt:393)
02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importBatchConfig$default(MainActivity.kt:390)
02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.importClipboard(MainActivity.kt:382)
02-13 10:06:51.127 W/System.err(10464): at com.v2ray.ang.ui.MainActivity.onOptionsItemSelected(MainActivity.kt:222)
02-13 10:06:51.127 W/System.err(10464): at android.app.Activity.onMenuItemSelected(Activity.java:3256)
02-13 10:06:51.127 W/System.err(10464): at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
02-13 10:06:51.127 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
02-13 10:06:51.128 W/System.err(10464): at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
02-13 10:06:51.128 W/System.err(10464): at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-13 10:06:51.128 W/System.err(10464): at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
02-13 10:06:51.128 W/System.err(10464): at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
02-13 10:06:51.128 W/System.err(10464): at android.widget.AbsListView$3.run(AbsListView.java:4043)
02-13 10:06:51.128 W/System.err(10464): at android.os.Handler.handleCallback(Handler.java:751)
02-13 10:06:51.128 W/System.err(10464): at android.os.Handler.dispatchMessage(Handler.java:95)
02-13 10:06:51.128 W/System.err(10464): at android.os.Looper.loop(Looper.java:154)
02-13 10:06:51.128 W/System.err(10464): at android.app.ActivityThread.main(ActivityThread.java:6227)
02-13 10:06:51.128 W/System.err(10464): at java.lang.reflect.Method.invoke(Native Method)
02-13 10:06:51.128 W/System.err(10464): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
02-13 10:06:51.128 W/System.err(10464): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
</details>

**Comment by niwoa11** [comment]
好兄弟，你有没有配置vpn的，我这个过期了作者不愿意做了，我可以出钱的

**Comment by ChuJian2** [comment]
什么意思，请详细说明？

**Comment by niwoa11** [comment]
就是我之前和一位作者买的一年vpn，但是今年到期了，就用不了，而且他也不继续做了，所以我现在没法用vpn了，就想问你一下可以在你这里买一个vpn吗

**Comment by ChuJian2** [comment]
可以，請添加qq:3468381517




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2dust/v2rayNG"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月15日(星期一) 晚上8:47
收件人:&nbsp;"2dust/v2rayNG"<v2rayNG@noreply.github.com&gt;;
抄送:&nbsp;"初见"<2474681296@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [2dust/v2rayNG] 导入某些vmess失败 (#886)





 
就是我之前和一位作者买的一年vpn，但是今年到期了，就用不了，而且他也不继续做了，所以我现在没法用vpn了，就想问你一下可以在你这里买一个vpn吗

**Comment by yuhan6665** [comment]
Please try latest version
