### ISSUE TITLE
希望默认关闭各个节点的流量统计

### ISSUE THREAD

**Issue by Fhokud** [2dust/v2rayNG#888]
v2ray 的流量统计功能会使 ReadV 和 WriteV 失效
也许可以在默认节点配置中删除以下字段
①
    "system": {
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
②
  "stats": {}

**Comment by niwoa11** [comment]
好兄弟，你有没有配置vpn的，我这个过期了作者不愿意做了，我可以出钱的

**Comment by Fhokud** [comment]
> 好兄弟，你有没有配置vpn的，我这个过期了作者不愿意做了，我可以出钱的

留下邮箱

**Comment by yuhan6665** [comment]
Planning to fix..
