### ISSUE TITLE
快捷开关无法真正启动代理服务

### ISSUE THREAD

**Issue by orgsss** [2dust/v2rayNG#89]
预期行为
使用快捷开关可以一键启动代理并正常上网

实际行为
点击快捷开关启动v2rayNG后显示已连接VPN，但是此时无法访问任何网站，需要手动点开v2rayNG APP后才可以访问网络
与代理方式无关，无论代理方式是否绕过大陆，在不打开v2rayNG APP的前提下都无法访问国内外任何网站
 复现方法
1.用一台Android 7.0手机，添加v2rayNG快捷开关
2.选择好一条可以用的线路，退出v2rayNG
3.通过快捷开关打开代理，会发现虽然显示已连接但是v2rayNG不在后台常驻的情况下完全无法访问网络

日志信息
没有有用信息，使用开关后确实有连接记录，打开v2rayNG前后日志无明显变化

 环境信息
Android 7.0，nubia UI 5.0（控制中心支持添加快捷开关）
v2rayNG最新版本
谷歌服务可用，线路可用，国内网络且可用。

**Comment by kirbyzhu** [comment]
同样问题，且在界面往往也无法正常启动服务。需要关机重启或者先启动其他VPN后切换为NG。

**Comment by Chinternet** [comment]
ng做得挺烂的，换bifrostv吧

**Comment by kirbyzhu** [comment]
ng在连接成功后的稳定性上是超过bi的，而且在能耗上优于bi。我购买了bi的脱广告版，但是还是常用ng。

**Comment by yflwz** [comment]
这个开机自动连接的功能是很实用的，并不单单是说用上电视上，手机上其实也是，很期待。

**Comment by yflwz** [comment]
bifrostv好像不支持电视的安卓4.3等低版本。

**Comment by mela93** [comment]
你好请问是在哪里添加快捷开关的？
我的系统是Android Pie，但是并没有找到快捷开关这个微件(widget)。。。
