### ISSUE TITLE
“开启流量探测选项”在v2rayNG和v2rayN的区别

### ISSUE THREAD

**Issue by GeorgeRudd** [2dust/v2rayNG#893]
在电脑上用v2rayN，“开启流量探测“选项不打勾，流量可以正常分流，具体表现为在百度搜索"ip"结果在国内。
在手机上用v2rayNG，“开启流量探测”选项不打勾，流量却不可以正常分流，具体表现为在百度搜索"ip"结果在香港。
两个软件使用的节点一样，配置一样，在两个软件各自的"路由设置"-”直连的domain或ip"里都填的是geosite:cn,geoip:private,
geoip:cn 这三个。同时，”代理的domain或ip"均留空不填。v2rayN中dns设置留空，v2rayNG中也不启用本地dns。v2rayNG"预定规则"选择"绕过大陆和局域网".
v2rayNG的geo资源文件也是最新的。
请问为什么会这样？

**Comment by GeorgeRudd** [comment]
v2rayNG勾选“开启流量探测选项”后 可以正常分流 我的疑问是 为什么电脑上不用勾选就可以正常分流 而手机上却必须勾选才能正常

**Comment by yuhan6665** [comment]
Android and Windows use different mechanism. On Android VPN service move almost all traffic to core. That's why it works for third party apps. It is similar to SSTap, Netch on Windows.
https://github.com/2dust/v2rayNG/wiki/Mode
