### ISSUE TITLE
无法访问百度

### ISSUE THREAD

**Issue by Clouxin** [2dust/v2rayNG#897]
![Screenshot_2021-02-19-16-39-37-901_mark via gp](https://user-images.githubusercontent.com/32696551/108481660-6dc19080-72d3-11eb-82fb-e0d59195033f.jpg)
其他基本能打开，设置就绕过局域及大陆。但百度以及贴吧一直无法访问，关闭vpn后就能访问。

**Comment by chunqiaow** [comment]
怎么设置啊

**Comment by chunqiaow** [comment]
怎么设置啊，这个官网上不了
