### ISSUE TITLE
希望增加http+tls代理的支持来连接naiveproxy

### ISSUE THREAD

**Issue by liurushi1** [2dust/v2rayNG#899]
rt  手机上暂时没naiveproxy客户端，希望能兼容一下

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by ghost** [comment]
👀
