### ISSUE TITLE
Google Play Store的下载链接失效

### ISSUE THREAD

**Issue by xujohnny** [2dust/v2rayNG#90]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
点进Google Play Store应该能下载啊。

### 实际行为
"抱歉，在此服务器上找不到所请求的网址。"

### 复现方法
1. https://play.google.com/store/apps/details?id=com.v2ray.ang
2.
3.

### 日志信息
<details>

通过 `adb logcat com.v2ray.ang` 获取日志。请自行删减日志中可能出现的敏感信息。
```
在这里粘贴日志
```
</details>

**Comment by asen1987** [comment]
商店里都搜不到了……

**Comment by xujohnny** [comment]
已经解决了，收到新的更新了，感谢！
