### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Magichuanjun** [2dust/v2rayNG#903]
每个节点都用不了。朋友借了一个他在用的我也用不了[https://imgchr.com/i/yTg9RP](这是照片
![Uploading Screenshot_20210221_223748_com.v2ray.ang.jpg…]

**Comment by zaning95** [comment]
我也是。。。但ss客户端就好好的

**Comment by Magichuanjun** [comment]
手机型号华为畅享20
