### ISSUE TITLE
建议去除xtls-rprx-splice之外其他所有xtls流控模式

### ISSUE THREAD

**Issue by haomuch** [2dust/v2rayNG#906]
因为origin模式太慢根本没有实用意义，direct无法发挥Android最大潜力，udp443的QUIC流量无法套xtls，放行之后反而性能降低！

**Comment by Fhokud** [comment]
这不现实

**Comment by Fhokud** [comment]
那你如何获取订阅，direct是全平台通用的，也是机场下发订阅首选的flow。

**Comment by Fhokud** [comment]
https://github.com/2dust/v2rayNG/issues/876#issue-803108426

**Comment by haomuch** [comment]
> 那你如何获取订阅，direct是全平台通用的，也是机场下发订阅首选的flow。

可以再ng上把direct订阅链接自动改成splice

**Comment by Fhokud** [comment]
这个可以有


> 可以再ng上把direct订阅链接自动改成splice

**Comment by Kam323** [comment]
老兄，我v2rayNG从Google play下载的，没有splice流控选项，你的有吗？
