### ISSUE TITLE
SOCKS代理无法使用

### ISSUE THREAD

**Issue by AlienwareHe** [2dust/v2rayNG#91]
@2dust 作者你好～再次叨扰一下～在使用中遇到了一些问题：
在手动配置了socks代理之后，vpn启动成功，但无法上网，包括国内的域名例如百度、美团。更换了几个PC端浏览器正常代理的socks资源后均无法成功，且点击连接测试时也正常返回延迟毫秒数～
代理配置：
`{
      "dns": {
        "servers": [
          "1.1.1.1"
        ]
      },
      "inbounds": [
        {
          "port": 10808,
          "protocol": "socks",
          "settings": {
            "auth": "noauth",
            "udp": true,
            "userLevel": 8
          },
          "sniffing": {
            "destOverride": [
              "http",
              "tls"
            ],
            "enabled": true
          },
          "tag": "socks"
        },
        {
          "port": 10809,
          "protocol": "http",
          "settings": {
            "userLevel": 8
          },
          "tag": "http"
        }
      ],
      "log": {
        "loglevel": "warning"
      },
      "outbounds": [
        {
          "mux": {
            "enabled": false
          },
          "protocol": "socks",
          "settings": {
            "servers": [
              {
                "address": "proxy.xxx.xxx.com",
                "level": 8,
                "method": "chacha20",
                "ota": false,
                "password": "123456",
                "port": 10080
              }
            ]
          },
          "streamSettings": {
            "network": "tcp"
          },
          "tag": "proxy"
        },
        {
          "protocol": "freedom",
          "settings": {},
          "tag": "direct"
        },
        {
          "protocol": "blackhole",
          "settings": {
            "response": {
              "type": "http"
            }
          },
          "tag": "block"
        }
      ],
      "policy": {
        "levels": {
          "8": {
            "connIdle": 300,
            "downlinkOnly": 1,
            "handshake": 4,
            "uplinkOnly": 1
          }
        },
        "system": {
          "statsInboundUplink": true,
          "statsInboundDownlink": true
        }
      },
      "routing": {
        "domainStrategy": "AsIs",
        "rules": []
      },
      "stats": {}
    }`

截取的部分错误日志：
`09-03 00:01:54.380 11633 12066 I GoLog   : Preparing Domain: 43.224.8.116:6667
09-03 00:01:54.381 11633 12066 I GoLog   : Prepare Result:
09-03 00:01:54.381 11633 12066 I GoLog   :  Domain: 43.224.8.116
09-03 00:01:54.381 11633 12066 I GoLog   :  Port: 6667
09-03 00:01:54.381 11633 12066 I GoLog   :  IPs: [43.224.8.116]
09-03 00:01:54.381 11633 11633 I GoLog   : file exists
09-03 00:01:54.381 11633 11633 I GoLog   : EnableLocalDNS: false
09-03 00:01:54.381 11633 11633 I GoLog   : ForwardIpv6: false
09-03 00:01:54.381 11633 11633 I GoLog   : DomainName: 43.224.8.116:6667
09-03 00:01:54.381 11633 11633 I GoLog   : loading v2ray config
09-03 00:01:54.382 11633 12066 I GoLog   : /data/user/0/com.v2ray.ang/tun2socks [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.252 --socks-server-addr 127.0.0.1:10808 --tunmtu 1500 --loglevel notice --enable-udprelay --sock-path /data/user/0/com.v2ray.ang/sock_path]
09-03 00:01:54.383 11633 11633 I GoLog   : new v2ray core
09-03 00:01:54.383 11633 11633 I GoLog   : start v2ray core
09-03 00:01:54.386 11633 11989 I GoLog   : [Warning] v2ray.com/core: V2Ray 4.20.0 started
09-03 00:01:54.452 11633 12066 I GoLog   : EscortRun Waiting....
09-03 00:01:54.546 11633 12060 I GoLog   : udp:127.0.0.1:44449 accepted udp:1.1.1.1:53 
09-03 00:01:54.550 11633 12051 I GoLog   : tcp:127.0.0.1:47516 accepted tcp:111.13.141.211:443 
09-03 00:01:54.633 11633 12060 I GoLog   : udp:127.0.0.1:40540 accepted udp:1.1.1.1:53 
09-03 00:01:56.091 11633 11960 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:01:57.619 11633 11960 I GoLog   : udp:127.0.0.1:37226 accepted udp:1.1.1.1:53 
09-03 00:01:58.138 11633 12051 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:01:58.814 11633 11960 I GoLog   : Not Using Prepared: udp,43.224.8.116:33541
09-03 00:01:59.558 11633 12016 I GoLog   : udp:127.0.0.1:44368 accepted udp:114.114.114.114:53 
09-03 00:01:59.644 11633 12051 I GoLog   : udp:127.0.0.1:44936 accepted udp:114.114.114.114:53 
09-03 00:02:01.109 11633 12049 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:02.145 11633 12020 I GoLog   : [Warning] [2072642128] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > read tcp 192.168.50.247:39480->43.224.8.116:6667: i/o timeout
09-03 00:02:02.632 11633 12020 I GoLog   : udp:127.0.0.1:38368 accepted udp:114.114.114.114:53 
09-03 00:02:02.949 11633 12060 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:04.563 11633 11960 I GoLog   : udp:127.0.0.1:44449 accepted udp:1.1.1.1:53 
09-03 00:02:04.646 11633 11960 I GoLog   : Not Using Prepared: udp,43.224.8.116:58181
09-03 00:02:04.648 11633 12060 I GoLog   : udp:127.0.0.1:40540 accepted udp:1.1.1.1:53 
09-03 00:02:05.104 11633 11969 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:05.111 11633 12060 I GoLog   : [Warning] [29255738] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > read tcp 192.168.50.247:39482->43.224.8.116:6667: i/o timeout
09-03 00:02:06.022 11633 12020 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:06.047 11633 12049 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:07.287 11633 12060 I GoLog   : Not Using Prepared: udp,43.224.8.116:49787
09-03 00:02:07.639 11633 12087 I GoLog   : udp:127.0.0.1:37226 accepted udp:1.1.1.1:53 
09-03 00:02:08.006 11633 11969 I GoLog   : tcp:127.0.0.1:47542 accepted tcp:47.88.232.213:80 
09-03 00:02:08.006 11633 11969 I GoLog   : tcp:127.0.0.1:47544 accepted tcp:47.88.232.213:443 
09-03 00:02:08.379 11633 12087 I GoLog   : Not Using Prepared: udp,43.224.8.116:60879
09-03 00:02:09.022 11633 12020 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:09.111 11633 12058 I GoLog   : [Warning] [2072642128] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > read tcp 192.168.50.247:39492->43.224.8.116:6667: i/o timeout
09-03 00:02:09.654 11633 12058 I GoLog   : udp:127.0.0.1:44936 accepted udp:114.114.114.114:53 
09-03 00:02:12.646 11633 12036 I GoLog   : udp:127.0.0.1:38368 accepted udp:114.114.114.114:53 
09-03 00:02:13.010 11633 11989 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:13.024 11633 12036 I GoLog   : [Warning] [29255738] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > read tcp 192.168.50.247:39494->43.224.8.116:6667: i/o timeout
09-03 00:02:14.625 11633 12049 I GoLog   : Not Using Prepared: udp,43.224.8.116:58120
09-03 00:02:14.654 11633 12049 I GoLog   : udp:127.0.0.1:45728 accepted udp:1.1.1.1:53 
09-03 00:02:15.352 11633 12049 I GoLog   : tcp:127.0.0.1:47558 accepted tcp:161.117.68.101:80 
09-03 00:02:16.162 11633 11989 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:16.356 11633 12051 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:18.000 11633 12087 I GoLog   : Not Using Prepared: udp,43.224.8.116:49713
09-03 00:02:18.163 11633 12020 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:19.666 11633 12087 I GoLog   : udp:127.0.0.1:45312 accepted udp:114.114.114.114:53 
09-03 00:02:19.769 11633 12020 I GoLog   : udp:127.0.0.1:42349 accepted udp:1.1.1.1:53 
09-03 00:02:20.155 11633 12049 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:20.156 11633 11989 I GoLog   : Not Using Prepared: udp,43.224.8.116:49160
09-03 00:02:21.158 11633 12058 I GoLog   : Using Prepared: 43.224.8.116
09-03 00:02:22.174 11633 12020 I GoLog   : [Warning] [3856688621] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > read tcp 192.168.50.247:39508->43.224.8.116:6667: i/o timeout`

**Comment by 2dust** [comment]
Solve it yourself

**Comment by AlienwareHe** [comment]
嗯嗯好的，但是想请教一下v2rayNG的inbounds设置在安卓上会生效吗

**Comment by 2dust** [comment]
会生效,ng没有修改core

**Comment by AlienwareHe** [comment]
@2dust 还是没有找到原因😂，请问一下，相同的socks代理在PC火狐上可以使用，在手机上无法使用，是因为socks服务端对UDP的转发不支持吗还是配置文件需要更改

**Comment by AlienwareHe** [comment]
@2dust 我在看GoLog时发现有很多53端口的UDP请求，而且socks代理服务端未实现udp转发，因此怀疑是DNS域名解析全是基于服务端来完成，因此域名无法解析成功，导致代理失败。但我在更改为本地DNS解析后，依然无法访问～ 请问我有什么办法可以修改libv2ray包里的代码增加日志等来debug吗

**Comment by AlienwareHe** [comment]
@2dust 还有一个疑惑以及一个代码中的问题～
1. 在NG中VpnService会将所有tun网卡的流量都从哪个inbound进入，如socks、dns-in等，这部分流量的分发控制逻辑是在哪处理的？tun2socks时会将所有的tcp/udp流量都导入socks inBound中吗，那么dns查询的udp流量如何区分～

2. 使用本地DNS时代码中生成v2ray路由规则时似乎存在优先级的顺序问题
`v2rayConfig.routing.rules.add(0, V2rayConfig.RoutingBean.RulesBean(
                    type = "field",
                    outboundTag = AppConfig.TAG_DIRECT,
                    port = "53",
                    ip = remoteDns,
                    domain = null)
            )

            v2rayConfig.routing.rules.add(0, V2rayConfig.RoutingBean.RulesBean(
                    type = "field",
                    outboundTag = AppConfig.AGENT,
                    port = "53",
                    ip = domesticDns,
                    domain = null)
            )`
这将会导致发起DNS查询时流量会优先从PROXY OutBounds中走出，即仍然通过代理服务器去查询DNS。

**Comment by AlienwareHe** [comment]
@2dust 还有一个疑惑以及一个代码中的问题～

在NG中VpnService会将所有tun网卡的流量都从哪个inbound进入，如socks、dns-in等，这部分流量的分发控制逻辑是在哪处理的？tun2socks时会将所有的tcp/udp流量都导入socks inBound中吗，那么dns查询的udp流量如何区分～

**Comment by AlienwareHe** [comment]
@2dust 你好～还有一个疑惑，烦请作者可以帮忙解惑：

在NG中VpnService会将所有tun网卡的流量都从哪个inbound进入，如socks、dns-in等，这部分流量的分发控制逻辑是在哪处理的？tun2socks时会将所有的tcp/udp流量都导入socks inBound中吗，那么dns查询的udp流量如何区分～

**Comment by AlienwareHe** [comment]
@2dust 忘记回复了，SOCKS代理无法上网问题已经解决～
原因：
1. socks代理服务器不支持UDP转发，手机的DNS解析是基于UDP的，所以无法正常完成DNS解析导致无法上网。
2. V2RAYNG默认DNS Server为1.1.1.1，并且会路由至PROXY的outbounds。
解决：
1. 开启本地DNS设为114.114.114.114，并将远程DNS设为114.114.114.114，具体实际情况可分析V2RAY生成的配置来调整。
原理：
V2RAY-CORE的本地DNS和Route路由策略，可参考官网文档。

**Comment by yihongyuelan** [comment]
> @2dust 忘记回复了，SOCKS代理无法上网问题已经解决～
> 原因：
> 
> 1. socks代理服务器不支持UDP转发，手机的DNS解析是基于UDP的，所以无法正常完成DNS解析导致无法上网。
> 2. V2RAYNG默认DNS Server为1.1.1.1，并且会路由至PROXY的outbounds。
>    解决：
> 3. 开启本地DNS设为114.114.114.114，并将远程DNS设为114.114.114.114，具体实际情况可分析V2RAY生成的配置来调整。
>    原理：
>    V2RAY-CORE的本地DNS和Route路由策略，可参考官网文档。

新版本只需要把“启用本地DNS“勾上即可

**Comment by yingshaoxo** [comment]
> @2dust 忘记回复了，SOCKS代理无法上网问题已经解决～
> 原因：
> 
> 1. socks代理服务器不支持UDP转发，手机的DNS解析是基于UDP的，所以无法正常完成DNS解析导致无法上网。
> 2. V2RAYNG默认DNS Server为1.1.1.1，并且会路由至PROXY的outbounds。
>    解决：
> 3. 开启本地DNS设为114.114.114.114，并将远程DNS设为114.114.114.114，具体实际情况可分析V2RAY生成的配置来调整。
>    原理：
>    V2RAY-CORE的本地DNS和Route路由策略，可参考官网文档。

To be specific, in Android:

At server device: enable local DNS

At client device: enable local DNS

> Now you can use a phone as a socks server, then connect that server with another phone

**Comment by stream1990** [comment]
> > @2dust 忘记回复了，SOCKS代理无法上网问题已经解决～
> > 原因：
> > 
> > 1. socks代理服务器不支持UDP转发，手机的DNS解析是基于UDP的，所以无法正常完成DNS解析导致无法上网。
> > 2. V2RAYNG默认DNS Server为1.1.1.1，并且会路由至PROXY的outbounds。
> >    解决：
> > 3. 开启本地DNS设为114.114.114.114，并将远程DNS设为114.114.114.114，具体实际情况可分析V2RAY生成的配置来调整。
> >    原理：
> >    V2RAY-CORE的本地DNS和Route路由策略，可参考官网文档。
> 
> 新版本只需要把“启用本地DNS“勾上即可

测试不行呢

**Comment by nidemei** [comment]
@stream1990 请问你解决了这个问题没有，我测试也不可以

**Comment by davidblus** [comment]
@stream1990 @nidemei 我用1.8.5版本，打开“启用本地DNS”，打开“启用虚拟DNS”，然后，就可以了。

**Comment by ribychen** [comment]
> @stream1990 @nidemei 我用1.8.5版本，打开“启用本地DNS”，打开“启用虚拟DNS”，然后，就可以了。

可以是可以，可是访问速度是PC sk5代理的20%左右，非常满。无法用
