### ISSUE TITLE
X86 Android 4.4平板 日志no such file or directory

### ISSUE THREAD

**Issue by sharwinmail** [2dust/v2rayNG#91]
在我的手机上正常使用的配置，我的x86 Android 平板,安装的x86最新版本,分享配置过去后
点了连接，有提示要建立vpn，也显示连接时间，但不能正常使用，日志上有tun2socks显示
没有此文件，但我查看了平板，上边是有tun2socks这个文件的,用模拟终端进入路径
执行./tun2socks 依然提示无些文件或目录.

--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
07-17 07:51:07.479 I/GoLog   (14595): NoAutoConvert:true VpnConf:<Service:<Target:"/data/data/com.v2ray.ang/tun2socks" Args:"--netif-ipaddr" Args:"26.26.26.2" Args:"--netif-netmask" Args:"255.255.255.0" Args:"--socks-server-addr" Args:"127.0.0.1:10808" Args:"--tunfd" Args:"3" Args:"--tunmtu" Args:"1500" Args:"--sock-path" Args:"/dev/null" Args:"--loglevel" Args:"4" Args:"--enable-udprelay" VPNSetupArg:"m,1500 a,26.26.26.1,24 r,0.0.0.0,0" > PreparedDomainName:<TCPVersion:"tcp4" UDPVersion:"udp4" DomainNameList:"XXXX:443" > > RootModeConf:<Scripts:<UpScript:"#none" DownScript:"#none" > > Env:<Vars:<key:"V2RaySocksPort" value:"10808" > > 
07-17 07:51:07.479 I/GoLog   (14595): [pdnsd-te.conf]<nil>
07-17 07:51:07.539 I/GoLog   (14595): Preparing DNS, XXXX:443
07-17 07:51:07.539 I/GoLog   (14595): unforgivenessCloser() <-v.unforgivnesschan
07-17 07:51:07.539 I/GoLog   (14595): <nil>2018/07/16 23:51:07 [Warning] Core: V2Ray 3.27 started
07-17 07:51:08.149 I/GoLog   (14595): (*net.UDPAddr)(0xXXXX)(XXXX:443)
07-17 07:51:08.239 I/GoLog   (14595): unforgivenessCloser() <-v.unforgivnesschan
07-17 07:51:08.249 I/GoLog   (14595): /data/data/com.v2ray.ang/tun2socks
07-17 07:51:08.259 I/GoLog   (14595): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
07-17 07:51:08.259 I/GoLog   (14595): fork/exec /data/data/com.v2ray.ang/tun2socks: no such file or directory
07-17 07:51:08.259 I/GoLog   (14595): Waiting....
07-17 07:51:08.259 I/GoLog   (14595): Exit
07-17 07:51:08.259 I/GoLog   (14595): exec: not started
07-17 07:51:08.259 I/GoLog   (14595): Unexpected Exit
07-17 07:51:08.269 I/GoLog   (14595): /data/data/com.v2ray.ang/tun2socks
07-17 07:51:08.269 I/GoLog   (14595): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
07-17 07:51:08.269 I/GoLog   (14595): fork/exec /data/data/com.v2ray.ang/tun2socks: no such file or directory
07-17 07:51:08.269 I/GoLog   (14595): Waiting....
07-17 07:51:08.269 I/GoLog   (14595): Exit
07-17 07:51:08.269 I/GoLog   (14595): exec: not started
07-17 07:51:08.269 I/GoLog   (14595): Unexpected Exit
07-17 07:51:08.289 I/GoLog   (14595): /data/data/com.v2ray.ang/tun2socks
07-17 07:51:08.299 I/GoLog   (14595): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
07-17 07:51:08.299 I/GoLog   (14595): fork/exec /data/data/com.v2ray.ang/tun2socks: no such file or directory
07-17 07:51:08.299 I/GoLog   (14595): Waiting....
07-17 07:51:08.299 I/GoLog   (14595): Exit
07-17 07:51:08.299 I/GoLog   (14595): exec: not started
07-17 07:51:08.299 I/GoLog   (14595): Unexpected Exit
07-17 07:51:08.309 I/GoLog   (14595): /data/data/com.v2ray.ang/tun2socks
07-17 07:51:08.309 I/GoLog   (14595): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
07-17 07:51:08.309 I/GoLog   (14595): fork/exec /data/data/com.v2ray.ang/tun2socks: no such file or directory
07-17 07:51:08.309 I/GoLog   (14595): Waiting....
07-17 07:51:08.309 I/GoLog   (14595): Exit
07-17 07:51:08.309 I/GoLog   (14595): exec: not started
07-17 07:51:08.309 I/GoLog   (14595): Unexpected Exit
07-17 07:51:08.329 I/GoLog   (14595): /data/data/com.v2ray.ang/tun2socks
07-17 07:51:08.329 I/GoLog   (14595): [--netif-ipaddr 26.26.26.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:10808 --tunfd 3 --tunmtu 1500 --sock-path /dev/null --loglevel 4 --enable-udprelay]
07-17 07:51:08.329 I/GoLog   (14595): fork/exec /data/data/com.v2ray.ang/tun2socks: no such file or directory
07-17 07:51:08.329 I/GoLog   (14595): Waiting....
07-17 07:51:08.329 I/GoLog   (14595): Exit
07-17 07:51:08.329 I/GoLog   (14595): exec: not started
07-17 07:51:08.329 I/GoLog   (14595): Unexpected Exit

**Comment by chestermax01** [comment]
额，我X86 5.01和你一样

**Comment by chestermax01** [comment]
能连上服务器，但用不了代理网络

**Comment by fei5seven** [comment]
是这样的，x86都是这个报错，目前试了一下BifrostV是没问题的，希望修复一下

**Comment by mokhtarabadi** [comment]
I have same problem

**Comment by chestermax01** [comment]
> 是这样的，x86都是这个报错，目前试了一下BifrostV是没问题的，希望修复一下

一样

**Comment by 2dust** [comment]
https://github.com/2dust/v2rayNG/releases/tag/0.6.1-beta5
