### ISSUE TITLE
1.3.3更新到1.4.13和1.5.15两个版本后出了问题

### ISSUE THREAD

**Issue by 88866888** [2dust/v2rayNG#910]
在用v2rayNG 1.3.3版本没有任何问题可以VPN，测试网速也是正常的。但更新到1.4.13后发现无法连接vpn网络，测试网速提示“失败：io.read/write on closed pipe"错误。升级到1.5.15版本后也是一样的错误。

我的手机为小米8青春和小米8旗舰

**Comment by skytimus** [comment]
> 在用v2rayNG 1.3.3版本没有任何问题可以VPN，测试网速也是正常的。但更新到1.4.13后发现无法连接vpn网络，测试网速提示“失败：io.read/write on closed pipe"错误。升级到1.5.15版本后也是一样的错误。
> 
> 我的手机为小米8青春和小米8旗舰

我也是MI 8，也遇到过类似问题。你可以尝试以下这几种方法，具体是那种方法奏效我还不清楚：

(1) 首先确保节点配置正确，然后右上角点击“重启服务”
(2) 点击左上角，进入设置，更改本地DNS和远程DNS，并将其添加到自定义规则的“直连网址或ip”，保存并退出，重启服务
(3) 有时候可能会出现端口占用的情况，这时候可以点击左上角，进入设置，更改http和socks代理端口，重启服务

以上每一步后都测试一下功能是否正常。如果还没能解决的话，我也爱莫能助了。

**Comment by xin78** [comment]
服务器端同步设置更改
