### ISSUE TITLE
tun2socks的dns可能有点问题

### ISSUE THREAD

**Issue by zenyanbo** [2dust/v2rayNG#911]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
自定义设置中，设置了拦截入站标签流量中53端口的流量到dns-out，dns理应被core的dns服务器接管
      {
        "inboundTag": [
          "socks",
          "http"
        ],
        "port": "53",
        "outboundTag": "dns-out",
        "type": "field"
      }

### 实际行为
启动配置的头几分钟，日志中确实可以看到
udp:1.1.1.1:53 [socks -> dns-out]
确实当时是可以拦截tun2socks设置的dns。
但是过了几分钟就无法拦截，dns服务器中自定义的host也失效了。日志中，udp:1.1.1.1:53 [socks -> dns-out]就消失了，但仍然存在其他app内置的dns拦截的消息，比如udp:103.126.92.133:53 [socks -> dns-out]（网易）。所以我猜测，可能问题出在tun2socks，没有把dns流量导入core

### 复现方法
1.在路由中，首条设置
      {
        "inboundTag": [
          "socks",
          "http"
        ],
        "port": "53",
        "outboundTag": "dns-out",
        "type": "field"
      }
不要开启本地dns。

### 日志信息
这三天没有电脑，稍后补上

**Comment by rurirei** [comment]
do you try Custom Configuration?

**Comment by zenyanbo** [comment]
> do you try Custom Configuration?

Yes

**Comment by rurirei** [comment]
@zenyanbo say your configuration and logcat logs.
