### ISSUE TITLE
使用Shadowsocks和trojan协议疑似DNS出现异常

### ISSUE THREAD

**Issue by 669800** [2dust/v2rayNG#914]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。
全局模式下，安卓10YouTube客户端内图片可以正常加载，但是所有视频一直转圈无法播放！！！用回vmess或者vless协议就没有这个问题！原版shadowsocks客户端也没有这个问题！

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by rurirei** [comment]
disable Experiment-QUIC of your Chrome:flags. #709

**Comment by 669800** [comment]
> disable Experiment-QUIC of your Chrome:flags. #709

不是chrome浏览器，是安卓YouTube客户端啊！

**Comment by rurirei** [comment]
say your logs. 
```cmd
adb logcat -s GoLog
```
