### ISSUE TITLE
点开启后，立即跳出v2rayNG已停止提示框，手机为三星S4 E330S 安卓4.4.2系统. ------ 是何原因望解答，谢谢！!！ 19年9月4日最新补充：(  --------- beginning of /dev/log/main --------- beginning of /dev/log/system  打开程序界面，启动代理后，便显示启动服务中，V2rayNG己停止，此次版本未更新之前，以前的老版本是安装后第一次运行程序界面都打不开，便显示V2r a yNG己停止，让点击报告或确定，现在的更新版本界面可以打开，可以加入代理IP，就是点启动代理时显示v2rayNG己停止；手机为三星S4韩版 SHV E330S，安卓系统版本4.4.2    。)  有进步，希望继续改进解决问题，解决后将给5星。

### ISSUE THREAD

**Issue by ShHTang** [2dust/v2rayNG#92]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 额外信息（可选）

点开启后，立即跳出v2rayNG已停止提示框，手机为三星S4 E330S 安卓4.4.2系统. ------ 是何原因望解答，谢谢！!！
19年9月4日最新补充：(
 --------- beginning of /dev/log/main
--------- beginning of /dev/log/system

打开程序界面，启动代理后，便显示启动服务中，V2rayNG己停止，此次版本未更新之前，以前的老版本是安装后第一次运行程序界面都打不开，便显示V2r a yNG己停止，让点击报告或确定，现在的更新版本界面可以打开，可以加入代理IP，就是点启动代理时显示v2rayNG己停止；手机为三星S4韩版
SHV E330S，安卓系统版本4.4.2    。)  有进步，希望继续改进解决问题，解决后将给5星。

**Comment by 2dust** [comment]
没有相同的环境可以测试,我想是解决不了你这个问题了
另外,最低版本以后会提升到5

**Comment by dancorpse** [comment]
我的情况和楼主一样，也是4.4.2，那么目前是无解了么？

**Comment by likounin** [comment]
安卓4.4.4同样有这个问题...身边一堆老设备都用不了...

**Comment by 0x05t** [comment]
442不能？
