### ISSUE TITLE
Geo全家桶 Surge规则链接已失效 已失效 已失效很久 隔壁KafuuChinoQ大佬失联

### ISSUE THREAD

**Issue by myjensen1973** [2dust/v2rayNG#92]
@2dust 2大能否自建个Geo全家桶 把V2RayGeoKit借鉴来改改 lhie1好规则可惜啊 年久失修 实测很多场景已无法使用 例如开启规则的情况下 基友们常用的智友app 各板块都进不去了 已被屏蔽 还有部分网站也打不开 代表3亿用户请求维护下全家桶 跪谢

**Comment by myjensen1973** [comment]
这么好的规则 荒废了着实可惜

**Comment by Platway** [comment]
我觉得如果全家桶难以维护，不如恢复为v2ray-core官方的geo*.dat
