### ISSUE TITLE
能否更新v2ray core

### ISSUE THREAD

**Issue by 22hello** [2dust/v2rayNG#920]
RT VMESS使用xray有问题 能否更新v2ray core到v4.34版本

**Comment by Fhokud** [comment]
> RT VMESS使用xray有问题 能否更新v2ray core到v4.34版本

什么问题呢？

**Comment by haozhengtu** [comment]
你也在等源码啊,就这大神写的最好 ，我等好几天了不支持vless 我留言了不知道大神能更新不

**Comment by haozhengtu** [comment]
> > RT VMESS使用xray有问题能否更新v2ray core到v4.34版本
> 
> 什么问题呢？

老大可以更新下源码 吗,源码不是最新的
