### ISSUE TITLE
v2ray什么时候适配安卓电视和电视盒子

### ISSUE THREAD

**Issue by JM-CPU-GPU** [2dust/v2rayNG#921]
V2ray什么时候能适配安卓电视，刚刚用最新版在安卓9的电视盒子上安装，显示安装失败

**Comment by HogwartsRico** [comment]
我觉得还是用软路由来的更方便和简单些

**Comment by ymcoming** [comment]
> 我觉得还是用软路由来的更方便和简单些

不一样，软路由是家用。如果在外地出差旅行什么的，我带一个fire stick 火棒什么的，随时插在电视上就能翻墙看netflix了。所以还是需要TV端的NG，适用性更好。

其实现在也勉强能用，但遥控器很多NG的菜单点不上，不方便。

**Comment by Barry-SH** [comment]
装在N1的盒子上没有问题。就是配置时候用蓝牙鼠标设置，遥控器无法配置。
