### ISSUE TITLE
息屏后常常自动断开连接

### ISSUE THREAD

**Issue by TinkMingKing** [2dust/v2rayNG#93]
最新版1.1.1
息屏后常常自动断开vpn连接

一加5T官方最新系统

**Comment by 2dust** [comment]
这个先尝试下系统自带的电池优化等设置

**Comment by TinkMingKing** [comment]
电池优化已取消，设置始终连接，但是还是会掉，不过锁后台貌似就没问题了，不过之前不用这样。。。算了，问题不大
