### ISSUE TITLE
应用被小米手机加入广告

### ISSUE THREAD

**Issue by Butterflyflower** [2dust/v2rayNG#930]
![IMG_20210310_204530_098](https://user-images.githubusercontent.com/67359838/110631721-ca80de80-81e1-11eb-9964-6063adab394a.jpg)
![IMG_20210310_204519_340](https://user-images.githubusercontent.com/67359838/110631728-cce33880-81e1-11eb-9ebc-8c279129e489.jpg)

v2rayng在小米手机上被 小米硬插入了开屏广告。

上次出这样的事情，是黑阈这个软件（木有广告）。
由于小米应用市场里 有黑阈 同包名软件，同包名软件加入了小米移动广告联盟。然后正版的黑阈软件，在小米手机上也被小米加了广告。

现在可能是小米应用市场里有一个同包名应用，加入了小米移动广告联盟。小米手机检测到 v2rayng 与 加入小米移动广告联盟的应用 包名一样，就开始推送开屏广告。

开发者可以更改v2rayng包名解决这个问题。

**Comment by ratzielhwb** [comment]
隐私保护-管理-特殊应用权限-显示在其他应用上层-智能服务关闭

**Comment by Z-fly** [comment]
我刚刚也发现了！

**Comment by Z-fly** [comment]
> 隐私保护-管理-特殊应用权限-显示在其他应用上层-智能服务关闭

MIUI12.5是这样
隐私保护-保护隐私-特殊权限设置-显示在其他应用上层-更多-显示系统程序-智能服务-允许显示在其他应用上层-关闭

**Comment by jiqing112** [comment]
吓得我以为小米又搞了什么小动作，赶紧卸载重装还是有类似的问题。果然有人也发现了。

可是我照着楼上的朋友的方法，关闭了智能服务的显示在上层，再重新打开v2rayng之后，还是有广告。再看智能服务，又是打开的了？？？

![Screenshot_2021-03-10-17-29-20-348_com v2ray ang](https://user-images.githubusercontent.com/17674011/110644027-a4fad180-81ef-11eb-93a7-f734d80e57cd.jpg)
![Screenshot_2021-03-10-17-29-11-947_com v2ray ang](https://user-images.githubusercontent.com/17674011/110644038-a6c49500-81ef-11eb-9235-2dcb799c4ffa.jpg)

**Comment by Butterflyflower** [comment]
就是小米搞的事情，你没有冤枉小米。

**Comment by Z-fly** [comment]
> 吓得我以为小米又搞了什么小动作，赶紧卸载重装还是有类似的问题。果然有人也发现了。
> 
> 可是我照着楼上的朋友的方法，关闭了智能服务的显示在上层，再重新打开v2rayng之后，还是有广告。再看智能服务，又是打开的了？？？
> 
> ![Screenshot_2021-03-10-17-29-20-348_com v2ray ang](https://user-images.githubusercontent.com/17674011/110644027-a4fad180-81ef-11eb-93a7-f734d80e57cd.jpg)
> ![Screenshot_2021-03-10-17-29-11-947_com v2ray ang](https://user-images.githubusercontent.com/17674011/110644038-a6c49500-81ef-11eb-9235-2dcb799c4ffa.jpg)

你是MIUI几？

**Comment by Cenicitas** [comment]
![photo_2021-03-11_02-04-51 (2)](https://user-images.githubusercontent.com/80419373/110677893-a7215800-8210-11eb-8c8d-d5b53869f374.jpg)
![photo_2021-03-11_02-04-51](https://user-images.githubusercontent.com/80419373/110677897-a7b9ee80-8210-11eb-84ed-b44ec17735e7.jpg)
![photo_2021-03-11_02-21-54 (2)](https://user-images.githubusercontent.com/80419373/110677898-a8528500-8210-11eb-950a-7f7b397b28ea.jpg)
![photo_2021-03-11_02-21-54](https://user-images.githubusercontent.com/80419373/110677902-a8eb1b80-8210-11eb-8cc7-9c18a88b00f3.jpg)
我这台小米6，miui11也被小米开始劫持了，另附商店更新信息，目前并无商店版替换应用的情况

**Comment by asdasd1dsadsa** [comment]
Same issue. I'm switching to raw Android.

**Comment by strplay** [comment]
adb shell pm uninstall --user 0 com.miui.systemAdSolution

至少我是这么干的

**Comment by zhang8688** [comment]
根目录有个miad文件夹，删除，用一个txt改名为miad，不要任何后缀即可取消

**Comment by yuhan6665** [comment]
👍 人人都是高手

**Comment by Z-fly** [comment]
> 👍 人人都是高手

想起那个大连车务段，笑死我力

**Comment by wlvx** [comment]
> 根目录有个miad文件夹，删除，用一个txt改名为miad，不要任何后缀即可取消

成功了，感谢！不知道这个是否会有影响

**Comment by Z-fly** [comment]
> > 根目录有个miad文件夹，删除，用一个txt改名为miad，不要任何后缀即可取消
> 
> 成功了，感谢！不知道这个是否会有影响

这个miad就是小米广告的意思

**Comment by wlvx** [comment]
> > > 根目录有个miad文件夹，删除，用一个txt改名为miad，不要任何后缀即可取消
> > 
> > 
> > 成功了，感谢！不知道这个是否会有影响
> 
> 这个miad就是小米广告的意思

哇！去掉了许多进入应用时的界面广告

**Comment by FikaCode** [comment]
小米牛皮，我刚想发一个Issue 就看到有人问了，猝不及防。

**Comment by LAJBK** [comment]
我也是在昨天晚上突然就出现了启动广告，我还以为之前下载了盗版的，更新了好几次还是有，用楼上兄台miad文件的方法已经解决了，感谢分享！

**Comment by LAJBK** [comment]
> 根目录有个miad文件夹，删除，用一个txt改名为miad，不要任何后缀即可取消

厉害了哥们儿

**Comment by FikaCode** [comment]
补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。

**Comment by sleepinghua** [comment]
我是卸载智能服务的更新解决的

**Comment by JakleSci** [comment]
> 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。

Google play下载小米国际版的文件管理可以免root查看，Android11.

**Comment by aaa1115910** [comment]
按理说要上架通过审核的应用才能够开启开屏广告https://dev.mi.com/console/doc/detail?pId=902

**Comment by LAJBK** [comment]
> 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。

我是电脑创建的文件然后拷到手机里的

**Comment by Z-fly** [comment]
> > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> 
> Google play下载小米国际版的文件管理可以免root查看，Android11.

小米部分机型已经不让使用Google play了

**Comment by Butterflyflower** [comment]
> 按理说要上架通过审核的应用才能够开启开屏广告https://dev.mi.com/console/doc/detail?pId=902

一、同包名应用加入了小米广告联盟
二、小米广告联盟bug
三、内部人员干的事

**Comment by LAJBK** [comment]
> > > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> > 
> > 
> > Google play下载小米国际版的文件管理可以免root查看，Android11.
> 
> 小米部分机型已经不让使用Google play了

这个以后怎么解决，买国际版的手机能不能解决

**Comment by Z-fly** [comment]
> > > > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> > > 
> > > 
> > > Google play下载小米国际版的文件管理可以免root查看，Android11.
> > 
> > 
> > 小米部分机型已经不让使用Google play了
> 
> 这个以后怎么解决，买国际版的手机能不能解决

最简单的办法是解BL锁后ROOT，小米至少能让所有机型解开BL锁。

**Comment by PlayerYK** [comment]
> > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> 
> Google play下载小米国际版的文件管理可以免root查看，Android11.

刚研究了一下，虽然不能拷贝不能新建文件，但是可以把这个文件夹压缩，然后重命名。

**Comment by cairenbin** [comment]
> 隐私保护-管理-特殊应用权限-显示在其他应用上层-智能服务关闭

我没开也有。。。

改用楼上放个文件占坑的方式解决了。。。

真的家贼难防

**Comment by ohyeah521** [comment]
不要用小米手机，换成一加。

**Comment by shuax** [comment]
> > > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> > 
> > 
> > Google play下载小米国际版的文件管理可以免root查看，Android11.
> 
> 刚研究了一下，虽然不能拷贝不能新建文件，但是可以把这个文件夹压缩，然后重命名。

这个办法简单，用自带的文件管理就能操作完成。
操作完了以后很多软件都没广告了。

**Comment by kokutoukiritsugu** [comment]
小米/红米手机建议高通CPU机型都解锁后刷xiaomi.eu的rom
都科学上网了, 建议还是用欧洲的ROM吧...

**Comment by gatspy** [comment]
> 隐私保护-管理-特殊应用权限-显示在其他应用上层-智能服务关闭

关闭后，一打开app又自动开启了这个服务。怎么解

**Comment by lvziqiao521** [comment]
我是miui11，怎么找不到com.miui.systemAdSolution我怎么找不到这个文件？

> 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。

**Comment by FikaCode** [comment]
@lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。

**Comment by lvziqiao521** [comment]
> @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。

文件管理器一打开也没找到这个文件啊。能详细点说吗？

**Comment by FikaCode** [comment]
> > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> 
> 文件管理器一打开也没找到这个文件啊。能详细点说吗？

手头没有安卓10的机子，网上找的图。

![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)

第二张图，删掉，然后新建一个文件，miad。

**Comment by lvziqiao521** [comment]
> 根目录有个miad文件夹，删除，用一个txt改名为miad，不要任何后缀即可取消

亲测可用，技术大佬牛

**Comment by lvziqiao521** [comment]
> > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > 
> > 
> > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> 
> 手头没有安卓10的机子，网上找的图。
> 
> ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> 
> 第二张图，删掉，然后新建一个文件，miad。

我去，我把整个miad文件都删掉了没事吧？

**Comment by FikaCode** [comment]
> > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > 
> > > 
> > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > 
> > 
> > 手头没有安卓10的机子，网上找的图。
> > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > 第二张图，删掉，然后新建一个文件，miad。
> 
> 我去，我把整个miad文件都删掉了没事吧？

不影响。

**Comment by lvziqiao521** [comment]
> > > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > > 
> > > > 
> > > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > > 
> > > 
> > > 手头没有安卓10的机子，网上找的图。
> > > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > > 第二张图，删掉，然后新建一个文件，miad。
> > 
> > 
> > 我去，我把整个miad文件都删掉了没事吧？
> 
> 不影响。

谢谢啦，顺带问句如果不再新建一个miad文件会出bug吗？

**Comment by FikaCode** [comment]
> > > > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > > > 
> > > > > 
> > > > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > > > 
> > > > 
> > > > 手头没有安卓10的机子，网上找的图。
> > > > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > > > 第二张图，删掉，然后新建一个文件，miad。
> > > 
> > > 
> > > 我去，我把整个miad文件都删掉了没事吧？
> > 
> > 
> > 不影响。
> 
> 谢谢啦，顺带问句如果不再新建一个miad文件会出bug吗？

不新建的话，等会再打开文件管理器，小米又会把这个文件弄出来。

**Comment by lvziqiao521** [comment]
> > > > > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > > > > 
> > > > > > 
> > > > > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > > > > 
> > > > > 
> > > > > 手头没有安卓10的机子，网上找的图。
> > > > > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > > > > 第二张图，删掉，然后新建一个文件，miad。
> > > > 
> > > > 
> > > > 我去，我把整个miad文件都删掉了没事吧？
> > > 
> > > 
> > > 不影响。
> > 
> > 
> > 谢谢啦，顺带问句如果不再新建一个miad文件会出bug吗？
> 
> 不新建的话，等会再打开文件管理器，小米又会把这个文件弄出来。
太可怕了，我手机只能新建空文件夹，你们是怎么建的txt文件？

**Comment by FikaCode** [comment]
> > > > > > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > > > > > 
> > > > > > > 
> > > > > > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > > > > > 
> > > > > > 
> > > > > > 手头没有安卓10的机子，网上找的图。
> > > > > > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > > > > > 第二张图，删掉，然后新建一个文件，miad。
> > > > > 
> > > > > 
> > > > > 我去，我把整个miad文件都删掉了没事吧？
> > > > 
> > > > 
> > > > 不影响。
> > > 
> > > 
> > > 谢谢啦，顺带问句如果不再新建一个miad文件会出bug吗？
> > 
> > 
> > 不新建的话，等会再打开文件管理器，小米又会把这个文件弄出来。
> > 太可怕了，我手机只能新建空文件夹，你们是怎么建的txt文件？

用上面这个老哥 @PlayerYK 的方法，随便新建一个文件，长按该文件，更多里面选择压缩，然后压缩名字改为 miad ，后面的后缀 zip 不要。

**Comment by lvziqiao521** [comment]
> > > > > > > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 手头没有安卓10的机子，网上找的图。
> > > > > > > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > > > > > > 第二张图，删掉，然后新建一个文件，miad。
> > > > > > 
> > > > > > 
> > > > > > 我去，我把整个miad文件都删掉了没事吧？
> > > > > 
> > > > > 
> > > > > 不影响。
> > > > 
> > > > 
> > > > 谢谢啦，顺带问句如果不再新建一个miad文件会出bug吗？
> > > 
> > > 
> > > 不新建的话，等会再打开文件管理器，小米又会把这个文件弄出来。
> > > 太可怕了，我手机只能新建空文件夹，你们是怎么建的txt文件？
> 
> 用上面这个老哥 @PlayerYK 的方法，随便新建一个文件，长按该文件，更多里面选择压缩，然后压缩名字改为 miad ，后面的后缀 zip 不要。

我的更多里面只有复制、设为私密、重命名、详情

**Comment by lvziqiao521** [comment]
> > > > > > > > > @lvziqiao521 miui 11 应该是安卓10 ，在根目录下面，就是文件管理器一打开就是根目录。安卓11 才需要去data下面弄。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 文件管理器一打开也没找到这个文件啊。能详细点说吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 手头没有安卓10的机子，网上找的图。
> > > > > > > ![屏幕截图 2021-03-11 152118](https://user-images.githubusercontent.com/42266215/110750576-a8d53500-827d-11eb-82fc-f8fd23d1bd2d.png)
> > > > > > > 第二张图，删掉，然后新建一个文件，miad。
> > > > > > 
> > > > > > 
> > > > > > 我去，我把整个miad文件都删掉了没事吧？
> > > > > 
> > > > > 
> > > > > 不影响。
> > > > 
> > > > 
> > > > 谢谢啦，顺带问句如果不再新建一个miad文件会出bug吗？
> > > 
> > > 
> > > 不新建的话，等会再打开文件管理器，小米又会把这个文件弄出来。
> > > 太可怕了，我手机只能新建空文件夹，你们是怎么建的txt文件？
> 
> 用上面这个老哥 @PlayerYK 的方法，随便新建一个文件，长按该文件，更多里面选择压缩，然后压缩名字改为 miad ，后面的后缀 zip 不要。

老哥我随便找了个不是文件夹的文件照你这么说的压缩了。。不知道有没有影响

**Comment by lvziqiao521** [comment]
![Screenshot_2021-03-11-15-46-21-734_com android fileexplorer](https://user-images.githubusercontent.com/80446294/110753010-9a4e3580-820b-11eb-93bc-5be2501e65f7.jpg)
我刚发现能发图。。

**Comment by FikaCode** [comment]
@lvziqiao521 不影响。你发图好像不对，miad 最后是一个文件不是文件夹，不可以打开的。

**Comment by lvziqiao521** [comment]
> @lvziqiao521 不影响。你发图好像不对，miad 最后是一个文件不是文件夹，不可以打开的。

![Screenshot_2021-03-11-16-01-28-235_com android fileexplorer](https://user-images.githubusercontent.com/80446294/110754799-d2567800-820d-11eb-807c-c9cfeb8c79d7.jpg)
我把以前的miad文件夹删了，把里面那个miad移动到根目录下这样行吗？

**Comment by cairenbin** [comment]
> > @lvziqiao521 不影响。你发图好像不对，miad 最后是一个文件不是文件夹，不可以打开的。
> 
> ![Screenshot_2021-03-11-16-01-28-235_com android fileexplorer](https://user-images.githubusercontent.com/80446294/110754799-d2567800-820d-11eb-807c-c9cfeb8c79d7.jpg)
> 我把以前的miad文件夹删了，把里面那个miad移动到根目录下这样行吗？

你把miad文件夹压缩成miad.zip，然后把文件夹删掉，再重命名zip文件把后缀名删掉就行了，用文件占着坑，不让服务拉广告流数据下来

**Comment by lvziqiao521** [comment]
> > > @lvziqiao521 不影响。你发图好像不对，miad 最后是一个文件不是文件夹，不可以打开的。
> > 
> > 
> > ![Screenshot_2021-03-11-16-01-28-235_com android fileexplorer](https://user-images.githubusercontent.com/80446294/110754799-d2567800-820d-11eb-807c-c9cfeb8c79d7.jpg)
> > 我把以前的miad文件夹删了，把里面那个miad移动到根目录下这样行吗？
> 
> 你把miad文件夹压缩成miad.zip，然后把文件夹删掉，再重命名zip文件把后缀名删掉就行了，用文件占着坑，不让服务拉广告流数据下来

miad文件夹被我不小心一整个删掉了。。

**Comment by FikaCode** [comment]
@lvziqiao521 你按照 @cairenbin 这个老哥操作来。没有miad 文件的话随便随便创建一个文件夹，压缩它就可以了。最后只有miad这个文件，没有miad文件夹。

**Comment by cairenbin** [comment]
> > > > @lvziqiao521 不影响。你发图好像不对，miad 最后是一个文件不是文件夹，不可以打开的。
> > > 
> > > 
> > > ![Screenshot_2021-03-11-16-01-28-235_com android fileexplorer](https://user-images.githubusercontent.com/80446294/110754799-d2567800-820d-11eb-807c-c9cfeb8c79d7.jpg)
> > > 我把以前的miad文件夹删了，把里面那个miad移动到根目录下这样行吗？
> > 
> > 
> > 你把miad文件夹压缩成miad.zip，然后把文件夹删掉，再重命名zip文件把后缀名删掉就行了，用文件占着坑，不让服务拉广告流数据下来
> 
> miad文件夹被我不小心一整个删掉了。。


只是要占位而已，随便什么都行。。。
真纠结你就再打开一下，让广告再开一次文件夹就回来了

**Comment by lvziqiao521** [comment]
> @lvziqiao521 你按照 @cairenbin 这个老哥操作来。没有miad 文件的话随便随便创建一个文件夹，压缩它就可以了。最后只有miad这个文件，没有miad文件夹。

![IMG_20210311_161943](https://user-images.githubusercontent.com/80446294/110756807-45f98480-8210-11eb-8728-44cab3ce073b.jpg)
不是这样吗？

**Comment by sumiort** [comment]
真给力神速

**Comment by FikaCode** [comment]
@lvziqiao521 应该是没问题。你的和其他老哥的区别在于，你的这个文件是从原来的miad 文件夹里移动出来的，其他人的是 要么新建，要么压缩。你打开v2rayNG 看看是否还有开屏广告，看看是否生效。

**Comment by lvziqiao521** [comment]
> @lvziqiao521 应该是没问题。你的和其他老哥的区别在于，你的这个文件是从原来的miad 文件夹里移动出来的，其他人的是 要么新建，要么压缩。你打开v2rayNG 看看是否还有开屏广告，看看是否生效。

目前还没啥问题，谢啦！后期如果再有问题我再删了重新建一个

**Comment by VVaraiotoko** [comment]
> 按理说要上架通过审核的应用才能够开启开屏广告https://dev.mi.com/console/doc/detail?pId=902

如果世人都讲理，世界该多么美好…这种情况应该是有人故意提交同包名应用白嫖广告费，小米客服肯定只检查它有没有冒名小米应用商店里的应用，别的都不管。😂

**Comment by flyhong666** [comment]
我的是miui 12.5 最新内测版，还没发现有广告。

**Comment by jiqing112** [comment]
现在已经没有广告了，各位朋友测试一下看看

**Comment by imkyleshing** [comment]
> > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> 
> 我是电脑创建的文件然后拷到手机里的

我用MT管理器去这里看不到MIAD文件夹，然后用新建功能建了MIAD的无后缀文件，不知道有影响不。

**Comment by CodeDreamfy** [comment]
有人说是v2ex的网友恶搞的，不清楚是不是真的，v2ex专门有这么个群

**Comment by Z-fly** [comment]
> 有人说是v2ex的网友恶搞的，不清楚是不是真的，v2ex专门有这么个群

事情已经解决了吧

**Comment by Butterflyflower** [comment]
> 有人说是v2ex的网友恶搞的，不清楚是不是真的，v2ex专门有这么个
已经没有后续反馈了，应该没有广告了。

> 有人说是v2ex的网友恶搞的，不清楚是不是真的，v2ex专门有这么个群

应该没有在弹广告了

**Comment by qyuzh** [comment]
专门下了个Kiwi浏览器, 就是喜欢它的没有广告. 结果今天一更新系统广告就来了, 我开始还以为是kiwi, 结果是小米, 恶心的一批, 艹....还是选择iphone吧.

**Comment by Z-fly** [comment]
> 专门下了个Kiwi浏览器, 就是喜欢它的没有广告. 结果今天一更新系统广告就来了, 我开始还以为是kiwi, 结果是小米, 恶心的一批, 艹....还是选择iphone吧.

毕竟是小米

**Comment by yannsean** [comment]
修改文件方法可以，插个眼以防以后换了文件夹

**Comment by xhemj** [comment]
kiwi现在也被插了开屏广告了

**Comment by hesaicn** [comment]
呼唤小爱助手   关闭系统广告 完事

**Comment by ghost** [comment]
> > 补充：安卓11 miad 的位置，/Android/data/com.miui.systemAdSolution/files 下面，但是自带的文件管理器无法创建文件，可以使用rootExpore，可能需要root，具体没试过（我的手机是root了的）。
> 
> Google play下载小米国际版的文件管理可以免root查看，Android11.

不用那么麻烦，数据线连接到电脑上，用电脑操作就行了。几秒搞定

**Comment by fj4090** [comment]
我红米10x pro 稳定版12.5.6,miad目录找到也是和11一样，压缩目录，改名，删除原目录，目前没广告，这个软件能卸载吗？反正只是一个广告推送app？

**Comment by czfadmin** [comment]
> > 专门下了个Kiwi浏览器, 就是喜欢它的没有广告. 结果今天一更新系统广告就来了, 我开始还以为是kiwi, 结果是小米, 恶心的一批, 艹....还是选择iphone吧.
> 
> 毕竟是小米

小米，这广告这么恶心的吗

**Comment by yjd** [comment]
大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。
后来直接用adb删除那2个内置广告应用。
pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案
pm uninstall --user 0 com.miui.analytics //小米广告分析

**Comment by sssme** [comment]
> 大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。
> 后来直接用adb删除那2个内置广告应用。
> pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案
> pm uninstall --user 0 com.miui.analytics //小米广告分析

这样会不会导致无法开机

**Comment by yjd** [comment]
> > 大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。
> > 后来直接用adb删除那2个内置广告应用。
> > pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案
> > pm uninstall --user 0 com.miui.analytics //小米广告分析
> 
> 这样会不会导致无法开机

不会有问题，还可以用 pm install-existing xxx 重新把内置应用安装回去

**Comment by Bumblehao** [comment]
> ![IMG_20210310_204530_098](https://user-images.githubusercontent.com/67359838/110631721-ca80de80-81e1-11eb-9964-6063adab394a.jpg) ![IMG_20210310_204519_340](https://user-images.githubusercontent.com/67359838/110631728-cce33880-81e1-11eb-9ebc-8c279129e489.jpg)
> 
> v2rayng在小米手机上被 小米硬插入了开屏广告。
> 
> 上次出这样的事情，是黑阈这个软件（木有广告）。 由于小米应用市场里 有黑阈 同包名软件，同包名软件加入了小米移动广告联盟。然后正版的黑阈软件，在小米手机上也被小米加了广告。
> 
> 现在可能是小米应用市场里有一个同包名应用，加入了小米移动广告联盟。小米手机检测到 v2rayng 与 加入小米移动广告联盟的应用 包名一样，就开始推送开屏广告。
> 
> 开发者可以更改v2rayng包名解决这个问题。

miui就™这德行，酷安也被加广告，垃圾miui

**Comment by Momo-ProMax** [comment]
辣鸡miui，就™你小米加广告，别的厂商都没有，酷安也被加广告。

**Comment by WenqiOfficial** [comment]
当初是Malody被加广告才发现是小米的广告服务，那时候还能对miad下手，现在都直接移动到data里面去了；
虽说广告是为了增加自己的收入，但是至少也给用户能选择的权力，**能自由关闭才是对的**

**Comment by hujesse83** [comment]
哈哈哈哈 太搞笑了

**Comment by weiwoduga** [comment]
1.手机管家→隐私保护→右划点击“保护隐私”，拉到底点击“特殊权限设置”→显示在其他应用的上层→点击底部中间的“更多”，点击“显示系统程序”→拉到底，点击“智能服务”这个APP→关闭
2.手机管家→隐私保护→右划点击“保护隐私”，拉到底点击“特殊权限设置”，点击“修改系统设置”→点击底部中间的“更多”，点击“显示系统程序”→拉到底，点击“智能服务”这个APP→关闭

**Comment by gloryandel** [comment]
自从在小米应用商店下载UC浏览器后没有屏蔽全部广告选项就不敢随便在上面更新了

**Comment by drw2005** [comment]
我一直用的海外版uc browser以前没有广告，后来也出现广告了，我一直以为是uc作恶。难道也是因为miui？
按照楼上说的先关闭试试。

我现在是最新的MIUI13

**Comment by gloryandel** [comment]
> 辣鸡miui，就™你小米加广告，别的厂商都没有，酷安也被加广告。

指的是小米应用商店下载或更新的可能加,MIUI本身并没有

**Comment by drw2005** [comment]
靠，今天又有了，最新的MIUI13内测版，下面是用海外版UC Browser浏览器出现的广告，有的是点击菜单跟着弹出的，有的直接开屏广告。有没有高手知道是是小米的原因，还是UC本身的原因？已经按照上面的大佬们说的关闭智能服务了。

跟着菜单弹出的
![Screenshot_2022-04-11-09-13-37-615_com UCMobile intl](https://user-images.githubusercontent.com/33473981/162653408-b88b7c2f-89f8-44f2-8f0b-e493705b4d7d.png)

后台切换回来后，直接满屏的：
![Screenshot_2022-04-11-09-14-36-717_com UCMobile intl](https://user-images.githubusercontent.com/33473981/162653417-745007e2-9fce-4de3-8d0b-c7e9f14e3586.png)

**Comment by asdasd1dsadsa** [comment]
> 大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。 后来直接用adb删除那2个内置广告应用。 pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案 pm uninstall --user 0 com.miui.analytics //小米广告分析

补充一下，新一点的改包名了。比如国际版的叫 `com.miui.msa.global`

**Comment by soyadokio** [comment]
#### MIUI版本
MIUI 11.0.4|稳定版
11.0.4.0(QFJCNXM)
#### Android版本
10
#### 操作
设置-密码、隐私与安全-系统安全-特殊应用权限-显示在其他应用的上层
#### 其它
但我在`显示在其他应用的上层`中并未找到`智能服务`选项

**Comment by whp98** [comment]
真离谱有那种劫持http网站插广告脚本的意思了

**Comment by wangyifan349** [comment]
我的建议就是利用v2ray的拦截功能
domain:xiaomi,
domain:MIUI.com
这小米有毒!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by simin-in-tw** [comment]
Maybe you should not use MIUI, instead of suggesting to change the package name.

**Comment by slindore** [comment]
噗，虽然我没看到广告，可是还是好奇的点进来，小米这操作真是给我整乐了

**Comment by HaoweiCh** [comment]
用小米的就没人用三方 ROM？ 抱怨 MIUI 的人群里我觉得不会有程序员。😄

**Comment by tigertall** [comment]
> #### MIUI版本
> MIUI 11.0.4|稳定版 11.0.4.0(QFJCNXM)
> 
> #### Android版本
> 10
> 
> #### 操作
> 设置-密码、隐私与安全-系统安全-特殊应用权限-显示在其他应用的上层
> 
> #### 其它
> 但我在`显示在其他应用的上层`中并未找到`智能服务`选项
底部三个点更多，选显示系统应用就有了

**Comment by fj4090** [comment]
> > 大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。 后来直接用adb删除那2个内置广告应用。 pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案 pm uninstall --user 0 com.miui.analytics //小米广告分析
> 
> 补充一下，新一点的改包名了。比如国际版的叫 `com.miui.msa.global`

我看系统还有个Android AdServices,要删除吗？看名字好像AD功能

**Comment by fj4090** [comment]
> 大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。 后来直接用adb删除那2个内置广告应用。 pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案 pm uninstall --user 0 com.miui.analytics //小米广告分析

我看系统还有个Android AdServices,要删除吗？看名字好像AD功能

**Comment by Freya-Tzimisce** [comment]
> > 大家都遇到了？我也是用了好几年。最近一个月才出现强行插入第三方应用开屏广告。 后来直接用adb删除那2个内置广告应用。 pm uninstall --user 0 com.miui.systemAdSolution //小米系统广告解决方案 pm uninstall --user 0 com.miui.analytics //小米广告分析
> 
> 我看系统还有个Android AdServices,要删除吗？看名字好像AD功能

先观望，这是Google自己搞的，甚至是以模块化系统组件的形式加入Android
