### ISSUE TITLE
如何加入自定义协议

### ISSUE THREAD

**Issue by dreamrover** [2dust/v2rayNG#938]
想给客户端加入自定义协议，看了下源码，貌似VMESS等协议被封装在了这个库里面：libv2ray.aar，能否介绍一下如何生成这个库？如果要创建一个类似的库以实现自定义协议，需要实现的接口有哪些？
我在网上找不到任何资料，谢谢。

**Comment by rurirei** [comment]
do you know v2fly/v2ray-core ?

**Comment by dreamrover** [comment]
> do you know v2fly/v2ray-core 

Of course I know, and I'm maintaining a deb installer [v2ray-deb](https://github.com/dreamrover/v2ray-deb).
And I've developed another proxy server based on my own protocol, but lacks an android client. The development of a new android proxy app like v2rayNG from ground is too complex. 
So I want to fork this project and completely replace v2ray-core with my own proxy lib in it. I'm not quite familiar with android development and not very clear with the procedure.
Could you provide some guidance?
Thanks a lot.

**Comment by rurirei** [comment]
>> So I want to fork this project and completely replace v2ray-core with my own proxy lib in it.

do you planning a proxy app on Android? maybe helped: 
@xiaokangwang/AndroidLibV2ray 
@2dust/AndroidLibV2rayLite 
@rurirei/go-libv2ray 
or @dreamcro/clash
