### ISSUE TITLE
如何实现类似于pac(gfwlist)

### ISSUE THREAD

**Issue by zaiweijian** [2dust/v2rayNG#939]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by zaiweijian** [comment]
v2rayn目前的自定义规则已经可以实现了，不知道ng有没有计划？

**Comment by zaiweijian** [comment]
或者增加个放弃使用预定义规则的选项，默认全部放行，然后使用自定义规则拦截。。。

**Comment by zaiweijian** [comment]
这样可以在自定义规则里只把geosite:gfw加到代理栏目里，其他全部放行。可以实现类似pac的效果

**Comment by sacc-leo** [comment]
> 这样可以在自定义规则里只把geosite:gfw加到代理栏目里，其他全部放行。可以实现类似pac的效果

其他全放行怎么设置？
