### ISSUE TITLE
链接不上

### ISSUE THREAD

**Issue by wannaNo1** [2dust/v2rayNG#94]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
<details>
通过 `adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main` 获取日志。请自行删减日志中可能出现的敏感信息。
--------- beginning of system
--------- beginning of main
09-05 10:31:51.211 I/GoLog   ( 9874): udp:127.0.0.1:48697 accepted udp:1.1.1.1:53 
09-05 10:31:51.570 I/GoLog   ( 9874): udp:127.0.0.1:37754 accepted udp:1.1.1.1:53 
09-05 10:31:52.155 I/GoLog   ( 9874): tcp:127.0.0.1:42960 accepted tcp:101.91.63.221:8080 
09-05 10:31:52.155 I/GoLog   ( 9874): Not Using Prepared: tcp,101.91.63.221:8080
09-05 10:31:52.818 I/GoLog   ( 9874): udp:127.0.0.1:55986 accepted udp:185.171.120.112:21104 
09-05 10:31:53.068 I/GoLog   ( 9874): udp:127.0.0.1:39736 accepted udp:1.1.1.1:53 
09-05 10:31:53.097 I/GoLog   ( 9874): tcp:127.0.0.1:42970 accepted tcp:101.91.63.221:8080 
09-05 10:31:53.097 I/GoLog   ( 9874): Not Using Prepared: tcp,101.91.63.221:8080
09-05 10:31:53.097 I/GoLog   ( 9874): tcp:127.0.0.1:42968 accepted tcp:101.91.63.221:8080 
09-05 10:31:53.098 I/GoLog   ( 9874): udp:127.0.0.1:57907 accepted udp:1.1.1.1:53 
09-05 10:31:53.098 I/GoLog   ( 9874): Not Using Prepared: tcp,101.91.63.221:8080

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

**Comment by 2dust** [comment]
没有可用的信息,解决不了
