### ISSUE TITLE
对DNS over HTTPS的流量进行代理会导致程序崩溃

### ISSUE THREAD

**Issue by 10330384** [2dust/v2rayNG#942]
v2fly 1.5.12

自定义配置文件中使用 DOH 并使用 `dns.google` 

并在 路由 中配置 `dns.google` 的流量通过代理服务器访问

会导致程序崩溃

若不在路由上配置，使DNS通过直连出口则没有问题

该配置在PC v2fly-core 可正常运行

部分配置内容如下所示

![snipaste](https://user-images.githubusercontent.com/16956298/111092228-6dce4c80-8570-11eb-8487-75eb28222607.jpg)

配置文件文本内容

[config.json.txt](https://github.com/2dust/v2rayNG/files/6138191/config.json.txt)

崩溃日志内容

[crash.log](https://github.com/2dust/v2rayNG/files/6138194/crash.log)

**Comment by rurirei** [comment]
say your complete configuration and logs.
