### ISSUE TITLE
自定义规则和预定义规则的关系？

### ISSUE THREAD

**Issue by blueboyggh** [2dust/v2rayNG#943]
如果预定义规则设置了绕过大陆和局域网，而自定义规则内写了一个大陆地址使用代理，那么这个大陆地址是遵循自定义规则还是预定义规则呢？

如果想完全使用自定义规则，如何需要预定义规则？

**Comment by libook** [comment]
我也有这个疑问，我测试得出的结论是预定义规则的优先级很可能高于自定义规则。

不知道是不是有特别的原因要这样设计，对于我来说希望自定义规则是对预定义规则的补充，所以要是自定义规则的优先级能高于预定义规则就好了。

**Comment by yuhan6665** [comment]
预定义直连局域网IP > 自定义代理 > 自定义直连 > 自定义黑洞 > 预定义直连 cn IP > 预定义直连 cn geosite

**Comment by laotang001** [comment]
自定义规则的优先级较高，会覆盖预定义规则。

如果预定义规则设置了绕过大陆和局域网，而自定义规则内写了一个大陆地址使用代理，那么这个大陆地址会遵循自定义规则而不是预定义规则
