### ISSUE TITLE
Android 10, targetSdkVersion update to 29, cmd.Start err fork/exec /data/user/0/xxxxxxxx/tun2socks: permission denied

### ISSUE THREAD

**Issue by Sopage** [2dust/v2rayNG#95]
Android 10
 targetSdkVersion update to 29
cmd.Start err fork/exec /data/user/0/xxxxxx/tun2socks: permission denied

### 预期行为
描述你认为应该发生什么

### 实际行为
描述实际发生了什么

### 复现方法
1.
2.
3.

### 日志信息
cmd.Start err fork/exec /data/user/0/xxxxx/tun2socks: permission denied

### 环境信息
Pixel XL
Android 10

**Comment by 2dust** [comment]
https://github.com/shadowsocks/shadowsocks-android

**Comment by 2dust** [comment]
You can learn from here
Solve it yourself

**Comment by bkbits** [comment]
我也被这个问题困扰了2天。。。最后发现是因为android 10的权限相关行为改变了，android 10为了兼容以前的app，在app targetSDK<29时会兼容以前的权限行为检查，所以你只需要吧targetSDK改为28就行了。

**Comment by TobiasYin** [comment]
> 我也被这个问题困扰了2天。。。最后发现是因为android 10的权限相关行为改变了，android 10为了兼容以前的app，在app targetSDK<29时会兼容以前的权限行为检查，所以你只需要吧targetSDK改为28就行了。

感谢老哥，被困扰的要自闭了，终于解决了，🙏🙏🙏🙏🙏🙏🙏🙏
