### ISSUE TITLE
Couldn't find DNS address

### ISSUE THREAD

**Issue by eroxs** [2dust/v2rayNG#950]
I connect to the tls + ws or http + tcp configuration and everything looks good at first
But suddenly (maybe a few hours or minutes later) when I try to open a site in a browser, I get an error I can not find the DNS address.
This error is very weak in the Chrome browser (sometimes displayed but the site suddenly opens)
This is also true for applications that use domains.
You have to think and have a solution
This does not look good at all

**Comment by dylanhowl** [comment]
to try setting:Advanced-Use secure DNS-off

**Comment by ghost** [comment]
if u turn on local dns? try to use localhost insteed alidns.

**Comment by eroxs** [comment]
The problem is not solved

**Comment by 2ndMessiah** [comment]
I got this problem very frequently so that I've switched to the bootlegged clash( which doesn't seem to support xtls)

With local DNS turned on, such situations still happen for unknown reasons.

**Comment by eroxs** [comment]
@2ndMessiah what is bootlegged clash ? 
Do you still have this problem? ) (find DNS)

**Comment by Lstions** [comment]
> if u turn on local dns? try to use localhost insteed alidns.

i tried and no avail, i can only close it to solve the problem

**Comment by libea18** [comment]
@2ndMessiah @Lstions turn on ipv6 route and share the result
