### ISSUE TITLE
新手使用问题

### ISSUE THREAD

**Issue by nyhy007** [2dust/v2rayNG#951]
香港谷歌云vps，日本线路
![Screenshot_20210318_071213_com chrome beta](https://user-images.githubusercontent.com/62008725/111550534-46b68b80-87b9-11eb-8873-b8f0f09dfa41.jpg)如图direct没有数据流量，求大神指教

**Comment by yaott2020-666** [comment]
你设置了全局吗

**Comment by nyhy007** [comment]
设置了 应该是墙高了？


yaott2020-666 ***@***.***> 于2021年3月18日周四 上午8:19写道：

**Comment by yaott2020-666** [comment]
这个和墙没关系
