### ISSUE TITLE
log功能仍然无法使用

### ISSUE THREAD

**Issue by haomuch** [2dust/v2rayNG#952]
无论如何配置，log功能页面都是一片空白，最新版1.5.17仍然没有解决这个问题，敬请大佬修复。

**Comment by ghost** [comment]
我的是正常的,你的情况应该是系统环境的问题,试下看让NG拥有storage权限 allow

**Comment by haomuch** [comment]
> 我的是正常的,你的情况应该是系统环境的问题,试下看让NG拥有storage权限 allow

storage权限是一只打开的，1.5.16版开始出现这个问题，之前都是正常的

**Comment by zhongchina666** [comment]
这应该是由WINDOWS 10最近的更新造成的新BUG而不是V2RayNG引起的。我的一款照片管理软件启动时写LOG文件导致软件挂起，然后看到新闻，是最近的一个更新导致写日志文件出现故障。

**Comment by zhongchina666** [comment]
Win10 KB4601319 更新后，部分用户文件历史记录备份功能失效。https://www.ithome.com/0/538/653.htm

**Comment by haomuch** [comment]
> V2RayNG引起的。我的一款照片管理软件启动

ng是在手机上使用啊，和Windows 10有啥关系呢

**Comment by zhongchina666** [comment]
> > V2RayNG引起的。我的一款照片管理软件启动
> 
> ng是在手机上使用啊，和Windows 10有啥关系呢

对不起，我犯了一个非常愚蠢的错误！

**Comment by haomuch** [comment]
最新1.6.2在OPPO Reno 4 pro，系统版本2021.03.13上仍然无法显示日志
