### ISSUE TITLE
Google 商店的版本不会再更新了吗？

### ISSUE THREAD

**Issue by TrayBer** [2dust/v2rayNG#959]
Google 商店的版本已经好久没有更新了，大概更新周期多久啊？

**Comment by winds365** [comment]
什么叫好久没更新，你打开测试版看看版本号

**Comment by TrayBer** [comment]
> 什么叫好久没更新，你打开测试版看看版本号

https://play.google.com/store/apps/details?id=com.v2ray.ang&hl=zh&gl=US
"更新日期 2020年11月28日"

我说的有错吗？

**Comment by 0honus0** [comment]
> > 什么叫好久没更新，你打开测试版看看版本号
> 
> https://play.google.com/store/apps/details?id=com.v2ray.ang&hl=zh&gl=US
> "更新日期 2020年11月28日"
> 
> 我说的有错吗？

从这里下测试版就能用，不用从商店下

**Comment by rurirei** [comment]
beta channel or apkmirror.com .
