### ISSUE TITLE
更新以后，可以上网，无法打游戏。上个版本是1.4.13

### ISSUE THREAD

**Issue by Kelvin-Go** [2dust/v2rayNG#961]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

以前用的一直是这个节点，什么都正常

今天更新最新版本以后（1.5.16），上网还是正常，游戏却提示连接不到服务器。

于是卸载了新版本，我找了一个老版本，用了相同的节点，可以游戏，可以上网。
继而我又把老版本更新成新版本以后，又是相同的问题。求解决！

**Comment by Wagnerxyz** [comment]
两部小米手机，Android10 &11 ，从1.4.13升级到最新1.5.16后，youtube观看严重卡顿，手机浏览器看youtube也一样卡顿。
卸载重装1.4.13版本恢复正常。
传输协议ws
