### ISSUE TITLE
新版本对某些json的兼容问题（无法启动，无法删除，UI错乱）

### ISSUE THREAD

**Issue by Sumire-Heanna** [2dust/v2rayNG#966]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
这是旧版本下导入附件的效果
![image](https://user-images.githubusercontent.com/37390710/112709498-2c855780-8ef5-11eb-99f4-9cbaedaa1975.png)

### 实际行为
描述实际发生了什么
这是更新后，以及新版本导入附件的效果
![image](https://user-images.githubusercontent.com/37390710/112709488-1a0b1e00-8ef5-11eb-969e-0beaf7f1935e.png)
![image](https://user-images.githubusercontent.com/37390710/112709545-884fe080-8ef5-11eb-82e6-c77a09a8b7aa.png)

### 复现方法
1.导入附件即可复现
2.有其他正常的节点，多次导入此json再试图删除即会出现UI错乱
3.

### 日志信息
<details>

03-27 12:19:28.404 21296 21296 E com.v2ray.ang: Not starting debugger since process cannot load the jdwp agent.
03-27 12:19:28.503 21296 21296 W com.v2ray.ang: Method Lcom/github/jinatonic/confetti/ConfettiSource;.getInitialX is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/name.mikanoshi.customiuizer-X46H5q7cEK2i5jr-NYW08A==/base.apk
03-27 12:19:28.503 21296 21296 W com.v2ray.ang: Method Lcom/github/jinatonic/confetti/ConfettiSource;.getInitialY is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/name.mikanoshi.customiuizer-X46H5q7cEK2i5jr-NYW08A==/base.apk
03-27 12:19:28.635 21296 21296 W com.v2ray.ang: Method Landroid/support/v4/media/MediaBrowserCompat$ConnectionCallback;.onConnected is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.635 21296 21296 W com.v2ray.ang: Method Landroid/support/v4/media/MediaBrowserCompat$ConnectionCallback;.onConnectionFailed is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.635 21296 21296 W com.v2ray.ang: Method Landroid/support/v4/media/MediaBrowserCompat$ConnectionCallback;.onConnectionSuspended is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.635 21296 21296 W com.v2ray.ang: Method Landroidx/appcompat/graphics/drawable/DrawableContainer;.cloneConstantState is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/core/graphics/TypefaceCompatBaseImpl;.createFromFontFamilyFilesResourceEntry is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/core/graphics/TypefaceCompatBaseImpl;.createFromFontInfo is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/core/view/WindowInsetsCompat$BuilderImpl;.build is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/core/view/WindowInsetsCompat$BuilderImpl;.setSystemWindowInsets is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/fragment/app/FragmentFactory;.instantiate is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/media/MediaBrowserServiceCompat$Result;.onResultSent is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.clearNonTransitionAlpha is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.getTransitionAlpha is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.saveNonTransitionAlpha is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.setAnimationMatrix is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.setTransitionAlpha is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.transformMatrixToGlobal is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.636 21296 21296 W com.v2ray.ang: Method Landroidx/transition/ViewUtilsBase;.transformMatrixToLocal is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.getElevation is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.initializeBackgroundDrawable is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.jumpDrawableToCurrentState is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.onDrawableStateChanged is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.onElevationsChanged is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.requirePreDrawListener is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.shouldAddPadding is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/floatingactionbutton/FloatingActionButtonImpl;.updateFromViewRotation is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.637 21296 21296 W com.v2ray.ang: Method Lcom/google/android/material/shape/CornerTreatment;.getCornerPath is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.640 21296 21296 W com.v2ray.ang: Method Landroidx/core/graphics/drawable/WrappedDrawableApi14;.isCompatTintEnabled is abstract, but the declaring class is neither abstract nor an interface in dex file /data/app/nil.nadph.qnotified-7f4J8hwwO3Idh3BCxD7bmg==/base.apk
03-27 12:19:28.957 21296 21323 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
03-27 12:19:28.960 21296 21323 I com.v2ray.ang: The ClassLoaderContext is a special shared library.
03-27 12:19:28.990 21296 21296 W com.v2ray.ang: type=1400 audit(0.0:17770): avc: denied { search } for name="ru.auLSaZJK.OldqqVPqY" dev="sda32" ino=127555 scontext=u:r:untrusted_app:s0:c125,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c59,c257,c512,c768 tclass=dir permissive=0
03-27 12:19:28.990 21296 21296 W com.v2ray.ang: type=1400 audit(0.0:17772): avc: denied { search } for name="ru.auLSaZJK.OldqqVPqY" dev="sda32" ino=127555 scontext=u:r:untrusted_app:s0:c125,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c59,c257,c512,c768 tclass=dir permissive=0
03-27 12:19:29.050 21296 21332 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geoip.dat
03-27 12:19:29.055 21296 21332 I com.v2ray.ang: Copied from apk assets folder to /storage/emulated/0/Android/data/com.v2ray.ang/files/assets/geosite.dat
03-27 12:19:36.926 21296 21316 I com.v2ray.ang: ProcessProfilingInfo new_methods=245 is saved saved_to_disk=1 resolve_classes_delay=8000

</details>

### 环境信息
Redmi K20 MIUI 11

### 额外信息（可选）
附件
[direct.json.txt](https://github.com/2dust/v2rayNG/files/6215122/direct.json.txt)

**Comment by 2dust** [comment]
因为1.5.18使用了新的存储，现在自定义配置文件也会检查。
您给出的测试用例的outbound没有NG支持的协议，有兼容问题，请重新下载并测试下
https://github.com/2dust/v2rayNG/releases/tag/1.5.18

**Comment by yuhan6665** [comment]
~~感谢反馈 我会尽快修复~~
https://github.com/2dust/v2rayNG/releases/tag/1.5.18 测试了这个版本已经好了 👍
