### ISSUE TITLE
1.5.18 Vless+XTLS+TCP无法保存host，更新订阅也不会导入host导致连接失败

### ISSUE THREAD

**Issue by MFYDev** [2dust/v2rayNG#969]
### 预期行为
Vless+XTLS+TCP无法保存host，更新订阅也不会导入host导致连接失败 ，1.5.17运行正常

### 实际行为
Xray+XTLS+tcp的订阅，或者单独输入节点，均无法保存host，host自动变空，更新订阅也不会导入host，导致连接崩溃

### 复现方法
1. 使用XTLS+TCP的节点，输入host伪装域名
2. 点击右上角保存
3. 再次编辑节点，发现host自动为空

### 环境信息
MIUI 最新内测版 Android 11

**Comment by MFYDev** [comment]
已降级切换回1.5.17版本，1.5.18极其不稳定，建议排查

**Comment by MFYDev** [comment]
重新下载测试确认复现率百分之百，但是很奇怪的是只限于XTLS+TCP协议的host不会保存，其他vless可以，很奇怪，不知道为什么要remove bug label

**Comment by 2dust** [comment]
因为1.5.18版本的配置存储的时候，会检查您的配置是否符合core的规则，不符合的属性将被抛弃。
新版本host的有些用法将用sni取代，所以您可以先设置sni，后面将会增加一些兼容功能

**Comment by 2dust** [comment]
刚刚修复了下，重新下载安装一次
https://github.com/2dust/v2rayNG/releases/tag/1.5.18

**Comment by MFYDev** [comment]
太感谢2dust了，这次可以了，我自己再去搜搜看为什么变成这么用了。。。
