### ISSUE TITLE
手机端kcp无法使用

### ISSUE THREAD

**Issue by lsgbx** [2dust/v2rayNG#97]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
手机端可以使用kcp

### 实际行为
自己架设的服务器，有高端口ipv4，6的kcp，80的cdn ws，80的不代理只‪‍‍‏‍‪‪‮‭‌⁠‌‪‫‬‭‌‭‎‎‌‏‫‍域名解析ws
最近手机kcp刚连上可以ping通，之后ping不通，测速不通
ws都可以通正常使用
老手机旧版本症状一样，换wifi，4g症状一样
在电脑端v2rayn就完全正常

### 复现方法
1.手机任何情况下，kcp节点
2.
3.

### 日志信息
<details>
 dir6. No address associated with hostname] > v2ray.com/core/common/retry: all retry attempts failed
09-07 09:19:25.270 I/GoLog   (31650): Not Using Prepared: udp,dir6.:15285
09-07 09:19:25.270 I/GoLog   (31650): udp:127.0.0.1:47546 accepted udp:8.8.8.8:53 
09-07 09:19:29.464 I/GoLog   (31650): udp:127.0.0.1:47892 accepted udp:8.8.8.8:53 
09-07 09:19:29.464 I/GoLog   (31650): Not Using Prepared: udp,dir6:12274
09-07 09:19:30.275 I/GoLog   (31650): Not Using Prepared: udp,dir6.:13571
09-07 09:19:30.275 I/GoLog   (31650): udp:127.0.0.1:47546 accepted udp:8.8.8.8:53 

</details>
dir.xxxx是我的域名删掉了一部分，就算换直连ip也显示这个not using prepared udp

### 环境信息
安卓9，7.1，cernet2，联通4g

**Comment by 2dust** [comment]
kcp自己折腾吧,不行就换app
