### ISSUE TITLE
1.5.18 导入自定义配置文件 = 号 变成了 \u003d

### ISSUE THREAD

**Issue by ghost** [2dust/v2rayNG#971]
从v2rayN导出自定义配置文件，在手机里导入到v2rayNG 1.5.18中。发现=号变成了 \u003d。

用到=号是WS 的 path后我加了 ?=2048，=号就变成了 \u003d。

1.5.17版本无此问题。

**Comment by ghost** [comment]
手动添加好VMESS配置。点导出完整配置到剪切板。

在手机的记事本粘贴，发现同样 = 号变成了  \u003d

**Comment by yuhan6665** [comment]
感谢反馈 将尽快修复
