### ISSUE TITLE
v2rayNg在红米note7错误，提示启动服务失败

### ISSUE THREAD

**Issue by lzffeng** [2dust/v2rayNG#972]
![Screenshot_2021-03-28-13-25-30-189_com v2ray ang](https://user-images.githubusercontent.com/81423538/112743366-4c039b00-8f5c-11eb-8a53-18b6c47af113.jpg)

**Comment by Didudia** [comment]
建议重启几次，跟你一样的手机型号

**Comment by yuhan6665** [comment]
1. 如果是 1.5.18 尝试一下老版本
2. 请附上 log 和 配置 （注意替换敏感信息）
