### ISSUE TITLE
最新版本无法在MIUI 12.5系统控制中心启动

### ISSUE THREAD

**Issue by TrayBer** [2dust/v2rayNG#979]
如图所示，点击控制中心的 v2rayNG 图标，无法正常启动服务。

安卓系统：MIUI 12.5 开发版（Android 11）
v2rayNG 版本：1.6.0（此处下载，非商店版本）

<img width="1081" alt="sohfao0w34r" src="https://user-images.githubusercontent.com/8769077/113231745-7a6fd600-92ce-11eb-9eb4-fd8e5e6ce772.png">

**Comment by yuhan6665** [comment]
在 app 中启动成功之后再回来试一下

**Comment by burycreek** [comment]
![Screenshot_2021-04-05-01-37-50-440_com miui powerkeeper](https://user-images.githubusercontent.com/51310701/113516961-c7de9280-95af-11eb-9f37-5a4db21f2e43.png)
应用程序，将NG改为无限制即可。 之前也是苦恼我许久
