### ISSUE TITLE
allowInsecure无法关闭，NG也存在相关问题

### ISSUE THREAD

**Issue by violte** [2dust/v2rayNG#98]
v2rayNG中`allowInsecure`默认值为`true`，这意味着V2Ray不会检查远端主机所提供的 TLS 证书的有效性。
在日渐复杂的网络环境中，用户极易面临伪造证书的https劫持的高危风险且无法及时发现。

建议新版设置默认`allowInsecure`值为`false`，或者增加allowInsecure开关。

**Comment by 2dust** [comment]
allowInsecure = false时,测试发现都不能正常连接
