### ISSUE TITLE
V2RayNG自行编译UI完全是1.0.2版本，最新版本完全闭源了吗？

### ISSUE THREAD

**Issue by MFYDev** [2dust/v2rayNG#982]
今天由于XRay突然更新了1.4.2，所以想快速用上最新版就自己编译了，

但是编译完发现UI完全是1.0.2版本，整体代码非常老旧，和release的版本完全不一致，

按道理说使用GPL 3.0授权，此协议并不允许开发者在发布软件时并不提供源码，并且即使是基于此项目源码的衍生项目，一样要提供源码，

目前这个项目正在违反自己选择的授权协议。

强烈建议源码彻底开源，这样不论是学习亦或者是二次开发都会有更多的机会吧？

**Comment by wc7086** [comment]
1.0.2之后的版本已转向闭源，发布的软件包中并未提到GPL协议。版权所有者有权在后续版本中更改协议或将软件转为闭源私有软件。

#172
