### ISSUE TITLE
VpnService error after using new compiled arr library.

### ISSUE THREAD

**Issue by ojaynico** [2dust/v2rayNG#985]
I get the error below in my console when using a new compiled android libv2ray.aar. The error shows when i try to connect to a configuration file. However the default aar library works.

`D/VpnService: prepare function with android vpn context is called for non knox vpn profile`

**Comment by rurirei** [comment]
need more.

`knox` may something due to Samsung.

**Comment by AnmLobby** [comment]
I encountered the same problem, is there a solution for this problem?
