### ISSUE TITLE
似乎自定义规则不能拦截网址或者ip

### ISSUE THREAD

**Issue by cDQK** [2dust/v2rayNG#986]
似乎自定义规则不能拦截我指定的网址和ip，我是在自定义规则中的“阻止...”界面这样输入的：
jd.com,211.144.27.126,等等jd的几个ip
然后打勾退出，完全关闭这个程序，再进入打开vless或者trojan连接成功，再打开已选中代理的浏览器打开这个网站，可是完全不能拦截这个网站

### 预期行为
我想这个功能这样用是没问题的，并且自定义的规则应该是等级最高的，应该优先于预定义规则和geo。

### 复现方法
1.看到浏览器输入栏出现union.click.jd.com，也加进入了，没用

### 日志信息
没有电脑

### 环境信息
版本1.6.2

### 额外信息（可选）
issue指定输入信息有点多

**Comment by dadaoyixing** [comment]
好像要先勾选本地dns，好像如果是域名的话前面要加上domain:
domain:jd.com,211.144.27.126,
