### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by cnboy95** [2dust/v2rayNG#987]
希望后期能加入开机自启动和v2rayNG安卓版作为服务端使用。

**Comment by Fhokud** [comment]
都已经实现了

**Comment by moyada** [comment]
挺多问题的，先开v2再联网就不可用，然后自动关闭链接，导致国内ip暴露

**Comment by Fhokud** [comment]
参考#810

**Comment by imcaoxuan** [comment]
安卓很久以前就不支持静态注册广播了，所以开机自启估计得跟手机厂商合作才可能实现。
