### ISSUE TITLE
1.6.3版本在连接后很快自动断开

### ISSUE THREAD

**Issue by wwjj999** [2dust/v2rayNG#993]
在提出问题前请先自行排除服务器端问题，同时也请通过搜索确认是否有人提出过相同问题。

### 预期行为
描述你认为应该发生什么
1.6.3版本在连接后很快自动断开
### 实际行为
描述实际发生了什么
1.6.3版本在连接后很快自动断开
### 复现方法
1.speedtest下立即断线
2.退到后台（已锁定后台）一会儿就断开
3.

### 日志信息
<details>

通过`adb logcat -s com.v2ray.ang GoLog V2rayConfigUtilGoLog Main`获取日志。请自行删减日志中可能出现的敏感信息。

如果问题可重现，建议先执行`adb logcat -c`清空系统日志再执行上述命令，再操作重现问题。
```
在这里粘贴日志
```
</details>

### 环境信息
miui12.5版本

**Comment by wwjj999** [comment]
--------- beginning of system
--------- beginning of main
04-07 02:18:21.657 E/com.v2ray.ang(14851): Not starting debugger since process cannot load the jdwp agent.
04-07 02:18:21.723 I/com.v2ray.ang(14851): The ClassLoaderContext is a special shared library.
04-07 02:18:21.729 I/com.v2ray.ang(14851): The ClassLoaderContext is a special shared library.
04-07 02:18:21.735 E/com.v2ray.ang(14851): Dex checksum does not match for dex: /system/app/MiuiContentCatcher/MiuiContentCatcher.apk.Expected: 2447750414, actual: 299541489
04-07 02:18:21.743 W/com.v2ray.ang(14851): Method Landroid/support/v4/media/c;.close is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:18:21.743 W/com.v2ray.ang(14851): Method Landroid/support/v4/media/c;.e is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:18:21.743 W/com.v2ray.ang(14851): Method Lb/a/b/b/b;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:18:21.744 W/com.v2ray.ang(14851): Method Lcom/google/common/collect/Maps$h;.g is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:25:07.252 E/com.v2ray.ang(16643): Not starting debugger since process cannot load the jdwp agent.
04-07 02:25:07.315 I/com.v2ray.ang(16643): The ClassLoaderContext is a special shared library.
04-07 02:25:07.323 I/com.v2ray.ang(16643): The ClassLoaderContext is a special shared library.
04-07 02:25:07.325 E/com.v2ray.ang(16643): Dex checksum does not match for dex: /system/app/MiuiContentCatcher/MiuiContentCatcher.apk.Expected: 2447750414, actual: 299541489
04-07 02:25:07.336 W/com.v2ray.ang(16643): Method Landroid/support/v4/media/c;.close is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:25:07.336 W/com.v2ray.ang(16643): Method Landroid/support/v4/media/c;.e is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:25:07.336 W/com.v2ray.ang(16643): Method Lb/a/b/b/b;.b is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk
04-07 02:25:07.336 W/com.v2ray.ang(16643): Method Lcom/google/common/collect/Maps$h;.g is abstract, but the declaring class is neither abstract nor an interface in dex file /system/app/MiuiContentCatcher/MiuiContentCatcher.apk

**Comment by yuhan6665** [comment]
1. 请先清空 log ，等待复现，然后再上传一份
2. 如果你留在 v2rayNG 里面会自动断开吗？

**Comment by wangjianpro** [comment]
不，我已换回1.6.2版，断线几乎不再发生
