### ISSUE TITLE
Version 1.6.3 of v2rayng, v2ray tcp and obfuscation have been unable to connect, showing read/write on closed pipe

### ISSUE THREAD

**Issue by tyronesaint** [2dust/v2rayNG#996]
Version 1.6.3 of v2rayng, v2ray tcp and obfuscation have been unable to connect, showing read/write on closed pipe

**Comment by yuhan6665** [comment]
1. Double check your config
2. Try older version

**Comment by tyronesaint** [comment]
I have been using the old version now, there is no problem with the old version, I just said that the new version 1.6.3 has been tried and cannot be used, so report the bug. 1.6.3 Obfuscation cannot be used, but it is available without obfuscation. I have tried it all.

**Comment by yuhan6665** [comment]
what is your config?

**Comment by wfniub** [comment]
> I have been using the old version now, there is no problem with the old version, I just said that the new version 1.6.3 has been tried and cannot be used, so report the bug. 1.6.3 Obfuscation cannot be used, but it is available without obfuscation. I have tried it all.

是的我也遇到同样的问题，请问有解决吗，或者你现在用的哪个旧版本！
