### ISSUE TITLE
允许整理过的自定义配置中存在注释

### ISSUE THREAD

**Issue by Fhokud** [2dust/v2rayNG#997]
感谢各位大佬的无私付出，这是一个小小的提议，望采纳

 比如

>  // xxxxxxxx

可以在任意位置

**Comment by rurirei** [comment]
you requires **jsonc** support for TextView. this may be a good idea? @yuhan6665

**Comment by yuhan6665** [comment]
感谢反馈，这个不太好处理，跟 2dust 讨论之后决定暂时回滚“自定义配置整理”这个功能。（内部将保存两份设置）
